/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.AlgebraicTopology.FundamentalGroup.CoverGeneration
public import EpsilonEridani.AlgebraicTopology.ThricePuncturedSphere.PuncturedHalfPlanes

/-!
# The peripheral loops generate the fundamental group of the thrice-punctured sphere

The thrice-punctured sphere `ℂ ∖ {0, 1}` is the union of the open sets `A = {re z < 1}` and
`B = {0 < re z}`. Both are path connected, and so is their intersection, the open strip
`0 < re z < 1`, which contains the basepoint `1/2`. By the generation half of the Seifert--van
Kampen theorem (`EpsilonEridani.FundamentalGroup.range_map_subtypeVal_sup_eq_top`), `π₁(ℂ ∖ {0, 1}, 1/2)`
is generated by the images of `π₁(A, 1/2)` and `π₁(B, 1/2)`. These are infinite cyclic, generated
by the classes of the peripheral loops `γ0` and `γ1`, whose images are `periph0` and `periph1`.
Hence `periph0` and `periph1` generate `π₁(ℂ ∖ {0, 1}, 1/2)`.

In particular a homomorphism out of `π₁(ℂ ∖ {0, 1}, 1/2)` is determined by its values on `periph0`
and `periph1`. For the monodromy representation of a cover this says that the monodromy group, the
image of `π₁`, is generated by the monodromy permutations around `0` and around `1`, which is how
a cover's permutation triple sees the transitivity of its monodromy.

## Main declarations

* `EpsilonEridani.ThricePuncturedSphere.closure_periph0_periph1`: `periph0` and `periph1` generate
  `π₁(ℂ ∖ {0, 1}, 1/2)`.
* `EpsilonEridani.ThricePuncturedSphere.fundamentalGroup_hom_ext`: a homomorphism out of
  `π₁(ℂ ∖ {0, 1}, 1/2)` is determined by its values on `periph0` and `periph1`.

## References

* A. Hatcher, *Algebraic Topology*, Cambridge University Press, 2002, Theorem 1.20.
-/

public section

open Set

namespace EpsilonEridani

namespace ThricePuncturedSphere

/-- The image of `π₁(A, 1/2)` in `π₁(ℂ ∖ {0, 1}, 1/2)` is generated by `periph0`. -/
private theorem range_map_leftOpen :
    ((FundamentalGroup.map (ContinuousMap.subtypeVal leftOpen)
      ⟨basePt, basePt_mem_leftOpen⟩).range :
        Subgroup (FundamentalGroup ThricePuncturedSphere basePt)) =
      Subgroup.zpowers periph0 := by
  rw [MonoidHom.range_eq_map, ← zpowers_periph0Left, MonoidHom.map_zpowers]
  exact congrArg Subgroup.zpowers map_val_periph0Left

/-- The image of `π₁(B, 1/2)` in `π₁(ℂ ∖ {0, 1}, 1/2)` is generated by `periph1`. -/
private theorem range_map_rightOpen :
    ((FundamentalGroup.map (ContinuousMap.subtypeVal rightOpen)
      ⟨basePt, basePt_mem_rightOpen⟩).range :
        Subgroup (FundamentalGroup ThricePuncturedSphere basePt)) =
      Subgroup.zpowers periph1 := by
  rw [MonoidHom.range_eq_map, ← zpowers_periph1Right, MonoidHom.map_zpowers]
  exact congrArg Subgroup.zpowers map_val_periph1Right

/-- **The peripheral elements `periph0` and `periph1` generate `π₁(ℂ ∖ {0, 1}, 1/2)`.** -/
@[simp]
theorem closure_periph0_periph1 :
    Subgroup.closure {periph0, periph1} = ⊤ := by
  have h := FundamentalGroup.range_map_subtypeVal_sup_eq_top
    (by rw [isOpen_leftOpen.interior_eq, isOpen_rightOpen.interior_eq, leftOpen_union_rightOpen])
    isPathConnected_leftOpen isPathConnected_rightOpen isPathConnected_leftOpen_inter_rightOpen
    basePt_mem_leftOpen basePt_mem_rightOpen
  rw [range_map_leftOpen, range_map_rightOpen] at h
  rw [eq_top_iff, ← h]
  exact sup_le (Subgroup.zpowers_le.2 (Subgroup.subset_closure (mem_insert _ _)))
    (Subgroup.zpowers_le.2 (Subgroup.subset_closure (mem_insert_of_mem _ rfl)))

/-- A homomorphism out of `π₁(ℂ ∖ {0, 1}, 1/2)` is determined by its values on the peripheral
elements `periph0` and `periph1`. -/
@[ext]
theorem fundamentalGroup_hom_ext {G : Type*} [Monoid G]
    {f g : FundamentalGroup ThricePuncturedSphere basePt →* G}
    (h0 : f periph0 = g periph0) (h1 : f periph1 = g periph1) : f = g :=
  MonoidHom.eq_of_eqOn_dense closure_periph0_periph1 (by
    rintro _ (rfl | rfl)
    exacts [h0, h1])

end ThricePuncturedSphere

end EpsilonEridani
