/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.NumberTheory.NumberField.Cyclotomic.Basic
public import EpsilonEridani.NumberTheory.NumberField.Index.Basic

/-!
# The index of a primitive root of unity is `1`

Let `K` be an `n`-th cyclotomic extension of `ℚ` and `ζ` a primitive `n`-th root of unity in `K`.
Then `ζ` is an algebraic integer generating `K` over `ℚ`, hence an integral primitive element of
`K`, and `𝓞 K = ℤ[ζ]` (Mathlib's `IsCyclotomicExtension.Rat.adjoin_singleton_eq_top`), so its index
`[𝓞 K : ℤ[ζ]]` is `1`. The case `n = 4` is the fourth cyclotomic field `ℚ(i)`, where `ℤ[i]` has
index `1`.

## Main definitions

* `IsPrimitiveRoot.integralPrimitiveElement`: a primitive `n`-th root of unity in an `n`-th
  cyclotomic extension of `ℚ`, as an integral primitive element.

## Main results

* `IsPrimitiveRoot.integralPrimitiveElement_index`: the index of a primitive root of unity is
  `1`.

## References

* J. Neukirch, *Algebraic Number Theory*, Chapter I, Proposition (10.2).
-/

public section

open scoped NumberField

namespace IsPrimitiveRoot

variable {K : Type*} [Field K] [NumberField K] {n : ℕ} [NeZero n] {ζ : K}

/-- A primitive `n`-th root of unity in an `n`-th cyclotomic extension of `ℚ`, as an integral
primitive element. -/
noncomputable def integralPrimitiveElement [IsCyclotomicExtension {n} ℚ K]
    (hζ : IsPrimitiveRoot ζ n) : EpsilonEridani.NumberField.IntegralPrimitiveElement K :=
  ⟨hζ.toInteger, IsCyclotomicExtension.adjoin_primitive_root_eq_top hζ⟩

/-- The underlying algebraic integer of a primitive root of unity, as an integral primitive
element, is the root of unity itself. -/
@[simp]
theorem coe_integralPrimitiveElement [IsCyclotomicExtension {n} ℚ K]
    (hζ : IsPrimitiveRoot ζ n) : (hζ.integralPrimitiveElement : 𝓞 K) = hζ.toInteger :=
  (rfl)

/-- **The index of a primitive root of unity is `1`.** In an `n`-th cyclotomic extension `K` of
`ℚ`, the order `ℤ[ζ]` generated by a primitive `n`-th root of unity `ζ` is all of `𝓞 K`. -/
@[simp]
theorem integralPrimitiveElement_index [IsCyclotomicExtension {n} ℚ K]
    (hζ : IsPrimitiveRoot ζ n) : hζ.integralPrimitiveElement.index = 1 := by
  rw [EpsilonEridani.NumberField.IntegralPrimitiveElement.index_eq_one_iff,
    EpsilonEridani.NumberField.IntegralPrimitiveElement.adjoin_def, coe_integralPrimitiveElement]
  exact IsCyclotomicExtension.Rat.adjoin_singleton_eq_top hζ

end IsPrimitiveRoot
