/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.Algebra.Group.Subgroup.TwoTorsionClosure
public import EpsilonEridani.NumberTheory.DirichletCharacter.Conductor
public import EpsilonEridani.NumberTheory.DirichletCharacter.Quadratic
public import EpsilonEridani.NumberTheory.DirichletCharacter.Subgroup
public import EpsilonEridani.NumberTheory.Multiquadratic.Legendre.PrimeDiscriminant.Dirichlet.Character
public import Mathlib.Data.Fintype.Sets
public import Mathlib.NumberTheory.MulChar.Duality
import EpsilonEridani.NumberTheory.Multiquadratic.Legendre.PrimeDiscriminant.Dirichlet.Basic

/-!
# The character group of a prime-discriminant family

Let `s` be a finite family of distinct prime discriminants which does not contain all three even
prime discriminants, and put `N = |∏ P ∈ s, P|`. Each quadratic character belonging to a factor
`P` lifts to level `N`
(`primeDiscriminantCharAtLevel`), and the products of these lifted characters are indexed by the
subsets `t` of `s` (`genusCharAtLevel`). The level stays `N` as `t` shrinks — only the subset
varies — which is what puts all of these characters in a single group: multiplication corresponds
to symmetric difference of subsets. When `t` has at most one even member, the conductor of its
character is `|∏ P ∈ t, P|`.

Consequently the subgroup generated by the factor characters has exactly `2 ^ #s` elements. This
is the character-group counterpart of the degree-`2 ^ #s` prime-discriminant compositum. It is
the input for combining the individual quadratic character fixed fields inside one cyclotomic
field.

The whole-family character `EpsilonEridani.Multiquadratic.genusChar s hs` is the case `t = Finset.univ`
of `genusCharAtLevel`: that is how
`EpsilonEridani/NumberTheory/Multiquadratic/Quadratic/GenusCharacter/Dirichlet.lean` defines it, so the
`genusChar` API (its values on integers, its primitivity) is the whole-family case of the API
here, and `conductor_genusCharAtLevel` is the subset form of `isPrimitive_genusChar`.

The prime-discriminant description is classical; see K. Ireland and M. Rosen, *A Classical
Introduction to Modern Number Theory*, Chapter 6, and D. A. Cox, *Primes of the Form x² + ny²*,
§§3.B and 6.A.

## Main definitions and results

* `primeDiscriminantCharAtLevel`: the character of one factor, lifted to the common level.
* `genusCharAtLevel`: the product character indexed by a subset of the factors.
* `genusCharAtLevel_apply_int`: its value at an integer coprime to the level.
* `genusCharAtLevel_symmDiff`: multiplication corresponds to symmetric difference.
* `conductor_genusCharAtLevel`: the conductor is the product of the factor conductors.
* `genusCharAtLevel_injective`: distinct subsets give distinct characters.
* `genusCharGroup`: the subgroup consisting of all subset characters, identified by
  `genusCharGroup_eq_closure` with the subgroup generated by the factor characters.
* `genusCharGroupEquiv`: the subsets of `s` are in bijection with that subgroup.
* `natCard_genusCharGroup`: that subgroup has `2 ^ #s` elements.
* `dirichletConductor_genusCharGroup`: the conductor of that subgroup is the least common
  multiple of the `|P|`.
-/

public section

open scoped symmDiff

namespace EpsilonEridani.Multiquadratic

open DirichletCharacter

variable (s : Finset ℤ) (hs : ∀ P ∈ s, IsPrimeDiscriminant P)

/-- The character of a prime-discriminant factor, lifted to the common level
`|∏ P ∈ s, P|`. -/
noncomputable def primeDiscriminantCharAtLevel (P : s) :
    DirichletCharacter ℤ (∏ Q ∈ s, Q).natAbs :=
  changeLevel (Int.natAbs_dvd_natAbs.mpr (Finset.dvd_prod_of_mem id P.property))
    (primeDiscriminantChar P (hs P P.property))

/-- The defining equation of `primeDiscriminantCharAtLevel`: the factor character lifted along
`|P| ∣ |∏ Q ∈ s, Q|`. -/
theorem primeDiscriminantCharAtLevel_def (P : s) :
    primeDiscriminantCharAtLevel s hs P =
      changeLevel (Int.natAbs_dvd_natAbs.mpr (Finset.dvd_prod_of_mem id P.property))
        (primeDiscriminantChar P (hs P P.property)) := (rfl)

/-- At an integer coprime to the common level, a lifted prime-discriminant character agrees with
the character attached to its factor. -/
theorem primeDiscriminantCharAtLevel_apply_int (P : s) (n : ℤ)
    (hn : IsCoprime n (∏ Q ∈ s, Q).natAbs) :
    primeDiscriminantCharAtLevel s hs P n = primeDiscriminantChar P (hs P P.property) n := by
  rw [primeDiscriminantCharAtLevel_def, changeLevel_eq_cast_of_dvd' _ _ hn]

/-- The conductor of a lifted prime-discriminant character is the absolute value of its factor. -/
@[simp] theorem conductor_primeDiscriminantCharAtLevel (P : s) :
    (primeDiscriminantCharAtLevel s hs P).conductor = P.val.natAbs := by
  let _ := neZero_natAbs_prod_of_forall_isPrimeDiscriminant hs
  rw [primeDiscriminantCharAtLevel_def, conductor_changeLevel]
  exact isPrimitive_primeDiscriminantChar P (hs P P.property)

/-- A lifted prime-discriminant character is quadratic. -/
theorem isQuadratic_primeDiscriminantCharAtLevel (P : s) :
    (primeDiscriminantCharAtLevel s hs P).IsQuadratic :=
  isQuadratic_changeLevel (isQuadratic_primeDiscriminantChar P (hs P P.property)) _

/-- A lifted prime-discriminant character squares to the trivial character. -/
@[simp] theorem primeDiscriminantCharAtLevel_sq (P : s) :
    primeDiscriminantCharAtLevel s hs P ^ 2 = 1 :=
  (isQuadratic_primeDiscriminantCharAtLevel s hs P).sq_eq_one

/-- The common-level genus character indexed by a subset of the prime-discriminant factors. -/
noncomputable def genusCharAtLevel (t : Finset s) :
    DirichletCharacter ℤ (∏ P ∈ s, P).natAbs :=
  ∏ P ∈ t, primeDiscriminantCharAtLevel s hs P

/-- The defining equation of `genusCharAtLevel`: the product of the lifted characters of the
factors in the subset. -/
theorem genusCharAtLevel_def (t : Finset s) :
    genusCharAtLevel s hs t = ∏ P ∈ t, primeDiscriminantCharAtLevel s hs P := (rfl)

@[simp] theorem genusCharAtLevel_empty : genusCharAtLevel s hs ∅ = 1 := by
  simp [genusCharAtLevel_def]

@[simp] theorem genusCharAtLevel_singleton (P : s) :
    genusCharAtLevel s hs {P} = primeDiscriminantCharAtLevel s hs P := by
  simp [genusCharAtLevel_def]

/-- Inserting a new factor multiplies its character into the subset character. -/
@[simp] theorem genusCharAtLevel_insert {P : s} {t : Finset s} (hP : P ∉ t) :
    genusCharAtLevel s hs (insert P t) =
      primeDiscriminantCharAtLevel s hs P * genusCharAtLevel s hs t := by
  simp [genusCharAtLevel_def, hP]

/-- At an integer coprime to the common level, a subset character is the product of the
prime-discriminant character functions of its factors. -/
theorem genusCharAtLevel_apply_int (t : Finset s) (n : ℤ)
    (hn : IsCoprime n (∏ Q ∈ s, Q).natAbs) :
    genusCharAtLevel s hs t n = ∏ P ∈ t, primeDiscriminantCharFun P n := by
  have hu : IsUnit ((n : ℤ) : ZMod (∏ Q ∈ s, Q).natAbs) :=
    (ZMod.coe_int_isUnit_iff_isCoprime _ _).mpr hn.symm
  induction t using Finset.induction_on with
  | empty => rw [genusCharAtLevel_empty, Finset.prod_empty, MulChar.one_apply hu]
  | @insert P t hP ih =>
    rw [genusCharAtLevel_insert s hs hP, MulChar.mul_apply, ih, Finset.prod_insert hP,
      primeDiscriminantCharAtLevel_apply_int s hs P n hn, primeDiscriminantChar_apply_int]

/-- Multiplication of subset characters corresponds to symmetric difference of the subsets. -/
@[simp] theorem genusCharAtLevel_symmDiff (t u : Finset s) :
    genusCharAtLevel s hs (t ∆ u) = genusCharAtLevel s hs t * genusCharAtLevel s hs u := by
  rw [genusCharAtLevel_def, genusCharAtLevel_def, genusCharAtLevel_def, Finset.symmDiff_def]
  exact EpsilonEridani.prod_sdiff_union_sdiff _ fun P _ ↦ primeDiscriminantCharAtLevel_sq s hs P

/-- Every subset character is quadratic. -/
theorem isQuadratic_genusCharAtLevel (t : Finset s) : (genusCharAtLevel s hs t).IsQuadratic :=
  MulChar.isQuadratic_prod fun P _ ↦ isQuadratic_primeDiscriminantCharAtLevel s hs P

/-- If the subset contains at most one even prime discriminant, its character's conductor is the
product of the absolute values of its factors. -/
theorem conductor_genusCharAtLevel
    (t : Finset s)
    (heven : ∀ P ∈ t, ∀ Q ∈ t,
      IsEvenPrimeDiscriminant P → IsEvenPrimeDiscriminant Q → P = Q) :
    (genusCharAtLevel s hs t).conductor = ∏ P ∈ t, P.val.natAbs := by
  let _ := neZero_natAbs_prod_of_forall_isPrimeDiscriminant hs
  rw [genusCharAtLevel_def, EpsilonEridani.conductor_prod_eq_prod_of_pairwise_coprime]
  · simp
  · intro P hPt Q hQt hPQ
    simp only [conductor_primeDiscriminantCharAtLevel]
    exact Int.isCoprime_iff_nat_coprime.mp
      (isCoprime_primeDiscriminant_of_ne_of_not_both_even
        (hs P P.property) (hs Q Q.property) (fun h ↦ hPQ (Subtype.ext h))
        (fun h ↦ hPQ (heven P hPt Q hQt h.1 h.2)))
  · exact Or.inr (NeZero.ne _)

/-- If `s` does not contain all three even prime discriminants, distinct subsets of `s` give
distinct characters of level `|∏ P ∈ s, P|`. -/
theorem genusCharAtLevel_injective
    (hnoall : ¬ (-4 ∈ s ∧ 8 ∈ s ∧ -8 ∈ s)) :
    Function.Injective (genusCharAtLevel s hs) := by
  let _ := neZero_natAbs_prod_of_forall_isPrimeDiscriminant hs
  intro t u htu
  apply Finset.symmDiff_eq_empty.mp
  by_contra hne
  have hchar : genusCharAtLevel s hs (t ∆ u) = 1 := by
    rw [genusCharAtLevel_symmDiff, htu, ← pow_two,
      (isQuadratic_genusCharAtLevel s hs u).sq_eq_one]
  obtain ⟨P, hP⟩ := Finset.nonempty_iff_ne_empty.mpr hne
  let ε : ℤ → ℤˣ := fun Q => if Q = P.val then -1 else 1
  obtain ⟨a, ha⟩ := exists_forall_primeDiscriminantCharFun_eq_of_not_all_three_even hs hnoall ε
  have hcop : ∀ Q ∈ s, IsCoprime (a : ℤ) Q := by
    intro Q hQ
    by_contra hn
    have hz := (primeDiscriminantCharFun_eq_zero_iff (hs Q hQ)).mpr hn
    rw [ha Q hQ] at hz
    exact (ε Q).ne_zero hz
  have hcopProd : IsCoprime (a : ℤ) (∏ Q ∈ s, Q) :=
    IsCoprime.prod_right fun Q hQ => hcop Q hQ
  have haLevel : IsCoprime (a : ℤ) ((∏ Q ∈ s, Q).natAbs : ℤ) := by
    simpa only [Int.isCoprime_iff_nat_coprime, Int.natAbs_natCast] using hcopProd
  have hu : IsUnit (((a : ℕ) : ℤ) : ZMod (∏ Q ∈ s, Q).natAbs) :=
    (ZMod.coe_int_isUnit_iff_isCoprime _ _).mpr haLevel.symm
  have hvalue := genusCharAtLevel_apply_int s hs (t ∆ u) (a : ℤ) haLevel
  rw [hchar, MulChar.one_apply hu] at hvalue
  have hprod : ∏ Q ∈ t ∆ u, primeDiscriminantCharFun Q a = -1 := by
    calc
      _ = ∏ Q ∈ t ∆ u, (ε Q : ℤ) :=
        Finset.prod_congr rfl fun Q _ => ha Q Q.property
      _ = -1 := by
        rw [Finset.prod_eq_mul_prod_sdiff_singleton_of_mem hP]
        have hεP : (ε P : ℤ) = -1 := by simp [ε]
        rw [hεP, Finset.prod_eq_one fun Q hQ => by
          simp only [ε]
          rw [ite_eq_right
            ((Finset.mem_sdiff.mp hQ).2 ∘ Finset.mem_singleton.mpr ∘ Subtype.ext)]
          rfl]
        norm_num
  rw [hprod] at hvalue
  omega

/-- The subgroup of common-level Dirichlet characters obtained by taking products over subsets of
the prime-discriminant factors. -/
noncomputable def genusCharGroup :
    Subgroup (DirichletCharacter ℤ (∏ P ∈ s, P).natAbs) where
  carrier := Set.range (genusCharAtLevel s hs)
  one_mem' := ⟨∅, genusCharAtLevel_empty s hs⟩
  mul_mem' := by
    rintro _ _ ⟨t, rfl⟩ ⟨u, rfl⟩
    exact ⟨t ∆ u, genusCharAtLevel_symmDiff s hs t u⟩
  inv_mem' := by
    rintro _ ⟨t, rfl⟩
    refine ⟨t, ?_⟩
    exact (isQuadratic_genusCharAtLevel s hs t).inv.symm

/-- Membership in the prime-discriminant character group means being the character of a subset. -/
@[simp] theorem mem_genusCharGroup_iff {chi : DirichletCharacter ℤ (∏ P ∈ s, P).natAbs} :
    chi ∈ genusCharGroup s hs ↔ ∃ t : Finset s, genusCharAtLevel s hs t = chi :=
  Iff.rfl

/-- The subset characters are exactly the subgroup generated by the individual
prime-discriminant characters. -/
theorem genusCharGroup_eq_closure :
    genusCharGroup s hs =
      Subgroup.closure (Set.range (primeDiscriminantCharAtLevel s hs)) := by
  apply SetLike.coe_injective
  rw [← Set.image_univ, ← Finset.coe_univ,
    EpsilonEridani.closure_image_eq_image_powerset (Finset.univ : Finset s)
      (primeDiscriminantCharAtLevel s hs) (fun P _ ↦ primeDiscriminantCharAtLevel_sq s hs P)]
  ext chi
  simp only [SetLike.mem_coe, mem_genusCharGroup_iff, Set.mem_image,
    Finset.mem_powerset, Finset.subset_univ, true_and, genusCharAtLevel_def]

/-- If the family does not contain all three even prime discriminants, its subsets are in
bijection with its character group. -/
noncomputable def genusCharGroupEquiv
    (hnoall : ¬ (-4 ∈ s ∧ 8 ∈ s ∧ -8 ∈ s)) :
    Finset s ≃ genusCharGroup s hs :=
  Equiv.ofInjective (genusCharAtLevel s hs) (genusCharAtLevel_injective s hs hnoall)

/-- The subset equivalence sends a subset to its corresponding common-level genus character. -/
@[simp] theorem coe_genusCharGroupEquiv_apply
    (hnoall : ¬ (-4 ∈ s ∧ 8 ∈ s ∧ -8 ∈ s)) (t : Finset s) :
    ↑(genusCharGroupEquiv s hs hnoall t) = genusCharAtLevel s hs t := by
  rfl

/-- If `s` does not contain all three even prime discriminants, its character group has one
element for each subset. -/
theorem natCard_genusCharGroup
    (hnoall : ¬ (-4 ∈ s ∧ 8 ∈ s ∧ -8 ∈ s)) :
    Nat.card (genusCharGroup s hs) = 2 ^ s.card := by
  rw [← Nat.card_congr (genusCharGroupEquiv s hs hnoall), Nat.card_eq_fintype_card,
    Fintype.card_finset, Fintype.card_coe]

/-- **The conductor of the prime-discriminant character group** is the least common multiple of
the absolute values of the prime discriminants. -/
@[simp]
theorem dirichletConductor_genusCharGroup :
    (genusCharGroup s hs).dirichletConductor = s.lcm Int.natAbs := by
  let _ := neZero_natAbs_prod_of_forall_isPrimeDiscriminant hs
  apply Nat.dvd_antisymm
  · rw [Subgroup.dirichletConductor_dvd_iff]
    intro χ hχ
    obtain ⟨t, rfl⟩ := (mem_genusCharGroup_iff s hs).mp hχ
    clear hχ
    rw [genusCharAtLevel_def]
    induction t using Finset.induction_on with
    | empty => rw [Finset.prod_empty, conductor_one]; exact one_dvd _
    | @insert P t hP ih =>
      rw [Finset.prod_insert hP]
      refine (conductor_mul_dvd_lcm_conductor _ _).trans (Nat.lcm_dvd ?_ ih)
      rw [conductor_primeDiscriminantCharAtLevel]
      exact Finset.dvd_lcm P.property
  · refine Finset.lcm_dvd fun P hP ↦ ?_
    rw [← conductor_primeDiscriminantCharAtLevel s hs ⟨P, hP⟩]
    exact Subgroup.conductor_dvd_dirichletConductor _
      ((mem_genusCharGroup_iff s hs).mpr ⟨{⟨P, hP⟩}, genusCharAtLevel_singleton ..⟩)

end EpsilonEridani.Multiquadratic
