/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.Algebra.Lie.HighestWeight.Character
public import EpsilonEridani.Algebra.Lie.HighestWeight.Separation
public import EpsilonEridani.LinearAlgebra.RootSystem.Weyl.DominantIntegral
import EpsilonEridani.Algebra.Lie.HighestWeight.Freudenthal
import EpsilonEridani.Data.Finset.Basic

/-!
# The Weyl character formula

Let `L` be a finite-dimensional Lie algebra with non-degenerate Killing form over an algebraically
closed field of characteristic zero, `H` a Cartan subalgebra, `b` a base of its root system, and
`M` a finite-dimensional module generated by a highest weight vector of weight `lam`. With
`c(χ) = ⟨χ + ρ, χ + ρ⟩ - ⟨ρ, ρ⟩` the Casimir scalar (`EpsilonEridani.casimirScalar`), this file proves
that `c` takes the single value `c(lam)` on the support of the product `ch M · Δ` of the formal
character with the Weyl denominator `Δ = ∏_{α>0}(1 - e^{-α})`.

Since `c` separates the dominant integral weights below `lam`, it follows that `ch M · Δ` vanishes
at every dominant integral weight other than `lam`, where its coefficient is `1`. These are the
dominant integral coefficients through which
`EpsilonEridani.formalCharacter_mul_weylDenominator_eq_of_forall_coeff_isDominantIntegral_eq` determines
`ch M · Δ`. The Weyl numerator `N(lam) = ∑_{w ∈ W} sgn(w) e^{w ⬝ lam}` has the very same dominant
integral coefficients, by `EpsilonEridani.coeff_weylNumerator_self_of_dominantIntegral` and
`EpsilonEridani.coeff_weylNumerator_eq_zero_of_dominantIntegral_of_ne`, and is supported in `lam - Q⁺`
as well, so the two are equal: that is the **Weyl character formula**, proved at the end of this
file.

## The argument

Write `m(χ) = dim M_χ` and `σ_T = ∑_{α ∈ T} α` for a set `T` of positive roots, so that the
coefficient of `ch M · Δ` at `χ` is `∑_T (-1)^{|T|} m(χ + σ_T)`. Multiply the `T`-th term by
`c(lam) - c(χ)` and split this as `(c(lam) - c(χ + σ_T)) + (c(χ + σ_T) - c(χ))`.

* By `EpsilonEridani.freudenthal_multiplicity_formula`, `(c(lam) - c(μ)) m(μ)` is twice the sum over the
  positive roots `α` of the Freudenthal string sums `∑_{j ≥ 1} m(μ + jα) ⟨μ + jα, α⟩`.
* `c(χ + σ) - c(χ) = 2⟨χ + σ, σ⟩ - c(-σ)`, and `⟨χ + σ_T, σ_T⟩` is the sum of the pairings with the
  roots `α ∈ T`.

For each positive root `α`, the string sum at `μ` is the string sum at `μ + α` plus
`m(μ + α) ⟨μ + α, α⟩`; pairing the sets `T ∌ α` with `T ∪ {α}` therefore cancels the string sums
against the root pairings. What survives is `-∑_T (-1)^{|T|} c(-σ_T) m(χ + σ_T)`, which groups
into `-∑_x c(x) Δ_x m(χ - x)`. This vanishes because `c` vanishes on the support of `Δ`
(`EpsilonEridani.casimirScalar_eq_zero_of_coeff_weylDenominator_ne_zero`): restricted to the weights
where `c ≠ 0`, the denominator is still alternating for the dot action (`c` is dot invariant),
lies in the negative root cone and has no dominant integral weight in its support, so it is zero
by `EpsilonEridani.IsDotAlternating.eq_zero_of_forall_coeff_dominantIntegral_eq_zero`.

## Main results

* `EpsilonEridani.casimirScalar_dotAction`: the Casimir scalar is invariant under the dot action.
* `EpsilonEridani.casimirScalar_eq_zero_of_coeff_weylDenominator_ne_zero`: the Casimir scalar vanishes on
  the support of the Weyl denominator.
* `EpsilonEridani.casimirScalar_eq_of_coeff_formalCharacter_mul_weylDenominator_ne_zero`: **the Casimir
  scalar is constant, equal to `c(lam)`, on the support of `ch M · Δ`.**
* `EpsilonEridani.coeff_formalCharacter_mul_weylDenominator_eq_zero_of_isDominantIntegral_of_ne`:
  **`ch M · Δ` vanishes at every dominant integral weight other than `lam`.**
* `EpsilonEridani.formalCharacter_mul_weylDenominator_eq_weylNumerator`: **the Weyl character formula**
  `ch M · Δ = N(lam)`, for `M` a finite-dimensional module generated by a highest weight vector.

## References

* V. G. Kac, *Infinite dimensional Lie algebras*, 3rd ed., Cambridge University Press (1990),
  §10.4, where the character formula is derived from the equality `|λ + ρ|² = |Λ + ρ|²` on the
  weights `λ` occurring in `ch L(Λ) · Δ`; there that equality comes from the Casimir operator on
  Verma modules, here it is derived from Freudenthal's formula.
* J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*, GTM 9, §22.3 and §24.
-/

public section

namespace EpsilonEridani

open Finset LieAlgebra LieModule Module

universe u v w

variable {K : Type u} {L : Type v} [Field K] [CharZero K]
  [LieRing L] [LieAlgebra K L] [IsKilling K L] [FiniteDimensional K L]
  {H : LieSubalgebra K L} [H.IsCartanSubalgebra]
  {M : Type w} [AddCommGroup M] [Module K M] [LieRingModule L M] [LieModule K L M]
  [FiniteDimensional K M]

section Triangularizable

variable [IsTriangularizable K H L]

/-! ### The Casimir scalar and the dot action -/

section Denominator

variable (b : (IsKilling.rootSystem H).Base)

/-- **The Casimir scalar is invariant under the dot action**: `c(w ⬝ x) = c(x)`, since
`w ⬝ x + ρ = w (x + ρ)` and the invariant form is Weyl invariant. -/
@[simp]
theorem casimirScalar_dotAction (w : (IsKilling.rootSystem H).weylGroup) (x : Dual K H) :
    casimirScalar b (dotAction (IsKilling.rootSystem H) b w x) = casimirScalar b x := by
  rw [casimirScalar_def, casimirScalar_def, dotAction_add_weylVector]
  congr 1
  simpa only [rootInvariantForm_form] using
    RootPairing.InvariantForm.apply_weylGroup_smul (IsKilling.rootSystem H)
      (B := rootInvariantForm (H := H)) w (x + weylVector (IsKilling.rootSystem H) b)
      (x + weylVector (IsKilling.rootSystem H) b)

/-- **The Casimir scalar vanishes on the support of the Weyl denominator.** -/
theorem casimirScalar_eq_zero_of_coeff_weylDenominator_ne_zero {x : Dual K H}
    (hx : (weylDenominator (IsKilling.rootSystem H) b).coeff x ≠ 0) :
    casimirScalar b x = 0 := by
  classical
  set f : AddMonoidAlgebra ℤ (Dual K H) := AddMonoidAlgebra.ofCoeff
    ((weylDenominator (IsKilling.rootSystem H) b).coeff.filter fun y ↦ casimirScalar b y ≠ 0)
  have hcoeff : ∀ y, f.coeff y = if casimirScalar b y ≠ 0 then
      (weylDenominator (IsKilling.rootSystem H) b).coeff y else 0 := fun y ↦ by
    simp [f, Finsupp.filter_apply]
  have hsupp : ∀ y, f.coeff y ≠ 0 →
      (weylDenominator (IsKilling.rootSystem H) b).coeff y ≠ 0 ∧ casimirScalar b y ≠ 0 :=
    fun y hy ↦ by
      rw [hcoeff] at hy
      split_ifs at hy with h
      exacts [⟨hy, h⟩, absurd rfl hy]
  have halt : IsDotAlternating (IsKilling.rootSystem H) b f :=
    (isDotAlternating_iff _ _ f).mpr fun w y ↦ by
      rw [hcoeff, hcoeff, casimirScalar_dotAction,
        (isDotAlternating_weylDenominator (IsKilling.rootSystem H) b).coeff_dotAction]
      split_ifs <;> simp
  have hcone : ∀ y, f.coeff y ≠ 0 → 0 - y ∈ posRootCone (IsKilling.rootSystem H) b :=
    fun y hy ↦ by
      rw [zero_sub]
      exact neg_mem_posRootCone_of_coeff_weylDenominator_ne_zero _ b (hsupp y hy).1
  have hf : f = 0 := by
    refine halt.eq_zero_of_forall_coeff_dominantIntegral_eq_zero hcone (fun y hy i _ ↦ ?_)
      fun y hdom ↦ ?_
    · obtain ⟨z, hz⟩ := exists_intCast_eq_coroot'_of_mem_posRootCone (IsKilling.rootSystem H) b
        (neg_mem_posRootCone_of_coeff_weylDenominator_ne_zero _ b (hsupp y hy).1) i
      exact ⟨-z, by rw [map_neg] at hz; push_cast; rw [← hz, neg_neg]⟩
    · by_contra hy
      have hy' : IsDominantIntegral b y := isDominantIntegral_iff.mpr fun i hi ↦ by
        obtain ⟨n, hn⟩ := hdom i hi
        exact ⟨n, by rwa [← rootSystem_coroot'_apply]⟩
      -- a dominant integral weight in the negative root cone is zero
      have hy0 : y = 0 := by
        by_contra hy0
        obtain ⟨q, hq0, hq⟩ := hy'.exists_nonneg_rat_invForm_of_mem_posRootCone
          (by simpa using hcone y hy)
        obtain ⟨p, hp0, hp⟩ := hy'.isIntegralWeight.exists_pos_rat_invForm_self hy0
        rw [map_neg, hp] at hq
        have : -p = q := by exact_mod_cast hq
        linarith
      exact (hsupp y hy).2 (by rw [hy0, casimirScalar_zero])
  by_contra hc
  have h := hcoeff x
  rw [hf] at h
  simp only [ne_eq, hc, not_false_eq_true, ite_true] at h
  exact hx (by simpa using h.symm)

/-- **The signed expansion of the Weyl denominator is annihilated by the Casimir scalar**: for any
function `g`, the sum over the sets `T` of positive roots of `(-1)^{|T|} c(-σ_T) g(σ_T)`, where
`σ_T` is the sum of the roots in `T`, vanishes. Grouping the sets by `σ_T` turns the sum into
`∑_x c(x) Δ_x g(-x)`, and each term vanishes by
`EpsilonEridani.casimirScalar_eq_zero_of_coeff_weylDenominator_ne_zero`. -/
private theorem sum_powerset_neg_one_pow_mul_casimirScalar_mul_eq_zero (g : Dual K H → K) :
    ∑ T ∈ (posRootsFinset (IsKilling.rootSystem H) b).powerset, (-1 : K) ^ T.card *
      (casimirScalar b (-∑ i ∈ T, ((i : Weight K H L) : Dual K H)) *
        g (∑ i ∈ T, ((i : Weight K H L) : Dual K H))) = 0 := by
  classical
  set P := posRootsFinset (IsKilling.rootSystem H) b
  let σ : Finset H.root → Dual K H := fun T ↦ ∑ i ∈ T, ((i : Weight K H L) : Dual K H)
  rw [← Finset.sum_fiberwise_of_maps_to (g := fun T ↦ -σ T)
    (t := P.powerset.image fun T ↦ -σ T) fun T hT ↦ Finset.mem_image_of_mem _ hT]
  refine Finset.sum_eq_zero fun x _ ↦ ?_
  have hfib : ∀ T ∈ P.powerset.filter (fun T ↦ -σ T = x),
      (-1 : K) ^ T.card * (casimirScalar b (-σ T) * g (σ T)) =
        casimirScalar b x * g (-x) * (-1 : K) ^ T.card := fun T hT ↦ by
    simp only [← (Finset.mem_filter.mp hT).2, neg_neg]
    ring
  have hcoeff : (((weylDenominator (IsKilling.rootSystem H) b).coeff x : ℤ) : K) =
      ∑ T ∈ P.powerset.filter (fun T ↦ -σ T = x), (-1 : K) ^ T.card := by
    rw [weylDenominator_eq_sum_powerset, AddMonoidAlgebra.coeff_sum, Finsupp.finsetSum_apply,
      Finset.sum_filter]
    push_cast
    refine Finset.sum_congr rfl fun T _ ↦ ?_
    simp only [AddMonoidAlgebra.coeff_single, Finsupp.single_apply,
      IsKilling.rootSystem_root_apply, σ]
    split_ifs <;> simp
  rw [Finset.sum_congr rfl hfib, ← Finset.mul_sum, ← hcoeff]
  by_cases hx : (weylDenominator (IsKilling.rootSystem H) b).coeff x = 0
  · simp [hx]
  · simp [casimirScalar_eq_zero_of_coeff_weylDenominator_ne_zero b hx]

end Denominator

/-! ### The Weyl character formula -/

variable {b : (IsKilling.rootSystem H).Base}

/-- The coefficients of `ch M · Δ`, expanded over the subsets of the positive roots. -/
private theorem intCast_coeff_formalCharacter_mul_weylDenominator (chi : Dual K H) :
    (((formalCharacter K H M * weylDenominator (IsKilling.rootSystem H) b).coeff chi : ℤ) : K) =
      ∑ T ∈ (posRootsFinset (IsKilling.rootSystem H) b).powerset, (-1 : K) ^ T.card *
        (finrank K (genWeightSpace M
          ((chi + ∑ i ∈ T, ((i : Weight K H L) : Dual K H) : Dual K H) : H → K)) : K) := by
  classical
  rw [weylDenominator_eq_sum_powerset, Finset.mul_sum, AddMonoidAlgebra.coeff_sum,
    Finsupp.finsetSum_apply]
  simp only [IsKilling.rootSystem_root_apply]
  push_cast
  refine Finset.sum_congr rfl fun T _ ↦ ?_
  rw [AddMonoidAlgebra.coeff_mul_single_apply, formalCharacter_coeff, neg_neg]
  push_cast
  ring

end Triangularizable

section HighestWeightModule

variable [IsAlgClosed K] {b : (IsKilling.rootSystem H).Base} {lam : Dual K H} {v : M}
  (hv : IsHighestWeightVector b lam v)
  (hgen : LieSubmodule.lieSpan K L {v} = ⊤)

include hv hgen

/-- **The Casimir scalar is constant on the support of `ch M · Δ`**: for a finite-dimensional
module generated by a highest weight vector of weight `lam`, every weight carrying a nonzero
coefficient of `ch M · Δ` has the Casimir scalar of `lam`. -/
theorem casimirScalar_eq_of_coeff_formalCharacter_mul_weylDenominator_ne_zero {chi : Dual K H}
    (hchi : (formalCharacter K H M * weylDenominator (IsKilling.rootSystem H) b).coeff chi ≠ 0) :
    casimirScalar b chi = casimirScalar b lam := by
  classical
  -- the multiplicity of a weight, the sum of a set of roots, and a Freudenthal string summand
  set P := posRootsFinset (IsKilling.rootSystem H) b
  let m : Dual K H → K := fun nu ↦ (finrank K (genWeightSpace M (nu : H → K)) : K)
  let σ : Finset H.root → Dual K H := fun T ↦ ∑ i ∈ T, ((i : Weight K H L) : Dual K H)
  let str : H.root → Dual K H → K := fun i mu ↦
    ∑ j ∈ (weightString M (Weight.coe_toLinear_ne_zero_iff.mpr (H.isNonZero_coe_root i))
        mu).erase 0,
      m (mu + j • ((i : Weight K H L) : Dual K H)) *
        invForm (mu + j • ((i : Weight K H L) : Dual K H)) ((i : Weight K H L) : Dual K H)
  let F : H.root → Finset H.root → K := fun i T ↦
    invForm (chi + σ T) ((i : Weight K H L) : Dual K H) * m (chi + σ T)
  -- Freudenthal's formula at each translate `chi + σ T`, rearranged
  have hA : ∀ T : Finset H.root, (casimirScalar b lam - casimirScalar b chi) * m (chi + σ T) =
      2 * (∑ i ∈ P, str i (chi + σ T) + ∑ i ∈ T, F i T) -
        casimirScalar b (-σ T) * m (chi + σ T) := fun T ↦ by
    have hfreud := freudenthal_multiplicity_formula hv hgen (chi + σ T)
    have htrans := casimirScalar_add_sub_casimirScalar (base := b) chi (σ T)
    have hsum : invForm (chi + σ T) (σ T) = ∑ i ∈ T, invForm (chi + σ T) ((i : Weight K H L) :
        Dual K H) := map_sum _ _ _
    simp only [F, str, m] at hfreud htrans hsum ⊢
    rw [← Finset.sum_mul, ← hsum]
    simp only [casimirScalar_def] at htrans ⊢
    linear_combination hfreud + (finrank K (genWeightSpace M ((chi + σ T : Dual K H) : H → K)) :
      K) * htrans
  -- the Freudenthal string sums cancel against the root pairings, telescoping along each root
  have hB : ∑ T ∈ P.powerset, (-1 : K) ^ T.card *
      (∑ i ∈ P, str i (chi + σ T) + ∑ i ∈ T, F i T) = 0 :=
    Finset.sum_powerset_neg_one_pow_mul_eq_zero P (fun i T ↦ str i (chi + σ T)) F
      fun i _ t ht ↦ by
      have hit : i ∉ t := fun h ↦ Finset.notMem_erase i P (Finset.mem_powerset.mp ht h)
      have hσ : chi + σ (insert i t) = chi + σ t + ((i : Weight K H L) : Dual K H) := by
        simp only [σ, Finset.sum_insert hit]
        abel
      simp only [F, str, m]
      rw [hσ, sum_weightString_erase_zero_eq_add_sum_erase_zero]
      ring
  have hkey : (casimirScalar b lam - casimirScalar b chi) *
      (((formalCharacter K H M * weylDenominator (IsKilling.rootSystem H) b).coeff chi : ℤ) :
        K) = 0 := by
    rw [intCast_coeff_formalCharacter_mul_weylDenominator, Finset.mul_sum]
    have h2 : ∀ T ∈ P.powerset, (casimirScalar b lam - casimirScalar b chi) *
        ((-1 : K) ^ T.card * m (chi + σ T)) =
        2 * ((-1 : K) ^ T.card * (∑ i ∈ P, str i (chi + σ T) + ∑ i ∈ T, F i T)) -
          (-1 : K) ^ T.card * (casimirScalar b (-σ T) * m (chi + σ T)) := fun T _ ↦ by
      rw [mul_left_comm, hA T]
      ring
    rw [Finset.sum_congr rfl h2, Finset.sum_sub_distrib, ← Finset.mul_sum, hB, mul_zero,
      zero_sub, neg_eq_zero]
    exact sum_powerset_neg_one_pow_mul_casimirScalar_mul_eq_zero b fun nu ↦ m (chi + nu)
  rcases mul_eq_zero.mp hkey with h | h
  · exact (sub_eq_zero.mp h).symm
  · exact absurd (Int.cast_eq_zero.mp h) hchi

/-- **`ch M · Δ` vanishes at every dominant integral weight other than the highest weight.** A
dominant integral weight in the support lies below `lam` and has the Casimir scalar of `lam`, and
the Casimir scalar separates dominant integral weights along the root cone order. -/
theorem coeff_formalCharacter_mul_weylDenominator_eq_zero_of_isDominantIntegral_of_ne
    {nu : Dual K H} (hnu : IsDominantIntegral b nu) (hne : nu ≠ lam) :
    (formalCharacter K H M * weylDenominator (IsKilling.rootSystem H) b).coeff nu = 0 := by
  by_contra h
  have hlam := hv.isDominantIntegral
  exact hlam.casimirScalar_ne_casimirScalar_of_isDominantIntegral_of_sub_mem_posRootCone_of_ne
      hnu (sub_mem_posRootCone_of_coeff_formalCharacter_mul_weylDenominator_ne_zero hv hgen h) hne
      (casimirScalar_eq_of_coeff_formalCharacter_mul_weylDenominator_ne_zero hv hgen h).symm

/-! ### The Weyl character formula -/

/-- **The Weyl character formula.** For a finite-dimensional module `M` generated by a highest
weight vector of weight `lam`, the formal character of `M` times the Weyl denominator is the Weyl
numerator of `lam`:
`ch M · ∏_{α>0} (1 - e^{-α}) = ∑_{w ∈ W} sgn(w) e^{w(lam + ρ) - ρ}`.

Both sides are alternating for the dot action and supported in `lam - Q⁺`, so
`EpsilonEridani.formalCharacter_mul_weylDenominator_eq_of_forall_coeff_isDominantIntegral_eq` reduces the
identity to the coefficients at the dominant integral weights. There both sides are `1` at `lam`
and `0` elsewhere: on the left by the two coefficient computations above and
`coeff_formalCharacter_mul_weylDenominator_eq_one_of_isHighestWeightVector_of_lieSpan_eq_top`,
on the right because the dot orbit of a dominant integral weight is free and meets the dominant
integral weights only at `lam`.

Such an `M` is irreducible, by
`EpsilonEridani.isIrreducible_of_isHighestWeightVector_of_lieSpan_eq_top`, so this is the character of
`L(lam)`; it is stated for `M` itself so that no identification with `L(lam)` is needed to use
it. -/
theorem formalCharacter_mul_weylDenominator_eq_weylNumerator
    [Fintype (IsKilling.rootSystem H).weylGroup] :
    formalCharacter K H M * weylDenominator (IsKilling.rootSystem H) b
      = weylNumerator (IsKilling.rootSystem H) b lam := by
  have hcoroot : ∀ {chi : Dual K H}, IsDominantIntegral b chi →
      ∀ i ∈ b.support, ∃ n : ℕ, (IsKilling.rootSystem H).coroot' i chi = (n : K) :=
    fun hchi i hi ↦ by
      obtain ⟨n, hn⟩ := isDominantIntegral_iff.mp hchi i hi
      exact ⟨n, by rwa [rootSystem_coroot'_apply]⟩
  have hlam := hcoroot hv.isDominantIntegral
  refine formalCharacter_mul_weylDenominator_eq_of_forall_coeff_isDominantIntegral_eq hv hgen
    (isDotAlternating_weylNumerator (IsKilling.rootSystem H) b lam)
    (fun _ h ↦ sub_mem_posRootCone_of_coeff_weylNumerator_ne_zero hlam h) fun nu hnu ↦ ?_
  rcases eq_or_ne nu lam with rfl | hne
  · rw [coeff_formalCharacter_mul_weylDenominator_eq_one_of_isHighestWeightVector_of_lieSpan_eq_top
      hv hgen, coeff_weylNumerator_self_of_dominantIntegral hlam]
  · rw [coeff_formalCharacter_mul_weylDenominator_eq_zero_of_isDominantIntegral_of_ne hv hgen hnu
      hne, coeff_weylNumerator_eq_zero_of_dominantIntegral_of_ne hlam (hcoroot hnu) hne]

end HighestWeightModule

end EpsilonEridani
