/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.Module.Submodule.Invariant
public import Mathlib.Algebra.Module.Submodule.Range

import Mathlib.Tactic.LinearCombination
import Mathlib.Tactic.NoncommRing
import EpsilonEridani.Algebra.Module.Submodule.Invariant
import EpsilonEridani.Algebra.Module.Submodule.Ker
import EpsilonEridani.RingTheory.Idempotents.CubeRootOne
import EpsilonEridani.RingTheory.Idempotents.SquareRootOne

/-!
# Operators of order two and three: Choie–Zagier criterion, Popa–Zagier's projection and exactness

The group `PSL(2, ℤ)` is generated by `S` of order two and `U` of order three, and
`T = U S`. Popa and Zagier's proof of the Eichler–Selberg trace formula works in the rational
vector space `ℛ = ℚ[ℳ]` spanned by integral matrices of positive determinant modulo `±1`, on which
`PSL(2, ℤ)` acts on both sides. The idempotents `π_S = (1 + S) / 2` and `π_U = (1 + U + U²) / 3`
generate the right ideal

`𝓘 = π_S ℛ + π_U ℛ`

(their (5)). This file records the linear algebra behind their Lemmas 1 and 3 and the exactness
step in the proof of their §3 Theorem 2, for endomorphisms `σ` and `υ` of a module `M` with
`σ ^ 2 = 1` and `υ ^ 3 = 1`, which are the left multiplications by `S` and `U`; the right
multiplications by `S` and `U` give a second such pair `σ'`, `υ'`, commuting with the first.
The ideal `𝓘` becomes the submodule `range (1 + σ) ⊔ range (1 + υ + υ ^ 2)`: when `2`
and `3` are invertible the unnormalised operators have the same ranges as the idempotents, and the
unnormalised form needs no invertibility where none is used.

## Main results

* `EpsilonEridani.End.one_sub_apply_mem_range_one_sub_mul_iff`: **the Choie–Zagier criterion**
  (Popa–Zagier, Lemma 1): if `2` and `3` are invertible and `ker (1 + σ)` and `ker (1 + υ + υ ^ 2)`
  are disjoint, then `x ∈ range (1 + σ) ⊔ range (1 + υ + υ ^ 2)` exactly when
  `(1 - σ) x ∈ range (1 - υ * σ)`, that is, `ξ ∈ 𝓘 ↔ (1 - S) ξ ∈ (1 - T) ℛ`. The forward direction,
  `EpsilonEridani.End.one_sub_apply_mem_range_one_sub_mul_of_mem_sup`, needs neither hypothesis.
* `EpsilonEridani.End.exists_mem_sup_one_add_apply_sub_mem`: **the existence half of Popa–Zagier's
  Lemma 3** for the idempotents `(1 + σ) / 2` and `(1 + υ + υ ^ 2) / 3`, stated with the
  unnormalised operators: if `(1 + σ) ξ` and `(1 + υ + υ ^ 2) ξ` lie in `P ⊔ Q`, for submodules `P`
  and `Q` stable under `1 + υ + υ ^ 2` and `1 + σ`, then `ξ` can be corrected by an element `ι` of
  `P ⊔ Q` so that `(1 + σ) (ξ - ι) ∈ Q` and `(1 + υ + υ ^ 2) (ξ - ι) ∈ P`.
* `EpsilonEridani.End.mem_sup_range_one_add_mul_one_sub`: **exactness in Popa–Zagier's §3 Theorem 2**:
  if `2` and `3` are invertible and `ker (1 + σ')`, `ker (1 + υ' + υ' ^ 2)` are disjoint, then a
  vector `ξ ∈ range (1 - σ') ⊔ range (1 - υ')` with `(1 + σ') ξ ∈ range (1 + υ + υ ^ 2)` and
  `(1 + υ' + υ' ^ 2) ξ ∈ range (1 + σ)` lies in
  `range ((1 + σ) (1 - σ')) ⊔ range ((1 + υ + υ ^ 2) (1 - υ'))`, that is, an element of their
  `ℬ` (6) whose right coset sums vanish lies in `𝒥 = π_S ℛ (1 - π_S) + π_U ℛ (1 - π_U)` (7).
* `EpsilonEridani.one_sub_mul_one_add_add_sq`: the ring identity
  `(1 - σ) (1 + υ + υ ^ 2) = (1 - υ σ) (-σ (1 + υ + υ ^ 2))` for `σ ^ 2 = 1` and `υ ^ 3 = 1`, and
  its mirror image `EpsilonEridani.one_add_add_sq_mul_one_sub`, for right multiplications.
* `EpsilonEridani.one_sub_mul_one_add_of_sq_eq_one`, `EpsilonEridani.one_add_mul_one_sub_of_sq_eq_one`,
  `EpsilonEridani.one_sub_mul_one_add_add_sq_of_pow_three_eq_one`,
  `EpsilonEridani.one_add_add_sq_mul_one_sub_of_pow_three_eq_one`: `(1 ∓ σ) (1 ± σ) = 0` for
  `σ ^ 2 = 1`, and `(1 - υ) (1 + υ + υ ^ 2) = (1 + υ + υ ^ 2) (1 - υ) = 0` for `υ ^ 3 = 1`.
* `EpsilonEridani.End.range_one_add_eq_ker_one_sub`, `EpsilonEridani.End.range_one_add_add_sq_eq_ker_one_sub`:
  the fixed vectors of `σ` and of `υ` are the ranges of `1 + σ` and of `1 + υ + υ ^ 2`. The
  inclusions `EpsilonEridani.End.range_one_add_le_ker_one_sub` and
  `EpsilonEridani.End.range_one_add_add_sq_le_ker_one_sub` need no invertibility, and the reverse
  inclusions hold inside any submodule `Y` without the order hypotheses:
  `EpsilonEridani.End.inf_ker_one_sub_le_map_one_add` and
  `EpsilonEridani.End.inf_ker_one_sub_le_map_one_add_add_sq` (`Y ⊓ ker (1 - σ) ≤ Y.map (1 + σ)` when `2`
  is invertible, and likewise with `3`).
* `EpsilonEridani.End.range_one_sub_le_ker_one_add`, `EpsilonEridani.End.range_one_sub_le_ker_one_add_add_sq`:
  dually, `1 + σ` kills `range (1 - σ)` and `1 + υ + υ ^ 2` kills `range (1 - υ)`.

## Implementation notes

The ring identities are proved in an arbitrary ring and then applied in `Module.End`; the
acyclicity hypothesis is stated as `Disjoint (ker (1 + σ)) (ker (1 + υ + υ ^ 2))`. The existence
half of Lemma 3 for arbitrary idempotents is
`EpsilonEridani.End.exists_mem_sup_apply_sub_mem_of_isIdempotentElem`, and the exactness step for
arbitrary commuting endomorphisms is `EpsilonEridani.End.mem_inf_ker_sup_inf_ker_of_mem_sup`.

## References

* A. Popa and D. Zagier, *An elementary proof of the Eichler–Selberg trace formula*,
  J. Reine Angew. Math. 762 (2020), 105–122, arXiv:1711.00327, Section 3, Lemmas 1 and 3 and
  the proof of Theorem 2.
* Y. J. Choie and D. Zagier, *Rational period functions for `PSL(2, ℤ)`*,
  Contemp. Math. 143 (1993), 89–108.
-/

public section

namespace EpsilonEridani

section Ring

variable {A : Type*} [Ring A] {σ υ : A}

/-- `(1 - σ) (1 + σ) = 0` for `σ ^ 2 = 1`. -/
theorem one_sub_mul_one_add_of_sq_eq_one (hσ : σ ^ 2 = 1) : (1 - σ) * (1 + σ) = 0 := by
  linear_combination (norm := noncomm_ring) -hσ

/-- `(1 + σ) (1 - σ) = 0` for `σ ^ 2 = 1`. -/
theorem one_add_mul_one_sub_of_sq_eq_one (hσ : σ ^ 2 = 1) : (1 + σ) * (1 - σ) = 0 := by
  linear_combination (norm := noncomm_ring) -hσ

/-- `(1 - υ) (1 + υ + υ²) = 0` for `υ ^ 3 = 1`. -/
theorem one_sub_mul_one_add_add_sq_of_pow_three_eq_one (hυ : υ ^ 3 = 1) :
    (1 - υ) * (1 + υ + υ ^ 2) = 0 := by
  linear_combination (norm := noncomm_ring) -hυ

/-- `(1 + υ + υ²) (1 - υ) = 0` for `υ ^ 3 = 1`. -/
theorem one_add_add_sq_mul_one_sub_of_pow_three_eq_one (hυ : υ ^ 3 = 1) :
    (1 + υ + υ ^ 2) * (1 - υ) = 0 := by
  linear_combination (norm := noncomm_ring) -hυ

/-- **`(1 - σ) (1 + υ + υ²)` lies in `(1 - υ σ) A`** when `σ ^ 2 = 1` and `υ ^ 3 = 1`.
This is Popa–Zagier's relation `(1 - S) π_U = (1 - T⁻¹) π_U` for `T = U S`, rewritten through
`1 - T⁻¹ = (1 - T) (-T⁻¹)`, and it is the forward direction of the Choie–Zagier criterion. -/
theorem one_sub_mul_one_add_add_sq (hσ : σ ^ 2 = 1) (hυ : υ ^ 3 = 1) :
    (1 - σ) * (1 + υ + υ ^ 2) = (1 - υ * σ) * -(σ * (1 + υ + υ ^ 2)) := by
  linear_combination (norm := noncomm_ring) -hυ - υ * hσ * (1 + υ + υ ^ 2)

/-- `(1 + υ + υ²) (1 - σ) = -((1 + υ + υ²) σ) (1 - σ υ)` for `σ ^ 2 = 1` and `υ ^ 3 = 1`: the
mirror image of `EpsilonEridani.one_sub_mul_one_add_add_sq`, for right multiplications. -/
theorem one_add_add_sq_mul_one_sub (hσ : σ ^ 2 = 1) (hυ : υ ^ 3 = 1) :
    (1 + υ + υ ^ 2) * (1 - σ) = -((1 + υ + υ ^ 2) * σ) * (1 - σ * υ) := by
  linear_combination (norm := noncomm_ring) -hυ - (1 + υ + υ ^ 2) * hσ * υ

end Ring

namespace End

open Module LinearMap

section Semiring

variable {R M : Type*} [Semiring R] [AddCommGroup M] [Module R M] {σ υ : End R M}

/-- For `σ ^ 2 = 1`, the vectors `(1 + σ) x` are fixed by `σ`. -/
theorem range_one_add_le_ker_one_sub (hσ : σ ^ 2 = 1) : range (1 + σ) ≤ ker (1 - σ) :=
  range_le_ker_iff.2 (one_sub_mul_one_add_of_sq_eq_one hσ)

/-- For `σ ^ 2 = 1`, the vectors `(1 - σ) x` are killed by `1 + σ`. -/
theorem range_one_sub_le_ker_one_add (hσ : σ ^ 2 = 1) : range (1 - σ) ≤ ker (1 + σ) :=
  range_le_ker_iff.2 (one_add_mul_one_sub_of_sq_eq_one hσ)

/-- When `2` is invertible, a vector `y ∈ Y` fixed by `σ` is `(1 + σ) (y / 2)`. -/
theorem inf_ker_one_sub_le_map_one_add [Invertible (2 : R)] (Y : Submodule R M) :
    Y ⊓ ker (1 - σ) ≤ Y.map (1 + σ) := by
  intro y hy
  obtain ⟨hy, hfix⟩ := Submodule.mem_inf.1 hy
  have hfix : y = σ y := by simpa [sub_eq_zero] using hfix
  exact ⟨(⅟2 : R) • y, Y.smul_mem _ hy, by simp [← hfix, ← two_smul R]⟩

/-- **The fixed vectors of an involution are the range of `1 + σ`**, when `2` is invertible. -/
theorem range_one_add_eq_ker_one_sub [Invertible (2 : R)] (hσ : σ ^ 2 = 1) :
    range (1 + σ) = ker (1 - σ) :=
  (range_one_add_le_ker_one_sub hσ).antisymm <| by simpa using inf_ker_one_sub_le_map_one_add ⊤

/-- When `3` is invertible, a vector `y ∈ Y` fixed by `υ` is `(1 + υ + υ²) (y / 3)`. -/
theorem inf_ker_one_sub_le_map_one_add_add_sq [Invertible (3 : R)] (Y : Submodule R M) :
    Y ⊓ ker (1 - υ) ≤ Y.map (1 + υ + υ ^ 2) := by
  intro y hy
  obtain ⟨hy, hfix⟩ := Submodule.mem_inf.1 hy
  have hfix : y = υ y := by simpa [sub_eq_zero] using hfix
  refine ⟨(⅟3 : R) • y, Y.smul_mem _ hy, ?_⟩
  simpa [sq, ← hfix, ← two_add_one_eq_three, add_smul, two_smul] using invOf_smul_smul (3 : R) y

/-- For `υ ^ 3 = 1`, the vectors `(1 + υ + υ²) x` are fixed by `υ`. -/
theorem range_one_add_add_sq_le_ker_one_sub (hυ : υ ^ 3 = 1) :
    range (1 + υ + υ ^ 2) ≤ ker (1 - υ) :=
  range_le_ker_iff.2 (one_sub_mul_one_add_add_sq_of_pow_three_eq_one hυ)

/-- For `υ ^ 3 = 1`, the vectors `(1 - υ) x` are killed by `1 + υ + υ²`. -/
theorem range_one_sub_le_ker_one_add_add_sq (hυ : υ ^ 3 = 1) :
    range (1 - υ) ≤ ker (1 + υ + υ ^ 2) :=
  range_le_ker_iff.2 (one_add_add_sq_mul_one_sub_of_pow_three_eq_one hυ)

/-- **The fixed vectors of an endomorphism `υ` with `υ ^ 3 = 1` are the range of
`1 + υ + υ²`**, when `3` is invertible. -/
theorem range_one_add_add_sq_eq_ker_one_sub [Invertible (3 : R)] (hυ : υ ^ 3 = 1) :
    range (1 + υ + υ ^ 2) = ker (1 - υ) :=
  (range_one_add_add_sq_le_ker_one_sub hυ).antisymm <| by
    simpa using inf_ker_one_sub_le_map_one_add_add_sq ⊤

/-- **The Choie–Zagier criterion, forward direction** (Popa–Zagier, Lemma 1, `⇒`): for
`σ ^ 2 = 1` and `υ ^ 3 = 1`, if `x ∈ range (1 + σ) ⊔ range (1 + υ + υ²)` then
`(1 - σ) x ∈ range (1 - υ σ)`. No invertibility is needed. -/
theorem one_sub_apply_mem_range_one_sub_mul_of_mem_sup (hσ : σ ^ 2 = 1) (hυ : υ ^ 3 = 1) {x : M}
    (hx : x ∈ range (1 + σ) ⊔ range (1 + υ + υ ^ 2)) : (1 - σ) x ∈ range (1 - υ * σ) := by
  obtain ⟨-, ⟨a, rfl⟩, -, ⟨b, rfl⟩, rfl⟩ := Submodule.mem_sup.1 hx
  refine ⟨(-(σ * (1 + υ + υ ^ 2)) : End R M) b, ?_⟩
  simp only [map_add, ← End.mul_apply, one_sub_mul_one_add_of_sq_eq_one hσ,
    one_sub_mul_one_add_add_sq hσ hυ, zero_apply, zero_add]

/-- **The ranges of `1 - σ` and `1 - υ` are disjoint** when `σ ^ 2 = 1`, `υ ^ 3 = 1` and
`ker (1 + σ)`, `ker (1 + υ + υ²)` are disjoint. -/
theorem disjoint_range_one_sub_of_disjoint_ker (hσ : σ ^ 2 = 1) (hυ : υ ^ 3 = 1)
    (hacyc : Disjoint (ker (1 + σ)) (ker (1 + υ + υ ^ 2))) :
    Disjoint (range (1 - σ)) (range (1 - υ)) :=
  hacyc.mono (range_one_sub_le_ker_one_add hσ) (range_one_sub_le_ker_one_add_add_sq hυ)

/-- **The Choie–Zagier criterion** (Popa–Zagier, Lemma 1): for `σ ^ 2 = 1` and `υ ^ 3 = 1` with
`2` and `3` invertible and `ker (1 + σ)`, `ker (1 + υ + υ²)` disjoint, a vector `x` lies in
`range (1 + σ) ⊔ range (1 + υ + υ²)` exactly when `(1 - σ) x ∈ range (1 - υ σ)`. -/
theorem one_sub_apply_mem_range_one_sub_mul_iff [Invertible (2 : R)] [Invertible (3 : R)]
    (hσ : σ ^ 2 = 1) (hυ : υ ^ 3 = 1) (hacyc : Disjoint (ker (1 + σ)) (ker (1 + υ + υ ^ 2)))
    {x : M} : (1 - σ) x ∈ range (1 - υ * σ) ↔ x ∈ range (1 + σ) ⊔ range (1 + υ + υ ^ 2) := by
  refine ⟨fun ⟨η, hη⟩ => ?_, one_sub_apply_mem_range_one_sub_mul_of_mem_sup hσ hυ⟩
  -- `(1 - σ) (x - η) = (1 - υ) (σ η)` lies in `range (1 - σ) ⊓ range (1 - υ) = ⊥`
  have hc : (1 - σ) (x - η) = (1 - υ) (σ η) := by
    rw [map_sub, ← hη]
    simp [sub_sub_sub_cancel_left]
  have h0 : (1 - σ) (x - η) = 0 := Submodule.disjoint_def.1
    (disjoint_range_one_sub_of_disjoint_ker hσ hυ hacyc) _ ⟨_, rfl⟩ ⟨_, hc.symm⟩
  -- so `x - η` is fixed by `σ` and `σ η = (1 + υ + υ²) w` by `υ`, whence
  -- `x = (x - η) + (1 + σ) η + (1 + υ + υ²) (-w)`
  have h1 : x - η ∈ range (1 + σ) := (range_one_add_eq_ker_one_sub hσ).ge (mem_ker.2 h0)
  obtain ⟨w, hw⟩ := (range_one_add_add_sq_eq_ker_one_sub hυ).ge (mem_ker.2 (hc.symm.trans h0))
  have hx : x = (x - η) + (1 + σ) η + (1 + υ + υ ^ 2 : End R M) (-w) := by
    rw [map_neg, hw, add_apply, End.one_apply]
    abel
  rw [hx]
  exact add_mem (add_mem (Submodule.mem_sup_left h1) (Submodule.mem_sup_left (mem_range_self _ η)))
    (Submodule.mem_sup_right (mem_range_self _ _))

/-- **Exactness in Popa–Zagier's §3 Theorem 2**: for `σ ^ 2 = σ' ^ 2 = 1` and `υ ^ 3 = υ' ^ 3 = 1`,
with `σ` and `υ` commuting with `σ'` and `υ'`, `2` and `3` invertible and `ker (1 + σ')`,
`ker (1 + υ' + υ'²)` disjoint: if `ξ ∈ range (1 - σ') ⊔ range (1 - υ')`,
`(1 + σ') ξ ∈ range (1 + υ + υ²)` and `(1 + υ' + υ'²) ξ ∈ range (1 + σ)`, then
`ξ ∈ range ((1 + σ) (1 - σ')) ⊔ range ((1 + υ + υ²) (1 - υ'))`.

For the left multiplications `σ, υ` and the right multiplications `σ', υ'` by `S, U` on `ℛ`, the
hypotheses on `ξ` say that `ξ ∈ ℛ (1 - S) + ℛ (1 - U)`, the elements whose right coset sums vanish,
and that `ξ` lies in their `ℬ = {ξ | ξ π_S ∈ π_U ℛ, ξ π_U ∈ π_S ℛ}` (6); the conclusion is
`ξ ∈ 𝒥 = π_S ℛ (1 - π_S) + π_U ℛ (1 - π_U)` (7). -/
theorem mem_sup_range_one_add_mul_one_sub [Invertible (2 : R)] [Invertible (3 : R)]
    {σ' υ' : End R M} (hσ : σ ^ 2 = 1) (hυ : υ ^ 3 = 1) (hσ' : σ' ^ 2 = 1) (hυ' : υ' ^ 3 = 1)
    (hσσ' : Commute σ σ') (hσυ' : Commute σ υ') (hυσ' : Commute υ σ') (hυυ' : Commute υ υ')
    (hacyc : Disjoint (ker (1 + σ')) (ker (1 + υ' + υ' ^ 2))) {ξ : M}
    (hξ : ξ ∈ range (1 - σ') ⊔ range (1 - υ')) (hσ'ξ : (1 + σ') ξ ∈ range (1 + υ + υ ^ 2))
    (hυ'ξ : (1 + υ' + υ' ^ 2 : End R M) ξ ∈ range (1 + σ)) :
    ξ ∈ range ((1 + σ) * (1 - σ')) ⊔ range ((1 + υ + υ ^ 2) * (1 - υ')) := by
  have hc {a b : End R M} (h : Commute a b) :
      Commute (1 - a) (1 + b) ∧ Commute (1 - a) (1 + b + b ^ 2) :=
    have h' := (Commute.one_left _).sub_left h
    ⟨.add_right (.one_right _) h', .add_right (.add_right (.one_right _) h') (h'.pow_right 2)⟩
  refine sup_le_sup ((inf_ker_one_sub_le_map_one_add _).trans_eq (range_comp _ _).symm)
    ((inf_ker_one_sub_le_map_one_add_add_sq _).trans_eq (range_comp _ _).symm) <|
    mem_inf_ker_sup_inf_ker_of_mem_sup (hc hσσ').1
    (hc hσυ').2 (hc hυσ').1 (hc hυυ').2 hacyc
    (range_one_sub_le_ker_one_add hσ') (range_one_sub_le_ker_one_add_add_sq hυ') hξ
    (range_one_add_add_sq_le_ker_one_sub hυ hσ'ξ) (range_one_add_le_ker_one_sub hσ hυ'ξ)

end Semiring

section Ring

variable {R M : Type*} [Ring R] [AddCommGroup M] [Module R M] {σ υ : End R M}

/-- **Popa–Zagier's projection for operators of order two and three** (Lemma 3, existence half):
for `σ ^ 2 = 1` and `υ ^ 3 = 1` with `2` and `3` invertible, `P` stable under `1 + υ + υ²` and `Q`
under `1 + σ`, if `(1 + σ) ξ` and `(1 + υ + υ²) ξ` lie in `P ⊔ Q`, then there is `ι ∈ P ⊔ Q` with
`(1 + σ) (ξ - ι) ∈ Q` and `(1 + υ + υ²) (ξ - ι) ∈ P`. This is
`EpsilonEridani.End.exists_mem_sup_apply_sub_mem_of_isIdempotentElem` for the idempotents `(1 + σ) / 2` and
`(1 + υ + υ²) / 3`; the ring `R` need not be commutative, since `2` and `3` are central. -/
theorem exists_mem_sup_one_add_apply_sub_mem [Invertible (2 : R)] [Invertible (3 : R)]
    (hσ : σ ^ 2 = 1) (hυ : υ ^ 3 = 1) {P Q : Submodule R M} (hP : P ∈ (1 + υ + υ ^ 2).invtSubmodule)
    (hQ : Q ∈ (1 + σ).invtSubmodule) {ξ : M} (hσξ : (1 + σ) ξ ∈ P ⊔ Q)
    (hυξ : (1 + υ + υ ^ 2 : End R M) ξ ∈ P ⊔ Q) :
    ∃ ι ∈ P ⊔ Q, (1 + σ) (ξ - ι) ∈ Q ∧ (1 + υ + υ ^ 2 : End R M) (ξ - ι) ∈ P := by
  -- normalise over the commutative ring `Subring.center R`, in which `2` and `3` stay invertible
  -- and over which `End R M` is an algebra
  let _ : Invertible (2 : Subring.center R) :=
    ⟨⟨⅟2, Set.invOf_mem_center (Set.ofNat_mem_center _ _)⟩, Subtype.ext (invOf_mul_self _),
      Subtype.ext (mul_invOf_self _)⟩
  let _ : Invertible (3 : Subring.center R) :=
    ⟨⟨⅟3, Set.invOf_mem_center (Set.ofNat_mem_center _ _)⟩, Subtype.ext (invOf_mul_self _),
      Subtype.ext (mul_invOf_self _)⟩
  have key := exists_mem_sup_apply_sub_mem_of_isIdempotentElem (ξ := ξ)
    (halfOneAdd_def (Subring.center R) σ ▸
      isIdempotentElem_halfOneAdd (Subring.center R) ((sq σ).symm.trans hσ))
    (isIdempotentElem_invOf_three_smul_one_add_add_sq (Subring.center R) hυ)
    (Module.End.invtSubmodule_le_invtSubmodule_smul _ _ hP)
    (Module.End.invtSubmodule_le_invtSubmodule_smul _ _ hQ)
  simp only [smul_apply] at key
  obtain ⟨ι, hι, h₁, h₂⟩ :=
    key (Submodule.smul_of_tower_mem _ _ hσξ) (Submodule.smul_of_tower_mem _ _ hυξ)
  -- multiply back by `2` and `3`
  refine ⟨ι, hι, ?_, ?_⟩
  · simpa using Submodule.smul_of_tower_mem _ (2 : Subring.center R) h₁
  · simpa using Submodule.smul_of_tower_mem _ (3 : Subring.center R) h₂

end Ring

end End

end EpsilonEridani
