/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Data.ZMod.Basic
public import Mathlib.LinearAlgebra.Finsupp.LSum
public import EpsilonEridani.KnotTheory.Grid.BlockedRectangle

/-!
# The fully blocked grid chain module

This file packages the first algebraic object in the grid-combinatorial lane: the free
`ZMod 2`-module on grid states, together with the linear map whose matrix coefficient from
`x` to `y` is the parity of fully blocked empty rectangles from `x` to `y`.

The square-zero theorem is deliberately not asserted here. This module only supplies the
concrete finite free module and differential map to which the later rectangle-pairing proof
will apply.

## Main definitions

* `EpsilonEridani.GridChain`: the free module generated by grid states.
* `EpsilonEridani.GridChain.transposeEquiv`: the linear automorphism of grid chains relabeling each
  generator by the diagonal reflection of grid states.
* `EpsilonEridani.GridDiagram.fullyBlockedDifferentialOnGenerator`: the row of the fully blocked
  differential on one generator.
* `EpsilonEridani.GridDiagram.fullyBlockedDifferential`: the corresponding `ZMod 2`-linear map.
* `EpsilonEridani.GridDiagram.exists_swapColumns_of_fullyBlockedDifferentialOnGenerator_ne_zero`: the
  fully blocked differential of a generator is supported on its column transpositions.

## References

The coefficient formula follows Ozsváth--Stipsicz--Szabó, *Grid Homology for Knots and Links*,
Chapter 3.
-/

public section

namespace EpsilonEridani

/-- Finitely supported coefficient functions on grid states of size `n`.

When `R` has the needed algebraic structure, this is the free module generated by those
grid states with coefficients in `R`. -/
abbrev GridChain (R : Type*) [Zero R] (n : ℕ) : Type _ :=
  GridState n →₀ R

namespace GridChain

/-- The linear automorphism of grid chains induced by the diagonal reflection of grid states.

Because `GridState.transpose` is an involution, relabeling each generator `x` by `x.transpose`
gives a linear automorphism of the chain module `GridChain R n`. -/
noncomputable def transposeEquiv (R : Type*) [Semiring R] (n : ℕ) :
    GridChain R n ≃ₗ[R] GridChain R n :=
  Finsupp.domLCongr (Function.Involutive.toPerm _ GridState.transpose_transpose)

/-- The transpose relabeling sends the generator `x` to the generator `x.transpose`. -/
@[simp]
theorem transposeEquiv_single {R : Type*} [Semiring R] {n : ℕ} (x : GridState n) (a : R) :
    transposeEquiv R n (Finsupp.single x a) = Finsupp.single x.transpose a :=
  Finsupp.domLCongr_single _ x a

/-- The `y`-coefficient of a relabeled chain is the `y.transpose`-coefficient of the original
chain. -/
@[simp]
theorem transposeEquiv_apply {R : Type*} [Semiring R] {n : ℕ} (f : GridChain R n)
    (y : GridState n) : transposeEquiv R n f y = f y.transpose := by
  rw [transposeEquiv, Finsupp.domLCongr_apply]
  exact Finsupp.equivMapDomain_apply _ _ _

/-- The transpose relabeling is its own inverse: since `GridState.transpose` is an involution, the
inverse automorphism is again `transposeEquiv`. This lets the forward lemmas
`transposeEquiv_single` and `transposeEquiv_apply` also drive the inverse map. -/
@[simp]
theorem transposeEquiv_symm {R : Type*} [Semiring R] {n : ℕ} :
    (transposeEquiv R n).symm = transposeEquiv R n := by
  unfold transposeEquiv
  rw [Finsupp.domLCongr_symm,
    Function.Involutive.toPerm_symm GridState.transpose_transpose]

end GridChain

namespace GridDiagram

variable {n : ℕ} (G : GridDiagram n)

/-- The value of the fully blocked differential on a single grid-state generator.

Its `y`-coefficient is the parity of fully blocked empty rectangles from `x` to `y`. -/
@[expose]
noncomputable def fullyBlockedDifferentialOnGenerator (x : GridState n) : GridChain (ZMod 2) n :=
  Finset.univ.sum fun y : GridState n =>
    Finsupp.single y (G.fullyBlockedRectangleCount x y)

/-- The generator row of the fully blocked differential is the finite sum of rectangle-count
coefficients. -/
theorem fullyBlockedDifferentialOnGenerator_def (x : GridState n) :
    G.fullyBlockedDifferentialOnGenerator x =
      Finset.univ.sum fun y : GridState n =>
        Finsupp.single y (G.fullyBlockedRectangleCount x y) :=
  rfl

/-- The `y`-coefficient of the fully blocked differential on the generator `x`. -/
@[simp]
theorem fullyBlockedDifferentialOnGenerator_apply (x y : GridState n) :
    G.fullyBlockedDifferentialOnGenerator x y = G.fullyBlockedRectangleCount x y := by
  classical
  rw [fullyBlockedDifferentialOnGenerator]
  rw [Finsupp.finsetSum_apply]
  rw [Finset.sum_eq_single y]
  · simp
  · intro z _ hz
    simp [hz.symm]
  · intro hy
    exact (hy (Finset.mem_univ y)).elim

/-- The fully blocked differential of a generator is supported on the column transpositions of
that generator: if the `y`-coefficient is nonzero, then `y` is a column transposition of `x`. -/
theorem exists_swapColumns_of_fullyBlockedDifferentialOnGenerator_ne_zero {x y : GridState n}
    (h : G.fullyBlockedDifferentialOnGenerator x y ≠ 0) :
    ∃ a b : Fin n, a ≠ b ∧ y = x.swapColumns a b := by
  rw [fullyBlockedDifferentialOnGenerator_apply] at h
  exact G.exists_swapColumns_of_fullyBlockedRectangleCount_ne_zero x y h

/-- The fully blocked grid differential as a `ZMod 2`-linear map on chains. -/
noncomputable def fullyBlockedDifferential : GridChain (ZMod 2) n →ₗ[ZMod 2] GridChain (ZMod 2) n :=
  Finsupp.lsum (ZMod 2) fun x : GridState n =>
    (LinearMap.id : ZMod 2 →ₗ[ZMod 2] ZMod 2).smulRight
      (G.fullyBlockedDifferentialOnGenerator x)

/-- The fully blocked differential sends a single generator to the corresponding rectangle-count
row. -/
@[simp]
theorem fullyBlockedDifferential_single (x : GridState n) :
    G.fullyBlockedDifferential (Finsupp.single x 1) =
      G.fullyBlockedDifferentialOnGenerator x := by
  classical
  rw [fullyBlockedDifferential]
  rw [Finsupp.lsum_single]
  simp

/-- The matrix coefficient of the fully blocked differential on a single generator is the fully
blocked rectangle count. -/
theorem fullyBlockedDifferential_single_apply (x y : GridState n) :
    G.fullyBlockedDifferential (Finsupp.single x 1) y =
      G.fullyBlockedRectangleCount x y := by
  simp

/-- There is no self-term in the fully blocked differential of a generator. -/
theorem fullyBlockedDifferentialOnGenerator_apply_self (x : GridState n) :
    G.fullyBlockedDifferentialOnGenerator x x = 0 := by
  simp

/-- The self-coefficient of the fully blocked differential on a single generator is zero. -/
theorem fullyBlockedDifferential_single_apply_self (x : GridState n) :
    G.fullyBlockedDifferential (Finsupp.single x 1) x = 0 := by
  simp

/-- The fully blocked differential is the finite sum of its generator rows over the support
of a chain. -/
theorem fullyBlockedDifferential_apply (c : GridChain (ZMod 2) n) :
    G.fullyBlockedDifferential c =
      c.sum fun x a => a • G.fullyBlockedDifferentialOnGenerator x := by
  rw [fullyBlockedDifferential]
  rw [Finsupp.lsum_apply]
  simp [Finsupp.sum, LinearMap.smulRight_apply]

/-- The coefficient formula for the fully blocked differential on an arbitrary chain. -/
@[simp]
theorem fullyBlockedDifferential_apply_apply (c : GridChain (ZMod 2) n) (y : GridState n) :
    G.fullyBlockedDifferential c y =
      c.sum fun x a => a * G.fullyBlockedRectangleCount x y := by
  classical
  rw [fullyBlockedDifferential_apply]
  simp [Finsupp.sum_apply]

end GridDiagram

end EpsilonEridani
