/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.GroupTheory.SpecificGroups.Dihedral.Frobenius
public import EpsilonEridani.RepresentationTheory.FrobeniusGroup.Basic

/-!
# The Frobenius kernel of an odd dihedral group is its rotation subgroup

For odd `n > 1` the subgroup generated by a reflection is a Frobenius complement in
`DihedralGroup n` (`EpsilonEridani.isFrobeniusComplement_zpowers_dihedralSr`). Frobenius's theorem then
produces a normal complement to it out of nothing but the trivial-intersection property: the
elements lying in no conjugate of the complement, together with the identity, form a subgroup
(`EpsilonEridani.frobeniusKernelSubgroup`). This file identifies that subgroup.

It is the rotation subgroup, of order `n`. The identification is immediate from
`EpsilonEridani.frobeniusKernelSubgroup_eq_of_isComplement'`, because the semidirect decomposition
`DihedralGroup n = C_n ⋊ C₂` is already available; the content is that the character-theoretic
construction, which never mentions rotations, lands on them. On the underlying *set* of elements no
character theory is involved, and that statement is already
`EpsilonEridani.frobeniusKernel_zpowers_dihedralSr`, proved in
`EpsilonEridani/GroupTheory/SpecificGroups/Dihedral/Frobenius.lean`. Compare
`EpsilonEridani/RepresentationTheory/FrobeniusGroup/SymmetricThree.lean`, which settles the degree-`3`
member of this family in the permutation presentation of the same abstract group: it works
directly with `Equiv.Perm (Fin 3)`, a point stabilizer and the alternating subgroup, in place of
`DihedralGroup 3`, a reflection subgroup and the rotations, and no isomorphism between the two
presentations is used.

Reading the count off in this family also checks the general divisibility
`|H| ∣ |N| - 1` of `EpsilonEridani.card_dvd_card_frobeniusKernelSubgroup_sub_one`: it says `2 ∣ n - 1`,
which is oddness again.

## Main results

* `EpsilonEridani.frobeniusKernelSubgroup_zpowers_dihedralSr`: **the Frobenius kernel of a reflection
  subgroup of an odd dihedral group is the rotation subgroup.**
* `EpsilonEridani.card_frobeniusKernelSubgroup_zpowers_dihedralSr`: that kernel has `n` elements.

## References

* I. M. Isaacs, *Character Theory of Finite Groups*, AMS Chelsea (1976), Chapter 7, Theorem 7.2
  and the examples following it.
* J.-P. Serre, *Linear Representations of Finite Groups*, Springer GTM 42 (1977), Sections 5.3
  and 7.2.
-/

public section

namespace EpsilonEridani

variable {n : ℕ} [NeZero n]

/-- **The Frobenius kernel of a reflection subgroup of an odd dihedral group is the rotation
subgroup.** Frobenius's theorem builds a normal complement out of the trivial-intersection
property alone, and the rotation subgroup is a normal complement, so the two agree. -/
@[simp]
theorem frobeniusKernelSubgroup_zpowers_dihedralSr (hn : Odd n) (i : ZMod n) :
    frobeniusKernelSubgroup (isTISubgroup_zpowers_dihedralSr hn i) = dihedralRotations n :=
  frobeniusKernelSubgroup_eq_of_isComplement' _
    (isComplement'_dihedralRotations_zpowers_sr i)

/-- **The Frobenius kernel of an odd dihedral group has `n` elements**, the index of the
complement. -/
theorem card_frobeniusKernelSubgroup_zpowers_dihedralSr (hn : Odd n) (i : ZMod n) :
    Nat.card (frobeniusKernelSubgroup (isTISubgroup_zpowers_dihedralSr hn i)) = n := by
  rw [frobeniusKernelSubgroup_zpowers_dihedralSr hn i, card_dihedralRotations]

/-- The general divisibility `|H| ∣ |N| - 1` between a Frobenius complement and its kernel reads,
in this family, as `2 ∣ n - 1`. That is oddness again, so the general theorem is consistent with
the count computed here. -/
example (hn : Odd n) (i : ZMod n) : 2 ∣ n - 1 := by
  have h := card_dvd_card_frobeniusKernelSubgroup_sub_one (isTISubgroup_zpowers_dihedralSr hn i)
  rwa [Nat.card_zpowers, DihedralGroup.orderOf_sr,
    card_frobeniusKernelSubgroup_zpowers_dihedralSr hn i] at h

end EpsilonEridani
