/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.AlgebraicGeometry.EllipticCurve.Affine.FunctionField.GenericPoint
public import EpsilonEridani.AlgebraicGeometry.EllipticCurve.Isogeny.Basic
-- Proof-only, named in no statement here: the passage from an integral `x`-coordinate to an
-- integral `y`-coordinate along the Weierstrass equation.
import EpsilonEridani.AlgebraicGeometry.EllipticCurve.Integrality

/-!
# Pointedness is decided by the `x`-coordinate

`MapsInfinity` asks that every element of the source coordinate ring, read in the source function
field, be integral over the target coordinate ring acting through the pullback. That is a
condition on infinitely many elements, but it is equivalent to the single case of the generic
`x`-coordinate — one direction because that coordinate is one of them, the other because:

* the generic `y`-coordinate is then integral too, because the Weierstrass equation exhibits it
  as a root of a monic quadratic whose coefficients are polynomial in `x`;
* every element of the coordinate ring lies in the subalgebra generated by the two coordinates,
  and integrality is preserved by the ring operations.

So a construction that produces a coordinate pullback only has to exhibit one integral witness.

## Main results

* `EpsilonEridani.CoordinatePullback.mapsInfinity_iff_isIntegralElem_genericX`: a coordinate pullback
  maps infinity to infinity exactly when the generic `x`-coordinate is integral over it.

## Implementation notes

The hypothesis is stated with `RingHom.IsIntegralElem` against `p.toRingHom` rather than as
`IsIntegral W₂.CoordinateRing`, because for an endomorphism the source and target coordinate
rings coincide and `W₁.FunctionField` then carries two `Algebra W₂.CoordinateRing` structures —
the fraction-field embedding and the one pulled back along `p`. Naming the homomorphism leaves no
instance to be resolved.

## References

* [J. Silverman, *The Arithmetic of Elliptic Curves*][silverman2009], II.2.
-/

public section

open Polynomial WeierstrassCurve WeierstrassCurve.Affine

namespace EpsilonEridani

variable {F : Type*} [Field F] {W₁ W₂ : WeierstrassCurve.Affine F}

namespace CoordinatePullback

/-- **Pointedness is decided by the `x`-coordinate.** A coordinate pullback maps infinity to
infinity exactly when the generic `x`-coordinate of the source is integral over the target
coordinate ring acting through it, so a construction producing a coordinate pullback has to
exhibit one integral witness. -/
-- Deliberately not `@[simp]`: `CoordinatePullback.mapsInfinity_iff` already carries that attribute
-- and rewrites `MapsInfinity` to its quantified form, so this left-hand side is not in simp-normal
-- form and the `simpNF` linter rejects the pair.
theorem mapsInfinity_iff_isIntegralElem_genericX (p : CoordinatePullback W₁ W₂) :
    p.MapsInfinity ↔ RingHom.IsIntegralElem p.toRingHom W₁.genericX := by
  refine ⟨fun h => ?_, fun hx => ?_⟩
  · have hgen := (mapsInfinity_iff p).1 h (CoordinateRing.mk W₁ (C X))
    rwa [← W₁.genericX_def] at hgen
  rw [mapsInfinity_iff]
  let _ : Algebra W₂.CoordinateRing W₁.FunctionField := p.toRingHom.toAlgebra
  have halg : ∀ x : F, algebraMap F W₁.FunctionField x =
      algebraMap W₂.CoordinateRing W₁.FunctionField (algebraMap F W₂.CoordinateRing x) :=
    fun x ↦ (p.commutes x).symm
  have hmap : (algebraMap W₂.CoordinateRing W₁.FunctionField).comp
      (algebraMap F W₂.CoordinateRing) = algebraMap F W₁.FunctionField := by
    ext x; exact (halg x).symm
  have hgx : IsIntegral W₂.CoordinateRing W₁.genericX := hx
  have hgy : IsIntegral W₂.CoordinateRing W₁.genericY :=
    WeierstrassCurve.isIntegral_y_of_equation_of_isIntegral_x
      (W₁.map (algebraMap F W₂.CoordinateRing))
      (by
        simpa only [_root_.WeierstrassCurve.baseChange, _root_.WeierstrassCurve.map_map, hmap]
          using W₁.equation_genericX_genericY) hgx
  have hG : ∀ x ∈ Set.range (algebraMap F W₁.FunctionField) ∪
      ({W₁.genericX, W₁.genericY} : Set W₁.FunctionField),
      IsIntegral W₂.CoordinateRing x := by
    rintro x (⟨r, rfl⟩ | (rfl | rfl))
    · rw [halg r]; exact isIntegral_algebraMap
    · exact hgx
    · exact hgy
  intro z
  have hmem := W₁.algebraMap_mem_adjoin_genericX_genericY z
  rw [← Subalgebra.mem_toSubring, Algebra.adjoin_eq_ring_closure] at hmem
  exact IsIntegral.of_mem_closure'' _ hG _ hmem

end CoordinatePullback

end EpsilonEridani

end
