/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.AlgebraicGeometry.EllipticCurve.Affine.FunctionField.GenericPoint
public import EpsilonEridani.AlgebraicGeometry.EllipticCurve.Isogeny.Basic

/-!
# The tautological point of a coordinate pullback

A coordinate pullback `p : W₂.CoordinateRing →ₐ[F] W₁.FunctionField` — the data underlying an
isogeny `W₁ ⟶ W₂` — sends the two coordinate functions of `W₂` to elements of `F(W₁)`. The
Weierstrass relation is exactly what the coordinate ring quotients out, so the pair solves the
equation of `W₂` over `F(W₁)`, and on an elliptic target that solution is a point. A coordinate
pullback therefore cuts out a point of `W₂⁄F(W₁)`, its *tautological point*, and does so
injectively: evaluating the coordinate ring there recovers the pullback it came from.

The pointedness of an isogeny plays no part in any of this, so everything is stated for a bare
coordinate pullback; an isogeny `φ` uses `φ.pullback.tautologicalPoint`.

For the identity pullback this is the generic point of `W`, of which the construction here is the
pullback-indexed generalisation.

The construction is functorial in `F(W₁)`: post-composing a pullback with an algebra homomorphism
into the function field of any third curve is the same as moving its point by the induced map on
points. Combined with `tautologicalPoint_injective` that reflects equality, which is how a
fixed-field argument uses a pullback: the condition that a pullback is fixed by an endomorphism, a
condition on a whole coordinate ring, becomes one on the two coordinates of a point.

## Main definitions

* `EpsilonEridani.CoordinatePullback.tautologicalPoint`: the point of `W₂⁄F(W₁)` cut out by a coordinate
  pullback.

## Main results

* `EpsilonEridani.CoordinatePullback.tautologicalPoint_ne_zero`: it is an affine point, never the point
  at infinity.
* `EpsilonEridani.CoordinatePullback.evalAlgHom_tautologicalPoint`: evaluating the coordinate ring at it
  recovers the pullback.
* `EpsilonEridani.CoordinatePullback.tautologicalPoint_injective`: a pullback is determined by it.
* `EpsilonEridani.CoordinatePullback.tautologicalPoint_id`: the identity pullback's tautological point is
  the generic point.
* `EpsilonEridani.CoordinatePullback.tautologicalPoint_comp`: post-composition moves the point by the
  induced map on points.
-/

public section

open Polynomial WeierstrassCurve.Affine

open scoped Polynomial.Bivariate

namespace EpsilonEridani

open _root_.WeierstrassCurve.Affine

variable {F : Type*} [Field F] {W₁ W₂ : WeierstrassCurve.Affine F}

namespace CoordinatePullback

variable [W₂.IsElliptic]

/-- **The tautological point of a coordinate pullback**: the point of `W₂`, with coordinates in
the function field of `W₁`, cut out by the images of the coordinate functions of `W₂`. They solve
the equation of `W₂` because the Weierstrass polynomial is what the coordinate ring quotients
out. -/
noncomputable def tautologicalPoint (p : CoordinatePullback W₁ W₂) :
    (W₂⁄W₁.FunctionField).toAffine.Point :=
  Point.mk (CoordinateRing.equation_of_algHom p)

/-- **The tautological point is affine**, never the point at infinity. This is what lets consumers
use the coordinate API for nonzero points. -/
theorem tautologicalPoint_ne_zero (p : CoordinatePullback W₁ W₂) : p.tautologicalPoint ≠ 0 :=
  Point.some_ne_zero _

@[simp]
theorem xCoord_tautologicalPoint (p : CoordinatePullback W₁ W₂) :
    Point.xCoord p.tautologicalPoint = p (AdjoinRoot.of W₂.polynomial X) :=
  Point.xCoord_some _

@[simp]
theorem yCoord_tautologicalPoint (p : CoordinatePullback W₁ W₂) :
    Point.yCoord p.tautologicalPoint = p (AdjoinRoot.root W₂.polynomial) :=
  Point.yCoord_some _

-- Not `@[simp]`: the coordinate lemmas above already rewrite the point's coordinates back to the
-- pullback's values, so simp reaches this on its own. It is exported for consumers to name.
/-- **Evaluating the coordinate ring at the tautological point recovers the pullback.** This is
the elimination rule: it turns a statement about the point back into one about the pullback. -/
theorem evalAlgHom_tautologicalPoint (p : CoordinatePullback W₁ W₂) :
    CoordinateRing.evalAlgHom (Point.nonsingular_coords (tautologicalPoint_ne_zero p)).left = p :=
  CoordinateRing.algHom_ext
    (by rw [CoordinateRing.evalAlgHom_of_X, xCoord_tautologicalPoint])
    (by rw [CoordinateRing.evalAlgHom_root, yCoord_tautologicalPoint])

/-- **A coordinate pullback is determined by its tautological point.** The coordinate ring is
generated by its two coordinate functions, so a pullback is fixed by where it sends them. -/
theorem tautologicalPoint_injective :
    Function.Injective (tautologicalPoint (W₁ := W₁) (W₂ := W₂)) := fun p q h =>
  CoordinateRing.algHom_ext
    (by rw [← xCoord_tautologicalPoint, h, xCoord_tautologicalPoint])
    (by rw [← yCoord_tautologicalPoint, h, yCoord_tautologicalPoint])

/-- **The identity pullback's tautological point is the generic point**, of which this
construction is the pullback-indexed generalisation. -/
@[simp]
theorem tautologicalPoint_id (W : WeierstrassCurve.Affine F) [W.IsElliptic] :
    (CoordinatePullback.id W).tautologicalPoint = W.genericPoint := by
  rw [tautologicalPoint, genericPoint_eq_some]
  congr 1
  · rw [CoordinatePullback.id_apply, genericX_def, AdjoinRoot.mk_C]
  · rw [CoordinatePullback.id_apply, genericY_def, AdjoinRoot.mk_X]

/-- **Post-composing with an algebra homomorphism of function fields moves the tautological point
by the induced map on points.** Both sides are the affine point whose coordinates are the images of
the two coordinate functions, so a pullback's interaction with such a homomorphism is read off
entirely from its point. -/
@[simp]
theorem tautologicalPoint_comp {W₀ : WeierstrassCurve.Affine F} (p : CoordinatePullback W₁ W₂)
    (σ : W₁.FunctionField →ₐ[F] W₀.FunctionField) :
    tautologicalPoint (σ.comp p) = Point.map σ p.tautologicalPoint :=
  by
  rw [← Point.some_coords (tautologicalPoint_ne_zero p), Point.map_some,
    ← Point.some_coords (tautologicalPoint_ne_zero (σ.comp p))]
  simp only [xCoord_tautologicalPoint, yCoord_tautologicalPoint, AlgHom.comp_apply]

/-- **Two homomorphisms agreeing on the pullback's two coordinate values move the tautological
point to the same place.** The point's coordinates are those two values, so the induced map on
points cannot see anything else about the homomorphism. -/
theorem map_tautologicalPoint_eq_of_apply_eq {Ω : Type*} [Field Ω] [Algebra F Ω] [DecidableEq Ω]
    (p : CoordinatePullback W₁ W₂) (σ τ : W₁.FunctionField →ₐ[F] Ω)
    (hx : σ (p (AdjoinRoot.of W₂.polynomial X)) = τ (p (AdjoinRoot.of W₂.polynomial X)))
    (hy : σ (p (AdjoinRoot.root W₂.polynomial)) = τ (p (AdjoinRoot.root W₂.polynomial))) :
    Point.map σ p.tautologicalPoint = Point.map τ p.tautologicalPoint := by
  rw [← Point.some_coords (tautologicalPoint_ne_zero p), Point.map_some, Point.map_some,
    Point.some.injEq]
  simp only [xCoord_tautologicalPoint, yCoord_tautologicalPoint]
  exact ⟨hx, hy⟩

end CoordinatePullback

end EpsilonEridani

end
