/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.RepresentationTheory.Basic

/-!
# The monoid-algebra action of a representation

General facts about `Representation.asAlgebraHom`, the extension of a representation `ρ` of a
monoid `G` to the monoid algebra `k[G]`.

The first is the description of the image of a monoid-algebra lift: since `k[G]` is spanned by
`G`, its image is, as a submodule, the span of the image of the defining monoid homomorphism
(`MonoidAlgebra.toSubmodule_range_lift`). For a representation this identifies both the submodule
and the subalgebra generated by its image. This is what turns a statement about a monoid action
into a statement about the subalgebra of endomorphisms it generates, as a double-centralizer
theorem needs.

The second is a vanishing criterion. An element `a` of the monoid algebra `k[G]` acting through a
representation `ρ` kills a vector `v` when three conditions meet: doubling is injective on `V`,
some `g` fixes `v`, and right multiplication by `g` negates `a`. The last two make
`ρ.asAlgebraHom a v` its own negative, and injective doubling turns being its own negative into
vanishing.

That is the mechanism behind the column-antisymmetrizer vanishing arguments of
`EpsilonEridani/RepresentationTheory/Symmetric/`, which are its consumers: the antisymmetrizer of a set of
indices absorbs each permutation of those indices up to its sign, so against a vector fixed by an
odd such permutation the two conditions hold and the action is zero.

Nothing here is specific to symmetric groups or to `ℚ`. `G` is a monoid, and the module and the
scalars are arbitrary; nothing is asked of `2` in `k` at all: the hypothesis is that doubling is
injective on `V`, taken as an explicit assumption rather than read off the scalars. So this covers
torsion-free modules over `ℤ`, where `2` is not a unit, and equally modules over a ring with zero
divisors whose additive group has no `2`-torsion.

## Main results

* `MonoidAlgebra.toSubmodule_range_lift`: the image of a monoid-algebra lift is the span of the
  image of its defining monoid homomorphism.
* `Representation.range_asAlgebraHom_eq_adjoin`: the image of a representation's monoid-algebra
  action is the algebra generated by the representation.
* `Representation.mem_centralizer_range_asAlgebraHom_iff`: centralizing the monoid-algebra image
  is equivalent to commuting with every element of the monoid action.
* `Representation.commute_asAlgebraHom_of_forall_commute`: commuting with the monoid action
  propagates to the action of the monoid algebra.
* `Representation.asAlgebraHom_eq_zero_of_mul_single_eq_neg`: with doubling injective on `V`, an
  algebra element negated by right multiplication by an element fixing `v` annihilates `v`.
-/

public section

section Range

namespace MonoidAlgebra

variable {k G A : Type*} [CommSemiring k] [Monoid G] [Semiring A] [Algebra k A]

/-- **The image of a monoid-algebra lift is the span of the image of the monoid homomorphism.**
The monoid algebra `k[G]` is spanned by the elements of `G`, so an element of its image is a finite
`k`-combination of the elements `F g`, and conversely every `F g` lies in the image. -/
theorem toSubmodule_range_lift (F : G →* A) :
    Subalgebra.toSubmodule (MonoidAlgebra.lift k A G F).range =
      Submodule.span k (Set.range F) := by
  -- `k[G]` is spanned by `G`: each element lies in the span of its support
  -- (`MonoidAlgebra.mem_span_support_coeff`), a subset of the image of `MonoidAlgebra.of`
  have htop : Submodule.span k (Set.range ⇑(MonoidAlgebra.of k G)) = ⊤ :=
    eq_top_iff.2 fun a _ =>
      Submodule.span_mono (Set.image_subset_range _ _) (MonoidAlgebra.mem_span_support_coeff a)
  -- and `F` is the composite of `MonoidAlgebra.of` with the monoid-algebra lift
  have hrange : Set.range F = (MonoidAlgebra.lift k A G F).toLinearMap ''
      Set.range ⇑(MonoidAlgebra.of k G) := by
    rw [← Set.range_comp]
    simp [Function.comp_def]
  rw [hrange, ← Submodule.map_span, htop, Submodule.map_top]
  ext x
  simp [AlgHom.mem_range]

end MonoidAlgebra

namespace Representation

variable {k G V : Type*} [CommSemiring k] [Monoid G] [AddCommMonoid V] [Module k V]

/-- **The image of a representation's monoid-algebra action is the span of the representation.** -/
theorem toSubmodule_range_asAlgebraHom (ρ : Representation k G V) :
    Subalgebra.toSubmodule ρ.asAlgebraHom.range = Submodule.span k (Set.range ρ) := by
  simpa only [Representation.asAlgebraHom_def] using MonoidAlgebra.toSubmodule_range_lift ρ

/-- **The image of a representation's monoid-algebra action is the algebra generated by the
representation.** -/
theorem range_asAlgebraHom_eq_adjoin (ρ : Representation k G V) :
    ρ.asAlgebraHom.range = Algebra.adjoin k (Set.range ρ) := by
  apply le_antisymm
  · intro x hx
    have hx' : x ∈ Submodule.span k (Set.range ρ) := by
      rw [← toSubmodule_range_asAlgebraHom ρ]
      exact hx
    have hspan : Submodule.span k (Set.range ρ) ≤
        (Algebra.adjoin k (Set.range ρ)).toSubmodule :=
      Submodule.span_le.2 Algebra.subset_adjoin
    exact hspan hx'
  · exact Algebra.adjoin_le fun _ ⟨g, hg⟩ ↦ hg ▸
      ⟨MonoidAlgebra.of k G g, Representation.asAlgebraHom_of ρ g⟩

/-- If an endomorphism commutes with every operator in a representation, then it commutes with
the action of every element of the monoid algebra. -/
theorem commute_asAlgebraHom_of_forall_commute (ρ : Representation k G V) {x : Module.End k V}
    (h : ∀ g, Commute x (ρ g)) (a : MonoidAlgebra k G) : Commute x (ρ.asAlgebraHom a) := by
  refine Commute.span_right (R := k) (s := Set.range ρ) (fun y hy ↦ ?_) _ ?_
  · obtain ⟨g, rfl⟩ := hy
    exact h g
  · rw [← toSubmodule_range_asAlgebraHom ρ]
    exact ⟨a, rfl⟩

/-- An endomorphism centralizes the image of a representation's monoid-algebra action exactly
when it commutes with every operator in the representation. -/
theorem mem_centralizer_range_asAlgebraHom_iff (ρ : Representation k G V) {x : Module.End k V} :
    x ∈ Subalgebra.centralizer k (Set.range ⇑ρ.asAlgebraHom) ↔ ∀ g, Commute x (ρ g) := by
  rw [Subalgebra.mem_centralizer_iff]
  refine ⟨fun hx g ↦ (hx _ ⟨MonoidAlgebra.of k G g, Representation.asAlgebraHom_of ρ g⟩).symm,
    fun hx y hy ↦ ?_⟩
  obtain ⟨a, rfl⟩ := hy
  exact (commute_asAlgebraHom_of_forall_commute ρ hx a).symm

end Representation

end Range

namespace Representation

section Vanishing

variable {k G V : Type*} [CommRing k] [Monoid G] [AddCommGroup V] [Module k V]

/-- **An algebra element absorbed by a fixing element, up to sign, annihilates the vector.**
If doubling is injective on `V`, `g` fixes `v`, and right multiplication by `single g 1` negates
`a`, then `a` acts as zero on `v`. -/
theorem asAlgebraHom_eq_zero_of_mul_single_eq_neg
    (h2inj : Function.Injective fun w : V ↦ (2 : ℕ) • w)
    (ρ : Representation k G V) {a : MonoidAlgebra k G} {g : G} {v : V} (hfix : ρ g v = v)
    (hneg : a * MonoidAlgebra.single g 1 = -a) :
    ρ.asAlgebraHom a v = 0 := by
  -- Absorbing `g` into `a` costs a sign but leaves `v` alone, so the value equals its negation
  have key : ρ.asAlgebraHom a v = -(ρ.asAlgebraHom a v) := by
    conv_lhs => rw [← hfix]
    rw [← Representation.asAlgebraHom_single_one ρ, ← Module.End.mul_apply, ← map_mul, hneg,
      map_neg, LinearMap.neg_apply]
  -- so doubling it agrees with doubling `0`, and doubling is injective
  refine h2inj ?_
  simp only [two_nsmul, add_zero]
  nth_rewrite 1 [key]
  exact neg_add_cancel _

end Vanishing

end Representation
