/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.Algebra.AlgebraicGroup.Representation.Embedding
public import EpsilonEridani.Algebra.AlgebraicGroup.Representation.PointsAction
public import EpsilonEridani.Algebra.Coalgebra.Comodule.MatrixCoefficient.Dual
import EpsilonEridani.Algebra.Coalgebra.Comodule.PointSeparation

/-!
# Faithful representations and matrix coefficients

Let `M` be a finite free comodule over a commutative Hopf algebra `H`. A basis of `M` gives a
coordinate morphism

```text
O(GL(M)) ⟶ H.
```

This file identifies its range with the algebra generated by the matrix coefficients of `M` and
their antipode images. Equivalently, it is the coefficient algebra of `M × Mᵛ`, where `Mᵛ` is
the dual comodule. It follows that the associated morphism of affine group schemes is a closed
immersion exactly when those coefficients generate `H`.

The dual coefficients are essential. For the standard one-dimensional representation of
`𝔾ₘ`, the original coefficient is `T`, whereas the dual coefficient is `T⁻¹`; together they
generate `R[T, T⁻¹]`. Thus a criterion using only the original coefficient algebra would fail
even for the identity representation of `𝔾ₘ`.

This completes the ReductiveGroups roadmap's Layer 1 target "Faithfulness done right": faithful
means that the representation morphism is a closed immersion, and this geometric condition is
equivalent to generation of the coordinate ring by matrix coefficients and their duals.

## Main declarations

* `EpsilonEridani.Comodule.coordinateBialgHom_range`: the exact range of the coordinate morphism.
* `EpsilonEridani.Comodule.IsFaithful`: the basis-independent predicate for a faithful comodule.
* `EpsilonEridani.Comodule.isFaithful_iff_matrixCoefficientSubalgebra_sup_antipode_eq_top`: the
  matrix-coefficient criterion for faithfulness.
* `EpsilonEridani.Comodule.isFaithful_corestrict_of_surjective`: corestriction along a surjective
  bialgebra morphism preserves faithfulness.
* `EpsilonEridani.Comodule.pointsAction_injective_of_isFaithful`: a faithful comodule separates
  algebra-valued points.
* `EpsilonEridani.Comodule.isClosedImmersion_coordinateGroupSchemeHom_iff_of_bases`: faithfulness is
  independent of the chosen finite basis.

## References

* J. S. Milne, *Algebraic Groups* (2017), Remark 4.1 and Theorems 4.9 and 4.14.
-/

public section

open Module

namespace EpsilonEridani.Comodule

universe u v w x

noncomputable section

variable {R : Type u} {H : Type v} {M : Type w} {n : ℕ}
variable [CommRing R] [CommRing H] [HopfAlgebra R H]
variable [AddCommMonoid M] [Module R M] [Comodule R H M]

/-- The algebra generated by a comodule's matrix coefficients and their antipode images. -/
private abbrev faithfulCoefficientAlgebra : Subalgebra R H :=
  matrixCoefficientSubalgebra (R := R) (C := H) (M := M) ⊔
    (matrixCoefficientSubalgebra (R := R) (C := H) (M := M)).map
      (HopfAlgebra.antipodeAlgHom R H)

/-- The coordinate morphism carries a matrix-coordinate generator into the algebra generated by the
comodule's matrix coefficients and their antipode images. -/
private theorem coordinateBialgHom_X_mem_faithfulCoefficientAlgebra
    (b : Basis (Fin n) R M) (i j : Fin n) :
    coordinateBialgHom (H := H) b
        (GeneralLinear.coordinateHopfAlgebraAlgEquiv R n
          (GeneralLinear.coordinateRingMap R n (MvPolynomial.X (i, j)))) ∈
      faithfulCoefficientAlgebra (R := R) (H := H) (M := M) := by
  -- the generator's image is the matrix coefficient at `(i, j)`, which is a generator of the
  -- left summand
  rw [coordinateBialgHom_X, coefficientMatrix_apply]
  exact Algebra.mem_sup_left
    (matrixCoefficient_mem_subalgebra (R := R) (C := H) (b.coord i) (b j))

/-- The coordinate morphism carries the antipode of a matrix-coordinate generator into that same
algebra. -/
private theorem coordinateBialgHom_antipode_X_mem_faithfulCoefficientAlgebra
    (b : Basis (Fin n) R M) (i j : Fin n) :
    coordinateBialgHom (H := H) b
        (HopfAlgebra.antipode R
          (GeneralLinear.coordinateHopfAlgebraAlgEquiv R n
            (GeneralLinear.coordinateRingMap R n (MvPolynomial.X (i, j))))) ∈
      faithfulCoefficientAlgebra (R := R) (H := H) (M := M) := by
  -- the antipode generator is an entry of the inverse generic matrix, whose image is the
  -- antipode of the matrix coefficient at `(i, j)` — a generator of the right summand
  rw [GeneralLinear.coordinateHopfAlgebra_antipode_X, coordinateBialgHom_antipode_X,
    coefficientMatrix_apply]
  apply Algebra.mem_sup_right
  exact ⟨matrixCoefficient (R := R) (C := H) (b.coord i) (b j),
    matrixCoefficient_mem_subalgebra (R := R) (C := H) (b.coord i) (b j),
    HopfAlgebra.antipodeAlgHom_apply R H _⟩

/-- The range of the coordinate morphism is contained in the algebra generated by the matrix
coefficients of the comodule and their antipode images. -/
private theorem coordinateBialgHom_range_le_faithfulCoefficientAlgebra
    (b : Basis (Fin n) R M) :
    (coordinateBialgHom (H := H) b).toAlgHom.range ≤
      faithfulCoefficientAlgebra (R := R) (H := H) (M := M) := by
  let f := (coordinateBialgHom (H := H) b).toAlgHom
  have htop : (⊤ : Subalgebra R (GeneralLinear.coordinateHopfAlgebra R n)) ≤
      (faithfulCoefficientAlgebra (R := R) (H := H) (M := M)).comap f := by
    -- rewriting `⊤` as the adjoin of the generators produces the generating set, so it need not be
    -- written out; the resulting membership goal then unfolds to the two lemmas above, which are
    -- stated for the bundled bialgebra morphism rather than its algebra-hom coercion
    rw [← GeneralLinear.adjoin_coordinateHopfAlgebra_X_union_antipode_X, Algebra.adjoin_le_iff]
    rintro x (⟨⟨i, j⟩, rfl⟩ | ⟨⟨i, j⟩, rfl⟩)
    · exact coordinateBialgHom_X_mem_faithfulCoefficientAlgebra b i j
    · exact coordinateBialgHom_antipode_X_mem_faithfulCoefficientAlgebra b i j
  intro y hy
  rcases hy with ⟨x, rfl⟩
  exact htop (Set.mem_univ x)

/-- The antipode image of the matrix coefficient algebra lies in the range of the coordinate
morphism. This is the inverse-coordinate half of the range calculation. -/
private theorem map_antipode_matrixCoefficientSubalgebra_le_coordinateBialgHom_range
    (b : Basis (Fin n) R M) :
    (matrixCoefficientSubalgebra (R := R) (C := H) (M := M)).map
        (HopfAlgebra.antipodeAlgHom R H) ≤
      (coordinateBialgHom (H := H) b).toAlgHom.range := by
  rintro y ⟨x, hx, rfl⟩
  rcases matrixCoefficientSubalgebra_le_coordinateBialgHom_range b hx with ⟨z, rfl⟩
  refine ⟨HopfAlgebra.antipode R z, ?_⟩
  -- Membership in an algebra-hom range leaves algebra-hom coercions in the goal; expose the
  -- bialgebra morphism so `map_antipode` applies.
  change coordinateBialgHom (H := H) b (HopfAlgebra.antipode R z) =
    HopfAlgebra.antipodeAlgHom R H (coordinateBialgHom (H := H) b z)
  rw [HopfAlgebra.antipodeAlgHom_apply, BialgHomClass.map_antipode]

/-- **The range of a comodule's coordinate morphism is generated by its coefficients and their
antipode images.**

The first summand records the images of the generic matrix entries of `O(GLₙ)`; the second
records the images of the inverse-matrix entries. -/
theorem coordinateBialgHom_range (b : Basis (Fin n) R M) :
    (coordinateBialgHom (H := H) b).toAlgHom.range =
      matrixCoefficientSubalgebra (R := R) (C := H) (M := M) ⊔
        (matrixCoefficientSubalgebra (R := R) (C := H) (M := M)).map
          (HopfAlgebra.antipodeAlgHom R H) := by
  apply le_antisymm
  · exact coordinateBialgHom_range_le_faithfulCoefficientAlgebra b
  · apply sup_le
    · exact matrixCoefficientSubalgebra_le_coordinateBialgHom_range b
    · exact map_antipode_matrixCoefficientSubalgebra_le_coordinateBialgHom_range b

/-- The coordinate morphism is surjective exactly when the matrix coefficients and their
antipode images generate the coordinate Hopf algebra. -/
theorem coordinateBialgHom_surjective_iff_matrixCoefficientSubalgebra_sup_antipode_eq_top
    (b : Basis (Fin n) R M) :
    Function.Surjective (coordinateBialgHom (H := H) b) ↔
      matrixCoefficientSubalgebra (R := R) (C := H) (M := M) ⊔
        (matrixCoefficientSubalgebra (R := R) (C := H) (M := M)).map
          (HopfAlgebra.antipodeAlgHom R H) = ⊤ := by
  -- `AlgHom.range_eq_top` is stated for the algebra-hom coercion of the coordinate morphism.
  change Function.Surjective (coordinateBialgHom (H := H) b).toAlgHom ↔ _
  rw [← AlgHom.range_eq_top, coordinateBialgHom_range]

section Dual

attribute [local instance] dual Prod

/-- The range of a comodule's coordinate morphism is equivalently the coefficient algebra of
the direct sum of the comodule and its dual. -/
theorem coordinateBialgHom_range_eq_matrixCoefficientSubalgebra_prod_dual
    (b : Basis (Fin n) R M) :
    letI : Module.Finite R M := Module.Finite.of_basis b
    letI : Module.Free R M := Module.Free.of_basis b
    letI : Module.Projective R M := inferInstance
    (coordinateBialgHom (H := H) b).toAlgHom.range =
      matrixCoefficientSubalgebra (R := R) (C := H)
        (M := M × Module.Dual R M) := by
  let : Module.Finite R M := Module.Finite.of_basis b
  let : Module.Free R M := Module.Free.of_basis b
  let : Module.Projective R M := inferInstance
  rw [coordinateBialgHom_range, matrixCoefficientSubalgebra_prod_dual]

/-- The coordinate morphism is surjective exactly when the coefficients of the comodule and its
dual generate the coordinate Hopf algebra. This is the rigid-category form of the
matrix-coefficient-and-antipode criterion above. -/
theorem coordinateBialgHom_surjective_iff_matrixCoefficientSubalgebra_prod_dual_eq_top
    (b : Basis (Fin n) R M) :
    letI : Module.Finite R M := Module.Finite.of_basis b
    letI : Module.Free R M := Module.Free.of_basis b
    letI : Module.Projective R M := inferInstance
    Function.Surjective (coordinateBialgHom (H := H) b) ↔
      matrixCoefficientSubalgebra (R := R) (C := H)
        (M := M × Module.Dual R M) = ⊤ := by
  let : Module.Finite R M := Module.Finite.of_basis b
  let : Module.Free R M := Module.Free.of_basis b
  let : Module.Projective R M := inferInstance
  -- As above, pass from the bialgebra morphism to its algebra-hom range.
  change Function.Surjective (coordinateBialgHom (H := H) b).toAlgHom ↔ _
  rw [← AlgHom.range_eq_top,
    coordinateBialgHom_range_eq_matrixCoefficientSubalgebra_prod_dual b]

end Dual

section GroupScheme

open AlgebraicGeometry

variable {k H V : Type u} {d : ℕ}
variable [CommRing k] [CommRing H] [HopfAlgebra k H]
variable [AddCommMonoid V] [Module k V] [Comodule k H V]

/-- A comodule is faithful if its representation morphism into a general linear group is a
closed immersion for some finite basis. This property is independent of the witnessing basis. -/
def IsFaithful : Prop :=
  ∃ (d : ℕ) (b : Basis (Fin d) k V),
    IsClosedImmersion (coordinateGroupSchemeHom (H := H) b).hom.hom.left

/-- Faithfulness restated as the existence of a finite basis whose representation morphism is a
closed immersion. -/
theorem isFaithful_def :
    IsFaithful (k := k) (H := H) (V := V) ↔
      ∃ (d : ℕ) (b : Basis (Fin d) k V),
        IsClosedImmersion (coordinateGroupSchemeHom (H := H) b).hom.hom.left :=
  Iff.rfl

/-- **Faithfulness is generation by matrix coefficients.** The affine group-scheme morphism
associated to a finite free comodule is a closed immersion if and only if the coefficients of
the comodule together with their antipode images generate the coordinate Hopf algebra. -/
theorem
    isClosedImmersion_coordinateGroupSchemeHom_iff_matrixCoefficientSubalgebra_sup_antipode_eq_top
    (b : Basis (Fin d) k V) :
    IsClosedImmersion (coordinateGroupSchemeHom (H := H) b).hom.hom.left ↔
      matrixCoefficientSubalgebra (R := k) (C := H) (M := V) ⊔
        (matrixCoefficientSubalgebra (R := k) (C := H) (M := V)).map
          (HopfAlgebra.antipodeAlgHom k H) = ⊤ := by
  rw [isClosedImmersion_coordinateGroupSchemeHom_iff,
    coordinateBialgHom_surjective_iff_matrixCoefficientSubalgebra_sup_antipode_eq_top]

/-- Whether a finite free comodule defines a closed immersion into a general linear group is
independent of the chosen basis. The two target general linear groups may use different finite
index types; the matrix-coefficient criterion is basis-free. -/
theorem isClosedImmersion_coordinateGroupSchemeHom_iff_of_bases
    {e : ℕ} (b : Basis (Fin d) k V) (c : Basis (Fin e) k V) :
    IsClosedImmersion (coordinateGroupSchemeHom (H := H) b).hom.hom.left ↔
      IsClosedImmersion (coordinateGroupSchemeHom (H := H) c).hom.hom.left := by
  rw [
    isClosedImmersion_coordinateGroupSchemeHom_iff_matrixCoefficientSubalgebra_sup_antipode_eq_top,
    isClosedImmersion_coordinateGroupSchemeHom_iff_matrixCoefficientSubalgebra_sup_antipode_eq_top]

/-- A finite basis witnesses faithfulness exactly when its coordinate group-scheme morphism is a
closed immersion. -/
theorem isFaithful_iff_isClosedImmersion_coordinateGroupSchemeHom
    (b : Basis (Fin d) k V) :
    IsFaithful (k := k) (H := H) (V := V) ↔
      IsClosedImmersion (coordinateGroupSchemeHom (H := H) b).hom.hom.left := by
  constructor
  · rintro ⟨e, c, hc⟩
    exact (isClosedImmersion_coordinateGroupSchemeHom_iff_of_bases c b).mp hc
  · intro hb
    exact ⟨d, b, hb⟩

/-- Corestricting a faithful finite free comodule along a surjective bialgebra morphism gives a
faithful comodule over the codomain. Geometrically, restricting a faithful representation to a
closed subgroup remains faithful. -/
theorem isFaithful_corestrict_of_surjective
    {K : Type u} [CommRing K] [HopfAlgebra k K]
    (f : H →ₐc[k] K) (hf : Function.Surjective f)
    (hV : IsFaithful (k := k) (H := H) (V := V)) :
    letI : Comodule k K V := Corestrict f.toCoalgHom
    IsFaithful (k := k) (H := K) (V := V) := by
  rcases isFaithful_def.mp hV with ⟨d, b, hb⟩
  let _ : Comodule k K V := Corestrict f.toCoalgHom
  have hsurj : Function.Surjective (coordinateBialgHom (H := H) b) := by
    rw [← isClosedImmersion_coordinateGroupSchemeHom_iff]
    exact hb
  rw [isFaithful_iff_isClosedImmersion_coordinateGroupSchemeHom (b := b),
    isClosedImmersion_coordinateGroupSchemeHom_iff, coordinateBialgHom_corestrict f b]
  exact hf.comp hsurj

/-- A finite free comodule is faithful exactly when its matrix coefficients together with their
antipode images generate the coordinate Hopf algebra. -/
theorem isFaithful_iff_matrixCoefficientSubalgebra_sup_antipode_eq_top
    (b : Basis (Fin d) k V) :
    IsFaithful (k := k) (H := H) (V := V) ↔
      matrixCoefficientSubalgebra (R := k) (C := H) (M := V) ⊔
        (matrixCoefficientSubalgebra (R := k) (C := H) (M := V)).map
          (HopfAlgebra.antipodeAlgHom k H) = ⊤ := by
  rw [isFaithful_iff_isClosedImmersion_coordinateGroupSchemeHom (b := b),
    isClosedImmersion_coordinateGroupSchemeHom_iff_matrixCoefficientSubalgebra_sup_antipode_eq_top]

/-- A faithful comodule separates algebra-valued points. -/
theorem pointsAction_injective_of_isFaithful
    {K : Type x} [CommRing K] [Algebra k K]
    (hV : IsFaithful (k := k) (H := H) (V := V)) :
    Function.Injective (pointsAction (R := k) (H := H) (A := K) V) := by
  intro g h haction
  have hEnd : endOfPoint V g.ofConv = endOfPoint V h.ofConv := by
    simpa only [pointsAction_toLinearMap] using congrArg LinearEquiv.toLinearMap haction
  have hInvAction : pointsAction V g⁻¹ = pointsAction V h⁻¹ := by
    simpa only [map_inv] using congrArg Inv.inv haction
  have hInvEnd : endOfPoint V (g⁻¹).ofConv = endOfPoint V (h⁻¹).ofConv := by
    simpa only [pointsAction_toLinearMap] using congrArg LinearEquiv.toLinearMap hInvAction
  have hCoefficients :
      Set.EqOn g.ofConv h.ofConv
        (matrixCoefficientSubalgebra (R := k) (C := H) (M := V)) :=
    eqOn_matrixCoefficientSubalgebra_of_endOfPoint_eq _ _ hEnd
  have hInvCoefficients :
      Set.EqOn (g⁻¹).ofConv (h⁻¹).ofConv
        (matrixCoefficientSubalgebra (R := k) (C := H) (M := V)) :=
    eqOn_matrixCoefficientSubalgebra_of_endOfPoint_eq _ _ hInvEnd
  have hAntipodeCoefficients :
      Set.EqOn g.ofConv h.ofConv
        ((matrixCoefficientSubalgebra (R := k) (C := H) (M := V)).map
          (HopfAlgebra.antipodeAlgHom k H)) := by
    rintro y ⟨x, hx, rfl⟩
    -- A `Subalgebra.map` witness retains the coerced `antipodeAlgHom` application at the
    -- current Mathlib pin, so expose its definition before applying the convolution-inverse API.
    change g.ofConv (HopfAlgebraStruct.antipode k x) =
      h.ofConv (HopfAlgebraStruct.antipode k x)
    simpa only [← AlgHom.convInv_apply] using hInvCoefficients hx
  rcases hV with ⟨d, b, hb⟩
  have hgenerate :
      matrixCoefficientSubalgebra (R := k) (C := H) (M := V) ⊔
          (matrixCoefficientSubalgebra (R := k) (C := H) (M := V)).map
            (HopfAlgebra.antipodeAlgHom k H) = ⊤ :=
    (isFaithful_iff_matrixCoefficientSubalgebra_sup_antipode_eq_top b).mp ⟨d, b, hb⟩
  exact WithConv.ofConv_injective
    (AlgHom.ext_on_codisjoint (codisjoint_iff.mpr hgenerate)
      hCoefficients hAntipodeCoefficients)

section Dual

attribute [local instance] dual Prod

/-- In a finite free comodule, the faithful-representation criterion can be read as
generation by the coefficients of the comodule together with its dual. -/
theorem isFaithful_iff_matrixCoefficientSubalgebra_prod_dual_eq_top
    (b : Basis (Fin d) k V) :
    letI : Module.Finite k V := Module.Finite.of_basis b
    letI : Module.Free k V := Module.Free.of_basis b
    letI : Module.Projective k V := inferInstance
    IsFaithful (k := k) (H := H) (V := V) ↔
      matrixCoefficientSubalgebra (R := k) (C := H)
        (M := V × Module.Dual k V) = ⊤ := by
  let : Module.Finite k V := Module.Finite.of_basis b
  let : Module.Free k V := Module.Free.of_basis b
  let : Module.Projective k V := inferInstance
  rw [isFaithful_iff_isClosedImmersion_coordinateGroupSchemeHom (b := b),
    isClosedImmersion_coordinateGroupSchemeHom_iff,
    coordinateBialgHom_surjective_iff_matrixCoefficientSubalgebra_prod_dual_eq_top]

end Dual

end GroupScheme

end


end EpsilonEridani.Comodule
