/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.Algebra.AlgebraicGroup.HopfIdeal.Equalizer
public import EpsilonEridani.Algebra.AlgebraicGroup.HopfIdeal.Scheme.Basic

/-!
# Endomorphisms of a subgroup scheme generated by a family of morphisms

Let `f i : H ⟶ K i` be morphisms of commutative Hopf algebras and let `𝔞` be their common-kernel
Hopf ideal, the largest Hopf ideal of `H` killed by all of them. Contravariantly, `Spec (H ⧸ 𝔞)`
is the closed subgroup scheme of `Spec H` generated by the images of the `Spec (K i)`, and a
morphism of commutative Hopf algebras `ψ : H ⟶ H ⧸ 𝔞` is a homomorphism from that subgroup scheme
to `Spec H`.

Such a homomorphism maps the generated subgroup scheme into itself exactly when `ψ` is killed by
`𝔞`, and this file reduces that condition to the generators: it suffices that each composite of
`ψ` with a factored generator is killed by `𝔞`, which holds as soon as each generator is carried
into some generator.

The reduction is the two-sided argument for `𝔞`. The image Hopf ideal `ψ(𝔞)` of `H ⧸ 𝔞` pulls
back along the quotient morphism to a Hopf ideal of `H` containing `𝔞`; the generator equations
make every `f i` kill that pullback, so it is contained in `𝔞` because `𝔞` is the largest Hopf
ideal with that property. The pullback is therefore `𝔞` itself, and `ψ(𝔞)` is zero.
Contravariantly: the preimage of the generated subgroup scheme under the homomorphism is a closed
subgroup scheme containing every generator, hence the whole of it.

From that containment the homomorphism factors through the generated subgroup scheme, giving an
endomorphism of it as a group scheme. Two such endomorphisms whose coordinate morphisms agree on
the generators are equal, by rigidity.

Nothing here asserts that such an endomorphism is an isogeny, surjective, or flat.

## Main results

In the namespace `EpsilonEridani.CommHopfAlgCat`:

* `commonKernelHopfIdeal_toIdeal_le_ker_of_comp_commonKernelLift` and
  `commonKernelHopfIdeal_toIdeal_le_ker_of_comp_eq`:
  the coordinate morphism is killed by the common-kernel ideal, from kernel containments and from
  generator equations respectively.
* `commonKernelSpecRestrict`, `commonKernelSpecRestrict_comp_quotientSpecι` and
  `commonKernelSpecRestrict_eq_of_comp_eq`: the resulting endomorphism of the generated subgroup
  scheme, its compatibility with the closed immersion, and its determination by the generators.

## References

* R. W. Carter, *Simple Groups of Lie Type*, §§7.1 and 12.2, for endomorphisms of a Chevalley
  group determined by their effect on the root subgroups and the torus.
* J. E. Humphreys, *Linear Algebraic Groups*, §27.
* J. C. Jantzen, *Representations of Algebraic Groups*, I.2, for the Hopf-ideal dictionary used
  in the reduction.
-/

public section

open AlgebraicGeometry CategoryTheory

namespace EpsilonEridani.CommHopfAlgCat

universe u v w

variable {R : Type u} [CommRing R]
variable {H : _root_.CommHopfAlgCat.{v} R}
variable {ι : Type w} {K : ι → _root_.CommHopfAlgCat.{v} R}
variable (f : ∀ i, H ⟶ K i)

/-- A member of the generating family kills the pullback of the image Hopf ideal of a morphism
into the common-kernel quotient, as soon as the corresponding composite is killed. -/
private theorem comp_eq_zero_of_le_ker {Y : _root_.CommHopfAlgCat.{v} R}
    (ψ : H ⟶ quotient H (commonKernelHopfIdeal f))
    (χ : quotient H (commonKernelHopfIdeal f) ⟶ Y)
    (hχ : (commonKernelHopfIdeal f).toIdeal ≤ RingHom.ker (ψ ≫ χ).hom.toAlgHom.toRingHom)
    {x : H}
    (hx : x ∈ HopfIdeal.comapOfSurjective
      (HopfIdeal.map (commonKernelHopfIdeal f) ψ.hom)
      (mkQuotient H (commonKernelHopfIdeal f)).hom
      (mkQuotient_surjective _ _)) :
    χ.hom ((mkQuotient H (commonKernelHopfIdeal f)).hom x) = 0 := by
  have hmem := HopfIdeal.mem_comapOfSurjective.1 hx
  rw [← HopfIdeal.mem_toIdeal, HopfIdeal.map_toIdeal] at hmem
  have hle : Ideal.map (ψ.hom : _ →+* _) (commonKernelHopfIdeal f).toIdeal ≤
      RingHom.ker (χ.hom.toAlgHom.toRingHom) := by
    rw [Ideal.map_le_iff_le_comap]
    intro y hy
    rw [Ideal.mem_comap, RingHom.mem_ker]
    have hy' := hχ hy
    rw [RingHom.mem_ker] at hy'
    simpa only [_root_.CommHopfAlgCat.comp_apply, BialgHom.coe_toAlgHom,
        AlgHom.toRingHom_eq_coe, RingHom.coe_coe] using hy'
  exact RingHom.mem_ker.1 (hle hmem)

/-- **A morphism into the common-kernel quotient whose composites with the factored generators
are killed by the common-kernel ideal is itself killed by it.** Contravariantly, a homomorphism
from the generated closed subgroup scheme to the ambient one which carries every generating
subgroup back into it maps the whole subgroup scheme into it. -/
theorem commonKernelHopfIdeal_toIdeal_le_ker_of_comp_commonKernelLift
    (ψ : H ⟶ quotient H (commonKernelHopfIdeal f))
    (hgen : ∀ i, (commonKernelHopfIdeal f).toIdeal ≤
      RingHom.ker (ψ ≫ commonKernelLift f i).hom.toAlgHom.toRingHom) :
    (commonKernelHopfIdeal f).toIdeal ≤ RingHom.ker ψ.hom.toAlgHom.toRingHom := by
  have hbot : HopfIdeal.map (commonKernelHopfIdeal f) ψ.hom = ⊥ := by
    refine eq_bot_of_comapOfSurjective_le _ ?_
    rw [le_commonKernelHopfIdeal_iff]
    intro i x hx
    rw [RingHom.mem_ker]
    simp only [BialgHom.coe_toAlgHom, AlgHom.toRingHom_eq_coe, RingHom.coe_coe]
    rw [← mkQuotient_comp_commonKernelLift f i, _root_.CommHopfAlgCat.comp_apply]
    exact comp_eq_zero_of_le_ker f ψ _ (hgen i) hx
  intro x hx
  have hker := (HopfIdeal.map_eq_bot_iff _ ψ.hom).1 hbot hx
  rw [RingHom.mem_ker] at hker ⊢
  exact hker

/-- **The generator form of the previous criterion.** A morphism into the common-kernel quotient
whose composite with the `i`th factored generator is the `s i`th generator followed by a morphism
`m i` of the codomains is killed by the common-kernel ideal.

Contravariantly, this is a homomorphism from the generated subgroup scheme to the ambient one
which sends the `i`th generating subgroup into the `s i`th one. -/
theorem commonKernelHopfIdeal_toIdeal_le_ker_of_comp_eq
    (ψ : H ⟶ quotient H (commonKernelHopfIdeal f)) (s : ι → ι) (m : ∀ i, K (s i) ⟶ K i)
    (hgen : ∀ i, ψ ≫ commonKernelLift f i = f (s i) ≫ m i) :
    (commonKernelHopfIdeal f).toIdeal ≤ RingHom.ker ψ.hom.toAlgHom.toRingHom := by
  refine commonKernelHopfIdeal_toIdeal_le_ker_of_comp_commonKernelLift f ψ fun i x hx => ?_
  rw [RingHom.mem_ker]
  simp only [BialgHom.coe_toAlgHom, AlgHom.toRingHom_eq_coe, RingHom.coe_coe]
  rw [hgen i, _root_.CommHopfAlgCat.comp_apply]
  have hzero := commonKernelHopfIdeal_toIdeal_le_ker f (s i) hx
  rw [RingHom.mem_ker] at hzero
  simp only [BialgHom.coe_toAlgHom, AlgHom.toRingHom_eq_coe, RingHom.coe_coe] at hzero
  rw [hzero, map_zero]

/-! ### The restricted endomorphism -/

variable {f}

/-- **The endomorphism of a generated closed subgroup scheme restricting a homomorphism into the
ambient group scheme** which maps it into itself: the spectrum of the factorization of the
coordinate morphism `ψ` through the common-kernel quotient. -/
noncomputable def commonKernelSpecRestrict {H : _root_.CommHopfAlgCat.{u} R}
    {K : ι → _root_.CommHopfAlgCat.{u} R} {f : ∀ i, H ⟶ K i}
    (ψ : H ⟶ quotient H (commonKernelHopfIdeal f))
    (hψ : (commonKernelHopfIdeal f).toIdeal ≤ RingHom.ker ψ.hom.toAlgHom.toRingHom) :
    quotientSpec H (commonKernelHopfIdeal f) ⟶ quotientSpec H (commonKernelHopfIdeal f) :=
  (hopfSpec (CommRingCat.of R)).map (liftQuotient (commonKernelHopfIdeal f) ψ hψ).op

/-- The restricted endomorphism is the spectrum of the quotient factorization. -/
theorem commonKernelSpecRestrict_def {H : _root_.CommHopfAlgCat.{u} R}
    {K : ι → _root_.CommHopfAlgCat.{u} R} {f : ∀ i, H ⟶ K i}
    (ψ : H ⟶ quotient H (commonKernelHopfIdeal f))
    (hψ : (commonKernelHopfIdeal f).toIdeal ≤ RingHom.ker ψ.hom.toAlgHom.toRingHom) :
    commonKernelSpecRestrict ψ hψ =
      (hopfSpec (CommRingCat.of R)).map (liftQuotient (commonKernelHopfIdeal f) ψ hψ).op := by
  rw [commonKernelSpecRestrict]

/-- Following the restricted endomorphism by the closed immersion into the ambient group scheme
recovers the original homomorphism. -/
@[simp]
theorem commonKernelSpecRestrict_comp_quotientSpecι {H : _root_.CommHopfAlgCat.{u} R}
    {K : ι → _root_.CommHopfAlgCat.{u} R} {f : ∀ i, H ⟶ K i}
    (ψ : H ⟶ quotient H (commonKernelHopfIdeal f))
    (hψ : (commonKernelHopfIdeal f).toIdeal ≤ RingHom.ker ψ.hom.toAlgHom.toRingHom) :
    commonKernelSpecRestrict ψ hψ ≫ quotientSpecι H (commonKernelHopfIdeal f) =
      (hopfSpec (CommRingCat.of R)).map ψ.op := by
  rw [commonKernelSpecRestrict_def, quotientSpecι_def, ← Functor.map_comp, ← op_comp,
    mkQuotient_comp_liftQuotient]

/-- **Two restricted endomorphisms agreeing on the generators agree.** The coordinate morphisms
are determined by their composites with the factored generators, so the endomorphisms they
restrict to are equal. -/
theorem commonKernelSpecRestrict_eq_of_comp_eq {H : _root_.CommHopfAlgCat.{u} R}
    {K : ι → _root_.CommHopfAlgCat.{u} R} {f : ∀ i, H ⟶ K i}
    (ψ ψ' : H ⟶ quotient H (commonKernelHopfIdeal f))
    (hψ : (commonKernelHopfIdeal f).toIdeal ≤ RingHom.ker ψ.hom.toAlgHom.toRingHom)
    (hψ' : (commonKernelHopfIdeal f).toIdeal ≤ RingHom.ker ψ'.hom.toAlgHom.toRingHom)
    (hgen : ∀ i, ψ ≫ commonKernelLift f i = ψ' ≫ commonKernelLift f i) :
    commonKernelSpecRestrict ψ hψ = commonKernelSpecRestrict ψ' hψ' := by
  have heq : ψ = ψ' := commonKernelLift_hom_ext f ψ ψ' hgen
  subst heq
  rfl

end EpsilonEridani.CommHopfAlgCat
