/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.Algebra.Lie.F4.ModularLattice

/-!
# The modular short-root coordinate space in type F₄

In the full integral F₄ Chevalley lattice reduced modulo two, the distinguished coordinate
subspace is spanned by the twenty-four short-root vectors and the
two short simple coroots.

The subspace is defined only after reduction modulo two. Its integral coordinate span is not a Lie
ideal: a short--short bracket can be twice a long-root vector.

This is the full integral Chevalley lattice reduced modulo two. In this characteristic it must
not be replaced by the Lie algebra generated by the reductions of the simple generators: taking
the generated image and reducing the full integral lattice need not commute.

## Main declaration

* `EpsilonEridani.DynkinType.f4ShortRootLieIdeal`: the characteristic-two short-root ideal of the reduced
  integral Chevalley algebra, used in the construction of the F₄ special isogeny.

## References

* R. Steinberg, *Endomorphisms of linear algebraic groups*, Memoirs AMS 80 (1968), §11.
* R. W. Carter, *Simple Groups of Lie Type*, §12.3.
-/

public section

namespace EpsilonEridani.DynkinType

open _root_.LieAlgebra _root_.LieAlgebra.IsKilling LieModule Module Set
open scoped TensorProduct

noncomputable section

/-- A Chevalley coordinate is short when it is labelled by a short root or by one of the two
short simple coroots. -/
def F4ChevalleyIndexIsShort : f4ChevalleyIndex → Prop :=
  Sum.elim (fun α => f4Length (f4PinnedRootIndex α) = 1)
    (fun j => f4PinnedSimpleIndexEquiv j = 2 ∨ f4PinnedSimpleIndexEquiv j = 3)

@[simp] theorem f4ChevalleyIndexIsShort_inl_iff
    (α : (F4.cartanSubalgebra valid_F4).root) :
    F4ChevalleyIndexIsShort (Sum.inl α) ↔
      f4Length (f4PinnedRootIndex α) = 1 := Iff.rfl

@[simp] theorem f4ChevalleyIndexIsShort_inr_iff (j : f4KillingBase.support) :
    F4ChevalleyIndexIsShort (Sum.inr j) ↔
      f4PinnedSimpleIndexEquiv j = 2 ∨ f4PinnedSimpleIndexEquiv j = 3 := Iff.rfl

/-- The coordinate labels spanning the modular short-root space. -/
def f4ShortChevalleyIndices : Set f4ChevalleyIndex :=
  {i | F4ChevalleyIndexIsShort i}

@[simp] theorem mem_f4ShortChevalleyIndices_iff (i : f4ChevalleyIndex) :
    i ∈ f4ShortChevalleyIndices ↔ F4ChevalleyIndexIsShort i := Iff.rfl

/-- The modular coordinate subspace spanned by short root vectors and the two short simple
coroots. It is a Lie ideal; see `f4ShortRootLieIdeal`. -/
def f4ShortRootSubspace : Submodule (ZMod 2) f4ModularChevalleyLieAlgebra :=
  Submodule.span (ZMod 2) (f4ModularChevalleyBasis '' f4ShortChevalleyIndices)

/-- The short-root subspace is the span of the Chevalley basis vectors with short indices. -/
theorem f4ShortRootSubspace_eq_span :
    f4ShortRootSubspace =
      Submodule.span (ZMod 2) (f4ModularChevalleyBasis '' f4ShortChevalleyIndices) := by rfl

theorem f4ModularChevalleyBasis_mem_shortRootSubspace {i : f4ChevalleyIndex}
    (hi : F4ChevalleyIndexIsShort i) :
    f4ModularChevalleyBasis i ∈ f4ShortRootSubspace := by
  apply Submodule.subset_span
  exact ⟨i, hi, rfl⟩

theorem f4ModularRootVector_mem_shortRootSubspace (β : Fin 48)
    (hβ : f4Length β = 1) :
    f4ModularRootVector β ∈ f4ShortRootSubspace := by
  rw [f4ModularRootVector_eq_basis]
  apply f4ModularChevalleyBasis_mem_shortRootSubspace
  simpa only [f4ChevalleyIndexIsShort_inl_iff,
    f4PinnedRootIndex_f4KillingRootLabel] using hβ

theorem f4ModularSimpleCoroot_mem_shortRootSubspace (i : Fin F4.rank)
    (hi : Fin.cast rank_F4 i = 2 ∨ Fin.cast rank_F4 i = 3) :
    f4ModularSimpleCoroot i ∈ f4ShortRootSubspace := by
  apply Submodule.subset_span
  refine ⟨Sum.inr ((F4.lieBasis valid_F4).baseSupportEquiv i), ?_,
    (f4ModularSimpleCoroot_eq_basis i).symm⟩
  -- Membership unfolds the defining coordinate predicate on a simple-coroot label.
  change f4PinnedSimpleIndexEquiv ((F4.lieBasis valid_F4).baseSupportEquiv i) = 2 ∨
    f4PinnedSimpleIndexEquiv ((F4.lieBasis valid_F4).baseSupportEquiv i) = 3
  simpa only [f4PinnedSimpleIndexEquiv_baseSupportEquiv] using hi

/-- Every short-root coroot reduces to the span of the two short simple coroots modulo two. -/
theorem f4ModularCoroot_mem_shortRootSubspace (β : Fin 48) (hβ : f4Length β = 1) :
    f4ModularCoroot β ∈ f4ShortRootSubspace := by
  obtain ⟨k₀, k₁, h₀, h₁⟩ :=
    exists_f4Coroot_longSimple_coordinates_eq_two_mul β hβ
  rw [f4ModularCoroot_eq_sum_simple]
  apply Submodule.sum_mem
  intro i _
  let j : Fin 4 := Fin.cast rank_F4 i
  by_cases hj₀ : j = 0
  · have hz : (f4Coroot β j : ZMod 2) = 0 := by
      rw [hj₀, h₀, Int.cast_mul,
        Int.cast_ofNat, CharTwo.two_eq_zero (R := ZMod 2), zero_mul]
    -- The local name j is the same node with its rank-four index made explicit.
    rw [show Fin.cast rank_F4 i = j by rfl, hz, zero_smul]
    exact Submodule.zero_mem _
  by_cases hj₁ : j = 1
  · have hz : (f4Coroot β j : ZMod 2) = 0 := by
      rw [hj₁, h₁, Int.cast_mul,
        Int.cast_ofNat, CharTwo.two_eq_zero (R := ZMod 2), zero_mul]
    -- The local name j is the same node with its rank-four index made explicit.
    rw [show Fin.cast rank_F4 i = j by rfl, hz, zero_smul]
    exact Submodule.zero_mem _
  · have hj : j = 2 ∨ j = 3 := by omega
    exact Submodule.smul_mem _ _ (f4ModularSimpleCoroot_mem_shortRootSubspace i hj)

/-- A short--short Chevalley bracket with long-root target vanishes in the modular lattice. -/
theorem f4Modular_lie_rootVector_eq_zero_of_short_add_short_eq_long (α β γ : Fin 48)
    (hα : f4Length α = 1) (hβ : f4Length β = 1) (hγ : f4Length γ = 2)
    (h : f4SimplyConnectedRootDatum.root γ =
      f4SimplyConnectedRootDatum.root β + f4SimplyConnectedRootDatum.root α) :
    ⁅f4ModularRootVector α, f4ModularRootVector β⁆ = 0 := by
  obtain ⟨z, hzabs, hlie⟩ := exists_f4Modular_lie_rootVector_eq_smul_of_add α β γ h
  rw [f4_chainBotCoeff_eq_one_of_short_add_short_eq_long α β γ hα hβ hγ h] at hzabs
  have hzmod : (z : ZMod 2) = 0 := by
    rw [← ZMod.natAbs_mod_two, hzabs]
    exact ZMod.natCast_self 2
  rw [hlie, hzmod, zero_smul]

/-- Bracketing an arbitrary modular root vector with a short-root vector stays in the modular
short-root coordinate space. -/
theorem f4Modular_lie_rootVector_mem_shortRootSubspace (α β : Fin 48)
    (hβ : f4Length β = 1) :
    ⁅f4ModularRootVector α, f4ModularRootVector β⁆ ∈ f4ShortRootSubspace := by
  let H := F4.cartanSubalgebra valid_F4
  by_cases hsum :
      (f4KillingRoot α : H → ℚ) + (f4KillingRoot β : H → ℚ) = 0
  · have hindex : α = f4OppositeRootIndex β := by
      by_contra hopp
      exact f4KillingRoot_add_ne_zero_of_ne_opposite α β hopp hsum
    rw [hindex, ← lie_skew, f4Modular_lie_rootVector_opposite]
    exact Submodule.neg_mem _ (f4ModularCoroot_mem_shortRootSubspace β hβ)
  by_cases hbot : rootSpace H
      ((f4KillingRoot α : H → ℚ) + (f4KillingRoot β : H → ℚ)) = ⊥
  · rw [f4Modular_lie_rootVector_eq_zero_of_rootSpace_add_eq_bot α β hbot]
    exact Submodule.zero_mem _
  · have hadd : (f4KillingRoot β : H → ℚ) + (f4KillingRoot α : H → ℚ) =
        (f4KillingRoot α : H → ℚ) + (f4KillingRoot β : H → ℚ) := add_comm _ _
    have hroot : rootSpace H
        ((f4KillingRoot β : H → ℚ) + (f4KillingRoot α : H → ℚ)) ≠ ⊥ := by
      rw [hadd]
      exact hbot
    let δ : Weight ℚ H (F4.lieAlgebra valid_F4) :=
      ⟨(f4KillingRoot β : H → ℚ) + (f4KillingRoot α : H → ℚ), hroot⟩
    have hδ : δ.IsNonZero := by
      intro hz
      apply hsum
      -- Nonzero weight means its underlying function is nonzero; δ was defined by this sum.
      change (f4KillingRoot β : H → ℚ) + (f4KillingRoot α : H → ℚ) = 0 at hz
      exact hadd.symm.trans hz
    let r : H.root := ⟨δ, by simpa only [LieSubalgebra.root, Finset.mem_filter,
      Finset.mem_univ, true_and] using hδ⟩
    let γ : Fin 48 := f4PinnedRootIndex r
    have hγweight : f4KillingRoot γ = δ := by
      exact congrArg
        (fun s : H.root => (s : Weight ℚ H (F4.lieAlgebra valid_F4)))
        (f4KillingRootLabel_f4PinnedRootIndex r)
    have hγ : f4SimplyConnectedRootDatum.root γ =
        f4SimplyConnectedRootDatum.root β + f4SimplyConnectedRootDatum.root α := by
      have h := (f4KillingRoot_eq_add_zsmul_iff α β γ 1).mp (by
        rw [Int.cast_one, one_smul]
        exact congrArg DFunLike.coe hγweight)
      simpa only [one_zsmul] using h
    rcases f4Length_eq_one_or_eq_two γ with hγshort | hγlong
    · obtain ⟨z, _, hlie⟩ := exists_f4Modular_lie_rootVector_eq_smul_of_add α β γ hγ
      rw [hlie]
      exact Submodule.smul_mem _ _
        (f4ModularRootVector_mem_shortRootSubspace γ hγshort)
    · rcases f4Length_eq_one_or_eq_two α with hαshort | hαlong
      · rw [f4Modular_lie_rootVector_eq_zero_of_short_add_short_eq_long α β γ
          hαshort hβ hγlong hγ]
        exact Submodule.zero_mem _
      · have hγshort :=
          f4_n_eq_one_and_pairing_eq_neg_one_and_length_eq_one_of_short_add_nsmul_long
            α β γ 1 hαlong hβ (by omega) (by
          simpa using hγ)
        omega

/-- Bracketing an arbitrary modular root vector with either short simple coroot stays in the
modular short-root coordinate space. Long-root coefficients vanish by length symmetry modulo
two. -/
theorem f4Modular_lie_rootVector_simpleCoroot_mem_shortRootSubspace
    (α : Fin 48) (i : Fin F4.rank)
    (hi : Fin.cast rank_F4 i = 2 ∨ Fin.cast rank_F4 i = 3) :
    ⁅f4ModularRootVector α, f4ModularSimpleCoroot i⁆ ∈ f4ShortRootSubspace := by
  rw [f4Modular_lie_rootVector_simpleCoroot]
  rcases f4Length_eq_one_or_eq_two α with hαshort | hαlong
  · exact Submodule.smul_mem _ _
      (f4ModularRootVector_mem_shortRootSubspace α hαshort)
  · let j : Fin 4 := Fin.cast rank_F4 i
    let s : Fin 48 := Fin.castAdd 44 j
    have hs : f4Length s = 1 := by
      rcases hi with hi | hi
      · simp only [s, f4Length_castAdd, rootLength_F4, j, hi]
        norm_num
      · simp only [s, f4Length_castAdd, rootLength_F4, j, hi]
        norm_num
    have hsym := f4Length_mul_pairing_comm s α
    rw [hs, hαlong, one_mul] at hsym
    have heven : f4SimplyConnectedRootDatum.pairing α s =
        2 * f4SimplyConnectedRootDatum.pairing s α := hsym
    have hz : (f4SimplyConnectedRootDatum.pairing α s : ZMod 2) = 0 := by
      rw [heven, Int.cast_mul,
        Int.cast_ofNat, CharTwo.two_eq_zero (R := ZMod 2), zero_mul]
    -- The local name s denotes this simple-root index in the full root table.
    rw [show Fin.castAdd 44 (Fin.cast rank_F4 i) = s by rfl, hz, neg_zero, zero_smul]
    exact Submodule.zero_mem _

theorem f4Modular_lie_simpleCoroot_rootVector_mem_shortRootSubspace
    (i : Fin F4.rank) (α : Fin 48) (hα : f4Length α = 1) :
    ⁅f4ModularSimpleCoroot i, f4ModularRootVector α⁆ ∈ f4ShortRootSubspace := by
  rw [f4Modular_lie_simpleCoroot_rootVector]
  exact Submodule.smul_mem _ _ (f4ModularRootVector_mem_shortRootSubspace α hα)

private theorem f4Modular_lie_basis_inl_inl_mem_shortRootSubspace
    (α β : (F4.cartanSubalgebra valid_F4).root)
    (hβ : F4ChevalleyIndexIsShort (Sum.inl β)) :
    ⁅f4ModularChevalleyBasis (Sum.inl α),
      f4ModularChevalleyBasis (Sum.inl β)⁆ ∈ f4ShortRootSubspace := by
  rw [f4ModularChevalleyBasis_inl_eq_rootVector,
    f4ModularChevalleyBasis_inl_eq_rootVector]
  exact f4Modular_lie_rootVector_mem_shortRootSubspace
    (f4PinnedRootIndex α) (f4PinnedRootIndex β)
    ((f4ChevalleyIndexIsShort_inl_iff β).mp hβ)

private theorem f4Modular_lie_basis_inl_inr_mem_shortRootSubspace
    (α : (F4.cartanSubalgebra valid_F4).root) (b : f4KillingBase.support)
    (hbshort : F4ChevalleyIndexIsShort (Sum.inr b)) :
    ⁅f4ModularChevalleyBasis (Sum.inl α),
      f4ModularChevalleyBasis (Sum.inr b)⁆ ∈ f4ShortRootSubspace := by
  let k : Fin F4.rank := (F4.lieBasis valid_F4).baseSupportEquiv.symm b
  have hk : Fin.cast rank_F4 k = 2 ∨ Fin.cast rank_F4 k = 3 := by
    simpa only [k, f4PinnedSimpleIndexEquiv, f4PinnedSimpleIndexEquiv,
      Equiv.trans_apply, finCongr_apply, Fin.cast_mk] using
      (f4ChevalleyIndexIsShort_inr_iff b).mp hbshort
  rw [f4ModularChevalleyBasis_inl_eq_rootVector,
    f4ModularChevalleyBasis_inr_eq_simpleCoroot]
  exact f4Modular_lie_rootVector_simpleCoroot_mem_shortRootSubspace
    (f4PinnedRootIndex α) k hk

private theorem f4Modular_lie_basis_inr_inl_mem_shortRootSubspace
    (a : f4KillingBase.support) (β : (F4.cartanSubalgebra valid_F4).root)
    (hβ : F4ChevalleyIndexIsShort (Sum.inl β)) :
    ⁅f4ModularChevalleyBasis (Sum.inr a),
      f4ModularChevalleyBasis (Sum.inl β)⁆ ∈ f4ShortRootSubspace := by
  let k : Fin F4.rank := (F4.lieBasis valid_F4).baseSupportEquiv.symm a
  simp only [f4ModularChevalleyBasis_inr_eq_simpleCoroot,
    f4ModularChevalleyBasis_inl_eq_rootVector]
  exact f4Modular_lie_simpleCoroot_rootVector_mem_shortRootSubspace k
    (f4PinnedRootIndex β) ((f4ChevalleyIndexIsShort_inl_iff β).mp hβ)

private theorem f4Modular_lie_basis_inr_inr_mem_shortRootSubspace
    (a b : f4KillingBase.support) :
    ⁅f4ModularChevalleyBasis (Sum.inr a),
      f4ModularChevalleyBasis (Sum.inr b)⁆ ∈ f4ShortRootSubspace := by
  simp only [f4ModularChevalleyBasis_inr_eq_simpleCoroot,
    f4Modular_lie_simpleCoroot_simpleCoroot_eq_zero]
  exact Submodule.zero_mem _

/-- A Chevalley basis vector brackets every distinguished short Chevalley basis vector back into
the short coordinate space. -/
theorem f4Modular_lie_basis_mem_shortRootSubspace (i j : f4ChevalleyIndex)
    (hj : F4ChevalleyIndexIsShort j) :
    ⁅f4ModularChevalleyBasis i, f4ModularChevalleyBasis j⁆ ∈
      f4ShortRootSubspace := by
  rcases i with α | a <;> rcases j with β | b
  · exact f4Modular_lie_basis_inl_inl_mem_shortRootSubspace α β hj
  · exact f4Modular_lie_basis_inl_inr_mem_shortRootSubspace α b hj
  · exact f4Modular_lie_basis_inr_inl_mem_shortRootSubspace a β hj
  · exact f4Modular_lie_basis_inr_inr_mem_shortRootSubspace a b

/-- The modular short-root coordinate space is stable under the bracket with every element of the
reduced Chevalley Lie algebra. -/
theorem f4ShortRootSubspace_lie_mem (x : f4ModularChevalleyLieAlgebra)
    {y : f4ModularChevalleyLieAlgebra} (hy : y ∈ f4ShortRootSubspace) :
    ⁅x, y⁆ ∈ f4ShortRootSubspace := by
  have hx := f4ModularChevalleyBasis.mem_span x
  rw [f4ShortRootSubspace_eq_span] at hy ⊢
  induction hx, hy using Submodule.span_induction₂ with
  | mem_mem x y hx hy =>
      rcases hx with ⟨i, rfl⟩
      rcases hy with ⟨j, hj, rfl⟩
      apply f4Modular_lie_basis_mem_shortRootSubspace i j
      exact (mem_f4ShortChevalleyIndices_iff j).mp hj
  | zero_left =>
      rw [zero_lie]
      exact Submodule.zero_mem _
  | zero_right x _ =>
      -- The tensor-product bracket is definitionally ad; this fixes its ZMod 2 module structure.
      change (LieAlgebra.ad (ZMod 2) f4ModularChevalleyLieAlgebra x) 0 ∈ _
      rw [map_zero]
      exact Submodule.zero_mem _
  | add_left _ _ _ _ _ _ h₁ h₂ =>
      rw [add_lie]
      exact Submodule.add_mem _ h₁ h₂
  | add_right x y z _ _ _ h₁ h₂ =>
      -- Use ad's additivity with the scalar-extension bracket, not the inferred LieModule bracket.
      change (LieAlgebra.ad (ZMod 2) f4ModularChevalleyLieAlgebra x) (y + z) ∈ _
      rw [map_add]
      exact Submodule.add_mem _ h₁ h₂
  | smul_left r _ _ _ _ h =>
      rw [smul_lie]
      exact Submodule.smul_mem _ r h
  | smul_right r x y _ _ h =>
      -- Express this bracket as the ZMod 2-linear adjoint map to fix the scalar action.
      change (LieAlgebra.ad (ZMod 2) f4ModularChevalleyLieAlgebra x) (r • y) ∈ _
      rw [map_smul]
      exact Submodule.smul_mem _ r h

/-- The characteristic-two short-root coordinate space as a Lie ideal in the reduced integral
Chevalley algebra. -/
noncomputable def f4ShortRootLieIdeal :
    LieIdeal (ZMod 2) f4ModularChevalleyLieAlgebra :=
  { f4ShortRootSubspace with
    lie_mem := fun {x _y} hy => f4ShortRootSubspace_lie_mem x hy }

@[simp] theorem f4ShortRootLieIdeal_toSubmodule :
    f4ShortRootLieIdeal.toSubmodule = f4ShortRootSubspace := by rfl

@[simp] theorem mem_f4ShortRootLieIdeal_iff {x : f4ModularChevalleyLieAlgebra} :
    x ∈ f4ShortRootLieIdeal ↔ x ∈ f4ShortRootSubspace := by
  rfl

/-- A modular Chevalley vector whose coordinates outside the distinguished short labels vanish
belongs to the short-root coordinate subspace. -/
theorem mem_f4ShortRootSubspace_of_repr_eq_zero
    (X : f4ModularChevalleyLieAlgebra)
    (hX : ∀ i : f4ChevalleyIndex, ¬ F4ChevalleyIndexIsShort i →
      f4ModularChevalleyBasis.repr X i = 0) :
    X ∈ f4ShortRootSubspace := by
  rw [← f4ModularChevalleyBasis.sum_repr X]
  apply Submodule.sum_mem
  intro i _
  by_cases hi : F4ChevalleyIndexIsShort i
  · exact Submodule.smul_mem _ _ (f4ModularChevalleyBasis_mem_shortRootSubspace hi)
  · rw [hX i hi, zero_smul]
    exact Submodule.zero_mem _


end

end EpsilonEridani.DynkinType
