/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.RepresentationTheory.Symmetric.Symmetrizer

/-!
# When a symmetrizer sandwich vanishes

For a `μ`-tableau `t` with row symmetrizer `a_t` and column antisymmetrizer `b_t`, the
irreducibility of the left ideal `ℚ[Sₙ] c_t` generated by the Young symmetrizer
`c_t = a_t b_t` is driven by the behaviour of the sandwiches `a_t σ b_t`, for `σ` a permutation
of the labels.  This file proves the criterion that governs them.

The criterion is a row/column intersection condition, recorded here as
`YoungTableau.RowMeetsColumnTwice t s`: two distinct labels lie in a common row of `t` and in a
common column of `s`, so that row and that column share not just one label but two.  The
**key vanishing lemma**
`YoungTableau.RowMeetsColumnTwice.rowSymmetrizer_mul_single_mul_columnAntisymmetrizer_eq_zero`
says that `a_t σ b_t = 0` as soon as a row of `t` meets a column of the relabelled tableau
`relabel σ t` in two distinct labels.  Its proof is the transposition trick: the swap `τ` of the
two labels lies in the row group, its conjugate `σ⁻¹ τ σ` lies in the column group, and pushing
`τ` across `σ` turns the sandwich into its own negative.

The direction of `σ` matters, and it is the one written here: the two labels sharing a column are
`σ⁻¹ x` and `σ⁻¹ y`, or equivalently `x` and `y` share a column of the relabelling `σt`, which is
Fulton's formulation.  The variant asking instead that `σ x` and `σ y` share a column of `t` is
false, as the sandwich lemmas below already show: if `x ≠ y` share a row of `t` and `x ≠ v` share
a column of `t`, then `σ = (x y) (x v)` carries `x` and `y` to the common-column pair `v` and `x`,
yet `σ` lies in `Row(t) · Col(t)`, so `a_t σ b_t ≠ 0` by
`YoungTableau.rowSymmetrizer_mul_single_mul_columnAntisymmetrizer_ne_zero`.

In the opposite direction, a permutation of the form `σ = p q` with `p` in the row group and `q`
in the column group has `a_t σ b_t = sign q • c_t ≠ 0`
(`YoungTableau.rowSymmetrizer_mul_single_mul_columnAntisymmetrizer_eq_sign_smul_youngSymmetrizer`),
and no row of `t` meets a column of `relabel σ t` twice
(`YoungTableau.not_rowMeetsColumnTwice_relabel_mul`).  So the criterion never fires on the
permutations whose sandwich is visibly nonzero, and it certifies that the permutations it does
fire on lie outside the product set `Row(t) · Col(t)`.

A relabelling can be moved from one argument of the criterion to the other by inverting it
(`YoungTableau.rowMeetsColumnTwice_relabel_left_iff`), which is what lets the criterion be applied
when it is the tableau whose *rows* are read that has been relabelled.

Neither half is vacuous: `YoungTableau.exists_rowMeetsColumnTwice_relabel` produces a permutation
the criterion fires on whenever `t` has a row and a column each containing two distinct labels, so
`YoungTableau.exists_rowSymmetrizer_mul_single_mul_columnAntisymmetrizer_eq_zero` exhibits a
vanishing sandwich for every shape other than a single row or a single column.

Note that the criterion, and not the cruder condition `σ ∉ Row(t) · Col(t)`, is what the
transposition trick establishes; the converse implication (a permutation on which the criterion
fails already factors as `p q`) is a separate combinatorial theorem and is not proved here.

## References

* [W. Fulton, *Young Tableaux*][fulton1997], Section 7.2.
* W. Fulton and J. Harris, *Representation Theory: A First Course* (1991), Lecture 4.
* [Schur--Weyl roadmap](https://github.com/EpsilonEridaniProject/EpsilonEridaniRoadmap/blob/main/EpsilonEridaniRoadmap/RepresentationTheory/SchurWeyl/README.md),
  Layer 2.
-/

public section

namespace EpsilonEridani

namespace YoungTableau

open scoped Pointwise

variable {μ : YoungDiagram}

/-- A row of the tableau `t` **meets a column** of the tableau `s` **twice** if two distinct
labels lie in a common row of `t` and in a common column of `s`.  A row of `t` and a column of `t`
share at most one label, so meeting once is no condition at all and it is the second shared label
that carries the content.  The relation is not symmetric: rows are read off `t` and columns off
`s`. -/
def RowMeetsColumnTwice (t s : YoungTableau μ) : Prop :=
  ∃ x y, x ≠ y ∧ rowIndex t x = rowIndex t y ∧ colIndex s x = colIndex s y

/-- The defining characterisation of `RowMeetsColumnTwice`, for introducing and eliminating the
predicate on arbitrary tableaux.  Not a `simp` lemma: it would shadow the normal forms
`rowMeetsColumnTwice_relabel_iff` and `not_rowMeetsColumnTwice_self`. -/
theorem rowMeetsColumnTwice_def (t s : YoungTableau μ) :
    RowMeetsColumnTwice t s ↔
      ∃ x y, x ≠ y ∧ rowIndex t x = rowIndex t y ∧ colIndex s x = colIndex s y :=
  Iff.rfl

/-- A row of `t` meets a column of the relabelling `relabel σ t` exactly when two distinct labels
of a common row of `t` have their `σ`-preimages in a common column of `t`. -/
@[simp]
theorem rowMeetsColumnTwice_relabel_iff (t : YoungTableau μ) (σ : Equiv.Perm (Fin μ.card)) :
    RowMeetsColumnTwice t (relabel σ t) ↔
      ∃ x y, x ≠ y ∧ rowIndex t x = rowIndex t y ∧
        colIndex t (σ⁻¹ x) = colIndex t (σ⁻¹ y) := by
  simp only [rowMeetsColumnTwice_def, colIndex_relabel]

/-- Relabelling moves across the criterion by inverting: a row of `relabel σ t` meets a column of
`s` twice exactly when a row of `t` meets a column of `relabel σ⁻¹ s` twice.  Both sides say that
two distinct labels share a row of `t` after applying `σ⁻¹` and share a column of `s`, read from
the two ends.

Not a `simp` lemma: neither side is simpler than the other, and pushing the relabelling to the
right would fight `rowMeetsColumnTwice_relabel_iff`. -/
theorem rowMeetsColumnTwice_relabel_left_iff (t s : YoungTableau μ)
    (σ : Equiv.Perm (Fin μ.card)) :
    RowMeetsColumnTwice (relabel σ t) s ↔ RowMeetsColumnTwice t (relabel σ⁻¹ s) := by
  simp only [rowMeetsColumnTwice_def, rowIndex_relabel, colIndex_relabel, inv_inv]
  constructor
  · rintro ⟨x, y, hxy, hrow, hcol⟩
    exact ⟨σ⁻¹ x, σ⁻¹ y, fun h => hxy (σ⁻¹.injective h), hrow, by simpa using hcol⟩
  · rintro ⟨x, y, hxy, hrow, hcol⟩
    exact ⟨σ x, σ y, fun h => hxy (σ.injective h), by simpa using hrow, hcol⟩

/-- No row of a tableau meets one of its own columns twice: a label is determined by its row
together with its column. -/
@[simp]
theorem not_rowMeetsColumnTwice_self (t : YoungTableau μ) : ¬RowMeetsColumnTwice t t := by
  rw [rowMeetsColumnTwice_def]
  rintro ⟨x, y, hxy, hrow, hcol⟩
  exact hxy (rowIndex_colIndex_injective t (Prod.ext hrow hcol))

/-- The criterion is satisfiable as soon as `t` has a row containing two distinct labels and a
column containing two distinct labels: some relabelling of `t` then has a column meeting that row
twice.  Concretely one moves `x` and `y` onto `u` and `v` and relabels by the inverse. -/
theorem exists_rowMeetsColumnTwice_relabel (t : YoungTableau μ) {x y u v : Fin μ.card} (hxy : x ≠ y)
    (hrow : rowIndex t x = rowIndex t y) (huv : u ≠ v) (hcol : colIndex t u = colIndex t v) :
    ∃ σ : Equiv.Perm (Fin μ.card), RowMeetsColumnTwice t (relabel σ t) := by
  -- a permutation carrying `x` to `u` and `y` to `v`, obtained by extending the injection
  -- `x, y ↦ u, v` to a permutation
  obtain ⟨ρ, hρ⟩ := Equiv.Perm.exists_extending_pair (fun b : Bool => bif b then x else y)
    (fun b : Bool => bif b then u else v) (fun a b h => by cases a <;> cases b <;> simp_all)
    (fun a b h => by cases a <;> cases b <;> simp_all)
  refine ⟨ρ⁻¹, ?_⟩
  rw [rowMeetsColumnTwice_relabel_iff]
  refine ⟨x, y, hxy, hrow, ?_⟩
  have hx : ρ x = u := by simpa using hρ true
  have hy : ρ y = v := by simpa using hρ false
  rw [inv_inv, hx, hy]
  exact hcol

/-- **The key vanishing lemma**, in terms of explicit labels: if the distinct labels `x` and `y`
lie in a common row of `t` while their `σ`-preimages lie in a common column of `t`, then the
sandwich `a_t σ b_t` vanishes. -/
theorem rowSymmetrizer_mul_single_mul_columnAntisymmetrizer_eq_zero (t : YoungTableau μ)
    (σ : Equiv.Perm (Fin μ.card)) {x y : Fin μ.card} (hxy : x ≠ y)
    (hrow : rowIndex t x = rowIndex t y)
    (hcol : colIndex t (σ⁻¹ x) = colIndex t (σ⁻¹ y)) :
    rowSymmetrizer t * MonoidAlgebra.single σ (1 : ℚ) * columnAntisymmetrizer t = 0 := by
  have hxy' : σ⁻¹ x ≠ σ⁻¹ y := fun h => hxy ((σ⁻¹ : Equiv.Perm (Fin μ.card)).injective h)
  -- absorbing the transposition of `x` and `y` into the row symmetrizer
  have habsorb : rowSymmetrizer t * MonoidAlgebra.single (Equiv.swap x y) (1 : ℚ) =
      rowSymmetrizer t :=
    mul_rowSymmetrizer_right t ⟨Equiv.swap x y, swap_mem_rowSubgroup hrow⟩
  -- its conjugate transposes two labels of a common column, so it acts by its sign
  have hsign : MonoidAlgebra.single (Equiv.swap (σ⁻¹ x) (σ⁻¹ y)) (1 : ℚ) *
      columnAntisymmetrizer t =
      ((Equiv.Perm.sign (Equiv.swap (σ⁻¹ x) (σ⁻¹ y)) : ℤ) : ℚ) • columnAntisymmetrizer t :=
    mul_columnAntisymmetrizer_left t ⟨Equiv.swap (σ⁻¹ x) (σ⁻¹ y), swap_mem_colSubgroup hcol⟩
  -- multiplying by `σ` on the right turns the swap of `x` and `y` into the swap of their
  -- `σ`-preimages: this is the step that moves the swap from the row side to the column side
  have hswap : MonoidAlgebra.single (Equiv.swap x y) (1 : ℚ) * MonoidAlgebra.single σ (1 : ℚ) =
      MonoidAlgebra.single σ (1 : ℚ) *
        MonoidAlgebra.single (Equiv.swap (σ⁻¹ x) (σ⁻¹ y)) (1 : ℚ) := by
    rw [MonoidAlgebra.single_mul_single, MonoidAlgebra.single_mul_single, mul_one,
      Equiv.swap_mul_eq_mul_swap]
  have hneg : ((Equiv.Perm.sign (Equiv.swap (σ⁻¹ x) (σ⁻¹ y)) : ℤ) : ℚ) = -1 := by
    rw [Equiv.Perm.sign_swap hxy']
    simp
  have key : rowSymmetrizer t * MonoidAlgebra.single σ (1 : ℚ) * columnAntisymmetrizer t =
      -(rowSymmetrizer t * MonoidAlgebra.single σ (1 : ℚ) * columnAntisymmetrizer t) :=
    calc rowSymmetrizer t * MonoidAlgebra.single σ (1 : ℚ) * columnAntisymmetrizer t
        = rowSymmetrizer t * (MonoidAlgebra.single (Equiv.swap x y) (1 : ℚ) *
            MonoidAlgebra.single σ (1 : ℚ)) * columnAntisymmetrizer t := by
          rw [← mul_assoc (rowSymmetrizer t), habsorb]
      _ = rowSymmetrizer t * MonoidAlgebra.single σ (1 : ℚ) *
            (MonoidAlgebra.single (Equiv.swap (σ⁻¹ x) (σ⁻¹ y)) (1 : ℚ) *
              columnAntisymmetrizer t) := by
          rw [hswap]
          simp only [mul_assoc]
      _ = -(rowSymmetrizer t * MonoidAlgebra.single σ (1 : ℚ) * columnAntisymmetrizer t) := by
          rw [hsign, hneg, neg_one_smul, mul_neg]
  have h2 : (2 : ℚ) •
      (rowSymmetrizer t * MonoidAlgebra.single σ (1 : ℚ) * columnAntisymmetrizer t) = 0 := by
    rw [two_smul]
    nth_rewrite 2 [key]
    exact add_neg_cancel _
  exact (smul_eq_zero.mp h2).resolve_left (by norm_num)

/-- **The key vanishing lemma.**  If a row of `t` meets a column of the relabelled tableau
`relabel σ t` in two distinct labels, then the sandwich `a_t σ b_t` vanishes. -/
@[simp]
theorem RowMeetsColumnTwice.rowSymmetrizer_mul_single_mul_columnAntisymmetrizer_eq_zero
    {t : YoungTableau μ} {σ : Equiv.Perm (Fin μ.card)} (h : RowMeetsColumnTwice t (relabel σ t)) :
    rowSymmetrizer t * MonoidAlgebra.single σ (1 : ℚ) * columnAntisymmetrizer t = 0 := by
  obtain ⟨x, y, hxy, hrow, hcol⟩ := (rowMeetsColumnTwice_relabel_iff t σ).mp h
  exact YoungTableau.rowSymmetrizer_mul_single_mul_columnAntisymmetrizer_eq_zero t σ hxy hrow hcol

/-- A permutation lying in the product of the row and the column group has its sandwich equal to
the Young symmetrizer, up to the sign of its column part. -/
@[simp]
theorem rowSymmetrizer_mul_single_mul_columnAntisymmetrizer_eq_sign_smul_youngSymmetrizer
    (t : YoungTableau μ) {p q : Equiv.Perm (Fin μ.card)} (hp : p ∈ rowSubgroup t)
    (hq : q ∈ colSubgroup t) :
    rowSymmetrizer t * MonoidAlgebra.single (p * q) (1 : ℚ) * columnAntisymmetrizer t =
      ((Equiv.Perm.sign q : ℤ) : ℚ) • youngSymmetrizer t := by
  have hrow : rowSymmetrizer t * MonoidAlgebra.single p (1 : ℚ) = rowSymmetrizer t :=
    mul_rowSymmetrizer_right t ⟨p, hp⟩
  have hcol : MonoidAlgebra.single q (1 : ℚ) * columnAntisymmetrizer t =
      ((Equiv.Perm.sign q : ℤ) : ℚ) • columnAntisymmetrizer t :=
    mul_columnAntisymmetrizer_left t ⟨q, hq⟩
  have hpq : MonoidAlgebra.single (p * q) (1 : ℚ) =
      MonoidAlgebra.single p (1 : ℚ) * MonoidAlgebra.single q (1 : ℚ) := by
    rw [MonoidAlgebra.single_mul_single, mul_one]
  rw [hpq, ← mul_assoc, hrow, mul_assoc, hcol, mul_smul_comm, youngSymmetrizer_def]

/-- A permutation lying in the product of the row and the column group has a nonzero
sandwich. -/
theorem rowSymmetrizer_mul_single_mul_columnAntisymmetrizer_ne_zero (t : YoungTableau μ)
    {p q : Equiv.Perm (Fin μ.card)} (hp : p ∈ rowSubgroup t) (hq : q ∈ colSubgroup t) :
    rowSymmetrizer t * MonoidAlgebra.single (p * q) (1 : ℚ) * columnAntisymmetrizer t ≠ 0 := by
  rw [rowSymmetrizer_mul_single_mul_columnAntisymmetrizer_eq_sign_smul_youngSymmetrizer t hp hq]
  refine smul_ne_zero ?_ (youngSymmetrizer_ne_zero t)
  simp

/-- No row of `t` meets a column of `relabel (p * q) t` twice, when `p` lies in the row group and
`q` in the column group: the two labels would share a row and a column of `t` itself. -/
theorem not_rowMeetsColumnTwice_relabel_mul (t : YoungTableau μ)
    {p q : Equiv.Perm (Fin μ.card)} (hp : p ∈ rowSubgroup t) (hq : q ∈ colSubgroup t) :
    ¬RowMeetsColumnTwice t (relabel (p * q) t) := by
  rw [rowMeetsColumnTwice_relabel_iff]
  rintro ⟨x, y, hxy, hrow, hcol⟩
  refine not_rowMeetsColumnTwice_self t ⟨p⁻¹ x, p⁻¹ y, fun h => hxy (p⁻¹.injective h), ?_, ?_⟩
  · rw [mem_rowSubgroup.mp (inv_mem hp) x, mem_rowSubgroup.mp (inv_mem hp) y]
    exact hrow
  · rw [mul_inv_rev, Equiv.Perm.mul_apply, Equiv.Perm.mul_apply,
      mem_colSubgroup.mp (inv_mem hq) (p⁻¹ x), mem_colSubgroup.mp (inv_mem hq) (p⁻¹ y)] at hcol
    exact hcol

/-- A permutation on which the row/column criterion fires lies outside the product set
`Row(t) · Col(t)`. -/
theorem notMem_mul_of_rowMeetsColumnTwice {t : YoungTableau μ} {σ : Equiv.Perm (Fin μ.card)}
    (h : RowMeetsColumnTwice t (relabel σ t)) :
    σ ∉ (rowSubgroup t : Set (Equiv.Perm (Fin μ.card))) *
      (colSubgroup t : Set (Equiv.Perm (Fin μ.card))) := by
  intro hmem
  rw [Set.mem_mul] at hmem
  obtain ⟨p, hp, q, hq, rfl⟩ := hmem
  exact not_rowMeetsColumnTwice_relabel_mul t (SetLike.mem_coe.mp hp) (SetLike.mem_coe.mp hq) h

/-- The vanishing lemma is not vacuous: a tableau with a row containing two distinct labels and a
column containing two distinct labels admits a permutation whose sandwich vanishes. -/
theorem exists_rowSymmetrizer_mul_single_mul_columnAntisymmetrizer_eq_zero (t : YoungTableau μ)
    {x y u v : Fin μ.card} (hxy : x ≠ y) (hrow : rowIndex t x = rowIndex t y) (huv : u ≠ v)
    (hcol : colIndex t u = colIndex t v) :
    ∃ σ : Equiv.Perm (Fin μ.card),
      rowSymmetrizer t * MonoidAlgebra.single σ (1 : ℚ) * columnAntisymmetrizer t = 0 :=
  let ⟨σ, hσ⟩ := exists_rowMeetsColumnTwice_relabel t hxy hrow huv hcol
  ⟨σ, hσ.rowSymmetrizer_mul_single_mul_columnAntisymmetrizer_eq_zero⟩

/-- The contrapositive of the key vanishing lemma: a nonzero sandwich forces every two distinct
labels of a common row of `t` into distinct columns of `relabel σ t`. -/
theorem not_rowMeetsColumnTwice_relabel_of_ne_zero {t : YoungTableau μ}
    {σ : Equiv.Perm (Fin μ.card)}
    (h : rowSymmetrizer t * MonoidAlgebra.single σ (1 : ℚ) * columnAntisymmetrizer t ≠ 0) :
    ¬RowMeetsColumnTwice t (relabel σ t) :=
  fun hc => h hc.rowSymmetrizer_mul_single_mul_columnAntisymmetrizer_eq_zero

end YoungTableau

end EpsilonEridani
