/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.Algebra.Lie.D4.Tripled.GroupScheme
public import EpsilonEridani.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Torus.Coroot
import EpsilonEridani.LinearAlgebra.Matrix.Cartan.TypeD

/-!
# Generation of the tripled type-D4 weight torus by root subgroups

The tripled type-`D₄` carrier is defined from its eight positive and negative numbered simple-root
subgroups together with its rank-four split weight torus. This file proves that, over every
commutative ring, the torus is already contained in the elementary subgroup generated by those
root subgroups.

The represented simple generators at each node form an `sl₂` triple by
`EpsilonEridani.D4Tripled.isSl2Triple_rep_serreRootGenerator`, and every row of the type-`D₄` Cartan
matrix has the explicit Bezout certificate `EpsilonEridani.sum_cartanMatrixD_mul_typeDCartanBezout`, so
every simple root is a primitive character of the weight torus. The generic Kostant
coroot-generation theorem then makes the torus redundant in the pointwise generating family.

The conclusion concerns subgroups of the automorphism group of the base-changed admissible
lattice. Identifying these generated points with all points of the toral-closure group scheme is a
separate scheme-theoretic comparison.

## Main results

* `EpsilonEridani.D4Tripled.weightTorusSubgroup_le_elementarySubgroup`: the weight torus lies in the
  elementary subgroup over every commutative ring.
* `EpsilonEridani.D4Tripled.weightTorusSubsystemSubgroup_univ_eq_elementarySubgroup`: adjoining the
  weight torus to all numbered root subgroups gives exactly the elementary subgroup.

## References

* R. Steinberg, *Lectures on Chevalley Groups*, Section 3.
* R. W. Carter, *Simple Groups of Lie Type*, Sections 6.4 and 7.1.
* `EpsilonEridani.Algebra.Lie.Orthogonal.TypeD.SpinCarrier.Generation`, whose formal template this file
  follows with the tripled weights in place of the spin weights.
-/

public section

open scoped Matrix TensorProduct

universe v

namespace EpsilonEridani.D4Tripled

open EpsilonEridani.DynkinType EpsilonEridani.UniversalEnvelopingAlgebra

attribute [local instance 100] LieRing.ofAssociativeRing
attribute [local instance high] Algebra.toModule

/-- Over every commutative ring, the tripled type-`D₄` weight torus on the base-changed
admissible lattice is contained in the elementary group generated by the positive and negative
numbered simple root subgroups. -/
theorem weightTorusSubgroup_le_elementarySubgroup (A : CommAlgCat.{v} ℤ) :
    kostantTorusSubgroup lattice.toAddSubgroup latticeBasis d4TripledWeight A ≤
      kostantElementarySubgroup (EpsilonEridani.serreRootGenerator weightTable.cartanMatrix)
        (EpsilonEridani.serreH ℚ weightTable.cartanMatrix) rep lattice.toAddSubgroup
        rep_kostantForm_mem_lattice isNilpotent_rep_serreRootGenerator A :=
  kostantTorusSubgroup_le_kostantElementarySubgroup
    (EpsilonEridani.serreRootGenerator weightTable.cartanMatrix)
    (EpsilonEridani.serreH ℚ weightTable.cartanMatrix) rep lattice.toAddSubgroup
    rep_kostantForm_mem_lattice isNilpotent_rep_serreRootGenerator latticeBasis d4TripledWeight
    isCartanWeightVector_latticeBasis (TypeDStd.rootGeneratorWeight 4)
    lie_serreH_serreRootGenerator Sum.inl Sum.inr isSl2Triple_rep_serreRootGenerator
    (fun i => funext fun j => by simp) (typeDCartanBezout 4)
    (fun i => by
      simpa only [TypeDStd.rootGeneratorWeight_inl] using
        sum_cartanMatrixD_mul_typeDCartanBezout (n := 4) (by norm_num) i) A

/-- Over every commutative ring, adjoining the tripled type-`D₄` weight torus to all positive and
negative numbered simple root subgroups does not enlarge their elementary subgroup. -/
theorem weightTorusSubsystemSubgroup_univ_eq_elementarySubgroup (A : CommAlgCat.{v} ℤ) :
    kostantTorusSubsystemSubgroup (EpsilonEridani.serreRootGenerator weightTable.cartanMatrix)
        (EpsilonEridani.serreH ℚ weightTable.cartanMatrix) rep lattice.toAddSubgroup
        rep_kostantForm_mem_lattice isNilpotent_rep_serreRootGenerator latticeBasis
        d4TripledWeight Set.univ A =
      kostantElementarySubgroup (EpsilonEridani.serreRootGenerator weightTable.cartanMatrix)
        (EpsilonEridani.serreH ℚ weightTable.cartanMatrix) rep lattice.toAddSubgroup
        rep_kostantForm_mem_lattice isNilpotent_rep_serreRootGenerator A :=
  (kostantTorusSubsystemSubgroup_univ _ _ _ _ _ _ _ _ A).trans
    (sup_eq_left.2 ((kostantTorusSubgroup_eq_range _ _ _ A).symm.trans_le
      (weightTorusSubgroup_le_elementarySubgroup A)))

end EpsilonEridani.D4Tripled
