/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.Lie.CartanSubalgebra
public import Mathlib.Algebra.Lie.Engel
public import EpsilonEridani.Algebra.Lie.Nilradical

/-!
# Extending a nilpotent action by a normalizing element

Let `M` be a Lie module over `L`, let `H` be a Lie subalgebra of `L` acting nilpotently on `M`, and
let `y : L` normalize `H` and act nilpotently on `M`.  This file proves that the Lie subalgebra
`LieSubalgebra.lieSpan R L (insert y ↑H)` spanned by `y` and `H` again acts nilpotently on `M`, so
that in particular every element `t • y + h` acts nilpotently.  This is the step by which
Hochschild's proof of Ado's theorem enlarges a nilpotently-acting subalgebra one element at a time,
and it is applied there to two different modules, so it is stated once for a general module.

Because `y` normalizes `H`, that Lie span is already spanned by `y` and `H` as a *module*: its
underlying submodule is `R ∙ y ⊔ H.toSubmodule`.  Its elements are therefore exactly the `t • y + h`
with `t : R` and `h ∈ H`, which is the form in which the extension lemma is used.

No Noetherian or finiteness hypothesis is needed for the subalgebra statement.  Engel's theorem
enters only in the variants whose hypothesis on `H` is the pointwise one,
`∀ x ∈ H, IsNilpotent (toEnd x)`, and those carry `[IsNoetherian R M]`.

## Main statements

* `LieSubalgebra.lieSpan_insert_toSubmodule`: the Lie span of `insert y ↑H` has underlying submodule
  `R ∙ y ⊔ H.toSubmodule`, when `y` normalizes `H`.
* `LieSubalgebra.lieModule_isNilpotent_lieSpan_insert`: **the nilpotent-extension lemma**.  If `H`
  acts nilpotently on `M` and a normalizing element `y` acts nilpotently on `M`, then the Lie span
  of `y` and `H` acts nilpotently on `M`.
* `LieSubalgebra.mem_lieSpan_insert_iff`: the elements of that Lie span are exactly the
  `t • y + h` with `h ∈ H`, with intro form `LieSubalgebra.smul_add_mem_lieSpan_insert`.
* `LieSubalgebra.isNilpotent_toEnd_of_mem_lieSpan_insert` and
  `LieSubalgebra.isNilpotent_toEnd_of_mem_lieSpan_insert_of_forall`: the pointwise readings, the
  second one taking the pointwise hypothesis on `H` as well, together with the `t • y + h` reading
  `LieSubalgebra.isNilpotent_toEnd_smul_add_of_mem`.
* `LieIdeal.isNilpotent_toEnd_of_mem_span_singleton_sup`: the special case of an ideal, where the
  normalizing hypothesis is automatic and the conclusion can be read off the submodule
  `R ∙ y ⊔ I.toSubmodule` directly, together with its `t • y + x` reading
  `LieIdeal.isNilpotent_toEnd_smul_add_of_mem`.
* `EpsilonEridani.LieAlgebra.isNilpotent_ad_of_mem_span_singleton_sup_nilradical` and
  `EpsilonEridani.LieAlgebra.isNilpotent_ad_smul_add_of_mem_nilradical`: the adjoint specialization, that
  `t • y + n` is `ad`-nilpotent for `n` in the nilradical and `y` `ad`-nilpotent.

## References

* G. Hochschild, *An addition to Ado's theorem*, Proc. Amer. Math. Soc. 17 (1966), 531-533.
* [W. Fulton and J. Harris, *Representation Theory: A First Course*][fulton-harris1991],
  Appendix E, §E.2.
* Mathlib's `LieAlgebra.exists_engelian_lieSubalgebra_of_lt_normalizer` in
  `Mathlib/Algebra/Lie/Engel.lean`, the source this file follows.
-/

public section

namespace LieSubalgebra

variable {R L : Type*} [CommRing R] [LieRing L] [LieAlgebra R L]
variable {M : Type*} [AddCommGroup M] [Module R M] [LieRingModule L M] [LieModule R L M]

/-- When `y` normalizes a Lie subalgebra `H`, the Lie subalgebra generated by `H` together with `y`
is already spanned by them as a module: its underlying submodule is `R ∙ y ⊔ H.toSubmodule`. -/
theorem lieSpan_insert_toSubmodule (H : LieSubalgebra R L) {y : L} (hy : y ∈ H.normalizer) :
    (lieSpan R L (insert y (H : Set L))).toSubmodule = R ∙ y ⊔ H.toSubmodule := by
  -- the submodule `R ∙ y ⊔ H.toSubmodule` is already closed under the bracket, so it underlies a
  -- Lie subalgebra `K`, which the Lie span is then squeezed between on both sides
  let K : LieSubalgebra R L :=
    { R ∙ y ⊔ H.toSubmodule with
      lie_mem' := fun {_ _} => lie_mem_sup_of_mem_normalizer hy }
  refine le_antisymm ?_ (sup_le ?_ ?_)
  · exact (toSubmodule_le_toSubmodule _ K).mpr <| lieSpan_le.mpr <| Set.insert_subset
      (Submodule.mem_sup_left (Submodule.mem_span_singleton_self y))
      fun _ hz => Submodule.mem_sup_right hz
  · exact Submodule.span_le.mpr <|
      Set.singleton_subset_iff.mpr <| subset_lieSpan (Set.mem_insert _ _)
  · exact fun _ hz => subset_lieSpan (Set.mem_insert_of_mem _ hz)

/-- When `y` normalizes a Lie subalgebra `H`, the elements of the Lie subalgebra spanned by `H`
together with `y` are exactly the `t • y + h` with `t : R` and `h ∈ H`. -/
theorem mem_lieSpan_insert_iff (H : LieSubalgebra R L) {y : L} (hy : y ∈ H.normalizer) {z : L} :
    z ∈ lieSpan R L (insert y (H : Set L)) ↔ ∃ t : R, ∃ h ∈ H, z = t • y + h := by
  rw [← mem_toSubmodule, lieSpan_insert_toSubmodule H hy, Submodule.mem_sup]
  constructor
  · rintro ⟨u, hu, h, hh, rfl⟩
    obtain ⟨t, rfl⟩ := Submodule.mem_span_singleton.mp hu
    exact ⟨t, h, hh, rfl⟩
  · rintro ⟨t, h, hh, rfl⟩
    exact ⟨t • y, Submodule.smul_mem _ t (Submodule.mem_span_singleton_self y), h, hh, rfl⟩

/-- When `y` normalizes a Lie subalgebra `H`, every `t • y + h` with `h ∈ H` lies in the Lie
subalgebra spanned by `H` together with `y`. -/
theorem smul_add_mem_lieSpan_insert (H : LieSubalgebra R L) {y : L} (hy : y ∈ H.normalizer)
    (t : R) {h : L} (hh : h ∈ H) : t • y + h ∈ lieSpan R L (insert y (H : Set L)) :=
  (H.mem_lieSpan_insert_iff hy).mpr ⟨t, h, hh, rfl⟩

/-- **The nilpotent-extension lemma.**  If a Lie subalgebra `H` acts nilpotently on `M`, and an
element `y` normalizing `H` acts nilpotently on `M`, then the Lie subalgebra spanned by `y` and `H`
acts nilpotently on `M`. -/
theorem lieModule_isNilpotent_lieSpan_insert (H : LieSubalgebra R L) {y : L}
    (hy : y ∈ H.normalizer) [LieModule.IsNilpotent H M]
    (hyM : IsNilpotent (LieModule.toEnd R L M y)) :
    LieModule.IsNilpotent (lieSpan R L (insert y (H : Set L))) M := by
  have hHK : H ≤ lieSpan R L (insert y (H : Set L)) :=
    fun _ hx => subset_lieSpan (Set.mem_insert_of_mem _ hx)
  have hyK : y ∈ lieSpan R L (insert y (H : Set L)) := subset_lieSpan (Set.mem_insert _ _)
  have hKN : lieSpan R L (insert y (H : Set L)) ≤ H.normalizer :=
    lieSpan_le.mpr <| Set.insert_subset hy H.le_normalizer
  obtain ⟨I, hI⟩ := exists_nested_lieIdeal_ofLe_normalizer hHK hKN
  -- `LieSubmodule.isNilpotentOfIsNilpotentSpanSupEqTop` needs the spanning equation *inside* the
  -- larger subalgebra.  Both sides are submodules of the Lie span, and the subtype inclusion of
  -- that submodule is injective, so it suffices to check the equation after pushing it forward
  -- into `L`, where it is exactly `lieSpan_insert_toSubmodule`.
  have hI₂ : R ∙ (⟨y, hyK⟩ : lieSpan R L (insert y (H : Set L))) ⊔
      LieSubmodule.toSubmodule I = ⊤ := by
    rw [← LieIdeal.toLieSubalgebra_toSubmodule R (lieSpan R L (insert y (H : Set L))) I, hI]
    apply Submodule.map_injective_of_injective
      ((lieSpan R L (insert y (H : Set L)) : Submodule R L).injective_subtype)
    simp only [coe_ofLe, Submodule.map_sup, Submodule.map_subtype_range_inclusion,
      Submodule.map_top, Submodule.range_subtype]
    rw [Submodule.map_subtype_span_singleton]
    exact (lieSpan_insert_toSubmodule H hy).symm
  -- both equivalences only re-wrap the carrier: `H`, `ofLe hHK` and `I` have the same elements of
  -- `L`, so `⁅f x, m⁆` and `⁅x, m⁆` are literally the same bracket of `L` on `M`, and the
  -- bracket-compatibility hypothesis is definitional
  have hIM : LieModule.IsNilpotent I M :=
    (Equiv.lieModule_isNilpotent_iff
        ((equivOfLe hHK).trans (LieEquiv.ofEq _ _ ((coe_set_eq _ _).mpr hI.symm)))
        (1 : M ≃ₗ[R] M) fun _ _ => rfl).mp ‹_›
  exact LieSubmodule.isNilpotentOfIsNilpotentSpanSupEqTop hI₂ hyM hIM

/-- Every element of the Lie subalgebra spanned by a normalizing element `y` and `H` acts
nilpotently on `M`, as soon as `H` does and `y` does. -/
theorem isNilpotent_toEnd_of_mem_lieSpan_insert (H : LieSubalgebra R L) {y : L}
    (hy : y ∈ H.normalizer) [LieModule.IsNilpotent H M]
    (hyM : IsNilpotent (LieModule.toEnd R L M y)) {z : L}
    (hz : z ∈ lieSpan R L (insert y (H : Set L))) :
    IsNilpotent (LieModule.toEnd R L M z) := by
  have : LieModule.IsNilpotent (lieSpan R L (insert y (H : Set L))) M :=
    H.lieModule_isNilpotent_lieSpan_insert hy hyM
  -- the action of `⟨z, hz⟩` through the subalgebra is the action of `z` through `L`
  rw [← toEnd_mk R L M (lieSpan R L (insert y (H : Set L))) hz]
  exact LieModule.isNilpotent_toEnd_of_isNilpotent R (lieSpan R L (insert y (H : Set L))) M
    ⟨z, hz⟩

/-- The `t • y + h` reading of `LieSubalgebra.isNilpotent_toEnd_of_mem_lieSpan_insert`: if `H` acts
nilpotently on `M` and a normalizing element `y` acts nilpotently on `M`, then so does every
`t • y + h` with `h ∈ H`. -/
theorem isNilpotent_toEnd_smul_add_of_mem (H : LieSubalgebra R L) {y : L}
    (hy : y ∈ H.normalizer) [LieModule.IsNilpotent H M]
    (hyM : IsNilpotent (LieModule.toEnd R L M y)) (t : R) {h : L} (hh : h ∈ H) :
    IsNilpotent (LieModule.toEnd R L M (t • y + h)) :=
  H.isNilpotent_toEnd_of_mem_lieSpan_insert hy hyM (H.smul_add_mem_lieSpan_insert hy t hh)

/-- The pointwise form of the nilpotent-extension lemma: if every element of `H` acts nilpotently on
a Noetherian module `M`, and so does a normalizing element `y`, then so does every element of the
Lie subalgebra spanned by `y` and `H`. -/
theorem isNilpotent_toEnd_of_mem_lieSpan_insert_of_forall [IsNoetherian R M]
    (H : LieSubalgebra R L) {y : L} (hy : y ∈ H.normalizer)
    (hH : ∀ x ∈ H, IsNilpotent (LieModule.toEnd R L M x))
    (hyM : IsNilpotent (LieModule.toEnd R L M y)) {z : L}
    (hz : z ∈ lieSpan R L (insert y (H : Set L))) :
    IsNilpotent (LieModule.toEnd R L M z) := by
  have : LieModule.IsNilpotent H M :=
    -- `LieSubalgebra.toEnd_mk`: the action of `⟨x, hx⟩` through `H` is that of `x` through `L`
    (LieModule.isNilpotent_iff_forall' (R := R)).mpr fun ⟨x, hx⟩ => by
      rw [toEnd_mk R L M H hx]
      exact hH x hx
  exact H.isNilpotent_toEnd_of_mem_lieSpan_insert hy hyM hz

end LieSubalgebra

namespace LieIdeal

variable {R L : Type*} [CommRing R] [LieRing L] [LieAlgebra R L]
variable {M : Type*} [AddCommGroup M] [Module R M] [LieRingModule L M] [LieModule R L M]

/-- The nilpotent-extension lemma for an **ideal** `I` of `L`: the normalizing hypothesis is
automatic, and the elements covered by the conclusion are exactly those of the submodule
`R ∙ y ⊔ I.toSubmodule`, that is, the elements `t • y + x` with `x ∈ I`. -/
theorem isNilpotent_toEnd_of_mem_span_singleton_sup [IsNoetherian R M] (I : LieIdeal R L)
    (hI : ∀ x ∈ I, IsNilpotent (LieModule.toEnd R L M x)) {y : L}
    (hy : IsNilpotent (LieModule.toEnd R L M y)) {z : L}
    (hz : z ∈ (R ∙ y) ⊔ LieSubmodule.toSubmodule I) :
    IsNilpotent (LieModule.toEnd R L M z) := by
  -- every element of `L` normalizes an ideal: `LieIdeal.normalizer_eq_top`
  have hyN : y ∈ (I : LieSubalgebra R L).normalizer := by
    rw [I.normalizer_eq_top]
    exact LieSubalgebra.mem_top y
  have hz' : z ∈ LieSubalgebra.lieSpan R L (insert y ((I : LieSubalgebra R L) : Set L)) := by
    rw [← LieSubalgebra.mem_toSubmodule, LieSubalgebra.lieSpan_insert_toSubmodule _ hyN,
      LieIdeal.toLieSubalgebra_toSubmodule R L I]
    exact hz
  exact (I : LieSubalgebra R L).isNilpotent_toEnd_of_mem_lieSpan_insert_of_forall hyN
    (fun x hx => hI x ((mem_toLieSubalgebra R L I x).mp hx)) hy hz'

/-- The `t • y + x` reading of `LieIdeal.isNilpotent_toEnd_of_mem_span_singleton_sup`: for an ideal
`I` all of whose elements act nilpotently on `M`, and `y` acting nilpotently on `M`, every
`t • y + x` with `x ∈ I` acts nilpotently on `M`. -/
theorem isNilpotent_toEnd_smul_add_of_mem [IsNoetherian R M] (I : LieIdeal R L)
    (hI : ∀ x ∈ I, IsNilpotent (LieModule.toEnd R L M x)) {y : L}
    (hy : IsNilpotent (LieModule.toEnd R L M y)) (t : R) {x : L} (hx : x ∈ I) :
    IsNilpotent (LieModule.toEnd R L M (t • y + x)) :=
  I.isNilpotent_toEnd_of_mem_span_singleton_sup hI hy <| Submodule.add_mem _
    (Submodule.mem_sup_left (Submodule.smul_mem _ t (Submodule.mem_span_singleton_self y)))
    (Submodule.mem_sup_right ((LieSubmodule.mem_toSubmodule I).mpr hx))

end LieIdeal

namespace EpsilonEridani.LieAlgebra

variable {R L : Type*} [CommRing R] [LieRing L] [LieAlgebra R L]

/-- The adjoint specialization of the nilpotent-extension lemma: if `y` is `ad`-nilpotent, then so
is every element of `R ∙ y ⊔ nilradical R L`.  Every element of the nilradical is `ad`-nilpotent, so
no nilpotency hypothesis on the ideal is needed. -/
theorem isNilpotent_ad_of_mem_span_singleton_sup_nilradical [IsNoetherian R L] {y : L}
    (hy : IsNilpotent (_root_.LieAlgebra.ad R L y)) {z : L}
    (hz : z ∈ (R ∙ y) ⊔ LieSubmodule.toSubmodule (nilradical R L)) :
    IsNilpotent (_root_.LieAlgebra.ad R L z) :=
  LieIdeal.isNilpotent_toEnd_of_mem_span_singleton_sup (nilradical R L)
    (fun _ hx => isNilpotent_ad_of_mem_nilradical hx) hy hz

/-- The `t • y + n` reading of `isNilpotent_ad_of_mem_span_singleton_sup_nilradical`: if `y` is
`ad`-nilpotent, then so is `t • y + n` for every `n` in the nilradical. -/
theorem isNilpotent_ad_smul_add_of_mem_nilradical [IsNoetherian R L] {y : L}
    (hy : IsNilpotent (_root_.LieAlgebra.ad R L y)) (t : R) {n : L} (hn : n ∈ nilradical R L) :
    IsNilpotent (_root_.LieAlgebra.ad R L (t • y + n)) :=
  LieIdeal.isNilpotent_toEnd_smul_add_of_mem (nilradical R L)
    (fun _ hx => isNilpotent_ad_of_mem_nilradical hx) hy t hn

end EpsilonEridani.LieAlgebra
