/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Topology.Spectral.ConstructibleTopology
public import Mathlib.Topology.Spectral.Basic

/-!
# Pro-constructible subsets of a spectral space

A subset of a topological space is **pro-constructible** when it is closed for the constructible
topology — the patch topology, generated by the quasi-compact opens and their complements. The
name records the classical description of such a set on a spectral space: an intersection of
finite unions of quasi-compact opens and complements of quasi-compact opens, that is, a filtered
intersection of constructible sets.

The point of the notion is the theorem at the end of this file: a pro-constructible subspace of a
spectral space is again spectral. This is how spectrality is *transported* to those subspaces of a
valuation spectrum that adic geometry obtains by cutting: `Cont A` is closed in `Spv(A,IA)` and
`Spa(A,A⁺)` is pro-constructible in it, and each inherits spectrality this way. Some such
hypothesis is needed, since the naive statement — "a subspace of a spectral space is spectral" —
is false. It is not a universal substitute either: `Spv(A,I)` is *not* obtained from `Spv A` by
such a cut, since the inclusion `Spv(A,I) → Spv A` is not even a spectral map, and its spectrality
is established by a separate retraction argument instead.

## Implementation notes

`IsProConstructible s` is defined as closedness of the copy of `s` in Mathlib's type synonym
`WithConstructibleTopology X`, so that typeclass inference has direct access to the instances
carried by that topology — above all its compactness on a spectral space, which is the engine of
every result below. `EpsilonEridani.isProConstructible_iff_isClosed` is the same statement with the
topology carried explicitly as `IsClosed[constructibleTopology X] s`.

Recall that Mathlib orders topologies by *reverse* inclusion of their open sets, so
`constructibleTopology X ≤ t` says that the constructible topology is finer.

## Main definitions

* `EpsilonEridani.IsProConstructible` — `s` is closed for the constructible topology.

## Main results

* `EpsilonEridani.IsOpen.isOpen_constructibleTopology` — on a prespectral space the constructible
  topology refines the given one; hence `IsClosed.isProConstructible`.
* `IsCompact.isProConstructible` — a quasi-compact open subset is pro-constructible. It is
  in fact clopen for the constructible topology, which is what makes the two previous families
  interact.
* `EpsilonEridani.IsProConstructible.inter`, `.iInter`, `.sInter`, `.union`, `.iUnion` — the calculus of
  pro-constructible subsets. Arbitrary intersections and finite unions are allowed.
* `EpsilonEridani.IsProConstructible.preimage` — pro-constructibility is stable under preimage along a
  spectral map; `EpsilonEridani.IsProConstructible.prod` and `.pi` — and under products when the ambient
  factors complementary to each projection are quasi-compact.
* `EpsilonEridani.IsProConstructible.isCompact` — a pro-constructible subset of a spectral space is
  quasi-compact.
* `EpsilonEridani.IsProConstructible.mem_of_isGenericPoint` — the generic point of the closure of a
  pro-constructible subset of a spectral space lies in that subset. This is the whole content of
  the sobriety half of the main theorem.
* `EpsilonEridani.IsProConstructible.spectralSpace` — **a pro-constructible subspace of a spectral space
  is spectral**, together with `EpsilonEridani.IsProConstructible.isSpectralMap_subtypeVal`: its
  inclusion is a spectral map. `IsClosed.spectralSpace` is the closed special case, the
  counterpart of Mathlib's `Topology.IsOpenEmbedding.spectralSpace`.

## References

* T. Wedhorn, *Adic Spaces*, arXiv:1910.05934v1, §3.
* The Stacks Project, tag 08YF.
-/

public section

namespace EpsilonEridani

open Set Topology TopologicalSpace

variable {X Y : Type*} [tX : TopologicalSpace X] [tY : TopologicalSpace Y]

/-! ### The constructible topology refines the given topology -/

/-- On a prespectral space every open subset is open for the constructible topology: an open set
is a union of quasi-compact opens, and those belong to the defining subbasis. -/
theorem IsOpen.isOpen_constructibleTopology [PrespectralSpace X] {s : Set X} (hs : IsOpen s) :
    IsOpen[constructibleTopology X] s := by
  rw [(PrespectralSpace.isTopologicalBasis (X := X)).open_eq_sUnion' hs]
  refine @isOpen_sUnion X (constructibleTopology X) _ ?_
  rintro U ⟨⟨hUo, hUc⟩, -⟩
  exact hUc.isOpen_constructibleTopology_of_isOpen hUo

/-- The copy in `WithConstructibleTopology X` of an open subset of a prespectral space is open. -/
theorem IsOpen.isOpen_preimage_ofTopology [PrespectralSpace X] {s : Set X} (hs : IsOpen s) :
    IsOpen (WithTopology.ofTopology ⁻¹' s : Set (WithConstructibleTopology X)) :=
  WithConstructibleTopology.isOpen_iff.2 (IsOpen.isOpen_constructibleTopology hs)

variable (X) in
/-- On a prespectral space the identity map from the constructible topology to the given topology
is continuous. -/
theorem continuous_ofTopology_withConstructibleTopology [PrespectralSpace X] :
    Continuous (WithTopology.ofTopology : WithConstructibleTopology X → X) :=
  continuous_def.2 fun _ hs ↦ IsOpen.isOpen_preimage_ofTopology hs

/-! ### Pro-constructible subsets -/

/-- A subset of a topological space is **pro-constructible** if it is closed for the constructible
topology. On a spectral space these are exactly the filtered intersections of constructible
subsets, whence the name.

The definition is phrased through Mathlib's type synonym `WithConstructibleTopology X`;
`EpsilonEridani.isProConstructible_iff_isClosed` is the same statement with the topology explicit. -/
def IsProConstructible (s : Set X) : Prop :=
  IsClosed (WithTopology.ofTopology ⁻¹' s : Set (WithConstructibleTopology X))

/-- Pro-constructibility of `s` is closedness of `s` for the constructible topology of `X`,
carried explicitly as `IsClosed[constructibleTopology X] s` rather than through the type synonym
`WithConstructibleTopology X` used in the definition. -/
theorem isProConstructible_iff_isClosed {s : Set X} :
    IsProConstructible s ↔ IsClosed[constructibleTopology X] s :=
  WithConstructibleTopology.isClosed_iff

@[simp]
theorem isProConstructible_empty : IsProConstructible (∅ : Set X) := by
  simp [IsProConstructible]

@[simp]
theorem isProConstructible_univ : IsProConstructible (univ : Set X) := by
  simp [IsProConstructible]

theorem IsProConstructible.inter {s t : Set X} (hs : IsProConstructible s)
    (ht : IsProConstructible t) : IsProConstructible (s ∩ t) :=
  IsClosed.inter hs ht

theorem IsProConstructible.union {s t : Set X} (hs : IsProConstructible s)
    (ht : IsProConstructible t) : IsProConstructible (s ∪ t) :=
  IsClosed.union hs ht

/-- A finite indexed union of pro-constructible subsets is pro-constructible. -/
theorem IsProConstructible.iUnion {ι : Type*} [Finite ι] {f : ι → Set X}
    (hf : ∀ i, IsProConstructible (f i)) : IsProConstructible (⋃ i, f i) := by
  rw [IsProConstructible, Set.preimage_iUnion]
  exact isClosed_iUnion_of_finite hf

/-- A union of pro-constructible subsets over a finite set is pro-constructible. -/
theorem _root_.Set.Finite.isProConstructible_biUnion {ι : Type*} {I : Set ι} {f : ι → Set X}
    (hI : I.Finite) (hf : ∀ i ∈ I, IsProConstructible (f i)) :
    IsProConstructible (⋃ i ∈ I, f i) := by
  simp only [IsProConstructible, Set.preimage_iUnion]
  exact hI.isClosed_biUnion hf

/-- A union of pro-constructible subsets over a finset is pro-constructible. -/
theorem _root_.Finset.isProConstructible_biUnion {ι : Type*} (I : Finset ι) {f : ι → Set X}
    (hf : ∀ i ∈ I, IsProConstructible (f i)) : IsProConstructible (⋃ i ∈ I, f i) :=
  Set.Finite.isProConstructible_biUnion I.finite_toSet hf

theorem IsProConstructible.iInter {ι : Sort*} {f : ι → Set X}
    (hf : ∀ i, IsProConstructible (f i)) : IsProConstructible (⋂ i, f i) := by
  rw [IsProConstructible, Set.preimage_iInter]
  exact isClosed_iInter hf

theorem IsProConstructible.biInter {ι : Sort*} {p : ι → Prop} {f : ∀ i, p i → Set X}
    (hf : ∀ i hi, IsProConstructible (f i hi)) : IsProConstructible (⋂ i, ⋂ hi, f i hi) :=
  IsProConstructible.iInter fun i ↦ IsProConstructible.iInter (hf i)

theorem IsProConstructible.sInter {S : Set (Set X)} (hS : ∀ s ∈ S, IsProConstructible s) :
    IsProConstructible (⋂₀ S) := by
  rw [Set.sInter_eq_iInter]
  exact IsProConstructible.iInter fun s ↦ hS s.1 s.2

/-- A quasi-compact open subset is pro-constructible: it is even clopen for the constructible
topology, since it and its complement both belong to the defining subbasis. -/
theorem _root_.IsCompact.isProConstructible {s : Set X} (hcomp : IsCompact s) (hopen : IsOpen s) :
    IsProConstructible s :=
  isProConstructible_iff_isClosed.2 <|
    (@isOpen_compl_iff X s (constructibleTopology X)).1 <|
      IsCompact.isOpen_constructibleTopology_of_isClosed (by simpa using hcomp)
        hopen.isClosed_compl

/-- A closed subset of a prespectral space is pro-constructible. -/
theorem _root_.IsClosed.isProConstructible [PrespectralSpace X] {s : Set X} (hs : IsClosed s) :
    IsProConstructible s := by
  rw [IsProConstructible, ← isOpen_compl_iff, ← Set.preimage_compl]
  exact IsOpen.isOpen_preimage_ofTopology hs.isOpen_compl

/-! ### Functoriality -/

/-- A spectral map is continuous for the constructible topologies: it pulls the defining subbasis
back into itself. -/
theorem IsSpectralMap.continuous_constructibleTopology {f : X → Y} (hf : IsSpectralMap f) :
    Continuous[constructibleTopology X, constructibleTopology Y] f := by
  refine continuous_generateFrom_iff.2 fun U hU ↦ ?_
  obtain ⟨hUo, hUc⟩ | ⟨hUcl, hUcc⟩ := hU
  · exact (hUc.preimage_of_isOpen hf hUo).isOpen_constructibleTopology_of_isOpen
      (hUo.preimage hf.continuous)
  · refine IsCompact.isOpen_constructibleTopology_of_isClosed ?_ (hUcl.preimage hf.continuous)
    rw [← Set.preimage_compl]
    exact hUcc.preimage_of_isOpen hf hUcl.isOpen_compl

/-- Pro-constructible subsets pull back along spectral maps. -/
theorem IsProConstructible.preimage {f : X → Y} {s : Set Y} (hs : IsProConstructible s)
    (hf : IsSpectralMap f) : IsProConstructible (f ⁻¹' s) :=
  isProConstructible_iff_isClosed.2
    (@IsClosed.preimage X Y (constructibleTopology X) (constructibleTopology Y) f
      (IsSpectralMap.continuous_constructibleTopology hf) s
      (isProConstructible_iff_isClosed.1 hs))

/-- Evaluation at a coordinate `i` is a spectral map as soon as every *other* factor is
quasi-compact: the preimage of a quasi-compact open is a box with that set in the `i`-th slot and
the whole space elsewhere, so only those other slots need a compactness hypothesis. -/
theorem isSpectralMap_eval {ι : Type*} {Z : ι → Type*} [∀ i, TopologicalSpace (Z i)] (i : ι)
    (hZ : ∀ j, j ≠ i → IsCompact (univ : Set (Z j))) :
    IsSpectralMap (fun f : ∀ i, Z i ↦ f i) where
  toContinuous := continuous_apply i
  isCompact_preimage_of_isOpen := fun U _ hUc ↦ by
    classical
    have hpre : (fun f : ∀ i, Z i ↦ f i) ⁻¹' U =
        Set.pi univ (Function.update (fun _ ↦ univ) i U) := Set.eval_preimage
    rw [hpre]
    refine isCompact_univ_pi fun j ↦ ?_
    rcases eq_or_ne j i with rfl | hj
    · simpa using hUc
    · rw [Function.update_of_ne hj]
      exact hZ j hj

/-- A product of two pro-constructible subsets in compact ambient spaces is pro-constructible. -/
theorem IsProConstructible.prod [CompactSpace X] [CompactSpace Y] {s : Set X} {t : Set Y}
    (hs : IsProConstructible s) (ht : IsProConstructible t) : IsProConstructible (s ×ˢ t) := by
  rw [Set.prod_eq]
  exact (hs.preimage isProperMap_fst_of_compactSpace.isSpectralMap).inter
    (ht.preimage isProperMap_snd_of_compactSpace.isSpectralMap)

/-- A product of a family of pro-constructible subsets is pro-constructible when, for each
coordinate, every other ambient factor is quasi-compact. -/
theorem IsProConstructible.pi {ι : Type*} {Z : ι → Type*} [∀ i, TopologicalSpace (Z i)]
    {s : ∀ i, Set (Z i)} (hZ : ∀ i j, j ≠ i → IsCompact (univ : Set (Z j)))
    (hs : ∀ i, IsProConstructible (s i)) : IsProConstructible (Set.pi univ s) := by
  have hpi : Set.pi univ s = ⋂ i, (fun f : ∀ i, Z i ↦ f i) ⁻¹' s i := by ext f; simp
  rw [hpi]
  exact IsProConstructible.iInter fun i ↦
    (hs i).preimage (isSpectralMap_eval i (hZ i))

/-! ### Pro-constructible subspaces of a spectral space -/

section Spectral

variable [SpectralSpace X] {s : Set X}

/-- A pro-constructible subset of a spectral space is quasi-compact: it is closed in the
constructible topology, which is compact. -/
theorem IsProConstructible.isCompact (hs : IsProConstructible s) : IsCompact s := by
  have h : IsCompact (WithTopology.ofTopology ⁻¹' s : Set (WithConstructibleTopology X)) :=
    IsClosed.isCompact hs
  have h' := h.image (continuous_ofTopology_withConstructibleTopology X)
  rwa [Set.image_preimage_eq _ (WithTopology.ofTopology_surjective _)] at h'

/-- **The key sobriety step.** If `s` is pro-constructible in a spectral space and `η` is a
generic point of the closure of `s`, then `η ∈ s`.

The quasi-compact open neighbourhoods of `η` form a filtered family — this is quasi-separatedness
— and each meets `s` because `η` adheres to `s`. The traces `s ∩ U` are closed for the
constructible topology, so patch compactness produces a common point `ζ ∈ s` of all of them. Then
`ζ` lies in every quasi-compact open neighbourhood of `η`, that is `η ∈ closure {ζ}`, while
`ζ ∈ s` gives `closure {ζ} ⊆ closure s = closure {η}`. The two points are therefore topologically
indistinguishable, hence equal. -/
theorem IsProConstructible.mem_of_isGenericPoint (hs : IsProConstructible s) {η : X}
    (hη : IsGenericPoint η (closure s)) : η ∈ s := by
  have hmem : η ∈ closure s := hη ▸ subset_closure (mem_singleton η)
  have hne : Nonempty {U : Set X // IsOpen U ∧ IsCompact U ∧ η ∈ U} :=
    ⟨⟨univ, isOpen_univ, isCompact_univ, mem_univ η⟩⟩
  have hcl : ∀ U : {U : Set X // IsOpen U ∧ IsCompact U ∧ η ∈ U},
      IsClosed (WithTopology.ofTopology ⁻¹' (s ∩ U.1) : Set (WithConstructibleTopology X)) :=
    fun U ↦ hs.inter (U.2.2.1.isProConstructible U.2.1)
  have hnonempty : ∀ U : {U : Set X // IsOpen U ∧ IsCompact U ∧ η ∈ U},
      (WithTopology.ofTopology ⁻¹' (s ∩ U.1) : Set (WithConstructibleTopology X)).Nonempty :=
    fun U ↦ by
      obtain ⟨x, hxU, hxs⟩ := mem_closure_iff.1 hmem U.1 U.2.1 U.2.2.2
      exact ⟨WithTopology.toTopology _ x, hxs, hxU⟩
  have hdir : Directed (· ⊇ ·)
      fun U : {U : Set X // IsOpen U ∧ IsCompact U ∧ η ∈ U} ↦
        (WithTopology.ofTopology ⁻¹' (s ∩ U.1) : Set (WithConstructibleTopology X)) := by
    rintro ⟨U, hUo, hUc, hUη⟩ ⟨V, hVo, hVc, hVη⟩
    refine ⟨⟨U ∩ V, hUo.inter hVo,
      QuasiSeparatedSpace.inter_isCompact U V hUo hUc hVo hVc, hUη, hVη⟩, ?_, ?_⟩
    · exact fun x hx ↦ ⟨hx.1, hx.2.1⟩
    · exact fun x hx ↦ ⟨hx.1, hx.2.2⟩
  obtain ⟨x, hx⟩ := IsCompact.nonempty_iInter_of_directed_nonempty_isCompact_isClosed
    (fun U : {U : Set X // IsOpen U ∧ IsCompact U ∧ η ∈ U} ↦
      (WithTopology.ofTopology ⁻¹' (s ∩ U.1) : Set (WithConstructibleTopology X)))
    hdir hnonempty (fun U ↦ (hcl U).isCompact) hcl
  rw [Set.mem_iInter] at hx
  have hζs : WithTopology.ofTopology x ∈ s := (hx ⟨univ, isOpen_univ, isCompact_univ, mem_univ η⟩).1
  -- `ζ` lies in every quasi-compact open neighbourhood of `η`, hence `η ∈ closure {ζ}`.
  have hηζ : η ∈ closure ({WithTopology.ofTopology x} : Set X) := by
    rw [mem_closure_iff]
    intro o ho hηo
    obtain ⟨U, ⟨hUo, hUc⟩, hηU, hUo'⟩ :=
      PrespectralSpace.isTopologicalBasis.exists_subset_of_mem_open hηo ho
    exact ⟨_, hUo' (hx ⟨U, hUo, hUc, hηU⟩).2, rfl⟩
  -- Conversely `ζ ∈ s ⊆ closure s = closure {η}`.
  have hζη : WithTopology.ofTopology x ∈ closure ({η} : Set X) := by
    rw [hη]; exact subset_closure hζs
  have hζeq : WithTopology.ofTopology x = η :=
    ((specializes_iff_mem_closure.2 hηζ).antisymm (specializes_iff_mem_closure.2 hζη)).eq
  exact hζeq ▸ hζs

/-- The inclusion of a pro-constructible subset of a spectral space is a spectral map: the trace
on it of a quasi-compact open is again pro-constructible, hence quasi-compact. -/
theorem IsProConstructible.isSpectralMap_subtypeVal (hs : IsProConstructible s) :
    IsSpectralMap ((↑) : s → X) where
  toContinuous := continuous_subtype_val
  isCompact_preimage_of_isOpen := fun _ hUo hUc ↦ by
    rw [Subtype.isCompact_iff, Subtype.image_preimage_coe]
    exact IsProConstructible.isCompact (hs.inter (hUc.isProConstructible hUo))

/-- A pro-constructible subspace of a spectral space is quasi-compact. -/
theorem IsProConstructible.compactSpace (hs : IsProConstructible s) : CompactSpace s :=
  isCompact_iff_compactSpace.1 hs.isCompact

/-- A pro-constructible subspace of a spectral space has a basis of quasi-compact opens: the
traces of the quasi-compact opens of the ambient space. -/
theorem IsProConstructible.prespectralSpace (hs : IsProConstructible s) : PrespectralSpace s :=
  .of_isInducing _ IsEmbedding.subtypeVal.isInducing hs.isSpectralMap_subtypeVal

/-- A pro-constructible subspace of a spectral space is quasi-separated: on the basis of traces
of quasi-compact opens, quasi-separatedness is inherited from the ambient space. -/
theorem IsProConstructible.quasiSeparatedSpace (hs : IsProConstructible s) :
    QuasiSeparatedSpace s := by
  refine QuasiSeparatedSpace.of_isTopologicalBasis
    (b := fun U : {U : Set X // IsOpen U ∧ IsCompact U} ↦ ((↑) : s → X) ⁻¹' U.1) ?_ ?_
  · have h := Topology.IsInducing.isTopologicalBasis (f := ((↑) : s → X))
      IsEmbedding.subtypeVal.isInducing (PrespectralSpace.isTopologicalBasis (X := X))
    convert h using 1
    ext V
    simp [Set.range, Subtype.exists, eq_comm]
  · rintro ⟨U, hUo, hUc⟩ ⟨V, hVo, hVc⟩
    rw [← Set.preimage_inter]
    exact hs.isSpectralMap_subtypeVal.isCompact_preimage_of_isOpen (hUo.inter hVo)
      (QuasiSeparatedSpace.inter_isCompact U V hUo hUc hVo hVc)

/-- A pro-constructible subspace of a spectral space is sober. An irreducible closed subset `Z`
of it has irreducible image in the ambient space, whose closure has a generic point `η`; the
image of `Z` is pro-constructible, so `η` lies in it by
`EpsilonEridani.IsProConstructible.mem_of_isGenericPoint`, and its preimage generates `Z`. -/
theorem IsProConstructible.quasiSober (hs : IsProConstructible s) : QuasiSober s where
  sober := by
    intro Z hZirr hZcl
    have hZ' : IsProConstructible (((↑) : s → X) '' Z) := by
      obtain ⟨C, hC, rfl⟩ := IsEmbedding.subtypeVal.isInducing.isClosed_iff.1 hZcl
      rw [Subtype.image_preimage_coe]
      exact hs.inter (IsClosed.isProConstructible hC)
    obtain ⟨η, hη⟩ := QuasiSober.sober
      (hZirr.image _ continuous_subtype_val.continuousOn).closure isClosed_closure
    obtain ⟨ζ, hζZ, rfl⟩ := hZ'.mem_of_isGenericPoint hη
    refine ⟨ζ, ?_⟩
    have h₁ := IsEmbedding.subtypeVal.isInducing.closure_eq_preimage_closure_image
      ({ζ} : Set s)
    have h₂ := IsEmbedding.subtypeVal.isInducing.closure_eq_preimage_closure_image (Z : Set s)
    rw [isGenericPoint_def, h₁, Set.image_singleton, hη, ← h₂, hZcl.closure_eq]

/-- **A pro-constructible subspace of a spectral space is spectral.**

This is the transport principle behind the spectrality of `Cont A` and of `Spa(A,A⁺)` in adic
geometry: both are obtained by cutting a space already known to be spectral along a
pro-constructible condition. `Spv(A,I)` is not of this form and is handled separately. -/
theorem IsProConstructible.spectralSpace (hs : IsProConstructible s) : SpectralSpace s where
  __ := hs.compactSpace
  __ := hs.quasiSober
  __ := hs.quasiSeparatedSpace
  __ := hs.prespectralSpace

/-- A closed subspace of a spectral space is spectral. Mathlib has the open counterpart,
`Topology.IsOpenEmbedding.spectralSpace`; this is the closed one. -/
theorem _root_.IsClosed.spectralSpace (hs : IsClosed s) : SpectralSpace s :=
  IsProConstructible.spectralSpace (IsClosed.isProConstructible hs)

end Spectral

end EpsilonEridani
