/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Codex
-/
module

public import EpsilonEridani.LinearAlgebra.QuadraticForm.CartanDieudonne.SpecialOrthogonal
import EpsilonEridani.LinearAlgebra.QuadraticForm.Radical
public import EpsilonEridani.LinearAlgebra.Matrix.OrthogonalGroup.QuadraticForm
import Mathlib.LinearAlgebra.Matrix.ToLinearEquiv

/-!
# Reflection-pair generation in matrix coordinates

The determinant-one matrices preserving the standard symmetric form are generated by pairs of
reflections. This file translates the abstract quadratic-space generation theorem into the
matrix model `Matrix.specialOrthogonalGroup`, the model represented by the special orthogonal
coordinate Hopf algebra. Generation holds over every field of characteristic different from
two, with no positivity hypothesis on the dimension.

## References

* H. B. Lawson and M.-L. Michelsohn, *Spin Geometry* (1989), Chapter I, §2.
-/

public section

namespace EpsilonEridani

open Matrix

universe u v

variable {n : Type v} [Fintype n] [DecidableEq n]

variable {K : Type u} [Field K] [NeZero (2 : K)]

/-- The matrix special orthogonal group is generated, as a monoid, by the matrices of products
of two reflections in the standard quadratic form. -/
theorem closure_reflection_mul_eq_matrixSpecialOrthogonalGroup :
    let Q := Matrix.toQuadraticForm' (1 : Matrix n n K)
    Submonoid.closure {A : Matrix n n K |
      ∃ (v w : n → K) (_ : Invertible (Q v)) (_ : Invertible (Q w)),
        LinearMap.toMatrix' (QuadraticMap.reflection Q v).toLinearMap *
          LinearMap.toMatrix' (QuadraticMap.reflection Q w).toLinearMap = A} =
      Matrix.specialOrthogonalGroup n K := by
  let _ : Invertible (2 : K) := invertibleOfNonzero (NeZero.ne (2 : K))
  let Q := Matrix.toQuadraticForm' (1 : Matrix n n K)
  let S : Set (Matrix n n K) := {A |
    ∃ (v w : n → K) (_ : Invertible (Q v)) (_ : Invertible (Q w)),
      LinearMap.toMatrix' (QuadraticMap.reflection Q v).toLinearMap *
        LinearMap.toMatrix' (QuadraticMap.reflection Q w).toLinearMap = A}
  have hQ : Q.Nondegenerate := by
    apply LinearMap.BilinForm.Nondegenerate.toQuadraticMap
      ((Matrix.nondegenerate_toLinearMap₂'_iff).mpr (by
        rw [Matrix.nondegenerate_iff_det_ne_zero]
        simp))
    apply LinearMap.ext₂
    intro x y
    simp only [LinearMap.flip_apply, Matrix.toLinearMap₂'_apply', Matrix.one_mulVec]
    exact dotProduct_comm y x
  let F : ((n → K) ≃ₗ[K] (n → K)) →* Matrix n n K :=
    LinearMap.toMatrixAlgEquiv'.toAlgHom.toMonoidHom.comp
      LinearEquiv.automorphismGroup.toLinearMapMonoidHom
  have hF (e : (n → K) ≃ₗ[K] (n → K)) : F e = LinearMap.toMatrix' e.toLinearMap := by
    ext i j
    simp [F, LinearMap.toMatrix'_apply]
  apply le_antisymm
  · apply Submonoid.closure_le.mpr
    rintro _ ⟨v, w, hv, hw, rfl⟩
    rw [← hF, ← hF, ← map_mul, hF]
    apply (toMatrix_mem_specialOrthogonalGroup_iff K n
      ((isUnit_of_invertible (2 : K)).isSMulRegular K) _).mpr
    apply QuadraticMap.mem_specialOrthogonalGroup_iff.mpr
    exact ⟨(QuadraticMap.orthogonalGroup Q).mul_mem
      (QuadraticMap.reflection_mem_orthogonalGroup Q v)
      (QuadraticMap.reflection_mem_orthogonalGroup Q w), by simp⟩
  · intro A hA
    have hunit : IsUnit A := (Matrix.isUnit_iff_isUnit_det A).mpr
      (by rw [(Matrix.mem_specialOrthogonalGroup_iff.mp hA).2]; exact isUnit_one)
    let e := A.toLinearEquiv' hunit.invertible
    have he : LinearMap.toMatrix' e.toLinearMap = A := by
      rw [Matrix.toLinearEquiv'_apply, LinearMap.toMatrix'_toLin']
    have hmem := (toMatrix_mem_specialOrthogonalGroup_iff K n
      ((isUnit_of_invertible (2 : K)).isSMulRegular K) e).mp (he.symm ▸ hA)
    have hle := QuadraticMap.specialOrthogonalGroup_le_of_reflection_mul_mem Q hQ
      ((Submonoid.closure S).comap F) (fun v w hv hw ↦ ?_)
    · simpa only [Submonoid.mem_comap, hF, he] using hle hmem
    · rw [Submonoid.mem_comap, map_mul, hF, hF]
      exact Submonoid.subset_closure ⟨v, w, hv, hw, rfl⟩

end EpsilonEridani
