/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.RingTheory.DedekindDomain.Ideal.Basic
public import EpsilonEridani.NumberTheory.LocalField.NormalizedValuation

/-!
# Principal fractional ideals of a nonarchimedean local field

The fractional ideals of the ring of integers `𝒪[K]` of a valued field `K` that are generated by
one element are ordered by the valuation: `x 𝒪[K] ≤ y 𝒪[K]` exactly when `v(x) ≤ v(y)`. For a
nonarchimedean local field, whose ring of integers is a discrete valuation ring, the principal
fractional ideal generated by `x ≠ 0` is the power `𝓂[K] ^ v_K(x)` of the maximal ideal, for the
normalized valuation `v_K`.

## Main results

* `EpsilonEridani.spanSingleton_le_spanSingleton_iff_valuation_le`: inclusion of principal fractional
  ideals is the order of the valuation.
* `Units.spanSingleton_eq_maximalIdeal_zpow`: `x 𝒪[K] = 𝓂[K] ^ v_K(x)`.
-/

public section

open ValuativeRel

namespace EpsilonEridani

section Valuation

variable {K : Type*} [Field K] [ValuativeRel K]

/-- Inclusion of principal fractional ideals of the ring of integers of a valued field is the
reverse of divisibility, that is, the order of the valuation. -/
theorem spanSingleton_le_spanSingleton_iff_valuation_le {x y : K} :
    FractionalIdeal.spanSingleton (nonZeroDivisors 𝒪[K]) x ≤
        FractionalIdeal.spanSingleton (nonZeroDivisors 𝒪[K]) y ↔
      valuation K x ≤ valuation K y := by
  rw [FractionalIdeal.spanSingleton_le_iff_mem, FractionalIdeal.mem_spanSingleton]
  constructor
  · rintro ⟨z, rfl⟩
    rw [Subring.smul_def, smul_eq_mul, map_mul]
    exact mul_le_of_le_one_left' z.2
  · intro h
    rcases eq_or_ne y 0 with rfl | hy
    · exact ⟨0, by simp_all⟩
    refine ⟨⟨x / y, ?_⟩, ?_⟩
    · rw [Valuation.mem_integer_iff, map_div₀]
      exact div_le_one_of_le₀ h zero_le
    · rw [Subring.smul_def, smul_eq_mul, div_mul_cancel₀ x hy]

end Valuation

end EpsilonEridani

namespace Units

open EpsilonEridani

variable {K : Type*} [Field K] [ValuativeRel K] [TopologicalSpace K]
  [IsNonarchimedeanLocalField K]

/-- The principal fractional ideal generated by `x : Kˣ` is `𝓂[K] ^ v_K(x)`. -/
theorem spanSingleton_eq_maximalIdeal_zpow (x : Kˣ) :
    FractionalIdeal.spanSingleton (nonZeroDivisors 𝒪[K]) (x : K) =
      ((IsLocalRing.maximalIdeal 𝒪[K] : Ideal 𝒪[K]) : FractionalIdeal (nonZeroDivisors 𝒪[K]) K) ^
        (normalizedValuation K x).toAdd := by
  obtain ⟨π, hπ⟩ := IsDiscreteValuationRing.exists_irreducible 𝒪[K]
  have hπ0 : (π : K) ≠ 0 := fun h => hπ.ne_zero (Subtype.ext h)
  set n := (normalizedValuation K x).toAdd
  have hπn : normalizedValuation K (Units.mk0 (π : K) hπ0 ^ n) = normalizedValuation K x := by
    rw [map_zpow, normalizedValuation_irreducible hπ, ← ofAdd_zsmul, _root_.smul_eq_mul, mul_one,
      ofAdd_toAdd]
  have hv : valuation K (x : K) = valuation K ((π : K) ^ n) := by
    have h₁ := (toAdd_normalizedValuation_le_iff_valuation_le (Units.mk0 (π : K) hπ0 ^ n) x).mp
      (by rw [hπn])
    have h₂ := (toAdd_normalizedValuation_le_iff_valuation_le x (Units.mk0 (π : K) hπ0 ^ n)).mp
      (by rw [hπn])
    simp only [Units.val_zpow_eq_zpow_val, Units.val_mk0] at h₁ h₂
    exact le_antisymm h₁ h₂
  have h𝓂 : ((IsLocalRing.maximalIdeal 𝒪[K] : Ideal 𝒪[K]) :
      FractionalIdeal (nonZeroDivisors 𝒪[K]) K) = FractionalIdeal.spanSingleton _ (π : K) := by
    rw [hπ.maximalIdeal_eq, FractionalIdeal.coeIdeal_span_singleton]
    -- The algebra map out of `𝒪[K]` is the subtype coercion.
    rfl
  rw [le_antisymm (spanSingleton_le_spanSingleton_iff_valuation_le.mpr hv.le)
    (spanSingleton_le_spanSingleton_iff_valuation_le.mpr hv.ge), h𝓂]
  rcases Int.eq_nat_or_neg n with ⟨m, hm | hm⟩ <;> rw [hm]
  · rw [zpow_natCast, zpow_natCast, FractionalIdeal.spanSingleton_pow]
  · rw [zpow_neg, zpow_neg, zpow_natCast, zpow_natCast, FractionalIdeal.spanSingleton_pow,
      FractionalIdeal.spanSingleton_inv]

end Units
