/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.GroupTheory.IsPerfect
public import EpsilonEridani.GroupTheory.SpecificGroups.CFSG.Suzuki.Torus

/-!
# The Suzuki groups are perfect

For `n ≠ 0` the generated Suzuki group `EpsilonEridani.suzukiGroup n`, the subgroup of
`GL₄(𝔽_(2^(2n+1)))` generated by the unipotent matrices `u(a, b)` and the Weyl element `w`, is
its own derived subgroup. The restriction is necessary: `EpsilonEridani.suzukiGroup 0` is the solvable
group `Sz(2)`.

The derived subgroup `D` is shown to contain every generator. The torus `h(κ)` of
`EpsilonEridani.GroupTheory.SpecificGroups.CFSG.Suzuki.Torus` lies in the group and conjugates `u(a, b)`
to `u(κ^θ κ⁻² a, κ^(-θ) b)`, `θ = 2^(n+1)`, so its commutators with the unipotent generators are

```text
[h(κ), u(0, b)] = u(0, (κ^(-θ) + 1) b),
[h(κ), u(a, 0)] = u((λ + 1) a, (λ + 1) a^(1+θ)),      λ = κ^θ κ⁻².
```

For `n ≠ 0` the generator field has a unit with `κ^θ ≠ κ^2`, so `λ ≠ 1` and `κ^θ ≠ 1`, and the
two commutator families together with the multiplication rule `u(a, b') u(0, b + b') = u(a, b)`
put every `u(a, b)` in `D`. The Weyl element then follows from the rank-one Bruhat relation at
`b = 1`, `w u(0, 1) w = u(1, 1) w u(1, 0)`, since `w u(0, 1) w = [w, u(0, 1)] u(0, 1)` is in
`D` once `u(0, 1)` is.

Nothing here concerns the centre of the group, its order, or its simplicity.

## Main results

* `EpsilonEridani.Suzuki.commutator_suzukiGroup_eq_self`: for `n ≠ 0` the Suzuki group is its own
  derived subgroup.
* `EpsilonEridani.Suzuki.isPerfect_suzukiGroup`: for `n ≠ 0` the Suzuki group is perfect.

## References

* M. Suzuki, *On a class of doubly transitive groups*, Annals of Mathematics **75** (1962),
  105--145.
* R. A. Wilson, *The Finite Simple Groups*, Springer GTM 251 (2009), §4.2.
-/

public section

noncomputable section

open scoped commutatorElement

namespace EpsilonEridani

namespace Suzuki

variable {n : ℕ}

/-! ## The unipotent generators lie in the derived subgroup -/

/-- For `n ≠ 0` every long-root generator `u(0, b)` lies in the derived subgroup of the Suzuki
group; it is a commutator of a torus element with another long-root generator. -/
private theorem unipotent_zero_mem_commutator_suzukiGroup (hn : n ≠ 0)
    (b : GaloisField 2 (2 * n + 1)) :
    unipotent n 0 b ∈ ⁅suzukiGroup n, suzukiGroup n⁆ := by
  obtain ⟨κ, hκ⟩ := exists_pow_two_pow_succ_ne_sq n hn
  have hμ : ((κ : GaloisField 2 (2 * n + 1)) ^ 2 ^ (n + 1))⁻¹ + 1 ≠ 0 := by
    intro h0
    have h1 : (κ : GaloisField 2 (2 * n + 1)) ^ 2 ^ (n + 1) = 1 := by
      simpa using CharTwo.add_eq_zero.mp h0
    apply hκ
    rw [h1, ← pow_two_pow_succ_pow_two_pow_succ n (κ : GaloisField 2 (2 * n + 1)), h1, one_pow]
  have key := Subgroup.commutator_mem_commutator (torus_mem_suzukiGroup n κ)
    (unipotent_mem_suzukiGroup 0 (b / (((κ : GaloisField 2 (2 * n + 1)) ^ 2 ^ (n + 1))⁻¹ + 1)))
  rw [commutatorElement_torus_unipotent] at key
  simpa [mul_div_cancel₀ _ hμ] using key

/-- For `n ≠ 0` every unipotent generator `u(a, b)` lies in the derived subgroup of the Suzuki
group. -/
private theorem unipotent_mem_commutator_suzukiGroup (hn : n ≠ 0)
    (a b : GaloisField 2 (2 * n + 1)) :
    unipotent n a b ∈ ⁅suzukiGroup n, suzukiGroup n⁆ := by
  obtain ⟨κ, hκ⟩ := exists_pow_two_pow_succ_ne_sq n hn
  set l : GaloisField 2 (2 * n + 1) :=
    (κ : GaloisField 2 (2 * n + 1)) ^ 2 ^ (n + 1) / (κ : GaloisField 2 (2 * n + 1)) ^ 2 + 1 with hl
  have hl0 : l ≠ 0 := by
    intro h0
    exact hκ ((div_eq_one_iff_eq (pow_ne_zero _ κ.ne_zero)).mp (CharTwo.add_eq_zero.mp h0))
  clear_value l
  have key := Subgroup.commutator_mem_commutator (torus_mem_suzukiGroup n κ)
    (unipotent_mem_suzukiGroup (a / l) 0)
  rw [commutatorElement_torus_unipotent, ← hl] at key
  have h2 := mul_mem key
    (unipotent_zero_mem_commutator_suzukiGroup hn (b + l * (a / l) * (a / l) ^ 2 ^ (n + 1)))
  rw [unipotent_mul_unipotent] at h2
  convert h2 using 2
  · rw [mul_div_cancel₀ _ hl0, add_zero]
  · simp only [mul_zero, zero_add, zero_pow (pow_ne_zero _ two_ne_zero), add_zero]
    linear_combination (-(l * (a / l) * (a / l) ^ 2 ^ (n + 1))) *
      (CharTwo.two_eq_zero : (2 : GaloisField 2 (2 * n + 1)) = 0)

/-! ## The Weyl generator lies in the derived subgroup -/

/-- For `n ≠ 0` the Weyl generator lies in the derived subgroup of the Suzuki group. -/
private theorem weyl_mem_commutator_suzukiGroup (hn : n ≠ 0) :
    weyl n ∈ ⁅suzukiGroup n, suzukiGroup n⁆ := by
  have hrel := weyl_mul_unipotent_zero_mul_weyl n 1 one_ne_zero
  simp only [one_pow, div_one, inv_one, Units.mk0_one, map_one, mul_one] at hrel
  have hconj : weyl n * unipotent n 0 1 * weyl n ∈ ⁅suzukiGroup n, suzukiGroup n⁆ := by
    have : weyl n * unipotent n 0 1 * weyl n = ⁅weyl n, unipotent n 0 1⁆ * unipotent n 0 1 := by
      rw [commutatorElement_def, weyl_inv]
      group
    rw [this]
    exact mul_mem (Subgroup.commutator_mem_commutator weyl_mem_suzukiGroup
      (unipotent_mem_suzukiGroup 0 1)) (unipotent_mem_commutator_suzukiGroup hn 0 1)
  have : weyl n = (unipotent n 1 1)⁻¹ * (weyl n * unipotent n 0 1 * weyl n) *
      (unipotent n 1 0)⁻¹ := by
    rw [hrel]
    group
  rw [this]
  exact mul_mem (mul_mem (inv_mem (unipotent_mem_commutator_suzukiGroup hn 1 1)) hconj)
    (inv_mem (unipotent_mem_commutator_suzukiGroup hn 1 0))

/-! ## Perfectness -/

/-- **A Suzuki group is its own derived subgroup** for `n ≠ 0`. -/
theorem commutator_suzukiGroup_eq_self (hn : n ≠ 0) :
    ⁅suzukiGroup n, suzukiGroup n⁆ = suzukiGroup n :=
  le_antisymm (suzukiGroup n).commutator_le_self
    (suzukiGroup_le_iff.2
      ⟨unipotent_mem_commutator_suzukiGroup hn, weyl_mem_commutator_suzukiGroup hn⟩)

/-- **The Suzuki groups are perfect**: for `n ≠ 0`, `EpsilonEridani.suzukiGroup n` equals its
commutator subgroup. At `n = 0` the group is the solvable `Sz(2)`, and the statement fails. -/
theorem isPerfect_suzukiGroup (hn : n ≠ 0) : Group.IsPerfect ↥(suzukiGroup n) :=
  Subgroup.isPerfect_iff.2 (commutator_suzukiGroup_eq_self hn)

end Suzuki

end EpsilonEridani
