/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.FieldTheory.Galois.FixedField
public import EpsilonEridani.FieldTheory.Normal.Closure

/-!
# Automorphisms of extensions of prime degree

A finite extension of prime degree is Galois as soon as it has a nonidentity automorphism.
Indeed, the automorphism group has order dividing the degree, by the fixed-field degree
formula. This criterion is useful when a second root of a minimal polynomial already lies
in the field generated by its first root. The general divisibility statement
`EpsilonEridani.natCard_algEquiv_dvd_finrank` lives in `EpsilonEridani.FieldTheory.Galois.FixedField`, and the
splitting-field facts for a normal simple extension in `EpsilonEridani.FieldTheory.Normal.Closure`.
-/

public section

namespace EpsilonEridani

open IntermediateField Polynomial

/-- A finite extension of prime degree with a nontrivial automorphism is Galois. -/
theorem isGalois_of_prime_finrank_of_exists_aut_ne_one
    (F E : Type*) [Field F] [Field E] [Algebra F E]
    (hprime : (Module.finrank F E).Prime)
    (h : ∃ σ : E ≃ₐ[F] E, σ ≠ 1) : IsGalois F E := by
  have : FiniteDimensional F E := FiniteDimensional.of_finrank_pos hprime.pos
  have hne : Nat.card (E ≃ₐ[F] E) ≠ 1 := by
    intro hone
    have : Subsingleton (E ≃ₐ[F] E) := (Nat.card_eq_one_iff_unique.mp hone).1
    obtain ⟨σ, hσ⟩ := h
    exact hσ (Subsingleton.elim σ 1)
  exact IsGalois.of_card_aut_eq_finrank F E
    ((hprime.eq_one_or_self_of_dvd _ (natCard_algEquiv_dvd_finrank F E)).resolve_left hne)

/-- A simple root field of a prime-degree polynomial is Galois as soon as it has a nonidentity
automorphism. -/
theorem isGalois_of_natDegree_prime_of_adjoin_simple_eq_top_of_exists_aut_ne_one
    (F : Type*) [Field F] (q : F[X]) (hprime : q.natDegree.Prime)
    (E : Type*) [Field E] [Algebra F E] (x : E)
    (hminpoly : minpoly F x = q) (hgen : F⟮x⟯ = ⊤)
    (hAut : ∃ σ : E ≃ₐ[F] E, σ ≠ 1) : IsGalois F E := by
  have hq : q ≠ 0 := by
    rintro rfl
    exact hprime.ne_zero natDegree_zero
  have hx : IsIntegral F x := minpoly.ne_zero_iff.mp (hminpoly ▸ hq)
  have hfinrank : Module.finrank F E = q.natDegree := by
    rw [← finrank_top', ← hgen, adjoin.finrank hx, hminpoly]
  exact isGalois_of_prime_finrank_of_exists_aut_ne_one F E (hfinrank ▸ hprime) hAut

/-- A prime-degree polynomial whose simple root field has a nonidentity automorphism is
separable. -/
theorem separable_of_natDegree_prime_of_exists_aut_ne_one
    (F : Type*) [Field F] (q : F[X]) (hprime : q.natDegree.Prime)
    (E : Type*) [Field E] [Algebra F E] (x : E)
    (hminpoly : minpoly F x = q) (hgen : F⟮x⟯ = ⊤)
    (hAut : ∃ σ : E ≃ₐ[F] E, σ ≠ 1) : q.Separable :=
  have := isGalois_of_natDegree_prime_of_adjoin_simple_eq_top_of_exists_aut_ne_one F q hprime E x
    hminpoly hgen hAut
  hminpoly ▸ IsGalois.separable F x

/-- A prime-degree polynomial whose simple root field has a nonidentity automorphism has Galois
group of order equal to its degree. -/
theorem natCard_gal_eq_natDegree_of_prime_of_exists_aut_ne_one
    (F : Type*) [Field F] (q : F[X]) (hprime : q.natDegree.Prime)
    (E : Type*) [Field E] [Algebra F E] (x : E)
    (hminpoly : minpoly F x = q) (hgen : F⟮x⟯ = ⊤)
    (hAut : ∃ σ : E ≃ₐ[F] E, σ ≠ 1) : Nat.card q.Gal = q.natDegree := by
  have := isGalois_of_natDegree_prime_of_adjoin_simple_eq_top_of_exists_aut_ne_one F q hprime E x
    hminpoly hgen hAut
  have hx : IsIntegral F x := IsGalois.integral F x
  rw [← hminpoly, natCard_gal_minpoly_eq_finrank x hgen, ← finrank_top', ← hgen,
    adjoin.finrank hx]

end EpsilonEridani
