/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.Algebra.HopfAlgebra.Augmentation
public import EpsilonEridani.Algebra.HopfAlgebra.Antipode
public import EpsilonEridani.RingTheory.Idempotents.Connected.Component

/-!
# The identity component of an affine group

Let `H` be a commutative Hopf algebra over a field whose prime spectrum is locally connected.
The connected component of the counit point is cut out by the principal ideal generated by the
complement of its component idempotent. This file proves that inversion preserves that ideal and
records the corresponding antipode closure statement needed to make it a Hopf ideal. The
locally-connected hypothesis is automatic for a bundled finite-type coordinate Hopf algebra over
a Noetherian base, through `EpsilonEridani.FiniteTypeCommHopfAlgCat.isNoetherianRing`. For an unbundled
`H` with `Algebra.FiniteType k H`, the user must first supply
`IsNoetherianRing H := Algebra.FiniteType.isNoetherianRing k H`.
Counit closure follows from the generic augmentation-component API; the remaining
comultiplication statement is equivalent to closure of the component under the group
multiplication.

The component here is the ordinary connected component over the ground field. The geometric
identity component is obtained by applying the construction after base change to an algebraic
closure; its descent and the component group are later parts of Layer 3.

## Main declarations

* `EpsilonEridani.HopfAlgebra.antipode_connectedComponentIdempotent_augmentationPoint_eq_self`: the
  antipode fixes the component idempotent of the augmentation point.
* `EpsilonEridani.HopfAlgebra.antipode_mem_connectedComponentIdeal_augmentationPoint_iff`: antipode
  images belong to the augmentation point's component ideal exactly when their preimages do.
* `EpsilonEridani.HopfAlgebra.map_antipodeAlgHom_connectedComponentIdeal_augmentationPoint_eq_self`:
  mapping the augmentation point's component ideal along the antipode fixes it.

## References

* J. S. Milne, *Algebraic Groups* (2017), Proposition 2.37.
* W. C. Waterhouse, *Introduction to Affine Group Schemes*, Section 6.7.

This advances Layer 3, "Identity component `G°` and component group `π₀(G)`", of the
ReductiveGroups roadmap. The next step is comultiplication closure and the resulting quotient
Hopf algebra; geometric connectedness and the finite étale component group then remain.
-/

public section

open AlgebraicGeometry

namespace EpsilonEridani.HopfAlgebra

universe u v

variable {k : Type u} [Field k]
variable {H : Type v} [CommRing H] [_root_.HopfAlgebra k H]

private theorem comap_antipodeAlgEquiv_augmentationPoint_eq_self :
    PrimeSpectrum.comap
        ((antipodeAlgEquiv (R := k) (A := H)).toRingEquiv : H →+* H)
        (Bialgebra.augmentationPoint k H) = Bialgebra.augmentationPoint k H := by
  rw [AlgEquiv.toRingEquiv_toRingHom, antipodeAlgEquiv_toRingHom]
  exact comap_antipodeAlgHom_augmentationPoint_eq_self (k := k) (H := H)

variable [LocallyConnectedSpace (PrimeSpectrum H)]

/-- The antipode fixes the component idempotent of the augmentation point. -/
@[simp]
theorem antipode_connectedComponentIdempotent_augmentationPoint_eq_self :
    HopfAlgebraStruct.antipode k
        (PrimeSpectrum.connectedComponentIdempotent (Bialgebra.augmentationPoint k H)) =
      PrimeSpectrum.connectedComponentIdempotent (Bialgebra.augmentationPoint k H) := by
  rw [← antipodeAlgEquiv_apply]
  exact PrimeSpectrum.map_connectedComponentIdempotent_eq_self
    (antipodeAlgEquiv (R := k) (A := H)).toRingEquiv
    (Bialgebra.augmentationPoint k H)
    (comap_antipodeAlgEquiv_augmentationPoint_eq_self (k := k) (H := H))

/-- Mapping the ideal cutting out the augmentation point's connected component along the
antipode fixes it. This is the ideal-theoretic form of inversion stability of the ordinary
identity component. -/
@[simp]
theorem map_antipodeAlgHom_connectedComponentIdeal_augmentationPoint_eq_self :
    Ideal.map (_root_.HopfAlgebra.antipodeAlgHom k H)
        (PrimeSpectrum.connectedComponentIdeal (Bialgebra.augmentationPoint k H)) =
      PrimeSpectrum.connectedComponentIdeal (Bialgebra.augmentationPoint k H) := by
  calc
    Ideal.map (_root_.HopfAlgebra.antipodeAlgHom k H)
        (PrimeSpectrum.connectedComponentIdeal (Bialgebra.augmentationPoint k H)) =
      Ideal.map (_root_.HopfAlgebra.antipodeAlgHom k H : H →+* H)
        (PrimeSpectrum.connectedComponentIdeal (Bialgebra.augmentationPoint k H)) :=
      (Ideal.map_coe (_root_.HopfAlgebra.antipodeAlgHom k H) _).symm
    _ = Ideal.map
        ((antipodeAlgEquiv (R := k) (A := H)).toRingEquiv : H →+* H)
        (PrimeSpectrum.connectedComponentIdeal (Bialgebra.augmentationPoint k H)) := by
      rw [AlgEquiv.toRingEquiv_toRingHom, antipodeAlgEquiv_toRingHom]
    _ = Ideal.map (antipodeAlgEquiv (R := k) (A := H)).toRingEquiv
        (PrimeSpectrum.connectedComponentIdeal (Bialgebra.augmentationPoint k H)) :=
      Ideal.map_coe (antipodeAlgEquiv (R := k) (A := H)).toRingEquiv _
    _ = PrimeSpectrum.connectedComponentIdeal (Bialgebra.augmentationPoint k H) :=
      PrimeSpectrum.map_connectedComponentIdeal_eq_self
        (antipodeAlgEquiv (R := k) (A := H)).toRingEquiv
        (Bialgebra.augmentationPoint k H)
        (comap_antipodeAlgEquiv_augmentationPoint_eq_self (k := k) (H := H))

/-- An antipode image belongs to the ideal cutting out the augmentation point's connected
component exactly when its preimage does. -/
@[simp]
theorem antipode_mem_connectedComponentIdeal_augmentationPoint_iff {x : H} :
    HopfAlgebraStruct.antipode k x ∈
        PrimeSpectrum.connectedComponentIdeal (Bialgebra.augmentationPoint k H) ↔
      x ∈ PrimeSpectrum.connectedComponentIdeal (Bialgebra.augmentationPoint k H) := by
  have h := PrimeSpectrum.apply_mem_connectedComponentIdeal_iff_of_comap_eq_self
    (antipodeAlgEquiv (R := k) (A := H)).toRingEquiv
    (Bialgebra.augmentationPoint k H)
    (comap_antipodeAlgEquiv_augmentationPoint_eq_self (k := k) (H := H)) (r := x)
  simpa using h

end EpsilonEridani.HopfAlgebra
