/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.Rigidity
public import EpsilonEridani.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.ToralClosure.Basic
import EpsilonEridani.AlgebraicGeometry.AffineGroupScheme.HopfSpec

/-!
# Rigidity of the toral Kostant carrier

The toral Kostant carrier is the smallest closed subgroup scheme of `GLₙ` containing both the
represented root subgroups and the represented weight torus. Consequently, a homomorphism out of
that carrier is determined by its restrictions to those generators.

This file proves that statement first on coordinate Hopf algebras and then for affine group
schemes. It complements
`EpsilonEridani.UniversalEnvelopingAlgebra.kostantGeneratedGroupScheme_hom_ext`, which applies to the
carrier generated by root subgroups alone. For the toral carrier, agreement on the root subgroups
does not by itself account for the adjoined torus, so the torus restriction is an essential second
hypothesis.

The final theorem gives the equivalent interface in which agreement on all root subgroups is
replaced by agreement on the closed immersion of the root-generated carrier. This is the form used
when an endomorphism has already been constructed on the root-generated part.

## Main results

* `EpsilonEridani.UniversalEnvelopingAlgebra.kostantToralCoordinate_hom_ext`: coordinate morphisms into
  the toral quotient are determined by every root coordinate and the weight-torus coordinate.
* `EpsilonEridani.UniversalEnvelopingAlgebra.kostantToralGroupScheme_hom_ext`: group-scheme morphisms out
  of the toral carrier are determined by every root subgroup and the weight torus.
* `EpsilonEridani.UniversalEnvelopingAlgebra.kostantToralGroupScheme_hom_ext_of_generated`: it is enough
  to agree on the root-generated carrier and the weight torus.

## Roadmap

This is the uniqueness step for the explicit carrier in Layer 9, “the isomorphism theorem for
pinned groups”, of `EpsilonEridaniRoadmap/ReductiveGroups/README.md`. The full pinned isomorphism theorem
must additionally construct the morphism from a root-datum isomorphism and reduce its determining
data to the pinned simple root subgroups. Milestone L1 of
`EpsilonEridaniRoadmap/CFSGStatement/README.md` consumes that theorem to turn a Dynkin-diagram symmetry
into the graph automorphism in a Steinberg endomorphism.

## References

* J. E. Humphreys, *Linear Algebraic Groups*, §27.
* R. W. Carter, *Simple Groups of Lie Type*, §§7.1 and 12.2.
-/

public section

open AlgebraicGeometry CategoryTheory TensorProduct

namespace EpsilonEridani.UniversalEnvelopingAlgebra

universe u w

-- Match tensor products to the `ℤ`-algebra structure used by scalar extension.
attribute [local instance high] Algebra.toModule

variable {L : Type u} [LieRing L] [LieAlgebra ℚ L]
variable {I : Type w} {κ : Type} [Finite κ]
variable {V : Type} [AddCommGroup V] [Module ℚ V]

variable (e : I → L) (h : κ → L)
variable (ρ : _root_.UniversalEnvelopingAlgebra ℚ L →ₐ[ℚ] Module.End ℚ V)
variable (M : AddSubgroup V)
variable (hM : ∀ u ∈ kostantForm e h, ∀ m ∈ M, ρ u m ∈ M)
variable (hnil : ∀ i, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i))))
variable {n : ℕ} (b : Module.Basis (Fin n) ℤ M)
variable (wt : Fin n → κ → ℤ)

/-- **Coordinate rigidity of the toral carrier.** Two morphisms of commutative Hopf algebras into
the coordinate algebra of the toral Kostant carrier are equal when they agree after composition
with every root-subgroup coordinate and with the weight-torus coordinate.

Contravariantly, a homomorphism out of the closed group scheme generated by the root subgroups and
the torus is determined on those generators. -/
theorem kostantToralCoordinate_hom_ext {Y : _root_.CommHopfAlgCat.{0} ℤ}
    (u v : Y ⟶ CommHopfAlgCat.quotient (GeneralLinear.coordinateHopfAlgebra ℤ n)
      (kostantToralDefiningIdeal e h ρ M hM hnil b wt))
    (hroot : ∀ i, u ≫ kostantRootSubgroupToralCoordinateMap e h ρ M hM hnil b wt i =
      v ≫ kostantRootSubgroupToralCoordinateMap e h ρ M hM hnil b wt i)
    (htorus : u ≫ kostantWeightTorusToralCoordinateMap e h ρ M hM hnil b wt =
      v ≫ kostantWeightTorusToralCoordinateMap e h ρ M hM hnil b wt) :
    u = v := by
  refine (CommHopfAlgCat.equalizerHopfIdeal_eq_bot_iff u v).1
    (CommHopfAlgCat.eq_bot_of_comapOfSurjective_le _ ?_)
  rw [le_kostantToralDefiningIdeal_iff]
  -- The equalizer pulls back to an ideal killed by each original generator. The two branches
  -- differ only in whether that generator is a root subgroup or the weight torus.
  constructor
  · intro i x hx
    have hmem :
        (CommHopfAlgCat.mkQuotient (GeneralLinear.coordinateHopfAlgebra ℤ n)
            (kostantToralDefiningIdeal e h ρ M hM hnil b wt)).hom x ∈
          CommHopfAlgCat.equalizerHopfIdeal u v :=
      HopfIdeal.mem_comapOfSurjective.1 hx
    have hzero :
        (kostantRootSubgroupToralCoordinateMap e h ρ M hM hnil b wt i).hom
            ((CommHopfAlgCat.mkQuotient (GeneralLinear.coordinateHopfAlgebra ℤ n)
              (kostantToralDefiningIdeal e h ρ M hM hnil b wt)).hom x) = 0 :=
      RingHom.mem_ker.1
        ((CommHopfAlgCat.equalizerHopfIdeal_toIdeal_le_ker_iff u v _).2 (hroot i) hmem)
    have hcomp :
        (kostantRootSubgroupToralCoordinateMap e h ρ M hM hnil b wt i).hom
            ((CommHopfAlgCat.mkQuotient (GeneralLinear.coordinateHopfAlgebra ℤ n)
              (kostantToralDefiningIdeal e h ρ M hM hnil b wt)).hom x) =
          (kostantRootSubgroupCoordinateMap e h ρ M hM i (hnil i) b).hom x :=
      congrArg (fun f => f.hom x)
        (mkQuotient_comp_kostantRootSubgroupToralCoordinateMap
          e h ρ M hM hnil b wt i)
    rw [RingHom.mem_ker]
    simpa only [BialgHom.coe_toAlgHom, AlgHom.toRingHom_eq_coe, RingHom.coe_coe] using
      hcomp.symm.trans hzero
  · intro x hx
    have hmem :
        (CommHopfAlgCat.mkQuotient (GeneralLinear.coordinateHopfAlgebra ℤ n)
            (kostantToralDefiningIdeal e h ρ M hM hnil b wt)).hom x ∈
          CommHopfAlgCat.equalizerHopfIdeal u v :=
      HopfIdeal.mem_comapOfSurjective.1 hx
    have hzero :
        (kostantWeightTorusToralCoordinateMap e h ρ M hM hnil b wt).hom
            ((CommHopfAlgCat.mkQuotient (GeneralLinear.coordinateHopfAlgebra ℤ n)
              (kostantToralDefiningIdeal e h ρ M hM hnil b wt)).hom x) = 0 :=
      RingHom.mem_ker.1
        ((CommHopfAlgCat.equalizerHopfIdeal_toIdeal_le_ker_iff u v _).2 htorus hmem)
    have hcomp :
        (kostantWeightTorusToralCoordinateMap e h ρ M hM hnil b wt).hom
            ((CommHopfAlgCat.mkQuotient (GeneralLinear.coordinateHopfAlgebra ℤ n)
              (kostantToralDefiningIdeal e h ρ M hM hnil b wt)).hom x) =
          (GeneralLinear.weightTorusCoordinateMap wt).hom x :=
      congrArg (fun f => f.hom x)
        (mkQuotient_comp_kostantWeightTorusToralCoordinateMap
          e h ρ M hM hnil b wt)
    rw [RingHom.mem_ker]
    simpa only [BialgHom.coe_toAlgHom, AlgHom.toRingHom_eq_coe, RingHom.coe_coe] using
      hcomp.symm.trans hzero

/-- **Rigidity of the toral Kostant group scheme.** Two homomorphisms out of the toral carrier are
equal when they agree on every represented root subgroup and on the represented weight torus.

This is the scheme-theoretic form of `kostantToralCoordinate_hom_ext`. -/
theorem kostantToralGroupScheme_hom_ext {Y : _root_.CommHopfAlgCat.{0} ℤ}
    (φ ψ : kostantToralGroupScheme e h ρ M hM hnil b wt ⟶
      (hopfSpec (CommRingCat.of ℤ)).obj (Opposite.op Y))
    (hroot : ∀ i, kostantRootSubgroupToToral e h ρ M hM hnil b wt i ≫ φ =
      kostantRootSubgroupToToral e h ρ M hM hnil b wt i ≫ ψ)
    (htorus : kostantWeightTorusToToral e h ρ M hM hnil b wt ≫ φ =
      kostantWeightTorusToToral e h ρ M hM hnil b wt ≫ ψ) :
    φ = ψ := by
  refine CommHopfAlgCat.hom_ext_of_preimage_unop_eq φ ψ
    (kostantToralCoordinate_hom_ext e h ρ M hM hnil b wt _ _ (fun i => ?_) ?_)
  · refine CommHopfAlgCat.preimage_unop_comp_eq_of_hopfSpec_map_comp_eq _ φ ψ ?_
    have hi := hroot i
    rw [kostantRootSubgroupToToral_def, Category.assoc, Category.assoc] at hi
    exact (cancel_epi (eqToHom (AdditiveGroup.groupScheme_def ℤ))).1 hi
  · refine CommHopfAlgCat.preimage_unop_comp_eq_of_hopfSpec_map_comp_eq _ φ ψ ?_
    rw [kostantWeightTorusToToral_def, Category.assoc, Category.assoc] at htorus
    exact (cancel_epi (eqToHom
      (DiagonalizableGroup.groupScheme_def ℤ (SplitTorus.characterGroup κ)))).1 htorus

/-- It is enough to compare homomorphisms out of the toral carrier on the root-generated closed
subgroup scheme and on the weight torus. This packages all root-subgroup hypotheses of
`kostantToralGroupScheme_hom_ext` through `kostantGeneratedToToral`. -/
theorem kostantToralGroupScheme_hom_ext_of_generated {Y : _root_.CommHopfAlgCat.{0} ℤ}
    (φ ψ : kostantToralGroupScheme e h ρ M hM hnil b wt ⟶
      (hopfSpec (CommRingCat.of ℤ)).obj (Opposite.op Y))
    (hgenerated : kostantGeneratedToToral e h ρ M hM hnil b wt ≫ φ =
      kostantGeneratedToToral e h ρ M hM hnil b wt ≫ ψ)
    (htorus : kostantWeightTorusToToral e h ρ M hM hnil b wt ≫ φ =
      kostantWeightTorusToToral e h ρ M hM hnil b wt ≫ ψ) :
    φ = ψ := by
  apply kostantToralGroupScheme_hom_ext e h ρ M hM hnil b wt φ ψ _ htorus
  intro i
  rw [← kostantRootSubgroupToGenerated_comp_kostantGeneratedToToral,
    Category.assoc, Category.assoc, hgenerated]

end EpsilonEridani.UniversalEnvelopingAlgebra
