/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Probability.Independence.Basic

/-!
# Independence from disjoint blocks of an independent family

Mathlib's `ProbabilityTheory.iIndepFun.indepFun_finset` splits an independent family along two
disjoint **finite** index sets. The statement is true for arbitrary index sets, and that is what a
random object built from a countably infinite block of independent noise needs: the two objects are
independent as soon as the coordinates they read are disjoint, however many of them there are.

`EpsilonEridani.Probability.blockSigma` names the σ-algebra a block of coordinates generates, and
`EpsilonEridani.Probability.indepFun_of_measurable_blockSigma` is the resulting independence criterion. The
proof is Mathlib's `ProbabilityTheory.indep_iSup_of_disjoint` together with the monotonicity of
independence in both σ-algebras.

## Main declarations

* `EpsilonEridani.Probability.blockSigma` — the σ-algebra generated by a set of members of a family of
  random variables;
* `EpsilonEridani.Probability.blockSigma_def` — its defining supremum, for use across module boundaries;
* `EpsilonEridani.Probability.blockSigma_empty` — an empty block generates the bottom σ-algebra;
* `EpsilonEridani.Probability.blockSigma_mono` — monotonicity in the block;
* `EpsilonEridani.Probability.blockSigma_le_iff` — the universal property of that σ-algebra;
* `EpsilonEridani.Probability.measurable_blockSigma_of_mem` — a member of the block is measurable for it;
* `EpsilonEridani.Probability.indepFun_of_measurable_blockSigma` — two random elements measurable for the
  σ-algebras of disjoint blocks of an independent family are independent.
-/

public section

open MeasureTheory

namespace EpsilonEridani

namespace Probability

variable {Ω ι : Type*} [MeasurableSpace Ω] {β : ι → Type*} [∀ i, MeasurableSpace (β i)]

/-- The σ-algebra generated by the members `Z i` of a family with `i` in a block `S` of indices. -/
@[implicit_reducible]
def blockSigma (Z : ∀ i, Ω → β i) (S : Set ι) : MeasurableSpace Ω :=
  ⨆ i ∈ S, MeasurableSpace.comap (Z i) inferInstance

omit [MeasurableSpace Ω] in
/-- The defining supremum of `blockSigma`. -/
theorem blockSigma_def (Z : ∀ i, Ω → β i) (S : Set ι) :
    blockSigma Z S = ⨆ i ∈ S, MeasurableSpace.comap (Z i) inferInstance :=
  (rfl)

omit [MeasurableSpace Ω] in
/-- The block σ-algebra is the σ-algebra pulled back along the restriction of the family to the
block. -/
theorem blockSigma_eq_comap_restrict (Z : ∀ i, Ω → β i) (S : Set ι) :
    blockSigma Z S = MeasurableSpace.comap (fun ω => fun i : S => Z i ω) inferInstance := by
  rw [blockSigma_def, MeasurableSpace.pi, MeasurableSpace.comap_iSup]
  simp only [MeasurableSpace.comap_comp, iSup_subtype, Function.comp_def]

omit [MeasurableSpace Ω] in
/-- The block σ-algebra of a finite block is the σ-algebra pulled back along the `Finset`
restriction of the family to the block. -/
theorem blockSigma_coe_eq_comap_finset_restrict (Z : ∀ i, Ω → β i) (S : Finset ι) :
    blockSigma Z ↑S = MeasurableSpace.comap (fun ω => S.restrict fun i => Z i ω) inferInstance :=
  -- the subtype of the coerced finset is the subtype of the finset, and the restriction to it is
  -- `Finset.restrict`, both by definition
  blockSigma_eq_comap_restrict Z ↑S

omit [MeasurableSpace Ω] in
/-- The σ-algebra generated by an empty block is the bottom σ-algebra. -/
@[simp]
theorem blockSigma_empty (Z : ∀ i, Ω → β i) : blockSigma Z ∅ = ⊥ := by
  simp [blockSigma]

omit [MeasurableSpace Ω] in
/-- A member of a block is measurable for the σ-algebra that block generates. -/
theorem measurable_blockSigma_of_mem {Z : ∀ i, Ω → β i} {S : Set ι} {i : ι} (hi : i ∈ S) :
    Measurable[blockSigma Z S] (Z i) :=
  Measurable.of_comap_le
    (le_iSup₂ (f := fun i (_ : i ∈ S) => MeasurableSpace.comap (Z i) inferInstance) i hi)

omit [MeasurableSpace Ω] in
/-- The σ-algebra of a block grows with the block. -/
theorem blockSigma_mono {Z : ∀ i, Ω → β i} {S T : Set ι} (hST : S ⊆ T) :
    blockSigma Z S ≤ blockSigma Z T :=
  iSup_le_iSup_of_subset hST

omit [MeasurableSpace Ω] in
/-- The σ-algebra generated by a block is below `m` exactly when every member of the block is
measurable with respect to `m`. -/
theorem blockSigma_le_iff {Z : ∀ i, Ω → β i} {S : Set ι} {m : MeasurableSpace Ω} :
    blockSigma Z S ≤ m ↔ ∀ i ∈ S, Measurable[m] (Z i) := by
  constructor
  · intro h i hi
    exact Measurable.of_comap_le ((measurable_blockSigma_of_mem hi).comap_le.trans h)
  · exact fun h => iSup₂_le fun i hi => (h i hi).comap_le

/-- The σ-algebra of a block of an independent family sits inside the ambient σ-algebra. -/
theorem blockSigma_le {Z : ∀ i, Ω → β i} (S : Set ι)
    (hZ : ∀ i ∈ S, Measurable (Z i)) :
    blockSigma Z S ≤ (inferInstance : MeasurableSpace Ω) :=
  blockSigma_le_iff.mpr hZ

/-- **Disjoint blocks of an independent family are independent.** Two random elements, each
measurable for the σ-algebra generated by its own block of an independent family, are independent
as soon as the two blocks are disjoint. Unlike
`ProbabilityTheory.iIndepFun.indepFun_finset`, the blocks may be infinite. -/
theorem indepFun_of_measurable_blockSigma {μ : Measure Ω} {Z : ∀ i, Ω → β i}
    {S T : Set ι} (hZ : ProbabilityTheory.iIndepFun (fun i : ↥(S ∪ T) => Z i) μ)
    (hZ_meas : ∀ i ∈ S ∪ T, Measurable (Z i)) (hST : Disjoint S T)
    {γ δ : Type*} [MeasurableSpace γ] [MeasurableSpace δ] {U : Ω → γ} {V : Ω → δ}
    (hU : Measurable[blockSigma Z S] U) (hV : Measurable[blockSigma Z T] V) :
    ProbabilityTheory.IndepFun U V μ := by
  classical
  let m : ↥(S ∪ T) → MeasurableSpace Ω := fun i => MeasurableSpace.comap (Z i) inferInstance
  have hm_le : ∀ i, m i ≤ (inferInstance : MeasurableSpace Ω) :=
    fun i => (hZ_meas i i.property).comap_le
  have hm_block (A : Set ι) (hA : A ⊆ S ∪ T) :
      (⨆ i ∈ (Subtype.val ⁻¹' A : Set ↥(S ∪ T)), m i) = blockSigma Z A := by
    apply le_antisymm
    · rw [blockSigma]
      refine iSup₂_le fun i hi => ?_
      exact le_iSup_of_le i.1 (le_iSup_of_le hi le_rfl)
    · rw [blockSigma]
      refine iSup₂_le fun i hi => ?_
      exact le_iSup_of_le (⟨i, hA hi⟩ : ↥(S ∪ T)) (le_iSup_of_le hi le_rfl)
  have hST' : Disjoint (Subtype.val ⁻¹' S : Set ↥(S ∪ T)) (Subtype.val ⁻¹' T) :=
    Set.disjoint_left.mpr fun _ hi hi' => Set.disjoint_left.mp hST hi hi'
  have hblocks := ProbabilityTheory.indep_iSup_of_disjoint hm_le hZ.iIndep hST'
  rw [hm_block S Set.subset_union_left, hm_block T Set.subset_union_right] at hblocks
  exact ProbabilityTheory.indep_of_indep_of_le
    hblocks hU.comap_le hV.comap_le

end Probability

end EpsilonEridani
