/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Probability.Independence.Basic

/-!
# Independence under a pushforward

Two functions are independent under the pushforward of a measure along a measurable map exactly
when their composites with that map are independent under the measure: the events generated by
the composites are the preimages of the events generated by the functions.

## Main results

* `ProbabilityTheory.indepFun_map_iff_comp`
-/

public section

open MeasureTheory

namespace ProbabilityTheory

variable {Ω Ω' β γ : Type*} [MeasurableSpace Ω] [MeasurableSpace Ω'] [MeasurableSpace β]
  [MeasurableSpace γ] {μ : Measure Ω}

/-- Independence of two functions under a pushforward is independence of their composites. -/
theorem indepFun_map_iff_comp {m : Ω → Ω'} (hm : Measurable m) {f : Ω' → β} {g : Ω' → γ}
    (hf : Measurable f) (hg : Measurable g) :
    IndepFun f g (μ.map m) ↔ IndepFun (f ∘ m) (g ∘ m) μ := by
  -- the defining identity for the pushforward is the defining identity for the composites
  have key : ∀ s₁ s₂, MeasurableSet s₁ → MeasurableSet s₂ →
      ((μ.map m) (f ⁻¹' s₁ ∩ g ⁻¹' s₂) = (μ.map m) (f ⁻¹' s₁) * (μ.map m) (g ⁻¹' s₂) ↔
        μ ((f ∘ m) ⁻¹' s₁ ∩ (g ∘ m) ⁻¹' s₂) = μ ((f ∘ m) ⁻¹' s₁) * μ ((g ∘ m) ⁻¹' s₂)) := by
    intro s₁ s₂ hs₁ hs₂
    rw [Measure.map_apply hm (hf hs₁), Measure.map_apply hm (hg hs₂),
      Measure.map_apply hm ((hf hs₁).inter (hg hs₂)), Set.preimage_inter, Set.preimage_comp,
      Set.preimage_comp]
  rw [indepFun_iff_measure_inter_preimage_eq_mul, indepFun_iff_measure_inter_preimage_eq_mul]
  exact forall₄_congr key

end ProbabilityTheory
