/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.NumberTheory.NumberField.Frobenius.FixedField.Inertia
public import EpsilonEridani.NumberTheory.RamificationInertia.DoubleCoset.Basic
import EpsilonEridani.GroupTheory.QuotientGroup.Basic

/-!
# Decomposition-group orbits on cosets and the primes of a fixed field

Let `M / K` be a Galois extension of number fields with group `G`, let `H` be a subgroup of `G`
with fixed field `E = M ^ H`, and let `Q` be a prime of `𝓞 M` above a prime `p` of `𝓞 K`, with
decomposition group `D`. The double coset law of `EpsilonEridani/NumberTheory/RamificationInertia/
DoubleCoset/Basic.lean` indexes the primes of `𝓞 E` above `p` by `H \ G / D`. This file reads
the same law on the left cosets `G ⧸ H`, where `D` acts by translation: the coset `τ H` is
attached to the prime `τ⁻¹ Q ∩ 𝓞 E` (`Ideal.primesOverOfCoset`), two cosets are attached to the
same prime exactly when they lie in one `D`-orbit, every prime arises, and the `D`-orbit of `τ H`
has `e · f` elements, where `e` and `f` are the ramification index and the residue degree of the
attached prime over `p`. Altogether, the multiset of the sizes of the `D`-orbits on `G ⧸ H` is
the multiset of the local degrees `e · f` over the primes of `𝓞 E` above `p`.

This is the form of the double coset law that Dedekind's theorem uses: when `E = K(α)` for a root
`α` of an irreducible polynomial, `G ⧸ H` is the set of roots. If moreover `p` is unramified in
`E`, so that every `e` is `1`, and `D` is generated by a Frobenius element, then the orbit sizes
of that Frobenius on the roots are the residue degrees of the primes of `E` above `p`.

## Main definitions

* `Ideal.primesOverOfCoset`: the prime `τ⁻¹ Q ∩ 𝓞 (M ^ H)` attached to the coset `τ H`.
* `Ideal.orbitQuotientEquivPrimesOver`: the orbits of the decomposition group on `G ⧸ H` are the
  primes of `𝓞 (M ^ H)` above `p`.

## Main results

* `Ideal.primesOverOfCoset_eq_iff`: the fibres of `primesOverOfCoset` are the orbits of the
  decomposition group of `Q`.
* `Ideal.primesOverOfCoset_surjective`: every prime of `𝓞 (M ^ H)` above `p` is attached to a
  coset.
* `Ideal.card_orbit_stabilizer_coset`: the orbit of a coset under the decomposition group has
  `e · f` elements, for the prime attached to the coset.
* `Ideal.map_card_orbit_stabilizer_eq_map_ramificationIdx_mul_inertiaDeg`: the multiset of orbit
  sizes is the multiset of local degrees over the primes of `𝓞 (M ^ H)` above `p`.

## References

* [J. Neukirch, *Algebraic Number Theory*][Neukirch1992], Chapter I, §9.
* G. J. Janusz, *Algebraic Number Fields*, Chapter I.
-/

public section

open IntermediateField MulAction NumberField

open scoped NumberField Pointwise

namespace Ideal

variable {K M : Type*} [Field K] [NumberField K] [Field M] [NumberField M] [Algebra K M]

variable (p : Ideal (𝓞 K)) (Q : Ideal (𝓞 M)) [Q.IsPrime] [Q.LiesOver p]
  (H : Subgroup (M ≃ₐ[K] M))

/-- The prime of the fixed field `M ^ H` above `p` attached to a coset `τ H`: the contraction
`τ⁻¹ Q ∩ 𝓞 (M ^ H)`. It does not depend on the representative `τ`, because `H` fixes `M ^ H`
pointwise and so does not move contractions to it. -/
noncomputable def primesOverOfCoset : (M ≃ₐ[K] M) ⧸ H → p.primesOver (𝓞 ↥(fixedField H)) :=
  _root_.Quotient.lift (fun τ => ⟨(τ⁻¹ • Q).under (𝓞 ↥(fixedField H)), inferInstance,
      ⟨by rw [under_under]; exact (inferInstance : (τ⁻¹ • Q).LiesOver p).over⟩⟩) fun τ τ' h => by
    apply Subtype.ext
    dsimp only
    rw [under_fixedField_eq_iff_mem_orbit]
    refine ⟨⟨τ⁻¹ * τ', QuotientGroup.leftRel_apply.mp h⟩, ?_⟩
    simp only [Subgroup.smul_def, smul_smul, mul_inv_cancel_right]

/-- The prime attached to the coset of `τ` is the contraction of `τ⁻¹ Q`. -/
@[simp]
theorem coe_primesOverOfCoset_mk (τ : M ≃ₐ[K] M) :
    (primesOverOfCoset p Q H (τ : (M ≃ₐ[K] M) ⧸ H) : Ideal (𝓞 ↥(fixedField H))) =
      (τ⁻¹ • Q).under (𝓞 ↥(fixedField H)) :=
  (rfl)

/-- **The fibres are the orbits of the decomposition group.** Two cosets are attached to the
same prime of `M ^ H` exactly when one is a translate of the other by the decomposition group of
`Q`. -/
theorem primesOverOfCoset_eq_iff (x y : (M ≃ₐ[K] M) ⧸ H) :
    primesOverOfCoset p Q H x = primesOverOfCoset p Q H y ↔
      x ∈ orbit (stabilizer (M ≃ₐ[K] M) Q) y := by
  induction x using QuotientGroup.induction_on with | H τ => ?_
  induction y using QuotientGroup.induction_on with | H τ' => ?_
  rw [Subtype.ext_iff, coe_primesOverOfCoset_mk, coe_primesOverOfCoset_mk,
    under_fixedField_eq_iff_mem_orbit, mem_orbit_iff, mem_orbit_iff]
  constructor
  · rintro ⟨h, hh⟩
    rw [Subgroup.smul_def, smul_smul] at hh
    refine ⟨⟨τ * h * τ'⁻¹, ?_⟩, ?_⟩
    · rw [mem_stabilizer_iff, mul_assoc, mul_smul, hh, smul_smul, mul_inv_cancel, one_smul]
    · rw [Subgroup.smul_def, MulAction.Quotient.smul_mk, QuotientGroup.eq, smul_eq_mul,
        Subgroup.coe_mk]
      convert H.inv_mem h.2 using 1
      group
  · rintro ⟨d, hd⟩
    rw [Subgroup.smul_def, MulAction.Quotient.smul_mk, QuotientGroup.eq] at hd
    have hmem : τ⁻¹ * d * τ' ∈ H := by
      have := H.inv_mem hd
      simpa [mul_inv_rev, mul_assoc] using this
    refine ⟨⟨τ⁻¹ * d * τ', hmem⟩, ?_⟩
    rw [Subgroup.smul_def, smul_smul, mul_inv_cancel_right, mul_smul, mem_stabilizer_iff.mp d.2]

/-- **Every prime of the fixed field above `p` is attached to a coset.** -/
theorem primesOverOfCoset_surjective [IsGalois K M] :
    Function.Surjective (primesOverOfCoset p Q H) := by
  rintro ⟨𝔮, h𝔮, h𝔮p⟩
  obtain ⟨σ, hσ⟩ := exists_smul_under_fixedField_eq p Q H 𝔮
  exact ⟨((σ⁻¹ : M ≃ₐ[K] M) : (M ≃ₐ[K] M) ⧸ H),
    Subtype.ext (by rw [coe_primesOverOfCoset_mk, inv_inv]; exact hσ)⟩

/-- **The orbits of the decomposition group on `G ⧸ H` are the primes of the fixed field above
`p`**: the map `primesOverOfCoset`, which is constant on the orbits of the decomposition group of
`Q` and identifies exactly them, descends to a bijection from the orbit quotient. -/
noncomputable def orbitQuotientEquivPrimesOver [IsGalois K M] :
    orbitRel.Quotient (stabilizer (M ≃ₐ[K] M) Q) ((M ≃ₐ[K] M) ⧸ H) ≃
      p.primesOver (𝓞 ↥(fixedField H)) :=
  Equiv.ofBijective
    (_root_.Quotient.lift (primesOverOfCoset p Q H) fun x y h =>
      (primesOverOfCoset_eq_iff p Q H x y).mpr (orbitRel_apply.mp h))
    ⟨fun ω ω' h => _root_.Quotient.inductionOn₂' ω ω' (fun x y h => _root_.Quotient.sound'
        (orbitRel_apply.mpr ((primesOverOfCoset_eq_iff p Q H x y).mp h))) h,
      fun 𝔮 => (primesOverOfCoset_surjective p Q H 𝔮).elim fun x hx =>
        ⟨_root_.Quotient.mk'' x, hx⟩⟩

/-- The orbit of a coset is sent to the prime attached to the coset. -/
@[simp]
theorem orbitQuotientEquivPrimesOver_mk [IsGalois K M] (x : (M ≃ₐ[K] M) ⧸ H) :
    orbitQuotientEquivPrimesOver p Q H (_root_.Quotient.mk'' x) = primesOverOfCoset p Q H x :=
  (rfl)

/-- **Orbit sizes are local degrees.** The orbit of a coset under the decomposition group of `Q`
has as many elements as the ramification index times the residue degree of the prime of
`𝓞 (M ^ H)` attached to the coset. -/
theorem card_orbit_stabilizer_coset [IsGalois K M] (x : (M ≃ₐ[K] M) ⧸ H) :
    Nat.card (orbit (stabilizer (M ≃ₐ[K] M) Q) x) =
      (primesOverOfCoset p Q H x).1.ramificationIdx (𝓞 K) *
        (primesOverOfCoset p Q H x).1.inertiaDeg (𝓞 K) := by
  induction x using QuotientGroup.induction_on with | H τ => ?_
  rw [coe_primesOverOfCoset_mk,
    ramificationIdx_mul_inertiaDeg_under_fixedField_eq_relIndex (τ⁻¹ • Q) H,
    stabilizer_smul_eq_stabilizer_map_conj, ← Subgroup.relIndex_comap,
    Subgroup.comap_equiv_eq_map_symm', Nat.card_congr (orbitEquivQuotientStabilizer _ _),
    ← Subgroup.index_eq_card, Subgroup.relIndex]
  congr 1
  ext d
  rw [mem_stabilizer_iff, Subgroup.mem_subgroupOf, MulAction.subgroup_smul_def,
    ← mem_stabilizer_iff, EpsilonEridani.stabilizer_quotientGroup_mk]
  rfl

open scoped Classical in
/-- **The multiset of orbit sizes is the multiset of local degrees.** The sizes of the orbits of
the decomposition group of `Q` on `Gal(M/K) ⧸ H` are, as a multiset, the products `e · f` of
the ramification index and the residue degree over the primes of `𝓞 (M ^ H)` above `p`. -/
theorem map_card_orbit_stabilizer_eq_map_ramificationIdx_mul_inertiaDeg [IsGalois K M]
    [p.IsMaximal] :
    (Finset.univ : Finset (orbitRel.Quotient (stabilizer (M ≃ₐ[K] M) Q)
        ((M ≃ₐ[K] M) ⧸ H))).val.map (fun ω => Nat.card ω.orbit) =
      (Finset.univ : Finset (p.primesOver (𝓞 ↥(fixedField H)))).val.map
        (fun 𝔮 : p.primesOver (𝓞 ↥(fixedField H)) =>
          𝔮.1.ramificationIdx (𝓞 K) * 𝔮.1.inertiaDeg (𝓞 K)) := by
  -- The orbit sizes, read through the bijection with the primes above `p`.
  have hcard : ∀ ω : orbitRel.Quotient (stabilizer (M ≃ₐ[K] M) Q) ((M ≃ₐ[K] M) ⧸ H),
      Nat.card ω.orbit = (orbitQuotientEquivPrimesOver p Q H ω).1.ramificationIdx (𝓞 K) *
        (orbitQuotientEquivPrimesOver p Q H ω).1.inertiaDeg (𝓞 K) := by
    intro ω
    refine _root_.Quotient.inductionOn' ω fun x => ?_
    rw [orbitRel.Quotient.orbit_mk, orbitQuotientEquivPrimesOver_mk p Q H,
      card_orbit_stabilizer_coset p Q H]
  calc (Finset.univ : Finset (orbitRel.Quotient (stabilizer (M ≃ₐ[K] M) Q)
          ((M ≃ₐ[K] M) ⧸ H))).val.map (fun ω => Nat.card ω.orbit)
      = Finset.univ.val.map (fun ω => (orbitQuotientEquivPrimesOver p Q H ω).1.ramificationIdx
          (𝓞 K) * (orbitQuotientEquivPrimesOver p Q H ω).1.inertiaDeg (𝓞 K)) :=
        Multiset.map_congr rfl fun ω _ => hcard ω
    _ = (Finset.univ.val.map (orbitQuotientEquivPrimesOver p Q H)).map
          (fun 𝔮 : p.primesOver (𝓞 ↥(fixedField H)) =>
            𝔮.1.ramificationIdx (𝓞 K) * 𝔮.1.inertiaDeg (𝓞 K)) := by
        rw [Multiset.map_map, Function.comp_def]
    _ = _ := by rw [Multiset.map_univ_val_equiv]

end Ideal
