/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.FieldTheory.GaloisGroups.Stabilizer
public import EpsilonEridani.GroupTheory.Perm.Blocks

/-!
# Blocks of a polynomial Galois action

For an irreducible separable polynomial, the blocks of the Galois action that contain a chosen
root correspond contravariantly to the intermediate fields of the simple extension generated by
that root. A block is sent to the field fixed by its setwise stabilizer; in the other direction,
an intermediate field is sent to the orbit of the root under its fixing subgroup. Equivalently,
that orbit consists of the roots of the root's minimal polynomial over the intermediate field.

The correspondence identifies primitivity of the root action with the absence of proper
intermediate fields in the simple extension.

## Main results

* `EpsilonEridani.rootBlockIntermediateFieldOrderIso`: blocks containing a root are order anti-isomorphic
  to intermediate fields contained in the field generated by that root.
* `EpsilonEridani.coe_rootBlockIntermediateFieldOrderIso_symm_apply_eq_preimage_rootSet_minpoly`: the
  block attached to an intermediate field is the set of roots of the corresponding minimal
  polynomial.
* `EpsilonEridani.isPreprimitive_iff_isAtom_adjoin_simple`: the root action is primitive exactly when
  the generated simple extension is an atom in the lattice of intermediate fields.
* `EpsilonEridani.isPreprimitive_of_irreducible_of_separable_of_prime_natDegree`: an irreducible
  separable polynomial of prime degree has a primitive root action.

## References

* H. Wielandt, *Finite Permutation Groups*, Theorem 7.5
* J. D. Dixon and B. Mortimer, *Permutation Groups*, Section 1.5
-/

public section

namespace EpsilonEridani

open scoped Pointwise

open IntermediateField MulAction Polynomial

universe u

variable {F : Type u} [Field F] {p : F[X]}

/-- **Blocks containing a root correspond to intermediate fields of its simple extension.**

The correspondence sends a block `B` to the field fixed by its setwise stabilizer. Its inverse
sends an intermediate field `E ⊆ F⟨x⟩` to the orbit of `x` under `Gal(L/E)`, where
`L = p.SplittingField`. The codomain is order-dual because larger blocks have larger stabilizers
and hence smaller fixed fields. -/
noncomputable def rootBlockIntermediateFieldOrderIso
    (hp : Irreducible p) (hsep : p.Separable)
    (x : p.rootSet p.SplittingField) :
    BlockMem p.Gal x ≃o (Set.Iic F⟮(x : p.SplittingField)⟯)ᵒᵈ :=
  letI : IsGalois F p.SplittingField := IsGalois.of_separable_splitting_field hsep
  letI : IsPretransitive p.Gal (p.rootSet p.SplittingField) :=
    isPretransitive_of_irreducible hp
  let e := IsGaloisGroup.intermediateFieldEquivSubgroup p.Gal F p.SplittingField
  -- Identify the stabilizer interval with the dual of the image interval of `F⟮x⟯`.
  let dualIci : Set.Ici (stabilizer p.Gal x) ≃o (Set.Iic (e F⟮(x : p.SplittingField)⟯))ᵒᵈ :=
    { toFun := fun H ↦ OrderDual.toDual ⟨OrderDual.toDual H.1,
        (stabilizer_eq_fixingSubgroup_adjoin_simple x).symm.trans_le H.2⟩
      invFun := fun H ↦ ⟨(OrderDual.ofDual H).1.ofDual,
        (stabilizer_eq_fixingSubgroup_adjoin_simple x).trans_le (OrderDual.ofDual H).2⟩
      left_inv := fun _ ↦ rfl
      right_inv := fun _ ↦ rfl
      map_rel_iff' := Iff.rfl }
  (block_stabilizerOrderIso p.Gal x).trans <|
    dualIci.trans (e.Iic F⟮(x : p.SplittingField)⟯).symm.dual

/-- A block is sent to the field fixed by its setwise stabilizer: an element belongs to the
corresponding intermediate field exactly when every element of the stabilizer fixes it. -/
@[simp]
theorem mem_rootBlockIntermediateFieldOrderIso_apply_iff
    (hp : Irreducible p) (hsep : p.Separable)
    (x : p.rootSet p.SplittingField) (B : BlockMem p.Gal x) (y : p.SplittingField) :
    y ∈ ((rootBlockIntermediateFieldOrderIso hp hsep x B).ofDual :
      IntermediateField F p.SplittingField) ↔
      ∀ g ∈ stabilizer p.Gal (B : Set (p.rootSet p.SplittingField)), g • y = y :=
  by
    let _ : IsGalois F p.SplittingField := IsGalois.of_separable_splitting_field hsep
    -- `block_stabilizerOrderIso` matches on its argument, so destructure the block first.
    obtain ⟨B, hxB, hB⟩ := B
    have hfield : ((rootBlockIntermediateFieldOrderIso hp hsep x ⟨B, hxB, hB⟩).ofDual :
        IntermediateField F p.SplittingField) =
          FixedPoints.intermediateField (stabilizer p.Gal B) :=
      IsGaloisGroup.intermediateFieldEquivSubgroup_symm_apply_toDual p.Gal F p.SplittingField
    rw [hfield, FixedPoints.mem_intermediateField_iff]
    exact ⟨fun h g hg ↦ h ⟨g, hg⟩, fun h g ↦ h g g.2⟩

/-- The singleton block corresponds to the whole simple extension, confirming the orientation of
`rootBlockIntermediateFieldOrderIso`. -/
theorem rootBlockIntermediateFieldOrderIso_apply_bot
    (hp : Irreducible p) (hsep : p.Separable)
    (x : p.rootSet p.SplittingField) :
    ((rootBlockIntermediateFieldOrderIso hp hsep x
      (⊥ : BlockMem p.Gal x)).ofDual.1 : IntermediateField F p.SplittingField) =
      F⟮(x : p.SplittingField)⟯ := by
  exact congrArg (fun E ↦ (E.ofDual.1 : IntermediateField F p.SplittingField))
    (rootBlockIntermediateFieldOrderIso hp hsep x).map_bot

/-- The block of all roots corresponds to the base field, confirming the orientation of
`rootBlockIntermediateFieldOrderIso`. -/
theorem rootBlockIntermediateFieldOrderIso_apply_top
    (hp : Irreducible p) (hsep : p.Separable)
    (x : p.rootSet p.SplittingField) :
    ((rootBlockIntermediateFieldOrderIso hp hsep x
      (⊤ : BlockMem p.Gal x)).ofDual.1 : IntermediateField F p.SplittingField) = ⊥ := by
  exact congrArg (fun E ↦ (E.ofDual.1 : IntermediateField F p.SplittingField))
    (rootBlockIntermediateFieldOrderIso hp hsep x).map_top

/-- The underlying set of the block attached to an intermediate field is the orbit of the chosen
root under the field's fixing subgroup. -/
@[simp]
theorem coe_rootBlockIntermediateFieldOrderIso_symm_apply
    (hp : Irreducible p) (hsep : p.Separable)
    (x : p.rootSet p.SplittingField) (E : Set.Iic F⟮(x : p.SplittingField)⟯) :
    (((rootBlockIntermediateFieldOrderIso hp hsep x).symm (OrderDual.toDual E) :
      BlockMem p.Gal x) : Set (p.rootSet p.SplittingField)) =
      orbit (fixingSubgroup p.Gal (E.1 : Set p.SplittingField)) x := by
  let _ : IsGalois F p.SplittingField := IsGalois.of_separable_splitting_field hsep
  let _ : IsPretransitive p.Gal (p.rootSet p.SplittingField) :=
    isPretransitive_of_irreducible hp
  -- Any block sent to `E` has `E` as the fixed field of its stabilizer, hence is the orbit of `x`
  -- under the fixing subgroup of `E`; the block at hand is sent to `E` by `apply_symm_apply`.
  suffices h : ∀ B : BlockMem p.Gal x,
      ((rootBlockIntermediateFieldOrderIso hp hsep x B).ofDual.1 :
        IntermediateField F p.SplittingField) = E.1 →
      (B : Set (p.rootSet p.SplittingField)) =
        orbit (fixingSubgroup p.Gal (E.1 : Set p.SplittingField)) x from
    h _ (by rw [OrderIso.apply_symm_apply, OrderDual.ofDual_toDual])
  intro B hBE
  have hfield : ((rootBlockIntermediateFieldOrderIso hp hsep x B).ofDual.1 :
      IntermediateField F p.SplittingField) =
      FixedPoints.intermediateField
        (stabilizer p.Gal (B : Set (p.rootSet p.SplittingField))) := by
    ext y
    rw [mem_rootBlockIntermediateFieldOrderIso_apply_iff hp hsep x B y,
      FixedPoints.mem_intermediateField_iff]
    exact ⟨fun h g ↦ h g g.2, fun h g hg ↦ h ⟨g, hg⟩⟩
  have hstab : fixingSubgroup p.Gal (E.1 : Set p.SplittingField) =
      stabilizer p.Gal (B : Set (p.rootSet p.SplittingField)) := by
    rw [← hBE, hfield]
    exact IsGaloisGroup.fixingSubgroup_fixedPoints ..
  rw [hstab]
  exact (B.2.2.orbit_stabilizer_eq B.2.1).symm

/-- The block attached to an intermediate field is the fibre, among the roots of `p`, of the
minimal polynomial of the chosen root over that field. -/
theorem coe_rootBlockIntermediateFieldOrderIso_symm_apply_eq_preimage_rootSet_minpoly
    (hp : Irreducible p) (hsep : p.Separable)
    (x : p.rootSet p.SplittingField) (E : Set.Iic F⟮(x : p.SplittingField)⟯) :
    (((rootBlockIntermediateFieldOrderIso hp hsep x).symm (OrderDual.toDual E) :
      BlockMem p.Gal x) : Set (p.rootSet p.SplittingField)) =
      Subtype.val ⁻¹' (minpoly E.1 (x : p.SplittingField)).rootSet p.SplittingField := by
  let _ : IsGalois F p.SplittingField := IsGalois.of_separable_splitting_field hsep
  let H := fixingSubgroup p.Gal (E.1 : Set p.SplittingField)
  have horbit (y : p.rootSet p.SplittingField) :
      y ∈ orbit H x ↔
        (y : p.SplittingField) ∈ orbit Gal(p.SplittingField/E.1) (x : p.SplittingField) := by
    constructor
    · rintro ⟨g, rfl⟩
      refine ⟨IsGaloisGroup.mulEquivCongr H Gal(p.SplittingField/E.1) E.1
        p.SplittingField g, ?_⟩
      simpa only [Subgroup.smul_def, Gal.coe_smul, Gal.smul_eq_apply] using
        IsGaloisGroup.mulEquivCongr_apply_smul H Gal(p.SplittingField/E.1) E.1
          p.SplittingField g (x : p.SplittingField)
    · rintro ⟨σ, hσ⟩
      obtain ⟨g, rfl⟩ :=
        (IsGaloisGroup.mulEquivCongr H Gal(p.SplittingField/E.1) E.1
          p.SplittingField).surjective σ
      refine ⟨g, Subtype.ext ?_⟩
      rw [← hσ]
      simpa only [Subgroup.smul_def, Gal.coe_smul, Gal.smul_eq_apply] using
        (IsGaloisGroup.mulEquivCongr_apply_smul H Gal(p.SplittingField/E.1) E.1
          p.SplittingField g (x : p.SplittingField)).symm
  rw [coe_rootBlockIntermediateFieldOrderIso_symm_apply]
  ext y
  rw [Set.mem_preimage, horbit, ← Normal.minpoly_eq_iff_mem_orbit p.SplittingField]
  have hint : IsIntegral E.1 (x : p.SplittingField) := IsIntegral.of_finite E.1 _
  rw [mem_rootSet]
  refine ⟨fun h ↦ ⟨minpoly.ne_zero hint, h ▸ minpoly.aeval E.1 (y : p.SplittingField)⟩,
    fun h ↦ ?_⟩
  exact (minpoly.eq_of_irreducible_of_monic (minpoly.irreducible hint) h.2
    (minpoly.monic hint)).symm

/-- **The Galois action on the roots is primitive exactly when the simple extension generated by
a root has no proper intermediate fields.** The degree assumption excludes the one-point action,
for which Mathlib's definition of primitivity is deliberately nontrivial. -/
theorem isPreprimitive_iff_isAtom_adjoin_simple
    (hp : Irreducible p) (hsep : p.Separable) (hdeg : 1 < p.natDegree)
    (x : p.rootSet p.SplittingField) :
    IsPreprimitive p.Gal (p.rootSet p.SplittingField) ↔
      IsAtom F⟮(x : p.SplittingField)⟯ := by
  let _ : IsPretransitive p.Gal (p.rootSet p.SplittingField) :=
    isPretransitive_of_irreducible hp
  have hcard : Fintype.card (p.rootSet p.SplittingField) = p.natDegree :=
    card_rootSet_eq_natDegree hsep (SplittingField.splits p)
  let _ : Nontrivial (p.rootSet p.SplittingField) :=
    Fintype.one_lt_card_iff_nontrivial.mp (by simpa only [hcard] using hdeg)
  rw [← isSimpleOrder_blockMem_iff_isPreprimitive p.Gal x,
    (rootBlockIntermediateFieldOrderIso hp hsep x).isSimpleOrder_iff,
    ← isSimpleOrder_iff_isSimpleOrder_orderDual, Set.isSimpleOrder_Iic_iff_isAtom]

/-- An irreducible separable polynomial of prime degree has a primitive Galois action on its
roots. -/
theorem isPreprimitive_of_irreducible_of_separable_of_prime_natDegree
    (hp : Irreducible p) (hsep : p.Separable) (hprime : p.natDegree.Prime) :
    IsPreprimitive p.Gal (p.rootSet p.SplittingField) := by
  let _ : IsPretransitive p.Gal (p.rootSet p.SplittingField) :=
    isPretransitive_of_irreducible hp
  apply IsPreprimitive.of_prime_card
  rw [Nat.card_eq_fintype_card,
    card_rootSet_eq_natDegree hsep (SplittingField.splits p)]
  exact hprime

end EpsilonEridani
