/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.FieldTheory.GaloisGroups.Reduction
public import EpsilonEridani.FieldTheory.GaloisGroups.Resolvent.Quintic.Basic

import Mathlib.Algebra.Polynomial.Eval.Irreducible
import Mathlib.RingTheory.AdjoinRoot

/-!
# Evidence for quintic Galois-group certificates

A factorization of a monic integral polynomial at a prime not dividing its discriminant gives
lower-bound evidence for its Galois group: the factor degrees are the full cycle type of an
element of the Galois image. A root of a separable resolvent gives upper-bound evidence. This
module packages those two kinds of evidence, together with the condition that a polynomial has a
formal second-root representative modulo the polynomial. For a monic irreducible polynomial,
this modular evidence represents a distinct second root in the field generated by one root.

The predicates contain only finite data. They do not search for a suitable prime, resolvent root,
or second root. Their elimination lemmas expose the mathematical consequences used by quintic
certificates, while keeping the proof of primality bundled with the factor-degree computation.

## Main definitions

* `EpsilonEridani.IsGoodPrime`: a prime candidate does not divide the polynomial discriminant.
* `EpsilonEridani.HasFactorDegrees`: a good prime with specified factor degrees.
* `EpsilonEridani.HasSexticRoot`: an integral root of a separable quintic resolvent sextic.
* `EpsilonEridani.HasSecondRootInRootField`: formal modular evidence for a second root, whose root-field
  interpretation requires the polynomial to be monic and irreducible.

## Main results

* `EpsilonEridani.HasFactorDegrees.exists_fullCycleType`: factor-degree evidence produces an element of
  the Galois image with that full cycle type.
* `EpsilonEridani.HasFactorDegrees.irreducible_map_rat`: singleton evidence proves irreducibility over
  `ℚ`.
* `EpsilonEridani.HasFactorDegrees.exists_orderOf_eq_two`,
  `EpsilonEridani.HasFactorDegrees.exists_orderOf_eq_three`, and
  `EpsilonEridani.HasFactorDegrees.exists_orderOf_eq_six`: the factor types used by the dihedral,
  alternating, and symmetric certificate routes produce elements of the required orders.
* `EpsilonEridani.HasSexticRoot.isRoot_specialize_rat` and
  `EpsilonEridani.HasSexticRoot.separable_specialize_rat`: the two consequences of resolvent evidence in
  the rational specialization used by quintic labels.
-/

public section
noncomputable section

open Equiv Equiv.Perm Polynomial

namespace EpsilonEridani

attribute [local instance] Polynomial.Gal.splits_ℚ_ℂ

-- The certificate predicates below implement the Layer 6 interface in the
-- PolynomialGaloisGroups roadmap:
-- https://github.com/EpsilonEridaniProject/EpsilonEridaniRoadmap/blob/main/EpsilonEridaniRoadmap/PolynomialGaloisGroups/README.md
/-- A good-prime factorization item: `p` is prime, does not divide the discriminant of `f`, and
the irreducible factors of `f` modulo `p` have degrees `t`, with multiplicity. -/
def HasFactorDegrees (f : ℤ[X]) (p : ℕ) (t : Multiset ℕ) : Prop :=
  ∃ hp : p.Prime, IsGoodPrime f p ∧ @Polynomial.factorDegrees f p ⟨hp⟩ = t

/-- The defining characterization of factor-degree evidence. -/
@[simp]
theorem hasFactorDegrees_iff (f : ℤ[X]) (p : ℕ) (t : Multiset ℕ) :
    HasFactorDegrees f p t ↔
      ∃ hp : p.Prime, IsGoodPrime f p ∧ @Polynomial.factorDegrees f p ⟨hp⟩ = t :=
  Iff.rfl

/-- Construct factor-degree evidence from a prime instance, goodness, and the factor degrees. -/
theorem HasFactorDegrees.mk {f : ℤ[X]} {p : ℕ} [hp : Fact p.Prime] {t : Multiset ℕ}
    (hgood : IsGoodPrime f p) (hfac : f.factorDegrees p = t) : HasFactorDegrees f p t :=
  ⟨hp.out, hgood, hfac⟩

/-- Eliminate factor-degree evidence while retaining a local primality instance. -/
theorem HasFactorDegrees.exists_fact {f : ℤ[X]} {p : ℕ} {t : Multiset ℕ}
    (h : HasFactorDegrees f p t) :
    ∃ hp : Fact p.Prime, IsGoodPrime f p ∧ @Polynomial.factorDegrees f p hp = t := by
  obtain ⟨hp, hgood, hfac⟩ := h
  exact ⟨⟨hp⟩, hgood, hfac⟩

/-- The factor degrees recorded by evidence for a monic polynomial sum to its degree. -/
theorem HasFactorDegrees.sum_eq_natDegree {f : ℤ[X]} {p : ℕ} {t : Multiset ℕ}
    (h : HasFactorDegrees f p t) (hf : f.Monic) : t.sum = f.natDegree := by
  obtain ⟨hp, -, rfl⟩ := h.exists_fact
  exact hf.sum_factorDegrees p

/-- Factor-degree evidence produces an element of the Galois image whose full cycle type is the
specified multiset. -/
theorem HasFactorDegrees.exists_fullCycleType {f : ℤ[X]} {p : ℕ} {t : Multiset ℕ}
    (h : HasFactorDegrees f p t) (hf : f.Monic) :
    ∃ σ ∈ (Polynomial.Gal.galActionHom (f.map (Int.castRingHom ℚ)) ℂ).range,
      σ.fullCycleType = t := by
  obtain ⟨hp, hgood, hfac⟩ := h.exists_fact
  let _ := hp
  obtain ⟨σ, hσ, htype⟩ :=
    exists_mem_range_galActionHom_fullCycleType_eq_factorDegrees hf p
      ((isGoodPrime_iff f p).mp hgood)
  exact ⟨σ, hσ, htype.trans hfac⟩

/-- Factor-degree evidence exhibits an element of the Galois image whose order is the least common
multiple of the specified factor degrees. -/
theorem HasFactorDegrees.exists_orderOf_eq_lcm {f : ℤ[X]} {p : ℕ} {t : Multiset ℕ}
    (h : HasFactorDegrees f p t) (hf : f.Monic) :
    ∃ σ ∈ (Polynomial.Gal.galActionHom (f.map (Int.castRingHom ℚ)) ℂ).range,
      orderOf σ = t.lcm := by
  obtain ⟨σ, hσ, htype⟩ := h.exists_fullCycleType hf
  refine ⟨σ, hσ, ?_⟩
  rw [← htype, Equiv.Perm.fullCycleType_def, Equiv.Perm.lcm_parts_partition]

/-- Factor degrees `(1,2,2)` exhibit an element of order two in the Galois image. This is the
lower-bound evidence that distinguishes the dihedral quintic label from the cyclic one. -/
theorem HasFactorDegrees.exists_orderOf_eq_two {f : ℤ[X]} {p : ℕ}
    (h : HasFactorDegrees f p {1, 2, 2}) (hf : f.Monic) :
    ∃ σ ∈ (Polynomial.Gal.galActionHom (f.map (Int.castRingHom ℚ)) ℂ).range,
      orderOf σ = 2 := by
  obtain ⟨σ, hσ, horder⟩ := h.exists_orderOf_eq_lcm hf
  exact ⟨σ, hσ, horder.trans (by decide)⟩

/-- Factor degrees `(2,3)` exhibit an element of order six in the Galois image. In degree five,
this is the lower-bound evidence for the full symmetric label. -/
theorem HasFactorDegrees.exists_orderOf_eq_six {f : ℤ[X]} {p : ℕ}
    (h : HasFactorDegrees f p {2, 3}) (hf : f.Monic) :
    ∃ σ ∈ (Polynomial.Gal.galActionHom (f.map (Int.castRingHom ℚ)) ℂ).range,
      orderOf σ = 6 := by
  obtain ⟨σ, hσ, horder⟩ := h.exists_orderOf_eq_lcm hf
  exact ⟨σ, hσ, horder.trans (by decide)⟩

/-- Factor degrees `(1,1,3)` exhibit an element of order three in the Galois image. In degree
five, this is the lower-bound evidence for the alternating label. -/
theorem HasFactorDegrees.exists_orderOf_eq_three {f : ℤ[X]} {p : ℕ}
    (h : HasFactorDegrees f p {1, 1, 3}) (hf : f.Monic) :
    ∃ σ ∈ (Polynomial.Gal.galActionHom (f.map (Int.castRingHom ℚ)) ℂ).range,
      orderOf σ = 3 := by
  obtain ⟨σ, hσ, horder⟩ := h.exists_orderOf_eq_lcm hf
  exact ⟨σ, hσ, horder.trans (by decide)⟩

/-- Singleton factor-degree evidence proves that the reduction is irreducible and records its
degree. -/
theorem HasFactorDegrees.irreducible_map {f : ℤ[X]} {p n : ℕ}
    (h : HasFactorDegrees f p {n}) :
    ∃ _hp : Fact p.Prime,
      Irreducible (f.map (Int.castRingHom (ZMod p))) ∧
        (f.map (Int.castRingHom (ZMod p))).natDegree = n := by
  obtain ⟨hp, -, hfac⟩ := h.exists_fact
  let _ := hp
  exact ⟨hp, Polynomial.factorDegrees_eq_singleton_iff.mp hfac⟩

/-- Any singleton factor-degree evidence for a monic polynomial proves that its image over
`ℚ` is irreducible. -/
theorem HasFactorDegrees.irreducible_map_rat {f : ℤ[X]} {p n : ℕ}
    (h : HasFactorDegrees f p {n}) (hf : f.Monic) :
    Irreducible (f.map (Int.castRingHom ℚ)) := by
  obtain ⟨hp, hirr, -⟩ := h.irreducible_map
  let _ := hp
  exact (IsPrimitive.Int.irreducible_iff_irreducible_map_cast hf.isPrimitive).mp
    (Monic.irreducible_of_irreducible_map (Int.castRingHom (ZMod p)) f hf hirr)

/-- A resolvent item: `a` is an integral root of the quintic resolvent sextic and the sextic has
nonzero discriminant. The latter condition is precisely the separation evidence needed to read
the root as an upper bound on the Galois image. -/
def HasSexticRoot (f : ℤ[X]) (a : ℤ) : Prop :=
  (resolventSextic f).eval a = 0 ∧ (resolventSextic f).discr ≠ 0

/-- The defining characterization of resolvent-root evidence. -/
@[simp]
theorem hasSexticRoot_iff (f : ℤ[X]) (a : ℤ) :
    HasSexticRoot f a ↔
      (resolventSextic f).eval a = 0 ∧ (resolventSextic f).discr ≠ 0 :=
  Iff.rfl

/-- Construct resolvent-root evidence from its two defining conditions. -/
theorem HasSexticRoot.mk {f : ℤ[X]} {a : ℤ} (hroot : (resolventSextic f).eval a = 0)
    (hdisc : (resolventSextic f).discr ≠ 0) : HasSexticRoot f a :=
  ⟨hroot, hdisc⟩

/-- The integer carried by resolvent evidence is a root of the resolvent sextic. -/
theorem HasSexticRoot.isRoot {f : ℤ[X]} {a : ℤ} (h : HasSexticRoot f a) :
    (resolventSextic f).IsRoot a :=
  h.1

/-- The resolvent sextic in a resolvent item becomes separable over `ℚ`. -/
theorem HasSexticRoot.separable_map_rat {f : ℤ[X]} {a : ℤ} (h : HasSexticRoot f a) :
    ((resolventSextic f).map (Int.castRingHom ℚ)).Separable :=
  (monic_resolventSextic f).discr_ne_zero_iff_separable_map ℚ |>.mp h.2

/-- Resolvent evidence remains a root after mapping the sextic and its root to any commutative
ring. -/
theorem HasSexticRoot.isRoot_map {F : Type*} [CommRing F] {f : ℤ[X]} {a : ℤ}
    (h : HasSexticRoot f a) :
    ((resolventSextic f).map (Int.castRingHom F)).IsRoot (a : F) :=
  h.isRoot.map

/-- Resolvent evidence gives a root of the rational specialization of the quintic
`F₂₀`-resolvent. -/
theorem HasSexticRoot.isRoot_specialize_rat {f : ℤ[X]} {a : ℤ} (h : HasSexticRoot f a) :
    (quinticF20Spec.specialize ℚ (f.map (Int.castRingHom ℚ))).IsRoot (a : ℚ) := by
  rw [← ResolventSpec.specialize_map, ← resolventSextic_def]
  exact h.isRoot_map

/-- The rational specialization of the quintic `F₂₀`-resolvent in a resolvent item is
separable. -/
theorem HasSexticRoot.separable_specialize_rat {f : ℤ[X]} {a : ℤ}
    (h : HasSexticRoot f a) :
    (quinticF20Spec.specialize ℚ (f.map (Int.castRingHom ℚ))).Separable := by
  rw [← ResolventSpec.specialize_map, ← resolventSextic_def]
  exact h.separable_map_rat

/-- Formal modular evidence that `b` is a root representative distinct from the class of `X`.
When `f` is monic and irreducible, the quotient is the field generated by one root and this
evidence represents a distinct second root there. -/
def HasSecondRootInRootField (f : ℤ[X]) (b : ℚ[X]) : Prop :=
  ((f.map (Int.castRingHom ℚ)).comp b) %ₘ (f.map (Int.castRingHom ℚ)) = 0 ∧
    b %ₘ (f.map (Int.castRingHom ℚ)) ≠ X %ₘ (f.map (Int.castRingHom ℚ))

/-- The defining characterization of formal second-root evidence. -/
@[simp]
theorem hasSecondRootInRootField_iff (f : ℤ[X]) (b : ℚ[X]) :
    HasSecondRootInRootField f b ↔
      ((f.map (Int.castRingHom ℚ)).comp b) %ₘ (f.map (Int.castRingHom ℚ)) = 0 ∧
        b %ₘ (f.map (Int.castRingHom ℚ)) ≠ X %ₘ (f.map (Int.castRingHom ℚ)) :=
  Iff.rfl

/-- Construct formal second-root evidence from its two defining congruences. -/
theorem HasSecondRootInRootField.mk {f : ℤ[X]} {b : ℚ[X]}
    (hroot : ((f.map (Int.castRingHom ℚ)).comp b) %ₘ (f.map (Int.castRingHom ℚ)) = 0)
    (hne : b %ₘ (f.map (Int.castRingHom ℚ)) ≠ X %ₘ (f.map (Int.castRingHom ℚ))) :
    HasSecondRootInRootField f b :=
  ⟨hroot, hne⟩

/-- The polynomial represented by a second-root item vanishes after substitution, modulo `f`. -/
theorem HasSecondRootInRootField.comp_modByMonic_eq_zero {f : ℤ[X]} {b : ℚ[X]}
    (h : HasSecondRootInRootField f b) :
    ((f.map (Int.castRingHom ℚ)).comp b) %ₘ (f.map (Int.castRingHom ℚ)) = 0 :=
  h.1

/-- The polynomial represented by a second-root item is not the distinguished root `X` modulo
`f`. -/
theorem HasSecondRootInRootField.modByMonic_ne_X_modByMonic {f : ℤ[X]} {b : ℚ[X]}
    (h : HasSecondRootInRootField f b) :
    b %ₘ (f.map (Int.castRingHom ℚ)) ≠ X %ₘ (f.map (Int.castRingHom ℚ)) :=
  h.2

/-- For a monic polynomial, formal second-root evidence gives the represented root in
`AdjoinRoot` and proves that it differs from the distinguished root. -/
theorem HasSecondRootInRootField.isRoot_mk_and_ne_root {f : ℤ[X]} {b : ℚ[X]}
    (h : HasSecondRootInRootField f b) (hf : f.Monic) :
    let fℚ := f.map (Int.castRingHom ℚ)
    ((fℚ.map (algebraMap ℚ (AdjoinRoot fℚ))).IsRoot (AdjoinRoot.mk fℚ b)) ∧
      AdjoinRoot.mk fℚ b ≠ AdjoinRoot.root fℚ := by
  let fℚ := f.map (Int.castRingHom ℚ)
  have hfℚ : fℚ.Monic := hf.map _
  have hdiv : fℚ ∣ fℚ.comp b :=
    (modByMonic_eq_zero_iff_dvd hfℚ).mp h.comp_modByMonic_eq_zero
  have heval : (fℚ.map (algebraMap ℚ (AdjoinRoot fℚ))).eval (AdjoinRoot.mk fℚ b) =
      AdjoinRoot.mk fℚ (fℚ.comp b) := by
    rw [eval_map, ← aeval_def, ← AdjoinRoot.aeval_eq b, ← aeval_comp,
      AdjoinRoot.aeval_eq]
  constructor
  · rw [Polynomial.IsRoot, heval, AdjoinRoot.mk_eq_zero]
    exact hdiv
  · intro heq
    apply h.modByMonic_ne_X_modByMonic
    have heq' : AdjoinRoot.mk fℚ b = AdjoinRoot.mk fℚ X :=
      heq.trans (AdjoinRoot.mk_X).symm
    have hmod := congrArg (AdjoinRoot.modByMonicHom hfℚ) heq'
    rw [AdjoinRoot.modByMonicHom_mk, AdjoinRoot.modByMonicHom_mk] at hmod
    exact hmod

end EpsilonEridani
