/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Codex
-/
module

public import EpsilonEridani.InformationTheory.Coding.GeneratorParityCheck
public import EpsilonEridani.InformationTheory.Coding.Weight.Enumerator
public import Mathlib.Algebra.Field.ZMod

import Mathlib.LinearAlgebra.Matrix.Notation

/-!
# The ternary tetracode

The tetracode is the row space over `ZMod 3` of the matrix with rows `(1,0,1,1)` and
`(0,1,1,-1)`. It is a Euclidean self-dual code of length four and dimension two, and all
eight nonzero words have weight three. Its homogeneous weight enumerator is
`X^4 + 8XY^3`.

The membership criterion identifies its words with `(a,b,a+b,a-b)`. The displayed generator
is also a parity-check matrix, independently verifying self-duality through the matrix API.
These explicit parameters and weights make the code usable in ternary lattice constructions.

## References

W. C. Huffman and V. Pless, *Fundamentals of Error-Correcting Codes*, Cambridge University
Press (2003), Example 1.3.3.
-/

public section

namespace EpsilonEridani

open Matrix MvPolynomial

/-- The standard systematic generator matrix of the ternary tetracode. -/
def tetracodeGenerator : Matrix (Fin 2) (Fin 4) (ZMod 3) :=
  !![1, 0, 1, 1; 0, 1, 1, -1]

/-- The entries of the standard tetracode generator. -/
theorem tetracodeGenerator_def :
    tetracodeGenerator = !![1, 0, 1, 1; 0, 1, 1, -1] := (rfl)

/-- The ternary tetracode, as the row space of its standard generator matrix. -/
def tetracode : LinearCode (ZMod 3) (Fin 4) :=
  tetracodeGenerator.generatedBy

/-- The tetracode is generated by the displayed two-row matrix. -/
theorem tetracode_def : tetracode = tetracodeGenerator.generatedBy := (rfl)

/-- Multiplication by the generator encodes the information symbols in the first two positions. -/
@[simp]
theorem vecMul_tetracodeGenerator (a : Fin 2 → ZMod 3) :
    a ᵥ* tetracodeGenerator = ![a 0, a 1, a 0 + a 1, a 0 - a 1] := by
  ext i
  fin_cases i <;> simp [tetracodeGenerator, vecMul, dotProduct, Fin.sum_univ_two, sub_eq_add_neg]

/-- A word is in the tetracode exactly when its last two symbols are the sum and difference
of its first two symbols. -/
@[simp]
theorem mem_tetracode_iff (x : Fin 4 → ZMod 3) :
    x ∈ tetracode ↔ x 2 = x 0 + x 1 ∧ x 3 = x 0 - x 1 := by
  rw [tetracode_def, Matrix.mem_generatedBy_iff]
  constructor
  · rintro ⟨a, rfl⟩
    simp
  · rintro ⟨h₂, h₃⟩
    refine ⟨![x 0, x 1], ?_⟩
    rw [vecMul_tetracodeGenerator]
    ext i
    fin_cases i <;> simp [h₂, h₃]

/-- The generator matrix also checks the tetracode. -/
-- Use this as an explicit rewrite: `Matrix.checkedBy_eq_euclideanDual_generatedBy` already
-- simplifies its left-hand side, so a `simp` annotation here would violate `simpNF`.
theorem checkedBy_tetracodeGenerator : tetracodeGenerator.checkedBy = tetracode := by
  ext x
  rw [Matrix.mem_checkedBy_iff, mem_tetracode_iff]
  exact (by decide : ∀ x : Fin 4 → ZMod 3,
    tetracodeGenerator *ᵥ x = 0 ↔ x 2 = x 0 + x 1 ∧ x 3 = x 0 - x 1) x

/-- The tetracode is Euclidean self-dual. -/
@[simp]
theorem euclideanDual_tetracode : tetracode.euclideanDual = tetracode := by
  rw [tetracode_def, ← Matrix.checkedBy_eq_euclideanDual_generatedBy,
    checkedBy_tetracodeGenerator, ← tetracode_def]

/-- The tetracode has dimension two over the ternary field. -/
@[simp]
theorem finrank_tetracode : Module.finrank (ZMod 3) tetracode = 2 := by
  have h := Submodule.two_mul_finrank_eq_card_of_eq_euclideanDual
    euclideanDual_tetracode.symm
  norm_num at h
  omega

/-- The tetracode has nine words. -/
@[simp↓]
theorem natCard_tetracode : Nat.card tetracode = 9 := by
  rw [Module.natCard_eq_pow_finrank (K := ZMod 3), finrank_tetracode]
  norm_num [Nat.card_eq_fintype_card]

/-- Every nonzero tetracode word has weight three. -/
theorem hammingNorm_eq_three_of_mem_tetracode_of_ne_zero {x : Fin 4 → ZMod 3}
    (hx : x ∈ tetracode) (hx0 : x ≠ 0) : hammingNorm x = 3 := by
  rw [mem_tetracode_iff] at hx
  exact (by decide : ∀ x : Fin 4 → ZMod 3,
    (x 2 = x 0 + x 1 ∧ x 3 = x 0 - x 1) → x ≠ 0 → hammingNorm x = 3) x hx hx0

/-- The minimum distance of the tetracode is three. -/
@[simp]
theorem hammingMinDist_tetracode : (tetracode : Set (Fin 4 → ZMod 3)).hammingMinDist = 3 := by
  have hne : tetracode.toAddSubgroup ≠ ⊥ := by
    intro h
    have hm : ![1, 0, 1, 1] ∈ tetracode := by simp
    have hz : ![1, 0, 1, 1] = (0 : Fin 4 → ZMod 3) := by
      exact AddSubgroup.mem_bot.mp (h ▸ hm)
    have := congrFun hz 0
    norm_num at this
  obtain ⟨x, hx, hx0, hd⟩ := Set.exists_hammingNorm_eq_hammingMinDist hne
  exact hd.symm.trans (hammingNorm_eq_three_of_mem_tetracode_of_ne_zero hx hx0)

/-- The weight distribution of the tetracode consists of one word of weight zero and eight
words of weight three. -/
@[simp]
theorem weightDistribution_tetracode (w : ℕ) :
    (tetracode : Set (Fin 4 → ZMod 3)).weightDistribution w =
      if w = 0 then 1 else if w = 3 then 8 else 0 := by
  simpa only [SetLike.coe_sort_coe, natCard_tetracode, Nat.reduceSub] using
    weightDistribution_eq_of_constant_weight (Set.toFinite _) tetracode.zero_mem
      (by decide : 3 ≠ 0) (fun _ hx hx0 ↦
        hammingNorm_eq_three_of_mem_tetracode_of_ne_zero hx hx0) w

/-- The homogeneous weight enumerator of the tetracode is `X^4 + 8XY^3`. -/
@[simp]
theorem weightEnumerator_tetracode :
    (tetracode : Set (Fin 4 → ZMod 3)).weightEnumerator =
      X 0 ^ 4 + 8 * X 0 * X 1 ^ 3 := by
  simp [Set.weightEnumerator_def, weightDistribution_tetracode, Finset.sum_range_succ]

end EpsilonEridani
