/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.NumberTheory.Multiquadratic.Quadratic.Ramification
import EpsilonEridani.NumberTheory.Multiquadratic.Galois.Basic
import EpsilonEridani.NumberTheory.NumberField.Inertia

/-!
# The ramified primes of a multiquadratic field

Let `d₁, …, dₙ` be squarefree integers and let `M = ℚ(√d₁, …, √dₙ)`. A rational prime `p`
ramifies in `M` exactly when it ramifies in one of the possibly trivial square-root-generated
factors `ℚ(√dᵢ)`, that is, when it divides one of the fundamental discriminants
`fundamentalDiscriminant dᵢ`. Concretely:

* an odd prime ramifies in `M` exactly when it divides some `dᵢ`;
* the prime `2` ramifies in `M` exactly when some `dᵢ` is not `1` modulo `4`.

Thus the odd primes excluded by the multiquadratic splitting law
(`NumberField.ncard_primesOver_multiquadratic_iff`, which assumes `p ∤ dᵢ` for every `i`) are
exactly the odd ramified primes, and at `2` the ramification is governed by the discriminants
`dᵢ` or `4dᵢ` of the fields generated by the individual square roots rather than by the
radicands themselves.

The reduction to the individual square-root factors is `NumberField.ramifiedPrimes_iSup`: in a
Galois number field, a compositum ramifies exactly where one of its factors does. The quadratic
case, including the trivial factor contributed by the radicand `1`, is
`EpsilonEridani.Multiquadratic.mem_ramifiedPrimes_adjoin_iff_dvd_fundamentalDiscriminant`, so the
radicands need not be nonsquares.

## Main results

* `EpsilonEridani.Multiquadratic.mem_ramifiedPrimes_adjoin_range_iff`: the ramified primes of the
  subfield `ℚ(√d₁, …, √dₙ)` of a number field.
* `EpsilonEridani.Multiquadratic.mem_ramifiedPrimes_iff_exists_dvd_fundamentalDiscriminant`: the same
  for a number field generated by the square roots.
* `EpsilonEridani.Multiquadratic.isUnramifiedIn_iff_forall_not_dvd_of_ne_two`: an odd prime is
  unramified exactly when it divides none of the radicands.
* `EpsilonEridani.Multiquadratic.isUnramifiedIn_two_iff_forall_mod_four_eq_one`: the prime `2` is
  unramified exactly when every radicand is `1` modulo `4`.

## References

* D. A. Cox, *Primes of the Form x² + ny²*, §5.B and §6.A.
* F. Lemmermeyer, *Reciprocity Laws: From Euler to Eisenstein*, §2.2.
-/

public section

open IntermediateField NumberField
open scoped NumberField

namespace EpsilonEridani.Multiquadratic

variable {ι : Type*} [Finite ι] {L : Type*} [Field L] [NumberField L]
  {d : ι → ℤ} {r : ι → L}

/-- **The ramified primes of a multiquadratic field.** Let `r i` be square roots of squarefree
integers `d i` in a number field. A rational prime ramifies in `ℚ(r i : i)` exactly when it
divides the fundamental discriminant of one of the `d i`, that is, exactly when it ramifies in one
of the possibly trivial square-root-generated factors `ℚ(r i)`. -/
theorem mem_ramifiedPrimes_adjoin_range_iff (hd : ∀ i, Squarefree (d i))
    (hr : ∀ i, r i ^ 2 = algebraMap ℤ L (d i)) {p : ℕ} (hp : p.Prime) :
    p ∈ ramifiedPrimes (adjoin ℚ (Set.range r)) ↔
      ∃ i, (p : ℤ) ∣ fundamentalDiscriminant (d i) := by
  have hrℚ (i : ι) : r i ^ 2 = algebraMap ℚ L (d i : ℚ) := by
    rw [hr i, eq_intCast, map_intCast]
  have : IsGalois ℚ (adjoin ℚ (Set.range r)) := isGalois hrℚ
  have hgen (i : ι) : gen (K := ℚ) r i ^ 2 = algebraMap ℤ (adjoin ℚ (Set.range r)) (d i) := by
    rw [gen_sq hrℚ, eq_intCast, map_intCast]
  have hsup : adjoin ℚ (Set.range (gen (K := ℚ) r)) = ⨆ i, adjoin ℚ {gen (K := ℚ) r i} := by
    rw [← adjoin_iUnion, Set.iUnion_singleton_eq_range]
  rw [← ((equivOfEq (adjoin_gen_eq_top (K := ℚ) (root := r))).trans topEquiv).ramifiedPrimes_eq,
    hsup, ramifiedPrimes_iSup, Set.mem_iUnion]
  exact exists_congr fun i =>
    mem_ramifiedPrimes_adjoin_iff_dvd_fundamentalDiscriminant (hd i) (hgen i) hp

/-- **The ramified primes of a field generated by square roots.** The form of
`mem_ramifiedPrimes_adjoin_range_iff` for a number field `L` generated by square roots of
squarefree integers. -/
theorem mem_ramifiedPrimes_iff_exists_dvd_fundamentalDiscriminant (hd : ∀ i, Squarefree (d i))
    (hr : ∀ i, r i ^ 2 = algebraMap ℤ L (d i)) (htop : adjoin ℚ (Set.range r) = ⊤) {p : ℕ}
    (hp : p.Prime) :
    p ∈ ramifiedPrimes L ↔ ∃ i, (p : ℤ) ∣ fundamentalDiscriminant (d i) := by
  rw [← mem_ramifiedPrimes_adjoin_range_iff hd hr hp,
    ((equivOfEq htop).trans topEquiv).ramifiedPrimes_eq]

/-- **The odd ramified primes are the divisors of the radicands.** In a number field `L` generated
by square roots of squarefree integers `d i`, an odd prime `p` is unramified exactly when it
divides none of the `d i`. -/
theorem isUnramifiedIn_iff_forall_not_dvd_of_ne_two (hd : ∀ i, Squarefree (d i))
    (hr : ∀ i, r i ^ 2 = algebraMap ℤ L (d i)) (htop : adjoin ℚ (Set.range r) = ⊤) {p : ℕ}
    (hp : p.Prime) (hp2 : p ≠ 2) :
    Algebra.IsUnramifiedIn (𝓞 L) (Ideal.span {(p : ℤ)}) ↔ ∀ i, ¬ (p : ℤ) ∣ d i := by
  have hcop : IsCoprime (p : ℤ) 2 := by
    have h := Nat.isCoprime_iff_coprime.mpr ((Nat.coprime_primes hp Nat.prime_two).mpr hp2)
    exact_mod_cast h
  have h := (mem_ramifiedPrimes_iff_exists_dvd_fundamentalDiscriminant hd hr htop hp).not
  simp only [mem_ramifiedPrimes_iff, hp, true_and, not_not, not_exists,
    dvd_fundamentalDiscriminant_iff hcop] at h
  exact h

/-- **The prime `2` is unramified exactly when every radicand is `1` modulo `4`.** In a number
field generated by square roots of squarefree integers `d i`, the prime `2` is unramified exactly
when `d i ≡ 1 (mod 4)` for every `i`. -/
theorem isUnramifiedIn_two_iff_forall_mod_four_eq_one (hd : ∀ i, Squarefree (d i))
    (hr : ∀ i, r i ^ 2 = algebraMap ℤ L (d i)) (htop : adjoin ℚ (Set.range r) = ⊤) :
    Algebra.IsUnramifiedIn (𝓞 L) (Ideal.span {(2 : ℤ)}) ↔ ∀ i, d i % 4 = 1 := by
  have h := (mem_ramifiedPrimes_iff_exists_dvd_fundamentalDiscriminant hd hr htop
    Nat.prime_two).not
  simp only [mem_ramifiedPrimes_iff, Nat.prime_two, true_and, not_not, not_exists,
    Nat.cast_ofNat, two_not_dvd_fundamentalDiscriminant_iff_mod_four_eq_one] at h
  exact h

end EpsilonEridani.Multiquadratic
