/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.NumberTheory.Multiquadratic.Quadratic.RamifiedPrime.Independence
public import EpsilonEridani.NumberTheory.Multiquadratic.Quadratic.RamifiedPrime.Narrow
public import EpsilonEridani.NumberTheory.NumberField.NarrowClassGroup.ElementaryTwoQuotient
import EpsilonEridani.NumberTheory.NumberField.Quadratic.Conjugation.NarrowClassGroup
import EpsilonEridani.NumberTheory.NumberField.Quadratic.InfinitePlace
import Mathlib.NumberTheory.NumberField.ClassNumber
import EpsilonEridani.Data.ZMod.IntUnitsPower
import EpsilonEridani.NumberTheory.Multiquadratic.Quadratic.GenusCharacter.ElementaryTwoQuotient
import EpsilonEridani.NumberTheory.Multiquadratic.Quadratic.GenusCharacter.Independence
import Mathlib.LinearAlgebra.Dimension.Constructions
import Mathlib.LinearAlgebra.FiniteDimensional.Lemmas

/-!
# The `2`-rank of a quadratic class group

For a squarefree integer `d` let `K = ℚ(√d)` and let `t` be the number of rational primes that
ramify in `K`. Genus theory computes the `2`-rank of the *narrow* class group `Cl⁺(K)`,
the dimension over `𝔽₂` of `Cl⁺(K)/Cl⁺(K)²`, to be exactly `t - 1`. This file proves that formula,

`2-rank Cl⁺(K) = t - 1`,

for a quadratic field of **either signature**: the upper bound is the ambiguous class number bound,
and the lower bound is the independence of the genus characters. The ordinary bound
`2-rank Cl(K) ≤ t - 1` follows because forgetting positivity is surjective
(`NumberField.NarrowClassGroup.classGroupTwoRank_le_twoRank`). It is the class-group counterpart of
the field-theoretic `2 ^ (t - 1)` available for the candidate genus field, whose degree over the
embedded copy of `K` is `2 ^ (t - 1)`
(`finrank_candidateGenusField_over_candidateGenusFieldBase_eq_two_pow_ncard_ramifiedPrimes`).

Two inputs combine. The `2`-torsion of `Cl⁺(K)` is generated by the narrow classes of the ramified
primes (`NumberField.NarrowClassGroup.mem_closure_of_sq_eq_one`, which rests on the Hilbert-90
descent to ambiguous ideals — narrowly, with no hypothesis on the signature), and the subgroup those
classes generate has at most `2 ^ (t - 1)` elements (`natCard_closure_image_narrowMk0_le`, where the
`- 1` comes from the narrow relation `exists_nonempty_prod_narrowMk0_eq_one`). Since the maximal
elementary-`2` quotient and the `2`-torsion subgroup have the same cardinality,
`2 ^ (2-rank) ≤ 2 ^ (t - 1)`.

The lower bound `t - 1 ≤ 2-rank Cl⁺(K)` comes from the genus characters. The `t` prime discriminants
dividing the discriminant of `K` give `t` characters of `Cl⁺(K)` with values `±1`
(`genusCharFunNarrowClassGroupHom`), hence a `ZMod 2`-linear map `Cl⁺(K)/Cl⁺(K)² → (ZMod 2)^t`.
Every sign pattern of product `1` is attained, by the class of a degree-one prime ideal supplied by
Dirichlet's theorem (`exists_forall_genusCharFunNarrowClassGroupHom_singleton_eq`), so the image
contains a hyperplane and the `2`-rank is at least `t - 1`.

For an *imaginary* quadratic field the narrow and ordinary class groups coincide, and the ordinary
lower bound also follows from the independence of the ramified-prime classes
(`EpsilonEridani.Multiquadratic.ncard_ramifiedPrimes_sub_one_le_twoRank`); combining it with the upper
bound gives the imaginary quadratic `2`-rank formula for `Cl(K)`. For a real quadratic field the
ordinary `2`-rank can be strictly smaller than `t - 1` — `ℚ(√3)` has `t = 2` and class number `1` —
so there the formula is genuinely a statement about `Cl⁺(K)`.

See F. Lemmermeyer, *Reciprocity Laws: From Euler to Eisenstein*, §2.2, which runs the same
route: its Proposition 2.9 is the Hilbert-90 descent realising an ambiguous class by an ambiguous
ideal, and its "first inequality" `#Cl⁺/Cl⁺² ≤ 2^(t-1)` is the bound proved here. D. A. Cox,
*Primes of the Form x² + ny²*, §6.A has the same statement for field discriminants, and §3.B the
form-theoretic genus theory it descends from.

## Main results

* `EpsilonEridani.Multiquadratic.narrowTwoRank_le_ncard_ramifiedPrimes_sub_one`: the upper bound on the
  narrow `2`-rank of a quadratic field.
* `EpsilonEridani.Multiquadratic.twoRank_le_ncard_ramifiedPrimes_sub_one`: the same bound for the ordinary
  `2`-rank.
* `EpsilonEridani.Multiquadratic.twoRank_eq_ncard_ramifiedPrimes_sub_one`: the `2`-rank of an imaginary
  quadratic class group is exactly `t - 1`.
* `EpsilonEridani.Multiquadratic.ncard_ramifiedPrimes_sub_one_le_narrowTwoRank`: the lower bound on the
  narrow `2`-rank of a quadratic field of either signature.
* `EpsilonEridani.Multiquadratic.narrowTwoRank_eq_ncard_ramifiedPrimes_sub_one`: the narrow `2`-rank of a
  quadratic field of either signature is exactly `t - 1`.
* `EpsilonEridani.Multiquadratic.twoRank_eq_ncard_ramifiedPrimes_sub_one_of_exists_norm_eq_neg_one`: the
  ordinary `2`-rank is also exactly `t - 1` when some unit of `𝓞 K` has norm `-1`.
* `EpsilonEridani.Multiquadratic.ncard_ramifiedPrimes_sub_two_le_twoRank` and
  `EpsilonEridani.Multiquadratic.twoRank_eq_ncard_ramifiedPrimes_sub_one_or_sub_two`: the ordinary
  `2`-rank of any field of degree `2` over `ℚ` is `t - 1` or `t - 2`.
-/

public section

open Polynomial NumberField
open scoped NumberField nonZeroDivisors

namespace EpsilonEridani.Multiquadratic

variable {K : Type*} [Field K] [NumberField K] {θ : 𝓞 K} {d : ℤ}

/-- **The narrow ambiguous class number bound.** For `K = ℚ(√d)` with `d` squarefree and `1 < |d|`,
the `2`-rank of the narrow class group `Cl⁺(K)` is at most `t - 1`, where `t` is the number of
rational primes ramifying in `K`. No hypothesis on the signature of `K` is needed.

The `2`-torsion of `Cl⁺(K)` is generated by the narrow classes of the ramified primes, and those
classes satisfy a relation, so they span at most `2 ^ (t - 1)` classes. The hypothesis `1 < |d|`
excludes `d = -1`, where the radicand has no prime factor; see
`exists_nonempty_prod_narrowMk0_eq_one`. -/
theorem narrowTwoRank_le_ncard_ramifiedPrimes_sub_one
    (hmin : minpoly ℤ θ = X ^ 2 - C d) (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤)
    (hsf : Squarefree d) (hd : 1 < d.natAbs) :
    NumberField.NarrowClassGroup.twoRank K ≤ (ramifiedPrimes K).ncard - 1 := by
  classical
  set s := (NumberField.finite_ramifiedPrimes (K := K)).toFinset
  have hscoe : (s : Set ℕ) = ramifiedPrimes K := Set.Finite.coe_toFinset _
  have hcard : s.card = (ramifiedPrimes K).ncard := by
    rw [← Set.ncard_coe_finset, hscoe]
  obtain ⟨Q, hprimes, hovers⟩ :=
    NumberField.exists_primeIdealFamily (K := K) s fun p hp =>
      prime_of_mem_ramifiedPrimes (hscoe ▸ Finset.mem_coe.mpr hp)
  have hmems : ∀ p ∈ ramifiedPrimes K, p ∈ s := fun p hp =>
    Finset.mem_coe.mp (hscoe ▸ hp)
  have hprime : ∀ p ∈ ramifiedPrimes K, (Q p : Ideal (𝓞 K)).IsPrime := fun p hp =>
    hprimes p (hmems p hp)
  have hover : ∀ p ∈ ramifiedPrimes K,
      (Q p : Ideal (𝓞 K)).LiesOver (Ideal.span {(p : ℤ)}) := fun p hp => hovers p (hmems p hp)
  -- The `2`-torsion injects into the subgroup generated by the narrow classes of the ramified
  -- primes, which has at most `2 ^ (t - 1)` elements.
  have hinj : Nat.card {C : NumberField.NarrowClassGroup K // C ^ 2 = 1} ≤
      Nat.card (Subgroup.closure
        ((fun p ↦ NumberField.NarrowClassGroup.mk0 (Q p)) '' (↑s : Set ℕ))) := by
    refine Nat.card_le_card_of_injective
      (fun C => ⟨C.1, hscoe.symm ▸ NumberField.NarrowClassGroup.mem_closure_of_sq_eq_one hmin hgen
        hprime hover C.2⟩) ?_
    intro a b h
    exact Subtype.ext (Subtype.mk_eq_mk.mp h)
  have hbound := hinj.trans
    (natCard_closure_image_narrowMk0_le hmin hgen hsf hd hscoe hprime hover)
  have hpow : (2 : ℕ) ^ NumberField.NarrowClassGroup.twoRank K ≤ 2 ^ (s.card - 1) := by
    rw [← NumberField.NarrowClassGroup.card_elementaryTwoQuotient_eq_two_pow_twoRank,
      EpsilonEridani.card_elementaryTwoQuotient_eq_card_twoTorsion]
    exact hbound
  rw [← hcard]
  exact (Nat.pow_le_pow_iff_right (le_refl 2)).mp hpow

/-- **The ambiguous class number bound.** For `K = ℚ(√d)` with `d` squarefree and `1 < |d|`, the
`2`-rank of `Cl(𝓞 K)` is at most `t - 1`, where `t` is the number of rational primes ramifying in
`K`.

Forgetting total positivity is a surjection `Cl⁺(K) → Cl(K)`, so the ordinary `2`-rank is at most
the narrow one, which `narrowTwoRank_le_ncard_ramifiedPrimes_sub_one` bounds by `t - 1`. For a real
quadratic field the inequality can be strict: `ℚ(√3)` has `t = 2` and class number `1`. -/
theorem twoRank_le_ncard_ramifiedPrimes_sub_one
    (hmin : minpoly ℤ θ = X ^ 2 - C d) (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤)
    (hsf : Squarefree d) (hd : 1 < d.natAbs) :
    EpsilonEridani.ClassGroup.twoRank (𝓞 K) ≤ (ramifiedPrimes K).ncard - 1 :=
  (NumberField.NarrowClassGroup.classGroupTwoRank_le_twoRank K).trans
    (narrowTwoRank_le_ncard_ramifiedPrimes_sub_one hmin hgen hsf hd)

/-- **The `2`-rank formula for an imaginary quadratic field.** For `K = ℚ(√d)` with `d < 0`
squarefree, the `2`-rank of `Cl(𝓞 K)` is exactly `t - 1`, where `t` is the number of rational
primes ramifying in `K`. -/
theorem twoRank_eq_ncard_ramifiedPrimes_sub_one
    (hmin : minpoly ℤ θ = X ^ 2 - C d) (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤)
    (hsf : Squarefree d) (hd : d < 0) :
    EpsilonEridani.ClassGroup.twoRank (𝓞 K) = (ramifiedPrimes K).ncard - 1 := by
  let _ : IsTotallyComplex K :=
    NumberField.isTotallyComplex_of_minpoly_eq_X_sq_sub_C_of_neg hmin hd
  by_cases hgauss : d = -1
  · subst d
    have hfin : Module.finrank ℚ K = 2 := NumberField.finrank_rat_eq_two hmin hgen
    have hcomplex : InfinitePlace.nrComplexPlaces K = 1 :=
      InfinitePlace.nrComplexPlaces_eq_one_of_finrank_eq_two hfin
    have hdisc : NumberField.discr K = -4 := by
      simpa using NumberField.discr_eq_four_mul_of_mod_four_ne_one hmin hgen hsf (by norm_num)
    have hpid : IsPrincipalIdealRing (𝓞 K) := by
      apply RingOfIntegers.isPrincipalIdealRing_of_abs_discr_lt
      rw [hdisc, hcomplex, hfin]
      norm_num [abs_of_nonneg]
      nlinarith [Real.pi_gt_three]
    have hrank : EpsilonEridani.ClassGroup.twoRank (𝓞 K) = 0 := by
      have hclass : NumberField.classNumber K = 1 :=
        NumberField.classNumber_eq_one_iff.mpr hpid
      rw [EpsilonEridani.ClassGroup.twoRank_def, ← EpsilonEridani.twoRank_def]
      apply EpsilonEridani.twoRank_of_odd_card
      rw [Nat.card_eq_fintype_card, ← NumberField.classNumber, hclass]
      exact odd_one
    have hram : ramifiedPrimes K = {2} := by
      rw [← primeDiscriminantPrime_of_isEvenPrimeDiscriminant isEvenPrimeDiscriminant_neg_four]
      apply ramifiedPrimes_eq_singleton (D := -4) isPrimeDiscriminant_neg_four
      · rwa [primeDiscriminantRadicand_neg_four]
      · exact hgen
    rw [hrank, hram, Set.ncard_singleton]
  · apply le_antisymm
    · exact twoRank_le_ncard_ramifiedPrimes_sub_one hmin hgen hsf (by
        have hdabs : (1 : ℤ) < |d| := by rw [abs_of_neg hd]; omega
        rwa [Int.abs_eq_natAbs, Nat.one_lt_cast] at hdabs)
    · exact ncard_ramifiedPrimes_sub_one_le_twoRank hmin hgen hsf (by omega)

/-! ### The narrow lower bound -/

/-- **The genus characters bound the narrow `2`-rank from below.** Let `K = ℚ(√d)` with `d`
squarefree and let `∏ P ∈ s, P = fundamentalDiscriminant d` be the prime-discriminant factorization,
`t = #s`. Then `t - 1 ≤ 2-rank Cl⁺(K)`. -/
theorem card_sub_one_le_narrowTwoRank {s : Finset ℤ}
    (hs : ∀ P ∈ s, IsPrimeDiscriminant P)
    (heven : ∀ P ∈ s, ∀ P' ∈ s, IsEvenPrimeDiscriminant P → IsEvenPrimeDiscriminant P' → P = P')
    (hprod : ∏ P ∈ s, P = fundamentalDiscriminant d)
    (hmin : minpoly ℤ θ = X ^ 2 - C d) (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤)
    (hsf : Squarefree d) :
    s.card - 1 ≤ NumberField.NarrowClassGroup.twoRank K := by
  classical
  rcases s.eq_empty_or_nonempty with rfl | hne
  · simp
  let _ : Nonempty ↥s := hne.to_subtype
  -- The family of singleton genus characters, and the coordinate-sum functional.
  set Φ := genusCharFunElementaryTwoQuotientFamilyLinearMap hs heven hprod hmin hgen hsf
  let σ := EpsilonEridani.additiveIntUnitsCoordinateSum ↥s
  -- Every vector of coordinate sum `0` is a value of `Φ`.
  have hker : LinearMap.ker σ ≤ LinearMap.range Φ := by
    intro v hv
    rw [LinearMap.mem_ker, EpsilonEridani.additiveIntUnitsCoordinateSum_apply] at hv
    obtain ⟨x, hx⟩ :=
      exists_genusCharFunElementaryTwoQuotientFamilyLinearMap_eq hs heven hprod hmin hgen hsf v hv
    exact ⟨x, hx⟩
  calc s.card - 1 = Module.finrank (ZMod 2) (LinearMap.ker σ) := by
        simpa [σ] using (EpsilonEridani.finrank_ker_additiveIntUnitsCoordinateSum ↥s).symm
    _ ≤ Module.finrank (ZMod 2) (LinearMap.range Φ) := Submodule.finrank_mono hker
    _ ≤ Module.finrank (ZMod 2) (NumberField.NarrowClassGroup.ElementaryTwoQuotient K) :=
        LinearMap.finrank_range_le Φ
    _ = NumberField.NarrowClassGroup.twoRank K :=
        (NumberField.NarrowClassGroup.twoRank_def K).symm

/-- **The genus-theoretic lower bound on the narrow `2`-rank.** For `K = ℚ(√d)` with `d` squarefree,
the `2`-rank of the narrow class group `Cl⁺(K)` is at least `t - 1`, where `t` is the number of
rational primes ramifying in `K`. No hypothesis on the signature of `K` is needed. -/
theorem ncard_ramifiedPrimes_sub_one_le_narrowTwoRank
    (hmin : minpoly ℤ θ = X ^ 2 - C d) (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤)
    (hsf : Squarefree d) :
    (ramifiedPrimes K).ncard - 1 ≤ NumberField.NarrowClassGroup.twoRank K := by
  obtain ⟨s, hs, heven, hprod⟩ :=
    (isFundamentalDiscriminant_fundamentalDiscriminant hsf).exists_finset_primeDiscriminant
  rw [ncard_ramifiedPrimes_eq_card hmin hgen hsf hs heven hprod]
  exact card_sub_one_le_narrowTwoRank hs heven hprod hmin hgen hsf

/-- **The `2`-rank formula for the narrow class group of a quadratic field.** For `K = ℚ(√d)` with
`d` squarefree, of either signature, the `2`-rank of `Cl⁺(K)` is exactly `t - 1`, where `t` is the
number of rational primes ramifying in `K`. For an imaginary `K` the narrow and ordinary class
groups coincide, and this recovers `twoRank_eq_ncard_ramifiedPrimes_sub_one`; that identity is also
how the Gaussian field `d = -1`, which the ambiguous class number bound excludes, is covered. -/
theorem narrowTwoRank_eq_ncard_ramifiedPrimes_sub_one
    (hmin : minpoly ℤ θ = X ^ 2 - C d) (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤)
    (hsf : Squarefree d) :
    NumberField.NarrowClassGroup.twoRank K = (ramifiedPrimes K).ncard - 1 := by
  by_cases hd : 1 < d.natAbs
  · exact le_antisymm (narrowTwoRank_le_ncard_ramifiedPrimes_sub_one hmin hgen hsf hd)
      (ncard_ramifiedPrimes_sub_one_le_narrowTwoRank hmin hgen hsf)
  · have hne1 : d ≠ 1 := fun h =>
      NumberField.not_isSquare_radicand hmin ⟨1, by rw [h]; norm_num⟩
    have hneg : d < 0 := by
      have := hsf.ne_zero
      omega
    have : IsTotallyComplex K :=
      NumberField.isTotallyComplex_of_minpoly_eq_X_sq_sub_C_of_neg hmin hneg
    rw [NumberField.NarrowClassGroup.twoRank_eq_classGroupTwoRank,
      twoRank_eq_ncard_ramifiedPrimes_sub_one hmin hgen hsf hneg]

/-- **The `2`-rank formula for a real quadratic field with a unit of norm `-1`.** For `K = ℚ(√d)`
with `d` squarefree, if some unit of `𝓞 K` has norm `-1` then the narrow and ordinary class groups
coincide (`NumberField.NarrowClassGroup.toClassGroup_injective_of_norm_eq_neg_one`), so the
ordinary `2`-rank inherits the narrow value `t - 1`, with `t` the number of rational primes
ramifying in `K`. A unit of norm `-1` suffices to keep the real case from dropping; without one
the ordinary rank can be smaller, as for `ℚ(√3)`, which has `t = 2` and class number `1`. -/
theorem twoRank_eq_ncard_ramifiedPrimes_sub_one_of_exists_norm_eq_neg_one
    (hmin : minpoly ℤ θ = X ^ 2 - C d) (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤)
    (hsf : Squarefree d)
    (hu : ∃ u : (𝓞 K)ˣ, Algebra.norm ℚ (((u : 𝓞 K) : K)) = -1) :
    EpsilonEridani.ClassGroup.twoRank (𝓞 K) = (ramifiedPrimes K).ncard - 1 := by
  obtain ⟨u, hu⟩ := hu
  rw [← NumberField.NarrowClassGroup.twoRank_eq_classGroupTwoRank_of_injective K
    (NumberField.NarrowClassGroup.toClassGroup_injective_of_norm_eq_neg_one hmin hgen hu)]
  exact narrowTwoRank_eq_ncard_ramifiedPrimes_sub_one hmin hgen hsf

/-! ### The ordinary `2`-rank of a quadratic field -/

/-- **The ordinary `2`-rank of a quadratic field falls at most one short of `t - 1`.** For any
field `K` of degree `2` over `ℚ`, `t - 2 ≤ 2-rank Cl(𝓞 K)`, where `t` is the number of rational
primes ramifying in `K`.

Writing `K = ℚ(√d)` with `d` squarefree
(`NumberField.exists_minpoly_eq_X_sq_sub_C_and_adjoin_eq_top`), the narrow `2`-rank is exactly
`t - 1` (`narrowTwoRank_eq_ncard_ramifiedPrimes_sub_one`) and forgetting positivity is a surjection
`Cl⁺(K) → Cl(K)` whose kernel has at most two elements
(`NumberField.card_ker_toClassGroup_le_two`), so the ordinary `2`-rank drops by at most one
(`MonoidHom.twoRank_le_twoRank_add_of_card_ker_le_two_pow`). For an imaginary field the kernel is
trivial and no drop occurs; for a real field it can, as `ℚ(√3)` shows. -/
theorem ncard_ramifiedPrimes_sub_two_le_twoRank (hK : Module.finrank ℚ K = 2) :
    (ramifiedPrimes K).ncard - 2 ≤ EpsilonEridani.ClassGroup.twoRank (𝓞 K) := by
  obtain ⟨θ, d, hmin, hgen, hsf⟩ :=
    NumberField.exists_minpoly_eq_X_sq_sub_C_and_adjoin_eq_top hK
  have hnarrow : EpsilonEridani.twoRank (NumberField.NarrowClassGroup K) =
      (ramifiedPrimes K).ncard - 1 := by
    rw [EpsilonEridani.twoRank_def, ← NumberField.NarrowClassGroup.twoRank_def]
    exact narrowTwoRank_eq_ncard_ramifiedPrimes_sub_one hmin hgen hsf
  have hdrop : EpsilonEridani.twoRank (NumberField.NarrowClassGroup K) ≤
      EpsilonEridani.twoRank (ClassGroup (𝓞 K)) + 1 :=
    MonoidHom.twoRank_le_twoRank_add_of_card_ker_le_two_pow (n := 1)
      (NumberField.NarrowClassGroup.toClassGroup (K := K))
      NumberField.NarrowClassGroup.toClassGroup_surjective
      (by simpa using NumberField.card_ker_toClassGroup_le_two hK)
  rw [EpsilonEridani.ClassGroup.twoRank_def, ← EpsilonEridani.twoRank_def]
  omega

/-- **The ordinary `2`-rank of a quadratic field is `t - 1` or `t - 2`.** For any field `K` of
degree `2` over `ℚ`, the `2`-rank of `Cl(𝓞 K)` is one of the two values allowed by the narrow
formula `2-rank Cl⁺(K) = t - 1`, with `t` the number of ramified rational primes. Both values occur
among real quadratic fields: `ℚ(√3)` has `t = 2` and class number `1`, so its `2`-rank is
`0 = t - 2`, while `ℚ(√10)` has `t = 2` and class number `2`, so its `2`-rank is `1 = t - 1`. For
an imaginary field the value is always `t - 1` (`twoRank_eq_ncard_ramifiedPrimes_sub_one`). -/
theorem twoRank_eq_ncard_ramifiedPrimes_sub_one_or_sub_two (hK : Module.finrank ℚ K = 2) :
    EpsilonEridani.ClassGroup.twoRank (𝓞 K) = (ramifiedPrimes K).ncard - 1 ∨
      EpsilonEridani.ClassGroup.twoRank (𝓞 K) = (ramifiedPrimes K).ncard - 2 := by
  obtain ⟨θ, d, hmin, hgen, hsf⟩ :=
    NumberField.exists_minpoly_eq_X_sq_sub_C_and_adjoin_eq_top hK
  have hupper : EpsilonEridani.ClassGroup.twoRank (𝓞 K) ≤ (ramifiedPrimes K).ncard - 1 :=
    (NumberField.NarrowClassGroup.classGroupTwoRank_le_twoRank K).trans_eq
      (narrowTwoRank_eq_ncard_ramifiedPrimes_sub_one hmin hgen hsf)
  have hlower := ncard_ramifiedPrimes_sub_two_le_twoRank hK
  omega

end EpsilonEridani.Multiquadratic
