/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Combinatorics.Quiver.Covering
public import EpsilonEridani.RepresentationTheory.Quiver.PathAlgebra.Map
public import EpsilonEridani.RepresentationTheory.Quiver.Preprojective.Gauge

/-!
# The signless preprojective relation

Let `R` be a quiver with a reversal of arrows, such as the doubled quiver of a simple graph. When
the outgoing star at a vertex `v` is finite, the **signless local relator** at `v` is the sum of
all length-two backtracks based at `v`,

```text
s_v = ∑_{e : v ⟶ w} (v → w → v),
```

The quotient API additionally assumes that `R` has finitely many vertices and is locally finite;
the **signless preprojective algebra** is then the path algebra of `R` modulo the two-sided ideal
generated by all the `s_v`. For the doubled quiver of a simple graph `G` the relator is
`∑_{j ∼ i} (i → j → i)`, the relation which Huerfano and Khovanov find in the quadratic dual of
the zigzag algebra of `G`. Unlike the preprojective relator it carries no signs, and so involves no
choice of orientation.

Over a coefficient ring in which `2 = 0` the sign is invisible: the signless and preprojective
local relators are the same element, their relation ideals coincide, and the signless algebra of a
symmetrified quiver is its preprojective algebra.

For a quiver `Q` the signless relator of `Quiver.Symmetrify Q` at `v` is
`∑_{head a = v} a a* + ∑_{tail a = v} a* a`, which differs from the local preprojective relator
`ρ_v = ∑_{head a = v} a a* - ∑_{tail a = v} a* a` by the sign of the second sum. When `Q` is
*bipartite*, that is its vertices carry a colouring `c : Q → Bool` whose two colours differ at the
two ends of every arrow, the signs can be repaired by the arrow rescaling multiplying each arrow `a`
of `Q` by `1` if its head has colour `true` and by `-1` otherwise. Indeed that labelling turns
the preprojective relator into `∑_v ±s_v`, and its corner at `v` is `±s_v`, so the two relations
generate the same ideal. This gives an explicit isomorphism between the signless algebra of
`Quiver.Symmetrify Q` and the preprojective algebra `Π_k(Q)`. For a source--sink orientation, in
which every arrow has its head coloured `true`, the rescaling is the identity.

## Main definitions

* `EpsilonEridani.signlessPreprojectiveRelator`: the signless local relator `s_v`.
* `EpsilonEridani.signlessPreprojectiveIdeal` and `EpsilonEridani.signlessPreprojectiveAlgebra`: the relation
  ideal and the quotient algebra, with quotient map `EpsilonEridani.signlessPreprojectiveMk` and universal
  property `EpsilonEridani.signlessPreprojectiveLift`.
* `EpsilonEridani.symmetrifySignlessPreprojectiveAlgebraEquiv`: **the signless algebra of the doubled
  quiver of a bipartite quiver is its preprojective algebra**, by an explicit sign rescaling.

## Main results

* `EpsilonEridani.signlessPreprojectiveRelator_of`: for a symmetrified quiver it is the sum of the head
  backtracks into and the tail backtracks out of the vertex.
* `EpsilonEridani.signlessPreprojectiveRelator_congr`: it does not depend on the finiteness structure
  chosen on the star.
* `EpsilonEridani.gaugedPreprojectiveRelator_bipartite_eq_sum_smul`: the preprojective relator with arrows
  signed by the colour of their heads is a signed sum of the signless relators.
* `EpsilonEridani.gaugedPreprojectiveRelator_bipartite_vertexCorner_eq_smul`: its corner at `v` is
  `±s_v`.
* `EpsilonEridani.symmetrifySignlessPreprojectiveIdeal_eq_gaugedPreprojectiveIdeal`: the two relations
  generate the same ideal.
* `EpsilonEridani.symmetrifySignlessPreprojectiveAlgebraEquiv_signlessPreprojectiveMk_of_forall_head`:
  for a source--sink orientation the isomorphism is induced by the identity of path algebras.
* `EpsilonEridani.signlessPreprojectiveIdeal_eq_preprojectiveIdeal_of_two_eq_zero` and
  `EpsilonEridani.signlessPreprojectiveAlgebraEquivPreprojectiveOfTwoEqZero`: in characteristic two the
  signless and preprojective relations agree for every finite quiver.

## Implementation notes

The relator is defined for any quiver with a reversal, in particular for
`EpsilonEridani.DoubledQuiver G`, whose arrows live in `Type`. The comparison with `Π_k(Q)` is stated for
`Quiver.Symmetrify Q`, with `Q` in the universe of quivers accepted by
`EpsilonEridani.preprojectiveAlgebra`.
The identification of the relator of `EpsilonEridani.DoubledQuiver G` with the sum of the backtracks at
`v`, `EpsilonEridani.signlessPreprojectiveRelator_vertex`, lives downstream in
`EpsilonEridani.RepresentationTheory.Quiver.Zigzag.Signless`, so that this file does not depend on the
zigzag theory.

## References

S. Huerfano and M. Khovanov, *A category for the adjoint representation*, Section 3,
https://arxiv.org/abs/math/0002060, for the signless relation of the quadratic dual of the zigzag
algebra and its comparison with the preprojective relation for bipartite graphs. The preprojective
conventions follow Crawley-Boevey, *Quiver algebras, weighted projective lines, and the
Deligne--Simpson problem*, Section 1.
-/

public section

namespace EpsilonEridani

open _root_.Quiver PathAlgebra

universe u v w

/-! ### The signless relator -/

section Relator

variable (k : Type w) {R : Type u} [Semiring k] [Quiver.{v} R] [HasReverse R]

/-- The **signless local relator** at a vertex `v`: the sum, over the arrows `e : v ⟶ w`, of the
backtrack which traverses `e` and then its reverse. -/
noncomputable def signlessPreprojectiveRelator (v : R) [Fintype (Quiver.Star v)] :
    pathAlgebra k R :=
  ∑ x : Quiver.Star v, ofPath ⟨v, v, x.2.toPath.comp (Quiver.reverse x.2).toPath⟩

/-- The signless relator, by its defining sum. -/
theorem signlessPreprojectiveRelator_def (v : R) [Fintype (Quiver.Star v)] :
    signlessPreprojectiveRelator k v =
      ∑ x : Quiver.Star v, ofPath ⟨v, v, x.2.toPath.comp (Quiver.reverse x.2).toPath⟩ := by
  rw [signlessPreprojectiveRelator]

@[simp]
theorem vertexIdempotent_mul_signlessPreprojectiveRelator (v : R) [Fintype (Quiver.Star v)] :
    vertexIdempotent k v * signlessPreprojectiveRelator k v = signlessPreprojectiveRelator k v := by
  simp only [signlessPreprojectiveRelator_def, Finset.mul_sum, vertexIdempotent_mul_ofPath]

@[simp]
theorem signlessPreprojectiveRelator_mul_vertexIdempotent (v : R) [Fintype (Quiver.Star v)] :
    signlessPreprojectiveRelator k v * vertexIdempotent k v = signlessPreprojectiveRelator k v := by
  simp only [signlessPreprojectiveRelator_def, Finset.sum_mul, ofPath_mul_vertexIdempotent]

/-- The signless relator at `v` lies in the corner at `v`: every other vertex idempotent
annihilates it on the left. -/
@[simp]
theorem vertexIdempotent_mul_signlessPreprojectiveRelator_of_ne {u v : R} [Fintype (Quiver.Star v)]
    (h : u ≠ v) :
    vertexIdempotent k u * signlessPreprojectiveRelator k v = 0 := by
  simp only [signlessPreprojectiveRelator_def, Finset.mul_sum]
  exact Finset.sum_eq_zero fun x _ => vertexIdempotent_mul_ofPath_of_ne _ h

/-- Every vertex idempotent other than `e_v` annihilates the signless relator at `v` on the
right. -/
@[simp]
theorem signlessPreprojectiveRelator_mul_vertexIdempotent_of_ne {u v : R} [Fintype (Quiver.Star v)]
    (h : u ≠ v) :
    signlessPreprojectiveRelator k v * vertexIdempotent k u = 0 := by
  simp only [signlessPreprojectiveRelator_def, Finset.sum_mul]
  exact Finset.sum_eq_zero fun x _ => ofPath_mul_vertexIdempotent_of_ne _ h

/-- The signless relator does not depend on the finiteness structure chosen on the star: any two
of them enumerate the same backtracks. -/
theorem signlessPreprojectiveRelator_congr (v : R) (i₁ i₂ : Fintype (Quiver.Star v)) :
    @signlessPreprojectiveRelator k R _ _ _ v i₁
      = @signlessPreprojectiveRelator k R _ _ _ v i₂ := by
  rw [Subsingleton.elim i₁ i₂]

end Relator

section RelatorMap

variable (k : Type w) {R : Type u} [CommSemiring k] [Quiver.{v} R] [HasReverse R] [Finite R]

/-- A reversal-preserving prefunctor that is bijective on vertices and on the star at `v` carries
the signless relator at `v` to the signless relator at its image. -/
theorem mapAlgHom_signlessPreprojectiveRelator {S : Type*} [Quiver S] [HasReverse S] [Finite S]
    (φ : R ⥤q S) [φ.MapReverse] (hφobj : Function.Bijective φ.obj)
    (hφstar : Function.Bijective (φ.star v)) [Fintype (Quiver.Star v)]
    [Fintype (Quiver.Star (φ.obj v))] :
    PathAlgebra.mapAlgHom k φ hφobj (signlessPreprojectiveRelator k v) =
      signlessPreprojectiveRelator k (φ.obj v) := by
  rw [signlessPreprojectiveRelator_def, map_sum, signlessPreprojectiveRelator_def,
    ← (Equiv.ofBijective (φ.star v) hφstar).sum_comp]
  apply Finset.sum_congr rfl
  intro x _
  rw [PathAlgebra.mapAlgHom_ofPath, Prefunctor.mapTotalPath_mk, Prefunctor.mapPath_comp,
    Prefunctor.mapPath_toPath, Prefunctor.mapPath_toPath, Prefunctor.map_reverse]
  rfl

end RelatorMap

/-! ### The signless algebra -/

section Ideal

variable (k : Type w) (R : Type u) [Ring k] [Quiver.{v} R] [HasReverse R]
  [∀ x : R, Fintype (Quiver.Star x)]

/-- The two-sided ideal generated by the signless relators at all vertices. -/
noncomputable def signlessPreprojectiveIdeal : TwoSidedIdeal (pathAlgebra k R) :=
  TwoSidedIdeal.span (Set.range fun v : R => signlessPreprojectiveRelator k v)

/-- The signless ideal is the two-sided span of the signless relators. -/
theorem signlessPreprojectiveIdeal_eq_span :
    signlessPreprojectiveIdeal k R =
      TwoSidedIdeal.span (Set.range fun v : R => signlessPreprojectiveRelator k v) := by
  rw [signlessPreprojectiveIdeal]

variable {R} in
theorem signlessPreprojectiveRelator_mem_signlessPreprojectiveIdeal (v : R) :
    signlessPreprojectiveRelator k v ∈ signlessPreprojectiveIdeal k R := by
  rw [signlessPreprojectiveIdeal_eq_span]
  exact TwoSidedIdeal.subset_span ⟨v, rfl⟩

end Ideal

section Algebra

variable (k : Type w) (R : Type u) [CommRing k] [Quiver.{v} R] [HasReverse R] [Finite R]
  [∀ x : R, Fintype (Quiver.Star x)]

/-- The **signless preprojective algebra**: the path algebra of `R` modulo the signless relators.
-/
noncomputable abbrev signlessPreprojectiveAlgebra : Type _ :=
  pathAlgebra k R ⧸ (signlessPreprojectiveIdeal k R).asIdeal

/-- The quotient map onto the signless preprojective algebra. -/
noncomputable def signlessPreprojectiveMk :
    pathAlgebra k R →ₐ[k] signlessPreprojectiveAlgebra k R :=
  Ideal.Quotient.mkₐ k _

theorem signlessPreprojectiveMk_apply (f : pathAlgebra k R) :
    signlessPreprojectiveMk k R f =
      Ideal.Quotient.mk (signlessPreprojectiveIdeal k R).asIdeal f := by
  rw [signlessPreprojectiveMk, Ideal.Quotient.mkₐ_eq_mk]

theorem signlessPreprojectiveMk_surjective : Function.Surjective (signlessPreprojectiveMk k R) :=
  Ideal.Quotient.mk_surjective

@[simp]
theorem signlessPreprojectiveMk_eq_zero_iff {f : pathAlgebra k R} :
    signlessPreprojectiveMk k R f = 0 ↔ f ∈ signlessPreprojectiveIdeal k R := by
  rw [signlessPreprojectiveMk_apply, Ideal.Quotient.eq_zero_iff_mem, TwoSidedIdeal.mem_asIdeal]

variable {R} in
/-- **The defining relation of the signless algebra**: the backtracks at every vertex sum to
zero. -/
@[simp]
theorem signlessPreprojectiveMk_signlessPreprojectiveRelator (v : R) :
    signlessPreprojectiveMk k R (signlessPreprojectiveRelator k v) = 0 :=
  (signlessPreprojectiveMk_eq_zero_iff k R).2
    (signlessPreprojectiveRelator_mem_signlessPreprojectiveIdeal k v)

end Algebra

section Lift

variable {k : Type w} {R : Type u} {B : Type*} [CommRing k] [Quiver.{v} R] [HasReverse R]
  [Finite R] [∀ x : R, Fintype (Quiver.Star x)] [Semiring B] [Algebra k B]
  (f : pathAlgebra k R →ₐ[k] B)

/-- An algebra map out of the path algebra which kills every signless relator kills the signless
ideal. -/
theorem signlessPreprojectiveIdeal_le_ker (hf : ∀ v : R, f (signlessPreprojectiveRelator k v) = 0) :
    signlessPreprojectiveIdeal k R ≤ TwoSidedIdeal.ker f := by
  rw [signlessPreprojectiveIdeal_eq_span]
  refine TwoSidedIdeal.span_le.2 ?_
  rintro _ ⟨v, rfl⟩
  exact (TwoSidedIdeal.mem_ker f).2 (hf v)

/-- **The universal property of the signless algebra**: an algebra map out of the path algebra
which kills every signless relator descends to the quotient. -/
noncomputable def signlessPreprojectiveLift
    (hf : ∀ v : R, f (signlessPreprojectiveRelator k v) = 0) :
    signlessPreprojectiveAlgebra k R →ₐ[k] B :=
  Ideal.Quotient.liftₐ _ f fun _ ha =>
    (TwoSidedIdeal.mem_ker f).1
      (signlessPreprojectiveIdeal_le_ker f hf (TwoSidedIdeal.mem_asIdeal.1 ha))

/-- The lift descends `f`: composing it with the quotient map recovers `f`. -/
theorem signlessPreprojectiveLift_comp_signlessPreprojectiveMk
    (hf : ∀ v : R, f (signlessPreprojectiveRelator k v) = 0) :
    (signlessPreprojectiveLift f hf).comp (signlessPreprojectiveMk k R) = f := by
  rw [signlessPreprojectiveLift, signlessPreprojectiveMk, Ideal.Quotient.liftₐ_comp]

/-- Pointwise, the lift sends the quotient class of `x` to `f x`. -/
@[simp]
theorem signlessPreprojectiveLift_signlessPreprojectiveMk
    (hf : ∀ v : R, f (signlessPreprojectiveRelator k v) = 0) (x : pathAlgebra k R) :
    signlessPreprojectiveLift f hf (signlessPreprojectiveMk k R x) = f x :=
  AlgHom.congr_fun (signlessPreprojectiveLift_comp_signlessPreprojectiveMk f hf) x

/-- The lift is the only algebra map whose composite with the quotient map is `f`. -/
theorem signlessPreprojectiveLift_unique (hf : ∀ v : R, f (signlessPreprojectiveRelator k v) = 0)
    (g : signlessPreprojectiveAlgebra k R →ₐ[k] B) (hg : g.comp (signlessPreprojectiveMk k R) = f) :
    g = signlessPreprojectiveLift f hf := by
  refine AlgHom.ext fun y => ?_
  obtain ⟨x, rfl⟩ := signlessPreprojectiveMk_surjective k R y
  rw [signlessPreprojectiveLift_signlessPreprojectiveMk, ← hg, AlgHom.comp_apply]

end Lift

/-! ### Symmetrified quivers -/

section Symmetrify

variable (k : Type w) {Q : Type u} [Semiring k] [Quiver.{v} Q] [Fintype Q]
  [∀ i j : Q, Fintype (i ⟶ j)]

/-- **The signless relator of a symmetrified quiver** at `v` is the sum of the head backtracks
`a a*` of the arrows into `v` and the tail backtracks `a* a` of the arrows out of `v`: the local
preprojective relator with its sign removed. -/
theorem signlessPreprojectiveRelator_of (v : Q) :
    signlessPreprojectiveRelator k (Symmetrify.of.obj v) =
      (∑ i : Q, ∑ a : (i ⟶ v), headBacktrackElem k a) +
        ∑ j : Q, ∑ a : (v ⟶ j), tailBacktrackElem k a := by
  rw [signlessPreprojectiveRelator_def, add_comm, ← Finset.sum_add_distrib, Fintype.sum_sigma]
  refine Finset.sum_congr rfl fun (j : Q) _ => ?_
  -- An arrow of the doubled quiver out of `v` is an arrow of `Q` out of `v` or into `v`, and its
  -- backtrack is the tail backtrack respectively the head backtrack of that arrow.
  simp only [tailBacktrackElem_def, headBacktrackElem_def]
  exact Fintype.sum_sum_type (α₁ := v ⟶ j) (α₂ := j ⟶ v) _

end Symmetrify

section Bipartite

variable (k : Type w) {Q : Type u} [CommRing k] [Quiver.{v} Q] [Fintype Q]
  [∀ i j : Q, Fintype (i ⟶ j)] {c : Q → Bool} (hc : ∀ ⦃i j : Q⦄, (i ⟶ j) → c i ≠ c j)
include hc

/-- **The colour-signed preprojective relator is a signed sum of signless relators.** Label each
arrow of `Q` by `1` or `-1` according to the colour of its head. When the colours differ at the
two ends of every arrow, the gauged preprojective relator for that labelling is `∑_v ±s_v`, the
sign at `v` being `1` or `-1` according to the colour of `v`. -/
theorem gaugedPreprojectiveRelator_bipartite_eq_sum_smul :
    gaugedPreprojectiveRelator k (fun _ j _ => if c j then (1 : k) else -1) =
      ∑ v : Q, (if c v then (1 : k) else -1) •
        signlessPreprojectiveRelator k (Symmetrify.of.obj v) := by
  have htail : ∀ ⦃i j : Q⦄, (i ⟶ j) →
      (if c j then (1 : k) else -1) = -(if c i then (1 : k) else -1) := fun i j a => by
    have := hc a
    revert this
    cases c i <;> cases c j <;> simp
  simp only [signlessPreprojectiveRelator_of, smul_add, Finset.smul_sum, Finset.sum_add_distrib,
    gaugedPreprojectiveRelator_def, sub_eq_add_neg]
  congr 1
  · -- Each head backtrack is counted at the head of its arrow.
    exact Finset.sum_comm
  · -- Each tail backtrack is counted at the tail of its arrow, whose colour has the other sign.
    exact Finset.sum_congr rfl fun i _ => Finset.sum_congr rfl fun j _ =>
      Finset.sum_congr rfl fun a _ => by rw [htail a, smul_neg, neg_smul, neg_neg]

/-- The corner at `v` of the colour-signed preprojective relator is `±s_v`. -/
theorem gaugedPreprojectiveRelator_bipartite_vertexCorner_eq_smul (v : Q) :
    vertexIdempotent k (Symmetrify.of.obj v) *
        gaugedPreprojectiveRelator k (fun _ j _ => if c j then (1 : k) else -1) *
        vertexIdempotent k (Symmetrify.of.obj v) =
      (if c v then (1 : k) else -1) • signlessPreprojectiveRelator k (Symmetrify.of.obj v) := by
  rw [gaugedPreprojectiveRelator_bipartite_eq_sum_smul k hc, Finset.mul_sum, Finset.sum_mul,
    Finset.sum_eq_single v]
  · rw [mul_smul_comm, smul_mul_assoc, vertexIdempotent_mul_signlessPreprojectiveRelator,
      signlessPreprojectiveRelator_mul_vertexIdempotent]
  · intro w _ hw
    rw [mul_smul_comm, vertexIdempotent_mul_signlessPreprojectiveRelator_of_ne k
      (R := Symmetrify Q) (u := Symmetrify.of.obj v) (v := Symmetrify.of.obj w) fun h => hw h.symm,
      smul_zero, zero_mul]
  · exact fun h => absurd (Finset.mem_univ v) h

/-- **For a bipartite quiver the signless relation and the colour-signed preprojective relation
generate the same ideal.** -/
theorem symmetrifySignlessPreprojectiveIdeal_eq_gaugedPreprojectiveIdeal :
    signlessPreprojectiveIdeal k (Symmetrify Q) =
      gaugedPreprojectiveIdeal k (fun _ j _ => if c j then (1 : k) else -1) := by
  rw [signlessPreprojectiveIdeal_eq_span, gaugedPreprojectiveIdeal_eq_span]
  refine le_antisymm (TwoSidedIdeal.span_le.2 ?_) (TwoSidedIdeal.span_le.2 ?_)
  · rintro _ ⟨(v : Q), rfl⟩
    beta_reduce
    -- The signless relator at `v` is `±` the corner at `v` of the gauged relator.
    have hv : signlessPreprojectiveRelator k (Symmetrify.of.obj v) =
        algebraMap k _ (if c v then (1 : k) else -1) *
          (vertexIdempotent k (Symmetrify.of.obj v) *
            gaugedPreprojectiveRelator k (fun _ j _ => if c j then (1 : k) else -1) *
            vertexIdempotent k (Symmetrify.of.obj v)) := by
      rw [← Algebra.smul_def, gaugedPreprojectiveRelator_bipartite_vertexCorner_eq_smul k hc,
        smul_smul]
      cases c v <;> simp
    exact hv ▸ TwoSidedIdeal.mul_mem_left _ _ _ (TwoSidedIdeal.mul_mem_right _ _ _
      (TwoSidedIdeal.mul_mem_left _ _ _ (TwoSidedIdeal.subset_span rfl)))
  · rintro _ rfl
    rw [SetLike.mem_coe, gaugedPreprojectiveRelator_bipartite_eq_sum_smul k hc]
    refine sum_mem fun v _ => ?_
    rw [Algebra.smul_def]
    exact TwoSidedIdeal.mul_mem_left _ _ _
      (signlessPreprojectiveRelator_mem_signlessPreprojectiveIdeal k _)

/-- **The signless algebra of a bipartite quiver is its preprojective algebra.** For a colouring
`c` of the vertices of `Q` whose colours differ at the two ends of every arrow, the isomorphism
multiplies each arrow of `Q` by `1` or `-1` according to the colour of its head, and fixes the
formal reverses. -/
noncomputable def symmetrifySignlessPreprojectiveAlgebraEquiv :
    signlessPreprojectiveAlgebra k (Symmetrify Q) ≃ₐ[k] preprojectiveAlgebra k Q :=
  (Ideal.quotientEquivAlgOfEq k (congrArg TwoSidedIdeal.asIdeal
      (symmetrifySignlessPreprojectiveIdeal_eq_gaugedPreprojectiveIdeal k hc))).trans
    (preprojectiveAlgebraEquivGauged k _ (fun _ j _ => if c j then 1 else -1)
      fun _ j _ => by cases c j <;> simp).symm

/-- **The comparison isomorphism is the explicit sign rescaling**: it multiplies each arrow of `Q`
by `1` or `-1` according to the colour of its head, fixes the formal reverses, and passes to the
preprojective quotient. -/
@[simp]
theorem symmetrifySignlessPreprojectiveAlgebraEquiv_signlessPreprojectiveMk
    (x : pathAlgebra k (Symmetrify Q)) :
    symmetrifySignlessPreprojectiveAlgebraEquiv k hc (signlessPreprojectiveMk k _ x) =
      preprojectiveMk k Q
        (rescale (doubledLabelling k fun _ j _ => if c j then (1 : k) else -1) x) := by
  rw [symmetrifySignlessPreprojectiveAlgebraEquiv, AlgEquiv.trans_apply,
    signlessPreprojectiveMk_apply, Ideal.quotientEquivAlgOfEq_mk, ← gaugedPreprojectiveMk_apply,
    preprojectiveAlgebraEquivGauged_symm_gaugedPreprojectiveMk]
  congr 2
  refine rescale_congr _ _ fun (_ _ : Q) b => ?_
  cases b with
  | inl a =>
    refine (doubledLabelling_of (k := k) _ a).trans
      ((doubledLabelling_of (k := k) _ a).trans ?_).symm
    cases c _ <;> simp
  | inr a => exact (doubledLabelling_reverse_of _ a).trans (doubledLabelling_reverse_of _ a).symm

/-- The inverse comparison isomorphism applies the same involutive sign rescaling to a
preprojective quotient representative. -/
@[simp]
theorem symmetrifySignlessPreprojectiveAlgebraEquiv_symm_preprojectiveMk
    (x : pathAlgebra k (Symmetrify Q)) :
    (symmetrifySignlessPreprojectiveAlgebraEquiv k hc).symm (preprojectiveMk k Q x) =
      signlessPreprojectiveMk k _
        (rescale (doubledLabelling k fun _ j _ => if c j then (1 : k) else -1) x) := by
  apply (symmetrifySignlessPreprojectiveAlgebraEquiv k hc).injective
  rw [AlgEquiv.apply_symm_apply,
    symmetrifySignlessPreprojectiveAlgebraEquiv_signlessPreprojectiveMk,
    rescale_doubledLabelling_rescale_doubledLabelling k _ _]
  intro _ j _
  cases c j <;> simp

/-- **For a source--sink orientation no rescaling is needed**: if every arrow of `Q` ends at a
vertex coloured `true`, the comparison isomorphism is induced by the identity of the doubled path
algebra. -/
theorem symmetrifySignlessPreprojectiveAlgebraEquiv_signlessPreprojectiveMk_of_forall_head
    (hhead : ∀ ⦃i j : Q⦄, (i ⟶ j) → c j = true) (x : pathAlgebra k (Symmetrify Q)) :
    symmetrifySignlessPreprojectiveAlgebraEquiv k hc (signlessPreprojectiveMk k _ x) =
      preprojectiveMk k Q x := by
  rw [symmetrifySignlessPreprojectiveAlgebraEquiv_signlessPreprojectiveMk,
    rescale_congr _ (fun _ _ _ => (1 : k)) fun _ _ b => ?_, rescale_one, AlgHom.id_apply]
  cases b with
  | inl a => exact (doubledLabelling_of _ a).trans (by simp [hhead a])
  | inr a => exact doubledLabelling_reverse_of _ a

/-- For a source--sink orientation, the inverse comparison isomorphism is also induced by the
identity of the doubled path algebra. -/
theorem symmetrifySignlessPreprojectiveAlgebraEquiv_symm_preprojectiveMk_of_forall_head
    (hhead : ∀ {i j : Q}, (i ⟶ j) → c j = true) (x : pathAlgebra k (Symmetrify Q)) :
    (symmetrifySignlessPreprojectiveAlgebraEquiv k hc).symm (preprojectiveMk k Q x) =
      signlessPreprojectiveMk k _ x := by
  rw [symmetrifySignlessPreprojectiveAlgebraEquiv_symm_preprojectiveMk,
    rescale_congr _ (fun _ _ _ => (1 : k)) fun _ _ b => ?_, rescale_one, AlgHom.id_apply]
  cases b with
  | inl a => exact (doubledLabelling_of _ a).trans (by simp [hhead a])
  | inr a => exact doubledLabelling_reverse_of _ a

end Bipartite

/-! ### Characteristic two -/

section CharTwo

variable (k : Type w) {Q : Type u} [CommRing k] [Quiver.{v + 1} Q] [Fintype Q]
  [∀ i j : Q, Fintype (i ⟶ j)]

/-- **In characteristic two the signless relator is the preprojective relator.** The two differ
only in the sign of the tail backtracks. -/
@[simp]
theorem signlessPreprojectiveRelator_eq_localPreprojectiveRelator_of_two_eq_zero
    (h2 : (2 : k) = 0) (v : Q) :
    signlessPreprojectiveRelator k (Symmetrify.of.obj v) = localPreprojectiveRelator k v := by
  have hneg : ∀ z : pathAlgebra k (Symmetrify Q), -z = z := fun z =>
    neg_eq_of_add_eq_zero_left (by rw [← two_smul k z, h2, zero_smul])
  rw [signlessPreprojectiveRelator_of, localPreprojectiveRelator_def, sub_eq_add_neg, hneg]

/-- **In characteristic two the signless and the preprojective relation ideals coincide**, for
every finite quiver, bipartite or not. -/
@[simp]
theorem signlessPreprojectiveIdeal_eq_preprojectiveIdeal_of_two_eq_zero (h2 : (2 : k) = 0) :
    signlessPreprojectiveIdeal k (Symmetrify Q) = preprojectiveIdeal k Q := by
  rw [signlessPreprojectiveIdeal_eq_span,
    preprojectiveIdeal_eq_span_range_localPreprojectiveRelator]
  congr 1
  ext x
  simp only [Set.mem_range]
  constructor
  · rintro ⟨w, rfl⟩
    exact ⟨w, (signlessPreprojectiveRelator_eq_localPreprojectiveRelator_of_two_eq_zero
      (Q := Q) k h2 w).symm⟩
  · rintro ⟨w, rfl⟩
    exact ⟨w, signlessPreprojectiveRelator_eq_localPreprojectiveRelator_of_two_eq_zero
      (Q := Q) k h2 w⟩

/-- **In characteristic two the signless algebra of a doubled quiver is its preprojective
algebra**, by the identity of the doubled path algebra. -/
noncomputable def signlessPreprojectiveAlgebraEquivPreprojectiveOfTwoEqZero (h2 : (2 : k) = 0) :
    signlessPreprojectiveAlgebra k (Symmetrify Q) ≃ₐ[k] preprojectiveAlgebra k Q :=
  Ideal.quotientEquivAlgOfEq k (congrArg TwoSidedIdeal.asIdeal
    (signlessPreprojectiveIdeal_eq_preprojectiveIdeal_of_two_eq_zero k h2))

/-- The characteristic-two comparison is induced by the identity of the doubled path algebra. -/
@[simp]
theorem signlessPreprojectiveAlgebraEquivPreprojectiveOfTwoEqZero_signlessPreprojectiveMk
    (h2 : (2 : k) = 0) (x : pathAlgebra k (Symmetrify Q)) :
    signlessPreprojectiveAlgebraEquivPreprojectiveOfTwoEqZero k h2
        (signlessPreprojectiveMk k _ x) = preprojectiveMk k Q x := by
  rw [signlessPreprojectiveAlgebraEquivPreprojectiveOfTwoEqZero, signlessPreprojectiveMk_apply,
    Ideal.quotientEquivAlgOfEq_mk, preprojectiveMk_apply]

/-- The inverse of the characteristic-two comparison is also induced by the identity of the
doubled path algebra. -/
@[simp]
theorem signlessPreprojectiveAlgebraEquivPreprojectiveOfTwoEqZero_symm_preprojectiveMk
    (h2 : (2 : k) = 0) (x : pathAlgebra k (Symmetrify Q)) :
    (signlessPreprojectiveAlgebraEquivPreprojectiveOfTwoEqZero k h2).symm
        (preprojectiveMk k Q x) = signlessPreprojectiveMk k _ x := by
  apply (signlessPreprojectiveAlgebraEquivPreprojectiveOfTwoEqZero k h2).injective
  rw [AlgEquiv.apply_symm_apply,
    signlessPreprojectiveAlgebraEquivPreprojectiveOfTwoEqZero_signlessPreprojectiveMk]

end CharTwo

end EpsilonEridani
