/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.Geometry.Lie.Adjoint.Exponential.Basic
public import EpsilonEridani.Geometry.Lie.Adjoint.Infinitesimal
public import EpsilonEridani.Geometry.Lie.Exponential.Smoothness
public import EpsilonEridani.Geometry.Lie.Exponential.Trotter
-- Non-public: the slope characterisation of a derivative and the module description of a slope
-- are used only inside proofs, and no statement below mentions `slope`.
import Mathlib.Analysis.Calculus.Deriv.Slope

/-!
# The Lie subalgebra of a subgroup

For a subgroup `K` of a Lie group `G` the derivations whose one-parameter subgroup never leaves
`K`,

`𝔨 = {X : 𝔤 | ∀ t : ℝ, lieExp (t • X) ∈ K}`,

are the candidate Lie algebra of `K`. `EpsilonEridani.Lie.lieSubalgebraOfSubgroup K` is the Lie
subalgebra of `𝔤` they generate, defined for every subgroup, and this file proves that for a
**closed** `K` the generating set is already a Lie subalgebra, so that the generation is inert and
membership is exactly the defining condition
(`EpsilonEridani.Lie.mem_lieSubalgebraOfSubgroup`).

Addition and the bracket produce the new element as a *limit* of elements of `K`, each using a
different piece of the Layer 0/1 machinery; scalars involve no limit at all:

* scalars are free: `t • (c • X) = (t * c) • X` reparametrises the exponential line of `X`, so the
  one-parameter subgroup of `c • X` is a reparametrisation of that of `X` and lands in `K` on the
  nose;
* addition is the **Trotter product formula** `EpsilonEridani.Lie.tendsto_lieExp_smul_mul_lieExp_smul_pow`,
  which exhibits `lieExp (t • (X + Y))` as a limit of products of elements of `K`;
* the bracket is the **infinitesimal adjoint**. If `X` and `Y` both generate one-parameter
  subgroups inside `K` then so does `Ad (lieExp (s • X)) Y`, by the conjugation formula
  `EpsilonEridani.Lie.conj_lieExp`; the curve `s ↦ Ad (lieExp (s • X)) Y` therefore runs inside `𝔨` and
  starts at `Y`, and its derivative at `0` is `⁅X, Y⁆` by
  `EpsilonEridani.Lie.hasDerivAt_Ad_lieExp_smul_apply_zero`, the derivation-level form of the Layer 1
  theorem `EpsilonEridani.Lie.hasDerivAt_tangentAd_mulInvariantExp_smul_apply_zero`. A difference quotient
  of a curve in a linear subspace stays in that subspace, so `⁅X, Y⁆` lies in its closure.

## Why the definition generates, and closedness

The definition of `lieSubalgebraOfSubgroup` is total in `K`, as the roadmap specifies it, because
it takes the Lie subalgebra *generated* by `𝔨` rather than asserting that `𝔨` is one. That the
generating set is itself a subalgebra is true for an arbitrary subgroup — for `X, Y ∈ 𝔨` the
subgroup generated by the two one-parameter subgroups is arcwise connected, hence an immersed Lie
subgroup of `K` whose Lie algebra contains `X + Y` and `⁅X, Y⁆` — but that argument is the
subalgebra ↔ immersed-subgroup correspondence, which the roadmap schedules two layers later
(Layer 4, `exists_immersedLieSubgroup_lieSubalgebra`) and which is not available here.

What *is* available without it is the closed case: only the scalar closure survives with no
topological hypothesis, since both the Trotter formula and the difference quotient produce the new
element as a *limit* of elements of `K`, never as an element of `K` on the nose.
`EpsilonEridani.Lie.isClosed_setOf_forall_lieExp_smul_mem` turns those limits back into membership, and it
is the only place closedness is used. So for a closed `K` the generation collapses
(`EpsilonEridani.Lie.coe_lieSubalgebraOfSubgroup`), which is the hypothesis under which the next Layer 2
target — the closed-subgroup theorem, promoting `K` to an embedded Lie subgroup with
`Lie(K) = 𝔨` — is stated.

## Main definitions

* `EpsilonEridani.Lie.lieSubalgebraOfSubgroup`: the Lie algebra of a subgroup.

## Main results

* `EpsilonEridani.Lie.lieExp_smul_add_mem`, `EpsilonEridani.Lie.lieExp_smul_smul_mem` and
  `EpsilonEridani.Lie.lieExp_smul_lie_mem`: the three closure properties, stated on the defining
  condition itself so that they can be used without producing the bundled subalgebra.
* `EpsilonEridani.Lie.hasDerivAt_Ad_lieExp_smul_apply_zero`: the adjoint orbit `s ↦ Ad (lieExp (s • X)) Y`
  has derivative `⁅X, Y⁆` at the origin. This is the derivation-level infinitesimal adjoint, the
  analytic input to bracket closure.
* `EpsilonEridani.Lie.lieSubalgebraOfSubgroup_le_iff`: the universal property of the generated subalgebra,
  for an arbitrary subgroup.
* `EpsilonEridani.Lie.mem_lieSubalgebraOfSubgroup` and `EpsilonEridani.Lie.coe_lieSubalgebraOfSubgroup`: for a
  closed subgroup, the Lie algebra of `K` is exactly `𝔨`.
* `EpsilonEridani.Lie.isClosed_setOf_forall_lieExp_smul_mem`: the candidate Lie algebra is a closed
  subset of `𝔤`.
* `EpsilonEridani.Lie.Ad_mem_lieSubalgebraOfSubgroup`: the Lie algebra of `K` is invariant under the
  adjoint action of `K`.

## References

* [Lie groups and the Lie algebra correspondence roadmap](https://github.com/EpsilonEridaniProject/EpsilonEridaniRoadmap/blob/main/EpsilonEridaniRoadmap/RepresentationTheory/LieGroups/README.md),
  Deliverable A, Layer 2, "The Lie subalgebra of a subgroup".
* J. Hilgert and K.-H. Neeb, *Structure and Geometry of Lie Groups*, Springer (2012),
  Section 9.1.
* J. M. Lee, *Introduction to Smooth Manifolds*, 2nd edition (2013), Theorem 20.12.
-/

public section

noncomputable section

namespace EpsilonEridani.Lie

open Filter
open scoped ContDiff Manifold Topology

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
  {H : Type*} [TopologicalSpace H] {I : ModelWithCorners ℝ E H}
  {G : Type*} [TopologicalSpace G] [ChartedSpace H G] [Group G]
  [FiniteDimensional ℝ E] [LieGroup I ∞ G] [T2Space G]

attribute [local instance] LieGroup.minSmoothnessThree
attribute [local instance] ContMDiffMul.boundarylessManifold

/-! ### The three closure properties -/

/-- The zero derivation generates the trivial one-parameter subgroup, which lies in every
subgroup. -/
theorem lieExp_smul_zero_mem (K : Subgroup G) (t : ℝ) :
    lieExp (I := I) (t • (0 : LeftInvariantDerivation I G)) ∈ K := by
  simp

/-- **Scalar closure.** Rescaling a derivation reparametrises its one-parameter subgroup, so the
condition defining the Lie algebra of a subgroup is invariant under scalars. No hypothesis on the
subgroup is needed. -/
theorem lieExp_smul_smul_mem {K : Subgroup G} {X : LeftInvariantDerivation I G}
    (hX : ∀ t : ℝ, lieExp (I := I) (t • X) ∈ K) (c t : ℝ) :
    lieExp (I := I) (t • c • X) ∈ K := by
  rw [smul_smul]
  exact hX _

/-- **Additive closure**, from the Trotter product formula: `lieExp (t • (X + Y))` is the limit of
the powers `(lieExp ((t / n) • X) * lieExp ((t / n) • Y)) ^ n`, each of which lies in `K`, so a
closed `K` contains the limit. -/
theorem lieExp_smul_add_mem {K : Subgroup G} (hK : IsClosed (K : Set G))
    {X Y : LeftInvariantDerivation I G} (hX : ∀ t : ℝ, lieExp (I := I) (t • X) ∈ K)
    (hY : ∀ t : ℝ, lieExp (I := I) (t • Y) ∈ K) (t : ℝ) :
    lieExp (I := I) (t • (X + Y)) ∈ K := by
  refine hK.mem_of_tendsto (tendsto_lieExp_smul_mul_lieExp_smul_pow (I := I) (G := G) X Y t) ?_
  filter_upwards with n
  exact K.pow_mem (K.mul_mem (hX _) (hY _)) n

/-- **The candidate Lie algebra of a closed subgroup is closed.** It is an intersection over the
time parameter of preimages of `K` under the continuous maps `X ↦ lieExp (t • X)`. -/
theorem isClosed_setOf_forall_lieExp_smul_mem {K : Subgroup G} (hK : IsClosed (K : Set G)) :
    IsClosed {X : LeftInvariantDerivation I G | ∀ t : ℝ, lieExp (I := I) (t • X) ∈ K} := by
  have hset : {X : LeftInvariantDerivation I G | ∀ t : ℝ, lieExp (I := I) (t • X) ∈ K} =
      ⋂ t : ℝ, (fun X : LeftInvariantDerivation I G => lieExp (I := I) (t • X)) ⁻¹'
        (K : Set G) := by
    ext X
    simp only [Set.mem_ofPred_eq, Set.mem_iInter, Set.mem_preimage, SetLike.mem_coe]
  rw [hset]
  refine isClosed_iInter fun t => hK.preimage ?_
  exact (contMDiff_lieExp (I := I) (G := G)).continuous.comp (continuous_const_smul t)

/-- The adjoint action of an element of `K` preserves the defining condition: conjugating the
one-parameter subgroup of `Y` by `g ∈ K` is the one-parameter subgroup of `Ad g Y`, and stays
inside `K`. -/
theorem lieExp_smul_Ad_mem {K : Subgroup G} {g : G} (hg : g ∈ K)
    {Y : LeftInvariantDerivation I G} (hY : ∀ t : ℝ, lieExp (I := I) (t • Y) ∈ K) (t : ℝ) :
    lieExp (I := I) (t • Ad (I := I) g Y) ∈ K := by
  have hconj : lieExp (I := I) (t • Ad (I := I) g Y) = g * lieExp (I := I) (t • Y) * g⁻¹ := by
    rw [← map_smul, conj_lieExp (I := I) g (t • Y)]
  rw [hconj]
  exact K.mul_mem (K.mul_mem hg (hY t)) (K.inv_mem hg)

/-! ### The derivative of the adjoint orbit -/

/-- **The infinitesimal adjoint, on derivations.** The adjoint orbit `s ↦ Ad (lieExp (s • X)) Y`
has derivative `⁅X, Y⁆` at `s = 0`.

This is `EpsilonEridani.Lie.hasDerivAt_tangentAd_mulInvariantExp_smul_apply_zero`, the same statement for
the tangent space at the identity, transported across the canonical isometric identification
`EpsilonEridani.Lie.leftInvariantDerivationLinearIsometryEquivModelVectorSpace` of
`LeftInvariantDerivation I G` with the model space `E`. Bracket closure below is the only consumer
so far: it is what makes `⁅X, Y⁆` a limit of difference quotients of a curve in `𝔨`. -/
theorem hasDerivAt_Ad_lieExp_smul_apply_zero (X Y : LeftInvariantDerivation I G) :
    HasDerivAt (fun s : ℝ => Ad (I := I) (lieExp (I := I) (s • X)) Y) ⁅X, Y⁆ 0 := by
  let e : LeftInvariantDerivation I G ≃ₗᵢ[ℝ] E :=
    leftInvariantDerivationLinearIsometryEquivModelVectorSpace (I := I) (G := G)
  -- Evaluation at the identity, read in the model space, is the linear equivalence `lieExp` and
  -- `Ad` are built from; this named `rfl` lemma is the bridge between the two spellings.
  have he : ∀ Z : LeftInvariantDerivation I G, (e Z : E) =
      (leftInvariantDerivationEquivGroupLieAlgebra (I := I) (G := G)
        BoundarylessManifold.isInteriorPoint Z : E) := fun Z =>
    leftInvariantDerivationLinearIsometryEquivModelVectorSpace_apply Z
  -- The exponential line of the tangent vector of `X` is the one-parameter subgroup of `X`; the
  -- two differ only by the bridge `he`, so the equality is `congrArg` applied to it.
  have hexp : ∀ s : ℝ,
      mulInvariantExp (I := I) (G := G) (s • ((e X : E) : GroupLieAlgebra I G)) =
        lieExp (I := I) (s • X) := fun s => by
    rw [lieExp_eq_mulInvariantExp, map_smul]
    exact congrArg (fun v : GroupLieAlgebra I G =>
      mulInvariantExp (I := I) (G := G) (s • v)) (he X)
  -- Evaluation at the identity is a Lie equivalence, so it carries `⁅X, Y⁆` to the tangent-level
  -- adjoint action the derivative theorem produces.
  have hbracket : ((e ⁅X, Y⁆ : E) : GroupLieAlgebra I G) =
      LieAlgebra.ad ℝ (GroupLieAlgebra I G) ((e X : E) : GroupLieAlgebra I G)
        ((e Y : E) : GroupLieAlgebra I G) := by
    have hmap := (leftInvariantDerivationLieEquivGroupLieAlgebra
      (I := I) (G := G) BoundarylessManifold.isInteriorPoint).map_lie X Y
    simp only [leftInvariantDerivationLieEquivGroupLieAlgebra_apply] at hmap
    rw [he X, he Y, he ⁅X, Y⁆, LieAlgebra.ad_apply]
    exact hmap
  -- Read the orbit in the model space, where the tangent-level theorem applies. As in that
  -- theorem, the `show E from` ascription is what exposes the model space `E` — to which
  -- `GroupLieAlgebra I G` reduces definitionally — to the normed-space derivative API.
  have key : HasDerivAt (fun s : ℝ => (e (Ad (I := I) (lieExp (I := I) (s • X)) Y) : E))
      (e ⁅X, Y⁆) 0 := by
    have hraw := hasDerivAt_tangentAd_mulInvariantExp_smul_apply_zero (I := I) (G := G)
      ((e X : E) : GroupLieAlgebra I G) ((e Y : E) : GroupLieAlgebra I G)
    have hfun : (fun s : ℝ => (e (Ad (I := I) (lieExp (I := I) (s • X)) Y) : E)) =
        fun s : ℝ => show E from tangentAd (I := I)
          (mulInvariantExp (I := I) (G := G) (s • ((e X : E) : GroupLieAlgebra I G)))
          ((e Y : E) : GroupLieAlgebra I G) := by
      funext s
      rw [hexp s]
      exact leftInvariantDerivationLinearIsometryEquivModelVectorSpace_Ad
        (I := I) (lieExp (I := I) (s • X)) Y
    rw [hfun, hbracket]
    exact hraw
  -- Transport the derivative back along the identification, which is linear and continuous.
  have hcomp := (e.symm.toContinuousLinearEquiv.hasFDerivAt
    (x := (fun s : ℝ => (e (Ad (I := I) (lieExp (I := I) (s • X)) Y) : E)) 0)).comp_hasDerivAt
      0 key
  simpa [Function.comp_def] using hcomp

/-! ### Bracket closure -/

/-- **Bracket closure.** The curve `s ↦ Ad (lieExp (s • X)) Y` takes its values in the candidate
Lie algebra of `K`, starts at `Y` and has derivative `⁅X, Y⁆` at `s = 0`; its difference quotients
therefore lie in the linear span, and the bracket is their limit. -/
theorem lieExp_smul_lie_mem {K : Subgroup G} (hK : IsClosed (K : Set G))
    {X Y : LeftInvariantDerivation I G} (hX : ∀ t : ℝ, lieExp (I := I) (t • X) ∈ K)
    (hY : ∀ t : ℝ, lieExp (I := I) (t • Y) ∈ K) (t : ℝ) :
    lieExp (I := I) (t • ⁅X, Y⁆) ∈ K := by
  -- The candidate Lie algebra, as a linear subspace of `𝔤`.
  let S : Submodule ℝ (LeftInvariantDerivation I G) :=
    { carrier := {Z : LeftInvariantDerivation I G | ∀ s : ℝ, lieExp (I := I) (s • Z) ∈ K}
      zero_mem' := lieExp_smul_zero_mem K
      add_mem' := fun {_ _} hZ hW => lieExp_smul_add_mem hK hZ hW
      smul_mem' := fun c {_} hZ => lieExp_smul_smul_mem hZ c }
  have hmemS : ∀ Z : LeftInvariantDerivation I G,
      Z ∈ S ↔ ∀ s : ℝ, lieExp (I := I) (s • Z) ∈ K := fun _ => Iff.rfl
  have hSclosed : IsClosed (S : Set (LeftInvariantDerivation I G)) :=
    isClosed_setOf_forall_lieExp_smul_mem hK
  -- The adjoint orbit of `Y` along the one-parameter subgroup of `X`.
  set φ : ℝ → LeftInvariantDerivation I G := fun s => Ad (I := I) (lieExp (I := I) (s • X)) Y
    with hφ
  have hφmem : ∀ s : ℝ, φ s ∈ S := fun s => lieExp_smul_Ad_mem (hX s) hY
  have hφzero : φ 0 = Y := by simp [hφ]
  have hderiv : HasDerivAt φ ⁅X, Y⁆ 0 := hasDerivAt_Ad_lieExp_smul_apply_zero X Y
  -- A difference quotient of a curve in `S` stays in `S`, and `S` is closed.
  have hslope : ∀ s : ℝ, slope φ 0 s ∈ S := by
    intro s
    rw [slope_def_module]
    exact S.smul_mem _ (S.sub_mem (hφmem s) (hφzero ▸ hφmem 0))
  have hlie : ⁅X, Y⁆ ∈ S :=
    hSclosed.mem_of_tendsto (hasDerivAt_iff_tendsto_slope.mp hderiv)
      (Eventually.of_forall hslope)
  exact (hmemS _).mp hlie t

/-! ### The Lie subalgebra -/

/-- **The Lie algebra of a subgroup.** For a subgroup `K` of a Lie group `G`, the Lie subalgebra of
`𝔤` generated by the derivations whose one-parameter subgroup lies entirely in `K`. It is the
candidate `Lie K`, identified with the honest Lie algebra of `K` by the closed-subgroup theorem.

The generating set is itself a Lie subalgebra — for a closed `K` this is
`coe_lieSubalgebraOfSubgroup` below, and for an arbitrary `K` it is a Layer 4 statement not
available here — so generating is inert; it is what makes the definition total in `K`. See the
module docstring. -/
def lieSubalgebraOfSubgroup (K : Subgroup G) : LieSubalgebra ℝ (LeftInvariantDerivation I G) :=
  LieSubalgebra.lieSpan ℝ (LeftInvariantDerivation I G)
    {X : LeftInvariantDerivation I G | ∀ t : ℝ, lieExp (I := I) (t • X) ∈ K}

/-- A derivation whose one-parameter subgroup lies in `K` lies in the Lie algebra of `K`. This
direction needs no hypothesis on `K`. -/
theorem mem_lieSubalgebraOfSubgroup_of_forall {K : Subgroup G} {X : LeftInvariantDerivation I G}
    (hX : ∀ t : ℝ, lieExp (I := I) (t • X) ∈ K) : X ∈ lieSubalgebraOfSubgroup (I := I) K :=
  LieSubalgebra.subset_lieSpan hX

/-- **The universal property of the Lie algebra of a subgroup.** It is the least Lie subalgebra
containing every derivation whose one-parameter subgroup lies in `K`, so a Lie subalgebra contains
it as soon as it contains those derivations. No hypothesis on `K` is needed; together with
`mem_lieSubalgebraOfSubgroup_of_forall` this is the elimination rule for an arbitrary subgroup. -/
theorem lieSubalgebraOfSubgroup_le_iff {K : Subgroup G}
    {L : LieSubalgebra ℝ (LeftInvariantDerivation I G)} :
    lieSubalgebraOfSubgroup (I := I) K ≤ L ↔
      ∀ X : LeftInvariantDerivation I G, (∀ t : ℝ, lieExp (I := I) (t • X) ∈ K) → X ∈ L :=
  LieSubalgebra.lieSpan_le

/-- **The Lie algebra of a closed subgroup is exactly `𝔨`**: the three closure properties make the
defining condition a Lie subalgebra, so generating it adds nothing. -/
@[simp]
theorem mem_lieSubalgebraOfSubgroup {K : Subgroup G} (hK : IsClosed (K : Set G))
    {X : LeftInvariantDerivation I G} :
    X ∈ lieSubalgebraOfSubgroup (I := I) K ↔ ∀ t : ℝ, lieExp (I := I) (t • X) ∈ K := by
  refine ⟨fun hX => ?_, mem_lieSubalgebraOfSubgroup_of_forall⟩
  let S : LieSubalgebra ℝ (LeftInvariantDerivation I G) :=
    { carrier := {Z : LeftInvariantDerivation I G | ∀ t : ℝ, lieExp (I := I) (t • Z) ∈ K}
      zero_mem' := lieExp_smul_zero_mem K
      add_mem' := fun {_ _} hZ hW => lieExp_smul_add_mem hK hZ hW
      smul_mem' := fun c {_} hZ => lieExp_smul_smul_mem hZ c
      lie_mem' := fun {_ _} hZ hW => lieExp_smul_lie_mem hK hZ hW }
  exact lieSubalgebraOfSubgroup_le_iff (L := S) |>.mpr (fun _ hZ => hZ) hX

/-- **The Lie algebra of a closed subgroup is exactly `𝔨`**, as sets. -/
theorem coe_lieSubalgebraOfSubgroup {K : Subgroup G} (hK : IsClosed (K : Set G)) :
    (lieSubalgebraOfSubgroup (I := I) K : Set (LeftInvariantDerivation I G)) =
      {X : LeftInvariantDerivation I G | ∀ t : ℝ, lieExp (I := I) (t • X) ∈ K} :=
  Set.ext fun _ => mem_lieSubalgebraOfSubgroup hK

/-- The one-parameter subgroup generated by an element of the Lie algebra of a closed subgroup `K`
lies in `K`. -/
theorem lieExp_smul_mem_of_mem_lieSubalgebraOfSubgroup {K : Subgroup G}
    (hK : IsClosed (K : Set G)) {X : LeftInvariantDerivation I G}
    (hX : X ∈ lieSubalgebraOfSubgroup (I := I) K) (t : ℝ) :
    lieExp (I := I) (t • X) ∈ K :=
  (mem_lieSubalgebraOfSubgroup hK).mp hX t

/-- The exponential of an element of the Lie algebra of a closed subgroup `K` lies in `K`. -/
theorem lieExp_mem_of_mem_lieSubalgebraOfSubgroup {K : Subgroup G}
    (hK : IsClosed (K : Set G)) {X : LeftInvariantDerivation I G}
    (hX : X ∈ lieSubalgebraOfSubgroup (I := I) K) : lieExp (I := I) X ∈ K := by
  simpa using lieExp_smul_mem_of_mem_lieSubalgebraOfSubgroup hK hX 1

/-- The Lie algebra of a closed subgroup is a closed subset of `𝔤`. This is what makes the
closed-subgroup theorem's complement argument available: `𝔨` is a closed linear subspace of a
finite-dimensional space, hence has a linear complement on which the exponential is transverse. -/
theorem isClosed_lieSubalgebraOfSubgroup {K : Subgroup G} (hK : IsClosed (K : Set G)) :
    IsClosed (lieSubalgebraOfSubgroup (I := I) K : Set (LeftInvariantDerivation I G)) := by
  rw [coe_lieSubalgebraOfSubgroup hK]
  exact isClosed_setOf_forall_lieExp_smul_mem hK

/-- **Monotonicity.** A larger subgroup has a larger Lie algebra. -/
theorem lieSubalgebraOfSubgroup_mono {K K' : Subgroup G} (h : K ≤ K') :
    lieSubalgebraOfSubgroup (I := I) K ≤ lieSubalgebraOfSubgroup (I := I) K' :=
  LieSubalgebra.lieSpan_mono fun _ hX t => h (hX t)

/-- The Lie algebra of the whole group is the whole Lie algebra. -/
@[simp]
theorem lieSubalgebraOfSubgroup_top :
    lieSubalgebraOfSubgroup (I := I) (⊤ : Subgroup G) = ⊤ :=
  eq_top_iff.mpr fun _ _ =>
    mem_lieSubalgebraOfSubgroup_of_forall fun _ => Subgroup.mem_top _

/-- **The Lie algebra of `K` is invariant under the adjoint action of `K`.** Conjugating by `g ∈ K`
carries the one-parameter subgroup of `X` to the one of `Ad g X`, which therefore also stays in `K`.
This is the bundled form of `lieExp_smul_Ad_mem`, the statement that makes the adjoint orbit of the
bracket proof run inside `𝔨`. No hypothesis on `K` is needed: `Ad g` is an automorphism of `𝔤`
preserving the generating set, hence preserves the subalgebra it generates. Invariance under `Ad g`
for `g` outside `K` — which for a normal `K` would say that `𝔨` is an ideal of `𝔤` — is not
asserted here. -/
theorem Ad_mem_lieSubalgebraOfSubgroup {K : Subgroup G} {g : G}
    (hg : g ∈ K) {X : LeftInvariantDerivation I G}
    (hX : X ∈ lieSubalgebraOfSubgroup (I := I) K) :
    Ad (I := I) g X ∈ lieSubalgebraOfSubgroup (I := I) K :=
  lieSubalgebraOfSubgroup_le_iff
      (L := (lieSubalgebraOfSubgroup (I := I) K).comap (Ad (I := I) g).toLieHom)
      |>.mpr (fun _ hY => mem_lieSubalgebraOfSubgroup_of_forall (lieExp_smul_Ad_mem hg hY)) hX

end EpsilonEridani.Lie
