/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Borel
public import EpsilonEridani.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Weyl.Elementary
public import EpsilonEridani.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Weyl.Torus

/-!
# Coroot values in the elementary group, and when the weight torus is redundant

The points of a Kostant carrier over a value ring `A` are generated by two families: the root
subgroups `xᵢ(t)`, generating the elementary group
`EpsilonEridani.UniversalEnvelopingAlgebra.kostantElementarySubgroup`, and the split weight torus `t(s)`.
This file shows that the second family is often already contained in the first, so that the
torus contributes no new points.

The mechanism is Chevalley's, and it needs no new computation inside the `sl₂` triple. Write
`n = xᵢ(1) xⱼ(-1) xᵢ(1)` for the Weyl representative of a root pair `(eᵢ, eⱼ)` with Cartan index
`c`, and `α` for the weight of `eᵢ`. Conjugation by a torus point rescales the parameter of each
root subgroup, so `n` lies in the elementary group and the elementary group is stable under that
conjugation; hence

```text
t(s) t(s_α s)⁻¹ = t(s) n t(s)⁻¹ n⁻¹
```

lies in the elementary group. The left-hand side is a torus point again, and a very particular
one: the reflection `s_α` divides the `c`-th coordinate of `s` by the value `α(s)` and leaves the
others alone, so the product above is the point supported at `c` with value `α(s)`. Under the
displayed `sl₂`-triple hypothesis, the `c`-th coordinate cocharacter is Chevalley's coroot
cocharacter, and the identity puts its value at `α(s)` in the elementary group for every `s`.

What is left is a question about the integers alone: which values `u` arise as `α(s)`? Writing
`α` in the coordinates of the designated Cartan vectors, `α(s) = ∏ⱼ s(j) ^ α(j)`, so every unit
arises as soon as the integers `α(j)` are setwise coprime. For a simple root of an irreducible
finite Dynkin diagram those integers are its row of the Cartan matrix, which is coprime precisely
when it contains an odd entry: equivalently, an off-diagonal `-1` or `-3`. The rows that are not
coprime are the rank-one row `(2)` and the long-simple-root rows of `B₂` and `Cₙ`; the long row
`(-3, 2)` of `G₂` has no `-1` but is nevertheless coprime. When the condition holds at every
Cartan index the whole torus lies in the elementary group, and the Borel-type join of the torus
with all root subgroups collapses to the elementary group.

Nothing here identifies the elementary group with the points of the toral closure group scheme,
which is a separate statement that this file does not use or prove: the comparison is between two
subgroups of `Aut_A(A ⊗[ℤ] M)`, both generated by named elements.

The cocharacter supported at one coordinate,
`EpsilonEridani.UniversalEnvelopingAlgebra.kostantCoordinateCocharacter`, and the identity
`EpsilonEridani.UniversalEnvelopingAlgebra.kostantTorusPoints_mul_inv_weylReflectTorusPoint`
expressing the quotient displayed above as one of its values, both belong to the torus itself and
are imported from
`EpsilonEridani/Algebra/Lie/UniversalEnveloping/Kostant/RootSubgroup/Torus/Basic.lean`.

## Main results

* `kostantCoordinateCocharacter_torusCharacter_mem_kostantElementarySubgroup`: under an
  `sl₂`-triple hypothesis, the coroot value at `α(s)` lies in the elementary group.
* `EpsilonEridani.UniversalEnvelopingAlgebra.kostantCoordinateCocharacter_mem_kostantElementarySubgroup`:
  with a unimodular root it does so at every unit.
* `EpsilonEridani.UniversalEnvelopingAlgebra.kostantTorusSubgroup_le_kostantElementarySubgroup` and
  `kostantTorusSubsystemSubgroup_univ_eq_kostantElementarySubgroup`: with a unimodular root pair
  at every Cartan index, the weight torus and then the whole Borel-type join are contained in the
  elementary group.

## References

* R. Steinberg, *Lectures on Chevalley Groups*, §3, Lemma 20 and Corollary 5.
* R. W. Carter, *Simple Groups of Lie Type*, §§6.4 and 7.1.
* J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*, §§25--27.
-/

public section

open TensorProduct

namespace EpsilonEridani.UniversalEnvelopingAlgebra

universe u v w

variable {L : Type u} [LieRing L] [LieAlgebra ℚ L]
variable {ι : Type*} {κ : Type*}
variable {V : Type v} [AddCommGroup V] [Module ℚ V]

variable (e : ι → L) (h : κ → L)
variable (ρ : _root_.UniversalEnvelopingAlgebra ℚ L →ₐ[ℚ] Module.End ℚ V)
variable (M : AddSubgroup V)
variable (hM : ∀ u ∈ kostantForm e h, ∀ v ∈ M, ρ u v ∈ M)
variable (hnil : ∀ i, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i))))

attribute [local instance 100] LieRing.ofAssociativeRing

-- Match tensor products to the `ℤ`-algebra instance stored by `CommAlgCat` objects.
attribute [local instance high] Algebra.toModule

/-! ## Coroot values in the elementary group -/

section Coroot

variable {η : Type*} (b : Module.Basis η ℤ M) (wt : η → κ → ℤ)
variable [Fintype κ] [DecidableEq κ]

/-- **A coroot element at a value of the root lies in the elementary group.** For every torus
point `s`, the coroot element at the Cartan index `c` with value `α(s)` is the commutator
`t(s) n t(s)⁻¹ n⁻¹` of `s` with the Weyl representative `n` of the root pair, and both factors are
elementary: the torus normalizes the elementary group, which contains `n`. -/
theorem kostantCoordinateCocharacter_torusCharacter_mem_kostantElementarySubgroup
    (hwt : ∀ x, IsCartanWeightVector h ρ (wt x) ((b x : M) : V))
    (rt : ι → κ → ℤ) (hrt : ∀ i j, ⁅h j, e i⁆ = (rt i j : ℚ) • e i)
    {i j : ι} {c : κ}
    (hT : IsSl2Triple (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (h c)))
      (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i)))
      (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e j))))
    (hopp : rt j = -rt i) (A : CommAlgCat.{w} ℤ) (s : κ → Aˣ) :
    kostantCoordinateCocharacter M b wt A c (torusCharacter s (rt i)) ∈
      kostantElementarySubgroup e h ρ M hM hnil A := by
  have hneg : ∀ j', ⁅h j', e j⁆ = -((rt i j' : ℚ) • e j) := by
    intro j'
    rw [hrt j j', hopp]
    simp only [Pi.neg_apply, Int.cast_neg, neg_smul]
  have hn : kostantWeylGL e h ρ M hM (hnil i) (hnil j) A ∈
      kostantElementarySubgroup e h ρ M hM hnil A :=
    kostantWeylGL_mem_kostantElementarySubgroup e h ρ M hM hnil i j A
  have hconj := kostantWeylGL_conj_kostantTorusPoints e h ρ M hM (hnil i) (hnil j) hT (hrt i)
    hneg b wt hwt s
  rw [← kostantTorusPoints_mul_inv_weylReflectTorusPoint M b wt A (rt i) c s, ← hconj]
  have hrewrite : kostantTorusPoints M b wt A s *
      (kostantWeylGL e h ρ M hM (hnil i) (hnil j) A * kostantTorusPoints M b wt A s *
        (kostantWeylGL e h ρ M hM (hnil i) (hnil j) A)⁻¹)⁻¹ =
      (MulAut.conj (kostantTorusPoints M b wt A s))
          (kostantWeylGL e h ρ M hM (hnil i) (hnil j) A) *
        (kostantWeylGL e h ρ M hM (hnil i) (hnil j) A)⁻¹ := by
    rw [MulAut.conj_apply]
    group
  rw [hrewrite]
  refine mul_mem ?_ (inv_mem hn)
  rw [← map_kostantElementarySubgroup_conj_kostantTorusPoints e h ρ M hM b wt hwt rt hrt hnil A s]
  exact ⟨_, hn, rfl⟩

/-- **A unimodular root puts every coroot element in the elementary group.** If the coordinates of
the root `rt i` have a `ℤ`-linear combination equal to one, then every unit is a value `α(s)`, so
the previous result reaches the whole coroot cocharacter. -/
theorem kostantCoordinateCocharacter_mem_kostantElementarySubgroup
    (hwt : ∀ x, IsCartanWeightVector h ρ (wt x) ((b x : M) : V))
    (rt : ι → κ → ℤ) (hrt : ∀ i j, ⁅h j, e i⁆ = (rt i j : ℚ) • e i)
    {i j : ι} {c : κ}
    (hT : IsSl2Triple (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (h c)))
      (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i)))
      (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e j))))
    (hopp : rt j = -rt i) {m : κ → ℤ} (hm : ∑ j', rt i j' * m j' = 1)
    (A : CommAlgCat.{w} ℤ) (u : Aˣ) :
    kostantCoordinateCocharacter M b wt A c u ∈
      kostantElementarySubgroup e h ρ M hM hnil A := by
  obtain ⟨s, hs⟩ := exists_torusCharacter_eq_of_sum_mul_eq_one (m := m) hm u
  rw [← hs]
  exact kostantCoordinateCocharacter_torusCharacter_mem_kostantElementarySubgroup
    e h ρ M hM hnil b wt hwt rt hrt hT hopp A s

omit [DecidableEq κ] in
/-- **The weight torus lies in the elementary group.** A torus point is the product over the
Cartan indices of its coroot elements, so a unimodular root pair at every index puts the whole
torus inside the group generated by the root subgroups. -/
theorem kostantTorusSubgroup_le_kostantElementarySubgroup
    (hwt : ∀ x, IsCartanWeightVector h ρ (wt x) ((b x : M) : V))
    (rt : ι → κ → ℤ) (hrt : ∀ i j, ⁅h j, e i⁆ = (rt i j : ℚ) • e i)
    (raise lower : κ → ι)
    (hT : ∀ c, IsSl2Triple (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (h c)))
      (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e (raise c))))
      (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e (lower c)))))
    (hopp : ∀ c, rt (lower c) = -rt (raise c))
    (m : κ → κ → ℤ) (hm : ∀ c, ∑ j', rt (raise c) j' * m c j' = 1)
    (A : CommAlgCat.{w} ℤ) :
    kostantTorusSubgroup M b wt A ≤ kostantElementarySubgroup e h ρ M hM hnil A := by
  classical
  rw [kostantTorusSubgroup_eq_range]
  rintro - ⟨s, rfl⟩
  have key : s ∈ (kostantElementarySubgroup e h ρ M hM hnil A).comap
      (kostantTorusPoints M b wt A) := by
    rw [← Finset.univ_prod_mulSingle s]
    refine prod_mem fun c _ => Subgroup.mem_comap.2 ?_
    rw [← kostantCoordinateCocharacter_apply]
    exact kostantCoordinateCocharacter_mem_kostantElementarySubgroup e h ρ M hM hnil b wt hwt rt hrt
      (hT c) (hopp c) (hm c) A (s c)
  exact Subgroup.mem_comap.1 key

omit [DecidableEq κ] in
/-- **The Borel-type join of the torus with every root subgroup is the elementary group.** With a
unimodular root pair at every Cartan index the torus is redundant, so adjoining it to the root
subgroups adds nothing. -/
theorem kostantTorusSubsystemSubgroup_univ_eq_kostantElementarySubgroup
    (hwt : ∀ x, IsCartanWeightVector h ρ (wt x) ((b x : M) : V))
    (rt : ι → κ → ℤ) (hrt : ∀ i j, ⁅h j, e i⁆ = (rt i j : ℚ) • e i)
    (raise lower : κ → ι)
    (hT : ∀ c, IsSl2Triple (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (h c)))
      (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e (raise c))))
      (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e (lower c)))))
    (hopp : ∀ c, rt (lower c) = -rt (raise c))
    (m : κ → κ → ℤ) (hm : ∀ c, ∑ j', rt (raise c) j' * m c j' = 1)
    (A : CommAlgCat.{w} ℤ) :
    kostantTorusSubsystemSubgroup e h ρ M hM hnil b wt Set.univ A =
      kostantElementarySubgroup e h ρ M hM hnil A := by
  classical
  rw [kostantTorusSubsystemSubgroup_univ, ← kostantTorusSubgroup_eq_range,
    sup_eq_left]
  exact kostantTorusSubgroup_le_kostantElementarySubgroup e h ρ M hM hnil b wt hwt rt hrt
    raise lower hT hopp m hm A

end Coroot

end EpsilonEridani.UniversalEnvelopingAlgebra
