/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Borel
public import EpsilonEridani.GroupTheory.SemidirectProduct

/-!
# The Kostant torus--elementary subgroup as a semidirect product

Let `U_S(A)` be the subgroup generated by the represented Kostant root subgroups indexed by a set
`S` of roots over a commutative value ring `A`, and let `T(A)` be the image of the diagonal action
of the split weight torus. Their join `B_S(A) = U_S(A) ⊔ T(A)` is
`EpsilonEridani.UniversalEnvelopingAlgebra.kostantTorusSubsystemSubgroup`, built in
`EpsilonEridani.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Borel`, where it is also shown that
`T(A)` normalizes `U_S(A)` by the pinning equation `t(s) xᵢ(u) t(s)⁻¹ = xᵢ(α(s) u)`.

This file packages that normalization as an action of `T(A)` on `U_S(A)` and identifies `B_S(A)`
with the image of the multiplication map out of the external semidirect product

```text
U_S(A) ⋊ T(A) ⟶ B_S(A).
```

No injectivity is asserted: the represented torus can meet the root-generated subgroup, so
identifying the join with an external semidirect product on the nose would need an additional
disjointness hypothesis. The surjection nevertheless gives the normal form `g = x * t` for every
element of `B_S(A)`. Taking `S = Set.univ`, where `U_S(A)` is the full elementary subgroup by
`kostantSubsystemSubgroup_univ`, this is the pointwise assembly step toward the pinned
Chevalley--Demazure group scheme; representability of the assembled functor and the Borel and
maximal-torus properties remain later parts of Layer 9 of the reductive-groups roadmap.

The two group-theoretic ingredients — the range of the semidirect-product multiplication map and
the resulting membership normal form — are proved for an arbitrary normalizing pair of subgroups in
`EpsilonEridani.GroupTheory.SemidirectProduct` and are instantiated here.

## Main declarations

* `EpsilonEridani.UniversalEnvelopingAlgebra.kostantTorusSubsystemAction` is the conjugation action of the
  torus on the root-generated subgroup, and
  `EpsilonEridani.UniversalEnvelopingAlgebra.kostantTorusSubsystemMonoidHom` is multiplication from the
  resulting external semidirect product.

## Main results

* `EpsilonEridani.UniversalEnvelopingAlgebra.range_kostantTorusPoints_le_normalizer` records the pinning
  equation as normalization by the whole torus subgroup.
* `EpsilonEridani.UniversalEnvelopingAlgebra.range_kostantTorusSubsystemMonoidHom` proves that the
  multiplication map is onto `B_S(A)`.
* `EpsilonEridani.UniversalEnvelopingAlgebra.mem_kostantTorusSubsystemSubgroup_iff` gives the resulting
  `x * t` normal form.

## References

* R. W. Carter, *Simple Groups of Lie Type*, Sections 4.4 and 7.1.
* J. C. Jantzen, *Representations of Algebraic Groups*, II.1.
-/

public section

open TensorProduct

namespace EpsilonEridani.UniversalEnvelopingAlgebra

universe u v w

variable {L : Type u} [LieRing L] [LieAlgebra ℚ L]
variable {ι : Type*} {κ : Type*}
variable {V : Type v} [AddCommGroup V] [Module ℚ V]

variable (e : ι → L) (h : κ → L)
variable (ρ : _root_.UniversalEnvelopingAlgebra ℚ L →ₐ[ℚ] Module.End ℚ V)
variable (M : AddSubgroup V)
variable (hM : ∀ u ∈ kostantForm e h, ∀ v ∈ M, ρ u v ∈ M)
variable (hnil : ∀ i, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i))))
variable {η : Type*} (b : Module.Basis η ℤ M) (wt : η → κ → ℤ)

-- Match tensor products to the `ℤ`-algebra instance stored by `CommAlgCat` objects.
attribute [local instance high] Algebra.toModule

variable [Fintype κ]
variable (hwt : ∀ x, IsCartanWeightVector h ρ (wt x) ((b x : M) : V))
variable (α : ι → κ → ℤ) (S : Set ι)
variable (hα : ∀ i ∈ S, ∀ j, ⁅h j, e i⁆ = (α i j : ℚ) • e i)
variable (A : CommAlgCat.{w} ℤ)

/-! ## The torus subgroup normalizes the root-generated subgroup -/

include hwt hα in
/-- The represented split torus normalizes the subgroup generated by the root subgroups indexed by
`S`. This is the subgroup form of the pointwise statement
`kostantTorusPoints_mem_normalizer_kostantSubsystemSubgroup`. -/
theorem range_kostantTorusPoints_le_normalizer :
    kostantTorusSubgroup M b wt A ≤
      Subgroup.normalizer (kostantSubsystemSubgroup e h ρ M hM hnil S A : Set _) := by
  rw [kostantTorusSubgroup_eq_range]
  rintro _ ⟨s, rfl⟩
  exact kostantTorusPoints_mem_normalizer_kostantSubsystemSubgroup e h ρ M hM hnil b wt hwt α S hα
    A s

/-! ## The semidirect-product multiplication map -/

/-- The action of the represented torus subgroup on the root-generated subgroup by conjugation. -/
noncomputable abbrev kostantTorusSubsystemAction :
    kostantTorusSubgroup M b wt A →*
      MulAut (kostantSubsystemSubgroup e h ρ M hM hnil S A) :=
  (kostantSubsystemSubgroup e h ρ M hM hnil S A).normalizerMonoidHom.comp
    (Subgroup.inclusion (range_kostantTorusPoints_le_normalizer e h ρ M hM hnil b wt hwt α S hα A))

/-- The external semidirect product attached to the conjugation action of the represented torus on
the root-generated subgroup. Its multiplication map need not be injective. -/
abbrev KostantTorusSubsystemSemidirectProduct :=
  kostantSubsystemSubgroup e h ρ M hM hnil S A ⋊[
    kostantTorusSubsystemAction e h ρ M hM hnil b wt hwt α S hα A]
      kostantTorusSubgroup M b wt A

/-- Multiplication from the torus action's external semidirect product to the ambient general
linear group.

This is a reducible wrapper for `SemidirectProduct.monoidHomSubgroup`, so Mathlib's
`SemidirectProduct.monoidHomSubgroup_apply` computes it as `x.left * x.right` without unfolding
anything by hand; likewise `Subgroup.normalizerMonoidHom_apply_apply_coe` computes
`kostantTorusSubsystemAction` as conjugation. -/
noncomputable abbrev kostantTorusSubsystemMonoidHom :
    KostantTorusSubsystemSemidirectProduct e h ρ M hM hnil b wt hwt α S hα A →*
      LinearMap.GeneralLinearGroup A (A ⊗[ℤ] M) :=
  SemidirectProduct.monoidHomSubgroup
    (range_kostantTorusPoints_le_normalizer e h ρ M hM hnil b wt hwt α S hα A)

/-- The range of the semidirect-product multiplication map is exactly the subgroup generated by
the root subgroups indexed by `S` together with the represented torus. -/
theorem range_kostantTorusSubsystemMonoidHom :
    (kostantTorusSubsystemMonoidHom e h ρ M hM hnil b wt hwt α S hα A).range =
      kostantTorusSubsystemSubgroup e h ρ M hM hnil b wt S A := by
  rw [kostantTorusSubsystemSubgroup_eq_sup, ← kostantTorusSubgroup_eq_range]
  exact SemidirectProduct.range_monoidHomSubgroup _

include hwt hα in
/-- An element belongs to `B_S(A)` exactly when it is a product of an element of the root-generated
subgroup `U_S(A)` followed by a represented torus point. -/
theorem mem_kostantTorusSubsystemSubgroup_iff
    (g : LinearMap.GeneralLinearGroup A (A ⊗[ℤ] M)) :
    g ∈ kostantTorusSubsystemSubgroup e h ρ M hM hnil b wt S A ↔
      ∃ x ∈ kostantSubsystemSubgroup e h ρ M hM hnil S A,
        ∃ t ∈ kostantTorusSubgroup M b wt A, g = x * t := by
  rw [kostantTorusSubsystemSubgroup_eq_sup, ← kostantTorusSubgroup_eq_range]
  exact Subgroup.mem_sup_of_right_le_normalizer_left
    (range_kostantTorusPoints_le_normalizer e h ρ M hM hnil b wt hwt α S hα A)

end EpsilonEridani.UniversalEnvelopingAlgebra
