/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Codex
-/
module

public import EpsilonEridani.Algebra.AlgebraicGroup.GeneralLinear.Coordinate.BaseChange
public import EpsilonEridani.Algebra.AlgebraicGroup.HopfIdeal.BaseChange
public import EpsilonEridani.Algebra.AlgebraicGroup.SpecialOrthogonal.Basic

/-!
# Base change of the special orthogonal group

For a morphism of commutative rings `R → K`, scalar extension of the coordinate Hopf algebra
of the standard special orthogonal group `SOₙ` is canonically the coordinate Hopf algebra
constructed directly over `K`.

The defining ideal is generated by the entries of `X Xᵀ - 1` together with `det X - 1`.
The general-linear base-change isomorphism carries both families of generators to their
counterparts over `K`, so the general base-change theorem for Hopf-ideal quotients applies.

## Main declarations

* `EpsilonEridani.SpecialOrthogonal.coordinateHopfAlgebraBaseChangeIso`: base change of the coordinate
  Hopf algebra of `SOₙ`.
* `baseChangeMap_coordinateMap_comp_coordinateHopfAlgebraBaseChangeIso_hom`: compatibility with
  the quotient coordinate morphisms from `O(GLₙ)`.
* `EpsilonEridani.SpecialOrthogonal.finiteTypeCoordinateHopfAlgebraBaseChangeIso`: the finite-type form
  of the same isomorphism.

## References

* J. S. Milne, *Basic Theory of Affine Group Schemes*, Chapter IV, §1.8.
* The Stacks Project, Tags [01JO](https://stacks.math.columbia.edu/tag/01JO) and
  [022W](https://stacks.math.columbia.edu/tag/022W).

The quotient-transport construction follows
`EpsilonEridani.Symplectic.coordinateHopfAlgebraBaseChangeIso`, with the orthogonality relations and
the determinant-one relation transported together. This is the scalar-extension compatibility
needed to formulate geometric connectedness and reductivity of the `SOₙ` worked example.
-/

public section

open CategoryTheory Matrix
open scoped TensorProduct

namespace EpsilonEridani.SpecialOrthogonal

universe u v

variable (R : Type u) (K : Type max u v) [CommRing R] [CommRing K] [Algebra R K]
variable (n : ℕ)

/-- The `R`-algebra structure obtained by restricting the coordinate algebra over `K`. -/
noncomputable local instance : Algebra R (GeneralLinear.coordinateHopfAlgebra K n) :=
  Algebra.compHom _ (algebraMap R K)

/-- The coordinate algebra over `K` is a scalar tower over `R → K`. -/
local instance : IsScalarTower R K (GeneralLinear.coordinateHopfAlgebra K n) :=
  IsScalarTower.of_algebraMap_eq' rfl

/-- The restriction of the general-linear base-change isomorphism to the original coordinate
Hopf algebra. -/
private noncomputable def baseChangeAlgHom :
    GeneralLinear.coordinateHopfAlgebra R n →ₐ[R]
      GeneralLinear.coordinateHopfAlgebra K n :=
  ((GeneralLinear.coordinateHopfAlgebraBaseChangeIso R K n).hom.hom.toAlgHom.restrictScalars R).comp
    (Algebra.TensorProduct.includeRight :
      GeneralLinear.coordinateHopfAlgebra R n →ₐ[R]
        K ⊗[R] GeneralLinear.coordinateHopfAlgebra R n)

/-- Applying the restricted base-change map is applying the ambient isomorphism to a scalar pure
tensor. -/
private theorem baseChangeAlgHom_apply (x : GeneralLinear.coordinateHopfAlgebra R n) :
    baseChangeAlgHom R K n x =
      (GeneralLinear.coordinateHopfAlgebraBaseChangeIso R K n).hom.hom (1 ⊗ₜ[R] x) := by
  simp only [baseChangeAlgHom, AlgHom.comp_apply, Algebra.TensorProduct.includeRight_apply,
    AlgHom.coe_restrictScalars', BialgHom.coe_toAlgHom]

/-- The general-linear base-change isomorphism carries each scalar-extended orthogonality
relation to the corresponding relation over the new base. -/
private theorem coordinateHopfAlgebraBaseChangeIso_hom_relationMatrix (i j : Fin n) :
    (GeneralLinear.coordinateHopfAlgebraBaseChangeIso R K n).hom.hom
        (1 ⊗ₜ[R] ConstantForm.relationMatrix R n 1 i j) =
      ConstantForm.relationMatrix K n 1 i j := by
  rw [← baseChangeAlgHom_apply R K n]
  have hgeneric : (GeneralLinear.genericMatrix R n).map (baseChangeAlgHom R K n) =
      GeneralLinear.genericMatrix K n := by
    simpa only [baseChangeAlgHom] using
      GeneralLinear.coordinateHopfAlgebraBaseChangeIso_hom_genericMatrix R K n
  have hmatrix := ConstantForm.relationMatrix_map R n (1 : Matrix (Fin n) (Fin n) R)
    (baseChangeAlgHom R K n)
  rw [hgeneric, Matrix.map_one _ (map_zero _) (map_one _)] at hmatrix
  have hentry := congrFun (congrFun hmatrix i) j
  rw [Matrix.map_apply] at hentry
  have hdef := congrFun (congrFun
    (ConstantForm.relationMatrix_def K n (1 : Matrix (Fin n) (Fin n) K)) i) j
  rw [Matrix.map_one _ (map_zero _) (map_one _)] at hdef
  exact hentry.trans hdef.symm

/-- The defining ideal is the span of the orthogonality relations and the determinant-one
relation. -/
private theorem definingHopfIdeal_toIdeal_eq_span_union :
    (definingHopfIdeal R n).toIdeal =
      Ideal.span (Orthogonal.relationSet R n ∪
        {(GeneralLinear.determinantGroupLike R n :
          GeneralLinear.coordinateHopfAlgebra R n) - 1}) := by
  rw [definingHopfIdeal_toIdeal, Ideal.span_union]

/-- The general-linear base-change isomorphism carries the base-changed special-orthogonal
defining Hopf ideal onto the special-orthogonal defining Hopf ideal over the new base. -/
private theorem map_baseChangeHopfIdeal_definingHopfIdeal :
    (CommHopfAlgCat.baseChangeHopfIdeal (K := K) (definingHopfIdeal R n)).map
        (GeneralLinear.coordinateHopfAlgebraBaseChangeIso R K n).hom.hom =
      definingHopfIdeal K n := by
  refine CommHopfAlgCat.map_baseChangeHopfIdeal_of_toIdeal_eq_span
    (definingHopfIdeal R n) (definingHopfIdeal K n)
    (GeneralLinear.coordinateHopfAlgebraBaseChangeIso R K n)
    (definingHopfIdeal_toIdeal_eq_span_union R n)
    (definingHopfIdeal_toIdeal_eq_span_union K n) ?_
  rw [Set.image_union]
  congr 1
  · ext x
    constructor
    · rintro ⟨_, hy, rfl⟩
      obtain ⟨i, j, rfl⟩ := (ConstantForm.mem_relationSet_iff R n 1).mp hy
      have hrel :
          (GeneralLinear.coordinateHopfAlgebraBaseChangeIso R K n).hom.hom
              (1 ⊗ₜ[R] ConstantForm.relationMatrix R n 1 i j) =
            ConstantForm.relationMatrix K n 1 i j :=
        coordinateHopfAlgebraBaseChangeIso_hom_relationMatrix R K n i j
      dsimp only
      rw [hrel]
      exact ConstantForm.relationMatrix_mem_relationSet K n 1 i j
    · intro hx
      obtain ⟨i, j, rfl⟩ := (ConstantForm.mem_relationSet_iff K n 1).mp hx
      have hrel :
          (GeneralLinear.coordinateHopfAlgebraBaseChangeIso R K n).hom.hom
              (1 ⊗ₜ[R] ConstantForm.relationMatrix R n 1 i j) =
            ConstantForm.relationMatrix K n 1 i j :=
        coordinateHopfAlgebraBaseChangeIso_hom_relationMatrix R K n i j
      exact ⟨ConstantForm.relationMatrix R n 1 i j,
        ConstantForm.relationMatrix_mem_relationSet R n 1 i j,
        hrel⟩
  · have hdet :=
      GeneralLinear.coordinateHopfAlgebraBaseChangeIso_hom_determinantGroupLike R K n
    simp only [Set.image_singleton, TensorProduct.tmul_sub,
      ← Algebra.TensorProduct.one_def, map_sub, map_one]
    congr 1
    exact congrArg (fun x ↦ x - 1) hdet

/-- Base change of the special-orthogonal coordinate Hopf algebra is canonically the
special-orthogonal coordinate Hopf algebra over the new base. -/
noncomputable def coordinateHopfAlgebraBaseChangeIso :
    CommHopfAlgCat.baseChange (K := K) (coordinateHopfAlgebra R n) ≅
      coordinateHopfAlgebra K n :=
  CommHopfAlgCat.quotientBaseChangeIsoOfMapEq
    (definingHopfIdeal R n) (definingHopfIdeal K n)
    (GeneralLinear.coordinateHopfAlgebraBaseChangeIso R K n)
    (map_baseChangeHopfIdeal_definingHopfIdeal R K n)

/-- The special-orthogonal base-change isomorphism is compatible with the quotient coordinate
morphisms from the corresponding general-linear coordinate Hopf algebras. -/
@[simp]
theorem baseChangeMap_coordinateMap_comp_coordinateHopfAlgebraBaseChangeIso_hom :
    CommHopfAlgCat.baseChangeMap (K := K) (coordinateMap R n) ≫
        (coordinateHopfAlgebraBaseChangeIso R K n).hom =
      (GeneralLinear.coordinateHopfAlgebraBaseChangeIso R K n).hom ≫ coordinateMap K n := by
  rw [coordinateMap_def, coordinateMap_def]
  exact CommHopfAlgCat.baseChangeMap_mkQuotient_comp_quotientBaseChangeIsoOfMapEq_hom
    (definingHopfIdeal R n) (definingHopfIdeal K n)
    (GeneralLinear.coordinateHopfAlgebraBaseChangeIso R K n)
    (map_baseChangeHopfIdeal_definingHopfIdeal R K n)

/-- The finite-type coordinate Hopf algebra of `SOₙ` commutes with base change. -/
noncomputable def finiteTypeCoordinateHopfAlgebraBaseChangeIso :
    FiniteTypeCommHopfAlgCat.baseChange (K := K) (finiteTypeCoordinateHopfAlgebra R n) ≅
      finiteTypeCoordinateHopfAlgebra K n :=
  FiniteTypeCommHopfAlgCat.baseChangeIsoOfObjIso
    (finiteTypeCoordinateHopfAlgebra_obj R n)
    (finiteTypeCoordinateHopfAlgebra_obj K n)
    (coordinateHopfAlgebraBaseChangeIso R K n)

/-- The underlying commutative-Hopf-algebra morphism of the finite-type base-change isomorphism
is the coordinate-Hopf-algebra base-change isomorphism, with the object equalities made explicit.
-/
@[simp]
theorem finiteTypeCoordinateHopfAlgebraBaseChangeIso_hom :
    (finiteTypeCoordinateHopfAlgebraBaseChangeIso R K n).hom.hom =
      (eqToIso (congrArg (CommHopfAlgCat.baseChange (K := K))
          (finiteTypeCoordinateHopfAlgebra_obj R n)) ≪≫
        coordinateHopfAlgebraBaseChangeIso R K n ≪≫
        eqToIso (finiteTypeCoordinateHopfAlgebra_obj K n).symm).hom := by
  exact FiniteTypeCommHopfAlgCat.baseChangeIsoOfObjIso_hom
    (finiteTypeCoordinateHopfAlgebra_obj R n)
    (finiteTypeCoordinateHopfAlgebra_obj K n)
    (coordinateHopfAlgebraBaseChangeIso R K n)

end EpsilonEridani.SpecialOrthogonal
