/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Codex
-/
module

public import EpsilonEridani.Algebra.AlgebraicGroup.GeneralLinear.SmoothConnected
public import EpsilonEridani.Algebra.AlgebraicGroup.Smooth.CommHopfAlgCat
public import EpsilonEridani.Algebra.AlgebraicGroup.SpecialOrthogonal.Basic
import EpsilonEridani.LinearAlgebra.Matrix.SpecialOrthogonalGroup.Lift

/-!
# Smoothness of the special orthogonal group

When `2` is invertible in the ground ring, the coordinate algebra of the standard special
orthogonal group `SOₙ` is smooth. The infinitesimal lifting criterion turns a lift of a
coordinate-algebra map through a square-zero quotient into a lift of the corresponding special
orthogonal matrix. The matrix lift is supplied by
`Matrix.SpecialOrthogonalGroup.map_quotient_mk_surjective_of_sq_eq_bot`.

Finite presentation follows because the defining ideal is generated by the finitely many
entries of `X Xᵀ - 1` together with `det X - 1`. The proof follows the formal-smoothness route
used for `EpsilonEridani.Symplectic`, with the half-error correction particular to symmetric forms.

## Main declarations

* `EpsilonEridani.SpecialOrthogonal.instSmoothCoordinateHopfAlgebra`: the coordinate algebra of
  `SOₙ` is smooth when `2` is invertible.
* `EpsilonEridani.SpecialOrthogonal.smoothCommHopfAlgProperty_finiteTypeCoordinateHopfAlgebra`: the
  same result for the bundled finite-type commutative Hopf algebra.

## References

* SGA 3, Exposé XXIII, for split orthogonal group schemes away from characteristic two.
* The Stacks Project, Tags 00TH, 00TI, 00T2, and 00TN, for formal smoothness and smooth algebras.

This supplies the smoothness prerequisite for the `SOₙ` reductivity worked example in Layer 6
of the ReductiveGroups roadmap.
-/

public section

open WithConv

namespace EpsilonEridani.SpecialOrthogonal

universe u

noncomputable section

attribute [local instance] starRingOfComm

variable (R : Type u) [CommRing R] (n : ℕ)

/-- The special orthogonal coordinate algebra is formally smooth when `2` is invertible in the
ground ring. -/
private instance instFormallySmoothCoordinateHopfAlgebra [Invertible (2 : R)] :
    Algebra.FormallySmooth R (coordinateHopfAlgebra R n) := by
  apply Algebra.FormallySmooth.of_comp_surjective
  intro B _ _ I hI f
  let _ : Invertible (2 : B) :=
    (Invertible.map (algebraMap R B) 2).copy 2 (map_ofNat (algebraMap R B) 2).symm
  obtain ⟨t, ht⟩ :=
    Matrix.SpecialOrthogonalGroup.map_quotient_mk_surjective_of_sq_eq_bot
      (n := Fin n) I hI (pointsMulEquiv R n (A := B ⧸ I) (toConv f))
  let g : WithConv (coordinateHopfAlgebra R n →ₐ[R] B) :=
    (pointsMulEquiv R n (A := B)).symm t
  refine ⟨g.ofConv, ?_⟩
  apply toConv_injective
  apply (pointsMulEquiv R n (A := B ⧸ I)).injective
  rw [← AlgHom.mapValue_apply, pointsMulEquiv_mapValue]
  have hg : pointsMulEquiv R n (A := B) g = t :=
    (pointsMulEquiv R n (A := B)).apply_symm_apply t
  rw [hg]
  have hq : ((Ideal.Quotient.mkₐ R I : B →ₐ[R] B ⧸ I) : B →+* B ⧸ I) = Ideal.Quotient.mk I := by
    rw [← AlgHom.toRingHom_eq_coe]
    exact Ideal.Quotient.mkₐ_toRingHom (R₁ := R) I
  rw [hq]
  exact ht

/-- The coordinate algebra of `SOₙ` is smooth when `2` is invertible in the ground ring. -/
instance instSmoothCoordinateHopfAlgebra [Invertible (2 : R)] :
    Algebra.Smooth R (coordinateHopfAlgebra R n) := by
  have hfg : (definingHopfIdeal R n).toIdeal.FG := by
    rw [definingHopfIdeal_toIdeal]
    apply Submodule.FG.sup
    · apply Submodule.fg_span
      let f := fun ij : Fin n × Fin n ↦ Orthogonal.relationMatrix R n ij.1 ij.2
      refine (Set.finite_range f).subset ?_
      intro x hx
      obtain ⟨i, j, hij⟩ :=
        (ConstantForm.mem_relationSet_iff
          (R := R) (n := n) (C := (1 : Matrix (Fin n) (Fin n) R))).mp hx
      exact ⟨(i, j), hij⟩
    · exact Submodule.fg_span_singleton _
  let _ : Algebra.FinitePresentation R (coordinateHopfAlgebra R n) :=
    Algebra.FinitePresentation.quotient hfg
  exact ⟨inferInstance, inferInstance⟩

/-- The finite-type commutative Hopf algebra representing `SOₙ` has smooth coordinate ring
when `2` is invertible in the ground ring. -/
theorem smoothCommHopfAlgProperty_finiteTypeCoordinateHopfAlgebra [Invertible (2 : R)] :
    smoothCommHopfAlgProperty R (finiteTypeCoordinateHopfAlgebra R n).obj := by
  rw [smoothCommHopfAlgProperty_iff, finiteTypeCoordinateHopfAlgebra_obj]
  infer_instance

end

end EpsilonEridani.SpecialOrthogonal
