/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.FieldTheory.GaloisGroups.Resolvent.Spec
public import EpsilonEridani.GroupTheory.Perm.TransitiveGroupLabel.Basic
import EpsilonEridani.RingTheory.MvPolynomial.Symmetric.Elementary

/-!
# The quartic resolvent specification and the resolvent cubic

The `D₄`-invariant of four formal roots is `x₀x₂ + x₁x₃`. A permutation of the roots fixes it
exactly when it preserves the pairing `{{0, 2}, {1, 3}}`, that is, exactly when it lies in the
dihedral group of order `8` generated by the rotation `(0 1 2 3)` and the diagonal swap `(0 2)`,
which is the reference subgroup of the transitive-group label `4T3`. Its orbit under all
permutations consists of the three pairing sums

`x₀x₂ + x₁x₃`, `x₀x₁ + x₂x₃`, `x₀x₃ + x₁x₂`,

so the orbit resolvent is a cubic. Written in the elementary symmetric polynomials `e₁, …, e₄`
of the roots, it is

`X³ - e₂ X² + (e₁e₃ - 4e₄) X - (e₁²e₄ + e₃² - 4e₂e₄)`.

Specializing at a quartic `X⁴ + aX³ + bX² + cX + d` gives the classical resolvent cubic
`X³ - bX² + (ac - 4d)X - (a²d + c² - 4bd)`, and at a depressed quartic `X⁴ + pX² + qX + r` it
gives `EpsilonEridani.resolventCubic p q r = X³ - pX² - 4rX + (4pr - q²)`. Both are theorems about the
universal object `EpsilonEridani.quarticD4Spec`, not definitions of the resolvent: the closed form is
identified with the orbit product through the uniqueness of the symmetric expression.

The invariant is `x₀x₂ + x₁x₃` rather than one of the other two orbit elements because its
stabilizer is the reference subgroup of `4T3` on the nose; the other two have conjugate
stabilizers and the same resolvent.

## Main definitions

* `EpsilonEridani.quarticD4Invariant`: the invariant `x₀x₂ + x₁x₃`.
* `EpsilonEridani.quarticD4Spec`: the resolvent specification of the invariant, for the subgroup `4T3`.
* `EpsilonEridani.resolventCubic`: the resolvent cubic of the depressed quartic `X⁴ + pX² + qX + r`.

## Main results

* `EpsilonEridani.rename_quarticD4Invariant_eq_self_iff`: the stabilizer of the invariant is exactly the
  reference subgroup of `4T3`.
* `EpsilonEridani.renameOrbit_quarticD4Invariant`: its orbit is the three pairing sums, and
  `EpsilonEridani.card_renameOrbit_quarticD4Invariant`: it has three elements.
* `EpsilonEridani.quarticD4Spec_orbitProduct`: the orbit product in the elementary symmetric
  polynomials.
* `EpsilonEridani.quarticD4Spec_specialize`: the resolvent of an arbitrary polynomial, read off its
  coefficients of degree at most three.
* `EpsilonEridani.quarticD4Spec_specialize_depressed`: the resolvent of a depressed quartic is
  `resolventCubic p q r`.
* `EpsilonEridani.natDegree_quarticD4Spec_specialize`: the resolvent of a quartic is a cubic.

## References

* K. Conrad, *Galois groups of cubics and quartics (not in characteristic 2)*, Definition 3.1
  and (3.7).
-/

public section

open Equiv Equiv.Perm Polynomial

namespace EpsilonEridani

open MvPolynomial (renameOrbit universalResolvent)

/-- The `D₄`-invariant `x₀x₂ + x₁x₃` of four formal roots: the sum over the pairing
`{{0, 2}, {1, 3}}` of the products of paired roots. -/
noncomputable def quarticD4Invariant : MvPolynomial (Fin 4) ℤ :=
  MvPolynomial.X 0 * MvPolynomial.X 2 + MvPolynomial.X 1 * MvPolynomial.X 3

/-- The defining formula of the quartic `D₄`-invariant. -/
theorem quarticD4Invariant_def :
    quarticD4Invariant =
      MvPolynomial.X 0 * MvPolynomial.X 2 + MvPolynomial.X 1 * MvPolynomial.X 3 :=
  (rfl)

/-- Renaming the variables of the `D₄`-invariant along `σ`. -/
theorem rename_quarticD4Invariant (σ : Perm (Fin 4)) :
    MvPolynomial.rename (⇑σ) quarticD4Invariant =
      MvPolynomial.X (σ 0) * MvPolynomial.X (σ 2) +
        MvPolynomial.X (σ 1) * MvPolynomial.X (σ 3) := by
  simp [quarticD4Invariant]

/-- Twice the invariant is the sum of `xᵢ xᵢ₊₂` over all `i`, a form in which invariance under a
permutation commuting with `i ↦ i + 2` is a reindexing of the sum. -/
private theorem two_smul_quarticD4Invariant :
    (2 : ℤ) • quarticD4Invariant =
      ∑ i : Fin 4, MvPolynomial.X i * MvPolynomial.X (i + 2) := by
  have h1 : (1 : Fin 4) + 2 = 3 := rfl
  have h2 : (2 : Fin 4) + 2 = 0 := rfl
  have h3 : (3 : Fin 4) + 2 = 1 := rfl
  simp only [Fin.sum_univ_four, zero_add, h1, h2, h3, quarticD4Invariant]
  ring

/-- The `D₄`-invariant takes the value `13` at the point `(1, 2, 3, 5)`, and every permutation of
the coordinates that does not preserve the pairing `{{0, 2}, {1, 3}}` changes that value. -/
private theorem pairing_or_value_ne (σ : Perm (Fin 4)) :
    (∀ i, σ (i + 2) = σ i + 2) ∨
      (![1, 2, 3, 5] (σ 0) * ![1, 2, 3, 5] (σ 2) + ![1, 2, 3, 5] (σ 1) * ![1, 2, 3, 5] (σ 3) :
        ℤ) ≠ 13 := by
  revert σ
  decide

/-- **The exact stabilizer.** A permutation fixes the `D₄`-invariant if and only if it lies in
the reference subgroup of `4T3`, the dihedral group preserving the pairing `{{0, 2}, {1, 3}}`. -/
theorem rename_quarticD4Invariant_eq_self_iff (σ : Perm (Fin 4)) :
    MvPolynomial.rename (⇑σ) quarticD4Invariant = quarticD4Invariant ↔
      σ ∈ referenceSubgroup 4 ⟨2, by simp⟩ := by
  rw [mem_referenceSubgroup_four_two_iff]
  constructor
  · intro h
    refine (pairing_or_value_ne σ).resolve_right fun hne => hne ?_
    have := congrArg (MvPolynomial.eval ![1, 2, 3, 5]) h
    simpa [rename_quarticD4Invariant, quarticD4Invariant] using this
  · intro h
    refine smul_right_injective _ (two_ne_zero : (2 : ℤ) ≠ 0) ?_
    dsimp only
    rw [← map_zsmul, two_smul_quarticD4Invariant, map_sum]
    simp only [map_mul, MvPolynomial.rename_X, h]
    exact Equiv.sum_comp σ fun i : Fin 4 =>
      (MvPolynomial.X i * MvPolynomial.X (i + 2) : MvPolynomial (Fin 4) ℤ)

/-- **The orbit of the `D₄`-invariant** consists of the three pairing sums. -/
theorem renameOrbit_quarticD4Invariant :
    renameOrbit quarticD4Invariant =
      {MvPolynomial.X 0 * MvPolynomial.X 2 + MvPolynomial.X 1 * MvPolynomial.X 3,
        MvPolynomial.X 0 * MvPolynomial.X 1 + MvPolynomial.X 2 * MvPolynomial.X 3,
        MvPolynomial.X 0 * MvPolynomial.X 3 + MvPolynomial.X 1 * MvPolynomial.X 2} := by
  ext Ψ
  simp only [MvPolynomial.mem_renameOrbit, Finset.mem_insert, Finset.mem_singleton]
  constructor
  · rintro ⟨σ, rfl⟩
    -- Every permutation lies in one of the three cosets `H`, `(1 2) H`, `(2 3) H` of the
    -- stabilizer `H`, and the invariant takes one value on each coset.
    have hcoset : ∀ σ : Perm (Fin 4), (∀ i, σ (i + 2) = σ i + 2) ∨
        (∀ i, swap 1 2 (σ (i + 2)) = swap 1 2 (σ i) + 2) ∨
        (∀ i, swap 2 3 (σ (i + 2)) = swap 2 3 (σ i) + 2) := by
      decide
    have hstab (τ : Perm (Fin 4)) (h : ∀ i, τ (i + 2) = τ i + 2) :
        MvPolynomial.rename (⇑τ) quarticD4Invariant = quarticD4Invariant :=
      (rename_quarticD4Invariant_eq_self_iff τ).2 (mem_referenceSubgroup_four_two_iff.2 h)
    rcases hcoset σ with h | h | h
    · exact Or.inl (hstab σ h)
    · right; left
      rw [← swap_mul_self_mul 1 2 σ, coe_mul, ← MvPolynomial.rename_rename,
        hstab (swap 1 2 * σ) h, rename_quarticD4Invariant]
      simp [swap_apply_of_ne_of_ne]
    · right; right
      rw [← swap_mul_self_mul 2 3 σ, coe_mul, ← MvPolynomial.rename_rename,
        hstab (swap 2 3 * σ) h, rename_quarticD4Invariant]
      simp [swap_apply_of_ne_of_ne]
  · rintro (rfl | rfl | rfl)
    · exact ⟨1, by simp [quarticD4Invariant]⟩
    · exact ⟨swap 1 2, by simp [rename_quarticD4Invariant, swap_apply_of_ne_of_ne]⟩
    · exact ⟨swap 2 3, by simp [rename_quarticD4Invariant, swap_apply_of_ne_of_ne]⟩

/-- The three pairing sums are distinct: at the point `(1, 2, 3, 5)` they take the values `13`,
`17` and `11`. -/
private theorem pairingSums_ne :
    (MvPolynomial.X 0 * MvPolynomial.X 2 + MvPolynomial.X 1 * MvPolynomial.X 3 :
        MvPolynomial (Fin 4) ℤ) ≠
        MvPolynomial.X 0 * MvPolynomial.X 1 + MvPolynomial.X 2 * MvPolynomial.X 3 ∧
      (MvPolynomial.X 0 * MvPolynomial.X 2 + MvPolynomial.X 1 * MvPolynomial.X 3 :
        MvPolynomial (Fin 4) ℤ) ≠
        MvPolynomial.X 0 * MvPolynomial.X 3 + MvPolynomial.X 1 * MvPolynomial.X 2 ∧
      (MvPolynomial.X 0 * MvPolynomial.X 1 + MvPolynomial.X 2 * MvPolynomial.X 3 :
        MvPolynomial (Fin 4) ℤ) ≠
        MvPolynomial.X 0 * MvPolynomial.X 3 + MvPolynomial.X 1 * MvPolynomial.X 2 := by
  refine ⟨fun h => ?_, fun h => ?_, fun h => ?_⟩ <;>
    simpa using congrArg (MvPolynomial.eval (![1, 2, 3, 5] : Fin 4 → ℤ)) h

/-- The orbit of the `D₄`-invariant has three elements, so its resolvent is a cubic. -/
theorem card_renameOrbit_quarticD4Invariant : (renameOrbit quarticD4Invariant).card = 3 := by
  obtain ⟨h₁, h₂, h₃⟩ := pairingSums_ne
  rw [renameOrbit_quarticD4Invariant, Finset.card_eq_three]
  exact ⟨_, _, _, h₁, h₂, h₃, rfl⟩

/-- **The quartic resolvent specification**: the `D₄`-invariant `x₀x₂ + x₁x₃`, whose stabilizer
is exactly the reference subgroup of `4T3`, with its orbit product
`X³ - e₂ X² + (e₁e₃ - 4e₄) X - (e₁²e₄ + e₃² - 4e₂e₄)` in the elementary symmetric polynomials,
where `eₖ₊₁` is the variable `xₖ`. -/
noncomputable def quarticD4Spec : ResolventSpec 4 where
  H := referenceSubgroup 4 ⟨2, by simp⟩
  Φ := quarticD4Invariant
  stabilizer_eq := rename_quarticD4Invariant_eq_self_iff
  orbitProduct := X ^ 3 - C (MvPolynomial.X 1) * X ^ 2 +
    C (MvPolynomial.X 0 * MvPolynomial.X 2 - 4 * MvPolynomial.X 3) * X -
    C (MvPolynomial.X 0 ^ 2 * MvPolynomial.X 3 + MvPolynomial.X 2 ^ 2 -
      4 * MvPolynomial.X 1 * MvPolynomial.X 3)
  orbitProduct_esymm := by
    obtain ⟨h₁, h₂, h₃⟩ := pairingSums_ne
    obtain ⟨e₁, e₂, e₃, e₄⟩ := esymm_fin_four (R := ℤ)
    rw [MvPolynomial.universalResolvent_def, renameOrbit_quarticD4Invariant,
      Finset.prod_insert (by simp [h₁, h₂]), Finset.prod_insert (by simp [h₃]),
      Finset.prod_singleton]
    simp only [Polynomial.map_sub, Polynomial.map_add, Polynomial.map_mul, Polynomial.map_pow,
      Polynomial.map_X, Polynomial.map_C, map_sub, map_add, map_mul, map_pow, map_ofNat,
      Polynomial.map_ofNat, esymmSubst_X, Fin.isValue, Fin.coe_ofNat_eq_mod, Nat.reduceMod,
      Nat.reduceAdd, e₁, e₂, e₃, e₄]
    ring

@[simp]
theorem quarticD4Spec_H : quarticD4Spec.H = referenceSubgroup 4 ⟨2, by simp⟩ :=
  (rfl)

@[simp]
theorem quarticD4Spec_Φ : quarticD4Spec.Φ = quarticD4Invariant :=
  (rfl)

/-- The orbit product of the quartic specification, in the elementary symmetric polynomials
`eₖ₊₁ = xₖ`. -/
theorem quarticD4Spec_orbitProduct :
    quarticD4Spec.orbitProduct = X ^ 3 - C (MvPolynomial.X 1) * X ^ 2 +
      C (MvPolynomial.X 0 * MvPolynomial.X 2 - 4 * MvPolynomial.X 3) * X -
      C (MvPolynomial.X 0 ^ 2 * MvPolynomial.X 3 + MvPolynomial.X 2 ^ 2 -
        4 * MvPolynomial.X 1 * MvPolynomial.X 3) :=
  (rfl)

/-- **The resolvent cubic of a polynomial**, read off its coefficients: for the quartic
`X⁴ + aX³ + bX² + cX + d` it is `X³ - bX² + (ac - 4d)X - (a²d + c² - 4bd)`. The formula holds for
every polynomial `f`, since the specialization only reads the coefficients of `f` of degree at
most three. -/
theorem quarticD4Spec_specialize (R : Type*) [CommRing R] (f : R[X]) :
    quarticD4Spec.specialize R f = X ^ 3 - C (f.coeff 2) * X ^ 2 +
      C (f.coeff 3 * f.coeff 1 - 4 * f.coeff 0) * X -
      C (f.coeff 3 ^ 2 * f.coeff 0 + f.coeff 1 ^ 2 - 4 * f.coeff 2 * f.coeff 0) := by
  rw [ResolventSpec.specialize_def, quarticD4Spec_orbitProduct]
  simp only [Polynomial.map_sub, Polynomial.map_add, Polynomial.map_mul, Polynomial.map_pow,
    Polynomial.map_X, Polynomial.map_C, Polynomial.map_ofNat, map_sub, map_add, map_mul, map_pow,
    map_neg, map_one, map_ofNat, vietaHom_X, Fin.isValue, Fin.coe_ofNat_eq_mod, Nat.reduceMod,
    Nat.reduceAdd, Nat.reduceSub]
  ring

/-- The **resolvent cubic** `X³ - pX² - 4rX + (4pr - q²)` of the depressed quartic
`X⁴ + pX² + qX + r`: the specialization of the quartic resolvent specification at the
depressed quartic (`EpsilonEridani.quarticD4Spec_specialize_depressed`). -/
noncomputable def resolventCubic {R : Type*} [CommRing R] (p q r : R) : R[X] :=
  X ^ 3 - C p * X ^ 2 - C (4 * r) * X + C (4 * p * r - q ^ 2)

/-- The defining formula of the resolvent cubic. -/
theorem resolventCubic_def {R : Type*} [CommRing R] (p q r : R) :
    resolventCubic p q r = X ^ 3 - C p * X ^ 2 - C (4 * r) * X + C (4 * p * r - q ^ 2) :=
  (rfl)

/-- **The closed form of the quartic resolvent**: the specialization of the quartic specification
at the depressed quartic `X⁴ + pX² + qX + r` is its resolvent cubic. -/
theorem quarticD4Spec_specialize_depressed {R : Type*} [CommRing R] (p q r : R) :
    quarticD4Spec.specialize R (X ^ 4 + C p * X ^ 2 + C q * X + C r) = resolventCubic p q r := by
  rw [quarticD4Spec_specialize, resolventCubic_def]
  simp only [coeff_add, coeff_X_pow, coeff_C_mul, coeff_X, coeff_C]
  norm_num
  ring

/-- The resolvent cubic is monic. -/
theorem monic_resolventCubic {R : Type*} [CommRing R] (p q r : R) :
    (resolventCubic p q r).Monic := by
  rw [← quarticD4Spec_specialize_depressed]
  exact quarticD4Spec.monic_specialize R _

/-- The resolvent of the quartic specification is a cubic over every nonzero ring, since the
orbit of the `D₄`-invariant has three elements.

This is not a `simp` lemma: `EpsilonEridani.ResolventSpec.natDegree_specialize` already rewrites the
left-hand side, to the index of the subgroup of the specification. -/
theorem natDegree_quarticD4Spec_specialize {R : Type*} [CommRing R] [Nontrivial R] (f : R[X]) :
    (quarticD4Spec.specialize R f).natDegree = 3 := by
  rw [ResolventSpec.natDegree_specialize, ← ResolventSpec.card_renameOrbit, quarticD4Spec_Φ,
    card_renameOrbit_quarticD4Invariant]

/-- The resolvent cubic has degree `3` over every nonzero ring. -/
@[simp]
theorem natDegree_resolventCubic {R : Type*} [CommRing R] [Nontrivial R] (p q r : R) :
    (resolventCubic p q r).natDegree = 3 := by
  rw [← quarticD4Spec_specialize_depressed, natDegree_quarticD4Spec_specialize]

end EpsilonEridani
