/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.Algebra.WordFiltration.Domain
public import EpsilonEridani.Algebra.Lie.UniversalEnveloping.Bialgebra
public import EpsilonEridani.Algebra.Lie.UniversalEnveloping.PBW.AssociatedGraded

/-!
# The enveloping algebra is a domain once its PBW associated graded is

The PBW filtration of `U(L)` is the word filtration generated by the canonical Lie map
`UniversalEnvelopingAlgebra.ι R`, and it is exhaustive
(`EpsilonEridani.UniversalEnvelopingAlgebra.iSup_pbwFiltration_eq_top`), so the filtered-to-graded
transfer of `EpsilonEridani/Algebra/WordFiltration/Domain.lean` applies to it verbatim: if the PBW
associated graded `gr U(L)` has no zero divisors, then neither does `U(L)`.

Transferring the domain property downwards needs two mathematical inputs: exhaustivity of the
filtration, and the domain property of the graded side. The first holds for the PBW filtration of
any Lie algebra over any commutative ring. The second is a hypothesis of the statements below, and
its classical source is the Poincaré--Birkhoff--Witt theorem: the canonical map
`EpsilonEridani.UniversalEnvelopingAlgebra.pbwAssociatedGradedMap` from the symmetric algebra `Sym(L)` to
`gr U(L)` is surjective
(`EpsilonEridani.UniversalEnvelopingAlgebra.pbwAssociatedGradedMap_surjective`) and, for a free `L`,
injective, hence an isomorphism, so `gr U(L)` inherits the domain property of `Sym(L)` over a
domain.

## Main results

* `EpsilonEridani.UniversalEnvelopingAlgebra.noZeroDivisors_of_noZeroDivisors_pbwAssociatedGraded`:
  `U(L)` has no zero divisors as soon as `gr U(L)` has none.
* `EpsilonEridani.UniversalEnvelopingAlgebra.isDomain_of_noZeroDivisors_pbwAssociatedGraded`: over a
  nontrivial base ring, `U(L)` is then a domain.

## References

* J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*, Chapter V, §17.
* N. Bourbaki, *Lie Groups and Lie Algebras*, Chapter I, §2.7.
-/

public section

namespace EpsilonEridani.UniversalEnvelopingAlgebra

universe u v

variable (R : Type u) (L : Type v) [CommRing R] [LieRing L] [LieAlgebra R L]

attribute [local instance 100] LieRing.ofAssociativeRing

local notation "U" => _root_.UniversalEnvelopingAlgebra R L

/-- **The enveloping algebra has no zero divisors as soon as its PBW associated graded has
none.** -/
theorem noZeroDivisors_of_noZeroDivisors_pbwAssociatedGraded
    [NoZeroDivisors (PBWAssociatedGraded R L)] : NoZeroDivisors U :=
  EpsilonEridani.Algebra.wordFiltration.noZeroDivisors_of_noZeroDivisors_associatedGraded
    (_root_.UniversalEnvelopingAlgebra.ι R (L := L)).toLinearMap
    fun a => by simpa only [pbwFiltration_def] using exists_mem_pbwFiltration R L a

/-- **The enveloping algebra of a Lie algebra over a nontrivial base ring is a domain as soon as
its PBW associated graded has no zero divisors.** -/
theorem isDomain_of_noZeroDivisors_pbwAssociatedGraded [Nontrivial R]
    [NoZeroDivisors (PBWAssociatedGraded R L)] : IsDomain U := by
  have : Nontrivial U := Bialgebra.nontrivial R
  exact EpsilonEridani.Algebra.wordFiltration.isDomain_of_noZeroDivisors_associatedGraded
    (_root_.UniversalEnvelopingAlgebra.ι R (L := L)).toLinearMap
    fun a => by simpa only [pbwFiltration_def] using exists_mem_pbwFiltration R L a

end EpsilonEridani.UniversalEnvelopingAlgebra
