/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.Algebra.Subalgebra.Lattice
public import Mathlib.Algebra.Ring.Subring.Basic

/-!
# The subalgebra generated by a subring

Adjoining a subring `R` of an `S`-algebra `A` creates nothing beyond the `S`-span of `R`: a subring
is already closed under multiplication and contains `1`, so the products that `Algebra.adjoin`
forms are again elements of `R`.

## Main results

* `Subring.toSubmodule_adjoin_coe`: `Algebra.adjoin S (R : Set A)`, as a submodule, is
  `Submodule.span S (R : Set A)`.
-/

public section

namespace Subring

variable {S A : Type*} [CommSemiring S] [Ring A] [Algebra S A]

/-- The `S`-subalgebra generated by a subring is its `S`-span. A subring is already closed under
multiplication and contains `1`, so adjoining it creates no products that its span misses. -/
theorem toSubmodule_adjoin_coe (R : Subring A) :
    Subalgebra.toSubmodule (Algebra.adjoin S (R : Set A)) = Submodule.span S (R : Set A) := by
  have hclosure : (Submonoid.closure (R : Set A) : Set A) ⊆
      (Submodule.span S (R : Set A) : Set A) := by
    rw [← Subring.coe_toSubmonoid, Submonoid.closure_eq]
    exact Submodule.subset_span
  exact Algebra.adjoin_eq_span_of_subset S hclosure

end Subring
