/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.CharZero.Infinite
public import EpsilonEridani.RepresentationTheory.ClassicalGroups.WeylModule.Basic
public import EpsilonEridani.RepresentationTheory.Irreducible
public import EpsilonEridani.RepresentationTheory.Simple.Basic
public import EpsilonEridani.RepresentationTheory.Symmetric.Factorization
public import EpsilonEridani.RepresentationTheory.Symmetric.TensorAction.GeneralLinear
public import EpsilonEridani.RingTheory.Semisimple.NilpotentIdeal

/-!
# The Weyl module is an irreducible representation of `GL n k`

Over a field `k` of characteristic zero, the Weyl module `𝕊^μ(kⁿ) = c_t · (kⁿ)^{⊗d}` of a
`μ`-tableau `t`, the image of its Young symmetrizer `c_t` acting on the tensor power, is an
**irreducible** representation of `GL n k` whenever it is nonzero, that is, whenever `μ` has at most
`n` rows (`EpsilonEridani.YoungTableau.isIrreducible_weylRep`). Together with the vanishing criterion
`EpsilonEridani.YoungTableau.weylModule_eq_bot_iff`, irreducibility holds exactly when `μ.colLen 0 ≤ n`
(`EpsilonEridani.YoungTableau.isIrreducible_weylRep_iff`), and the same holds for the shape-indexed Weyl
module and its bundled forms `EpsilonEridani.weylFDRepOfShape` and `EpsilonEridani.schurFunctor`.

## Main results

* `EpsilonEridani.YoungTableau.isAtom_weylModule`: the Weyl module of a tableau with at most `n` rows is a
  minimal nonzero subrepresentation of `(kⁿ)^{⊗d}`.
* `EpsilonEridani.YoungTableau.isIrreducible_weylRep`: it is an irreducible representation of `GL n k`,
  and `EpsilonEridani.YoungTableau.isIrreducible_weylRep_iff` characterizes irreducibility by the number
  of rows.
* `EpsilonEridani.isIrreducible_weylRepOfShape_iff`, `EpsilonEridani.simple_weylFDRepOfShape_iff` and
  `EpsilonEridani.simple_schurFunctor_iff`: the same criterion for the Weyl module of a shape, as a
  representation and as an object of `FDRep`.

## References

* W. Fulton and J. Harris, *Representation Theory: A First Course* (1991), Lecture 6, Theorem 6.3,
  proved there in §6.2 through the commutant of `k[S_d]`; the same commutant drives the argument
  here, with an annihilator computation in place of their Lemma 6.22.
* C. Procesi, *Lie Groups: An Approach through Invariants and Representations* (2007), Chapter 9.
-/

public section

open Matrix
open scoped Nat TensorProduct

universe u

namespace EpsilonEridani

namespace YoungTableau

variable {k : Type u} [Field k] [CharZero k] {n : ℕ} {μ : YoungDiagram}

/-- An element of `k[S_d]` killing a nonzero vector `c_t u` of the Weyl module already
annihilates `c_t` from the right. -/
private theorem mul_youngSymmetrizerOver_eq_zero (t : YoungTableau μ)
    {u : ⨂[k]^μ.card (Fin n → k)}
    (hu : permTensorActionAlgHom k n μ.card (youngSymmetrizerOver k t) u ≠ 0)
    {r : MonoidAlgebra k (Equiv.Perm (Fin μ.card))}
    (hr : permTensorActionAlgHom k n μ.card r
      (permTensorActionAlgHom k n μ.card (youngSymmetrizerOver k t) u) = 0) :
    r * youngSymmetrizerOver k t = 0 := by
  -- Maschke's theorem makes `k[S_d]` semisimple
  have : NeZero (Nat.card (Equiv.Perm (Fin μ.card)) : k) :=
    ⟨Nat.cast_ne_zero.mpr Nat.card_pos.ne'⟩
  -- every sandwich `c_t (b r) c_t` vanishes: it is a multiple of `c_t` killing `u`
  have hsand : ∀ b, youngSymmetrizerOver k t * (b * r) * youngSymmetrizerOver k t = 0 := by
    intro b
    obtain ⟨κ, hκ⟩ := exists_eq_smul_youngSymmetrizerOver_mul_mul k t (b * r)
    have happ := congrArg (fun a => permTensorActionAlgHom k n μ.card a u) hκ
    simp only [map_mul, Module.End.mul_apply, map_smul, LinearMap.smul_apply] at happ
    rw [hr, map_zero, map_zero] at happ
    rw [hκ, (smul_eq_zero.mp happ.symm).resolve_right hu, zero_smul]
  -- so the left ideal generated by `r c_t` is square-zero, hence zero
  have hbot : Submodule.span (MonoidAlgebra k (Equiv.Perm (Fin μ.card)))
      {r * youngSymmetrizerOver k t} = ⊥ := by
    refine Submodule.eq_bot_of_forall_mul_eq_zero fun x hx y hy => ?_
    obtain ⟨a, rfl⟩ := Submodule.mem_span_singleton.mp hx
    obtain ⟨b, rfl⟩ := Submodule.mem_span_singleton.mp hy
    rw [smul_eq_mul, smul_eq_mul]
    calc a * (r * youngSymmetrizerOver k t) * (b * (r * youngSymmetrizerOver k t)) =
          a * r * (youngSymmetrizerOver k t * (b * r) * youngSymmetrizerOver k t) := by
          simp only [mul_assoc]
      _ = 0 := by rw [hsand b, mul_zero]
  have hmem := Submodule.mem_span_singleton_self
    (R := MonoidAlgebra k (Equiv.Perm (Fin μ.card))) (r * youngSymmetrizerOver k t)
  rwa [hbot, Submodule.mem_bot] at hmem

/-- Every nonzero vector of the Weyl module generates it under the action of `k[GLₙ]`. -/
private theorem exists_asAlgebraHom_apply_eq (t : YoungTableau μ)
    {w x : ⨂[k]^μ.card (Fin n → k)} (hw : w ∈ (weylModule k n t).toSubmodule) (hw0 : w ≠ 0)
    (hx : x ∈ (weylModule k n t).toSubmodule) :
    ∃ a : MonoidAlgebra k (GL (Fin n) k), (tensorPowerRep k n μ.card).asAlgebraHom a w = x := by
  have : NeZero (Nat.card (Equiv.Perm (Fin μ.card)) : k) :=
    ⟨Nat.cast_ne_zero.mpr Nat.card_pos.ne'⟩
  have : NeZero (μ.card ! : k) := ⟨Nat.cast_ne_zero.mpr (Nat.factorial_ne_zero _)⟩
  rw [weylModule_toSubmodule] at hw hx
  obtain ⟨u, rfl⟩ := hw
  obtain ⟨u', rfl⟩ := hx
  -- an element of `k[S_d]` killing `c_t u` kills `c_t u'`, so some endomorphism commuting with
  -- `k[S_d]` carries `c_t u` to `c_t u'`
  obtain ⟨f, hf, hfx⟩ := (exists_mem_centralizer_range_apply_eq_iff
    (permTensorActionAlgHom k n μ.card)
    (x := permTensorActionAlgHom k n μ.card (youngSymmetrizerOver k t) u')).mpr fun r hr => by
      rw [← Module.End.mul_apply, ← map_mul, mul_youngSymmetrizerOver_eq_zero t hw0 hr, map_zero,
        LinearMap.zero_apply]
  -- by Schur-Weyl duality, such an endomorphism is the action of an element of `k[GLₙ]`
  rw [centralizer_range_permTensorActionAlgHom_eq_range_tensorPowerRep_asAlgebraHom] at hf
  obtain ⟨a, rfl⟩ := hf
  exact ⟨a, hfx⟩

/-- **The Weyl module is a minimal subrepresentation.** In characteristic zero, the Weyl module of a
`μ`-tableau with at most `n` rows is an atom of the lattice of subrepresentations of `(kⁿ)^{⊗|μ|}`:
it is nonzero and has no nonzero proper subrepresentation. -/
theorem isAtom_weylModule (t : YoungTableau μ) (hn : μ.colLen 0 ≤ n) :
    IsAtom (weylModule k n t) := by
  refine ⟨weylModule_ne_bot t hn, fun τ hτ => ?_⟩
  by_contra hne
  obtain ⟨w, hwτ, hw0⟩ := Submodule.exists_mem_ne_zero_of_ne_bot fun h =>
    hne (Subrepresentation.toSubmodule_injective h)
  -- a nonzero vector of `τ` generates the whole Weyl module, contradicting `τ < weylModule`
  refine hτ.not_ge fun x hx => ?_
  obtain ⟨a, rfl⟩ := exists_asAlgebraHom_apply_eq t (hτ.le hwτ) hw0 hx
  rw [← Subrepresentation.coe_toRepresentation_asAlgebraHom_apply τ a ⟨w, hwτ⟩]
  exact Submodule.coe_mem _

/-- **The Weyl module is irreducible.** In characteristic zero, the Weyl module
`𝕊^μ(kⁿ) = c_t · (kⁿ)^{⊗|μ|}` of a `μ`-tableau `t` with at most `n` rows is an irreducible
representation of `GL n k`. -/
theorem isIrreducible_weylRep (t : YoungTableau μ) (hn : μ.colLen 0 ≤ n) :
    Representation.IsIrreducible (V := (weylModule k n t).toSubmodule) (weylRep k n t) :=
  Representation.isIrreducible_toRepresentation_of_isAtom (isAtom_weylModule t hn)

/-- **The irreducibility criterion for the Weyl module.** In characteristic zero, the Weyl module
of a `μ`-tableau is an irreducible representation of `GL n k` exactly when `μ` has at most `n`
rows; otherwise it is zero. -/
@[simp]
theorem isIrreducible_weylRep_iff (t : YoungTableau μ) :
    Representation.IsIrreducible (V := (weylModule k n t).toSubmodule) (weylRep k n t) ↔
      μ.colLen 0 ≤ n := by
  refine ⟨fun h => not_lt.mp fun hn => ?_, isIrreducible_weylRep t⟩
  exact Submodule.nontrivial_iff_ne_bot.mp (Representation.IsIrreducible.nontrivial h)
    (by rw [weylModule_eq_bot t hn, Subrepresentation.toSubmodule_bot])

end YoungTableau

section Shape

variable {k : Type u} [Field k] [CharZero k] {n : ℕ}

/-- **The irreducibility criterion for the Weyl module of a shape.** In characteristic zero, the
Weyl module of `μ` is an irreducible representation of `GL n k` exactly when `μ` has at most `n`
rows. -/
@[simp]
theorem isIrreducible_weylRepOfShape_iff (μ : YoungDiagram) :
    Representation.IsIrreducible (V := (weylModuleOfShape k n μ).toSubmodule)
      (weylRepOfShape k n μ) ↔ μ.colLen 0 ≤ n := by
  refine ⟨fun h => not_lt.mp fun hn => ?_, fun hn => ?_⟩
  · exact Submodule.nontrivial_iff_ne_bot.mp (Representation.IsIrreducible.nontrivial h)
      (by rw [(weylModuleOfShape_eq_bot_iff k n μ).mpr hn, Subrepresentation.toSubmodule_bot])
  · refine Representation.isIrreducible_toRepresentation_of_isAtom ?_
    rw [weylModuleOfShape_def]
    exact YoungTableau.isAtom_weylModule _ hn

/-- The bundled Weyl module of a shape `μ` is a simple object of `FDRep k (GL (Fin n) k)` exactly
when `μ` has at most `n` rows. -/
@[simp]
theorem simple_weylFDRepOfShape_iff (μ : YoungDiagram) :
    CategoryTheory.Simple (weylFDRepOfShape k n μ) ↔ μ.colLen 0 ≤ n := by
  rw [FDRep.simple_iff_isIrreducible]
  exact isIrreducible_weylRepOfShape_iff μ

/-- **The Schur functor `𝕊^μ(ℂⁿ)` is irreducible** exactly when `μ` has at most `n` rows. -/
theorem simple_schurFunctor_iff (n : ℕ) (μ : YoungDiagram) :
    CategoryTheory.Simple (schurFunctor n μ) ↔ μ.colLen 0 ≤ n :=
  simple_weylFDRepOfShape_iff μ

end Shape

end EpsilonEridani
