/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.Exact.Basic
public import EpsilonEridani.Algebra.MvPolynomial.Rename
public import EpsilonEridani.KnotTheory.Grid.Unblocked

/-!
# The simply blocked grid map

The unblocked grid complex `GC⁻` has one polynomial variable `V_c` for each `O`-marking.  Blocking
the `O`-marking in a chosen column `i` means setting `V_i = 0`.  The resulting simply blocked
construction keeps the variables indexed by the other columns and counts exactly the empty
rectangles which cover neither an `X`-marking nor the blocked `O`-marking.  This specialization is
defined for every grid diagram and every commutative coefficient semiring.  For a knot grid over a
coefficient semiring of characteristic two, it is the simply blocked differential.  Outside
characteristic two it is only the unsigned candidate linear map: exactly as for the unblocked
differential it specializes, the unsigned rectangle count squares to zero only after a sign
assignment, and signs use additive inverses, so the sign-corrected construction needs a
commutative coefficient ring.  For a multi-component link, the corresponding simply blocked theory
instead requires blocking one `O`-marking on each component.

The coefficients form the polynomial semiring `R[V_c | c ≠ i]`, rather than one carrying a
redundant variable known to act by zero.  Mathlib's `MvPolynomial.killCompl` makes the relation to
`GC⁻` explicit, while `simplyBlockedCoefficient_eq_sum` identifies the terms that remain after
specialization.

## Main definitions

* `EpsilonEridani.GridChainHat`: the free module underlying the one-variable specialization.
* `EpsilonEridani.simplyBlockedRingHom`: setting `V_i` to zero, as a ring homomorphism.
* `EpsilonEridani.simplyBlockedSpecialization`: coefficientwise specialization of `GC⁻` at `V_i = 0`.
* `EpsilonEridani.GridDiagram.simplyBlockedRectangles`: the empty, `X`-avoiding rectangles which also
  avoid the chosen `O`-marking.
* `EpsilonEridani.GridDiagram.simplyBlockedCoefficient`: the matrix coefficient of the specialized map.
* `EpsilonEridani.GridDiagram.simplyBlockedDifferential`: the map obtained from `GC⁻` by
  specializing `V_i` to zero.

## Main results

* `EpsilonEridani.simplyBlockedSpecialization_surjective` and
  `EpsilonEridani.exact_X_smul_simplyBlockedSpecialization`: specialization presents the specialized
  chain module as the quotient of `GC⁻` by the multiples of `V_i`, which
  `EpsilonEridani.X_smul_gridChainMinus_injective` says form a copy of `GC⁻`.
* `EpsilonEridani.GridDiagram.simplyBlockedCoefficient_eq_sum`: a matrix coefficient is the sum, over the
  rectangles which avoid the blocked `O`-marking, of the product of the variables of the other
  `O`-markings the rectangle covers.
* `EpsilonEridani.GridDiagram.simplyBlockedSpecialization_unblockedDifferential`: coefficientwise
  specialization intertwines the unblocked differential with the simply blocked map, so the latter
  really is the `V_i = 0` reduction of the former.

## References

The specialization and rectangle formula follow Ozsváth--Stipsicz--Szabó, *Grid Homology for
Knots and Links*, Chapter 4.6.
-/

public section

namespace EpsilonEridani

open MvPolynomial

/-- The chain module underlying the one-variable specialization, freely generated by grid states
over the polynomial semiring in the columns other than the blocked column `i`.  Its homology, for
a knot grid in characteristic two, is the simply blocked grid homology, which is not defined
here. -/
abbrev GridChainHat (R : Type*) [CommSemiring R] (n : ℕ) (i : Fin n) : Type _ :=
  GridChain (MvPolynomial {c : Fin n // c ≠ i} R) n

/-- Setting the blocked variable `V_i` to zero, as a ring homomorphism
`R[V₀, …, V_{n-1}] → R[V_c | c ≠ i]`. It is the homomorphism over which
`EpsilonEridani.simplyBlockedSpecialization` is semilinear. -/
noncomputable abbrev simplyBlockedRingHom {n : ℕ} (R : Type*) [CommSemiring R] (i : Fin n) :
    MvPolynomial (Fin n) R →+* MvPolynomial {c : Fin n // c ≠ i} R :=
  (MvPolynomial.killCompl (R := R) (f := (Subtype.val : {c : Fin n // c ≠ i} → Fin n))
    Subtype.val_injective).toRingHom

/-- The coefficient specialization is `MvPolynomial.killCompl`. -/
@[simp]
theorem simplyBlockedRingHom_apply {n : ℕ} (R : Type*) [CommSemiring R] (i : Fin n)
    (p : MvPolynomial (Fin n) R) :
    simplyBlockedRingHom R i p =
      MvPolynomial.killCompl (f := (Subtype.val : {c : Fin n // c ≠ i} → Fin n))
        Subtype.val_injective p :=
  by
    unfold simplyBlockedRingHom
    rfl

/-- The blocked variable specializes to zero.

Not a `simp` lemma: `EpsilonEridani.simplyBlockedRingHom_apply` and
`MvPolynomial.killCompl_X_of_notMem_range` already rewrite the left-hand side to `0`. -/
theorem simplyBlockedRingHom_X_eq_zero {n : ℕ} (R : Type*) [CommSemiring R] (i : Fin n) :
    simplyBlockedRingHom R i (MvPolynomial.X i) = 0 := by
  rw [simplyBlockedRingHom_apply]
  exact MvPolynomial.killCompl_X_of_notMem_range Subtype.val_injective (by simp)

/-- Coefficientwise specialization of an unblocked grid chain at `V_i = 0`.

This is semilinear over `MvPolynomial.killCompl`: specializing a polynomial multiple of a chain
specializes both the scalar and every coefficient. -/
noncomputable def simplyBlockedSpecialization {n : ℕ} (R : Type*) [CommSemiring R] (i : Fin n) :
    GridChainMinus R n →ₛₗ[simplyBlockedRingHom R i] GridChainHat R n i :=
  Finsupp.mapRange.linearMap (simplyBlockedRingHom R i).toSemilinearMap

/-- Specializing a grid chain applies `MvPolynomial.killCompl` to each coefficient. -/
@[simp]
theorem simplyBlockedSpecialization_apply {n : ℕ} (R : Type*) [CommSemiring R] (i : Fin n)
    (c : GridChainMinus R n) (x : GridState n) :
    simplyBlockedSpecialization R i c x =
      MvPolynomial.killCompl (f := Subtype.val) Subtype.val_injective (c x) := by
  rw [simplyBlockedSpecialization, Finsupp.mapRange.linearMap_apply, Finsupp.mapRange_apply,
    RingHom.coe_toSemilinearMap, simplyBlockedRingHom_apply]

/-- Specialization sends a single supported coefficient to the single supported specialized
coefficient. -/
@[simp]
theorem simplyBlockedSpecialization_single {n : ℕ} (R : Type*) [CommSemiring R] (i : Fin n)
    (x : GridState n) (a : MvPolynomial (Fin n) R) :
    simplyBlockedSpecialization R i (Finsupp.single x a) =
      Finsupp.single x
        (MvPolynomial.killCompl (f := Subtype.val) Subtype.val_injective a) := by
  classical
  rw [simplyBlockedSpecialization, Finsupp.mapRange.linearMap_apply, Finsupp.mapRange_single,
    RingHom.coe_toSemilinearMap, simplyBlockedRingHom_apply]

/-! ### Specialization as a quotient map -/

section Specialization

variable {n : ℕ} (R : Type*) [CommSemiring R] (i : Fin n)

/-- The coefficient specialization is surjective. -/
theorem simplyBlockedRingHom_surjective : Function.Surjective (simplyBlockedRingHom R i) :=
  fun p ↦ ⟨MvPolynomial.rename Subtype.val p, by simp⟩

/-- Specialization at `V_i = 0` is surjective: renaming the surviving variables back is a
section of it. -/
theorem simplyBlockedSpecialization_surjective :
    Function.Surjective (simplyBlockedSpecialization R i) := by
  intro g
  obtain ⟨f, hf⟩ := Finsupp.mapRange_surjective (simplyBlockedRingHom R i) (map_zero _)
    (simplyBlockedRingHom_surjective R i) g
  refine ⟨f, ?_⟩
  unfold simplyBlockedSpecialization
  exact hf

/-- Multiplication by the blocked variable `V_i` is injective on the unblocked grid chain
module. -/
theorem X_smul_gridChainMinus_injective :
    Function.Injective
      fun c : GridChainMinus R n => (MvPolynomial.X i : MvPolynomial (Fin n) R) • c :=
  (MvPolynomial.isRegular_X (R := R) (n := i)).left.isSMulRegular.finsupp

/-- Multiplication by `V_i` and coefficient specialization form an exact pair. -/
theorem exact_X_mul_simplyBlockedRingHom :
    Function.Exact (fun p : MvPolynomial (Fin n) R => MvPolynomial.X i * p)
      (simplyBlockedRingHom R i) := by
  have hrange : Set.range (Subtype.val : {c : Fin n // c ≠ i} → Fin n) = {i}ᶜ := by
    ext d
    simp
  intro p
  rw [simplyBlockedRingHom_apply,
    MvPolynomial.killCompl_eq_zero_iff_X_dvd Subtype.val_injective hrange]
  constructor <;> rintro ⟨q, hq⟩ <;> exact ⟨q, hq.symm⟩

/-- The chains killed by specialization at `V_i = 0` are exactly the multiples of `V_i`:
together with `EpsilonEridani.X_smul_gridChainMinus_injective` and
`EpsilonEridani.simplyBlockedSpecialization_surjective` this presents the specialized chain module as
the quotient of `GC⁻` by a copy of itself. -/
theorem exact_X_smul_simplyBlockedSpecialization :
    Function.Exact
      (fun c : GridChainMinus R n => (MvPolynomial.X i : MvPolynomial (Fin n) R) • c)
      (simplyBlockedSpecialization R i) := by
  have hmap :
      (fun c : GridChainMinus R n => (MvPolynomial.X i : MvPolynomial (Fin n) R) • c) =
        Finsupp.mapRange (fun p => MvPolynomial.X i * p) (mul_zero _) := by
    funext c
    ext x
    simp [Finsupp.smul_apply]
  intro c
  rw [Finsupp.ext_iff, hmap, Finsupp.range_mapRange]
  simp only [simplyBlockedSpecialization_apply, Finsupp.coe_zero, Pi.zero_apply,
    Set.mem_ofPred_eq]
  exact forall_congr' fun x => exact_X_mul_simplyBlockedRingHom R i (c x)

end Specialization

namespace GridDiagram

variable {n : ℕ} (G : GridDiagram n)
variable (R : Type*) [CommSemiring R]

/-- A rectangle covering the blocked `O`-marking has weight zero after specialization. -/
@[simp]
theorem killCompl_OMonomial_eq_zero_of_mem {i : Fin n} {r : GridRectangle n}
    (hi : i ∈ G.OColumns r) :
    MvPolynomial.killCompl (R := R) (f := Subtype.val)
      (Subtype.val_injective : Function.Injective
        (Subtype.val : {c : Fin n // c ≠ i} → Fin n))
      (G.OMonomial R r) = 0 := by
  rw [G.OMonomial_eq_monomial R]
  refine MvPolynomial.killCompl_monomial_eq_zero_of_notMem_range _ 1
    (a := i) ?_ ?_
  · rw [Finsupp.support_sum_eq_biUnion _ (by simp)]
    simpa using hi
  · rintro ⟨⟨c, hc⟩, hci⟩
    exact hc hci

/-- A rectangle avoiding the blocked `O`-marking keeps as its weight the product of the variables
of the other `O`-markings it covers. -/
@[simp]
theorem killCompl_OMonomial_eq_prod_of_notMem {i : Fin n} {r : GridRectangle n}
    (hi : i ∉ G.OColumns r) :
    MvPolynomial.killCompl (R := R) (f := Subtype.val)
      (Subtype.val_injective : Function.Injective
        (Subtype.val : {c : Fin n // c ≠ i} → Fin n)) (G.OMonomial R r) =
      ∏ c ∈ (G.OColumns r).subtype (· ≠ i), MvPolynomial.X c := by
  have hrename :
      MvPolynomial.rename (Subtype.val : {c : Fin n // c ≠ i} → Fin n)
          (∏ c ∈ (G.OColumns r).subtype (· ≠ i), MvPolynomial.X (R := R) c) =
        G.OMonomial R r := by
    rw [map_prod, G.OMonomial_eq_monomial R, MvPolynomial.monomial_sum_one]
    simp only [MvPolynomial.rename_X]
    simpa only [← MvPolynomial.X_pow_eq_monomial, pow_one] using
      Finset.prod_subtype_of_mem (s := G.OColumns r) (p := fun c : Fin n => c ≠ i)
        (MvPolynomial.X (R := R))
        (fun c hc (hci : c = i) => hi (hci ▸ hc))
  rw [← hrename, MvPolynomial.killCompl_rename_app]

/-- The rectangles counted after blocking column `i`: unblocked rectangles which do not cover
the `O`-marking in column `i`. -/
noncomputable def simplyBlockedRectangles (i : Fin n) (x y : GridState n) :
    Finset (GridRectangleBetween x y) :=
  (G.unblockedRectangles x y).filter fun r => i ∉ G.OColumns r.toGridRectangle

/-- Membership in the simply blocked rectangle set is emptiness, `X`-avoidance, and avoidance of
the `O`-marking in the selected column. -/
@[simp]
theorem mem_simplyBlockedRectangles (i : Fin n) {x y : GridState n}
    (r : GridRectangleBetween x y) :
    r ∈ G.simplyBlockedRectangles i x y ↔
      r.IsEmpty ∧ Disjoint r.toGridRectangle.coveredSquares G.XSet ∧
        (i, G.O i) ∉ r.toGridRectangle.coveredSquares := by
  rw [simplyBlockedRectangles, Finset.mem_filter, G.mem_unblockedRectangles,
    G.mem_OColumns]
  tauto

/-- Simply blocked rectangles are among those counted by the unblocked differential. -/
theorem simplyBlockedRectangles_subset_unblockedRectangles (i : Fin n) (x y : GridState n) :
    G.simplyBlockedRectangles i x y ⊆ G.unblockedRectangles x y :=
  Finset.filter_subset _ _

/-- There are no simply blocked rectangles from a grid state to itself. -/
@[simp]
theorem simplyBlockedRectangles_self (i : Fin n) (x : GridState n) :
    G.simplyBlockedRectangles i x x = ∅ := by
  simp [simplyBlockedRectangles]

/-- The matrix coefficient of the simply blocked map, obtained by specializing the
corresponding coefficient of `GC⁻`. -/
noncomputable def simplyBlockedCoefficient (i : Fin n) (x y : GridState n) :
    MvPolynomial {c : Fin n // c ≠ i} R :=
  MvPolynomial.killCompl (f := Subtype.val) Subtype.val_injective
    (G.unblockedCoefficient R x y)

/-- The simply blocked coefficient is the finite sum over the contributing rectangles.  Terms
covering the blocked marking disappear; each of the other terms is the product of the variables of
the remaining `O`-markings the rectangle covers. -/
theorem simplyBlockedCoefficient_eq_sum (i : Fin n) (x y : GridState n) :
    G.simplyBlockedCoefficient R i x y =
      ∑ r ∈ G.simplyBlockedRectangles i x y,
        ∏ c ∈ (G.OColumns r.toGridRectangle).subtype (· ≠ i), MvPolynomial.X c := by
  classical
  rw [simplyBlockedCoefficient, G.unblockedCoefficient_def R, map_sum,
    ← Finset.sum_subset (G.simplyBlockedRectangles_subset_unblockedRectangles i x y)]
  · refine Finset.sum_congr rfl fun r hr => ?_
    refine G.killCompl_OMonomial_eq_prod_of_notMem R ?_
    rw [G.mem_OColumns]
    exact ((G.mem_simplyBlockedRectangles i r).mp hr).2.2
  · intro r hr hri
    have hi : i ∈ G.OColumns r.toGridRectangle := by
      by_contra hi
      exact hri (Finset.mem_filter.mpr ⟨hr, hi⟩)
    exact G.killCompl_OMonomial_eq_zero_of_mem R hi

/-- The simply blocked map has no diagonal matrix coefficient. -/
@[simp]
theorem simplyBlockedCoefficient_self (i : Fin n) (x : GridState n) :
    G.simplyBlockedCoefficient R i x x = 0 := by
  simp [simplyBlockedCoefficient]

/-- The value of the simply blocked map on one grid-state generator. -/
noncomputable def simplyBlockedDifferentialOnGenerator (i : Fin n) (x : GridState n) :
    GridChainHat R n i :=
  Finsupp.equivFunOnFinite.symm (G.simplyBlockedCoefficient R i x)

/-- The `y`-coefficient of the simply blocked map on the generator `x`. -/
@[simp]
theorem simplyBlockedDifferentialOnGenerator_apply (i : Fin n) (x y : GridState n) :
    G.simplyBlockedDifferentialOnGenerator R i x y = G.simplyBlockedCoefficient R i x y :=
  congrFun (Finsupp.coe_equivFunOnFinite_symm (G.simplyBlockedCoefficient R i x)) y

/-- The simply blocked map of a generator is supported on its column transpositions. -/
theorem simplyBlockedDifferentialOnGenerator_support_subset (i : Fin n) (x : GridState n) :
    (G.simplyBlockedDifferentialOnGenerator R i x).support ⊆ x.columnSwapNeighbors := by
  intro y hy
  rw [Finsupp.mem_support_iff, simplyBlockedDifferentialOnGenerator_apply] at hy
  apply G.unblockedDifferentialOnGenerator_support_subset R x
  rw [Finsupp.mem_support_iff, G.unblockedDifferentialOnGenerator_apply R]
  intro hzero
  rw [simplyBlockedCoefficient, hzero, map_zero] at hy
  exact hy rfl

/-- Specializing the unblocked differential of a generator gives its simply blocked row. -/
@[simp]
theorem simplyBlockedSpecialization_unblockedDifferentialOnGenerator (i : Fin n)
    (x : GridState n) :
    simplyBlockedSpecialization R i (G.unblockedDifferentialOnGenerator R x) =
      G.simplyBlockedDifferentialOnGenerator R i x := by
  apply Finsupp.ext
  intro y
  rw [simplyBlockedSpecialization_apply,
    G.simplyBlockedDifferentialOnGenerator_apply R i x y,
    G.unblockedDifferentialOnGenerator_apply R x y, simplyBlockedCoefficient]

/-- The linear map obtained from the `GC⁻` differential by setting `V_i = 0`.  For a knot grid
over a coefficient semiring of characteristic two it is the simply blocked differential;
outside characteristic two it is only the unsigned candidate map, since sign correction uses
additive inverses and so needs a commutative coefficient ring.  A link with multiple components
requires one blocked marking on each component instead. -/
noncomputable def simplyBlockedDifferential (i : Fin n) :
    GridChainHat R n i →ₗ[MvPolynomial {c : Fin n // c ≠ i} R] GridChainHat R n i :=
  Finsupp.linearCombination (MvPolynomial {c : Fin n // c ≠ i} R)
    (G.simplyBlockedDifferentialOnGenerator R i)

/-- The simply blocked map sends a single generator to its rectangle-weight row. -/
@[simp]
theorem simplyBlockedDifferential_single (i : Fin n) (x : GridState n) :
    G.simplyBlockedDifferential R i (Finsupp.single x 1) =
      G.simplyBlockedDifferentialOnGenerator R i x := by
  simp [simplyBlockedDifferential]

/-- The simply blocked map is the finite sum of its generator rows over the support of
a chain. -/
theorem simplyBlockedDifferential_apply (i : Fin n) (c : GridChainHat R n i) :
    G.simplyBlockedDifferential R i c =
      c.sum fun x a => a • G.simplyBlockedDifferentialOnGenerator R i x := by
  rw [simplyBlockedDifferential, Finsupp.linearCombination_apply]

/-- The coefficient formula for the simply blocked map on an arbitrary chain. -/
@[simp]
theorem simplyBlockedDifferential_apply_apply (i : Fin n)
    (c : GridChainHat R n i) (y : GridState n) :
    G.simplyBlockedDifferential R i c y =
      c.sum fun x a => a * G.simplyBlockedCoefficient R i x y := by
  rw [G.simplyBlockedDifferential_apply R i c]
  simp [Finsupp.sum_apply]

private theorem simplyBlockedSpecialization_unblockedDifferential_single (i : Fin n)
    (x : GridState n) (a : MvPolynomial (Fin n) R) :
    simplyBlockedSpecialization R i
        (G.unblockedDifferential R (Finsupp.single x a)) =
      G.simplyBlockedDifferential R i
        (simplyBlockedSpecialization R i (Finsupp.single x a)) := by
  rw [simplyBlockedSpecialization_single]
  nth_rewrite 1 [← Finsupp.smul_single_one x a]
  rw [map_smul, map_smulₛₗ,
    G.unblockedDifferential_single R x,
    G.simplyBlockedSpecialization_unblockedDifferentialOnGenerator R i x,
    ← Finsupp.smul_single_one x
      (MvPolynomial.killCompl (f := Subtype.val) Subtype.val_injective a),
    map_smul, G.simplyBlockedDifferential_single R i x]
  rw [simplyBlockedRingHom_apply]

/-- Coefficientwise specialization intertwines the unblocked and simply blocked maps. -/
@[simp]
theorem simplyBlockedSpecialization_unblockedDifferential (i : Fin n)
    (c : GridChainMinus R n) :
    simplyBlockedSpecialization R i (G.unblockedDifferential R c) =
      G.simplyBlockedDifferential R i (simplyBlockedSpecialization R i c) := by
  induction c using Finsupp.induction with
  | zero =>
      rw [(G.unblockedDifferential R).map_zero,
        (simplyBlockedSpecialization R i).map_zero,
        (G.simplyBlockedDifferential R i).map_zero]
  | single_add x a c _ _ ih =>
      rw [(G.unblockedDifferential R).map_add, (simplyBlockedSpecialization R i).map_add,
        (simplyBlockedSpecialization R i).map_add,
        (G.simplyBlockedDifferential R i).map_add, ih,
        G.simplyBlockedSpecialization_unblockedDifferential_single R i x a]

end GridDiagram

end EpsilonEridani
