/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.Analysis.Semigroups.Generator.Basic
public import EpsilonEridani.Analysis.Semigroups.GrowthBound
public import EpsilonEridani.Analysis.Semigroups.Generator.Uniqueness

/-!
# The identity strongly continuous semigroup

This file records the identity C₀-semigroup, equivalently the semigroup generated by the
zero bounded operator. It supplies the smallest concrete example for the bounded-generator
acceptance examples in the one-parameter-semigroups roadmap. Conversely, uniqueness of the
semigroup generated by an operator identifies every C₀-semigroup with vanishing generator with
this one (`StronglyContinuousSemigroup.eq_id_of_generator_eq_zero`).

## References
This is the zero-generator case of the standard uniformly continuous semigroup
`S(t) = exp(tA)`.
-/

public section

noncomputable section

open scoped NNReal Topology

namespace EpsilonEridani.Semigroups

variable (X : Type*) [NormedAddCommGroup X] [NormedSpace ℝ X]

namespace StronglyContinuousSemigroup

/-- The identity C₀-semigroup `S(t) = id`, generated by the zero operator. -/
def id : StronglyContinuousSemigroup X where
  toFun _ := ContinuousLinearMap.id ℝ X
  map_zero' := rfl
  map_add' _ _ := by
    ext x
    rfl
  continuousAt_zero' x := by
    simpa using (continuous_const : Continuous fun _ : ℝ≥0 => x).continuousAt

variable {X}

/-- The identity C₀-semigroup is constantly the identity operator. -/
@[simp]
theorem id_apply (t : ℝ≥0) : (StronglyContinuousSemigroup.id X) t = ContinuousLinearMap.id ℝ X :=
  by
    rw [StronglyContinuousSemigroup.id]
    rfl

/-- Pointwise form of `StronglyContinuousSemigroup.id_apply`. -/
theorem id_apply_apply (t : ℝ≥0) (x : X) : (StronglyContinuousSemigroup.id X) t x = x := by
  rw [id_apply]
  exact ContinuousLinearMap.id_apply x

end StronglyContinuousSemigroup

namespace ContractionSemigroup

/-- The identity contraction semigroup. -/
def id : ContractionSemigroup X where
  toStronglyContinuousSemigroup := StronglyContinuousSemigroup.id X
  contracting _ := by
    -- The contraction field exposes the raw `toFun`, which is definitionally the identity
    -- operator; no rewrite lemma reaches through the structure projection, so `change`
    -- restates the goal for `ContinuousLinearMap.norm_id_le`.
    change ‖ContinuousLinearMap.id ℝ X‖ ≤ 1
    exact ContinuousLinearMap.norm_id_le

variable {X}

/-- The identity contraction semigroup is constantly the identity operator. -/
@[simp]
theorem id_apply (t : ℝ≥0) : (ContractionSemigroup.id X) t = ContinuousLinearMap.id ℝ X :=
  by
    rw [ContractionSemigroup.id]
    rfl

/-- Pointwise form of `ContractionSemigroup.id_apply`. -/
theorem id_apply_apply (t : ℝ≥0) (x : X) : (ContractionSemigroup.id X) t x = x := by
  rw [id_apply]
  exact ContinuousLinearMap.id_apply x

/-- The C₀-semigroup underlying the identity contraction semigroup. -/
@[simp]
theorem id_toStronglyContinuousSemigroup :
    (ContractionSemigroup.id X).toStronglyContinuousSemigroup =
      StronglyContinuousSemigroup.id X :=
  by
    rw [ContractionSemigroup.id]

end ContractionSemigroup

namespace StronglyContinuousSemigroup

variable {X}

/-- The identity semigroup has the contraction growth bound `(0, 1)`. -/
theorem id_hasGrowthBound : (StronglyContinuousSemigroup.id X).HasGrowthBound 0 1 := by
  rw [← ContractionSemigroup.id_toStronglyContinuousSemigroup]
  exact (ContractionSemigroup.id X).hasGrowthBound

/-- The difference quotient `(S t x - x)/t` of the identity semigroup is identically zero,
hence tends to `0` as `t → 0⁺`. -/
private theorem id_genQuot_tendsto (x : X) :
    Filter.Tendsto (fun t => (1 / t) • ((StronglyContinuousSemigroup.id X).realOperator t x - x))
      (nhdsWithin 0 (Set.Ioi 0)) (nhds 0) := by
  refine (tendsto_const_nhds : Filter.Tendsto (fun _ : ℝ => (0 : X))
    (nhdsWithin 0 (Set.Ioi 0)) (nhds 0)).congr' ?_
  filter_upwards [self_mem_nhdsWithin] with t ht
  have ht_coe : ((t.toNNReal : ℝ) = t) := Real.coe_toNNReal t ht.le
  rw [← ht_coe, StronglyContinuousSemigroup.realOperator_coe, id_apply_apply, sub_self,
    smul_zero]

/-- Every vector lies in the generator domain of the identity semigroup. -/
theorem mem_id_domain (x : X) :
    x ∈ (StronglyContinuousSemigroup.id X).domain :=
  ((StronglyContinuousSemigroup.id X).generator_eq_toPMap_top_of_forall_tendsto 0
    (by simpa using id_genQuot_tendsto (X := X))).1.ge trivial

/-- The generator domain of the identity semigroup is all of the space. -/
@[simp]
theorem id_domain_eq_top : (StronglyContinuousSemigroup.id X).domain = ⊤ :=
  ((StronglyContinuousSemigroup.id X).generator_eq_toPMap_top_of_forall_tendsto 0
    (by simpa using id_genQuot_tendsto (X := X))).1

/-- The generator of the identity semigroup is the zero operator. -/
@[simp]
theorem id_generator_eq_zero : (StronglyContinuousSemigroup.id X).generator = 0 := by
  rw [((StronglyContinuousSemigroup.id X).generator_eq_toPMap_top_of_forall_tendsto 0
    (by simpa using id_genQuot_tendsto (X := X))).2]
  rfl

/-- A strongly continuous semigroup whose generator vanishes is the identity semigroup. -/
theorem eq_id_of_generator_eq_zero [CompleteSpace X] {S : StronglyContinuousSemigroup X}
    (h : S.generator = 0) : S = StronglyContinuousSemigroup.id X :=
  eq_of_generator_eq (h.trans id_generator_eq_zero.symm)

end StronglyContinuousSemigroup

end EpsilonEridani.Semigroups

end
