/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

-- `EpsilonEridani.Algebra.BrauerGroup.Quaternion` is imported publicly: `EpsilonEridani.BrauerGroup.mk`,
-- `EpsilonEridani.CSA.of` and `ℍ[ℝ]` occur in every statement below, and it supplies
-- `EpsilonEridani.Quaternion.orderOf_mk_eq_two`, which is what turns the generation statement into the
-- cardinality `2`. It re-exports the whole Brauer-group stack.
public import EpsilonEridani.Algebra.BrauerGroup.Quaternion
-- `Mathlib.GroupTheory.SpecificGroups.Cyclic` is imported publicly because
-- `Multiplicative (ZMod 2)` occurs in the isomorphism below, and `zmodMulEquivOfGenerator` is
-- what builds it.
public import Mathlib.GroupTheory.SpecificGroups.Cyclic
-- Non-public: Frobenius' theorem and the division-algebra representatives are what the proof of
-- the two-element classification runs on, and neither occurs in a statement.
import EpsilonEridani.Algebra.BrauerGroup.Division
import EpsilonEridani.Algebra.CentralSimple.Real

/-!
# The Brauer group of the reals is `ℤ/2`

`EpsilonEridani/Algebra/BrauerGroup/Quaternion.lean` shows that the Brauer class of `ℍ[ℝ]` has order `2`.
This file shows that it is the only class besides the identity, so `BrauerGroup ℝ` is cyclic of
order `2`.

The input is Frobenius' theorem, `EpsilonEridani.nonempty_algEquiv_real_or_quaternion`: a
finite-dimensional central division algebra over `ℝ` is `ℝ` or `ℍ[ℝ]`. Every Brauer class has such
a representative (`EpsilonEridani.BrauerGroup.exists_eq_mk_centralDivisionRing`), and the class of `ℝ` is
the identity, so there are at most the two classes already known. They are distinct by
`EpsilonEridani.Quaternion.mk_ne_one`, so `[ℍ[ℝ]]` generates a group of exactly two elements, and
Mathlib's `zmodMulEquivOfGenerator` names the resulting isomorphism.

## Main results

* `EpsilonEridani.Quaternion.eq_one_or_eq_mk`: **every real Brauer class is the identity or the class of
  `ℍ[ℝ]`.**
* `EpsilonEridani.Quaternion.zpowers_mk_eq_top`: the class of `ℍ[ℝ]` generates `BrauerGroup ℝ`.
* `EpsilonEridani.Quaternion.card_brauerGroup_eq_two`: `BrauerGroup ℝ` has exactly two elements.
* `EpsilonEridani.Quaternion.brauerGroupMulEquiv`: **`BrauerGroup ℝ ≃* Multiplicative (ZMod 2)`**, the
  summit of the real base field target, sending the class of `ℍ[ℝ]` to the generator.

## References

This is the "real base field" target of Layer 6 of the
[semisimple algebras roadmap](https://github.com/EpsilonEridaniProject/EpsilonEridaniRoadmap/blob/main/EpsilonEridaniRoadmap/RepresentationTheory/SemisimpleAlgebras/README.md):
"`BrauerGroup ℝ ≃ ℤ/2`, generated by the class of the Hamilton quaternions `ℍ[ℝ]`". See P. Gille,
T. Szamuely, *Central Simple Algebras and Galois Cohomology*, CUP (2006), §1.1 and §2.4.
-/

public section

open scoped Quaternion

namespace EpsilonEridani

namespace Quaternion

/-- **Every Brauer class over `ℝ` is the identity or the class of the real quaternions.**

The class has a central division-algebra representative, which by Frobenius' theorem is `ℝ` or
`ℍ[ℝ]`; the class of `ℝ` is the identity. -/
theorem eq_one_or_eq_mk (x : BrauerGroup.{0, 0} ℝ) :
    x = 1 ∨ x = BrauerGroup.mk (CSA.of ℝ ℍ[ℝ]) := by
  obtain ⟨D, hring, halg, hcentral, hfinite, hx⟩ :=
    BrauerGroup.exists_eq_mk_centralDivisionRing ℝ x
  let _ : DivisionRing D := hring
  let _ : Algebra ℝ D := halg
  let _ : Algebra.IsCentral ℝ D := hcentral
  let _ : FiniteDimensional ℝ D := hfinite
  subst hx
  rcases nonempty_algEquiv_real_or_quaternion D with hD | hD
  · exact Or.inl <| by
      rw [BrauerGroup.mk_eq_mk_of_algEquiv (B := CSA.base ℝ) hD.some, BrauerGroup.mk_base]
  · exact Or.inr (BrauerGroup.mk_eq_mk_of_algEquiv (B := CSA.of ℝ ℍ[ℝ]) hD.some)

/-- **The Brauer class of `ℍ[ℝ]` generates the Brauer group of `ℝ`.** -/
theorem zpowers_mk_eq_top :
    Subgroup.zpowers (BrauerGroup.mk (CSA.of ℝ ℍ[ℝ])) = (⊤ : Subgroup (BrauerGroup.{0, 0} ℝ)) :=
  eq_top_iff.2 fun x _ ↦ by
    rcases eq_one_or_eq_mk x with rfl | rfl
    · exact one_mem _
    · exact Subgroup.mem_zpowers _

/-- **The Brauer group of `ℝ` has exactly two elements.** It is generated by the class of `ℍ[ℝ]`,
whose order is `2`. -/
@[simp]
theorem card_brauerGroup_eq_two : Nat.card (BrauerGroup.{0, 0} ℝ) = 2 := by
  rw [← Subgroup.card_top (G := BrauerGroup.{0, 0} ℝ), ← zpowers_mk_eq_top, Nat.card_zpowers,
    orderOf_mk_eq_two]

/-- **The Brauer group of the reals is `ℤ/2`**, generated by the class of the Hamilton quaternions.

This is the summit of the real base field target: alongside
`EpsilonEridani.subsingleton_brauerGroup_of_isAlgClosed` and
`EpsilonEridani.subsingleton_brauerGroup_of_finite`, it is the first Brauer group computed in Tau Ceti
that is nontrivial. The isomorphism is characterised by
`EpsilonEridani.Quaternion.brauerGroupMulEquiv_mk` and its inverse by
`EpsilonEridani.Quaternion.brauerGroupMulEquiv_symm_ofAdd_one`. -/
noncomputable def brauerGroupMulEquiv : BrauerGroup.{0, 0} ℝ ≃* Multiplicative (ZMod 2) :=
  (zmodMulEquivOfGenerator (fun x ↦ zpowers_mk_eq_top ▸ Subgroup.mem_top x)
    card_brauerGroup_eq_two).symm

/-- **The characterisation of `EpsilonEridani.Quaternion.brauerGroupMulEquiv`**: it sends the Brauer class
of `ℍ[ℝ]` to `Multiplicative.ofAdd 1`, the generator of `Multiplicative (ZMod 2)`. Since that class
generates (`EpsilonEridani.Quaternion.zpowers_mk_eq_top`), this determines the isomorphism. -/
@[simp]
theorem brauerGroupMulEquiv_mk :
    brauerGroupMulEquiv (BrauerGroup.mk (CSA.of ℝ ℍ[ℝ])) = Multiplicative.ofAdd 1 :=
  zmodMulEquivOfGenerator_symm_apply_generator _ _

/-- **The inverse of `EpsilonEridani.Quaternion.brauerGroupMulEquiv` sends the generator
`Multiplicative.ofAdd 1` of `Multiplicative (ZMod 2)` back to the Brauer class of `ℍ[ℝ]`**, the
other half of the characterisation in `EpsilonEridani.Quaternion.brauerGroupMulEquiv_mk`. -/
@[simp]
theorem brauerGroupMulEquiv_symm_ofAdd_one :
    brauerGroupMulEquiv.symm (Multiplicative.ofAdd 1) = BrauerGroup.mk (CSA.of ℝ ℍ[ℝ]) := by
  rw [← brauerGroupMulEquiv_mk, MulEquiv.symm_apply_apply]

end Quaternion

/-! ### Worked examples -/

section Examples

/-- **The Brauer group of `ℝ` is not the trivial group**, in contrast with the two Brauer groups
already computed: `EpsilonEridani.subsingleton_brauerGroup_of_isAlgClosed` for `ℂ` and
`EpsilonEridani.subsingleton_brauerGroup_of_finite` for a finite field. -/
example : Nat.card (BrauerGroup.{0, 0} ℝ) ≠ 1 := by
  rw [Quaternion.card_brauerGroup_eq_two]
  norm_num

/-- **The Brauer class of an arbitrary central simple `ℝ`-algebra is the identity or the class of
`ℍ[ℝ]`.** The classification is stated for classes, so it applies to an arbitrary representative
and not only to a division algebra. -/
example (A : CSA.{0, 0} ℝ) :
    BrauerGroup.mk A = 1 ∨ BrauerGroup.mk A = BrauerGroup.mk (CSA.of ℝ ℍ[ℝ]) :=
  Quaternion.eq_one_or_eq_mk _

end Examples

end EpsilonEridani
