/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.Group.Action.End
public import Mathlib.Algebra.Group.Subgroup.ZPowers.Basic
public import Mathlib.Data.Fintype.Perm
public import Mathlib.Data.Set.Card
public import Mathlib.GroupTheory.Complement
public import Mathlib.GroupTheory.FixedPointFree
public import Mathlib.GroupTheory.GroupAction.ConjAct
public import Mathlib.GroupTheory.GroupAction.Defs
public import Mathlib.GroupTheory.SpecificGroups.Alternating
public import EpsilonEridani.GroupTheory.TrivialIntersection

/-!
# The two subgroups of the symmetric group on three points

`Equiv.Perm (Fin 3)` is the symmetric group `S₃`, and it has two kinds of proper nontrivial
subgroup. The stabilizer of a point `a` is the two-element subgroup generated by the transposition
of the two other points, which are `a + 1` and `a + 2` whichever `a` is; this file identifies that
stabilizer -- by membership, as a set, as a cyclic subgroup and by its order -- and records that
it is not normal, conjugating its transposition by one that moves `a` off the stabilizer. The
alternating subgroup `A₃` is the other one, and what is recorded of it here is that it has order
three and that nothing outside it centralizes it, so that `S₃` is as far from abelian along `A₃`
as it could be.  The two sit together as a semidirect decomposition `S₃ = A₃ ⋊ ⟨(a+1 a+2)⟩` whose
complement acts on `A₃` without nonidentity fixed points, which exhibits the stabilizer as a
Frobenius complement and `S₃` as the smallest Frobenius group.

All the facts about `Fin 3` that the arguments need are settled by `decide` over the six
permutations.

## Main statements

* `Equiv.Perm.fin_three_cases`: every permutation of three points is the identity, one of the
  three transpositions, or one of the two rotations.
* `EpsilonEridani.mem_stabilizer_perm_fin_three_iff`: a permutation of three points fixes `a` exactly
  when it is the identity or the transposition of the other two points.
* `EpsilonEridani.coe_stabilizer_perm_fin_three`: the same, as an equality of sets.
* `EpsilonEridani.stabilizer_perm_fin_three_eq_zpowers`: the stabilizer is the subgroup generated by that
  transposition.
* `EpsilonEridani.card_stabilizer_perm_fin_three`: it has order two.
* `EpsilonEridani.not_normal_stabilizer_perm_fin_three`: it is not normal.
* `EpsilonEridani.sign_eq_one_or_card_fixedPoints_eq_one_perm_fin_three`: a permutation of three points
  is even or fixes exactly one point.
* `EpsilonEridani.sign_mul_card_fixedPoints_fin_three`: the ring-valued form of that disjunction, the
  sign times the number of fixed points as their sum less one.
* `EpsilonEridani.card_alternatingGroup_fin_three`: the alternating subgroup has order three.
* `EpsilonEridani.centralizer_alternatingGroup_fin_three_le`: only the alternating subgroup centralizes
  the alternating subgroup.
* `EpsilonEridani.fixedPointFree_conjNormal_alternatingGroup_fin_three`: a point stabilizer acts on the
  alternating subgroup by conjugation without nonidentity fixed points, a transposition inverting
  each of the two rotations.
* `EpsilonEridani.isComplement'_alternatingGroup_stabilizer_perm_fin_three`: the two subgroups are
  complementary, `S₃ = A₃ ⋊ ⟨(a+1 a+2)⟩`.
* `EpsilonEridani.isTISubgroup_stabilizer_perm_fin_three`: a point stabilizer is a trivial-intersection
  subgroup.
* `EpsilonEridani.isFrobeniusComplement_stabilizer_perm_fin_three`: `S₃` is a Frobenius group with
  complement a point stabilizer.
-/

public section

namespace Equiv.Perm

/-- The six permutations of `Fin 3`: the identity, the three transpositions, and the two
rotations. -/
theorem fin_three_cases (ρ : Equiv.Perm (Fin 3)) :
    ρ = 1 ∨ ρ = Equiv.swap 0 1 ∨ ρ = Equiv.swap 1 2 ∨ ρ = Equiv.swap 0 2 ∨
      ρ = finRotate 3 ∨ ρ = (finRotate 3)⁻¹ := by
  revert ρ
  decide

end Equiv.Perm

namespace EpsilonEridani

/-- **A permutation of three points fixing `a` is the identity or the transposition of the other
two points.** Written with `a + 1` and `a + 2` so that the statement is uniform in `a`: those are
the two points other than `a`, whichever `a` is. -/
theorem mem_stabilizer_perm_fin_three_iff (a : Fin 3) (σ : Equiv.Perm (Fin 3)) :
    σ ∈ MulAction.stabilizer (Equiv.Perm (Fin 3)) a ↔
      σ = 1 ∨ σ = Equiv.swap (a + 1) (a + 2) := by
  simp only [MulAction.mem_stabilizer_iff, Equiv.Perm.smul_def]
  revert σ
  revert a
  decide

/-- The point stabilizer of `S₃`, as a set: the identity and one transposition. -/
theorem coe_stabilizer_perm_fin_three (a : Fin 3) :
    (MulAction.stabilizer (Equiv.Perm (Fin 3)) a : Set (Equiv.Perm (Fin 3)))
      = {1, Equiv.swap (a + 1) (a + 2)} :=
  Set.ext fun σ => mem_stabilizer_perm_fin_three_iff a σ

/-- **The point stabilizer of `S₃` is generated by a transposition**: it is the roadmap's
`⟨(1 2)⟩`, written at the point it stabilizes. -/
theorem stabilizer_perm_fin_three_eq_zpowers (a : Fin 3) :
    MulAction.stabilizer (Equiv.Perm (Fin 3)) a
      = Subgroup.zpowers (Equiv.swap (a + 1) (a + 2)) := by
  have hmem : Equiv.swap (a + 1) (a + 2) ∈ MulAction.stabilizer (Equiv.Perm (Fin 3)) a :=
    (mem_stabilizer_perm_fin_three_iff a _).mpr (Or.inr rfl)
  refine le_antisymm (fun σ hσ => ?_) (Subgroup.zpowers_le.mpr hmem)
  rcases (mem_stabilizer_perm_fin_three_iff a σ).mp hσ with rfl | rfl
  · exact one_mem _
  · exact Subgroup.mem_zpowers _

/-- The transposition of the two points other than `a` is not the identity. -/
private theorem one_ne_swap_perm_fin_three (a : Fin 3) :
    (1 : Equiv.Perm (Fin 3)) ≠ Equiv.swap (a + 1) (a + 2) := by
  revert a
  decide

/-- **The point stabilizer of `S₃` has order two**: it is the two-element subgroup generated by a
transposition, the roadmap's `⟨(1 2)⟩`. -/
theorem card_stabilizer_perm_fin_three (a : Fin 3) :
    Nat.card (MulAction.stabilizer (Equiv.Perm (Fin 3)) a) = 2 := by
  rw [← SetLike.coe_sort_coe, Nat.card_coe_set_eq, coe_stabilizer_perm_fin_three,
    Set.ncard_pair (one_ne_swap_perm_fin_three a)]

/-- Conjugating the transposition fixing `a` by a transposition that moves `a` leaves the
stabilizer: the conjugate carries `a` elsewhere. -/
private theorem conj_swap_notMem_stabilizer_perm_fin_three (a : Fin 3) :
    Equiv.swap a (a + 1) * Equiv.swap (a + 1) (a + 2) * (Equiv.swap a (a + 1))⁻¹ ∉
      MulAction.stabilizer (Equiv.Perm (Fin 3)) a := by
  rw [mem_stabilizer_perm_fin_three_iff]
  revert a
  decide

/-- **The point stabilizer of `S₃` is not normal**: conjugating its transposition by a
transposition moving `a` produces a permutation that no longer fixes `a`. -/
theorem not_normal_stabilizer_perm_fin_three (a : Fin 3) :
    ¬ (MulAction.stabilizer (Equiv.Perm (Fin 3)) a).Normal := by
  intro hnormal
  have hmem : Equiv.swap (a + 1) (a + 2) ∈ MulAction.stabilizer (Equiv.Perm (Fin 3)) a :=
    (mem_stabilizer_perm_fin_three_iff a _).mpr (Or.inr rfl)
  exact conj_swap_notMem_stabilizer_perm_fin_three a
    (hnormal.conj_mem _ hmem (Equiv.swap a (a + 1)))

/-- **An odd permutation of three points fixes exactly one point**, stated as a disjunction: a
permutation of three points is either even or has exactly one fixed point. The two cases are
exhaustive and disjoint -- the even permutations are the identity, fixing all three points, and
the two three-cycles, fixing none, while the three transpositions are odd and fix exactly one --
so the disjunction is what a case split on the parity consumes. -/
theorem sign_eq_one_or_card_fixedPoints_eq_one_perm_fin_three (σ : Equiv.Perm (Fin 3)) :
    Equiv.Perm.sign σ = 1 ∨ Nat.card {x : Fin 3 // σ • x = x} = 1 := by
  have h : ∀ τ : Equiv.Perm (Fin 3), Equiv.Perm.sign τ = 1 ∨
      ({x : Fin 3 | τ x = x} : Finset (Fin 3)).card = 1 := by decide
  rcases h σ with h | h
  · exact Or.inl h
  · refine Or.inr ?_
    rw [Nat.card_eq_fintype_card, Fintype.card_subtype]
    simpa only [Equiv.Perm.smul_def] using h

/-- **The sign of a permutation of three points against its number of fixed points**: writing `F`
for the number of points that `σ` fixes, `sgn σ · F = sgn σ + F - 1` in any ring. This is the
ring-valued form of `EpsilonEridani.sign_eq_one_or_card_fixedPoints_eq_one_perm_fin_three`, and it is what
turns the product of the sign character of `S₃` with a permutation character into a sum. -/
theorem sign_mul_card_fixedPoints_fin_three {k : Type*} [NonAssocRing k] (σ : Equiv.Perm (Fin 3)) :
    ((Equiv.Perm.sign σ : ℤ) : k) * (Nat.card {x : Fin 3 // σ • x = x} : k)
      = ((Equiv.Perm.sign σ : ℤ) : k) + (Nat.card {x : Fin 3 // σ • x = x} : k) - 1 := by
  rcases sign_eq_one_or_card_fixedPoints_eq_one_perm_fin_three σ with h | h <;> rw [h] <;> simp

/-- **The alternating subgroup of `S₃` has order three**: half of `3! = 6`. -/
theorem card_alternatingGroup_fin_three : Nat.card (alternatingGroup (Fin 3)) = 3 := by
  rw [nat_card_alternatingGroup, Nat.card_eq_fintype_card, Fintype.card_fin]
  rfl

/-- **Nothing outside `A₃` centralizes `A₃`.** A permutation commuting with every even permutation
of three points is itself even; equivalently, the centralizer of the alternating subgroup is the
alternating subgroup, since an abelian subgroup centralizes itself. This is the failure of
commutation that makes a faithful linear character of `A₃` induce irreducibly to `S₃`. -/
theorem centralizer_alternatingGroup_fin_three_le :
    Subgroup.centralizer (alternatingGroup (Fin 3) : Set (Equiv.Perm (Fin 3)))
      ≤ alternatingGroup (Fin 3) := by
  intro g hg
  rw [Subgroup.mem_centralizer_iff] at hg
  revert hg
  revert g
  simp only [SetLike.mem_coe, Equiv.Perm.mem_alternatingGroup]
  decide

/-- **A point stabilizer of `S₃` acts on `A₃` without nonidentity fixed points**: conjugation by
a nonidentity element of the stabilizer of `a` fixes no nonidentity element of the alternating
subgroup.  This is the fixed-point hypothesis of
`EpsilonEridani.isTISubgroup_of_isComplement'_of_fixedPointFree`. -/
theorem fixedPointFree_conjNormal_alternatingGroup_fin_three (a : Fin 3) :
    ∀ h : MulAction.stabilizer (Equiv.Perm (Fin 3)) a, h ≠ 1 →
      MonoidHom.FixedPointFree
        (MulAut.conjNormal (h : Equiv.Perm (Fin 3)) : MulAut (alternatingGroup (Fin 3))) := by
  -- the stabilizer of `a` is `{1, (a+1 a+2)}`, and that transposition inverts each of the two
  -- rotations, neither of which is its own inverse
  have key : ∀ b : Fin 3, ∀ m : Equiv.Perm (Fin 3), Equiv.Perm.sign m = 1 →
      Equiv.swap (b + 1) (b + 2) * m * (Equiv.swap (b + 1) (b + 2))⁻¹ = m → m = 1 := by decide
  intro h hh1 n hfix
  have hfix' : (h : Equiv.Perm (Fin 3)) * (n : Equiv.Perm (Fin 3)) * (h : Equiv.Perm (Fin 3))⁻¹
      = (n : Equiv.Perm (Fin 3)) :=
    (MulAut.conjNormal_apply _ _).symm.trans (congrArg Subtype.val hfix)
  refine Subtype.ext ?_
  rcases (mem_stabilizer_perm_fin_three_iff a _).mp h.2 with h1 | h1
  · exact absurd (Subtype.ext h1 : h = 1) hh1
  · rw [h1] at hfix'
    exact key a n (Equiv.Perm.mem_alternatingGroup.mp n.2) hfix'

/-- **`A₃` is a normal complement to a point stabilizer in `S₃`**: the two have orders `3` and `2`,
which are coprime and multiply to `3! = 6`. -/
theorem isComplement'_alternatingGroup_stabilizer_perm_fin_three (a : Fin 3) :
    (alternatingGroup (Fin 3)).IsComplement'
      (MulAction.stabilizer (Equiv.Perm (Fin 3)) a) := by
  refine Subgroup.isComplement'_of_coprime ?_ ?_ <;>
    rw [card_alternatingGroup_fin_three, card_stabilizer_perm_fin_three]
  · rw [Nat.card_eq_fintype_card, Fintype.card_perm, Fintype.card_fin]
    decide
  · decide

/-- **A point stabilizer of `S₃` is a trivial-intersection subgroup**, by the fixed-point-free
action of `EpsilonEridani.isTISubgroup_of_isComplement'_of_fixedPointFree` on the alternating
complement. -/
theorem isTISubgroup_stabilizer_perm_fin_three (a : Fin 3) :
    IsTISubgroup (MulAction.stabilizer (Equiv.Perm (Fin 3)) a) :=
  isTISubgroup_of_isComplement'_of_fixedPointFree
    (isComplement'_alternatingGroup_stabilizer_perm_fin_three a)
    (fixedPointFree_conjNormal_alternatingGroup_fin_three a)

/-- **`S₃` is a Frobenius group with complement a point stabilizer.**  Properness and
nontriviality come from the stabilizer not being normal, which `⊥` and `⊤` both are. -/
theorem isFrobeniusComplement_stabilizer_perm_fin_three (a : Fin 3) :
    IsFrobeniusComplement (MulAction.stabilizer (Equiv.Perm (Fin 3)) a) := by
  refine isFrobeniusComplement_of_isComplement'_of_fixedPointFree
    (isComplement'_alternatingGroup_stabilizer_perm_fin_three a) ?_ ?_
    (fixedPointFree_conjNormal_alternatingGroup_fin_three a)
  · intro hbot
    refine not_normal_stabilizer_perm_fin_three a ?_
    rw [hbot]
    infer_instance
  · intro htop
    refine not_normal_stabilizer_perm_fin_three a ?_
    rw [htop]
    infer_instance

end EpsilonEridani
