/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.GroupTheory.Perm.Basic
public import EpsilonEridani.GroupTheory.Perm.OrbitCount.Basic
import EpsilonEridani.Algebra.GroupAction.OrbitRelQuotient
import Mathlib.Dynamics.PeriodicPts.Lemmas

/-!
# Transpositions and the number of orbits

Multiplying a permutation `σ` of a finite type by the transposition `Equiv.swap a b` of two
distinct points either merges the orbit of `a` with the orbit of `b`, or splits the single orbit
carrying both of them in two. The number of orbits therefore changes by exactly one, and which way
is decided by `Equiv.Perm.SameCycle σ a b`:

* `EpsilonEridani.orbitCount_swap_mul_add_one_of_not_sameCycle`, the merging step; its hypothesis
  `¬ Equiv.Perm.SameCycle σ a b` already forces `a ≠ b`, since a point shares its own orbit;
* `EpsilonEridani.orbitCount_swap_mul_of_sameCycle`, the splitting step, which asks for `a ≠ b`
  explicitly.

The degenerate case `a = b` falls outside that dichotomy: `Equiv.swap a a` is the identity, so the
number of orbits is unchanged, and `Equiv.Perm.SameCycle σ a b`, which then holds, decides nothing.

Iterating the two steps measures how many transpositions it takes to build `σ`: every
factorization of `σ` into transpositions has at least `Nat.card α - EpsilonEridani.orbitCount σ` factors
(`EpsilonEridani.card_le_orbitCount_add_length`), and one with exactly that many exists
(`Equiv.Perm.exists_isSwap_list_prod_eq_and_orbitCount_add_length_eq_card`), so that number is
the reflection length of `σ` (`Equiv.Perm.isLeast_card_sub_orbitCount`). More generally,
`EpsilonEridani.card_add_orbitCount_le_length_add_two_mul_card_orbits` sharpens the lower bound by
retaining the orbit count of their product and the number of orbits generated by the factors;
`EpsilonEridani.card_add_orbitCount_le_length_add_two` is its transitive specialization.

Both steps rest on a description of the orbits of the product:
`Equiv.Perm.SameCycle.sameCycle_or_of_swap_mul` says that two points sharing an orbit of
`Equiv.swap a b * σ` either shared an orbit of `σ` already, or were attached one to `a` and the
other to `b`. That containment needs no hypothesis at all; what the two orbit-relation statements
`EpsilonEridani.sameCycle_swap_mul_of_mem_periodicPts_of_not_sameCycle` and
`EpsilonEridani.not_sameCycle_swap_mul_of_mem_periodicPts_of_ne_of_sameCycle` do need is that the orbit
being walked round comes back to its starting point, that is, that the relevant point is periodic
for `σ`. Every point of a finite type is periodic (`Function.Injective.mem_periodicPts`), which is
how the orbit-count steps below supply that.

⚠ That periodicity is essential rather than a convenience. For the shift on two disjoint copies of
`ℤ`, with `a` and `b` the two origins, the product `Equiv.swap a b * σ` cuts both lines and
reconnects them into two lines again, so the two orbits do not merge.

`EpsilonEridani.orbitCount_mul_swap_add_one` in `EpsilonEridani/GroupTheory/Perm/OrbitCount/Basic.lean` is the
specialized fixed-point formulation of the right-multiplication merging step: the transposition
splices that one-point orbit into another one. The generalized step lemmas below assume only
finiteness of the relevant orbit quotient together with an explicit periodic-point hypothesis;
their `@[simp]` corollaries assume that the underlying type is finite.

## Source

`Equiv.Perm.exists_isSwap_list_prod_eq_and_orbitCount_add_length_eq_card` returns the list that
Mathlib's `Equiv.Perm.swapFactors` builds by the recursion of `Equiv.Perm.swapFactorsAux` in
`Mathlib/GroupTheory/Perm/Sign.lean`, and measures it: that list `L` satisfies
`EpsilonEridani.orbitCount σ + L.length = Nat.card α`. With the lower bound
`EpsilonEridani.card_le_orbitCount_add_length` this makes `Nat.card α - EpsilonEridani.orbitCount σ` the
reflection length of `σ`, so that an induction along a minimal factorization, as in
Euler-characteristic bounds for products of permutations, changes the number of orbits by exactly
one at each step.
-/

public section

namespace EpsilonEridani

open Equiv Equiv.Perm

-- The two transposition steps are the step lemma of Layer 0.5 of the Tau Ceti `BelyiMaps`
-- roadmap, whose formal prototype `Suggested.lean` states them as one equation in the deferred
-- `cycleCount` of a permutation; here they are stated for `EpsilonEridani.orbitCount`, and in the two
-- directions rather than through a `Nat` subtraction. The minimal factorization is what the
-- induction for the Euler-characteristic bound of that roadmap's Layer 0.6 walks along.

variable {α : Type*} [DecidableEq α] {σ : Perm α} {a b x y : α}

/-- The orbits of `σ`, with the orbit of `a` and the orbit of `b` merged into one. This is the orbit
relation of the group generated by `σ` and `Equiv.swap a b`, which is what
`Equiv.Perm.SameCycle.sameCycle_or_of_swap_mul` and
`EpsilonEridani.sameCycle_swap_mul_of_mem_periodicPts_of_not_sameCycle` prove between them for the single
element `Equiv.swap a b * σ` of that group. -/
private def MergeRel (σ : Perm α) (a b : α) : α → α → Prop := fun x y =>
  σ.SameCycle x y ∨ ((σ.SameCycle x a ∨ σ.SameCycle x b) ∧ (σ.SameCycle y a ∨ σ.SameCycle y b))

omit [DecidableEq α] in
private theorem mergeRel_attach (hxy : σ.SameCycle x y)
    (hy : σ.SameCycle y a ∨ σ.SameCycle y b) : σ.SameCycle x a ∨ σ.SameCycle x b :=
  hy.imp hxy.trans hxy.trans

omit [DecidableEq α] in
private theorem equivalence_mergeRel (σ : Perm α) (a b : α) : Equivalence (MergeRel σ a b) := by
  refine ⟨fun u => Or.inl (SameCycle.refl σ u), ?_, ?_⟩
  · rintro u v (huv | ⟨hu, hv⟩)
    · exact Or.inl huv.symm
    · exact Or.inr ⟨hv, hu⟩
  · rintro u v w (huv | ⟨hu, hv⟩) (hvw | ⟨hv', hw⟩)
    · exact Or.inl (huv.trans hvw)
    · exact Or.inr ⟨mergeRel_attach huv hv', hw⟩
    · exact Or.inr ⟨hu, mergeRel_attach hvw.symm hv⟩
    · exact Or.inr ⟨hu, hw⟩

/-- Every element of the group generated by `σ` and `Equiv.swap a b` moves each point inside its
class for `EpsilonEridani.MergeRel σ a b`: the generator `σ` does so because it preserves its own orbits,
and the generator `Equiv.swap a b` does so because the classes of `a` and of `b` have been
merged. -/
private theorem mergeRel_apply_of_mem_closure (σ : Perm α) (a b : α) {g : Perm α}
    (hg : g ∈ Subgroup.closure {σ, Equiv.swap a b}) (z : α) : MergeRel σ a b z (g z) := by
  have heq := equivalence_mergeRel σ a b
  let H : Subgroup (Perm α) :=
    { carrier := {g | ∀ z, MergeRel σ a b z (g z)}
      one_mem' := fun z => heq.refl z
      mul_mem' := fun {g h} hg hh z => heq.trans (hh z) (hg (h z))
      inv_mem' := fun {g} hg z => heq.symm (by simpa using hg (g⁻¹ z)) }
  have hclosure : Subgroup.closure {σ, Equiv.swap a b} ≤ H := by
    rw [Subgroup.closure_le]
    intro f hf
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hf
    rcases hf with rfl | rfl
    · exact fun z => Or.inl ⟨1, by simp⟩
    · intro z
      rcases eq_or_ne z a with rfl | hza
      · rw [Equiv.swap_apply_left]
        exact Or.inr ⟨Or.inl (SameCycle.refl σ z), Or.inr (SameCycle.refl σ b)⟩
      rcases eq_or_ne z b with rfl | hzb
      · rw [Equiv.swap_apply_right]
        exact Or.inr ⟨Or.inr (SameCycle.refl σ z), Or.inl (SameCycle.refl σ a)⟩
      · rw [Equiv.swap_apply_of_ne_of_ne hza hzb]
        exact Or.inl (SameCycle.refl σ z)
  exact hclosure hg z

/-- **Multiplying by a transposition can only merge the orbits of its two points.** Two points in
one orbit of `Equiv.swap a b * σ` either lie in one orbit of `σ` already, or one of them is joined
to `a` and the other to `b`. -/
theorem _root_.Equiv.Perm.SameCycle.sameCycle_or_of_swap_mul
    (h : (Equiv.swap a b * σ).SameCycle x y) :
    σ.SameCycle x y ∨
      ((σ.SameCycle x a ∨ σ.SameCycle x b) ∧ (σ.SameCycle y a ∨ σ.SameCycle y b)) := by
  obtain ⟨i, rfl⟩ := h
  refine mergeRel_apply_of_mem_closure σ a b (zpow_mem (mul_mem ?_ ?_) i) x
  · exact Subgroup.subset_closure (by simp)
  · exact Subgroup.subset_closure (by simp)

/-- Once `a` and `b` share an orbit of `Equiv.swap a b * σ` — the receiver `hab` — every orbit of
`σ` is contained in an orbit of that product. -/
theorem _root_.Equiv.Perm.SameCycle.swap_mul_of_sameCycle
    (hab : (Equiv.swap a b * σ).SameCycle a b) (h : σ.SameCycle x y) :
    (Equiv.swap a b * σ).SameCycle x y := by
  have h' : (Equiv.swap a b * (Equiv.swap a b * σ)).SameCycle x y := by
    rwa [Equiv.swap_mul_self_mul]
  rcases h'.sameCycle_or_of_swap_mul with hxy | ⟨hx, hy⟩
  · exact hxy
  · exact SameCycle.trans (hx.elim id fun h => h.trans hab.symm)
      (SameCycle.symm (hy.elim id fun h => h.trans hab.symm))

/-- The walk along the orbit of `c`: as long as the powers of `σ` have carried `c` neither to `a`
nor to `b`, the product `Equiv.swap a b * σ` has moved `c` exactly as `σ` does. -/
private theorem pow_swap_mul_apply_of_lt {c : α} {j : ℕ}
    (h : ∀ i, 0 < i → i < j → (σ ^ i) c ≠ a ∧ (σ ^ i) c ≠ b) :
    ∀ i < j, ((Equiv.swap a b * σ) ^ i) c = (σ ^ i) c := by
  intro i
  induction i with
  | zero => exact fun _ => by simp
  | succ i ih =>
    intro hi
    have hne := h (i + 1) (by omega) hi
    have h1 : σ ((σ ^ i) c) ≠ a := by
      rw [← Equiv.Perm.mul_apply, ← pow_succ']; exact hne.1
    have h2 : σ ((σ ^ i) c) ≠ b := by
      rw [← Equiv.Perm.mul_apply, ← pow_succ']; exact hne.2
    rw [pow_succ', Equiv.Perm.mul_apply, ih (by omega), Equiv.Perm.mul_apply,
      Equiv.swap_apply_of_ne_of_ne h1 h2, pow_succ' σ, Equiv.Perm.mul_apply]

/-- The last step of the walk: when the `j`-th power of `σ` is the first to carry `c` to `b`, the
`j`-th power of `Equiv.swap a b * σ` carries `c` to `a` instead. -/
private theorem pow_swap_mul_apply_eq {c : α} {j : ℕ} (hj : 0 < j)
    (h : ∀ i, 0 < i → i < j → (σ ^ i) c ≠ a ∧ (σ ^ i) c ≠ b) (hjb : (σ ^ j) c = b) :
    ((Equiv.swap a b * σ) ^ j) c = a := by
  obtain ⟨j, rfl⟩ : ∃ k, j = k + 1 := ⟨j - 1, by omega⟩
  have hstep : σ ((σ ^ j) c) = b := by rw [← Equiv.Perm.mul_apply, ← pow_succ']; exact hjb
  rw [pow_succ', Equiv.Perm.mul_apply, pow_swap_mul_apply_of_lt h j (by omega),
    Equiv.Perm.mul_apply, hstep, Equiv.swap_apply_right]

/-- **Multiplying by a transposition merges the orbits of its two points.** If `a` and `b` lie in
different orbits of `σ`, and `b` is a periodic point of `σ`, they lie in one orbit of
`Equiv.swap a b * σ`: following the orbit of `b` right round, the product diverts its closing step
to `a`. -/
theorem sameCycle_swap_mul_of_mem_periodicPts_of_not_sameCycle
    (hb : b ∈ Function.periodicPts (σ : α → α)) (h : ¬ σ.SameCycle a b) :
    (Equiv.swap a b * σ).SameCycle a b := by
  obtain ⟨m, hmpos, hmb, hmin⟩ : ∃ m : ℕ, 0 < m ∧ (σ ^ m) b = b ∧
      ∀ i, 0 < i → i < m → (σ ^ i) b ≠ b :=
    ⟨Function.minimalPeriod (⇑σ) b,
      Function.minimalPeriod_pos_of_mem_periodicPts hb,
      Function.isPeriodicPt_minimalPeriod (⇑σ) b,
      fun i hi him => Function.not_isPeriodicPt_of_pos_of_lt_minimalPeriod hi.ne' him⟩
  have hna : ∀ i : ℕ, (σ ^ i) b ≠ a := fun i hcon =>
    h (SameCycle.symm (⟨(i : ℤ), by simpa using hcon⟩ : σ.SameCycle b a))
  refine SameCycle.symm (⟨(m : ℤ), ?_⟩ : (Equiv.swap a b * σ).SameCycle b a)
  simpa using pow_swap_mul_apply_eq hmpos (fun i hi him => ⟨hna i, hmin i hi him⟩) hmb

/-- The data from the closed arc used in the splitting step: `a` remains periodic under the
product, while `a` and `b` no longer share an orbit. -/
private theorem mem_periodicPts_and_not_sameCycle_swap_mul_of_sameCycle
    (ha : a ∈ Function.periodicPts (σ : α → α)) (hab : a ≠ b) (h : σ.SameCycle a b) :
    a ∈ Function.periodicPts (Equiv.swap a b * σ : α → α) ∧
      ¬ (Equiv.swap a b * σ).SameCycle a b := by
  classical
  obtain ⟨j, hjpos, hja, hjmin⟩ : ∃ j : ℕ, 0 < j ∧ (σ ^ j) a = b ∧
      ∀ i, 0 < i → i < j → (σ ^ i) a ≠ b := by
    have hex := h.exists_pos_pow_eq_of_mem_periodicPts ha
    exact ⟨Nat.find hex, (Nat.find_spec hex).1, (Nat.find_spec hex).2,
      fun i hi hij hcon => Nat.find_min hex hij ⟨hi, hcon⟩⟩
  -- Before reaching `b`, the powers of `σ` cannot return to `a` either.
  have hwalk : ∀ i, 0 < i → i < j → (σ ^ i) a ≠ a ∧ (σ ^ i) a ≠ b := by
    refine fun i hi hij => ⟨fun hcon => hjmin (j - i) (by omega) (by omega) ?_, hjmin i hi hij⟩
    have hgo : (σ ^ (j - i)) ((σ ^ i) a) = b := by
      rw [← Equiv.Perm.mul_apply, ← pow_add, Nat.sub_add_cancel hij.le]
      exact hja
    rwa [hcon] at hgo
  have hfix : Function.IsPeriodicPt (Equiv.swap a b * σ : α → α) j a :=
    pow_swap_mul_apply_eq hjpos hwalk hja
  have hper : a ∈ Function.periodicPts (Equiv.swap a b * σ : α → α) :=
    Function.mem_periodicPts.mpr ⟨j, hjpos, hfix⟩
  refine ⟨hper, fun hsc => ?_⟩
  -- The orbit of `a` under the product is spanned by the powers below `j`, and none of them is `b`.
  obtain ⟨r, -, hr⟩ := hsc.exists_pos_pow_eq_of_mem_periodicPts hper
  have hlt : r % j < j := Nat.mod_lt _ hjpos
  have hmod : ((Equiv.swap a b * σ) ^ (r % j)) a = b := by
    rw [Equiv.Perm.coe_pow, hfix.iterate_mod_apply r, ← Equiv.Perm.coe_pow]
    exact hr
  rcases Nat.eq_zero_or_pos (r % j) with hr0 | hrpos
  · rw [hr0, pow_zero] at hmod
    exact hab (by simpa using hmod)
  · rw [pow_swap_mul_apply_of_lt hwalk (r % j) hlt] at hmod
    exact hjmin (r % j) hrpos hlt hmod

/-- **Multiplying by a transposition splits the orbit of its two points.** If `a ≠ b` lie in one
orbit of `σ`, and `a` is a periodic point of `σ`, they lie in different orbits of
`Equiv.swap a b * σ`: the product closes the arc from `a` to `b` into an orbit of its own, which
`b` is not on. -/
theorem not_sameCycle_swap_mul_of_mem_periodicPts_of_ne_of_sameCycle
    (ha : a ∈ Function.periodicPts (σ : α → α)) (hab : a ≠ b) (h : σ.SameCycle a b) :
    ¬ (Equiv.swap a b * σ).SameCycle a b :=
  (mem_periodicPts_and_not_sameCycle_swap_mul_of_sameCycle ha hab h).2

/-- **The transposition step lemma, merging, for a finite set of orbits.** If `a` and `b` lie in
different orbits of `σ`, the orbit set of `σ` is finite, and `b` is periodic, then
`Equiv.swap a b * σ` has one orbit fewer than `σ`. -/
theorem orbitCount_swap_mul_add_one_of_mem_periodicPts_of_not_sameCycle
    [Finite (Quotient (SameCycle.setoid σ))]
    (hb : b ∈ Function.periodicPts (σ : α → α)) (h : ¬ σ.SameCycle a b) :
    orbitCount (Equiv.swap a b * σ) + 1 = orbitCount σ :=
  have hab := sameCycle_swap_mul_of_mem_periodicPts_of_not_sameCycle hb h
  orbitCount_add_one_of_merge (fun huv => hab.swap_mul_of_sameCycle huv)
    (fun huv => huv.sameCycle_or_of_swap_mul) hab h

/-- **The transposition step lemma, merging.** If `a` and `b` lie in different orbits of `σ`, then
`Equiv.swap a b * σ` has one orbit fewer than `σ`: its orbits are those of `σ`, with the orbit of
`a` and the orbit of `b` merged. -/
@[simp]
theorem orbitCount_swap_mul_add_one_of_not_sameCycle [Finite α] (h : ¬ σ.SameCycle a b) :
    orbitCount (Equiv.swap a b * σ) + 1 = orbitCount σ :=
  orbitCount_swap_mul_add_one_of_mem_periodicPts_of_not_sameCycle
    (σ.injective.mem_periodicPts b) h

/-- **The transposition step lemma, splitting, for a finite set of resulting orbits.** If `a ≠ b`
lie in one orbit of `σ`, `a` is periodic for `σ`, and the orbit set of
`Equiv.swap a b * σ` is finite, then that product has one orbit more than `σ`. -/
theorem orbitCount_swap_mul_of_mem_periodicPts_of_ne_of_sameCycle
    [Finite (Quotient (SameCycle.setoid (Equiv.swap a b * σ)))]
    (ha : a ∈ Function.periodicPts (σ : α → α)) (hab : a ≠ b) (h : σ.SameCycle a b) :
    orbitCount (Equiv.swap a b * σ) = orbitCount σ + 1 := by
  have hdata := mem_periodicPts_and_not_sameCycle_swap_mul_of_sameCycle ha hab h
  have hmerge := orbitCount_swap_mul_add_one_of_mem_periodicPts_of_not_sameCycle
    (σ := Equiv.swap a b * σ) (a := b) (b := a) hdata.1 (fun hba => hdata.2 hba.symm)
  rw [Equiv.swap_comm b a, Equiv.swap_mul_self_mul] at hmerge
  exact hmerge.symm

/-- **The transposition step lemma, splitting.** If `a ≠ b` lie in one orbit of `σ`, then
`Equiv.swap a b * σ` has one orbit more than `σ`: that orbit has been cut in two. -/
@[simp]
theorem orbitCount_swap_mul_of_sameCycle [Finite α] (hab : a ≠ b) (h : σ.SameCycle a b) :
    orbitCount (Equiv.swap a b * σ) = orbitCount σ + 1 :=
  orbitCount_swap_mul_of_mem_periodicPts_of_ne_of_sameCycle
    (σ.injective.mem_periodicPts a) hab h

/-- Multiplying on the left by a transposition removes at most one orbit, whichever of the two
steps applies. -/
theorem _root_.Equiv.Perm.orbitCount_le_orbitCount_swap_mul_add_one [Finite α] (σ : Perm α)
    (a b : α) : orbitCount σ ≤ orbitCount (Equiv.swap a b * σ) + 1 := by
  rcases eq_or_ne a b with rfl | hab
  · rw [Equiv.swap_self, ← Equiv.Perm.one_def, one_mul]
    omega
  by_cases h : σ.SameCycle a b
  · rw [orbitCount_swap_mul_of_sameCycle hab h]
    omega
  · exact (orbitCount_swap_mul_add_one_of_not_sameCycle h).symm.le

/-- **The transposition step lemma on the other side, merging, for a finite set of orbits.** If
`a` and `b` lie in different orbits of `σ`, the orbit set of `σ` is finite, and `b` is periodic,
then `σ * Equiv.swap a b` has one orbit fewer than `σ`. -/
theorem orbitCount_mul_swap_add_one_of_mem_periodicPts_of_not_sameCycle
    [Finite (Quotient (SameCycle.setoid σ))]
    (hb : b ∈ Function.periodicPts (σ : α → α)) (h : ¬ σ.SameCycle a b) :
    orbitCount (σ * Equiv.swap a b) + 1 = orbitCount σ := by
  rw [Equiv.mul_swap_eq_swap_mul]
  refine orbitCount_swap_mul_add_one_of_mem_periodicPts_of_not_sameCycle
    ((Function.Commute.refl (σ : α → α)).mapsTo_periodicPts hb) ?_
  rwa [sameCycle_apply_left, sameCycle_apply_right]

/-- **The transposition step lemma on the other side, merging.** If `a` and `b` lie in different
orbits of `σ`, then multiplying on the right merges those two orbits just as multiplying on the
left does, so `σ * Equiv.swap a b` has one orbit fewer than `σ`:
`orbitCount (σ * Equiv.swap a b) + 1 = orbitCount σ`. -/
@[simp]
theorem orbitCount_mul_swap_add_one_of_not_sameCycle [Finite α] (h : ¬ σ.SameCycle a b) :
    orbitCount (σ * Equiv.swap a b) + 1 = orbitCount σ :=
  orbitCount_mul_swap_add_one_of_mem_periodicPts_of_not_sameCycle
    (σ.injective.mem_periodicPts b) h

/-- **The transposition step lemma on the other side, splitting, for a finite set of resulting
orbits.** If `a ≠ b` lie in one orbit of `σ`, `a` is periodic for `σ`, and the orbit set of
`σ * Equiv.swap a b` is finite, then that product has one orbit more than `σ`. -/
theorem orbitCount_mul_swap_of_mem_periodicPts_of_ne_of_sameCycle
    [Finite (Quotient (SameCycle.setoid (σ * Equiv.swap a b)))]
    (ha : a ∈ Function.periodicPts (σ : α → α)) (hab : a ≠ b) (h : σ.SameCycle a b) :
    orbitCount (σ * Equiv.swap a b) = orbitCount σ + 1 := by
  let _ : Finite (Quotient
      (SameCycle.setoid (Equiv.swap (σ a) (σ b) * σ))) := by
    rw [← Equiv.mul_swap_eq_swap_mul]
    infer_instance
  rw [Equiv.mul_swap_eq_swap_mul]
  refine orbitCount_swap_mul_of_mem_periodicPts_of_ne_of_sameCycle
    ((Function.Commute.refl (σ : α → α)).mapsTo_periodicPts ha) (σ.injective.ne hab) ?_
  rwa [sameCycle_apply_left, sameCycle_apply_right]

/-- **The transposition step lemma on the other side, splitting.** If `a ≠ b` lie in one orbit of
`σ`, then multiplying on the right cuts that orbit in two just as multiplying on the left does, so
`σ * Equiv.swap a b` has one orbit more than `σ`:
`orbitCount (σ * Equiv.swap a b) = orbitCount σ + 1`. -/
@[simp]
theorem orbitCount_mul_swap_of_sameCycle [Finite α] (hab : a ≠ b) (h : σ.SameCycle a b) :
    orbitCount (σ * Equiv.swap a b) = orbitCount σ + 1 :=
  orbitCount_mul_swap_of_mem_periodicPts_of_ne_of_sameCycle
    (σ.injective.mem_periodicPts a) hab h

/-- Multiplying on the right by a transposition removes at most one orbit, the mirror of
`Equiv.Perm.orbitCount_le_orbitCount_swap_mul_add_one`. -/
theorem _root_.Equiv.Perm.orbitCount_le_orbitCount_mul_swap_add_one [Finite α] (σ : Perm α)
    (a b : α) : orbitCount σ ≤ orbitCount (σ * Equiv.swap a b) + 1 := by
  rw [Equiv.mul_swap_eq_swap_mul]
  exact σ.orbitCount_le_orbitCount_swap_mul_add_one (σ a) (σ b)

omit [DecidableEq α] in
/-- A permutation other than the identity has fewer orbits than there are points: the two ends of
one of its nontrivial steps share an orbit. -/
theorem orbitCount_lt_card_of_ne_one [Finite α] (h : σ ≠ 1) : orbitCount σ < Nat.card α := by
  classical
  obtain ⟨x, hx⟩ : ∃ x, σ x ≠ x := by
    by_contra hcon
    refine h (Equiv.ext fun x => ?_)
    simpa using not_not.mp (not_exists.mp hcon x)
  have hsplit := orbitCount_swap_mul_of_sameCycle (Ne.symm hx)
    (⟨1, by simp⟩ : σ.SameCycle x (σ x))
  have hle := (Equiv.swap x (σ x) * σ).orbitCount_le_card
  omega

/-- **No factorization into transpositions is shorter than the reflection length.** Every
factorization of a permutation into transpositions has at least `Nat.card α - orbitCount` factors,
because each factor removes at most one orbit from the `Nat.card α` orbits of the identity. -/
theorem card_le_orbitCount_add_length [Finite α] {L : List (Perm α)} (hL : ∀ g ∈ L, g.IsSwap) :
    Nat.card α ≤ orbitCount L.prod + L.length := by
  induction L with
  | nil => simp
  | cons t L ih =>
    obtain ⟨u, v, -, rfl⟩ := hL t (by simp)
    have hih := ih fun g hg => hL g (List.mem_cons_of_mem _ hg)
    have hstep := L.prod.orbitCount_le_orbitCount_swap_mul_add_one u v
    rw [List.prod_cons, List.length_cons]
    omega

/-- The subgroup of permutations which move every point within its orbit under `π`. -/
private def cyclePreservingSubgroup (π : Perm α) : Subgroup (Perm α) where
  carrier := {g | ∀ x, π.SameCycle x (g x)}
  one_mem' := fun x => SameCycle.refl π x
  mul_mem' := fun {g h} hg hh x => (hh x).trans (hg (h x))
  inv_mem' := by
    intro g hg x
    have hx := (hg (g⁻¹ x)).symm
    simpa using hx

omit [DecidableEq α] in
/-- Membership in `EpsilonEridani.cyclePreservingSubgroup`. -/
private theorem mem_cyclePreservingSubgroup {π g : Perm α} :
    g ∈ cyclePreservingSubgroup π ↔ ∀ x, π.SameCycle x (g x) := Iff.rfl

/-- A list of transpositions admits a permutation whose cycles are the components joined by the
transpositions. The numerical inequality records, simultaneously, the number of components and
the number of cycles of the list product. -/
private theorem exists_componentPerm [Finite α] (L : List (Perm α))
    (hL : ∀ g ∈ L, g.IsSwap) :
    ∃ π : Perm α, Nat.card α + orbitCount L.prod ≤ L.length + 2 * orbitCount π ∧
      ∀ g ∈ L, ∀ x, π.SameCycle x (g x) := by
  induction L with
  | nil =>
      refine ⟨1, ?_, by simp⟩
      simp only [List.prod_nil, orbitCount_one, List.length_nil, zero_add]
      omega
  | cons t L ih =>
      obtain ⟨a, b, hab, rfl⟩ := hL t (by simp)
      obtain ⟨π, hbound, hpres⟩ := ih (fun g hg => hL g (List.mem_cons_of_mem _ hg))
      by_cases hcomp : π.SameCycle a b
      · have hswapPres' : ∀ x, π.SameCycle x (Equiv.swap a b x) := by
          intro x
          rcases eq_or_ne x a with rfl | hxa
          · simpa using hcomp
          rcases eq_or_ne x b with rfl | hxb
          · simpa using hcomp.symm
          · rw [Equiv.swap_apply_of_ne_of_ne hxa hxb]
        have hstep : orbitCount (Equiv.swap a b * L.prod) ≤ orbitCount L.prod + 1 := by
          by_cases hcycle : L.prod.SameCycle a b
          · rw [orbitCount_swap_mul_of_sameCycle hab hcycle]
          · have hmerge := orbitCount_swap_mul_add_one_of_not_sameCycle hcycle
            omega
        refine ⟨π, ?_, ?_⟩
        · simp only [List.prod_cons, List.length_cons]
          omega
        · intro g hg x
          rcases List.mem_cons.mp hg with rfl | hg
          · exact hswapPres' x
          · exact hpres g hg x
      · have hprod_mem : L.prod ∈ cyclePreservingSubgroup π :=
          (cyclePreservingSubgroup π).list_prod_mem (fun g hg => hpres g hg)
        have hcycle : ¬ L.prod.SameCycle a b := by
          intro hcycle
          obtain ⟨i, hi⟩ := hcycle
          have hpow := mem_cyclePreservingSubgroup.mp
            ((cyclePreservingSubgroup π).zpow_mem hprod_mem i)
          exact hcomp (by simpa [hi] using hpow a)
        have hprodMerge := orbitCount_swap_mul_add_one_of_not_sameCycle hcycle
        have hcompMerge := orbitCount_swap_mul_add_one_of_not_sameCycle hcomp
        have hab' : (Equiv.swap a b * π).SameCycle a b :=
          sameCycle_swap_mul_of_mem_periodicPts_of_not_sameCycle
            (π.injective.mem_periodicPts b) hcomp
        refine ⟨Equiv.swap a b * π, ?_, ?_⟩
        · simp only [List.prod_cons, List.length_cons]
          omega
        · intro g hg x
          rcases List.mem_cons.mp hg with rfl | hg
          · rcases eq_or_ne x a with rfl | hxa
            · simpa using hab'
            rcases eq_or_ne x b with rfl | hxb
            · simpa using hab'.symm
            · rw [Equiv.swap_apply_of_ne_of_ne hxa hxb]
          · exact hab'.swap_mul_of_sameCycle (hpres g hg x)

-- Source: the combinatorial route of Layer 0.6 of the Tau Ceti `BelyiMaps` roadmap, which
-- proves the connected Euler bound (step 3) from a transposition factorization; here that
-- argument is run one orbit of the generated group at a time, as needed for the general bound
-- `χ(t) ≤ 2 · (number of monodromy orbits)` (step 4).
/-- **Hurwitz's transposition bound, componentwise.** If `L` is a list of transpositions,
the number of points plus the number of cycles of its product is at most the length of `L`
plus twice the number of orbits of the group generated by `L`.

This is the disconnected form of `EpsilonEridani.card_add_orbitCount_le_length_add_two`: each orbit
of the generated group is one connected component of the transposition graph. -/
theorem card_add_orbitCount_le_length_add_two_mul_card_orbits [Finite α]
    {L : List (Perm α)} (hL : ∀ g ∈ L, g.IsSwap) :
    Nat.card α + orbitCount L.prod ≤ L.length +
      2 * Nat.card (MulAction.orbitRel.Quotient (Subgroup.closure {g | g ∈ L}) α) := by
  cases nonempty_fintype α
  let H := Subgroup.closure {g : Perm α | g ∈ L}
  obtain ⟨π, hbound, hpres⟩ := exists_componentPerm L hL
  have hclosure : H ≤ cyclePreservingSubgroup π := by
    rw [Subgroup.closure_le]
    exact fun g hg => hpres g hg
  let f : MulAction.orbitRel.Quotient H α → Quotient (SameCycle.setoid π) :=
    fun q => Quotient.liftOn' q (fun x => Quotient.mk'' x) fun a b hab => by
      apply Quotient.sound
      rw [MulAction.orbitRel_apply, MulAction.mem_orbit_iff] at hab
      obtain ⟨g, rfl⟩ := hab
      exact (mem_cyclePreservingSubgroup.mp (hclosure g.2) b).symm
  have hf : Function.Surjective f := by
    intro q
    induction q using Quotient.inductionOn'
    exact ⟨Quotient.mk'' _, rfl⟩
  have hcard : orbitCount π ≤ Nat.card (MulAction.orbitRel.Quotient H α) := by
    rw [orbitCount_def]
    exact Nat.card_le_card_of_surjective f hf
  exact hbound.trans (by dsimp only [H] at hcard ⊢; omega)

/-- **Hurwitz's transposition bound.** If a list of transpositions generates a group acting
transitively on a finite type, its length is at least the number of points plus the number of
cycles of its product, minus two. Equivalently,
`Nat.card α + orbitCount L.prod ≤ L.length + 2`. -/
theorem card_add_orbitCount_le_length_add_two [Finite α]
    {L : List (Perm α)} (hL : ∀ g ∈ L, g.IsSwap)
    (htrans : MulAction.IsPretransitive (Subgroup.closure {g | g ∈ L}) α) :
    Nat.card α + orbitCount L.prod ≤ L.length + 2 := by
  rcases isEmpty_or_nonempty α with _ | _
  · have := L.prod.orbitCount_le_card
    have hcard : Nat.card α = 0 := Nat.card_of_isEmpty
    omega
  let H := Subgroup.closure {g : Perm α | g ∈ L}
  have horbit : Nat.card (MulAction.orbitRel.Quotient H α) = 1 :=
    MulAction.card_orbitRelQuotient_eq_one
  have hbound := card_add_orbitCount_le_length_add_two_mul_card_orbits hL
  dsimp only [H] at horbit
  rw [horbit] at hbound
  omega

/-- Mathlib's `Equiv.Perm.swapFactorsAux` construction has exactly the reflection length. -/
private theorem swapFactorsAux_orbitCount_add_length_eq_card [Fintype α]
    (l : List α) (σ : Perm α) (h : ∀ {x}, σ x ≠ x → x ∈ l) :
    orbitCount σ + (Equiv.Perm.swapFactorsAux l σ h).1.length = Fintype.card α := by
  induction l generalizing σ with
  | nil =>
    have h1 : σ = 1 := by
      apply Equiv.ext
      intro x
      simpa using not_not.mp (mt h List.not_mem_nil)
    subst h1
    rw [Equiv.Perm.swapFactorsAux.eq_1]
    simp
  | cons x l ih =>
    by_cases hx : x = σ x
    · rw [Equiv.Perm.swapFactorsAux.eq_2]
      dsimp only
      rw [dite_eq_left hx]
      exact ih σ (fun {y} hy => List.mem_of_ne_of_mem
        (fun hxy : y = x => by simp [hxy, hx.symm] at hy) (h hy))
    · have hsplit : orbitCount (Equiv.swap x (σ x) * σ) = orbitCount σ + 1 :=
        orbitCount_swap_mul_of_sameCycle hx ⟨1, by simp⟩
      have hτ : ∀ {y : α}, (Equiv.swap x (σ x) * σ) y ≠ y → y ∈ l := fun {y} hy =>
        List.mem_of_ne_of_mem (Equiv.Perm.ne_and_ne_of_swap_mul_apply_ne_self hy).2
          (h (Equiv.Perm.ne_and_ne_of_swap_mul_apply_ne_self hy).1)
      have hrec := ih (Equiv.swap x (σ x) * σ) hτ
      rw [Equiv.Perm.swapFactorsAux.eq_2]
      dsimp only
      rw [dite_eq_right hx, List.length_cons]
      -- The recursive call in `Equiv.Perm.swapFactorsAux` carries a membership proof built inside
      -- that definition; `hrec` uses `hτ` instead, and the two agree by proof irrelevance.
      omega

/-- **A factorization into transpositions of exactly the reflection length exists.** Splitting off
the transposition `Equiv.swap x (σ x)` adds one orbit, so after `Nat.card α - orbitCount σ` such
steps the identity is reached. -/
theorem _root_.Equiv.Perm.exists_isSwap_list_prod_eq_and_orbitCount_add_length_eq_card
    [Finite α] (σ : Perm α) :
    ∃ L : List (Perm α), (∀ g ∈ L, g.IsSwap) ∧ L.prod = σ ∧
      orbitCount σ + L.length = Nat.card α := by
  cases nonempty_fintype α
  let _ : LinearOrder α := LinearOrder.lift' (Fintype.equivFin α) (Fintype.equivFin α).injective
  let L := Equiv.Perm.swapFactors σ
  refine ⟨L.1, L.2.2, L.2.1, ?_⟩
  simpa only [L, Equiv.Perm.swapFactors, Nat.card_eq_fintype_card] using
    swapFactorsAux_orbitCount_add_length_eq_card
      ((Finset.univ : Finset α).sort (· ≤ ·)) σ (fun {_ _} => by simp)

/-- **The reflection length of a permutation of a finite type.** The least number of transpositions
whose product is `σ` is `Nat.card α - orbitCount σ`. -/
theorem _root_.Equiv.Perm.isLeast_card_sub_orbitCount [Finite α] (σ : Perm α) :
    IsLeast {m : ℕ | ∃ L : List (Perm α), (∀ g ∈ L, g.IsSwap) ∧ L.prod = σ ∧ L.length = m}
      (Nat.card α - orbitCount σ) := by
  obtain ⟨L, hL, hprod, hlen⟩ := σ.exists_isSwap_list_prod_eq_and_orbitCount_add_length_eq_card
  refine ⟨⟨L, hL, hprod, by omega⟩, ?_⟩
  rintro m ⟨M, hM, hprod', rfl⟩
  have hbound := card_le_orbitCount_add_length hM
  rw [hprod'] at hbound
  omega

end EpsilonEridani
