/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.MeasureTheory.Measure.Portmanteau
public import Mathlib.Topology.Compactness.Lindelof

/-!
# The Giry σ-algebra and the weak topology on probability measures

`ProbabilityMeasure X` carries two structures that are defined independently of one another: the
Giry σ-algebra, generated by the evaluations `P ↦ P s` at measurable sets `s`, and the topology of
weak convergence, induced by the integrals `P ↦ ∫⁻ f ∂P` of bounded continuous functions. This file
compares them.

* **Giry sets are Borel.** When `X` is a Borel space in which closed sets are approximated from
  outside by bounded continuous functions (for instance a pseudometrizable space), every map into
  `ProbabilityMeasure X` that is continuous for the weak topology is measurable for the Giry
  σ-algebra, as soon as its domain has measurable open sets. By the portmanteau theorem,
  `P ↦ P F` is upper semicontinuous for each closed `F`, hence Borel measurable; a Dynkin-system
  argument passes from closed sets to all measurable sets.
* **Borel sets are Giry sets, on hereditarily Lindelöf subspaces.** If
  `g : α → ProbabilityMeasure X` is a Giry-measurable topological inducing map and `α` is
  hereditarily Lindelöf (for instance second countable), then every open subset of `α` is
  measurable. The weak topology is induced by
  finitely many integrals at a time, so each point of an open set lies in a measurable open
  cylinder inside it, and countably many of these cylinders already cover the set.

Together, a hereditarily Lindelöf space topologically embedded in `ProbabilityMeasure X`, with the
measurable structure pulled back from the Giry σ-algebra, is a Borel space. This is how subspaces of
laws carrying a finer topology of their own, such as spaces of laws with finite moments under a
Wasserstein metric, are identified as Borel spaces.

## Main statements

* `Continuous.measurable_probabilityMeasure` — weakly continuous maps into probability measures are
  Giry measurable;
* `Topology.IsInducing.opensMeasurableSpace_probabilityMeasure` — a hereditarily Lindelöf space
  inducing into probability measures by a measurable map has measurable open sets;
* `Topology.IsInducing.borelSpace_probabilityMeasure` — the Borel space conclusion when the
  measurable structure is pulled back from the Giry σ-algebra;
* `EpsilonEridani.MeasureTheory.ProbabilityMeasure.borelSpace` and
  `EpsilonEridani.MeasureTheory.ProbabilityMeasure.borelSpace_subtype` — the instances on
  `ProbabilityMeasure X` and on its subtypes.

## References

* P. Billingsley, *Convergence of Probability Measures*, 2nd edition, Wiley 1999, §1.2 and §1.6.
* A. S. Kechris, *Classical Descriptive Set Theory*, Springer 1995, Theorem 17.24.
-/

public section

noncomputable section

open MeasureTheory Set Filter Topology BoundedContinuousFunction
open scoped ENNReal NNReal

variable {X α : Type*} [TopologicalSpace X] [MeasurableSpace X]
  [TopologicalSpace α] [MeasurableSpace α]

/-- **Weakly continuous maps into probability measures are Giry measurable.** If `X` is a Borel
space whose closed sets are approximated from outside by bounded continuous functions, and `α` has
measurable open sets, then a map `α → ProbabilityMeasure X` that is continuous for the topology of
weak convergence is measurable for the Giry σ-algebra. -/
theorem Continuous.measurable_probabilityMeasure [HasOuterApproxClosed X] [BorelSpace X]
    [OpensMeasurableSpace α] {g : α → ProbabilityMeasure X} (hg : Continuous g) :
    Measurable g := by
  -- It suffices that every evaluation `a ↦ g a s` at a measurable set `s` is measurable.
  suffices h : ∀ s, MeasurableSet s → Measurable fun a ↦ (g a : Measure X) s from
    (Measure.measurable_of_measurable_coe _ h).subtype_mk
  refine MeasurableSpace.induction_on_inter (BorelSpace.measurable_eq.trans
    borel_eq_generateFrom_isClosed) isPiSystem_isClosed (by simp) (fun F hF ↦ ?_)
    (fun s hs h ↦ ?_) (fun f hdisj hf h ↦ ?_)
  · -- Closed sets: the portmanteau theorem makes `P ↦ P F` upper semicontinuous.
    refine UpperSemicontinuous.measurable (upperSemicontinuous_iff_limsup_le.2 fun a ↦ ?_)
    exact ProbabilityMeasure.limsup_measure_closed_le_of_tendsto (hg.tendsto a) hF
  · -- Complements: `P sᶜ = 1 - P s`.
    simp_rw [prob_compl_eq_one_sub hs]
    exact measurable_const.sub h
  · -- Disjoint countable unions: countable additivity.
    simp_rw [measure_iUnion hdisj hf]
    exact Measurable.tsum h

/-- **Open sets are measurable in a hereditarily Lindelöf space of laws.** Let
`g : α → ProbabilityMeasure X` be a topological inducing map that is measurable for the Giry
σ-algebra. If `α` is hereditarily Lindelöf, for instance second countable, then every open subset
of `α` is measurable. -/
theorem Topology.IsInducing.opensMeasurableSpace_probabilityMeasure [OpensMeasurableSpace X]
    [HereditarilyLindelofSpace α] {g : α → ProbabilityMeasure X} (hg : IsInducing g)
    (hgm : Measurable g) : OpensMeasurableSpace α := by
  -- The weak topology is induced by the family of integrals of bounded continuous functions.
  let Φ : α → (X →ᵇ ℝ≥0) → ℝ≥0 := fun a ↦ (g a).toWeakDualBCNN
  -- The weak topology on `ProbabilityMeasure X` is by definition induced through
  -- `toFiniteMeasure` and `FiniteMeasure.toWeakDualBCNN` from the product topology on
  -- `(X →ᵇ ℝ≥0) → ℝ≥0`, so these three inducing statements hold by `rfl`.
  have hΦ : IsInducing Φ :=
    (IsInducing.mk (f := fun φ : WeakDual ℝ≥0 (X →ᵇ ℝ≥0) ↦ (φ : (X →ᵇ ℝ≥0) → ℝ≥0)) rfl).comp <|
      (IsInducing.mk (f := FiniteMeasure.toWeakDualBCNN (Ω := X)) rfl).comp <|
      (IsInducing.mk (f := ProbabilityMeasure.toFiniteMeasure (Ω := X)) rfl).comp hg
  have hΦm : Measurable Φ := measurable_pi_iff.2 fun f ↦ by
    simp only [Φ, ProbabilityMeasure.toWeakDualBCNN_apply]
    refine Measurable.ennreal_toNNReal ?_
    exact (Measure.measurable_lintegral (measurable_coe_nnreal_ennreal.comp
      f.continuous.measurable)).comp (measurable_subtype_coe.comp hgm)
  refine ⟨MeasurableSpace.generateFrom_le fun U hU ↦ ?_⟩
  obtain ⟨W, hW, rfl⟩ := hΦ.isOpen_iff.1 hU
  -- Each point of `Φ ⁻¹' W` lies in the preimage of a finite-dimensional open cylinder in `W`.
  have hcyl : ∀ a : Φ ⁻¹' W, ∃ V : Set α, IsOpen V ∧ MeasurableSet V ∧ (a : α) ∈ V ∧
      V ⊆ Φ ⁻¹' W := fun a ↦ by
    obtain ⟨I, u, hu, hsub⟩ := isOpen_pi_iff.1 hW _ a.2
    refine ⟨Φ ⁻¹' (I : Set (X →ᵇ ℝ≥0)).pi u, ?_, ?_, fun f hf ↦ (hu f hf).2,
      preimage_mono hsub⟩
    · exact (isOpen_set_pi I.finite_toSet fun f hf ↦ (hu f hf).1).preimage hΦ.continuous
    · exact hΦm (MeasurableSet.pi I.countable_toSet fun f hf ↦ (hu f hf).1.measurableSet)
  choose V hVo hVm hmem hsub using hcyl
  have hunion : ⋃ a, V a = Φ ⁻¹' W :=
    Subset.antisymm (iUnion_subset hsub) fun a ha ↦ mem_iUnion.2 ⟨⟨a, ha⟩, hmem _⟩
  -- Countably many of these cylinders already cover `Φ ⁻¹' W`.
  obtain ⟨t, htc, ht⟩ := eq_open_union_countable V hVo
  rw [← hunion, ← ht]
  exact MeasurableSet.biUnion htc fun a _ ↦ hVm a

/-- **A hereditarily Lindelöf space of laws is a Borel space.** Let `g : α → ProbabilityMeasure X`
be a topological inducing map, and give `α` the measurable structure pulled back along `g` from the
Giry σ-algebra. If `X` is a Borel space whose closed sets are approximated from outside by bounded
continuous functions, and `α` is hereditarily Lindelöf, then this measurable structure is the Borel
σ-algebra of `α`. -/
theorem Topology.IsInducing.borelSpace_probabilityMeasure [HasOuterApproxClosed X] [BorelSpace X]
    [HereditarilyLindelofSpace α] {g : α → ProbabilityMeasure X} (hg : IsInducing g)
    (hm : ‹MeasurableSpace α› = .comap g inferInstance) : BorelSpace α := by
  have hgm : Measurable g := by
    rw [hm]
    exact comap_measurable g
  have := hg.opensMeasurableSpace_probabilityMeasure hgm
  refine ⟨le_antisymm ?_ OpensMeasurableSpace.borel_le⟩
  rw [hm]
  -- The pulled-back structure is below the Borel one, since `g` is continuous.
  let : MeasurableSpace α := borel α
  have : BorelSpace α := ⟨rfl⟩
  exact hg.continuous.measurable_probabilityMeasure.comap_le

namespace EpsilonEridani.MeasureTheory.ProbabilityMeasure

variable [HasOuterApproxClosed X] [BorelSpace X]

/-- If the topology of weak convergence on `ProbabilityMeasure X` is hereditarily Lindelöf (for
instance second countable), then the Giry σ-algebra is its Borel σ-algebra. -/
instance borelSpace [HereditarilyLindelofSpace (ProbabilityMeasure X)] :
    BorelSpace (ProbabilityMeasure X) :=
  IsInducing.id.borelSpace_probabilityMeasure MeasurableSpace.comap_id.symm

/-- On a hereditarily Lindelöf (for instance second countable) set of laws, the Giry σ-algebra
inherited by the subtype is the Borel σ-algebra of the subspace topology. -/
instance borelSpace_subtype {S : Set (ProbabilityMeasure X)} [HereditarilyLindelofSpace S] :
    BorelSpace S :=
  IsInducing.subtypeVal.borelSpace_probabilityMeasure rfl

end EpsilonEridani.MeasureTheory.ProbabilityMeasure
