/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.MeasureTheory.Measure.ProbabilityMeasure
public import Mathlib.MeasureTheory.SetAlgebra
import Mathlib.MeasureTheory.Function.FactorsThrough

/-!
# Measurable coding of probability measures

The Giry measurable space on `ProbabilityMeasure α` is generated by evaluation on measurable
sets, but it is not currently available as a standard Borel space. When `α` is countably
generated, probability measures nevertheless admit a canonical measurable injective code into a
countable product of `ℝ≥0∞`: evaluate on the countable set algebra generated by Mathlib's chosen
`countableGeneratingSet α`.

This code lets probability arguments use a standard Borel target without imposing a topology on
`α`. Its coordinates generate the Giry measurable space, so every measurable function of a
probability measure into a nonempty standard Borel space factors measurably through the code.
Injectivity follows from uniqueness of finite measures on a generating set algebra.

## Main definitions and results

* `EpsilonEridani.MeasureTheory.ProbabilityMeasureCodeIndex` -- the countable generating set algebra;
* `EpsilonEridani.MeasureTheory.probabilityMeasureCode` -- evaluation on every member of that algebra;
* `EpsilonEridani.MeasureTheory.measurable_probabilityMeasureCode` -- measurability of the code;
* `EpsilonEridani.MeasureTheory.measurableSpace_probabilityMeasure_eq_comap_probabilityMeasureCode` --
  the Giry measurable space is induced by the code;
* `Measurable.exists_eq_measurable_comp_probabilityMeasureCode` -- measurable
  factorization through the code;
* `EpsilonEridani.MeasureTheory.probabilityMeasureCode_injective` -- the code determines the measure.
-/

public section

noncomputable section

open MeasureTheory MeasurableSpace

open scoped ENNReal

namespace EpsilonEridani

namespace MeasureTheory

variable {α : Type*} [MeasurableSpace α] [CountablyGenerated α]

/-- The countable index type used to code a probability measure: the set algebra generated by
Mathlib's chosen countable generating family for the measurable space. -/
abbrev ProbabilityMeasureCodeIndex (α : Type*) [MeasurableSpace α] [CountablyGenerated α] :=
  {s : Set α // s ∈ generateSetAlgebra (countableGeneratingSet α)}

instance instCountableProbabilityMeasureCodeIndex : Countable (ProbabilityMeasureCodeIndex α) :=
  Set.Countable.to_subtype (countable_generateSetAlgebra countable_countableGeneratingSet)

/-- The measurable evaluation code of a probability measure on a countably generated space. -/
def probabilityMeasureCode (P : ProbabilityMeasure α) : ProbabilityMeasureCodeIndex α → ℝ≥0∞ :=
  fun s => (P : Measure α) s.1

/-- Evaluation of the probability-measure code. -/
@[simp]
theorem probabilityMeasureCode_apply (P : ProbabilityMeasure α)
    (s : ProbabilityMeasureCodeIndex α) :
    probabilityMeasureCode P s = (P : Measure α) s.1 :=
  (rfl)

/-- Every member of the coding set algebra is measurable. -/
theorem measurableSet_probabilityMeasureCodeIndex (s : ProbabilityMeasureCodeIndex α) :
    MeasurableSet (s.1 : Set α) := by
  have hgen : (inferInstance : MeasurableSpace α) =
      generateFrom (generateSetAlgebra (countableGeneratingSet α)) := by
    simp only [generateFrom_generateSetAlgebra_eq, generateFrom_countableGeneratingSet]
  simpa only [MeasurableSet, hgen] using measurableSet_generateFrom s.2

/-- The evaluation code is measurable into its countable product space. -/
theorem measurable_probabilityMeasureCode : Measurable (probabilityMeasureCode (α := α)) :=
  Measurable.of_eval fun s =>
    (Measure.measurable_coe (measurableSet_probabilityMeasureCodeIndex s)).comp
      measurable_subtype_coe

/-- The Giry measurable space on probability measures over a countably generated space is the
pullback of the product measurable space along the canonical evaluation code. -/
theorem measurableSpace_probabilityMeasure_eq_comap_probabilityMeasureCode :
    (inferInstance : MeasurableSpace (ProbabilityMeasure α)) =
      MeasurableSpace.comap (probabilityMeasureCode (α := α)) inferInstance := by
  apply le_antisymm
  · let mProb : MeasurableSpace (ProbabilityMeasure α) := inferInstance
    let mCode : MeasurableSpace (ProbabilityMeasure α) :=
      MeasurableSpace.comap (probabilityMeasureCode (α := α)) inferInstance
    have hcode : @Measurable (ProbabilityMeasure α)
        (ProbabilityMeasureCodeIndex α → ℝ≥0∞) mCode inferInstance
        (probabilityMeasureCode (α := α)) :=
      Measurable.of_comap_le le_rfl
    have hmeasure : @Measurable (ProbabilityMeasure α) (Measure α) mCode inferInstance
        ProbabilityMeasure.toMeasure := by
      refine Measurable.measure_of_isPiSystem_of_isProbabilityMeasure
        (S := generateSetAlgebra (countableGeneratingSet α)) ?_ ?_ ?_
      · simp only [generateFrom_generateSetAlgebra_eq, generateFrom_countableGeneratingSet]
      · exact isSetAlgebra_generateSetAlgebra.isSetRing.isSetSemiring.isPiSystem
      · intro s hs
        convert (measurable_pi_apply ⟨s, hs⟩).comp hcode using 1
        ext P
        exact (probabilityMeasureCode_apply P ⟨s, hs⟩).symm
    have hid : @Measurable (ProbabilityMeasure α) (ProbabilityMeasure α) mCode mProb id := by
      exact hmeasure.subtype_mk (p := fun μ : Measure α => IsProbabilityMeasure μ)
    have hle := hid.comap_le
    simpa only [MeasurableSpace.comap_id] using hle
  · exact measurable_probabilityMeasureCode.comap_le

/-- A measurable function of a probability measure into a nonempty standard Borel space factors
measurably through its canonical code. The extension away from codes of actual probability
measures is not specified. -/
theorem _root_.Measurable.exists_eq_measurable_comp_probabilityMeasureCode
    {γ : Type*} [MeasurableSpace γ]
    [StandardBorelSpace γ] [Nonempty γ]
    {F : ProbabilityMeasure α → γ} (hF : Measurable F) :
    ∃ G : (ProbabilityMeasureCodeIndex α → ℝ≥0∞) → γ,
      Measurable G ∧ F = G ∘ probabilityMeasureCode := by
  have hF' : Measurable[MeasurableSpace.comap probabilityMeasureCode inferInstance] F := by
    rw [← measurableSpace_probabilityMeasure_eq_comap_probabilityMeasureCode (α := α)]
    exact hF
  exact hF'.exists_eq_measurable_comp

/-- The evaluation code determines a probability measure on a countably generated space. -/
theorem probabilityMeasureCode_injective :
    Function.Injective (probabilityMeasureCode (α := α)) := by
  intro P Q hPQ
  apply ProbabilityMeasure.toMeasure_injective
  let 𝒜 := generateSetAlgebra (countableGeneratingSet α)
  have hgen : (inferInstance : MeasurableSpace α) = generateFrom 𝒜 := by
    simp only [𝒜, generateFrom_generateSetAlgebra_eq, generateFrom_countableGeneratingSet]
  have hP : IsProbabilityMeasure (P : Measure α) := P.2
  refine ext_of_generate_finite 𝒜 hgen
    isSetAlgebra_generateSetAlgebra.isSetRing.isSetSemiring.isPiSystem
    (fun s hs => congrFun hPQ ⟨s, hs⟩) ?_
  exact hP.measure_univ.trans Q.2.measure_univ.symm

end MeasureTheory

end EpsilonEridani

end
