/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.NumberTheory.NumberField.Quadratic.Conjugation.Ambiguous.Basic
public import EpsilonEridani.NumberTheory.NumberField.RamifiedPrimes
import EpsilonEridani.NumberTheory.NumberField.Quadratic.Conjugation.Ambiguous.Structure

/-!
# Classes of ambiguous ideals are generated by ramified primes

Let `K` be a quadratic number field with quadratic conjugation `σ`. An ideal `I` of `𝓞 K` is
*ambiguous* when `σI = I`. This file draws the class-group consequence of the structure theorem for
ambiguous ideals: the class of an ambiguous ideal lies in the subgroup of `Cl(𝓞 K)` generated by the
classes of the primes above the ramified rational primes.

The work is done by `NumberField.exists_eq_span_singleton_mul_prod_of_map_eq_self`, which writes an
ambiguous ideal as `m 𝓞 K · ∏_{p ∈ s} Q p` with `m` a positive rational integer and `s` a finite set
of ramified rational primes. The rational factor is principal, so it contributes the trivial class,
and each remaining factor is one of the named generators.

Combined with the Hilbert-90 descent of `Quadratic/Conjugation/Ambiguous/Basic.lean`, which for a
totally complex `K` represents every `2`-torsion class by an ambiguous ideal, this says that
`Cl(𝓞 K)[2]` is generated by the classes of the ramified primes. The relation `∏ 𝔭 = (θ)` of
`EpsilonEridani.Multiquadratic.span_singleton_eq_prod_primeFactors` then removes one generator, bounding
the `2`-rank by `t - 1` for an imaginary quadratic field.

The genus-theoretic bound itself
(`EpsilonEridani.Multiquadratic.twoRank_le_ncard_ramifiedPrimes_sub_one`) is proved for a quadratic field
of *either* signature, so it runs through the narrow counterparts of these two statements —
`NumberField.NarrowClassGroup.mk0_mem_closure_of_map_eq_self` and
`NumberField.NarrowClassGroup.mem_closure_of_sq_eq_one` — which need no hypothesis on the signature.
What is recorded here is the ordinary form of the generation statement.

See F. Lemmermeyer, *Reciprocity Laws: From Euler to Eisenstein*, §2.2, and D. A. Cox, *Primes of
the Form x² + ny²*, §6.A, for the classical ambiguous class number formula.

## Main results

* `NumberField.classGroupMk0_mem_closure_of_map_eq_self`: the class of an ambiguous ideal is a
  product of classes of primes above ramified rational primes.
* `NumberField.mem_closure_of_sq_eq_one`: for a totally complex quadratic field, every `2`-torsion
  ideal class is such a product.
-/

public section

open Polynomial Ideal Module
open scoped NumberField nonZeroDivisors

namespace NumberField

variable {K : Type*} [Field K] [NumberField K] {θ : 𝓞 K} {d : ℤ}
  {Q : ℕ → (Ideal (𝓞 K))⁰}

/-- **The class of an ambiguous ideal is a product of classes of ramified primes.** Let `K` be a
quadratic number field with quadratic conjugation `σ`, and let `Q p` be a prime of `𝓞 K` above each
ramified rational prime `p`. If `σI = I` then the class of `I` lies in the subgroup of `Cl(𝓞 K)`
generated by the classes `[Q p]` for ramified `p`.

This is the class-group shadow of `exists_eq_span_singleton_mul_prod_of_map_eq_self`: the rational
factor of an ambiguous ideal is principal, so only the ramified primes survive. -/
theorem classGroupMk0_mem_closure_of_map_eq_self (hmin : minpoly ℤ θ = X ^ 2 - C d)
    (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤)
    (hprime : ∀ p ∈ ramifiedPrimes K, (Q p : Ideal (𝓞 K)).IsPrime)
    (hover : ∀ p ∈ ramifiedPrimes K,
      (Q p : Ideal (𝓞 K)).LiesOver (span {(p : ℤ)})) {I : (Ideal (𝓞 K))⁰}
    (hI : Ideal.map (ringOfIntegersQuadraticConj hmin hgen) (I : Ideal (𝓞 K)) =
      (I : Ideal (𝓞 K))) :
    ClassGroup.mk0 I ∈
      Subgroup.closure ((fun p ↦ ClassGroup.mk0 (Q p)) '' ramifiedPrimes K) := by
  classical
  obtain ⟨m, hm0, s, hs, hIeq⟩ :=
    exists_eq_span_singleton_mul_prod_of_map_eq_self hmin hgen hprime hover
      (mem_nonZeroDivisors_iff_ne_zero.mp I.2) hI
  have hmne : (m : 𝓞 K) ≠ 0 := Nat.cast_ne_zero.mpr hm0.ne'
  -- The rational factor, as an element of the monoid of nonzero ideals.
  set A : (Ideal (𝓞 K))⁰ := ⟨span {(m : 𝓞 K)}, mem_nonZeroDivisors_iff_ne_zero.mpr (by
    simpa [Ideal.zero_eq_bot, Ideal.span_singleton_eq_bot] using hmne)⟩ with hA
  have hIfact : I = A * ∏ p ∈ s, Q p := by
    refine Subtype.ext ?_
    rw [Submonoid.coe_mul, hA, Submonoid.coe_finsetProd]
    exact hIeq
  have hAone : ClassGroup.mk0 A = 1 :=
    (ClassGroup.mk0_eq_one_iff A.2).mpr ⟨(m : 𝓞 K), (submodule_span_eq).symm⟩
  rw [hIfact, map_mul, map_prod, hAone, one_mul]
  exact Subgroup.prod_mem _ fun p hp =>
    Subgroup.subset_closure ⟨p, hs (by exact_mod_cast hp), rfl⟩

/-- **The `2`-torsion of the class group of an imaginary quadratic field is generated by the
ramified primes.** A `2`-torsion class of a totally complex quadratic field is the class of an
ambiguous ideal (`exists_map_ringOfIntegersQuadraticConj_eq_self_of_sq_eq_one`, the Hilbert-90
descent step), and the class of an ambiguous ideal is a product of classes of ramified primes.

This generation result yields the genus-theoretic upper bound; it does not state the exact
ambiguous class number formula, whose real quadratic form also includes a unit index. Total
complexity is needed for the descent step, not for the generation lemma. -/
theorem mem_closure_of_sq_eq_one [IsTotallyComplex K] (hmin : minpoly ℤ θ = X ^ 2 - C d)
    (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤)
    (hprime : ∀ p ∈ ramifiedPrimes K, (Q p : Ideal (𝓞 K)).IsPrime)
    (hover : ∀ p ∈ ramifiedPrimes K,
      (Q p : Ideal (𝓞 K)).LiesOver (span {(p : ℤ)}))
    {Cl : ClassGroup (𝓞 K)} (hCl : Cl ^ 2 = 1) :
    Cl ∈ Subgroup.closure ((fun p ↦ ClassGroup.mk0 (Q p)) '' ramifiedPrimes K) := by
  obtain ⟨I, hIfix, rfl⟩ :=
    exists_map_ringOfIntegersQuadraticConj_eq_self_of_sq_eq_one hmin hgen hCl
  exact classGroupMk0_mem_closure_of_map_eq_self hmin hgen hprime hover hIfix

end NumberField
