/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.RingTheory.DedekindDomain.AdicValuation.IntegralClosure
public import EpsilonEridani.RingTheory.DiscreteValuationRing.Monogenic
import Mathlib.FieldTheory.Perfect

/-!
# Monogenicity of completed integer rings

Let `L/K` be an extension of fraction fields of Dedekind domains, and let `w` be a height-one
prime of the top ring above a height-one prime `v` of the base. When the residue fields are finite,
the ring of integers `𝒪_w` is generated by one element over `𝒪_v`.

The generator can simultaneously be viewed as an integral element which generates the local
field extension. This is the form needed to apply formulas for the different which use a
generator of both the integer ring and its fraction field.

## Main results

* The theorem `adjoin_adicCompletion_eq_top_of_adjoin_adicCompletionIntegers_eq_top` promotes
  any generator of the completed integer extension to a generator of the completed field
  extension.
* The theorem
  `exists_adjoin_adicCompletionIntegers_eq_top_and_isIntegral_and_adjoin_adicCompletion_eq_top`
  gives one element which generates the completed integer ring and the completed field extension,
  and is integral over the base completed integer ring.

## References

* [J.-P. Serre, *Corps locaux*][serre1968], Chapter III, §6, Proposition 12.
-/

public section
noncomputable section

open IsDedekindDomain
open scoped AdicCompletionExtension

namespace IsDedekindDomain.HeightOneSpectrum

variable {R : Type*} [CommRing R] [IsDedekindDomain R]
  {K : Type*} [Field K] [Algebra R K] [IsFractionRing R K]
  {B : Type*} [CommRing B] [IsDedekindDomain B] [Algebra R B]
  {L : Type*} [Field L] [Algebra K L] [Algebra R L] [IsScalarTower R K L]
  [Algebra B L] [IsFractionRing B L] [IsScalarTower R B L]
  (v : HeightOneSpectrum R) (w : HeightOneSpectrum B) [w.asIdeal.LiesOver v.asIdeal]
  [Finite (R ⧸ v.asIdeal)] [Finite (B ⧸ w.asIdeal)]

/-- A generator of the completed integer extension also generates the completed field extension. -/
theorem adjoin_adicCompletion_eq_top_of_adjoin_adicCompletionIntegers_eq_top
    (x : w.adicCompletionIntegers L)
    (hx : Algebra.adjoin (v.adicCompletionIntegers K) {x} = ⊤) :
    Algebra.adjoin (v.adicCompletion K) {(x : w.adicCompletion L)} = ⊤ := by
  rw [← Algebra.algebraMap_ofSubsemiring_apply (w.adicCompletionIntegers L) x]
  exact Algebra.adjoin_eq_top_of_intermediateField
    (fun y _ ↦ Algebra.IsAlgebraic.isAlgebraic y)
    (EpsilonEridani.IntermediateField.adjoin_eq_top_of_algebra_adjoin_eq_top hx)

/-- When both residue fields are finite, the completed integer ring `𝒪_w` is generated over
`𝒪_v` by an element which is also an integral generator of the field extension. -/
theorem
    exists_adjoin_adicCompletionIntegers_eq_top_and_isIntegral_and_adjoin_adicCompletion_eq_top :
    ∃ x : w.adicCompletionIntegers L,
      Algebra.adjoin (v.adicCompletionIntegers K) {x} = ⊤ ∧
      IsIntegral (v.adicCompletionIntegers K) x ∧
      Algebra.adjoin (v.adicCompletion K) {(x : w.adicCompletion L)} = ⊤ := by
  let _ : IsLocalHom (algebraMap (v.adicCompletionIntegers K)
      (w.adicCompletionIntegers L)) := isLocalHom_algebraMap_adicCompletionIntegers K L v w
  let _ : Finite (IsLocalRing.ResidueField (v.adicCompletionIntegers K)) :=
    Finite.of_equiv _ (v.residueFieldEquivAdicCompletionIntegers (K := K)).toEquiv
  let _ : Algebra.IsSeparable
      (IsLocalRing.ResidueField (v.adicCompletionIntegers K))
      (IsLocalRing.ResidueField (w.adicCompletionIntegers L)) := by
    infer_instance
  let ⟨pb⟩ := EpsilonEridani.IsDiscreteValuationRing.nonempty_powerBasis
    (R := v.adicCompletionIntegers K) (S := w.adicCompletionIntegers L)
  refine ⟨pb.gen, pb.adjoin_gen_eq_top, pb.isIntegral_gen, ?_⟩
  exact adjoin_adicCompletion_eq_top_of_adjoin_adicCompletionIntegers_eq_top
    (K := K) (L := L) v w pb.gen pb.adjoin_gen_eq_top

end IsDedekindDomain.HeightOneSpectrum
