/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.AlgebraicGeometry.EllipticCurve.MinimalModel.DiscriminantIdeal
public import EpsilonEridani.AlgebraicGeometry.EllipticCurve.MinimalModel.ObstructionExponent
public import Mathlib.RingTheory.ClassGroup.Basic
import Mathlib.Algebra.FiniteSupport.Basic
import EpsilonEridani.AlgebraicGeometry.EllipticCurve.IntegralModel
import EpsilonEridani.RingTheory.DedekindDomain.Factorization

/-!
# The defect ideal of an integral Weierstrass equation

Let `O` be a Dedekind domain with fraction field `K`, and let `W` be an integral elliptic
Weierstrass equation over `O`. Its local obstruction exponents

`fᵥ(W) = (v(Δ W) - v(Δ_min,ᵥ)) / 12`

are nonnegative integers. This file assembles them into the **defect ideal**

`𝔍_W = ∏ᵥ 𝔭ᵥ ^ fᵥ(W)`.

The product is finite because each exponent is bounded by the multiplicity of `𝔭ᵥ` in the
nonzero principal ideal generated by `Δ W`. Its characteristic identity is

`(Δ W) = 𝔇_{E/K} · 𝔍_W ^ 12`,

where `𝔇_{E/K}` is the minimal discriminant ideal. Thus the defect ideal records exactly the
failure of an integral equation to be globally minimal; in particular it is the unit ideal
precisely for globally minimal equations.

## Main definitions

* `WeierstrassCurve.weierstrassDefectIdeal`: the ideal `∏ᵥ 𝔭ᵥ ^ fᵥ(W)`.

## Main results

* `WeierstrassCurve.hasFiniteMulSupport_pow_obstructionExponentAt_toNat`: the defining product
  has finite support.
* `WeierstrassCurve.weierstrassDefectIdeal_ne_bot`: the defect ideal is nonzero.
* `WeierstrassCurve.count_weierstrassDefectIdeal_eq_obstructionExponentAt`: the exponent of
  `𝔭ᵥ` in the defect ideal is `fᵥ(W)`.
* `WeierstrassCurve.coe_weierstrassDefectIdeal_smul_mul_toPrincipalIdeal`: the transformation
  formula for defect ideals.
* `WeierstrassCurve.span_Δ_eq_minimalDiscriminantIdeal_mul_weierstrassDefectIdeal_pow_twelve`:
  the discriminant ideal factors as `𝔇_{E/K} · 𝔍_W ^ 12`.
* `WeierstrassCurve.weierstrassDefectIdeal_eq_top_iff_isGlobalMinimal`: the defect ideal is the
  unit ideal exactly when the equation is globally minimal.

## References

* [J. Silverman, *The Arithmetic of Elliptic Curves*][silverman2009], VIII.8.
-/

public section

namespace WeierstrassCurve

open IsDedekindDomain IsDedekindDomain.HeightOneSpectrum
open scoped nonZeroDivisors

variable (O : Type*) [CommRing O] [IsDedekindDomain O]
  {K : Type*} [Field K] [Algebra O K] [IsFractionRing O K]

/-- **The exponent of `𝔭ᵥ` in the discriminant ideal is the local minimal exponent plus twelve
times the local obstruction exponent.** This integer-valued identity holds for any elliptic
equation with a global integral representative `d` of its discriminant; the equation itself need
not be integral. -/
theorem count_span_Δ_eq_localMinimalDiscriminantValuation_add_twelve_mul_obstructionExponentAt
    (W : WeierstrassCurve K) (v : HeightOneSpectrum O) [W.IsElliptic] {d : O}
    (hd : algebraMap O K d = W.Δ) :
    ((Associates.mk v.asIdeal).count (Associates.mk (Ideal.span {d})).factors : ℤ) =
      (W.localMinimalDiscriminantValuation (Localization.AtPrime v.asIdeal) : ℤ) +
        12 * obstructionExponentAt O v W := by
  have hcount := count_span_Δ_eq_ord_Δ W v hd
  have hdef := twelve_mul_obstructionExponentAt O v W
  omega

/-- **For an equation integral at `v`, the primewise discriminant-defect identity in natural
exponents.** Local integrality makes the obstruction exponent nonnegative, so taking `toNat`
loses no information. -/
theorem
    count_span_Δ_eq_localMinimalDiscriminantValuation_add_twelve_mul_obstructionExponentAt_toNat
    (W : WeierstrassCurve K) (v : HeightOneSpectrum O) [W.IsElliptic]
    [IsIntegral (Localization.AtPrime v.asIdeal) W] {d : O} (hd : algebraMap O K d = W.Δ) :
    (Associates.mk v.asIdeal).count (Associates.mk (Ideal.span {d})).factors =
      W.localMinimalDiscriminantValuation (Localization.AtPrime v.asIdeal) +
        12 * (obstructionExponentAt O v W).toNat := by
  have hnonneg := obstructionExponentAt_nonneg_of_isIntegral O v W
  have hsplit :=
    count_span_Δ_eq_localMinimalDiscriminantValuation_add_twelve_mul_obstructionExponentAt
      O W v hd
  omega

/-- **Only finitely many local obstruction exponents of an integral equation are nonzero.**
Equivalently, the prime-power family defining the defect ideal has finite multiplicative
support. -/
theorem hasFiniteMulSupport_pow_obstructionExponentAt_toNat (W : WeierstrassCurve K)
    [W.IsElliptic] [IsIntegral O W] :
    Function.HasFiniteMulSupport fun v : HeightOneSpectrum O =>
      v.asIdeal ^ (obstructionExponentAt O v W).toNat := by
  obtain ⟨d, hd⟩ := Δ_integral_of_isIntegral O W
  have hspan : Ideal.span {d} ≠ 0 :=
    Submodule.span_singleton_eq_bot.mp.mt fun h =>
      W.isUnit_Δ.ne_zero (by rw [← hd, h, map_zero])
  refine Ideal.hasFiniteMulSupport_asIdeal_pow_of_le_count hspan _ fun v => ?_
  have : IsIntegral (Localization.AtPrime v.asIdeal) W :=
    IsIntegral.of_isScalarTower (R := O) W
  have hsplit :=
    count_span_Δ_eq_localMinimalDiscriminantValuation_add_twelve_mul_obstructionExponentAt_toNat
      O W v hd
  omega

/-- **The defect ideal** `𝔍_W = ∏ᵥ 𝔭ᵥ ^ fᵥ(W)` of an integral Weierstrass equation.
Integrality makes every local obstruction exponent nonnegative, so its natural-number part loses
no information. The product ranges over the finite support certified by
`hasFiniteMulSupport_pow_obstructionExponentAt_toNat`, which is how the construction consumes
integrality; `weierstrassDefectIdeal_def` recovers the `finprod` over all height-one primes. -/
noncomputable def weierstrassDefectIdeal (W : WeierstrassCurve K) [W.IsElliptic]
    [IsIntegral O W] : Ideal O :=
  let h := hasFiniteMulSupport_pow_obstructionExponentAt_toNat O W
  ∏ v ∈ h.toFinset, v.asIdeal ^ (obstructionExponentAt O v W).toNat

/-- The defining prime-power factorisation of the defect ideal, as a product over all height-one
primes. -/
theorem weierstrassDefectIdeal_def (W : WeierstrassCurve K) [W.IsElliptic]
    [IsIntegral O W] :
    weierstrassDefectIdeal O W =
      ∏ᶠ v : HeightOneSpectrum O, v.asIdeal ^ (obstructionExponentAt O v W).toNat := by
  rw [weierstrassDefectIdeal,
    finprod_eq_prod _ (hasFiniteMulSupport_pow_obstructionExponentAt_toNat O W)]

/-- **The defect ideal is nonzero.** -/
theorem weierstrassDefectIdeal_ne_bot (W : WeierstrassCurve K) [W.IsElliptic]
    [IsIntegral O W] : weierstrassDefectIdeal O W ≠ 0 := by
  rw [weierstrassDefectIdeal_def,
    finprod_eq_prod _ (hasFiniteMulSupport_pow_obstructionExponentAt_toNat O W)]
  exact Finset.prod_ne_zero_iff.2 fun v _ => pow_ne_zero _ v.ne_bot

/-- **The exponent of `𝔭ᵥ` in the defect ideal is the local obstruction exponent
`fᵥ(W)`.** The cast to `ℤ` reflects that `obstructionExponentAt` is defined for arbitrary rational
equations, while ideal multiplicities are natural numbers. -/
@[simp]
theorem count_weierstrassDefectIdeal_eq_obstructionExponentAt
    (W : WeierstrassCurve K) (v : HeightOneSpectrum O) [W.IsElliptic] [IsIntegral O W] :
    ((Associates.mk v.asIdeal).count
      (Associates.mk (weierstrassDefectIdeal O W)).factors : ℤ) =
      obstructionExponentAt O v W := by
  have hexp : ∀ᶠ w : HeightOneSpectrum O in Filter.cofinite,
      ((obstructionExponentAt O w W).toNat : ℤ) = 0 := by
    rw [Filter.eventually_cofinite]
    refine (hasFiniteMulSupport_pow_obstructionExponentAt_toNat O W).subset fun w hw => ?_
    simp only [Set.mem_ofPred_eq, Int.natCast_eq_zero, Function.mem_mulSupport, ne_eq,
      Ideal.one_eq_top, Ideal.pow_eq_top_iff, w.isPrime.ne_top, false_or] at hw ⊢
    exact hw
  rw [← FractionalIdeal.count_coe K v (weierstrassDefectIdeal_ne_bot O W),
    weierstrassDefectIdeal_def, FractionalIdeal.coeIdeal_finprod (nonZeroDivisors O) K le_rfl]
  simp_rw [FractionalIdeal.coeIdeal_pow, ← zpow_natCast]
  rw [FractionalIdeal.count_finprod K v _ hexp]
  have : IsIntegral (Localization.AtPrime v.asIdeal) W :=
    IsIntegral.of_isScalarTower (R := O) W
  exact Int.toNat_of_nonneg (obstructionExponentAt_nonneg_of_isIntegral O v W)

/-- **The defect ideals of two integral equations related by `C` differ by the principal
fractional ideal generated by `C.u`:** `𝔍_(C • W) · (C.u) = 𝔍_W`.

Primewise, this is the change-of-variables identity
`f_v(C • W) + ord_v(C.u) = f_v(W)`. The equation is stated in fractional ideals because `C.u`
need not lie in `O`. -/
theorem coe_weierstrassDefectIdeal_smul_mul_toPrincipalIdeal
    (W : WeierstrassCurve K) [W.IsElliptic]
    (C : VariableChange K) [IsIntegral O W] [IsIntegral O (C • W)] :
    (weierstrassDefectIdeal O (C • W) : FractionalIdeal O⁰ K) *
        (toPrincipalIdeal O K C.u : FractionalIdeal O⁰ K) =
      (weierstrassDefectIdeal O W : FractionalIdeal O⁰ K) := by
  let I : (FractionalIdeal O⁰ K)ˣ := FractionalIdeal.mk0 K
    ⟨weierstrassDefectIdeal O (C • W),
      mem_nonZeroDivisors_iff_ne_zero.mpr (weierstrassDefectIdeal_ne_bot O (C • W))⟩
  let J : (FractionalIdeal O⁰ K)ˣ := FractionalIdeal.mk0 K
    ⟨weierstrassDefectIdeal O W,
      mem_nonZeroDivisors_iff_ne_zero.mpr (weierstrassDefectIdeal_ne_bot O W)⟩
  have hI : (I : FractionalIdeal O⁰ K) =
      (weierstrassDefectIdeal O (C • W) : FractionalIdeal O⁰ K) := by
    rfl
  have hJ : (J : FractionalIdeal O⁰ K) =
      (weierstrassDefectIdeal O W : FractionalIdeal O⁰ K) := by
    rfl
  have hcount (v : HeightOneSpectrum O) :
      FractionalIdeal.count K v
          ((I * toPrincipalIdeal O K C.u : (FractionalIdeal O⁰ K)ˣ) :
            FractionalIdeal O⁰ K) =
        FractionalIdeal.count K v (J : FractionalIdeal O⁰ K) := by
    rw [Units.val_mul, FractionalIdeal.count_mul K v I.ne_zero
      (toPrincipalIdeal O K C.u).ne_zero,
      FractionalIdeal.count_toPrincipalIdeal_eq_neg_log_valuation, hI, hJ,
      FractionalIdeal.count_coe K v (weierstrassDefectIdeal_ne_bot O (C • W)),
      FractionalIdeal.count_coe K v (weierstrassDefectIdeal_ne_bot O W),
      count_weierstrassDefectIdeal_eq_obstructionExponentAt,
      count_weierstrassDefectIdeal_eq_obstructionExponentAt,
      obstructionExponentAt_smul, Valuation.ord_def]
    ring
  have hunit : I * toPrincipalIdeal O K C.u = J := by
    rw [FractionalIdeal.finprod_unitOfPrime_zpow_count (I * toPrincipalIdeal O K C.u),
      FractionalIdeal.finprod_unitOfPrime_zpow_count J]
    apply finprod_congr
    exact fun v ↦ by rw [hcount v]
  exact congrArg Units.val hunit

variable {O}

/-- **The discriminant ideal of an integral equation is its minimal discriminant ideal times the
twelfth power of its defect ideal:** `(Δ W) = 𝔇_{E/K} · 𝔍_W ^ 12`. -/
theorem span_Δ_eq_minimalDiscriminantIdeal_mul_weierstrassDefectIdeal_pow_twelve
    (W : WeierstrassCurve K) [W.IsElliptic] [IsIntegral O W] {d : O}
    (hd : algebraMap O K d = W.Δ) :
    Ideal.span {d} = minimalDiscriminantIdeal O W * weierstrassDefectIdeal O W ^ 12 := by
  have hspan : Ideal.span {d} ≠ 0 :=
    Submodule.span_singleton_eq_bot.mp.mt fun h =>
      W.isUnit_Δ.ne_zero (by rw [← hd, h, map_zero])
  have hminSupport := hasFiniteMulSupport_pow_localMinimalDiscriminantValuation O W
  have hdefectSupport := hasFiniteMulSupport_pow_obstructionExponentAt_toNat O W
  have hdefectPowSupport :
      Function.HasFiniteMulSupport fun v : HeightOneSpectrum O =>
        (v.asIdeal ^ (obstructionExponentAt O v W).toNat) ^ 12 :=
    Function.HasFiniteMulSupport.fun_comp hdefectSupport (one_pow 12)
  calc
    Ideal.span {d} = ∏ᶠ v : HeightOneSpectrum O, v.maxPowDividing (Ideal.span {d}) :=
      (Ideal.finprod_heightOneSpectrum_factorization hspan).symm
    _ = ∏ᶠ v : HeightOneSpectrum O,
        v.asIdeal ^ W.localMinimalDiscriminantValuation (Localization.AtPrime v.asIdeal) *
          (v.asIdeal ^ (obstructionExponentAt O v W).toNat) ^ 12 := by
      apply finprod_congr
      intro v
      rw [HeightOneSpectrum.maxPowDividing, ← pow_mul, ← pow_add]
      congr 1
      have : IsIntegral (Localization.AtPrime v.asIdeal) W :=
        IsIntegral.of_isScalarTower (R := O) W
      have hsplit :=
        count_span_Δ_eq_localMinimalDiscriminantValuation_add_twelve_mul_obstructionExponentAt_toNat
          O W v hd
      omega
    _ = (∏ᶠ v : HeightOneSpectrum O,
          v.asIdeal ^ W.localMinimalDiscriminantValuation (Localization.AtPrime v.asIdeal)) *
        ∏ᶠ v : HeightOneSpectrum O,
          (v.asIdeal ^ (obstructionExponentAt O v W).toNat) ^ 12 :=
      finprod_mul_distrib hminSupport hdefectPowSupport
    _ = minimalDiscriminantIdeal O W * weierstrassDefectIdeal O W ^ 12 := by
      rw [minimalDiscriminantIdeal_def, weierstrassDefectIdeal_def,
        finprod_pow hdefectSupport 12]

/-- **An integral equation has trivial defect ideal exactly when it is globally minimal.** -/
@[simp]
theorem weierstrassDefectIdeal_eq_top_iff_isGlobalMinimal (W : WeierstrassCurve K)
    [W.IsElliptic] [IsIntegral O W] :
    weierstrassDefectIdeal O W = ⊤ ↔ IsGlobalMinimal O W := by
  rw [isGlobalMinimal_iff_obstructionExponentAt_eq_zero O W]
  constructor
  · intro h v
    have hc := count_weierstrassDefectIdeal_eq_obstructionExponentAt O W v
    rw [h, ← Ideal.one_eq_top, Associates.mk_one, Associates.factors_one,
      Associates.count_zero v.associates_irreducible, Nat.cast_zero] at hc
    exact hc.symm
  · intro h
    have hz (v : HeightOneSpectrum O) : (obstructionExponentAt O v W).toNat = 0 := by
      rw [h v]
      norm_num
    rw [weierstrassDefectIdeal_def]
    simp only [hz, pow_zero]
    simpa only [← Ideal.one_eq_top] using
      (finprod_one : (∏ᶠ _ : HeightOneSpectrum O, (1 : Ideal O)) = 1)

end WeierstrassCurve

end
