/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.AlgebraicGeometry.EllipticCurve.MinimalModel.Basic

/-!
# The local minimal discriminant ideal

Let `R` be a discrete valuation ring with fraction field `K`. The discriminant of an integral
minimal Weierstrass equation over `K` belongs to `R`, and the principal ideal it generates is
independent of the chosen minimal equation. This file packages that ideal as
`WeierstrassCurve.localMinimalDiscriminant`.

Mathlib's `WeierstrassCurve.minimal` chooses one minimal equation in the variable-change orbit.
The definition uses that choice, while `localMinimalDiscriminant_eq_span_Δ` is the choice-free
interface: any integral minimal equation in the same orbit generates the same ideal. The reason is
that two minimal equations have equal discriminant valuation; over a discrete valuation ring their
discriminants therefore differ by a unit. In particular the ideal is invariant under every change
of variables of the original equation.

This is the local invariant whose products over the height-one primes form the minimal
discriminant ideal over a Dedekind domain. For an elliptic curve it is nonzero. The later global
comparison with an arbitrary integral equation additionally records the excess valuation in
multiples of twelve; no obstruction exponent is defined here.

## Main definitions

* `WeierstrassCurve.localMinimalDiscriminant`: the principal ideal generated by the discriminant
  of a local minimal equation.

## Main results

* `WeierstrassCurve.associated_integralModel_Δ_of_isMinimal_smul`: minimal equations in the same
  variable-change orbit have associated integral discriminants.
* `WeierstrassCurve.localMinimalDiscriminant_eq_span_Δ`: any such minimal equation computes the
  local minimal discriminant.
* `WeierstrassCurve.localMinimalDiscriminant_smul`: the ideal is invariant under a change of
  variables.
* `WeierstrassCurve.localMinimalDiscriminant_ne_bot`: an elliptic curve has nonzero local minimal
  discriminant.
* `WeierstrassCurve.localMinimalDiscriminant_eq_top_iff`: the ideal is trivial exactly at good
  reduction.

The mathematics is Silverman, *The Arithmetic of Elliptic Curves*, VII.1.
-/

public section

namespace WeierstrassCurve

open IsDiscreteValuationRing IsDedekindDomain.HeightOneSpectrum

variable (R : Type*) [CommRing R] [IsDomain R] [IsDiscreteValuationRing R]
  {K : Type*} [Field K] [Algebra R K] [IsFractionRing R K]

/-- **The local minimal discriminant ideal.** It is the principal ideal of `R` generated by the
discriminant of a minimal integral equation in the variable-change orbit of `W`.

The definition uses Mathlib's chosen `W.minimal R`; use `localMinimalDiscriminant_eq_span_Δ` to
compute it from any minimal equation in the same orbit. -/
noncomputable def localMinimalDiscriminant (W : WeierstrassCurve K) : Ideal R :=
  Ideal.span {((W.minimal R).integralModel R).Δ}

/-- **Minimal equations in one variable-change orbit have associated integral discriminants.**
Their discriminants have the same valuation in `K`; equality of valuations in a discrete
valuation ring says exactly that their lifts to `R` differ by a unit. -/
theorem associated_integralModel_Δ_of_isMinimal_smul
    {W₁ W₂ : WeierstrassCurve K} [IsMinimal R W₁] [IsMinimal R W₂]
    (D : VariableChange K) (hD : D • W₁ = W₂) :
    Associated (W₁.integralModel R).Δ (W₂.integralModel R).Δ := by
  obtain ⟨u, hu⟩ := associated_of_valuation_eq W₁.Δ W₂.Δ
    (valuation_Δ_eq_of_isMinimal_smul R D hD).symm
  refine ⟨u, ?_⟩
  apply IsFractionRing.injective R K
  rw [map_mul, integralModel_Δ_eq R W₁, integralModel_Δ_eq R W₂]
  simpa [Units.smul_def, Algebra.smul_def, mul_comm] using hu

/-- **Every minimal equation in the orbit computes the local minimal discriminant.** If `W'` is
minimal and `D` carries `W` to `W'`, then the chosen minimal equation and `W'` have associated
integral discriminants, hence generate the same ideal of `R`. -/
theorem localMinimalDiscriminant_eq_span_Δ (W : WeierstrassCurve K)
    {W' : WeierstrassCurve K} [IsMinimal R W']
    (D : VariableChange K) (hD : D • W = W') :
    W.localMinimalDiscriminant R = Ideal.span {(W'.integralModel R).Δ} := by
  obtain ⟨C, hC⟩ := W.exists_smul_eq_minimal R
  have hE : (D * C⁻¹) • W.minimal R = W' := by
    rw [← hC, mul_smul, inv_smul_smul, hD]
  rw [localMinimalDiscriminant, Ideal.span_singleton_eq_span_singleton]
  exact associated_integralModel_Δ_of_isMinimal_smul R _ hE

/-- **The local minimal discriminant is invariant under a change of variables.** It depends on
the curve presented by a Weierstrass equation, not on that presentation. -/
@[simp]
theorem localMinimalDiscriminant_smul (D : VariableChange K) (W : WeierstrassCurve K) :
    (D • W).localMinimalDiscriminant R = W.localMinimalDiscriminant R := by
  obtain ⟨C, hC⟩ := W.exists_smul_eq_minimal R
  rw [localMinimalDiscriminant_eq_span_Δ R (D • W) (C * D⁻¹)
    (by rw [mul_smul, inv_smul_smul, hC]), localMinimalDiscriminant]

/-- **An elliptic curve has nonzero local minimal discriminant.** Its chosen minimal equation is
again elliptic, so its discriminant, and therefore its lift to `R`, is nonzero. -/
theorem localMinimalDiscriminant_ne_bot (W : WeierstrassCurve K) [W.IsElliptic] :
    W.localMinimalDiscriminant R ≠ ⊥ := by
  rw [localMinimalDiscriminant, ne_eq, Ideal.span_singleton_eq_bot]
  intro hΔ
  have hmap := congrArg (algebraMap R K) hΔ
  rw [integralModel_Δ_eq R (W.minimal R)] at hmap
  have hminimalΔ : (W.minimal R).Δ ≠ 0 := by
    obtain ⟨C, hC⟩ := W.exists_smul_eq_minimal R
    rw [← hC, variableChange_Δ]
    exact mul_ne_zero (pow_ne_zero _ (Units.ne_zero _)) W.isUnit_Δ.ne_zero
  exact hminimalΔ (by simpa using hmap)

/-- **The local minimal discriminant is the unit ideal exactly at good reduction.** This reads
good reduction from the curve-level ideal rather than from a chosen minimal equation. -/
theorem localMinimalDiscriminant_eq_top_iff (W : WeierstrassCurve K) :
    W.localMinimalDiscriminant R = ⊤ ↔ (W.minimal R).HasGoodReduction R := by
  rw [localMinimalDiscriminant, Ideal.span_singleton_eq_top,
    hasGoodReduction_iff_isElliptic_reduction]
  simp only [reduction, isElliptic_iff, map_Δ, isUnit_iff_ne_zero, ne_eq,
    IsLocalRing.residue_eq_zero_iff]
  rw [IsLocalRing.mem_maximalIdeal, mem_nonunits_iff, not_not]

end WeierstrassCurve

end
