/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.LinearAlgebra.IntegralLattice.Overlattice.Index
public import EpsilonEridani.LinearAlgebra.IntegralLattice.RootLattice.TypeD.Basic

/-!
# The spinor glue enlargement of the checkerboard lattice in rank eight

This file constructs the lattice `D₈⁺` by gluing the rank-eight checkerboard lattice along its
spinor class.  The gluing subgroup is the cyclic subgroup generated by the Conway--Sloane spinor
class in the discriminant group of `D₈`.  Its inverse image is identified literally as

```text
D₈⁺ = D₈ ∪ (s + D₈),
```

where `s = (1/2, ..., 1/2)`.  The spinor class has order two and quadratic value zero, so the
inverse image is an even lattice of index two.  The overlattice discriminant formula then shows
that `D₈⁺` has discriminant one and is unimodular.

The subsequent identification of this coordinate lattice with the positive `E₈` root lattice
requires the exceptional-root-lattice bridge and is deliberately separate.  The definitions here
use the same spinor representative as the type `D` discriminant-form calculation, so that bridge
does not need a change of coordinates.

## Main declarations

* `EpsilonEridani.IntegralLattice.d8SpinorSubgroup`: the order-two subgroup generated by the spinor
  class in `A_{D₈}`.
* `EpsilonEridani.IntegralLattice.d8PlusCarrier`: its inverse image in the dual of `D₈`.
* `EpsilonEridani.IntegralLattice.mem_d8PlusCarrier_iff`: the formula
  `D₈⁺ = D₈ ∪ (s + D₈)`.
* `EpsilonEridani.IntegralLattice.d8PlusLattice`: the resulting even integral lattice.
* `EpsilonEridani.IntegralLattice.toIntegralLattice_eq_d8PlusLattice`: the general glued-overlattice
  construction along the spinor subgroup is `d8PlusLattice`.
* `EpsilonEridani.IntegralLattice.isPosDef_d8PlusLattice`: `D₈⁺` is positive definite.
* `EpsilonEridani.IntegralLattice.isUnimodular_d8PlusLattice`: `D₈⁺` is unimodular.

## References

* J. H. Conway and N. J. A. Sloane, *Sphere Packings, Lattices and Groups*, §4.8.1.
* V. V. Nikulin, *Integral symmetric bilinear forms and some of their applications*, §1.4,
  Proposition 1.4.1.
* W. Ebeling, *Lattices and Codes*, Chapter 3.
* `EpsilonEridaniRoadmap/IntegralLattices/README.md`, Layer 5, the `D₈ ⊂ E₈` glue calculation.
* `EpsilonEridaniRoadmap/IntegralLattices/Suggested.lean` (`d8SpinorSubgroup`,
  `natCard_d8SpinorSubgroup`, `d8Plus`, `d8Plus_isUnimodular`).
-/

public section

namespace EpsilonEridani

namespace IntegralLattice

private theorem even_eight : Even 8 := ⟨4, by omega⟩

/-- The glue subgroup of `A_{D₈}` generated by the Conway--Sloane spinor class. -/
noncomputable def d8SpinorSubgroup :
    AddSubgroup (checkerboardLattice 8).DiscriminantGroup :=
  AddSubgroup.zmultiples (checkerboardSpinorClass 8)

/-- A discriminant class belongs to the spinor glue subgroup exactly when it is zero or the
spinor class. -/
@[simp]
theorem mem_d8SpinorSubgroup_iff
    (x : (checkerboardLattice 8).DiscriminantGroup) :
    x ∈ d8SpinorSubgroup ↔ x = 0 ∨ x = checkerboardSpinorClass 8 := by
  simpa only [d8SpinorSubgroup] using
    mem_zmultiples_checkerboardSpinorClass_iff 8 even_eight x

/-- The spinor glue subgroup has order two. -/
theorem natCard_d8SpinorSubgroup : Nat.card d8SpinorSubgroup = 2 := by
  rw [d8SpinorSubgroup, Nat.card_zmultiples,
    addOrderOf_checkerboardSpinorClass_of_even 8 even_eight]

/-- The intermediate carrier obtained by gluing `D₈` along its spinor class. -/
noncomputable def d8PlusCarrier : (checkerboardLattice 8).IntermediateCarrier :=
  (checkerboardLattice 8).intermediateCarrierOfDiscriminantSubgroup d8SpinorSubgroup

/-- A vector belongs to `D₈⁺` exactly when it belongs to `D₈`, or differs from the spinor vector
by an element of `D₈`.  This is the literal coordinate formula
`D₈⁺ = D₈ ∪ (s + D₈)`. -/
@[simp]
theorem mem_d8PlusCarrier_iff (x : Fin 8 → ℚ) :
    x ∈ d8PlusCarrier.1 ↔
      x ∈ (checkerboardLattice 8).carrier ∨
        x - checkerboardSpinor 8 ∈ (checkerboardLattice 8).carrier := by
  rw [d8PlusCarrier,
    (checkerboardLattice 8).mem_intermediateCarrierOfDiscriminantSubgroup_iff]
  constructor
  · rintro ⟨hxdual, hx⟩
    rw [mem_d8SpinorSubgroup_iff] at hx
    rcases hx with hx | hx
    · left
      exact ((checkerboardLattice 8).discriminantGroup_mk_eq_zero_iff
        ⟨x, hxdual⟩).mp hx
    · right
      rw [checkerboardSpinorClass_def] at hx
      exact ((checkerboardLattice 8).discriminantGroup_mk_eq_iff
        ⟨x, hxdual⟩ ⟨checkerboardSpinor 8, checkerboardSpinor_mem_dualCarrier⟩).mp hx
  · rintro (hx | hx)
    · have hxdual := (checkerboardLattice 8).le_dualCarrier hx
      refine ⟨hxdual, ?_⟩
      rw [mem_d8SpinorSubgroup_iff]
      left
      exact ((checkerboardLattice 8).discriminantGroup_mk_eq_zero_iff
        ⟨x, hxdual⟩).mpr hx
    · have hxdiff := (checkerboardLattice 8).le_dualCarrier hx
      have hxdual : x ∈ (checkerboardLattice 8).dualCarrier := by
        have hadd := (checkerboardLattice 8).dualCarrier.add_mem hxdiff
          checkerboardSpinor_mem_dualCarrier
        simpa only [sub_add_cancel] using hadd
      refine ⟨hxdual, ?_⟩
      rw [mem_d8SpinorSubgroup_iff]
      right
      rw [checkerboardSpinorClass_def]
      exact ((checkerboardLattice 8).discriminantGroup_mk_eq_iff
        ⟨x, hxdual⟩ ⟨checkerboardSpinor 8, checkerboardSpinor_mem_dualCarrier⟩).mpr hx

/-- The discriminant subgroup cut out by `d8PlusCarrier` is the spinor glue subgroup. -/
@[simp]
theorem discriminantSubgroup_d8PlusCarrier :
    (checkerboardLattice 8).discriminantSubgroup d8PlusCarrier = d8SpinorSubgroup := by
  rw [d8PlusCarrier,
    (checkerboardLattice 8).discriminantSubgroup_intermediateCarrierOfDiscriminantSubgroup]

/-- The rank-eight spinor class has quadratic value zero. -/
theorem d8SpinorClass_quadratic_eq_zero :
    (checkerboardLattice 8).discriminantQuadraticMap (isEven_checkerboardLattice 8)
      (checkerboardSpinorClass 8) = 0 := by
  rw [discriminantQuadraticMap_checkerboardSpinorClass]
  norm_num

/-- The spinor glue subgroup is quadratic-isotropic. -/
theorem isIsotropic_d8SpinorSubgroup :
    ((checkerboardLattice 8).discriminantQuadraticModule
      (isEven_checkerboardLattice 8)).IsIsotropic d8SpinorSubgroup := by
  apply ((checkerboardLattice 8).isEven_intermediateCarrierOfDiscriminantSubgroup_iff
    (isEven_checkerboardLattice 8) d8SpinorSubgroup).mp
  rw [(IntermediateCarrier.isEven_iff_forall_discriminantQuadraticMap_eq_zero
    (isEven_checkerboardLattice 8)),
    (checkerboardLattice 8).discriminantSubgroup_intermediateCarrierOfDiscriminantSubgroup]
  intro x hx
  rw [mem_d8SpinorSubgroup_iff] at hx
  rcases hx with rfl | rfl
  · exact map_zero _
  · exact d8SpinorClass_quadratic_eq_zero

/-- The spinor glue carrier is even: its only nonzero glue class has quadratic value
`8 / 8 = 0` in `ℚ/ℤ`. -/
theorem isEven_d8PlusCarrier : IntermediateCarrier.IsEven d8PlusCarrier := by
  rw [d8PlusCarrier,
    (checkerboardLattice 8).isEven_intermediateCarrierOfDiscriminantSubgroup_iff]
  exact isIsotropic_d8SpinorSubgroup

/-- The `D₈⁺` integral lattice, obtained from the even spinor glue carrier with the same standard
dot product as the checkerboard lattice. -/
noncomputable def d8PlusLattice : IntegralLattice (Fin 8 → ℚ) :=
  isEven_d8PlusCarrier.isIntegral.toIntegralLattice

/-- The even overlattice glued along the spinor subgroup is the `D₈⁺` lattice.  This exposes
`d8PlusLattice` to the general overlattice theorems, which name the glued lattice through a proof
of evenness of the inverse image. -/
theorem toIntegralLattice_eq_d8PlusLattice
    (h : IntermediateCarrier.IsEven
      ((checkerboardLattice 8).intermediateCarrierOfDiscriminantSubgroup d8SpinorSubgroup)) :
    h.isIntegral.toIntegralLattice = d8PlusLattice := (rfl)

/-- The carrier of the `D₈⁺` lattice is the spinor glue carrier. -/
@[simp]
theorem d8PlusLattice_carrier : d8PlusLattice.carrier = d8PlusCarrier.1 := by
  rw [d8PlusLattice, IntermediateCarrier.IsIntegral.toIntegralLattice_carrier]

/-- The form of `D₈⁺` is the standard dot product inherited from `D₈`. -/
@[simp]
theorem d8PlusLattice_form : d8PlusLattice.form = (checkerboardLattice 8).form := by
  rw [d8PlusLattice, IntermediateCarrier.IsIntegral.toIntegralLattice_form]

/-- The `D₈⁺` lattice is nondegenerate. -/
instance instIsNondegenerateD8PlusLattice : d8PlusLattice.IsNondegenerate := by
  rw [d8PlusLattice]
  infer_instance

/-- The `D₈⁺` lattice is even. -/
theorem isEven_d8PlusLattice : d8PlusLattice.IsEven := by
  rw [d8PlusLattice]
  exact isEven_d8PlusCarrier.isEven_toIntegralLattice

/-- The spinor enlargement `D₈ ⊂ D₈⁺` has index two. -/
theorem index_d8PlusCarrier : IntermediateCarrier.index d8PlusCarrier = 2 := by
  rw [d8PlusCarrier, IntermediateCarrier.index_intermediateCarrierOfDiscriminantSubgroup,
    natCard_d8SpinorSubgroup]

/-- The `D₈⁺` lattice has discriminant one. -/
theorem discriminant_d8PlusLattice : d8PlusLattice.discriminant = 1 := by
  rw [d8PlusLattice,
    IntermediateCarrier.IsIntegral.discriminant_eq_discriminant_div_index_sq,
    index_d8PlusCarrier, discriminant_checkerboardLattice]
  norm_num

/-- **`D₈⁺` is positive definite**: gluing takes place inside the ambient space of `D₈` and keeps
its form. -/
theorem isPosDef_d8PlusLattice : d8PlusLattice.IsPosDef :=
  isEven_d8PlusCarrier.isIntegral.isPosDef_toIntegralLattice_iff.mpr
    (isPosDef_checkerboardLattice 8)

/-- **The spinor glue enlargement `D₈⁺` is unimodular.** -/
theorem isUnimodular_d8PlusLattice : d8PlusLattice.IsUnimodular := by
  rw [d8PlusLattice.isUnimodular_iff_discriminant_eq_one, discriminant_d8PlusLattice]

end IntegralLattice

end EpsilonEridani
