/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.NumberTheory.Multiquadratic.Frobenius
public import EpsilonEridani.NumberTheory.Multiquadratic.MultiquadraticSplitting
public import EpsilonEridani.NumberTheory.Multiquadratic.SquareClass.Rational

/-!
# Frobenius and the splitting law for rational radicands

The multiquadratic splitting law `NumberField.ncard_primesOver_multiquadratic_iff` and its
Frobenius refinements `NumberField.exists_isArithFrobAt_multiquadratic` and
`NumberField.isArithFrobAt_multiquadratic_eq_one_iff` are stated for integer radicands: `K` is
generated over `ℚ` by square roots `r i` of integers `d i`. A multiquadratic field over `ℚ` is
equally generated by square roots of *rational* numbers, and this file reduces that case to the
integral one by square classes.

Write each rational radicand as `d i = a i * c i ^ 2` with `a i ∈ ℤ` and `c i ∈ ℚ` nonzero
(for instance with `a i` squarefree, `Rat.exists_squarefree_int_mul_sq`). The rescaled roots
`(c i)⁻¹ * r i` are square roots of the integers `a i` and generate the same field
(`EpsilonEridani.Multiquadratic.sq_algebraMap_inv_mul_eq_of_eq_mul_sq`,
`EpsilonEridani.IntermediateField.adjoin_range_algebraMap_mul`), and a Frobenius commutes with the
rational rescaling. So, for an odd prime `p` dividing none of the `a i`, the Frobenius at `p`
acts on `r i` by the Legendre symbol `(a i / p)`, and `p` splits completely in `K` iff every
`a i` is a quadratic residue mod `p`. No condition on `c i` modulo `p` is needed: the square
factor affects neither the field nor the Legendre symbol.

Taking the canonical representative `a = num d · den d` (so `d = a · (den d)⁻²`) gives a
statement free of choices: for `p` dividing neither the numerator nor the denominator of any
`d i`, `p` splits completely iff every `num (d i) · den (d i)` is a quadratic residue mod `p`.

## Main results

* `EpsilonEridani.Multiquadratic.isArithFrobAt_apply_sqrt_of_eq_mul_sq`: a Frobenius at `p` sends a
  square root of `a c²` to `(a / p)` times itself.
* `EpsilonEridani.Multiquadratic.exists_isArithFrobAt_multiquadratic_of_eq_mul_sq` and
  `EpsilonEridani.Multiquadratic.isArithFrobAt_multiquadratic_eq_one_iff_of_eq_mul_sq`: the Frobenius
  action on the generators of a multiquadratic field with rational radicands, and its triviality
  criterion.
* `EpsilonEridani.Multiquadratic.ncard_primesOver_multiquadratic_iff_of_eq_mul_sq`: the splitting law
  for rational radicands, read off their integral square-class representatives.
* `EpsilonEridani.Multiquadratic.ncard_primesOver_multiquadratic_iff_num_mul_den`: the same with the
  canonical representatives `num · den`.
-/

public section

open NumberField Ideal Module

open scoped NumberField

namespace EpsilonEridani.Multiquadratic

variable {K : Type*} [Field K] [NumberField K] {ι : Type*} {p : ℕ} [Fact p.Prime]

/-- **A Frobenius acts on the square root of a rational number by a Legendre symbol.** Let `p` be
an odd prime and `σ ∈ Gal(K/ℚ)` an arithmetic Frobenius at an ideal `Q` of `𝓞 K` above `p`. If
`x ∈ K` is a square root of a rational number `d = a c²` with `a ∈ ℤ`, `p ∤ a` and `c ≠ 0`, then
`σ x = legendreSym p a • x`. The factor `c` may be divisible by `p`. -/
theorem isArithFrobAt_apply_sqrt_of_eq_mul_sq (hodd : p ≠ 2) {d : ℚ} {a : ℤ} {c : ℚ}
    (hc : c ≠ 0) (hdec : d = a * c ^ 2) (ha : ¬ (p : ℤ) ∣ a) {x : K}
    (hx : x ^ 2 = algebraMap ℚ K d) (Q : Ideal (𝓞 K)) [Q.LiesOver (span {(p : ℤ)})]
    {σ : K ≃ₐ[ℚ] K} (hσ : IsArithFrobAt ℤ σ Q) :
    σ x = legendreSym p a • x := by
  have h := isArithFrobAt_apply_sqrt hodd ha
    (sq_algebraMap_inv_mul_eq_of_eq_mul_sq hc hdec hx) Q hσ
  rw [map_mul, AlgEquiv.commutes, ← mul_smul_comm] at h
  exact mul_left_cancel₀ ((map_ne_zero _).mpr (inv_ne_zero hc)) h

/-- **The Frobenius of a multiquadratic field with rational radicands.** Let `K` be a Galois
number field containing square roots `r i` of rational numbers `d i = a i * c i ^ 2`, with
`a i ∈ ℤ` and `c i ≠ 0`, and let `p` be an odd prime dividing none of the `a i`. At every prime
`Q` of `𝓞 K` above `p` there is an arithmetic Frobenius `σ`, and it acts on each generator by the
Legendre symbol of the integral representative: `σ (r i) = legendreSym p (a i) • r i`. -/
theorem exists_isArithFrobAt_multiquadratic_of_eq_mul_sq [IsGalois ℚ K] {d : ι → ℚ}
    {a : ι → ℤ} {c : ι → ℚ} (hc : ∀ i, c i ≠ 0) (hdec : ∀ i, d i = a i * c i ^ 2) (r : ι → K)
    (hr : ∀ i, r i ^ 2 = algebraMap ℚ K (d i)) (hodd : p ≠ 2) (hcop : ∀ i, ¬ (p : ℤ) ∣ a i)
    (Q : Ideal (𝓞 K)) [Q.IsPrime] [Q.LiesOver (span {(p : ℤ)})] :
    ∃ σ : K ≃ₐ[ℚ] K, IsArithFrobAt ℤ σ Q ∧ ∀ i, σ (r i) = legendreSym p (a i) • r i := by
  obtain ⟨σ, hσ⟩ := exists_isArithFrobAt_int_of_liesOver (p := p) Q
  exact ⟨σ, hσ, fun i =>
    isArithFrobAt_apply_sqrt_of_eq_mul_sq hodd (hc i) (hdec i) (hcop i) (hr i) Q hσ⟩

/-- **A multiquadratic Frobenius with rational radicands is trivial iff every representative is a
residue.** Let `K = ℚ(√d₁, …, √dₙ)` be generated by square roots `r i` of rational numbers
`d i = a i * c i ^ 2`, with `a i ∈ ℤ` and `c i ≠ 0`, let `p` be an odd prime dividing none of the
`a i`, and let `σ` be an arithmetic Frobenius at an ideal `Q` of `𝓞 K` above `p`. Then `σ = 1`
iff every `a i` is a quadratic residue mod `p`. -/
theorem isArithFrobAt_multiquadratic_eq_one_iff_of_eq_mul_sq {d : ι → ℚ} {a : ι → ℤ}
    {c : ι → ℚ} (hc : ∀ i, c i ≠ 0) (hdec : ∀ i, d i = a i * c i ^ 2) (r : ι → K)
    (hr : ∀ i, r i ^ 2 = algebraMap ℚ K (d i))
    (htop : IntermediateField.adjoin ℚ (Set.range r) = ⊤) (hodd : p ≠ 2)
    (hcop : ∀ i, ¬ (p : ℤ) ∣ a i) (Q : Ideal (𝓞 K)) [Q.LiesOver (span {(p : ℤ)})]
    {σ : K ≃ₐ[ℚ] K} (hσ : IsArithFrobAt ℤ σ Q) :
    σ = 1 ↔ ∀ i, legendreSym p (a i) = 1 :=
  isArithFrobAt_multiquadratic_eq_one_iff a _
    (fun i => sq_algebraMap_inv_mul_eq_of_eq_mul_sq (hc i) (hdec i) (hr i))
    (by simpa [htop] using (EpsilonEridani.IntermediateField.adjoin_range_algebraMap_mul
      (fun i => inv_ne_zero (hc i)) r)) hodd hcop Q hσ

/-- **The multiquadratic splitting law for rational radicands.** Let `K = ℚ(√d₁, …, √dₙ)` be
generated over `ℚ` by square roots `r i` of rational numbers `d i = a i * c i ^ 2`, with
`a i ∈ ℤ` and `c i ≠ 0`, and let `p` be an odd prime dividing none of the `a i`. Then `p` splits
completely in `K` iff every `a i` is a quadratic residue mod `p`. -/
theorem ncard_primesOver_multiquadratic_iff_of_eq_mul_sq [Finite ι] {d : ι → ℚ} {a : ι → ℤ}
    {c : ι → ℚ} (hc : ∀ i, c i ≠ 0) (hdec : ∀ i, d i = a i * c i ^ 2) (r : ι → K)
    (hr : ∀ i, r i ^ 2 = algebraMap ℚ K (d i))
    (htop : IntermediateField.adjoin ℚ (Set.range r) = ⊤) (hodd : p ≠ 2)
    (hcop : ∀ i, ¬ (p : ℤ) ∣ a i) :
    (primesOver (span {(p : ℤ)}) (𝓞 K)).ncard = finrank ℚ K ↔
      ∀ i, legendreSym p (a i) = 1 :=
  ncard_primesOver_multiquadratic_iff a _
    (fun i => sq_algebraMap_inv_mul_eq_of_eq_mul_sq (hc i) (hdec i) (hr i))
    (by simpa [htop] using (EpsilonEridani.IntermediateField.adjoin_range_algebraMap_mul
      (fun i => inv_ne_zero (hc i)) r)) hodd hcop

/-- **The multiquadratic splitting law for rational radicands, canonical form.** Let
`K = ℚ(√d₁, …, √dₙ)` be generated over `ℚ` by square roots `r i` of rational numbers `d i`, and
let `p` be an odd prime dividing neither the numerator nor the denominator of any `d i`. Then `p`
splits completely in `K` iff every `num (d i) · den (d i)`, the integer in the square class of
`d i`, is a quadratic residue mod `p`. -/
theorem ncard_primesOver_multiquadratic_iff_num_mul_den [Finite ι] {d : ι → ℚ} (r : ι → K)
    (hr : ∀ i, r i ^ 2 = algebraMap ℚ K (d i))
    (htop : IntermediateField.adjoin ℚ (Set.range r) = ⊤) (hodd : p ≠ 2)
    (hnum : ∀ i, ¬ (p : ℤ) ∣ (d i).num) (hden : ∀ i, ¬ p ∣ (d i).den) :
    (primesOver (span {(p : ℤ)}) (𝓞 K)).ncard = finrank ℚ K ↔
      ∀ i, legendreSym p ((d i).num * (d i).den) = 1 := by
  refine ncard_primesOver_multiquadratic_iff_of_eq_mul_sq (c := fun i => ((d i).den : ℚ)⁻¹)
    (fun i => inv_ne_zero (Nat.cast_ne_zero.mpr (d i).den_nz)) (fun i => ?_) r hr htop hodd
    fun i hdvd => ?_
  · push_cast
    rw [← Rat.mul_den_eq_num (d i)]
    field_simp
  · rcases (Nat.prime_iff_prime_int.mp (Fact.out : p.Prime)).dvd_or_dvd hdvd with h | h
    · exact hnum i h
    · exact hden i (Int.natCast_dvd_natCast.mp h)

end EpsilonEridani.Multiquadratic
