/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.RingTheory.Huber.Restricted.Flat
public import EpsilonEridani.RingTheory.Flat.QuotientRegular

/-!
# The Laurent quotients `A⟨X⟩/(f - X)` and `A⟨X⟩/(1 - f X)` are flat

Wedhorn's Lemma 8.31(2): for a complete noetherian Tate ring `A` and `f ∈ A`, the rings
`A⟨X⟩/(f - X)` and `A⟨X⟩/(1 - f X)` are flat over `A`. They are the coordinate rings of the
Laurent rational subsets `{|f| ≤ 1}` and `{|f| ≥ 1}` of `Spa A` (Wedhorn, Example 6.38), which is
why Proposition 8.30 consumes them.

Wedhorn's "complete noetherian Tate ring" is spelled here as the full standing hypothesis list of
the final section: `A` is a complete `T0` uniform additive group whose uniformity is countably
generated, and is a nonarchimedean, Tate and noetherian ring (`CompleteSpace`, `T0Space`,
`(𝓤 A).IsCountablyGenerated`, `NonarchimedeanRing`, `IsTateRing`, `IsNoetherianRing`). The
uniform-structure hypotheses are what make Wedhorn's completeness and separation assumptions
usable in Lean; none of them is derivable from the others here.

Wedhorn's proof: `A⟨X⟩/(g)` is flat as soon as multiplication by `g` is injective on `M⟨X⟩` for
every finitely generated `M` — the `Tor`-sequence claim that is
`Module.Flat.quotient_span_singleton_of_lTensor_mulLeft_injective` — and for `g = 1 - f X` and
`g = f - X` that injectivity is a computation on the coefficients of `M⟨X⟩ = M ⊗[A] A⟨X⟩`
(Remark 8.29).

## Main results

* `EpsilonEridani.Huber.flat_quotient_algebraMap_sub_restrictedX`: `A⟨X⟩/(f - X)` is flat over `A`.
* `EpsilonEridani.Huber.flat_quotient_one_sub_algebraMap_mul_restrictedX`: `A⟨X⟩/(1 - f X)` is flat
  over `A`.
* `EpsilonEridani.Huber.mulX`: multiplication by `X` on series with coefficients in a module, which
  shifts every coefficient up by one; `EpsilonEridani.Huber.restrictedMulX` restricts it to `M⟨X⟩`.

## Implementation notes

The comparison map intertwines `X • ·` on `M ⊗[A] A⟨X⟩` with multiplication by `X` on `M⟨X⟩`
(`restrictedMvPowerSeriesBaseChange_comp_lTensor_mulLeft_restrictedX`), and scalars act as
scalars. So `(1 - f X) • ·` and `(f - X) • ·` on `M ⊗[A] A⟨X⟩` are `id - f • mulX` and
`f • id - mulX` on coefficients — that is
`lTensor_mulLeft_one_sub_algebraMap_mul_restrictedX` and
`lTensor_mulLeft_algebraMap_sub_restrictedX`. The first is injective by induction
on the coefficient index. The second is Wedhorn's argument: if `f • s = X s` then `f • s₀ = 0`
and `f • sⱼ₊₁ = sⱼ`, so every coefficient is a power of `f` times a later one; the chain of
submodules spanned by the initial coefficients stabilises because `M` is noetherian, the
stabilised submodule is generated by a single coefficient `sₗ`, and
`sₗ = f ^ (l + 1) • s₂ₗ₊₁ = a • f ^ (l + 1) • sₗ = 0`. Both are transported through the injective
comparison map to `(A ⧸ I) ⊗[A] A⟨X⟩`, which is what the ideal criterion asks for. That criterion
is this repository's own `Module.Flat.quotient_span_singleton_of_lTensor_mulLeft_injective`
(`EpsilonEridani/RingTheory/Flat/QuotientRegular.lean`), built on Mathlib's
`Module.Flat.iff_rTensor_injective`. No topology enters
beyond the module topology of `A ⧸ I` (`IsModuleTopology.instQuot`).

Exponents of one-variable series are identified with `ℕ` through `Finsupp.uniqueEquiv`;
multiplication by `X` is stated on `MvPowerSeries (Fin 1) M`, with no topology, and restricted
afterwards.

## References

* [Wedhorn, *Adic Spaces*][wedhorn_adic], Lemma 8.31 and Example 6.38.
* [AINTLIB](https://github.com/CBirkbeck/AINTLIB), branch `dev/adic-spaces`, at commit
  `37bbdaeb9`, `projects/AdicSpaces/Adic spaces/Wedhorn828.lean`.

## Provenance

Nothing here is ported. The ideal criterion is this repository's
`Module.Flat.quotient_span_singleton_of_lTensor_mulLeft_injective`; the comparison map and
the module-coefficient layer `M⟨X⟩` it runs on are `Restricted/BaseChange.lean` and
`Restricted/PowerSeries.lean`; the rest is new here.

AINTLIB (`github.com/CBirkbeck/AINTLIB` @ `37bbdaeb9`, Apache-2.0), the roadmap's designated
prior formalisation for this layer, **does** prove Lemma 8.31(2), and both shapes of it:
`Adic spaces/Wedhorn828.lean` has `lemma_8_31_fSubX_flat` (`A⟨X⟩/(f − X)` flat) and
`lemma_8_31_oneSubfX_flat` (`A⟨X⟩/(1 − fX)` flat), with `lemma_8_31_tateAlgebra_faithfullyFlat`
for 8.31(1). They were consulted, not ported, and the reason is the object rather than the
statement. Both are stated over AINTLIB's `TateAlgebra A`, which this repository does not
have, and both are proved by saturation — `Module.Flat.quotient_of_flat_of_saturated` applied
to `mul_fSubX_regular` / `mul_oneSubfX_regular` and the two `*_saturated_faithful` lemmas —
not by Wedhorn's coefficient argument. That argument needs series with coefficients in a
*module*, and `Restricted/PowerSeries.lean` records under its own Provenance that AINTLIB's
`TateAlgebra` layer is a ring-coefficient object with no `M⟨X⟩` at all. So the route here is
not available there, and porting theirs would mean porting the `TateAlgebra` layer and its
saturation machinery instead. The hypotheses are comparable rather than weaker: AINTLIB
carries `[IsTateRing A] [IsNoetherianRing A] [T2Space A]` (and `[IsStronglyNoetherian A]` on
the `f − X` shape), this file `[IsTateRing A] [IsNoetherianRing A]` with a completeness bundle.

That check was made by reading AINTLIB's declarations under their own names, not by grepping
this repository's vocabulary — the method that produced the false negative `BaseChange.lean`
records. Their sorry-freeness was measured with comments stripped: a plain `grep sorry` on
`Wedhorn828.lean` reports 17 hits and every one is a docstring mention, mostly the phrase
"sorry-free", so the file has none; the same instrument reports 9 in `Presheaf.lean`, which
is the control that it can find one.
-/

open Filter Topology
open scoped Uniformity

public section

namespace EpsilonEridani.Huber
/-! ### One variable: multiplication by `X`

Stated over a semiring and an additive monoid: it is pure reindexing, and nothing here
needs subtraction. The regularity results below, which do, keep `CommRing` and `AddCommGroup`. -/

section MulX

variable {A : Type*} [Semiring A]

variable {M : Type*} [AddCommMonoid M] [Module A M]

variable (A) in
/-- **Multiplication by `X` on series with coefficients in a module**: on coefficients it is
`∑ mⱼ Xʲ ↦ ∑ mⱼ Xʲ⁺¹`. This is what `X • ·` on `M⟨X⟩ = M ⊗[A] A⟨X⟩` looks like on coefficients
(`restrictedMvPowerSeriesBaseChange_tmul_restrictedX_mul`). -/
noncomputable def mulX : MvPowerSeries (Fin 1) M →ₗ[A] MvPowerSeries (Fin 1) M where
  -- `MvPowerSeries (Fin 1) M` unfolds to the coefficient function type, but only
  -- definitionally; the ascription is what lets the lambda below elaborate against it.
  toFun s := show (Fin 1 →₀ ℕ) → M from
    fun n ↦ if n 0 = 0 then 0 else (s : (Fin 1 →₀ ℕ) → M) (Finsupp.single 0 (n 0 - 1))
  map_add' s t := by
    funext n
    -- Present the goal in `mulX`'s defining if-then-else form so `split_ifs` can fire. This
    -- is a definitional unfolding of the structure field, not an equation, so there is no
    -- lemma for `rw` to use; `change` is the step.
    change (if n 0 = 0 then (0 : M) else (s + t : (Fin 1 →₀ ℕ) → M) (Finsupp.single 0 (n 0 - 1))) =
      (if n 0 = 0 then (0 : M) else (s : (Fin 1 →₀ ℕ) → M) (Finsupp.single 0 (n 0 - 1))) +
        (if n 0 = 0 then (0 : M) else (t : (Fin 1 →₀ ℕ) → M) (Finsupp.single 0 (n 0 - 1)))
    split_ifs
    · simp
    · rfl
  map_smul' a s := by
    funext n
    -- Same definitional unfolding as in `map_add'`.
    change (if n 0 = 0 then (0 : M) else (a • s : (Fin 1 →₀ ℕ) → M) (Finsupp.single 0 (n 0 - 1))) =
      a • (if n 0 = 0 then (0 : M) else (s : (Fin 1 →₀ ℕ) → M) (Finsupp.single 0 (n 0 - 1)))
    split_ifs
    · simp
    · rfl

/-- The coefficients of `mulX A s`: it vanishes in degree `0`, and in every other
degree it takes the coefficient of `s` one degree down. -/
@[simp]
theorem coeff_mulX (s : MvPowerSeries (Fin 1) M) (n : Fin 1 →₀ ℕ) :
    (mulX A s : (Fin 1 →₀ ℕ) → M) n =
      if n 0 = 0 then 0 else (s : (Fin 1 →₀ ℕ) → M) (Finsupp.single 0 (n 0 - 1)) := (rfl)

/-- `mulX A s` has no constant term.

Not `@[simp]`: the general equation `coeff_mulX` above is `@[simp]` and rewrites this
left-hand side first, so annotating the degree-`0` specialisation too would leave it out of
simp normal form. `simp` proves this statement on its own. -/
theorem coeff_zero_mulX (s : MvPowerSeries (Fin 1) M) :
    (mulX A s : (Fin 1 →₀ ℕ) → M) 0 = 0 := by
  simp [coeff_mulX]

/-- In degree `j + 1`, `mulX A s` takes the degree-`j` coefficient of `s`.

Deliberately not `@[simp]`: `Finsupp.single 0 (j + 1)` is not in simp normal form, since
`Finsupp.single_add` rewrites it to `Finsupp.single 0 j + Finsupp.single 0 1`, so the
annotation could never fire. The uses in this file rewrite with it explicitly. -/
theorem coeff_succ_mulX (s : MvPowerSeries (Fin 1) M) (j : ℕ) :
    (mulX A s : (Fin 1 →₀ ℕ) → M) (Finsupp.single 0 (j + 1)) =
      (s : (Fin 1 →₀ ℕ) → M) (Finsupp.single 0 j) := by
  simp [coeff_mulX]

/-- Multiplication by `X` preserves restrictedness: it reindexes coefficients along `j ↦ j + 1`. -/
theorem IsRestricted.mulX [TopologicalSpace M] {s : MvPowerSeries (Fin 1) M}
    (hs : IsRestricted s) : IsRestricted (EpsilonEridani.Huber.mulX A s) := by
  simp only [isRestricted_iff, Filter.ZeroAtFilter] at hs ⊢
  -- Exponents of a one-variable series are natural numbers. `Finsupp.uniqueEquiv 0` is Mathlib's
  -- name for that bijection, and multiplication by `X` is a reindexing along it.
  have hs' : Tendsto (fun j : ℕ ↦
      (s : (Fin 1 →₀ ℕ) → M) ((Finsupp.uniqueEquiv (0 : Fin 1)).symm j)) cofinite (nhds 0) :=
    hs.comp (Finsupp.uniqueEquiv (0 : Fin 1)).symm.injective.tendsto_cofinite
  have h2 : Tendsto (fun j : ℕ ↦ if j = 0 then (0 : M) else
      (s : (Fin 1 →₀ ℕ) → M) ((Finsupp.uniqueEquiv (0 : Fin 1)).symm (j - 1)))
      cofinite (nhds 0) := by
    rw [Nat.cofinite_eq_atTop] at hs' ⊢
    rw [← Filter.tendsto_add_atTop_iff_nat 1]
    simpa using hs'
  have key : (EpsilonEridani.Huber.mulX A s : (Fin 1 →₀ ℕ) → M) =
      (fun j : ℕ ↦ if j = 0 then (0 : M) else
        (s : (Fin 1 →₀ ℕ) → M) ((Finsupp.uniqueEquiv (0 : Fin 1)).symm (j - 1))) ∘
        Finsupp.uniqueEquiv (0 : Fin 1) := by
    funext n
    simp [coeff_mulX]
  rw [key]
  exact h2.comp (Finsupp.uniqueEquiv (0 : Fin 1)).injective.tendsto_cofinite

end MulX

/-! ### Multiplication by `X` and by scalars, through the comparison map -/

section Compat

variable {A : Type*} [CommRing A] [TopologicalSpace A] [NonarchimedeanRing A]

variable {M : Type*} [AddCommGroup M] [Module A M] [TopologicalSpace M] [ContinuousAdd M]
  [ContinuousSMul A M]

/-- Multiplication by `X` on `M⟨X⟩`. -/
noncomputable def restrictedMulX :
    restrictedMvPowerSeriesSubmodule 1 A M →ₗ[A] restrictedMvPowerSeriesSubmodule 1 A M :=
  (mulX A).restrict fun _ hs ↦ mem_restrictedMvPowerSeriesSubmodule.mpr
    (mem_restrictedMvPowerSeriesSubmodule.mp hs).mulX

omit [NonarchimedeanRing A] in
/-- `restrictedMulX` acts as `mulX` on the underlying series. -/
@[simp]
theorem coe_restrictedMulX (s : restrictedMvPowerSeriesSubmodule 1 A M) :
    ((restrictedMulX s : restrictedMvPowerSeriesSubmodule 1 A M) : MvPowerSeries (Fin 1) M) =
      mulX A (s : MvPowerSeries (Fin 1) M) := (rfl)

/-- On a pure tensor, multiplying the series factor by `X` shifts the coefficients of the
comparison map's value up by one. -/
theorem restrictedMvPowerSeriesBaseChange_tmul_restrictedX_mul (m : M)
    (b : restrictedMvPowerSeriesSubring 1 A) :
    restrictedMvPowerSeriesBaseChange (TensorProduct.tmul A m ((restrictedX 0) * b)) =
      restrictedMulX (restrictedMvPowerSeriesBaseChange (TensorProduct.tmul A m b)) := by
  apply restrictedMvPowerSeriesSubmodule_ext
  intro n
  obtain ⟨j, rfl⟩ : ∃ j, n = Finsupp.single 0 j := ⟨n 0, Finsupp.unique_single n⟩
  rw [coeff_restrictedMvPowerSeriesBaseChange_tmul, coe_restrictedMulX, Subring.coe_mul,
    coe_restrictedX]
  cases j with
  | zero => rw [Finsupp.single_zero, coeff_zero_mulX, MvPowerSeries.coeff_zero_X_mul, zero_smul]
  | succ j =>
    rw [coeff_succ_mulX, coeff_restrictedMvPowerSeriesBaseChange_tmul,
      -- `Finsupp.single_add` splits `single 0 (1 + j)`, so the exponent is commuted in
      -- place here rather than in a separate step.
      show j + 1 = 1 + j from Nat.add_comm j 1, Finsupp.single_add, MvPowerSeries.X_def,
      MvPowerSeries.coeff_add_monomial_mul, one_mul]

/-- The comparison map intertwines `X • ·` on `M ⊗[A] A⟨X⟩` with multiplication by `X`. -/
theorem restrictedMvPowerSeriesBaseChange_comp_lTensor_mulLeft_restrictedX :
    (restrictedMvPowerSeriesBaseChange : TensorProduct A M (restrictedMvPowerSeriesSubring 1 A)
        →ₗ[A] restrictedMvPowerSeriesSubmodule 1 A M) ∘ₗ
      LinearMap.lTensor M (LinearMap.mulLeft A (restrictedX 0)) =
    restrictedMulX ∘ₗ restrictedMvPowerSeriesBaseChange :=
  TensorProduct.ext' fun m b ↦ by
    simp only [LinearMap.comp_apply, LinearMap.lTensor_tmul, LinearMap.mulLeft_apply]
    exact restrictedMvPowerSeriesBaseChange_tmul_restrictedX_mul m b

/-- Through the comparison map, `X • ·` on `M ⊗[A] A⟨X⟩` is multiplication by `X` on `M⟨X⟩`. -/
theorem restrictedMvPowerSeriesBaseChange_lTensor_mulLeft_restrictedX
    (z : TensorProduct A M (restrictedMvPowerSeriesSubring 1 A)) :
    restrictedMvPowerSeriesBaseChange
        (LinearMap.lTensor M (LinearMap.mulLeft A (restrictedX 0)) z) =
      restrictedMulX (restrictedMvPowerSeriesBaseChange z) :=
  LinearMap.congr_fun restrictedMvPowerSeriesBaseChange_comp_lTensor_mulLeft_restrictedX z

omit [TopologicalSpace M] [ContinuousAdd M] [ContinuousSMul A M] in
/-- `(1 - f X) • ·` on `M ⊗[A] A⟨X⟩`, in terms of `X • ·`. -/
theorem lTensor_mulLeft_one_sub_algebraMap_mul_restrictedX (f : A) :
    LinearMap.lTensor M (LinearMap.mulLeft A
        (1 - algebraMap A (restrictedMvPowerSeriesSubring 1 A) f * (restrictedX 0))) =
      LinearMap.id - f • LinearMap.lTensor M (LinearMap.mulLeft A (restrictedX 0)) :=
  TensorProduct.ext' fun m b ↦ by
    simp [LinearMap.lTensor_tmul, LinearMap.mulLeft_apply, sub_mul, ← Algebra.smul_def,
      TensorProduct.tmul_sub, TensorProduct.tmul_smul]

omit [TopologicalSpace M] [ContinuousAdd M] [ContinuousSMul A M] in
/-- `(f - X) • ·` on `M ⊗[A] A⟨X⟩`, in terms of `X • ·`. -/
theorem lTensor_mulLeft_algebraMap_sub_restrictedX (f : A) :
    LinearMap.lTensor M (LinearMap.mulLeft A
        (algebraMap A (restrictedMvPowerSeriesSubring 1 A) f - (restrictedX 0))) =
      f • LinearMap.id - LinearMap.lTensor M (LinearMap.mulLeft A (restrictedX 0)) :=
  TensorProduct.ext' fun m b ↦ by
    simp [LinearMap.lTensor_tmul, LinearMap.mulLeft_apply, sub_mul, ← Algebra.smul_def,
      TensorProduct.tmul_sub, TensorProduct.tmul_smul]

end Compat

/-! ### Regularity of `1 - f X` and of `f - X` on `MvPowerSeries (Fin 1) M`

Restrictedness is irrelevant to these two lemmas, so they are stated on all of
`MvPowerSeries (Fin 1) M`, with no topology; the statements on `M⟨X⟩` follow by restriction. -/

section Regular

variable {A : Type*} [CommRing A] {M : Type*} [AddCommGroup M] [Module A M]

/-- **Multiplication by `1 - f X` is injective on series with coefficients in any module.** -/
theorem id_sub_smul_mulX_injective (f : A) :
    Function.Injective (LinearMap.id - f • mulX A : MvPowerSeries (Fin 1) M →ₗ[A] _) := by
  rw [injective_iff_map_eq_zero]
  intro s hs
  have hs' : s = f • mulX A s := by
    simpa [sub_eq_zero] using hs
  have hc : ∀ j, (s : (Fin 1 →₀ ℕ) → M) (Finsupp.single 0 j) =
      f • (mulX A s : (Fin 1 →₀ ℕ) → M) (Finsupp.single 0 j) := fun j ↦
    congrArg (fun t : MvPowerSeries (Fin 1) M ↦ (t : (Fin 1 →₀ ℕ) → M) (Finsupp.single 0 j)) hs'
  have hzero : ∀ j, (s : (Fin 1 →₀ ℕ) → M) (Finsupp.single 0 j) = 0 := by
    intro j
    induction j with
    | zero => simpa using hc 0
    | succ j ih => rw [hc (j + 1), coeff_succ_mulX, ih, smul_zero]
  -- Equality of one-variable series is definitionally equality of their coefficient
  -- functions, which is what `funext` needs to see.
  change (s : (Fin 1 →₀ ℕ) → M) = 0
  funext n
  rw [Finsupp.unique_single n]
  exact hzero _

/-- From `f • c (j + 1) = c j`, every term of the sequence is `f ^ i` times a later one. -/
private theorem eq_pow_smul_of_smul_succ {f : A} {c : ℕ → M} (hsucc : ∀ j, f • c (j + 1) = c j) :
    ∀ i j, c j = f ^ i • c (j + i) := by
  intro i
  induction i with
  | zero => simp
  | succ i ih =>
    intro j
    rw [ih j, ← Nat.add_assoc, ← hsucc (j + i), ← mul_smul, ← pow_succ]

/-- **A sequence in a noetherian module killed by `f` at the start and shifted back by `f` at
each step vanishes.** This is the noetherian stabilisation in Wedhorn's proof of Lemma 8.31(2):
the submodules spanned by the initial terms increase, so they stabilise at some `l`; then `c l`
generates all of them and is divisible by an arbitrarily large power of `f`, so it vanishes. -/
private theorem eq_zero_of_smul_eq_zero_of_smul_succ [IsNoetherian A M] {f : A} {c : ℕ → M}
    (h0 : f • c 0 = 0) (hsucc : ∀ j, f • c (j + 1) = c j) (j : ℕ) : c j = 0 := by
  have hshift := eq_pow_smul_of_smul_succ hsucc
  have hpow : ∀ j, f ^ (j + 1) • c j = 0 := by
    intro j
    induction j with
    | zero => simpa using h0
    | succ j ih => rw [pow_succ, mul_smul, hsucc, ih]
  let S : ℕ →o Submodule A M :=
    ⟨fun l ↦ Submodule.span A (c '' Set.Iic l), fun _ _ h ↦
      Submodule.span_mono (Set.image_mono (Set.Iic_subset_Iic.mpr h))⟩
  obtain ⟨l, hl⟩ := monotone_stabilizes_iff_noetherian.mpr ‹IsNoetherian A M› S
  have hmul : ∀ i ≤ l, c i = f ^ (l - i) • c l := fun i hi ↦ by
    have := hshift (l - i) i
    rwa [Nat.add_sub_cancel' hi] at this
  have hSl : S l ≤ Submodule.span A {c l} := Submodule.span_le.mpr <| by
    rintro _ ⟨i, hi, rfl⟩
    rw [hmul i hi]
    exact Submodule.smul_mem _ _ (Submodule.mem_span_singleton_self _)
  have hmem : c (2 * l + 1) ∈ Submodule.span A {c l} := hSl <| by
    rw [hl (2 * l + 1) (by omega)]
    exact Submodule.subset_span ⟨2 * l + 1, Set.mem_Iic.mpr le_rfl, rfl⟩
  obtain ⟨a, ha⟩ := Submodule.mem_span_singleton.mp hmem
  have hcl : c l = 0 := by
    have h1 : c l = f ^ (l + 1) • c (2 * l + 1) := by
      have := hshift (l + 1) l
      -- `hshift` produces the index in the form `l + (l + 1)`; the stabilisation below is
      -- stated at `2 * l + 1`, so the two spellings are reconciled here rather than by
      -- restating `hshift`.
      rwa [show l + (l + 1) = 2 * l + 1 by ring] at this
    rw [h1, ← ha, smul_comm, hpow, smul_zero]
  rcases le_or_gt j l with hj | hj
  · rw [hmul j hj, hcl, smul_zero]
  · have hS0 : S l = ⊥ := Submodule.span_eq_bot.mpr <| by
      rintro _ ⟨i, hi, rfl⟩
      rw [hmul i hi, hcl, smul_zero]
    have hjS : c j ∈ S j := Submodule.subset_span ⟨j, Set.mem_Iic.mpr le_rfl, rfl⟩
    rw [← hl j hj.le, hS0] at hjS
    exact (Submodule.mem_bot A).mp hjS

/-- **Multiplication by `f - X` is injective on series with coefficients in a noetherian
module.** -/
theorem smul_id_sub_mulX_injective [IsNoetherian A M] (f : A) :
    Function.Injective (f • LinearMap.id - mulX A : MvPowerSeries (Fin 1) M →ₗ[A] _) := by
  rw [injective_iff_map_eq_zero]
  intro s hs
  have hs' : f • s = mulX A s := by
    simpa [sub_eq_zero] using hs
  have hrec : ∀ j, f • (s : (Fin 1 →₀ ℕ) → M) (Finsupp.single 0 j) =
      (mulX A s : (Fin 1 →₀ ℕ) → M) (Finsupp.single 0 j) := fun j ↦
    congrArg (fun t : MvPowerSeries (Fin 1) M ↦ (t : (Fin 1 →₀ ℕ) → M) (Finsupp.single 0 j)) hs'
  have hall := eq_zero_of_smul_eq_zero_of_smul_succ
    (c := fun j ↦ (s : (Fin 1 →₀ ℕ) → M) (Finsupp.single 0 j)) (by simpa using hrec 0)
    fun j ↦ by have := hrec (j + 1); rwa [coeff_succ_mulX] at this
  -- Equality of one-variable series is definitionally equality of their coefficient
  -- functions, which is what `funext` needs to see.
  change (s : (Fin 1 →₀ ℕ) → M) = 0
  funext n
  rw [Finsupp.unique_single n]
  exact hall _

end Regular

/-! ### Lemma 8.31(2) -/

section Laurent

variable {A : Type*} [CommRing A] [UniformSpace A] [IsUniformAddGroup A] [CompleteSpace A]
  [(𝓤 A).IsCountablyGenerated] [T0Space A] [NonarchimedeanRing A] [IsTateRing A]
  [IsNoetherianRing A]
  {N : Type*} [AddCommGroup N] [Module A N] [Module.Finite A N] [TopologicalSpace N]
  [ContinuousAdd N] [IsModuleTopology A N]

/-- `1 - f X` acts injectively on `N ⊗[A] A⟨X⟩` for a finite `N` with its module topology. -/
theorem lTensor_mulLeft_one_sub_algebraMap_mul_restrictedX_injective (f : A) :
    Function.Injective (LinearMap.lTensor N (LinearMap.mulLeft A
      (1 - algebraMap A (restrictedMvPowerSeriesSubring 1 A) f * (restrictedX 0)))) := by
  rw [lTensor_mulLeft_one_sub_algebraMap_mul_restrictedX, injective_iff_map_eq_zero]
  intro z hz
  have h := congrArg
    (fun w : restrictedMvPowerSeriesSubmodule 1 A N ↦ (w : MvPowerSeries (Fin 1) N))
    (congrArg restrictedMvPowerSeriesBaseChange hz)
  simp only [LinearMap.sub_apply, LinearMap.id_apply, LinearMap.smul_apply, map_sub, map_smul,
    restrictedMvPowerSeriesBaseChange_lTensor_mulLeft_restrictedX, map_zero,
    Submodule.coe_sub, Submodule.coe_smul, coe_restrictedMulX, Submodule.coe_zero] at h
  have h' : ((restrictedMvPowerSeriesBaseChange z : restrictedMvPowerSeriesSubmodule 1 A N) :
      MvPowerSeries (Fin 1) N) = 0 :=
    (injective_iff_map_eq_zero _).mp (id_sub_smul_mulX_injective f) _ (by simpa using h)
  exact (restrictedMvPowerSeriesBaseChange_bijective (k := 1) (A := A) (M := N)).injective
    (by rw [map_zero]; exact Subtype.ext h')

/-- `f - X` acts injectively on `N ⊗[A] A⟨X⟩` for a finite `N` with its module topology. -/
theorem lTensor_mulLeft_algebraMap_sub_restrictedX_injective (f : A) :
    Function.Injective (LinearMap.lTensor N (LinearMap.mulLeft A
      (algebraMap A (restrictedMvPowerSeriesSubring 1 A) f - (restrictedX 0)))) := by
  rw [lTensor_mulLeft_algebraMap_sub_restrictedX, injective_iff_map_eq_zero]
  intro z hz
  have h := congrArg
    (fun w : restrictedMvPowerSeriesSubmodule 1 A N ↦ (w : MvPowerSeries (Fin 1) N))
    (congrArg restrictedMvPowerSeriesBaseChange hz)
  simp only [LinearMap.sub_apply, LinearMap.id_apply, LinearMap.smul_apply, map_sub, map_smul,
    restrictedMvPowerSeriesBaseChange_lTensor_mulLeft_restrictedX, map_zero,
    Submodule.coe_sub, Submodule.coe_smul, coe_restrictedMulX, Submodule.coe_zero] at h
  have h' : ((restrictedMvPowerSeriesBaseChange z : restrictedMvPowerSeriesSubmodule 1 A N) :
      MvPowerSeries (Fin 1) N) = 0 :=
    (injective_iff_map_eq_zero _).mp (smul_id_sub_mulX_injective f) _ (by simpa using h)
  exact (restrictedMvPowerSeriesBaseChange_bijective (k := 1) (A := A) (M := N)).injective
    (by rw [map_zero]; exact Subtype.ext h')

variable (A) in
/-- **`A⟨X⟩/(f - X)` is flat over a complete noetherian Tate ring** (Wedhorn, Lemma 8.31(2)).

"Complete noetherian Tate ring" abbreviates this section's standing hypotheses on `A`:
`CompleteSpace`, `T0Space` and `(𝓤 A).IsCountablyGenerated` for the uniform structure, and
`NonarchimedeanRing`, `IsTateRing`, `IsNoetherianRing` for the ring. -/
theorem flat_quotient_algebraMap_sub_restrictedX (f : A) :
    Module.Flat A (restrictedMvPowerSeriesSubring 1 A ⧸
      Ideal.span {algebraMap A (restrictedMvPowerSeriesSubring 1 A) f - (restrictedX 0)}) := by
  have := flat_restrictedMvPowerSeriesSubring (k := 1) (A := A)
  exact Module.Flat.quotient_span_singleton_of_lTensor_mulLeft_injective _ fun I _ ↦
    lTensor_mulLeft_algebraMap_sub_restrictedX_injective (N := A ⧸ I) f

variable (A) in
/-- **`A⟨X⟩/(1 - f X)` is flat over a complete noetherian Tate ring** (Wedhorn, Lemma 8.31(2)).

Same standing hypotheses on `A` as `flat_quotient_algebraMap_sub_restrictedX`. -/
theorem flat_quotient_one_sub_algebraMap_mul_restrictedX (f : A) :
    Module.Flat A (restrictedMvPowerSeriesSubring 1 A ⧸
      Ideal.span {1 - algebraMap A (restrictedMvPowerSeriesSubring 1 A) f * (restrictedX 0)}) := by
  have := flat_restrictedMvPowerSeriesSubring (k := 1) (A := A)
  exact Module.Flat.quotient_span_singleton_of_lTensor_mulLeft_injective _ fun I _ ↦
    lTensor_mulLeft_one_sub_algebraMap_mul_restrictedX_injective (N := A ⧸ I) f

end Laurent

end EpsilonEridani.Huber
