/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.Algebra.Lie.UniversalEnveloping.Kostant.Adjoint.Basic
public import EpsilonEridani.Algebra.Lie.UniversalEnveloping.Kostant.Weight.Basis
public import EpsilonEridani.Algebra.Module.Submodule.Finite

/-!
# The weight basis of a Chevalley lattice

`EpsilonEridani.UniversalEnvelopingAlgebra.kostantWeightBasis` produces a basis of weight vectors for an
admissible lattice `M ≤ V` from three inputs: stability of `M` under the Kostant integral form,
finite generation of `M` over `ℤ`, and the requirement that `M` lie in the span of the integral
joint weight spaces of the designated Cartan vectors. Every consumer of a weight basis — the split
maximal torus, the matrix coordinates of a Kostant root subgroup, and the group scheme generated by
the root subgroups — therefore still carried those three as hypotheses.

This file discharges them for the Chevalley lattice `L_ℤ = (rootCorootSpan x).toAddSubgroup` of a
Chevalley system `x`, whose admissibility for the adjoint representation is
`EpsilonEridani.IsChevalleySystem.chevalleyKostantForm_apply_mem` and whose finite generation is
`EpsilonEridani.instModuleFiniteRootCorootSpan` read through `EpsilonEridani.instModuleFiniteToAddSubgroup`. The
distinguished Cartan vectors are `EpsilonEridani.corootFamily`, and the missing input is the weight datum:
`L_ℤ` is spanned by the root vectors and the coroots, and each of those is a joint eigenvector of
the operators `ad α∨`. A root vector `x β` has the integer weight `EpsilonEridani.rootCartanWeight β`,
while a coroot is annihilated by every `ad α∨` and so has weight zero. That is exactly the span
condition, so the Chevalley lattice acquires a weight basis with nothing left to assume. Only the
stability input needs the Chevalley system; the weight datum holds for any normalized system of
root vectors.

That the resulting basis is a basis of a full `ℤ`-form, rather than of a proper subspace, is
`EpsilonEridani.IsSl2System.span_rootCorootSpan_eq_top` read through `Submodule.coe_toAddSubgroup`.

Two consequences are recorded. The lattice is the internal direct sum of the sublattices it cuts out
of the weight spaces, and over any commutative ring the torus of coroot cocharacters acts diagonally
on the base change of the lattice, scaling a weight vector by the value of its character. That last
equation identifies the character by which the torus acts on each weight component. It is not by
itself a pinning: the pinning equation `t(s) xᵢ(u) t(s)⁻¹ = xᵢ(α(s) u)` relating the torus to the
root subgroups needs the separate hypothesis that the root vectors act nilpotently, which this file
does not supply, and exhibiting the *maximal* torus of the pinning needs a rank-`ℓ` cocharacter
datum — equivalently the simply connected lattice — which the adjoint lattice does not provide.

A `ℤ`-basis of a lattice is not canonical and this one is no exception: the underlying
`kostantWeightBasis` chooses a basis of each weight sublattice. What is canonical is the weight
decomposition, and the Chevalley basis itself is one of the admissible choices rather than the one
this construction returns.

## Main definitions

* `EpsilonEridani.rootCorootWeightBasisCard`: the number of index values of the weight basis of the
  integral root--coroot span.
* `EpsilonEridani.IsChevalleySystem.chevalleyWeightBasis` and
  `EpsilonEridani.IsChevalleySystem.chevalleyWeightBasisFin`: the weight basis of the Chevalley lattice,
  the latter numbered by `Fin`, paired with `EpsilonEridani.IsChevalleySystem.chevalleyWeightFin`.
* `EpsilonEridani.IsChevalleySystem.chevalleyTorusPoints`: the torus of coroot cocharacters on the points
  of the Chevalley lattice.

## Main results

* `EpsilonEridani.IsSl2System.isCartanWeightVector_rootVector` and
  `EpsilonEridani.isCartanWeightVector_cartan`, specialized to a coroot in
  `EpsilonEridani.isCartanWeightVector_coroot`: the generators of the Chevalley lattice are joint
  eigenvectors of the coroot operators, of the stated integral weights.
* `EpsilonEridani.IsSl2System.mem_iSup_jointWeightSpace`: the Chevalley lattice lies in the span of the
  integral joint weight spaces.
* `EpsilonEridani.IsChevalleySystem.kostantForm_apply_mem_rootCorootSpan`: the Chevalley lattice is stable
  under its Kostant form, in the shape the weight-basis API consumes.
* `EpsilonEridani.IsChevalleySystem.isInternal_weightSublattice`: the Chevalley lattice is the internal
  direct sum of its weight sublattices.
* `EpsilonEridani.IsChevalleySystem.isCartanWeightVector_chevalleyWeightBasisFin`: the numbered weight
  basis consists of weight vectors of the recorded weights.
* `EpsilonEridani.IsChevalleySystem.chevalleyTorusPoints_tmul_of_isCartanWeightVector`: a torus point
  scales a weight vector by the value of its character.

## References

* J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*, GTM 9, §27.1.
* R. W. Carter, *Simple Groups of Lie Type*, §4.4.
* J. C. Jantzen, *Representations of Algebraic Groups*, II.1.

This advances Layer 9 of `EpsilonEridaniRoadmap/ReductiveGroups/README.md`, which asks for a pinning
`(G, T, B, {X_α})` of the explicitly constructed Chevalley--Demazure group scheme; the torus `T`
acts by a character on each weight component, so a weight basis of the admissible lattice is what
has to exist before it can be written down. Layer 9 is consumed by milestone L0 of
`EpsilonEridaniRoadmap/CFSGStatement/README.md`.
-/

public section

namespace EpsilonEridani

open LieAlgebra LieAlgebra.IsKilling LieModule TensorProduct

attribute [local instance] EpsilonEridani.moduleNNRat

-- Match tensor products to the `ℤ`-algebra instance the Kostant torus is stated against.
attribute [local instance high] Algebra.toModule

universe v w

variable {L : Type v} [LieRing L] [LieAlgebra ℚ L] [LieAlgebra.IsKilling ℚ L]
  [FiniteDimensional ℚ L] {H : LieSubalgebra ℚ L} [H.IsCartanSubalgebra]
  [LieModule.IsTriangularizable ℚ H L]

/-! ## The generators of the Chevalley lattice are weight vectors -/

omit [LieModule.IsTriangularizable ℚ H L] in
/-- **An element of the Cartan subalgebra is a joint eigenvector of the coroot operators of weight
zero**: the Cartan subalgebra is abelian, so every `ad α∨` annihilates it. -/
theorem isCartanWeightVector_cartan (y : H) :
    UniversalEnvelopingAlgebra.IsCartanWeightVector (corootFamily H)
      (UniversalEnvelopingAlgebra.representation ℚ L L) 0 (y : L) :=
  (UniversalEnvelopingAlgebra.isCartanWeightVector_iff _ _).2 fun α => by
    rw [corootFamily_apply, UniversalEnvelopingAlgebra.representation_ι_ad,
      LieAlgebra.ad_apply, lie_cartan_cartan_eq_zero]
    simp

omit [LieModule.IsTriangularizable ℚ H L] in
/-- **A coroot is a joint eigenvector of the coroot operators of weight zero**, being an element of
the Cartan subalgebra. -/
theorem isCartanWeightVector_coroot (β : Weight ℚ H L) :
    UniversalEnvelopingAlgebra.IsCartanWeightVector (corootFamily H)
      (UniversalEnvelopingAlgebra.representation ℚ L L) 0 ((coroot β : H) : L) :=
  isCartanWeightVector_cartan (coroot β)

namespace IsSl2System

variable {x : Weight ℚ H L → L} (hx : IsSl2System x)

include hx

/-- **A root vector is a joint eigenvector of the coroot operators**, of the integral weight
`EpsilonEridani.rootCartanWeight β`. -/
theorem isCartanWeightVector_rootVector (β : Weight ℚ H L) :
    UniversalEnvelopingAlgebra.IsCartanWeightVector (corootFamily H)
      (UniversalEnvelopingAlgebra.representation ℚ L L) (rootCartanWeight β) (x β) :=
  (UniversalEnvelopingAlgebra.isCartanWeightVector_iff _ _).2 fun α => by
    rw [corootFamily_apply, UniversalEnvelopingAlgebra.representation_ι_ad,
      LieAlgebra.ad_apply, hx.lie_coroot_rootVector α β]

/-- **The integral root--coroot span lies in the span of the integral joint weight spaces.** Its
generators are the root vectors and the coroots, and each of them is a joint eigenvector of the
coroot operators with integer eigenvalues. -/
theorem mem_iSup_jointWeightSpace (y : (rootCorootSpan x).toAddSubgroup) :
    (y : L) ∈ ⨆ μ : Weight ℚ H L → ℤ,
      UniversalEnvelopingAlgebra.jointWeightSpace (corootFamily H)
        (UniversalEnvelopingAlgebra.representation ℚ L L) μ := by
  have hle : rootCorootSpan x ≤
      (⨆ μ : Weight ℚ H L → ℤ,
        UniversalEnvelopingAlgebra.jointWeightSpace (corootFamily H)
          (UniversalEnvelopingAlgebra.representation ℚ L L) μ).restrictScalars ℤ := by
    rw [rootCorootSpan_le_iff]
    refine ⟨fun β => ?_, fun β => ?_⟩
    · exact (Submodule.restrictScalars_mem ℤ _ _).2 (Submodule.mem_iSup_of_mem (rootCartanWeight β)
        ((UniversalEnvelopingAlgebra.mem_jointWeightSpace_iff _ _).2
          (hx.isCartanWeightVector_rootVector β)))
    · exact (Submodule.restrictScalars_mem ℤ _ _).2 (Submodule.mem_iSup_of_mem 0
        ((UniversalEnvelopingAlgebra.mem_jointWeightSpace_iff _ _).2
          (isCartanWeightVector_coroot β)))
  exact (Submodule.restrictScalars_mem ℤ _ _).1 (hle ((Submodule.mem_toAddSubgroup _).1 y.2))

end IsSl2System

/-! ## The weight basis of the Chevalley lattice -/

/-- The number of index values of `EpsilonEridani.UniversalEnvelopingAlgebra.kostantWeightBasis` for the
integral root--coroot span of `x` against the coroot family. For a Chevalley system this is the
rank of that lattice, by `EpsilonEridani.IsChevalleySystem.rootCorootWeightBasisCard_eq_finrank`; for an
arbitrary family `x` no such claim is made. -/
noncomputable abbrev rootCorootWeightBasisCard (x : Weight ℚ H L → L) : ℕ :=
  Nat.card (Σ μ : Weight ℚ H L → ℤ, Module.Free.ChooseBasisIndex ℤ
    (UniversalEnvelopingAlgebra.weightSublattice (corootFamily H)
      (UniversalEnvelopingAlgebra.representation ℚ L L)
      (rootCorootSpan x).toAddSubgroup μ))

namespace IsChevalleySystem

variable {ω : L ≃ₗ⁅ℚ⁆ L} {x : Weight ℚ H L → L} (hx : IsChevalleySystem ω x)

include hx

/-- **The Chevalley lattice is stable under its Kostant form**, in the shape
`EpsilonEridani.UniversalEnvelopingAlgebra.kostantWeightBasis` consumes. -/
theorem kostantForm_apply_mem_rootCorootSpan :
    ∀ u ∈ UniversalEnvelopingAlgebra.kostantForm x (corootFamily H),
      ∀ y ∈ (rootCorootSpan x).toAddSubgroup,
        UniversalEnvelopingAlgebra.representation ℚ L L u y ∈
          (rootCorootSpan x).toAddSubgroup := by
  intro u hu y hy
  rw [Submodule.mem_toAddSubgroup, ← hx.mem_chevalleyLieLattice_iff] at hy ⊢
  exact hx.chevalleyKostantForm_apply_mem ((chevalleyKostantForm_def x).ge hu) hy

/-- **The Chevalley lattice is the internal direct sum of its weight sublattices.** This is
Humphreys' Lemma 27.1 for the adjoint admissible lattice: the decomposition itself is canonical,
unlike the bases of the summands chosen below. -/
theorem isInternal_weightSublattice [DecidableEq (Weight ℚ H L → ℤ)] :
    DirectSum.IsInternal (UniversalEnvelopingAlgebra.weightSublattice (corootFamily H)
      (UniversalEnvelopingAlgebra.representation ℚ L L)
      (rootCorootSpan x).toAddSubgroup) :=
  UniversalEnvelopingAlgebra.isInternal_weightSublattice x (corootFamily H) _ _
    hx.kostantForm_apply_mem_rootCorootSpan hx.toIsSl2System.mem_iSup_jointWeightSpace

/-- **A weight basis of the Chevalley lattice.** All three hypotheses of
`EpsilonEridani.UniversalEnvelopingAlgebra.kostantWeightBasis` hold for the adjoint admissible lattice of a
Chevalley system, so it has a basis of joint eigenvectors of the coroot operators. -/
noncomputable def chevalleyWeightBasis :
    Module.Basis
      (Σ μ : Weight ℚ H L → ℤ, Module.Free.ChooseBasisIndex ℤ
        (UniversalEnvelopingAlgebra.weightSublattice (corootFamily H)
          (UniversalEnvelopingAlgebra.representation ℚ L L)
          (rootCorootSpan x).toAddSubgroup μ))
      ℤ (rootCorootSpan x).toAddSubgroup :=
  UniversalEnvelopingAlgebra.kostantWeightBasis x (corootFamily H) _ _
    hx.kostantForm_apply_mem_rootCorootSpan hx.toIsSl2System.mem_iSup_jointWeightSpace

/-- The defining equation of `EpsilonEridani.IsChevalleySystem.chevalleyWeightBasis`: it is the Kostant
weight basis of the Chevalley lattice, so the whole `kostantWeightBasis` API applies to it. -/
theorem chevalleyWeightBasis_def :
    hx.chevalleyWeightBasis =
      UniversalEnvelopingAlgebra.kostantWeightBasis x (corootFamily H)
        (UniversalEnvelopingAlgebra.representation ℚ L L) (rootCorootSpan x).toAddSubgroup
        hx.kostantForm_apply_mem_rootCorootSpan hx.toIsSl2System.mem_iSup_jointWeightSpace :=
  (rfl)

/-- **The weight basis consists of weight vectors** of the weights recorded by the first component
of its index. -/
theorem isCartanWeightVector_chevalleyWeightBasis
    (a : Σ μ : Weight ℚ H L → ℤ, Module.Free.ChooseBasisIndex ℤ
      (UniversalEnvelopingAlgebra.weightSublattice (corootFamily H)
        (UniversalEnvelopingAlgebra.representation ℚ L L)
        (rootCorootSpan x).toAddSubgroup μ)) :
    UniversalEnvelopingAlgebra.IsCartanWeightVector (corootFamily H)
      (UniversalEnvelopingAlgebra.representation ℚ L L) a.1
      ((hx.chevalleyWeightBasis a : (rootCorootSpan x).toAddSubgroup) : L) := by
  rw [hx.chevalleyWeightBasis_def]
  exact UniversalEnvelopingAlgebra.isCartanWeightVector_kostantWeightBasis x (corootFamily H) _ _
    hx.kostantForm_apply_mem_rootCorootSpan hx.toIsSl2System.mem_iSup_jointWeightSpace a

/-- The weight basis of the Chevalley lattice, numbered by `Fin`: the shape in which the split
torus, the matrix coordinates and the generated group scheme read a basis. -/
noncomputable def chevalleyWeightBasisFin :
    Module.Basis (Fin (rootCorootWeightBasisCard x)) ℤ (rootCorootSpan x).toAddSubgroup :=
  UniversalEnvelopingAlgebra.kostantWeightBasisFin x (corootFamily H) _ _
    hx.kostantForm_apply_mem_rootCorootSpan hx.toIsSl2System.mem_iSup_jointWeightSpace

/-- The defining equation of `EpsilonEridani.IsChevalleySystem.chevalleyWeightBasisFin`, through which
`EpsilonEridani.UniversalEnvelopingAlgebra.kostantWeightBasisFin_apply` and the rest of the numbered-basis
API apply to it. -/
theorem chevalleyWeightBasisFin_def :
    hx.chevalleyWeightBasisFin =
      UniversalEnvelopingAlgebra.kostantWeightBasisFin x (corootFamily H)
        (UniversalEnvelopingAlgebra.representation ℚ L L) (rootCorootSpan x).toAddSubgroup
        hx.kostantForm_apply_mem_rootCorootSpan hx.toIsSl2System.mem_iSup_jointWeightSpace :=
  (rfl)

/-- The weight carried by each vector of the numbered weight basis of the Chevalley lattice. -/
noncomputable def chevalleyWeightFin :
    Fin (rootCorootWeightBasisCard x) → Weight ℚ H L → ℤ :=
  UniversalEnvelopingAlgebra.kostantWeightFin x (corootFamily H) _ _
    hx.kostantForm_apply_mem_rootCorootSpan hx.toIsSl2System.mem_iSup_jointWeightSpace

/-- The defining equation of `EpsilonEridani.IsChevalleySystem.chevalleyWeightFin`. -/
theorem chevalleyWeightFin_def :
    hx.chevalleyWeightFin =
      UniversalEnvelopingAlgebra.kostantWeightFin x (corootFamily H)
        (UniversalEnvelopingAlgebra.representation ℚ L L) (rootCorootSpan x).toAddSubgroup
        hx.kostantForm_apply_mem_rootCorootSpan hx.toIsSl2System.mem_iSup_jointWeightSpace :=
  (rfl)

/-- **The numbered weight basis consists of weight vectors** of the recorded weights. Together with
`EpsilonEridani.IsChevalleySystem.chevalleyWeightBasisFin` this is the weight datum that the split torus of
the pinning takes as given. -/
theorem isCartanWeightVector_chevalleyWeightBasisFin (i : Fin (rootCorootWeightBasisCard x)) :
    UniversalEnvelopingAlgebra.IsCartanWeightVector (corootFamily H)
      (UniversalEnvelopingAlgebra.representation ℚ L L) (hx.chevalleyWeightFin i)
      ((hx.chevalleyWeightBasisFin i : (rootCorootSpan x).toAddSubgroup) : L) :=
  UniversalEnvelopingAlgebra.isCartanWeightVector_kostantWeightBasisFin x (corootFamily H) _ _
    hx.kostantForm_apply_mem_rootCorootSpan hx.toIsSl2System.mem_iSup_jointWeightSpace i

/-- The rank of the Chevalley lattice is the number of vectors of its weight basis. -/
theorem rootCorootWeightBasisCard_eq_finrank :
    rootCorootWeightBasisCard x = Module.finrank ℤ (rootCorootSpan x).toAddSubgroup :=
  UniversalEnvelopingAlgebra.nat_card_kostantWeightBasis_index_eq_finrank x (corootFamily H) _ _
    hx.kostantForm_apply_mem_rootCorootSpan hx.toIsSl2System.mem_iSup_jointWeightSpace

/-! ## The torus of coroot cocharacters on the points of the Chevalley lattice -/

section Torus

/-- **The diagonal coroot-parameter torus action on the Chevalley lattice.** Over any commutative
ring `A` it acts on `A ⊗[ℤ] L_ℤ`, scaling the base-changed weight-basis vector `b i` by the value at
`s` of its character `chevalleyWeightFin i`.

The parameter is indexed by all weights of `L` rather than by the roots alone; at the zero weight
the coroot vanishes, and with it both the cocharacter
(`EpsilonEridani.corootFamily_eq_zero_of_isZero`) and the weights of the generators
(`EpsilonEridani.rootCartanWeight_eq_zero_of_isZero`). This is not yet the maximal torus of the Layer 9
pinning: exhibiting that needs a rank-`ℓ` cocharacter datum, equivalently the simply connected
lattice, which the adjoint lattice does not supply. -/
noncomputable def chevalleyTorusPoints (A : Type*) [CommRing A] [Algebra ℤ A] :
    (Weight ℚ H L → Aˣ) →*
      LinearMap.GeneralLinearGroup A (A ⊗[ℤ] (rootCorootSpan x).toAddSubgroup) :=
  UniversalEnvelopingAlgebra.kostantTorusPoints (rootCorootSpan x).toAddSubgroup
    hx.chevalleyWeightBasisFin hx.chevalleyWeightFin A

/-- The image of the diagonal coroot-parameter action in the general linear group. -/
noncomputable def chevalleyTorusSubgroup (A : Type*) [CommRing A] [Algebra ℤ A] :
    Subgroup (LinearMap.GeneralLinearGroup A (A ⊗[ℤ] (rootCorootSpan x).toAddSubgroup)) :=
  (hx.chevalleyTorusPoints A).range

/-- The Chevalley torus subgroup is the range of the torus-points homomorphism. -/
theorem chevalleyTorusSubgroup_eq_range (A : Type*) [CommRing A] [Algebra ℤ A] :
    hx.chevalleyTorusSubgroup A = (hx.chevalleyTorusPoints A).range :=
  (rfl)

/-- **A torus point acts on a weight vector of the Chevalley lattice by the value of its
character.** In particular the root vector `x β` is scaled by
`torusCharacter s (rootCartanWeight β)`, that is by `∏ α, (s α) ^ (β α∨)`. This is the equation
that identifies the character by which the torus acts on each weight component. -/
theorem chevalleyTorusPoints_tmul_of_isCartanWeightVector {A : Type*} [CommRing A] [Algebra ℤ A]
    {μ : Weight ℚ H L → ℤ} {m : (rootCorootSpan x).toAddSubgroup}
    (hm : UniversalEnvelopingAlgebra.IsCartanWeightVector (corootFamily H)
      (UniversalEnvelopingAlgebra.representation ℚ L L) μ (m : L))
    (s : Weight ℚ H L → Aˣ) (a : A) :
    (hx.chevalleyTorusPoints A s).val (a ⊗ₜ[ℤ] m) = ((torusCharacter s μ : A) * a) ⊗ₜ[ℤ] m :=
  UniversalEnvelopingAlgebra.kostantTorusPoints_tmul_of_isCartanWeightVector x (corootFamily H)
    (UniversalEnvelopingAlgebra.representation ℚ L L) _
    hx.kostantForm_apply_mem_rootCorootSpan
    hx.chevalleyWeightBasisFin hx.chevalleyWeightFin
    hx.isCartanWeightVector_chevalleyWeightBasisFin hm s a

/-- A Chevalley torus point scales a base-changed weight-basis vector by its recorded character. -/
@[simp] theorem chevalleyTorusPoints_tmul_basis {A : Type*} [CommRing A] [Algebra ℤ A]
    (s : Weight ℚ H L → Aˣ) (a : A) (i : Fin (rootCorootWeightBasisCard x)) :
    (hx.chevalleyTorusPoints A s).val (a ⊗ₜ[ℤ] hx.chevalleyWeightBasisFin i) =
      ((torusCharacter s (hx.chevalleyWeightFin i) : A) * a) ⊗ₜ[ℤ]
        hx.chevalleyWeightBasisFin i := by
  exact UniversalEnvelopingAlgebra.kostantTorusPoints_tmul_basis _ _ _ s a i

/-- A Chevalley torus point scales a base-changed root-vector generator by its Cartan character. -/
theorem chevalleyTorusPoints_tmul_rootVector {A : Type*} [CommRing A] [Algebra ℤ A]
    (β : Weight ℚ H L) (s : Weight ℚ H L → Aˣ) (a : A) :
    (hx.chevalleyTorusPoints A s).val
        (a ⊗ₜ[ℤ] (⟨x β, rootVector_mem_rootCorootSpan x β⟩ : (rootCorootSpan x).toAddSubgroup)) =
      ((torusCharacter s (rootCartanWeight β) : A) * a) ⊗ₜ[ℤ]
        (⟨x β, rootVector_mem_rootCorootSpan x β⟩ : (rootCorootSpan x).toAddSubgroup) :=
  hx.chevalleyTorusPoints_tmul_of_isCartanWeightVector
    (hx.toIsSl2System.isCartanWeightVector_rootVector β) s a

/-- Naturality of the Chevalley torus action in the value ring. -/
theorem map_chevalleyTorusPoints {A B : Type*} [CommRing A] [CommRing B]
    (φ : A →+* B) (s : Weight ℚ H L → Aˣ) (z : A ⊗[ℤ] (rootCorootSpan x).toAddSubgroup) :
    TensorProduct.map φ.toIntAlgHom.toLinearMap LinearMap.id
        ((hx.chevalleyTorusPoints A s).val z) =
      (hx.chevalleyTorusPoints B fun α => Units.map (φ : A →* B) (s α)).val
        (TensorProduct.map φ.toIntAlgHom.toLinearMap LinearMap.id z) := by
  exact UniversalEnvelopingAlgebra.map_kostantTorusPoints _ _ _ φ s z

/-- Scalar extension carries a Chevalley torus point to the point with mapped parameters. -/
theorem mapScalarExtensionAutomorphisms_chevalleyTorusPoints {A B : CommAlgCat.{w} ℤ}
    (φ : A ⟶ B) (s : Weight ℚ H L → Aˣ) :
    GeneralLinear.mapScalarExtensionAutomorphisms (V := (rootCorootSpan x).toAddSubgroup) φ
        (hx.chevalleyTorusPoints A s) =
      hx.chevalleyTorusPoints B fun α => Units.map φ.hom.toRingHom.toMonoidHom (s α) := by
  exact UniversalEnvelopingAlgebra.mapScalarExtensionAutomorphisms_kostantTorusPoints _ _ _ φ s

/-- The Chevalley torus action in the coordinates of its numbered weight basis. -/
noncomputable def chevalleyTorusMatrix {A : Type*} [CommRing A] [Algebra ℤ A] :
    (Weight ℚ H L → Aˣ) →* Matrix.GeneralLinearGroup
      (Fin (rootCorootWeightBasisCard x)) A :=
  UniversalEnvelopingAlgebra.kostantTorusMatrix (rootCorootSpan x).toAddSubgroup
    hx.chevalleyWeightBasisFin hx.chevalleyWeightFin

/-- In the Chevalley weight basis, a torus point is diagonal with its weight characters. -/
@[simp] theorem chevalleyTorusMatrix_apply {A : Type*} [CommRing A] [Algebra ℤ A]
    (s : Weight ℚ H L → Aˣ) :
    hx.chevalleyTorusMatrix s = diagGL fun i => torusCharacter s (hx.chevalleyWeightFin i) := by
  exact UniversalEnvelopingAlgebra.kostantTorusMatrix_apply _ _ _ s

end Torus

end IsChevalleySystem

end EpsilonEridani
