/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.Algebra.Lie.HighestWeight.Maximal
import EpsilonEridani.Algebra.Lie.Submodule.Atom
import EpsilonEridani.Algebra.Lie.Weights.Eigenvector

/-!
# The integrability relation of a highest weight module

Let `L` be a finite-dimensional Lie algebra with non-degenerate Killing form over a field of
characteristic zero, `H` a splitting Cartan subalgebra, `b` a base of its root system, and `M` a
module generated by a highest weight vector `v` of weight `lam`.  Fix a simple root `αᵢ` and
suppose the highest weight is *integral along it*, `lam (αᵢ^∨) = n` for a natural number `n`.  This
file proves the **integrability relation**: the vector

`w = fᵢ^{n + 1} · v`

obtained by lowering `v` to degree `n + 1` in its `αᵢ`-string is again a highest weight vector,
of weight `lam - (n + 1) αᵢ`, as soon as it is nonzero.  Consequently it *is* zero whenever `M` is
irreducible: an irreducible module has highest weight vectors of only one weight.

The relation is the mechanism by which dominance makes a highest weight module small.  In the Verma
module `M(lam)` the vector `w` is nonzero, for a nonzero lowering vector `fᵢ`, and the submodule it
generates is then a proper submodule, hence one contained in the maximal submodule that the
irreducible quotient `L(lam)` divides out; in `L(lam)` the vector itself vanishes.  This relation
on the highest-weight generator is the first step toward proving local nilpotence along every
simple root.  The vanishing is proved here for every irreducible highest weight module, which is
what `L(lam)` will be.

## The argument

Three facts have to be checked about `w`, and they use different parts of the theory.

* **`H` acts through `lam - (n + 1) αᵢ`.**  Lowering by a root vector of `-αᵢ` subtracts `αᵢ` from
  the weight, one step at a time; this is `EpsilonEridani.lie_pow_toEnd_eq_smul_of_mem_rootSpace`, an
  induction on the number of steps out of the Leibniz rule.
* **The root space of `αᵢ` annihilates `w`.**  This is the rank-one statement, and it is exactly
  Mathlib's `IsSl2Triple.HasPrimitiveVectorWith.lie_e_pow_succ_toEnd_f`: raising `fᵢ^{k + 1} v`
  returns `(k + 1)(n - k)` times `fᵢ^k v`, which vanishes at `k = n`.  Both root spaces are lines,
  so the normalized triple of `αᵢ` computes the whole of them.
* **Every other positive root space annihilates `w`.**  Here the rank-one theory says nothing, and
  the input is the geometry of the weight cone.  A positive root `αⱼ` would move `w` to the weight
  `lam - (n + 1) αᵢ + αⱼ`, and the weights of a highest weight module lie in `lam - Q⁺`, so
  `(n + 1) αᵢ - αⱼ` would have to be a nonnegative combination of simple roots.  By
  `EpsilonEridani.eq_of_nsmul_root_sub_root_mem_posRootCone` that forces `αⱼ = αᵢ`, which is the case
  already treated.

## Main results

* `EpsilonEridani.isHighestWeightVector_pow_toEnd_of_lieSpan_eq_top_of_ne_zero`: **the integrability
  relation**, that `fᵢ^{n + 1} v` is a highest weight vector of weight `lam - (n + 1) αᵢ` when it
  is nonzero.
* `EpsilonEridani.pow_toEnd_mem_maximalSubmodule_of_isHighestWeightVector_of_lieSpan_eq_top`: it lies in
  the maximal submodule of a highest weight module, so it dies in the irreducible quotient.
* `EpsilonEridani.pow_toEnd_eq_zero_of_isHighestWeightVector_of_isIrreducible`: in an irreducible highest
  weight module it is therefore zero.

## References

This is the "integrability relation" milestone of Layer 4, "the classification of
finite-dimensional irreducibles", of
`EpsilonEridaniRoadmap/RepresentationTheory/LieHighestWeight/README.md`.

* J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*, GTM 9, §21.2 and
  §21.4.
-/

public section

namespace EpsilonEridani

open LieAlgebra LieModule Module

universe u v w

variable {K : Type u} {L : Type v} [Field K] [CharZero K] [LieRing L] [LieAlgebra K L]
  [IsKilling K L] [FiniteDimensional K L]
  {H : LieSubalgebra K L} [H.IsCartanSubalgebra] [IsTriangularizable K H L]
  {M : Type w} [AddCommGroup M] [Module K M] [LieRingModule L M] [LieModule K L M]

/-! ### The integrability relation -/

variable {b : (IsKilling.rootSystem H).Base} {lam : Dual K H} {v : M}

/-- The rank-one half of the integrability relation: for a positive root `αᵢ` along which the
highest weight is integral, the root space of `αᵢ` annihilates `fᵢ^{n + 1} v`.

The `sl₂` triple of `αᵢ` makes `v` a primitive vector of eigenvalue `n`, and Mathlib's
`IsSl2Triple.HasPrimitiveVectorWith.lie_e_pow_succ_toEnd_f` evaluates the raising operator on the
lowered vectors; the coefficient `(n + 1)(n - n)` vanishes. Since both root spaces are lines, one
normalized triple computes the bracket for every choice of raising and lowering vector. -/
theorem lie_pow_toEnd_eq_zero_of_isHighestWeightVector (hv : IsHighestWeightVector b lam v)
    {i : H.root} (hi : i ∈ posRoots (IsKilling.rootSystem H) b) {n : ℕ}
    (hn : lam ((IsKilling.rootSystem H).coroot i) = (n : K))
    {e f : L} (he : e ∈ rootSpace H ((i : Weight K H L) : H → K))
    (hf : f ∈ rootSpace H ((-(i : Weight K H L) : Weight K H L) : H → K)) :
    ⁅e, ((toEnd K L M f) ^ (n + 1)) v⁆ = 0 := by
  have hα : (i : Weight K H L).IsNonZero := H.isNonZero_coe_root i
  obtain ⟨h₀, e₀, f₀, ht, he₀, hf₀⟩ := IsKilling.exists_isSl2Triple_of_weight_isNonZero hα
  -- the generating vector is a primitive vector of eigenvalue `n` for the triple of `αᵢ`
  have hP : ht.HasPrimitiveVectorWith v (n : K) :=
    { ne_zero := hv.ne_zero
      lie_h := by
        rw [ht.h_eq_coroot hα he₀ hf₀, ← hn, IsKilling.rootSystem_coroot_apply]
        exact hv.lie_eq_smul _
      lie_e := hv.lie_eq_zero_of_mem_rootSpace hi he₀ }
  -- the two root spaces are the lines spanned by the members of the triple
  obtain ⟨c, rfl⟩ : ∃ c : K, c • e₀ = e := by
    have := IsKilling.toSubmodule_rootSpace_eq_span (i : Weight K H L) hα e₀ ht.e_ne_zero he₀
    exact Submodule.mem_span_singleton.mp (this ▸ he)
  obtain ⟨d, rfl⟩ : ∃ d : K, d • f₀ = f := by
    have := IsKilling.toSubmodule_rootSpace_eq_span (-(i : Weight K H L)) hα.neg f₀
      ht.f_ne_zero hf₀
    exact Submodule.mem_span_singleton.mp (this ▸ hf)
  have hzero : ⁅e₀, ((toEnd K L M f₀) ^ (n + 1)) v⁆ = 0 := by
    rw [hP.lie_e_pow_succ_toEnd_f n]
    simp
  rw [map_smul, smul_pow, LinearMap.smul_apply, smul_lie, lie_smul, hzero, smul_zero, smul_zero]

/-- **The integrability relation.** Let `M` be a highest weight module of weight `lam` generated by
`v`, let `αᵢ` be a simple root and suppose `lam (αᵢ^∨) = n` is a natural number. Then the lowered
vector `fᵢ^{n + 1} v` is, whenever it is nonzero, again a highest weight vector, of weight
`lam - (n + 1) αᵢ`.

Its `H`-eigenvalue is read off `EpsilonEridani.lie_pow_toEnd_eq_smul_of_mem_rootSpace`. Of the positive
root spaces, that of `αᵢ` annihilates it by the rank-one theory, and every other one does so
because it would otherwise produce a weight above the cone `lam - Q⁺` that bounds a highest weight
module. -/
theorem isHighestWeightVector_pow_toEnd_of_lieSpan_eq_top_of_ne_zero
    (hv : IsHighestWeightVector b lam v)
    (hgen : LieSubmodule.lieSpan K L {v} = ⊤) {i : H.root} (hi : i ∈ b.support) {n : ℕ}
    (hn : lam ((IsKilling.rootSystem H).coroot i) = (n : K))
    {f : L} (hf : f ∈ rootSpace H ((-(i : Weight K H L) : Weight K H L) : H → K))
    (hw : ((toEnd K L M f) ^ (n + 1)) v ≠ 0) :
    IsHighestWeightVector b (lam - (n + 1) • (IsKilling.rootSystem H).root i)
      (((toEnd K L M f) ^ (n + 1)) v) := by
  set w := ((toEnd K L M f) ^ (n + 1)) v with hwdef
  set mu : Dual K H := lam - (n + 1) • (IsKilling.rootSystem H).root i with hmudef
  -- the Cartan subalgebra acts on `w` through `mu`
  have hcartan : ∀ x : H, ⁅(x : L), w⁆ = mu x • w := by
    intro x
    rw [hwdef, lie_pow_toEnd_eq_smul_of_mem_rootSpace (chi := (lam : H → K))
      (fun y => hv.lie_eq_smul y) hf (n + 1) x]
    congr 1
    simp only [hmudef, LinearMap.sub_apply, LinearMap.smul_apply, IsKilling.rootSystem_root_apply,
      Weight.toLinear_apply, Weight.coe_neg, Pi.neg_apply, nsmul_eq_mul, Nat.cast_add,
      Nat.cast_one]
    ring
  have : IsAddTorsionFree (Dual K H) := IsAddTorsionFree.of_isTorsionFree K _
  have : IsAddTorsionFree H := IsAddTorsionFree.of_isTorsionFree K _
  refine isHighestWeightVector_of_forall_rootSpace hw hcartan fun j hj x hx => ?_
  rcases eq_or_ne j i with rfl | hji
  · exact lie_pow_toEnd_eq_zero_of_isHighestWeightVector hv
      (support_subset_posRoots (IsKilling.rootSystem H) b hi) hn hx hf
  -- a positive root other than `αᵢ` would raise `w` out of the cone below `lam`
  · by_contra hne
    -- the weight of `⁅x, w⁆`, a sum in `Dual K H`, as the sum of the two weight functions
    have hcoe : (((IsKilling.rootSystem H).root j + mu : Dual K H) : H → K)
        = ((j : Weight K H L) : H → K) + ((mu : Dual K H) : H → K) := by
      rw [LinearMap.coe_add, IsKilling.rootSystem_root_apply, Weight.coe_coe]
    have hmem : ⁅x, w⁆ ∈ genWeightSpace M
        (((IsKilling.rootSystem H).root j + mu : Dual K H) : H → K) := by
      have hmaps := mapsTo_toEnd_genWeightSpace_add_of_mem_rootSpace (R := K) (L := L) (H := H)
        (M := M) ((j : Weight K H L) : H → K) ((mu : Dual K H) : H → K) hx
      rw [hcoe]
      exact hmaps (mem_genWeightSpace_of_forall_lie_eq_smul hcartan)
    have hbot : genWeightSpace M
        ((((IsKilling.rootSystem H).root j + mu : Dual K H)) : H → K) ≠ ⊥ := fun hb => by
      rw [hb] at hmem
      exact hne (by simpa using hmem)
    have hcone :=
      sub_mem_posRootCone_of_genWeightSpace_ne_bot_of_isHighestWeightVector_of_lieSpan_eq_top
        hv hgen hbot
    have hrewrite : lam - ((IsKilling.rootSystem H).root j + mu)
        = (n + 1) • (IsKilling.rootSystem H).root i - (IsKilling.rootSystem H).root j := by
      rw [hmudef]; abel
    rw [hrewrite] at hcone
    exact hji (eq_of_nsmul_root_sub_root_mem_posRootCone (IsKilling.rootSystem H) b hi hj hcone)

/-! ### Vanishing in the irreducible quotient -/

/-- A weight is not obtained from itself by subtracting a positive multiple of a root. -/
private theorem ne_sub_nsmul_root (lam : Dual K H) (i : H.root) (n : ℕ) :
    lam ≠ lam - (n + 1) • (IsKilling.rootSystem H).root i := fun heq => by
  have : IsAddTorsionFree (Dual K H) := IsAddTorsionFree.of_isTorsionFree K _
  exact (IsKilling.rootSystem H).ne_zero i
    ((nsmul_eq_zero_iff_right n.succ_ne_zero).mp (sub_eq_self.mp heq.symm))

/-- **The lowered vector dies in the irreducible quotient.** In a highest weight module of weight
`lam` generated by `v`, the vector `fᵢ^{n + 1} v` lies in the maximal submodule
`EpsilonEridani.maximalSubmodule`, so it maps to `0` in the irreducible quotient.

If it is nonzero it is a highest weight vector of weight `lam - (n + 1) αᵢ`, so the submodule it
generates cannot be everything: a module is a highest weight module for at most one weight. The
maximal submodule of a highest weight module is its greatest proper submodule, so that submodule
lies inside it. -/
theorem pow_toEnd_mem_maximalSubmodule_of_isHighestWeightVector_of_lieSpan_eq_top
    (hv : IsHighestWeightVector b lam v) (hgen : LieSubmodule.lieSpan K L {v} = ⊤)
    {i : H.root} (hi : i ∈ b.support) {n : ℕ}
    (hn : lam ((IsKilling.rootSystem H).coroot i) = (n : K))
    {f : L} (hf : f ∈ rootSpace H ((-(i : Weight K H L) : Weight K H L) : H → K)) :
    ((toEnd K L M f) ^ (n + 1)) v ∈ maximalSubmodule H M lam := by
  rcases eq_or_ne (((toEnd K L M f) ^ (n + 1)) v) 0 with hzero | hw
  · rw [hzero]
    exact zero_mem _
  have hhw := isHighestWeightVector_pow_toEnd_of_lieSpan_eq_top_of_ne_zero hv hgen hi hn hf hw
  have hproper : LieSubmodule.lieSpan K L {((toEnd K L M f) ^ (n + 1)) v} ≠ ⊤ := fun htop =>
    ne_sub_nsmul_root lam i n (eq_of_isHighestWeightVector_of_lieSpan_eq_top hv hgen hhw htop)
  exact (le_maximalSubmodule_iff_ne_top_of_isHighestWeightVector_of_lieSpan_eq_top hv
    hgen).mpr hproper (LieSubmodule.subset_lieSpan rfl)

/-- **The integrability relation in an irreducible highest weight module.** If `M` is irreducible
with highest weight vector `v` of weight `lam`, and `lam (αᵢ^∨) = n` is a natural number, then
`fᵢ^{n + 1} v = 0`.

This is the integrability relation on the highest-weight generator. Were the lowered vector
nonzero it would be a highest weight vector of weight `lam - (n + 1) αᵢ`, and an irreducible module
carries highest weight vectors of only one weight
(`EpsilonEridani.IsHighestWeightVector.unique_of_isIrreducible`). -/
theorem pow_toEnd_eq_zero_of_isHighestWeightVector_of_isIrreducible
    [LieModule.IsIrreducible K L M] (hv : IsHighestWeightVector b lam v) {i : H.root}
    (hi : i ∈ b.support) {n : ℕ} (hn : lam ((IsKilling.rootSystem H).coroot i) = (n : K))
    {f : L} (hf : f ∈ rootSpace H ((-(i : Weight K H L) : Weight K H L) : H → K)) :
    ((toEnd K L M f) ^ (n + 1)) v = 0 := by
  by_contra hw
  exact ne_sub_nsmul_root lam i n (hv.unique_of_isIrreducible
    (isHighestWeightVector_pow_toEnd_of_lieSpan_eq_top_of_ne_zero hv
      (lieSpan_singleton_eq_top_of_ne_zero hv.ne_zero) hi hn hf hw))

end EpsilonEridani
