/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.Algebra.Lie.HighestWeight.Module
import EpsilonEridani.Algebra.Lie.Submodule.Atom

/-!
# The maximal submodule of a highest weight module, and its irreducible quotient

A highest weight module has a *greatest* proper submodule, namely the sum of all the submodules
that meet its top weight space trivially, and therefore a unique irreducible quotient. This file
builds that submodule, `EpsilonEridani.maximalSubmodule`, and proves both statements.

## The argument

The `lam`-weight space of a highest weight module is the line `K ∙ v` spanned by the generator
(`EpsilonEridani.genWeightSpace_eq_span_singleton_of_isHighestWeightVector_of_lieSpan_eq_top`), so a
submodule meets it trivially exactly when it misses `v`, which in turn is exactly when it is
proper. What is not formal is that the *sum* of such submodules still misses `v`, and that is the
content of the file: a Lie submodule missing `v` is contained in the span of the weight spaces at
the weights other than `lam`, a submodule which misses `v` for the trivial reason that the weight
spaces are independent.

That containment is the statement that a submodule is compatible with the weight grading, in the
one degree where it is needed. Since a highest weight module is spanned by the weight spaces below
`lam` and its `lam`-weight space is `K ∙ v`, an element of a submodule `N` can be written as
`c • v + m` with `m` a sum of finitely many vectors of weights other than `lam`, and the claim is
that already `c • v ∈ N`. One weight of `m` is removed at a time. If `m` has a component `m₀` of
weight `chi ≠ lam`, pick `x : H` with `chi x ≠ lam x` and a `k` with `(x - chi x)^k` killing `m₀`;
applying that operator to `c • v + m` leaves an element of `N` of the same shape, with `m₀` gone
and `c` multiplied by `(lam x - chi x)^k ≠ 0`, since `v` is an honest eigenvector of `x`. Both
`N` and the span of the remaining weight spaces are stable under the operator, so the induction
goes through.

## Main definitions

* `EpsilonEridani.maximalSubmodule H M lam`: the sum of all Lie submodules of `M` meeting the
  `lam`-weight space trivially.

## Main results

* `EpsilonEridani.genWeightSpace_sup_genWeightSpaceSpan_eq_top_of_isHighestWeightVector_of_lieSpan_eq_top`:
  a highest weight module is the sum of its `lam`-weight space and the span of its other weight
  spaces, and `EpsilonEridani.disjoint_genWeightSpace_genWeightSpaceSpan_ne` says the two meet trivially.
* `EpsilonEridani.le_genWeightSpaceSpan_ne_of_notMem_of_isHighestWeightVector_of_lieSpan_eq_top`: **a Lie
  submodule of a highest weight module which misses the generator misses the whole top weight
  space**, being contained in the span of the other weight spaces.
* `EpsilonEridani.notMem_iff_ne_top_of_isHighestWeightVector_of_lieSpan_eq_top` and
  `EpsilonEridani.disjoint_genWeightSpace_iff_notMem_of_isHighestWeightVector_of_lieSpan_eq_top`: for a
  Lie submodule of a highest weight module, being proper, missing the generator and meeting the
  top weight space trivially are the same condition.
* `EpsilonEridani.notMem_maximalSubmodule_of_isHighestWeightVector_of_lieSpan_eq_top` and
  `EpsilonEridani.isGreatest_maximalSubmodule_of_isHighestWeightVector_of_lieSpan_eq_top`: **the maximal
  submodule of a highest weight module is its greatest proper submodule**, so by
  `EpsilonEridani.eq_top_of_maximalSubmodule_lt_of_isHighestWeightVector_of_lieSpan_eq_top` anything
  strictly above it is everything.
* `EpsilonEridani.isCoatom_maximalSubmodule_of_isHighestWeightVector_of_lieSpan_eq_top`: **it is a coatom**
  of the lattice of Lie submodules, so by `EpsilonEridani.isIrreducible_quotient_iff_isCoatom` the quotient
  by it is irreducible.
* `EpsilonEridani.isIrreducible_quotient_maximalSubmodule_of_isHighestWeightVector_of_lieSpan_eq_top`:
  **the quotient by it is irreducible**, and
  `EpsilonEridani.isHighestWeightVector_mk_of_isHighestWeightVector_of_lieSpan_eq_top` together with
  `EpsilonEridani.lieSpan_mk_eq_top_of_lieSpan_eq_top` exhibit that quotient as again a highest weight
  module of weight `lam`, generated by the image of the generator.

## Implementation notes

`EpsilonEridani.maximalSubmodule` is defined for an arbitrary module, as the sum of the submodules meeting
the `lam`-weight space trivially; it is only for a highest weight module of weight `lam` that it is
the greatest proper submodule, and the results asserting that carry the hypotheses. Defining it
intrinsically, rather than as the sum of the submodules missing a chosen generator, is what makes
it manifestly independent of the choice of generator.

Nothing here needs the module to be finite-dimensional: the Verma module of Layer 3 of the roadmap,
whose irreducible quotient is `L(lam)`, is infinite-dimensional, and it is the module this file
exists to be applied to. In particular the weight spaces are the *generalized* ones throughout, and
the one place where an honest eigenvector is needed is the generator itself, which is one by the
definition of `EpsilonEridani.IsHighestWeightVector`.

## References

This is the "irreducible quotient `L(λ)`" item of Layer 3 of
`EpsilonEridaniRoadmap/RepresentationTheory/LieHighestWeight/README.md`: "`M(λ)` has a **unique maximal
submodule** (the sum of all submodules meeting the `λ`-weight space trivially), hence a unique
irreducible quotient `L(λ)`". Since the Verma module `M(λ)` itself is not yet built, the statements
are proved for an arbitrary highest weight module, which is how `L(λ)` will consume them.

* J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*, GTM 9, §20.3.
-/

public section

namespace EpsilonEridani

open LieAlgebra LieModule Module

universe u v w x

variable {K : Type u} {L : Type v} [Field K] [CharZero K] [LieRing L] [LieAlgebra K L]
  [IsKilling K L] [FiniteDimensional K L]
  {H : LieSubalgebra K L} [H.IsCartanSubalgebra] [IsTriangularizable K H L]
  {M : Type w} [AddCommGroup M] [Module K M] [LieRingModule L M] [LieModule K L M]

/-! ### Powers of a shifted Cartan operator -/

omit [CharZero K] [IsKilling K L] [FiniteDimensional K L] [H.IsCartanSubalgebra]
  [IsTriangularizable K H L] in
/-- A submodule stable under the action of `x : H` is stable under every power of `x - mu`. This is
applied both to a Lie submodule and to a span of weight spaces. -/
private theorem pow_toEnd_sub_smul_mem {P : Submodule K M} {x : H}
    (hP : ∀ m ∈ P, toEnd K H M x m ∈ P) (mu : K) (k : ℕ) :
    ∀ m ∈ P, ((toEnd K H M x - mu • (1 : Module.End K M)) ^ k) m ∈ P := by
  induction k with
  | zero => intro m hm; simpa using hm
  | succ k ih =>
    intro m hm
    rw [pow_succ, Module.End.mul_apply]
    refine ih _ ?_
    have hsub : (toEnd K H M x - mu • (1 : Module.End K M)) m = toEnd K H M x m - mu • m := by
      simp
    rw [hsub]
    exact sub_mem (hP m hm) (Submodule.smul_mem _ _ hm)

omit [CharZero K] [IsKilling K L] [FiniteDimensional K L] [H.IsCartanSubalgebra]
  [IsTriangularizable K H L] in
/-- An honest eigenvector of `x : H` with eigenvalue `nu` is an eigenvector of every power of
`⁅x, -⁆ - mu`, with eigenvalue `(nu - mu) ^ k`. -/
private theorem pow_toEnd_sub_smul_apply {x : H} {mu nu : K} {v : M}
    (hv : ⁅(x : L), v⁆ = nu • v) (k : ℕ) :
    ((toEnd K H M x - mu • (1 : Module.End K M)) ^ k) v = (nu - mu) ^ k • v := by
  induction k with
  | zero => simp
  | succ k ih =>
    rw [pow_succ, Module.End.mul_apply]
    have hsub : (toEnd K H M x - mu • (1 : Module.End K M)) v = (nu - mu) • v := by
      simp [LieSubalgebra.coe_bracket_of_module, hv, sub_smul]
    rw [hsub, map_smul, ih, smul_smul, pow_succ, mul_comm]

/-! ### The weight spaces other than the top one -/

variable (b : (IsKilling.rootSystem H).Base) {lam : Dual K H} {v : M}

omit [CharZero K] [IsKilling K L] [FiniteDimensional K L] [H.IsCartanSubalgebra]
  [IsTriangularizable K H L] in
variable (H M) [LieRing.IsNilpotent H] in
/-- **The top weight space is disjoint from the span of the other weight spaces**, the weight
spaces of a module being independent. -/
theorem disjoint_genWeightSpace_genWeightSpaceSpan_ne (lam : Dual K H) :
    Disjoint (genWeightSpace M ((lam : Dual K H) : H → K))
      (genWeightSpaceSpan H M {chi | chi ≠ ((lam : Dual K H) : H → K)}) :=
  (iSupIndep_genWeightSpace K H M ((lam : Dual K H) : H → K)).mono_right
    (genWeightSpaceSpan_le_iff.mpr fun _ hchi => le_iSup₂_of_le _ hchi le_rfl)

variable {b}

/-- **A highest weight module is the sum of its top weight space and the span of its other weight
spaces.** Every weight space of a highest weight module sits at a weight `lam - nu`, which is
either `lam` itself or one of the others. -/
theorem genWeightSpace_sup_genWeightSpaceSpan_eq_top_of_isHighestWeightVector_of_lieSpan_eq_top
    (hv : IsHighestWeightVector b lam v) (hgen : LieSubmodule.lieSpan K L {v} = ⊤) :
    genWeightSpace M ((lam : Dual K H) : H → K)
        ⊔ genWeightSpaceSpan H M {chi | chi ≠ ((lam : Dual K H) : H → K)} = ⊤ := by
  refine eq_top_iff.mpr ?_
  rw [← iSup_genWeightSpace_sub_posRootCone_eq_top_of_isHighestWeightVector_of_lieSpan_eq_top hv
    hgen]
  refine iSup₂_le fun nu _ => ?_
  by_cases h : ((lam - nu : Dual K H) : H → K) = ((lam : Dual K H) : H → K)
  · rw [h]
    exact le_sup_left
  · exact le_sup_of_le_right (genWeightSpace_le_genWeightSpaceSpan h)

/-! ### Submodules missing the generator -/

/-- The heart of the file: if an element of a Lie submodule `N` is `c • v` plus a vector supported
on finitely many weights other than `lam`, then already `c • v ∈ N`.

The induction removes one weight at a time, by applying a power of `⁅x, -⁆ - chi x` for an `x : H`
separating that weight from `lam`. -/
private theorem smul_mem_of_add_mem_iSup (hv : IsHighestWeightVector b lam v)
    {N : LieSubmodule K L M}
    (s : Finset {chi : H → K // chi ≠ ((lam : Dual K H) : H → K)}) :
    ∀ (c : K) (m : M),
      m ∈ ⨆ chi ∈ s, (genWeightSpace M (chi : H → K) : Submodule K M) →
        c • v + m ∈ N → c • v ∈ N := by
  classical
  induction s using Finset.induction with
  | empty =>
    intro c m hm hcm
    have hm_zero : m = 0 := by simpa using hm
    subst m
    simpa using hcm
  | insert chi0 s _ ih =>
    intro c m hm hcm
    rw [Finset.iSup_insert] at hm
    obtain ⟨m0, hm0, m', hm', rfl⟩ := Submodule.mem_sup.mp hm
    -- separate the weight `chi0` from `lam`
    obtain ⟨x, hx⟩ : ∃ x : H, (chi0 : H → K) x ≠ ((lam : Dual K H) : H → K) x := by
      by_contra! hcontra
      exact chi0.2 (funext hcontra)
    obtain ⟨k, hk⟩ := (mem_genWeightSpace M (chi0 : H → K) m0).mp hm0 x
    set f := (toEnd K H M x - (chi0 : H → K) x • (1 : Module.End K M)) with hf
    -- the scalar by which the operator below multiplies the generator
    set d := (((lam : Dual K H) : H → K) x - (chi0 : H → K) x) ^ k with hdef
    -- the surviving part stays inside the span of the remaining weight spaces
    have hcomap : (⨆ chi ∈ s, (genWeightSpace M (chi : H → K) : Submodule K M))
        ≤ Submodule.comap (toEnd K H M x)
          (⨆ chi ∈ s, (genWeightSpace M (chi : H → K) : Submodule K M)) :=
      iSup₂_le fun chi hchi n hn =>
        Submodule.mem_comap.mpr (Submodule.mem_iSup_of_mem chi
          (Submodule.mem_iSup_of_mem hchi (LieSubmodule.lie_mem _ hn)))
    have hstab : ∀ n ∈ (⨆ chi ∈ s, (genWeightSpace M (chi : H → K) : Submodule K M)),
        toEnd K H M x n ∈ (⨆ chi ∈ s, (genWeightSpace M (chi : H → K) : Submodule K M)) :=
      fun n hn => hcomap hn
    have hm'mem := pow_toEnd_sub_smul_mem hstab ((chi0 : H → K) x) k m' hm'
    -- the whole element stays inside `N`
    have hNstab : ∀ n ∈ (N : Submodule K M), toEnd K H M x n ∈ (N : Submodule K M) :=
      fun n hn => N.lie_mem hn
    have hcmN := pow_toEnd_sub_smul_mem hNstab ((chi0 : H → K) x) k _ hcm
    -- compute the image
    have hvimage : (f ^ k) (c • v) = (c * d) • v := by
      rw [map_smul, hf, hdef, pow_toEnd_sub_smul_apply (hv.lie_eq_smul x), smul_smul]
    rw [map_add, map_add, hvimage, hk, zero_add] at hcmN
    have hd : d ≠ 0 := pow_ne_zero _ (sub_ne_zero.mpr (Ne.symm hx))
    have hcd := ih _ _ hm'mem hcmN
    have hfinal := Submodule.smul_mem (N : Submodule K M) d⁻¹ hcd
    have hscalar : d⁻¹ * (c * d) = c := by field_simp
    rwa [smul_smul, hscalar] at hfinal

/-- **A Lie submodule of a highest weight module which misses the generator misses the whole top
weight space**: it is contained in the span of the weight spaces at the other weights.

This is the weight-compatibility of submodules, in the degree where it is needed: the `lam`-part of
an element of a submodule already lies in that submodule, so a submodule with no `lam`-part at all
is supported on the other weights. -/
theorem le_genWeightSpaceSpan_ne_of_notMem_of_isHighestWeightVector_of_lieSpan_eq_top
    (hv : IsHighestWeightVector b lam v) (hgen : LieSubmodule.lieSpan K L {v} = ⊤)
    {N : LieSubmodule K L M} (hvN : v ∉ N) :
    (N : Submodule K M)
      ≤ (genWeightSpaceSpan H M {chi | chi ≠ ((lam : Dual K H) : H → K)} : Submodule K M) := by
  intro n hn
  -- split `n` along the sum decomposition of the module
  have htop :=
    genWeightSpace_sup_genWeightSpaceSpan_eq_top_of_isHighestWeightVector_of_lieSpan_eq_top hv hgen
  have hmem : n ∈ (genWeightSpace M ((lam : Dual K H) : H → K) : Submodule K M)
      ⊔ (genWeightSpaceSpan H M {chi | chi ≠ ((lam : Dual K H) : H → K)} : Submodule K M) := by
    rw [← LieSubmodule.sup_toSubmodule, htop]
    trivial
  obtain ⟨y, hy, m, hm, rfl⟩ := Submodule.mem_sup.mp hmem
  -- the top part is a multiple of the generator, and lies in `N`, so it vanishes
  rw [genWeightSpace_eq_span_singleton_of_isHighestWeightVector_of_lieSpan_eq_top hv hgen,
    Submodule.mem_span_singleton] at hy
  obtain ⟨c, rfl⟩ := hy
  rw [genWeightSpaceSpan_eq_iSup] at hm
  rw [LieSubmodule.iSup_toSubmodule, Submodule.mem_iSup_iff_exists_finset] at hm
  obtain ⟨s, hs⟩ := hm
  have hcv : c • v ∈ N := smul_mem_of_add_mem_iSup hv s c m hs hn
  have hc : c = 0 := by
    by_contra hc
    exact hvN (by simpa [hc, smul_smul] using N.smul_mem c⁻¹ hcv)
  rw [hc, zero_smul, zero_add] at hn ⊢
  rw [genWeightSpaceSpan_eq_iSup, LieSubmodule.iSup_toSubmodule]
  exact Submodule.mem_iSup_iff_exists_finset.mpr ⟨s, hs⟩

/-! ### The maximal submodule -/

omit [CharZero K] [IsKilling K L] [FiniteDimensional K L] [H.IsCartanSubalgebra]
  [IsTriangularizable K H L] in
variable (H M) [LieRing.IsNilpotent H] in
/-- **The sum of all the Lie submodules meeting the `lam`-weight space trivially.** For a highest
weight module of weight `lam` this is the greatest proper submodule
(`EpsilonEridani.isGreatest_maximalSubmodule_of_isHighestWeightVector_of_lieSpan_eq_top`), and the
quotient by it is the unique irreducible quotient; for an arbitrary module it is only the sum
named. -/
def maximalSubmodule (lam : Dual K H) : LieSubmodule K L M :=
  sSup {N : LieSubmodule K L M |
    Disjoint (N : Submodule K M)
      (genWeightSpace M ((lam : Dual K H) : H → K) : Submodule K M)}

omit [CharZero K] [IsKilling K L] [FiniteDimensional K L] [H.IsCartanSubalgebra]
  [IsTriangularizable K H L] in
/-- The supremum description underlying `maximalSubmodule`. -/
theorem maximalSubmodule_eq_sSup [LieRing.IsNilpotent H] :
    maximalSubmodule H M lam =
      sSup {N : LieSubmodule K L M |
        Disjoint (N : Submodule K M)
          (genWeightSpace M ((lam : Dual K H) : H → K) : Submodule K M)} := by
  rw [maximalSubmodule]

omit [CharZero K] [IsKilling K L] [FiniteDimensional K L] [H.IsCartanSubalgebra]
  [IsTriangularizable K H L] in
/-- A Lie submodule meeting the `lam`-weight space trivially lies in the maximal submodule. -/
theorem le_maximalSubmodule [LieRing.IsNilpotent H] {N : LieSubmodule K L M}
    (h : Disjoint (N : Submodule K M)
      (genWeightSpace M ((lam : Dual K H) : H → K) : Submodule K M)) :
    N ≤ maximalSubmodule H M lam :=
  le_sSup h

omit [CharZero K] [IsKilling K L] [FiniteDimensional K L] [H.IsCartanSubalgebra]
  [IsTriangularizable K H L] in
/-- The maximal submodule lies in `P` exactly when every submodule meeting the `lam`-weight space
trivially lies in `P`. -/
@[simp]
theorem maximalSubmodule_le_iff [LieRing.IsNilpotent H] {P : LieSubmodule K L M} :
    maximalSubmodule H M lam ≤ P ↔
      ∀ N : LieSubmodule K L M,
        Disjoint (N : Submodule K M)
          (genWeightSpace M ((lam : Dual K H) : H → K) : Submodule K M) → N ≤ P := by
  rw [maximalSubmodule_eq_sSup, sSup_le_iff]
  rfl

/-- In a highest weight module, meeting the top weight space trivially is missing the generator,
the top weight space being the line the generator spans. -/
theorem disjoint_genWeightSpace_iff_notMem_of_isHighestWeightVector_of_lieSpan_eq_top
    (hv : IsHighestWeightVector b lam v) (hgen : LieSubmodule.lieSpan K L {v} = ⊤)
    {N : LieSubmodule K L M} :
    Disjoint (N : Submodule K M)
        (genWeightSpace M ((lam : Dual K H) : H → K) : Submodule K M) ↔ v ∉ N := by
  rw [genWeightSpace_eq_span_singleton_of_isHighestWeightVector_of_lieSpan_eq_top hv hgen,
    Submodule.disjoint_span_singleton]
  exact ⟨fun h hvN => hv.ne_zero (h hvN), fun h hvN => absurd hvN h⟩

omit [CharZero K] [LieAlgebra K L] [IsKilling K L] [FiniteDimensional K L] [LieModule K L M] in
/-- In a highest weight module, a Lie submodule is proper exactly when it misses the generator. -/
theorem notMem_iff_ne_top_of_isHighestWeightVector_of_lieSpan_eq_top
    (hgen : LieSubmodule.lieSpan K L {v} = ⊤) {N : LieSubmodule K L M} : v ∉ N ↔ N ≠ ⊤ := by
  constructor
  · rintro hvN rfl
    exact hvN trivial
  · intro hN hvN
    exact hN (top_le_iff.mp (hgen ▸ LieSubmodule.lieSpan_le.mpr (by simpa using hvN)))

/-- **The maximal submodule of a highest weight module misses the generator**: each of the
submodules summed to build it is supported on the weights other than `lam`, hence so is the sum,
and the generator is not. -/
theorem notMem_maximalSubmodule_of_isHighestWeightVector_of_lieSpan_eq_top
    (hv : IsHighestWeightVector b lam v) (hgen : LieSubmodule.lieSpan K L {v} = ⊤) :
    v ∉ maximalSubmodule H M lam := by
  intro hmem
  -- the sum is supported on the weights other than `lam`
  have hle : (maximalSubmodule H M lam : Submodule K M)
      ≤ (genWeightSpaceSpan H M {chi | chi ≠ ((lam : Dual K H) : H → K)} : Submodule K M) := by
    rw [maximalSubmodule, LieSubmodule.sSup_toSubmodule]
    refine sSup_le ?_
    rintro P ⟨N, hN, rfl⟩
    have hvN := (disjoint_genWeightSpace_iff_notMem_of_isHighestWeightVector_of_lieSpan_eq_top hv
      hgen).mp hN
    exact le_genWeightSpaceSpan_ne_of_notMem_of_isHighestWeightVector_of_lieSpan_eq_top hv hgen hvN
  -- but the generator lies in the top weight space, which meets that span trivially
  have hdisj := disjoint_genWeightSpace_genWeightSpaceSpan_ne H M lam
  have hbot : (genWeightSpace M ((lam : Dual K H) : H → K) : Submodule K M)
      ⊓ (genWeightSpaceSpan H M {chi | chi ≠ ((lam : Dual K H) : H → K)} : Submodule K M) = ⊥ := by
    rw [← LieSubmodule.inf_toSubmodule, disjoint_iff.mp hdisj, LieSubmodule.bot_toSubmodule]
  have hvbot : v ∈ (⊥ : Submodule K M) :=
    hbot ▸ Submodule.mem_inf.mpr ⟨hv.mem_genWeightSpace, hle hmem⟩
  exact hv.ne_zero (by simpa using hvbot)

/-- **The maximal submodule of a highest weight module is its greatest proper submodule.** -/
theorem isGreatest_maximalSubmodule_of_isHighestWeightVector_of_lieSpan_eq_top
    (hv : IsHighestWeightVector b lam v) (hgen : LieSubmodule.lieSpan K L {v} = ⊤) :
    IsGreatest {N : LieSubmodule K L M | N ≠ ⊤} (maximalSubmodule H M lam) := by
  refine ⟨?_, fun N hN => le_maximalSubmodule ?_⟩
  · exact (notMem_iff_ne_top_of_isHighestWeightVector_of_lieSpan_eq_top hgen).mp
      (notMem_maximalSubmodule_of_isHighestWeightVector_of_lieSpan_eq_top hv hgen)
  · exact (disjoint_genWeightSpace_iff_notMem_of_isHighestWeightVector_of_lieSpan_eq_top hv
      hgen).mpr ((notMem_iff_ne_top_of_isHighestWeightVector_of_lieSpan_eq_top hgen).mpr hN)

/-- A Lie submodule of a highest weight module lies in the maximal submodule exactly when it is
proper. -/
theorem le_maximalSubmodule_iff_ne_top_of_isHighestWeightVector_of_lieSpan_eq_top
    (hv : IsHighestWeightVector b lam v) (hgen : LieSubmodule.lieSpan K L {v} = ⊤)
    {N : LieSubmodule K L M} : N ≤ maximalSubmodule H M lam ↔ N ≠ ⊤ := by
  constructor
  · intro hN htop
    subst N
    exact (isGreatest_maximalSubmodule_of_isHighestWeightVector_of_lieSpan_eq_top hv hgen).1
      (top_le_iff.mp hN)
  · intro hN
    exact (isGreatest_maximalSubmodule_of_isHighestWeightVector_of_lieSpan_eq_top hv hgen).2 hN

/-- A Lie submodule of a highest weight module lies in the maximal submodule exactly when it
misses the highest weight generator. -/
theorem le_maximalSubmodule_iff_notMem_of_isHighestWeightVector_of_lieSpan_eq_top
    (hv : IsHighestWeightVector b lam v) (hgen : LieSubmodule.lieSpan K L {v} = ⊤)
    {N : LieSubmodule K L M} : N ≤ maximalSubmodule H M lam ↔ v ∉ N := by
  rw [le_maximalSubmodule_iff_ne_top_of_isHighestWeightVector_of_lieSpan_eq_top hv hgen,
    notMem_iff_ne_top_of_isHighestWeightVector_of_lieSpan_eq_top hgen]

/-- A Lie submodule of a highest weight module lies in the maximal submodule exactly when it meets
the highest weight space trivially. -/
theorem le_maximalSubmodule_iff_disjoint_genWeightSpace_of_isHighestWeightVector_of_lieSpan_eq_top
    (hv : IsHighestWeightVector b lam v) (hgen : LieSubmodule.lieSpan K L {v} = ⊤)
    {N : LieSubmodule K L M} :
    N ≤ maximalSubmodule H M lam ↔
      Disjoint (N : Submodule K M)
        (genWeightSpace M ((lam : Dual K H) : H → K) : Submodule K M) := by
  rw [le_maximalSubmodule_iff_notMem_of_isHighestWeightVector_of_lieSpan_eq_top hv hgen,
    disjoint_genWeightSpace_iff_notMem_of_isHighestWeightVector_of_lieSpan_eq_top hv hgen]

/-- A Lie submodule of a highest weight module strictly containing the maximal submodule is
everything. -/
theorem eq_top_of_maximalSubmodule_lt_of_isHighestWeightVector_of_lieSpan_eq_top
    (hv : IsHighestWeightVector b lam v) (hgen : LieSubmodule.lieSpan K L {v} = ⊤)
    {N : LieSubmodule K L M} (hN : maximalSubmodule H M lam < N) : N = ⊤ := by
  by_contra hcontra
  exact absurd
    ((isGreatest_maximalSubmodule_of_isHighestWeightVector_of_lieSpan_eq_top hv hgen).2 hcontra)
    (not_le_of_gt hN)

/-! ### The irreducible quotient -/

omit [CharZero K] [IsKilling K L] [FiniteDimensional K L] in
/-- The image of the generator generates the quotient. -/
theorem lieSpan_mk_eq_top_of_lieSpan_eq_top (hgen : LieSubmodule.lieSpan K L {v} = ⊤)
    (N : LieSubmodule K L M) :
    LieSubmodule.lieSpan K L {LieSubmodule.Quotient.mk' N v} = ⊤ := by
  have hcomap : LieSubmodule.lieSpan K L {v}
      ≤ (LieSubmodule.lieSpan K L {LieSubmodule.Quotient.mk' N v}).comap
        (LieSubmodule.Quotient.mk' N) :=
    LieSubmodule.lieSpan_le.mpr (Set.singleton_subset_iff.mpr
      (LieSubmodule.mem_comap.mpr (LieSubmodule.subset_lieSpan rfl)))
  refine eq_top_iff.mpr fun q _ => ?_
  obtain ⟨m, rfl⟩ := LieSubmodule.Quotient.surjective_mk' N q
  have hm : m ∈ LieSubmodule.lieSpan K L {v} := by rw [hgen]; trivial
  exact hcomap hm

/-- **The image of the generator in the quotient by the maximal submodule is again a highest weight
vector of weight `lam`.** It is nonzero because the maximal submodule misses the generator, and the
two equations defining a highest weight vector pass to the quotient. -/
theorem isHighestWeightVector_mk_of_isHighestWeightVector_of_lieSpan_eq_top
    (hv : IsHighestWeightVector b lam v) (hgen : LieSubmodule.lieSpan K L {v} = ⊤) :
    IsHighestWeightVector b lam
      (LieSubmodule.Quotient.mk' (maximalSubmodule H M lam) v) := by
  refine isHighestWeightVector_iff.mpr ⟨?_, fun x => ?_, fun x hx => ?_⟩
  · rw [Ne, LieSubmodule.Quotient.mk_eq_zero]
    exact notMem_maximalSubmodule_of_isHighestWeightVector_of_lieSpan_eq_top hv hgen
  · rw [← LieModuleHom.map_lie, hv.lie_eq_smul x, map_smul]
  · rw [← LieModuleHom.map_lie, hv.lie_eq_zero_of_mem_positiveNilradical hx, map_zero]

/-- **The maximal submodule of a highest weight module is a coatom** of its lattice of Lie
submodules: it is proper because it misses the generator, and anything strictly above it is
everything. -/
theorem isCoatom_maximalSubmodule_of_isHighestWeightVector_of_lieSpan_eq_top
    (hv : IsHighestWeightVector b lam v) (hgen : LieSubmodule.lieSpan K L {v} = ⊤) :
    IsCoatom (maximalSubmodule H M lam) :=
  ⟨fun htop => notMem_maximalSubmodule_of_isHighestWeightVector_of_lieSpan_eq_top hv hgen
      (htop ▸ LieSubmodule.mem_top v),
    fun _ hN =>
      eq_top_of_maximalSubmodule_lt_of_isHighestWeightVector_of_lieSpan_eq_top hv hgen hN⟩

/-- **The quotient of a highest weight module by its maximal submodule is irreducible**, the
maximal submodule being a coatom. -/
theorem isIrreducible_quotient_maximalSubmodule_of_isHighestWeightVector_of_lieSpan_eq_top
    (hv : IsHighestWeightVector b lam v) (hgen : LieSubmodule.lieSpan K L {v} = ⊤) :
    LieModule.IsIrreducible K L (M ⧸ maximalSubmodule H M lam) :=
  isIrreducible_quotient_iff_isCoatom.mpr
    (isCoatom_maximalSubmodule_of_isHighestWeightVector_of_lieSpan_eq_top hv hgen)

variable {Q : Type x} [AddCommGroup Q] [Module K Q] [LieRingModule L Q] [LieModule K L Q]

omit [LieModule K L Q] in
/-- The kernel of every surjection from a highest weight module to a nontrivial irreducible module
is its maximal submodule. -/
theorem ker_eq_maximalSubmodule_of_surjective_of_isIrreducible
    (hv : IsHighestWeightVector b lam v) (hgen : LieSubmodule.lieSpan K L {v} = ⊤)
    (f : M →ₗ⁅K,L⁆ Q) (hf : Function.Surjective f) [Nontrivial Q]
    [LieModule.IsIrreducible K L Q] : f.ker = maximalSubmodule H M lam := by
  have hker_ne : f.ker ≠ ⊤ := by
    intro hker
    obtain ⟨q, hq⟩ := exists_ne (0 : Q)
    obtain ⟨m, rfl⟩ := hf q
    exact hq (LieModuleHom.mem_ker.mp (hker ▸ (trivial : m ∈ (⊤ : LieSubmodule K L M))))
  have hker_le : f.ker ≤ maximalSubmodule H M lam :=
    (isGreatest_maximalSubmodule_of_isHighestWeightVector_of_lieSpan_eq_top hv hgen).2 hker_ne
  refine le_antisymm hker_le ?_
  apply (f.le_ker_iff_map (maximalSubmodule H M lam)).mpr
  rcases IsSimpleOrder.eq_bot_or_eq_top (LieSubmodule.map f (maximalSubmodule H M lam)) with
    hmap | hmap
  · exact hmap
  · exfalso
    apply (isGreatest_maximalSubmodule_of_isHighestWeightVector_of_lieSpan_eq_top hv hgen).1
    apply LieSubmodule.toSubmodule_injective
    have hker_le' : LinearMap.ker (f : M →ₗ[K] Q) ≤
        (maximalSubmodule H M lam : Submodule K M) := by
      rw [← LieModuleHom.ker_toSubmodule]
      exact hker_le
    calc
      (maximalSubmodule H M lam : Submodule K M) =
          Submodule.comap (f : M →ₗ[K] Q)
            (Submodule.map (f : M →ₗ[K] Q) (maximalSubmodule H M lam : Submodule K M)) :=
        (Submodule.comap_map_eq_self hker_le').symm
      _ = ⊤ := by rw [← LieSubmodule.toSubmodule_map, hmap]; simp

/-- The canonical irreducible quotient of a highest weight module is equivalent to every
nontrivial irreducible quotient. -/
noncomputable def quotientMaximalSubmoduleEquivOfSurjectiveOfIsIrreducible
    (hv : IsHighestWeightVector b lam v) (hgen : LieSubmodule.lieSpan K L {v} = ⊤)
    (f : M →ₗ⁅K,L⁆ Q) (hf : Function.Surjective f) [Nontrivial Q]
    [LieModule.IsIrreducible K L Q] : (M ⧸ maximalSubmodule H M lam) ≃ₗ⁅K,L⁆ Q := by
  have hker : (maximalSubmodule H M lam : Submodule K M) =
      LinearMap.ker (f : M →ₗ[K] Q) := by
    rw [← LieModuleHom.ker_toSubmodule,
      ker_eq_maximalSubmodule_of_surjective_of_isIrreducible hv hgen f hf]
  let e : (M ⧸ maximalSubmodule H M lam) ≃ₗ[K] Q :=
    (Submodule.quotEquivOfEq _ _ hker).trans
      ((f : M →ₗ[K] Q).quotKerEquivOfSurjective hf)
  exact { e with
    map_lie' := by
      intro y q
      obtain ⟨m, rfl⟩ := LieSubmodule.Quotient.surjective_mk' (maximalSubmodule H M lam) q
      -- A quotient by a Lie submodule is defined as the quotient by its underlying submodule, and
      -- `LieSubmodule.Quotient.mk` abbreviates `Submodule.Quotient.mk`; expose exactly those two
      -- wrappers so the linear quotient equivalence lemmas below apply.
      change e (Submodule.Quotient.mk (⁅y, m⁆)) = ⁅y, e (Submodule.Quotient.mk m)⁆
      dsimp only [e]
      rw [LinearEquiv.trans_apply, Submodule.quotEquivOfEq_mk,
        LinearMap.quotKerEquivOfSurjective_apply_mk, LinearEquiv.trans_apply,
        Submodule.quotEquivOfEq_mk, LinearMap.quotKerEquivOfSurjective_apply_mk]
      exact f.map_lie y m }

omit [LieModule K L Q] in
@[simp]
theorem quotientMaximalSubmoduleEquivOfSurjectiveOfIsIrreducible_apply_mk
    (hv : IsHighestWeightVector b lam v) (hgen : LieSubmodule.lieSpan K L {v} = ⊤)
    (f : M →ₗ⁅K,L⁆ Q) (hf : Function.Surjective f) [Nontrivial Q]
    [LieModule.IsIrreducible K L Q] (m : M) :
    quotientMaximalSubmoduleEquivOfSurjectiveOfIsIrreducible hv hgen f hf
        (LieSubmodule.Quotient.mk (N := maximalSubmodule H M lam) m) = f m := by
  rfl

end EpsilonEridani
