/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.Algebra.Lie.HighestWeight.Character
public import EpsilonEridani.Algebra.Lie.HighestWeight.FiniteDimensional
public import EpsilonEridani.Algebra.Lie.HighestWeight.Trivial

/-!
# Minuscule weights

Let `L` be a finite-dimensional Lie algebra with non-degenerate Killing form over an algebraically
closed field of characteristic zero, let `H` be a Cartan subalgebra and `b` a base of its root
system. A dominant integral weight `mu` is **minuscule** when every weight of the irreducible
module `L(mu)` lies in the Weyl orbit of `mu`; if `L(mu)` is nonzero its weights are then exactly
that orbit. This file defines `EpsilonEridani.IsMinuscule` and proves the dimension count that the orbit
condition buys: a highest weight module whose weights lie in one Weyl orbit has

`dim M = |W · lam|`,

the dimension being the size of a Weyl orbit — a purely combinatorial count, with no Weyl
character formula in sight.

## Why the orbit condition does all the work

Two facts about the formal character of `EpsilonEridani/Algebra/Lie/Weights/FormalCharacter.lean` combine
to give everything. Its coefficient at the highest weight of a highest weight module is `1`
(`EpsilonEridani.formalCharacter_coeff_eq_one_of_isHighestWeightVector_of_lieSpan_eq_top`, the top weight
space being the line spanned by the generator); and it is Weyl-invariant
(`EpsilonEridani.formalCharacter_coeff_weylGroup_smul`, the Weyl invariance of weight multiplicities,
proved from the rank-one theory and not from the character formula). So *every* weight in the orbit
of the highest weight already has multiplicity `1`, whatever the module
(`formalCharacter_coeff_weylGroup_smul_eq_one_of_isHighestWeightVector_of_lieSpan_eq_top`); the
orbit condition is exactly the statement that there are no other weights, and the dimension is
then the number of coefficients, all of them `1`.

Accordingly the substance of the file is stated for an arbitrary finite-dimensional module
generated by a highest weight vector whose weights lie in one orbit
(`EpsilonEridani.finrank_eq_card_orbit_of_isHighestWeightVector_of_lieSpan_eq_top`). That statement is
unconditional: it assumes a highest weight vector and produces the dimension of its orbit.

## The named carrier

`EpsilonEridani.irreducibleQuotient` is built from the Verma module, and `L(mu)` is the zero module
exactly when `M(mu)` is (`EpsilonEridani.subsingleton_irreducibleQuotient_iff`). That `M(mu) ≠ 0` for a
dominant integral `mu` is the freeness half of Poincaré--Birkhoff--Witt, which this file does not
assume. A zero `L(mu)` has no weights at all, so the orbit condition holds vacuously at such a
weight, and what the condition gives at the named carrier unconditionally is the inequality
`EpsilonEridani.IsMinuscule.finrank_irreducibleQuotient_le`, `dim L(mu) ≤ |W · mu|`; it is an equality as
soon as `L(mu)` is nonzero, read off from
`EpsilonEridani.finrank_eq_card_orbit_of_isHighestWeightVector_of_lieSpan_eq_top`.

At the zero weight the nonvanishing is available unconditionally, and there the count is complete:
`EpsilonEridani.isMinuscule_zero` proves `0` minuscule, and `EpsilonEridani.finrank_irreducibleQuotient_zero`,
which needs only triviality, agrees that `dim L(0) = 1`.

## Main definitions

* `EpsilonEridani.IsMinuscule`: `mu` is dominant integral and every weight of `L(mu)` is Weyl-conjugate to
  `mu`, with `EpsilonEridani.isMinuscule_iff` its defining characterization.

## Main results

* `EpsilonEridani.finrank_eq_card_orbit_of_isHighestWeightVector_of_lieSpan_eq_top`: **a highest weight
  module whose weights lie in one Weyl orbit has the dimension of that orbit**, the substance of
  the file. It rests on the fact that the orbit of the highest weight consists of weights, all of
  them simple
  (`formalCharacter_coeff_weylGroup_smul_eq_one_of_isHighestWeightVector_of_lieSpan_eq_top`), and
  hence that the orbit condition makes the weights exactly the orbit
  (`genWeightSpace_ne_bot_iff_mem_orbit_of_isHighestWeightVector_of_lieSpan_eq_top`).
* `EpsilonEridani.IsMinuscule.finrank_irreducibleQuotient_le`: **`dim L(mu) ≤ |W · mu|`**, the part of the
  dimension count at the named carrier that needs no Verma-module nonvanishing.
* `EpsilonEridani.isMinuscule_zero`: **the zero weight is minuscule**, so the notion is not empty. It is
  unconditional, and the point orbit it exhibits matches the one-dimensionality of `L(0)` recorded
  by `EpsilonEridani.finrank_irreducibleQuotient_zero`.

## Implementation notes

The Weyl group acts here as `(LieAlgebra.IsKilling.rootSystem H).weylGroup` acting on
`Module.Dual K H`, which is the action the invariance of weight multiplicities
(`EpsilonEridani.formalCharacter_coeff_weylGroup_smul`) is stated for; the orbit is Mathlib's
`MulAction.orbit`, counted with `Nat.card`.

## References

* N. Bourbaki, *Groupes et algèbres de Lie*, Ch. VIII, §7.3, where minuscule weights are
  introduced.
* J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*, GTM 9, §13 and §21.2.
-/

public section

namespace EpsilonEridani

open LieAlgebra LieModule Module

universe u v w

section General

variable {K : Type u} {L : Type v} [Field K] [CharZero K] [IsAlgClosed K]
  [LieRing L] [LieAlgebra K L] [IsKilling K L] [FiniteDimensional K L]
  {H : LieSubalgebra K L} [H.IsCartanSubalgebra]
  {M : Type w} [AddCommGroup M] [Module K M] [LieRingModule L M] [LieModule K L M]
  [FiniteDimensional K M]
  {b : (IsKilling.rootSystem H).Base} {lam : Dual K H} {v : M}

/-- **The weights of a highest weight module whose weights lie in one Weyl orbit are exactly that
orbit**: a linear form has a nonzero weight space in such a module precisely when it lies in the
Weyl orbit of the highest weight. -/
theorem genWeightSpace_ne_bot_iff_mem_orbit_of_isHighestWeightVector_of_lieSpan_eq_top
    (hv : IsHighestWeightVector b lam v) (hgen : LieSubmodule.lieSpan K L {v} = ⊤)
    (horb : ∀ chi : Dual K H, genWeightSpace M (chi : H → K) ≠ ⊥ →
      ∃ w : (IsKilling.rootSystem H).weylGroup, w • lam = chi)
    (chi : Dual K H) :
    genWeightSpace M (chi : H → K) ≠ ⊥ ↔
      chi ∈ MulAction.orbit (IsKilling.rootSystem H).weylGroup lam := by
  refine ⟨fun h ↦ MulAction.mem_orbit_iff.mpr (horb chi h), ?_⟩
  rintro ⟨w, rfl⟩
  exact genWeightSpace_weylGroup_smul_ne_bot_of_isHighestWeightVector_of_lieSpan_eq_top hv hgen w

/-- **A highest weight module whose weights lie in a single Weyl orbit has the dimension of that
orbit**: a finite-dimensional module generated by a highest weight vector of weight `lam`, all of
whose weights are Weyl-conjugate to `lam`, has dimension the cardinality of the Weyl orbit of
`lam`. This is the dimension count that minusculeness buys, stated before `EpsilonEridani.IsMinuscule`
names the condition. -/
theorem finrank_eq_card_orbit_of_isHighestWeightVector_of_lieSpan_eq_top
    (hv : IsHighestWeightVector b lam v) (hgen : LieSubmodule.lieSpan K L {v} = ⊤)
    (horb : ∀ chi : Dual K H, genWeightSpace M (chi : H → K) ≠ ⊥ →
      ∃ w : (IsKilling.rootSystem H).weylGroup, w • lam = chi) :
    finrank K M = Nat.card (MulAction.orbit (IsKilling.rootSystem H).weylGroup lam) := by
  classical
  have hone : ∀ chi ∈ (formalCharacter K H M).coeff.support,
      (formalCharacter K H M).coeff chi = 1 := by
    intro chi hchi
    rw [Finsupp.mem_support_iff] at hchi
    obtain ⟨w, rfl⟩ := horb chi ((not_congr formalCharacter_coeff_eq_zero_iff).mp hchi)
    exact formalCharacter_coeff_weylGroup_smul_eq_one_of_isHighestWeightVector_of_lieSpan_eq_top
      hv hgen w
  have hsupp : (((formalCharacter K H M).coeff.support : Finset (Dual K H)) : Set (Dual K H)) =
      MulAction.orbit (IsKilling.rootSystem H).weylGroup lam := by
    ext chi
    rw [Finset.mem_coe, Finsupp.mem_support_iff,
      ← genWeightSpace_ne_bot_iff_mem_orbit_of_isHighestWeightVector_of_lieSpan_eq_top
        hv hgen horb chi]
    exact not_congr formalCharacter_coeff_eq_zero_iff
  have hsum := sum_formalCharacter_coeff_eq_finrank K H M
  rw [Finsupp.sum, Finset.sum_congr rfl hone, Finset.sum_const, nsmul_eq_mul, mul_one] at hsum
  have hcard : Nat.card (MulAction.orbit (IsKilling.rootSystem H).weylGroup lam) =
      (formalCharacter K H M).coeff.support.card := by
    rw [← hsupp, Nat.card_coe_set_eq, Set.ncard_coe_finset]
  rw [hcard]
  exact_mod_cast hsum.symm

attribute [local instance] Classical.propDecidable

/-- **The formal-character coefficient of a highest-weight module whose weights lie in one Weyl
orbit is the indicator of that orbit**: every Weyl translate of its highest weight occurs with
multiplicity one, and the orbit-support hypothesis excludes every other weight. -/
theorem formalCharacter_coeff_eq_ite_of_isHighestWeightVector_of_lieSpan_eq_top
    (hv : IsHighestWeightVector b lam v) (hgen : LieSubmodule.lieSpan K L {v} = ⊤)
    (horb : ∀ chi : Dual K H, genWeightSpace M (chi : H → K) ≠ ⊥ →
      ∃ w : (IsKilling.rootSystem H).weylGroup, w • lam = chi)
    (chi : Dual K H) :
    (formalCharacter K H M).coeff chi =
      if chi ∈ MulAction.orbit (IsKilling.rootSystem H).weylGroup lam then 1 else 0 := by
  classical
  have hsupp := genWeightSpace_ne_bot_iff_mem_orbit_of_isHighestWeightVector_of_lieSpan_eq_top
    hv hgen horb chi
  by_cases horb' : chi ∈ MulAction.orbit (IsKilling.rootSystem H).weylGroup lam
  · obtain ⟨w, rfl⟩ := horb'
    have hw : w • lam ∈ MulAction.orbit (IsKilling.rootSystem H).weylGroup lam :=
      ⟨w, rfl⟩
    simpa [hw] using
      formalCharacter_coeff_weylGroup_smul_eq_one_of_isHighestWeightVector_of_lieSpan_eq_top
        hv hgen w
  · have hbot : LieModule.genWeightSpace M (chi : H → K) = ⊥ := by
      by_contra hne
      exact horb' (hsupp.mp hne)
    simp [formalCharacter_coeff_eq_zero_iff.mpr hbot, horb']

end General

section Minuscule

variable {K : Type u} {L : Type v} [Field K] [CharZero K] [IsAlgClosed K]
  [LieRing L] [LieAlgebra K L] [IsKilling K L] [FiniteDimensional K L]
  {H : LieSubalgebra K L} [H.IsCartanSubalgebra]

variable (b : (IsKilling.rootSystem H).Base) (mu : Dual K H)

/-- **A minuscule weight**: a dominant integral weight `mu` every companion weight of which in
`L(mu)` is Weyl-conjugate to it, so that the weights of a nonzero `L(mu)` are exactly one Weyl
orbit.

The condition is on the weights of `EpsilonEridani.irreducibleQuotient`, so it holds vacuously at a
weight where that module vanishes; see the module docstring. -/
def IsMinuscule : Prop :=
  IsDominantIntegral b mu ∧
    ∀ nu : Dual K H, genWeightSpace (irreducibleQuotient b mu) (nu : H → K) ≠ ⊥ →
      ∃ w : (IsKilling.rootSystem H).weylGroup, w • mu = nu

variable {b mu}

/-- The defining condition on a minuscule weight, matching `EpsilonEridani.isDominantIntegral_iff` beside
`EpsilonEridani.IsDominantIntegral`. -/
theorem isMinuscule_iff :
    IsMinuscule b mu ↔ IsDominantIntegral b mu ∧
      ∀ nu : Dual K H, genWeightSpace (irreducibleQuotient b mu) (nu : H → K) ≠ ⊥ →
        ∃ w : (IsKilling.rootSystem H).weylGroup, w • mu = nu :=
  Iff.rfl

/-- A minuscule weight is dominant integral. -/
theorem IsMinuscule.isDominantIntegral (h : IsMinuscule b mu) : IsDominantIntegral b mu :=
  h.1

/-- Every weight of a minuscule `L(mu)` is Weyl-conjugate to `mu`. -/
theorem IsMinuscule.exists_weylGroup_smul_eq (h : IsMinuscule b mu) {nu : Dual K H}
    (hnu : genWeightSpace (irreducibleQuotient b mu) (nu : H → K) ≠ ⊥) :
    ∃ w : (IsKilling.rootSystem H).weylGroup, w • mu = nu :=
  h.2 nu hnu

attribute [local instance] Classical.propDecidable

/-- **The character of a nonzero minuscule module is the orbit indicator**: every Weyl translate
of its highest weight occurs with multiplicity one, and minuscule-ness excludes every other
weight. -/
theorem formalCharacter_coeff_irreducibleQuotient_eq_ite_of_isMinuscule_of_vermaGenerator_ne_zero
    (h : IsMinuscule b mu) (hM : vermaGenerator b mu ≠ 0) (chi : Dual K H) :
    letI := finiteDimensional_irreducibleQuotient_of_isDominantIntegral h.isDominantIntegral
    (formalCharacter K H (irreducibleQuotient b mu)).coeff chi =
      if chi ∈ MulAction.orbit (IsKilling.rootSystem H).weylGroup mu then 1 else 0 := by
  let _ := finiteDimensional_irreducibleQuotient_of_isDominantIntegral h.isDominantIntegral
  let hv := isHighestWeightVector_irreducibleQuotientGenerator b mu hM
  let hgen := lieSpan_irreducibleQuotientGenerator_eq_top b mu
  exact formalCharacter_coeff_eq_ite_of_isHighestWeightVector_of_lieSpan_eq_top hv hgen h.2 chi

/-- **The dimension of a minuscule module is at most the size of the Weyl orbit of its highest
weight**, `dim L(mu) ≤ |W · mu|`, with equality as soon as `L(mu)` is nonzero; see the module
docstring. -/
theorem IsMinuscule.finrank_irreducibleQuotient_le (h : IsMinuscule b mu) :
    finrank K (irreducibleQuotient b mu) ≤
      Nat.card (MulAction.orbit (IsKilling.rootSystem H).weylGroup mu) := by
  have _ := finiteDimensional_irreducibleQuotient_of_isDominantIntegral h.isDominantIntegral
  by_cases h0 : vermaGenerator b mu = 0
  · have _ : Subsingleton (irreducibleQuotient b mu) :=
      (subsingleton_irreducibleQuotient_iff b mu).mpr h0
    rw [finrank_zero_of_subsingleton]
    exact Nat.zero_le _
  · exact le_of_eq (finrank_eq_card_orbit_of_isHighestWeightVector_of_lieSpan_eq_top
      (isHighestWeightVector_irreducibleQuotientGenerator b mu h0)
      (lieSpan_irreducibleQuotientGenerator_eq_top b mu) h.2)

end Minuscule

section Zero

variable {K : Type u} {L : Type v} [Field K] [CharZero K] [IsAlgClosed K]
  [LieRing L] [LieAlgebra K L] [IsKilling K L] [FiniteDimensional K L]
  {H : LieSubalgebra K L} [H.IsCartanSubalgebra]

variable (b : (IsKilling.rootSystem H).Base)

/-- **The zero weight is minuscule.** Its module `L(0)` is the trivial one-dimensional module, so
its only weight is `0`, which is its own Weyl orbit. -/
@[simp]
theorem isMinuscule_zero : IsMinuscule b (0 : Dual K H) := by
  have h : vermaGenerator b (0 : Dual K H) ≠ 0 :=
    (isHighestWeightVector_vermaGenerator_zero b).ne_zero
  have hw := isHighestWeightVector_irreducibleQuotientGenerator b (0 : Dual K H) h
  have _ := finiteDimensional_irreducibleQuotient_of_isDominantIntegral
    (isDominantIntegral_zero (b := b))
  have _ : LieModule.IsTrivial L (irreducibleQuotient b (0 : Dual K H)) :=
    isTrivial_of_isHighestWeightVector_weight_zero_of_lieSpan_eq_top hw
      (lieSpan_irreducibleQuotientGenerator_eq_top b 0)
  have _ : LieModule.IsTrivial H (irreducibleQuotient b (0 : Dual K H)) :=
    ⟨fun x m ↦ LieModule.IsTrivial.trivial (x : L) m⟩
  refine ⟨isDominantIntegral_zero, fun nu hnu ↦ ⟨1, ?_⟩⟩
  rw [one_smul, eq_comm]
  exact LinearMap.ext fun x ↦ congrFun (eq_zero_of_genWeightSpace_ne_bot_of_isTrivial hnu) x

end Zero

end EpsilonEridani
