/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.Algebra.Lie.HighestWeight.Casimir
public import EpsilonEridani.Algebra.Lie.Weights.Positivity
import EpsilonEridani.Algebra.Lie.HighestWeight.Module
import EpsilonEridani.Algebra.Lie.HighestWeight.Weight.Support

/-!
# Separation by the Casimir scalar

Let `L` be a finite-dimensional Lie algebra with non-degenerate Killing form over a field of
characteristic zero, let `H` be a splitting Cartan subalgebra and let `base` be a base of its root
system. `EpsilonEridani/Algebra/Lie/HighestWeight/Casimir.lean` computes the scalar by which the Casimir
element `Ω` acts on a highest weight module of weight `lam`, namely

`c(lam) = ⟨lam + ρ, lam + ρ⟩ - ⟨ρ, ρ⟩`.

This file proves the two nonvanishing statements that make that scalar separate things. The second
of them additionally assumes that `K` is algebraically closed, because it compares the weights of a
module with each other.

The first is **separation from the trivial module**: `c(lam)` is nonzero as soon as `lam` is a
nonzero dominant integral weight (`EpsilonEridani.casimirScalar_ne_zero`), while `Ω` acts by zero on a
module with trivial action
(`EpsilonEridani.representation_casimirElement_apply_eq_zero_of_isTrivial`). Applying this to every
nontrivial finite-dimensional irreducible additionally requires the theorem that an irreducible
highest-weight module of highest weight zero is trivial; that theorem is not proved here.

The second is **separation of the weights of one module**, and here `K` is algebraically closed: on
a finite-dimensional module generated by a highest weight vector of weight `lam`, the scalars
`c(mu)` attached to the weights `mu` of the module are all different from `c(lam)` except at
`mu = lam` itself
(`EpsilonEridani.casimirScalar_ne_casimirScalar_of_genWeightSpace_ne_bot_of_isHighestWeightVector`). This
is what turns `EpsilonEridani.freudenthal_multiplicity_formula` into a downward computation of the weight
multiplicities: the coefficient that recursion divides by is
`⟨lam + ρ, lam + ρ⟩ - ⟨mu + ρ, mu + ρ⟩ = c(lam) - c(mu)`.

## The argument

Expanding the square, `c(lam) = ⟨lam, lam⟩ + ∑_{α > 0} ⟨lam, α⟩`
(`EpsilonEridani.casimirScalar_eq_add_sum`), and the summands are read off by the
positivity of `EpsilonEridani/Algebra/Lie/Weights/Positivity.lean`. A dominant integral weight is integral
(`EpsilonEridani.IsDominantIntegral.isIntegralWeight`, the passage from the simple coroots to all of them
going through `EpsilonEridani.IsDominantIntegral.exists_nat_apply_coroot` and, for a negative root, the
sign change `LieAlgebra.IsKilling.coroot_neg`), so `⟨lam, lam⟩` is a positive rational when
`lam ≠ 0`. And `⟨lam, α⟩ = ⟨α, α⟩ lam(α^∨) / 2` is a nonnegative rational for a positive root `α`,
the root length being positive and `lam(α^∨)` a natural number by dominance. A positive rational
plus nonnegative rationals is nonzero, and a nonzero rational stays nonzero in a field of
characteristic zero. That is the first statement.

Dominance is essential, not decoration: for a general integral `lam` the two summands can have
opposite signs and `c(lam)` can vanish. For example, `lam = -2ρ` is integral and satisfies
`lam + ρ = -ρ`, hence `c(lam) = 0`.

The same expansion turns the difference into
`c(lam) - c(mu) = (⟨lam, lam⟩ - ⟨mu, mu⟩) + ⟨2ρ, lam - mu⟩`. The weights of a highest weight
module lie in `lam - Q⁺`, so `lam - mu` is a nonzero member of the positive root cone when
`mu ≠ lam`, and the second summand is a positive rational: `2ρ` pairs with a simple root `αᵢ` in
`⟨αᵢ, αᵢ⟩`, a positive rational, because `2ρ(αᵢ^∨) = 2`. The first summand is where dominance of
`mu` would be needed and is not available, so `mu` is replaced by a dominant conjugate: the weights
of a finite-dimensional module are Weyl stable and integral, so `mu` has a Weyl translate
`nu = w · mu` that is again a weight of the module and is dominant integral, by
`EpsilonEridani.exists_weylGroup_smul_isDominantIntegral_of_genWeightSpace_ne_bot` of
`EpsilonEridani/Algebra/Lie/HighestWeight/Weight/Support.lean`. The form is Weyl
invariant (`RootPairing.InvariantForm.apply_weylGroup_smul`), so
`⟨mu, mu⟩ = ⟨nu, nu⟩` and the first summand is
`⟨lam + nu, lam - nu⟩`, which is nonnegative: `lam + nu` is dominant integral and `lam - nu` lies
in the cone. A nonnegative rational plus a positive one is nonzero.

## Main results

* `EpsilonEridani.casimirScalar_ne_zero` and `EpsilonEridani.casimirScalar_eq_zero_iff`: the Casimir scalar of a
  dominant integral weight vanishes exactly at the zero weight.
* `EpsilonEridani.casimir_apply_ne_zero_of_isHighestWeightVector_of_lieSpan_eq_top`: on a highest weight
  module with nonzero dominant integral highest weight, the Casimir element kills no nonzero
  vector.
* `EpsilonEridani.representation_casimirElement_apply_eq_zero_of_isTrivial`: on a module with trivial
  action the Casimir element acts by zero.
* `EpsilonEridani.IsDominantIntegral.exists_nonneg_rat_invForm_of_mem_posRootCone`: a dominant integral
  weight pairs to a nonnegative rational with every member of the positive root cone.
* `casimirScalar_ne_casimirScalar_of_isDominantIntegral_of_sub_mem_posRootCone_of_ne` (in the
  `EpsilonEridani.IsDominantIntegral` namespace): **the Casimir scalar separates a dominant integral
  weight from the dominant integral weights strictly below it.**
* `EpsilonEridani.casimirScalar_ne_casimirScalar_of_genWeightSpace_ne_bot_of_isHighestWeightVector`:
  **over an algebraically closed field, the Casimir scalar of a weight of a finite-dimensional
  highest weight module differs from that of the highest weight, except at the highest weight
  itself.**

## References

* J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*, GTM 9, §6.3, where
  the separation is the engine of Weyl's theorem, and §13.4 and §22.3, where the comparison of
  `⟨lam + ρ, lam + ρ⟩` with `⟨mu + ρ, mu + ρ⟩` is the input of Freudenthal's recursion.

This is the "the eigenvalue separates the trivial module from nontrivial irreducibles" step of
Layer 5 of `EpsilonEridaniRoadmap/RepresentationTheory/LieHighestWeight/README.md`, together with the
nonvanishing that Layer 7's "Freudenthal's multiplicity formula" needs to be read as a recursion.
-/

public section

namespace EpsilonEridani

open Finset LieAlgebra LieAlgebra.IsKilling LieModule Module

universe u v w

variable {K : Type u} {L : Type v} [Field K] [CharZero K] [LieRing L] [LieAlgebra K L]
  [IsKilling K L] [FiniteDimensional K L]
  {H : LieSubalgebra K L} [H.IsCartanSubalgebra] [IsTriangularizable K H L]
  {M : Type w} [AddCommGroup M] [Module K M] [LieRingModule L M] [LieModule K L M]
  {base : (IsKilling.rootSystem H).Base} {lam : Module.Dual K H}

/-! ### The Casimir scalar of a dominant integral weight -/

/-- **A dominant integral weight pairs nonnegatively with a positive root.** The normalisation
`⟨lam, α⟩ = ⟨α, α⟩ lam(α^∨) / 2` has a positive root length and, by dominance, a natural value
`lam(α^∨)`. -/
theorem IsDominantIntegral.exists_nonneg_rat_invForm_root (hlam : IsDominantIntegral base lam)
    {i : H.root} (hi : i ∈ posRoots (IsKilling.rootSystem H) base) :
    ∃ q : ℚ, 0 ≤ q ∧ invForm lam ((IsKilling.rootSystem H).root i) = (q : K) := by
  obtain ⟨n, hn⟩ := hlam.exists_nat_apply_coroot hi
  obtain ⟨r, hr0, hr⟩ := exists_pos_rat_invForm_root_self (H.isNonZero_coe_root i)
  have h2 := invForm_coroot lam i
  simp only [IsKilling.rootSystem_root_apply] at h2 hr ⊢
  rw [hn, hr] at h2
  refine ⟨n * r / 2, by positivity, ?_⟩
  push_cast
  linear_combination -h2 / 2

/-- **The Casimir scalar of a nonzero dominant integral weight is nonzero.** Expanded, the scalar
is `⟨lam, lam⟩ + ∑_{α > 0} ⟨lam, α⟩`: a positive rational plus a sum of nonnegative rationals.

This distinguishes such a highest-weight module from a trivial module, whose Casimir scalar is
`0`. -/
theorem casimirScalar_ne_zero (hlam : IsDominantIntegral base lam) (h0 : lam ≠ 0) :
    casimirScalar base lam ≠ 0 := by
  classical
  rw [casimirScalar_eq_add_sum]
  obtain ⟨q, hq0, hq⟩ := hlam.isIntegralWeight.exists_pos_rat_invForm_self h0
  choose g hg using fun i : H.root ↦
    hlam.isIntegralWeight.exists_rat_invForm_root (i : Weight K H L)
  have hgnn : ∀ i ∈ posRootsFinset (IsKilling.rootSystem H) base, 0 ≤ g i := by
    intro i hi
    obtain ⟨s, hs0, hs⟩ :=
      hlam.exists_nonneg_rat_invForm_root
        ((mem_posRootsFinset (IsKilling.rootSystem H) base i).mp hi)
    have : (g i : K) = (s : K) := by
      rw [← hg i, ← hs, IsKilling.rootSystem_root_apply]
    rwa [Rat.cast_injective this]
  have hsum : ∑ i ∈ posRootsFinset (IsKilling.rootSystem H) base,
      invForm lam ((IsKilling.rootSystem H).root i) =
      ((∑ i ∈ posRootsFinset (IsKilling.rootSystem H) base, g i : ℚ) : K) := by
    push_cast
    exact Finset.sum_congr rfl fun i _ ↦ by
      rw [IsKilling.rootSystem_root_apply, hg i]
  rw [hq, hsum, ← Rat.cast_add]
  have : (0 : ℚ) < q + ∑ i ∈ posRootsFinset (IsKilling.rootSystem H) base, g i := by
    have := Finset.sum_nonneg hgnn
    linarith
  exact_mod_cast this.ne'

/-- **The Casimir scalar of a dominant integral weight vanishes exactly at the zero weight.** The
converse direction is the computation `⟨ρ, ρ⟩ - ⟨ρ, ρ⟩ = 0`. -/
@[simp]
theorem casimirScalar_eq_zero_iff (hlam : IsDominantIntegral base lam) :
    casimirScalar base lam = 0 ↔ lam = 0 := by
  refine ⟨fun h ↦ by_contra fun h0 ↦ casimirScalar_ne_zero hlam h0 h, ?_⟩
  rintro rfl
  exact casimirScalar_zero

/-! ### Separation on modules -/

/-- **The Casimir element kills no nonzero vector of a highest weight module whose highest weight
is a nonzero dominant integral weight.** It acts by the scalar of
`EpsilonEridani.casimir_smul_of_isHighestWeightVector_of_lieSpan_eq_top`, which
`EpsilonEridani.casimirScalar_ne_zero` shows to be nonzero. -/
theorem casimir_apply_ne_zero_of_isHighestWeightVector_of_lieSpan_eq_top {v : M}
    (hv : IsHighestWeightVector base lam v) (hgen : LieSubmodule.lieSpan K L {v} = ⊤)
    (hlam : IsDominantIntegral base lam) (h0 : lam ≠ 0) {m : M} (hm : m ≠ 0) :
    UniversalEnvelopingAlgebra.representation K L M (casimirElement K L) m ≠ 0 := by
  rw [casimir_smul_of_isHighestWeightVector_of_lieSpan_eq_top hv hgen m]
  exact smul_ne_zero (casimirScalar_ne_zero hlam h0) hm

/-! ### Pairings with the positive root cone -/

/-- **A dominant integral weight pairs nonnegatively with the positive root cone.** A member of
the cone is a natural combination of the simple roots, and a dominant integral weight pairs
nonnegatively with each of those by
`EpsilonEridani.IsDominantIntegral.exists_nonneg_rat_invForm_root`. -/
theorem IsDominantIntegral.exists_nonneg_rat_invForm_of_mem_posRootCone {chi u : Module.Dual K H}
    (hchi : IsDominantIntegral base chi)
    (hu : u ∈ posRootCone (IsKilling.rootSystem H) base) :
    ∃ q : ℚ, 0 ≤ q ∧ invForm chi u = (q : K) := by
  classical
  obtain ⟨f, rfl⟩ := (mem_posRootCone (IsKilling.rootSystem H) base).mp hu
  choose g hg using fun i : H.root ↦
    hchi.isIntegralWeight.exists_rat_invForm_root (i : Weight K H L)
  have hg0 : ∀ i ∈ base.support, 0 ≤ g i := by
    intro i hi
    obtain ⟨s, hs0, hs⟩ := hchi.exists_nonneg_rat_invForm_root
      (support_subset_posRoots (IsKilling.rootSystem H) base hi)
    have hgs : (g i : K) = (s : K) := by
      rw [← hg i, ← hs, IsKilling.rootSystem_root_apply]
    rwa [Rat.cast_injective hgs]
  refine ⟨∑ i ∈ base.support, (f i : ℚ) * g i,
    Finset.sum_nonneg fun i hi ↦ mul_nonneg (by positivity) (hg0 i hi), ?_⟩
  push_cast
  rw [map_sum]
  exact Finset.sum_congr rfl fun i _ ↦ by
    rw [map_nsmul, nsmul_eq_mul, IsKilling.rootSystem_root_apply, hg i]

/-- **The sum of the positive roots pairs with a simple root in that root's squared length**:
`⟨2ρ, αᵢ⟩ = ⟨αᵢ, αᵢ⟩`, because `2ρ` takes the value `2` on every simple coroot. -/
private theorem invForm_twoWeylVector_root {i : H.root} (hi : i ∈ base.support) :
    invForm (twoWeylVector (IsKilling.rootSystem H) base) ((IsKilling.rootSystem H).root i) =
      invForm ((IsKilling.rootSystem H).root i) ((IsKilling.rootSystem H).root i) := by
  have hcoroot : (twoWeylVector (IsKilling.rootSystem H) base)
      ((IsKilling.rootSystem H).coroot i) = 2 := by
    have h := coroot'_twoWeylVector (IsKilling.rootSystem H) base hi
    rwa [LinearMap.flip_apply, IsKilling.rootSystem_toLinearMap_apply] at h
  have h := invForm_coroot (twoWeylVector (IsKilling.rootSystem H) base) i
  rw [hcoroot] at h
  linear_combination -h / 2

/-- **The sum of the positive roots pairs positively with a nonzero member of the positive root
cone.** Each simple root contributes its own squared length, a positive rational by
`EpsilonEridani.exists_pos_rat_invForm_root_self`, and a nonzero member of the cone involves at least one
simple root. -/
private theorem exists_pos_rat_invForm_twoWeylVector {u : Module.Dual K H}
    (hu : u ∈ posRootCone (IsKilling.rootSystem H) base) (hu0 : u ≠ 0) :
    ∃ q : ℚ, 0 < q ∧
      invForm (twoWeylVector (IsKilling.rootSystem H) base) u = (q : K) := by
  classical
  obtain ⟨f, rfl⟩ := (mem_posRootCone (IsKilling.rootSystem H) base).mp hu
  choose g hg0 hg using fun i : H.root ↦
    exists_pos_rat_invForm_root_self (H.isNonZero_coe_root i)
  -- at least one simple root occurs, or the member would be zero
  have hex : ∃ i ∈ base.support, f i ≠ 0 := by
    by_contra hcon
    push Not at hcon
    exact hu0 (Finset.sum_eq_zero fun i hi ↦ by rw [hcon i hi, zero_smul])
  obtain ⟨i₀, hi₀, hf₀⟩ := hex
  have hf₀' : (0 : ℚ) < (f i₀ : ℚ) := by exact_mod_cast Nat.pos_of_ne_zero hf₀
  refine ⟨∑ i ∈ base.support, (f i : ℚ) * g i, Finset.sum_pos'
    (fun i _ ↦ mul_nonneg (by positivity) (hg0 i).le) ⟨i₀, hi₀, mul_pos hf₀' (hg0 i₀)⟩, ?_⟩
  push_cast
  rw [map_sum]
  exact Finset.sum_congr rfl fun i hi ↦ by
    rw [map_nsmul, nsmul_eq_mul, invForm_twoWeylVector_root hi,
      IsKilling.rootSystem_root_apply, hg i]

/-! ### Separating dominant integral weights -/

namespace IsDominantIntegral

/-- **The Casimir scalar separates a dominant integral weight from the dominant integral weights
below it**: if `lam` and `nu` are dominant integral, `lam - nu` lies in the positive root cone and
`nu ≠ lam`, then `c(lam) ≠ c(nu)`.

In the expansion `c(lam) - c(nu) = ⟨lam + nu, lam - nu⟩ + ⟨2ρ, lam - nu⟩` the first summand is a
nonnegative rational, `lam + nu` being dominant integral, and the second a positive one, `lam - nu`
being a nonzero member of the cone. -/
theorem casimirScalar_ne_casimirScalar_of_isDominantIntegral_of_sub_mem_posRootCone_of_ne
    (hlam : IsDominantIntegral base lam) {nu : Module.Dual K H}
    (hnu : IsDominantIntegral base nu)
    (hle : lam - nu ∈ posRootCone (IsKilling.rootSystem H) base) (hne : nu ≠ lam) :
    casimirScalar base lam ≠ casimirScalar base nu := by
  obtain ⟨q₁, hq₁0, hq₁⟩ := (hlam.add hnu).exists_nonneg_rat_invForm_of_mem_posRootCone hle
  obtain ⟨q₂, hq₂0, hq₂⟩ := exists_pos_rat_invForm_twoWeylVector hle (sub_ne_zero_of_ne hne.symm)
  have hdiff : casimirScalar base lam - casimirScalar base nu = ((q₁ + q₂ : ℚ) : K) := by
    rw [casimirScalar_sub_casimirScalar, invForm_self_sub_invForm_self, hq₁, hq₂, Rat.cast_add]
  have hne0 : ((q₁ + q₂ : ℚ) : K) ≠ 0 := by
    have hpos : (0 : ℚ) < q₁ + q₂ := by linarith
    exact_mod_cast hpos.ne'
  exact fun hcon ↦ hne0 (by rw [← hdiff, hcon, sub_self])

end IsDominantIntegral

/-! ### Separating the weights of a highest weight module -/

section HighestWeightModule

variable [IsAlgClosed K] [FiniteDimensional K M] {v : M}

/-- **The Casimir scalar separates the highest weight of a highest weight module from its other
weights**: over an algebraically closed field, on a finite-dimensional module generated by a
highest weight vector of weight `lam`, the scalar `⟨mu + ρ, mu + ρ⟩` attached to a weight
`mu ≠ lam` differs from `⟨lam + ρ, lam + ρ⟩`.

This is what turns `EpsilonEridani.freudenthal_multiplicity_formula` into a downward computation of the
weight multiplicities of `M`: the coefficient the recursion divides by,
`⟨lam + ρ, lam + ρ⟩ - ⟨mu + ρ, mu + ρ⟩`, is `casimirScalar base lam - casimirScalar base mu`, and
is nonzero at every weight other than `lam` itself.

Expanded, the difference is `(⟨lam, lam⟩ - ⟨mu, mu⟩) + ⟨2ρ, lam - mu⟩`. The second summand is
positive because `lam - mu` is a nonzero member of the positive root cone. For the first, replace
`mu` by the dominant integral conjugate `nu = w · mu` of
`EpsilonEridani.exists_weylGroup_smul_isDominantIntegral_of_genWeightSpace_ne_bot`, which has the same
length by `RootPairing.InvariantForm.apply_weylGroup_smul`; then
`⟨lam, lam⟩ - ⟨nu, nu⟩ = ⟨lam + nu, lam - nu⟩` is
nonnegative, `lam + nu` being dominant integral and `lam - nu` a member of the cone. -/
theorem casimirScalar_ne_casimirScalar_of_genWeightSpace_ne_bot_of_isHighestWeightVector
    (hv : IsHighestWeightVector base lam v) (hgen : LieSubmodule.lieSpan K L {v} = ⊤)
    {mu : Module.Dual K H} (hmu : genWeightSpace M (mu : H → K) ≠ ⊥) (hne : mu ≠ lam) :
    casimirScalar base lam ≠ casimirScalar base mu := by
  obtain ⟨w, hwS, hwdom⟩ :=
    exists_weylGroup_smul_isDominantIntegral_of_genWeightSpace_ne_bot hv hgen hmu
  set nu : Module.Dual K H := w • mu
  obtain ⟨q₁, hq₁0, hq₁⟩ :=
    (hv.isDominantIntegral.add hwdom).exists_nonneg_rat_invForm_of_mem_posRootCone
      (sub_mem_posRootCone_of_genWeightSpace_ne_bot_of_isHighestWeightVector_of_lieSpan_eq_top
        hv hgen hwS)
  obtain ⟨q₂, hq₂0, hq₂⟩ := exists_pos_rat_invForm_twoWeylVector
    (sub_mem_posRootCone_of_genWeightSpace_ne_bot_of_isHighestWeightVector_of_lieSpan_eq_top
      hv hgen hmu)
    (sub_ne_zero_of_ne (Ne.symm hne))
  -- `mu` and its dominant conjugate `nu` have the same length
  have hlen : invForm mu mu = invForm nu nu := by
    simpa only [rootInvariantForm_form] using
      (RootPairing.InvariantForm.apply_weylGroup_smul (IsKilling.rootSystem H)
        (B := rootInvariantForm (H := H)) w mu mu).symm
  have hdiff : casimirScalar base lam - casimirScalar base mu = ((q₁ + q₂ : ℚ) : K) := by
    rw [casimirScalar_sub_casimirScalar, hlen, invForm_self_sub_invForm_self, hq₁, hq₂,
      Rat.cast_add]
  have hne0 : ((q₁ + q₂ : ℚ) : K) ≠ 0 := by
    have hpos : (0 : ℚ) < q₁ + q₂ := by linarith
    exact_mod_cast hpos.ne'
  exact fun hcon ↦ hne0 (by rw [← hdiff, hcon, sub_self])

end HighestWeightModule

end EpsilonEridani
