/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.Algebra.Lie.HighestWeight.Basic
import Mathlib.Algebra.Lie.Basis.Base
import EpsilonEridani.Algebra.Lie.HighestWeight.Integrability
import EpsilonEridani.Algebra.Lie.Submodule.Atom

/-!
# Highest weight zero and the trivial module

Let `L` be a finite-dimensional Lie algebra with non-degenerate Killing form over a field of
characteristic zero. This file proves that a finite-dimensional highest weight module generated by
a vector of weight zero is trivial.

For each positive root, its `sl₂` triple makes a highest weight vector of weight zero a primitive
vector of `sl₂`-weight zero. The finite-dimensional `sl₂` string therefore stops immediately, so
the corresponding negative root space annihilates the vector. The Cartan and the positive
nilradical already annihilate it by the definition of highest weight zero, and the triangular
decomposition then shows that all of `L` annihilates it. If the vector generates the module, the
whole action is trivial.

## Main results

* `EpsilonEridani.IsHighestWeightVector.lie_eq_zero_of_weight_zero`: every element of `L` annihilates a
  highest weight vector of weight zero in a finite-dimensional module.
* `EpsilonEridani.isTrivial_of_isHighestWeightVector_weight_zero_of_lieSpan_eq_top`: a finite-dimensional
  highest weight module of highest weight zero is trivial.
* `EpsilonEridani.isTrivial_of_isHighestWeightVector_weight_zero_of_isIrreducible`: an irreducible with a
  highest weight vector of weight zero is trivial.

## References

This is the zero-weight separation step in Layer 5, "Weyl's complete reducibility theorem", of
`EpsilonEridaniRoadmap/RepresentationTheory/LieHighestWeight/README.md`. Humphreys, *Introduction to Lie
Algebras and Representation Theory*, §6 supplies the model for the subsequent Casimir-splitting
argument; the rank-one zero-highest-weight argument used here is from §§7.2 and 21.1.
-/

public section

namespace EpsilonEridani

open LieAlgebra LieModule Module

universe u v w

variable {K : Type u} {L : Type v} [Field K] [CharZero K]
  [LieRing L] [LieAlgebra K L] [IsKilling K L] [FiniteDimensional K L]
  {H : LieSubalgebra K L} [H.IsCartanSubalgebra] [IsTriangularizable K H L]
  {M : Type w} [AddCommGroup M] [Module K M] [LieRingModule L M] [LieModule K L M]
  {b : (IsKilling.rootSystem H).Base} {v : M}

section FiniteDimensional

variable [FiniteDimensional K M]

private theorem IsHighestWeightVector.lie_eq_zero_of_mem_rootSpace_of_mem_negRoots_of_weight_zero
    (hv : IsHighestWeightVector b (0 : Dual K H) v)
    {alpha : H.root} (halpha : alpha ∈ negRoots (IsKilling.rootSystem H) b) {x : L}
    (hx : x ∈ rootSpace H (alpha : H → K)) : ⁅x, v⁆ = 0 := by
  refine forall_rootSpace_neg_lie_eq_zero_of_lie_coroot_eq_zero_of_forall_rootSpace_lie_eq_zero
    (K := K) (L := L) (H := H) (M := M)
    (α := ((-alpha : H.root) : Weight K H L)) ?_ ?_ x ?_
  · simpa using hv.lie_eq_smul (IsKilling.coroot (-alpha))
  · exact fun e he => hv.lie_eq_zero_of_mem_rootSpace
      (neg_mem_posRoots_of_mem_negRoots b halpha) he
  · simpa only [IsKilling.val_neg_root, neg_neg, Weight.coe_coe] using hx

/-- Every element of `L` annihilates a highest weight vector of weight zero in a finite-dimensional
module. -/
theorem IsHighestWeightVector.lie_eq_zero_of_weight_zero
    (hv : IsHighestWeightVector b (0 : Dual K H) v) (x : L) : ⁅x, v⁆ = 0 := by
  have hneg : negativeNilradical H b ≤ lieAnnihilator K L v :=
    (negativeNilradical_le_iff H b).mpr fun _ halpha _ hx =>
      (mem_lieAnnihilator K L).mpr
        (hv.lie_eq_zero_of_mem_rootSpace_of_mem_negRoots_of_weight_zero halpha hx)
  have hcartan : H ≤ lieAnnihilator K L v := fun y hy =>
    (mem_lieAnnihilator K L).mpr (by
    simpa using hv.lie_eq_smul ⟨y, hy⟩)
  have hpos : positiveNilradical H b ≤ lieAnnihilator K L v := fun _ hx =>
    (mem_lieAnnihilator K L).mpr (hv.lie_eq_zero_of_mem_positiveNilradical hx)
  have hborel : borelSubalgebra H b ≤ lieAnnihilator K L v := by
    rw [borelSubalgebra_eq_sup]
    exact sup_le hcartan hpos
  obtain ⟨y, hy, z, hz, rfl⟩ :=
    exists_mem_negativeNilradical_add_mem_borelSubalgebra H b x
  exact (mem_lieAnnihilator K L).mp (add_mem (hneg hy) (hborel hz))

/-- A finite-dimensional highest weight module generated in weight zero is a trivial Lie module. -/
theorem isTrivial_of_isHighestWeightVector_weight_zero_of_lieSpan_eq_top
    (hv : IsHighestWeightVector b (0 : Dual K H) v)
    (hgen : LieSubmodule.lieSpan K L {v} = ⊤) : LieModule.IsTrivial L M :=
  isTrivial_of_forall_lie_eq_zero_of_lieSpan_eq_top
    hv.lie_eq_zero_of_weight_zero hgen

end FiniteDimensional

/-- An irreducible module with a highest weight vector of weight zero is trivial. -/
theorem isTrivial_of_isHighestWeightVector_weight_zero_of_isIrreducible
    [LieModule.IsIrreducible K L M] (hv : IsHighestWeightVector b (0 : Dual K H) v) :
    LieModule.IsTrivial L M := by
  classical
  have hnonzero (i : b.support) : ((i : H.root) : Weight K H L).IsNonZero :=
    H.isNonZero_coe_root i
  choose h e f ht he hf using fun i =>
    IsKilling.exists_isSl2Triple_of_weight_isNonZero (hnonzero i)
  have he_zero (i : b.support) : ⁅e i, v⁆ = 0 :=
    hv.lie_eq_zero_of_mem_rootSpace
      (support_subset_posRoots (IsKilling.rootSystem H) b i.2) (he i)
  have hf_zero (i : b.support) : ⁅f i, v⁆ = 0 := by
    have hpow := pow_toEnd_eq_zero_of_isHighestWeightVector_of_isIrreducible
      hv i.2 (n := 0) (by simp) (hf i)
    simpa using hpow
  have hspan : LieSubalgebra.lieSpan K L (Set.range e ∪ Set.range f) = ⊤ :=
    LieAlgebra.lieSpan_range_union_eq_top_of_mem_rootSpace b e f
      (fun i => by
        rw [IsKilling.rootSystem_coroot_apply,
          ← (ht i).h_eq_coroot (hnonzero i) (he i) (hf i)]
        exact ht i) he hf
  have hann : lieAnnihilator K L v = ⊤ := by
    apply eq_top_iff.mpr
    rw [← hspan, LieSubalgebra.lieSpan_le]
    rintro x (⟨i, rfl⟩ | ⟨i, rfl⟩)
    · exact (mem_lieAnnihilator K L).mpr (he_zero i)
    · exact (mem_lieAnnihilator K L).mpr (hf_zero i)
  apply isTrivial_of_forall_lie_eq_zero_of_lieSpan_eq_top
    (R := K) (L := L) (M := M)
    (hgen := lieSpan_singleton_eq_top_of_ne_zero hv.ne_zero)
  intro x
  exact (mem_lieAnnihilator K L).mp (hann ▸ LieSubalgebra.mem_top x)

end EpsilonEridani
