/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.Algebra.Lie.HighestWeight.Maximal
public import EpsilonEridani.Algebra.Lie.UniversalEnveloping.Module

/-!
# Verma modules

Let `L` be a finite-dimensional Lie algebra with non-degenerate Killing form over a field `K` of
characteristic zero, let `H` be a splitting Cartan subalgebra and let `b` be a base of the root
system `LieAlgebra.IsKilling.rootSystem H`, so that the Borel subalgebra `𝔟 = H + n⁺` of
`EpsilonEridani/Algebra/Lie/Weights/Borel.lean` is available. For a linear form `lam` on `H` this file
builds the **Verma module** `M(lam)`, the universal module generated by a vector on which `H` acts
through `lam` and which the positive nilradical annihilates.

## The presentation

`M(lam)` is classically written `U(L) ⊗_{U(𝔟)} K_lam`, where `K_lam` is the one-dimensional
`𝔟`-module on which `x = h + n` acts by `lam h`. Since `U(L)` is a free right `U(𝔟)`-module only
after Poincaré--Birkhoff--Witt, and since Mathlib's tensor product is taken over a *commutative*
base, this file instead uses a quotient presentation:

`EpsilonEridani.vermaIdeal b lam` is the left ideal generated by the elements `ι x - lam x` for `x : H`
together with `ι x` for `x` in the positive nilradical, and
`EpsilonEridani.VermaModule b lam := U(L) ⧸ vermaIdeal b lam`.

For a decomposition `x = h + n` of an element of `𝔟`, the associated degree-one relation satisfies
`ι x - lam h = (ι h - lam h) + ι n` and hence belongs to this ideal. This containment is the content
of `EpsilonEridani.exists_ι_sub_algebraMap_mem_vermaIdeal_of_mem_borelSubalgebra` below.

Reading the quotient as a Lie module is what
`EpsilonEridani/Algebra/Lie/UniversalEnveloping/Module.lean` was built for: a left ideal is exactly a
`U(L)`-submodule of `U(L)`, so the quotient is a `U(L)`-module, and
`EpsilonEridani.UniversalEnvelopingAlgebra.asLieRingModule` turns that into an `L`-module. The same file
supplies the two dictionary results the universal property runs on: Lie module homomorphisms out of
`M(lam)` are `U(L)`-linear maps, and the Lie submodule generated by the canonical vector is its
`U(L)`-span.

## What is proved, and what needs PBW

The universal property `EpsilonEridani.existsUnique_lieModuleHom_apply_vermaGenerator` is proved in the
form that does *not* presuppose `M(lam) ≠ 0`: for **any** vector `v` of **any** `L`-module on which
`H` acts through `lam` and which `n⁺` annihilates — `v = 0` allowed — there is a unique Lie module
homomorphism `M(lam) → N` sending the canonical generator to `v`. Everything below is a consequence
of it.

What is *not* proved here is that `M(lam)` is nonzero. That is exactly the statement that the
left ideal `vermaIdeal b lam` is proper, and the classical proof of it is the freeness of `U(L)`
as a right `U(𝔟)`-module, hence Poincaré--Birkhoff--Witt; only the spanning half of PBW is
available (`EpsilonEridani.UniversalEnvelopingAlgebra.span_orderedPBWMonomials_eq_pbwFiltration`), and
spanning is the wrong half. Rather than assume it, the dependence is isolated in an equivalence:
`EpsilonEridani.isHighestWeightVector_vermaGenerator_iff` says the canonical generator is a highest
weight vector exactly when it is nonzero, and
`EpsilonEridani.vermaGenerator_ne_zero_of_isHighestWeightVector` says that this happens as soon as a
highest weight vector of weight `lam` exists anywhere. So `M(lam) ≠ 0` and "some `L`-module has a
highest weight vector of weight `lam`" are the same statement, and the irreducible quotient
`L(lam)` of `EpsilonEridani/Algebra/Lie/HighestWeight/Maximal.lean` follows from either.

For `lam = 0` that input is available: the trivial one-dimensional module is a highest weight
module of weight `0`, so `EpsilonEridani.isHighestWeightVector_vermaGenerator_zero` proves *without any
hypothesis* that `M(0)` is nonzero and that its canonical generator is a highest weight vector.
The construction therefore is not the zero quotient, and `L(0)` exists outright.

## Main definitions

* `EpsilonEridani.vermaRelations b lam` and `EpsilonEridani.vermaIdeal b lam`: the defining relations of weight
  `lam` and the left ideal of `U(L)` they generate.
* `EpsilonEridani.VermaModule b lam`: the Verma module `M(lam)`, with its `K`-module, `U(L)`-module and
  `L`-module structures.
* `EpsilonEridani.vermaMk b lam`: the canonical projection `U(L) → M(lam)`, as a `U(L)`-linear map.
* `EpsilonEridani.vermaGenerator b lam`: the canonical generator `v_lam`, the class of `1`.
* `EpsilonEridani.irreducibleQuotient b lam`: the irreducible quotient `L(lam)`, the quotient of `M(lam)`
  by its maximal submodule, with its `K`-module and `L`-module structures.
* `EpsilonEridani.irreducibleQuotientMk b lam`: the canonical projection `M(lam) → L(lam)`, as a Lie
  module homomorphism.
* `EpsilonEridani.irreducibleQuotientGenerator b lam`: the canonical generator of `L(lam)`, the class of
  the canonical generator of `M(lam)`.

## Main results

* `EpsilonEridani.lie_vermaGenerator_eq_smul` and
  `EpsilonEridani.lie_vermaGenerator_eq_zero_of_mem_positiveNilradical`: the Cartan subalgebra acts on the
  canonical generator through `lam`, and the positive nilradical annihilates it.
* `EpsilonEridani.lieSpan_vermaGenerator_eq_top`: the canonical generator generates `M(lam)`, so `M(lam)`
  is a highest weight module of weight `lam` as soon as the generator is nonzero.
* `EpsilonEridani.existsUnique_lieModuleHom_apply_vermaGenerator`: **the universal property**.
* `EpsilonEridani.exists_surjective_lieModuleHom_of_isHighestWeightVector`: **every highest weight module
  of weight `lam` is a quotient of `M(lam)`**, which is what makes `M(lam)` universal in the sense
  the classification uses.
* `EpsilonEridani.isHighestWeightVector_vermaGenerator_zero`: **`M(0) ≠ 0`, unconditionally**, its
  canonical generator being a highest weight vector of weight `0`.
* `EpsilonEridani.isHighestWeightVector_vermaGenerator_iff`,
  `EpsilonEridani.vermaGenerator_ne_zero_of_isHighestWeightVector`,
  `EpsilonEridani.vermaGenerator_eq_zero_iff` and `EpsilonEridani.subsingleton_vermaModule_iff`: the isolation of
  the one missing input described above, as the properness of `EpsilonEridani.vermaIdeal`.
* `EpsilonEridani.irreducibleQuotientMk_surjective` and
  `EpsilonEridani.lieSpan_irreducibleQuotientGenerator_eq_top`: every vector of `L(lam)` is the class of
  one of `M(lam)`, and the canonical generator generates `L(lam)`.
* `EpsilonEridani.isIrreducible_irreducibleQuotient` and
  `EpsilonEridani.isHighestWeightVector_irreducibleQuotientGenerator`: **`L(lam)` is irreducible and its
  canonical generator is a highest weight vector of weight `lam`**, once the Verma module is known
  to be nonzero.
* `EpsilonEridani.subsingleton_irreducibleQuotient_iff`: in the remaining case `L(lam)` is the zero
  module, so it is **either irreducible or zero, never anything else**.

## Roadmap

This is the "Verma modules" item of Layer 3 of
`EpsilonEridaniRoadmap/RepresentationTheory/LieHighestWeight/README.md`, whose targets `vermaModule`,
`vermaHighestWeightVector` and `vermaModule_universal` are pinned in the accompanying
`Suggested.lean`. The carrier is named `EpsilonEridani.VermaModule` rather than `vermaModule` because it
is a type, and the canonical vector `EpsilonEridani.vermaGenerator` rather than
`vermaHighestWeightVector` because it is only a highest weight vector once it is known to be
nonzero. `EpsilonEridani.irreducibleQuotient` is the carrier of the same layer's "irreducible quotient
`L(λ)`" item; the two properties `Suggested.lean` pins of it, irreducibility and the existence of a
highest weight vector of weight `lam`, are proved here under the hypothesis
`vermaGenerator b lam ≠ 0`, which is the missing PBW input described above and cannot be dropped
without it.

## References

* J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*, GTM 9, §20.3.
* J. E. Humphreys, *Representations of Semisimple Lie Algebras in the BGG Category `O`*, §1.3.
-/

public section

open UniversalEnvelopingAlgebra

namespace EpsilonEridani

open LieAlgebra LieModule Module

universe u v w

variable {K : Type u} {L : Type v} [Field K] [CharZero K] [LieRing L] [LieAlgebra K L]
  [IsKilling K L] [FiniteDimensional K L]
  {H : LieSubalgebra K L} [H.IsCartanSubalgebra] [IsTriangularizable K H L]

local notation "U" => _root_.UniversalEnvelopingAlgebra K L

variable (b : (IsKilling.rootSystem H).Base) (lam : Dual K H)

/-! ### The defining left ideal -/

/-- The **Verma relations** of weight `lam`: the elements `ι x - lam x` of `U(L)` for `x` in the
Cartan subalgebra, together with the elements `ι x` for `x` in the positive nilradical. Their
image in `M(lam)` is what forces the Cartan subalgebra to act on the class of `1` through `lam`
and the positive nilradical to annihilate it. Those are two of the three conditions defining a
highest weight vector, so that class is a highest weight vector of weight `lam` exactly when it
is nonzero; see `EpsilonEridani.isHighestWeightVector_vermaGenerator_iff`. -/
def vermaRelations : Set U :=
  Set.range (fun x : H => (ι K (x : L) : U) - algebraMap K U (lam x)) ∪
    (fun x : L => (ι K x : U)) '' (positiveNilradical H b : Set L)

/-- The **Verma ideal** of weight `lam`: the left ideal of `U(L)` generated by the Verma
relations. -/
def vermaIdeal : Submodule U U :=
  Submodule.span U (vermaRelations b lam)

/-- The relation `ι x - lam x` lies in the Verma ideal, for `x` in the Cartan subalgebra. -/
theorem ι_sub_algebraMap_mem_vermaIdeal (x : H) :
    (ι K (x : L) : U) - algebraMap K U (lam x) ∈ vermaIdeal b lam :=
  Submodule.subset_span (Or.inl ⟨x, rfl⟩)

/-- The relation `ι x` lies in the Verma ideal, for `x` in the positive nilradical. -/
theorem ι_mem_vermaIdeal_of_mem_positiveNilradical {x : L}
    (hx : x ∈ positiveNilradical H b) : (ι K x : U) ∈ vermaIdeal b lam :=
  Submodule.subset_span (Or.inr ⟨x, hx, rfl⟩)

/-- For an element `x = h + n` of the Borel subalgebra, the degree-one relation `ι x - lam h`
belongs to the Verma ideal, since it is the sum of the two kinds of generator. -/
theorem exists_ι_sub_algebraMap_mem_vermaIdeal_of_mem_borelSubalgebra {x : L}
    (hx : x ∈ borelSubalgebra H b) :
    ∃ h : H, (ι K x : U) - algebraMap K U (lam h) ∈ vermaIdeal b lam := by
  rw [← LieSubalgebra.mem_toSubmodule, borelSubalgebra_toSubmodule, Submodule.mem_sup] at hx
  obtain ⟨h, hh, n, hn, rfl⟩ := hx
  refine ⟨⟨h, hh⟩, ?_⟩
  have hsplit : (ι K ((h : L) + n) : U) - algebraMap K U (lam ⟨h, hh⟩)
      = ((ι K h : U) - algebraMap K U (lam ⟨h, hh⟩)) + (ι K n : U) := by
    rw [map_add]
    abel
  rw [hsplit]
  exact Submodule.add_mem _ (ι_sub_algebraMap_mem_vermaIdeal b lam ⟨h, hh⟩)
    (ι_mem_vermaIdeal_of_mem_positiveNilradical b lam hn)

/-! ### The Verma module and its structures -/

/-- **The Verma module** `M(lam)`, defined here as the quotient of `U(L)` by the left ideal
`EpsilonEridani.vermaIdeal` of Verma relations. -/
def VermaModule : Type max u v :=
  U ⧸ vermaIdeal b lam

instance : AddCommGroup (VermaModule b lam) :=
  inferInstanceAs (AddCommGroup (U ⧸ vermaIdeal b lam))

instance : Module U (VermaModule b lam) :=
  inferInstanceAs (Module U (U ⧸ vermaIdeal b lam))

instance : Module K (VermaModule b lam) :=
  inferInstanceAs (Module K (U ⧸ vermaIdeal b lam))

instance : IsScalarTower K U (VermaModule b lam) :=
  inferInstanceAs (IsScalarTower K U (U ⧸ vermaIdeal b lam))

noncomputable instance : LieRingModule L (VermaModule b lam) :=
  UniversalEnvelopingAlgebra.asLieRingModule K L (VermaModule b lam)

noncomputable instance : LieModule K L (VermaModule b lam) :=
  UniversalEnvelopingAlgebra.asLieModule K L (VermaModule b lam)

/-- The `L`-action on the Verma module is the action of the canonical Lie generators of `U(L)`.
This is the compatibility hypothesis the enveloping-algebra dictionary consumes. -/
theorem vermaModule_ι_smul (x : L) (m : VermaModule b lam) : (ι K x : U) • m = ⁅x, m⁆ :=
  (UniversalEnvelopingAlgebra.asLieRingModule_bracket K L (VermaModule b lam) x m).symm

/-- **The canonical projection** `U(L) → M(lam)`, bundled as a `U(L)`-linear map so that its
algebraic behaviour — `map_zero`, `map_add`, `map_smul` — is available from the `LinearMap` API
without unfolding the quotient. -/
def vermaMk : U →ₗ[U] VermaModule b lam :=
  Submodule.mkQ (vermaIdeal b lam)

theorem vermaMk_surjective : Function.Surjective (vermaMk b lam) :=
  Submodule.mkQ_surjective _

theorem vermaMk_eq_iff {u w : U} :
    vermaMk b lam u = vermaMk b lam w ↔ u - w ∈ vermaIdeal b lam :=
  Submodule.Quotient.eq _

@[simp]
theorem vermaMk_eq_zero_iff {u : U} : vermaMk b lam u = 0 ↔ u ∈ vermaIdeal b lam :=
  Submodule.Quotient.mk_eq_zero _

@[simp]
theorem smul_vermaMk (u w : U) : u • vermaMk b lam w = vermaMk b lam (u * w) :=
  (Submodule.Quotient.mk_smul _ u w).symm

/-- **The canonical generator** `v_lam` of the Verma module, the class of `1`. It is a highest
weight vector of weight `lam` exactly when it is nonzero, which is
`EpsilonEridani.isHighestWeightVector_vermaGenerator_iff`. -/
def vermaGenerator : VermaModule b lam :=
  vermaMk b lam 1

@[simp]
theorem smul_vermaGenerator (u : U) : u • vermaGenerator b lam = vermaMk b lam u := by
  rw [vermaGenerator, smul_vermaMk, mul_one]

/-- **The Cartan subalgebra acts on the canonical generator through `lam`.** -/
@[simp]
theorem lie_vermaGenerator_eq_smul (x : H) :
    ⁅(x : L), vermaGenerator b lam⁆ = lam x • vermaGenerator b lam := by
  rw [← vermaModule_ι_smul b lam, smul_vermaGenerator, vermaGenerator, ← algebraMap_smul U (lam x),
    smul_vermaMk, mul_one, vermaMk_eq_iff]
  exact ι_sub_algebraMap_mem_vermaIdeal b lam x

/-- **The positive nilradical annihilates the canonical generator.** -/
theorem lie_vermaGenerator_eq_zero_of_mem_positiveNilradical {x : L}
    (hx : x ∈ positiveNilradical H b) : ⁅x, vermaGenerator b lam⁆ = 0 := by
  rw [← vermaModule_ι_smul b lam, smul_vermaGenerator, vermaMk_eq_zero_iff]
  exact ι_mem_vermaIdeal_of_mem_positiveNilradical b lam hx

/-- The canonical generator spans the Verma module over `U(L)`. -/
theorem span_vermaGenerator_eq_top :
    Submodule.span U {vermaGenerator b lam} = ⊤ := by
  refine top_le_iff.mp fun m _ => ?_
  obtain ⟨u, rfl⟩ := vermaMk_surjective b lam m
  rw [← smul_vermaGenerator]
  exact Submodule.smul_mem _ _ (Submodule.mem_span_singleton_self _)

/-- **The canonical generator generates the Verma module** as a Lie module, by the dictionary
carrying generated Lie submodules to `U(L)`-spans. Together with
`EpsilonEridani.isHighestWeightVector_vermaGenerator_iff` this exhibits `M(lam)` as a highest weight
module of weight `lam` whenever it is nonzero. -/
theorem lieSpan_vermaGenerator_eq_top :
    LieSubmodule.lieSpan K L {vermaGenerator b lam} = ⊤ := by
  refine (UniversalEnvelopingAlgebra.lieSubmoduleOrderIso
    (vermaModule_ι_smul b lam)).injective ?_
  rw [UniversalEnvelopingAlgebra.lieSubmoduleOrderIso_lieSpan, span_vermaGenerator_eq_top,
    OrderIso.map_top]

/-! ### The universal property -/

variable {N : Type w} [AddCommGroup N] [Module K N] [LieRingModule L N] [LieModule K L N]

/-- **The universal property of the Verma module.** If `H` acts on a vector `v` of an `L`-module
`N` through `lam` and the positive nilradical annihilates `v`, then there is a unique homomorphism
of `L`-modules `M(lam) → N` carrying the canonical generator to `v`.

The vector `v` is *not* assumed nonzero, so this does not presuppose that `M(lam)` is nonzero;
conversely it forces `M(lam)` to be nonzero as soon as some `v ≠ 0` is available, which is
`EpsilonEridani.vermaGenerator_ne_zero_of_isHighestWeightVector`. -/
theorem existsUnique_lieModuleHom_apply_vermaGenerator (v : N)
    (hcartan : ∀ x : H, ⁅(x : L), v⁆ = lam x • v)
    (hpos : ∀ x ∈ positiveNilradical H b, ⁅x, v⁆ = 0) :
    ∃! φ : VermaModule b lam →ₗ⁅K,L⁆ N, φ (vermaGenerator b lam) = v := by
  let _ : Module U N := UniversalEnvelopingAlgebra.asModule K L N
  have _ : IsScalarTower K U N := UniversalEnvelopingAlgebra.isScalarTower_asModule K L N
  have hN : ∀ (x : L) (n : N), (ι K x : U) • n = ⁅x, n⁆ :=
    UniversalEnvelopingAlgebra.asModule_ι_smul K L N
  have hM := vermaModule_ι_smul b lam
  set f : U →ₗ[U] N := LinearMap.toSpanSingleton U N v
  have hf : ∀ u : U, f u = u • v := by
    intro u
    simp only [f, LinearMap.toSpanSingleton_apply]
  have hker : vermaIdeal b lam ≤ LinearMap.ker f := by
    rw [vermaIdeal, Submodule.span_le]
    rintro u (⟨x, rfl⟩ | ⟨x, hx, rfl⟩)
    · simp only [SetLike.mem_coe, LinearMap.mem_ker, hf, sub_smul, hN, hcartan x,
        algebraMap_smul, sub_self]
    · simp only [SetLike.mem_coe, LinearMap.mem_ker, hf, hN, hpos x hx]
  set g : VermaModule b lam →ₗ[U] N := Submodule.liftQ (vermaIdeal b lam) f hker
  have hg : ∀ u : U, g (vermaMk b lam u) = u • v := by
    intro u
    calc
      g (vermaMk b lam u) = f u := by
        apply Submodule.liftQ_apply
      _ = u • v := hf u
  have hcoe : ⇑((UniversalEnvelopingAlgebra.lieModuleHomEquiv hM hN).symm g) = ⇑g :=
    UniversalEnvelopingAlgebra.coe_lieModuleHomEquiv_symm hM hN g
  have hval : ((UniversalEnvelopingAlgebra.lieModuleHomEquiv hM hN).symm g)
      (vermaGenerator b lam) = v := by
    rw [hcoe, vermaGenerator, hg, one_smul]
  refine ⟨(UniversalEnvelopingAlgebra.lieModuleHomEquiv hM hN).symm g, hval, fun ψ hψ => ?_⟩
  refine (UniversalEnvelopingAlgebra.lieModuleHomEquiv hM hN).injective ?_
  rw [LinearEquiv.apply_symm_apply]
  refine LinearMap.ext_on (span_vermaGenerator_eq_top b lam) ?_
  rintro x rfl
  rw [UniversalEnvelopingAlgebra.coe_lieModuleHomEquiv, hψ, vermaGenerator, hg, one_smul]

/-! ### Highest weight vectors and the missing nonvanishing -/

/-- **The canonical generator is a highest weight vector exactly when it is nonzero.** The other
two conditions hold unconditionally, by `EpsilonEridani.lie_vermaGenerator_eq_smul` and
`EpsilonEridani.lie_vermaGenerator_eq_zero_of_mem_positiveNilradical`. -/
theorem isHighestWeightVector_vermaGenerator_iff :
    IsHighestWeightVector b lam (vermaGenerator b lam) ↔ vermaGenerator b lam ≠ 0 :=
  ⟨fun h => h.ne_zero, fun h => isHighestWeightVector_iff.mpr ⟨h, lie_vermaGenerator_eq_smul b lam,
    fun _ hx => lie_vermaGenerator_eq_zero_of_mem_positiveNilradical b lam hx⟩⟩

/-- **The Verma module is nonzero as soon as some module has a highest weight vector of weight
`lam`.** The universal property carries the canonical generator to that vector, so the generator
cannot vanish. -/
theorem vermaGenerator_ne_zero_of_isHighestWeightVector {v : N}
    (hv : IsHighestWeightVector b lam v) : vermaGenerator b lam ≠ 0 := by
  obtain ⟨φ, hφ, -⟩ := existsUnique_lieModuleHom_apply_vermaGenerator b lam v hv.lie_eq_smul
    fun _ hx => hv.lie_eq_zero_of_mem_positiveNilradical hx
  intro h
  exact hv.ne_zero (by rw [← hφ, h, map_zero])

/-- **The Verma module of weight zero is nonzero, and its canonical generator really is a highest
weight vector.** The trivial one-dimensional module `K` carries the nonzero vector `1`, on which
the Cartan subalgebra acts through `0` and which the positive nilradical annihilates, so the
universal property produces a homomorphism `M(0) → K` sending the canonical generator to `1`.
This is the unconditional witness that the construction is not the zero module: `M(0) ≠ 0` and
`M(0) ⧸ maximalSubmodule` is the irreducible module `L(0)`, with no appeal to
Poincaré--Birkhoff--Witt. -/
theorem isHighestWeightVector_vermaGenerator_zero :
    IsHighestWeightVector b (0 : Dual K H) (vermaGenerator b (0 : Dual K H)) := by
  rw [isHighestWeightVector_vermaGenerator_iff]
  refine vermaGenerator_ne_zero_of_isHighestWeightVector b 0 (N := TrivialLieModule K L K)
    (v := (TrivialLieModule.equiv K L K).symm 1) (isHighestWeightVector_iff.mpr ⟨?_, ?_, ?_⟩)
  · simp
  · intro x
    rw [trivial_lie_zero]
    simp
  · intro x _
    rw [trivial_lie_zero]

/-- **Every highest weight module of weight `lam` is a quotient of the Verma module.** This is the
sense in which `M(lam)` is the universal highest weight module of weight `lam`, and the form in
which the classification of the irreducible highest weight modules consumes it. -/
theorem exists_surjective_lieModuleHom_of_isHighestWeightVector {v : N}
    (hv : IsHighestWeightVector b lam v) (hgen : LieSubmodule.lieSpan K L {v} = ⊤) :
    ∃ φ : VermaModule b lam →ₗ⁅K,L⁆ N,
      Function.Surjective φ ∧ φ (vermaGenerator b lam) = v := by
  obtain ⟨φ, hφ, -⟩ := existsUnique_lieModuleHom_apply_vermaGenerator b lam v hv.lie_eq_smul
    fun _ hx => hv.lie_eq_zero_of_mem_positiveNilradical hx
  refine ⟨φ, ?_, hφ⟩
  rw [← LieModuleHom.range_eq_top, ← top_le_iff, ← hgen, LieSubmodule.lieSpan_le]
  rintro w rfl
  exact ⟨vermaGenerator b lam, hφ⟩

/-- **The canonical generator vanishes exactly when the Verma ideal is improper.** This is the
precise form of the one input the file does not supply: `M(lam) ≠ 0` says that the left ideal
generated by the Verma relations is proper, which classically follows from the freeness of `U(L)`
as a right `U(𝔟)`-module, hence from Poincaré--Birkhoff--Witt. -/
theorem vermaGenerator_eq_zero_iff : vermaGenerator b lam = 0 ↔ vermaIdeal b lam = ⊤ := by
  rw [vermaGenerator, vermaMk_eq_zero_iff]
  refine ⟨fun h => eq_top_iff.mpr fun u _ => ?_, fun h => h ▸ trivial⟩
  simpa using Submodule.smul_mem (vermaIdeal b lam) u h

/-- **The Verma module vanishes exactly when its canonical generator does**, the generator
spanning it. -/
theorem subsingleton_vermaModule_iff :
    Subsingleton (VermaModule b lam) ↔ vermaGenerator b lam = 0 := by
  -- The quotient criterion is stated for a literal quotient, so unfold the named carrier before
  -- rewriting with it.
  change Subsingleton (U ⧸ vermaIdeal b lam) ↔ vermaGenerator b lam = 0
  rw [Submodule.Quotient.subsingleton_iff, ← vermaGenerator_eq_zero_iff]

/-- **The irreducible quotient `L(lam)`**: the quotient of the Verma module by the maximal
submodule of `EpsilonEridani/Algebra/Lie/HighestWeight/Maximal.lean`. As with
`EpsilonEridani.VermaModule`, the carrier is a definition with its module structures declared
one by one, so that statements about `L(lam)` are made against this name rather than against the
quotient it is built from.

Nothing about it is irreducible by fiat: irreducibility is
`EpsilonEridani.isIrreducible_irreducibleQuotient`, which needs `M(lam) ≠ 0`. Naming the carrier is what
lets a statement about `L(lam)` be phrased at one fixed module instead of at an arbitrary
irreducible module carrying a highest weight vector of weight `lam`. -/
def irreducibleQuotient : Type max u v :=
  VermaModule b lam ⧸ maximalSubmodule H (VermaModule b lam) lam

noncomputable instance : AddCommGroup (irreducibleQuotient b lam) :=
  inferInstanceAs
    (AddCommGroup (VermaModule b lam ⧸ maximalSubmodule H (VermaModule b lam) lam))

noncomputable instance : Module K (irreducibleQuotient b lam) :=
  inferInstanceAs
    (Module K (VermaModule b lam ⧸ maximalSubmodule H (VermaModule b lam) lam))

noncomputable instance : LieRingModule L (irreducibleQuotient b lam) :=
  inferInstanceAs
    (LieRingModule L (VermaModule b lam ⧸ maximalSubmodule H (VermaModule b lam) lam))

noncomputable instance : LieModule K L (irreducibleQuotient b lam) :=
  inferInstanceAs
    (LieModule K L (VermaModule b lam ⧸ maximalSubmodule H (VermaModule b lam) lam))

/-- **The canonical projection** `M(lam) → L(lam)`, bundled as a Lie module homomorphism, so that
its algebraic behaviour — `map_zero`, `map_add`, `map_smul`, `map_lie` — is available from the
`LieModuleHom` API without unfolding the quotient. It is the analogue for `L(lam)` of
`EpsilonEridani.vermaMk`, and together with `EpsilonEridani.irreducibleQuotientMk_surjective` it is how every
vector of `L(lam)` is reached. -/
noncomputable def irreducibleQuotientMk : VermaModule b lam →ₗ⁅K,L⁆ irreducibleQuotient b lam :=
  LieSubmodule.Quotient.mk' (maximalSubmodule H (VermaModule b lam) lam)

/-- **The canonical projection onto `L(lam)` is surjective**: every vector of `L(lam)` is the
class of one of `M(lam)`. This is the elimination rule matching
`EpsilonEridani.irreducibleQuotientMk`, and it is what lets a statement about `L(lam)` be checked on
representatives without unfolding the quotient. -/
theorem irreducibleQuotientMk_surjective : Function.Surjective (irreducibleQuotientMk b lam) :=
  fun q => LieSubmodule.Quotient.surjective_mk' _ q

/-- **The canonical generator of `L(lam)`**, the class of the canonical generator of `M(lam)`.
It is a highest weight vector of weight `lam` as soon as `M(lam)` is nonzero
(`EpsilonEridani.isHighestWeightVector_irreducibleQuotientGenerator`), and it is the introduction rule
through which `L(lam)` is populated without unfolding the quotient. The body is not exposed: the
public equation is `EpsilonEridani.irreducibleQuotientMk_vermaGenerator`. -/
noncomputable def irreducibleQuotientGenerator : irreducibleQuotient b lam :=
  irreducibleQuotientMk b lam (vermaGenerator b lam)

@[simp]
theorem irreducibleQuotientMk_vermaGenerator :
    irreducibleQuotientMk b lam (vermaGenerator b lam) = irreducibleQuotientGenerator b lam :=
  (rfl)

/-- **The canonical generator generates `L(lam)`**, the canonical generator of `M(lam)` generating
`M(lam)` and the projection being surjective. So `L(lam)` is a highest weight module of weight
`lam` as soon as `M(lam)` is nonzero. -/
theorem lieSpan_irreducibleQuotientGenerator_eq_top :
    LieSubmodule.lieSpan K L {irreducibleQuotientGenerator b lam} = ⊤ :=
  lieSpan_mk_eq_top_of_lieSpan_eq_top (lieSpan_vermaGenerator_eq_top b lam) _

/-- **`L(lam)` is irreducible.** As soon as the Verma module is nonzero, it is a highest weight
module of weight `lam`, so its quotient by the maximal submodule is irreducible. By
`EpsilonEridani.quotientMaximalSubmoduleEquivOfSurjectiveOfIsIrreducible` it is then the only irreducible
highest weight module of weight `lam`, up to isomorphism. -/
theorem isIrreducible_irreducibleQuotient (h : vermaGenerator b lam ≠ 0) :
    LieModule.IsIrreducible K L (irreducibleQuotient b lam) :=
  isIrreducible_quotient_maximalSubmodule_of_isHighestWeightVector_of_lieSpan_eq_top
    ((isHighestWeightVector_vermaGenerator_iff b lam).mpr h)
    (lieSpan_vermaGenerator_eq_top b lam)

/-- **`L(lam)` carries a highest weight vector of weight `lam`**, its canonical generator; the
anti-vacuity companion of `EpsilonEridani.isIrreducible_irreducibleQuotient`, without which any family of
pairwise non-isomorphic irreducibles would do. -/
theorem isHighestWeightVector_irreducibleQuotientGenerator (h : vermaGenerator b lam ≠ 0) :
    IsHighestWeightVector b lam (irreducibleQuotientGenerator b lam) :=
  isHighestWeightVector_mk_of_isHighestWeightVector_of_lieSpan_eq_top
    ((isHighestWeightVector_vermaGenerator_iff b lam).mpr h)
    (lieSpan_vermaGenerator_eq_top b lam)

/-- **`L(lam)` is the zero module exactly when `M(lam)` is.** It is a quotient of `M(lam)`, and
conversely it is irreducible, hence nonzero, as soon as `M(lam)` is nonzero. Together with
`EpsilonEridani.isIrreducible_irreducibleQuotient` this settles the named carrier in both cases: `L(lam)`
is irreducible when `M(lam) ≠ 0` and zero otherwise, so a statement about it never has to leave
the missing Poincaré--Birkhoff--Witt input undischarged. -/
theorem subsingleton_irreducibleQuotient_iff :
    Subsingleton (irreducibleQuotient b lam) ↔ vermaGenerator b lam = 0 := by
  refine ⟨fun h ↦ ?_, fun h ↦ ?_⟩
  · by_contra h0
    have _ := isIrreducible_irreducibleQuotient b lam h0
    have _ : Nontrivial (irreducibleQuotient b lam) :=
      LieModule.nontrivial_of_isIrreducible (R := K) (L := L) (M := irreducibleQuotient b lam)
    exact not_subsingleton _ h
  · have _ : Subsingleton (VermaModule b lam) := (subsingleton_vermaModule_iff b lam).mpr h
    exact (irreducibleQuotientMk_surjective b lam).subsingleton

end EpsilonEridani
