/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.NumberTheory.Multiquadratic.Quadratic.GenusCharacter.OrdinaryTwoRank
public import EpsilonEridani.NumberTheory.Multiquadratic.Three.ClassNumber
import EpsilonEridani.NumberTheory.Multiquadratic.Prime.Discriminants

/-!
# The `2`-ranks of the class groups of `ℚ(√3)`

The real quadratic field `K = ℚ(√3)` separates the two `2`-rank formulas of genus theory. Its
discriminant `12 = (-4) · (-3)` is a product of two prime discriminants, so `t = 2` rational
primes ramify (`2` and `3`), and the narrow formula gives `2-rank Cl⁺(K) = t - 1 = 1`. The
ordinary class group, however, is trivial
(`EpsilonEridani.NumberField.classNumber_eq_one_of_minpoly_eq_X_sq_sub_three`), so
`2-rank Cl(K) = 0 = t - 2`: the formula `t - 1` is **false** for the ordinary class group of a
real quadratic field.

Genus theory gives the drop: both prime discriminants dividing `12` are negative, so
`EpsilonEridani.Multiquadratic.twoRank_eq_ncard_ramifiedPrimes_sub_two_of_neg` already gives
`2-rank Cl(K) = t - 2` and, in particular,
`EpsilonEridani.Multiquadratic.twoRank_eq_zero_of_minpoly_eq_X_sq_sub_three`.

Together with `2-rank Cl⁺(K) = 1` the triviality of `Cl(K)` pins the narrow class group down:
`Cl⁺(K)` is generated by principal classes, hence has exponent dividing `2`, hence is its own
maximal elementary-`2` quotient, of order `2`. So `ℚ(√3)` has class number `1` and narrow class
number `2`.

## References

* F. Lemmermeyer, *Reciprocity Laws: From Euler to Eisenstein*, §2.2.
* D. A. Cox, *Primes of the Form x² + ny²*, §6.A.

## Main results

* `EpsilonEridani.Multiquadratic.ncard_ramifiedPrimes_eq_two_of_minpoly_eq_X_sq_sub_three`: `t = 2`.
* `EpsilonEridani.Multiquadratic.narrowTwoRank_eq_one_of_minpoly_eq_X_sq_sub_three`: the narrow
  `2`-rank is `t - 1 = 1`.
* `EpsilonEridani.Multiquadratic.twoRank_eq_zero_of_minpoly_eq_X_sq_sub_three` and
  `EpsilonEridani.Multiquadratic.twoRank_ne_ncard_ramifiedPrimes_sub_one_of_minpoly_eq_X_sq_sub_three`:
  the ordinary `2`-rank is `0`, so the `t - 1` formula fails for `Cl(K)`.
* `EpsilonEridani.Multiquadratic.natCard_narrowClassGroup_eq_two_of_minpoly_eq_X_sq_sub_three`: the
  narrow class number of `ℚ(√3)` is `2`.
-/

public section

open Polynomial NumberField
open scoped NumberField

namespace EpsilonEridani.Multiquadratic

variable {K : Type*} [Field K] [NumberField K] {θ : 𝓞 K}

private theorem isPrimeDiscriminant_of_mem_neg_four_neg_three :
    ∀ P ∈ ({-4, -3} : Finset ℤ), IsPrimeDiscriminant P := by
  intro P hP
  fin_cases hP
  · exact isPrimeDiscriminant_neg_four
  · simpa [oddPrimeDiscriminant_of_mod_four_eq_three (by norm_num : 3 % 4 = 3)]
      using isPrimeDiscriminant_oddPrimeDiscriminant (p := 3) (by decide) (by decide)

private theorem eq_of_mem_neg_four_neg_three_of_even :
    ∀ P ∈ ({-4, -3} : Finset ℤ), ∀ Q ∈ ({-4, -3} : Finset ℤ),
      IsEvenPrimeDiscriminant P → IsEvenPrimeDiscriminant Q → P = Q := by
  intro P hP Q hQ
  fin_cases hP <;> fin_cases hQ <;> simp only [IsEvenPrimeDiscriminant] <;> decide

private theorem prod_neg_four_neg_three :
    ∏ P ∈ ({-4, -3} : Finset ℤ), P = fundamentalDiscriminant (3 : ℤ) := by
  rw [Finset.prod_pair (by decide : (-4 : ℤ) ≠ -3),
    fundamentalDiscriminant_of_mod_four_ne_one (by decide : (3 : ℤ) % 4 ≠ 1)]
  norm_num

/-- **Two rational primes ramify in `ℚ(√3)`.** Its fundamental discriminant `12` factors as
`(-4) · (-3)` into two prime discriminants, so the ramified primes are `2` and `3`. -/
theorem ncard_ramifiedPrimes_eq_two_of_minpoly_eq_X_sq_sub_three
    (hmin : minpoly ℤ θ = X ^ 2 - C (3 : ℤ)) (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤) :
    (ramifiedPrimes K).ncard = 2 := by
  rw [ncard_ramifiedPrimes_eq_card hmin hgen Int.prime_three.squarefree
      isPrimeDiscriminant_of_mem_neg_four_neg_three eq_of_mem_neg_four_neg_three_of_even
      prod_neg_four_neg_three,
    Finset.card_pair (by decide : (-4 : ℤ) ≠ -3)]

/-- **`ℚ(√3)` has class-group `2`-rank `0`.** Its discriminant `12 = (-4) · (-3)` has two negative
prime-discriminant factors, so two primes ramify and the `2`-rank is `t - 2 = 0`, one less than
the narrow `2`-rank `t - 1 = 1`. -/
theorem twoRank_eq_zero_of_minpoly_eq_X_sq_sub_three
    (hmin : minpoly ℤ θ = X ^ 2 - C (3 : ℤ)) (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤) :
    EpsilonEridani.ClassGroup.twoRank (𝓞 K) = 0 := by
  rw [twoRank_eq_ncard_ramifiedPrimes_sub_two_of_neg
      isPrimeDiscriminant_of_mem_neg_four_neg_three eq_of_mem_neg_four_neg_three_of_even
      prod_neg_four_neg_three hmin hgen Int.prime_three.squarefree (by norm_num)
      (P := -4) (by simp) (by norm_num),
    ncard_ramifiedPrimes_eq_two_of_minpoly_eq_X_sq_sub_three hmin hgen]

/-- **The `2`-rank of the narrow class group of `ℚ(√3)` is `1`.** The genus-theoretic formula
`2-rank Cl⁺(K) = t - 1` at `t = 2`. -/
theorem narrowTwoRank_eq_one_of_minpoly_eq_X_sq_sub_three
    (hmin : minpoly ℤ θ = X ^ 2 - C (3 : ℤ)) (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤) :
    NumberField.NarrowClassGroup.twoRank K = 1 := by
  rw [narrowTwoRank_eq_ncard_ramifiedPrimes_sub_one hmin hgen Int.prime_three.squarefree,
    ncard_ramifiedPrimes_eq_two_of_minpoly_eq_X_sq_sub_three hmin hgen]

/-- **The `t - 1` formula fails for the ordinary class group of a real quadratic field.** In
`ℚ(√3)` two rational primes ramify while the class group is trivial, so its `2`-rank is `0`, not
`t - 1 = 1`. This is why `EpsilonEridani.Multiquadratic.twoRank_eq_ncard_ramifiedPrimes_sub_one` is
restricted to imaginary quadratic fields and the unrestricted formula
`EpsilonEridani.Multiquadratic.narrowTwoRank_eq_ncard_ramifiedPrimes_sub_one` is about the narrow class
group. -/
theorem twoRank_ne_ncard_ramifiedPrimes_sub_one_of_minpoly_eq_X_sq_sub_three
    (hmin : minpoly ℤ θ = X ^ 2 - C (3 : ℤ)) (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤) :
    EpsilonEridani.ClassGroup.twoRank (𝓞 K) ≠ (ramifiedPrimes K).ncard - 1 := by
  rw [twoRank_eq_zero_of_minpoly_eq_X_sq_sub_three hmin hgen,
    ncard_ramifiedPrimes_eq_two_of_minpoly_eq_X_sq_sub_three hmin hgen]
  decide

/-- **The narrow class number of `ℚ(√3)` is `2`.** Since the ordinary class group is trivial,
every narrow class is a principal class, so `Cl⁺(K)` has exponent dividing `2`
(`NumberField.NarrowClassGroup.mkPrincipal_sq`) and therefore coincides with its own maximal
elementary-`2` quotient, whose order is `2 ^ (t - 1) = 2`. -/
theorem natCard_narrowClassGroup_eq_two_of_minpoly_eq_X_sq_sub_three
    (hmin : minpoly ℤ θ = X ^ 2 - C (3 : ℤ)) (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤) :
    Nat.card (NumberField.NarrowClassGroup K) = 2 := by
  have hclass := EpsilonEridani.NumberField.classNumber_eq_one_of_minpoly_eq_X_sq_sub_three hmin hgen
  rw [NumberField.NarrowClassGroup.card_eq_two_pow_twoRank_of_classNumber_eq_one K hclass,
    narrowTwoRank_eq_one_of_minpoly_eq_X_sq_sub_three hmin hgen]
  norm_num

/-- **Worked example.** In the concrete number field `AdjoinRoot (X² - 3)`, modelling `ℚ(√3)`,
two rational primes ramify. -/
@[simp]
theorem ncard_ramifiedPrimes_adjoinRoot_sqrt_three_eq_two :
    (ramifiedPrimes (AdjoinRoot (X ^ 2 - C (3 : ℚ)))).ncard = 2 := by
  obtain ⟨θ, hmin, hgen⟩ :=
    EpsilonEridani.NumberField.exists_minpoly_eq_X_sq_sub_three_and_adjoin_eq_top
  exact ncard_ramifiedPrimes_eq_two_of_minpoly_eq_X_sq_sub_three hmin hgen

/-- **Worked example.** The concrete number field `AdjoinRoot (X² - 3)`, modelling `ℚ(√3)`, has
narrow class-group `2`-rank `1`. Not `@[simp]`: the `@[simp]` lemma
`NumberField.NarrowClassGroup.twoRank_def` unfolds the left-hand side, so this closed form is not
in simp-normal form. -/
theorem narrowTwoRank_adjoinRoot_sqrt_three_eq_one :
    NumberField.NarrowClassGroup.twoRank (AdjoinRoot (X ^ 2 - C (3 : ℚ))) = 1 := by
  obtain ⟨θ, hmin, hgen⟩ :=
    EpsilonEridani.NumberField.exists_minpoly_eq_X_sq_sub_three_and_adjoin_eq_top
  exact narrowTwoRank_eq_one_of_minpoly_eq_X_sq_sub_three hmin hgen

/-- **Worked example.** The concrete number field `AdjoinRoot (X² - 3)`, modelling `ℚ(√3)`, has
ordinary class-group `2`-rank `0`, one less than the narrow one. Not `@[simp]`, for the same
reason as `narrowTwoRank_adjoinRoot_sqrt_three_eq_one`. -/
theorem twoRank_adjoinRoot_sqrt_three_eq_zero :
    EpsilonEridani.ClassGroup.twoRank (𝓞 (AdjoinRoot (X ^ 2 - C (3 : ℚ)))) = 0 := by
  obtain ⟨θ, hmin, hgen⟩ :=
    EpsilonEridani.NumberField.exists_minpoly_eq_X_sq_sub_three_and_adjoin_eq_top
  exact twoRank_eq_zero_of_minpoly_eq_X_sq_sub_three hmin hgen

/-- **The `t - 1` formula fails in the concrete model of `ℚ(√3)`.** Its ordinary class-group
`2`-rank is not one less than the number of ramified rational primes. -/
theorem twoRank_ne_ncard_ramifiedPrimes_sub_one_adjoinRoot_sqrt_three :
    EpsilonEridani.ClassGroup.twoRank (𝓞 (AdjoinRoot (X ^ 2 - C (3 : ℚ)))) ≠
      (ramifiedPrimes (AdjoinRoot (X ^ 2 - C (3 : ℚ)))).ncard - 1 := by
  obtain ⟨θ, hmin, hgen⟩ :=
    EpsilonEridani.NumberField.exists_minpoly_eq_X_sq_sub_three_and_adjoin_eq_top
  exact twoRank_ne_ncard_ramifiedPrimes_sub_one_of_minpoly_eq_X_sq_sub_three hmin hgen

/-- **Worked example.** The concrete number field `AdjoinRoot (X² - 3)`, modelling `ℚ(√3)`, has
narrow class number `2`, while its class number is `1`
(`EpsilonEridani.NumberField.classNumber_adjoinRoot_sqrt_three_eq_one`). -/
@[simp]
theorem card_narrowClassGroup_adjoinRoot_sqrt_three_eq_two :
    @Fintype.card (NumberField.NarrowClassGroup (AdjoinRoot (X ^ 2 - C (3 : ℚ))))
      (Fintype.ofFinite _) = 2 := by
  obtain ⟨θ, hmin, hgen⟩ :=
    EpsilonEridani.NumberField.exists_minpoly_eq_X_sq_sub_three_and_adjoin_eq_top
  rw [← @Nat.card_eq_fintype_card _ (Fintype.ofFinite _)]
  exact natCard_narrowClassGroup_eq_two_of_minpoly_eq_X_sq_sub_three hmin hgen

end EpsilonEridani.Multiquadratic
