/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/

module

public import EpsilonEridani.Algebra.Lie.Orthogonal.TypeD.Serre.PositiveSimpleRootSpan
public import EpsilonEridani.RepresentationTheory.Spin.Polarization.TypeD.ForkWeights

/-!
# The positive simple-root span in type D

This file applies the Lie subalgebra generated by the simple positive root vectors to the two
standard half-spin vectors. Their annihilation by this span is the generator-level input for
showing that they are highest-weight vectors once the span is identified with the positive
nilradical of a compatible Borel subalgebra.
-/

open CliffordAlgebra
open EpsilonEridani

public section

namespace EpsilonEridani.SpinPolarizationData

attribute [local instance 100] LieRing.ofAssociativeRing

variable {V : Type*} [AddCommGroup V] [Module ℚ V] {Q : QuadraticForm ℚ V}
  (P : SpinPolarizationData Q) {n : ℕ} (b : Module.Basis (Fin n) ℚ P.W)

/-- For the transported type-`D` spin representation, annihilation by every positive simple
generator implies annihilation by their Lie span. -/
theorem typeDSpinSerreRepresentation_positiveSimpleRootLieSpan_le_lieAnnihilator
    (hn : 4 ≤ n) {v : ExteriorAlgebra ℚ P.W}
    (hv : ∀ i : Fin n,
      P.typeDSpinSerreRepresentation b hn
          (EpsilonEridani.serreE ℚ (CartanMatrix.D n) i) v = 0) :
    letI : LieRingModule (Matrix.ToLieAlgebra ℚ (CartanMatrix.D n))
        (ExteriorAlgebra ℚ P.W) :=
      LieRingModule.compLieHom _ (P.typeDSpinSerreRepresentation b hn)
    letI : LieModule ℚ (Matrix.ToLieAlgebra ℚ (CartanMatrix.D n))
        (ExteriorAlgebra ℚ P.W) :=
      LieModule.compLieHom _ (P.typeDSpinSerreRepresentation b hn)
    EpsilonEridani.TypeDStd.positiveSimpleRootLieSpan n ≤
      EpsilonEridani.lieAnnihilator ℚ _ v := by
  let _ : LieRingModule (Matrix.ToLieAlgebra ℚ (CartanMatrix.D n))
      (ExteriorAlgebra ℚ P.W) :=
    LieRingModule.compLieHom _ (P.typeDSpinSerreRepresentation b hn)
  let _ : LieModule ℚ (Matrix.ToLieAlgebra ℚ (CartanMatrix.D n))
      (ExteriorAlgebra ℚ P.W) :=
    LieModule.compLieHom _ (P.typeDSpinSerreRepresentation b hn)
  apply EpsilonEridani.TypeDStd.positiveSimpleRootLieSpan_le_lieAnnihilator n v
  intro i
  exact by simpa [LieRingModule.compLieHom_apply] using hv i

/-- The all-coordinate exterior-basis vector is annihilated by the positive simple-root Lie span
in the transported type-`D` spin representation. -/
theorem typeDSpinSerreRepresentation_positiveSimpleRootLieSpan_le_lieAnnihilator_univ
    (hn : 4 ≤ n) :
    letI : LieRingModule (Matrix.ToLieAlgebra ℚ (CartanMatrix.D n))
        (ExteriorAlgebra ℚ P.W) :=
      LieRingModule.compLieHom _ (P.typeDSpinSerreRepresentation b hn)
    letI : LieModule ℚ (Matrix.ToLieAlgebra ℚ (CartanMatrix.D n))
        (ExteriorAlgebra ℚ P.W) :=
      LieModule.compLieHom _ (P.typeDSpinSerreRepresentation b hn)
    EpsilonEridani.TypeDStd.positiveSimpleRootLieSpan n ≤
      EpsilonEridani.lieAnnihilator ℚ _
        (b.ExteriorAlgebra (Finset.univ : Finset (Fin n))) := by
  apply P.typeDSpinSerreRepresentation_positiveSimpleRootLieSpan_le_lieAnnihilator b hn
  intro i
  rw [P.typeDSpinSerreRepresentation_serreE b hn]
  rw [← P.typeDSpinRep_serreE_eq_spinAction b hn]
  exact P.typeDSpinRep_serreE_exteriorBasis_univ_eq_zero b hn i

/-- The exterior-basis vector obtained by erasing the final coordinate from the all-coordinate
vector is annihilated by the positive simple-root Lie span in the transported type-`D` spin
representation. -/
theorem typeDSpinSerreRepresentation_positiveSimpleRootLieSpan_le_lieAnnihilator_univ_erase_last
    (hn : 4 ≤ n) :
    letI : LieRingModule (Matrix.ToLieAlgebra ℚ (CartanMatrix.D n))
        (ExteriorAlgebra ℚ P.W) :=
      LieRingModule.compLieHom _ (P.typeDSpinSerreRepresentation b hn)
    letI : LieModule ℚ (Matrix.ToLieAlgebra ℚ (CartanMatrix.D n))
        (ExteriorAlgebra ℚ P.W) :=
      LieModule.compLieHom _ (P.typeDSpinSerreRepresentation b hn)
    EpsilonEridani.TypeDStd.positiveSimpleRootLieSpan n ≤
      EpsilonEridani.lieAnnihilator ℚ _
        (b.ExteriorAlgebra
          ((Finset.univ : Finset (Fin n)).erase (⟨n - 1, by omega⟩ : Fin n))) := by
  apply P.typeDSpinSerreRepresentation_positiveSimpleRootLieSpan_le_lieAnnihilator b hn
  intro i
  rw [P.typeDSpinSerreRepresentation_serreE b hn]
  rw [← P.typeDSpinRep_serreE_eq_spinAction b hn]
  exact P.typeDSpinRep_serreE_exteriorBasis_univ_erase_last_eq_zero b hn i

end EpsilonEridani.SpinPolarizationData
