/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.Algebra.Lie.UniversalEnveloping.Bialgebra
public import EpsilonEridani.Algebra.Lie.UniversalEnveloping.Kostant.Form
public import EpsilonEridani.Algebra.TensorProduct.Subring

/-!
# Comultiplication and counit of the Kostant integral form

Let `L` be a Lie algebra over `ℚ`, and let `kostantForm e h` be the subring of its universal
enveloping algebra generated by the divided powers of the designated root vectors `e` and the
generalized binomial coefficients of the designated Cartan vectors `h`. This file proves that the
rational bialgebra comultiplication and counit are integral on that form.

For the comultiplication, the integral target is represented inside the rational tensor square.
The canonical map

```text
kostantForm e h ⊗[ℤ] kostantForm e h → U(L) ⊗[ℚ] U(L)
```

sends a pure tensor to the pure tensor of its two underlying elements. It is injective because a
subring of a rational algebra is torsion-free, hence flat over `ℤ`; this is the general theorem
`Subring.tensorSquareMap_injective`. Its range is `kostantTensorForm e h`, so it gives the
equivalence `kostantTensorEquiv` between the integral tensor square and that range.

The coefficient-one coproduct formulas for divided powers and generalized binomial coefficients
show that the rational comultiplication of every element of the Kostant form lies in this range.
Transporting the range-valued restriction back through `kostantTensorEquiv` gives the canonical
integral coproduct `kostantFormComul : U_ℤ →ₐ[ℤ] U_ℤ ⊗[ℤ] U_ℤ`. Thus integrality now means an
actual algebra homomorphism, rather than only the existence of an integral tensor representative.

The counit has no such issue. It sends every positive generator to zero and hence the entire form
to the integer-cast subring of `ℚ`. The map `kostantFormCounit` is its canonical restriction to
`ℤ`, and `intCast_kostantFormCounit_apply` identifies it with the rational counit.

## Main definitions and results

* `EpsilonEridani.UniversalEnvelopingAlgebra.kostantTensorMap`: the canonical map from the integral
  tensor square to the rational tensor square.
* `EpsilonEridani.UniversalEnvelopingAlgebra.kostantTensorMap_injective`: the canonical tensor map is
  injective.
* `EpsilonEridani.UniversalEnvelopingAlgebra.kostantTensorForm`: the range of that map.
* `EpsilonEridani.UniversalEnvelopingAlgebra.kostantTensorEquiv`: the equivalence from the integral tensor
  square onto that range.
* `EpsilonEridani.UniversalEnvelopingAlgebra.comul_mem_kostantTensorForm`: the rational coproduct of an
  element of the Kostant form has an integral tensor representative.
* `EpsilonEridani.UniversalEnvelopingAlgebra.counit_mem_bot_of_mem_kostantForm`: the rational counit of an
  element of the Kostant form is an integer.
* `EpsilonEridani.UniversalEnvelopingAlgebra.kostantFormComul`: the canonical integral comultiplication.
* `EpsilonEridani.UniversalEnvelopingAlgebra.kostantFormComul_dividedPower` and
  `EpsilonEridani.UniversalEnvelopingAlgebra.kostantFormComul_ringChoose`: its formulas on the
  generators of the Kostant form.
* `EpsilonEridani.UniversalEnvelopingAlgebra.kostantFormCounit`: the counit of the Kostant form, valued
  in `ℤ`.

## References

The coproduct formulas and the resulting Hopf order are standard; see J. E. Humphreys,
*Introduction to Lie Algebras and Representation Theory*, §26, and J. C. Jantzen,
*Representations of Algebraic Groups*, II.1. This supplies the comultiplication and counit part of
the Kostant-form input to the Chevalley--Demazure construction in Layer 9 of
`EpsilonEridaniRoadmap/ReductiveGroups/README.md`.
-/

public section

open scoped TensorProduct

namespace EpsilonEridani.UniversalEnvelopingAlgebra

universe u v w

variable {L : Type u} [LieRing L] [LieAlgebra ℚ L]
variable {ι : Type v} {κ : Type w}

local notation "U" => _root_.UniversalEnvelopingAlgebra ℚ L

attribute [local instance] EpsilonEridani.moduleNNRat

/-! ## The integral tensor form -/

/-- The canonical map from the tensor square of a Kostant form over `ℤ` to the tensor square of
the ambient universal enveloping algebra over `ℚ`.

On pure tensors this is `x ⊗ y ↦ (x : U(L)) ⊗ (y : U(L))`. -/
noncomputable def kostantTensorMap (e : ι → L) (h : κ → L) :
    kostantForm e h ⊗[ℤ] kostantForm e h →ₐ[ℤ] U ⊗[ℚ] U :=
  Subring.tensorSquareMap ℚ (kostantForm e h)

/-- The canonical integral tensor map sends a pure tensor to the pure tensor of the underlying
elements in the rational tensor square. -/
@[simp]
theorem kostantTensorMap_tmul (e : ι → L) (h : κ → L) (x y : kostantForm e h) :
    kostantTensorMap e h (x ⊗ₜ[ℤ] y) = (x : U) ⊗ₜ[ℚ] (y : U) := by
  simp [kostantTensorMap]

/-- The integral tensor form inside the rational tensor square: the range of the canonical map
from `kostantForm e h ⊗[ℤ] kostantForm e h`.

This range is the codomain of the rational restriction; `kostantTensorEquiv` below identifies it
with the integral tensor square. -/
noncomputable def kostantTensorForm (e : ι → L) (h : κ → L) : Subring (U ⊗[ℚ] U) :=
  Subring.tensorSquareRange ℚ (kostantForm e h)

/-- Membership in the integral tensor form is equivalent to having an integral tensor
representative under the canonical tensor map. -/
@[simp]
theorem mem_kostantTensorForm_iff (e : ι → L) (h : κ → L) (z : U ⊗[ℚ] U) :
    z ∈ kostantTensorForm e h ↔
      ∃ t : kostantForm e h ⊗[ℤ] kostantForm e h, kostantTensorMap e h t = z := by
  simpa only [kostantTensorForm, kostantTensorMap] using
    Subring.mem_tensorSquareRange_iff ℚ (kostantForm e h) z

/-- A pure rational tensor whose two factors lie in the Kostant form belongs to the integral
tensor form. -/
theorem tmul_mem_kostantTensorForm (e : ι → L) (h : κ → L) {x y : U}
    (hx : x ∈ kostantForm e h) (hy : y ∈ kostantForm e h) :
    x ⊗ₜ[ℚ] y ∈ kostantTensorForm e h := by
  simpa only [kostantTensorForm] using
    Subring.tmul_mem_tensorSquareRange ℚ (kostantForm e h) hx hy

/-! ## Stability under comultiplication -/

private theorem mem_comulComap_iff (S : Subring (U ⊗[ℚ] U)) (a : U) :
    a ∈ S.comap (Bialgebra.comulAlgHom ℚ U).toRingHom ↔
      Coalgebra.comul (R := ℚ) a ∈ S := by
  simp only [Subring.mem_comap, AlgHom.toRingHom_eq_coe, RingHom.coe_coe,
    Bialgebra.comulAlgHom_apply]

/-- **The rational comultiplication is integral on the Kostant form.** Every coproduct of an
element of `kostantForm e h` lies in the range of its integral tensor square. -/
theorem comul_mem_kostantTensorForm (e : ι → L) (h : κ → L) {a : U}
    (ha : a ∈ kostantForm e h) :
    Coalgebra.comul (R := ℚ) a ∈ kostantTensorForm e h := by
  rw [← mem_comulComap_iff]
  exact (kostantForm_le_iff e h
    ((kostantTensorForm e h).comap (Bialgebra.comulAlgHom ℚ U).toRingHom)).mpr
      ⟨fun i n => by
        rw [mem_comulComap_iff, comul_ι_dividedPower]
        exact sum_mem fun ij _ =>
          tmul_mem_kostantTensorForm e h (dividedPower_mem_kostantForm e h i ij.1)
            (dividedPower_mem_kostantForm e h i ij.2),
      fun j n => by
        rw [mem_comulComap_iff, comul_ι_choose]
        exact sum_mem fun ij _ =>
          tmul_mem_kostantTensorForm e h (ringChoose_mem_kostantForm e h j ij.1)
            (ringChoose_mem_kostantForm e h j ij.2)⟩ ha

-- The rational comultiplication restricted to the range of the integral tensor square.
private noncomputable def kostantFormComulRingHom (e : ι → L) (h : κ → L) :
    kostantForm e h →+* kostantTensorForm e h :=
  (Bialgebra.comulAlgHom ℚ U).toRingHom.restrict (kostantForm e h) (kostantTensorForm e h)
    fun _ ha => comul_mem_kostantTensorForm e h ha

private noncomputable def kostantFormComulRange (e : ι → L) (h : κ → L) :
    kostantForm e h →ₐ[ℤ] kostantTensorForm e h :=
  (kostantFormComulRingHom e h).toIntAlgHom

private theorem coe_kostantFormComulRange_apply (e : ι → L) (h : κ → L)
    (a : kostantForm e h) :
    (kostantFormComulRange e h a : U ⊗[ℚ] U) = Coalgebra.comul (R := ℚ) (a : U) := by
  rw [kostantFormComulRange, RingHom.toIntAlgHom_apply, kostantFormComulRingHom]
  simpa only [AlgHom.toRingHom_eq_coe, RingHom.coe_coe,
    Bialgebra.comulAlgHom_apply] using
    RingHom.coe_restrict_apply (Bialgebra.comulAlgHom ℚ U).toRingHom
      (kostantForm e h) (kostantTensorForm e h)
      (fun _ ha => comul_mem_kostantTensorForm e h ha) a

/-- The canonical map from the integral tensor square of a Kostant form to the rational tensor
square of its enveloping algebra is injective. -/
theorem kostantTensorMap_injective (e : ι → L) (h : κ → L) :
    Function.Injective (kostantTensorMap e h) := by
  simpa only [kostantTensorMap] using
    Subring.tensorSquareMap_injective (kostantForm e h)

/-- The canonical equivalence from the integral tensor square of a Kostant form onto its image in
the rational tensor square. -/
noncomputable def kostantTensorEquiv (e : ι → L) (h : κ → L) :
    kostantForm e h ⊗[ℤ] kostantForm e h ≃ₐ[ℤ] kostantTensorForm e h :=
  Subring.tensorSquareEquivRange (kostantForm e h)

/-- The tensor equivalence acts by the canonical map into the rational tensor square. -/
@[simp]
theorem coe_kostantTensorEquiv_apply (e : ι → L) (h : κ → L)
    (t : kostantForm e h ⊗[ℤ] kostantForm e h) :
    (kostantTensorEquiv e h t : U ⊗[ℚ] U) = kostantTensorMap e h t := by
  exact Subring.coe_tensorSquareEquivRange_apply (kostantForm e h) t

/-- The integral comultiplication of a Kostant form. It is the unique algebra homomorphism whose
composition with `kostantTensorMap` is the rational enveloping-algebra comultiplication. -/
noncomputable def kostantFormComul (e : ι → L) (h : κ → L) :
    kostantForm e h →ₐ[ℤ] kostantForm e h ⊗[ℤ] kostantForm e h :=
  (kostantTensorEquiv e h).symm.toAlgHom.comp (kostantFormComulRange e h)

/-- The integral comultiplication becomes the rational enveloping-algebra comultiplication under
the canonical tensor embedding. -/
@[simp]
theorem kostantTensorMap_kostantFormComul_apply (e : ι → L) (h : κ → L)
    (a : kostantForm e h) :
    kostantTensorMap e h (kostantFormComul e h a) =
      Coalgebra.comul (R := ℚ) (a : U) := by
  rw [kostantFormComul, AlgHom.comp_apply]
  calc
    kostantTensorMap e h
        ((kostantTensorEquiv e h).symm (kostantFormComulRange e h a)) =
        (kostantTensorEquiv e h
          ((kostantTensorEquiv e h).symm (kostantFormComulRange e h a)) : U ⊗[ℚ] U) :=
      (coe_kostantTensorEquiv_apply e h _).symm
    _ = (kostantFormComulRange e h a : U ⊗[ℚ] U) :=
      congrArg Subtype.val
        ((kostantTensorEquiv e h).apply_symm_apply (kostantFormComulRange e h a))
    _ = _ := coe_kostantFormComulRange_apply e h a

/-- The integral comultiplication is uniquely determined by its agreement with the rational
enveloping-algebra comultiplication. -/
theorem kostantFormComul_unique (e : ι → L) (h : κ → L)
    (f : kostantForm e h →ₐ[ℤ] kostantForm e h ⊗[ℤ] kostantForm e h)
    (hf : ∀ a, kostantTensorMap e h (f a) = Coalgebra.comul (R := ℚ) (a : U)) :
    f = kostantFormComul e h := by
  ext a
  apply kostantTensorMap_injective e h
  rw [hf, kostantTensorMap_kostantFormComul_apply]

/-- The integral coproduct of a divided power is the coefficient-one antidiagonal sum. -/
@[simp]
theorem kostantFormComul_dividedPower (e : ι → L) (h : κ → L) (i : ι) (n : ℕ) :
    kostantFormComul e h
        ⟨Associative.dividedPower n
            ((UniversalEnvelopingAlgebra.mkAlgHom ℚ L) ((TensorAlgebra.ι ℚ) (e i))),
          by simpa only [UniversalEnvelopingAlgebra.ι_apply] using
            dividedPower_mem_kostantForm e h i n⟩ =
      ∑ ij ∈ Finset.antidiagonal n,
        (⟨Associative.dividedPower ij.1 (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i)),
            dividedPower_mem_kostantForm e h i ij.1⟩ : kostantForm e h) ⊗ₜ[ℤ]
          (⟨Associative.dividedPower ij.2 (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i)),
            dividedPower_mem_kostantForm e h i ij.2⟩ : kostantForm e h) := by
  apply kostantTensorMap_injective e h
  rw [kostantTensorMap_kostantFormComul_apply]
  simp only [← UniversalEnvelopingAlgebra.ι_apply]
  rw [comul_ι_dividedPower]
  simp only [map_sum, kostantTensorMap_tmul]

/-- The integral coproduct of a generalized Cartan binomial is the coefficient-one antidiagonal
sum. -/
@[simp]
theorem kostantFormComul_ringChoose (e : ι → L) (h : κ → L) (j : κ) (n : ℕ) :
    kostantFormComul e h
        ⟨Ring.choose
            ((UniversalEnvelopingAlgebra.mkAlgHom ℚ L) ((TensorAlgebra.ι ℚ) (h j))) n,
          by simpa only [UniversalEnvelopingAlgebra.ι_apply] using
            ringChoose_mem_kostantForm e h j n⟩ =
      ∑ ij ∈ Finset.antidiagonal n,
        (⟨Ring.choose (_root_.UniversalEnvelopingAlgebra.ι ℚ (h j)) ij.1,
            ringChoose_mem_kostantForm e h j ij.1⟩ : kostantForm e h) ⊗ₜ[ℤ]
          (⟨Ring.choose (_root_.UniversalEnvelopingAlgebra.ι ℚ (h j)) ij.2,
            ringChoose_mem_kostantForm e h j ij.2⟩ : kostantForm e h) := by
  apply kostantTensorMap_injective e h
  rw [kostantTensorMap_kostantFormComul_apply]
  simp only [← UniversalEnvelopingAlgebra.ι_apply]
  rw [comul_ι_choose]
  simp only [map_sum, kostantTensorMap_tmul]

/-! ## The integral counit -/

private theorem mem_counitComap_iff (a : U) :
    a ∈ (⊥ : Subring ℚ).comap (Bialgebra.counitAlgHom ℚ U).toRingHom ↔
      Coalgebra.counit (R := ℚ) a ∈ (⊥ : Subring ℚ) := by
  simp only [Subring.mem_comap, AlgHom.toRingHom_eq_coe, RingHom.coe_coe,
    Bialgebra.counitAlgHom_apply]

/-- The rational counit of an element of the Kostant form belongs to the integer-cast subring of
`ℚ`. -/
theorem counit_mem_bot_of_mem_kostantForm (e : ι → L) (h : κ → L) {a : U}
    (ha : a ∈ kostantForm e h) : Coalgebra.counit (R := ℚ) a ∈ (⊥ : Subring ℚ) := by
  rw [← mem_counitComap_iff]
  exact (kostantForm_le_iff e h
    ((⊥ : Subring ℚ).comap (Bialgebra.counitAlgHom ℚ U).toRingHom)).mpr
      ⟨fun i n => by
        cases n with
        | zero =>
            rw [mem_counitComap_iff, Associative.dividedPower_zero, Bialgebra.counit_one]
            exact one_mem _
        | succ n =>
            rw [mem_counitComap_iff, counit_ι_dividedPower]
            exact zero_mem _,
      fun j n => by
        cases n with
        | zero =>
            rw [mem_counitComap_iff, Ring.choose_zero_right, Bialgebra.counit_one]
            exact one_mem _
        | succ n =>
            rw [mem_counitComap_iff, counit_ι_choose]
            exact zero_mem _⟩ ha

-- The rational counit restricted to the integer-cast subring of `ℚ`.
private noncomputable def kostantFormCounitRange (e : ι → L) (h : κ → L) :
    kostantForm e h →+* (⊥ : Subring ℚ) :=
  (Bialgebra.counitAlgHom ℚ U).toRingHom.restrict (kostantForm e h) (⊥ : Subring ℚ)
    fun _ ha => counit_mem_bot_of_mem_kostantForm e h ha

-- The canonical ring equivalence from `ℤ` to the integer-cast subring of `ℚ`.
-- For subrings of `ℚ`, `⊥` is definitionally the range of `Int.castRingHom ℚ`.
private noncomputable def intEquivBot : ℤ ≃+* (⊥ : Subring ℚ) :=
  RingEquiv.ofLeftInverse (f := Int.castRingHom ℚ) (g := Rat.num) fun n => Rat.num_intCast n

/-- The counit of the Kostant integral form, valued in `ℤ`.

It is the rational bialgebra counit restricted along the canonical identification of `ℤ` with the
integer-cast subring of `ℚ`. -/
noncomputable def kostantFormCounit (e : ι → L) (h : κ → L) : kostantForm e h →ₐ[ℤ] ℤ :=
  (intEquivBot.symm.toRingHom.comp (kostantFormCounitRange e h)).toIntAlgHom

private theorem kostantFormCounit_apply (e : ι → L) (h : κ → L) (a : kostantForm e h) :
    kostantFormCounit e h a = intEquivBot.symm (kostantFormCounitRange e h a) := by
  rw [kostantFormCounit, RingHom.toIntAlgHom_apply, RingHom.comp_apply]
  exact congr_fun (RingEquiv.coe_toRingHom intEquivBot.symm) _

/-- After casting to `ℚ`, the integral counit agrees with the rational bialgebra counit. -/
@[simp, norm_cast]
theorem intCast_kostantFormCounit_apply (e : ι → L) (h : κ → L) (a : kostantForm e h) :
    (kostantFormCounit e h a : ℚ) = Coalgebra.counit (R := ℚ) (a : U) := by
  calc
    (kostantFormCounit e h a : ℚ) = (intEquivBot (kostantFormCounit e h a) : ℚ) :=
      by simp [intEquivBot]
    _ = (intEquivBot (intEquivBot.symm (kostantFormCounitRange e h a)) : ℚ) := by
      rw [kostantFormCounit_apply]
    _ = (kostantFormCounitRange e h a : ℚ) := by rw [intEquivBot.apply_symm_apply]
    _ = Coalgebra.counit (R := ℚ) (a : U) := by
      rw [kostantFormCounitRange]
      simpa only [AlgHom.toRingHom_eq_coe, RingHom.coe_coe,
        Bialgebra.counitAlgHom_apply] using
        RingHom.coe_restrict_apply (Bialgebra.counitAlgHom ℚ U).toRingHom
          (kostantForm e h) (⊥ : Subring ℚ)
          (fun _ ha => counit_mem_bot_of_mem_kostantForm e h ha) a

end EpsilonEridani.UniversalEnvelopingAlgebra
