/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.Algebra.Lie.UniversalEnveloping.Kostant.Form

/-!
# Integral orbits of a Kostant form

Let `L` be a Lie algebra over `ℚ` and let `U_ℤ = kostantForm e h` be the Kostant integral form
generated by families `e` of root vectors and `h` of Cartan vectors. For a module `V` over
`U(L)` and a vector `v : V`, this file studies the integral orbit

```text
U_ℤ • v ⊆ V.
```

The orbit is stable under `U_ℤ`; in particular, it is preserved by the divided powers of the root
vectors and the binomial coefficients of the Cartan vectors. When `e` and `h` generate `L` as a
Lie algebra, its `ℚ`-span is the whole `U(L)`-submodule generated by `v`. For a cyclic module this
is all of `V`.

Finite generation over `ℤ` is not proved here. Thus the orbit is not yet asserted to be a lattice
in the sense of Humphreys §27; that requires the integral Poincaré--Birkhoff--Witt theorem. The
present stability and spanning results are the parts of the admissible-lattice construction that
are available without integral PBW.

The representation-oriented variant `orbitOfRep` starts from a subring `S`, an algebra
representation `ρ : A →ₐ[ℚ] End(V)`, and a set of generating vectors. It is the integral span of
all their images under `S`. This avoids manufacturing a global `A`-module instance when a
construction already carries its representation as an algebra homomorphism. Its specialization to
the Kostant form and a singleton agrees with `kostantOrbit`.

## Main definitions and results

* `EpsilonEridani.UniversalEnvelopingAlgebra.kostantOrbit`: the integral orbit `U_ℤ • v`.
* `EpsilonEridani.UniversalEnvelopingAlgebra.smul_mem_kostantOrbit`: stability under the integral form.
* `EpsilonEridani.UniversalEnvelopingAlgebra.dividedPower_smul_mem_kostantOrbit` and
  `EpsilonEridani.UniversalEnvelopingAlgebra.ringChoose_smul_mem_kostantOrbit`: stability under the two
  families of Kostant generators.
* `EpsilonEridani.UniversalEnvelopingAlgebra.span_kostantOrbit_eq_span_singleton`: under a
  Lie-generation hypothesis, the `ℚ`-span is the `U(L)`-submodule generated by `v`.
* `EpsilonEridani.UniversalEnvelopingAlgebra.span_kostantOrbit_eq_top`: for a cyclic module the orbit
  spans `V` over `ℚ`.
* `EpsilonEridani.UniversalEnvelopingAlgebra.orbitOfRep`: the integral orbit of a set through an algebra
  representation, with stability and spanning lemmas.

## References

* J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*, §26 and §27.
* J. C. Jantzen, *Representations of Algebraic Groups*, II.1.
* R. Steinberg, *Lectures on Chevalley Groups*, §2.
-/

public section

universe u v w

namespace EpsilonEridani.UniversalEnvelopingAlgebra

open Set

private theorem span_subring_smul_eq_span_singleton
    {A : Type u} [Ring A] [Algebra ℚ A] {V : Type v} [AddCommGroup V]
    [Module A V] [Module ℚ V] [IsScalarTower ℚ A V] (S : Subring A)
    (hspan : Submodule.span ℚ (S : Set A) = ⊤) (v : V) :
    Submodule.span ℚ ((Submodule.span S {v}).restrictScalars ℤ : Set V) =
      (Submodule.span A {v}).restrictScalars ℚ := by
  have horbit : ((Submodule.span S {v}).restrictScalars ℤ : Set V) =
      (LinearMap.toSpanSingleton A V v).restrictScalars ℚ '' (S : Set A) := by
    ext x
    rw [Set.mem_image, Submodule.coe_restrictScalars]
    simp only [SetLike.mem_coe]
    rw [Submodule.mem_span_singleton]
    simp only [LinearMap.restrictScalars_apply, LinearMap.toSpanSingleton_apply]
    constructor
    · rintro ⟨u, rfl⟩
      exact ⟨u, u.property, (Subring.smul_def u v).symm⟩
    · rintro ⟨u, hu, rfl⟩
      exact ⟨⟨u, hu⟩, Subring.smul_def ⟨u, hu⟩ v⟩
  rw [horbit, Submodule.span_image, hspan, Submodule.map_top,
    LinearMap.span_singleton_eq_range, LinearMap.range_restrictScalars]

variable {L : Type u} [LieRing L] [LieAlgebra ℚ L]
variable {ι : Type w} {κ : Type*}

attribute [local instance] EpsilonEridani.moduleNNRat

local notation "U" => _root_.UniversalEnvelopingAlgebra ℚ L

section Orbit

variable {V : Type v} [AddCommGroup V]
variable [Module (_root_.UniversalEnvelopingAlgebra ℚ L) V]
variable {e : ι → L} {h : κ → L} {v : V}

/-- The integral orbit generated by `v` under the Kostant form attached to `e` and `h`.

This is the span of `v` over the subring `kostantForm e h`, regarded as a `ℤ`-submodule of `V`.
No finite-generation or lattice property is asserted. -/
def kostantOrbit (e : ι → L) (h : κ → L) (v : V) : Submodule ℤ V :=
  (Submodule.span (kostantForm e h) {v}).restrictScalars ℤ

/-- The Kostant orbit consists exactly of the vectors `u • v` for `u` in the integral form. -/
@[simp]
theorem mem_kostantOrbit_iff {x : V} :
    x ∈ kostantOrbit e h v ↔ ∃ u ∈ kostantForm e h, u • v = x := by
  unfold kostantOrbit
  rw [Submodule.restrictScalars_mem, Submodule.mem_span_singleton]
  constructor
  · rintro ⟨u, rfl⟩
    exact ⟨u, u.property, (Subring.smul_def u v).symm⟩
  · rintro ⟨u, hu, rfl⟩
    exact ⟨⟨u, hu⟩, Subring.smul_def ⟨u, hu⟩ v⟩

/-- The generating vector belongs to its Kostant orbit. -/
theorem mem_kostantOrbit_self : v ∈ kostantOrbit e h v :=
  mem_kostantOrbit_iff.2 ⟨1, (kostantForm e h).one_mem, one_smul U v⟩

/-- The Kostant orbit is stable under the integral form. -/
theorem smul_mem_kostantOrbit {u : U} (hu : u ∈ kostantForm e h) {x : V}
    (hx : x ∈ kostantOrbit e h v) : u • x ∈ kostantOrbit e h v := by
  unfold kostantOrbit at hx ⊢
  rw [Submodule.restrictScalars_mem] at hx ⊢
  rw [← Subring.smul_def (⟨u, hu⟩ : kostantForm e h) x]
  exact Submodule.smul_mem _ ⟨u, hu⟩ hx

/-- The divided powers of the root vectors preserve the Kostant orbit. This is the stability
statement needed before locally finite root-vector exponentials can be defined. -/
theorem dividedPower_smul_mem_kostantOrbit (i : ι) (n : ℕ) {x : V}
    (hx : x ∈ kostantOrbit e h v) :
    Associative.dividedPower n (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i)) • x ∈
      kostantOrbit e h v :=
  smul_mem_kostantOrbit (dividedPower_mem_kostantForm e h i n) hx

/-- The binomial coefficients of the Cartan vectors preserve the Kostant orbit. -/
theorem ringChoose_smul_mem_kostantOrbit (i : κ) (n : ℕ) {x : V}
    (hx : x ∈ kostantOrbit e h v) :
    Ring.choose (_root_.UniversalEnvelopingAlgebra.ι ℚ (h i)) n • x ∈ kostantOrbit e h v :=
  smul_mem_kostantOrbit (ringChoose_mem_kostantForm e h i n) hx

/-- The Kostant orbit of the identity in the regular module is the integral form itself. -/
@[simp]
theorem kostantOrbit_one (e : ι → L) (h : κ → L) :
    kostantOrbit e h (1 : U) = (kostantForm e h).toAddSubgroup.toIntSubmodule := by
  refine SetLike.ext' ?_
  rw [AddSubgroup.coe_toIntSubmodule]
  ext x
  simp [mem_kostantOrbit_iff, eq_comm]

section Rational

variable [Module ℚ V]
variable [IsScalarTower ℚ (_root_.UniversalEnvelopingAlgebra ℚ L) V]

/-- If the supplied root and Cartan vectors generate `L` as a Lie algebra, the `ℚ`-span of their
Kostant orbit is the `U(L)`-submodule generated by `v`. -/
theorem span_kostantOrbit_eq_span_singleton (e : ι → L) (h : κ → L)
    (hgen : LieSubalgebra.lieSpan ℚ L (range e ∪ range h) = ⊤) (v : V) :
    Submodule.span ℚ (kostantOrbit e h v : Set V) =
      (Submodule.span U {v}).restrictScalars ℚ :=
  span_subring_smul_eq_span_singleton (kostantForm e h) (span_kostantForm_eq_top e h hgen) v

/-- If `v` generates `V` over `U(L)`, the Kostant orbit spans the whole module over `ℚ`. -/
theorem span_kostantOrbit_eq_top (e : ι → L) (h : κ → L)
    (hgen : LieSubalgebra.lieSpan ℚ L (range e ∪ range h) = ⊤) (v : V)
    (hv : Submodule.span U {v} = ⊤) :
    Submodule.span ℚ (kostantOrbit e h v : Set V) = ⊤ := by
  rw [span_kostantOrbit_eq_span_singleton e h hgen v, hv]
  exact Submodule.restrictScalars_top ℚ U V

end Rational

end Orbit

section OrbitOfRep

variable {A : Type u} [Ring A] [Algebra ℚ A]
variable {V : Type v} [AddCommGroup V] [Module ℚ V]
variable (S : Subring A) (ρ : A →ₐ[ℚ] Module.End ℚ V) (X : Set V)

/-- The integral orbit of a set through an algebra representation: the `ℤ`-span of all `ρ a x`
with `a ∈ S` and `x ∈ X`. -/
def orbitOfRep : Submodule ℤ V :=
  Submodule.span ℤ {v | ∃ a ∈ S, ∃ x ∈ X, ρ a x = v}

/-- The represented orbit is the integral span of the images of its generators. -/
theorem orbitOfRep_def :
    orbitOfRep S ρ X = Submodule.span ℤ {v | ∃ a ∈ S, ∃ x ∈ X, ρ a x = v} := (rfl)

/-- A represented translate of a generator belongs to its integral orbit. -/
theorem apply_mem_orbitOfRep {a : A} (ha : a ∈ S) {x : V} (hx : x ∈ X) :
    ρ a x ∈ orbitOfRep S ρ X :=
  Submodule.subset_span ⟨a, ha, x, hx, rfl⟩

/-- The generators themselves belong to their integral orbit. -/
theorem subset_orbitOfRep : X ⊆ (orbitOfRep S ρ X : Set V) := by
  intro x hx
  simpa only [SetLike.mem_coe, map_one, Module.End.one_apply] using
    apply_mem_orbitOfRep S ρ X S.one_mem hx

/-- The elimination principle for a represented integral orbit. -/
theorem orbitOfRep_le_iff (N : Submodule ℤ V) :
    orbitOfRep S ρ X ≤ N ↔ ∀ a ∈ S, ∀ x ∈ X, ρ a x ∈ N := by
  rw [orbitOfRep, Submodule.span_le]
  constructor
  · intro hle a ha x hx
    exact hle ⟨a, ha, x, hx, rfl⟩
  · rintro hle - ⟨a, ha, x, hx, rfl⟩
    exact hle a ha x hx

/-- The represented integral orbit is stable under the subring. -/
theorem apply_mem_orbitOfRep_of_mem {a : A} (ha : a ∈ S) {v : V}
    (hv : v ∈ orbitOfRep S ρ X) : ρ a v ∈ orbitOfRep S ρ X := by
  induction hv using Submodule.span_induction with
  | mem w hw =>
      obtain ⟨b, hb, x, hx, rfl⟩ := hw
      simpa only [map_mul, Module.End.mul_apply] using
        apply_mem_orbitOfRep S ρ X (S.mul_mem ha hb) hx
  | zero => rw [map_zero]; exact zero_mem _
  | add a b _ _ ha hb => rw [map_add]; exact add_mem ha hb
  | smul c a _ ha => rw [map_zsmul]; exact Submodule.smul_mem _ c ha

/-- If `S` spans `A` over `ℚ`, the rational span of the represented integral orbit is the span of
all translates through the full algebra. -/
theorem span_orbitOfRep_eq_span (hS : Submodule.span ℚ (S : Set A) = ⊤) :
    Submodule.span ℚ (orbitOfRep S ρ X : Set V) =
      Submodule.span ℚ {v | ∃ a : A, ∃ x ∈ X, ρ a x = v} := by
  apply le_antisymm
  · rw [Submodule.span_le]
    intro v hv
    induction hv using Submodule.span_induction with
    | mem w hw =>
        obtain ⟨a, -, x, hx, rfl⟩ := hw
        exact Submodule.subset_span ⟨a, x, hx, rfl⟩
    | zero => exact zero_mem _
    | add a b _ _ ha hb => exact add_mem ha hb
    | smul c a _ ha =>
        exact AddSubgroup.zsmul_mem
          (Submodule.span ℚ {v | ∃ a : A, ∃ x ∈ X, ρ a x = v}).toAddSubgroup ha c
  · rw [Submodule.span_le]
    rintro - ⟨a, x, hx, rfl⟩
    have ha : a ∈ Submodule.span ℚ (S : Set A) := by rw [hS]; trivial
    induction ha using Submodule.span_induction with
    | mem b hb =>
        exact Submodule.subset_span (apply_mem_orbitOfRep S ρ X hb hx)
    | zero =>
        rw [map_zero, LinearMap.zero_apply]
        exact zero_mem _
    | add a b _ _ ha hb =>
        rw [map_add, LinearMap.add_apply]
        exact add_mem ha hb
    | smul q a _ ha =>
        rw [map_smul, LinearMap.smul_apply]
        exact Submodule.smul_mem (Submodule.span ℚ (orbitOfRep S ρ X : Set V)) q ha

/-- If the supplied vectors span over `ℚ`, their represented integral orbit is full. -/
theorem span_orbitOfRep_eq_top (hX : Submodule.span ℚ X = ⊤) :
    Submodule.span ℚ (orbitOfRep S ρ X : Set V) = ⊤ := by
  apply top_unique
  rw [← hX]
  exact Submodule.span_mono (subset_orbitOfRep S ρ X)

end OrbitOfRep

section Comparison

variable {V : Type v} [AddCommGroup V]
variable [Module (_root_.UniversalEnvelopingAlgebra ℚ L) V] [Module ℚ V]
variable [IsScalarTower ℚ (_root_.UniversalEnvelopingAlgebra ℚ L) V]

/-- The represented orbit of a singleton under a Kostant form agrees with `kostantOrbit`. -/
theorem orbitOfRep_kostantForm_singleton_eq_kostantOrbit
    (e : ι → L) (h : κ → L) (v : V) :
    orbitOfRep (kostantForm e h) (Algebra.lsmul ℚ ℚ V) {v} = kostantOrbit e h v := by
  apply le_antisymm
  · rw [orbitOfRep_le_iff]
    intro u hu x hx
    rw [Set.mem_singleton_iff.mp hx]
    exact mem_kostantOrbit_iff.2 ⟨u, hu, Algebra.lsmul_apply ℚ ℚ V u v⟩
  · intro x hx
    obtain ⟨u, hu, rfl⟩ := mem_kostantOrbit_iff.1 hx
    simpa only [Algebra.lsmul_apply] using
      apply_mem_orbitOfRep (kostantForm e h) (Algebra.lsmul ℚ ℚ V) {v} hu
        (Set.mem_singleton v)

end Comparison

end EpsilonEridani.UniversalEnvelopingAlgebra
