/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.GroupTheory.Torsion
public import EpsilonEridani.Topology.Algebra.ContinuousMulEquiv
public import EpsilonEridani.Topology.Algebra.Group.Profinite.Demushkin.D0
public import EpsilonEridani.Topology.Algebra.Group.Profinite.ProP.PadicInt
public import EpsilonEridani.Topology.Algebra.Group.Profinite.ProP.Product
public import EpsilonEridani.Topology.Algebra.Group.TopologicalAbelianization.Lift

/-!
# The abelianization of the dyadic Demushkin group `D₀`

The topological abelianization of `D₀ = ⟨A, S, Y ∣ A²S⁴(S,Y)⟩` is `ℤ₂ × ℤ₂ × ℤ/2`. Abelianizing
kills the commutator `(S, Y)`, so the relator becomes `2A + 4S`, and `D₀^{ab}` is the abelian
pro-`2` group `ℤ₂³ ⧸ ⟨(2, 4, 0)⟩`; in the basis `S, Y, AS²` of `ℤ₂³` the relation reads
`2 · AS² = 0`, which exhibits the quotient as `ℤ₂ × ℤ₂ × ℤ/2` with the classes of `S` and `Y`
spanning the free part and the class of `AS²` generating the torsion.

The isomorphism is built from the universal properties on both sides. The homomorphism
`D₀ → ℤ₂ × ℤ₂ × ℤ/2` with `A ↦ (-2, 0, 1)`, `S ↦ (1, 0, 0)`, `Y ↦ (0, 1, 0)` kills the relator and
factors through the abelianization; the inverse sends `(u, v, ε)` to `S^u Y^v (AS²)^ε`, using the
`2`-adic powers of the abelian pro-`2` group `D₀^{ab}`. Consequently the torsion subgroup of
`D₀^{ab}` has exactly two elements: this is the invariant `q(D₀) = 2` of the Demushkin
classification, computed from the presentation alone.

## Main definitions

* `EpsilonEridani.d0AbelianizationHom`: the continuous homomorphism `D₀ → ℤ₂ × ℤ₂ × ℤ/2` with
  `A ↦ (-2, 0, 1)`, `S ↦ (1, 0, 0)`, `Y ↦ (0, 1, 0)`.
* `EpsilonEridani.d0AbelianizationEquiv`: the topological isomorphism `D₀^{ab} ≃ₜ* ℤ₂ × ℤ₂ × ℤ/2`.
* `EpsilonEridani.d0AbelianizationTorsionGenerator`: the class of `AS²` in `D₀^{ab}`, of order two.

## Main results

* `EpsilonEridani.d0AbelianizationEquiv_mk`, `EpsilonEridani.d0AbelianizationEquiv_symm_ofAdd`: the
  isomorphism is induced by `d0AbelianizationHom`, and its inverse is `(u, v, ε) ↦ S^u Y^v (AS²)^ε`.
* `EpsilonEridani.torsion_topologicalAbelianization_demushkinD0`,
  `EpsilonEridani.nat_card_torsion_topologicalAbelianization_demushkinD0`: the torsion subgroup of
  `D₀^{ab}` is generated by the class of `AS²` and has two elements.

## References

* J. P. Labute, *Classification of Demushkin groups*, Canad. J. Math. 19 (1967), 106–132, p. 106.
* J. Neukirch, A. Schmidt, K. Wingberg, *Cohomology of Number Fields*, 2nd ed., Chapter III, §9.
-/

public section

namespace EpsilonEridani

open CommGroup (torsion)
open Multiplicative

/-- The abelian group `ℤ₂ × ℤ₂ × ℤ/2`, written multiplicatively, is pro-`2`. -/
theorem isProP_multiplicative_padicInt_prod_padicInt_prod_zmod :
    IsProP 2 (Multiplicative ((ℤ_[2] × ℤ_[2]) × ZMod 2)) :=
  ((((isProP_multiplicative_padicInt 2).prod (isProP_multiplicative_padicInt 2)).of_equiv
    (ContinuousMulEquiv.prodMultiplicative ℤ_[2] ℤ_[2]).symm).prod
      (isProP_multiplicative_zmod_pow 2 1)).of_equiv
    (ContinuousMulEquiv.prodMultiplicative (ℤ_[2] × ℤ_[2]) (ZMod 2)).symm

/-- The continuous homomorphism `D₀ → ℤ₂ × ℤ₂ × ℤ/2` with `A ↦ (-2, 0, 1)`, `S ↦ (1, 0, 0)` and
`Y ↦ (0, 1, 0)`. It kills the relator `A²S⁴(S,Y)`, because the commutator dies in an abelian
group and `2 · (-2, 0, 1) + 4 · (1, 0, 0) = (0, 0, 2) = 0`. -/
noncomputable def d0AbelianizationHom :
    demushkinD0 →ₜ* Multiplicative ((ℤ_[2] × ℤ_[2]) × ZMod 2) :=
  d0Lift isProP_multiplicative_padicInt_prod_padicInt_prod_zmod (ofAdd ((-2, 0), 1))
    (ofAdd ((1, 0), 0)) (ofAdd ((0, 1), 0)) (by
      simp only [← ofAdd_nsmul, ← ofAdd_neg, ← ofAdd_add, ofAdd_eq_one, Prod.smul_mk,
        Prod.neg_mk, Prod.mk_add_mk, Prod.mk_eq_zero, nsmul_eq_mul]
      refine ⟨⟨by ring, by ring⟩, ?_⟩
      decide)

/-- `d0AbelianizationHom` sends `A` to `(-2, 0, 1)`. -/
@[simp]
theorem d0AbelianizationHom_d0A : d0AbelianizationHom d0A = ofAdd ((-2, 0), 1) :=
  d0Lift_d0A _ _ _ _ _

/-- `d0AbelianizationHom` sends `S` to `(1, 0, 0)`. -/
@[simp]
theorem d0AbelianizationHom_d0S : d0AbelianizationHom d0S = ofAdd ((1, 0), 0) :=
  d0Lift_d0S _ _ _ _ _

/-- `d0AbelianizationHom` sends `Y` to `(0, 1, 0)`. -/
@[simp]
theorem d0AbelianizationHom_d0Y : d0AbelianizationHom d0Y = ofAdd ((0, 1), 0) :=
  d0Lift_d0Y _ _ _ _ _

/-- `d0AbelianizationHom` sends `AS²` to `(0, 0, 1)`: the class of `AS²` is the torsion
coordinate of the abelianization. -/
@[simp]
theorem d0AbelianizationHom_d0A_mul_d0S_sq :
    d0AbelianizationHom (d0A * d0S ^ 2) = ofAdd ((0, 0), 1) := by
  simp only [map_mul, map_pow, d0AbelianizationHom_d0A, d0AbelianizationHom_d0S, ← ofAdd_nsmul,
    ← ofAdd_add]
  congr 1
  simp only [Prod.smul_mk, Prod.mk_add_mk, nsmul_eq_mul, Prod.mk.injEq]
  refine ⟨⟨by ring, by ring⟩, ?_⟩
  decide

/-- The topological abelianization of `D₀` is pro-`2`. -/
theorem isProP_topologicalAbelianization_demushkinD0 :
    IsProP 2 (TopologicalAbelianization demushkinD0) :=
  isProP_demushkinD0.quotient _

/-- The class of `AS²` in `D₀^{ab}`, the element of order `2` corresponding to `(0, 0, 1)` under
`d0AbelianizationEquiv`: `S`, `Y`, `AS²` is the basis of `ℤ₂³` in which the abelianized relator
reads `2 · AS²`. -/
noncomputable def d0AbelianizationTorsionGenerator : TopologicalAbelianization demushkinD0 :=
  ((d0A * d0S ^ 2 : demushkinD0) : TopologicalAbelianization demushkinD0)

/-- The class of `AS²` in `D₀^{ab}` squares to `1`: `(AS²)² = A²S⁴ = (S,Y)⁻¹ = 1`. -/
@[simp]
theorem d0AbelianizationTorsionGenerator_sq : d0AbelianizationTorsionGenerator ^ 2 = 1 := by
  have h := congrArg (QuotientGroup.mk : demushkinD0 → TopologicalAbelianization demushkinD0)
    d0_relation
  simp only [QuotientGroup.mk_mul, QuotientGroup.mk_pow, QuotientGroup.mk_inv,
    QuotientGroup.mk_one, mul_assoc, inv_mul_cancel_comm_assoc, inv_mul_cancel, mul_one] at h
  rw [d0AbelianizationTorsionGenerator, QuotientGroup.mk_mul, QuotientGroup.mk_pow, mul_pow,
    ← pow_mul]
  exact h

section Inverse

/-- The order-two homomorphism `ℤ/2 → D₀^{ab}` sending the generator to the class of `AS²`. -/
private noncomputable def d0AbelianizationTorsionHom :
    Multiplicative (ZMod 2) →* TopologicalAbelianization demushkinD0 :=
  AddMonoidHom.toMultiplicativeLeft (ZMod.lift 2 ⟨zmultiplesHom _
    (Additive.ofMul d0AbelianizationTorsionGenerator), by
      rw [zmultiplesHom_apply, ← ofMul_zpow, ofMul_eq_zero, zpow_natCast]
      exact d0AbelianizationTorsionGenerator_sq⟩)

private theorem d0AbelianizationTorsionHom_ofAdd_one :
    d0AbelianizationTorsionHom (ofAdd 1) = d0AbelianizationTorsionGenerator := by
  have h1 : (1 : ZMod 2) = ((1 : ℤ) : ZMod 2) := Int.cast_one.symm
  rw [d0AbelianizationTorsionHom, AddMonoidHom.toMultiplicativeLeft_apply_apply, toAdd_ofAdd, h1,
    ZMod.lift_coe, zmultiplesHom_apply, one_zsmul, toMul_ofMul]

/-- The inverse `ℤ₂ × ℤ₂ × ℤ/2 → D₀^{ab}`, `(u, v, ε) ↦ S^u Y^v (AS²)^ε`, with `2`-adic powers in
the abelian pro-`2` group `D₀^{ab}`. -/
private noncomputable def d0AbelianizationInv :
    Multiplicative ((ℤ_[2] × ℤ_[2]) × ZMod 2) →ₜ* TopologicalAbelianization demushkinD0 where
  toFun t := isProP_topologicalAbelianization_demushkinD0.padicPow d0S t.toAdd.1.1 *
    isProP_topologicalAbelianization_demushkinD0.padicPow d0Y t.toAdd.1.2 *
    d0AbelianizationTorsionHom (ofAdd t.toAdd.2)
  map_one' := by simp
  map_mul' s t := by
    simp only [toAdd_mul, Prod.fst_add, Prod.snd_add, IsProP.padicPow_add, ofAdd_add, map_mul]
    ac_rfl
  continuous_toFun := by
    refine ((isProP_topologicalAbelianization_demushkinD0.continuous_padicPow.comp
      ((continuous_fst.comp (continuous_fst.comp continuous_toAdd)).prodMk continuous_const)).mul
      (isProP_topologicalAbelianization_demushkinD0.continuous_padicPow.comp
        ((continuous_snd.comp (continuous_fst.comp continuous_toAdd)).prodMk
          continuous_const))).mul ?_
    exact continuous_of_discreteTopology.comp (continuous_snd.comp continuous_toAdd)

private theorem d0AbelianizationInv_ofAdd (u v : ℤ_[2]) (ε : ZMod 2) :
    d0AbelianizationInv (ofAdd ((u, v), ε)) =
      isProP_topologicalAbelianization_demushkinD0.padicPow d0S u *
        isProP_topologicalAbelianization_demushkinD0.padicPow d0Y v *
        d0AbelianizationTorsionHom (ofAdd ε) :=
  (rfl)

private theorem lift_d0AbelianizationInv (t : Multiplicative ((ℤ_[2] × ℤ_[2]) × ZMod 2)) :
    TopologicalAbelianization.lift d0AbelianizationHom (d0AbelianizationInv t) = t := by
  rw [← ofAdd_toAdd t]
  obtain ⟨⟨u, v⟩, ε⟩ := t.toAdd
  -- The `2`-adic powers of `(1, 0, 0)` and `(0, 1, 0)` in the target are `(u, 0, 0)` and
  -- `(0, v, 0)`: the exponent acts through the coordinate inclusions.
  have h1 := isProP_multiplicative_padicInt_prod_padicInt_prod_zmod.padicPow_ofAdd_apply_one
    ((AddMonoidHom.inl (ℤ_[2] × ℤ_[2]) (ZMod 2)).comp (AddMonoidHom.inl ℤ_[2] ℤ_[2]))
    ((continuous_id.prodMk continuous_const).prodMk continuous_const) u
  have h2 := isProP_multiplicative_padicInt_prod_padicInt_prod_zmod.padicPow_ofAdd_apply_one
    ((AddMonoidHom.inl (ℤ_[2] × ℤ_[2]) (ZMod 2)).comp (AddMonoidHom.inr ℤ_[2] ℤ_[2]))
    ((continuous_const.prodMk continuous_id).prodMk continuous_const) v
  simp only [AddMonoidHom.coe_comp, Function.comp_apply, AddMonoidHom.inl_apply,
    AddMonoidHom.inr_apply] at h1 h2
  -- The lift commutes with the `2`-adic powers.
  have hS := DFunLike.congr_fun (isProP_topologicalAbelianization_demushkinD0.comp_padicPowHom
    isProP_multiplicative_padicInt_prod_padicInt_prod_zmod
    (TopologicalAbelianization.lift d0AbelianizationHom)
    (d0S : TopologicalAbelianization demushkinD0)) (ofAdd u)
  have hY := DFunLike.congr_fun (isProP_topologicalAbelianization_demushkinD0.comp_padicPowHom
    isProP_multiplicative_padicInt_prod_padicInt_prod_zmod
    (TopologicalAbelianization.lift d0AbelianizationHom)
    (d0Y : TopologicalAbelianization demushkinD0)) (ofAdd v)
  simp only [ContinuousMonoidHom.coe_comp, Function.comp_apply, IsProP.padicPowHom_apply,
    toAdd_ofAdd, TopologicalAbelianization.lift_mk, d0AbelianizationHom_d0S,
    d0AbelianizationHom_d0Y, h1, h2] at hS hY
  -- The torsion generator `AS²` goes to `(0, 0, 1)`.
  have hε : TopologicalAbelianization.lift d0AbelianizationHom
      (d0AbelianizationTorsionHom (ofAdd ε)) = ofAdd ((0, 0), ε) := by
    obtain rfl | rfl := (by decide : ∀ x : ZMod 2, x = 0 ∨ x = 1) ε
    · simp [Prod.mk_zero_zero]
    · rw [d0AbelianizationTorsionHom_ofAdd_one, d0AbelianizationTorsionGenerator,
        TopologicalAbelianization.lift_mk, d0AbelianizationHom_d0A_mul_d0S_sq]
  rw [d0AbelianizationInv_ofAdd, map_mul, map_mul, hS, hY, hε, ← ofAdd_add, ← ofAdd_add]
  simp

private theorem d0AbelianizationInv_comp_lift :
    d0AbelianizationInv.comp (TopologicalAbelianization.lift d0AbelianizationHom) =
      ContinuousMonoidHom.id _ := by
  refine TopologicalAbelianization.hom_ext (DFunLike.congr_fun (d0_hom_ext ?_ ?_ ?_ :
    (d0AbelianizationInv.comp (TopologicalAbelianization.lift d0AbelianizationHom)).comp
      (ContinuousMonoidHom.quotientMk _) = ContinuousMonoidHom.quotientMk _)) <;>
    simp only [ContinuousMonoidHom.coe_comp, Function.comp_apply,
      ContinuousMonoidHom.quotientMk_apply, TopologicalAbelianization.lift_mk,
      d0AbelianizationHom_d0A, d0AbelianizationHom_d0S, d0AbelianizationHom_d0Y,
      d0AbelianizationInv_ofAdd]
  · rw [d0AbelianizationTorsionHom_ofAdd_one, d0AbelianizationTorsionGenerator,
      QuotientGroup.mk_mul, QuotientGroup.mk_pow]
    simp only [IsProP.padicPow_neg, IsProP.padicPow_ofNat, IsProP.padicPow_zero, mul_one]
    rw [mul_comm, mul_assoc, mul_inv_cancel, mul_one]
  · simp
  · simp

end Inverse

/-- **The abelianization of `D₀`.** The topological abelianization of
`D₀ = ⟨A, S, Y ∣ A²S⁴(S,Y)⟩` is `ℤ₂ × ℤ₂ × ℤ/2`, by the isomorphism induced by
`A ↦ (-2, 0, 1)`, `S ↦ (1, 0, 0)`, `Y ↦ (0, 1, 0)`; the classes of `S` and `Y` span the free part
and the class of `AS²` generates the torsion. -/
noncomputable def d0AbelianizationEquiv :
    TopologicalAbelianization demushkinD0 ≃ₜ* Multiplicative ((ℤ_[2] × ℤ_[2]) × ZMod 2) where
  toFun := TopologicalAbelianization.lift d0AbelianizationHom
  invFun := d0AbelianizationInv
  left_inv x := by
    have h := DFunLike.congr_fun d0AbelianizationInv_comp_lift x
    simpa only [ContinuousMonoidHom.coe_comp, Function.comp_apply, ContinuousMonoidHom.coe_id,
      id_eq] using h
  right_inv := lift_d0AbelianizationInv
  map_mul' := map_mul _
  continuous_toFun := (TopologicalAbelianization.lift d0AbelianizationHom).continuous
  continuous_invFun := d0AbelianizationInv.continuous

/-- The isomorphism `D₀^{ab} ≃ₜ* ℤ₂ × ℤ₂ × ℤ/2` is induced by `d0AbelianizationHom`. -/
@[simp]
theorem d0AbelianizationEquiv_mk (x : demushkinD0) :
    d0AbelianizationEquiv (x : TopologicalAbelianization demushkinD0) = d0AbelianizationHom x :=
  TopologicalAbelianization.lift_mk _ x

/-- The inverse of `d0AbelianizationEquiv` sends `(u, v, ε)` to `S^u Y^v (AS²)^ε`, where the
first two factors are `2`-adic powers in `D₀^{ab}` and the last is a power of the class of
`AS²`. -/
theorem d0AbelianizationEquiv_symm_ofAdd (u v : ℤ_[2]) (ε : ZMod 2) :
    d0AbelianizationEquiv.symm (ofAdd ((u, v), ε)) =
      isProP_topologicalAbelianization_demushkinD0.padicPow d0S u *
        isProP_topologicalAbelianization_demushkinD0.padicPow d0Y v *
        d0AbelianizationTorsionGenerator ^ ε.val := by
  have h : d0AbelianizationTorsionGenerator ^ ε.val = d0AbelianizationTorsionHom (ofAdd ε) := by
    obtain rfl | rfl := (by decide : ∀ x : ZMod 2, x = 0 ∨ x = 1) ε
    · simp
    · rw [d0AbelianizationTorsionHom_ofAdd_one, ZMod.val_one, pow_one]
  rw [h, ContinuousMulEquiv.symm_apply_eq, ← d0AbelianizationInv_ofAdd]
  exact (lift_d0AbelianizationInv _).symm

/-- The torsion subgroup of `D₀^{ab}` is generated by the class of `AS²`. -/
theorem torsion_topologicalAbelianization_demushkinD0 :
    torsion (TopologicalAbelianization demushkinD0) =
      Subgroup.zpowers d0AbelianizationTorsionGenerator := by
  refine le_antisymm (fun x hx ↦ ?_) (Subgroup.zpowers_le.2 ?_)
  · -- A torsion element has vanishing `ℤ₂ × ℤ₂`-coordinates, so it is a power of `AS²`.
    have h0 : (d0AbelianizationEquiv x).toAdd.1 = 0 :=
      (mem_torsion_iff_of_mulEquiv isAddTorsion_of_finite d0AbelianizationEquiv.toMulEquiv).1 hx
    have hx' : d0AbelianizationEquiv x = ofAdd ((0, 0), (d0AbelianizationEquiv x).toAdd.2) := by
      conv_lhs => rw [← ofAdd_toAdd (d0AbelianizationEquiv x)]
      exact congrArg ofAdd (Prod.ext (h0.trans Prod.mk_zero_zero.symm) rfl)
    have h := d0AbelianizationEquiv_symm_ofAdd 0 0 (d0AbelianizationEquiv x).toAdd.2
    rw [← hx', d0AbelianizationEquiv.symm_apply_apply, IsProP.padicPow_zero,
      IsProP.padicPow_zero, one_mul, one_mul] at h
    exact Subgroup.mem_zpowers_iff.2 ⟨(d0AbelianizationEquiv x).toAdd.2.val,
      (zpow_natCast _ _).trans h.symm⟩
  · exact (CommGroup.mem_torsion _).2
      (isOfFinOrder_iff_pow_eq_one.2 ⟨2, two_pos, d0AbelianizationTorsionGenerator_sq⟩)

/-- **The `q`-invariant of `D₀`.** The torsion subgroup of `D₀^{ab} ≅ ℤ₂ × ℤ₂ × ℤ/2` has exactly
two elements, the identity and the class of `AS²`. -/
theorem nat_card_torsion_topologicalAbelianization_demushkinD0 :
    Nat.card (torsion (TopologicalAbelianization demushkinD0)) = 2 := by
  rw [Nat.card_congr (torsionMulEquiv isAddTorsion_of_finite
    d0AbelianizationEquiv.toMulEquiv).toEquiv, Nat.card_eq_fintype_card,
    Fintype.card_multiplicative, ZMod.card]

end EpsilonEridani
