/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.Algebra.AlgebraicGroup.HopfIdeal.BaseChange
public import EpsilonEridani.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.ToralClosure.Subsystem.Basic

/-!
# Base change of a Kostant torus subsystem

A Kostant torus subsystem over `ℤ` is the closed subgroup scheme of `GLₙ` generated by a selected
set of represented root subgroups together with the represented weight torus. This file transports
its coordinate presentation along `ℤ → A`. The base-changed defining ideal cuts out the specialized
carrier, and its quotient coordinate Hopf algebra is canonically the scalar extension of the
integral subsystem carrier.

The selected root-subgroup maps and the weight-torus map are transported through the same quotient
comparison. Their factorization equations ensure that scalar extension preserves the chosen
pinning data, rather than only the underlying carrier. The construction remains in tensor-product
coordinate algebras; transporting it into the coordinate rings constructed directly over `A` is a
separate comparison.

## Main declarations

* `EpsilonEridani.UniversalEnvelopingAlgebra.kostantTorusSubsystemBaseChangeIdeal`: the scalar extension
  of the integral subsystem ideal.
* `EpsilonEridani.UniversalEnvelopingAlgebra.kostantTorusSubsystemBaseChangeIso`: the quotient comparison
  identifying the specialized carrier with the base change of the integral carrier.
* `EpsilonEridani.UniversalEnvelopingAlgebra.kostantRootSubgroupTorusSubsystemBaseChangeCoordinateMap`:
  the transported factorization of each selected root subgroup.
* `EpsilonEridani.UniversalEnvelopingAlgebra.kostantWeightTorusTorusSubsystemBaseChangeCoordinateMap`:
  the transported factorization of the weight torus.

## References

* R. W. Carter, *Simple Groups of Lie Type*, §4.4.
* B. Conrad, *Reductive Group Schemes*, §1.

The declaration structure follows the base-change interface for the full Kostant toral closure in
`EpsilonEridani.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.ToralClosure.BaseChange`.
-/

public section

open CategoryTheory

namespace EpsilonEridani.UniversalEnvelopingAlgebra

universe u w

-- Match tensor products to the `ℤ`-algebra structure used by scalar extension.
attribute [local instance high] Algebra.toModule

variable {L : Type u} [LieRing L] [LieAlgebra ℚ L]
variable {I : Type w} {κ : Type} [Finite κ]
variable {V : Type} [AddCommGroup V] [Module ℚ V]

variable (e : I → L) (h : κ → L)
variable (ρ : _root_.UniversalEnvelopingAlgebra ℚ L →ₐ[ℚ] Module.End ℚ V)
variable (M : AddSubgroup V)
variable (hM : ∀ u ∈ kostantForm e h, ∀ m ∈ M, ρ u m ∈ M)
variable {n : ℕ} (b : Module.Basis (Fin n) ℤ M)
variable (wt : Fin n → κ → ℤ) (S : Set I)
variable (hnilS : ∀ i : S,
  IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i.1))))
variable (A : Type*) [CommRing A]

/-- The defining ideal of the base-changed Kostant torus subsystem. -/
noncomputable def kostantTorusSubsystemBaseChangeIdeal :
    HopfIdeal A
      (CommHopfAlgCat.baseChange (K := A) (GeneralLinear.coordinateHopfAlgebra ℤ n)) :=
  CommHopfAlgCat.baseChangeHopfIdeal
    (kostantTorusSubsystemDefiningIdeal e h ρ M hM b wt S hnilS)

/-- Quotienting by the specialized subsystem ideal agrees with base-changing the integral
subsystem coordinate ring. -/
noncomputable def kostantTorusSubsystemBaseChangeIso :
    CommHopfAlgCat.quotient
        (CommHopfAlgCat.baseChange (K := A) (GeneralLinear.coordinateHopfAlgebra ℤ n))
        (kostantTorusSubsystemBaseChangeIdeal e h ρ M hM b wt S hnilS A) ≅
      CommHopfAlgCat.baseChange (K := A)
        (CommHopfAlgCat.quotient (GeneralLinear.coordinateHopfAlgebra ℤ n)
          (kostantTorusSubsystemDefiningIdeal e h ρ M hM b wt S hnilS)) :=
  CommHopfAlgCat.quotientBaseChangeIso
    (kostantTorusSubsystemDefiningIdeal e h ρ M hM b wt S hnilS)

/-- The subsystem base-change comparison is compatible with the integral quotient map. -/
@[simp]
theorem mkQuotient_comp_kostantTorusSubsystemBaseChangeIso_hom :
    CommHopfAlgCat.mkQuotient
          (CommHopfAlgCat.baseChange (K := A) (GeneralLinear.coordinateHopfAlgebra ℤ n))
          (kostantTorusSubsystemBaseChangeIdeal e h ρ M hM b wt S hnilS A) ≫
        (kostantTorusSubsystemBaseChangeIso e h ρ M hM b wt S hnilS A).hom =
      CommHopfAlgCat.baseChangeMap
        (CommHopfAlgCat.mkQuotient (GeneralLinear.coordinateHopfAlgebra ℤ n)
          (kostantTorusSubsystemDefiningIdeal e h ρ M hM b wt S hnilS)) := by
  unfold kostantTorusSubsystemBaseChangeIdeal kostantTorusSubsystemBaseChangeIso
  exact CommHopfAlgCat.mkQuotient_comp_quotientBaseChangeIso_hom (K := A)
    (kostantTorusSubsystemDefiningIdeal e h ρ M hM b wt S hnilS)

/-- The factored coordinate map of a selected root subgroup after base change. -/
noncomputable def kostantRootSubgroupTorusSubsystemBaseChangeCoordinateMap
    {i : I} (hi : i ∈ S) :
    CommHopfAlgCat.quotient
        (CommHopfAlgCat.baseChange (K := A) (GeneralLinear.coordinateHopfAlgebra ℤ n))
        (kostantTorusSubsystemBaseChangeIdeal e h ρ M hM b wt S hnilS A) ⟶
      CommHopfAlgCat.baseChange (K := A) (AdditiveGroup.coordinateHopfAlgebra ℤ) :=
  (kostantTorusSubsystemBaseChangeIso e h ρ M hM b wt S hnilS A).hom ≫
    CommHopfAlgCat.baseChangeMap
      (kostantRootSubgroupTorusSubsystemCoordinateMap
        e h ρ M hM b wt S hnilS hi)

/-- The specialized quotient map followed by a selected root-subgroup map is the base change of
the corresponding integral root-subgroup coordinate map. -/
@[simp]
theorem mkQuotient_comp_kostantRootSubgroupTorusSubsystemBaseChangeCoordinateMap
    {i : I} (hi : i ∈ S) :
    CommHopfAlgCat.mkQuotient
          (CommHopfAlgCat.baseChange (K := A) (GeneralLinear.coordinateHopfAlgebra ℤ n))
          (kostantTorusSubsystemBaseChangeIdeal e h ρ M hM b wt S hnilS A) ≫
        kostantRootSubgroupTorusSubsystemBaseChangeCoordinateMap
          e h ρ M hM b wt S hnilS A hi =
      CommHopfAlgCat.baseChangeMap
        (kostantRootSubgroupCoordinateMap e h ρ M hM i (hnilS ⟨i, hi⟩) b) := by
  rw [kostantRootSubgroupTorusSubsystemBaseChangeCoordinateMap, ← Category.assoc,
    mkQuotient_comp_kostantTorusSubsystemBaseChangeIso_hom,
    ← (CommHopfAlgCat.baseChangeFunctor (K := A)).map_comp,
    mkQuotient_comp_kostantRootSubgroupTorusSubsystemCoordinateMap]

/-- The factored coordinate map of the represented weight torus after base change. -/
noncomputable def kostantWeightTorusTorusSubsystemBaseChangeCoordinateMap :
    CommHopfAlgCat.quotient
        (CommHopfAlgCat.baseChange (K := A) (GeneralLinear.coordinateHopfAlgebra ℤ n))
        (kostantTorusSubsystemBaseChangeIdeal e h ρ M hM b wt S hnilS A) ⟶
      CommHopfAlgCat.baseChange (K := A)
        (DiagonalizableGroup.coordinateRing ℤ (SplitTorus.characterGroup κ)).obj :=
  (kostantTorusSubsystemBaseChangeIso e h ρ M hM b wt S hnilS A).hom ≫
    CommHopfAlgCat.baseChangeMap
      (kostantWeightTorusTorusSubsystemCoordinateMap e h ρ M hM b wt S hnilS)

/-- The specialized quotient map followed by the weight-torus map is the base change of the
integral weight-torus coordinate map. -/
@[simp]
theorem mkQuotient_comp_kostantWeightTorusTorusSubsystemBaseChangeCoordinateMap :
    CommHopfAlgCat.mkQuotient
          (CommHopfAlgCat.baseChange (K := A) (GeneralLinear.coordinateHopfAlgebra ℤ n))
          (kostantTorusSubsystemBaseChangeIdeal e h ρ M hM b wt S hnilS A) ≫
        kostantWeightTorusTorusSubsystemBaseChangeCoordinateMap
          e h ρ M hM b wt S hnilS A =
      CommHopfAlgCat.baseChangeMap (GeneralLinear.weightTorusCoordinateMap wt) := by
  rw [kostantWeightTorusTorusSubsystemBaseChangeCoordinateMap, ← Category.assoc,
    mkQuotient_comp_kostantTorusSubsystemBaseChangeIso_hom,
    ← (CommHopfAlgCat.baseChangeFunctor (K := A)).map_comp,
    mkQuotient_comp_kostantWeightTorusTorusSubsystemCoordinateMap]

/-- Every selected base-changed root-subgroup map kills the specialized subsystem ideal. -/
theorem kostantTorusSubsystemBaseChangeIdeal_toIdeal_le_root_ker
    {i : I} (hi : i ∈ S) :
    (kostantTorusSubsystemBaseChangeIdeal e h ρ M hM b wt S hnilS A).toIdeal ≤
      RingHom.ker
        (CommHopfAlgCat.baseChangeMap (K := A)
          (kostantRootSubgroupCoordinateMap
            e h ρ M hM i (hnilS ⟨i, hi⟩) b)).hom.toAlgHom.toRingHom :=
  CommHopfAlgCat.baseChangeHopfIdeal_toIdeal_le_ker_baseChangeMap
    (kostantTorusSubsystemDefiningIdeal e h ρ M hM b wt S hnilS)
    (kostantRootSubgroupCoordinateMap e h ρ M hM i (hnilS ⟨i, hi⟩) b)
    (kostantTorusSubsystemDefiningIdeal_toIdeal_le_root_ker
      e h ρ M hM b wt S hnilS hi)

/-- The base-changed weight-torus map kills the specialized subsystem ideal. -/
theorem kostantTorusSubsystemBaseChangeIdeal_toIdeal_le_torus_ker :
    (kostantTorusSubsystemBaseChangeIdeal e h ρ M hM b wt S hnilS A).toIdeal ≤
      RingHom.ker
        (CommHopfAlgCat.baseChangeMap (K := A)
          (GeneralLinear.weightTorusCoordinateMap wt)).hom.toAlgHom.toRingHom :=
  CommHopfAlgCat.baseChangeHopfIdeal_toIdeal_le_ker_baseChangeMap
    (kostantTorusSubsystemDefiningIdeal e h ρ M hM b wt S hnilS)
    (GeneralLinear.weightTorusCoordinateMap wt)
    (kostantTorusSubsystemDefiningIdeal_toIdeal_le_torus_ker
      e h ρ M hM b wt S hnilS)

end EpsilonEridani.UniversalEnvelopingAlgebra
