/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.ToralClosure.Basic
import EpsilonEridani.AlgebraicGeometry.AffineGroupScheme.HopfSpec
import EpsilonEridani.Algebra.AlgebraicGroup.HopfIdeal.Equalizer
import EpsilonEridani.Algebra.AlgebraicGroup.HopfIdeal.Scheme.Classification
import EpsilonEridani.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.ToralClosure.Internal

/-!
# Closed subschemes generated by a torus and selected Kostant root subgroups

Fix the data defining a Kostant toral closure inside `GLₙ`, and let `S` be a set of its root
indices. This file constructs the smallest closed subgroup scheme of `GLₙ` containing the
represented weight torus and the root-subgroup morphisms indexed by `S`. Its defining Hopf ideal
is the largest one killed by those morphisms; concretely, it is the common-kernel Hopf
ideal of the selected root-subgroup coordinate maps and the weight-torus coordinate map.

The resulting carrier is a closed subgroup scheme of the full toral closure. The inclusion is
functorial in `S`, and both the selected root subgroups and the weight torus factor through it.
For a positive system, this is the scheme-level candidate for the Borel component of a pinning.
No maximal-solvability or reductivity statement is made here: proving that this closed carrier is
a Borel subgroup for the Chevalley data is later geometric work.

This construction is the scheme counterpart of
`EpsilonEridani.UniversalEnvelopingAlgebra.kostantTorusSubsystemSubgroup`, which generates a subgroup on
points. The pointwise subgroup maps into the points of this closed carrier, but equality can fail
over a general value ring and is not asserted here.

## Main declarations

* `EpsilonEridani.UniversalEnvelopingAlgebra.kostantTorusSubsystemDefiningIdeal`: the common-kernel Hopf
  ideal for the selected root subgroups and the weight torus.
* `EpsilonEridani.UniversalEnvelopingAlgebra.kostantTorusSubsystemGroupScheme`: the corresponding closed
  subgroup scheme of `GLₙ`.
* `EpsilonEridani.UniversalEnvelopingAlgebra.kostantTorusSubsystemToToral`: its closed immersion into the
  full toral closure.
* `EpsilonEridani.UniversalEnvelopingAlgebra.kostantTorusSubsystemClosedSubgroup_le_iff`: its minimality
  among closed subgroups containing the selected root subgroups and weight torus.
* `EpsilonEridani.UniversalEnvelopingAlgebra.kostantRootSubgroupToTorusSubsystem` and
  `EpsilonEridani.UniversalEnvelopingAlgebra.kostantWeightTorusToTorusSubsystem`: the selected
  represented root-subgroup morphisms and the represented weight-torus morphism, factored through
  the subsystem carrier.

## References

* J. E. Humphreys, *Linear Algebraic Groups*, §§26--28.
* R. W. Carter, *Simple Groups of Lie Type*, §§4.4, 8.2, and 8.5.

Formally, this file follows and reuses
`EpsilonEridani.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.ToralClosure.Basic`, whose
generator family, defining ideal and factorization pattern for the full toral closure it
specializes to a selected set of root indices, and it is the scheme-level counterpart of the
pointwise subsystem subgroups in
`EpsilonEridani.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Borel`.
-/

public section

open AlgebraicGeometry CategoryTheory TensorProduct

namespace EpsilonEridani.UniversalEnvelopingAlgebra

universe u w

-- Match tensor products to the `ℤ`-algebra structure used by scalar extension.
attribute [local instance high] Algebra.toModule

variable {L : Type u} [LieRing L] [LieAlgebra ℚ L]
variable {I : Type w} {κ : Type} [Finite κ]
variable {V : Type} [AddCommGroup V] [Module ℚ V]

variable (e : I → L) (h : κ → L)
variable (ρ : _root_.UniversalEnvelopingAlgebra ℚ L →ₐ[ℚ] Module.End ℚ V)
variable (M : AddSubgroup V)
variable (hM : ∀ u ∈ kostantForm e h, ∀ m ∈ M, ρ u m ∈ M)
variable {n : ℕ} (b : Module.Basis (Fin n) ℤ M)
variable (wt : Fin n → κ → ℤ)

/-- The defining Hopf ideal of the closed subgroup scheme generated by the represented weight
torus and the Kostant root subgroups indexed by `S`. It is the common-kernel
Hopf ideal of the toral generator family restricted to `S`. -/
noncomputable def kostantTorusSubsystemDefiningIdeal (S : Set I)
    (hnilS : ∀ i : S, IsNilpotent
      (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i.1)))) :
    HopfIdeal ℤ (GeneralLinear.coordinateHopfAlgebra ℤ n) :=
  CommHopfAlgCat.commonKernelHopfIdeal
    (ToralClosure.Internal.kostantToralGeneratorMap e h ρ M hM b wt Subtype.val hnilS)

/-- The subsystem defining ideal is the common-kernel Hopf ideal of the selected root-subgroup
coordinate maps and the weight-torus coordinate map. -/
theorem kostantTorusSubsystemDefiningIdeal_def (S : Set I)
    (hnilS : ∀ i : S, IsNilpotent
      (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i.1)))) :
    kostantTorusSubsystemDefiningIdeal e h ρ M hM b wt S hnilS =
      CommHopfAlgCat.commonKernelHopfIdeal
        ((fun j : Sum S Unit =>
          match j with
          | .inl i => kostantRootSubgroupCoordinateMap e h ρ M hM i.1 (hnilS i) b
          | .inr _ => GeneralLinear.weightTorusCoordinateMap (R := ℤ) wt) :
          (j : Sum S Unit) → GeneralLinear.coordinateHopfAlgebra ℤ n ⟶
            match j with
            | .inl _ => AdditiveGroup.coordinateHopfAlgebra ℤ
            | .inr _ =>
                (DiagonalizableGroup.coordinateRing ℤ (SplitTorus.characterGroup κ)).obj) := by
  unfold kostantTorusSubsystemDefiningIdeal
  exact ToralClosure.Internal.commonKernelHopfIdeal_kostantToralGeneratorMap_subtype
    e h ρ M hM b wt S hnilS

/-- A Hopf ideal lies in the subsystem defining ideal exactly when the selected root-subgroup
maps and the weight-torus map kill it. This is the coordinate universal property of the closed
carrier. -/
theorem le_kostantTorusSubsystemDefiningIdeal_iff (S : Set I)
    (hnilS : ∀ i : S, IsNilpotent
      (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i.1))))
    (J : HopfIdeal ℤ (GeneralLinear.coordinateHopfAlgebra ℤ n)) :
    J ≤ kostantTorusSubsystemDefiningIdeal e h ρ M hM b wt S hnilS ↔
      (∀ (i : I) (hi : i ∈ S), J.toIdeal ≤ RingHom.ker
        (kostantRootSubgroupCoordinateMap e h ρ M hM i (hnilS ⟨i, hi⟩)
          b).hom.toAlgHom.toRingHom) ∧
      J.toIdeal ≤ RingHom.ker
        (GeneralLinear.weightTorusCoordinateMap wt).hom.toAlgHom.toRingHom := by
  rw [kostantTorusSubsystemDefiningIdeal, CommHopfAlgCat.le_commonKernelHopfIdeal_iff]
  constructor
  · intro hJ
    refine ⟨?_, ?_⟩
    · intro i hi
      simpa only [ToralClosure.Internal.kostantToralGeneratorMap_inl] using
        hJ (Sum.inl (β := Unit) (⟨i, hi⟩ : S))
    · simpa only [ToralClosure.Internal.kostantToralGeneratorMap_inr] using
        hJ (Sum.inr (α := S) ())
  · rintro ⟨hroot, htorus⟩ (i | u)
    · simpa only [ToralClosure.Internal.kostantToralGeneratorMap_inl] using hroot i.1 i.2
    · rcases u with ⟨⟩
      simpa only [ToralClosure.Internal.kostantToralGeneratorMap_inr] using htorus

/-- Enlarging the selected set can only shrink its common-kernel defining ideal. Equivalently,
the associated closed subgroup scheme grows with the selected root set. -/
theorem kostantTorusSubsystemDefiningIdeal_anti {S T : Set I}
    (hnilS : ∀ i : S, IsNilpotent
      (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i.1))))
    (hnilT : ∀ i : T, IsNilpotent
      (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i.1)))) (hST : S ⊆ T) :
    kostantTorusSubsystemDefiningIdeal e h ρ M hM b wt T hnilT ≤
      kostantTorusSubsystemDefiningIdeal e h ρ M hM b wt S hnilS := by
  rw [le_kostantTorusSubsystemDefiningIdeal_iff]
  exact ⟨fun i hi =>
    (le_kostantTorusSubsystemDefiningIdeal_iff e h ρ M hM b wt T hnilT _).mp le_rfl |>.1
      i (hST hi),
    (le_kostantTorusSubsystemDefiningIdeal_iff e h ρ M hM b wt T hnilT _).mp le_rfl |>.2⟩

/-- The full toral defining ideal lies in every subsystem defining ideal. -/
theorem kostantToralDefiningIdeal_le_kostantTorusSubsystemDefiningIdeal
    (hnil : ∀ i, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i))))
    (S : Set I) :
    kostantToralDefiningIdeal e h ρ M hM hnil b wt ≤
      kostantTorusSubsystemDefiningIdeal e h ρ M hM b wt S (fun i => hnil i.1) := by
  rw [le_kostantTorusSubsystemDefiningIdeal_iff]
  exact ⟨fun i _ =>
    kostantToralDefiningIdeal_toIdeal_le_root_ker e h ρ M hM hnil b wt i,
    kostantToralDefiningIdeal_toIdeal_le_torus_ker e h ρ M hM hnil b wt⟩

/-- Selecting every root subgroup recovers the defining ideal of the full toral closure. -/
@[simp]
theorem kostantTorusSubsystemDefiningIdeal_univ :
    kostantTorusSubsystemDefiningIdeal e h ρ M hM b wt Set.univ
        (fun i => hnil i.1) =
      kostantToralDefiningIdeal e h ρ M hM hnil b wt := by
  apply le_antisymm
  · rw [le_kostantToralDefiningIdeal_iff]
    exact ⟨fun i =>
      (le_kostantTorusSubsystemDefiningIdeal_iff e h ρ M hM b wt Set.univ
        (fun i => hnil i.1) _).mp
        le_rfl |>.1 i (Set.mem_univ i),
      (le_kostantTorusSubsystemDefiningIdeal_iff e h ρ M hM b wt Set.univ
        (fun i => hnil i.1) _).mp
        le_rfl |>.2⟩
  · exact kostantToralDefiningIdeal_le_kostantTorusSubsystemDefiningIdeal
      e h ρ M hM b wt hnil Set.univ

/-- Every selected represented root-subgroup coordinate map kills the subsystem defining ideal. -/
theorem kostantTorusSubsystemDefiningIdeal_toIdeal_le_root_ker (S : Set I)
    (hnilS : ∀ i : S, IsNilpotent
      (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i.1))))
    {i : I} (hi : i ∈ S) :
    (kostantTorusSubsystemDefiningIdeal e h ρ M hM b wt S hnilS).toIdeal ≤
      RingHom.ker
        (kostantRootSubgroupCoordinateMap e h ρ M hM i (hnilS ⟨i, hi⟩)
          b).hom.toAlgHom.toRingHom :=
  (le_kostantTorusSubsystemDefiningIdeal_iff e h ρ M hM b wt S hnilS _).mp le_rfl |>.1 i hi

/-- The represented weight-torus coordinate map kills every subsystem defining ideal. -/
theorem kostantTorusSubsystemDefiningIdeal_toIdeal_le_torus_ker (S : Set I)
    (hnilS : ∀ i : S, IsNilpotent
      (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i.1)))) :
    (kostantTorusSubsystemDefiningIdeal e h ρ M hM b wt S hnilS).toIdeal ≤
      RingHom.ker
        (GeneralLinear.weightTorusCoordinateMap wt).hom.toAlgHom.toRingHom :=
  (le_kostantTorusSubsystemDefiningIdeal_iff e h ρ M hM b wt S hnilS _).mp le_rfl |>.2

/-- The affine group scheme generated by the selected root subgroups and the weight torus. -/
noncomputable abbrev kostantTorusSubsystemGroupScheme (S : Set I)
    (hnilS : ∀ i : S, IsNilpotent
      (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i.1)))) :
    Grp (Over (Spec (CommRingCat.of ℤ))) :=
  CommHopfAlgCat.quotientSpec (GeneralLinear.coordinateHopfAlgebra ℤ n)
    (kostantTorusSubsystemDefiningIdeal e h ρ M hM b wt S hnilS)

/-- The inclusion of a torus-subsystem carrier into `GLₙ`. -/
noncomputable def kostantTorusSubsystemGroupSchemeι (S : Set I)
    (hnilS : ∀ i : S, IsNilpotent
      (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i.1)))) :
    kostantTorusSubsystemGroupScheme e h ρ M hM b wt S hnilS ⟶
      GeneralLinear.groupScheme ℤ n :=
  CommHopfAlgCat.quotientSpecι (GeneralLinear.coordinateHopfAlgebra ℤ n)
      (kostantTorusSubsystemDefiningIdeal e h ρ M hM b wt S hnilS) ≫
    eqToHom (GeneralLinear.groupScheme_def ℤ n).symm

/-- The subsystem inclusion is the quotient-spectrum inclusion transported across the named
presentation of `GLₙ`. -/
theorem kostantTorusSubsystemGroupSchemeι_def (S : Set I)
    (hnilS : ∀ i : S, IsNilpotent
      (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i.1)))) :
    kostantTorusSubsystemGroupSchemeι e h ρ M hM b wt S hnilS =
      CommHopfAlgCat.quotientSpecι (GeneralLinear.coordinateHopfAlgebra ℤ n)
          (kostantTorusSubsystemDefiningIdeal e h ρ M hM b wt S hnilS) ≫
        eqToHom (GeneralLinear.groupScheme_def ℤ n).symm := by
  rw [kostantTorusSubsystemGroupSchemeι]

/-- The torus-subsystem inclusion into `GLₙ` is a closed immersion. -/
instance isClosedImmersion_kostantTorusSubsystemGroupSchemeι (S : Set I)
    (hnilS : ∀ i : S, IsNilpotent
      (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i.1)))) :
    IsClosedImmersion
      (kostantTorusSubsystemGroupSchemeι e h ρ M hM b wt S hnilS).hom.hom.left := by
  unfold kostantTorusSubsystemGroupSchemeι
  rw [CommHopfAlgCat.quotientSpecι_def]
  apply (CommHopfAlgCat.isClosedImmersion_hopfSpec_map_comp_eqToHom_iff
    (GeneralLinear.groupScheme_def ℤ n)
    (CommHopfAlgCat.mkQuotient (GeneralLinear.coordinateHopfAlgebra ℤ n)
      (kostantTorusSubsystemDefiningIdeal e h ρ M hM b wt S hnilS))).mpr
  exact Ideal.Quotient.mkₐ_surjective ℤ
    (kostantTorusSubsystemDefiningIdeal e h ρ M hM b wt S hnilS).toIdeal

/-- An inclusion `S ⊆ T` induces the closed immersion from the carrier generated by `S` into
the carrier generated by `T`. -/
noncomputable def kostantTorusSubsystemMapOfSubset {S T : Set I}
    (hnilS : ∀ i : S, IsNilpotent
      (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i.1))))
    (hnilT : ∀ i : T, IsNilpotent
      (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i.1)))) (hST : S ⊆ T) :
    kostantTorusSubsystemGroupScheme e h ρ M hM b wt S hnilS ⟶
      kostantTorusSubsystemGroupScheme e h ρ M hM b wt T hnilT :=
  CommHopfAlgCat.quotientSpecMapOfLe (GeneralLinear.coordinateHopfAlgebra ℤ n)
    (kostantTorusSubsystemDefiningIdeal_anti e h ρ M hM b wt hnilS hnilT hST)

/-- The subsystem map induced by a reflexive set inclusion is the identity. -/
@[simp]
theorem kostantTorusSubsystemMapOfSubset_refl (S : Set I)
    (hnilS : ∀ i : S, IsNilpotent
      (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i.1)))) (hSS : S ⊆ S) :
    kostantTorusSubsystemMapOfSubset e h ρ M hM b wt hnilS hnilS hSS =
      𝟙 (kostantTorusSubsystemGroupScheme e h ρ M hM b wt S hnilS) := by
  rw [kostantTorusSubsystemMapOfSubset]
  exact CommHopfAlgCat.quotientSpecMapOfLe_refl _ _

/-- The map induced by inclusion of selected root sets is a closed immersion. -/
instance isClosedImmersion_kostantTorusSubsystemMapOfSubset {S T : Set I}
    (hnilS : ∀ i : S, IsNilpotent
      (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i.1))))
    (hnilT : ∀ i : T, IsNilpotent
      (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i.1)))) (hST : S ⊆ T) :
    IsClosedImmersion
      (kostantTorusSubsystemMapOfSubset e h ρ M hM b wt hnilS hnilT hST).hom.hom.left := by
  unfold kostantTorusSubsystemMapOfSubset
  infer_instance

/-- The inclusion induced by `S ⊆ T`, followed by the inclusion into `GLₙ`, is the direct
inclusion of the `S`-carrier. -/
@[simp]
theorem kostantTorusSubsystemMapOfSubset_comp_ι {S T : Set I}
    (hnilS : ∀ i : S, IsNilpotent
      (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i.1))))
    (hnilT : ∀ i : T, IsNilpotent
      (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i.1)))) (hST : S ⊆ T) :
    kostantTorusSubsystemMapOfSubset e h ρ M hM b wt hnilS hnilT hST ≫
        kostantTorusSubsystemGroupSchemeι e h ρ M hM b wt T hnilT =
      kostantTorusSubsystemGroupSchemeι e h ρ M hM b wt S hnilS := by
  unfold kostantTorusSubsystemGroupSchemeι
  rw [kostantTorusSubsystemMapOfSubset, ← Category.assoc,
    CommHopfAlgCat.quotientSpecMapOfLe_comp_quotientSpecι]

/-- Closed subsystem inclusions compose along inclusions of selected root sets. -/
@[simp]
theorem kostantTorusSubsystemMapOfSubset_comp {S T U : Set I}
    (hnilS : ∀ i : S, IsNilpotent
      (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i.1))))
    (hnilT : ∀ i : T, IsNilpotent
      (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i.1))))
    (hnilU : ∀ i : U, IsNilpotent
      (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i.1))))
    (hST : S ⊆ T) (hTU : T ⊆ U) :
    kostantTorusSubsystemMapOfSubset e h ρ M hM b wt hnilS hnilT hST ≫
        kostantTorusSubsystemMapOfSubset e h ρ M hM b wt hnilT hnilU hTU =
      kostantTorusSubsystemMapOfSubset e h ρ M hM b wt hnilS hnilU
        (hST.trans hTU) := by
  rw [kostantTorusSubsystemMapOfSubset, kostantTorusSubsystemMapOfSubset,
    kostantTorusSubsystemMapOfSubset,
    CommHopfAlgCat.quotientSpecMapOfLe_comp]

/-- The torus-subsystem carrier as a closed subgroup scheme of the full toral closure. -/
noncomputable def kostantTorusSubsystemToToral
    (hnil : ∀ i, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i))))
    (S : Set I) :
    kostantTorusSubsystemGroupScheme e h ρ M hM b wt S (fun i => hnil i.1) ⟶
      kostantToralGroupScheme e h ρ M hM hnil b wt :=
  CommHopfAlgCat.quotientSpecMapOfLe (GeneralLinear.coordinateHopfAlgebra ℤ n)
    (kostantToralDefiningIdeal_le_kostantTorusSubsystemDefiningIdeal
      e h ρ M hM b wt hnil S)

/-- The subsystem carrier includes into the full toral closure as a closed immersion. -/
instance isClosedImmersion_kostantTorusSubsystemToToral
    (hnil : ∀ i, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i))))
    (S : Set I) :
    IsClosedImmersion
      (kostantTorusSubsystemToToral e h ρ M hM b wt hnil S).hom.hom.left := by
  unfold kostantTorusSubsystemToToral
  infer_instance

/-- The subsystem inclusion followed by the full toral inclusion is its direct inclusion into
`GLₙ`. -/
@[simp]
theorem kostantTorusSubsystemToToral_comp_ι
    (hnil : ∀ i, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i))))
    (S : Set I) :
    kostantTorusSubsystemToToral e h ρ M hM b wt hnil S ≫
        kostantToralGroupSchemeι e h ρ M hM hnil b wt =
      kostantTorusSubsystemGroupSchemeι e h ρ M hM b wt S (fun i => hnil i.1) := by
  unfold kostantTorusSubsystemGroupSchemeι
  rw [kostantTorusSubsystemToToral, kostantToralGroupSchemeι_def,
    ← Category.assoc, CommHopfAlgCat.quotientSpecMapOfLe_comp_quotientSpecι]

/-- The map induced by `S ⊆ T`, followed by the inclusion of the `T`-carrier into the full
toral closure, is the inclusion of the `S`-carrier. -/
@[simp]
theorem kostantTorusSubsystemMapOfSubset_comp_kostantTorusSubsystemToToral
    (hnil : ∀ i, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i))))
    {S T : Set I} (hST : S ⊆ T) :
    kostantTorusSubsystemMapOfSubset e h ρ M hM b wt
        (fun i : S => hnil i.1) (fun i : T => hnil i.1) hST ≫
        kostantTorusSubsystemToToral e h ρ M hM b wt hnil T =
      kostantTorusSubsystemToToral e h ρ M hM b wt hnil S := by
  rw [kostantTorusSubsystemMapOfSubset, kostantTorusSubsystemToToral,
    kostantTorusSubsystemToToral, CommHopfAlgCat.quotientSpecMapOfLe_comp]

/-- A torus-subsystem carrier, regarded as a closed subgroup scheme of the full toral closure. -/
noncomputable def kostantTorusSubsystemClosedSubgroup
    (hnil : ∀ i, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i))))
    (S : Set I) :
    ClosedSubgroupScheme (kostantToralGroupScheme e h ρ M hM hnil b wt) :=
  ClosedSubgroupScheme.mk (kostantTorusSubsystemToToral e h ρ M hM b wt hnil S)

/-- The underlying subobject of a torus subsystem is represented by its canonical inclusion. -/
@[simp]
theorem coe_kostantTorusSubsystemClosedSubgroup
    (hnil : ∀ i, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i))))
    (S : Set I) :
    (kostantTorusSubsystemClosedSubgroup e h ρ M hM b wt hnil S).1 =
      Subobject.mk (kostantTorusSubsystemToToral e h ρ M hM b wt hnil S) :=
  ClosedSubgroupScheme.coe_mk _

private noncomputable def kostantToralSubsystemGeneratorMap
    (hnil : ∀ i, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i))))
    (S : Set I) (j : Sum S Unit) :
    CommHopfAlgCat.quotient (GeneralLinear.coordinateHopfAlgebra ℤ n)
          (kostantToralDefiningIdeal e h ρ M hM hnil b wt) ⟶
        ToralClosure.Internal.kostantToralGeneratorCodomain (kappa := κ) j :=
  match j with
  | .inl i => kostantRootSubgroupToralCoordinateMap e h ρ M hM hnil b wt i.1
  | .inr _ => kostantWeightTorusToralCoordinateMap e h ρ M hM hnil b wt

private noncomputable def kostantTorusSubsystemRelativeDefiningIdeal
    (hnil : ∀ i, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i))))
    (S : Set I) :
    HopfIdeal ℤ (CommHopfAlgCat.quotient (GeneralLinear.coordinateHopfAlgebra ℤ n)
      (kostantToralDefiningIdeal e h ρ M hM hnil b wt)) :=
  HopfIdeal.kerOfSurjective
    (CommHopfAlgCat.quotientMapOfLe (GeneralLinear.coordinateHopfAlgebra ℤ n)
      (kostantToralDefiningIdeal_le_kostantTorusSubsystemDefiningIdeal
        e h ρ M hM b wt hnil S)).hom
    (CommHopfAlgCat.quotientMapOfLe_surjective (GeneralLinear.coordinateHopfAlgebra ℤ n)
      (kostantToralDefiningIdeal_le_kostantTorusSubsystemDefiningIdeal
        e h ρ M hM b wt hnil S))

private theorem kostantTorusSubsystemRelativeDefiningIdeal_eq_commonKernel
    (hnil : ∀ i, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i))))
    (S : Set I) :
    kostantTorusSubsystemRelativeDefiningIdeal e h ρ M hM b wt hnil S =
      CommHopfAlgCat.commonKernelHopfIdeal
        (kostantToralSubsystemGeneratorMap e h ρ M hM b wt hnil S) := by
  let A := GeneralLinear.coordinateHopfAlgebra ℤ n
  let I₀ := kostantToralDefiningIdeal e h ρ M hM hnil b wt
  let Iₛ := kostantTorusSubsystemDefiningIdeal e h ρ M hM b wt S (fun i => hnil i.1)
  let q₀ := CommHopfAlgCat.mkQuotient A I₀
  let f := ToralClosure.Internal.kostantToralGeneratorMap
    e h ρ M hM b wt Subtype.val (fun i : S => hnil i.1)
  let p := kostantToralSubsystemGeneratorMap e h ρ M hM b wt hnil S
  have hI : I₀ ≤ Iₛ :=
    kostantToralDefiningIdeal_le_kostantTorusSubsystemDefiningIdeal
      e h ρ M hM b wt hnil S
  have hp : ∀ j, q₀ ≫ p j = f j := by
    rintro (i | u)
    · simpa only [q₀, p, f, kostantToralSubsystemGeneratorMap,
        ToralClosure.Internal.kostantToralGeneratorMap_inl] using
        mkQuotient_comp_kostantRootSubgroupToralCoordinateMap
          e h ρ M hM hnil b wt i.1
    · rcases u with ⟨⟩
      simpa only [q₀, p, f, kostantToralSubsystemGeneratorMap,
        ToralClosure.Internal.kostantToralGeneratorMap_inr] using
        mkQuotient_comp_kostantWeightTorusToralCoordinateMap
          e h ρ M hM hnil b wt
  have hrelative : kostantTorusSubsystemRelativeDefiningIdeal
      e h ρ M hM b wt hnil S = Iₛ.map q₀.hom := by
    unfold kostantTorusSubsystemRelativeDefiningIdeal
    simpa only [A, I₀, Iₛ, CommHopfAlgCat.quotientMapOfLe,
      CommHopfAlgCat.liftQuotient, q₀, CommHopfAlgCat.hom_mkQuotient,
      _root_.CommHopfAlgCat.hom_ofHom] using
      CommHopfAlgCat.kerOfSurjective_quotientMapOfLe A hI
  rw [hrelative]
  simpa only [Iₛ, q₀, f, kostantTorusSubsystemDefiningIdeal] using
    (CommHopfAlgCat.commonKernelHopfIdeal_eq_map_mkQuotient_of_comp f I₀ p hp).symm

private theorem kostantTorusSubsystemClosedSubgroup_eq_quotientClosedSubgroup
    (hnil : ∀ i, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i))))
    (S : Set I) :
    kostantTorusSubsystemClosedSubgroup e h ρ M hM b wt hnil S =
      CommHopfAlgCat.quotientClosedSubgroup
        (CommHopfAlgCat.quotient (GeneralLinear.coordinateHopfAlgebra ℤ n)
          (kostantToralDefiningIdeal e h ρ M hM hnil b wt))
        (kostantTorusSubsystemRelativeDefiningIdeal e h ρ M hM b wt hnil S) := by
  let A := GeneralLinear.coordinateHopfAlgebra ℤ n
  let I₀ := kostantToralDefiningIdeal e h ρ M hM hnil b wt
  let Iₛ := kostantTorusSubsystemDefiningIdeal e h ρ M hM b wt S (fun i => hnil i.1)
  let hI : I₀ ≤ Iₛ :=
    kostantToralDefiningIdeal_le_kostantTorusSubsystemDefiningIdeal
      e h ρ M hM b wt hnil S
  simpa only [kostantTorusSubsystemClosedSubgroup, kostantTorusSubsystemToToral,
    kostantTorusSubsystemRelativeDefiningIdeal, A, I₀, Iₛ, hI] using
    CommHopfAlgCat.mk_quotientSpecMapOfLe_eq_quotientClosedSubgroup A hI

/-- Inclusion of selected root sets gives inclusion of the corresponding closed subgroup
schemes of the full toral closure. -/
theorem kostantTorusSubsystemClosedSubgroup_mono
    (hnil : ∀ i, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i))))
    {S T : Set I} (hST : S ⊆ T) :
    kostantTorusSubsystemClosedSubgroup e h ρ M hM b wt hnil S ≤
      kostantTorusSubsystemClosedSubgroup e h ρ M hM b wt hnil T := by
  rw [← Subtype.coe_le_coe, coe_kostantTorusSubsystemClosedSubgroup,
    coe_kostantTorusSubsystemClosedSubgroup]
  exact Subobject.mk_le_mk_of_comm
    (kostantTorusSubsystemMapOfSubset e h ρ M hM b wt
      (fun i : S => hnil i.1) (fun i : T => hnil i.1) hST)
    (kostantTorusSubsystemMapOfSubset_comp_kostantTorusSubsystemToToral
      e h ρ M hM b wt hnil hST)

/-- The coordinate map through which a selected root subgroup factors into its subsystem
carrier. -/
noncomputable def kostantRootSubgroupTorusSubsystemCoordinateMap (S : Set I)
    (hnilS : ∀ i : S, IsNilpotent
      (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i.1))))
    {i : I} (hi : i ∈ S) :
    CommHopfAlgCat.quotient (GeneralLinear.coordinateHopfAlgebra ℤ n)
        (kostantTorusSubsystemDefiningIdeal e h ρ M hM b wt S hnilS) ⟶
      AdditiveGroup.coordinateHopfAlgebra ℤ :=
  CommHopfAlgCat.commonKernelLift
    (ToralClosure.Internal.kostantToralGeneratorMap e h ρ M hM b wt Subtype.val hnilS)
      (.inl ⟨i, hi⟩)

/-- The selected root-subgroup factorization recovers its represented coordinate map. -/
@[simp]
theorem mkQuotient_comp_kostantRootSubgroupTorusSubsystemCoordinateMap (S : Set I)
    (hnilS : ∀ i : S, IsNilpotent
      (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i.1))))
    {i : I} (hi : i ∈ S) :
    CommHopfAlgCat.mkQuotient (GeneralLinear.coordinateHopfAlgebra ℤ n)
          (kostantTorusSubsystemDefiningIdeal e h ρ M hM b wt S hnilS) ≫
        kostantRootSubgroupTorusSubsystemCoordinateMap e h ρ M hM b wt S hnilS hi =
      kostantRootSubgroupCoordinateMap e h ρ M hM i (hnilS ⟨i, hi⟩) b :=
  by
    simpa only [kostantRootSubgroupTorusSubsystemCoordinateMap,
      kostantTorusSubsystemDefiningIdeal,
      ToralClosure.Internal.kostantToralGeneratorMap_inl] using
      CommHopfAlgCat.mkQuotient_comp_commonKernelLift
        (ToralClosure.Internal.kostantToralGeneratorMap
          e h ρ M hM b wt Subtype.val hnilS) (.inl ⟨i, hi⟩)

/-- A surjective selected root-subgroup coordinate map remains surjective after factoring through
the subsystem carrier. -/
theorem kostantRootSubgroupTorusSubsystemCoordinateMap_surjective_of_surjective (S : Set I)
    (hnilS : ∀ i : S, IsNilpotent
      (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i.1)))) {i : I} (hi : i ∈ S)
    (hroot : Function.Surjective
      (kostantRootSubgroupCoordinateMap e h ρ M hM i (hnilS ⟨i, hi⟩) b).hom) :
    Function.Surjective
      (kostantRootSubgroupTorusSubsystemCoordinateMap e h ρ M hM b wt S hnilS hi).hom :=
  by
    apply CommHopfAlgCat.commonKernelLift_surjective_of_surjective
    simpa only [ToralClosure.Internal.kostantToralGeneratorMap_inl] using hroot

/-- The coordinate map through which the weight torus factors into a subsystem carrier. -/
noncomputable def kostantWeightTorusTorusSubsystemCoordinateMap (S : Set I)
    (hnilS : ∀ i : S, IsNilpotent
      (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i.1)))) :
    CommHopfAlgCat.quotient (GeneralLinear.coordinateHopfAlgebra ℤ n)
        (kostantTorusSubsystemDefiningIdeal e h ρ M hM b wt S hnilS) ⟶
      (DiagonalizableGroup.coordinateRing ℤ (SplitTorus.characterGroup κ)).obj :=
  CommHopfAlgCat.commonKernelLift
    (ToralClosure.Internal.kostantToralGeneratorMap e h ρ M hM b wt Subtype.val hnilS)
      (.inr ())

/-- The weight-torus factorization recovers its represented coordinate map. -/
@[simp]
theorem mkQuotient_comp_kostantWeightTorusTorusSubsystemCoordinateMap (S : Set I)
    (hnilS : ∀ i : S, IsNilpotent
      (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i.1)))) :
    CommHopfAlgCat.mkQuotient (GeneralLinear.coordinateHopfAlgebra ℤ n)
          (kostantTorusSubsystemDefiningIdeal e h ρ M hM b wt S hnilS) ≫
        kostantWeightTorusTorusSubsystemCoordinateMap e h ρ M hM b wt S hnilS =
      GeneralLinear.weightTorusCoordinateMap wt :=
  by
    simpa only [kostantWeightTorusTorusSubsystemCoordinateMap,
      kostantTorusSubsystemDefiningIdeal,
      ToralClosure.Internal.kostantToralGeneratorMap_inr] using
      CommHopfAlgCat.mkQuotient_comp_commonKernelLift
        (ToralClosure.Internal.kostantToralGeneratorMap
          e h ρ M hM b wt Subtype.val hnilS) (.inr ())

/-- **Coordinate rigidity of a torus-subsystem carrier.** Two morphisms into its coordinate
algebra are equal when they agree after composition with every selected root coordinate and with
the weight-torus coordinate. -/
theorem kostantTorusSubsystemCoordinate_hom_ext {Y : _root_.CommHopfAlgCat.{0} ℤ}
    (S : Set I)
    (hnilS : ∀ i : S, IsNilpotent
      (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i.1))))
    (u v : Y ⟶ CommHopfAlgCat.quotient (GeneralLinear.coordinateHopfAlgebra ℤ n)
      (kostantTorusSubsystemDefiningIdeal e h ρ M hM b wt S hnilS))
    (hroot : ∀ (i : I) (hi : i ∈ S),
      u ≫ kostantRootSubgroupTorusSubsystemCoordinateMap e h ρ M hM b wt S hnilS hi =
        v ≫ kostantRootSubgroupTorusSubsystemCoordinateMap e h ρ M hM b wt S hnilS hi)
    (htorus : u ≫ kostantWeightTorusTorusSubsystemCoordinateMap e h ρ M hM b wt S hnilS =
      v ≫ kostantWeightTorusTorusSubsystemCoordinateMap e h ρ M hM b wt S hnilS) :
    u = v := by
  apply CommHopfAlgCat.commonKernelLift_hom_ext
    (ToralClosure.Internal.kostantToralGeneratorMap e h ρ M hM b wt Subtype.val hnilS)
  rintro (i | u)
  · simpa only [kostantTorusSubsystemDefiningIdeal,
      kostantRootSubgroupTorusSubsystemCoordinateMap] using hroot i.1 i.2
  · rcases u with ⟨⟩
    simpa only [kostantTorusSubsystemDefiningIdeal,
      kostantWeightTorusTorusSubsystemCoordinateMap] using htorus

/-- A selected represented Kostant root subgroup, factored through the subsystem carrier. -/
noncomputable def kostantRootSubgroupToTorusSubsystem (S : Set I)
    (hnilS : ∀ i : S, IsNilpotent
      (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i.1)))) {i : I} (hi : i ∈ S) :
    AdditiveGroup.groupScheme ℤ ⟶
      kostantTorusSubsystemGroupScheme e h ρ M hM b wt S hnilS :=
  eqToHom (AdditiveGroup.groupScheme_def ℤ) ≫
    (AlgebraicGeometry.hopfSpec (CommRingCat.of ℤ)).map
      (kostantRootSubgroupTorusSubsystemCoordinateMap e h ρ M hM b wt S hnilS hi).op

/-- A selected root-subgroup morphism into its subsystem carrier is the spectrum map of its
factored coordinate morphism, after the canonical presentation of the additive group. -/
theorem kostantRootSubgroupToTorusSubsystem_def (S : Set I)
    (hnilS : ∀ i : S, IsNilpotent
      (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i.1)))) {i : I} (hi : i ∈ S) :
    kostantRootSubgroupToTorusSubsystem e h ρ M hM b wt S hnilS hi =
      eqToHom (AdditiveGroup.groupScheme_def ℤ) ≫
        (AlgebraicGeometry.hopfSpec (CommRingCat.of ℤ)).map
          (kostantRootSubgroupTorusSubsystemCoordinateMap
            e h ρ M hM b wt S hnilS hi).op := by
  rw [kostantRootSubgroupToTorusSubsystem]

/-- A selected root-subgroup morphism into its subsystem carrier is a closed immersion whenever
its factored coordinate map is surjective. -/
theorem isClosedImmersion_kostantRootSubgroupToTorusSubsystem_of_surjective (S : Set I)
    (hnilS : ∀ i : S, IsNilpotent
      (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i.1)))) {i : I} (hi : i ∈ S)
    (hroot : Function.Surjective
      (kostantRootSubgroupTorusSubsystemCoordinateMap
        e h ρ M hM b wt S hnilS hi).hom) :
    IsClosedImmersion
      (kostantRootSubgroupToTorusSubsystem e h ρ M hM b wt S hnilS hi).hom.hom.left := by
  rw [kostantRootSubgroupToTorusSubsystem_def]
  exact (CommHopfAlgCat.isClosedImmersion_eqToHom_comp_hopfSpec_map_iff
    (AdditiveGroup.groupScheme_def ℤ)
    (kostantRootSubgroupTorusSubsystemCoordinateMap e h ρ M hM b wt S hnilS hi)).2 hroot

/-- Factoring a selected root subgroup through its subsystem carrier and then including into
`GLₙ` recovers the represented root-subgroup morphism. -/
@[simp]
theorem kostantRootSubgroupToTorusSubsystem_comp_ι (S : Set I)
    (hnilS : ∀ i : S, IsNilpotent
      (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i.1)))) {i : I} (hi : i ∈ S) :
    kostantRootSubgroupToTorusSubsystem e h ρ M hM b wt S hnilS hi ≫
        kostantTorusSubsystemGroupSchemeι e h ρ M hM b wt S hnilS =
      kostantRootSubgroup e h ρ M hM i (hnilS ⟨i, hi⟩) b := by
  unfold kostantRootSubgroupToTorusSubsystem kostantTorusSubsystemGroupSchemeι
  rw [CommHopfAlgCat.quotientSpecι_def, kostantRootSubgroup_def]
  slice_lhs 2 3 =>
    rw [← (AlgebraicGeometry.hopfSpec (CommRingCat.of ℤ)).map_comp,
      ← op_comp, mkQuotient_comp_kostantRootSubgroupTorusSubsystemCoordinateMap]

/-- Factoring a selected root subgroup through nested subsystem carriers is natural in the
selected root set. -/
@[simp]
theorem kostantRootSubgroupToTorusSubsystem_comp_mapOfSubset {S T : Set I}
    (hnilS : ∀ i : S, IsNilpotent
      (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i.1))))
    (hnilT : ∀ i : T, IsNilpotent
      (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i.1)))) (hST : S ⊆ T)
    {i : I} (hi : i ∈ S) :
    kostantRootSubgroupToTorusSubsystem e h ρ M hM b wt S hnilS hi ≫
        kostantTorusSubsystemMapOfSubset e h ρ M hM b wt hnilS hnilT hST =
      kostantRootSubgroupToTorusSubsystem e h ρ M hM b wt T hnilT (hST hi) := by
  apply (cancel_mono (kostantTorusSubsystemGroupSchemeι e h ρ M hM b wt T hnilT)).1
  rw [Category.assoc, kostantTorusSubsystemMapOfSubset_comp_ι,
    kostantRootSubgroupToTorusSubsystem_comp_ι,
    kostantRootSubgroupToTorusSubsystem_comp_ι]

/-- Factoring a selected root subgroup through its subsystem and then into the full toral closure
agrees with the direct toral factorization. -/
@[simp]
theorem kostantRootSubgroupToTorusSubsystem_comp_kostantTorusSubsystemToToral
    (hnil : ∀ i, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i))))
    (S : Set I) {i : I} (hi : i ∈ S) :
    kostantRootSubgroupToTorusSubsystem e h ρ M hM b wt S (fun j => hnil j.1) hi ≫
        kostantTorusSubsystemToToral e h ρ M hM b wt hnil S =
      kostantRootSubgroupToToral e h ρ M hM hnil b wt i := by
  apply (cancel_mono (kostantToralGroupSchemeι e h ρ M hM hnil b wt)).1
  rw [Category.assoc, kostantTorusSubsystemToToral_comp_ι,
    kostantRootSubgroupToTorusSubsystem_comp_ι, kostantRootSubgroupToToral_comp_ι]

/-- The represented weight torus, factored through a torus-subsystem carrier. -/
noncomputable def kostantWeightTorusToTorusSubsystem (S : Set I)
    (hnilS : ∀ i : S, IsNilpotent
      (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i.1)))) :
    SplitTorus.groupScheme ℤ κ ⟶
      kostantTorusSubsystemGroupScheme e h ρ M hM b wt S hnilS :=
  eqToHom (DiagonalizableGroup.groupScheme_def ℤ (SplitTorus.characterGroup κ)) ≫
    (AlgebraicGeometry.hopfSpec (CommRingCat.of ℤ)).map
      (kostantWeightTorusTorusSubsystemCoordinateMap e h ρ M hM b wt S hnilS).op

/-- The weight-torus morphism into a subsystem carrier is the spectrum map of its factored
coordinate morphism, after the canonical presentation of the split torus. -/
theorem kostantWeightTorusToTorusSubsystem_def (S : Set I)
    (hnilS : ∀ i : S, IsNilpotent
      (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i.1)))) :
    kostantWeightTorusToTorusSubsystem e h ρ M hM b wt S hnilS =
      eqToHom (DiagonalizableGroup.groupScheme_def ℤ (SplitTorus.characterGroup κ)) ≫
        (AlgebraicGeometry.hopfSpec (CommRingCat.of ℤ)).map
          (kostantWeightTorusTorusSubsystemCoordinateMap e h ρ M hM b wt S hnilS).op := by
  rw [kostantWeightTorusToTorusSubsystem]

/-- A surjective represented weight-torus coordinate map remains surjective after factoring
through a subsystem carrier. -/
theorem kostantWeightTorusTorusSubsystemCoordinateMap_surjective_of_surjective (S : Set I)
    (hnilS : ∀ i : S, IsNilpotent
      (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i.1))))
    (htorus : Function.Surjective (GeneralLinear.weightTorusCoordinateMap (R := ℤ) wt).hom) :
    Function.Surjective
      (kostantWeightTorusTorusSubsystemCoordinateMap e h ρ M hM b wt S hnilS).hom := by
  apply CommHopfAlgCat.commonKernelLift_surjective_of_surjective
  simpa only [ToralClosure.Internal.kostantToralGeneratorMap_inr] using htorus

/-- The represented weight torus is a closed subgroup of its subsystem carrier whenever its
factored coordinate map is surjective. -/
theorem isClosedImmersion_kostantWeightTorusToTorusSubsystem_of_surjective (S : Set I)
    (hnilS : ∀ i : S, IsNilpotent
      (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i.1))))
    (htorus : Function.Surjective
      (kostantWeightTorusTorusSubsystemCoordinateMap e h ρ M hM b wt S hnilS).hom) :
    IsClosedImmersion
      (kostantWeightTorusToTorusSubsystem e h ρ M hM b wt S hnilS).hom.hom.left := by
  rw [kostantWeightTorusToTorusSubsystem_def]
  exact (CommHopfAlgCat.isClosedImmersion_eqToHom_comp_hopfSpec_map_iff
    (DiagonalizableGroup.groupScheme_def ℤ (SplitTorus.characterGroup κ))
    (kostantWeightTorusTorusSubsystemCoordinateMap e h ρ M hM b wt S hnilS)).2 htorus

/-- Spanning weights represent the weight torus as a closed subgroup of every subsystem
carrier. -/
theorem isClosedImmersion_kostantWeightTorusToTorusSubsystem (S : Set I)
    (hnilS : ∀ i : S, IsNilpotent
      (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i.1))))
    (hwt : Submodule.span ℤ (Set.range wt) = ⊤) :
    IsClosedImmersion
      (kostantWeightTorusToTorusSubsystem e h ρ M hM b wt S hnilS).hom.hom.left :=
  isClosedImmersion_kostantWeightTorusToTorusSubsystem_of_surjective
    e h ρ M hM b wt S hnilS
      (kostantWeightTorusTorusSubsystemCoordinateMap_surjective_of_surjective
        e h ρ M hM b wt S hnilS
          (GeneralLinear.weightTorusCoordinateMap_surjective wt hwt))

/-- Factoring the weight torus through a subsystem carrier and then including into `GLₙ`
recovers the represented weight-torus morphism. -/
@[simp]
theorem kostantWeightTorusToTorusSubsystem_comp_ι (S : Set I)
    (hnilS : ∀ i : S, IsNilpotent
      (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i.1)))) :
    kostantWeightTorusToTorusSubsystem e h ρ M hM b wt S hnilS ≫
        kostantTorusSubsystemGroupSchemeι e h ρ M hM b wt S hnilS =
      GeneralLinear.weightTorus (R := ℤ) wt := by
  unfold kostantWeightTorusToTorusSubsystem kostantTorusSubsystemGroupSchemeι
  rw [CommHopfAlgCat.quotientSpecι_def, GeneralLinear.weightTorus_def]
  slice_lhs 2 3 =>
    rw [← (AlgebraicGeometry.hopfSpec (CommRingCat.of ℤ)).map_comp,
      ← op_comp, mkQuotient_comp_kostantWeightTorusTorusSubsystemCoordinateMap]

/-- Factoring the weight torus through nested subsystem carriers is natural in the selected
root set. -/
@[simp]
theorem kostantWeightTorusToTorusSubsystem_comp_mapOfSubset {S T : Set I}
    (hnilS : ∀ i : S, IsNilpotent
      (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i.1))))
    (hnilT : ∀ i : T, IsNilpotent
      (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i.1)))) (hST : S ⊆ T) :
    kostantWeightTorusToTorusSubsystem e h ρ M hM b wt S hnilS ≫
        kostantTorusSubsystemMapOfSubset e h ρ M hM b wt hnilS hnilT hST =
      kostantWeightTorusToTorusSubsystem e h ρ M hM b wt T hnilT := by
  apply (cancel_mono (kostantTorusSubsystemGroupSchemeι e h ρ M hM b wt T hnilT)).1
  rw [Category.assoc, kostantTorusSubsystemMapOfSubset_comp_ι,
    kostantWeightTorusToTorusSubsystem_comp_ι,
    kostantWeightTorusToTorusSubsystem_comp_ι]

/-- Factoring the weight torus through a subsystem and then into the full toral closure agrees
with the direct toral factorization. -/
@[simp]
theorem kostantWeightTorusToTorusSubsystem_comp_kostantTorusSubsystemToToral
    (hnil : ∀ i, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i))))
    (S : Set I) :
    kostantWeightTorusToTorusSubsystem e h ρ M hM b wt S (fun i => hnil i.1) ≫
        kostantTorusSubsystemToToral e h ρ M hM b wt hnil S =
      kostantWeightTorusToToral e h ρ M hM hnil b wt := by
  apply (cancel_mono (kostantToralGroupSchemeι e h ρ M hM hnil b wt)).1
  rw [Category.assoc, kostantTorusSubsystemToToral_comp_ι,
    kostantWeightTorusToTorusSubsystem_comp_ι, kostantWeightTorusToToral_comp_ι]

/-- **Universal property of the torus-subsystem carrier.** It is the smallest closed subgroup
scheme of the full toral closure through which every selected root-subgroup morphism and the
weight-torus morphism factor. Each factorization is unique because the arrow representing a
closed subgroup is a monomorphism. -/
theorem kostantTorusSubsystemClosedSubgroup_le_iff
    (hnil : ∀ i, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i))))
    (S : Set I)
    (P : ClosedSubgroupScheme (kostantToralGroupScheme e h ρ M hM hnil b wt)) :
    kostantTorusSubsystemClosedSubgroup e h ρ M hM b wt hnil S ≤ P ↔
      (∀ (i : I) (_hi : i ∈ S), ∃! f : AdditiveGroup.groupScheme ℤ ⟶
        (P.1 : Grp (Over (Spec (CommRingCat.of ℤ)))),
          f ≫ P.1.arrow = kostantRootSubgroupToToral e h ρ M hM hnil b wt i) ∧
      ∃! f : SplitTorus.groupScheme ℤ κ ⟶
        (P.1 : Grp (Over (Spec (CommRingCat.of ℤ)))),
          f ≫ P.1.arrow = kostantWeightTorusToToral e h ρ M hM hnil b wt := by
  rw [kostantTorusSubsystemClosedSubgroup_eq_quotientClosedSubgroup,
    kostantTorusSubsystemRelativeDefiningIdeal_eq_commonKernel]
  let p := kostantToralSubsystemGeneratorMap e h ρ M hM b wt hnil S
  have hminimal := CommHopfAlgCat.quotientClosedSubgroup_commonKernel_le_iff p P
  constructor
  · intro hle
    have hP := hminimal.mp hle
    constructor
    · intro i hi
      apply (CategoryTheory.Subobject.factors_iff_existsUnique P.1 _).mp
      rw [kostantRootSubgroupToToral_def, CategoryTheory.Subobject.factors_eqToHom_comp_iff]
      exact hP (.inl ⟨i, hi⟩)
    · apply (CategoryTheory.Subobject.factors_iff_existsUnique P.1 _).mp
      rw [kostantWeightTorusToToral_def, CategoryTheory.Subobject.factors_eqToHom_comp_iff]
      exact hP (.inr ())
  · rintro ⟨hroot, htorus⟩
    apply hminimal.mpr
    rintro (i | u)
    · have hi := (CategoryTheory.Subobject.factors_iff_existsUnique P.1 _).mpr (hroot i.1 i.2)
      rw [kostantRootSubgroupToToral_def, CategoryTheory.Subobject.factors_eqToHom_comp_iff] at hi
      exact hi
    · rcases u with ⟨⟩
      have ht := (CategoryTheory.Subobject.factors_iff_existsUnique P.1 _).mpr htorus
      rw [kostantWeightTorusToToral_def, CategoryTheory.Subobject.factors_eqToHom_comp_iff] at ht
      exact ht

/-- **Rigidity of a torus-subsystem group scheme.** Two homomorphisms out of the subsystem
carrier are equal when they agree on every selected root subgroup and on the weight torus. -/
@[ext]
theorem kostantTorusSubsystemGroupScheme_hom_ext {Y : _root_.CommHopfAlgCat.{0} ℤ}
    (S : Set I)
    (hnilS : ∀ i : S, IsNilpotent
      (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i.1))))
    (φ ψ : kostantTorusSubsystemGroupScheme e h ρ M hM b wt S hnilS ⟶
      (hopfSpec (CommRingCat.of ℤ)).obj (Opposite.op Y))
    (hroot : ∀ (i : I) (hi : i ∈ S),
      kostantRootSubgroupToTorusSubsystem e h ρ M hM b wt S hnilS hi ≫ φ =
        kostantRootSubgroupToTorusSubsystem e h ρ M hM b wt S hnilS hi ≫ ψ)
    (htorus : kostantWeightTorusToTorusSubsystem e h ρ M hM b wt S hnilS ≫ φ =
      kostantWeightTorusToTorusSubsystem e h ρ M hM b wt S hnilS ≫ ψ) :
    φ = ψ := by
  refine _root_.CommHopfAlgCat.hom_ext_of_preimage_unop_eq φ ψ
    (kostantTorusSubsystemCoordinate_hom_ext e h ρ M hM b wt S hnilS _ _
      (fun i hi => ?_) ?_)
  · refine _root_.CommHopfAlgCat.preimage_unop_comp_eq_of_hopfSpec_map_comp_eq _ φ ψ ?_
    have hi' := hroot i hi
    rw [kostantRootSubgroupToTorusSubsystem_def, Category.assoc, Category.assoc] at hi'
    exact (cancel_epi (eqToHom (AdditiveGroup.groupScheme_def ℤ))).1 hi'
  · refine _root_.CommHopfAlgCat.preimage_unop_comp_eq_of_hopfSpec_map_comp_eq _ φ ψ ?_
    rw [kostantWeightTorusToTorusSubsystem_def, Category.assoc, Category.assoc] at htorus
    exact (cancel_epi (eqToHom
      (DiagonalizableGroup.groupScheme_def ℤ (SplitTorus.characterGroup κ)))).1 htorus

end EpsilonEridani.UniversalEnvelopingAlgebra
