/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.Algebra.Lie.Sl2.Classification
import EpsilonEridani.Algebra.Lie.Basic
import EpsilonEridani.Algebra.Lie.Submodule.Atom

/-!
# The Casimir operator of an `sl₂` triple

For an `sl₂` triple `t : IsSl2Triple h e f` in a Lie algebra `L` over a field `K` in which `2` is
nonzero, and an `L`-module `M`, the **Casimir operator** is the second-order operator

`Ω = e f + f e + h² / 2`

built from the action of the three elements of the triple on `M`. It is not the image of an element
of `L`; it is a quadratic expression in the action, and its point is that it *commutes with the
whole action*. The commutation is a short calculation from the relations `⁅e, f⁆ = h`,
`⁅h, e⁆ = 2e`, `⁅h, f⁆ = -2f` alone, so — unlike the Casimir element of a general semisimple Lie
algebra — it needs neither the universal enveloping algebra nor the Killing form, and is available
at this, the bottom, layer of the theory.

On a primitive vector of weight `n` the operator acts by the scalar `n (n + 2) / 2`
(`EpsilonEridani.sl2Casimir_apply_of_hasPrimitiveVectorWith`), which vanishes exactly when `n = 0`, that is
exactly on the trivial module `V(0)`. That dichotomy is the whole content of the operator:
`EpsilonEridani.sl2Casimir_injective` turns it into the statement that on an irreducible module on which
`L` acts at all, the Casimir operator is injective.

## Main definitions

* `EpsilonEridani.sl2Casimir`: the Casimir operator `e f + f e + h² / 2` of a triple, as an endomorphism
  of a module.
* `EpsilonEridani.sl2CasimirHom`: the Casimir operator as a morphism of `L`-modules, available
  once the triple generates `L`, so that its kernel is a Lie submodule.

## Main results

* `EpsilonEridani.lie_sl2Casimir`: **the Casimir operator commutes with the action** of every element of
  the subalgebra generated by the triple.
* `EpsilonEridani.sl2Casimir_apply_of_hasPrimitiveVectorWith`: the Casimir operator acts on a primitive
  vector of weight `n` by the scalar `n (n + 2) / 2`.
* `EpsilonEridani.sl2Casimir_injective`: **the Casimir operator of a nontrivial irreducible module is
  injective.**

## Implementation notes

Neither definition is exposed: `EpsilonEridani.sl2Casimir_apply` and `EpsilonEridani.sl2CasimirHom_apply`
characterise both completely, so nothing downstream needs to unfold further. Those two equations
are proved by the parenthesised `(rfl)`, which elaborates against the definitions themselves; a
bare `rfl` in an exported theorem would demand that they be `@[expose]`d.

## References

This is Layer 0 of `EpsilonEridaniRoadmap/RepresentationTheory/LieHighestWeight/README.md`.

* [J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*][humphreys1972],
  §6.2 and §7.2.
-/

public section

namespace EpsilonEridani

open LieModule Module

/-! ### The operator -/

section Defs

variable {L : Type*} [LieRing L]

variable (K) in
/-- The **Casimir operator** `e f + f e + h² / 2` of a triple `(h, e, f)`, acting on an `L`-module
`M` through the action of the three elements of the triple.

The formula makes sense over any field. The operator is worth naming only for an `sl₂` triple,
where `EpsilonEridani.lie_sl2Casimir` says it commutes with the action of the subalgebra the triple
generates; its coefficient `1 / 2` on `h²` is forced by that commutation, which is why the
commutation results — and not this definition — ask that `2` be nonzero. -/
noncomputable def sl2Casimir [Field K] [LieAlgebra K L] (h e f : L) (M : Type*)
    [AddCommGroup M] [Module K M] [LieRingModule L M] [LieModule K L M] : Module.End K M :=
  toEnd K L M e ∘ₗ toEnd K L M f + toEnd K L M f ∘ₗ toEnd K L M e +
    (2 : K)⁻¹ • (toEnd K L M h ∘ₗ toEnd K L M h)

variable {K : Type*} [Field K] [LieAlgebra K L]
variable {M : Type*} [AddCommGroup M] [Module K M] [LieRingModule L M] [LieModule K L M]
variable {h e f : L}

@[simp]
theorem sl2Casimir_apply (m : M) :
    sl2Casimir K h e f M m = ⁅e, ⁅f, m⁆⁆ + ⁅f, ⁅e, m⁆⁆ + (2 : K)⁻¹ • ⁅h, ⁅h, m⁆⁆ :=
  (rfl)

/-- The Casimir operator is unchanged by the symmetry `(h, e, f) ↦ (-h, f, e)` of an `sl₂` triple,
which merely exchanges the two off-diagonal terms and squares the sign on `h`. -/
theorem sl2Casimir_neg_swap : sl2Casimir K (-h) f e M = sl2Casimir K h e f M := by
  ext m
  simp only [sl2Casimir_apply, neg_lie, lie_neg, neg_neg]
  abel

/-- The Casimir operator of a Lie submodule is the restriction of the Casimir operator of the
ambient module: both are built from the same brackets. -/
theorem coe_sl2Casimir_lieSubmodule {N : LieSubmodule K L M} (v : N) :
    (sl2Casimir K h e f N v : M) = sl2Casimir K h e f M (v : M) := by
  simp

end Defs

/-! ### Commutation with the action -/

section Commute

variable {K : Type*} [Field K] [NeZero (2 : K)]
variable {L : Type*} [LieRing L] [LieAlgebra K L]
variable {M : Type*} [AddCommGroup M] [Module K M] [LieRingModule L M] [LieModule K L M]
variable {h e f : L} (t : IsSl2Triple h e f)
include t

omit [NeZero (2 : K)] in
/-- The Casimir operator commutes with the action of the Cartan element `h`. Each of the three
terms is separately preserved: `h` raises the weight by `2` on passing `e` and lowers it by `2` on
passing `f`, and each term of `e f + f e + h²/2` pairs a raising with a lowering step. -/
theorem lie_h_sl2Casimir (m : M) :
    ⁅h, sl2Casimir K h e f M m⁆ = sl2Casimir K h e f M ⁅h, m⁆ := by
  have key : ∀ (a b : L) (ca cb : K), ca + cb = 0 → ⁅h, a⁆ = ca • a → ⁅h, b⁆ = cb • b →
      ⁅h, ⁅a, ⁅b, m⁆⁆⁆ = ⁅a, ⁅b, ⁅h, m⁆⁆⁆ := by
    intro a b ca cb hsum ha hb
    rw [leibniz_lie h a ⁅b, m⁆, ha, leibniz_lie h b m, hb, lie_add]
    simp only [smul_lie, lie_smul]
    rw [← add_assoc, ← add_smul, hsum, zero_smul, zero_add]
  have hhe : ⁅h, e⁆ = (2 : K) • e := t.lie_h_e_smul K
  have hhf : ⁅h, f⁆ = (-2 : K) • f := by rw [t.lie_lie_smul_f K, neg_smul]
  simp only [sl2Casimir_apply, lie_add, lie_smul, key e f 2 (-2) (by ring) hhe hhf,
    key f e (-2) 2 (by ring) hhf hhe]

/-- The Casimir operator commutes with the action of the raising element `e`. This is the
calculation that fixes the coefficient `1 / 2` on `h²`: moving `e` past `e f + f e` produces
`⁅e, ⁅h, m⁆⁆ + ⁅h, ⁅e, m⁆⁆`, and moving it past `h² / 2` produces exactly the negative of that. -/
theorem lie_e_sl2Casimir (m : M) :
    ⁅e, sl2Casimir K h e f M m⁆ = sl2Casimir K h e f M ⁅e, m⁆ := by
  have htwo : ∀ y : M, (2 : K)⁻¹ • ((2 : K) • y) = y := fun y ↦ by
    rw [smul_smul, inv_mul_cancel₀ (two_ne_zero : (2 : K) ≠ 0), one_smul]
  have heh : ⁅e, h⁆ = -((2 : K) • e) := by rw [← lie_skew e h, t.lie_h_e_smul K]
  have h₁ : ⁅e, ⁅e, ⁅f, m⁆⁆⁆ = ⁅e, ⁅h, m⁆⁆ + ⁅e, ⁅f, ⁅e, m⁆⁆⁆ := by
    rw [leibniz_lie e f m, t.lie_e_f, lie_add]
  have h₂ : ⁅e, ⁅f, ⁅e, m⁆⁆⁆ = ⁅h, ⁅e, m⁆⁆ + ⁅f, ⁅e, ⁅e, m⁆⁆⁆ := by
    rw [leibniz_lie e f ⁅e, m⁆, t.lie_e_f]
  have hinner : ⁅e, ⁅h, m⁆⁆ = -((2 : K) • ⁅e, m⁆) + ⁅h, ⁅e, m⁆⁆ := by
    rw [leibniz_lie e h m, heh, neg_lie, smul_lie]
  have hA : ⁅e, ⁅h, ⁅h, m⁆⁆⁆ = -((2 : K) • ⁅e, ⁅h, m⁆⁆) + ⁅h, ⁅e, ⁅h, m⁆⁆⁆ := by
    rw [leibniz_lie e h ⁅h, m⁆, heh, neg_lie, smul_lie]
  have hB : ⁅h, ⁅e, ⁅h, m⁆⁆⁆ = -((2 : K) • ⁅h, ⁅e, m⁆⁆) + ⁅h, ⁅h, ⁅e, m⁆⁆⁆ := by
    rw [hinner, lie_add, lie_neg, lie_smul]
  have h₃ : (2 : K)⁻¹ • ⁅e, ⁅h, ⁅h, m⁆⁆⁆
      = -⁅e, ⁅h, m⁆⁆ + (-⁅h, ⁅e, m⁆⁆ + (2 : K)⁻¹ • ⁅h, ⁅h, ⁅e, m⁆⁆⁆) := by
    rw [hA, hB]
    simp only [smul_add, smul_neg, htwo]
  simp only [sl2Casimir_apply, lie_add, lie_smul, h₁, h₂, h₃]
  abel

/-- The Casimir operator commutes with the action of the lowering element `f`, by the symmetry
`EpsilonEridani.sl2Casimir_neg_swap` of the operator under `(h, e, f) ↦ (-h, f, e)`. -/
theorem lie_f_sl2Casimir (m : M) :
    ⁅f, sl2Casimir K h e f M m⁆ = sl2Casimir K h e f M ⁅f, m⁆ := by
  have := lie_e_sl2Casimir t.symm (K := K) (M := M) m
  rwa [sl2Casimir_neg_swap] at this

/-- **The Casimir operator commutes with the action.** Every element of the subalgebra generated by
the triple commutes with the Casimir operator, since the three generators do and the statement is
linear in the element. -/
theorem lie_sl2Casimir {x : L} (hx : x ∈ t.toLieSubalgebra K) (m : M) :
    ⁅x, sl2Casimir K h e f M m⁆ = sl2Casimir K h e f M ⁅x, m⁆ := by
  obtain ⟨c₁, c₂, c₃, rfl⟩ := IsSl2Triple.mem_toLieSubalgebra_iff.1 hx
  rw [t.lie_e_f]
  simp only [add_lie, smul_lie, map_add, map_smul, lie_e_sl2Casimir t, lie_f_sl2Casimir t,
    lie_h_sl2Casimir t]

end Commute

/-! ### The Casimir operator as a morphism of modules -/

section Hom

variable {K : Type*} [Field K] [NeZero (2 : K)]
variable {L : Type*} [LieRing L] [LieAlgebra K L]
variable {h e f : L}

/-- The Casimir operator as a morphism of `L`-modules, for a Lie algebra `L` generated by the
triple. Bundling it this way makes its kernel a Lie submodule, which is what lets
`EpsilonEridani.sl2Casimir_injective` play irreducibility against it. Over an ambient `L` that the triple
does not generate the operator is still `t.toLieSubalgebra K`-equivariant, by
`EpsilonEridani.lie_sl2Casimir`, but no more. -/
noncomputable def sl2CasimirHom (t : IsSl2Triple h e f)
    (htop : t.toLieSubalgebra K = ⊤) (M : Type*) [AddCommGroup M] [Module K M] [LieRingModule L M]
    [LieModule K L M] : M →ₗ⁅K,L⁆ M where
  __ := sl2Casimir K h e f M
  map_lie' {x m} := (lie_sl2Casimir t (htop ▸ LieSubalgebra.mem_top x) m).symm

variable {M : Type*} [AddCommGroup M] [Module K M] [LieRingModule L M] [LieModule K L M]
variable (t : IsSl2Triple h e f) (htop : t.toLieSubalgebra K = ⊤)

@[simp]
theorem sl2CasimirHom_apply (m : M) : sl2CasimirHom t htop M m = sl2Casimir K h e f M m :=
  (rfl)

end Hom

/-! ### The Casimir scalar of a highest weight vector -/

section Scalar

variable {K : Type*} [Field K] [NeZero (2 : K)]
variable {L : Type*} [LieRing L] [LieAlgebra K L]
variable {M : Type*} [AddCommGroup M] [Module K M] [LieRingModule L M] [LieModule K L M]
variable {h e f : L} {t : IsSl2Triple h e f} {m : M} {n : ℕ}

/-- **The Casimir scalar of a highest weight vector.** A primitive vector of weight `n` is an
eigenvector of the Casimir operator with eigenvalue `n (n + 2) / 2`: the raising operator kills it,
so `f e` contributes nothing, `e f` contributes `⁅h, m⁆ = n m`, and `h²` contributes `n² m`. -/
theorem sl2Casimir_apply_of_hasPrimitiveVectorWith (P : t.HasPrimitiveVectorWith m (n : K)) :
    sl2Casimir K h e f M m = ((n : K) * (n + 2) / 2) • m := by
  have hef : ⁅e, ⁅f, m⁆⁆ = (n : K) • m := by
    rw [leibniz_lie e f m, t.lie_e_f, P.lie_e, lie_zero, add_zero, P.lie_h]
  have hhh : ⁅h, ⁅h, m⁆⁆ = ((n : K) * n) • m := by
    rw [P.lie_h, lie_smul, P.lie_h, smul_smul]
  have h2 : (2 : K) ≠ 0 := two_ne_zero
  rw [sl2Casimir_apply, hef, hhh, P.lie_e, lie_zero, add_zero, smul_smul, ← add_smul]
  congr 1
  field_simp
  ring

/-- The Casimir scalar `n (n + 2) / 2` vanishes only for `n = 0`: on an irreducible module the
Casimir operator is therefore zero exactly on the trivial module `V(0)`. -/
theorem sl2CasimirScalar_ne_zero {K : Type*} [Field K] [CharZero K] {n : ℕ} (hn : n ≠ 0) :
    ((n : K) * (n + 2) / 2) ≠ 0 := by
  have hn' : (n : K) ≠ 0 := Nat.cast_ne_zero.2 hn
  have h₂ : (n : K) + 2 ≠ 0 := by
    have : ((n + 2 : ℕ) : K) ≠ 0 := Nat.cast_ne_zero.2 (by omega)
    push_cast at this
    exact this
  exact div_ne_zero (mul_ne_zero hn' h₂) (by norm_num)

/-- The Casimir scalar `n (n + 2) / 2` determines the natural number `n`: the scalar is
`((n + 1)² - 1)/2` and `n + 1` is positive. -/
theorem sl2CasimirScalar_injective {K : Type*} [Field K] [CharZero K] :
    Function.Injective fun q : ℕ ↦ (q : K) * ((q : K) + 2) / 2 := by
  intro p q hpq
  simp only at hpq
  rw [div_eq_div_iff two_ne_zero two_ne_zero] at hpq
  have hfac : ((p : K) - q) * ((p : K) + q + 2) = 0 := by linear_combination hpq / 2
  refine Nat.cast_injective (R := K)
    (sub_eq_zero.1 ((mul_eq_zero.1 hfac).resolve_right fun hc ↦ ?_))
  have hz : ((p + q + 2 : ℕ) : K) = 0 := by push_cast; linear_combination hc
  exact absurd (Nat.cast_eq_zero.1 hz) (by omega)

end Scalar

/-! ### Injectivity on a nontrivial irreducible -/

section Irreducible

variable {K : Type*} [Field K] [CharZero K]
variable {L : Type*} [LieRing L] [LieAlgebra K L]
variable {M : Type*} [AddCommGroup M] [Module K M] [LieRingModule L M] [LieModule K L M]
variable {h e f : L} {t : IsSl2Triple h e f}

/-- **A highest weight vector of weight zero of an irreducible module is invariant, so the module
is trivial.** The weight string of such a vector stops at once, so all three generators of `L` kill
it; its invariants are therefore a nonzero Lie submodule, hence everything. -/
theorem lie_eq_zero_of_hasPrimitiveVectorWith_zero (htop : t.toLieSubalgebra K = ⊤)
    [IsTorsionFree K M] [IsNoetherian K M] [LieModule.IsIrreducible K L M] {m : M}
    (P : t.HasPrimitiveVectorWith m (0 : K)) (x : L) (v : M) : ⁅x, v⁆ = 0 := by
  have hfm : ⁅f, m⁆ = 0 := by
    have := P.pow_toEnd_f_eq_zero_of_eq_nat (n := 0) (by simp)
    simpa using this
  have hgen : ∀ y : L, ⁅y, m⁆ = 0 := by
    intro y
    obtain ⟨c₁, c₂, c₃, rfl⟩ :=
      IsSl2Triple.mem_toLieSubalgebra_iff.1 (htop ▸ LieSubalgebra.mem_top y)
    rw [t.lie_e_f]
    simp [P.lie_e, hfm, P.lie_h]
  exact (isTrivial_of_forall_lie_eq_zero_of_lieSpan_eq_top hgen
    (lieSpan_singleton_eq_top_of_ne_zero (R := K) (L := L) (M := M) P.ne_zero)).trivial x v

/-- **The Casimir operator of a nontrivial irreducible module is injective.** An irreducible module
has a primitive vector of some weight `n : ℕ`, on which the Casimir operator acts by
`n (n + 2) / 2`. If `n = 0` the module is trivial, which is excluded; otherwise that scalar is
nonzero, so the kernel of the Casimir operator is a proper Lie submodule, hence zero. -/
theorem sl2Casimir_injective (htop : t.toLieSubalgebra K = ⊤) [FiniteDimensional K M]
    [IsTriangularizable K L M] [LieModule.IsIrreducible K L M]
    (hact : ∃ (x : L) (v : M), ⁅x, v⁆ ≠ 0) :
    Function.Injective (sl2Casimir K h e f M) := by
  have : Nontrivial M := LieModule.nontrivial_of_isIrreducible K L M
  obtain ⟨w, n, P⟩ := exists_hasPrimitiveVectorWith (K := K) M t
  have hn : n ≠ 0 := by
    rintro rfl
    obtain ⟨x, v, hv⟩ := hact
    exact hv (lie_eq_zero_of_hasPrimitiveVectorWith_zero htop (by simpa using P) x v)
  have hw : sl2Casimir K h e f M w ≠ 0 := by
    rw [sl2Casimir_apply_of_hasPrimitiveVectorWith P]
    exact smul_ne_zero (sl2CasimirScalar_ne_zero hn) P.ne_zero
  have hker : (sl2CasimirHom t htop M).ker = ⊥ := by
    refine (IsSimpleOrder.eq_bot_or_eq_top _).resolve_right fun hcon ↦ hw ?_
    have : w ∈ (sl2CasimirHom t htop M).ker := hcon ▸ LieSubmodule.mem_top w
    simpa using this
  intro a b hab
  exact (LieModuleHom.ker_eq_bot _).1 hker (by simpa using hab)

end Irreducible

end EpsilonEridani
