/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.Algebra.Lie.Sl2.Standard

/-!
# The classification of the finite-dimensional irreducible `sl₂`-modules

`EpsilonEridani/Algebra/Lie/Sl2/WeightString.lean` shows that a module carrying a primitive vector of
weight `n : ℕ` and irreducible over the subalgebra of an `sl₂` triple is determined by `n`, and
`EpsilonEridani/Algebra/Lie/Sl2/Standard.lean` exhibits such a module, `EpsilonEridani.Sl2Std K n = V(n)`, for
every `n`. What neither file supplies is the remaining half of the classification: that a
finite-dimensional irreducible module *has* a primitive vector at all. This file supplies it and
draws the classification.

The argument is the standard one, and Mathlib runs it: over a triangularizable module the Cartan
element `h` has an eigenvector which the raising operator pushes up the `h`-spectrum by `2` at a
time until it dies, leaving a primitive vector (`IsSl2Triple.exists_hasPrimitiveVectorWith`). All
that is added here is that `IsSl2Triple.HasPrimitiveVectorWith.exists_nat` makes the weight a
natural number.

Triangularizability is carried as a hypothesis rather than bought with an algebraically closed
field: over such a field a finite-dimensional module is triangularizable by Mathlib's
`LieModule.instIsTriangularizableOfIsAlgClosed`, so the algebraically closed case is these
statements with that instance supplied by inference, and needs no separate form.

Note that no irreducibility is needed for the existence of a primitive vector: a nonzero
triangularizable Noetherian module suffices. Irreducibility enters only when the weight string of
that vector is asked to be the whole module.

Both halves are stated for an arbitrary Lie algebra `L` generated by an `sl₂` triple, and then
specialized to `sl (Fin 2) K` with its standard triple, where they say that every
finite-dimensional triangularizable irreducible module is `V(n)` for exactly one `n`.

## Main results

* `EpsilonEridani.exists_hasPrimitiveVectorWith`: **every nonzero triangularizable module over an `sl₂`
  triple has a primitive vector**, of weight a natural number.
* `EpsilonEridani.existsUnique_nat_hasPrimitiveVectorWith`: **the classification by highest weight.** A
  triangularizable irreducible module over a Lie algebra generated by an `sl₂` triple has exactly
  one highest weight `n : ℕ`, and `EpsilonEridani.finrank_eq_of_hasPrimitiveVectorWith_of_eq_top` computes
  its dimension as `n + 1`.
* `EpsilonEridani.nonempty_lieModuleEquiv_of_hasPrimitiveVectorWith`: **the highest weight determines the
  module**, now as an equivalence over the whole of `L` rather than over the subalgebra of the
  triple.
* `EpsilonEridani.Sl2Std.existsUnique_nonempty_lieModuleEquiv`: **the classification for `sl (Fin 2) K`.**
  A finite-dimensional triangularizable irreducible `sl (Fin 2) K`-module is equivalent to `V(n)`
  for exactly one `n : ℕ`.
* `EpsilonEridani.Sl2Std.exists_eq_sub_two_mul_of_hasEigenvalue`: every weight of such a module is among
  `n, n - 2, …, -n`. That its weights are in particular integers holds for an arbitrary
  finite-dimensional module, irreducible or not, and is
  `EpsilonEridani.exists_int_of_hasEigenvalue_slFinTwo` in
  `EpsilonEridani/Algebra/Lie/Sl2/Spectrum.lean`.

## References

This is Layer 0 of `EpsilonEridaniRoadmap/RepresentationTheory/LieHighestWeight/README.md`, whose
`exists_hasPrimitiveVectorWith` is `EpsilonEridani.exists_hasPrimitiveVectorWith`.

* [J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*][humphreys1972],
  §7.2.
-/

public section

namespace EpsilonEridani

open LieModule Module

/-! ### Existence of a primitive vector -/

section Triangularizable

variable {K : Type*} [CommRing K] [IsDomain K] [CharZero K]
variable {L : Type*} [LieRing L] [LieAlgebra K L]
variable {M : Type*} [AddCommGroup M] [Module K M] [LieRingModule L M] [LieModule K L M]
  [IsTorsionFree K M] [IsNoetherian K M]
variable {h e f : L}

variable (M) in
/-- **Existence of a primitive vector.** Every nonzero triangularizable module over an `sl₂` triple
carries a primitive vector, and its weight is a natural number.

This is the half of the classification of the finite-dimensional irreducible `sl₂`-modules that
`EpsilonEridani.exists_isIrreducible_hasPrimitiveVectorWith` leaves open. Irreducibility is not needed:
the eigenvector triangularizability supplies can be raised in any module at all. It refines
Mathlib's `IsSl2Triple.exists_hasPrimitiveVectorWith`, which produces a primitive vector of some
weight in `K`, by pinning that weight down to a natural number.

Over an algebraically closed field a finite-dimensional module is triangularizable, so there the
`LieModule.IsTriangularizable` hypothesis is discharged by instance inference. -/
theorem exists_hasPrimitiveVectorWith [Nontrivial M] [IsTriangularizable K L M]
    (t : IsSl2Triple h e f) :
    ∃ (w : M) (n : ℕ), t.HasPrimitiveVectorWith w (n : K) := by
  obtain ⟨μ, w, -, P⟩ := t.exists_hasPrimitiveVectorWith (R := K) (M := M)
  obtain ⟨n, hn⟩ := P.exists_nat
  exact ⟨w, n, hn ▸ P⟩

end Triangularizable

/-! ### The classification over a Lie algebra generated by a triple -/

section Generated

variable {K : Type*} [CommRing K] [IsDomain K] [CharZero K]
variable {L : Type*} [LieRing L] [LieAlgebra K L]
variable {M : Type*} [AddCommGroup M] [Module K M] [LieRingModule L M] [LieModule K L M]
  [IsTorsionFree K M] [IsNoetherian K M]
variable {h e f : L} {t : IsSl2Triple h e f} {m : M} {n : ℕ}

/-- **The rank of an irreducible with a given highest weight.** A module irreducible over a Lie
algebra generated by an `sl₂` triple, carrying a primitive vector of weight `n`, has rank `n + 1`.
This is `EpsilonEridani.finrank_eq_of_hasPrimitiveVectorWith` with the irreducibility hypothesis moved
from the subalgebra of the triple to the whole algebra, which generates it. -/
theorem finrank_eq_of_hasPrimitiveVectorWith_of_eq_top (htop : t.toLieSubalgebra K = ⊤)
    [LieModule.IsIrreducible K L M] (P : t.HasPrimitiveVectorWith m (n : K)) :
    finrank K M = n + 1 :=
  have := isIrreducible_of_eq_top (M := M) htop
  finrank_eq_of_hasPrimitiveVectorWith P

variable {M' : Type*} [AddCommGroup M'] [Module K M'] [LieRingModule L M'] [LieModule K L M']
  [IsTorsionFree K M'] [IsNoetherian K M'] {m' : M'}

/-- **The highest weight determines the irreducible, over the whole algebra.** Two modules
irreducible over a Lie algebra generated by an `sl₂` triple, carrying primitive vectors of the same
weight `n`, are equivalent as `L`-modules.

`EpsilonEridani.lieModuleEquivOfHasPrimitiveVectorWith` proves this over the subalgebra generated by the
triple, which is the correct hypothesis in general; when that subalgebra is everything,
`EpsilonEridani.lieModuleEquivOfEqTop` upgrades the conclusion to the ambient algebra. -/
theorem nonempty_lieModuleEquiv_of_hasPrimitiveVectorWith (htop : t.toLieSubalgebra K = ⊤)
    [LieModule.IsIrreducible K L M] [LieModule.IsIrreducible K L M']
    (P : t.HasPrimitiveVectorWith m (n : K)) (P' : t.HasPrimitiveVectorWith m' (n : K)) :
    Nonempty (M ≃ₗ⁅K,L⁆ M') :=
  have := isIrreducible_of_eq_top (M := M) htop
  have := isIrreducible_of_eq_top (M := M') htop
  ⟨lieModuleEquivOfEqTop htop (lieModuleEquivOfHasPrimitiveVectorWith P P')⟩

variable (M) in
/-- **The classification by highest weight.** A triangularizable irreducible module over a Lie
algebra generated by an `sl₂` triple has exactly one highest weight, a natural number: one exists
by `EpsilonEridani.exists_hasPrimitiveVectorWith`, and two would force two values on the dimension of `M`.

Together with `EpsilonEridani.finrank_eq_of_hasPrimitiveVectorWith_of_eq_top`,
`EpsilonEridani.nonempty_lieModuleEquiv_of_hasPrimitiveVectorWith` and
`EpsilonEridani.exists_isIrreducible_hasPrimitiveVectorWith` this is the classification: a triangularizable
irreducible has a highest weight `n : ℕ`, which determines it and gives it dimension `n + 1`, and
every natural number occurs as such a weight. -/
theorem existsUnique_nat_hasPrimitiveVectorWith (htop : t.toLieSubalgebra K = ⊤)
    [IsTriangularizable K L M] [LieModule.IsIrreducible K L M] :
    ∃! n : ℕ, ∃ w : M, t.HasPrimitiveVectorWith w (n : K) := by
  have : Nontrivial M := LieModule.nontrivial_of_isIrreducible K L M
  obtain ⟨w, n, P⟩ := exists_hasPrimitiveVectorWith (K := K) M t
  refine ⟨n, ⟨w, P⟩, fun n' ⟨w', P'⟩ ↦ ?_⟩
  have h₁ := finrank_eq_of_hasPrimitiveVectorWith_of_eq_top htop P
  have h₂ := finrank_eq_of_hasPrimitiveVectorWith_of_eq_top htop P'
  omega

end Generated

/-! ### The classification for `sl (Fin 2) K` -/

namespace Sl2Std

open LieAlgebra

variable {K : Type*} [Field K]
variable {M : Type*} [AddCommGroup M] [Module K M]
  [LieRingModule (SpecialLinear.sl (Fin 2) K) M]

/-- **`V(m)` and `V(n)` are not even linearly isomorphic unless `m = n`**, their dimensions being
`m + 1` and `n + 1`. -/
theorem eq_of_linearEquiv {m n : ℕ} (φ : Sl2Std K m ≃ₗ[K] Sl2Std K n) : m = n := by
  have hrank := φ.finrank_eq
  rw [finrank_eq, finrank_eq] at hrank
  omega

variable [LieModule K (SpecialLinear.sl (Fin 2) K) M]
variable {n : ℕ}

/-- **The weights of a module equivalent to `V(n)`.** An eigenvalue of the Cartan element
`h = E₀₀ - E₁₁` on such a module is one of `n, n - 2, …, -n`: the
equivalence carries an eigenvector to an eigenvector, and `EpsilonEridani.Sl2Std.eigenspace_diag_eq_bot`
says `V(n)` has no other weights. -/
theorem exists_eq_sub_two_mul_of_hasEigenvalue
    (φ : M ≃ₗ⁅K,SpecialLinear.sl (Fin 2) K⁆ Sl2Std K n) {μ : K}
    (hμ : (toEnd K (SpecialLinear.sl (Fin 2) K) M (slFinTwoBasis K 2)).HasEigenvalue μ) :
    ∃ i : Fin (n + 1), μ = (n : K) - 2 * (i : ℕ) := by
  by_contra! hcon
  obtain ⟨v, hv⟩ := hμ.exists_hasEigenvector
  have hlie : ⁅slFinTwoBasis K 2, v⁆ = μ • v := by
    simpa using Module.End.mem_eigenspace_iff.1 hv.1
  have hφ : φ ⁅slFinTwoBasis K 2, v⁆ = ⁅slFinTwoBasis K 2, φ v⁆ := φ.map_lie _ v
  have hmem : φ v ∈ Module.End.eigenspace (diag K n) μ := by
    refine Module.End.mem_eigenspace_iff.2 ?_
    rw [← lie_slFinTwoBasis_two, ← hφ, hlie, map_smul]
  rw [eigenspace_diag_eq_bot hcon] at hmem
  exact hv.2 (EquivLike.injective φ (by rw [(Submodule.mem_bot K).1 hmem, map_zero]))

variable [CharZero K]

variable (M) in
/-- **The classification of the finite-dimensional irreducible `sl₂`-modules.** Over a field of
characteristic zero, a finite-dimensional triangularizable irreducible `sl (Fin 2) K`-module is
equivalent to the standard module `V(n)` for exactly one `n : ℕ`. Over an algebraically closed
field triangularizability is automatic, so this reads as the classification of all the
finite-dimensional irreducibles.

The proof is the two halves meeting: `EpsilonEridani.exists_hasPrimitiveVectorWith` produces a primitive
vector of weight `n`, and `EpsilonEridani.Sl2Std.lieModuleEquiv` matches its weight string with that of
`V(n)`. Uniqueness of `n` is `EpsilonEridani.Sl2Std.eq_of_linearEquiv`. -/
theorem existsUnique_nonempty_lieModuleEquiv [FiniteDimensional K M]
    [IsTriangularizable K (SpecialLinear.sl (Fin 2) K) M]
    [LieModule.IsIrreducible K (SpecialLinear.sl (Fin 2) K) M] :
    ∃! n : ℕ, Nonempty (M ≃ₗ⁅K,SpecialLinear.sl (Fin 2) K⁆ Sl2Std K n) := by
  have htop := toLieSubalgebra_isSl2Triple_single_eq_top (R := K) (zero_ne_one : (0 : Fin 2) ≠ 1)
  have : Nontrivial M :=
    LieModule.nontrivial_of_isIrreducible K (SpecialLinear.sl (Fin 2) K) M
  have := isIrreducible_of_eq_top (M := M) htop
  obtain ⟨w, n, P⟩ := exists_hasPrimitiveVectorWith (K := K) M
    (isSl2Triple_single (R := K) (zero_ne_one : (0 : Fin 2) ≠ 1))
  refine ⟨n, ⟨lieModuleEquivOfEqTop htop (lieModuleEquiv P)⟩, fun n' ⟨ψ⟩ ↦ ?_⟩
  exact eq_of_linearEquiv
    (ψ.symm.trans (lieModuleEquivOfEqTop htop (lieModuleEquiv P))).toLinearEquiv

end Sl2Std

end EpsilonEridani
