/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.Algebra.Lie.Sl2.CompleteReducibility

/-!
# The spectrum of the Cartan element of an `sl₂` triple

Fix an `sl₂` triple `t : IsSl2Triple h e f` in a Lie algebra `L` and a finite-dimensional
`L`-module `M`. This file describes the spectrum of `h` on `M`: its eigenvalues are **integers**,
and — once the base field is algebraically closed — the eigenspaces **span** `M`, so `h` acts
diagonalizably.

Mathlib's `IsSl2Triple.HasPrimitiveVectorWith.exists_nat` pins the weight of a *primitive* vector
to a natural number, and `EpsilonEridani/Algebra/Lie/Sl2/Classification.lean` reads the whole spectrum off
the classification for an *irreducible* module. Neither covers an arbitrary module: an eigenvector
of `h` need not be primitive, and a general module is not irreducible. The gap is closed by raising:
the raising operator `e` moves the `μ`-eigenspace into the `μ + 2`-eigenspace, so applying it
repeatedly to an eigenvector either produces eigenvectors for the infinitely many distinct
eigenvalues `μ, μ + 2, μ + 4, …` — impossible in finite dimension — or dies, and the last nonzero
vector is a primitive vector of weight `μ + 2k`. Since that weight is a natural number `n`, the
original eigenvalue is `μ = n - 2k`, an integer.

That argument needs neither irreducibility nor an algebraically closed field: it works over any
field of characteristic zero, which matters because it is exactly the form in which the
highest-weight theory consumes it, restricting a module over a semisimple Lie algebra to the `sl₂`
triple attached to a root in order to prove that weights pair integrally with coroots.

Diagonalizability is a genuinely stronger statement and costs more. The sum of the eigenspaces of
`h` is a Lie submodule for the subalgebra `t.toLieSubalgebra K` generated by the triple (`e`, `f`
and `h` shift the eigenvalue by `2`, `-2` and `0`), so complete reducibility,
`EpsilonEridani.exists_isCompl_of_toLieSubalgebra_eq_top`, supplies a complementary Lie submodule; over an
algebraically closed field a nonzero complement would contain an eigenvector of `h`, which already
lies in the sum. Hence the complement vanishes and the eigenspaces exhaust `M`. Only here is
`IsAlgClosed` needed. Since everything happens over the subalgebra generated by the triple — which
that triple does generate — the triple itself need not generate the ambient `L`.

## Main results

* `EpsilonEridani.exists_hasPrimitiveVectorWith_pow_toEnd_e`: **raising an eigenvector to a primitive
  vector.** Some power of the raising operator carries an `h`-eigenvector of weight `μ` to a
  primitive vector of weight `μ + 2k`.
* `EpsilonEridani.exists_int_of_hasEigenvalue`: **the integer spectrum.** Every eigenvalue of the Cartan
  element of an `sl₂` triple on a finite-dimensional module is an integer. Its refinement
  `EpsilonEridani.exists_nat_sub_two_mul_of_lie_h_eq_smul` exhibits the eigenvalue as `n - 2k` with
  `n k : ℕ`.
* `EpsilonEridani.eigenspace_toEnd_eq_bot_of_forall_ne_intCast`: the eigenspaces at non-integer scalars
  vanish.
* `EpsilonEridani.iSup_eigenspace_toEnd_eq_top`: **diagonalizability.** Over an algebraically closed field
  of characteristic zero, the eigenspaces of the Cartan element of an `sl₂` triple span the
  module.
* `EpsilonEridani.iSup_eigenspace_toEnd_intCast_eq_top` and
  `EpsilonEridani.isInternal_eigenspace_toEnd_intCast`: the two halves combined — such a module is the
  internal direct sum of the eigenspaces at the *integers*.

## References

This is the "diagonalizability and the integer spectrum" bullet of Layer 0 of
`EpsilonEridaniRoadmap/RepresentationTheory/LieHighestWeight/README.md`, whose
`sl2_hAction_eigenvalue_isInt` is `EpsilonEridani.exists_int_of_hasEigenvalue`.

* [J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*][humphreys1972],
  §7.2.

The raising argument in `EpsilonEridani.exists_hasPrimitiveVectorWith_pow_toEnd_e` follows the proof of
Mathlib's `IsSl2Triple.exists_hasPrimitiveVectorWith`, which runs it from an eigenvector produced by
triangularizability; the version here starts from an eigenvector supplied by the caller, which is
what makes the eigenvalue statements below available without a triangularizability hypothesis.
-/

public section

namespace EpsilonEridani

open LieModule Module

/-! ### Raising an eigenvector to a primitive vector -/

section Raising

variable {K : Type*} [CommRing K] [IsDomain K] [CharZero K]
variable {L : Type*} [LieRing L] [LieAlgebra K L]
variable {M : Type*} [AddCommGroup M] [Module K M] [LieRingModule L M] [LieModule K L M]
  [IsTorsionFree K M] [IsNoetherian K M]
variable {h e f : L} {m : M} {μ : K}

/-- **Raising an eigenvector to a primitive vector.** If `m ≠ 0` is an `h`-eigenvector of weight
`μ`, then some power `eᵏ • m` is a primitive vector, of weight `μ + 2k`.

The raising operator shifts the weight by `2`, so if no power of `e` killed `m` the vectors
`m, e • m, e² • m, …` would be eigenvectors for the pairwise distinct weights `μ, μ + 2, μ + 4, …`,
hence linearly independent — impossible in a Noetherian module. The last nonzero vector of the
string is therefore killed by `e`, which is precisely primitivity.

Mathlib's `IsSl2Triple.exists_hasPrimitiveVectorWith` is this argument started from an eigenvector
obtained from `LieModule.IsTriangularizable`; taking the eigenvector as input instead is what lets
the integrality statements below dispense with that hypothesis. -/
theorem exists_hasPrimitiveVectorWith_pow_toEnd_e (t : IsSl2Triple h e f)
    (hm : ⁅h, m⁆ = μ • m) (hm0 : m ≠ 0) :
    ∃ k : ℕ, t.HasPrimitiveVectorWith ((toEnd K L M e ^ k) m) (μ + 2 * k) := by
  have hlie : ∀ n : ℕ, ⁅h, (toEnd K L M e ^ n) m⁆ = (μ + 2 * (n : K)) • (toEnd K L M e ^ n) m :=
    fun n ↦ t.lie_h_pow_toEnd_e hm n
  have hzero : ∃ k : ℕ, (toEnd K L M e ^ k) m = 0 := by
    by_contra! hne
    have hinj : Function.Injective fun n : ℕ ↦ μ + 2 * (n : K) := fun a b hab ↦ by
      simpa [add_right_inj, mul_eq_mul_left_iff, Nat.cast_inj] using hab
    have haux (n : ℕ) :
        (toEnd K L M h).HasEigenvector (μ + 2 * (n : K)) ((toEnd K L M e ^ n) m) :=
      ⟨Module.End.mem_eigenspace_iff.2 (by simpa using hlie n), hne n⟩
    have _i : Finite ℕ :=
      ((toEnd K L M h).eigenvectors_linearIndependent' _ hinj _ haux).finite
    exact not_finite ℕ
  obtain ⟨k, hk_ne, hk_zero⟩ := Nat.exists_not_and_succ_of_not_zero_of_exists hm0 hzero
  exact ⟨k, { ne_zero := hk_ne
              lie_h := hlie k
              lie_e := by rw [IsSl2Triple.lie_e_pow_toEnd_e k]; exact hk_zero }⟩

/-- **The eigenvalues of the Cartan element are integers, explicitly.** An `h`-eigenvector of weight
`μ` in a finite-dimensional module raises to a primitive vector of weight `μ + 2k`, and the weight
of a primitive vector is a natural number `n` (`IsSl2Triple.HasPrimitiveVectorWith.exists_nat`), so
`μ = n - 2k`. -/
theorem exists_nat_sub_two_mul_of_lie_h_eq_smul (t : IsSl2Triple h e f)
    (hm : ⁅h, m⁆ = μ • m) (hm0 : m ≠ 0) :
    ∃ n k : ℕ, μ = (n : K) - 2 * k := by
  obtain ⟨k, P⟩ := exists_hasPrimitiveVectorWith_pow_toEnd_e t hm hm0
  obtain ⟨n, hn⟩ := P.exists_nat
  exact ⟨n, k, by rw [← hn]; ring⟩

/-- **The integer spectrum, in eigenvector form.** The weight of a nonzero `h`-eigenvector in a
finite-dimensional module is an integer. -/
theorem exists_int_of_lie_h_eq_smul (t : IsSl2Triple h e f)
    (hm : ⁅h, m⁆ = μ • m) (hm0 : m ≠ 0) : ∃ z : ℤ, μ = (z : K) := by
  obtain ⟨n, k, hnk⟩ := exists_nat_sub_two_mul_of_lie_h_eq_smul t hm hm0
  exact ⟨(n : ℤ) - 2 * k, by push_cast [hnk]; ring⟩

/-- **The integer spectrum.** Every eigenvalue of the Cartan element `h` of an `sl₂` triple on a
finite-dimensional module is an integer.

No irreducibility is assumed, and the field need not be algebraically closed: this is the form in
which the highest-weight theory uses it, restricting a module over a semisimple Lie algebra to the
`sl₂` triple attached to a root to see that its weights pair integrally with the coroot. It extends
`IsSl2Triple.HasPrimitiveVectorWith.exists_nat` from the primitive vectors to the whole spectrum. -/
theorem exists_int_of_hasEigenvalue (t : IsSl2Triple h e f)
    (hμ : (toEnd K L M h).HasEigenvalue μ) : ∃ z : ℤ, μ = (z : K) := by
  obtain ⟨v, hv, hv0⟩ := hμ.exists_hasEigenvector
  refine exists_int_of_lie_h_eq_smul t ?_ hv0
  simpa using Module.End.mem_eigenspace_iff.1 hv

/-- **No eigenvalues off the integers.** The eigenspace of the Cartan element at a scalar that is
not an integer is trivial.

This is deliberately not a `simp` lemma: the triple `t` mentions `e` and `f`, which do not occur
in the left-hand side, so `simp` cannot infer them (the `simpNF` linter rejects the tag). -/
theorem eigenspace_toEnd_eq_bot_of_forall_ne_intCast (t : IsSl2Triple h e f)
    (hμ : ∀ z : ℤ, μ ≠ (z : K)) : (toEnd K L M h).eigenspace μ = ⊥ := by
  by_contra hbot
  obtain ⟨z, hz⟩ := exists_int_of_hasEigenvalue t (Module.End.hasEigenvalue_iff.2 hbot)
  exact hμ z hz

end Raising

/-! ### The eigenspaces of the Cartan element form a Lie submodule -/

section Ladder

variable {K : Type*} [CommRing K]
variable {L : Type*} [LieRing L] [LieAlgebra K L]
variable {M : Type*} [AddCommGroup M] [Module K M] [LieRingModule L M] [LieModule K L M]
variable {h e f : L} {v : M} {μ : K}

/-- The raising operator moves the `μ`-eigenspace of the Cartan element into the
`μ + 2`-eigenspace. -/
theorem lie_mem_eigenspace_add_two (t : IsSl2Triple h e f)
    (hv : v ∈ (toEnd K L M h).eigenspace μ) :
    ⁅e, v⁆ ∈ (toEnd K L M h).eigenspace (μ + 2) := by
  rw [Module.End.mem_eigenspace_iff] at hv ⊢
  rw [toEnd_apply_apply] at hv ⊢
  rw [leibniz_lie h e v, t.lie_h_e_smul (R := K), hv, smul_lie, lie_smul, add_smul]
  abel

/-- The lowering operator moves the `μ`-eigenspace of the Cartan element into the
`μ - 2`-eigenspace. -/
theorem lie_mem_eigenspace_sub_two (t : IsSl2Triple h e f)
    (hv : v ∈ (toEnd K L M h).eigenspace μ) :
    ⁅f, v⁆ ∈ (toEnd K L M h).eigenspace (μ - 2) := by
  rw [Module.End.mem_eigenspace_iff] at hv ⊢
  rw [toEnd_apply_apply] at hv ⊢
  rw [leibniz_lie h f v, t.lie_lie_smul_f (R := K), hv, neg_lie, smul_lie, lie_smul, sub_smul]
  abel

/-- The Cartan element preserves its own eigenspaces. -/
theorem lie_mem_eigenspace (hv : v ∈ (toEnd K L M h).eigenspace μ) :
    ⁅h, v⁆ ∈ (toEnd K L M h).eigenspace μ := by
  rw [Module.End.mem_eigenspace_iff] at hv ⊢
  rw [toEnd_apply_apply] at hv ⊢
  rw [hv, lie_smul, hv]

variable (t : IsSl2Triple h e f)

/-- **The sum of the eigenspaces of the Cartan element, as a Lie submodule.** The three generators
of the triple shift the eigenvalue by `2`, `-2` and `0`, so the span of the eigenspaces is invariant
under the subalgebra `t.toLieSubalgebra K` they generate; it is *not* in general invariant under the
ambient Lie algebra `L`.

This is the object complete reducibility is applied to in
`EpsilonEridani.iSup_eigenspace_toEnd_eq_top`; its underlying submodule is
`EpsilonEridani.eigenspaceSup_toSubmodule`, which is the abstraction boundary importing modules should use
rather than unfolding the definition. -/
def eigenspaceSup : LieSubmodule K (t.toLieSubalgebra K) M :=
  let S := ⨆ ν : K, (toEnd K L M h).eigenspace ν
  have key : ∀ z : L, (∀ ν : K, (toEnd K L M h).eigenspace ν ≤ S.comap (toEnd K L M z)) →
      ∀ y ∈ S, ⁅z, y⁆ ∈ S := by
    intro z hz y hy
    exact (iSup_le hz : S ≤ S.comap (toEnd K L M z)) hy
  t.lieSubmoduleOfStable S
    (key e fun ν _ hw ↦ Submodule.mem_iSup_of_mem (ν + 2) (lie_mem_eigenspace_add_two t hw))
    (key f fun ν _ hw ↦ Submodule.mem_iSup_of_mem (ν - 2) (lie_mem_eigenspace_sub_two t hw))

/-- The submodule underlying `EpsilonEridani.eigenspaceSup` is the sum of the eigenspaces of the Cartan
element. This is the abstraction boundary: it is how a downstream proof should pass between the
bundled Lie submodule and the eigenspaces, rather than unfolding the definition. -/
@[simp]
theorem eigenspaceSup_toSubmodule :
    (eigenspaceSup t (M := M)).toSubmodule = ⨆ ν : K, (toEnd K L M h).eigenspace ν := by
  simp only [eigenspaceSup, IsSl2Triple.lieSubmoduleOfStable_toSubmodule]

/-- An eigenvector of the Cartan element lies in the sum of its eigenspaces,
`EpsilonEridani.eigenspaceSup`. -/
theorem mem_eigenspaceSup_of_lie_h_eq_smul (hv : ⁅h, v⁆ = μ • v) :
    v ∈ eigenspaceSup (K := K) t := by
  rw [← LieSubmodule.mem_toSubmodule, eigenspaceSup_toSubmodule t]
  exact Submodule.mem_iSup_of_mem μ (Module.End.mem_eigenspace_iff.2 (by simpa using hv))

end Ladder

/-! ### Diagonalizability of the Cartan element -/

section Diagonalizable

variable {K : Type*} [Field K] [CharZero K] [IsAlgClosed K]
variable {L : Type*} [LieRing L] [LieAlgebra K L]
variable {M : Type*} [AddCommGroup M] [Module K M] [LieRingModule L M] [LieModule K L M]
  [FiniteDimensional K M]
variable {h e f : L}

/-- **The Cartan element acts diagonalizably.** Over an algebraically closed field of characteristic
zero, the eigenspaces of the Cartan element of an `sl₂` triple span every finite-dimensional module
over the ambient Lie algebra.

Only the action of the subalgebra `t.toLieSubalgebra K` generated by the triple is used, so the
triple need not generate `L`: the eigenspaces span a Lie submodule for that subalgebra
(`EpsilonEridani.eigenspaceSup`), which by complete reducibility
(`EpsilonEridani.exists_isCompl_of_toLieSubalgebra_eq_top`, applied over the subalgebra, which its own
triple does generate) has a complement. A nonzero complement is itself a finite-dimensional module
over an algebraically closed field, so `h` has an eigenvector in it — but every eigenvector already
lies in the span, and the two meet only in `0`. So the complement is trivial. -/
theorem iSup_eigenspace_toEnd_eq_top (t : IsSl2Triple h e f) :
    ⨆ μ : K, (toEnd K L M h).eigenspace μ = ⊤ := by
  obtain ⟨N, hN⟩ := exists_isCompl_of_toLieSubalgebra_eq_top
    t.restrict_toLieSubalgebra_eq_top (eigenspaceSup (K := K) (M := M) t)
  have hNbot : N = ⊥ := by
    by_contra hne
    have : Nontrivial N := (LieSubmodule.nontrivial_iff_ne_bot K _ M).2 hne
    obtain ⟨μ, hμ⟩ := LieModule.IsTriangularizable.exists_hasEigenvalue
      (R := K) (L := t.toLieSubalgebra K) (M := ↥N) ⟨h, t.h_mem_toLieSubalgebra⟩
    obtain ⟨v, hv, hv0⟩ := hμ.exists_hasEigenvector
    have hvM : ⁅h, (v : M)⁆ = μ • (v : M) := by
      have hv' : ⁅(⟨h, t.h_mem_toLieSubalgebra⟩ : t.toLieSubalgebra K), v⁆ = μ • v := by
        simpa only [LieModule.toEnd_apply_apply] using Module.End.mem_eigenspace_iff.1 hv
      -- Push the equality in `↥N` down to `M`, through the submodule and then the subalgebra.
      simpa only [LieSubmodule.coe_bracket, LieSubalgebra.coe_bracket_of_module,
        LieSubmodule.coe_smul] using congrArg (fun w : ↥N ↦ (w : M)) hv'
    have hmem : (v : M) ∈ eigenspaceSup t ⊓ N :=
      ⟨mem_eigenspaceSup_of_lie_h_eq_smul t hvM, v.2⟩
    rw [hN.inf_eq_bot] at hmem
    exact hv0 (Subtype.ext (by simpa using (LieSubmodule.mem_bot _).1 hmem))
  have hsup : eigenspaceSup (K := K) (M := M) t = ⊤ := by
    have := hN.sup_eq_top
    rwa [hNbot, sup_bot_eq] at this
  refine eq_top_iff.2 fun x _ ↦ ?_
  have hx : x ∈ eigenspaceSup (K := K) (M := M) t := by rw [hsup]; trivial
  rwa [← LieSubmodule.mem_toSubmodule, eigenspaceSup_toSubmodule t] at hx

/-- **The integral weight decomposition.** The two halves of the layer meet: the eigenspaces of the
Cartan element span (`EpsilonEridani.iSup_eigenspace_toEnd_eq_top`) and they are supported on the integers
(`EpsilonEridani.exists_int_of_hasEigenvalue`), so a finite-dimensional module is spanned by the
eigenspaces at the integers. -/
theorem iSup_eigenspace_toEnd_intCast_eq_top (t : IsSl2Triple h e f) :
    ⨆ z : ℤ, (toEnd K L M h).eigenspace (z : K) = ⊤ := by
  classical
  rw [← iSup_eigenspace_toEnd_eq_top (M := M) t]
  refine le_antisymm (iSup_le fun z ↦ le_iSup _ _) (iSup_le fun μ ↦ ?_)
  by_cases hμ : ∃ z : ℤ, μ = (z : K)
  · obtain ⟨z, rfl⟩ := hμ
    exact le_iSup (fun z : ℤ ↦ (toEnd K L M h).eigenspace (z : K)) z
  · push Not at hμ
    simp [eigenspace_toEnd_eq_bot_of_forall_ne_intCast t hμ]

/-- **The eigenspace decomposition at the integers.** The internal direct sum form of
`EpsilonEridani.iSup_eigenspace_toEnd_intCast_eq_top`. -/
theorem isInternal_eigenspace_toEnd_intCast (t : IsSl2Triple h e f) :
    DirectSum.IsInternal fun z : ℤ ↦ (toEnd K L M h).eigenspace (z : K) :=
  DirectSum.isInternal_submodule_of_iSupIndep_of_iSup_eq_top
    ((toEnd K L M h).eigenspaces_iSupIndep.comp (f := fun z : ℤ ↦ (z : K)) Int.cast_injective)
    (iSup_eigenspace_toEnd_intCast_eq_top t)

end Diagonalizable

/-! ### The model `sl₂` -/

section SlFinTwo

open LieAlgebra

variable {K : Type*} [Field K] [CharZero K]
variable {M : Type*} [AddCommGroup M] [Module K M]
  [LieRingModule (SpecialLinear.sl (Fin 2) K) M] [LieModule K (SpecialLinear.sl (Fin 2) K) M]
  [FiniteDimensional K M]

/-- **The integer spectrum for `sl (Fin 2) K`.** Every eigenvalue of the Cartan element
`h = E₀₀ - E₁₁` on a finite-dimensional `sl (Fin 2) K`-module is an integer.

Neither irreducibility nor an algebraically closed field is assumed, which is what distinguishes
this from what the classification of the irreducibles delivers. -/
theorem exists_int_of_hasEigenvalue_slFinTwo {μ : K}
    (hμ : (toEnd K (SpecialLinear.sl (Fin 2) K) M (slFinTwoBasis K 2)).HasEigenvalue μ) :
    ∃ z : ℤ, μ = (z : K) := by
  rw [slFinTwoBasis_two] at hμ
  exact exists_int_of_hasEigenvalue
    (isSl2Triple_single (R := K) (zero_ne_one : (0 : Fin 2) ≠ 1)) hμ

variable [IsAlgClosed K]

/-- **Diagonalizability for `sl (Fin 2) K`.** Over an algebraically closed field of characteristic
zero, a finite-dimensional `sl (Fin 2) K`-module is the direct sum of the integer eigenspaces of the
Cartan element `h = E₀₀ - E₁₁`. -/
theorem isInternal_eigenspace_toEnd_intCast_slFinTwo :
    DirectSum.IsInternal fun z : ℤ ↦
      (toEnd K (SpecialLinear.sl (Fin 2) K) M (slFinTwoBasis K 2)).eigenspace (z : K) := by
  rw [slFinTwoBasis_two]
  exact isInternal_eigenspace_toEnd_intCast
    (isSl2Triple_single (R := K) (zero_ne_one : (0 : Fin 2) ≠ 1))

end SlFinTwo

end EpsilonEridani
