/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Elementary.Basic
public import EpsilonEridani.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Weyl.Basic

/-!
# The Weyl representative lies in the elementary group

The Weyl representative of a root pair `(eᵢ, eⱼ)` is defined in
`EpsilonEridani.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Weyl.Basic` as the scalar extension
of an integral automorphism of the admissible lattice, and identified there with the product of
divided-power exponentials `exp(ρ eᵢ) exp(-ρ eⱼ) exp(ρ eᵢ)`. This file reads that product in the
parametrized root subgroups `xᵢ(t)` of
`EpsilonEridani.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Elementary.Basic`:

```text
n = xᵢ(1) xⱼ(-1) xᵢ(1),
```

so that `n` is visibly an element of the elementary group generated by the root subgroups.

The two files this sits between are independent of each other, which is why the identification
lives here rather than in either. No `sl₂` relation between `eᵢ` and `eⱼ` is used: the statement is
about the three exponentials alone.

## Main results

* `EpsilonEridani.UniversalEnvelopingAlgebra.kostantWeylGL_eq_kostantRootSubgroupParam_mul`: the Weyl
  representative is the product `xᵢ(1) xⱼ(-1) xᵢ(1)` of parametrized root-subgroup elements.
* `EpsilonEridani.UniversalEnvelopingAlgebra.kostantWeylGL_mem_kostantElementarySubgroup`: it therefore
  belongs to the elementary group.

## References

* R. W. Carter, *Simple Groups of Lie Type*, §6.4.
* R. Steinberg, *Lectures on Chevalley Groups*, §3.
-/

public section

open TensorProduct

namespace EpsilonEridani.UniversalEnvelopingAlgebra

universe u v w

variable {L : Type u} [LieRing L] [LieAlgebra ℚ L]
variable {ι : Type*} {κ : Type*}
variable {V : Type v} [AddCommGroup V] [Module ℚ V]

variable (e : ι → L) (h : κ → L)
variable (ρ : _root_.UniversalEnvelopingAlgebra ℚ L →ₐ[ℚ] Module.End ℚ V)
variable (M : AddSubgroup V)
variable (hM : ∀ u ∈ kostantForm e h, ∀ v ∈ M, ρ u v ∈ M)

-- Match tensor products to the `ℤ`-algebra instance stored by `CommAlgCat` objects.
attribute [local instance high] Algebra.toModule

variable {i j : ι}
variable (hi : IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i))))
variable (hj : IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e j))))

/-- **The Weyl representative is the Chevalley product `xᵢ(1) xⱼ(-1) xᵢ(1)`**, written in the
parametrized root subgroups. -/
theorem kostantWeylGL_eq_kostantRootSubgroupParam_mul (A : CommAlgCat.{w} ℤ) :
    kostantWeylGL e h ρ M hM hi hj A =
      kostantRootSubgroupParam e h ρ M hM i hi A (Multiplicative.ofAdd (1 : A)) *
        kostantRootSubgroupParam e h ρ M hM j hj A (Multiplicative.ofAdd (-1 : A)) *
        kostantRootSubgroupParam e h ρ M hM i hi A (Multiplicative.ofAdd (1 : A)) := by
  refine Units.ext ?_
  rw [kostantWeylGL_val, kostantWeylPoints_toLinearMap_eq]
  refine LinearMap.ext fun z => ?_
  simp only [Units.val_mul, Module.End.mul_apply, kostantRootSubgroupParam_val_apply,
    toAdd_ofAdd]

include e hM in
/-- **The Weyl representative lies in the elementary group**, being a product of three
root-subgroup elements. -/
theorem kostantWeylGL_mem_kostantElementarySubgroup
    (hnil : ∀ i, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i))))
    (i j : ι) (A : CommAlgCat.{w} ℤ) :
    kostantWeylGL e h ρ M hM (hnil i) (hnil j) A ∈
      kostantElementarySubgroup e h ρ M hM hnil A := by
  rw [kostantWeylGL_eq_kostantRootSubgroupParam_mul]
  exact mul_mem
    (mul_mem (kostantRootSubgroupParam_mem_kostantElementarySubgroup e h ρ M hM hnil A i _)
      (kostantRootSubgroupParam_mem_kostantElementarySubgroup e h ρ M hM hnil A j _))
    (kostantRootSubgroupParam_mem_kostantElementarySubgroup e h ρ M hM hnil A i _)

end EpsilonEridani.UniversalEnvelopingAlgebra
