/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.Algebra.Lie.E6.Minuscule.GroupScheme
public import EpsilonEridani.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Torus.Coroot

/-!
# Generation of the E₆ minuscule weight torus by root subgroups

The type-`E₆` minuscule carrier is defined from twelve numbered simple root subgroups together
with its rank-six weight torus. Over every commutative ring, this file proves that the represented
weight torus is already contained in the elementary group generated by those root subgroups.

The proof combines two concrete features of the minuscule carrier. The positive and negative
generators at every node form an `sl₂` triple after passing to the represented rational module.
Also, every row of the type-`E₆` Cartan matrix contains `-1`, giving an explicit integral Bézout
witness for the corresponding root character. The generic coroot-generation theorem therefore
puts every coordinate cocharacter, and hence every point of the weight torus, in the elementary
group.

The result concerns subgroups of the automorphism group of the base-changed admissible lattice.
It does not identify the elementary subgroup with all points of the toral-closure group scheme;
that is a separate scheme-theoretic comparison.

## Main results

* `EpsilonEridani.E6Minuscule.elementarySubgroup`: the subgroup of carrier points generated by the
  ranges of the twelve named root-subgroup maps.
* `EpsilonEridani.E6Minuscule.elementarySubgroup_le_iff`: its least-subgroup elimination principle.
* `EpsilonEridani.E6Minuscule.weightTorusPoints_range_le_elementarySubgroup`: the range of the named
  weight-torus map lies in the elementary subgroup over every commutative ring.

## References

* R. Steinberg, *Lectures on Chevalley Groups*, §3.
* R. W. Carter, *Simple Groups of Lie Type*, §§6.4 and 7.1.
-/

public section

open scoped TensorProduct

universe v

namespace EpsilonEridani.E6Minuscule

open EpsilonEridani.E6

open EpsilonEridani.DynkinType EpsilonEridani.UniversalEnvelopingAlgebra

attribute [local instance 100] LieRing.ofAssociativeRing
attribute [local instance high] Algebra.toModule

local notation "Λ" => EpsilonEridani.coordinateLattice (Fin 27)
local notation "𝓑" => EpsilonEridani.coordinateLatticeBasis (Fin 27)
local notation "rootGen" => EpsilonEridani.serreRootGenerator weightTable.cartanMatrix
local notation "cartanGen" => EpsilonEridani.serreH ℚ weightTable.cartanMatrix

/-- The elementary subgroup of the type-`E₆` minuscule carrier points, generated by the
ranges of its twelve named positive and negative simple-root subgroup maps. -/
noncomputable def elementarySubgroup (A : Type v) [CommRing A] : Subgroup (points A) :=
  ⨆ k, (rootSubgroupPoints k A).range

/-- Every point of a named root subgroup belongs to the elementary subgroup. -/
theorem rootSubgroupPoints_mem_elementarySubgroup (A : Type v) [CommRing A]
    (k : Fin 6 ⊕ Fin 6) (u : Multiplicative A) :
    rootSubgroupPoints k A u ∈ elementarySubgroup A :=
  (le_iSup (fun k ↦ (rootSubgroupPoints k A).range) k) ⟨u, rfl⟩

/-- A subgroup contains the elementary subgroup exactly when it contains every named
root-subgroup point. -/
theorem elementarySubgroup_le_iff (A : Type v) [CommRing A] {H : Subgroup (points A)} :
    elementarySubgroup A ≤ H ↔
      ∀ (k : Fin 6 ⊕ Fin 6) (u : Multiplicative A), rootSubgroupPoints k A u ∈ H := by
  rw [elementarySubgroup, iSup_le_iff]
  constructor
  · intro h k u
    exact h k ⟨u, rfl⟩
  · rintro h k _ ⟨u, rfl⟩
    exact h k u

private theorem map_kostantElementarySubgroup_le_map_elementarySubgroup
    (A : Type v) [CommRing A] :
    (kostantElementarySubgroup rootGen cartanGen weightTable.rep (Λ).toAddSubgroup
        weightTable.rep_kostantForm_mem_lattice
        weightTable.isNilpotent_rep_serreRootGenerator (CommAlgCat.of ℤ A)).map
          (Units.map (LinearMap.toMatrixAlgEquiv ((𝓑).baseChange A)).toMulEquiv) ≤
      (elementarySubgroup A).map (points A).subtype := by
  apply map_kostantElementarySubgroup_le_of_matrix_mem
    rootGen cartanGen weightTable.rep (Λ).toAddSubgroup
    weightTable.rep_kostantForm_mem_lattice weightTable.isNilpotent_rep_serreRootGenerator
    𝓑 A
  intro k q
  let u := AdditiveGroup.gaPointsMulEquiv (R := ℤ) (A := A) q
  refine ⟨rootSubgroupPoints k A u, rootSubgroupPoints_mem_elementarySubgroup A k u, ?_⟩
  apply Units.ext
  simp only [Subgroup.coe_subtype, coe_rootSubgroupPoints, u,
    MulEquiv.symm_apply_apply]

/-- Over every commutative ring, the range of the named type-`E₆` minuscule weight-torus map
is contained in the elementary subgroup generated by the named root-subgroup maps. -/
theorem weightTorusPoints_range_le_elementarySubgroup (A : Type v) [CommRing A] :
    (weightTorusPoints A).range ≤ elementarySubgroup A := by
  rintro _ ⟨s, rfl⟩
  have htorus :
      kostantTorusPoints (Λ).toAddSubgroup 𝓑 weightTable.weight A s ∈
        kostantTorusSubgroup (Λ).toAddSubgroup 𝓑 weightTable.weight
          (CommAlgCat.of ℤ A) := by
    rw [kostantTorusSubgroup_eq_range]
    exact ⟨s, rfl⟩
  have helementary :=
    (kostantTorusSubgroup_le_kostantElementarySubgroup
      rootGen cartanGen weightTable.rep (Λ).toAddSubgroup
      weightTable.rep_kostantForm_mem_lattice weightTable.isNilpotent_rep_serreRootGenerator
      𝓑 weightTable.weight weightTable.isCartanWeightVector_coordinateLatticeBasis
      rootGeneratorWeight
      (by intro k j; rw [weightTable_cartanMatrix]; exact lie_serreH_rootGenerator k j)
      Sum.inl Sum.inr
      (fun i ↦ weightTable.isSl2Triple_rep_serreRootGenerator i
        (by
          obtain ⟨a, ha⟩ := exists_e6MinusculeWeight_apply_eq_neg_one i
          exact ⟨a, by simp only [weightTable_weight, ha]; omega⟩))
      rootGeneratorWeight_inr_eq_neg_inl cartanBezout rootGeneratorWeight_sum_mul_cartanBezout
      (CommAlgCat.of ℤ A)) htorus
  have hmatrix :
      Units.map (LinearMap.toMatrixAlgEquiv ((𝓑).baseChange A)).toMulEquiv
          (kostantTorusPoints (Λ).toAddSubgroup 𝓑 weightTable.weight A s) ∈
        (elementarySubgroup A).map (points A).subtype :=
    map_kostantElementarySubgroup_le_map_elementarySubgroup A
      ⟨_, helementary, rfl⟩
  obtain ⟨g, hg, hg_eq⟩ := hmatrix
  have hpoint : weightTorusPoints A s = g := by
    apply Subtype.ext
    rw [coe_weightTorusPoints, ← basisMatrix_kostantTorusPoints]
    exact hg_eq.symm
  rwa [hpoint]

end EpsilonEridani.E6Minuscule
