/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.LinearAlgebra.TensorCoalgebra.Basic

/-!
# The conilpotence filtration of reduced tensor words

The reduced tensor coalgebra is filtered by tensor length, and reduced deconcatenation strictly
decreases that length: a word of length at most `n + 1` is cut into two words each of length at
most `n`.  This length bound is the inductive step behind conilpotence, which asserts that a high
enough iterate of the reduced coproduct annihilates every element.

The filtration is exhaustive and starts at the zero submodule, since the empty word is not a
reduced tensor word.

## Main definitions

* `EpsilonEridani.ReducedTensorWords.filtration`: the submodule generated by the tensor words of length
  at most `n`.

## Main results

* `EpsilonEridani.ReducedTensorWords.iSup_filtration_eq_top`: the filtration is exhaustive.
* `EpsilonEridani.ReducedTensorWords.map_deconcatenation_filtration_succ_le`: deconcatenating a word of
  length at most `n + 1` produces a sum of tensors of two words of length at most `n`.

## References

* E. Getzler and J. D. S. Jones, *A-infinity algebras and the cyclic bar complex*, Sections 1--2.
* B. Keller, *Introduction to A-infinity algebras and modules*, Sections 3.1 and 3.6.
-/

public section

open scoped BigOperators DirectSum TensorProduct

universe uR uM

namespace EpsilonEridani

namespace ReducedTensorWords

variable (R : Type uR) (M : Type uM) [CommSemiring R] [AddCommMonoid M] [Module R M]

/-- The `n`-th step of the conilpotence filtration: the submodule generated by the tensor words of
length at most `n`. -/
noncomputable def filtration (n : ℕ) : Submodule R (ReducedTensorWords R M) :=
  ⨆ (k : {k : ℕ // 0 < k}) (_ : k.1 ≤ n), LinearMap.range (of R M k)

/-- A tensor word of length at most `n` lies in the `n`-th step of the filtration. -/
theorem of_mem_filtration {k : {k : ℕ // 0 < k}} {n : ℕ} (hk : k.1 ≤ n)
    (x : TensorPower R k.1 M) : of R M k x ∈ filtration R M n :=
  Submodule.mem_iSup_of_mem k (Submodule.mem_iSup_of_mem hk ⟨x, rfl⟩)

/-- To prove that the `n`-th filtration step lies in a submodule, it suffices to check the
generating tensor powers of length at most `n`. -/
theorem filtration_le_iff {n : ℕ} {p : Submodule R (ReducedTensorWords R M)} :
    filtration R M n ≤ p ↔
      ∀ k : {k : ℕ // 0 < k}, k.1 ≤ n → LinearMap.range (of R M k) ≤ p := by
  rw [filtration, iSup₂_le_iff]

/-- The conilpotence filtration is increasing. -/
theorem filtration_monotone : Monotone (filtration R M) := fun _ _ hmn ↦
  biSup_mono fun _ hk ↦ hk.trans hmn

/-- A reduced tensor word has positive length, so the filtration starts at zero. -/
@[simp]
theorem filtration_zero : filtration R M 0 = ⊥ :=
  le_antisymm (iSup_le fun k ↦ iSup_le fun hk ↦ absurd (k.2.trans_le hk) (lt_irrefl 0)) bot_le

/-- The conilpotence filtration is exhaustive. -/
theorem iSup_filtration_eq_top : ⨆ n : ℕ, filtration R M n = ⊤ := by
  refine le_antisymm le_top ?_
  rw [← iSup_range_of]
  refine iSup_le fun k ↦ le_iSup_of_le k.1 ?_
  rintro _ ⟨x, rfl⟩
  exact of_mem_filtration R M le_rfl x

/-- A block of length at most `n` lies in the `n`-th step of the filtration. -/
theorem subword_mem_filtration {l : ℕ} (x : Fin l → M) (a : ℕ) {b n : ℕ} (hb : b ≤ n) :
    subword R x a b ∈ filtration R M n := by
  rcases Nat.eq_zero_or_pos b with hb0 | hb0
  · rw [hb0, subword_length_zero]
    exact Submodule.zero_mem _
  by_cases hab : a + b ≤ l
  · rw [subword_eq_of_tprod R x hb0 hab]
    exact of_mem_filtration R M hb _
  · rw [subword_eq_zero_of_lt_add R x (by omega)]
    exact Submodule.zero_mem _

/-- Reduced deconcatenation strictly decreases tensor length: a word of length at most `n + 1` is
sent into the image of `filtration n ⊗ filtration n`.  This is the length-lowering step behind the
conilpotence of the reduced tensor coalgebra. -/
theorem map_deconcatenation_filtration_succ_le (n : ℕ) :
    Submodule.map (deconcatenation R M) (filtration R M (n + 1)) ≤
      LinearMap.range (TensorProduct.mapIncl (filtration R M n) (filtration R M n)) := by
  rw [TensorProduct.range_mapIncl, Submodule.map_le_iff_le_comap, filtration_le_iff]
  intro k hk
  rintro _ ⟨z, rfl⟩
  simp only [Submodule.mem_comap]
  induction z using PiTensorProduct.induction_on with
  | smul_tprod r y =>
      rw [map_smul, map_smul, of_tprod_eq_subword R k.2 y,
        deconcatenation_subword R y (a := 0) (b := k.1)]
      refine Submodule.smul_mem _ _ (Submodule.sum_mem _ fun c hc ↦ ?_)
      simp only [Finset.mem_Ioo] at hc
      exact Submodule.apply_mem_map₂ _ (subword_mem_filtration R M y 0 (by omega))
        (subword_mem_filtration R M y (0 + c) (by omega))
  | add u v hu hv =>
      rw [map_add, map_add]
      exact Submodule.add_mem _ hu hv

end ReducedTensorWords

end EpsilonEridani
