/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.FieldTheory.GaloisGroups.FrobeniusOrbits
public import EpsilonEridani.NumberTheory.NumberField.Frobenius
public import EpsilonEridani.NumberTheory.NumberField.RootReduction
public import EpsilonEridani.NumberTheory.NumberField.SplittingField
public import EpsilonEridani.RingTheory.Polynomial.FactorDegrees
public import EpsilonEridani.RingTheory.Polynomial.Resultant.Discriminant
import Mathlib.Algebra.CharP.Basic
import Mathlib.FieldTheory.Perfect

/-!
# Dedekind's theorem: the cycle type of a Frobenius is the factorization type

Let `f` be a monic integer polynomial and `p` a prime modulo which `f` is squarefree. Let `M` be
a number field in which `f` splits, and let `σ ∈ Gal(M/ℚ)` be an arithmetic Frobenius at a prime
`Q` of `𝓞 M` over `p`. **Dedekind's theorem** says that the permutation `σ` induces on the roots
of `f` in `M` has, counting fixed points, cycle lengths the degrees of the irreducible factors of
`f` modulo `p`.

The proof reduces the roots modulo `Q`. The roots of `f` are algebraic integers, and reduction
modulo `Q` maps them bijectively onto the roots of `f mod p` in the residue field `𝓞 M ⧸ Q`:
their images are all the roots of `f mod p`, counted with multiplicity, and these are distinct
because `f mod p` is squarefree over the perfect field `𝔽_p`. The Frobenius congruence
`σ x ≡ x ^ p (mod Q)` makes this bijection carry `σ` to the `p`-th power map, whose cycle type on
the roots of a squarefree polynomial over `𝔽_p` is its factorization type
(`EpsilonEridani.FiniteField.fullCycleType_eq_map_natDegree_normalizedFactors`). Neither the index of
`ℤ[θ]` nor the ramification of `p` in the field generated by a root enters the argument.

Since `p ∤ disc f` makes `f mod p` squarefree, the theorem applies at every such prime to the
splitting field of `f` over `ℚ`, where Frobenius elements exist. Moving from that splitting field
to `ℂ` does not change the cycle type of a Galois automorphism, which gives the statement in the
vocabulary of `Polynomial.Gal`.

## Main results

* `EpsilonEridani.NumberField.fullCycleType_galActionHom_restrict_eq_factorDegrees`: Dedekind's theorem
  for a Frobenius element of a number field in which `f` splits.
* `EpsilonEridani.NumberField.fullCycleType_galActionHom_restrict_minpoly_eq_map_natDegree_monicFactorsMod`
  is the same statement for the minimal polynomial of an algebraic integer `θ`, with the factor
  degrees read off from `RingOfIntegers.monicFactorsMod θ p`.
* `EpsilonEridani.NumberField.factorizationType_eq_cycleType_isArithFrobAt`: the same statement with the
  cycle type and the number of fixed points as separate summands.
* `EpsilonEridani.NumberField.exists_gal_fullCycleType_eq_factorizationType`: for monic `f` and a prime
  `p ∤ disc f`, some element of the Galois group of `f` over `ℚ` acts on the complex roots of `f`
  with full cycle type the factor degrees of `f` modulo `p`.

## References

* [J. Neukirch, *Algebraic Number Theory*][Neukirch1992], Chapter I, §8, Exercises 4 and 5.
* D. A. Marcus, *Number Fields*, 2nd edition, Springer 2018, Chapter 4.
-/

public section

open Polynomial Ideal
open scoped NumberField

namespace EpsilonEridani.NumberField

variable {M : Type*} [Field M] [NumberField M] {f : ℤ[X]} {p : ℕ} [Fact p.Prime]

open scoped Classical in
/-- **Dedekind's theorem.** Let `f` be a monic integer polynomial which is squarefree modulo the
prime `p`, and let `M` be a number field in which `f` splits. If `σ ∈ Gal(M/ℚ)` is an arithmetic
Frobenius at a prime `Q` of `𝓞 M` over `p`, then the permutation of the roots of `f` in `M`
induced by `σ` has, counting fixed points, cycle lengths the degrees of the irreducible factors
of `f` modulo `p`, with multiplicity. -/
theorem fullCycleType_galActionHom_restrict_eq_factorDegrees (hf : f.Monic)
    (hsq : Squarefree (f.map (Int.castRingHom (ZMod p))))
    [Fact (((f.map (Int.castRingHom ℚ)).map (algebraMap ℚ M)).Splits)]
    (Q : Ideal (𝓞 M)) [Q.IsPrime] [Q.LiesOver (span {(p : ℤ)})]
    {σ : M ≃ₐ[ℚ] M} (hσ : IsArithFrobAt ℤ σ Q) :
    (Gal.galActionHom (f.map (Int.castRingHom ℚ)) M
      (Gal.restrict (f.map (Int.castRingHom ℚ)) M σ)).fullCycleType = f.factorDegrees p := by
  classical
  have hp : (span {(p : ℤ)} : Ideal ℤ) ≠ ⊥ := by
    rw [Ne, span_singleton_eq_bot]
    exact_mod_cast (Fact.out : p.Prime).ne_zero
  have hQ : Q ≠ ⊥ := ne_bot_of_liesOver_of_ne_bot hp Q
  have : Q.IsMaximal := Ring.DimensionLEOne.maximalOfPrime hQ inferInstance
  let := Quotient.field Q
  have : Finite (𝓞 M ⧸ Q) := Ring.HasFiniteQuotients.finiteQuotient hQ
  have hpQ : (p : 𝓞 M) ∈ Q := by
    have h : ((p : ℤ) : 𝓞 M) ∈ Q := mem_of_liesOver Q (span {(p : ℤ)}) _ |>.mp
      (mem_span_singleton_self _)
    exact_mod_cast h
  have : CharP (𝓞 M ⧸ Q) p := (CharP.charP_iff_prime_eq_zero Fact.out).mpr <| by
    rw [← map_natCast (Ideal.Quotient.mk Q), Quotient.eq_zero_iff_mem]
    exact hpQ
  let := ZMod.algebra (𝓞 M ⧸ Q) p
  have : Algebra.IsAlgebraic (ZMod p) (𝓞 M ⧸ Q) := Algebra.IsAlgebraic.of_finite _ _
  obtain ⟨hsplit, e, he⟩ :=
    splits_and_exists_rootSet_equiv_of_squarefree_map_zmod hf hsq Fact.out (Ideal.Quotient.mk Q)
  have : Fact _ := ⟨hsplit⟩
  rw [factorDegrees_def, ← Equiv.Perm.fullCycleType_permCongr e]
  -- Match the concrete `ZMod` decision procedure with the classical one in the finite-field API.
  rw [show ZMod.decidableEq p = Classical.decEq (ZMod p) from Subsingleton.elim _ _]
  refine FiniteField.fullCycleType_eq_map_natDegree_normalizedFactors (𝓞 M ⧸ Q) hsq _ fun z => ?_
  obtain ⟨x, rfl⟩ := e.surjective z
  have hx : IsIntegral ℤ (x : M) := ⟨f, hf, by
    have h := aeval_eq_zero_of_mem_rootSet x.2
    rwa [aeval_def, eval₂_map,
      RingHom.ext_int ((algebraMap ℚ M).comp (Int.castRingHom ℚ)) (algebraMap ℤ M)] at h⟩
  obtain ⟨y, hy⟩ : ∃ y : 𝓞 M, algebraMap (𝓞 M) M y = x :=
    ⟨_, IsIntegralClosure.algebraMap_mk' _ _ hx⟩
  have hσy : algebraMap (𝓞 M) M (σ • y) =
      (Gal.galActionHom _ M (Gal.restrict _ M σ) x : M) := by
    rw [NumberField.algebraMap_smul_eq_apply, hy, Gal.galActionHom_restrict]
  rw [Equiv.permCongr_apply, e.symm_apply_apply, he _ _ hσy, he x y hy, ZMod.card,
    ← map_pow, Ideal.Quotient.eq]
  have h := hσ y
  rwa [← LiesOver.over (P := Q) (p := span {(p : ℤ)}), Int.card_ideal_quot] at h

open scoped Classical in
/-- **Dedekind's theorem for a generator.** Let `θ` be an algebraic integer of a number field `K`
whose minimal polynomial is squarefree modulo the prime `p`, and let `M` be a number field in which
the minimal polynomial of `θ` splits. If `σ ∈ Gal(M/ℚ)` is an arithmetic Frobenius at a prime `Q`
of `𝓞 M` over `p`, then the permutation of the roots of `minpoly ℚ θ` in `M` induced by `σ` has,
counting fixed points, cycle lengths the degrees of the monic irreducible factors
`RingOfIntegers.monicFactorsMod θ p` of `minpoly ℤ θ` modulo `p`. -/
theorem fullCycleType_galActionHom_restrict_minpoly_eq_map_natDegree_monicFactorsMod
    {K : Type*} [Field K] [NumberField K] {θ : 𝓞 K}
    (hsq : Squarefree ((minpoly ℤ θ).map (Int.castRingHom (ZMod p))))
    [Fact (((minpoly ℚ (θ : K)).map (algebraMap ℚ M)).Splits)]
    (Q : Ideal (𝓞 M)) [Q.IsPrime] [Q.LiesOver (span {(p : ℤ)})]
    {σ : M ≃ₐ[ℚ] M} (hσ : IsArithFrobAt ℤ σ Q) :
    (Gal.galActionHom (minpoly ℚ (θ : K)) M
      (Gal.restrict (minpoly ℚ (θ : K)) M σ)).fullCycleType =
        (RingOfIntegers.monicFactorsMod θ p).val.map natDegree := by
  have hmin : minpoly ℚ (θ : K) = (minpoly ℤ θ).map (Int.castRingHom ℚ) := by
    rw [← NumberField.RingOfIntegers.minpoly_coe,
      minpoly.isIntegrallyClosed_eq_field_fractions' ℚ θ.isIntegral_coe, algebraMap_int_eq]
  -- Transport the general theorem along `hmin`, generalizing the splitting instance.
  have key : ∀ (g : ℚ[X]) [Fact ((g.map (algebraMap ℚ M)).Splits)],
      g = (minpoly ℤ θ).map (Int.castRingHom ℚ) →
        (Gal.galActionHom g M (Gal.restrict g M σ)).fullCycleType =
          (minpoly ℤ θ).factorDegrees p := by
    rintro g _ rfl
    exact fullCycleType_galActionHom_restrict_eq_factorDegrees
      (minpoly.monic θ.isIntegral) hsq Q hσ
  have hnodup : (UniqueFactorizationMonoid.normalizedFactors
      ((minpoly ℤ θ).map (Int.castRingHom (ZMod p)))).Nodup :=
    (UniqueFactorizationMonoid.squarefree_iff_nodup_normalizedFactors
      ((minpoly.monic θ.isIntegral).map _).ne_zero).mp hsq
  rw [key _ hmin, factorDegrees_def, RingOfIntegers.monicFactorsMod, Multiset.toFinset_val,
    hnodup.dedup]

attribute [local instance] Gal.splits_ℚ_ℂ

open scoped Classical in
/-- **The polynomial form of Dedekind's theorem.** Let `f` be a monic integer polynomial and `p`
a prime not dividing the discriminant of `f`. Then some element of the Galois group of `f` over
`ℚ` acts on the complex roots of `f` with full cycle type (cycle lengths counted together with
fixed points) equal to the multiset of degrees of the irreducible factors of `f` modulo `p`.

The statement allows reducible `f`: the factor degrees of all the irreducible factors of `f`
are read off from a single Galois automorphism. -/
theorem exists_gal_fullCycleType_eq_factorizationType (f : ℤ[X]) (hf : f.Monic) (p : ℕ)
    [Fact p.Prime] (hp : ¬ (p : ℤ) ∣ f.discr) :
    ∃ σ : (f.map (Int.castRingHom ℚ)).Gal,
      (Gal.galActionHom (f.map (Int.castRingHom ℚ)) ℂ σ).fullCycleType = f.factorDegrees p := by
  set g := f.map (Int.castRingHom ℚ)
  set M := g.SplittingField
  have : Fact ((g.map (algebraMap ℚ M)).Splits) := ⟨SplittingField.splits g⟩
  have hsq : Squarefree (f.map (Int.castRingHom (ZMod p))) :=
    ((hf.separable_map_zmod_iff_not_dvd_discr p).mpr hp).squarefree
  have : IsGalois ℚ M := IsGalois.of_separable_splitting_field
    ((hf.discr_ne_zero_iff_separable_map ℚ).mp fun h => hp (h ▸ dvd_zero _))
  have : (span {(p : ℤ)} : Ideal ℤ).IsPrime :=
    (span_singleton_prime (by exact_mod_cast (Fact.out : p.Prime).ne_zero)).mpr
      (Nat.prime_iff_prime_int.mp Fact.out)
  obtain ⟨⟨Q, _, _⟩⟩ := (span {(p : ℤ)}).nonempty_primesOver (S := 𝓞 M)
  obtain ⟨σ, hσ⟩ := NumberField.exists_isArithFrobAt_int_of_liesOver (K := M) (p := p) Q
  refine ⟨Gal.restrict g M σ, ?_⟩
  rw [← fullCycleType_galActionHom_restrict_eq_factorDegrees hf hsq Q hσ,
    Gal.galActionHom_eq_permCongr g M ℂ, Equiv.Perm.fullCycleType_permCongr]

open scoped Classical in
/-- **Dedekind's theorem, with the fixed points counted separately.** The multiset of degrees of
the monic irreducible factors of `minpoly ℤ θ` modulo `p` is the cycle type of a Frobenius at a
prime above `p` acting on the roots of `minpoly ℚ θ`, together with one part `1` for each fixed
root. This is the form with the cycle type and the fixed points separated; the full cycle type of
`fullCycleType_galActionHom_restrict_minpoly_eq_map_natDegree_monicFactorsMod` packages the two
summands. -/
theorem factorizationType_eq_cycleType_isArithFrobAt
    {K : Type*} [Field K] [NumberField K] {θ : 𝓞 K}
    (hsq : Squarefree ((minpoly ℤ θ).map (Int.castRingHom (ZMod p))))
    [Fact (((minpoly ℚ (θ : K)).map (algebraMap ℚ M)).Splits)]
    (Q : Ideal (𝓞 M)) [Q.IsPrime] [Q.LiesOver (span {(p : ℤ)})]
    {σ : M ≃ₐ[ℚ] M} (hσ : IsArithFrobAt ℤ σ Q) :
    (RingOfIntegers.monicFactorsMod θ p).val.map natDegree =
      (Gal.galActionHom (minpoly ℚ (θ : K)) M
          (Gal.restrict (minpoly ℚ (θ : K)) M σ)).cycleType +
        Multiset.replicate (Nat.card (Function.fixedPoints
          (Gal.galActionHom (minpoly ℚ (θ : K)) M
            (Gal.restrict (minpoly ℚ (θ : K)) M σ)))) 1 := by
  rw [← fullCycleType_galActionHom_restrict_minpoly_eq_map_natDegree_monicFactorsMod hsq Q hσ,
    Equiv.Perm.fullCycleType_def, Equiv.Perm.parts_partition, Nat.card_eq_fintype_card,
    Equiv.Perm.card_fixedPoints, Equiv.Perm.sum_cycleType]

end EpsilonEridani.NumberField
