/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.GroupTheory.Coset.Basic
public import Mathlib.SetTheory.Cardinal.Finite

/-!
# Gaschütz's lemma on lifting generators

Let `f : G →* H` be a surjective homomorphism of finite groups and suppose that `G` is generated
by `n` elements. Gaschütz's lemma says that every generating `n`-tuple of `H` lifts to a
generating `n`-tuple of `G`: not merely to some `n`-tuple, which is trivial, but to one that
still generates.

The proof is a counting argument. For a subgroup `K ≤ G` and a tuple `h` generating `H`, let
`N(K, h)` be the number of tuples generating `K` and lifting `h`. The tuples *in* `K` lifting `h`
are counted by `|K ∩ ker f|^n` whenever `K` maps onto `H`, a number independent of `h`, and they
are partitioned by the subgroup they generate, so
`|K ∩ ker f|^n = ∑_{L ≤ K} N(L, h)`. Induction on `K` then shows that `N(K, h)` does not depend
on `h` (`MonoidHom.card_comp_eq_and_closure_range_eq_congr`). As `N(G, f ∘ g) ≥ 1` for a generating
tuple `g` of `G`, also `N(G, h) ≥ 1`, which is the lifting statement.

## Main results

* `MonoidHom.card_forall_mem_and_comp_eq_congr`: the number of tuples in a subgroup `K` lifting a
  tuple of `H` along `f` does not depend on the tuple, as long as `K` maps onto `H`.
* `MonoidHom.card_comp_eq_and_closure_range_eq_congr`: **Gaschütz's counting lemma**: the number of
  tuples generating `K` and lifting a generating tuple of `H` does not depend on that tuple.
* `MonoidHom.exists_comp_eq_and_closure_range_eq_top_of_surjective`: **Gaschütz's lemma**: along a
  surjection of finite groups, a generating tuple of the target lifts to a generating tuple of the
  source, provided the source is generated by a tuple of the same shape.

## References

* W. Gaschütz, *Zu einem von B. H. und H. Neumann gestellten Problem*, Math. Nachr. 14 (1955),
  249–252.
* L. Ribes and P. Zalesskii, *Profinite Groups*, Lemma 2.5.3.
-/

public section

namespace MonoidHom

variable {G H ι : Type*} [Group G] [Group H] (f : G →* H)

/-- If the subgroup `K` maps onto `H`, the number of `ι`-tuples in `K` lifting a tuple of `H`
along `f` does not depend on the tuple: such tuples are families of elements of the fibres of
`f.comp K.subtype`, and all fibres of a surjective homomorphism have the cardinality of its
kernel. -/
theorem card_forall_mem_and_comp_eq_congr {K : Subgroup G} (hK : K.map f = ⊤) (h h' : ι → H) :
    Nat.card {x : ι → G // (∀ i, x i ∈ K) ∧ f ∘ x = h} =
      Nat.card {x : ι → G // (∀ i, x i ∈ K) ∧ f ∘ x = h'} := by
  have hsurj : Function.Surjective (f.comp K.subtype) := fun y ↦ by
    obtain ⟨k, hk, rfl⟩ := Subgroup.mem_map.mp (hK ▸ Subgroup.mem_top y)
    exact ⟨⟨k, hk⟩, rfl⟩
  -- Tuples in `K` lifting `h` are families of elements of the fibres over the `h i`.
  let e : ∀ h : ι → H,
      {x : ι → G // (∀ i, x i ∈ K) ∧ f ∘ x = h} ≃ ∀ i, f.comp K.subtype ⁻¹' {h i} := fun h ↦
    { toFun x i := ⟨⟨x.1 i, x.2.1 i⟩, congr_fun x.2.2 i⟩
      invFun y := ⟨fun i ↦ ((y i : K) : G), fun i ↦ (y i).1.2, funext fun i ↦ (y i).2⟩
      left_inv _ := rfl
      right_inv _ := rfl }
  exact Nat.card_congr ((e h).trans
    ((Equiv.piCongrRight fun i ↦ fiberEquivOfSurjective hsurj (h i) (h' i)).trans (e h').symm))

variable [Finite G] [Finite ι]

/-- **Gaschütz's counting lemma.** For a subgroup `K` of a finite group `G`, the number of
`ι`-tuples that generate `K` and lift a given generating tuple of `H` along `f` does not depend on
that generating tuple. -/
theorem card_comp_eq_and_closure_range_eq_congr (K : Subgroup G) {h h' : ι → H}
    (hh : Subgroup.closure (Set.range h) = ⊤) (hh' : Subgroup.closure (Set.range h') = ⊤) :
    Nat.card {x : ι → G // f ∘ x = h ∧ Subgroup.closure (Set.range x) = K} =
      Nat.card {x : ι → G // f ∘ x = h' ∧ Subgroup.closure (Set.range x) = K} := by
  classical
  cases nonempty_fintype G
  cases nonempty_fintype ι
  have : Finite (Subgroup G) := Finite.of_injective _ SetLike.coe_injective
  let _ : Fintype (Subgroup G) := Fintype.ofFinite _
  induction K using WellFoundedLT.induction with
  | ind K ih =>
  by_cases hK : K.map f = ⊤
  · -- The tuples in `K` lifting a generating tuple `h` are partitioned by the subgroup `L ≤ K`
    -- they generate; the summand at `L < K` is independent of `h` by induction, and the total
    -- is independent of `h` by `card_forall_mem_and_comp_eq_congr`.
    have key : ∀ h : ι → H,
        Nat.card {x : ι → G // (∀ i, x i ∈ K) ∧ f ∘ x = h} =
          ∑ L ∈ Finset.univ.filter (· ≤ K),
            Nat.card {x : ι → G // f ∘ x = h ∧ Subgroup.closure (Set.range x) = L} := by
      intro h
      simp only [Nat.card_eq_fintype_card, Fintype.card_subtype]
      rw [Finset.card_eq_sum_card_fiberwise (f := fun x : ι → G ↦ Subgroup.closure (Set.range x))
        (t := Finset.univ.filter (· ≤ K))]
      · refine Finset.sum_congr rfl fun L hL ↦ ?_
        have hLK : L ≤ K := (Finset.mem_filter.mp hL).2
        rw [Finset.filter_filter]
        refine congr_arg Finset.card (Finset.filter_congr fun x _ ↦ ?_)
        constructor
        · rintro ⟨⟨-, hx⟩, hxL⟩
          exact ⟨hx, hxL⟩
        · rintro ⟨hx, hxL⟩
          exact ⟨⟨fun i ↦ hLK (hxL ▸ Subgroup.subset_closure (Set.mem_range_self i)), hx⟩, hxL⟩
      · intro x hx
        simp only [Finset.coe_filter, Finset.mem_univ, true_and, Set.mem_ofPred_eq] at hx ⊢
        exact (Subgroup.closure_le K).mpr (Set.range_subset_iff.mpr hx.1)
    have hKmem : K ∈ Finset.univ.filter (· ≤ K) := Finset.mem_filter.mpr ⟨Finset.mem_univ K, le_rfl⟩
    have htotal := f.card_forall_mem_and_comp_eq_congr hK h h'
    rw [key h, key h', ← Finset.add_sum_erase _ _ hKmem, ← Finset.add_sum_erase _ _ hKmem]
      at htotal
    have hrest : ∑ L ∈ (Finset.univ.filter (· ≤ K)).erase K,
          Nat.card {x : ι → G // f ∘ x = h ∧ Subgroup.closure (Set.range x) = L} =
        ∑ L ∈ (Finset.univ.filter (· ≤ K)).erase K,
          Nat.card {x : ι → G // f ∘ x = h' ∧ Subgroup.closure (Set.range x) = L} :=
      Finset.sum_congr rfl fun L hL ↦ ih L (lt_of_le_of_ne
        (Finset.mem_filter.mp (Finset.mem_of_mem_erase hL)).2 (Finset.ne_of_mem_erase hL))
    omega
  · -- No tuple generating `K` lifts a generating tuple of `H`, because the image of such a
    -- tuple would generate `K.map f = ⊤`.
    have hzero : ∀ {h : ι → H}, Subgroup.closure (Set.range h) = ⊤ →
        Nat.card {x : ι → G // f ∘ x = h ∧ Subgroup.closure (Set.range x) = K} = 0 := by
      intro h hh
      refine Nat.card_eq_zero.mpr (Or.inl ⟨fun ⟨x, hx, hxK⟩ ↦ hK ?_⟩)
      rw [← hxK, MonoidHom.map_closure, ← Set.range_comp, hx, hh]
    rw [hzero hh, hzero hh']

/-- **Gaschütz's lemma.** Let `f : G →* H` be a surjective homomorphism from a finite group, and
let `G` be generated by an `ι`-tuple. Then every generating `ι`-tuple of `H` lifts along `f` to a
generating `ι`-tuple of `G`. -/
theorem exists_comp_eq_and_closure_range_eq_top_of_surjective (hf : Function.Surjective f)
    {g : ι → G} (hg : Subgroup.closure (Set.range g) = ⊤) {h : ι → H}
    (hh : Subgroup.closure (Set.range h) = ⊤) :
    ∃ g' : ι → G, f ∘ g' = h ∧ Subgroup.closure (Set.range g') = ⊤ := by
  have hfg : Subgroup.closure (Set.range (f ∘ g)) = ⊤ := by
    rw [Set.range_comp, ← MonoidHom.map_closure, hg, Subgroup.map_top_of_surjective f hf]
  have hpos : 0 < Nat.card {x : ι → G // f ∘ x = h ∧ Subgroup.closure (Set.range x) = ⊤} := by
    rw [f.card_comp_eq_and_closure_range_eq_congr ⊤ hh hfg]
    have : Nonempty {x : ι → G // f ∘ x = f ∘ g ∧ Subgroup.closure (Set.range x) = ⊤} :=
      ⟨⟨g, rfl, hg⟩⟩
    exact Nat.card_pos
  obtain ⟨⟨x, hx, hxtop⟩⟩ := (Nat.card_pos_iff.mp hpos).1
  exact ⟨x, hx, hxtop⟩

end MonoidHom
