/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.NumberTheory.Multiquadratic.CandidateGenusField.GaloisGroup
public import EpsilonEridani.NumberTheory.Multiquadratic.CandidateGenusField.Relative.Degree
public import EpsilonEridani.NumberTheory.Multiquadratic.Unramified.Basic
import EpsilonEridani.FieldTheory.Minpoly
import EpsilonEridani.NumberTheory.Multiquadratic.Unramified.Maximality

/-!
# The narrow genus field of a quadratic field

This file gives the intrinsic finite-place characterization of the narrow genus field and proves
that the prime-discriminant compositum `candidateGenusField hd` has that characterization.

For a chosen square root `y² = d` in an abelian extension `L / ℚ`, the predicate
`EpsilonEridani.Multiquadratic.IsNarrowGenusField d L y` says that:

* `y` generates a quadratic subfield of `L`;
* `L` is unramified over that subfield at every finite place; and
* every other abelian extension of `ℚ` with these properties embeds into `L` over `ℚ`.

This is the narrow convention: no condition is imposed at the infinite places. For a real
quadratic field this is the field whose Galois group is governed by the narrow class group, unlike
the everywhere-unramified genus field governed by the ordinary class group. The universal
property is expressed through embeddings instead of a chosen algebraic closure, and
`IsNarrowGenusField.exists_algEquiv_apply_eq` records the resulting uniqueness by an equivalence
that respects the chosen square roots.

For every squarefree `d` which is not a rational square,
`isNarrowGenusField_candidateGenusField` assembles the already-established finite-prime
ramification and maximality theorems. Thus the prime-discriminant compositum is the narrow genus
field in both signatures. This supplies the field side needed for the real quadratic narrow
`2`-rank formula in Layer 3 of the Multiquadratic roadmap; identifying its relative Galois group
with the elementary-two quotient of the narrow class group remains downstream.

## Provenance

The universal-property packaging and uniqueness argument are the finite-place counterparts of the
everywhere-unramified `IsGenusField` developed in EpsilonEridani pull request #5041. This file supplies
the narrow variant which the roadmap requires separately for real quadratic fields.

## References

* D. A. Cox, *Primes of the Form x² + ny²*, Section 6.A.
* F. Lemmermeyer, *Reciprocity Laws: From Euler to Eisenstein*, Section 2.2.
-/

public section

open IntermediateField NumberField
open scoped NumberField

namespace EpsilonEridani.Multiquadratic

universe u

/-- An abelian extension `L / ℚ`, with a chosen quadratic subfield generated by `y² = d`, is a
**narrow genus field** when it is unramified over that subfield at every finite place and is
maximal among abelian extensions with those properties.

No condition is imposed at infinite places. This is the distinction between the narrow genus
field and the everywhere-unramified genus field for a real quadratic radicand. -/
structure IsNarrowGenusField (d : ℤ) (L : Type u) [Field L] [NumberField L] (y : L) : Prop where
  /-- The chosen element is a square root of the radicand. -/
  root_sq : y ^ 2 = algebraMap ℤ L d
  /-- The chosen root generates a quadratic subfield. -/
  finrank_adjoin : Module.finrank ℚ (adjoin ℚ {y} : IntermediateField ℚ L) = 2
  /-- The ambient extension is abelian and Galois over `ℚ`. -/
  isAbelianGalois : IsAbelianGalois ℚ L
  /-- The extension is unramified at every finite prime over its quadratic subfield. -/
  isUnramifiedAtFinitePlaces :
    ∀ q : Ideal (𝓞 (adjoin ℚ {y} : IntermediateField ℚ L)),
      q.IsPrime → q ≠ ⊥ → Algebra.IsUnramifiedIn (𝓞 L) q
  /-- Maximality among abelian extensions unramified at every finite place over `ℚ(√d)`. -/
  maximal :
    ∀ {M : Type u} [Field M] [NumberField M] [IsAbelianGalois ℚ M] {z : M},
      z ^ 2 = algebraMap ℤ M d →
      (∀ q : Ideal (𝓞 (adjoin ℚ {z} : IntermediateField ℚ M)),
        q.IsPrime → q ≠ ⊥ → Algebra.IsUnramifiedIn (𝓞 M) q) →
      Nonempty (M →ₐ[ℚ] L)

namespace IsNarrowGenusField

variable {d : ℤ}
variable {L M : Type u} [Field L] [NumberField L] [Field M] [NumberField M]
variable {y : L} {z : M}

/-- Any two narrow genus fields for the same radicand are isomorphic as `ℚ`-algebras by an
equivalence carrying the chosen square root in the first field to the chosen square root in the
second.

Each universal property supplies an embedding in one direction. Finite-dimensionality turns the
two resulting degree inequalities into equality, after which either embedding is surjective. A
target automorphism supplied by normality then makes the equivalence respect the chosen roots. -/
theorem exists_algEquiv_apply_eq (hL : IsNarrowGenusField d L y)
    (hM : IsNarrowGenusField d M z) : ∃ e : L ≃ₐ[ℚ] M, e y = z := by
  let _ : IsAbelianGalois ℚ L := hL.isAbelianGalois
  let _ : IsAbelianGalois ℚ M := hM.isAbelianGalois
  obtain ⟨φ⟩ := hM.maximal hL.root_sq hL.isUnramifiedAtFinitePlaces
  obtain ⟨ψ⟩ := hL.maximal hM.root_sq hM.isUnramifiedAtFinitePlaces
  have hLM : Module.finrank ℚ L ≤ Module.finrank ℚ M :=
    LinearMap.finrank_le_finrank_of_injective (f := φ.toLinearMap) φ.injective
  have hML : Module.finrank ℚ M ≤ Module.finrank ℚ L :=
    LinearMap.finrank_le_finrank_of_injective (f := ψ.toLinearMap) ψ.injective
  have hrank : Module.finrank ℚ L = Module.finrank ℚ M := le_antisymm hLM hML
  let e : L ≃ₐ[ℚ] M := EpsilonEridani.algEquivOfFinrankEq φ hrank
  have hminpoly {N : Type u} [Field N] [NumberField N] {w : N}
      (hN : IsNarrowGenusField d N w) :
      minpoly ℚ w = Polynomial.X ^ 2 - Polynomial.C ((d : ℤ) : ℚ) := by
    apply EpsilonEridani.Algebra.minpoly_eq_X_sq_sub_C_of_sq_eq_of_natDegree_eq_two
    · rw [hN.root_sq, IsScalarTower.algebraMap_apply ℤ ℚ N]
      norm_num
    · rw [← IntermediateField.adjoin.finrank (Algebra.IsIntegral.isIntegral w)]
      exact hN.finrank_adjoin
  have hmin : minpoly ℚ (e y) = minpoly ℚ z := by
    rw [minpoly.algEquiv_eq e y, hminpoly hL, hminpoly hM]
  have heval : Polynomial.aeval (e y) (minpoly ℚ z) = 0 := by
    rw [← hmin]
    exact minpoly.aeval ℚ (e y)
  obtain ⟨σ, hσ⟩ := minpoly.exists_algEquiv_of_root
    (Algebra.IsAlgebraic.isAlgebraic z) heval
  exact ⟨e.trans σ, by simpa only [AlgEquiv.trans_apply] using hσ⟩

/-- Any two narrow genus fields for the same radicand are isomorphic as `ℚ`-algebras. -/
theorem nonempty_algEquiv (hL : IsNarrowGenusField d L y) (hM : IsNarrowGenusField d M z) :
    Nonempty (L ≃ₐ[ℚ] M) :=
  (exists_algEquiv_apply_eq hL hM).nonempty

end IsNarrowGenusField

/-- **The prime-discriminant compositum is the narrow genus field.** For a squarefree integer `d`
which is not a rational square, `candidateGenusField hd` is abelian over `ℚ`, is unramified at
every finite place over its embedded copy of `ℚ(√d)`, and contains every other abelian extension
with those properties. -/
theorem isNarrowGenusField_candidateGenusField {d : ℤ} (hd : Squarefree d)
    (hnsq : ¬ IsSquare ((d : ℤ) : ℚ)) :
    IsNarrowGenusField d (candidateGenusField hd) (candidateGenusFieldBaseRoot hd) := by
  refine
    { root_sq := ?_
      finrank_adjoin := ?_
      isAbelianGalois := inferInstance
      isUnramifiedAtFinitePlaces := ?_
      maximal := ?_ }
  · rw [candidateGenusFieldBaseRoot_sq hd, IsScalarTower.algebraMap_apply ℤ ℚ]
    norm_num
  · rw [← candidateGenusFieldBase_def hd]
    exact finrank_candidateGenusFieldBase hd hnsq
  · rw [← candidateGenusFieldBase_def hd]
    exact fun q hq _ ↦ isUnramifiedIn_candidateGenusField hd hnsq q
  · intro M _ _ _ z hz hfinite
    exact nonempty_algHom_candidateGenusField hd hnsq hz hfinite

end EpsilonEridani.Multiquadratic
