/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.NumberTheory.Multiquadratic.Quadratic.Ramification
public import EpsilonEridani.NumberTheory.NumberField.Inertia

/-!
# Ramified primes in a Galois extension unramified over a quadratic subfield

Let `M / ℚ` be a Galois number-field extension and let `F ⊆ M` be a quadratic intermediate field
such that `M / F` is unramified at every finite prime. This file computes which rational primes
ramify in the intermediate fields of `M`. Two statements come out, and together they say that the
quadratic subfields of `M` ramified at a fixed prime `p` form a coset of those unramified at `p`.

* **Ramification descends to `F`.** Every rational prime ramifying in an intermediate field of `M`
  already ramifies in `F`.
* **Two ramified square roots multiply to an unramified one.** If `√a ∈ M` and `p` ramifies in
  `ℚ(√a)`, then `p` is unramified in `ℚ(√(ab))`, where `ℚ(√b) = F`.

Both are read off the inertia subgroups of the primes `P` of `𝓞 M` above `p`: an intermediate
field is unramified at `p` exactly when every one of them fixes it pointwise
(`NumberField.notMem_ramifiedPrimes_iff_forall_inertia_le`). Unramifiedness of `M / F` makes such
an inertia subgroup `I` meet `Gal(M / F)` trivially
(`NumberField.disjoint_inertia_of_ramificationIdx_eq_one`), and `Gal(M / F)` has index two, so any
two nonidentity elements of `I` coincide: `I` is `{1}` at an unramified prime and `{1, σ}` at a
ramified one. Since `σ` sends a square root of a rational number to plus or minus itself,
`σ √a = -√a` and `σ √b = -√b` give `σ (√a √b) = √a √b`, which is the second statement; and
`σ ≠ 1` does not lie in `Gal(M / F)`, which is the first.

For the second statement one prime above `p` still settles the others: the Galois group permutes
them transitively and conjugates their inertia subgroups (`Ideal.mem_inertia_pointwise_smul_iff`),
while `g √c = ±√c` for rational `c` makes fixing a quadratic subfield generated by a square root a
conjugation-invariant condition.

The arithmetic form of both statements is stated with `fundamentalDiscriminant`, using that the
discriminant of `ℚ(√a)` for squarefree `a` is `fundamentalDiscriminant a`
(`EpsilonEridani.Multiquadratic.discr_adjoin_singleton_eq_fundamentalDiscriminant`). It constrains the
prime discriminants of a quadratic subfield of `M` by those of `F`, which is the arithmetic half of
the maximality proof for the candidate genus field. The field-theoretic half is
`EpsilonEridani.Multiquadratic.exists_squarefree_root_adjoin_range_eq_top_of_isUnramifiedIn_over_quadratic`
in `EpsilonEridani/NumberTheory/Multiquadratic/Unramified/Basic.lean`, which presents such an `M` as a
multiquadratic field.

This is the classical argument in the genus-field construction; see D. A. Cox, *Primes of the Form
x² + ny²*, §6.A, and F. Lemmermeyer, *Reciprocity Laws: From Euler to Eisenstein*, §2.2.

## Main results

In the namespace `EpsilonEridani.Multiquadratic`:

* `ramifiedPrimes_subset_of_isUnramifiedIn`: a prime ramifying in an intermediate field ramifies
  in the quadratic subfield.
* `notMem_ramifiedPrimes_adjoin_mul`: a prime ramifying in `ℚ(√a)` is unramified in `ℚ(√(ab))`.
* `dvd_fundamentalDiscriminant_base_of_dvd_subfield` and
  `not_dvd_fundamentalDiscriminant_mul_of_dvd_subfield`: the arithmetic forms.

## Provenance

Independently reconstructed. The multiquadratic roadmap designates
[kim-em/erdos-unit-distance](https://github.com/kim-em/erdos-unit-distance) (the formalization of
L. Alpöge's disproof of the uniform-constant Erdős unit-distance conjecture) as the migration
source for its Layer-0 square-class machinery — `sqrtTower`, `mem_sup_adjoin_sq`,
`squareClass_of_sqrt_mem`, `sqrtTower_finrank`, `exists_transversal_family` and
`units_sq_index_le` — and none of that is used here: this file is inertia theory over the Galois
group of `M / ℚ`, resting on Mathlib's `Ideal.inertia` and on
`EpsilonEridani/NumberTheory/NumberField/Inertia.lean`.
-/

public section

open IntermediateField NumberField

open scoped NumberField

namespace EpsilonEridani.Multiquadratic

variable {M : Type*} [Field M] [NumberField M] [IsGalois ℚ M]

omit [IsGalois ℚ M] in
/-- An automorphism sends a square root of a rational number to plus or minus itself. -/
private theorem apply_eq_or_eq_neg {σ : M ≃ₐ[ℚ] M} {z : M} {c : ℚ}
    (hz : z ^ 2 = algebraMap ℚ M c) : σ z = z ∨ σ z = -z := by
  have hsq : σ z ^ 2 = z ^ 2 := by rw [← map_pow, hz, AlgEquiv.commutes]
  exact sq_eq_sq_iff_eq_or_eq_neg.mp hsq

omit [IsGalois ℚ M] in
/-- **Fixing a square root of a rational number is a conjugation-invariant condition.** If the
conjugate `g⁻¹ σ g` fixes `ℚ(z)` pointwise then so does `σ`, because `g z = ± z`. -/
private theorem mem_fixingSubgroup_adjoin_singleton_of_conj {σ g : M ≃ₐ[ℚ] M} {z : M} {c : ℚ}
    (hz : z ^ 2 = algebraMap ℚ M c)
    (h : g⁻¹ * σ * g ∈
      fixingSubgroup (M ≃ₐ[ℚ] M) ((adjoin ℚ {z} : IntermediateField ℚ M) : Set M)) :
    σ ∈ fixingSubgroup (M ≃ₐ[ℚ] M) ((adjoin ℚ {z} : IntermediateField ℚ M) : Set M) := by
  rw [_root_.mem_fixingSubgroup_iff] at h ⊢
  -- `mem_fixingSubgroup_iff` uses automorphism application, whereas the reusable fixed-on-adjoin
  -- criterion is stated for the definitionally equal scalar action; expose that form explicitly.
  change (∀ y ∈ adjoin ℚ {z}, (g⁻¹ * σ * g) • y = y) at h
  change ∀ y ∈ adjoin ℚ {z}, σ • y = y
  rw [IntermediateField.forall_mem_adjoin_smul_eq_self_iff] at h ⊢
  simp only [Set.mem_singleton_iff, forall_eq] at h ⊢
  -- Return from scalar action to `AlgEquiv` application for the conjugation calculation below.
  change (g⁻¹ * σ * g) z = z at h
  change σ z = z
  rw [AlgEquiv.mul_apply, AlgEquiv.mul_apply, AlgEquiv.aut_inv, AlgEquiv.symm_apply_eq] at h
  rcases apply_eq_or_eq_neg (σ := g) hz with hg | hg
  · rwa [hg] at h
  · rw [hg, map_neg, neg_inj] at h
    exact h

/-- The inertia subgroup at a prime above `p` meets `Gal(M / F)` trivially when `M / F` is
unramified at every finite prime. -/
private theorem disjoint_inertia (F : IntermediateField ℚ M)
    (hunr : ∀ q : Ideal (𝓞 F), q.IsPrime → q ≠ ⊥ → Algebra.IsUnramifiedIn (𝓞 M) q)
    {p : ℕ} (hp : p.Prime) (P : Ideal (𝓞 M)) (hP : P.IsPrime)
    (hPp : P.LiesOver (Ideal.span {(p : ℤ)})) :
    Disjoint (P.inertia (M ≃ₐ[ℚ] M)) (fixingSubgroup (M ≃ₐ[ℚ] M) (F : Set M)) := by
  have : P.IsPrime := hP
  have : P.LiesOver (Ideal.span {(p : ℤ)}) := hPp
  let _ : NumberField F := NumberField.of_intermediateField F
  have hbot : (Ideal.span {(p : ℤ)} : Ideal ℤ) ≠ ⊥ := by simpa using hp.ne_zero
  have hq : (P.under (𝓞 F)) ≠ ⊥ :=
    Ideal.ne_bot_of_liesOver_of_ne_bot (p := Ideal.span {(p : ℤ)}) hbot _
  exact NumberField.disjoint_inertia_of_ramificationIdx_eq_one (F := F)
    (fixingSubgroup (M ≃ₐ[ℚ] M) (F : Set M)) P hP
    ((hunr (P.under (𝓞 F)) inferInstance hq).ramificationIdx_eq_one inferInstance)

/-- **Ramification descends to the quadratic subfield.** Let `M / ℚ` be Galois, let `F ⊆ M` be an
intermediate field such that `M / F` is unramified at every finite prime, and let `E ⊆ M` be any
intermediate field. Then every rational prime ramifying in `E` ramifies in `F`.

Were such a prime unramified in `F`, the inertia subgroup of every prime `P` of `𝓞 M` above it
would be contained in `Gal(M / F)`; being also disjoint from `Gal(M / F)` it would be trivial,
hence contained in `Gal(M / E)`, and the prime would be unramified in `E`. -/
theorem ramifiedPrimes_subset_of_isUnramifiedIn (F E : IntermediateField ℚ M)
    (hunr : ∀ q : Ideal (𝓞 F), q.IsPrime → q ≠ ⊥ → Algebra.IsUnramifiedIn (𝓞 M) q) :
    ramifiedPrimes E ⊆ ramifiedPrimes F := by
  classical
  intro p hpE
  have hp : p.Prime := NumberField.prime_of_mem_ramifiedPrimes hpE
  let _ : NumberField E := NumberField.of_intermediateField E
  let _ : NumberField F := NumberField.of_intermediateField F
  by_contra hpF
  refine absurd hpE ((NumberField.notMem_ramifiedPrimes_iff_forall_inertia_le (K := M) (F := E)
    (fixingSubgroup (M ≃ₐ[ℚ] M) (E : Set M)) hp).mpr fun P hP hPp => ?_)
  have hle := (NumberField.notMem_ramifiedPrimes_iff_forall_inertia_le (K := M) (F := F)
    (fixingSubgroup (M ≃ₐ[ℚ] M) (F : Set M)) hp).mp hpF P hP hPp
  rw [(disjoint_inertia F hunr hp P hP hPp).eq_bot_of_le hle]
  exact bot_le

/-- **Two ramified square roots multiply to an unramified one.** Let `M / ℚ` be Galois, let
`y ∈ M` be a square root of a rational number generating a quadratic subfield `ℚ(y)`, and suppose
`M / ℚ(y)` is unramified at every finite prime. Let `x ∈ M` be a square root of a rational number.
If a rational prime `p` ramifies in `ℚ(x)`, then it is unramified in `ℚ(r x y)` for every
rational `r`.

Ramification in `ℚ(x)` produces a prime `P₀` above `p` whose inertia subgroup `I` does not fix
`ℚ(x)` pointwise, say `τ ∈ I` with `τ x ≠ x`, hence `τ x = -x`. As `I` is disjoint from
`Gal(M / ℚ(y))`, which has index two, any two nonidentity elements of `I` coincide: a nonidentity
`σ ∈ I` satisfies `σ τ = 1`, so `σ x = -x`, while `σ ∉ Gal(M / ℚ(y))` forces `σ y = -y`. Thus `σ`
fixes `x y`, and `I` fixes `ℚ(r x y)` pointwise. Any other prime above `p` is a translate
`g • P₀`, whose inertia subgroup is the conjugate `g I g⁻¹`, and fixing `ℚ(r x y)` is invariant
under conjugation. -/
theorem notMem_ramifiedPrimes_adjoin_mul {x y : M} {a b : ℚ}
    (hx : x ^ 2 = algebraMap ℚ M a) (hy : y ^ 2 = algebraMap ℚ M b)
    (hdeg : Module.finrank ℚ (adjoin ℚ {y} : IntermediateField ℚ M) = 2)
    (hunr : ∀ q : Ideal (𝓞 (adjoin ℚ {y} : IntermediateField ℚ M)), q.IsPrime → q ≠ ⊥ →
      Algebra.IsUnramifiedIn (𝓞 M) q)
    (r : ℚ) {p : ℕ} (hpx : p ∈ ramifiedPrimes (adjoin ℚ {x} : IntermediateField ℚ M)) :
    p ∉ ramifiedPrimes (adjoin ℚ {algebraMap ℚ M r * (x * y)} : IntermediateField ℚ M) := by
  classical
  have hp : p.Prime := NumberField.prime_of_mem_ramifiedPrimes hpx
  let _ : NumberField (adjoin ℚ {y} : IntermediateField ℚ M) := NumberField.of_intermediateField _
  let _ : NumberField (adjoin ℚ {x} : IntermediateField ℚ M) := NumberField.of_intermediateField _
  let _ : NumberField (adjoin ℚ {algebraMap ℚ M r * (x * y)} : IntermediateField ℚ M) :=
    NumberField.of_intermediateField _
  have hw : (algebraMap ℚ M r * (x * y)) ^ 2 = algebraMap ℚ M (r ^ 2 * (a * b)) := by
    rw [mul_pow, mul_pow, hx, hy, ← map_pow, ← map_mul, ← map_mul]
  have hindex : (fixingSubgroup (M ≃ₐ[ℚ] M)
      ((adjoin ℚ {y} : IntermediateField ℚ M) : Set M)).index = 2 := by
    rw [IsGaloisGroup.index_eq_finrank _ ℚ (adjoin ℚ {y} : IntermediateField ℚ M) M, hdeg]
  -- a prime `P₀` of `𝓞 M` above `p` whose inertia subgroup does not fix `ℚ(x)` pointwise
  obtain ⟨P₀, hP₀, hP₀p, hP₀x⟩ : ∃ P₀ : Ideal (𝓞 M), P₀.IsPrime ∧
      P₀.LiesOver (Ideal.span {(p : ℤ)}) ∧ ¬ P₀.inertia (M ≃ₐ[ℚ] M) ≤
        fixingSubgroup (M ≃ₐ[ℚ] M) ((adjoin ℚ {x} : IntermediateField ℚ M) : Set M) := by
    by_contra hcon
    push Not at hcon
    exact (NumberField.notMem_ramifiedPrimes_iff_forall_inertia_le (K := M)
      (F := adjoin ℚ {x})
      (fixingSubgroup (M ≃ₐ[ℚ] M) ((adjoin ℚ {x} : IntermediateField ℚ M) : Set M)) hp).mpr
      hcon hpx
  have hdisj := disjoint_inertia (adjoin ℚ {y}) hunr hp P₀ hP₀ hP₀p
  obtain ⟨τ, hτI, hτx⟩ : ∃ τ ∈ P₀.inertia (M ≃ₐ[ℚ] M), τ x ≠ x := by
    by_contra hcon
    push Not at hcon
    apply hP₀x
    intro σ hσ
    rw [_root_.mem_fixingSubgroup_iff]
    -- The fixed-on-adjoin criterion uses the scalar-action spelling of automorphism application.
    change ∀ z ∈ adjoin ℚ {x}, σ • z = z
    rw [IntermediateField.forall_mem_adjoin_smul_eq_self_iff]
    simp only [Set.mem_singleton_iff, forall_eq]
    -- Its singleton conclusion is definitionally the ordinary `AlgEquiv` application below.
    change σ x = x
    exact hcon σ hσ
  have hτ1 : τ ≠ 1 := fun h => hτx (by rw [h]; rfl)
  have hτF : τ ∉ fixingSubgroup (M ≃ₐ[ℚ] M) ((adjoin ℚ {y} : IntermediateField ℚ M) : Set M) :=
    fun hmem => hτ1 (Subgroup.disjoint_def.mp hdisj hτI hmem)
  have hτneg : τ x = -x := (apply_eq_or_eq_neg hx).resolve_left hτx
  -- the inertia subgroup at `P₀` fixes `ℚ(r x y)` pointwise
  have hkey : P₀.inertia (M ≃ₐ[ℚ] M) ≤ fixingSubgroup (M ≃ₐ[ℚ] M)
      ((adjoin ℚ {algebraMap ℚ M r * (x * y)} : IntermediateField ℚ M) : Set M) :=
    fun σ hσ => by
      rw [_root_.mem_fixingSubgroup_iff]
      -- Expose the scalar-action form required by the fixed-on-adjoin criterion.
      change ∀ z ∈ adjoin ℚ {algebraMap ℚ M r * (x * y)}, σ • z = z
      rw [IntermediateField.forall_mem_adjoin_smul_eq_self_iff]
      simp only [Set.mem_singleton_iff, forall_eq]
      -- Continue with ordinary `AlgEquiv` application to rewrite by `map_mul` below.
      change σ (algebraMap ℚ M r * (x * y)) = algebraMap ℚ M r * (x * y)
      by_cases hσF : σ ∈ fixingSubgroup (M ≃ₐ[ℚ] M)
        ((adjoin ℚ {y} : IntermediateField ℚ M) : Set M)
      · rw [Subgroup.disjoint_def.mp hdisj hσ hσF]
        rfl
      · have hone : σ * τ = 1 := Subgroup.disjoint_def.mp hdisj (mul_mem hσ hτI)
          ((Subgroup.mul_mem_iff_of_index_two hindex).mpr (by simp only [hσF, hτF]))
        have hσx : σ x = -x := by
          have h1 : (σ * τ) x = x := by rw [hone]; rfl
          rw [AlgEquiv.mul_apply, hτneg, map_neg] at h1
          exact neg_eq_iff_eq_neg.mp h1
        have hσy : σ y = -y := (apply_eq_or_eq_neg hy).resolve_left fun hfix =>
          hσF (by
            rw [_root_.mem_fixingSubgroup_iff]
            -- The fixed-on-adjoin criterion is phrased using the definitionally equal scalar
            -- action.
            change ∀ z ∈ adjoin ℚ {y}, σ • z = z
            rw [IntermediateField.forall_mem_adjoin_smul_eq_self_iff]
            simp only [Set.mem_singleton_iff, forall_eq]
            -- Its singleton conclusion is definitionally the desired `AlgEquiv` application.
            change σ y = y
            exact hfix)
        rw [map_mul, map_mul, AlgEquiv.commutes, hσx, hσy, neg_mul_neg]
  -- every prime above `p` is a translate of `P₀`, and its inertia subgroup the conjugate one
  refine (NumberField.notMem_ramifiedPrimes_iff_forall_inertia_le (K := M)
    (F := adjoin ℚ {algebraMap ℚ M r * (x * y)})
    (fixingSubgroup (M ≃ₐ[ℚ] M)
      ((adjoin ℚ {algebraMap ℚ M r * (x * y)} : IntermediateField ℚ M) : Set M)) hp).mpr
    fun P hP hPp => ?_
  have : P₀.IsPrime := hP₀
  have : P₀.LiesOver (Ideal.span {(p : ℤ)}) := hP₀p
  have : P.IsPrime := hP
  have : P.LiesOver (Ideal.span {(p : ℤ)}) := hPp
  obtain ⟨g, rfl⟩ :=
    Ideal.exists_smul_eq_of_isGaloisGroup (Ideal.span {(p : ℤ)}) P₀ P (M ≃ₐ[ℚ] M)
  intro σ hσ
  rw [Ideal.mem_inertia_pointwise_smul_iff] at hσ
  exact mem_fixingSubgroup_adjoin_singleton_of_conj hw (hkey hσ)

/-- **A ramified prime of a quadratic subfield ramifies in the quadratic base.** In a Galois
`M / ℚ` unramified over `ℚ(√d)` at every finite prime, every prime dividing the discriminant of a
quadratic subfield `ℚ(√a)` divides the discriminant of `ℚ(√d)`. -/
theorem dvd_fundamentalDiscriminant_base_of_dvd_subfield {x y : M} {a d : ℤ}
    (hsfa : Squarefree a) (hsfd : Squarefree d)
    (hx : x ^ 2 = algebraMap ℤ M a) (hy : y ^ 2 = algebraMap ℤ M d)
    (hunr : ∀ q : Ideal (𝓞 (adjoin ℚ {y} : IntermediateField ℚ M)), q.IsPrime → q ≠ ⊥ →
      Algebra.IsUnramifiedIn (𝓞 M) q)
    {p : ℕ} (hp : p.Prime) (hdvd : (p : ℤ) ∣ fundamentalDiscriminant a) :
    (p : ℤ) ∣ fundamentalDiscriminant d := by
  rw [← mem_ramifiedPrimes_adjoin_iff_dvd_fundamentalDiscriminant hsfd hy hp]
  exact ramifiedPrimes_subset_of_isUnramifiedIn _ _ hunr
    ((mem_ramifiedPrimes_adjoin_iff_dvd_fundamentalDiscriminant hsfa hx hp).mpr hdvd)

/-- **The product of two square roots is unramified where the first one ramifies.** In a Galois
`M / ℚ` unramified over the quadratic field `ℚ(√d)` at every finite prime, if `c` is a squarefree
integer in the square class of `a * d` then no prime dividing the discriminant of `ℚ(√a)` divides
the discriminant of `ℚ(√c)`. -/
theorem not_dvd_fundamentalDiscriminant_mul_of_dvd_subfield {x y : M} {a d c e : ℤ}
    (hsfa : Squarefree a) (hsfc : Squarefree c)
    (hx : x ^ 2 = algebraMap ℤ M a) (hy : y ^ 2 = algebraMap ℤ M d)
    (hdeg : Module.finrank ℚ (adjoin ℚ {y} : IntermediateField ℚ M) = 2)
    (hunr : ∀ q : Ideal (𝓞 (adjoin ℚ {y} : IntermediateField ℚ M)), q.IsPrime → q ≠ ⊥ →
      Algebra.IsUnramifiedIn (𝓞 M) q)
    (he : e ≠ 0) (hprod : a * d = c * e ^ 2)
    {p : ℕ} (hp : p.Prime) (hdvd : (p : ℤ) ∣ fundamentalDiscriminant a) :
    ¬ (p : ℤ) ∣ fundamentalDiscriminant c := by
  have hxq : x ^ 2 = algebraMap ℚ M (a : ℚ) := by
    rw [hx, IsScalarTower.algebraMap_apply ℤ ℚ M]; norm_num
  have hyq : y ^ 2 = algebraMap ℚ M (d : ℚ) := by
    rw [hy, IsScalarTower.algebraMap_apply ℤ ℚ M]; norm_num
  have heq : ((e : ℚ)) ≠ 0 := Int.cast_ne_zero.mpr he
  have hz : (algebraMap ℚ M ((e : ℚ)⁻¹) * (x * y)) ^ 2 = algebraMap ℤ M c := by
    have hrat : ((e : ℚ)⁻¹) ^ 2 * ((a : ℚ) * (d : ℚ)) = (c : ℚ) := by
      have hq : (a : ℚ) * (d : ℚ) = (c : ℚ) * (e : ℚ) ^ 2 := by exact_mod_cast hprod
      field_simp
      linear_combination hq
    calc (algebraMap ℚ M ((e : ℚ)⁻¹) * (x * y)) ^ 2
        = algebraMap ℚ M (((e : ℚ)⁻¹) ^ 2) * (x ^ 2 * y ^ 2) := by rw [map_pow]; ring
      _ = algebraMap ℚ M (((e : ℚ)⁻¹) ^ 2 * ((a : ℚ) * (d : ℚ))) := by
            rw [hxq, hyq, map_mul, map_mul]
      _ = algebraMap ℤ M c := by rw [hrat, IsScalarTower.algebraMap_apply ℤ ℚ M]; norm_num
  rw [← mem_ramifiedPrimes_adjoin_iff_dvd_fundamentalDiscriminant hsfc hz hp]
  exact notMem_ramifiedPrimes_adjoin_mul hxq hyq hdeg hunr ((e : ℚ)⁻¹)
    ((mem_ramifiedPrimes_adjoin_iff_dvd_fundamentalDiscriminant hsfa hx hp).mpr hdvd)

end EpsilonEridani.Multiquadratic
