/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.Ring.GeomSum
public import EpsilonEridani.Algebra.AlgebraicGroup.GeneralLinear.Determinant
public import EpsilonEridani.Algebra.AlgebraicGroup.HopfIdeal.Points.Kernel
public import EpsilonEridani.Algebra.AlgebraicGroup.HopfIdeal.Points.Naturality

/-!
# The special linear group coordinate Hopf algebra

For a commutative ring `R`, this file presents the coordinate Hopf algebra of `SLₙ` as the quotient
of `EpsilonEridani.GeneralLinear.coordinateHopfAlgebra R n` by the kernel Hopf ideal of the determinant
coordinate morphism. The underlying ideal is the principal ideal generated by the localized
generic determinant minus one:

`(det - 1) ⊂ R[Xᵢⱼ][det⁻¹]`.

The principal-ideal calculation works over every commutative ring and in every rank. Positive
integral powers use the geometric-series factorization. Negative powers are handled through the
unit attached to the group-like determinant, so no cancellation, nontriviality, or domain
hypothesis is needed.

The generic Hopf-ideal quotient API provides the quotient Hopf algebra. On algebra-valued
points, the generic quotient-point natural isomorphism and the general-linear point equivalence
identify the quotient naturally with Mathlib's `Matrix.SpecialLinearGroup (Fin n) A`; the induced
inclusion is `Matrix.SpecialLinearGroup.toGL`.

This construction includes rank zero and the zero ring. It deliberately stays at the
determinant-kernel boundary: no polynomial presentation, categorical pullback, smoothness,
reductivity, or base-change theorem is asserted here.

## Main declarations

* `EpsilonEridani.SpecialLinear.definingHopfIdeal_toIdeal`: the determinant kernel ideal is generated by
  the localized generic determinant minus one.
* `EpsilonEridani.SpecialLinear.definingHopfIdeal_toIdeal_le_ker_of_map_determinant_eq_one`: a coordinate
  morphism that kills `det - 1` kills the defining ideal of `SLₙ`.
* `EpsilonEridani.SpecialLinear.coordinateHopfAlgebra`: the determinant-one quotient Hopf algebra.
* `EpsilonEridani.SpecialLinear.pointsMulEquiv`: the natural multiplicative equivalence between quotient
  Hopf points and `Matrix.SpecialLinearGroup`.
* `EpsilonEridani.SpecialLinear.pointsNatIso`: the corresponding natural isomorphism of group-valued
  functors.

## References

* J. S. Milne, *Basic Theory of Affine Group Schemes*, Part I, §1.7, pp. 49–50.
* The Stacks Project, Tag 022X, "The general linear group scheme".

The ideal calculation below is a routine direct argument through Tau Ceti's kernel-Hopf-ideal
API; it is not adapted from either reference.
-/

public section

open CategoryTheory WithConv

namespace EpsilonEridani

namespace SpecialLinear

universe u v w

variable (R : Type u) [CommRing R] (n : ℕ)

/-! ### The determinant-one Hopf ideal and quotient -/

/-- Integral powers of a unit differ from one by a multiple of the unit minus one. -/
private lemma units_zpow_sub_one_mem_span {A : Type*} [CommRing A]
    (u : Aˣ) (m : ℤ) :
    (↑(u ^ m) : A) - 1 ∈ Ideal.span {(↑u : A) - 1} := by
  cases m with
  | ofNat k =>
      exact Ideal.mem_of_dvd _
        (by simpa using sub_one_dvd_pow_sub_one (↑u : A) k)
        (Ideal.mem_span_singleton_self ((↑u : A) - 1))
  | negSucc k =>
      have hpow : (↑u : A) ^ (k + 1) - 1 ∈ Ideal.span {(↑u : A) - 1} :=
        Ideal.mem_of_dvd _
          (sub_one_dvd_pow_sub_one (↑u : A) (k + 1))
          (Ideal.mem_span_singleton_self ((↑u : A) - 1))
      have hmul : (↑(u ^ Int.negSucc k) : A) * ((↑u : A) ^ (k + 1)) = 1 := by
        simpa only [zpow_negSucc, inv_pow, Units.val_mul,
          Units.val_inv_eq_inv_val, Units.val_pow_eq_pow_val]
          using (u ^ (k + 1)).inv_mul
      have hsub : (↑(u ^ Int.negSucc k) : A) - 1 =
          -(↑(u ^ Int.negSucc k) : A) * ((↑u : A) ^ (k + 1) - 1) := by
        rw [neg_mul, mul_sub, hmul, mul_one, neg_sub, sub_eq_add_neg, add_comm]
      rw [hsub]
      exact (Ideal.span {(↑u : A) - 1}).mul_mem_left _ hpow

/-- The unit calculation for an integral power of a group-like element. -/
private lemma groupLike_zpow_sub_one_mem_span {A : Type*} [CommRing A] [HopfAlgebra R A]
    (g : _root_.GroupLike R A) (m : ℤ) :
    (↑(g ^ m) : A) - 1 ∈ Ideal.span {(↑g : A) - 1} := by
  have h := units_zpow_sub_one_mem_span (_root_.GroupLike.toUnits R g) m
  rw [← (_root_.GroupLike.toUnits R).map_zpow g m] at h
  simpa only [_root_.GroupLike.val_toUnits_apply] using h

/-- The Hopf ideal cutting out determinant one inside the general-linear coordinate Hopf
algebra. It is the kernel Hopf ideal of the determinant coordinate morphism. -/
noncomputable abbrev definingHopfIdeal :
    HopfIdeal R (GeneralLinear.coordinateHopfAlgebra R n) :=
  CommHopfAlgCat.kernelHopfIdeal (GeneralLinear.determinantCoordinateMap R n)

/-- **The determinant coordinate map agrees with its counit modulo `det - 1`.** On the group
algebra of `ℤ`, the difference between the image of an element and the scalar its counit records
lies in the principal ideal generated by the generic determinant minus one. -/
private lemma determinantCoordinateMap_sub_algebraMap_counit_mem_span
    (x : MonoidAlgebra R (Multiplicative ℤ)) :
    (GeneralLinear.determinantCoordinateMap R n).hom x -
        algebraMap R (GeneralLinear.coordinateHopfAlgebra R n)
          (Coalgebra.counit (R := R) x) ∈
      Ideal.span
        {(GeneralLinear.determinantGroupLike R n :
            GeneralLinear.coordinateHopfAlgebra R n) - 1} := by
  -- On a generator `det ^ m` this is `groupLike_zpow_sub_one_mem_span`; linearity does the rest.
  induction x using MonoidAlgebra.induction_linear with
  | zero => simp
  | add x y hx hy => simpa [map_add, map_sub, add_sub_add_comm] using add_mem hx hy
  | single m r =>
      rw [← ofAdd_toAdd m, GeneralLinear.determinantCoordinateMap_single,
        MonoidAlgebra.counit_single, CommSemiring.counit_apply,
        Algebra.smul_def]
      simpa only [mul_sub, mul_one] using
        (Ideal.span
          {(GeneralLinear.determinantGroupLike R n :
              GeneralLinear.coordinateHopfAlgebra R n) - 1}).mul_mem_left
            (algebraMap R (GeneralLinear.coordinateHopfAlgebra R n) r)
            (groupLike_zpow_sub_one_mem_span (R := R)
              (GeneralLinear.determinantGroupLike R n) m.toAdd)

/-- The harder inclusion of `EpsilonEridani.SpecialLinear.definingHopfIdeal_toIdeal`: the determinant
kernel Hopf ideal is contained in the principal ideal generated by `det - 1`. -/
private lemma definingHopfIdeal_toIdeal_le :
    (definingHopfIdeal R n).toIdeal ≤
      Ideal.span
        {(GeneralLinear.determinantGroupLike R n :
            GeneralLinear.coordinateHopfAlgebra R n) - 1} := by
  rw [CommHopfAlgCat.kernelHopfIdeal_toIdeal, Ideal.map_le_iff_le_comap]
  intro x hx
  rw [Ideal.mem_comap]
  -- The counit vanishes on the kernel Hopf ideal, so the image is the difference of the
  -- previous lemma.
  have hx0 : Coalgebra.counit (R := R) x = 0 :=
    (HopfIdeal.mem_augmentation R
      (_root_.CommHopfAlgCat.of R (MonoidAlgebra R (Multiplicative ℤ)))).mp
      (HopfIdeal.mem_toIdeal.mp hx)
  simpa [hx0] using determinantCoordinateMap_sub_algebraMap_counit_mem_span R n x

/-- The determinant kernel Hopf ideal is the principal ideal generated by the localized generic
determinant minus one. -/
theorem definingHopfIdeal_toIdeal :
    (definingHopfIdeal R n).toIdeal =
      Ideal.span
        {(GeneralLinear.determinantGroupLike R n :
            GeneralLinear.coordinateHopfAlgebra R n) - 1} := by
  refine le_antisymm (definingHopfIdeal_toIdeal_le R n) ?_
  rw [Ideal.span_singleton_le_iff_mem]
  -- The generator is the image of `t - 1` for `t` the degree-one basis vector, whose counit
  -- vanishes, so it lies in the kernel Hopf ideal.
  let t : MonoidAlgebra R (Multiplicative ℤ) :=
    MonoidAlgebra.single (Multiplicative.ofAdd (1 : ℤ)) 1
  have ht : Coalgebra.counit (R := R) (t - 1) = 0 := by
    simp [t]
  have hmem := HopfIdeal.mem_toIdeal.mpr
    (CommHopfAlgCat.mem_kernelHopfIdeal_of_mem_augmentation
      (GeneralLinear.determinantCoordinateMap R n) ht)
  have hmap :
      (GeneralLinear.determinantCoordinateMap R n).hom t =
        (GeneralLinear.determinantGroupLike R n :
          GeneralLinear.coordinateHopfAlgebra R n) := by
    simpa [t] using GeneralLinear.determinantCoordinateMap_single R n 1 1
  simpa [map_sub, hmap] using hmem

/-- A morphism from the coordinate ring of `GLₙ` that sends the generic determinant to one
kills the defining ideal of `SLₙ`. -/
theorem definingHopfIdeal_toIdeal_le_ker_of_map_determinant_eq_one
    {H : _root_.CommHopfAlgCat R}
    (f : GeneralLinear.coordinateHopfAlgebra R n ⟶ H)
    (hdet : f.hom (GeneralLinear.determinantGroupLike R n :
      GeneralLinear.coordinateHopfAlgebra R n) = 1) :
    (definingHopfIdeal R n).toIdeal ≤ RingHom.ker f.hom.toAlgHom.toRingHom := by
  rw [definingHopfIdeal_toIdeal, Ideal.span_singleton_le_iff_mem, RingHom.mem_ker, map_sub]
  simp only [AlgHom.toRingHom_eq_coe, RingHom.coe_coe, BialgHom.coe_toAlgHom, hdet,
    map_one, sub_self]

/-- The coordinate Hopf algebra of `SLₙ`, obtained by imposing determinant one on the
general-linear coordinate Hopf algebra. -/
noncomputable abbrev coordinateHopfAlgebra : _root_.CommHopfAlgCat.{u} R :=
  CommHopfAlgCat.quotient (GeneralLinear.coordinateHopfAlgebra R n)
    (definingHopfIdeal R n)

/-- The quotient coordinate morphism `O(GLₙ) ⟶ O(SLₙ)`. Contravariantly, it is the
closed-subgroup inclusion `SLₙ ⟶ GLₙ`. -/
noncomputable abbrev coordinateMap :
    GeneralLinear.coordinateHopfAlgebra R n ⟶ coordinateHopfAlgebra R n :=
  CommHopfAlgCat.mkQuotient (GeneralLinear.coordinateHopfAlgebra R n)
    (definingHopfIdeal R n)

/-- The special-linear coordinate morphism sends an ambient coordinate to its quotient class. -/
theorem coordinateMap_apply (h : GeneralLinear.coordinateHopfAlgebra R n) :
    (coordinateMap R n).hom h =
      Ideal.Quotient.mkₐ R (definingHopfIdeal R n).toIdeal h :=
  CommHopfAlgCat.mkQuotient_apply
    (GeneralLinear.coordinateHopfAlgebra R n) (definingHopfIdeal R n) h

/-- The localized generic determinant is one in the special-linear coordinate Hopf algebra. -/
@[simp↓]
theorem coordinateMap_determinantGroupLike :
    (coordinateMap R n).hom (GeneralLinear.determinantGroupLike R n) = 1 := by
  rw [coordinateMap_apply]
  apply sub_eq_zero.mp
  rw [← map_one (Ideal.Quotient.mkₐ R (definingHopfIdeal R n).toIdeal), ← map_sub,
    Ideal.Quotient.mkₐ_eq_mk, Ideal.Quotient.eq_zero_iff_mem, definingHopfIdeal_toIdeal]
  exact Ideal.mem_span_singleton_self _

/-- The kernel of the special-linear coordinate morphism is the principal determinant-one
ideal. -/
theorem coordinateMap_ker :
    RingHom.ker (coordinateMap R n).hom.toAlgHom.toRingHom =
      Ideal.span
        {(GeneralLinear.determinantGroupLike R n :
            GeneralLinear.coordinateHopfAlgebra R n) - 1} := by
  rw [CommHopfAlgCat.mkQuotient_ker, definingHopfIdeal_toIdeal]

/-- The special-linear coordinate Hopf algebra bundled with its finite-type algebra property. -/
noncomputable def finiteTypeCoordinateHopfAlgebra : FiniteTypeCommHopfAlgCat R :=
  FiniteTypeCommHopfAlgCat.quotient
    (⟨GeneralLinear.coordinateHopfAlgebra R n, by
      rw [← GeneralLinear.finiteTypeCoordinateHopfAlgebra_obj]
      exact (GeneralLinear.finiteTypeCoordinateHopfAlgebra R n).property⟩ :
      FiniteTypeCommHopfAlgCat R)
    (definingHopfIdeal R n)

/-- The underlying commutative Hopf algebra of the finite-type object is the determinant-one
quotient. -/
@[simp]
theorem finiteTypeCoordinateHopfAlgebra_obj :
    (finiteTypeCoordinateHopfAlgebra R n).obj = coordinateHopfAlgebra R n :=
  by rw [finiteTypeCoordinateHopfAlgebra]

/-- The special-linear coordinate Hopf algebra is a finite-type `R`-algebra, being a quotient of
the finite-type general-linear coordinate Hopf algebra. -/
instance instAlgebraFiniteTypeCoordinateHopfAlgebra :
    Algebra.FiniteType R (coordinateHopfAlgebra R n) :=
  Algebra.FiniteType.quotient R (definingHopfIdeal R n).toIdeal

/-! ### Algebra-valued points -/

section Points

variable {A : Type w} [CommRing A] [Algebra R A]

/-- The determinant point map is the component of the generic contravariant point map induced by
the determinant coordinate morphism. -/
private theorem determinantPoints_eq_mapPointsFunctor_app
    (g : HopfAlgebra.points (R := R)
      (H := GeneralLinear.coordinateHopfAlgebra R n) (CommAlgCat.of R A)) :
    GeneralLinear.determinantPoints R n g =
      (CommHopfAlgCat.mapPointsFunctor
        (GeneralLinear.determinantCoordinateMap R n)).app (CommAlgCat.of R A) g := by
  apply WithConv.ofConv_injective
  apply AlgHom.ext
  intro x
  rw [GeneralLinear.determinantPoints_apply_apply,
    CommHopfAlgCat.mapPointsFunctor_app_apply_apply]

/-- Membership in the point subgroup cut out by the determinant kernel is determinant one.
This is the ambient membership criterion that further cuts consume; the determinant-one cut of
the orthogonal group (`EpsilonEridani.SpecialOrthogonal`) combines it with the orthogonal one. -/
@[simp]
theorem mem_definingPointsSubgroup_iff_det_eq_one
    (g : HopfAlgebra.points (R := R)
      (H := GeneralLinear.coordinateHopfAlgebra R n) (CommAlgCat.of R A)) :
    g ∈ CommHopfAlgCat.quotientPointsSubgroup
        (GeneralLinear.coordinateHopfAlgebra R n) (definingHopfIdeal R n)
        (CommAlgCat.of R A) ↔
      (GeneralLinear.pointsMulEquiv n g : Matrix (Fin n) (Fin n) A).det = 1 := by
  rw [← Matrix.GeneralLinearGroup.val_det_apply, Units.val_eq_one]
  constructor
  · intro hg
    have hpoint : GeneralLinear.determinantPoints R n g = 1 := by
      rw [determinantPoints_eq_mapPointsFunctor_app]
      exact (CommHopfAlgCat.mapPointsFunctor_app_eq_one_iff
        (GeneralLinear.determinantCoordinateMap R n) (CommAlgCat.of R A) g).mpr hg
    rw [← GeneralLinear.pointsMulEquiv_determinantPoints R n g, hpoint, map_one,
      MonoidHom.one_apply]
  · intro hdet
    have hpoint : GeneralLinear.determinantPoints R n g = 1 := by
      apply (DiagonalizableGroup.pointsMulEquiv
        (R := R) (A := A) (G := Multiplicative ℤ)).injective
      apply MonoidHom.ext_mint
      rw [GeneralLinear.pointsMulEquiv_determinantPoints, hdet, map_one,
        MonoidHom.one_apply]
    apply (CommHopfAlgCat.mapPointsFunctor_app_eq_one_iff
      (GeneralLinear.determinantCoordinateMap R n) (CommAlgCat.of R A) g).mp
    have hmap :
        (CommHopfAlgCat.mapPointsFunctor
          (GeneralLinear.determinantCoordinateMap R n)).app (CommAlgCat.of R A) g = 1 := by
      rw [← determinantPoints_eq_mapPointsFunctor_app]
      exact hpoint
    rw [CommHopfAlgCat.mapPointsFunctor_app_apply] at hmap
    exact hmap

/-- Turn a determinant-kernel ambient point into its determinant-one matrix. -/
private noncomputable def pointsSubgroupToSL
    (g : CommHopfAlgCat.quotientPointsSubgroup
      (GeneralLinear.coordinateHopfAlgebra R n) (definingHopfIdeal R n)
      (CommAlgCat.of R A)) :
    Matrix.SpecialLinearGroup (Fin n) A :=
  ⟨(GeneralLinear.pointsMulEquiv n g.1).val,
    (mem_definingPointsSubgroup_iff_det_eq_one R n g.1).mp g.property⟩

/-- Including the matrix attached to a determinant-kernel point recovers its ambient
general-linear matrix. -/
private lemma toGL_pointsSubgroupToSL
    (g : CommHopfAlgCat.quotientPointsSubgroup
      (GeneralLinear.coordinateHopfAlgebra R n) (definingHopfIdeal R n)
      (CommAlgCat.of R A)) :
    Matrix.SpecialLinearGroup.toGL (pointsSubgroupToSL R n g) =
      GeneralLinear.pointsMulEquiv n g.1 := by
  apply Matrix.GeneralLinearGroup.ext
  intro i j
  rfl

/-- Turn a determinant-one matrix into its ambient point, viewed in the determinant-kernel
subgroup. -/
private noncomputable def slToPointsSubgroup
    (s : Matrix.SpecialLinearGroup (Fin n) A) :
    CommHopfAlgCat.quotientPointsSubgroup
      (GeneralLinear.coordinateHopfAlgebra R n) (definingHopfIdeal R n)
      (CommAlgCat.of R A) :=
  ⟨(GeneralLinear.pointsMulEquiv (R := R) n).symm
      (Matrix.SpecialLinearGroup.toGL s), by
    apply (mem_definingPointsSubgroup_iff_det_eq_one R n _).mpr
    rw [MulEquiv.apply_symm_apply]
    exact s.property⟩

/-- The ambient point underlying `slToPointsSubgroup` is obtained from the general-linear point
equivalence. -/
private theorem slToPointsSubgroup_val
    (s : Matrix.SpecialLinearGroup (Fin n) A) :
    (slToPointsSubgroup R n s).1 =
      (GeneralLinear.pointsMulEquiv (R := R) (A := A) n).symm
        (Matrix.SpecialLinearGroup.toGL s) :=
  (rfl)

/-- The subgroup of general-linear points cut out by the determinant kernel is the ordinary
special linear group. -/
private noncomputable def definingPointsSubgroupMulEquiv :
    CommHopfAlgCat.quotientPointsSubgroup
        (GeneralLinear.coordinateHopfAlgebra R n) (definingHopfIdeal R n)
        (CommAlgCat.of R A) ≃*
      Matrix.SpecialLinearGroup (Fin n) A where
  toFun := pointsSubgroupToSL R n
  invFun := slToPointsSubgroup R n
  left_inv g := by
    apply Subtype.ext
    rw [slToPointsSubgroup_val, toGL_pointsSubgroupToSL, MulEquiv.symm_apply_apply]
  right_inv s := by
    apply Matrix.SpecialLinearGroup.toGL_injective
    rw [toGL_pointsSubgroupToSL, slToPointsSubgroup_val, MulEquiv.apply_symm_apply]
  map_mul' g h := by
    apply Matrix.SpecialLinearGroup.toGL_injective
    rw [toGL_pointsSubgroupToSL, map_mul, toGL_pointsSubgroupToSL,
      toGL_pointsSubgroupToSL]
    simpa only [Subgroup.coe_mul] using
      map_mul (GeneralLinear.pointsMulEquiv (R := R) (A := A) n) g.1 h.1

/-- The group of algebra-valued points of the special-linear coordinate Hopf algebra is
Mathlib's special linear group. The construction first applies the generic natural isomorphism
from quotient points to the cut-out ambient subgroup, then reads that subgroup as determinant-one
matrices through the general-linear point equivalence. -/
noncomputable def pointsMulEquiv :
    HopfAlgebra.points (R := R) (H := coordinateHopfAlgebra R n) (CommAlgCat.of R A) ≃*
      Matrix.SpecialLinearGroup (Fin n) A :=
  ((CommHopfAlgCat.quotientPointsSubgroupNatIso
    (GeneralLinear.coordinateHopfAlgebra R n) (definingHopfIdeal R n)).app
    (CommAlgCat.of R A)).groupIsoToMulEquiv.trans
      (definingPointsSubgroupMulEquiv R n)

/-- Internally, the special-linear point equivalence first forms the cut-out ambient subgroup
point and then reads it as a determinant-one matrix. -/
private theorem pointsMulEquiv_apply_eq
    (f : HopfAlgebra.points (R := R) (H := coordinateHopfAlgebra R n)
      (CommAlgCat.of R A)) :
    (pointsMulEquiv (R := R) (A := A) n) f =
      pointsSubgroupToSL R n
        (((CommHopfAlgCat.quotientPointsSubgroupNatIso
          (GeneralLinear.coordinateHopfAlgebra R n) (definingHopfIdeal R n)).app
          (CommAlgCat.of R A)).hom f) :=
  (rfl)

/-- Under the special- and general-linear point equivalences, the quotient-point inclusion is
Mathlib's canonical inclusion `Matrix.SpecialLinearGroup.toGL`. -/
theorem pointsMulEquiv_toGL
    (f : HopfAlgebra.points (R := R) (H := coordinateHopfAlgebra R n)
      (CommAlgCat.of R A)) :
    GeneralLinear.pointsMulEquiv n
        (CommHopfAlgCat.quotientPointsHom
          (GeneralLinear.coordinateHopfAlgebra R n) (definingHopfIdeal R n)
          (CommAlgCat.of R A) f) =
      Matrix.SpecialLinearGroup.toGL
        ((pointsMulEquiv (R := R) (A := A) n) f) := by
  have hcomponent := CommHopfAlgCat.quotientPointsSubgroupNatIso_hom_app_apply
    (GeneralLinear.coordinateHopfAlgebra R n) (definingHopfIdeal R n)
    (CommAlgCat.of R A) f
  rw [pointsMulEquiv_apply_eq]
  calc
    _ = Matrix.SpecialLinearGroup.toGL
        (pointsSubgroupToSL R n
          ⟨CommHopfAlgCat.quotientPointsHom
              (GeneralLinear.coordinateHopfAlgebra R n) (definingHopfIdeal R n)
              (CommAlgCat.of R A) f,
            CommHopfAlgCat.quotientPointsHom_mem_quotientPointsSubgroup
              (GeneralLinear.coordinateHopfAlgebra R n) (definingHopfIdeal R n)
              (CommAlgCat.of R A) f⟩) :=
      (toGL_pointsSubgroupToSL R n _).symm
    _ = _ := (congrArg
      (fun g => Matrix.SpecialLinearGroup.toGL (pointsSubgroupToSL R n g)) hcomponent).symm

/-- The ambient point attached to a special-linear matrix is the general-linear point attached to
its canonical inclusion. -/
@[simp]
theorem quotientPointsHom_pointsMulEquiv_symm
    (s : Matrix.SpecialLinearGroup (Fin n) A) :
    CommHopfAlgCat.quotientPointsHom
        (GeneralLinear.coordinateHopfAlgebra R n) (definingHopfIdeal R n)
        (CommAlgCat.of R A) ((pointsMulEquiv (R := R) (A := A) n).symm s) =
      (GeneralLinear.pointsMulEquiv (R := R) (A := A) n).symm
        (Matrix.SpecialLinearGroup.toGL s) := by
  apply (GeneralLinear.pointsMulEquiv (R := R) (A := A) n).injective
  rw [pointsMulEquiv_toGL, MulEquiv.apply_symm_apply, MulEquiv.apply_symm_apply]

variable {B : Type v} [CommRing B] [Algebra R B]

/-- The special-linear point equivalence is natural in the value algebra: postcomposition of Hopf
points agrees with entrywise mapping of determinant-one matrices. -/
theorem pointsMulEquiv_mapValue (phi : A →ₐ[R] B)
    (f : HopfAlgebra.points (R := R) (H := coordinateHopfAlgebra R n)
      (CommAlgCat.of R A)) :
    (pointsMulEquiv (R := R) (A := B) n)
        (AlgHom.mapValue (H := coordinateHopfAlgebra R n) phi f) =
      Matrix.SpecialLinearGroup.map phi.toRingHom
        ((pointsMulEquiv (R := R) (A := A) n) f) := by
  apply Matrix.SpecialLinearGroup.toGL_injective
  rw [← pointsMulEquiv_toGL, ← CommHopfAlgCat.mapValue_quotientPointsHom]
  rw [GeneralLinear.pointsMulEquiv_mapValue, pointsMulEquiv_toGL]
  apply Matrix.GeneralLinearGroup.ext
  intro i j
  rfl

end Points

/-! ### Naturality as an isomorphism of group-valued functors -/

section Functor

/-- The group-valued functor sending an `R`-algebra to its special linear group and an algebra
morphism to entrywise matrix mapping. Values are universe-lifted to match the Hopf-points
functor. -/
noncomputable def specialLinearFunctor :
    CommAlgCat.{w} R ⥤ GrpCat.{max u w} :=
  ({
    obj A := GrpCat.of (Matrix.SpecialLinearGroup (Fin n) (A : Type w))
    map phi := GrpCat.ofHom (Matrix.SpecialLinearGroup.map phi.hom.toRingHom)
    map_id _ := by
      ext g i j
      rfl
    map_comp _ _ := by
      ext g i j
      rfl
  } : CommAlgCat.{w} R ⥤ GrpCat.{w}) ⋙ GrpCat.uliftFunctor.{u, w}

/-- The object part of `specialLinearFunctor` is the universe lift of the ordinary special linear
group. -/
theorem specialLinearFunctor_obj (A : CommAlgCat.{w} R) :
    (specialLinearFunctor (R := R) n).obj A =
      GrpCat.of (ULift.{u, w} (Matrix.SpecialLinearGroup (Fin n) A)) :=
  (rfl)

/-- The morphism part of `specialLinearFunctor` applies the value-algebra morphism entrywise. -/
theorem specialLinearFunctor_map {A B : CommAlgCat.{w} R} (phi : A ⟶ B) :
    (specialLinearFunctor (R := R) n).map phi =
      eqToHom (specialLinearFunctor_obj (R := R) n A) ≫
        GrpCat.ofHom
          (MulEquiv.ulift.symm.toMonoidHom.comp
            ((Matrix.SpecialLinearGroup.map phi.hom.toRingHom).comp
              MulEquiv.ulift.toMonoidHom)) ≫
        eqToHom (specialLinearFunctor_obj (R := R) n B).symm :=
  (rfl)

/-- Entrywise computation of the value-algebra map on the special linear functor. -/
@[simp]
theorem specialLinearFunctor_map_apply_apply {A B : CommAlgCat.{w} R} (phi : A ⟶ B)
    (g : ULift.{u, w} (Matrix.SpecialLinearGroup (Fin n) A)) (i j : Fin n) :
    (eqToHom (specialLinearFunctor_obj (R := R) n B)
      ((specialLinearFunctor (R := R) n).map phi
        (eqToHom (specialLinearFunctor_obj (R := R) n A).symm g))).down i j =
      phi.hom (g.down.val i j) :=
  (rfl)

/-- The functor of points of the special-linear coordinate Hopf algebra is naturally isomorphic
to the ordinary special linear group functor. -/
noncomputable def pointsNatIso :
    HopfAlgebra.pointsFunctor (R := R) (H := coordinateHopfAlgebra R n) ≅
      specialLinearFunctor (R := R) n :=
  NatIso.ofComponents
    (fun A ↦ ((pointsMulEquiv (R := R) (A := A) n).trans
      MulEquiv.ulift.symm).toGrpIso)
    (by
      intro A B phi
      ext f
      apply ULift.ext
      -- The natural isomorphism is still being constructed, so no component rewrite lemma is
      -- available here. The functor maps and `MulEquiv.toGrpIso` reduce definitionally; after
      -- removing the universe lift, the square is exactly the named pointwise naturality result.
      exact pointsMulEquiv_mapValue (R := R) (A := A) (B := B) n phi.hom f)

/-- After transport along `specialLinearFunctor_obj`, the forward component of `pointsNatIso` is
the pointwise special-linear equivalence. -/
@[simp]
theorem pointsNatIso_hom_app_apply (A : CommAlgCat.{w} R)
    (f : HopfAlgebra.points (R := R) (H := coordinateHopfAlgebra R n) A) :
    (eqToHom (specialLinearFunctor_obj (R := R) n A)
      ((pointsNatIso (R := R) n).hom.app A f)).down =
      (pointsMulEquiv (R := R) (A := A) n) f :=
  (rfl)

/-- After transport back along `specialLinearFunctor_obj`, the inverse component of
`pointsNatIso` is the inverse pointwise special-linear equivalence. -/
@[simp]
theorem pointsNatIso_inv_app_apply (A : CommAlgCat.{w} R)
    (g : ULift.{u, w} (Matrix.SpecialLinearGroup (Fin n) A)) :
    (pointsNatIso (R := R) n).inv.app A
        (eqToHom (specialLinearFunctor_obj (R := R) n A).symm g) =
      (pointsMulEquiv (R := R) (A := A) n).symm g.down :=
  (rfl)

end Functor

end SpecialLinear

end EpsilonEridani
