/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.AlgebraicGeometry.EllipticCurve.Affine.FunctionField.AdjoinTower
public import EpsilonEridani.AlgebraicGeometry.EllipticCurve.DivisionPolynomial.RatFuncDegree

/-!
# The subfield of `F(W)` generated by `Φₙ / ΨSqₙ`

`RatFuncDegree.lean` shows that adjoining `Φₙ / ΨSqₙ` to `F` inside `F(x)` leaves an extension of
dimension `n²`. This file carries that up the tower `F(Φₙ/ΨSqₙ) ⊆ F(x) ⊆ F(W)` and computes
`[F(W) : F(Φₙ/ΨSqₙ)] = 2n²`, then divides the outer degree two back out: an embedding of function
fields carrying the affine coordinate to `Φₙ / ΨSqₙ` has image of index exactly `n²`.

That last statement is the geometric half of `deg [n] = n²`. The degree of an isogeny is the
degree of the extension of function fields it induces, and multiplication by `n` pulls the affine
coordinate `x` back to `Φₙ / ΨSqₙ`. So an isogeny with that pullback has image of index `n²` in
`F(W)`, which is its degree: the result below is stated for an arbitrary embedding precisely so
that identifying the pullback is all that remains.

## Main definitions

* `WeierstrassCurve.ratFuncAdjoinΦDivΨSqRange`: the copy of `F(Φₙ/ΨSqₙ)` inside `F(W)`, with
  `algebraMap_Φ_div_ΨSq_mem_ratFuncAdjoinΦDivΨSqRange` for its generator and
  `ratFuncAdjoinΦDivΨSqRange_le_iff` for its universal property.

## Main results

* `WeierstrassCurve.relfinrank_ratFuncAdjoinΦDivΨSqRange`: `[F(x) : F(Φₙ/ΨSqₙ)] = n²`, read
  inside `F(W)`.
* `WeierstrassCurve.finrank_ratFuncAdjoinΦDivΨSqRange`: `[F(W) : F(Φₙ/ΨSqₙ)] = 2n²`.
* `WeierstrassCurve.finrank_fieldRange_of_apply_X_eq_Φ_div_ΨSq`: `[F(W) : f(F(W'))] = n²` for any
  embedding `f` of function fields sending the affine coordinate of `W'` to `Φₙ / ΨSqₙ`. The copy
  of `F(Φₙ/ΨSqₙ)` is then the image of `F(x')`, by `Affine.extendRight_adjoin_eq_map_ratFuncRange`.

Nonsingularity is assumed as `n ≠ 0 → W.Δ ≠ 0`, the form `finrank_adjoin_Φ_div_ΨSq` takes: at
`n = 0` every displayed degree is `0` by `Module.finrank`'s value on an infinite extension, and
that holds for a singular `W` too.

## References

* [J. Silverman, *The Arithmetic of Elliptic Curves*][silverman2009], III.6.4(a).
-/

public section

open Polynomial IntermediateField

open scoped RatFunc

namespace WeierstrassCurve

variable {F : Type*} [Field F] (W : WeierstrassCurve F)

/-- The image of the field generated by `Φₙ / ΨSqₙ` inside `F(W)`. -/
noncomputable def ratFuncAdjoinΦDivΨSqRange (n : ℤ) :
    IntermediateField F W.toAffine.FunctionField :=
  (adjoin F {algebraMap F[X] (RatFunc F) (W.Φ n)
    / algebraMap F[X] (RatFunc F) (W.ΨSq n)}).extendRight W.toAffine.FunctionField

/-- **The universal property**: the copy of `F(Φₙ/ΨSqₙ)` lies inside an intermediate field
exactly when that field contains `Φₙ / ΨSqₙ`. -/
@[simp]
theorem ratFuncAdjoinΦDivΨSqRange_le_iff {n : ℤ}
    {L : IntermediateField F W.toAffine.FunctionField} :
    ratFuncAdjoinΦDivΨSqRange W n ≤ L ↔
      algebraMap (RatFunc F) W.toAffine.FunctionField
        (algebraMap F[X] (RatFunc F) (W.Φ n) / algebraMap F[X] (RatFunc F) (W.ΨSq n)) ∈ L := by
  rw [ratFuncAdjoinΦDivΨSqRange, IntermediateField.extendRight_adjoin_simple_le_iff]

/-- The generator: `Φₙ / ΨSqₙ` lies in the copy of `F(Φₙ/ΨSqₙ)`. -/
theorem algebraMap_Φ_div_ΨSq_mem_ratFuncAdjoinΦDivΨSqRange (n : ℤ) :
    algebraMap (RatFunc F) W.toAffine.FunctionField
        (algebraMap F[X] (RatFunc F) (W.Φ n) / algebraMap F[X] (RatFunc F) (W.ΨSq n)) ∈
      ratFuncAdjoinΦDivΨSqRange W n :=
  (ratFuncAdjoinΦDivΨSqRange_le_iff W).mp le_rfl

/-- **`[F(x) : F(Φₙ/ΨSqₙ)] = n²`**, read inside `F(W)`. -/
@[simp]
theorem relfinrank_ratFuncAdjoinΦDivΨSqRange (n : ℤ) (hΔ : n ≠ 0 → W.Δ ≠ 0) :
    relfinrank (ratFuncAdjoinΦDivΨSqRange W n) W.toAffine.ratFuncRange = n.natAbs ^ 2 := by
  rw [ratFuncAdjoinΦDivΨSqRange, Affine.relfinrank_extendRight,
    W.finrank_adjoin_Φ_div_ΨSq n hΔ]

/-- **`[F(W) : F(Φₙ/ΨSqₙ)] = 2n²`**. At `n = 0` both sides are `0`. -/
@[simp]
theorem finrank_ratFuncAdjoinΦDivΨSqRange (n : ℤ) (hΔ : n ≠ 0 → W.Δ ≠ 0) :
    Module.finrank (ratFuncAdjoinΦDivΨSqRange W n) W.toAffine.FunctionField =
      2 * n.natAbs ^ 2 := by
  rw [ratFuncAdjoinΦDivΨSqRange, Affine.finrank_extendRight,
    W.finrank_adjoin_Φ_div_ΨSq n hΔ]

/-- **`[F(W) : f(F(W'))] = n²`** for an embedding `f : F(W') → F(W)` of function fields carrying
the affine coordinate of `W'` to `Φₙ / ΨSqₙ`.

This is the geometric half of `deg [n] = n²`. -/
theorem finrank_fieldRange_of_apply_X_eq_Φ_div_ΨSq {W' : Affine F} {n : ℤ} (hΔ : n ≠ 0 → W.Δ ≠ 0)
    (f : W'.FunctionField →ₐ[F] W.toAffine.FunctionField)
    (hf : f (algebraMap F[X] W'.FunctionField X) =
      algebraMap (RatFunc F) W.toAffine.FunctionField
        (algebraMap F[X] (RatFunc F) (W.Φ n) / algebraMap F[X] (RatFunc F) (W.ΨSq n))) :
    Module.finrank f.fieldRange W.toAffine.FunctionField = n.natAbs ^ 2 := by
  rw [Affine.finrank_fieldRange_of_apply_X_eq W.toAffine f hf,
    W.finrank_adjoin_Φ_div_ΨSq n hΔ]

end WeierstrassCurve

end
