/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.AlgebraicGeometry.EllipticCurve.Affine.FunctionField.AdjoinTower
public import EpsilonEridani.FieldTheory.RatFunc.PowerTower

/-!
# Power subfields of the function field of a Weierstrass curve

For any field `K`, exponent `n`, and Weierstrass curve `W`, this file packages the tower
`K(x^n) ⊆ K(x) ⊆ K(W)` and computes `[K(W) : K(x^n)] = 2n`.

It is the generator `X ^ n` case of `AdjoinTower.lean`, which proves the same tower for an
arbitrary rational function; the single input this file supplies is
`EpsilonEridani.RatFunc.finrank_adjoin_X_pow`, that `[K(x) : K⟮X ^ n⟯] = n`.

At `n = 0`, the displayed degree formulas use `Module.finrank`'s value `0` for an
infinite-dimensional extension: `K(x^0) = K`, so both sides of each formula read `0`.

## Main results

* `WeierstrassCurve.Affine.ratFuncAdjoinXPowRange`: the copy of `K(x^n)` inside `K(W)`, with
  `algebraMap_X_pow_mem_ratFuncAdjoinXPowRange` for its generator.
* `WeierstrassCurve.Affine.finrank_ratFuncAdjoinXPowRange`: `[K(W) : K(x^n)] = 2 * n`.
* `WeierstrassCurve.Affine.ratFuncAdjoinXPowRange_eq_map_ratFuncRange` and
  `WeierstrassCurve.Affine.finrank_fieldRange_of_apply_X_eq_pow`: for any embedding
  `f : K(W') → K(W)` of function fields sending the affine coordinate of `W'` to `x ^ n`, the copy
  of `K(x^n)` is the image of `K(x')`, and `[K(W) : f(K(W'))] = n`. This is the whole tower
  comparison behind a degree of an inseparable isogeny; the absolute and the relative Frobenius
  each supply their own `hf` and read off their degree.

No result needs `W` to be elliptic: the Weierstrass equation alone gives the power basis.

The finite-field Frobenius and relative Frobenius degree computations both use this tower.

## Provenance

The tower argument lives in `Affine/FunctionField/AdjoinTower.lean`, stated for an arbitrary
generator; this file holds the `X ^ n` specialisation. Its finite-field ancestor is the AINTLIB
`HasseWeil` project (`github.com/CBirkbeck/AINTLIB`, Apache-2.0, pinned at
`513e83879e2f8cbc626eb9e04d660e92be16ccba`),
`HasseWeil/FrobeniusIsogeny.lean`, where the exponent is the cardinality of a finite field and the
embedding is the `q`-power map. The rational-function input `EpsilonEridani.RatFunc.finrank_adjoin_X_pow`
is recorded in `EpsilonEridani/FieldTheory/RatFunc/PowerTower.lean`; the finite-field specialisation stays
in `Affine/FunctionField/FrobeniusTower.lean`.
-/

public section

open Polynomial WeierstrassCurve IntermediateField

open scoped RatFunc

namespace WeierstrassCurve.Affine

variable {K : Type*} [Field K] (W : WeierstrassCurve.Affine K)

/-- The image of `X ^ n` in `K(W)` is the same whether `X ^ n` is read in `K[X]` or in `K(x)`. -/
-- Named because the three tower lemmas below each need this one coercion step.
private theorem algebraMap_X_pow_eq_algebraMap_ratFuncX_pow (n : ℕ) :
    algebraMap K[X] W.FunctionField X ^ n
      = algebraMap (RatFunc K) W.FunctionField ((RatFunc.X : RatFunc K) ^ n) := by
  rw [map_pow, ← toAlgHom_ratFuncX, IsScalarTower.coe_toAlgHom']

/-- The image of the field generated by `X ^ n` inside `K(W)`. This is
`IntermediateField.extendRight` at the generator `X ^ n`; everything below is
`AdjoinTower.lean`'s tower read through `EpsilonEridani.RatFunc.finrank_adjoin_X_pow`, which
supplies `[K(x) : K⟮X ^ n⟯] = n`. -/
noncomputable def ratFuncAdjoinXPowRange (n : ℕ) : IntermediateField K W.FunctionField :=
  (adjoin K {(RatFunc.X : RatFunc K) ^ n}).extendRight W.FunctionField

/-- The generator: `x ^ n` lies in the copy of `K(x^n)`. -/
theorem algebraMap_X_pow_mem_ratFuncAdjoinXPowRange (n : ℕ) :
    algebraMap K[X] W.FunctionField X ^ n ∈ ratFuncAdjoinXPowRange W n := by
  rw [ratFuncAdjoinXPowRange, algebraMap_X_pow_eq_algebraMap_ratFuncX_pow]
  exact IntermediateField.extendRight_adjoin_simple_le_iff.mp le_rfl

/-- **The universal property**: the copy of `K(x^n)` lies inside an intermediate field exactly
when that field contains `x ^ n`. -/
@[simp]
theorem ratFuncAdjoinXPowRange_le_iff {n : ℕ} {L : IntermediateField K W.FunctionField} :
    ratFuncAdjoinXPowRange W n ≤ L ↔ algebraMap K[X] W.FunctionField X ^ n ∈ L := by
  rw [ratFuncAdjoinXPowRange, IntermediateField.extendRight_adjoin_simple_le_iff,
    algebraMap_X_pow_eq_algebraMap_ratFuncX_pow]

/-- **`[K(x) : K(x^n)] = n`**, read inside `K(W)`. At `n = 0`, this is the `finrank` value
`0` for the infinite-dimensional extension `K(x) / K`. -/
@[simp]
theorem relfinrank_ratFuncAdjoinXPowRange (n : ℕ) :
    relfinrank (ratFuncAdjoinXPowRange W n) (ratFuncRange W) = n := by
  rw [ratFuncAdjoinXPowRange, relfinrank_extendRight,
    EpsilonEridani.RatFunc.finrank_adjoin_X_pow]

/-- **`[K(W) : K(x^n)] = 2n`.** At `n = 0`, both sides are `0`: the extension over
`K(x^0) = K` is infinite-dimensional, and `Module.finrank` reports `0`. -/
@[simp]
theorem finrank_ratFuncAdjoinXPowRange (n : ℕ) :
    Module.finrank (ratFuncAdjoinXPowRange W n) W.FunctionField = 2 * n := by
  rw [ratFuncAdjoinXPowRange, finrank_extendRight,
    EpsilonEridani.RatFunc.finrank_adjoin_X_pow]

/-- **The copy of `K(x^n)` inside `K(W)` is the image of the rational function field of `W'`**,
for any embedding `f : K(W') → K(W)` of function fields carrying the affine coordinate of `W'` to
`x ^ n`. This is the field the degree tower below is anchored at, in its two descriptions. -/
theorem ratFuncAdjoinXPowRange_eq_map_ratFuncRange {W' : WeierstrassCurve.Affine K} {n : ℕ}
    (f : W'.FunctionField →ₐ[K] W.FunctionField)
    (hf : f (algebraMap K[X] W'.FunctionField X) = algebraMap K[X] W.FunctionField X ^ n) :
    ratFuncAdjoinXPowRange W n = (ratFuncRange W').map f := by
  refine extendRight_adjoin_eq_map_ratFuncRange W f ?_
  rw [hf, algebraMap_X_pow_eq_algebraMap_ratFuncX_pow]

/-- **`[K(W) : f(K(W'))] = n`** for an embedding `f : K(W') → K(W)` of function fields carrying the
affine coordinate of `W'` to `x ^ n`. Both `K(x)` and the image of `K(W')` lie between `K(x^n)` and
`K(W)`, of relative degrees `n` and `2` over it; since `[K(W) : K(x)] = 2` as well, the two towers
give `2 · [K(W) : f(K(W'))] = 2n`. -/
theorem finrank_fieldRange_of_apply_X_eq_pow {W' : WeierstrassCurve.Affine K} {n : ℕ}
    (f : W'.FunctionField →ₐ[K] W.FunctionField)
    (hf : f (algebraMap K[X] W'.FunctionField X) = algebraMap K[X] W.FunctionField X ^ n) :
    Module.finrank f.fieldRange W.FunctionField = n := by
  rw [finrank_fieldRange_of_apply_X_eq W f (g := (RatFunc.X : RatFunc K) ^ n)
      (by rw [hf, algebraMap_X_pow_eq_algebraMap_ratFuncX_pow]),
    EpsilonEridani.RatFunc.finrank_adjoin_X_pow]

end WeierstrassCurve.Affine

end
