/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.AlgebraicGeometry.EllipticCurve.Affine.FunctionField.Separable

/-!
# The generic x-coordinate is a separating element

For an elliptic curve `E` over a field `F`, the function field `F(E)` is separable over the
subfield `F⟮genericX E⟯` generated by the affine coordinate `x`.

No Weierstrass-specific argument is repeated here. `isSeparable_functionField` already gives the
extension separable over any fraction field of `F[X]` inside `F(E)`, and `RatFunc F` is one; since
`genericX E` is transcendental over `F` (`transcendental_genericX`),
`RatFunc.algEquivOfTranscendental` identifies `RatFunc F` with `F⟮genericX E⟯` compatibly with
their two maps into `F(E)`, and `Algebra.IsSeparable.of_equiv_equiv` carries the separability
across.

Together with `transcendental_genericX`, this separability exhibits `genericX E` as a separating
element of `F(E)/F`, which is what proves the Kähler differentials of `F(E)` to have basis `dx`,
and hence basis the invariant differential.

## Main results

* `WeierstrassCurve.Affine.isSeparable_adjoin_genericX`: `F(E)` is separable over `F⟮genericX E⟯`.
-/

public section

open Polynomial

open scoped IntermediateField RatFunc nonZeroDivisors

namespace WeierstrassCurve.Affine

variable {F : Type*} [Field F] (E : WeierstrassCurve.Affine F)

/-- **The function field is separable over `F⟮x⟯`**, so that `genericX` is a separating element
of `F(E)/F`. Together with `transcendental_genericX` this is what the general separating-element
API for function fields runs on: it supplies the separability hypothesis of
`EpsilonEridani.D_ne_zero_of_separating`, `EpsilonEridani.span_D_eq_top_of_separating` and
`EpsilonEridani.finrank_kaehlerDifferential_eq_one_of_separating` at `x = genericX E`. -/
instance isSeparable_adjoin_genericX [E.IsElliptic] :
    Algebra.IsSeparable F⟮genericX E⟯ E.FunctionField :=
  Algebra.IsSeparable.of_equiv_equiv
    (RatFunc.algEquivOfTranscendental (genericX E) (transcendental_genericX E)).toRingEquiv
    (RingEquiv.refl E.FunctionField)
    (IsLocalization.ringHom_ext (F[X])⁰ (RingHom.ext fun q => by
      simp [RatFunc.algEquivOfTranscendental_algebraMap, ← IsScalarTower.algebraMap_apply,
        algebraMap_eq_aeval_genericX, IntermediateField.algebraMap_apply]))

end WeierstrassCurve.Affine

end
