/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.RingTheory.DiscreteValuationRing.Basic
public import Mathlib.RingTheory.PowerBasis
public import EpsilonEridani.FieldTheory.IntermediateField.Adjoin.EqTop
public import EpsilonEridani.RingTheory.LocalRing.Monogenic
import Mathlib.FieldTheory.Minpoly.IsIntegrallyClosed
-- for `UniqueFactorizationMonoid.instIsIntegrallyClosed`, which `PowerBasis.ofAdjoinEqTop'` needs
import Mathlib.RingTheory.Polynomial.RationalRoot

/-!
# Monogenicity of a finite extension of discrete valuation rings

Let `S` be a discrete valuation ring, finite over a discrete valuation subring `R`, and assume
the residue extension `𝓀(S)/𝓀(R)` is separable.  This file proves that `S = R[β]` for a single
`β : S`.  Both the ramified and the unramified case are covered; Mathlib's
`IsLocalRing.exists_adjoin_eq_top` covers only the unramified (finite étale) case, where the
generator may be taken to be any lift of a primitive element of the residue extension.

The proof is Serre's: pick a lift `a` of a primitive element of the residue extension and a
polynomial `g : R[X]` lifting its minimal polynomial.  Then `g(a)` lies in the maximal ideal and
`g'(a)` is a unit, so one Newton step, replacing `a` by `a + π` for a uniformizer `π` when that
is needed, arranges that `g(β)` *generates* the maximal ideal.  The subring `R[β]` then meets
every residue class modulo `𝓂(S)` and contains a uniformizer, hence meets every residue class
modulo `𝓂(S) ^ n`; taking `n` large enough that `𝓂(S) ^ n ⊆ 𝓂(R) S`, Nakayama's lemma gives
`R[β] = S`.

Nothing in that argument needs the two rings to be discrete valuation rings: it runs for a
module-finite extension of local rings in which the maximal ideal of `S` is principal, and it is
developed in that generality in `EpsilonEridani.RingTheory.LocalRing.Monogenic`. Being a discrete
valuation ring enters here only through `IsDiscreteValuationRing.exists_irreducible`, which
supplies the uniformizer generating `𝓂(S)`.

## Main results

* `EpsilonEridani.IsDiscreteValuationRing.exists_adjoin_eq_top`: a finite extension of discrete
  valuation rings with separable residue extension is monogenic.
* `EpsilonEridani.IsDiscreteValuationRing.nonempty_powerBasis`: the integral basis a generator produces,
  via Mathlib's `PowerBasis.ofAdjoinEqTop'`.
* `EpsilonEridani.IsDiscreteValuationRing.exists_powerBasis_intermediateField_adjoin_eq_top`: that
  integral basis can be chosen with its generator a primitive element of the fraction field of
  `S` over an intermediate base field.

## References

* [J.-P. Serre, *Corps locaux*][serre1968], Chapter III, §6, Proposition 12.
-/

public section

open IsLocalRing

namespace EpsilonEridani

namespace IsDiscreteValuationRing

variable {R S : Type*} [CommRing R] [CommRing S] [IsDomain R] [IsDomain S]
  [IsDiscreteValuationRing R] [IsDiscreteValuationRing S] [Algebra R S] [Module.Finite R S]
  [FaithfulSMul R S]

/-- **Local monogenicity.**  A finite extension of discrete valuation rings whose residue
extension is separable is generated by a single element.  Completeness of `R` is not needed: it
enters the classical statement only to guarantee that the integral closure of `R` in a finite
field extension is again a discrete valuation ring, which is here a hypothesis on `S`. -/
theorem exists_adjoin_eq_top [Algebra.IsSeparable (ResidueField R) (ResidueField S)] :
    ∃ β : S, Algebra.adjoin R {β} = ⊤ :=
  let ⟨_, hπ⟩ := _root_.IsDiscreteValuationRing.exists_irreducible S
  EpsilonEridani.IsLocalRing.exists_adjoin_eq_top_of_span_eq_maximalIdeal hπ.maximalIdeal_eq.symm

/-- A finite extension of discrete valuation rings with separable residue extension admits a
power basis: the integral basis `1, β, …, β ^ (n - 1)` attached to a generator `β`. -/
theorem nonempty_powerBasis [Algebra.IsSeparable (ResidueField R) (ResidueField S)] :
    Nonempty (PowerBasis R S) :=
  let ⟨β, h⟩ := exists_adjoin_eq_top (R := R) (S := S)
  ⟨PowerBasis.ofAdjoinEqTop' (IsIntegral.of_finite R β) h⟩

/-- The integral power basis of `EpsilonEridani.IsDiscreteValuationRing.nonempty_powerBasis` can be chosen
so that its generator is at the same time a primitive element of the fraction field `L` of `S`
over any field `K` between `R` and `L`: a generator of `S` over `R` also generates `L` over `K`,
by `EpsilonEridani.IntermediateField.adjoin_eq_top_of_algebra_adjoin_eq_top`. -/
theorem exists_powerBasis_intermediateField_adjoin_eq_top
    [Algebra.IsSeparable (ResidueField R) (ResidueField S)] (K L : Type*) [Field K] [Field L]
    [Algebra R K] [Algebra R L] [Algebra S L] [Algebra K L] [IsScalarTower R S L]
    [IsScalarTower R K L] [IsFractionRing S L] :
    ∃ pb : PowerBasis R S, IntermediateField.adjoin K {algebraMap S L pb.gen} = ⊤ := by
  obtain ⟨β, h⟩ := exists_adjoin_eq_top (R := R) (S := S)
  refine ⟨PowerBasis.ofAdjoinEqTop' (IsIntegral.of_finite R β) h, ?_⟩
  rw [PowerBasis.ofAdjoinEqTop'_gen]
  exact EpsilonEridani.IntermediateField.adjoin_eq_top_of_algebra_adjoin_eq_top h

end IsDiscreteValuationRing

end EpsilonEridani
