/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.Lie.UniversalEnveloping
public import Mathlib.RingTheory.FiniteType

/-!
# Basic results on universal enveloping algebras

This file records general results about universal enveloping algebras that do not depend on
additional structures such as filtrations, bialgebras, or antipodes.

## Main definitions and results

* `EpsilonEridani.UniversalEnvelopingAlgebra.adjoin_range_ι`: a universal enveloping algebra is
  generated, as an algebra, by its canonical Lie generators.
* `EpsilonEridani.UniversalEnvelopingAlgebra.induction_ι`: the induction principle on the canonical Lie
  generators that the previous statement supplies.
* `EpsilonEridani.UniversalEnvelopingAlgebra.instFiniteType`: a universal enveloping algebra is an algebra
  of finite type over the base ring as soon as the Lie algebra is finite as a module.
* `EpsilonEridani.UniversalEnvelopingAlgebra.representation`: the algebra homomorphism `U(L) → End M`
  attached to a Lie module `M`, in particular the adjoint action of `U(L)` on `L` at `M = L`.
* `EpsilonEridani.UniversalEnvelopingAlgebra.representation_lie_of_mem_center`: a central element of
  `U(L)` acts on a Lie module by a map commuting with the Lie action.
* `EpsilonEridani.UniversalEnvelopingAlgebra.mem_center_iff_forall_lie_ι`: centrality in `U(L)` is
  detected on the canonical Lie generators alone.
* `EpsilonEridani.UniversalEnvelopingAlgebra.ad_ι_pow_apply_ι`: iterating the commutator with a Lie
  generator reproduces, on the Lie generators, the iterated adjoint action of `L`.
* `EpsilonEridani.UniversalEnvelopingAlgebra.lie_map_ι`: an algebra representation maps the bracket of
  canonical Lie generators to the bracket of their images.
* `EpsilonEridani.UniversalEnvelopingAlgebra.lie_map_ι_eq_smul`: a Lie-bracket eigenvector remains one
  under an algebra representation.
* `EpsilonEridani.UniversalEnvelopingAlgebra.mul_sub_mul_eq_map_ι_lie`: the image of a Lie bracket
  under an algebra homomorphism is the ring commutator of the images.
* `EpsilonEridani.UniversalEnvelopingAlgebra.commute_of_lie_eq_zero`: images of Lie-commuting elements
  commute.
* `EpsilonEridani.UniversalEnvelopingAlgebra.zsmul_mul_zsmul_eq_add_nsmul_of_zsmul_lie_eq`: a scaled
  Lie-bracket relation gives the corresponding scaled ring-commutator relation.
* `EpsilonEridani.UniversalEnvelopingAlgebra.mul_eq_mul_add_zsmul_of_lie_eq`: an integral Lie-bracket
  structure constant gives the corresponding ring-commutator relation.
-/

public section

universe u v w

namespace EpsilonEridani.UniversalEnvelopingAlgebra

variable (R : Type u) (L : Type v)
variable [CommRing R] [LieRing L] [LieAlgebra R L]

local notation "U" => _root_.UniversalEnvelopingAlgebra R L

-- Mathlib does not register the Lie ring of an associative ring as a global instance; the
-- commutator of two elements of an enveloping algebra is written with it below.
attribute [local instance 100] LieRing.ofAssociativeRing

/-- **The enveloping algebra is generated by the canonical Lie generators.** This is the `U(L)`
analogue of `TensorAlgebra.adjoin_range_ι`, obtained by pushing that statement along the surjective
quotient map `UniversalEnvelopingAlgebra.mkAlgHom R L`. -/
theorem adjoin_range_ι :
    _root_.Algebra.adjoin R (Set.range ⇑(_root_.UniversalEnvelopingAlgebra.ι R)) =
      (⊤ : Subalgebra R U) := by
  have hcomp : (⇑(_root_.UniversalEnvelopingAlgebra.ι R) : L → U) =
      ⇑(_root_.UniversalEnvelopingAlgebra.mkAlgHom R L) ∘ ⇑(TensorAlgebra.ι R) :=
    funext fun x => _root_.UniversalEnvelopingAlgebra.ι_apply R x
  rw [hcomp, Set.range_comp, ← AlgHom.map_adjoin, TensorAlgebra.adjoin_range_ι,
    _root_.Algebra.map_top]
  -- `mkAlgHom R L` is by definition the quotient map `RingCon.mkₐ R (ringCon R L)`.
  exact (AlgHom.range_eq_top _).2 (RingCon.mkₐ_surjective _)

/-- **Induction on the canonical Lie generators.** A property of elements of `U(L)` that holds for
the canonical Lie generators and the scalars, and is stable under sums and products, holds
everywhere, since those generate `U(L)` as an `R`-algebra. -/
@[elab_as_elim]
theorem induction_ι {p : U → Prop}
    (ι : ∀ x : L, p (_root_.UniversalEnvelopingAlgebra.ι R x))
    (algebraMap : ∀ r : R, p (_root_.Algebra.algebraMap R U r))
    (add : ∀ a b, p a → p b → p (a + b)) (mul : ∀ a b, p a → p b → p (a * b)) (u : U) : p u := by
  have hu : u ∈ _root_.Algebra.adjoin R (Set.range ⇑(_root_.UniversalEnvelopingAlgebra.ι R)) := by
    rw [adjoin_range_ι R L]; exact _root_.Algebra.mem_top
  induction hu using _root_.Algebra.adjoin_induction with
  | mem u hu => obtain ⟨x, rfl⟩ := hu; exact ι x
  | algebraMap r => exact algebraMap r
  | add a b _ _ ha hb => exact add a b ha hb
  | mul a b _ _ ha hb => exact mul a b ha hb

variable {R L} in
/-- **The enveloping algebra of a Lie algebra which is finite as a module is an `R`-algebra of
finite type**: a finite spanning set of `L` generates `U(L)` as an algebra, the canonical Lie
generators of `U(L)` generating it
(`EpsilonEridani.UniversalEnvelopingAlgebra.adjoin_range_ι`). -/
instance instFiniteType [Module.Finite R L] : Algebra.FiniteType R U := by
  classical
  obtain ⟨S, hS⟩ := Module.Finite.fg_top (R := R) (M := L)
  -- the span of the image of a spanning set of `L` is the whole of the image of `L`
  have hrange : ((Submodule.span R
      (⇑((_root_.UniversalEnvelopingAlgebra.ι R : L →ₗ⁅R⁆ U) : L →ₗ[R] U) ''
        (S : Set L)) : Submodule R U) : Set U) =
      Set.range ⇑(_root_.UniversalEnvelopingAlgebra.ι R (L := L)) := by
    rw [← Submodule.map_span, hS, ← LinearMap.range_eq_map, LinearMap.coe_range,
      LieHom.coe_toLinearMap]
  exact ⟨S.image ⇑((_root_.UniversalEnvelopingAlgebra.ι R : L →ₗ⁅R⁆ U) : L →ₗ[R] U), by
    rw [Finset.coe_image, ← _root_.Algebra.adjoin_span, hrange, adjoin_range_ι R L]⟩

variable (M : Type w) [AddCommGroup M] [Module R M] [LieRingModule L M] [LieModule R L M]

/-- **The representation of a universal enveloping algebra on a Lie module**: the algebra
homomorphism obtained from `LieModule.toEnd` by the universal property of `U(L)`. At `M = L` this
is the adjoint action, since `LieAlgebra.ad R L` is `LieModule.toEnd R L L`. -/
noncomputable def representation : U →ₐ[R] Module.End R M :=
  _root_.UniversalEnvelopingAlgebra.lift R (LieModule.toEnd R L M)

-- Neither this lemma nor its pointwise form below is a `simp` lemma: `simp` unfolds `ι` through
-- Mathlib's `UniversalEnvelopingAlgebra.ι_apply`, so a left-hand side mentioning `ι` is not in
-- simp-normal form. This is why Mathlib's own `lift_ι_apply` is not a `simp` lemma either;
-- `representation_ι'` is the corresponding simp-normal form.
/-- The representation acts on a canonical Lie generator by the Lie action. -/
theorem representation_ι (x : L) :
    representation R L M (_root_.UniversalEnvelopingAlgebra.ι R x) = LieModule.toEnd R L M x :=
  _root_.UniversalEnvelopingAlgebra.lift_ι_apply R _ x

/-- The representation on the Lie algebra itself acts on a canonical generator by the adjoint
action. -/
theorem representation_ι_ad (x : L) :
    representation R L L (_root_.UniversalEnvelopingAlgebra.ι R x) = LieAlgebra.ad R L x :=
  representation_ι R L L x

/-- The `simp`-normal form of `EpsilonEridani.UniversalEnvelopingAlgebra.representation_ι`, stated for
the canonical generators as `simp` writes them. -/
@[simp]
theorem representation_ι' (x : L) :
    representation R L M
        (_root_.UniversalEnvelopingAlgebra.mkAlgHom R L (TensorAlgebra.ι R x)) =
      LieModule.toEnd R L M x :=
  _root_.UniversalEnvelopingAlgebra.lift_ι_apply' R _ x

/-- The pointwise form of `EpsilonEridani.UniversalEnvelopingAlgebra.representation_ι`: a Lie generator
acts by the Lie bracket. -/
theorem representation_ι_apply (x : L) (m : M) :
    representation R L M (_root_.UniversalEnvelopingAlgebra.ι R x) m = ⁅x, m⁆ := by
  rw [representation_ι, LieModule.toEnd_apply_apply]

/-- **A central element of `U(L)` acts on a Lie module by a map commuting with the Lie action.**
Equivalently, `EpsilonEridani.UniversalEnvelopingAlgebra.representation R L M u` is `L`-equivariant, that
is, a homomorphism of Lie modules. Centrality is used only against the canonical Lie generators,
which is what the Lie action is read off. -/
theorem representation_lie_of_mem_center {u : U} (hu : u ∈ Subalgebra.center R U) (x : L) (m : M) :
    representation R L M u ⁅x, m⁆ = ⁅x, representation R L M u m⁆ := by
  have h := congrArg (representation R L M)
    (Subalgebra.mem_center_iff.mp hu (_root_.UniversalEnvelopingAlgebra.ι R x))
  rw [map_mul, map_mul, representation_ι] at h
  have h₁ := congrArg (fun g : Module.End R M ↦ g m) h
  simpa only [Module.End.mul_apply, LieModule.toEnd_apply_apply] using h₁.symm

variable {R L}
variable {B : Type w} [Ring B] [Algebra R B]

/-- An algebra representation of the universal enveloping algebra maps the Lie bracket to the
commutator in its target algebra. -/
theorem lie_map_ι (ρ : _root_.UniversalEnvelopingAlgebra R L →ₐ[R] B) (x y : L) :
    ⁅ρ (_root_.UniversalEnvelopingAlgebra.ι R x), ρ (_root_.UniversalEnvelopingAlgebra.ι R y)⁆ =
      ρ (_root_.UniversalEnvelopingAlgebra.ι R ⁅x, y⁆) := by
  have hlie := LieHom.map_lie (_root_.UniversalEnvelopingAlgebra.ι R) x y
  rw [LieRing.of_associative_ring_bracket] at hlie
  rw [LieRing.of_associative_ring_bracket, hlie, map_sub, map_mul, map_mul]

/-- A Lie-bracket eigenvector remains one under an algebra representation of the universal
enveloping algebra. -/
theorem lie_map_ι_eq_smul (ρ : _root_.UniversalEnvelopingAlgebra R L →ₐ[R] B) {x y : L} {a : R}
    (hxy : ⁅x, y⁆ = a • y) :
    ⁅ρ (_root_.UniversalEnvelopingAlgebra.ι R x), ρ (_root_.UniversalEnvelopingAlgebra.ι R y)⁆ =
      a • ρ (_root_.UniversalEnvelopingAlgebra.ι R y) := by
  rw [lie_map_ι ρ, hxy, map_smul, map_smul]

/-- The image of a Lie bracket under an algebra homomorphism from a universal enveloping algebra
is the ring commutator of the images. -/
theorem mul_sub_mul_eq_map_ι_lie
    (ρ : _root_.UniversalEnvelopingAlgebra R L →ₐ[R] B) (a b : L) :
    ρ (_root_.UniversalEnvelopingAlgebra.ι R a) *
          ρ (_root_.UniversalEnvelopingAlgebra.ι R b) -
        ρ (_root_.UniversalEnvelopingAlgebra.ι R b) *
          ρ (_root_.UniversalEnvelopingAlgebra.ι R a) =
      ρ (_root_.UniversalEnvelopingAlgebra.ι R ⁅a, b⁆) := by
  rw [LieHom.map_lie (_root_.UniversalEnvelopingAlgebra.ι R) a b,
    LieRing.of_associative_ring_bracket, map_sub, map_mul, map_mul]

/-- Images of Lie-commuting elements commute under every algebra homomorphism from the universal
enveloping algebra. -/
theorem commute_of_lie_eq_zero
    (ρ : _root_.UniversalEnvelopingAlgebra R L →ₐ[R] B) {a b : L} (hab : ⁅a, b⁆ = 0) :
    Commute (ρ (_root_.UniversalEnvelopingAlgebra.ι R a))
      (ρ (_root_.UniversalEnvelopingAlgebra.ι R b)) := by
  have h := mul_sub_mul_eq_map_ι_lie ρ a b
  rw [hab, map_zero, map_zero] at h
  exact sub_eq_zero.mp h

/-- A scaled Lie-bracket relation becomes the corresponding scaled ring-commutator relation under
every algebra homomorphism from the universal enveloping algebra. -/
theorem zsmul_mul_zsmul_eq_add_nsmul_of_zsmul_lie_eq
    (ρ : _root_.UniversalEnvelopingAlgebra R L →ₐ[R] B) {a b b' : L} {p q r : ℤ} {n : ℕ}
    (hab : (p * q) • ⁅a, b⁆ = ((n : ℤ) * r) • b') :
    (p • ρ (_root_.UniversalEnvelopingAlgebra.ι R a)) *
        (q • ρ (_root_.UniversalEnvelopingAlgebra.ι R b)) =
      (q • ρ (_root_.UniversalEnvelopingAlgebra.ι R b)) *
          (p • ρ (_root_.UniversalEnvelopingAlgebra.ι R a)) +
        n • (r • ρ (_root_.UniversalEnvelopingAlgebra.ι R b')) := by
  have hbracket := congrArg ((p * q) • ·) (mul_sub_mul_eq_map_ι_lie ρ a b)
  rw [← map_zsmul, ← map_zsmul, hab, map_zsmul, map_zsmul] at hbracket
  rw [← sub_eq_iff_eq_add']
  have hcoeff : n • (r • ρ (_root_.UniversalEnvelopingAlgebra.ι R b')) =
      ((n : ℤ) * r) • ρ (_root_.UniversalEnvelopingAlgebra.ι R b') := by
    rw [← natCast_zsmul, ← mul_zsmul]
  rw [hcoeff]
  simpa only [smul_sub, mul_smul_comm, smul_mul_assoc, mul_zsmul, smul_comm p q] using
    hbracket

/-- A bracket relation with an integral structure constant becomes the corresponding commutator
relation under every algebra homomorphism from the universal enveloping algebra. -/
theorem mul_eq_mul_add_zsmul_of_lie_eq
    (ρ : _root_.UniversalEnvelopingAlgebra R L →ₐ[R] B) {a b b' : L} {c : ℤ}
    (hab : ⁅a, b⁆ = c • b') :
    ρ (_root_.UniversalEnvelopingAlgebra.ι R a) *
        ρ (_root_.UniversalEnvelopingAlgebra.ι R b) =
      ρ (_root_.UniversalEnvelopingAlgebra.ι R b) *
          ρ (_root_.UniversalEnvelopingAlgebra.ι R a) +
        c • ρ (_root_.UniversalEnvelopingAlgebra.ι R b') := by
  simpa using
    (zsmul_mul_zsmul_eq_add_nsmul_of_zsmul_lie_eq ρ
      (p := 1) (q := 1) (r := c) (n := 1) (by simpa using hab))


section Center

variable (R L)

/-- **Centrality in `U(L)` is detected on the canonical Lie generators.**  An element of `U(L)`
is central exactly when it brackets to zero against every canonical Lie generator, because those
generators generate `U(L)` as an algebra and the elements commuting with a fixed element form a
subalgebra. -/
theorem mem_center_iff_forall_lie_ι {u : U} :
    u ∈ Subalgebra.center R U ↔
      ∀ x : L, ⁅u, _root_.UniversalEnvelopingAlgebra.ι R x⁆ = 0 := by
  refine ⟨fun hu x => ?_, fun h => ?_⟩
  · rw [LieRing.of_associative_ring_bracket,
      ← Subalgebra.mem_center_iff.mp hu (_root_.UniversalEnvelopingAlgebra.ι R x), sub_self]
  · -- The centralizer of `u` is a subalgebra containing every Lie generator, hence everything.
    have hgen : (⊤ : Subalgebra R U) ≤ Subalgebra.centralizer R {u} := by
      rw [← adjoin_range_ι R L]
      refine Algebra.adjoin_le ?_
      rintro _ ⟨x, rfl⟩
      refine (Subalgebra.mem_centralizer_iff R).mpr fun g hg => ?_
      rw [Set.mem_singleton_iff] at hg
      subst hg
      have hx := h x
      rw [LieRing.of_associative_ring_bracket] at hx
      exact sub_eq_zero.mp hx
    exact Subalgebra.mem_center_iff.mpr fun b =>
      ((Subalgebra.mem_centralizer_iff R).mp (hgen (Set.mem_univ b)) u rfl).symm

variable {R L}

/-- **The iterated commutator with a Lie generator, read on the Lie generators.**  Bracketing
`n` times with `ι x` inside `U(L)` sends `ι y` to the image of the `n`-fold adjoint action of `x`
on `y`; that is, `ι` intertwines `LieAlgebra.ad R L x` with the inner derivation of `U(L)`
attached to `ι x`. -/
theorem ad_ι_pow_apply_ι (x y : L) (n : ℕ) :
    (LieAlgebra.ad R U (_root_.UniversalEnvelopingAlgebra.ι R x) ^ n)
        (_root_.UniversalEnvelopingAlgebra.ι R y) =
      _root_.UniversalEnvelopingAlgebra.ι R ((LieAlgebra.ad R L x ^ n) y) := by
  induction n generalizing y with
  | zero => simp
  | succ n ih =>
    rw [pow_succ, Module.End.mul_apply, LieAlgebra.ad_apply,
      ← LieHom.map_lie (_root_.UniversalEnvelopingAlgebra.ι R), ih, pow_succ,
      Module.End.mul_apply, LieAlgebra.ad_apply]

end Center

end EpsilonEridani.UniversalEnvelopingAlgebra
