/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.Lie.Nilpotent
public import EpsilonEridani.Algebra.Lie.UniversalEnveloping.Module

import Mathlib.Algebra.Lie.Engel
import Mathlib.RingTheory.Ideal.Quotient.Operations
import EpsilonEridani.Algebra.Lie.Nilradical
import EpsilonEridani.RingTheory.Ideal.Operations

/-!
# Lie ideals in universal enveloping algebras

A Lie ideal `I` of `L` generates a two-sided ideal of the universal enveloping algebra `U(L)`.
Although `Ideal.span (ι '' I)` is initially only a left ideal, the commutator relation
`ι x * ι y = ι [x, y] + ι y * ι x` and the Lie-ideal property show that it is also
closed under multiplication on the right.

An intermediate result identifies the image of the ideal generated by `I` under an arbitrary ring
homomorphism. The final results identify powers of the enveloping ideal with the lower-central
action filtration and give a uniform power contained in a two-sided ideal `J` when the canonical
images of the elements of `I` are nilpotent modulo `J` and `U(L) / J` is Noetherian over the base
ring. For the Ado--Iwasawa construction, `I` is the nilradical of a solvable Lie algebra and `J` is
the two-sided kernel of a finite-dimensional representation, whose quotient satisfies this
Noetherian hypothesis.

These declarations live in the root `LieIdeal` namespace, extending Mathlib's API and supporting
receiver notation on the Lie ideal.

## Main definitions and results

* `LieIdeal.envelopingIdeal`: the ideal of `U(L)` generated by a Lie ideal `I`.
* `LieIdeal.envelopingIdeal_le_iff`: its universal property as a generated ideal.
* `LieIdeal.envelopingIdeal_mono`, `LieIdeal.envelopingIdeal_bot`,
  `LieIdeal.envelopingIdeal_sup`, `LieIdeal.envelopingIdeal_top`: monotonicity and the values on
  `⊥`, `⊔`, and `⊤`.
* `LieIdeal.isTwoSided_envelopingIdeal`: the generated ideal is two-sided.
* `LieIdeal.map_envelopingIdeal`: its image under a ring homomorphism is generated by the images
  of the elements of `I`.
* `LieIdeal.lieSubmoduleOrderIso_lcs_eq_envelopingIdeal_pow_smul_top`: powers of the
  enveloping ideal act through the lower-central filtration for the restricted Lie action.
* `LieIdeal.exists_envelopingIdeal_pow_le_of_forall_isNilpotent`: nilpotence of the Lie
  generators modulo an ideal with Noetherian quotient gives a uniform power of the generated ideal
  contained in it.
* `LieIdeal.exists_sup_envelopingIdeal_pow_le_of_forall_isNilpotent`: the ideal generated by a
  Lie ideal is nilpotent modulo a two-sided ideal with Noetherian quotient when its Lie generators
  are nilpotent there.

## References

The ideal construction and its use in the proof of Ado's theorem follow W. Fulton and J. Harris,
*Representation Theory: A First Course*, Appendix E.

The uniform nilpotence argument uses Mathlib's Engel-theorem characterization
`LieModule.isNilpotent_iff_forall'` from `Mathlib.Algebra.Lie.Engel`.
-/

public section

namespace EpsilonEridani

universe u v

variable {R : Type u} {L : Type v} [CommRing R] [LieRing L] [LieAlgebra R L]

local notation "U" => UniversalEnvelopingAlgebra R L

-- Mathlib does not register the Lie ring of an associative ring as a global instance; the
-- commutator relation in the enveloping algebra is used below.
attribute [local instance 100] LieRing.ofAssociativeRing

/-- **The ideal generated by a Lie ideal in the universal enveloping algebra.** The ideal of
`U(L)` generated by the canonical images of the elements of `I`; it is two-sided by
`LieIdeal.isTwoSided_envelopingIdeal`. -/
def _root_.LieIdeal.envelopingIdeal (I : LieIdeal R L) : Ideal U :=
  Ideal.span (UniversalEnvelopingAlgebra.ι R '' (I : Set L))

/-- **The universal property of the enveloping ideal.** It is contained in an ideal `J` exactly
when `J` contains the canonical image of every element of the Lie ideal. -/
@[simp]
theorem _root_.LieIdeal.envelopingIdeal_le_iff {I : LieIdeal R L} {J : Ideal U} :
    I.envelopingIdeal ≤ J ↔
      ∀ x : L, x ∈ I → UniversalEnvelopingAlgebra.ι R x ∈ J := by
  rw [LieIdeal.envelopingIdeal, Ideal.span_le, Set.image_subset_iff]
  rfl

/-- A member of a Lie ideal maps into the ideal it generates in the enveloping algebra. -/
theorem _root_.LieIdeal.ι_mem_envelopingIdeal (I : LieIdeal R L) {x : L} (hx : x ∈ I) :
    UniversalEnvelopingAlgebra.ι R x ∈ I.envelopingIdeal :=
  Ideal.subset_span ⟨x, hx, rfl⟩

/-- The enveloping ideal construction is monotone. -/
@[gcongr]
theorem _root_.LieIdeal.envelopingIdeal_mono {I J : LieIdeal R L} (h : I ≤ J) :
    I.envelopingIdeal ≤ J.envelopingIdeal :=
  LieIdeal.envelopingIdeal_le_iff.mpr fun _ hx => J.ι_mem_envelopingIdeal (h hx)

/-- The zero Lie ideal generates the zero ideal of the universal enveloping algebra. -/
@[simp]
theorem _root_.LieIdeal.envelopingIdeal_bot :
    (⊥ : LieIdeal R L).envelopingIdeal = ⊥ := by
  rw [LieIdeal.envelopingIdeal]
  simp

/-- The enveloping ideal construction preserves binary suprema. -/
@[simp]
theorem _root_.LieIdeal.envelopingIdeal_sup (I J : LieIdeal R L) :
    (I ⊔ J).envelopingIdeal = I.envelopingIdeal ⊔ J.envelopingIdeal := by
  apply le_antisymm
  · rw [LieIdeal.envelopingIdeal_le_iff]
    intro x hx
    obtain ⟨y, hy, z, hz, rfl⟩ := Submodule.mem_sup.mp hx
    rw [map_add]
    exact add_mem
      (Ideal.mem_sup_left (I.ι_mem_envelopingIdeal hy))
      (Ideal.mem_sup_right (J.ι_mem_envelopingIdeal hz))
  · exact sup_le (LieIdeal.envelopingIdeal_mono le_sup_left)
      (LieIdeal.envelopingIdeal_mono le_sup_right)

/-- The top Lie ideal generates the ideal spanned by all canonical Lie generators. -/
@[simp]
theorem _root_.LieIdeal.envelopingIdeal_top :
    (⊤ : LieIdeal R L).envelopingIdeal =
      Ideal.span (Set.range (UniversalEnvelopingAlgebra.ι R)) := by
  rw [LieIdeal.envelopingIdeal, LieSubmodule.top_coe, Set.image_univ]

/-- **The ideal generated by a Lie ideal is two-sided.** `I.envelopingIdeal` is a two-sided ideal
of `U(L)`. -/
instance _root_.LieIdeal.isTwoSided_envelopingIdeal (I : LieIdeal R L) :
    I.envelopingIdeal.IsTwoSided := by
  constructor
  intro a b ha
  induction b using UniversalEnvelopingAlgebra.induction_ι R L generalizing a with
  | ι y =>
    induction ha using Submodule.span_induction with
    | mem z hz =>
      obtain ⟨x, hx, rfl⟩ := hz
      have hxy : ⁅x, y⁆ ∈ I := lie_mem_left R L I x y hx
      have hmap := UniversalEnvelopingAlgebra.mul_sub_mul_eq_map_ι_lie
        (AlgHom.id R U) x y
      simp only [AlgHom.id_apply] at hmap
      rw [sub_eq_iff_eq_add] at hmap
      rw [hmap]
      exact I.envelopingIdeal.add_mem (I.ι_mem_envelopingIdeal hxy)
        (I.envelopingIdeal.mul_mem_left (UniversalEnvelopingAlgebra.ι R y)
          (I.ι_mem_envelopingIdeal hx))
    | zero => rw [zero_mul]; exact I.envelopingIdeal.zero_mem
    | add x y _ _ hx hy => rw [add_mul]; exact I.envelopingIdeal.add_mem hx hy
    | smul c x _ hx =>
      rw [smul_eq_mul, mul_assoc]
      exact I.envelopingIdeal.mul_mem_left c hx
  | algebraMap r =>
    rw [← Algebra.commutes r a]
    exact I.envelopingIdeal.mul_mem_left _ ha
  | add b c hb hc =>
    rw [mul_add]
    exact I.envelopingIdeal.add_mem (hb ha) (hc ha)
  | mul b c hb hc =>
    rw [← mul_assoc]
    exact hc (hb ha)

/-- The image under a ring homomorphism of the enveloping ideal generated by `I` is the ideal
spanned by the images of the elements of `I`. This is `Ideal.map_span` with the generating set
rewritten to exhibit the composite map. -/
theorem _root_.LieIdeal.map_envelopingIdeal {A : Type*} [Semiring A]
    (I : LieIdeal R L) (f : U →+* A) :
    I.envelopingIdeal.map f =
      Ideal.span ((fun x : L => f (UniversalEnvelopingAlgebra.ι R x)) '' (I : Set L)) := by
  rw [LieIdeal.envelopingIdeal, Ideal.map_span, Set.image_image]

section ActionFiltration

variable {M : Type*} [AddCommGroup M] [Module R M]
  [Module (UniversalEnvelopingAlgebra R L) M]
  [IsScalarTower R (UniversalEnvelopingAlgebra R L) M]
  [LieRingModule L M] [LieModule R L M]

/-- The enveloping ideal generated by `I` acting on a Lie submodule `N` gives the Lie submodule
generated by the action of `I` on `N`.

This is the bridge between ideal powers in `U(L)` and the lower-central filtration of a Lie
module. The compatibility hypothesis says that the given `U(L)`-module structure extends the
given `L`-module structure. -/
theorem _root_.LieIdeal.lieSubmoduleOrderIso_lie_eq_envelopingIdeal_smul
    (I : LieIdeal R L) (N : LieSubmodule R L M)
    (hcompat : ∀ (x : L) (m : M), UniversalEnvelopingAlgebra.ι R x • m = ⁅x, m⁆) :
    UniversalEnvelopingAlgebra.lieSubmoduleOrderIso hcompat ⁅I, N⁆ =
      I.envelopingIdeal •
        UniversalEnvelopingAlgebra.lieSubmoduleOrderIso hcompat N := by
  apply le_antisymm
  · intro m hm
    rw [UniversalEnvelopingAlgebra.mem_lieSubmoduleOrderIso] at hm
    -- Membership in a Lie submodule is definitionally membership in its underlying submodule;
    -- there is no separate propositional conversion lemma in the `LieSubmodule` API.
    change m ∈ LieSubmodule.toSubmodule ⁅I, N⁆ at hm
    rw [LieSubmodule.lieIdeal_oper_eq_linear_span'] at hm
    induction hm using Submodule.span_induction with
    | mem m hm =>
      obtain ⟨x, hx, y, hy, rfl⟩ := hm
      rw [← hcompat]
      exact Submodule.smul_mem_smul (I.ι_mem_envelopingIdeal hx)
        ((UniversalEnvelopingAlgebra.mem_lieSubmoduleOrderIso hcompat).mpr hy)
    | zero => exact Submodule.zero_mem _
    | add x y _ _ hx hy => exact Submodule.add_mem _ hx hy
    | smul r x _ hx =>
      rw [← IsScalarTower.algebraMap_smul U r x]
      exact Submodule.smul_mem _ _ hx
  · refine Submodule.smul_le.mpr fun a ha m hm ↦ ?_
    induction ha using Submodule.span_induction with
    | mem a ha =>
      obtain ⟨x, hx, rfl⟩ := ha
      rw [hcompat]
      rw [UniversalEnvelopingAlgebra.mem_lieSubmoduleOrderIso]
      exact LieSubmodule.lie_mem_lie hx
        ((UniversalEnvelopingAlgebra.mem_lieSubmoduleOrderIso hcompat).mp hm)
    | zero => rw [zero_smul]; exact Submodule.zero_mem _
    | add x y _ _ hx hy =>
      rw [add_smul]
      exact Submodule.add_mem _ hx hy
    | smul u a _ ha =>
      rw [smul_eq_mul, mul_smul]
      exact Submodule.smul_mem _ u ha

/-- **Powers of an enveloping ideal are the lower-central action filtration.** Under the
enveloping-algebra dictionary, the `n`-fold action of a Lie ideal `I` on a module is exactly the
submodule generated by the action of `I.envelopingIdeal ^ n`.

Consequently, nilpotence of the restricted `I`-action is equivalent to the vanishing of some
power of the generated ideal on the module. -/
theorem _root_.LieIdeal.lieSubmoduleOrderIso_lcs_eq_envelopingIdeal_pow_smul_top
    (I : LieIdeal R L)
    (hcompat : ∀ (x : L) (m : M), UniversalEnvelopingAlgebra.ι R x • m = ⁅x, m⁆)
    (n : ℕ) :
    UniversalEnvelopingAlgebra.lieSubmoduleOrderIso hcompat (I.lcs M n) =
      I.envelopingIdeal ^ n • (⊤ : Submodule U M) := by
  induction n with
  | zero =>
    rw [LieIdeal.lcs_zero, OrderIso.map_top, Submodule.pow_zero, Ideal.one_eq_top,
      Submodule.top_smul]
  | succ n ih =>
    rw [LieIdeal.lcs_succ,
      I.lieSubmoduleOrderIso_lie_eq_envelopingIdeal_smul _ hcompat, ih,
      ← Submodule.smul_assoc, Ideal.smul_eq_mul,
      ← Ideal.IsTwoSided.pow_succ (I := I.envelopingIdeal) n]

/-- A Lie ideal acts nilpotently on a module exactly when a power of its enveloping ideal
annihilates the module. -/
theorem _root_.LieIdeal.isNilpotent_iff_exists_envelopingIdeal_pow_smul_top_eq_bot
    (I : LieIdeal R L)
    (hcompat : ∀ (x : L) (m : M), UniversalEnvelopingAlgebra.ι R x • m = ⁅x, m⁆) :
    LieModule.IsNilpotent (↥I) M ↔
      ∃ n : ℕ, I.envelopingIdeal ^ n • (⊤ : Submodule U M) = ⊥ := by
  rw [LieModule.isNilpotent_iff R]
  refine exists_congr fun n ↦ ?_
  rw [← LieIdeal.lcs_eq_bot_iff I M n]
  let e := UniversalEnvelopingAlgebra.lieSubmoduleOrderIso hcompat
  constructor
  · intro hn
    have hmap := congrArg e hn
    rw [e.map_bot,
      I.lieSubmoduleOrderIso_lcs_eq_envelopingIdeal_pow_smul_top hcompat n] at hmap
    exact hmap
  · intro hn
    apply e.injective
    rw [e.map_bot,
      I.lieSubmoduleOrderIso_lcs_eq_envelopingIdeal_pow_smul_top hcompat n, hn]

end ActionFiltration

section NoetherianQuotient

variable {K : Type u} {L' : Type v} [CommRing K] [LieRing L'] [LieAlgebra K L']

local notation "UK" => UniversalEnvelopingAlgebra K L'

/-- **A uniform power bound for an enveloping ideal modulo a two-sided ideal.**
If every canonical generator belonging to `I` is nilpotent modulo `J`, then a single power of
`I.envelopingIdeal` is contained in `J`, provided `U(L') / J` is Noetherian over the base ring.
In the Ado--Iwasawa construction, `I` is the nilradical. -/
theorem _root_.LieIdeal.exists_envelopingIdeal_pow_le_of_forall_isNilpotent
    (I : LieIdeal K L') (J : Ideal UK) [J.IsTwoSided] [IsNoetherian K (UK ⧸ J)]
    (hI : ∀ x : L', x ∈ I →
      IsNilpotent (Ideal.Quotient.mk J (UniversalEnvelopingAlgebra.ι K x))) :
    ∃ n : ℕ, I.envelopingIdeal ^ n ≤ J := by
  let : LieRingModule L' (UK ⧸ J) :=
    UniversalEnvelopingAlgebra.asLieRingModule K L' (UK ⧸ J)
  let : LieModule K L' (UK ⧸ J) :=
    UniversalEnvelopingAlgebra.asLieModule K L' (UK ⧸ J)
  have htoEnd (x : I) : LieModule.toEnd K (↥I) (UK ⧸ J) x =
      Algebra.lmul K (UK ⧸ J) (Ideal.Quotient.mk J
        (UniversalEnvelopingAlgebra.ι K (x : L'))) := by
    apply LinearMap.ext
    intro m
    rw [LieModule.toEnd_apply_apply, LieIdeal.coe_bracket_of_module,
      UniversalEnvelopingAlgebra.asLieRingModule_bracket, Algebra.coe_lmul_eq_mul]
    induction m using Quotient.inductionOn' with
    | _ m =>
      rw [LinearMap.mul_apply']
      exact
        (by
          calc
            (UniversalEnvelopingAlgebra.ι K (x : L')) • Ideal.Quotient.mk J m =
                Ideal.Quotient.mk J (UniversalEnvelopingAlgebra.ι K (x : L') * m) := by
              simpa only [smul_eq_mul, Ideal.Quotient.mk_eq_mk] using
                (Submodule.Quotient.mk_smul J
                  (UniversalEnvelopingAlgebra.ι K (x : L')) m).symm
            _ = Ideal.Quotient.mk J (UniversalEnvelopingAlgebra.ι K (x : L')) *
                Ideal.Quotient.mk J m := (Ideal.Quotient.mk J).map_mul _ _)
  have hnil : LieModule.IsNilpotent (↥I) (UK ⧸ J) :=
    (LieModule.isNilpotent_iff_forall' (R := K)).mpr fun x ↦ by
      rw [htoEnd]
      exact (hI x x.property).map (Algebra.lmul K (UK ⧸ J))
  obtain ⟨n, hn⟩ :=
    (I.isNilpotent_iff_exists_envelopingIdeal_pow_smul_top_eq_bot
      (fun x m ↦
        (UniversalEnvelopingAlgebra.asLieRingModule_bracket K L' (UK ⧸ J) x m).symm)).mp
      hnil
  refine ⟨n, fun a ha ↦ ?_⟩
  have ha' : a • (1 : UK ⧸ J) ∈
      I.envelopingIdeal ^ n • (⊤ : Submodule UK (UK ⧸ J)) :=
    Submodule.smul_mem_smul ha Submodule.mem_top
  rw [hn] at ha'
  have ha0 : a • (1 : UK ⧸ J) = 0 := by simpa using ha'
  rw [← Ideal.Quotient.eq_zero_iff_mem]
  calc
    Ideal.Quotient.mk J a = a • (1 : UK ⧸ J) := by
      simpa only [smul_eq_mul, mul_one, Ideal.Quotient.mk_eq_mk, map_one] using
        Submodule.Quotient.mk_smul J a (1 : UK)
    _ = 0 := ha0

/-- **Nilpotence of the ideal generated by nilpotent Lie generators modulo an ideal with Noetherian
quotient.** Let `J` be a two-sided ideal of `U(L')` whose quotient is Noetherian over the base ring.
If every canonical generator belonging to `I` is nilpotent modulo `J`, then the preimage
`J ⊔ I.envelopingIdeal` of the ideal they generate in the quotient is nilpotent modulo `J`.

For the Ado--Iwasawa construction, take `I` to be the nilradical. -/
theorem _root_.LieIdeal.exists_sup_envelopingIdeal_pow_le_of_forall_isNilpotent
    (I : LieIdeal K L') (J : Ideal UK) [J.IsTwoSided]
    [IsNoetherian K (UK ⧸ J)]
    (hI : ∀ x : L', x ∈ I →
      IsNilpotent (Ideal.Quotient.mk J (UniversalEnvelopingAlgebra.ι K x))) :
    ∃ n : ℕ, (J ⊔ I.envelopingIdeal) ^ n ≤ J := by
  obtain ⟨n, hn⟩ := I.exists_envelopingIdeal_pow_le_of_forall_isNilpotent J hI
  exact ⟨n, (Ideal.sup_pow_le_sup_pow_right J I.envelopingIdeal n).trans
    (sup_le le_rfl hn)⟩

end NoetherianQuotient

end EpsilonEridani
