/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.RingTheory.Huber.Basic

/-!
# Rings and ideals of definition of a Huber ring

Wedhorn's characterisation of the rings of definition, the enlargement constructions for pairs of
definition, and the two union descriptions they yield. On the **ring** side: Wedhorn's Lemma 6.2
and the parts of his Corollary 6.4 covered here — that `A°` is the union of the rings of definition,
that the subring generated by two rings of definition is again one, and that their intersection is
one too. Corollary 6.4(2) is not included. On the **ideal** side, a companion of the union
description: `A°°` is the union of the *ideals* of definition, and is therefore open.

Both sides live here because they share the enlargement machinery: the ring-side results rest on
`PairOfDefinition.enlarge`, and the ideal-side ones on `PairOfDefinition.enlargeIdeal`, which keeps
the ring and grows only the ideal. The ideal-side statement is also proved *from* the ring-side one,
reusing `isPowerBounded_iff_exists_mem_ringOfDefinition` below rather than rebuilding a pair.

The two ring-side parts rest on a single observation, isolated here as
`PairOfDefinition.enlarge`: **a bounded subring containing a ring of definition is itself a ring of
definition.** Openness is inherited
from the smaller ring, and the new ideal of definition is the `Ideal.map` of the old one, so
finite generation comes for free. Boundedness of the larger ring is the only real hypothesis, and
both applications get it from the lattice: `A₀[T]` is `A₀ ⊔ Subring.closure T`, bounded by
`isBounded_sup` against Wedhorn 5.30(2) (`isBounded_subringClosure`), which `adjoin` combines in
two lines at the point of use. The join case is `PairOfDefinition.enlargeSup`, which takes an
arbitrary bounded `B`; joining two rings of definition is the case where `B` is one of them.

Taking `T = {a}` in the first application proves that every power-bounded element belongs to some
ring of definition; the converse holds because every ring of definition is bounded.

Enlargement does not reach every ring of definition, and the last section of the file supplies
what does: **Wedhorn Lemma 6.2**, that the rings of definition are exactly the open bounded
subrings. Its content is the implication from openness and boundedness, since a ring of definition
is open by definition and bounded by `PairOfDefinition.isBounded_ringOfDefinition`. The proof
builds an ideal of definition for `B` out of a pair of definition `(A₀, I)` of `A`: choose `k ≥ 1`
with `Iᵏ ⊆ B` — possible because `B` is open — and let `J` be the ideal of `B` generated by the
degree-`k` monomials in a finite generating set of `I`. Then `I^(k * (n + 1)) ⊆ Jⁿ` makes every
power of `J` open, while boundedness of `B` puts `Jᵐ` inside `Iᵐ · B` and hence eventually inside
any neighbourhood of `0`.

That criterion is what the enlargement constructions cannot give. The intersection half of
Corollary 6.4 is a case in point: `A₀ ∩ A₁` is *smaller* than `A₀`, so an enlargement argument
would produce its ideal by `Ideal.comap` rather than `Ideal.map`, and a comap of a finitely
generated ideal need not be finitely generated. `enlarge` and its descendants are kept because
they name the ideal of definition of the larger ring explicitly — `Ideal.map` of the smaller
one — which Lemma 6.2, being an existence statement, does not.

## Main results

* `EpsilonEridani.Huber.PairOfDefinition.enlarge`: a bounded subring containing a ring of definition is
  a ring of definition.
* `EpsilonEridani.Huber.PairOfDefinition.adjoin`: adjoining finitely many power-bounded elements gives
  another pair of definition.
* `EpsilonEridani.Huber.PairOfDefinition.enlargeSup`: joining a ring of definition with any bounded
  subring gives a ring of definition, with `enlargeSup_ringOfDefinition`,
  `enlargeSup_idealOfDefinition`, `le_enlargeSup_left` and `le_enlargeSup_right` naming its
  components and inclusions.
* `EpsilonEridani.Huber.PairOfDefinition.sup`: the join of two rings of definition is a ring of
  definition.
* `EpsilonEridani.Huber.PairOfDefinition.enlargeIdeal`: adjoining a topologically nilpotent element to
  the *ideal* of definition again gives a pair of definition, with `enlargeIdeal_ringOfDefinition`
  and `enlargeIdeal_idealOfDefinition` naming its two components — the ring is unchanged and the
  ideal becomes `I ⊔ span {y}` — and `mem_enlargeIdeal_idealOfDefinition` recording that the
  adjoined element is in it, which is the form consumers use.
* `EpsilonEridani.Huber.isTopologicallyNilpotent_iff_exists_mem_idealOfDefinition`: the topologically
  nilpotent elements are exactly the union of the ideals of definition — the ideal-side companion
  of Corollary 6.4 below.
* `EpsilonEridani.Huber.isOpen_setOf_isTopologicallyNilpotent`: consequently the topologically nilpotent
  elements form an *open* set, each ideal of definition having open image in `A`.
* `EpsilonEridani.Huber.isPowerBounded_iff_exists_mem_ringOfDefinition`: the power-bounded subring is
  the union of the rings of definition.
* `EpsilonEridani.Huber.exists_pairOfDefinition_ringOfDefinition_eq`: **Wedhorn Lemma 6.2** — an open
  bounded subring of a Huber ring is a ring of definition. The three-way form is
  `EpsilonEridani.Huber.exists_pairOfDefinition_ringOfDefinition_eq_tfae`, which adds the intermediate
  condition "open with adic subspace topology" via `EpsilonEridani.Huber.isBounded_of_isAdic`, and the
  two-way criterion is `EpsilonEridani.Huber.exists_pairOfDefinition_ringOfDefinition_eq_iff`.
* `EpsilonEridani.Huber.exists_pairOfDefinition_ringOfDefinition_eq_inf`: **Wedhorn Corollary 6.4(1)**,
  the intersection half — the intersection of two rings of definition is a ring of definition.
* `EpsilonEridani.Huber.exists_pairOfDefinition_le_le`: **Wedhorn Corollary 6.4(4)** — a bounded subring
  inside an open subring is contained in a ring of definition inside that open subring. The case
  used in practice, `EpsilonEridani.Huber.exists_pairOfDefinition_ringOfDefinition_le`, is that every
  open subring of a Huber ring contains a ring of definition.
* `EpsilonEridani.Huber.exists_pairOfDefinition_ringOfDefinition_eq_top_iff`: **Wedhorn Corollary
  6.4(5)** — a Huber ring is adic exactly when it is bounded in itself.

## Provenance

The `adjoin` construction — and hence the adic-topology argument now extracted from it as
`enlarge` — is adapted from AINTLIB's `HuberRings.lean` (Apache 2.0), branch `dev/adic-spaces`
at commit `37bbdaeb9ad9e3bc9f0d660feadc2779e455a91c`. Names and the proof are adjusted to Tau
Ceti's `PairOfDefinition` and boundedness APIs.

The ideal-side headline, `isTopologicallyNilpotent_iff_exists_mem_idealOfDefinition`, corresponds to
AINTLIB's `topologicallyNilpotent_subseteq_union_definitionIdeals` in
`projects/AdicSpaces/Adic spaces/HuberRings.lean` (Apache 2.0, same branch and commit). **Only the
statement was consulted: AINTLIB's proof is a `sorry`**, whose note blames missing
definition-ring-enlargement infrastructure. Tau Ceti already had the ring-side enlargement, and what
was missing was the *ideal*-side `enlargeIdeal` supplied here, so no proof was ported. The
component lemmas of `enlargeIdeal` and the openness corollary have no AINTLIB counterpart.

`enlargeSup`, `sup` and the boundedness input `isBounded_sup` are **not** covered by that
attribution: AINTLIB cites Corollary 6.4 only for its parts (1)–(3), and has no counterpart to the
join of a ring of definition with a bounded subring.

The Lemma 6.2 section has **no source**. At the same AINTLIB commit, `HuberRings.lean`,
`Bounded.lean` and `OpenIdeals.lean` state no criterion recognising an open bounded subring as a
ring of definition, and the pinned Mathlib has no Huber rings at all. The proof below is written
from Wedhorn's, whose `T(k)`, `U` and `l` become the monomials of `Gk`, the images of the powers
of `I`, and the exponent `k` itself, `Iᵏ ⊆ B` playing both roles at once.

## References

* T. Wedhorn, *Adic Spaces*, arXiv:1910.05934v1, Lemma 6.2 and Corollary 6.4.
-/

public section

open Filter Pointwise Topology

namespace EpsilonEridani.Huber

namespace PairOfDefinition

variable {A : Type*} [CommRing A] [TopologicalSpace A] [NonarchimedeanRing A]

omit [NonarchimedeanRing A] in
/-- The original ring of definition is contained in the subring obtained by adjoining `T`. -/
private theorem le_adjoinRing (P : PairOfDefinition A) (T : Finset A) :
    P.ringOfDefinition ≤ Subring.closure ((P.ringOfDefinition : Set A) ∪ (T : Set A)) :=
  fun _ ha ↦ Subring.subset_closure (Set.mem_union_left _ ha)

end PairOfDefinition

variable {A : Type*} [CommRing A] [TopologicalSpace A]

namespace PairOfDefinition

variable [IsTopologicalRing A]

/-! ### Enlarging the ideal of definition -/

/-- If `x ^ k ∈ I ^ n` then `(I ⊔ span {x}) ^ (n + k) ≤ I ^ n`: Mathlib's binomial bound splits the
product into `I ^ n ⊔ span {x} ^ k`, and the second summand is `span {x ^ k}`, which `h` places
inside `I ^ n`.

Kept private: it is a general fact about ideals with no other consumer here, and Mathlib's
`Ideal.sup_pow_add_le_pow_sup_pow` already does the binomial step. -/
private theorem sup_span_singleton_pow_le {R : Type*} [CommRing R] (I : Ideal R) (x : R) (n k : ℕ)
    (h : x ^ k ∈ I ^ n) : (I ⊔ Ideal.span {x}) ^ (n + k) ≤ I ^ n := by
  refine Ideal.sup_pow_add_le_pow_sup_pow.trans (sup_le le_rfl ?_)
  rw [Ideal.span_singleton_pow, Ideal.span_le, Set.singleton_subset_iff]
  exact h

/-- **Adjoining a topologically nilpotent element to the ideal of definition.** The ring of
definition is unchanged and the ideal becomes `I ⊔ span {y}`. -/
noncomputable def enlargeIdeal (Q : PairOfDefinition A) {y : Q.ringOfDefinition}
    (hy : IsTopologicallyNilpotent y) : PairOfDefinition A where
  ringOfDefinition := Q.ringOfDefinition
  isOpen_ringOfDefinition := Q.isOpen_ringOfDefinition
  idealOfDefinition := Q.idealOfDefinition ⊔ Ideal.span {y}
  fg_idealOfDefinition := Submodule.FG.sup Q.fg_idealOfDefinition
    (by simpa [Ideal.span] using Submodule.fg_span_singleton y)
  isAdic_idealOfDefinition := by
    obtain ⟨hopen, hnhd⟩ := isAdic_iff.mp Q.isAdic_idealOfDefinition
    have hle : ∀ n : ℕ, (Q.idealOfDefinition ^ n : Ideal Q.ringOfDefinition)
        ≤ (Q.idealOfDefinition ⊔ Ideal.span {y}) ^ n :=
      fun n ↦ pow_le_pow_left' le_sup_left n
    refine isAdic_iff.mpr ⟨fun n ↦ Ideal.isOpen_of_isOpen_subideal (hle n) (hopen n), fun s hs ↦ ?_⟩
    obtain ⟨n, hn⟩ := hnhd s hs
    obtain ⟨k, hk⟩ := hy.exists_pow_mem_of_mem_nhds ((hopen n).mem_nhds (Ideal.zero_mem _))
    exact ⟨n + k,
      (SetLike.coe_subset_coe.mpr (sup_span_singleton_pow_le _ _ _ _ hk)).trans hn⟩

/-- The ring of definition is unchanged by `enlargeIdeal`. -/
@[simp]
theorem enlargeIdeal_ringOfDefinition (Q : PairOfDefinition A) {y : Q.ringOfDefinition}
    (hy : IsTopologicallyNilpotent y) :
    (Q.enlargeIdeal hy).ringOfDefinition = Q.ringOfDefinition := (rfl)

/-- The ideal of definition gains exactly `y`: it becomes `I ⊔ span {y}`. -/
@[simp]
theorem enlargeIdeal_idealOfDefinition (Q : PairOfDefinition A) {y : Q.ringOfDefinition}
    (hy : IsTopologicallyNilpotent y) :
    (Q.enlargeIdeal hy).idealOfDefinition =
      (enlargeIdeal_ringOfDefinition Q hy) ▸ (Q.idealOfDefinition ⊔ Ideal.span {y}) := (rfl)

/-- **The adjoined element lies in the enlarged ideal of definition.** This is the introduction
rule the enlargement exists for, and it reaches the membership through
`enlargeIdeal_idealOfDefinition` rather than by unfolding the constructor.

The element is presented as `⟨(y : A), h⟩` over the *enlarged* ring of definition rather than as
`y` itself. The two rings are equal — that is `enlargeIdeal_ringOfDefinition` — but only by
unfolding `enlargeIdeal`, whose body is sealed, so `y ∈ (Q.enlargeIdeal hy).idealOfDefinition`
cannot be stated directly: its `Membership` instance would have to unify
`↥Q.ringOfDefinition` with `↥(Q.enlargeIdeal hy).ringOfDefinition`. Taking the membership witness
as an argument is also exactly the shape the existential in
`isTopologicallyNilpotent_iff_exists_mem_idealOfDefinition` needs.

Deliberately not `@[simp]`: `enlargeIdeal_idealOfDefinition` already is, so `simp` rewrites the
ideal to `I ⊔ span {y}` and this statement's left-hand side is not in simp-normal form. It is an
introduction rule to `exact`, not a rewrite. -/
theorem mem_enlargeIdeal_idealOfDefinition (Q : PairOfDefinition A) {y : Q.ringOfDefinition}
    (hy : IsTopologicallyNilpotent y) (h : (y : A) ∈ (Q.enlargeIdeal hy).ringOfDefinition) :
    (⟨(y : A), h⟩ : (Q.enlargeIdeal hy).ringOfDefinition) ∈
      (Q.enlargeIdeal hy).idealOfDefinition := by
  rw [Q.enlargeIdeal_idealOfDefinition hy]
  exact Ideal.mem_sup_right (Ideal.mem_span_singleton_self y)

/-- Every power of the ideal of definition, carried into a larger subring `B`, is open in `B`.

Boundedness of `B` is not needed; only that `B` contains the ring of definition. -/
private theorem isOpen_idealOfDefinition_map_pow (P : PairOfDefinition A) (B : Subring A)
    (hle : P.ringOfDefinition ≤ B) (n : ℕ) :
    IsOpen (((P.idealOfDefinition.map (Subring.inclusion hle)) ^ n : Ideal B) : Set B) :=
  AddSubgroup.isOpen_of_mem_nhds
    ((P.idealOfDefinition.map (Subring.inclusion hle) ^ n).toAddSubgroup) <| by
    rw [Submodule.coe_toAddSubgroup]
    have hnhd : Subtype.val ⁻¹' (P.idealImage n : Set A) ∈ 𝓝 (0 : B) :=
      continuous_subtype_val.continuousAt.preimage_mem_nhds <|
        (P.isOpen_idealImage n).mem_nhds (P.idealImage n).zero_mem
    refine mem_of_superset hnhd ?_
    rintro ⟨x, hxB⟩ hx
    obtain ⟨y, hy, hxy⟩ := (P.mem_idealImage n).mp hx
    have heq : (⟨x, hxB⟩ : B) = Subring.inclusion hle y := Subtype.ext hxy.symm
    rw [heq, ← Ideal.map_pow]
    exact Ideal.mem_map_of_mem _ hy

/-- Every neighbourhood of `0` in a bounded subring `B` containing the ring of definition
contains a power of the ideal of definition carried into `B`. -/
private theorem exists_idealOfDefinition_map_pow_subset (P : PairOfDefinition A) (B : Subring A)
    (hle : P.ringOfDefinition ≤ B) (hB : IsBounded (B : Set A)) (s : Set B) (hs : s ∈ 𝓝 (0 : B)) :
    ∃ n : ℕ, (((P.idealOfDefinition.map (Subring.inclusion hle)) ^ n : Ideal B) : Set B) ⊆ s := by
  let := P.toNonarchimedeanRing
  rw [nhds_induced] at hs
  obtain ⟨U, hU, hUs⟩ := mem_comap.mp hs
  obtain ⟨G, hGU⟩ := NonarchimedeanRing.is_nonarchimedean U hU
  obtain ⟨V, hV, hVB⟩ := isBounded_iff.mp hB (G : Set A) (G.isOpen.mem_nhds G.zero_mem)
  obtain ⟨n, -, hn⟩ := P.hasBasis_nhds_zero.mem_iff.mp hV
  refine ⟨n, fun x hx ↦ hUs (hGU ?_)⟩
  have hx' : x ∈ P.idealOfDefinition.map (Subring.inclusion hle) ^ n := hx
  rw [← Ideal.map_pow] at hx'
  obtain ⟨f, hf, rfl⟩ := Submodule.mem_span_set.mp hx'
  simp only [Finsupp.sum, smul_eq_mul]
  have hcoe_sum : ((∑ i ∈ f.support, f i * i : B) : A) =
      ∑ i ∈ f.support, ((f i * i : B) : A) := map_sum B.subtype _ _
  rw [hcoe_sum]
  apply G.toAddSubgroup.sum_mem
  intro i hi
  obtain ⟨a, ha, rfl⟩ := hf (Finset.mem_coe.mpr hi)
  have hcoe : ((f (Subring.inclusion hle a) * Subring.inclusion hle a : B) : A) =
      (f (Subring.inclusion hle a) : A) * (a : A) := by
    rw [MulMemClass.coe_mul, Subring.coe_inclusion]
  rw [hcoe, mul_comm]
  exact hVB <| Set.mul_mem_mul (hn ((P.mem_idealImage n).mpr ⟨a, ha, rfl⟩))
    (f (Subring.inclusion hle a)).property

/-- **Enlarging a ring of definition.** Any bounded subring `B` containing a ring of definition
`A₀` is itself one, with the image of `I` as its ideal of definition. -/
def enlarge (P : PairOfDefinition A) (B : Subring A) (hle : P.ringOfDefinition ≤ B)
    (hB : IsBounded (B : Set A)) : PairOfDefinition A where
  ringOfDefinition := B
  isOpen_ringOfDefinition := AddSubgroup.isOpen_of_mem_nhds B.toAddSubgroup <|
    mem_of_superset
      (P.isOpen_ringOfDefinition.mem_nhds P.ringOfDefinition.zero_mem) hle
  idealOfDefinition := P.idealOfDefinition.map (Subring.inclusion hle)
  fg_idealOfDefinition := P.fg_idealOfDefinition.map _
  isAdic_idealOfDefinition :=
    isAdic_iff.mpr ⟨P.isOpen_idealOfDefinition_map_pow B hle,
      P.exists_idealOfDefinition_map_pow_subset B hle hB⟩

/-- The ring of definition of `P.enlarge B hle hB` is `B`. -/
@[simp]
theorem enlarge_ringOfDefinition (P : PairOfDefinition A) (B : Subring A)
    (hle : P.ringOfDefinition ≤ B) (hB : IsBounded (B : Set A)) :
    (P.enlarge B hle hB).ringOfDefinition = B := (rfl)

/-- The old ring of definition is contained in the enlarged one. -/
theorem le_enlarge (P : PairOfDefinition A) (B : Subring A) (hle : P.ringOfDefinition ≤ B)
    (hB : IsBounded (B : Set A)) :
    P.ringOfDefinition ≤ (P.enlarge B hle hB).ringOfDefinition := by
  rw [enlarge_ringOfDefinition]
  exact hle

/-- The ideal of definition of `P.enlarge B hle hB` is the image of `I`. -/
@[simp]
theorem enlarge_idealOfDefinition (P : PairOfDefinition A) (B : Subring A)
    (hle : P.ringOfDefinition ≤ B) (hB : IsBounded (B : Set A)) :
    (P.enlarge B hle hB).idealOfDefinition =
      P.idealOfDefinition.map (Subring.inclusion (P.le_enlarge B hle hB)) := (rfl)

/-- Adjoin a finite set of power-bounded elements to a pair of definition. The new ring of
definition is `A₀[T]`, and its ideal of definition is generated by the image of the old ideal. -/
def adjoin (P : PairOfDefinition A) (T : Finset A) (hT : ∀ t ∈ T, IsPowerBounded t) :
    PairOfDefinition A :=
  letI := P.toNonarchimedeanRing
  P.enlarge (Subring.closure ((P.ringOfDefinition : Set A) ∪ (T : Set A))) (P.le_adjoinRing T)
    (by
      rw [Subring.closure_union, Subring.closure_eq]
      exact isBounded_sup _ _ P.isBounded_ringOfDefinition
        (isBounded_subringClosure T.finite_toSet hT))

/-- The ring of definition of `P.adjoin T hT` is the subring `A₀[T]`. -/
@[simp]
theorem adjoin_ringOfDefinition (P : PairOfDefinition A) (T : Finset A)
    (hT : ∀ t ∈ T, IsPowerBounded t) :
    (P.adjoin T hT).ringOfDefinition =
      Subring.closure ((P.ringOfDefinition : Set A) ∪ (T : Set A)) := (rfl)

/-- The old ring of definition is contained in the enlarged ring of definition. -/
theorem le_adjoin (P : PairOfDefinition A) (T : Finset A)
    (hT : ∀ t ∈ T, IsPowerBounded t) :
    P.ringOfDefinition ≤ (P.adjoin T hT).ringOfDefinition := by
  rw [adjoin_ringOfDefinition]
  exact P.le_adjoinRing T

/-- The ideal of definition after adjoining `T` is generated by the image of the old ideal. -/
@[simp]
theorem adjoin_idealOfDefinition (P : PairOfDefinition A) (T : Finset A)
    (hT : ∀ t ∈ T, IsPowerBounded t) :
    (P.adjoin T hT).idealOfDefinition =
      P.idealOfDefinition.map (Subring.inclusion (P.le_adjoin T hT)) := by
  have hadjoin_ideal : (P.adjoin T hT).idealOfDefinition =
      P.idealOfDefinition.map (Subring.inclusion (P.le_adjoinRing T)) := rfl
  have hinclusion : Subring.inclusion (P.le_adjoinRing T) =
      Subring.inclusion (P.le_adjoin T hT) := by
    apply RingHom.ext
    intro x
    apply Subtype.ext
    rfl
  exact hadjoin_ideal.trans (congrArg (fun f ↦ P.idealOfDefinition.map f) hinclusion)

/-- Every adjoined element belongs to the enlarged ring of definition. -/
theorem mem_adjoin_of_mem (P : PairOfDefinition A) (T : Finset A)
    (hT : ∀ t ∈ T, IsPowerBounded t) {t : A} (ht : t ∈ T) :
    t ∈ (P.adjoin T hT).ringOfDefinition := by
  rw [adjoin_ringOfDefinition]
  exact Subring.subset_closure (Set.mem_union_right _ (Finset.mem_coe.mpr ht))

/-- **Joining a ring of definition with a bounded subring.** For any bounded `B`, the join
`A₀ ⊔ B` is again a ring of definition. The join of two rings of definition is the case
`B = A₁`. -/
def enlargeSup (P : PairOfDefinition A) (B : Subring A) (hB : IsBounded (B : Set A)) :
    PairOfDefinition A :=
  letI := P.toNonarchimedeanRing
  P.enlarge (P.ringOfDefinition ⊔ B) _root_.le_sup_left
    (isBounded_sup P.ringOfDefinition B P.isBounded_ringOfDefinition hB)

/-- The ring of definition of `P.enlargeSup B hB` is `A₀ ⊔ B`. -/
@[simp]
theorem enlargeSup_ringOfDefinition (P : PairOfDefinition A) (B : Subring A)
    (hB : IsBounded (B : Set A)) :
    (P.enlargeSup B hB).ringOfDefinition = P.ringOfDefinition ⊔ B :=
  P.enlarge_ringOfDefinition _ _ _

/-- The original ring of definition is contained in the join. -/
theorem le_enlargeSup_left (P : PairOfDefinition A) (B : Subring A)
    (hB : IsBounded (B : Set A)) :
    P.ringOfDefinition ≤ (P.enlargeSup B hB).ringOfDefinition := by
  rw [enlargeSup_ringOfDefinition]
  exact _root_.le_sup_left

/-- The adjoined subring is contained in the join — the defining property of the construction. -/
theorem le_enlargeSup_right (P : PairOfDefinition A) (B : Subring A)
    (hB : IsBounded (B : Set A)) :
    B ≤ (P.enlargeSup B hB).ringOfDefinition := by
  rw [enlargeSup_ringOfDefinition]
  exact _root_.le_sup_right

/-- The ideal of definition of `P.enlargeSup B hB` is the image of `I`, as for any `enlarge`. -/
@[simp]
theorem enlargeSup_idealOfDefinition (P : PairOfDefinition A) (B : Subring A)
    (hB : IsBounded (B : Set A)) :
    (P.enlargeSup B hB).idealOfDefinition =
      P.idealOfDefinition.map (Subring.inclusion (P.le_enlargeSup_left B hB)) :=
  P.enlarge_idealOfDefinition _ _ _

/-- **Wedhorn Corollary 6.4, the product half.** The join of two rings of definition is again a
ring of definition; its ideal of definition is the image of the first one's. -/
def sup (P Q : PairOfDefinition A) : PairOfDefinition A :=
  P.enlargeSup Q.ringOfDefinition Q.isBounded_ringOfDefinition

/-- The ring of definition of `P.sup Q` is `A₀ ⊔ A₁`. -/
@[simp]
theorem sup_ringOfDefinition (P Q : PairOfDefinition A) :
    (P.sup Q).ringOfDefinition = P.ringOfDefinition ⊔ Q.ringOfDefinition :=
  P.enlargeSup_ringOfDefinition _ _

/-- The first ring of definition is contained in the join. -/
theorem le_sup_left (P Q : PairOfDefinition A) :
    P.ringOfDefinition ≤ (P.sup Q).ringOfDefinition :=
  P.le_enlargeSup_left _ _

/-- The second ring of definition is contained in the join. -/
theorem le_sup_right (P Q : PairOfDefinition A) :
    Q.ringOfDefinition ≤ (P.sup Q).ringOfDefinition :=
  P.le_enlargeSup_right _ _

/-- The ideal of definition of `P.sup Q` is the image of `P`'s. -/
@[simp]
theorem sup_idealOfDefinition (P Q : PairOfDefinition A) :
    (P.sup Q).idealOfDefinition =
      P.idealOfDefinition.map (Subring.inclusion (P.le_sup_left Q)) :=
  P.enlargeSup_idealOfDefinition _ _

end PairOfDefinition

variable {A : Type*} [CommRing A] [TopologicalSpace A] [IsTopologicalRing A] [IsHuberRing A]

/-- Wedhorn Corollary 6.4: an element of a Huber ring is power-bounded exactly when it belongs
to some ring of definition. Equivalently, `A°` is the union of all rings of definition. -/
theorem isPowerBounded_iff_exists_mem_ringOfDefinition {a : A} :
    IsPowerBounded a ↔ ∃ P : PairOfDefinition A, a ∈ P.ringOfDefinition := by
  constructor
  · intro ha
    obtain ⟨P⟩ := IsHuberRing.nonempty_pairOfDefinition (A := A)
    let T : Finset A := {a}
    have hT : ∀ t ∈ T, IsPowerBounded t := by simpa [T] using ha
    exact ⟨P.adjoin T hT, P.mem_adjoin_of_mem T hT (by simp [T])⟩
  · rintro ⟨P, ha⟩
    exact mem_powerBoundedSubring.mp (P.le_powerBoundedSubring ha)

/-- **The ideal-side companion of Corollary 6.4**: an element of a Huber ring is topologically
nilpotent exactly when it belongs to some ideal of definition. Equivalently, the topologically
nilpotent elements are the union of all ideals of definition. -/
theorem isTopologicallyNilpotent_iff_exists_mem_idealOfDefinition {a : A} :
    IsTopologicallyNilpotent a ↔
      ∃ (P : PairOfDefinition A) (h : a ∈ P.ringOfDefinition),
        (⟨a, h⟩ : P.ringOfDefinition) ∈ P.idealOfDefinition := by
  constructor
  · intro ha
    obtain ⟨P, hmem⟩ := isPowerBounded_iff_exists_mem_ringOfDefinition.mp
      (IsPowerBounded.of_isTopologicallyNilpotent ha)
    -- `y` is the element itself, viewed in the ring of definition it was just placed in
    set y : P.ringOfDefinition := ⟨a, hmem⟩
    have hnil : IsTopologicallyNilpotent y := isTopologicallyNilpotent_mk hmem ha
    -- enlarging by `y` puts it in the ideal of definition, leaving the ring of definition alone
    exact ⟨P.enlargeIdeal hnil, hmem, P.mem_enlargeIdeal_idealOfDefinition hnil hmem⟩
  · rintro ⟨P, h, ha⟩
    exact P.isTopologicallyNilpotent_of_mem_idealOfDefinition ha

/-- **The topologically nilpotent elements of a Huber ring form an open set**, i.e. `A°°` is open
in `A`. -/
theorem isOpen_setOf_isTopologicallyNilpotent :
    IsOpen {x : A | IsTopologicallyNilpotent x} := by
  have hunion : {x : A | IsTopologicallyNilpotent x}
      = ⋃ P : PairOfDefinition A, (P.idealImage 1 : Set A) := by
    ext x
    simp only [Set.mem_ofPred_eq, Set.mem_iUnion, SetLike.mem_coe]
    constructor
    · intro hx
      obtain ⟨P, hmem, hI⟩ := isTopologicallyNilpotent_iff_exists_mem_idealOfDefinition.mp hx
      exact ⟨P, (P.mem_idealImage 1).mpr ⟨⟨x, hmem⟩, by simpa using hI, rfl⟩⟩
    · rintro ⟨P, hP⟩
      exact P.isTopologicallyNilpotent_of_mem_idealImage one_ne_zero hP
  rw [hunion]
  exact isOpen_iUnion fun P ↦ P.isOpen_idealImage 1

/-! ### Wedhorn Lemma 6.2: the rings of definition are the open bounded subrings -/

namespace PairOfDefinition

omit [IsTopologicalRing A] [IsHuberRing A] in
/-- A product of `n` elements of a set `S ⊆ B` whose images lie in `Iᵏ` has image in `I^(k * n)`.

This is the multiplicative bookkeeping behind Wedhorn's `Jⁿ = T(nk)·B` step: the `n`-th power of
an ideal generated by elements of `Iᵏ` still consists of elements of `I^(k * n)`. -/
private theorem mem_idealImage_of_mem_pow (P : PairOfDefinition A) {B : Subring A} {S : Set B}
    {k : ℕ} (hS : ∀ y ∈ S, (y : A) ∈ P.idealImage k) :
    ∀ (n : ℕ), ∀ y ∈ S ^ n, (y : A) ∈ P.idealImage (k * n) := by
  intro n
  induction n with
  | zero =>
    intro y hy
    rw [pow_zero, Set.mem_one] at hy
    subst hy
    exact (P.mem_idealImage 0).mpr ⟨1, by simp, rfl⟩
  | succ n ih =>
    intro y hy
    rw [pow_succ] at hy
    obtain ⟨u, hu, v, hv, rfl⟩ := Set.mem_mul.mp hy
    rw [Nat.mul_succ, MulMemClass.coe_mul]
    exact P.mul_mem_idealImage_add (ih u hu) (hS v hv)

omit [IsTopologicalRing A] [IsHuberRing A] in
/-- **The core of Wedhorn Lemma 6.2.** Let `Gk` span `Iᵏ`, let `Iᵏ` lie inside a subring `B`, and
let every element of `Gk` have a counterpart in a subset `S` of `B`; write `J = (S)` for the ideal
of `B` it spans. Then `I^(k * (n + 1))` lands inside `Jⁿ`.

At `n = 0` this is the hypothesis `Iᵏ ⊆ B`. The induction step writes an element of
`I^(k * (n + 2)) = Iᵏ · I^(k * (n + 1))` over `Gk` with cofactors in `I^(k * (n + 1))`, then
replaces each generator by its counterpart in `S ⊆ J` and each cofactor, by the induction
hypothesis, by an element of `Jⁿ`. Since each `I^m` is open, this is what makes the powers of `J`
neighbourhoods of `0`. -/
private theorem idealImage_subset_image_span_pow (P : PairOfDefinition A) {B : Subring A} {k : ℕ}
    (hk : (P.idealImage k : Set A) ⊆ B) {Gk : Finset P.ringOfDefinition}
    (hGk : Ideal.span (Gk : Set P.ringOfDefinition) = P.idealOfDefinition ^ k) {S : Set B}
    (hS : ∀ z ∈ Gk, ∃ y ∈ S, (y : A) = (z : A)) (n : ℕ) :
    (P.idealImage (k * (n + 1)) : Set A) ⊆
      Subtype.val '' ((Ideal.span S ^ n : Ideal B) : Set B) := by
  induction n with
  | zero =>
    intro x hx
    simp only [zero_add, mul_one] at hx
    exact ⟨⟨x, hk hx⟩, by simp, rfl⟩
  | succ n ih =>
    intro x hx
    obtain ⟨x', hx', rfl⟩ := (P.mem_idealImage _).mp hx
    -- Split `I ^ (k * (n + 2))` as `(Gk) * I ^ (k * (n + 1))` and expand over `Gk`.
    have hsplit : k + k * (n + 1) = k * (n + 1 + 1) := by ring
    have hmul : x' ∈ Ideal.span (Gk : Set P.ringOfDefinition) *
        P.idealOfDefinition ^ (k * (n + 1)) := by
      rw [hGk, ← pow_add, hsplit]
      exact hx'
    obtain ⟨c, hc, hsum⟩ :=
      exists_sum_eq_of_mem_span_mul Gk (P.idealOfDefinition ^ (k * (n + 1))) hmul
    -- Each cofactor `c z` has a counterpart in `Jⁿ`, by the induction hypothesis.
    have hcof : ∀ z : P.ringOfDefinition,
        ∃ w ∈ (Ideal.span S ^ n : Ideal B), (w : A) = (c z : A) :=
      fun z ↦ ih ((P.mem_idealImage _).mpr ⟨c z, hc z, rfl⟩)
    choose w hw hweq using hcof
    choose u hu hueq using hS
    refine ⟨∑ z ∈ Gk.attach, u z.1 z.2 * w z.1, Submodule.sum_mem _ fun z _ ↦ ?_, ?_⟩
    · rw [pow_succ']
      exact Ideal.mul_mem_mul (Ideal.subset_span (hu z.1 z.2)) (hw z.1)
    · rw [← hsum]
      push_cast
      rw [← Finset.sum_attach Gk fun z ↦ (z : A) * (c z : A)]
      exact Finset.sum_congr rfl fun z _ ↦ by rw [hueq z.1 z.2, hweq z.1]

end PairOfDefinition

/-- **Wedhorn Lemma 6.2, the substantial implication.** Every open bounded subring `B` of a Huber
ring is a ring of definition.

The ideal of definition is `J = (Gk)`, generated in `B` by the degree-`k` monomials in a finite
generating set of an ideal of definition `I`, for an exponent `k ≥ 1` large enough that `Iᵏ ⊆ B`.
Two inclusions make `J` adic: `I^(k * (n + 1)) ⊆ Jⁿ` makes every power of `J` open, and
boundedness of `B` — the hypothesis doing the real work — puts `Jᵐ` inside `Iᵐ · B`, which is
eventually inside any neighbourhood of `0`. -/
theorem exists_pairOfDefinition_ringOfDefinition_eq (B : Subring A)
    (hopen : IsOpen (B : Set A)) (hbdd : IsBounded (B : Set A)) :
    ∃ Q : PairOfDefinition A, Q.ringOfDefinition = B := by
  classical
  obtain ⟨P⟩ := IsHuberRing.nonempty_pairOfDefinition (A := A)
  obtain ⟨G, hG⟩ := P.fg_idealOfDefinition
  -- An exponent `k₀ + 1 ≥ 1` with `I ^ (k₀ + 1) ⊆ B`; positivity is used for `Jᵐ ⊆ Iᵐ · B`.
  obtain ⟨k₀, -, hk₀⟩ := P.hasBasis_nhds_zero.mem_iff.mp (hopen.mem_nhds B.zero_mem)
  have hk : (P.idealImage (k₀ + 1) : Set A) ⊆ B := fun x hx ↦
    hk₀ (P.idealImage_anti (Nat.le_succ k₀) hx)
  -- `Gk` spans `I ^ (k₀ + 1)`, and `S` is its copy inside `B`.
  have hspan : Ideal.span ((G ^ (k₀ + 1) : Finset P.ringOfDefinition) :
      Set P.ringOfDefinition) = P.idealOfDefinition ^ (k₀ + 1) := by
    rw [Finset.coe_pow]
    -- `Ideal.span` is definitionally `Submodule.span`; expose that representation to apply
    -- Mathlib's `Submodule.span_pow` directly.
    change Submodule.span P.ringOfDefinition ((G : Set P.ringOfDefinition) ^ (k₀ + 1)) = _
    rw [← Submodule.span_pow]
    exact congrArg (· ^ (k₀ + 1)) hG
  have hGkB : ∀ z ∈ G ^ (k₀ + 1), (z : A) ∈ B := fun z hz ↦
    hk ((P.mem_idealImage _).mpr ⟨z, hspan ▸ Ideal.subset_span hz, rfl⟩)
  set S : Set B :=
    Subtype.val ⁻¹' (Subtype.val '' ((G ^ (k₀ + 1) : Finset P.ringOfDefinition) :
      Set P.ringOfDefinition))
  have hSmem : ∀ z ∈ G ^ (k₀ + 1), ∃ y ∈ S, (y : A) = (z : A) := fun z hz ↦
    ⟨⟨(z : A), hGkB z hz⟩, ⟨z, hz, rfl⟩, rfl⟩
  have hSk : ∀ y ∈ S, (y : A) ∈ P.idealImage (k₀ + 1) := by
    rintro y ⟨z, hz, hzy⟩
    exact hzy ▸ (P.mem_idealImage _).mpr ⟨z, hspan ▸ Ideal.subset_span hz, rfl⟩
  refine ⟨{ ringOfDefinition := B
            isOpen_ringOfDefinition := hopen
            idealOfDefinition := Ideal.span S
            fg_idealOfDefinition := Submodule.fg_span (Set.Finite.preimage
              Subtype.val_injective.injOn ((G ^ (k₀ + 1)).finite_toSet.image _))
            isAdic_idealOfDefinition := isAdic_iff.mpr ⟨fun n ↦ ?_, fun s hs ↦ ?_⟩ }, rfl⟩
  · -- `Jⁿ` contains the trace of the open set `I ^ ((k₀ + 1) * (n + 1))`, hence is open.
    refine AddSubgroup.isOpen_of_mem_nhds (g := 0) (Ideal.span S ^ n).toAddSubgroup ?_
    rw [Submodule.coe_toAddSubgroup]
    refine mem_of_superset (continuous_subtype_val.continuousAt.preimage_mem_nhds
      ((P.isOpen_idealImage ((k₀ + 1) * (n + 1))).mem_nhds (P.idealImage _).zero_mem)) ?_
    intro y hy
    obtain ⟨v, hv, hveq⟩ := P.idealImage_subset_image_span_pow hk hspan hSmem n hy
    exact Subtype.val_injective hveq ▸ hv
  · -- Boundedness of `B` shrinks `Jᵐ` inside any neighbourhood of `0`.
    rw [nhds_induced] at hs
    obtain ⟨U, hU, hUs⟩ := Filter.mem_comap.mp hs
    obtain ⟨W, hWU⟩ := NonarchimedeanRing.is_nonarchimedean U hU
    obtain ⟨V, hV, hVB⟩ := isBounded_iff.mp hbdd (W : Set A) (W.isOpen.mem_nhds W.zero_mem)
    obtain ⟨m, -, hm⟩ := P.hasBasis_nhds_zero.mem_iff.mp hV
    refine ⟨m, fun x hx ↦ hUs (hWU ?_)⟩
    rw [Submodule.span_pow] at hx
    obtain ⟨f, hf, rfl⟩ := Submodule.mem_span_set.mp hx
    have hcoe_sum : ((∑ i ∈ f.support, f i • i : B) : A) = ∑ i ∈ f.support, ((f i • i : B) : A) :=
      map_sum B.subtype _ _
    rw [Finsupp.sum, hcoe_sum]
    refine W.toAddSubgroup.sum_mem fun i hi ↦ ?_
    have hiI : (i : A) ∈ P.idealImage m :=
      P.idealImage_anti (Nat.le_mul_of_pos_left m k₀.succ_pos)
        (P.mem_idealImage_of_mem_pow hSk m i (hf (Finset.mem_coe.mpr hi)))
    rw [smul_eq_mul, MulMemClass.coe_mul, mul_comm]
    exact hVB (Set.mul_mem_mul (hm hiI) (f i).property)

omit [IsHuberRing A] in
/-- **Wedhorn Lemma 6.2, the easy implication `(b) ⇒ (c)`.** An open subring whose subspace
topology is adic is bounded: the powers of the ideal are open in `B`, hence open in `A`, and each
of them absorbs multiplication by `B` because it is an ideal of `B`.

No finite generation of `J` is asked, and `A` need not be Huber. -/
theorem isBounded_of_isAdic {B : Subring A} (hopen : IsOpen (B : Set A)) {J : Ideal B}
    (hJ : IsAdic J) : IsBounded (B : Set A) := by
  rw [isBounded_iff]
  intro U hU
  obtain ⟨n, hn⟩ := (isAdic_iff.mp hJ).2 _
    (continuous_subtype_val.continuousAt.preimage_mem_nhds hU)
  refine ⟨Subtype.val '' ((J ^ n : Ideal B) : Set B),
    (hopen.isOpenEmbedding_subtypeVal.isOpenMap _ ((isAdic_iff.mp hJ).1 n)).mem_nhds
      ⟨0, (J ^ n).zero_mem, rfl⟩, ?_⟩
  rintro _ ⟨_, ⟨y, hy, rfl⟩, b, hb, rfl⟩
  exact hn (Ideal.mul_mem_right ⟨b, hb⟩ _ hy)

/-- **Wedhorn Lemma 6.2.** For a subring `B` of a Huber ring the following are equivalent:

1. `B` is a ring of definition, that is, it carries a finitely generated ideal whose adic topology
   is the subspace topology;
2. `B` is open and its subspace topology is adic for some — not necessarily finitely generated —
   ideal;
3. `B` is open and bounded.

The implication `1 → 2` forgets the finite generation, `2 → 3` is `isBounded_of_isAdic`, and
`3 → 1` is `exists_pairOfDefinition_ringOfDefinition_eq`, which manufactures a finitely generated
ideal out of boundedness. -/
theorem exists_pairOfDefinition_ringOfDefinition_eq_tfae (B : Subring A) :
    [∃ Q : PairOfDefinition A, Q.ringOfDefinition = B,
      IsOpen (B : Set A) ∧ ∃ J : Ideal B, IsAdic J,
      IsOpen (B : Set A) ∧ IsBounded (B : Set A)].TFAE := by
  tfae_have 1 → 2 := by
    rintro ⟨Q, rfl⟩
    exact ⟨Q.isOpen_ringOfDefinition, Q.idealOfDefinition, Q.isAdic_idealOfDefinition⟩
  tfae_have 2 → 3 := fun ⟨hopen, _, hJ⟩ ↦ ⟨hopen, isBounded_of_isAdic hopen hJ⟩
  tfae_have 3 → 1 := fun ⟨hopen, hbdd⟩ ↦
    exists_pairOfDefinition_ringOfDefinition_eq B hopen hbdd
  tfae_finish

/-- **Wedhorn Lemma 6.2 as a criterion:** the rings of definition of a Huber ring are exactly its
open bounded subrings. -/
@[simp]
theorem exists_pairOfDefinition_ringOfDefinition_eq_iff (B : Subring A) :
    (∃ Q : PairOfDefinition A, Q.ringOfDefinition = B) ↔
      IsOpen (B : Set A) ∧ IsBounded (B : Set A) := by
  refine ⟨?_, fun ⟨hopen, hbdd⟩ ↦ exists_pairOfDefinition_ringOfDefinition_eq B hopen hbdd⟩
  rintro ⟨Q, rfl⟩
  exact ⟨Q.isOpen_ringOfDefinition, Q.isBounded_ringOfDefinition⟩

/-! ### Additional parts of Wedhorn Corollary 6.4 (excluding part (2)) -/

/-- **Wedhorn Corollary 6.4(1), the intersection half.** The intersection of two rings of
definition is a ring of definition: it is open as an intersection of two opens and bounded as a
subset of either.

Unlike the join `EpsilonEridani.Huber.PairOfDefinition.sup`, this cannot be obtained by enlargement —
the ideal would arrive by `Ideal.comap` rather than `Ideal.map`, and a comap of a finitely
generated ideal need not be finitely generated. It is Lemma 6.2 that supplies one. -/
theorem exists_pairOfDefinition_ringOfDefinition_eq_inf (P Q : PairOfDefinition A) :
    ∃ R : PairOfDefinition A,
      R.ringOfDefinition = P.ringOfDefinition ⊓ Q.ringOfDefinition :=
  exists_pairOfDefinition_ringOfDefinition_eq _
    (by rw [Subring.coe_inf]
        exact P.isOpen_ringOfDefinition.inter Q.isOpen_ringOfDefinition)
    (P.isBounded_ringOfDefinition.subset
      (by rw [Subring.coe_inf]; exact Set.inter_subset_left))

/-- **Every open subring of a Huber ring contains a ring of definition:** intersect any ring of
definition with it and apply Lemma 6.2. This is the form in which Wedhorn Corollary 6.4(4) is
used, for instance to choose a ring of definition inside a ring of integral elements. -/
theorem exists_pairOfDefinition_ringOfDefinition_le {C : Subring A} (hC : IsOpen (C : Set A)) :
    ∃ Q : PairOfDefinition A, Q.ringOfDefinition ≤ C := by
  obtain ⟨P⟩ := IsHuberRing.nonempty_pairOfDefinition (A := A)
  obtain ⟨Q, hQ⟩ := exists_pairOfDefinition_ringOfDefinition_eq (P.ringOfDefinition ⊓ C)
    (by rw [Subring.coe_inf]; exact P.isOpen_ringOfDefinition.inter hC)
    (P.isBounded_ringOfDefinition.subset
      (by rw [Subring.coe_inf]; exact Set.inter_subset_left))
  exact ⟨Q, hQ ▸ inf_le_right⟩

/-- **Wedhorn Corollary 6.4(4).** A bounded subring `B` contained in an open subring `C` is
contained in a ring of definition which is itself contained in `C`: the candidate is
`(A₀ ⊓ C) ⊔ B`, open because it contains the open `A₀ ⊓ C` and bounded as a join of two bounded
subrings. -/
theorem exists_pairOfDefinition_le_le {B C : Subring A} (hB : IsBounded (B : Set A))
    (hC : IsOpen (C : Set A)) (hBC : B ≤ C) :
    ∃ Q : PairOfDefinition A, B ≤ Q.ringOfDefinition ∧ Q.ringOfDefinition ≤ C := by
  obtain ⟨P⟩ := IsHuberRing.nonempty_pairOfDefinition (A := A)
  have hinf : IsOpen ((P.ringOfDefinition ⊓ C : Subring A) : Set A) := by
    rw [Subring.coe_inf]
    exact P.isOpen_ringOfDefinition.inter hC
  obtain ⟨Q, hQ⟩ := exists_pairOfDefinition_ringOfDefinition_eq
    ((P.ringOfDefinition ⊓ C) ⊔ B)
    (AddSubgroup.isOpen_of_mem_nhds (g := 0)
      (P.ringOfDefinition ⊓ C ⊔ B : Subring A).toAddSubgroup
      (mem_of_superset (hinf.mem_nhds (by simp))
      (SetLike.coe_subset_coe.mpr _root_.le_sup_left)))
    (isBounded_sup _ _ (P.isBounded_ringOfDefinition.subset
      (by rw [Subring.coe_inf]; exact Set.inter_subset_left)) hB)
  exact ⟨Q, hQ ▸ _root_.le_sup_right, hQ ▸ sup_le inf_le_right hBC⟩

/-- **Wedhorn Corollary 6.4(5).** A Huber ring is adic — the whole ring is a ring of definition,
so that its topology is the adic topology of a finitely generated ideal — exactly when it is
bounded in itself. -/
theorem exists_pairOfDefinition_ringOfDefinition_eq_top_iff :
    (∃ Q : PairOfDefinition A, Q.ringOfDefinition = ⊤) ↔ IsBounded (Set.univ : Set A) := by
  rw [exists_pairOfDefinition_ringOfDefinition_eq_iff]
  simp

end EpsilonEridani.Huber
