/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.Analysis.InnerProductSpace.Spectrum
public import EpsilonEridani.Analysis.Semigroups.Group.Flow
public import EpsilonEridani.Analysis.Semigroups.Group.Generator
public import EpsilonEridani.Dynamics.Flow.Stable
import EpsilonEridani.Analysis.Normed.Operator.Exponential

/-!
# Flows of bounded linear operators

The operator exponential of a bounded endomorphism `A` gives a linear flow
`(t, x) ↦ exp (t A) x`. For a symmetric operator on a finite-dimensional real inner-product
space, its ordered orthonormal eigenbasis makes the asymptotic directions of this flow explicit.

This file proves the linear spectral model used by the stable-manifold theorem. For the flow of a
symmetric operator `T`, a vector converges to zero in forward time exactly when it belongs to the
negative spectral subspace of `T`, and it converges in backward time exactly when it belongs to
the positive spectral subspace. No invertibility hypothesis is needed: a component in the zero
eigenspace is constant and therefore belongs to neither asymptotic set unless it vanishes. The
negative-gradient convention used by Morse theory is recovered by applying these to `-T`.

## Main declarations

* `ContinuousLinearMap.flow`: the flow `exp (t A)` of a bounded linear operator.
* `LinearMap.IsSymmetric.eigenvectorBasis_repr_flow_neg_apply`: the coordinate formula for the
  flow of a negative symmetric operator in its ordered eigenbasis.
* `LinearMap.IsSymmetric.stableSet_flow_eq_negativeSpectralSubspace`: the stable set of zero
  for `exp (t T)` is the negative spectral subspace of `T`.
* `LinearMap.IsSymmetric.unstableSet_flow_eq_positiveSpectralSubspace`: the corresponding
  backward-time statement.

## References

M. Audin and M. Damian, *Morse Theory and Floer Homology*, Springer Universitext, 2014,
Chapter 2.
-/

public section

open Filter NormedSpace Set Topology
open scoped InnerProductSpace

noncomputable section

namespace ContinuousLinearMap

variable {X : Type*} [NormedAddCommGroup X] [NormedSpace ℝ X] [CompleteSpace X]

/-- The linear flow generated by a bounded endomorphism `A`, whose time-`t` map is
`exp (t • A)`. -/
def flow (A : X →L[ℝ] X) : _root_.Flow ℝ X :=
  (EpsilonEridani.Semigroups.StronglyContinuousGroup.ofBounded A).toFlow

/-- The flow generated by `A` is the operator exponential `exp (t • A)`. -/
@[simp]
theorem flow_apply (A : X →L[ℝ] X) (t : ℝ) (x : X) :
    A.flow t x = exp (t • A) x := by
  rw [flow, EpsilonEridani.Semigroups.StronglyContinuousGroup.toFlow_apply,
    EpsilonEridani.Semigroups.StronglyContinuousGroup.ofBounded_apply]

/-- Negating the generator reverses its linear flow. -/
@[simp]
theorem flow_neg (A : X →L[ℝ] X) : (-A).flow = A.flow.reverse := by
  apply _root_.Flow.ext
  intro t x
  rw [_root_.Flow.reverse_apply, flow_apply, flow_apply, smul_neg, neg_smul]

end ContinuousLinearMap

namespace ContinuousLinearMap

variable {X : Type*} [NormedAddCommGroup X] [NormedSpace ℝ X]

/-- Combine an exponential-flow estimate with a comparison of the initial-vector norms,
enlarging the latter estimate's constant from `M` to `K`. -/
theorem norm_exp_smul_apply_le_mul_norm_of_le {A : X →L[ℝ] X} {t c M K : ℝ} {w v : X}
    (hflow : ‖exp (t • A) w‖ ≤ c * ‖w‖) (hop : ‖w‖ ≤ M * ‖v‖)
    (hc : 0 ≤ c) (hMK : M ≤ K) :
    ‖exp (t • A) w‖ ≤ K * c * ‖v‖ := by
  calc
    ‖exp (t • A) w‖ ≤ c * ‖w‖ := hflow
    _ ≤ c * (M * ‖v‖) := mul_le_mul_of_nonneg_left hop hc
    _ = c * M * ‖v‖ := by ring
    _ ≤ c * K * ‖v‖ := by gcongr
    _ = K * c * ‖v‖ := by ring

end ContinuousLinearMap

namespace LinearMap.IsSymmetric

variable {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
  [FiniteDimensional ℝ E] {n : ℕ} {T : E →L[ℝ] E}

private theorem flow_neg_apply_eq_sum (hT : (T : E →ₗ[ℝ] E).IsSymmetric)
    (hn : Module.finrank ℝ E = n) (t : ℝ) (v : E) :
    (-T).flow t v = ∑ i, (Real.exp (-(t * hT.eigenvalues hn i)) *
      (hT.eigenvectorBasis hn).toBasis.repr v i) • hT.eigenvectorBasis hn i := by
  conv_lhs => rw [← (hT.eigenvectorBasis hn).toBasis.sum_repr v]
  rw [ContinuousLinearMap.flow_apply, map_sum]
  refine Finset.sum_congr rfl fun i _ ↦ ?_
  have hi : (-T) (hT.eigenvectorBasis hn i) =
      (-hT.eigenvalues hn i) • hT.eigenvectorBasis hn i := by
    have hi' : T (hT.eigenvectorBasis hn i) =
        hT.eigenvalues hn i • hT.eigenvectorBasis hn i :=
      hT.apply_eigenvectorBasis hn i
    simpa using congrArg (fun w : E ↦ -w) hi'
  rw [OrthonormalBasis.coe_toBasis, map_smul,
    ContinuousLinearMap.exp_smul_apply_of_apply_eq_smul (-T) hi t, ← Real.exp_eq_exp_ℝ]
  simp only [mul_neg, smul_smul]
  rw [mul_comm ((hT.eigenvectorBasis hn).toBasis.repr v i)]

/-- In an ordered orthonormal eigenbasis, the flow generated by `-T` multiplies the
`i`th coordinate by `exp (-t * λᵢ)`. -/
theorem eigenvectorBasis_repr_flow_neg_apply (hT : (T : E →ₗ[ℝ] E).IsSymmetric)
    (hn : Module.finrank ℝ E = n) (t : ℝ) (v : E) (i : Fin n) :
    (hT.eigenvectorBasis hn).toBasis.repr ((-T).flow t v) i =
      Real.exp (-(t * hT.eigenvalues hn i)) *
        (hT.eigenvectorBasis hn).toBasis.repr v i := by
  rw [flow_neg_apply_eq_sum hT hn t v, map_sum]
  simp

/-- The orbit of `v` under the flow of `-T`, reparametrised by the linear time change
`t ↦ s * t`, converges to zero in forward time exactly when every eigencoordinate of `v` that
is present has `0 < s * λ`. Taking `s = 1` and `s = -1` gives the forward- and backward-time
characterizations. -/
private theorem tendsto_flow_neg_mul_atTop_iff (hT : (T : E →ₗ[ℝ] E).IsSymmetric)
    (hn : Module.finrank ℝ E = n) (s : ℝ) (v : E) :
    Tendsto (fun t : ℝ ↦ (-T).flow (s * t) v) atTop (𝓝 0) ↔
      ∀ i ∈ ((hT.eigenvectorBasis hn).toBasis.repr v).support,
        0 < s * hT.eigenvalues hn i := by
  let b := (hT.eigenvectorBasis hn).toBasis
  constructor
  · intro hlim i hi
    have hcoord : Tendsto (fun t : ℝ ↦ b.repr ((-T).flow (s * t) v) i) atTop (𝓝 0) := by
      have hc : Continuous fun w : E ↦ b.repr w i :=
        (b.coord i).toContinuousLinearMap.continuous
      simpa [Function.comp_def] using
        (hc.tendsto 0).comp hlim
    have hcoord' : Tendsto (fun t : ℝ ↦
        Real.exp (-(s * t * hT.eigenvalues hn i)) * b.repr v i) atTop (𝓝 0) := by
      simpa only [b, eigenvectorBasis_repr_flow_neg_apply hT hn] using hcoord
    have hcoeff : b.repr v i ≠ 0 := Finsupp.mem_support_iff.mp hi
    by_contra hnot
    have hnonpos : s * hT.eigenvalues hn i ≤ 0 := le_of_not_gt hnot
    have hbound : ∀ᶠ t in atTop, |b.repr v i| ≤
        |Real.exp (-(s * t * hT.eigenvalues hn i)) * b.repr v i| := by
      filter_upwards [eventually_ge_atTop (0 : ℝ)] with t ht
      rw [abs_mul, Real.abs_exp]
      refine le_mul_of_one_le_left (abs_nonneg _) (Real.one_le_exp (neg_nonneg.mpr ?_))
      calc s * t * hT.eigenvalues hn i
          = t * (s * hT.eigenvalues hn i) := by ring
        _ ≤ 0 := mul_nonpos_of_nonneg_of_nonpos ht hnonpos
    have hzero : Tendsto (fun _ : ℝ ↦ |b.repr v i|) atTop (𝓝 0) :=
      squeeze_zero' (Eventually.of_forall fun _ ↦ abs_nonneg _) hbound (by
        simpa only [abs_zero] using hcoord'.abs)
    exact hcoeff (abs_eq_zero.mp (tendsto_nhds_unique tendsto_const_nhds hzero))
  · intro hsupp
    have hterm (i : Fin n) : Tendsto (fun t : ℝ ↦
        (Real.exp (-(s * t * hT.eigenvalues hn i)) * b.repr v i) •
          hT.eigenvectorBasis hn i) atTop (𝓝 0) := by
      by_cases hi : b.repr v i = 0
      · simp [hi]
      · have hpos : 0 < s * hT.eigenvalues hn i :=
          hsupp i (Finsupp.mem_support_iff.mpr hi)
        have harg : Tendsto (fun t : ℝ ↦ -(s * t * hT.eigenvalues hn i)) atTop atBot := by
          convert tendsto_id.const_mul_atTop_of_neg (neg_lt_zero.mpr hpos) using 1
          funext t
          simp only [id_eq]
          ring
        have hexp : Tendsto (fun t : ℝ ↦ Real.exp (-(s * t * hT.eigenvalues hn i)))
            atTop (𝓝 0) := Real.tendsto_exp_atBot.comp harg
        simpa [b, mul_comm] using (hexp.const_mul (b.repr v i)).smul_const
          (hT.eigenvectorBasis hn i)
    have hsum : Tendsto (fun t : ℝ ↦ ∑ i, (Real.exp (-(s * t * hT.eigenvalues hn i)) *
        b.repr v i) • hT.eigenvectorBasis hn i) atTop (𝓝 0) := by
      simpa only [Finset.sum_const_zero] using
        tendsto_finsetSum Finset.univ fun i _ ↦ hterm i
    simpa only [flow_neg_apply_eq_sum hT hn] using hsum

private theorem tendsto_flow_neg_atTop_iff (hT : (T : E →ₗ[ℝ] E).IsSymmetric)
    (hn : Module.finrank ℝ E = n) (v : E) :
    Tendsto (fun t : ℝ ↦ (-T).flow t v) atTop (𝓝 0) ↔
      ∀ i ∈ ((hT.eigenvectorBasis hn).toBasis.repr v).support,
        0 < hT.eigenvalues hn i := by
  simpa only [one_mul] using tendsto_flow_neg_mul_atTop_iff hT hn 1 v

private theorem tendsto_flow_neg_atBot_iff (hT : (T : E →ₗ[ℝ] E).IsSymmetric)
    (hn : Module.finrank ℝ E = n) (v : E) :
    Tendsto (fun t : ℝ ↦ (-T).flow t v) atBot (𝓝 0) ↔
      ∀ i ∈ ((hT.eigenvectorBasis hn).toBasis.repr v).support,
        hT.eigenvalues hn i < 0 := by
  have h := tendsto_flow_neg_mul_atTop_iff hT hn (-1) v
  simp only [neg_mul, one_mul, neg_pos] at h
  rw [← h]
  constructor
  · intro hlim
    simpa only [Function.comp_def] using hlim.comp tendsto_neg_atTop_atBot
  · intro hlim
    simpa only [Function.comp_def, neg_neg] using hlim.comp tendsto_neg_atBot_atTop

/-- For a finite-dimensional symmetric operator `T`, the stable set of zero under the linear
flow generated by `T` is exactly the negative spectral subspace of `T`. -/
@[simp]
theorem stableSet_flow_eq_negativeSpectralSubspace
    (hT : (T : E →ₗ[ℝ] E).IsSymmetric) (hn : Module.finrank ℝ E = n) :
    _root_.Flow.stableSet T.flow 0 =
      LinearMap.IsSymmetric.negativeSpectralSubspace hT hn := by
  rw [← _root_.Flow.unstableSet_reverse, ← ContinuousLinearMap.flow_neg]
  ext v
  rw [_root_.Flow.mem_unstableSet]
  exact (tendsto_flow_neg_atBot_iff hT hn v).trans
    (LinearMap.IsSymmetric.mem_negativeSpectralSubspace_iff hT hn).symm

/-- For a finite-dimensional symmetric operator `T`, the unstable set of zero under the linear
flow generated by `T` is exactly the positive spectral subspace of `T`. -/
@[simp]
theorem unstableSet_flow_eq_positiveSpectralSubspace
    (hT : (T : E →ₗ[ℝ] E).IsSymmetric) (hn : Module.finrank ℝ E = n) :
    _root_.Flow.unstableSet T.flow 0 =
      LinearMap.IsSymmetric.positiveSpectralSubspace hT hn := by
  rw [← _root_.Flow.stableSet_reverse, ← ContinuousLinearMap.flow_neg]
  ext v
  rw [_root_.Flow.mem_stableSet]
  exact (tendsto_flow_neg_atTop_iff hT hn v).trans
    (LinearMap.IsSymmetric.mem_positiveSpectralSubspace_iff hT hn).symm

end LinearMap.IsSymmetric

end
