/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.GroupTheory.OrderOfElement
public import Mathlib.GroupTheory.PresentedGroup
public import Mathlib.Data.Fin.VecNotation
import Mathlib.Tactic.FinCases

/-!
# The oriented triangle groups

For natural numbers `a b c`, the (oriented, von Dyck) triangle group `Δ(a, b, c)` is the group
presented by three generators `x, y, z` subject to

`x ^ a = 1`, `y ^ b = 1`, `z ^ c = 1`, `z * y * x = 1`.

The product relator is written in the display order `z * y * x`, the same order as the relation
`σinf * σ1 * σ0 = 1` of `EpsilonEridani.PermutationTriple`. By the universal property
`EpsilonEridani.TriangleGroup.lift`, a permutation triple whose components have orders dividing `a`, `b`,
`c` therefore determines a homomorphism `Δ(a, b, c) →* Equiv.Perm (Fin n)` sending `x, y, z` to
`σ0, σ1, σinf`; these finite permutation representations are how triangle groups enter the
combinatorics of three-point covers.

The presentation is taken as the definition. No identification with a group of isometries of the
sphere, the Euclidean plane or the hyperbolic plane is made here.

A parameter `0` is allowed: the relator `x ^ 0 = 1` is trivial, so it imposes no condition on the
corresponding generator. In particular `Δ(0, 0, 0)` is free of rank **two**, not three, because the
product relator determines `z` from `x` and `y` (`EpsilonEridani.TriangleGroup.equivFreeGroup`).

## Main definitions

* `EpsilonEridani.triangleRelators a b c`: the four relators, in `FreeGroup (Fin 3)`.
* `EpsilonEridani.TriangleGroup a b c`: the presented group.
* `EpsilonEridani.TriangleGroup.x`, `EpsilonEridani.TriangleGroup.y`, `EpsilonEridani.TriangleGroup.z`: the three
  distinguished generators.
* `EpsilonEridani.TriangleGroup.lift`: the universal property, and `EpsilonEridani.TriangleGroup.homEquiv`, the
  bijection between homomorphisms out of `Δ(a, b, c)` and triples of elements satisfying the
  relations.
* `EpsilonEridani.TriangleGroup.rotate`: the isomorphism `Δ(a, b, c) ≃* Δ(b, c, a)` rotating the
  generators.
* `EpsilonEridani.twoGeneratorTriangleRelators` and `EpsilonEridani.TriangleGroup.equivTwoGenerator`: the
  isomorphism with the two-generator presentation `⟨x, y | x ^ a, y ^ b, (y * x) ^ c⟩`.
* `EpsilonEridani.TriangleGroup.equivFreeGroup`: `Δ(0, 0, 0)` is the free group on two generators.

## Main results

* `EpsilonEridani.TriangleGroup.z_eq`: the third generator is `(y * x)⁻¹`.
* `EpsilonEridani.TriangleGroup.closure_x_y`: the generators `x` and `y` alone generate `Δ(a, b, c)`.
* `EpsilonEridani.TriangleGroup.hom_ext`: a homomorphism out of `Δ(a, b, c)` is determined by its values
  on `x` and `y`.
* `EpsilonEridani.TriangleGroup.range_eq_closure`: the range of a homomorphism out of `Δ(a, b, c)` is
  generated by the images of `x` and `y`.

## References

* E. Girondo, G. González-Diez, *Introduction to Compact Riemann Surfaces and Dessins d'Enfants*,
  LMS Student Texts 79, Cambridge University Press, 2012, Definition 2.28 and the presentation
  following it.
* S. K. Lando, A. K. Zvonkin, *Graphs on Surfaces and Their Applications*, Encyclopaedia of
  Mathematical Sciences 141, Springer, 2004.
-/

public section

namespace EpsilonEridani

open FreeGroup (of)

/-- The relators of the `(a, b, c)` triangle group in `FreeGroup (Fin 3)`: the powers
`of 0 ^ a`, `of 1 ^ b`, `of 2 ^ c` and the product relator `of 2 * of 1 * of 0`. -/
def triangleRelators (a b c : ℕ) : Set (FreeGroup (Fin 3)) :=
  {of 0 ^ a, of 1 ^ b, of 2 ^ c, of 2 * of 1 * of 0}

/-- The oriented triangle group `Δ(a, b, c) = ⟨x, y, z | x ^ a, y ^ b, z ^ c, z * y * x⟩`. -/
abbrev TriangleGroup (a b c : ℕ) : Type := PresentedGroup (triangleRelators a b c)

/-- The relators of the two-generator presentation `⟨x, y | x ^ a, y ^ b, (y * x) ^ c⟩` of the
triangle group, in `FreeGroup (Fin 2)`. -/
def twoGeneratorTriangleRelators (a b c : ℕ) : Set (FreeGroup (Fin 2)) :=
  {of 0 ^ a, of 1 ^ b, (of 1 * of 0) ^ c}

namespace TriangleGroup

variable (a b c : ℕ) {G : Type*} [Group G]

/-- The first distinguished generator of `Δ(a, b, c)`, of order dividing `a`. -/
def x : TriangleGroup a b c := PresentedGroup.of 0

/-- The second distinguished generator of `Δ(a, b, c)`, of order dividing `b`. -/
def y : TriangleGroup a b c := PresentedGroup.of 1

/-- The third distinguished generator of `Δ(a, b, c)`, of order dividing `c`; it equals
`(y * x)⁻¹` (`EpsilonEridani.TriangleGroup.z_eq`). -/
def z : TriangleGroup a b c := PresentedGroup.of 2

/-- The first distinguished generator satisfies the first power relation. -/
@[simp]
theorem x_pow : x a b c ^ a = 1 := by
  rw [x, PresentedGroup.of, ← map_pow]
  exact PresentedGroup.one_of_mem (by simp [triangleRelators])

/-- The second distinguished generator satisfies the second power relation. -/
@[simp]
theorem y_pow : y a b c ^ b = 1 := by
  rw [y, PresentedGroup.of, ← map_pow]
  exact PresentedGroup.one_of_mem (by simp [triangleRelators])

/-- The third distinguished generator satisfies the third power relation. -/
@[simp]
theorem z_pow : z a b c ^ c = 1 := by
  rw [z, PresentedGroup.of, ← map_pow]
  exact PresentedGroup.one_of_mem (by simp [triangleRelators])

/-- The product relation of `Δ(a, b, c)`, in the display order of the presentation. -/
@[simp]
theorem z_mul_y_mul_x : z a b c * y a b c * x a b c = 1 := by
  simp only [x, y, z, PresentedGroup.of]
  rw [← map_mul, ← map_mul]
  exact PresentedGroup.one_of_mem (by simp [triangleRelators])

/-- The third generator is determined by the first two. -/
theorem z_eq : z a b c = (y a b c * x a b c)⁻¹ :=
  eq_inv_of_mul_eq_one_left (by rw [← mul_assoc, z_mul_y_mul_x])

/-- The product `y * x` has order dividing `c`. -/
@[simp]
theorem y_mul_x_pow : (y a b c * x a b c) ^ c = 1 := by
  rw [← inv_inj, ← inv_pow, ← z_eq, z_pow, inv_one]

/-- The order of the first distinguished generator divides `a`. -/
theorem orderOf_x_dvd : orderOf (x a b c) ∣ a := orderOf_dvd_of_pow_eq_one (x_pow a b c)

/-- The order of the second distinguished generator divides `b`. -/
theorem orderOf_y_dvd : orderOf (y a b c) ∣ b := orderOf_dvd_of_pow_eq_one (y_pow a b c)

/-- The order of the third distinguished generator divides `c`. -/
theorem orderOf_z_dvd : orderOf (z a b c) ∣ c := orderOf_dvd_of_pow_eq_one (z_pow a b c)

/-- The generators `x` and `y` alone generate `Δ(a, b, c)`. -/
@[simp]
theorem closure_x_y : Subgroup.closure {x a b c, y a b c} = ⊤ := by
  refine eq_top_iff.2 fun g _ ↦ PresentedGroup.generated_by _ _ (fun j ↦ ?_) g
  have hx : x a b c ∈ Subgroup.closure {x a b c, y a b c} :=
    Subgroup.subset_closure (Set.mem_insert _ _)
  have hy : y a b c ∈ Subgroup.closure {x a b c, y a b c} :=
    Subgroup.subset_closure (Set.mem_insert_of_mem _ rfl)
  fin_cases j
  · exact hx
  · exact hy
  · -- `PresentedGroup.of 2` is `z` by definition
    exact (z_eq a b c ▸ inv_mem (mul_mem hy hx) : z a b c ∈ Subgroup.closure {x a b c, y a b c})

/-- A homomorphism out of `Δ(a, b, c)` is determined by its values on `x` and `y`. -/
@[ext]
theorem hom_ext {f g : TriangleGroup a b c →* G} (hx : f (x a b c) = g (x a b c))
    (hy : f (y a b c) = g (y a b c)) : f = g := by
  refine PresentedGroup.ext fun j ↦ ?_
  fin_cases j
  · exact hx
  · exact hy
  · -- `PresentedGroup.of 2` is `z` by definition
    exact (by simp only [z_eq, map_inv, map_mul, hx, hy] : f (z a b c) = g (z a b c))

/-- The range of a homomorphism out of `Δ(a, b, c)` is generated by the images of `x` and `y`. -/
theorem range_eq_closure (f : TriangleGroup a b c →* G) :
    f.range = Subgroup.closure {f (x a b c), f (y a b c)} := by
  rw [MonoidHom.range_eq_map, ← closure_x_y, MonoidHom.map_closure, Set.image_pair]

variable {a b c}

/-- **The universal property of the triangle group.** Elements `p q r` of a group with
`p ^ a = 1`, `q ^ b = 1`, `r ^ c = 1` and `r * q * p = 1` define a homomorphism out of `Δ(a, b, c)`
sending `x, y, z` to `p, q, r`. -/
def lift (p q r : G) (hp : p ^ a = 1) (hq : q ^ b = 1) (hr : r ^ c = 1) (h : r * q * p = 1) :
    TriangleGroup a b c →* G :=
  PresentedGroup.toGroup (f := ![p, q, r]) <| by
    rintro _ (rfl | rfl | rfl | rfl) <;> simp [hp, hq, hr, h]

@[simp]
theorem lift_x (p q r : G) (hp : p ^ a = 1) (hq : q ^ b = 1) (hr : r ^ c = 1)
    (h : r * q * p = 1) : lift p q r hp hq hr h (x a b c) = p :=
  PresentedGroup.toGroup.of _

@[simp]
theorem lift_y (p q r : G) (hp : p ^ a = 1) (hq : q ^ b = 1) (hr : r ^ c = 1)
    (h : r * q * p = 1) : lift p q r hp hq hr h (y a b c) = q :=
  PresentedGroup.toGroup.of _

@[simp]
theorem lift_z (p q r : G) (hp : p ^ a = 1) (hq : q ^ b = 1) (hr : r ^ c = 1)
    (h : r * q * p = 1) : lift p q r hp hq hr h (z a b c) = r :=
  PresentedGroup.toGroup.of _

/-- Homomorphisms `Δ(a, b, c) →* G` correspond to triples `(p, q, r)` of elements of `G` with
`p ^ a = 1`, `q ^ b = 1`, `r ^ c = 1` and `r * q * p = 1`, by evaluation at `(x, y, z)`. -/
def homEquiv :
    (TriangleGroup a b c →* G) ≃
      {g : G × G × G // g.1 ^ a = 1 ∧ g.2.1 ^ b = 1 ∧ g.2.2 ^ c = 1 ∧ g.2.2 * g.2.1 * g.1 = 1} where
  toFun f := ⟨(f (x a b c), f (y a b c), f (z a b c)), by
    simp only [← map_pow, ← map_mul, x_pow, y_pow, z_pow, z_mul_y_mul_x, map_one, and_self]⟩
  invFun g := lift g.1.1 g.1.2.1 g.1.2.2 g.2.1 g.2.2.1 g.2.2.2.1 g.2.2.2.2
  left_inv f := by ext <;> simp
  right_inv g := by ext <;> simp

@[simp]
theorem homEquiv_apply (f : TriangleGroup a b c →* G) :
    (homEquiv f : G × G × G) = (f (x a b c), f (y a b c), f (z a b c)) := (rfl)

@[simp]
theorem homEquiv_symm_apply
    (g : {g : G × G × G // g.1 ^ a = 1 ∧ g.2.1 ^ b = 1 ∧ g.2.2 ^ c = 1 ∧
      g.2.2 * g.2.1 * g.1 = 1}) :
    homEquiv.symm g = lift g.1.1 g.1.2.1 g.1.2.2 g.2.1 g.2.2.1 g.2.2.2.1 g.2.2.2.2 := (rfl)

/-- The rotation isomorphism `Δ(a, b, c) ≃* Δ(b, c, a)`, sending `x, y, z` to the generators
`z, x, y` of `Δ(b, c, a)`. The product relator `z * y * x` of the source becomes the cyclic
rotation `y * x * z` of the product relator of the target. -/
def rotate : TriangleGroup a b c ≃* TriangleGroup b c a :=
  MonoidHom.toMulEquiv
    (lift (z b c a) (x b c a) (y b c a) (z_pow b c a) (x_pow b c a) (y_pow b c a)
      (by simp [z_eq]))
    (lift (y a b c) (z a b c) (x a b c) (y_pow a b c) (z_pow a b c) (x_pow a b c)
      (by simp [z_eq]))
    (by ext <;> simp)
    (by ext <;> simp)

@[simp]
theorem rotate_x : rotate (x a b c) = z b c a := by
  simp [rotate]

@[simp]
theorem rotate_y : rotate (y a b c) = x b c a := by
  simp [rotate]

@[simp]
theorem rotate_z : rotate (z a b c) = y b c a := by
  simp [rotate]

@[simp]
theorem rotate_symm_x : rotate.symm (x b c a) = y a b c := by
  simp [rotate]

@[simp]
theorem rotate_symm_y : rotate.symm (y b c a) = z a b c := by
  simp [rotate]

@[simp]
theorem rotate_symm_z : rotate.symm (z b c a) = x a b c := by
  simp [rotate]

/-- The first generator in the two-generator presentation satisfies its power relation. -/
@[simp]
theorem twoGenerator_of_zero_pow :
    (PresentedGroup.of 0 : PresentedGroup (twoGeneratorTriangleRelators a b c)) ^ a = 1 := by
  rw [PresentedGroup.of, ← map_pow]
  exact PresentedGroup.one_of_mem (by simp [twoGeneratorTriangleRelators])

/-- The second generator in the two-generator presentation satisfies its power relation. -/
@[simp]
theorem twoGenerator_of_one_pow :
    (PresentedGroup.of 1 : PresentedGroup (twoGeneratorTriangleRelators a b c)) ^ b = 1 := by
  rw [PresentedGroup.of, ← map_pow]
  exact PresentedGroup.one_of_mem (by simp [twoGeneratorTriangleRelators])

/-- The product of the second and first generators in the two-generator presentation satisfies
its power relation. -/
@[simp]
theorem twoGenerator_mul_pow :
    ((PresentedGroup.of 1 : PresentedGroup (twoGeneratorTriangleRelators a b c)) *
      PresentedGroup.of 0) ^ c = 1 := by
  rw [PresentedGroup.of, PresentedGroup.of, ← map_mul, ← map_pow]
  exact PresentedGroup.one_of_mem (by simp [twoGeneratorTriangleRelators])

/-- The isomorphism of `Δ(a, b, c)` with the two-generator presentation
`⟨x, y | x ^ a, y ^ b, (y * x) ^ c⟩` obtained by eliminating `z = (y * x)⁻¹`. -/
def equivTwoGenerator :
    TriangleGroup a b c ≃* PresentedGroup (twoGeneratorTriangleRelators a b c) :=
  MonoidHom.toMulEquiv
    (lift (PresentedGroup.of 0) (PresentedGroup.of 1) (PresentedGroup.of 1 * PresentedGroup.of 0)⁻¹
      twoGenerator_of_zero_pow twoGenerator_of_one_pow
      (by rw [inv_pow, inv_eq_one, twoGenerator_mul_pow])
      (by rw [mul_assoc, inv_mul_cancel]))
    (PresentedGroup.toGroup (f := ![x a b c, y a b c]) <| by
      rintro _ (rfl | rfl | rfl) <;> simp)
    (by ext <;> simp [PresentedGroup.toGroup.of])
    (by
      refine PresentedGroup.ext fun j ↦ ?_
      fin_cases j <;> simp [PresentedGroup.toGroup.of])

@[simp]
theorem equivTwoGenerator_x : equivTwoGenerator (x a b c) = PresentedGroup.of 0 := by
  simp [equivTwoGenerator]

@[simp]
theorem equivTwoGenerator_y : equivTwoGenerator (y a b c) = PresentedGroup.of 1 := by
  simp [equivTwoGenerator]

@[simp]
theorem equivTwoGenerator_z :
    equivTwoGenerator (z a b c) = (PresentedGroup.of 1 * PresentedGroup.of 0)⁻¹ := by
  simp [equivTwoGenerator]

@[simp]
theorem equivTwoGenerator_symm_of_zero :
    (equivTwoGenerator (a := a) (b := b) (c := c)).symm (PresentedGroup.of 0) = x a b c := by
  simp [equivTwoGenerator]

@[simp]
theorem equivTwoGenerator_symm_of_one :
    (equivTwoGenerator (a := a) (b := b) (c := c)).symm (PresentedGroup.of 1) = y a b c := by
  simp [equivTwoGenerator]

/-- The triangle group `Δ(0, 0, 0)` is the free group on the two generators `x` and `y`: every
power relator is trivial, and the product relator only determines `z = (y * x)⁻¹`. -/
def equivFreeGroup : TriangleGroup 0 0 0 ≃* FreeGroup (Fin 2) :=
  MonoidHom.toMulEquiv
    (lift (of 0) (of 1) (of 1 * of 0)⁻¹ (pow_zero _) (pow_zero _) (pow_zero _)
      (by rw [mul_assoc, inv_mul_cancel]))
    (FreeGroup.lift ![x 0 0 0, y 0 0 0])
    (by ext <;> simp)
    (FreeGroup.ext_hom _ _ fun j ↦ by fin_cases j <;> simp)

@[simp]
theorem equivFreeGroup_x : equivFreeGroup (x 0 0 0) = of 0 := by
  simp [equivFreeGroup]

@[simp]
theorem equivFreeGroup_y : equivFreeGroup (y 0 0 0) = of 1 := by
  simp [equivFreeGroup]

@[simp]
theorem equivFreeGroup_z : equivFreeGroup (z 0 0 0) = (of 1 * of 0)⁻¹ := by
  simp [equivFreeGroup]

@[simp]
theorem equivFreeGroup_symm_of_zero : equivFreeGroup.symm (of 0) = x 0 0 0 := by
  simp [equivFreeGroup]

@[simp]
theorem equivFreeGroup_symm_of_one : equivFreeGroup.symm (of 1) = y 0 0 0 := by
  simp [equivFreeGroup]

end TriangleGroup

end EpsilonEridani
