/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.RepresentationTheory.Quiver.Acyclic.PathAlgebra
public import EpsilonEridani.RepresentationTheory.Quiver.Radical
public import EpsilonEridani.RepresentationTheory.Quiver.Zigzag.Relations

import EpsilonEridani.RepresentationTheory.Quiver.Zigzag.Admissible

/-!
# Arrow-ideal presentations of zigzag relation quotients

For a simple graph in which every vertex has at most one neighbour, every quadratic zigzag
relator vanishes. The uniform zigzag relation ideal is therefore generated by paths of length at
least three, and equals the cube of the arrow ideal. This file packages that presentation and
shows that, when the graph has an edge, omitting the cubic paths gives an algebra which is not a
finitely generated module.

## Main definitions

* `EpsilonEridani.nonisolatedZigzagQuotientEquivArrowIdealPowThree`: when every vertex has at most one
  neighbour, the zigzag relation quotient is the path algebra modulo the cube of the arrow ideal.

## Main results

* `EpsilonEridani.IsQuadraticZigzagRelator.eq_zero`, `EpsilonEridani.quadraticZigzagIdeal_eq_bot`: when every
  vertex has at most one neighbour, the quadratic relators vanish.
* `EpsilonEridani.asIdeal_zigzagIdeal_eq_arrowIdeal_pow_three`: when every vertex has at most one
  neighbour, the zigzag relation ideal is the cube of the arrow ideal.
* `EpsilonEridani.not_module_finite_quotient_quadraticZigzagIdeal`: when such a graph has an edge, the
  quadratic presentation is not a finitely generated module.
-/

public section

namespace EpsilonEridani

open PathAlgebra DoubledQuiver

universe u w

/-! ### Graphs whose vertices have at most one neighbour -/

section AtMostOneNeighbour

variable (k : Type w) [CommRing k] {V : Type u} {G : SimpleGraph V}

/-- **When every vertex has at most one neighbour, every quadratic zigzag relator is zero.** A
length-two path through a vertex with a single neighbour returns to its source, and the
backtracks at a vertex with a single neighbour all coincide. -/
theorem IsQuadraticZigzagRelator.eq_zero (hG : ∀ i, (G.neighborSet i).Subsingleton)
    {x : pathAlgebra k (DoubledQuiver G)} (hx : IsQuadraticZigzagRelator k G x) : x = 0 := by
  cases hx with
  | @nonreturn i l p length_eq different_endpoints =>
    obtain ⟨a, rfl⟩ : ∃ a, i = vertex G a :=
      ⟨(vertexEquiv G).symm i, (vertexEquiv_symm_apply G i).symm⟩
    obtain ⟨b, rfl⟩ : ∃ b, l = vertex G b :=
      ⟨(vertexEquiv G).symm l, (vertexEquiv_symm_apply G l).symm⟩
    obtain ⟨m, h, h', -⟩ := exists_eq_comp_arrowPath G p length_eq
    exact absurd (congrArg (vertex G) (hG m h.symm h')) different_endpoints
  | @equal_backtracks i p q p_length q_length =>
    obtain ⟨a, rfl⟩ : ∃ a, i = vertex G a :=
      ⟨(vertexEquiv G).symm i, (vertexEquiv_symm_apply G i).symm⟩
    obtain ⟨j, h, rfl⟩ := exists_eq_backtrackPath G p p_length
    obtain ⟨j', h', rfl⟩ := exists_eq_backtrackPath G q q_length
    obtain rfl : j = j' := hG _ h h'
    exact sub_self _

/-- **When every vertex has at most one neighbour, the quadratic zigzag ideal is zero.** -/
theorem quadraticZigzagIdeal_eq_bot (hG : ∀ i, (G.neighborSet i).Subsingleton) :
    quadraticZigzagIdeal k G = ⊥ := by
  rw [quadraticZigzagIdeal_eq_span, eq_bot_iff, TwoSidedIdeal.span_le]
  intro x hx
  rw [SetLike.mem_coe, TwoSidedIdeal.mem_bot]
  exact hx.eq_zero k hG

/-- **When every vertex has at most one neighbour, the zigzag relation ideal is the cube of the
arrow ideal**: the uniform relators reduce to the paths of length at least three, which span that
cube. -/
theorem asIdeal_zigzagIdeal_eq_arrowIdeal_pow_three [Finite V]
    (hG : ∀ i, (G.neighborSet i).Subsingleton) :
    (zigzagIdeal k G).asIdeal = arrowIdeal k (DoubledQuiver G) ^ 3 := by
  refine zigzagIdeal_eq_arrowIdeal_pow_three k G fun _ hx => ?_
  exact hx.eq_zero k hG ▸ zero_mem _

/-- **The arrow-ideal-cube presentation.** When every vertex has at most one neighbour, the
zigzag relation quotient is the path algebra of the doubled quiver modulo the cube of its arrow
ideal. -/
noncomputable def nonisolatedZigzagQuotientEquivArrowIdealPowThree [Finite V]
    (hG : ∀ i, (G.neighborSet i).Subsingleton) :
    nonisolatedZigzagQuotient k G ≃ₐ[k]
      pathAlgebra k (DoubledQuiver G) ⧸ arrowIdeal k (DoubledQuiver G) ^ 3 :=
  Ideal.quotientEquivAlgOfEq k (asIdeal_zigzagIdeal_eq_arrowIdeal_pow_three k hG)

/-- The arrow-ideal-cube presentation sends the class of a path-algebra element to its class. -/
@[simp]
theorem nonisolatedZigzagQuotientEquivArrowIdealPowThree_zigzagMk [Finite V]
    (hG : ∀ i, (G.neighborSet i).Subsingleton) (x : pathAlgebra k (DoubledQuiver G)) :
    nonisolatedZigzagQuotientEquivArrowIdealPowThree k hG (zigzagMk k G x) =
      Ideal.Quotient.mk (arrowIdeal k (DoubledQuiver G) ^ 3) x := by
  rw [nonisolatedZigzagQuotientEquivArrowIdealPowThree, zigzagMk_apply,
    Ideal.quotientEquivAlgOfEq_mk]

/-- The inverse of the arrow-ideal-cube presentation sends the class of a path-algebra element
to its class. -/
@[simp]
theorem nonisolatedZigzagQuotientEquivArrowIdealPowThree_symm_mk [Finite V]
    (hG : ∀ i, (G.neighborSet i).Subsingleton) (x : pathAlgebra k (DoubledQuiver G)) :
    (nonisolatedZigzagQuotientEquivArrowIdealPowThree k hG).symm
        (Ideal.Quotient.mk (arrowIdeal k (DoubledQuiver G) ^ 3) x) =
      zigzagMk k G x := by
  rw [AlgEquiv.symm_apply_eq, nonisolatedZigzagQuotientEquivArrowIdealPowThree_zigzagMk]

/-- **The quadratic presentation is infinite.** On a graph with an edge in which every vertex has
at most one neighbour, the quadratic relators vanish, so the quadratic quotient is the whole path
algebra of the doubled quiver. That algebra is not a finitely generated module, because the
backtrack along the edge is a closed path of positive length. -/
theorem not_module_finite_quotient_quadraticZigzagIdeal [Nontrivial k] [Finite V]
    (hG : ∀ i, (G.neighborSet i).Subsingleton) {i j : V} (h : G.Adj i j) :
    ¬Module.Finite k (pathAlgebra k (DoubledQuiver G) ⧸ (quadraticZigzagIdeal k G).asIdeal) := by
  intro hfin
  have hbot : (quadraticZigzagIdeal k G).asIdeal = ⊥ := by
    rw [quadraticZigzagIdeal_eq_bot k hG, TwoSidedIdeal.bot_asIdeal]
  have hacyclic := isAcyclic_of_module_finite_pathAlgebra k (DoubledQuiver G) <|
    Module.Finite.equiv
      ((Ideal.quotientEquivAlgOfEq k hbot).trans (AlgEquiv.quotientBot k _)).toLinearEquiv
  exact hacyclic.not_length_pos (backtrackPath G h) (by simp)

end AtMostOneNeighbour

end EpsilonEridani
