/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.RepresentationTheory.Quiver.Zigzag.Radical
public import EpsilonEridani.RingTheory.SimpleModule.Socle

/-!
# The socle and the top of a zigzag algebra

For a finite simple graph without isolated vertices over a field, the Jacobson radical of the
zigzag relation quotient is its positive-length part, its square is the span of the volume
classes, and its cube vanishes.  This file reads the two ends of that filtration as module
invariants: the **socle** of the algebra, viewed as a left module over itself, is the span of the
volume classes, and the **top** — the quotient by the radical — is the product of one copy of the
ground field for each vertex.  Both have dimension `|V|`.

The socle is computed as the square of the radical.  One containment is a nilpotence argument: a
simple submodule `m` is killed by the radical, since otherwise `J • m = m` forces `m = J³ • m = 0`,
and an element killed on the left by every arrow has no vertex and no arrow coordinate.  The other
containment needs the volume classes themselves to be simple, and that is where the multiplication
table enters: a left ideal absorbs an idempotent, an arrow and a volume class in only three ways,
and each of them sends the volume class at a vertex back into its own `k`-line.  So that line is a
left ideal of dimension one, hence a simple module.

The top is the first isomorphism theorem applied to the vertex-coefficient homomorphism, whose
kernel is the radical.  It exhibits the `|V|` simple modules of a zigzag algebra as the characters
reading a single vertex coordinate.

## Main declarations

* `EpsilonEridani.zigzagTopEquiv`: the top of a zigzag algebra is `k^V`, the vertex coefficients.

## Main results

* `EpsilonEridani.isSimpleModule_span_singleton_zigzagVolume`: the left ideal generated by a volume class
  is a simple module.
* `EpsilonEridani.socle_nonisolatedZigzagQuotient_eq_jacobson_sq` and
  `EpsilonEridani.restrictScalars_socle_nonisolatedZigzagQuotient_eq_zigzagVolumeSpan`: **the socle** is
  the square of the Jacobson radical, that is, the span of the volume classes.
* `EpsilonEridani.isSemisimpleRing_quotient_jacobson_nonisolatedZigzagQuotient`: **the top** is a
  semisimple ring.
* `EpsilonEridani.finrank_restrictScalars_socle_nonisolatedZigzagQuotient` and
  `EpsilonEridani.finrank_quotient_jacobson_nonisolatedZigzagQuotient`: socle and top both have dimension
  the number of vertices.
## References

This proves the socle and top part of the first clause of Layer 2 of
`EpsilonEridaniRoadmap/ZigzagPreprojective/README.md`, completing that clause alongside
`EpsilonEridani.RepresentationTheory.Quiver.Zigzag.Radical`.  See Huerfano--Khovanov, *A category for the
adjoint representation*, Section 3, and Ehrig--Tubbenhauer, *Algebraic properties of zigzag
algebras*, Section 2.
-/

public section

namespace EpsilonEridani

open PathAlgebra DoubledQuiver

universe u w

variable {V : Type u}

section CommRing

variable (k : Type w) [CommRing k] (G : SimpleGraph V) [Finite V]

/-- Left multiplication by any element carries a volume class into its own `k`-line: the
multiplication table sends it to itself, up to a scalar, or to zero. -/
theorem mul_zigzagVolume_mem_span_singleton (z : nonisolatedZigzagQuotient k G) (i : V) :
    z * zigzagVolume k G i ∈ Submodule.span k {zigzagVolume k G i} := by
  have hz : z ∈ Submodule.span k (Set.range (zigzagBasisFun k G)) := by
    rw [span_range_zigzagBasisFun_eq_top k G]
    trivial
  induction hz using Submodule.span_induction with
  | mem y hy =>
      obtain ⟨b, rfl⟩ := hy
      rcases b with j | d | j
      · rw [zigzagBasisFun_inl]
        rcases eq_or_ne j i with rfl | hji
        · rw [zigzagMk_vertexIdempotent_mul_zigzagVolume]
          exact Submodule.mem_span_singleton_self _
        · rw [zigzagMk_vertexIdempotent_mul_zigzagVolume_of_ne k G hji]
          exact Submodule.zero_mem _
      · rw [zigzagBasisFun_inr_inl, zigzagMk_ofArrow_mul_zigzagVolume]
        exact Submodule.zero_mem _
      · rw [zigzagBasisFun_inr_inr, zigzagVolume_mul_zigzagVolume]
        exact Submodule.zero_mem _
  | zero => rw [zero_mul]; exact Submodule.zero_mem _
  | add a b _ _ ha hb => rw [add_mul]; exact Submodule.add_mem _ ha hb
  | smul c a _ ha => rw [Algebra.smul_mul_assoc]; exact Submodule.smul_mem _ c ha

/-- The left ideal generated by a volume class is nothing but its `k`-line. -/
theorem restrictScalars_span_singleton_zigzagVolume (i : V) :
    (Submodule.span (nonisolatedZigzagQuotient k G) {zigzagVolume k G i}).restrictScalars k =
      Submodule.span k {zigzagVolume k G i} := by
  refine le_antisymm (fun y hy => ?_) ?_
  · rw [Submodule.restrictScalars_mem] at hy
    obtain ⟨z, rfl⟩ := Submodule.mem_span_singleton.1 hy
    rw [smul_eq_mul]
    exact mul_zigzagVolume_mem_span_singleton k G z i
  · rw [Submodule.span_le, Set.singleton_subset_iff, SetLike.mem_coe,
      Submodule.restrictScalars_mem]
    exact Submodule.mem_span_singleton_self _

variable {k G}

/-- An element killed on the left by every arrow is a combination of volume classes. -/
theorem mem_zigzagVolumeSpan_of_forall_zigzagMk_ofArrow_mul_eq_zero
    (hns : ∀ i : V, ∃ j, G.Adj i j) {x : nonisolatedZigzagQuotient k G}
    (hx : ∀ d : G.Dart, zigzagMk k G (ofArrow (arrow G d.adj)) * x = 0) :
    x ∈ zigzagVolumeSpan k G := by
  classical
  have hcoef : ∀ d : G.Dart,
      (zigzagBasis k G hns).repr x (.inl d.fst) = 0 ∧
        (zigzagBasis k G hns).repr x (.inr (.inl d.symm)) = 0 := by
    intro d
    have h0 := (zigzagMk_ofArrow_mul hns d x).symm.trans (hx d)
    have h1 := congrArg (fun z => (zigzagBasis k G hns).coord (.inr (.inl d)) z) h0
    have h2 := congrArg (fun z => (zigzagBasis k G hns).coord (.inr (.inr d.snd)) z) h0
    have hVolumeArrow : (Sum.inr (Sum.inr d.snd) : ZigzagBasisIndex G) ≠
        Sum.inr (Sum.inl d) := by simp
    have hArrowVolume : (Sum.inr (Sum.inl d) : ZigzagBasisIndex G) ≠
        Sum.inr (Sum.inr d.snd) := by simp
    simp only [map_add, map_smul, map_zero, smul_eq_mul] at h1 h2
    rw [zigzagBasis_coord_apply, ite_eq_left rfl, zigzagBasis_coord_apply,
      ite_eq_right hVolumeArrow,
      mul_one, mul_zero, add_zero] at h1
    rw [zigzagBasis_coord_apply, ite_eq_right hArrowVolume, zigzagBasis_coord_apply,
      ite_eq_left rfl, mul_zero, mul_one, zero_add] at h2
    exact ⟨by simpa only [Module.Basis.coord_apply] using h1,
      by simpa only [Module.Basis.coord_apply] using h2⟩
  rw [mem_zigzagVolumeSpan_iff hns]
  refine ⟨fun i => ?_, fun e => ?_⟩
  · obtain ⟨j, hij⟩ := hns i
    exact (hcoef ⟨(i, j), hij⟩).1
  · simpa using (hcoef e.symm).2

end CommRing

/-! ### The socle -/

section Field

variable (k : Type w) [Field k] (G : SimpleGraph V) [Finite V]

variable {k G}

/-- **The line spanned by a volume class is a simple left module.**  It is a one-dimensional
`k`-subspace by `EpsilonEridani.restrictScalars_span_singleton_zigzagVolume`, and a left ideal by
construction, so it has no proper nonzero submodule. -/
theorem isSimpleModule_span_singleton_zigzagVolume (i : V) (hi : ∃ j, G.Adj i j) :
    IsSimpleModule (nonisolatedZigzagQuotient k G)
      (Submodule.span (nonisolatedZigzagQuotient k G) {zigzagVolume k G i}) := by
  obtain ⟨j, hij⟩ := hi
  rw [isSimpleModule_iff_isAtom]
  refine ⟨fun hbot => zigzagVolume_ne_zero k G hij (Submodule.span_singleton_eq_bot.1 hbot), ?_⟩
  intro q hq
  by_contra hne
  obtain ⟨y, hyq, hy0⟩ := (Submodule.ne_bot_iff q).1 hne
  have hy : y ∈ Submodule.span k {zigzagVolume k G i} := by
    rw [← restrictScalars_span_singleton_zigzagVolume k G i]
    exact hq.le hyq
  obtain ⟨c, hc⟩ := Submodule.mem_span_singleton.1 hy
  have hc0 : c ≠ 0 := by
    rintro rfl
    exact hy0 (by simpa using hc.symm)
  have hv : zigzagVolume k G i ∈ q := by
    have hcv : (c⁻¹ : k) • y = zigzagVolume k G i := by
      rw [← hc, smul_smul, inv_mul_cancel₀ hc0, one_smul]
    rw [← hcv, ← algebraMap_smul (nonisolatedZigzagQuotient k G) c⁻¹ y]
    exact q.smul_mem _ hyq
  exact hq.ne (le_antisymm hq.le (by rwa [Submodule.span_le, Set.singleton_subset_iff]))

/-- Every volume class lies in the socle. -/
theorem zigzagVolume_mem_socle (i : V) (hi : ∃ j, G.Adj i j) :
    zigzagVolume k G i ∈
      socle (nonisolatedZigzagQuotient k G) (nonisolatedZigzagQuotient k G) :=
  le_socle (isSimpleModule_span_singleton_zigzagVolume i hi)
    (Submodule.mem_span_singleton_self _)

/-- **The socle of a zigzag algebra is the square of its Jacobson radical.**  Equivalently, by
`EpsilonEridani.restrictScalars_jacobson_sq_nonisolatedZigzagQuotient_eq_zigzagVolumeSpan`, it is the
span of the volume classes. -/
theorem socle_nonisolatedZigzagQuotient_eq_jacobson_sq (hns : ∀ i : V, ∃ j, G.Adj i j) :
    socle (nonisolatedZigzagQuotient k G) (nonisolatedZigzagQuotient k G) =
      Ring.jacobson (nonisolatedZigzagQuotient k G) ^ 2 := by
  refine le_antisymm (socle_le fun m hm => ?_) fun x hx => ?_
  · -- A simple submodule is killed by the radical, because the radical is nilpotent.
    have hatom : IsAtom m := isSimpleModule_iff_isAtom.1 hm
    have hsmul : Ring.jacobson (nonisolatedZigzagQuotient k G) • m = ⊥ := by
      rcases eq_or_lt_of_le (Submodule.smul_le_right :
          Ring.jacobson (nonisolatedZigzagQuotient k G) • m ≤ m) with heq | hlt
      · exfalso
        have e2 : (Ring.jacobson (nonisolatedZigzagQuotient k G) *
            Ring.jacobson (nonisolatedZigzagQuotient k G)) • m = m := by
          rw [Submodule.mul_smul, heq, heq]
        -- Ideal powers use the submodule successor recursion, so expose the exponents.
        have h3 : Ring.jacobson (nonisolatedZigzagQuotient k G) ^ 3 =
            Ring.jacobson (nonisolatedZigzagQuotient k G) ^ 2 *
              Ring.jacobson (nonisolatedZigzagQuotient k G) := by
          rw [show 3 = 2 + 1 by omega, Submodule.pow_succ]
        have h2 : Ring.jacobson (nonisolatedZigzagQuotient k G) ^ 2 =
            Ring.jacobson (nonisolatedZigzagQuotient k G) *
              Ring.jacobson (nonisolatedZigzagQuotient k G) := by
          rw [show 2 = 1 + 1 by omega, Submodule.pow_succ, Submodule.pow_one]
        have e3 : (Ring.jacobson (nonisolatedZigzagQuotient k G) ^ 3) • m = m := by
          rw [h3, Submodule.mul_smul, heq, h2, e2]
        rw [jacobson_pow_three_nonisolatedZigzagQuotient_eq_bot hns,
          Submodule.bot_smul] at e3
        exact hatom.1 e3.symm
      · exact hatom.2 _ hlt
    refine fun y hy => ?_
    have hzero : ∀ d : G.Dart, zigzagMk k G (ofArrow (arrow G d.adj)) * y = 0 := by
      intro d
      have hd : zigzagMk k G (ofArrow (arrow G d.adj)) ∈
          Ring.jacobson (nonisolatedZigzagQuotient k G) := by
        rw [← Submodule.restrictScalars_mem k,
          restrictScalars_jacobson_nonisolatedZigzagQuotient_eq_zigzagPositiveSpan hns]
        exact zigzagMk_ofArrow_mem_zigzagPositiveSpan d
      have := Submodule.smul_mem_smul hd hy
      rw [hsmul, Submodule.mem_bot, smul_eq_mul] at this
      exact this
    rw [← Submodule.restrictScalars_mem k,
      restrictScalars_jacobson_sq_nonisolatedZigzagQuotient_eq_zigzagVolumeSpan hns]
    exact mem_zigzagVolumeSpan_of_forall_zigzagMk_ofArrow_mul_eq_zero hns hzero
  · -- Conversely the square of the radical is spanned by the volume classes, which are in the
    -- socle.
    have hx' : x ∈ zigzagVolumeSpan k G := by
      rw [← restrictScalars_jacobson_sq_nonisolatedZigzagQuotient_eq_zigzagVolumeSpan hns,
        Submodule.restrictScalars_mem]
      exact hx
    refine zigzagVolumeSpan_le (N := (socle (nonisolatedZigzagQuotient k G)
      (nonisolatedZigzagQuotient k G)).restrictScalars k) (fun i => ?_) hx'
    exact zigzagVolume_mem_socle i (hns i)

/-- **The socle of a zigzag algebra is the span of its volume classes.** -/
theorem restrictScalars_socle_nonisolatedZigzagQuotient_eq_zigzagVolumeSpan
    (hns : ∀ i : V, ∃ j, G.Adj i j) :
    (socle (nonisolatedZigzagQuotient k G) (nonisolatedZigzagQuotient k G)).restrictScalars k =
      zigzagVolumeSpan k G := by
  rw [socle_nonisolatedZigzagQuotient_eq_jacobson_sq hns,
    restrictScalars_jacobson_sq_nonisolatedZigzagQuotient_eq_zigzagVolumeSpan hns]

/-- **The socle of a zigzag algebra has one dimension for each vertex.** -/
theorem finrank_restrictScalars_socle_nonisolatedZigzagQuotient [Fintype V]
    (hns : ∀ i : V, ∃ j, G.Adj i j) :
    Module.finrank k
        ((socle (nonisolatedZigzagQuotient k G)
          (nonisolatedZigzagQuotient k G)).restrictScalars k) = Fintype.card V := by
  rw [restrictScalars_socle_nonisolatedZigzagQuotient_eq_zigzagVolumeSpan hns,
    zigzagVolumeSpan_eq_span]
  exact finrank_span_eq_card (linearIndependent_zigzagVolume hns)

/-! ### The top -/

variable (k)

/-- **The top of a zigzag algebra.**  The quotient by the Jacobson radical is the product of one
copy of the ground field for each vertex, the vertex coefficients of an element being its
coordinates. -/
noncomputable def zigzagTopEquiv (hns : ∀ i : V, ∃ j, G.Adj i j) :
    (nonisolatedZigzagQuotient k G ⧸ Ring.jacobson (nonisolatedZigzagQuotient k G)) ≃ₐ[k]
      (DoubledQuiver G → k) :=
  (Ideal.quotientEquivAlgOfEq k (jacobson_nonisolatedZigzagQuotient_eq_ker hns)).trans
    (Ideal.quotientKerAlgEquivOfSurjective (zigzagTrivialCoeff_surjective k G))

@[simp]
theorem zigzagTopEquiv_mk (hns : ∀ i : V, ∃ j, G.Adj i j)
    (x : nonisolatedZigzagQuotient k G) :
    zigzagTopEquiv k hns (Ideal.Quotient.mk _ x) = zigzagTrivialCoeff k G x := by
  unfold zigzagTopEquiv
  exact (congrArg
    (Ideal.quotientKerAlgEquivOfSurjective (zigzagTrivialCoeff_surjective k G))
    (Ideal.quotientEquivAlgOfEq_mk k
      (jacobson_nonisolatedZigzagQuotient_eq_ker hns) x)).trans
    (Ideal.quotientKerAlgEquivOfSurjective_mk
      (zigzagTrivialCoeff_surjective k G) x)

/-- **The top of a zigzag algebra is semisimple.** -/
theorem isSemisimpleRing_quotient_jacobson_nonisolatedZigzagQuotient
    (hns : ∀ i : V, ∃ j, G.Adj i j) :
    IsSemisimpleRing
      (nonisolatedZigzagQuotient k G ⧸ Ring.jacobson (nonisolatedZigzagQuotient k G)) :=
  (zigzagTopEquiv k hns).symm.toRingEquiv.isSemisimpleRing

/-- **The top of a zigzag algebra has one dimension for each vertex**, matching the socle. -/
theorem finrank_quotient_jacobson_nonisolatedZigzagQuotient [Fintype V]
    (hns : ∀ i : V, ∃ j, G.Adj i j) :
    Module.finrank k
        (nonisolatedZigzagQuotient k G ⧸ Ring.jacobson (nonisolatedZigzagQuotient k G)) =
      Fintype.card V := by
  rw [(zigzagTopEquiv k hns).toLinearEquiv.finrank_eq, Module.finrank_fintype_fun_eq_card]
  exact Fintype.card_congr (vertexEquiv G).symm

end Field


end EpsilonEridani
