/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Codex
-/
module

public import EpsilonEridani.Algebra.AlgebraicGroup.GeneralLinear.Borel
public import EpsilonEridani.Algebra.AlgebraicGroup.Smooth.CommHopfAlgCat
public import EpsilonEridani.Algebra.AlgebraicGroup.Solvable.Basic
public import EpsilonEridani.Algebra.AlgebraicGroup.SpecialLinear.Basic
public import EpsilonEridani.LinearAlgebra.Matrix.SpecialLinearGroup.Borel
import EpsilonEridani.Algebra.AlgebraicGroup.HopfIdeal.Points.Separation
import EpsilonEridani.Algebra.AlgebraicGroup.Smooth.GeometricallyReduced

/-!
# The upper-triangular closed subgroup scheme of `SL₂`

The lower-left coordinate in `O(SL₂)` generates a Hopf ideal. Its quotient represents the
upper-triangular determinant-one matrices: over every commutative algebra `A`, the points cut
out by this ideal identify with the existing subgroup `EpsilonEridani.SL2Borel A`.

Over a field, this closed subgroup is maximal among closed subgroups whose coordinate algebra is
reduced and whose geometric points are solvable. In particular, it is maximal among smooth closed
subgroups with solvable geometric points. This is the maximality input for proving that the
standard upper-triangular subgroup scheme of `SL₂` is Borel; its smoothness, geometric
connectedness, and base-change compatibility are separate coordinate-geometric inputs.

## Main declarations

* `EpsilonEridani.SpecialLinear.Borel.definingHopfIdeal`: the lower-left-coordinate Hopf ideal in
  `O(SL₂)`.
* `EpsilonEridani.SpecialLinear.Borel.definingHopfIdeal_toIdeal`: its underlying ideal is generated by
  the lower-left coordinate.
* `EpsilonEridani.SpecialLinear.Borel.coordinateMap_ker`: the kernel of the quotient coordinate map is
  the lower-left-coordinate ideal.
* `EpsilonEridani.SpecialLinear.Borel.mem_definingPointsSubgroup_iff`: its algebra-valued points are
  precisely the matrices in `SL2Borel`.
* `EpsilonEridani.SpecialLinear.Borel.pointsMulEquiv`: the resulting equivalence from quotient Hopf
  points to `SL2Borel`.
* `EpsilonEridani.SpecialLinear.Borel.definingHopfIdeal_le_of_le_of_isReduced_of_geometricallySolvable`:
  maximality among closed subgroups with reduced coordinate algebra and solvable geometric points.
* `EpsilonEridani.SpecialLinear.Borel.definingHopfIdeal_le_of_le_of_smooth_of_geometricallySolvable`:
  maximality among smooth closed subgroups with solvable geometric points.

## References

* J. S. Milne, *Algebraic Groups* (2017), Chapters 12 and 21.
* R. W. Carter, *Simple Groups of Lie Type* (1972), Section 8.2.
* The Hopf ideal and maximality argument adapt
  `EpsilonEridani.Algebra.AlgebraicGroup.GeneralLinear.Borel`.
* The point-subgroup and point-equivalence API adapts
  `EpsilonEridani.Algebra.AlgebraicGroup.SpecialLinear.Basic`.
* The maximal-solvability input is `EpsilonEridani.SL2Borel.le_of_isSolvable_of_infinite` from
  `EpsilonEridani.LinearAlgebra.Matrix.SpecialLinearGroup.Borel`.
-/

public section

open CategoryTheory WithConv
open scoped MatrixGroups

namespace EpsilonEridani.SpecialLinear.Borel

universe u w

variable (R : Type u) [CommRing R]

/-- The lower-left coordinate of the generic determinant-one `2 × 2` matrix. -/
noncomputable def lowerLeftCoordinate : SpecialLinear.coordinateHopfAlgebra R 2 :=
  (SpecialLinear.coordinateMap R 2).hom (GeneralLinear.Borel.lowerLeftCoordinate R)

/-- The lower-left coordinate is the image of its general-linear counterpart. -/
theorem lowerLeftCoordinate_def :
    lowerLeftCoordinate R =
      (SpecialLinear.coordinateMap R 2).hom (GeneralLinear.Borel.lowerLeftCoordinate R) :=
  by rw [lowerLeftCoordinate]

/-- The Hopf ideal cutting out upper-triangular matrices inside `SL₂`.

It is the image of the general-linear upper-triangular Hopf ideal under the determinant-one
quotient map. -/
noncomputable def definingHopfIdeal :
    HopfIdeal R (SpecialLinear.coordinateHopfAlgebra R 2) :=
  (GeneralLinear.Borel.definingHopfIdeal R).map (SpecialLinear.coordinateMap R 2).hom

/-- The special-linear Borel ideal is the image of the general-linear Borel ideal under the
determinant-one quotient map. -/
theorem definingHopfIdeal_def :
    definingHopfIdeal R =
      (GeneralLinear.Borel.definingHopfIdeal R).map (SpecialLinear.coordinateMap R 2).hom :=
  by rw [definingHopfIdeal]

/-- The underlying ideal of the special-linear Borel Hopf ideal is generated by the lower-left
coordinate. -/
theorem definingHopfIdeal_toIdeal :
    (definingHopfIdeal R).toIdeal = Ideal.span {lowerLeftCoordinate R} := by
  rw [definingHopfIdeal, HopfIdeal.map_toIdeal,
    GeneralLinear.Borel.definingHopfIdeal_toIdeal, Ideal.map_span]
  simp only [Set.image_singleton]
  exact congrArg (fun x ↦ Ideal.span {x}) (lowerLeftCoordinate_def R).symm

/-- The coordinate Hopf algebra of the upper-triangular closed subgroup scheme of `SL₂`. -/
noncomputable abbrev coordinateHopfAlgebra : _root_.CommHopfAlgCat.{u} R :=
  CommHopfAlgCat.quotient (SpecialLinear.coordinateHopfAlgebra R 2) (definingHopfIdeal R)

/-- The quotient coordinate morphism from `O(SL₂)` to the upper-triangular coordinate Hopf
algebra. -/
noncomputable abbrev coordinateMap :
    SpecialLinear.coordinateHopfAlgebra R 2 ⟶ coordinateHopfAlgebra R :=
  CommHopfAlgCat.mkQuotient (SpecialLinear.coordinateHopfAlgebra R 2) (definingHopfIdeal R)

/-- The upper-triangular quotient coordinate morphism sends an ambient coordinate to its quotient
class. -/
theorem coordinateMap_apply (h : SpecialLinear.coordinateHopfAlgebra R 2) :
    (coordinateMap R).hom h = Ideal.Quotient.mkₐ R (definingHopfIdeal R).toIdeal h :=
  CommHopfAlgCat.mkQuotient_apply
    (SpecialLinear.coordinateHopfAlgebra R 2) (definingHopfIdeal R) h

/-- The kernel of the upper-triangular quotient coordinate morphism is the principal
lower-left-coordinate ideal. -/
theorem coordinateMap_ker :
    RingHom.ker (coordinateMap R).hom.toAlgHom.toRingHom =
      Ideal.span {lowerLeftCoordinate R} := by
  rw [CommHopfAlgCat.mkQuotient_ker, definingHopfIdeal_toIdeal]

/-- The lower-left coordinate vanishes in the upper-triangular quotient coordinate algebra. -/
@[simp↓]
theorem coordinateMap_lowerLeftCoordinate :
    (coordinateMap R).hom (lowerLeftCoordinate R) = 0 := by
  rw [coordinateMap_apply, Ideal.Quotient.mkₐ_eq_mk]
  exact Ideal.Quotient.eq_zero_iff_mem.mpr
    (definingHopfIdeal_toIdeal R ▸ Ideal.mem_span_singleton_self _)

/-- The upper-triangular special-linear coordinate Hopf algebra is finite type. -/
instance instAlgebraFiniteTypeCoordinateHopfAlgebra :
    Algebra.FiniteType R (coordinateHopfAlgebra R) :=
  Algebra.FiniteType.quotient R (definingHopfIdeal R).toIdeal

section Points

variable {A : Type w} [CommRing A] [Algebra R A]

/-- An algebra-valued point belongs to the subgroup cut out in `SL₂` exactly when its matrix is
upper triangular, equivalently when it belongs to `SL2Borel`. -/
@[simp]
theorem mem_definingPointsSubgroup_iff
    (g : HopfAlgebra.points (R := R) (H := SpecialLinear.coordinateHopfAlgebra R 2)
      (CommAlgCat.of R A)) :
    g ∈ CommHopfAlgCat.quotientPointsSubgroup
        (SpecialLinear.coordinateHopfAlgebra R 2) (definingHopfIdeal R)
        (CommAlgCat.of R A) ↔
      (SpecialLinear.pointsMulEquiv (R := R) (A := A) 2) g ∈ SL2Borel A := by
  rw [definingHopfIdeal_def,
    CommHopfAlgCat.mem_quotientPointsSubgroup_map_iff_of_surjective
      (SpecialLinear.coordinateMap R 2)
      (CommHopfAlgCat.mkQuotient_surjective
        (GeneralLinear.coordinateHopfAlgebra R 2) (SpecialLinear.definingHopfIdeal R 2)),
    GeneralLinear.UpperTriangular.mem_definingPointsSubgroup_iff]
  rw [CommHopfAlgCat.mapPointsFunctor_app_apply,
    ← CommHopfAlgCat.quotientPointsHom_apply
      (GeneralLinear.coordinateHopfAlgebra R 2) (SpecialLinear.definingHopfIdeal R 2)
      (CommAlgCat.of R A) g]
  have hmatrix := SpecialLinear.pointsMulEquiv_toGL (R := R) (A := A) 2 g
  rw [hmatrix]
  rw [GL2Borel.mem_iff, SL2Borel.mem_iff,
    Matrix.SpecialLinearGroup.coe_GL_coe_matrix]

/-- The point subgroup cut out by the special-linear Borel ideal is the ordinary subgroup of
upper-triangular determinant-one matrices. -/
private noncomputable def definingPointsSubgroupMulEquiv :
    CommHopfAlgCat.quotientPointsSubgroup
        (SpecialLinear.coordinateHopfAlgebra R 2) (definingHopfIdeal R)
        (CommAlgCat.of R A) ≃*
      SL2Borel A :=
  Subgroup.congrOfMapEq (SpecialLinear.pointsMulEquiv (R := R) (A := A) 2) <| by
    ext g
    rw [← (SpecialLinear.pointsMulEquiv (R := R) (A := A) 2).toMonoidHom_eq_coe,
      Subgroup.mem_map_equiv, mem_definingPointsSubgroup_iff,
      MulEquiv.apply_symm_apply]

/-- The group of algebra-valued points of the upper-triangular special-linear coordinate Hopf
algebra is the standard Borel subgroup `SL2Borel`. -/
noncomputable def pointsMulEquiv :
    HopfAlgebra.points (R := R) (H := coordinateHopfAlgebra R) (CommAlgCat.of R A) ≃*
      SL2Borel A :=
  ((CommHopfAlgCat.quotientPointsSubgroupNatIso
      (SpecialLinear.coordinateHopfAlgebra R 2) (definingHopfIdeal R)).app
      (CommAlgCat.of R A)).groupIsoToMulEquiv.trans
    (definingPointsSubgroupMulEquiv R)

/-- Internally, the Borel point equivalence first forms the cut-out ambient subgroup point and
then restricts the special-linear point equivalence to that subgroup. -/
private theorem pointsMulEquiv_apply_eq
    (f : HopfAlgebra.points (R := R) (H := coordinateHopfAlgebra R)
      (CommAlgCat.of R A)) :
    pointsMulEquiv (R := R) (A := A) f =
      definingPointsSubgroupMulEquiv R
        (((CommHopfAlgCat.quotientPointsSubgroupNatIso
          (SpecialLinear.coordinateHopfAlgebra R 2) (definingHopfIdeal R)).app
          (CommAlgCat.of R A)).hom f) :=
  rfl

private theorem coe_definingPointsSubgroupMulEquiv_apply
    (g : CommHopfAlgCat.quotientPointsSubgroup
      (SpecialLinear.coordinateHopfAlgebra R 2) (definingHopfIdeal R)
      (CommAlgCat.of R A)) :
    (definingPointsSubgroupMulEquiv R g : SL(2, A)) =
      SpecialLinear.pointsMulEquiv (R := R) (A := A) 2 g.1 :=
  Subgroup.coe_congrOfMapEq_apply _ _ g

/-- Under the Borel and special-linear point equivalences, the quotient-point inclusion is the
ordinary inclusion of the standard Borel into `SL₂`. -/
@[simp]
theorem pointsMulEquiv_coe
    (f : HopfAlgebra.points (R := R) (H := coordinateHopfAlgebra R)
      (CommAlgCat.of R A)) :
    SpecialLinear.pointsMulEquiv (R := R) (A := A) 2
        (CommHopfAlgCat.quotientPointsHom
          (SpecialLinear.coordinateHopfAlgebra R 2) (definingHopfIdeal R)
          (CommAlgCat.of R A) f) =
      (pointsMulEquiv (R := R) (A := A) f : SL(2, A)) := by
  have hcomponent := CommHopfAlgCat.quotientPointsSubgroupNatIso_hom_app_apply
    (SpecialLinear.coordinateHopfAlgebra R 2) (definingHopfIdeal R)
    (CommAlgCat.of R A) f
  calc
    _ = SpecialLinear.pointsMulEquiv (R := R) (A := A) 2
          (((CommHopfAlgCat.quotientPointsSubgroupNatIso
            (SpecialLinear.coordinateHopfAlgebra R 2) (definingHopfIdeal R)).app
            (CommAlgCat.of R A)).hom f).1 :=
      (congrArg
        (fun g ↦ SpecialLinear.pointsMulEquiv (R := R) (A := A) 2 g.1) hcomponent).symm
    _ = (definingPointsSubgroupMulEquiv R
          (((CommHopfAlgCat.quotientPointsSubgroupNatIso
            (SpecialLinear.coordinateHopfAlgebra R 2) (definingHopfIdeal R)).app
            (CommAlgCat.of R A)).hom f) : SL(2, A)) :=
      (coe_definingPointsSubgroupMulEquiv_apply R _).symm
    _ = _ := congrArg (fun g : SL2Borel A ↦ (g : SL(2, A)))
      (pointsMulEquiv_apply_eq R f).symm

/-- The ambient point attached to a standard Borel matrix is the special-linear point attached
to its ordinary inclusion. -/
@[simp]
theorem quotientPointsHom_pointsMulEquiv_symm (g : SL2Borel A) :
    CommHopfAlgCat.quotientPointsHom
        (SpecialLinear.coordinateHopfAlgebra R 2) (definingHopfIdeal R)
        (CommAlgCat.of R A) ((pointsMulEquiv (R := R) (A := A)).symm g) =
      (SpecialLinear.pointsMulEquiv (R := R) (A := A) 2).symm g.1 := by
  apply (SpecialLinear.pointsMulEquiv (R := R) (A := A) 2).injective
  rw [pointsMulEquiv_coe, MulEquiv.apply_symm_apply, MulEquiv.apply_symm_apply]

variable {B : Type*} [CommRing B] [Algebra R B]

/-- The standard Borel point equivalence is natural in the value algebra. -/
@[simp]
theorem pointsMulEquiv_mapValue (phi : A →ₐ[R] B)
    (f : HopfAlgebra.points (R := R) (H := coordinateHopfAlgebra R)
      (CommAlgCat.of R A)) :
    pointsMulEquiv (R := R) (A := B)
        (WithConv.toConv (phi.comp f.ofConv)) =
      SL2Borel.map phi.toRingHom (pointsMulEquiv (R := R) (A := A) f) := by
  rw [← AlgHom.mapValue_apply]
  apply Subtype.ext
  rw [SL2Borel.coe_map, ← pointsMulEquiv_coe,
    ← CommHopfAlgCat.mapValue_quotientPointsHom]
  rw [SpecialLinear.pointsMulEquiv_mapValue, pointsMulEquiv_coe]

end Points

section Field

variable {k : Type u} [Field k]

/-- The standard upper-triangular Hopf ideal in `O(SL₂)` is maximal, in the reverse ideal order
corresponding to inclusion of closed subgroups, among closed subgroups with reduced coordinate
algebra and solvable geometric points. -/
theorem definingHopfIdeal_le_of_le_of_isReduced_of_geometricallySolvable
    (I : HopfIdeal k (SpecialLinear.coordinateHopfAlgebra k 2))
    (hIB : I ≤ definingHopfIdeal k)
    [IsReduced (CommHopfAlgCat.quotient (SpecialLinear.coordinateHopfAlgebra k 2) I)]
    (hIsolvable : geometricallySolvablePointsCommHopfAlgProperty k
      (CommHopfAlgCat.quotient (SpecialLinear.coordinateHopfAlgebra k 2) I)) :
    definingHopfIdeal k ≤ I := by
  let K := AlgebraicClosure k
  let H := SpecialLinear.coordinateHopfAlgebra k 2
  let Q := CommHopfAlgCat.quotientPointsSubgroup H I (CommAlgCat.of k K)
  let e := SpecialLinear.pointsMulEquiv (R := k) (A := K) 2
  let P : Subgroup SL(2, K) := Q.map e.toMonoidHom
  have hBP : SL2Borel K ≤ P := by
    intro g hg
    rw [Subgroup.mem_map_equiv]
    apply CommHopfAlgCat.quotientPointsSubgroup_le_of_le H hIB (CommAlgCat.of k K)
    apply (mem_definingPointsSubgroup_iff k _).mpr
    simpa only [e, MulEquiv.apply_symm_apply] using hg
  rw [geometricallySolvablePointsCommHopfAlgProperty_iff] at hIsolvable
  let _ : Group.IsSolvable
      (HopfAlgebra.points (R := k) (H := CommHopfAlgCat.quotient H I)
        (CommAlgCat.of k K)) := hIsolvable
  let qEquiv :
      HopfAlgebra.points (R := k) (H := CommHopfAlgCat.quotient H I)
          (CommAlgCat.of k K) ≃* Q :=
    ((CommHopfAlgCat.quotientPointsSubgroupNatIso H I).app
      (CommAlgCat.of k K)).groupIsoToMulEquiv
  let _ : Group.IsSolvable Q :=
    Group.isSolvable_of_isSolvable_injective qEquiv.symm.injective
  let qToP : Q ≃* P := e.subgroupMap Q
  let _ : Group.IsSolvable P :=
    Group.isSolvable_of_surjective (f := qToP.toMonoidHom) qToP.surjective
  have hPB : P ≤ SL2Borel K := SL2Borel.le_of_isSolvable_of_infinite P hBP
  apply HopfIdeal.le_of_quotientPointsSubgroup_le (K := K)
  intro q hq
  apply (mem_definingPointsSubgroup_iff k q).mpr
  apply hPB
  exact ⟨q, hq, rfl⟩

/-- The standard upper-triangular Hopf ideal in `O(SL₂)` is maximal, in the reverse ideal
order corresponding to inclusion of closed subgroups, among smooth closed subgroups with
solvable geometric points. -/
theorem definingHopfIdeal_le_of_le_of_smooth_of_geometricallySolvable
    (I : HopfIdeal k (SpecialLinear.coordinateHopfAlgebra k 2))
    (hIB : I ≤ definingHopfIdeal k)
    (hIsmooth : smoothCommHopfAlgProperty k
      (CommHopfAlgCat.quotient (SpecialLinear.coordinateHopfAlgebra k 2) I))
    (hIsolvable : geometricallySolvablePointsCommHopfAlgProperty k
      (CommHopfAlgCat.quotient (SpecialLinear.coordinateHopfAlgebra k 2) I)) :
    definingHopfIdeal k ≤ I := by
  let _ : IsReduced
      (CommHopfAlgCat.quotient (SpecialLinear.coordinateHopfAlgebra k 2) I) :=
    ((smoothCommHopfAlgProperty_iff_geometricallyReduced k
      (CommHopfAlgCat.quotient (SpecialLinear.coordinateHopfAlgebra k 2) I)).mp hIsmooth).isReduced
  exact definingHopfIdeal_le_of_le_of_isReduced_of_geometricallySolvable I hIB hIsolvable

end Field

end EpsilonEridani.SpecialLinear.Borel
