/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.GroupTheory.Presentation.GroupPresentation

/-!
# A transcribed presentation of the Higman--Sims group

This file carries the `HS` row of the sporadic presentation data required by milestone S1 of
`EpsilonEridaniRoadmap/CFSGStatement/README.md`. It records John Bray's ATLAS version 3 presentation of
the Higman--Sims group on its standard generators `a` and `b` as a `EpsilonEridani.GroupPresentation`,
together with the source, the generator convention, transcription notes, and the expected counts.

Writing `s₁ = ab`, `s₂ = ab²`, `s₋₁ = ab⁻¹` and `s₋₂ = ab⁻²` for the four syllables that occur, the
thirteen transcribed relators are

```text
a², b⁵, s₁¹¹, s₂¹⁰, [a,b]⁵, [a,bab]³, [a,b²]⁶,
s₁s₁s₂s₋₁s₋₂s₋₁s₂s₁s₁s₋₂⁴,
s₁(s₂s₋₂²)²s₂s₁s₂(s₋₁s₂)²,
s₁s₁s₂²s₁s₋₁²s₁s₂²s₁s₁s₋₂s₋₁s₋₂,
(s₁s₁s₂s₋₁s₋₂s₁s₁s₋₁)²,
(s₁s₁s₂)²s₁s₁s₋₁s₁s₁s₂³s₁s₁s₋₁,
s₁(s₁s₂)³s₁s₁s₂s₋₁s₁s₋₂s₁s₋₁s₂.
```

The last three are redundant, and are flagged as such by the source; they are transcribed anyway
because the coset enumerations that the source uses to justify the presentation are run with them.

The source's commutator convention is `[r,s] = r⁻¹s⁻¹rs`, opposite to Mathlib's
`commutatorElement`, so each commutator is stored as `Relator.comm (.inv r) (.inv s)` as
`EpsilonEridani.Relator` prescribes. The proved `EpsilonEridani.Relator.toWord_toFreeGroup` is the audit boundary
between these expressions and the signed words that `PresentedGroup` consumes.

The source is a presentation rather than a semi-presentation, and it comes with a demonstration of
correctness: the relations `a² = b⁵ = (ab)¹¹ = 1` force the presented group to be perfect and
generated by conjugates of `a`; the subgroup listed in the source visibly centralizes `a` and a
coset enumeration returns the index `5775` of the involution centralizer of `HS`; and the double
cover `2·HS` is excluded because `ab²` lifts to elements of order `20` there, while `(ab²)¹⁰ = 1` is
a relator. GAP 4.15.1 independently checks that the thirteen words compiled by `Relator.toWord`
from the expressions below vanish on five independent standard generating pairs of the 100-point
primitive representation of `HS`, that is, pairs generating the group with `a` an involution whose
centralizer has order `7680`, `b` of order 5 with centralizer of order `500`, and `ab` of order
`11`. Both computations are provenance for the transcription, not Lean theorems: this file asserts
no order, finiteness, simplicity, or identification result.

## Independent source-to-Lean read-through

An independent read-through used the bytes of the ATLAS Magma source `HSG1-P1.M` whose SHA-256
digest is `6f1863b22ce2bf3a4c7dfb4b84200dc614d4b40a5f8f6bd164832ae998d3b25b`. Its constructor
`G<x,y>` fixes the generator order corresponding to the standard generators `a,b` in this row.
Writing its words in this module's syllables gives the seven short entries

```text
a², b⁵, s₁¹¹, s₂¹⁰, [a,b]⁵, [a,bab]³, [a,b²]⁶,
```

followed, in source order, by

```text
s₁s₁s₂s₋₁s₋₂s₋₁s₂s₁s₁s₋₂⁴,
s₁(s₂s₋₂²)²s₂s₁s₂(s₋₁s₂)²,
s₁s₁s₂²s₁s₋₁²s₁s₂²s₁s₁s₋₂s₋₁s₋₂,
(s₁s₁s₂s₋₁s₋₂s₁s₁s₋₁)²,
(s₁s₁s₂)²s₁s₁s₋₁s₁s₁s₂³s₁s₁s₋₁,
s₁(s₁s₂)³s₁s₁s₂s₋₁s₁s₋₂s₁s₋₁s₂.
```

These are exactly the thirteen entries of `hsPresentation_transcribed`, including every inverse,
power, commutator, and source-order position. The Magma file marks the last three as `R1`, `R2`,
and `R3`, says they are redundant but useful, and keeps them inside the constructor; the Lean row
therefore correctly retains them. The rendered presentation page omits those three and swaps the
display order of `[a,bab]³` and `[a,b²]⁶`, while the row deliberately follows the raw Magma order.
This comparison was performed from the pinned source bytes independently of the original
transcription and closes this row's S1 source-to-Lean read-through.

## Independent comparison with `FiniteSimpleGroups`

The comparison used `finite-simple-groups-lean` at commit
`7f09e33a9ceef6b59ce03e34cd4f0558c763e325`, whose named permutations `hsa`, `hsb`, and `hsc`
generate a subgroup of `Equiv.Perm (Fin 100)` with proved order `44352000` and proved simplicity.
Write those permutations as `x`, `y`, and `z`. The following words in them give images of the
ATLAS presentation generators:

```text
a = (z x x y x z⁻¹ x⁻¹ z⁻¹ z⁻¹ y⁻¹ x y x z⁻¹ y⁻¹ y⁻¹ y⁻¹ x⁻¹ z y⁻¹ x⁻¹ y⁻¹)⁴
b = (y⁻¹ x⁻¹ x⁻¹ z⁻¹ y⁻¹ z⁻¹ z⁻¹ x z y⁻¹ x y y z z y x x)⁴.
```

Direct calculation gives orders `2`, `5`, `11`, and `10` for `a`, `b`, `ab`, and `ab²`.
Moreover, the centralizers of `a` and `b` in the pinned subgroup have orders `7680` and `500`, so
the pair has the source's exact ATLAS classes rather than only the required element orders. All
thirteen compiled relators in this module evaluate to the identity. Schreier--Sims membership
checks put `a,b` in the subgroup generated by `x,y,z` and put each of `x,y,z` back in `⟨a,b⟩`;
the pair therefore generates the pinned group of order `44352000`.

The check used Python 3.14.6 and SymPy 1.14.0. Concatenating the forward image tables for `a` and
then `b`, with each image stored as a two-byte little-endian integer, has SHA-256
`6820d1571023e66bfff5a2fac256bd6d6ccb7e38bffd5f86b56db6ee1e17f6f2`. This is the independent
comparison artifact required by S1; no external code or permutation data is imported into Tau Ceti.

The row is a sealed definition, so it publishes an equation for each of its fields: the transcribed
relator expressions with their generator indices written out, and the provenance a manifest row
exists to record. Together with `EpsilonEridani.GroupPresentation.relators_def` and
`EpsilonEridani.GroupPresentation.mem_relatorSet_iff` the first of those determines the compiled words and
the relations defining the presented group, so a consumer reasons about the row without unfolding
it.

Three decidable checks accompany those equations. The relator lengths and their total record the
compiled data one word at a time and in aggregate, and cyclic reducedness is what makes such a
letter count comparable with a published presentation length, since both are measured after free
and cyclic reduction of each relator. This row has no published length to check against: Bray's
presentation page for `HS` is one of the 1997 stubs that record `Length ??`, and neither the ATLAS
page nor its Magma source file gives a figure. The total below therefore states the transcribed
data for a reviewer to compare with the source, rather than checking it against a recorded number.

## Main definitions and results

* `EpsilonEridani.Sporadic.hsPresentation`: John Bray's ATLAS finite presentation of `HS`.
* `EpsilonEridani.Sporadic.hsPresentation_transcribed` and the equations for the remaining fields: the
  characterization of the sealed row.
* `EpsilonEridani.Sporadic.hsPresentation_map_length_relators`,
  `EpsilonEridani.Sporadic.hsPresentation_totalLength` and
  `EpsilonEridani.Sporadic.hsPresentation_relatorsCyclicallyReduced`: the three checks on the compiled
  words.

## References

* R. A. Wilson, R. A. Parker, J. N. Bray et al., *ATLAS of Finite Group Representations*,
  version 3, presentation `HSG1-P1`, contributed by John Bray,
  <https://brauer.maths.qmul.ac.uk/Atlas/v3/pres/HSG1-P1>, with the relators and the demonstration
  of correctness in the Magma source file
  <https://brauer.maths.qmul.ac.uk/Atlas/spor/HS/mag/HSG1-P1.M>.
* J. N. Bray, presentation page for the Higman--Sims group,
  <https://webspace.maths.qmul.ac.uk/j.n.bray/web/Pres/HS.html>, which records `Length ??` and so
  publishes no letter count for this presentation.
* KitaKen1, *FiniteSimpleGroups*, `HS` construction at commit
  `7f09e33a9ceef6b59ce03e34cd4f0558c763e325`,
  <https://github.com/KitaKen1/finite-simple-groups-lean>.
-/

public section

namespace EpsilonEridani.Sporadic

private abbrev a : Relator (Fin 2) := .gen 0

private abbrev b : Relator (Fin 2) := .gen 1

@[inherit_doc Relator.mul]
local infixl:70 " ⬝ " => Relator.mul

/-- The source's commutator `[r, s] = r⁻¹ s⁻¹ r s`, which is `⁅r⁻¹, s⁻¹⁆` in Mathlib's
convention. -/
private abbrev sourceComm (r s : Relator (Fin 2)) : Relator (Fin 2) := .comm (.inv r) (.inv s)

/-- The syllable `a * b`. -/
private abbrev ab1 : Relator (Fin 2) := a ⬝ b

/-- The syllable `a * b ^ 2`. -/
private abbrev ab2 : Relator (Fin 2) := a ⬝ .pow b 2

/-- The syllable `a * b⁻¹`. -/
private abbrev abNeg1 : Relator (Fin 2) := a ⬝ .inv b

/-- The syllable `a * b⁻²`. -/
private abbrev abNeg2 : Relator (Fin 2) := a ⬝ .pow (.inv b) 2

/-- John Bray's ATLAS version 3 finite presentation of the Higman--Sims group `HS` on its standard
generators `a` and `b`.

The ATLAS lists this as a full presentation of the abstract group, separately from the
semi-presentation used to recognize standard generators inside a group already constructed. No
structural property of the presented group is asserted here: this definition records only the
cited generators and relations. -/
def hsPresentation : GroupPresentation where
  generatorNames := ["a", "b"]
  source := "R. A. Wilson, R. A. Parker, J. N. Bray et al., ATLAS of Finite Group \
    Representations, version 3; presentation contributed by John Bray"
  sourceLocator := "HSG1-P1, https://brauer.maths.qmul.ac.uk/Atlas/v3/pres/HSG1-P1, with the \
    relator list and the demonstration of correctness in the Magma source file \
    https://brauer.maths.qmul.ac.uk/Atlas/spor/HS/mag/HSG1-P1.M"
  generatorConvention := "The ATLAS standard generators a and b of HS, that is, a in class 2A and \
    b in class 5A with ab of order 11, in that order, so index 0 is a and index 1 is b. Products \
    are read left to right, negative exponents denote inverses, and [r,s] denotes r^-1 s^-1 r s."
  transcriptionNotes := "The thirteen words of the source's relator list are stored as thirteen \
    relators equal to the identity. The last three, marked R1, R2 and R3 there, are redundant, \
    and are transcribed because the source runs its coset enumerations with them. The source \
    demonstrates correctness by enumerating the 5775 cosets of a subgroup that visibly \
    centralizes a, using (a*b^2)^10 = 1 to exclude the double cover 2.HS. GAP 4.15.1 checks that \
    the thirteen compiled words vanish on five independent standard generating pairs of the \
    100-point primitive representation of HS, taking a with centralizer of order 7680, b of \
    order 5 with centralizer of order 500, and ab of order 11."
  expectedGeneratorCount := 2
  expectedRelatorCount := 13
  transcribed :=
    [ .pow a 2,
      .pow b 5,
      .pow ab1 11,
      .pow ab2 10,
      .pow (sourceComm a b) 5,
      .pow (sourceComm a (b ⬝ a ⬝ b)) 3,
      .pow (sourceComm a (.pow b 2)) 6,
      ab1 ⬝ ab1 ⬝ ab2 ⬝ abNeg1 ⬝ abNeg2 ⬝ abNeg1 ⬝ ab2 ⬝ ab1 ⬝ ab1 ⬝ .pow abNeg2 4,
      ab1 ⬝ .pow (ab2 ⬝ .pow abNeg2 2) 2 ⬝ ab2 ⬝ ab1 ⬝ ab2 ⬝ .pow (abNeg1 ⬝ ab2) 2,
      ab1 ⬝ ab1 ⬝ .pow ab2 2 ⬝ ab1 ⬝ .pow abNeg1 2 ⬝ ab1 ⬝ .pow ab2 2 ⬝ ab1 ⬝ ab1 ⬝
        abNeg2 ⬝ abNeg1 ⬝ abNeg2,
      .pow (ab1 ⬝ ab1 ⬝ ab2 ⬝ abNeg1 ⬝ abNeg2 ⬝ ab1 ⬝ ab1 ⬝ abNeg1) 2,
      .pow (ab1 ⬝ ab1 ⬝ ab2) 2 ⬝ ab1 ⬝ ab1 ⬝ abNeg1 ⬝ ab1 ⬝ ab1 ⬝ .pow ab2 3 ⬝ ab1 ⬝ ab1 ⬝ abNeg1,
      ab1 ⬝ .pow (ab1 ⬝ ab2) 3 ⬝ ab1 ⬝ ab1 ⬝ ab2 ⬝ abNeg1 ⬝ ab1 ⬝ abNeg2 ⬝ ab1 ⬝ abNeg1 ⬝ ab2 ]

/-- The generator names recorded for `HS`. The row's body is sealed, so this is what lets a
consumer see that it is a two-generator presentation. -/
@[simp]
theorem hsPresentation_generatorNames : hsPresentation.generatorNames = ["a", "b"] := by
  simp [hsPresentation]

/-- The source recorded for `HS`. The row's body is sealed, so this equation publishes the citation
itself, rather than only the row's name, to a downstream audit. -/
@[simp]
theorem hsPresentation_source :
    hsPresentation.source = "R. A. Wilson, R. A. Parker, J. N. Bray et al., ATLAS of Finite Group \
      Representations, version 3; presentation contributed by John Bray" := by
  simp [hsPresentation]

/-- The locator recorded for `HS`, pointing at the presentation and its demonstration of
correctness inside the source. -/
@[simp]
theorem hsPresentation_sourceLocator :
    hsPresentation.sourceLocator = "HSG1-P1, \
      https://brauer.maths.qmul.ac.uk/Atlas/v3/pres/HSG1-P1, with the relator list and the \
      demonstration of correctness in the Magma source file \
      https://brauer.maths.qmul.ac.uk/Atlas/spor/HS/mag/HSG1-P1.M" := by
  simp [hsPresentation]

/-- The generator convention recorded for `HS`, fixing which generator each relator index names and
which commutator convention the source uses. -/
@[simp]
theorem hsPresentation_generatorConvention :
    hsPresentation.generatorConvention = "The ATLAS standard generators a and b of HS, that is, a \
      in class 2A and b in class 5A with ab of order 11, in that order, so index 0 is a and index \
      1 is b. Products are read left to right, negative exponents denote inverses, and [r,s] \
      denotes r^-1 s^-1 r s." := by
  simp [hsPresentation]

/-- The transcription notes recorded for `HS`, including which of the source's relators it flags as
redundant. -/
@[simp]
theorem hsPresentation_transcriptionNotes :
    hsPresentation.transcriptionNotes = "The thirteen words of the source's relator list are \
      stored as thirteen relators equal to the identity. The last three, marked R1, R2 and R3 \
      there, are redundant, and are transcribed because the source runs its coset enumerations \
      with them. The source demonstrates correctness by enumerating the 5775 cosets of a subgroup \
      that visibly centralizes a, using (a*b^2)^10 = 1 to exclude the double cover 2.HS. GAP \
      4.15.1 checks that the thirteen compiled words vanish on five independent standard \
      generating pairs of the 100-point primitive representation of HS, taking a with centralizer \
      of order 7680, b of order 5 with centralizer of order 500, and ab of order 11." := by
  simp [hsPresentation]

/-- The generator count `HS`'s source states. With
`EpsilonEridani.Sporadic.hsPresentation_generatorNames` this makes
`EpsilonEridani.Sporadic.hsPresentation_matchesMetadata` an equation between two visible numbers. -/
@[simp]
theorem hsPresentation_expectedGeneratorCount : hsPresentation.expectedGeneratorCount = 2 := by
  simp [hsPresentation]

/-- The relator count `HS`'s source states; see
`EpsilonEridani.Sporadic.hsPresentation_expectedGeneratorCount`. -/
@[simp]
theorem hsPresentation_expectedRelatorCount : hsPresentation.expectedRelatorCount = 13 := by
  simp [hsPresentation]

/-- The relator expressions transcribed for `HS`, with their generator indices written out and the
private syllable abbreviations of this file expanded.

The row's body is sealed, so this is the equation that characterizes it: with
`EpsilonEridani.GroupPresentation.relators_def` it determines the compiled words, and with
`EpsilonEridani.GroupPresentation.mem_relatorSet_iff` it determines the relations defining
`EpsilonEridani.GroupPresentation.Group`, so a consumer never has to unfold the row. Index `0` is the
generator `a` and index `1` is `b`, and the bounds come from
`EpsilonEridani.Sporadic.hsPresentation_generatorNames`. The comments name each relator in the syllables
`s₁ = ab`, `s₂ = ab²`, `s₋₁ = ab⁻¹` and `s₋₂ = ab⁻²` of the module docstring. -/
@[simp]
theorem hsPresentation_transcribed :
    hsPresentation.transcribed =
      [
        -- a²
        .pow (.gen ⟨0, by simp⟩) 2,
        -- b⁵
        .pow (.gen ⟨1, by simp⟩) 5,
        -- s₁¹¹
        .pow (.gen ⟨0, by simp⟩ ⬝ .gen ⟨1, by simp⟩) 11,
        -- s₂¹⁰
        .pow (.gen ⟨0, by simp⟩ ⬝ .pow (.gen ⟨1, by simp⟩) 2) 10,
        -- [a,b]⁵, in the source's commutator convention
        .pow (.comm (.inv (.gen ⟨0, by simp⟩)) (.inv (.gen ⟨1, by simp⟩))) 5,
        -- [a,bab]³
        .pow (.comm (.inv (.gen ⟨0, by simp⟩))
              (.inv (.gen ⟨1, by simp⟩ ⬝ .gen ⟨0, by simp⟩ ⬝ .gen ⟨1, by simp⟩))) 3,
        -- [a,b²]⁶
        .pow (.comm (.inv (.gen ⟨0, by simp⟩)) (.inv (.pow (.gen ⟨1, by simp⟩) 2))) 6,
        -- s₁s₁s₂s₋₁s₋₂s₋₁s₂s₁s₁s₋₂⁴
        (.gen ⟨0, by simp⟩ ⬝ .gen ⟨1, by simp⟩) ⬝ (.gen ⟨0, by simp⟩ ⬝ .gen ⟨1, by simp⟩) ⬝
          (.gen ⟨0, by simp⟩ ⬝ .pow (.gen ⟨1, by simp⟩) 2) ⬝
          (.gen ⟨0, by simp⟩ ⬝ .inv (.gen ⟨1, by simp⟩)) ⬝
          (.gen ⟨0, by simp⟩ ⬝ .pow (.inv (.gen ⟨1, by simp⟩)) 2) ⬝
          (.gen ⟨0, by simp⟩ ⬝ .inv (.gen ⟨1, by simp⟩)) ⬝
          (.gen ⟨0, by simp⟩ ⬝ .pow (.gen ⟨1, by simp⟩) 2) ⬝
          (.gen ⟨0, by simp⟩ ⬝ .gen ⟨1, by simp⟩) ⬝ (.gen ⟨0, by simp⟩ ⬝ .gen ⟨1, by simp⟩) ⬝
          .pow (.gen ⟨0, by simp⟩ ⬝ .pow (.inv (.gen ⟨1, by simp⟩)) 2) 4,
        -- s₁(s₂s₋₂²)²s₂s₁s₂(s₋₁s₂)²
        (.gen ⟨0, by simp⟩ ⬝ .gen ⟨1, by simp⟩) ⬝
          .pow ((.gen ⟨0, by simp⟩ ⬝ .pow (.gen ⟨1, by simp⟩) 2) ⬝
          .pow (.gen ⟨0, by simp⟩ ⬝ .pow (.inv (.gen ⟨1, by simp⟩)) 2) 2) 2 ⬝
          (.gen ⟨0, by simp⟩ ⬝ .pow (.gen ⟨1, by simp⟩) 2) ⬝
          (.gen ⟨0, by simp⟩ ⬝ .gen ⟨1, by simp⟩) ⬝
          (.gen ⟨0, by simp⟩ ⬝ .pow (.gen ⟨1, by simp⟩) 2) ⬝
          .pow ((.gen ⟨0, by simp⟩ ⬝ .inv (.gen ⟨1, by simp⟩)) ⬝
          (.gen ⟨0, by simp⟩ ⬝ .pow (.gen ⟨1, by simp⟩) 2)) 2,
        -- s₁s₁s₂²s₁s₋₁²s₁s₂²s₁s₁s₋₂s₋₁s₋₂
        (.gen ⟨0, by simp⟩ ⬝ .gen ⟨1, by simp⟩) ⬝ (.gen ⟨0, by simp⟩ ⬝ .gen ⟨1, by simp⟩) ⬝
          .pow (.gen ⟨0, by simp⟩ ⬝ .pow (.gen ⟨1, by simp⟩) 2) 2 ⬝
          (.gen ⟨0, by simp⟩ ⬝ .gen ⟨1, by simp⟩) ⬝
          .pow (.gen ⟨0, by simp⟩ ⬝ .inv (.gen ⟨1, by simp⟩)) 2 ⬝
          (.gen ⟨0, by simp⟩ ⬝ .gen ⟨1, by simp⟩) ⬝
          .pow (.gen ⟨0, by simp⟩ ⬝ .pow (.gen ⟨1, by simp⟩) 2) 2 ⬝
          (.gen ⟨0, by simp⟩ ⬝ .gen ⟨1, by simp⟩) ⬝ (.gen ⟨0, by simp⟩ ⬝ .gen ⟨1, by simp⟩) ⬝
          (.gen ⟨0, by simp⟩ ⬝ .pow (.inv (.gen ⟨1, by simp⟩)) 2) ⬝
          (.gen ⟨0, by simp⟩ ⬝ .inv (.gen ⟨1, by simp⟩)) ⬝
          (.gen ⟨0, by simp⟩ ⬝ .pow (.inv (.gen ⟨1, by simp⟩)) 2),
        -- (s₁s₁s₂s₋₁s₋₂s₁s₁s₋₁)², the redundant relator R1
        .pow ((.gen ⟨0, by simp⟩ ⬝ .gen ⟨1, by simp⟩) ⬝
          (.gen ⟨0, by simp⟩ ⬝ .gen ⟨1, by simp⟩) ⬝
          (.gen ⟨0, by simp⟩ ⬝ .pow (.gen ⟨1, by simp⟩) 2) ⬝
          (.gen ⟨0, by simp⟩ ⬝ .inv (.gen ⟨1, by simp⟩)) ⬝
          (.gen ⟨0, by simp⟩ ⬝ .pow (.inv (.gen ⟨1, by simp⟩)) 2) ⬝
          (.gen ⟨0, by simp⟩ ⬝ .gen ⟨1, by simp⟩) ⬝ (.gen ⟨0, by simp⟩ ⬝ .gen ⟨1, by simp⟩) ⬝
          (.gen ⟨0, by simp⟩ ⬝ .inv (.gen ⟨1, by simp⟩))) 2,
        -- (s₁s₁s₂)²s₁s₁s₋₁s₁s₁s₂³s₁s₁s₋₁, the redundant relator R2
        .pow ((.gen ⟨0, by simp⟩ ⬝ .gen ⟨1, by simp⟩) ⬝
          (.gen ⟨0, by simp⟩ ⬝ .gen ⟨1, by simp⟩) ⬝
          (.gen ⟨0, by simp⟩ ⬝ .pow (.gen ⟨1, by simp⟩) 2)) 2 ⬝
          (.gen ⟨0, by simp⟩ ⬝ .gen ⟨1, by simp⟩) ⬝ (.gen ⟨0, by simp⟩ ⬝ .gen ⟨1, by simp⟩) ⬝
          (.gen ⟨0, by simp⟩ ⬝ .inv (.gen ⟨1, by simp⟩)) ⬝
          (.gen ⟨0, by simp⟩ ⬝ .gen ⟨1, by simp⟩) ⬝ (.gen ⟨0, by simp⟩ ⬝ .gen ⟨1, by simp⟩) ⬝
          .pow (.gen ⟨0, by simp⟩ ⬝ .pow (.gen ⟨1, by simp⟩) 2) 3 ⬝
          (.gen ⟨0, by simp⟩ ⬝ .gen ⟨1, by simp⟩) ⬝ (.gen ⟨0, by simp⟩ ⬝ .gen ⟨1, by simp⟩) ⬝
          (.gen ⟨0, by simp⟩ ⬝ .inv (.gen ⟨1, by simp⟩)),
        -- s₁(s₁s₂)³s₁s₁s₂s₋₁s₁s₋₂s₁s₋₁s₂, the redundant relator R3
        (.gen ⟨0, by simp⟩ ⬝ .gen ⟨1, by simp⟩) ⬝
          .pow ((.gen ⟨0, by simp⟩ ⬝ .gen ⟨1, by simp⟩) ⬝
          (.gen ⟨0, by simp⟩ ⬝ .pow (.gen ⟨1, by simp⟩) 2)) 3 ⬝
          (.gen ⟨0, by simp⟩ ⬝ .gen ⟨1, by simp⟩) ⬝ (.gen ⟨0, by simp⟩ ⬝ .gen ⟨1, by simp⟩) ⬝
          (.gen ⟨0, by simp⟩ ⬝ .pow (.gen ⟨1, by simp⟩) 2) ⬝
          (.gen ⟨0, by simp⟩ ⬝ .inv (.gen ⟨1, by simp⟩)) ⬝
          (.gen ⟨0, by simp⟩ ⬝ .gen ⟨1, by simp⟩) ⬝
          (.gen ⟨0, by simp⟩ ⬝ .pow (.inv (.gen ⟨1, by simp⟩)) 2) ⬝
          (.gen ⟨0, by simp⟩ ⬝ .gen ⟨1, by simp⟩) ⬝
          (.gen ⟨0, by simp⟩ ⬝ .inv (.gen ⟨1, by simp⟩)) ⬝
          (.gen ⟨0, by simp⟩ ⬝ .pow (.gen ⟨1, by simp⟩) 2) ] := by
  simp [hsPresentation]

/-- The generator and relator counts recorded for `HS` agree with the transcribed data. -/
theorem hsPresentation_matchesMetadata : hsPresentation.matchesMetadata := by decide

/-- The lengths of the thirteen compiled relator words for `HS`, in the order of the source.

Reading the counts off one relator at a time is what lets a reviewer locate a discrepancy, rather
than only observe one in the total of `EpsilonEridani.Sporadic.hsPresentation_totalLength`. -/
theorem hsPresentation_map_length_relators :
    hsPresentation.relators.map List.length =
      [2, 5, 22, 30, 20, 24, 36, 33, 38, 36, 36, 39, 38] := by
  simp [GroupPresentation.relators_def, hsPresentation]

/-- The compiled relator words for `HS` have `359` letters in total. The source records no
presentation length, so this figure states the transcribed data for a reviewer to compare with the
source, rather than checking it against a recorded number. -/
theorem hsPresentation_totalLength : hsPresentation.totalLength = 359 := by
  rw [GroupPresentation.totalLength_def, hsPresentation_map_length_relators]
  decide

/-- Every compiled relator word for `HS` is cyclically reduced. This is what makes the letter count
of `EpsilonEridani.Sporadic.hsPresentation_totalLength` comparable with a published presentation length,
which is measured after free and cyclic reduction of each relator. -/
theorem hsPresentation_relatorsCyclicallyReduced :
    hsPresentation.relatorsCyclicallyReduced := by
  simp only [GroupPresentation.relatorsCyclicallyReduced_iff, GroupPresentation.relators_def,
    hsPresentation, List.map_cons, List.map_nil, Relator.toWord_mul, Relator.toWord_pow,
    Relator.toWord_inv, Relator.toWord_comm, Relator.toWord_gen]
  decide

end EpsilonEridani.Sporadic
