/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.GroupTheory.Presentation.GroupPresentation

/-!
# A transcribed presentation of the O'Nan sporadic group

This file carries the `ONan` row of the sporadic presentation data required by milestone S1 of
`EpsilonEridaniRoadmap/CFSGStatement/README.md`. It records `GPLTable.ON.1` from Roderik Lindenbergh's
Group Presentations Library as a `EpsilonEridani.GroupPresentation`, together with the exact source,
generator convention, transcription notes, expected counts, and decidable checks on the
transcription.

The presentation starts with the Coxeter path

```text
a --3-- b --3-- c --8-- d --3-- e --3-- f.
```

Thus the path declares `x² = 1` for each of `a` through `f`, `(xy)^m = 1` for each displayed edge
`x --m-- y`, and `(xy)² = 1` for every pair omitted from the path. These are power relations, so
they force each of those orders to divide the exponent shown; that any exponent is attained is not
recorded here and is not proved below. The source then adds a seventh generator `g` and the eight
relations

```text
g^4,  af = g^2,  af = (cd)^4,  c c^(dgdg),  d d^(cgcg),  (bcdg)^5,
g b g^c g^b g^c,  g e g^d g^e g^d.
```

Here the source uses `x^y = y^-1 x y`, and its decoder compiles an equality `x = y` to the relator
`x^-1 y`. The Coxeter path contributes six square relations and fifteen pair relations, so the
complete list has `21 + 8 = 29` relators.

The row's body is sealed, so the equations below are what publish it: one per record field, and one
spelling the compiled words out letter by letter. The proved metadata theorem checks the generator
and relator counts, and two further decidable checks show that the compiled words contain `172`
signed letters and are cyclically reduced. GPL records no relator total or presentation length, so
the figures `29` and `172` compare the compiler's output with the hand expansion of the path and
eight auxiliary words, rather than with published figures. As a separate transcription check, GAP
4.15.1 enumerates `122760` cosets of the subgroup generated by `a` through `f`, agreeing with the
index of the `L3(7):2` subgroup recorded by GPL. An independent read-through of the version 1.0
`GPLTable.ON.1` record and its `DeCoxList`, `MakeWordList`, and
`InitializeGroupPresentationGPL` decoders checked the generator order, Coxeter path, all eight
appended relations, conjugation convention, and compiled signed letters below. These checks are
provenance rather than Lean theorems: this file asserts no order, finiteness, simplicity, or
identification result. The independent `FiniteSimpleGroups` development does not cover `ONan`, so
no further comparison against it applies to this row.

## Independent source-to-compiled audit record

This audit was performed from the GPL artifact independently of the original transcription. The
retrieved version 1.0 `gpl.g` bytes have SHA-256
`8b90a7a65317a585b5b74d015083bd2fa3db8a969c117a220d00d7e8773103c8`. The source record is

```text
presdef := [ "a3b3c8d3e3f", "g",
  "g^4,af=g^2,af=(cd)^4,cc^(dgdg),dd^(cgcg),(bcdg)^5,
   gbg^cg^bg^c,geg^dg^eg^d", ]
```

and the decoder comparison with `onanPresentation_relatorLetters` is:

* entries 1--6 are the squares of `a,b,c,d,e,f` inserted by `AddTrivialRelations`;
* entries 7--11 are `(ab)^3,(bc)^3,(cd)^8,(de)^3,(ef)^3`, the five labeled edges;
* entries 12--21 are the exponent-two relations on the ten complementary pairs
  `ac,ad,ae,af,bd,be,bf,ce,cf,df` inserted by `AddNonEdgeRelations`;
* entry 22 is `g^4`;
* entries 23--24 are the equality words `(af)⁻¹g^2` and `(af)⁻¹(cd)^4`, using
  `MakeWordList`'s left-inverse convention;
* entries 25--26 are `c c^(dgdg)` and `d d^(cgcg)`, with every conjugate expanded using the
  source convention `x^y = y⁻¹xy`; and
* entries 27--29 are `(bcdg)^5`, `g b g^c g^b g^c`, and `g e g^d g^e g^d`.

Expanding the powers, inverses, and conjugates gives exactly the signed lists in
`onanPresentation_relatorLetters`; no source letter or pair relation differs from that theorem.
This itemized record is the independent source-to-Lean review artifact; the theorem remains the
kernel-checked target against which it was read.

## Main definition

* `EpsilonEridani.Sporadic.onanPresentation`: the GPL finite presentation of the O'Nan sporadic group.

## References

* R. Lindenbergh, *Group Presentations Library*, version 1.0, record `GPLTable.ON.1`,
  <https://doris.tudelft.nl/~rlindenbergh/GPL/gpl.g>.
* C. E. Praeger and L. H. Soicher, *Low Rank Representations and Graphs for Sporadic Groups*,
  Cambridge University Press, 1997, Chapter 4, doi:10.1017/CBO9780511526039.005.
-/

public section

namespace EpsilonEridani.Sporadic

private abbrev a : Relator (Fin 7) := .gen 0

private abbrev b : Relator (Fin 7) := .gen 1

private abbrev c : Relator (Fin 7) := .gen 2

private abbrev d : Relator (Fin 7) := .gen 3

private abbrev e : Relator (Fin 7) := .gen 4

private abbrev f : Relator (Fin 7) := .gen 5

private abbrev g : Relator (Fin 7) := .gen 6

@[inherit_doc Relator.mul]
local infixl:70 " ⬝ " => Relator.mul

/-- The six square relations and the fifteen pair-power relations decoded from the Coxeter path
`a3b3c8d3e3f` in `GPLTable.ON.1`.

The ten nonedges are written explicitly with exponent two, so this list records the complete
Coxeter matrix rather than relying on an implicit default. -/
private def onanCoxeterRelators : List (Relator (Fin 7)) :=
  [ .pow a 2,
    .pow b 2,
    .pow c 2,
    .pow d 2,
    .pow e 2,
    .pow f 2,
    .pow (a ⬝ b) 3,
    .pow (b ⬝ c) 3,
    .pow (c ⬝ d) 8,
    .pow (d ⬝ e) 3,
    .pow (e ⬝ f) 3,
    .pow (a ⬝ c) 2,
    .pow (a ⬝ d) 2,
    .pow (a ⬝ e) 2,
    .pow (a ⬝ f) 2,
    .pow (b ⬝ d) 2,
    .pow (b ⬝ e) 2,
    .pow (b ⬝ f) 2,
    .pow (c ⬝ e) 2,
    .pow (c ⬝ f) 2,
    .pow (d ⬝ f) 2 ]

/-- The eight words following the Coxeter path in `GPLTable.ON.1`.

The source decoder represents an equality `x = y` by the relator `x^-1 y`, explaining the leading
inverses in the second and third entries. The other entries preserve the source's conjugation
convention `x^y = y^-1 x y`. -/
private def onanAdditionalRelators : List (Relator (Fin 7)) :=
  [ .pow g 4,
    .inv (a ⬝ f) ⬝ .pow g 2,
    .inv (a ⬝ f) ⬝ .pow (c ⬝ d) 4,
    c ⬝ Relator.conj c (d ⬝ g ⬝ d ⬝ g),
    d ⬝ Relator.conj d (c ⬝ g ⬝ c ⬝ g),
    .pow (b ⬝ c ⬝ d ⬝ g) 5,
    g ⬝ b ⬝ Relator.conj g c ⬝ Relator.conj g b ⬝ Relator.conj g c,
    g ⬝ e ⬝ Relator.conj g d ⬝ Relator.conj g e ⬝ Relator.conj g d ]

/-- The Group Presentations Library finite presentation `GPLTable.ON.1` of the O'Nan sporadic
group on generators `a`, `b`, `c`, `d`, `e`, `f`, and `g`.

The source describes this as a full presentation of the abstract group and identifies its origin
as Praeger--Soicher. No structural property of the presented group is asserted here: this
definition records only the cited generators and relations. -/
def onanPresentation : GroupPresentation where
  generatorNames := ["a", "b", "c", "d", "e", "f", "g"]
  source := "R. Lindenbergh, Group Presentations Library, version 1.0; presentation attributed \
    there to C. E. Praeger and L. H. Soicher, Low Rank Representations and Graphs for Sporadic \
    Groups, Cambridge University Press, 1997"
  sourceLocator := "GPLTable.ON.1 in \
    https://doris.tudelft.nl/~rlindenbergh/GPL/gpl.g; Praeger--Soicher, Chapter 4, \
    doi:10.1017/CBO9780511526039.005"
  generatorConvention := "Generators have source order a,b,c,d,e,f,g, so indices 0 through 6 \
    have those names. The Coxeter path declares x^2 = 1 for each of a through f, a labeled edge \
    x-m-y declares (x*y)^m = 1, and an omitted edge declares (x*y)^2 = 1. Products are read left \
    to right, x^y means y^-1*x*y, and the source decoder compiles x = y as x^-1*y."
  transcriptionNotes := "Expand the path a3b3c8d3e3f to six square relations, five \
    labeled-edge relations, and ten omitted-edge relations. Append the eight words in \
    presdef[3], compiling the two equalities and all conjugation expressions by the source's \
    MakeWordList \
    decoder. The expected relator count and total length are derived from this exact expansion. \
    GAP 4.15.1 enumerates 122760 cosets of the subgroup generated by a through f, agreeing with \
    the index of the L3(7):2 subgroup recorded by GPL. An independent read-through of \
    GPLTable.ON.1 and its DeCoxList, MakeWordList, and InitializeGroupPresentationGPL decoders \
    checked the generator order, Coxeter path, all eight appended relations, conjugation \
    convention, and compiled signed letters; the itemized comparison is recorded in this module's \
    independent audit section. The independent FiniteSimpleGroups development does not cover \
    ONan, so no further comparison against it applies to this row."
  expectedGeneratorCount := 7
  expectedRelatorCount := 29
  transcribed := onanCoxeterRelators ++ onanAdditionalRelators

/-- The generator names recorded for `ONan`. The row's body is sealed, so this is what lets a
consumer see that it is a seven-generator presentation. -/
@[simp]
theorem onanPresentation_generatorNames :
    onanPresentation.generatorNames = ["a", "b", "c", "d", "e", "f", "g"] := by
  simp [onanPresentation]

/-- The source recorded for `ONan`. The row's body is sealed, so this equation is what publishes the
citation itself, rather than only the row's name, to a downstream audit. -/
theorem onanPresentation_source :
    onanPresentation.source = "R. Lindenbergh, Group Presentations Library, version 1.0; \
      presentation attributed there to C. E. Praeger and L. H. Soicher, Low Rank Representations \
      and Graphs for Sporadic Groups, Cambridge University Press, 1997" := by
  simp [onanPresentation]

/-- The locator recorded for `ONan`, pointing at the presentation inside its source. -/
theorem onanPresentation_sourceLocator :
    onanPresentation.sourceLocator = "GPLTable.ON.1 in \
      https://doris.tudelft.nl/~rlindenbergh/GPL/gpl.g; Praeger--Soicher, Chapter 4, \
      doi:10.1017/CBO9780511526039.005" := by
  simp [onanPresentation]

/-- The generator convention recorded for `ONan`, fixing which generator each relator index names
and how the source's Coxeter path, conjugates, and equalities are decoded. -/
theorem onanPresentation_generatorConvention :
    onanPresentation.generatorConvention = "Generators have source order a,b,c,d,e,f,g, so \
      indices 0 through 6 have those names. The Coxeter path declares x^2 = 1 for each of a \
      through f, a labeled edge x-m-y declares (x*y)^m = 1, and an omitted edge declares \
      (x*y)^2 = 1. Products are read left to right, x^y means y^-1*x*y, and the source decoder \
      compiles x = y as x^-1*y." := by
  simp [onanPresentation]

/-- The transcription notes recorded for `ONan`, including the coset index of the external
enumeration. -/
theorem onanPresentation_transcriptionNotes :
    onanPresentation.transcriptionNotes = "Expand the path a3b3c8d3e3f to six square relations, \
      five labeled-edge relations, and ten omitted-edge relations. Append the eight words in \
      presdef[3], compiling the two equalities and all conjugation expressions by the source's \
      MakeWordList decoder. The expected relator count and total length are derived from this \
      exact expansion. GAP 4.15.1 enumerates 122760 cosets of the subgroup generated by a \
      through f, agreeing with the index of the L3(7):2 subgroup recorded by GPL. An independent \
      read-through of GPLTable.ON.1 and its DeCoxList, MakeWordList, and \
      InitializeGroupPresentationGPL decoders checked the generator order, Coxeter path, all \
      eight appended relations, conjugation convention, and compiled signed letters; the itemized \
      comparison is recorded in this module's independent audit section. The independent \
      FiniteSimpleGroups development does not cover ONan, so no further comparison against it \
      applies to this row." := by
  simp [onanPresentation]

/-- The generator count `ONan`'s source states. With
`EpsilonEridani.Sporadic.onanPresentation_generatorNames` this is what makes
`EpsilonEridani.Sporadic.onanPresentation_matchesMetadata` an equation between two visible numbers. -/
@[simp]
theorem onanPresentation_expectedGeneratorCount : onanPresentation.expectedGeneratorCount = 7 := by
  simp [onanPresentation]

/-- The relator count obtained by expanding the source's Coxeter path into six squares, five
labeled edges, and ten omitted edges, then appending its eight auxiliary words. -/
@[simp]
theorem onanPresentation_expectedRelatorCount : onanPresentation.expectedRelatorCount = 29 := by
  simp [onanPresentation]

/-- The relator expressions transcribed for `ONan`, with their generator indices written out.

The row's body is sealed, so this is the equation that characterizes it: with
`EpsilonEridani.GroupPresentation.relators_def` it determines the compiled words, and with
`EpsilonEridani.GroupPresentation.mem_relatorSet_iff` it determines the relations defining
`EpsilonEridani.GroupPresentation.Group`, so a consumer never has to unfold the row or its private
helpers. Indices `0` through `6` are the generators `a` through `g`, and the bounds come from
`EpsilonEridani.Sporadic.onanPresentation_generatorNames`. The first twenty-one entries are the Coxeter
relations and the last eight are the source's auxiliary words. -/
theorem onanPresentation_transcribed :
    onanPresentation.transcribed =
      [ .pow (.gen ⟨0, by decide⟩) 2,
        .pow (.gen ⟨1, by decide⟩) 2,
        .pow (.gen ⟨2, by decide⟩) 2,
        .pow (.gen ⟨3, by decide⟩) 2,
        .pow (.gen ⟨4, by decide⟩) 2,
        .pow (.gen ⟨5, by decide⟩) 2,
        .pow (.gen ⟨0, by decide⟩ ⬝ .gen ⟨1, by decide⟩) 3,
        .pow (.gen ⟨1, by decide⟩ ⬝ .gen ⟨2, by decide⟩) 3,
        .pow (.gen ⟨2, by decide⟩ ⬝ .gen ⟨3, by decide⟩) 8,
        .pow (.gen ⟨3, by decide⟩ ⬝ .gen ⟨4, by decide⟩) 3,
        .pow (.gen ⟨4, by decide⟩ ⬝ .gen ⟨5, by decide⟩) 3,
        .pow (.gen ⟨0, by decide⟩ ⬝ .gen ⟨2, by decide⟩) 2,
        .pow (.gen ⟨0, by decide⟩ ⬝ .gen ⟨3, by decide⟩) 2,
        .pow (.gen ⟨0, by decide⟩ ⬝ .gen ⟨4, by decide⟩) 2,
        .pow (.gen ⟨0, by decide⟩ ⬝ .gen ⟨5, by decide⟩) 2,
        .pow (.gen ⟨1, by decide⟩ ⬝ .gen ⟨3, by decide⟩) 2,
        .pow (.gen ⟨1, by decide⟩ ⬝ .gen ⟨4, by decide⟩) 2,
        .pow (.gen ⟨1, by decide⟩ ⬝ .gen ⟨5, by decide⟩) 2,
        .pow (.gen ⟨2, by decide⟩ ⬝ .gen ⟨4, by decide⟩) 2,
        .pow (.gen ⟨2, by decide⟩ ⬝ .gen ⟨5, by decide⟩) 2,
        .pow (.gen ⟨3, by decide⟩ ⬝ .gen ⟨5, by decide⟩) 2,
        .pow (.gen ⟨6, by decide⟩) 4,
        .inv (.gen ⟨0, by decide⟩ ⬝ .gen ⟨5, by decide⟩) ⬝ .pow (.gen ⟨6, by decide⟩) 2,
        .inv (.gen ⟨0, by decide⟩ ⬝ .gen ⟨5, by decide⟩) ⬝ .pow (.gen ⟨2, by decide⟩ ⬝
          .gen ⟨3, by decide⟩) 4,
        .gen ⟨2, by decide⟩ ⬝
          Relator.conj (.gen ⟨2, by decide⟩)
            (.gen ⟨3, by decide⟩ ⬝ .gen ⟨6, by decide⟩ ⬝
              .gen ⟨3, by decide⟩ ⬝ .gen ⟨6, by decide⟩),
        .gen ⟨3, by decide⟩ ⬝
          Relator.conj (.gen ⟨3, by decide⟩)
            (.gen ⟨2, by decide⟩ ⬝ .gen ⟨6, by decide⟩ ⬝
              .gen ⟨2, by decide⟩ ⬝ .gen ⟨6, by decide⟩),
        .pow
          (.gen ⟨1, by decide⟩ ⬝ .gen ⟨2, by decide⟩ ⬝
            .gen ⟨3, by decide⟩ ⬝ .gen ⟨6, by decide⟩) 5,
        .gen ⟨6, by decide⟩ ⬝ .gen ⟨1, by decide⟩ ⬝
          Relator.conj (.gen ⟨6, by decide⟩) (.gen ⟨2, by decide⟩) ⬝
          Relator.conj (.gen ⟨6, by decide⟩) (.gen ⟨1, by decide⟩) ⬝
          Relator.conj (.gen ⟨6, by decide⟩) (.gen ⟨2, by decide⟩),
        .gen ⟨6, by decide⟩ ⬝ .gen ⟨4, by decide⟩ ⬝
          Relator.conj (.gen ⟨6, by decide⟩) (.gen ⟨3, by decide⟩) ⬝
          Relator.conj (.gen ⟨6, by decide⟩) (.gen ⟨4, by decide⟩) ⬝
          Relator.conj (.gen ⟨6, by decide⟩) (.gen ⟨3, by decide⟩) ] := by
  simp [onanPresentation, onanCoxeterRelators, onanAdditionalRelators, Relator.conj]

/-- The generator and relator counts recorded for `ONan` agree with the transcribed data. -/
theorem onanPresentation_matchesMetadata : onanPresentation.matchesMetadata := by
  decide

/-- The compiled relator words for `ONan`, spelled out. A letter `(i, true)` is the generator with
index `i` and `(i, false)` is its inverse, so index `0` reads `a` and index `6` reads `g`.

This is the form in which the transcription is compared with the source letter by letter. The
length check below is read off from these letters; the cyclic-reduction check instead recompiles
the bounded words from `EpsilonEridani.Sporadic.onanPresentation_transcribed`. -/
theorem onanPresentation_relatorLetters :
    onanPresentation.relatorLetters =
      [[(0, true), (0, true)],
        [(1, true), (1, true)],
        [(2, true), (2, true)],
        [(3, true), (3, true)],
        [(4, true), (4, true)],
        [(5, true), (5, true)],
        [(0, true), (1, true), (0, true), (1, true), (0, true), (1, true)],
        [(1, true), (2, true), (1, true), (2, true), (1, true), (2, true)],
        [(2, true), (3, true), (2, true), (3, true), (2, true), (3, true), (2, true), (3, true),
          (2, true), (3, true), (2, true), (3, true), (2, true), (3, true), (2, true), (3, true)],
        [(3, true), (4, true), (3, true), (4, true), (3, true), (4, true)],
        [(4, true), (5, true), (4, true), (5, true), (4, true), (5, true)],
        [(0, true), (2, true), (0, true), (2, true)],
        [(0, true), (3, true), (0, true), (3, true)],
        [(0, true), (4, true), (0, true), (4, true)],
        [(0, true), (5, true), (0, true), (5, true)],
        [(1, true), (3, true), (1, true), (3, true)],
        [(1, true), (4, true), (1, true), (4, true)],
        [(1, true), (5, true), (1, true), (5, true)],
        [(2, true), (4, true), (2, true), (4, true)],
        [(2, true), (5, true), (2, true), (5, true)],
        [(3, true), (5, true), (3, true), (5, true)],
        [(6, true), (6, true), (6, true), (6, true)],
        [(5, false), (0, false), (6, true), (6, true)],
        [(5, false), (0, false), (2, true), (3, true), (2, true), (3, true), (2, true), (3, true),
          (2, true), (3, true)],
        [(2, true), (6, false), (3, false), (6, false), (3, false), (2, true), (3, true),
          (6, true), (3, true), (6, true)],
        [(3, true), (6, false), (2, false), (6, false), (2, false), (3, true), (2, true),
          (6, true), (2, true), (6, true)],
        [(1, true), (2, true), (3, true), (6, true), (1, true), (2, true), (3, true), (6, true),
          (1, true), (2, true), (3, true), (6, true), (1, true), (2, true), (3, true), (6, true),
          (1, true), (2, true), (3, true), (6, true)],
        [(6, true), (1, true), (2, false), (6, true), (2, true), (1, false), (6, true), (1, true),
          (2, false), (6, true), (2, true)],
        [(6, true), (4, true), (3, false), (6, true), (3, true), (4, false), (6, true), (4, true),
          (3, false), (6, true), (3, true)]] := by
  simp only [GroupPresentation.relatorLetters_def, GroupPresentation.relators_def,
    onanPresentation_transcribed, List.map_cons, List.map_nil, Relator.toWord_mul,
    Relator.toWord_pow, Relator.toWord_inv, Relator.toWord_gen, Relator.toWord_conj,
    FreeGroup.invRev]
  decide

/-- The compiled relators of the `ONan` presentation contain `172` signed letters in total. This is
read off from the spelled-out letters rather than from the record. -/
theorem onanPresentation_totalLength : onanPresentation.totalLength = 172 := by
  rw [← GroupPresentation.sum_map_length_relatorLetters, onanPresentation_relatorLetters]
  decide

/-- Every compiled relator of the `ONan` presentation is cyclically reduced. This is what makes the
letter count in `EpsilonEridani.Sporadic.onanPresentation_totalLength` comparable with a presentation
length, which is measured after free and cyclic reduction of each relator.

Only the compiler needs unfolding here: once the transcribed expressions are compiled away, the
words are closed data and the kernel decides the predicate. -/
theorem onanPresentation_relatorsCyclicallyReduced :
    onanPresentation.relatorsCyclicallyReduced := by
  simp only [GroupPresentation.relatorsCyclicallyReduced_iff, GroupPresentation.relators_def,
    onanPresentation_transcribed, List.map_cons, List.map_nil, Relator.toWord_mul,
    Relator.toWord_pow, Relator.toWord_inv, Relator.toWord_gen, Relator.toWord_conj]
  decide

end EpsilonEridani.Sporadic
