/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.LinearAlgebra.Matrix.GeneralLinearGroup.Symplectic.Levi
public import EpsilonEridani.LinearAlgebra.Matrix.GeneralLinearGroup.Symplectic.RootGeneration
public import EpsilonEridani.LinearAlgebra.Matrix.GeneralLinearGroup.Symplectic.UnipotentGeneration
public import EpsilonEridani.LinearAlgebra.Matrix.Pivot

/-!
# Gaussian generation of the symplectic group

Over a field, the standard symplectic group is generated by its root subgroups and split torus.
The proof first multiplies a symplectic matrix by an upper unipotent so that its upper-left block
is invertible. On that open cell, block Gaussian elimination gives

```text
[A B; C D] = [1 0; C A⁻¹ 1] [A 0; 0 A⁻ᵀ] [1 A⁻¹B; 0 1].
```

The two off-diagonal blocks are symmetric by the symplectic equations. The outer factors are
therefore generated by the long and sum root subgroups. Ordinary matrix elimination expresses
the middle general-linear Levi factor using difference roots and diagonal Levi elements.

## Main results

* `EpsilonEridani.GLSymplecticFin.exists_gaussian_decomposition_of_isUnit_toBlocks₁₁` is the block
  Gaussian decomposition on the open cell where the upper-left block is invertible.
* `EpsilonEridani.GLSymplecticFin.eq_top_of_root_subgroups_of_diagonal` proves that all standard root
  subgroups together with the diagonal Levi subgroup generate the whole symplectic group.
* `EpsilonEridani.GLSymplecticFin.eq_top_of_adjacent_of_long_of_diagonal` reduces the root hypotheses to
  both orientations of the adjacent difference roots and one positive and negative long root.

## References

* R. W. Carter, *Simple Groups of Lie Type* (1972), §5.2.
* R. Steinberg, *Lectures on Chevalley Groups* (1968), §§3--4.
-/

public section

open Matrix

namespace EpsilonEridani.GLSymplecticFin

universe u

variable {K : Type u} [Field K] {m : ℕ}

/-- A symplectic matrix whose upper-left block is invertible factors as a lower symmetric
unipotent, a general-linear Levi element, and an upper symmetric unipotent. -/
theorem exists_gaussian_decomposition_of_isUnit_toBlocks₁₁
    {R : Type u} [CommRing R]
    (g : GLSymplecticFin m R)
    (hunit : IsUnit (((mulEquivGLSymplectic m R g : GLSymplectic (Fin m) R) :
      GL (Fin m ⊕ Fin m) R) : Matrix (Fin m ⊕ Fin m) (Fin m ⊕ Fin m) R).toBlocks₁₁) :
    ∃ (S T : Matrix (Fin m) (Fin m) R) (P : GL (Fin m) R)
      (hS : S.IsSymm) (hT : T.IsSymm),
        g = lowerUnipotent S hS * leviHom P * upperUnipotent T hT := by
  let M : Matrix (Fin m ⊕ Fin m) (Fin m ⊕ Fin m) R :=
    ((mulEquivGLSymplectic m R g : GLSymplectic (Fin m) R) : GL (Fin m ⊕ Fin m) R)
  let A := M.toBlocks₁₁
  let B := M.toBlocks₁₂
  let C := M.toBlocks₂₁
  let D := M.toBlocks₂₂
  have hM : M ∈ Matrix.symplecticGroup (Fin m) R := by
    simpa only [M] using GLSymplectic.mem_iff_mem_symplecticGroup.mp
      (mulEquivGLSymplectic m R g).property
  have hMblocks : Matrix.fromBlocks A B C D = M := by
    simpa only [A, B, C, D] using M.fromBlocks_toBlocks
  have hblocks : Aᵀ * C = Cᵀ * A ∧ Bᵀ * D = Dᵀ * B ∧ Aᵀ * D - Cᵀ * B = 1 := by
    exact (SymplecticGroup.fromBlocks_mem_iff).mp (hMblocks ▸ hM)
  let P : GL (Fin m) R := Matrix.GeneralLinearGroup.mk'' A
    ((Matrix.isUnit_iff_isUnit_det A).mp hunit)
  set Ainv : Matrix (Fin m) (Fin m) R :=
    ((P⁻¹ : GL (Fin m) R) : Matrix (Fin m) (Fin m) R) with Ainv_def
  have hP : (P : Matrix (Fin m) (Fin m) R) = A := by simp [P]
  have hleft : Ainv * A = 1 := by
    rw [← hP, Ainv_def, ← Matrix.GeneralLinearGroup.coe_mul]
    simp
  have hright : A * Ainv = 1 := by
    rw [← hP, Ainv_def, ← Matrix.GeneralLinearGroup.coe_mul]
    simp
  set S := C * Ainv with S_def
  -- The two symplectic block equations supply the symmetric lower and upper
  -- Gaussian parameters `S = C A⁻¹` and `T = A⁻¹ B`.
  have hS : S.IsSymm := by
    rw [Matrix.IsSymm, S_def, Matrix.transpose_mul]
    calc
      Ainvᵀ * Cᵀ = Ainvᵀ * Cᵀ * (A * Ainv) := by rw [hright, mul_one]
      _ = Ainvᵀ * (Cᵀ * A) * Ainv := by simp only [mul_assoc]
      _ = Ainvᵀ * (Aᵀ * C) * Ainv := by rw [hblocks.1]
      _ = (Ainvᵀ * Aᵀ) * C * Ainv := by simp only [mul_assoc]
      _ = C * Ainv := by rw [← Matrix.transpose_mul, hright, Matrix.transpose_one, one_mul]
  have hdual : A * Bᵀ = B * Aᵀ := by
    have hMt : Matrix.fromBlocks Aᵀ Cᵀ Bᵀ Dᵀ ∈
        Matrix.symplecticGroup (Fin m) R := by
      rw [← Matrix.fromBlocks_transpose, hMblocks]
      exact SymplecticGroup.transpose_mem hM
    simpa only [Matrix.transpose_transpose] using
      (SymplecticGroup.fromBlocks_mem_iff.mp hMt).1
  set T := Ainv * B with T_def
  have hT : T.IsSymm := by
    rw [Matrix.IsSymm, T_def, Matrix.transpose_mul]
    calc
      Bᵀ * Ainvᵀ = (Ainv * A) * Bᵀ * Ainvᵀ := by rw [hleft, one_mul]
      _ = Ainv * (A * Bᵀ) * Ainvᵀ := by simp only [mul_assoc]
      _ = Ainv * (B * Aᵀ) * Ainvᵀ := by rw [hdual]
      _ = Ainv * B * (Aᵀ * Ainvᵀ) := by simp only [mul_assoc]
      _ = Ainv * B := by rw [← Matrix.transpose_mul, hleft, Matrix.transpose_one, mul_one]
  have hAD : Aᵀ * D = 1 + Cᵀ * B := sub_eq_iff_eq_add.mp hblocks.2.2
  have hAinvC : Ainvᵀ * Cᵀ = S := by
    calc
      Ainvᵀ * Cᵀ = Sᵀ := by simp only [S_def, Matrix.transpose_mul]
      _ = S := hS.eq
  have hD : D = S * A * T + Ainvᵀ := by
    calc
      D = (Ainvᵀ * Aᵀ) * D := by rw [← Matrix.transpose_mul, hright,
        Matrix.transpose_one, one_mul]
      _ = Ainvᵀ * (Aᵀ * D) := by rw [mul_assoc]
      _ = Ainvᵀ * (1 + Cᵀ * B) := by rw [hAD]
      _ = Ainvᵀ + (Ainvᵀ * Cᵀ) * B := by noncomm_ring
      _ = Ainvᵀ + S * B := by rw [hAinvC]
      _ = Ainvᵀ + S * A * T := by
        rw [T_def, ← mul_assoc (S * A) Ainv B, mul_assoc S A Ainv,
          hright, mul_one]
      _ = S * A * T + Ainvᵀ := add_comm _ _
  have hAT : A * T = B := by
    rw [T_def, ← mul_assoc, hright, one_mul]
  have hSA : S * A = C := by
    rw [S_def, mul_assoc, hleft, mul_one]
  have hfactor : g = lowerUnipotent S hS * leviHom P * upperUnipotent T hT := by
    apply (mulEquivGLSymplectic m R).injective
    rw [map_mul, map_mul, mulEquivGLSymplectic_leviHom]
    apply Subtype.ext
    simp only [Subgroup.coe_mul]
    apply Units.ext
    -- Here `M` is the local abbreviation for exactly the coerced matrix on the left; this
    -- change only exposes that abbreviation and does not unfold a group or matrix wrapper.
    change M = _
    simp only [Matrix.GeneralLinearGroup.coe_mul, coe_mulEquivGLSymplectic,
      coe_mulEquivGLSymplectic_lowerUnipotent,
      coe_mulEquivGLSymplectic_upperUnipotent, GLSymplectic.coe_ofSymplecticGroup,
      GLSymplectic.coe_leviHom]
    rw [Matrix.fromBlocks_multiply, Matrix.fromBlocks_multiply]
    simp only [Matrix.mul_one, Matrix.mul_zero, Matrix.zero_mul, Matrix.one_mul,
      add_zero, zero_add, hP]
    rw [← hMblocks]
    ext i j
    cases i <;> cases j <;> simp [hAT, hSA, hD, Ainv_def]
  exact ⟨S, T, P, hS, hT, hfactor⟩

/-- A symplectic matrix whose upper-left block is invertible belongs to every subgroup containing
all upper and lower symmetric unipotents and the general-linear Levi subgroup. -/
theorem mem_of_isUnit_toBlocks₁₁
    {R : Type u} [CommRing R]
    (H : Subgroup (GLSymplecticFin m R))
    (hupper : ∀ (B : Matrix (Fin m) (Fin m) R) (hB : B.IsSymm), upperUnipotent B hB ∈ H)
    (hlower : ∀ (C : Matrix (Fin m) (Fin m) R) (hC : C.IsSymm), lowerUnipotent C hC ∈ H)
    (hlevi : ∀ A : GL (Fin m) R, leviHom A ∈ H)
    (g : GLSymplecticFin m R)
    (hunit : IsUnit (((mulEquivGLSymplectic m R g : GLSymplectic (Fin m) R) :
      GL (Fin m ⊕ Fin m) R) : Matrix (Fin m ⊕ Fin m) (Fin m ⊕ Fin m) R).toBlocks₁₁) :
    g ∈ H := by
  obtain ⟨S, T, P, hS, hT, hfactor⟩ :=
    exists_gaussian_decomposition_of_isUnit_toBlocks₁₁ g hunit
  rw [hfactor]
  exact H.mul_mem (H.mul_mem (hlower S hS) (hlevi P)) (hupper T hT)

/-- **All standard symplectic root subgroups and the diagonal Levi subgroup generate the full
symplectic group over a field.** -/
theorem eq_top_of_root_subgroups_of_diagonal
    (H : Subgroup (GLSymplecticFin m K))
    (hroot : ∀ (root : RootSubgroupIndex m) (c : Multiplicative K), root.hom c ∈ H)
    (hdiagonal : ∀ s : Fin m → Kˣ, leviHom (diagGL s) ∈ H) : H = ⊤ := by
  apply eq_top_iff.mpr
  intro g _
  have hdifference : ∀ {i j : Fin m} (hij : i ≠ j) (c : K),
      differenceShortRootUnit hij c ∈ H := by
    intro i j hij c
    simpa only [RootSubgroupIndex.hom_difference, differenceShortRootHom_apply,
      toAdd_ofAdd] using
      hroot (.difference i j hij) (Multiplicative.ofAdd c)
  have hupper : ∀ (B : Matrix (Fin m) (Fin m) K) (hB : B.IsSymm),
      upperUnipotent B hB ∈ H := by
    intro B hB
    exact upperUnipotent_mem_of_root_subgroups H.toSubmonoid
      (fun i c ↦ by
        rw [Subgroup.mem_toSubmonoid]
        simpa only [RootSubgroupIndex.hom_positiveLong,
          positiveLongRootTransvectionHom_apply, toAdd_ofAdd] using
            hroot (.positiveLong i) (Multiplicative.ofAdd c))
      (fun hij c ↦ by
        rw [Subgroup.mem_toSubmonoid]
        simpa only [RootSubgroupIndex.hom_positiveSum, positiveSumShortRootHom_apply,
          toAdd_ofAdd] using
          hroot (.positiveSum _ _ hij) (Multiplicative.ofAdd c)) B hB
  have hlower : ∀ (C : Matrix (Fin m) (Fin m) K) (hC : C.IsSymm),
      lowerUnipotent C hC ∈ H := by
    intro C hC
    exact lowerUnipotent_mem_of_root_subgroups H.toSubmonoid
      (fun i c ↦ by
        rw [Subgroup.mem_toSubmonoid]
        simpa only [RootSubgroupIndex.hom_negativeLong,
          negativeLongRootTransvectionHom_apply, toAdd_ofAdd] using
            hroot (.negativeLong i) (Multiplicative.ofAdd c))
      (fun hij c ↦ by
        rw [Subgroup.mem_toSubmonoid]
        simpa only [RootSubgroupIndex.hom_negativeSum, negativeSumShortRootHom_apply,
          toAdd_ofAdd] using
          hroot (.negativeSum _ _ hij) (Multiplicative.ofAdd c)) C hC
  have hlevi : ∀ A : GL (Fin m) K, leviHom A ∈ H :=
    leviHom_mem_of_difference_of_diagonal H hdifference hdiagonal
  let M : Matrix (Fin m ⊕ Fin m) (Fin m ⊕ Fin m) K :=
    ((mulEquivGLSymplectic m K g : GLSymplectic (Fin m) K) : GL (Fin m ⊕ Fin m) K)
  let A := M.toBlocks₁₁
  let C := M.toBlocks₂₁
  have hM : M ∈ Matrix.symplecticGroup (Fin m) K := by
    simpa only [M] using GLSymplectic.mem_iff_mem_symplecticGroup.mp
      (mulEquivGLSymplectic m K g).property
  have hker (x : Fin m → K) (hAx : A • x = 0) (hCx : C • x = 0) : x = 0 := by
    have hAx' : M.toBlocks₁₁ *ᵥ x = 0 := by
      simpa only [Matrix.smul_eq_mulVec, A] using hAx
    have hCx' : M.toBlocks₂₁ *ᵥ x = 0 := by
      simpa only [Matrix.smul_eq_mulVec, C] using hCx
    have hv : M *ᵥ Sum.elim x 0 = M *ᵥ Sum.elim 0 0 := by
      rw [← M.fromBlocks_toBlocks]
      simp [Matrix.fromBlocks_mulVec, hAx', hCx']
    exact (Sum.elim_eq_iff.mp
      (Matrix.mulVec_injective_iff_isUnit.mpr
        (((mulEquivGLSymplectic m K g : GLSymplectic (Fin m) K) :
          GL (Fin m ⊕ Fin m) K).isUnit) hv)).1
  have hcomm : Aᵀ * C = Cᵀ * A := by
    have hblocks := (SymplecticGroup.fromBlocks_mem_iff).mp
      (M.fromBlocks_toBlocks ▸ hM)
    exact hblocks.1
  obtain ⟨X, hX, hunit⟩ :=
    exists_isSymm_isUnit_add_mul_of_ker_inter_eq_bot_of_transpose_mul_comm hker hcomm
  -- Left multiplication by `[1 X; 0 1]` changes the leading block to `A + XC`.
  have hu : upperUnipotent X hX ∈ H := hupper X hX
  have hprod : upperUnipotent X hX * g ∈ H := by
    apply mem_of_isUnit_toBlocks₁₁ H hupper hlower hlevi
    have hcoeProduct :
        ((((mulEquivGLSymplectic m K) (upperUnipotent X hX * g) :
          GLSymplectic (Fin m) K) : GL (Fin m ⊕ Fin m) K) :
            Matrix (Fin m ⊕ Fin m) (Fin m ⊕ Fin m) K) =
          ((((mulEquivGLSymplectic m K) (upperUnipotent X hX) :
            GLSymplectic (Fin m) K) : GL (Fin m ⊕ Fin m) K) :
              Matrix (Fin m ⊕ Fin m) (Fin m ⊕ Fin m) K) * M := by
      have h := congrArg
        (fun q : GLSymplectic (Fin m) K ↦
          (((q : GL (Fin m ⊕ Fin m) K) : Matrix (Fin m ⊕ Fin m) (Fin m ⊕ Fin m) K)))
        ((mulEquivGLSymplectic m K).map_mul (upperUnipotent X hX) g)
      simpa only [Subgroup.coe_mul, Matrix.GeneralLinearGroup.coe_mul, M] using h
    have htop :
        (((mulEquivGLSymplectic m K (upperUnipotent X hX * g) :
          GLSymplectic (Fin m) K) : GL (Fin m ⊕ Fin m) K) :
            Matrix (Fin m ⊕ Fin m) (Fin m ⊕ Fin m) K).toBlocks₁₁ = A + X * C := by
      rw [hcoeProduct]
      simp only [coe_mulEquivGLSymplectic, coe_mulEquivGLSymplectic_upperUnipotent,
        GLSymplectic.coe_ofSymplecticGroup]
      rw [← M.fromBlocks_toBlocks, Matrix.fromBlocks_multiply]
      simp only [Matrix.one_mul, Matrix.zero_mul, zero_add, A, C,
        Matrix.toBlocks_fromBlocks₁₁]
    rw [htop]
    exact hunit
  have := H.mul_mem (H.inv_mem hu) hprod
  simpa only [inv_mul_cancel_left] using this

/-- Both orientations of the adjacent difference roots, one positive and negative long root,
and the diagonal Levi subgroup generate the full symplectic group over a field. Choosing the
terminal long-root index gives the standard simple-root family of type `C`. -/
theorem eq_top_of_adjacent_of_long_of_diagonal
    (H : Subgroup (GLSymplecticFin m K)) (r : Fin m)
    (hadjacent : ∀ {i j : Fin m} (hij : i ≠ j) (c : K),
      i.val + 1 = j.val ∨ j.val + 1 = i.val → differenceShortRootUnit hij c ∈ H)
    (hpositive : ∀ c : K, positiveLongRootTransvectionUnit r c ∈ H)
    (hnegative : ∀ c : K, negativeLongRootTransvectionUnit r c ∈ H)
    (hdiagonal : ∀ s : Fin m → Kˣ, leviHom (diagGL s) ∈ H) : H = ⊤ := by
  apply eq_top_of_root_subgroups_of_diagonal H _ hdiagonal
  exact RootSubgroupIndex.hom_apply_mem_of_adjacent_of_long H r hadjacent hpositive hnegative

end EpsilonEridani.GLSymplecticFin
