/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.LinearAlgebra.Matrix.GeneralLinearGroup.Symplectic.Basic

/-!
# Symmetric unipotent blocks generated by symplectic root subgroups

The upper and lower unipotent block subgroups of the standard symplectic group consist of

```text
u(B) = [1 B; 0 1],        l(C) = [1 0; C 1]
```

for symmetric matrices `B` and `C`. This file proves that every such element is generated by the
standard type-`C` root subgroups. Diagonal entries are the long roots `±2eᵢ`, while an off-diagonal
symmetric pair is a short sum root `±(eᵢ + eⱼ)`. The proof decomposes a symmetric matrix into its
diagonal entries and its strictly upper-triangular entries together with their transposes.

The result works over every commutative ring, including characteristic two. It is one of the
Gaussian-decomposition steps needed to prove that, over a field, the root subgroups generate the
full symplectic group. That generation theorem identifies the explicit full-weight type-`C`
Kostant carrier with the standard symplectic group on field-valued points.

## Main definitions

* `EpsilonEridani.GLSymplecticFin.upperUnipotent`: the symplectic element with upper-right symmetric
  block `B`.
* `EpsilonEridani.GLSymplecticFin.lowerUnipotent`: the parallel lower-left construction.

## Main results

* `EpsilonEridani.GLSymplecticFin.upperUnipotent_mem_of_root_subgroups`: every upper unipotent belongs
  to a submonoid containing the positive long- and sum-root elements.
* `EpsilonEridani.GLSymplecticFin.lowerUnipotent_mem_of_root_subgroups`: the corresponding submonoid
  statement for negative roots and lower unipotents.

## References

* R. W. Carter, *Simple Groups of Lie Type* (1972), §5.2.
* R. Steinberg, *Lectures on Chevalley Groups* (1968), §§3--4.

This advances the Chevalley--Demazure construction in Layer 9 of the ReductiveGroups roadmap.
The field-valued generation theorem it feeds is needed to identify the type-`C` pinned carrier
consumed by milestone L0 of the CFSGStatement roadmap.
-/

public section

open Matrix

namespace EpsilonEridani.GLSymplecticFin

universe u

variable {R : Type u} [CommRing R] {m : ℕ}

private def unipotentBlock (upper : Bool) (B : Matrix (Fin m) (Fin m) R) :
    Matrix (Fin m ⊕ Fin m) (Fin m ⊕ Fin m) R :=
  if upper then Matrix.fromBlocks 1 B 0 1 else Matrix.fromBlocks 1 0 B 1

private def rootRow (upper : Bool) (i : Fin m) : Fin (m + m) :=
  if upper then finSumFinEquiv (Sum.inl i) else finSumFinEquiv (Sum.inr i)

private def rootColumn (upper : Bool) (j : Fin m) : Fin (m + m) :=
  if upper then finSumFinEquiv (Sum.inr j) else finSumFinEquiv (Sum.inl j)

private theorem unipotentBlock_add (upper : Bool) (B C : Matrix (Fin m) (Fin m) R) :
    unipotentBlock upper (B + C) = unipotentBlock upper B * unipotentBlock upper C := by
  cases upper <;> simp [unipotentBlock, Matrix.fromBlocks_multiply, add_comm]

private theorem unipotentBlock_zero (upper : Bool) :
    unipotentBlock upper (0 : Matrix (Fin m) (Fin m) R) = 1 := by
  cases upper <;> simp [unipotentBlock, Matrix.fromBlocks_one]

private theorem unipotentBlock_map {S : Type*} [CommRing S] (upper : Bool)
    (f : R →+* S) (B : Matrix (Fin m) (Fin m) R) :
    (unipotentBlock upper B).map f = unipotentBlock upper (B.map f) := by
  cases upper <;> simp [unipotentBlock, Matrix.fromBlocks_map]

private theorem unipotentBlock_add_reindex (upper : Bool)
    (B C : Matrix (Fin m) (Fin m) R) :
    (unipotentBlock upper (B + C)).submatrix finSumFinEquiv.symm finSumFinEquiv.symm =
      (unipotentBlock upper B).submatrix finSumFinEquiv.symm finSumFinEquiv.symm *
        (unipotentBlock upper C).submatrix finSumFinEquiv.symm finSumFinEquiv.symm := by
  rw [unipotentBlock_add]
  exact (Matrix.submatrix_mul_equiv _ _ finSumFinEquiv.symm finSumFinEquiv.symm
    finSumFinEquiv.symm).symm

private theorem unipotentBlock_zero_reindex (upper : Bool) :
    (unipotentBlock upper (0 : Matrix (Fin m) (Fin m) R)).submatrix
        finSumFinEquiv.symm finSumFinEquiv.symm = 1 := by
  rw [unipotentBlock_zero, Matrix.submatrix_one_equiv]

private theorem unipotentBlock_map_reindex {S : Type*} [CommRing S] (upper : Bool)
    (f : R →+* S) (B : Matrix (Fin m) (Fin m) R) :
    ((unipotentBlock upper B).submatrix finSumFinEquiv.symm finSumFinEquiv.symm).map f =
      (unipotentBlock upper (B.map f)).submatrix finSumFinEquiv.symm finSumFinEquiv.symm := by
  rw [← Matrix.submatrix_map, unipotentBlock_map]

private theorem unipotentBlock_single (upper : Bool) (i j : Fin m) (c : R) :
    (unipotentBlock upper (Matrix.single i j c)).submatrix
        finSumFinEquiv.symm finSumFinEquiv.symm =
      Matrix.transvection (rootRow upper i) (rootColumn upper j) c := by
  have upper_ne_lower (a b : Fin m) : Fin.castAdd m a ≠ b.addNat m := by
    simpa only [finSumFinEquiv_apply_left, finSumFinEquiv_apply_right,
      Fin.natAdd_eq_addNat] using finSumFinEquiv_inl_ne_inr a b
  have lower_ne_upper (a b : Fin m) : a.addNat m ≠ Fin.castAdd m b := by
    simpa only [finSumFinEquiv_apply_left, finSumFinEquiv_apply_right,
      Fin.natAdd_eq_addNat] using finSumFinEquiv_inr_ne_inl a b
  ext a b
  obtain ⟨a, rfl⟩ := finSumFinEquiv.surjective a
  obtain ⟨b, rfl⟩ := finSumFinEquiv.surjective b
  simp only [Matrix.submatrix_apply, Equiv.symm_apply_apply]
  cases upper <;> cases a <;> cases b <;>
    simp [unipotentBlock, rootRow, rootColumn, Matrix.fromBlocks, Matrix.transvection,
      Matrix.single, Matrix.one_apply, upper_ne_lower, lower_ne_upper]

private theorem unipotentBlock_single_add_transpose (upper : Bool)
    (i j : Fin m) (c : R) :
    (unipotentBlock upper (Matrix.single i j c + Matrix.single j i c)).submatrix
        finSumFinEquiv.symm finSumFinEquiv.symm =
      Matrix.transvection (rootRow upper i) (rootColumn upper j) c *
        Matrix.transvection (rootRow upper j) (rootColumn upper i) c := by
  rw [unipotentBlock_add_reindex, unipotentBlock_single, unipotentBlock_single]

/-! ## Symmetric block elements -/

/-- The upper unitriangular symplectic element with symmetric upper-right block `B`.

The result is transported from `Fin m ⊕ Fin m` coordinates to the `Fin (m + m)` coordinates
used by `EpsilonEridani.GLSymplecticFin`. -/
noncomputable def upperUnipotent (B : Matrix (Fin m) (Fin m) R) (hB : B.IsSymm) :
    GLSymplecticFin m R :=
  (mulEquivGLSymplectic m R).symm
    ((GLSymplectic.mulEquivSymplecticGroup (Fin m) R).symm
      ⟨Matrix.fromBlocks 1 B 0 1, GLSymplectic.fromBlocks_upper_mem B hB.eq⟩)

/-- The lower unitriangular symplectic element with symmetric lower-left block `C`.

The result is transported from `Fin m ⊕ Fin m` coordinates to the `Fin (m + m)` coordinates
used by `EpsilonEridani.GLSymplecticFin`. -/
noncomputable def lowerUnipotent (C : Matrix (Fin m) (Fin m) R) (hC : C.IsSymm) :
    GLSymplecticFin m R :=
  (mulEquivGLSymplectic m R).symm
    ((GLSymplectic.mulEquivSymplecticGroup (Fin m) R).symm
      ⟨Matrix.fromBlocks 1 0 C 1, GLSymplectic.fromBlocks_lower_mem C hC.eq⟩)

/-- In sum coordinates, `upperUnipotent B` is the block matrix `[1 B; 0 1]`. -/
@[simp]
theorem coe_mulEquivGLSymplectic_upperUnipotent (B : Matrix (Fin m) (Fin m) R)
    (hB : B.IsSymm) :
    Equiv.reindexGL finSumFinEquiv.symm R
        ((upperUnipotent B hB : GLSymplecticFin m R) : GL (Fin (m + m)) R) =
      GLSymplectic.ofSymplecticGroup (Fin m) R
        ⟨Matrix.fromBlocks 1 B 0 1, GLSymplectic.fromBlocks_upper_mem B hB.eq⟩ := by
  rw [← coe_mulEquivGLSymplectic]
  apply Matrix.GeneralLinearGroup.ext
  intro i j
  rw [← GLSymplectic.coe_mulEquivSymplecticGroup]
  simp [upperUnipotent]

/-- In sum coordinates, `lowerUnipotent C` is the block matrix `[1 0; C 1]`. -/
@[simp]
theorem coe_mulEquivGLSymplectic_lowerUnipotent (C : Matrix (Fin m) (Fin m) R)
    (hC : C.IsSymm) :
    Equiv.reindexGL finSumFinEquiv.symm R
        ((lowerUnipotent C hC : GLSymplecticFin m R) : GL (Fin (m + m)) R) =
      GLSymplectic.ofSymplecticGroup (Fin m) R
        ⟨Matrix.fromBlocks 1 0 C 1, GLSymplectic.fromBlocks_lower_mem C hC.eq⟩ := by
  rw [← coe_mulEquivGLSymplectic]
  apply Matrix.GeneralLinearGroup.ext
  intro i j
  rw [← GLSymplectic.coe_mulEquivSymplecticGroup]
  simp [lowerUnipotent]

/-- The entries of an upper unipotent are the entries of the block matrix `[1 B; 0 1]`. -/
@[simp]
theorem upperUnipotent_apply (B : Matrix (Fin m) (Fin m) R) (hB : B.IsSymm)
    (i j : Fin m ⊕ Fin m) :
    (((upperUnipotent B hB : GLSymplecticFin m R) : GL (Fin (m + m)) R) :
        Matrix (Fin (m + m)) (Fin (m + m)) R) (finSumFinEquiv i) (finSumFinEquiv j) =
      Matrix.fromBlocks 1 B 0 1 i j := by
  have h := congrArg
    (fun M : GL (Fin m ⊕ Fin m) R => (M : Matrix (Fin m ⊕ Fin m) (Fin m ⊕ Fin m) R) i j)
    (coe_mulEquivGLSymplectic_upperUnipotent B hB)
  simpa only [Equiv.coe_reindexGL, Equiv.symm_symm, Matrix.submatrix_apply,
    GLSymplectic.coe_ofSymplecticGroup] using h

/-- The entries of a lower unipotent are the entries of the block matrix `[1 0; C 1]`. -/
@[simp]
theorem lowerUnipotent_apply (C : Matrix (Fin m) (Fin m) R) (hC : C.IsSymm)
    (i j : Fin m ⊕ Fin m) :
    (((lowerUnipotent C hC : GLSymplecticFin m R) : GL (Fin (m + m)) R) :
        Matrix (Fin (m + m)) (Fin (m + m)) R) (finSumFinEquiv i) (finSumFinEquiv j) =
      Matrix.fromBlocks 1 0 C 1 i j := by
  have h := congrArg
    (fun M : GL (Fin m ⊕ Fin m) R => (M : Matrix (Fin m ⊕ Fin m) (Fin m ⊕ Fin m) R) i j)
    (coe_mulEquivGLSymplectic_lowerUnipotent C hC)
  simpa only [Equiv.coe_reindexGL, Equiv.symm_symm, Matrix.submatrix_apply,
    GLSymplectic.coe_ofSymplecticGroup] using h

/-- The underlying matrix of an upper unipotent is `[1 B; 0 1]`, reindexed by
`finSumFinEquiv`. -/
@[simp]
theorem coe_upperUnipotent (B : Matrix (Fin m) (Fin m) R) (hB : B.IsSymm) :
    (((upperUnipotent B hB : GLSymplecticFin m R) : GL (Fin (m + m)) R) :
        Matrix (Fin (m + m)) (Fin (m + m)) R) =
      (Matrix.fromBlocks 1 B 0 1).submatrix finSumFinEquiv.symm finSumFinEquiv.symm := by
  ext i j
  obtain ⟨i, rfl⟩ := finSumFinEquiv.surjective i
  obtain ⟨j, rfl⟩ := finSumFinEquiv.surjective j
  simp

/-- The underlying matrix of a lower unipotent is `[1 0; C 1]`, reindexed by
`finSumFinEquiv`. -/
@[simp]
theorem coe_lowerUnipotent (C : Matrix (Fin m) (Fin m) R) (hC : C.IsSymm) :
    (((lowerUnipotent C hC : GLSymplecticFin m R) : GL (Fin (m + m)) R) :
        Matrix (Fin (m + m)) (Fin (m + m)) R) =
      (Matrix.fromBlocks 1 0 C 1).submatrix finSumFinEquiv.symm finSumFinEquiv.symm := by
  ext i j
  obtain ⟨i, rfl⟩ := finSumFinEquiv.surjective i
  obtain ⟨j, rfl⟩ := finSumFinEquiv.surjective j
  simp

/-- Equality of upper unipotents is equivalent to equality of their symmetric blocks. -/
@[simp]
theorem upperUnipotent_inj (B C : Matrix (Fin m) (Fin m) R)
    (hB : B.IsSymm) (hC : C.IsSymm) :
    upperUnipotent B hB = upperUnipotent C hC ↔ B = C := by
  constructor
  · intro h
    ext i j
    have hij := congrArg
      (fun g : GLSymplecticFin m R =>
        (((g : GL (Fin (m + m)) R) : Matrix (Fin (m + m)) (Fin (m + m)) R)
          (finSumFinEquiv (Sum.inl i)) (finSumFinEquiv (Sum.inr j)))) h
    rw [upperUnipotent_apply, upperUnipotent_apply] at hij
    simpa using hij
  · rintro rfl
    rfl

/-- Equality of lower unipotents is equivalent to equality of their symmetric blocks. -/
@[simp]
theorem lowerUnipotent_inj (B C : Matrix (Fin m) (Fin m) R)
    (hB : B.IsSymm) (hC : C.IsSymm) :
    lowerUnipotent B hB = lowerUnipotent C hC ↔ B = C := by
  constructor
  · intro h
    ext i j
    have hij := congrArg
      (fun g : GLSymplecticFin m R =>
        (((g : GL (Fin (m + m)) R) : Matrix (Fin (m + m)) (Fin (m + m)) R)
          (finSumFinEquiv (Sum.inr i)) (finSumFinEquiv (Sum.inl j)))) h
    rw [lowerUnipotent_apply, lowerUnipotent_apply] at hij
    simpa using hij
  · rintro rfl
    rfl

/-- Upper unipotents commute with change of coefficient ring. -/
@[simp]
theorem map_upperUnipotent {S : Type*} [CommRing S] (f : R →+* S)
    (B : Matrix (Fin m) (Fin m) R) (hB : B.IsSymm) :
    GLSymplecticFin.map m R f (upperUnipotent B hB) =
      upperUnipotent (B.map f) (hB.map f) := by
  apply Subtype.ext
  apply Matrix.GeneralLinearGroup.ext
  intro i j
  simp only [GLSymplecticFin.coe_map, Matrix.GeneralLinearGroup.map_apply]
  rw [coe_upperUnipotent, coe_upperUnipotent]
  exact congrFun (congrFun (unipotentBlock_map_reindex true f B) i) j

/-- Lower unipotents commute with change of coefficient ring. -/
@[simp]
theorem map_lowerUnipotent {S : Type*} [CommRing S] (f : R →+* S)
    (C : Matrix (Fin m) (Fin m) R) (hC : C.IsSymm) :
    GLSymplecticFin.map m R f (lowerUnipotent C hC) =
      lowerUnipotent (C.map f) (hC.map f) := by
  apply Subtype.ext
  apply Matrix.GeneralLinearGroup.ext
  intro i j
  simp only [GLSymplecticFin.coe_map, Matrix.GeneralLinearGroup.map_apply]
  rw [coe_lowerUnipotent, coe_lowerUnipotent]
  exact congrFun (congrFun (unipotentBlock_map_reindex false f C) i) j

/-- Upper unipotent blocks turn addition of symmetric matrices into multiplication. -/
@[simp]
theorem upperUnipotent_add (B C : Matrix (Fin m) (Fin m) R)
    (hB : B.IsSymm) (hC : C.IsSymm) :
    upperUnipotent (B + C) (hB.add hC) = upperUnipotent B hB * upperUnipotent C hC := by
  refine Subtype.ext (Units.ext ?_)
  rw [Subgroup.coe_mul, Units.val_mul, coe_upperUnipotent, coe_upperUnipotent,
    coe_upperUnipotent]
  exact unipotentBlock_add_reindex true B C

/-- Lower unipotent blocks turn addition of symmetric matrices into multiplication. -/
@[simp]
theorem lowerUnipotent_add (B C : Matrix (Fin m) (Fin m) R)
    (hB : B.IsSymm) (hC : C.IsSymm) :
    lowerUnipotent (B + C) (hB.add hC) = lowerUnipotent B hB * lowerUnipotent C hC := by
  refine Subtype.ext (Units.ext ?_)
  rw [Subgroup.coe_mul, Units.val_mul, coe_lowerUnipotent, coe_lowerUnipotent,
    coe_lowerUnipotent]
  exact unipotentBlock_add_reindex false B C

/-- The upper unipotent attached to the zero matrix is the identity. -/
@[simp]
theorem upperUnipotent_zero :
    upperUnipotent (0 : Matrix (Fin m) (Fin m) R) Matrix.isSymm_zero = 1 := by
  refine Subtype.ext (Units.ext ?_)
  rw [Subgroup.coe_one, Units.val_one, coe_upperUnipotent]
  exact unipotentBlock_zero_reindex true

/-- The lower unipotent attached to the zero matrix is the identity. -/
@[simp]
theorem lowerUnipotent_zero :
    lowerUnipotent (0 : Matrix (Fin m) (Fin m) R) Matrix.isSymm_zero = 1 := by
  refine Subtype.ext (Units.ext ?_)
  rw [Subgroup.coe_one, Units.val_one, coe_lowerUnipotent]
  exact unipotentBlock_zero_reindex false

/-- The inverse of an upper unipotent is the upper unipotent of the negated block. -/
@[simp]
theorem inv_upperUnipotent (B : Matrix (Fin m) (Fin m) R) (hB : B.IsSymm) :
    (upperUnipotent B hB)⁻¹ = upperUnipotent (-B) hB.neg := by
  refine inv_eq_of_mul_eq_one_right ?_
  rw [← upperUnipotent_add]
  simp

/-- The inverse of a lower unipotent is the lower unipotent of the negated block. -/
@[simp]
theorem inv_lowerUnipotent (C : Matrix (Fin m) (Fin m) R) (hC : C.IsSymm) :
    (lowerUnipotent C hC)⁻¹ = lowerUnipotent (-C) hC.neg := by
  refine inv_eq_of_mul_eq_one_right ?_
  rw [← lowerUnipotent_add]
  simp

/-! ## Root matrices -/

/-- A diagonal upper unipotent summand is a positive long-root element. -/
@[simp]
theorem upperUnipotent_single_self (i : Fin m) (c : R) :
    upperUnipotent (Matrix.single i i c) (by simp [Matrix.IsSymm]) =
      positiveLongRootTransvectionUnit i c := by
  apply Subtype.ext
  apply Matrix.GeneralLinearGroup.ext
  intro a b
  rw [coe_upperUnipotent, coe_positiveLongRootTransvectionUnit, coe_transvectionUnit]
  simpa only [unipotentBlock, rootRow, rootColumn, Bool.true_eq, ite_true] using
    congrFun (congrFun (unipotentBlock_single true i i c) a) b

/-- A diagonal lower unipotent summand is a negative long-root element. -/
@[simp]
theorem lowerUnipotent_single_self (i : Fin m) (c : R) :
    lowerUnipotent (Matrix.single i i c) (by simp [Matrix.IsSymm]) =
      negativeLongRootTransvectionUnit i c := by
  apply Subtype.ext
  apply Matrix.GeneralLinearGroup.ext
  intro a b
  rw [coe_lowerUnipotent, coe_negativeLongRootTransvectionUnit, coe_transvectionUnit]
  simpa only [unipotentBlock, rootRow, rootColumn, Bool.false_eq_true, ite_false] using
    congrFun (congrFun (unipotentBlock_single false i i c) a) b

/-- An off-diagonal symmetric upper unipotent summand is a positive sum-root element. -/
@[simp]
theorem upperUnipotent_single_add_transpose {i j : Fin m} (hij : i ≠ j) (c : R) :
    upperUnipotent (Matrix.single i j c + Matrix.single j i c) (by
      simp [Matrix.IsSymm, add_comm]) = positiveSumShortRootUnit hij c := by
  apply Subtype.ext
  apply Matrix.GeneralLinearGroup.ext
  intro a b
  rw [coe_upperUnipotent, coe_positiveSumShortRootUnit]
  simp only [Units.val_mul, coe_transvectionUnit]
  exact congrFun (congrFun (unipotentBlock_single_add_transpose true i j c) a) b

/-- An off-diagonal symmetric lower unipotent summand is a negative sum-root element. -/
@[simp]
theorem lowerUnipotent_single_add_transpose {i j : Fin m} (hij : i ≠ j) (c : R) :
    lowerUnipotent (Matrix.single i j c + Matrix.single j i c) (by
      simp [Matrix.IsSymm, add_comm]) = negativeSumShortRootUnit hij c := by
  apply Subtype.ext
  apply Matrix.GeneralLinearGroup.ext
  intro a b
  rw [coe_lowerUnipotent, coe_negativeSumShortRootUnit]
  simp only [Units.val_mul, coe_transvectionUnit]
  exact congrFun (congrFun (unipotentBlock_single_add_transpose false i j c) a) b

/-! ## Generation -/

private def strictUpperPart (B : Matrix (Fin m) (Fin m) R) : Matrix (Fin m) (Fin m) R :=
  ∑ i, ∑ j ∈ Finset.Ioi i, Matrix.single i j (B i j)

private theorem strictUpperPart_apply (B : Matrix (Fin m) (Fin m) R) (a b : Fin m) :
    strictUpperPart B a b = if a < b then B a b else 0 := by
  simp only [strictUpperPart, Matrix.sum_apply]
  rw [Finset.sum_eq_single a]
  · by_cases hab : a < b
    · rw [Finset.sum_eq_single b]
      · simp [Matrix.single, hab]
      · intro j _ hjb
        simp [Matrix.single, hjb]
      · intro hba
        exact (hba (by simpa using hab)).elim
    · simp only [hab, ↓reduceIte]
      apply Finset.sum_eq_zero
      intro j hj
      have hjb : j ≠ b := by
        intro hjb
        exact hab (by simpa [hjb] using hj)
      simp [Matrix.single, hjb]
  · intro i _ hia
    apply Finset.sum_eq_zero
    intro j _
    simp [Matrix.single, hia]
  · simp

private theorem symmetric_eq_sum_diagonal_add_sum_pairs
    (B : Matrix (Fin m) (Fin m) R) (hB : B.IsSymm) :
    B = (∑ i, Matrix.single i i (B i i)) +
      ∑ i, ∑ j ∈ Finset.Ioi i,
        (Matrix.single i j (B i j) + Matrix.single j i (B i j)) := by
  have hpairs :
      (∑ i, ∑ j ∈ Finset.Ioi i,
          (Matrix.single i j (B i j) + Matrix.single j i (B i j))) =
        strictUpperPart B + (strictUpperPart B)ᵀ := by
    simp only [strictUpperPart, Finset.sum_add_distrib]
    congr 1
    symm
    rw [Matrix.transpose_sum]
    apply Finset.sum_congr rfl
    intro i _
    rw [Matrix.transpose_sum]
    apply Finset.sum_congr rfl
    intro j _
    simp
  rw [hpairs, Matrix.sum_single_eq_diagonal]
  apply Matrix.ext
  intro a b
  rw [Matrix.add_apply, Matrix.diagonal_apply, Matrix.add_apply,
    strictUpperPart_apply, Matrix.transpose_apply, strictUpperPart_apply]
  rcases lt_trichotomy a b with hab | rfl | hba
  · simp [hab, hab.not_gt, hab.ne]
  · simp
  · simp [hba, hba.not_gt, hba.ne.symm, hB.apply b a]

private theorem isSymm_sum {ι : Type*} (s : Finset ι)
    (A : ι → Matrix (Fin m) (Fin m) R) (hA : ∀ i ∈ s, (A i).IsSymm) :
    (∑ i ∈ s, A i).IsSymm := by
  rw [Matrix.IsSymm, Matrix.transpose_sum]
  apply Finset.sum_congr rfl
  intro i hi
  exact (hA i hi).eq

private theorem unipotent_sum_mem {ι : Type*}
    (U : (B : Matrix (Fin m) (Fin m) R) → B.IsSymm → GLSymplecticFin m R)
    (hzero : U 0 Matrix.isSymm_zero = 1)
    (hadd : ∀ (B C : Matrix (Fin m) (Fin m) R) (hB : B.IsSymm) (hC : C.IsSymm),
      U (B + C) (hB.add hC) = U B hB * U C hC)
    (H : Submonoid (GLSymplecticFin m R)) (s : Finset ι)
    (A : ι → Matrix (Fin m) (Fin m) R) (hA : ∀ i ∈ s, (A i).IsSymm)
    (hmem : ∀ (i) (hi : i ∈ s), U (A i) (hA i hi) ∈ H) :
    U (∑ i ∈ s, A i) (isSymm_sum s A hA) ∈ H := by
  classical
  induction s using Finset.induction_on with
  | empty => simpa only [Finset.sum_empty, hzero] using H.one_mem
  | @insert a s ha ih =>
      have haA : (A a).IsSymm := hA a (Finset.mem_insert_self a s)
      have hsA : ∀ i ∈ s, (A i).IsSymm := fun i hi ↦ hA i (Finset.mem_insert_of_mem hi)
      have hsa : U (A a) haA ∈ H :=
        hmem a (Finset.mem_insert_self a s)
      have hss : U (∑ i ∈ s, A i) (isSymm_sum s A hsA) ∈ H :=
        ih hsA (fun i hi ↦ hmem i (Finset.mem_insert_of_mem hi))
      have hprod := H.mul_mem hsa hss
      rw [← hadd] at hprod
      simpa only [Finset.sum_insert ha] using hprod

private theorem unipotent_mem_of_root_subgroups
    (U : (B : Matrix (Fin m) (Fin m) R) → B.IsSymm → GLSymplecticFin m R)
    (hzero : U 0 Matrix.isSymm_zero = 1)
    (hadd : ∀ (B C : Matrix (Fin m) (Fin m) R) (hB : B.IsSymm) (hC : C.IsSymm),
      U (B + C) (hB.add hC) = U B hB * U C hC)
    (H : Submonoid (GLSymplecticFin m R))
    (hDiagonal : ∀ (i : Fin m) (c : R),
      U (Matrix.single i i c) (by simp [Matrix.IsSymm]) ∈ H)
    (hPair : ∀ {i j : Fin m} (_hij : i < j) (c : R),
      U (Matrix.single i j c + Matrix.single j i c) (by
        simp [Matrix.IsSymm, add_comm]) ∈ H)
    (B : Matrix (Fin m) (Fin m) R) (hB : B.IsSymm) : U B hB ∈ H := by
  classical
  let D (i : Fin m) := Matrix.single i i (B i i)
  let P (i j : Fin m) := Matrix.single i j (B i j) + Matrix.single j i (B i j)
  have hD (i : Fin m) : (D i).IsSymm := by
    simp [D, Matrix.IsSymm]
  have hP (i j : Fin m) : (P i j).IsSymm := by
    simp [P, Matrix.IsSymm, add_comm]
  have hdiag :
      U (∑ i ∈ Finset.univ, D i)
        (isSymm_sum Finset.univ D (fun i _ ↦ hD i)) ∈ H :=
    unipotent_sum_mem U hzero hadd H Finset.univ D (fun i _ ↦ hD i) (fun i _ ↦ by
      simpa [D] using hDiagonal i (B i i))
  have hpair (i : Fin m) :
      U (∑ j ∈ Finset.Ioi i, P i j)
        (isSymm_sum (Finset.Ioi i) (P i) (fun j _ ↦ hP i j)) ∈ H :=
    unipotent_sum_mem U hzero hadd H (Finset.Ioi i) (P i) (fun j _ ↦ hP i j)
      (fun j hj ↦ by
        have hij : i < j := by simpa using hj
        simpa [P] using hPair hij (B i j))
  have hpairs :
      U (∑ i ∈ Finset.univ, ∑ j ∈ Finset.Ioi i, P i j)
        (isSymm_sum Finset.univ (fun i ↦ ∑ j ∈ Finset.Ioi i, P i j)
          (fun i _ ↦ isSymm_sum (Finset.Ioi i) (P i) (fun j _ ↦ hP i j))) ∈ H :=
    unipotent_sum_mem U hzero hadd H Finset.univ
      (fun i ↦ ∑ j ∈ Finset.Ioi i, P i j)
      (fun i _ ↦ isSymm_sum (Finset.Ioi i) (P i) (fun j _ ↦ hP i j))
      (fun i _ ↦ hpair i)
  have htotal := H.mul_mem hdiag hpairs
  rw [← hadd] at htotal
  have hdecomp := symmetric_eq_sum_diagonal_add_sum_pairs B hB
  simpa only [D, P, ← hdecomp] using htotal

/-- Every upper unipotent block belongs to a submonoid containing the positive long- and
sum-root elements for canonically ordered pairs. -/
theorem upperUnipotent_mem_of_root_subgroups (H : Submonoid (GLSymplecticFin m R))
    (hLong : ∀ (i : Fin m) (c : R), positiveLongRootTransvectionUnit i c ∈ H)
    (hSum : ∀ {i j : Fin m} (hij : i < j) (c : R),
      positiveSumShortRootUnit hij.ne c ∈ H)
    (B : Matrix (Fin m) (Fin m) R) (hB : B.IsSymm) : upperUnipotent B hB ∈ H := by
  apply unipotent_mem_of_root_subgroups upperUnipotent upperUnipotent_zero upperUnipotent_add H
  · intro i c
    simpa using hLong i c
  · intro i j hij c
    rw [upperUnipotent_single_add_transpose hij.ne]
    exact hSum hij c

/-- Every lower unipotent block belongs to a submonoid containing the negative long- and
sum-root elements for canonically ordered pairs. -/
theorem lowerUnipotent_mem_of_root_subgroups (H : Submonoid (GLSymplecticFin m R))
    (hLong : ∀ (i : Fin m) (c : R), negativeLongRootTransvectionUnit i c ∈ H)
    (hSum : ∀ {i j : Fin m} (hij : i < j) (c : R),
      negativeSumShortRootUnit hij.ne c ∈ H)
    (B : Matrix (Fin m) (Fin m) R) (hB : B.IsSymm) : lowerUnipotent B hB ∈ H := by
  apply unipotent_mem_of_root_subgroups lowerUnipotent lowerUnipotent_zero lowerUnipotent_add H
  · intro i c
    simpa using hLong i c
  · intro i j hij c
    rw [lowerUnipotent_single_add_transpose hij.ne]
    exact hSum hij c

end EpsilonEridani.GLSymplecticFin
