/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.NumberTheory.Multiquadratic.Quadratic.Ramification
public import EpsilonEridani.NumberTheory.NumberField.Quadratic.RamifiedPrimesClassGroup
import EpsilonEridani.Algebra.Group.Subgroup.TwoTorsionClosure
import Mathlib.Data.Nat.Squarefree
import Mathlib.Algebra.GroupWithZero.Torsion

/-!
# The relation between the ramified primes of a quadratic field

Let `K = ℚ(√d)` be a quadratic number field, presented by `θ : 𝓞 K` with
`minpoly ℤ θ = X ^ 2 - d` and `Algebra.adjoin ℚ {θ} = ⊤`, with `d` squarefree. Every rational
prime `p` dividing `d` ramifies, so `p 𝓞 K = 𝔭 ^ 2` for the unique prime `𝔭` of `𝓞 K` above it
(`EpsilonEridani.Multiquadratic.map_span_eq_sq_of_dvd_fundamentalDiscriminant`). Squaring the principal
ideal `(θ)` gives `(d)`, which is the product of those `p 𝓞 K`; cancelling the square in the
factorisation monoid of ideals leaves

`(θ) = ∏_{p ∣ d} 𝔭_p`.

This is an explicit relation of genus theory. The classes `[𝔭_p]` of the ramified primes are
`2`-torsion (`NumberField.classGroupMk0_sq_eq_one_of_mem_ramifiedPrimes`), so they span an
elementary-`2` subgroup of `Cl(𝓞 K)`, a priori of order at most `2 ^ t` with `t` the number
of ramified primes (`ncard_ramifiedPrimes_eq_card`). The identity above says that the product of
those spanning classes over `p ∣ d` is trivial, so they are generated by all but one prime factor
of `d` and span at most `2 ^ (t - 1)` classes. The matching lower bound is not proved here. In the
`2`-rank
formula `rank = t - 1` of the Multiquadratic roadmap this is where the `- 1` comes from; for real
quadratic fields that exact formula concerns the narrow class group, while this file only gives an
upper bound in the ordinary class group.

Because the ramified primes are exactly those dividing `fundamentalDiscriminant d`, which is `d`
or `4 * d`, the product here runs over `p ∣ d`. It covers all ramified primes unless
`d ≡ 3 (mod 4)`, in which case exactly the ramified prime `2` is omitted. That is why the counting
statement takes the ambient set of ramified primes as a parameter `s` and only asks that it contain
the prime factors of `d`: the relation lives on the prime factors of the radicand, while the classes
being counted are those of all the ramified primes.

The primes above the rational primes involved may be supplied by the caller as a family (`P` for
the ideal identity, `Q` for the class-group statements). The theorem
`exists_span_singleton_eq_prod_primeFactors` also chooses a family with the nonzero-divisor
packaging needed by `ClassGroup.mk0`.

The classical source for the relation and its use in genus theory is D. A. Cox, *Primes of the Form
x² + ny²*, Chapter 3, and F. Lemmermeyer, *Reciprocity Laws*, Chapter 6.

## Main results

* `EpsilonEridani.Multiquadratic.mem_ramifiedPrimes_of_mem_primeFactors`: a prime factor of the radicand
  ramifies.
* `EpsilonEridani.Multiquadratic.span_singleton_eq_prod_primeFactors`: `(θ) = ∏_{p ∣ d} 𝔭_p`.
* `EpsilonEridani.Multiquadratic.exists_span_singleton_eq_prod_primeFactors`: a family of primes above
  the prime factors of `d` exists and satisfies this identity.
* `EpsilonEridani.Multiquadratic.prod_classGroupMk0_eq_one`: the product of the classes `[𝔭_p]` over the
  prime factors of `d` is trivial in `Cl(𝓞 K)`.
* `EpsilonEridani.Multiquadratic.prod_classGroupMk0_eq_prod_sdiff`: consequently the class of a
  sub-product is the class of its complementary sub-product.
* `EpsilonEridani.Multiquadratic.natCard_closure_image_classGroupMk0_le`: the subgroup generated by the
  classes of the ramified primes has at most `2 ^ (t - 1)` elements.
-/

public section

open Polynomial
open scoped NumberField nonZeroDivisors
open NumberField (ramifiedPrimes)

namespace EpsilonEridani.Multiquadratic

variable {K : Type*} [Field K] [NumberField K] {θ : 𝓞 K} {d : ℤ}

/-- A prime factor of the radicand divides the field discriminant `fundamentalDiscriminant d`,
which is `d` or `4 * d`. -/
private theorem dvd_fundamentalDiscriminant_of_mem_primeFactors {p : ℕ}
    (hp : p ∈ d.natAbs.primeFactors) : (p : ℤ) ∣ fundamentalDiscriminant d := by
  obtain ⟨c, -, hc⟩ := exists_sq_mul_eq_fundamentalDiscriminant d
  refine hc ▸ Dvd.dvd.mul_left ?_ _
  exact (Int.natCast_dvd_natCast.mpr (Nat.dvd_of_mem_primeFactors hp)).trans
    (Int.natAbs_dvd.mpr dvd_rfl)

/-- A prime factor of the radicand is a ramified prime of `ℚ(√d)`. -/
theorem mem_ramifiedPrimes_of_mem_primeFactors (hmin : minpoly ℤ θ = X ^ 2 - C d)
    (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤) (hsf : Squarefree d) {p : ℕ}
    (hp : p ∈ d.natAbs.primeFactors) : p ∈ ramifiedPrimes K :=
  (mem_ramifiedPrimes_iff_dvd_fundamentalDiscriminant hmin hgen hsf
    (Nat.prime_of_mem_primeFactors hp)).mpr (dvd_fundamentalDiscriminant_of_mem_primeFactors hp)

/-- **The square root of the radicand generates the product of the ramified primes dividing it.**
Let `K = ℚ(√d)` with `d` squarefree, and for every prime factor `p` of `d` let `P p` be the prime
of `𝓞 K` above `p`. Then the principal ideal generated by `θ` is the product of those primes:

`(θ) = ∏_{p ∣ d} 𝔭_p`.

Squaring both sides gives `(d) = ∏_p p 𝓞 K`, which holds because `p 𝓞 K = 𝔭_p ^ 2` at every
ramified prime and `d` is squarefree; the ideals of a Dedekind domain form a factorisation monoid
with no `2`-torsion, so the squares may be cancelled. -/
theorem span_singleton_eq_prod_primeFactors (hmin : minpoly ℤ θ = X ^ 2 - C d)
    (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤) (hsf : Squarefree d) (P : ℕ → Ideal (𝓞 K))
    (hprime : ∀ p ∈ d.natAbs.primeFactors, (P p).IsPrime)
    (hover : ∀ p ∈ d.natAbs.primeFactors, (P p).LiesOver (Ideal.span {(p : ℤ)})) :
    Ideal.span {θ} = ∏ p ∈ d.natAbs.primeFactors, P p := by
  -- `θ` squares to `d`, so `(θ) ^ 2 = (d)`.
  have hθ : θ ^ 2 = algebraMap ℤ (𝓞 K) d := NumberField.gen_sq hmin
  -- At a prime factor `p` of `d`, `p 𝓞 K = 𝔭_p ^ 2`.
  have hsq : ∀ p ∈ d.natAbs.primeFactors,
      P p ^ 2 = Ideal.span {algebraMap ℤ (𝓞 K) (p : ℤ)} := by
    intro p hp
    have := hprime p hp
    have := hover p hp
    rw [← map_span_eq_sq_of_dvd_fundamentalDiscriminant hmin hgen hsf
      (Nat.prime_of_mem_primeFactors hp) (dvd_fundamentalDiscriminant_of_mem_primeFactors hp),
      Ideal.map_span, Set.image_singleton]
  -- The product of the prime factors of `d` is `|d|`, since `d` is squarefree.
  have hprod : ∏ p ∈ d.natAbs.primeFactors, algebraMap ℤ (𝓞 K) (p : ℤ) =
      algebraMap ℤ (𝓞 K) (d.natAbs : ℤ) := by
    rw [← map_prod, ← Nat.cast_prod,
      Nat.prod_primeFactors_of_squarefree (Int.squarefree_natAbs.mpr hsf)]
  -- `d` and `|d|` differ by a sign, so they generate the same ideal.
  have hsign : Ideal.span {algebraMap ℤ (𝓞 K) d} =
      Ideal.span {algebraMap ℤ (𝓞 K) (d.natAbs : ℤ)} := by
    rcases Int.natAbs_eq d with h | h
    · rw [← h]
    · have hmap_neg : algebraMap ℤ (𝓞 K) d =
          -algebraMap ℤ (𝓞 K) (d.natAbs : ℤ) := by
        rw [← map_neg]
        exact congrArg _ h
      rw [hmap_neg, Ideal.span_singleton_neg]
  -- Hence both sides have the same square.
  have key : Ideal.span {θ} ^ 2 = (∏ p ∈ d.natAbs.primeFactors, P p) ^ 2 := by
    rw [← Finset.prod_pow, Finset.prod_congr rfl hsq, Ideal.prod_span_singleton, hprod,
      Ideal.span_singleton_pow, hθ, hsign]
  exact pow_left_injective two_ne_zero key

/-- There is a family of prime ideals above the prime factors of `d` for which the square root
relation holds. The ideals are packaged as non-zero-divisors, so the same family can be used in
the class-group results below. -/
theorem exists_span_singleton_eq_prod_primeFactors (hmin : minpoly ℤ θ = X ^ 2 - C d)
    (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤) (hsf : Squarefree d) :
    ∃ Q : (ℕ → (Ideal (𝓞 K))⁰),
      (∀ p ∈ d.natAbs.primeFactors, (Q p : Ideal (𝓞 K)).IsPrime) ∧
      (∀ p ∈ d.natAbs.primeFactors,
        (Q p : Ideal (𝓞 K)).LiesOver (Ideal.span {(p : ℤ)})) ∧
      Ideal.span {θ} = ∏ p ∈ d.natAbs.primeFactors, (Q p : Ideal (𝓞 K)) := by
  obtain ⟨Q, hprime, hover⟩ := NumberField.exists_primeIdealFamily (K := K) d.natAbs.primeFactors
    (fun _ hp ↦ Nat.prime_of_mem_primeFactors hp)
  exact ⟨Q, hprime, hover,
    span_singleton_eq_prod_primeFactors hmin hgen hsf _ hprime hover⟩

variable (Q : ℕ → (Ideal (𝓞 K))⁰)

/-- **An explicit relation of genus theory.** In `Cl(𝓞 K)` for `K = ℚ(√d)` with `d` squarefree, the
product of the classes of the primes above the prime factors of `d` is trivial: their product is
the principal ideal `(θ)` by `span_singleton_eq_prod_primeFactors`.

Together with the fact that each such class is `2`-torsion
(`NumberField.classGroupMk0_sq_eq_one_of_mem_ramifiedPrimes`) this bounds the elementary-2 subgroup
they span by `2 ^ (t - 1)` elements. -/
theorem prod_classGroupMk0_eq_one (hmin : minpoly ℤ θ = X ^ 2 - C d)
    (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤) (hsf : Squarefree d)
    (hprime : ∀ p ∈ d.natAbs.primeFactors, (Q p : Ideal (𝓞 K)).IsPrime)
    (hover : ∀ p ∈ d.natAbs.primeFactors, (Q p : Ideal (𝓞 K)).LiesOver (Ideal.span {(p : ℤ)})) :
    ∏ p ∈ d.natAbs.primeFactors, ClassGroup.mk0 (Q p) = 1 := by
  rw [← map_prod, ClassGroup.mk0_eq_one_iff (∏ p ∈ d.natAbs.primeFactors, Q p).2,
    Submonoid.coe_finsetProd,
    ← span_singleton_eq_prod_primeFactors hmin hgen hsf _ hprime hover]
  exact ⟨θ, rfl⟩

private theorem classGroupMk0_sq_eq_one (hmin : minpoly ℤ θ = X ^ 2 - C d)
    (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤) {p : ℕ} (hram : p ∈ ramifiedPrimes K)
    [(Q p : Ideal (𝓞 K)).IsPrime]
    [(Q p : Ideal (𝓞 K)).LiesOver (Ideal.span {(p : ℤ)})] :
    ClassGroup.mk0 (Q p) ^ 2 = 1 :=
  NumberField.classGroupMk0_sq_eq_one_of_mem_ramifiedPrimes
    (NumberField.finrank_rat_eq_two hmin hgen) hram (Q p : Ideal (𝓞 K))

/-- **Complementary sub-products of the primes above the prime factors of `d` have the same
class.** For a subset `S` of the prime factors of `d`, the class of `∏_{p ∈ S} 𝔭_p` equals the
class of the complementary
product `∏_{p ∉ S} 𝔭_p`. This is `prod_classGroupMk0_eq_one` combined with the `2`-torsion of the
individual classes, and it is the concrete form of an explicit relation among the generators of
the elementary-2 subgroup spanned by the ramified-prime classes. -/
theorem prod_classGroupMk0_eq_prod_sdiff (hmin : minpoly ℤ θ = X ^ 2 - C d)
    (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤) (hsf : Squarefree d)
    (hprime : ∀ p ∈ d.natAbs.primeFactors, (Q p : Ideal (𝓞 K)).IsPrime)
    (hover : ∀ p ∈ d.natAbs.primeFactors, (Q p : Ideal (𝓞 K)).LiesOver (Ideal.span {(p : ℤ)}))
    {S : Finset ℕ} (hS : S ⊆ d.natAbs.primeFactors) :
    ∏ p ∈ S, ClassGroup.mk0 (Q p) = ∏ p ∈ d.natAbs.primeFactors \ S, ClassGroup.mk0 (Q p) := by
  have hsq : ∀ p ∈ S, ClassGroup.mk0 (Q p) ^ 2 = 1 := by
    intro p hpS
    have hp := hS hpS
    let _ := hprime p hp
    let _ := hover p hp
    exact classGroupMk0_sq_eq_one Q hmin hgen
      (mem_ramifiedPrimes_of_mem_primeFactors hmin hgen hsf hp)
  calc
    _ = (∏ p ∈ S, ClassGroup.mk0 (Q p)) *
        ∏ p ∈ d.natAbs.primeFactors, ClassGroup.mk0 (Q p) := by
      rw [prod_classGroupMk0_eq_one Q hmin hgen hsf hprime hover, mul_one]
    _ = ∏ p ∈ S \ d.natAbs.primeFactors ∪ d.natAbs.primeFactors \ S,
        ClassGroup.mk0 (Q p) :=
      (prod_sdiff_union_sdiff _ (fun p hp ↦ hsq p (Finset.mem_inter.mp hp).1)).symm
    _ = _ := by rw [Finset.sdiff_eq_empty_iff_subset.mpr hS, Finset.empty_union]

/-- **The classes of the ramified primes generate a subgroup of order at most
`2 ^ (t - 1)`.** Let `s` be a finite set of ramified primes of `K = ℚ(√d)` containing every
prime factor of `d`, with `Q p` the prime of `𝓞 K` above `p ∈ s`. Then the subgroup of
`Cl(𝓞 K)` generated by their classes has at most `2 ^ (#s - 1)` elements.

The classes are involutions, so the subgroup they generate is the set of sub-products, of which
there are at most `2 ^ #s`; the relation `prod_classGroupMk0_eq_one` over the prime factors of `d`
removes one generator (`EpsilonEridani.natCard_closure_image_le_two_pow_card_sub_one`). The hypothesis
`1 < |d|` excludes `d = -1`, the one radicand with no prime factor and hence no relation.

This is only an upper bound in the ordinary class group; no matching lower bound is asserted. -/
theorem natCard_closure_image_classGroupMk0_le (hmin : minpoly ℤ θ = X ^ 2 - C d)
    (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤) (hsf : Squarefree d) {s : Finset ℕ}
    (hram : ∀ p ∈ s, p ∈ ramifiedPrimes K)
    (hprime : ∀ p ∈ s, (Q p : Ideal (𝓞 K)).IsPrime)
    (hover : ∀ p ∈ s, (Q p : Ideal (𝓞 K)).LiesOver (Ideal.span {(p : ℤ)}))
    (hs : d.natAbs.primeFactors ⊆ s) (hd : 1 < d.natAbs) :
    Nat.card (Subgroup.closure ((fun p ↦ ClassGroup.mk0 (Q p)) '' (↑s : Set ℕ))) ≤
      2 ^ (s.card - 1) :=
  natCard_closure_image_le_two_pow_card_sub_one s _
    (fun p hp ↦ by
      let _ := hprime p hp
      let _ := hover p hp
      exact classGroupMk0_sq_eq_one Q hmin hgen (hram p hp))
    hs (Nat.nonempty_primeFactors.mpr hd)
    (prod_classGroupMk0_eq_one Q hmin hgen hsf (fun p hp ↦ hprime p (hs hp))
      fun p hp ↦ hover p (hs hp))

end EpsilonEridani.Multiquadratic
