/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.RingTheory.DedekindDomain.Instances
public import EpsilonEridani.RingTheory.DedekindDomain.Different.Localization
public import EpsilonEridani.RingTheory.DedekindDomain.Discriminant.Basic

/-!
# Localization of the relative discriminant

Let `B / A` be a finite torsion-free extension of Dedekind domains with separable extension of
fraction fields, and let `M` be a submonoid of `A`. If `Aₘ` is the localization of `A` at `M`
and `Bₘ` is the localization of `B` at the image of `M`, then the relative discriminant of
`Bₘ / Aₘ` is the ideal of `Aₘ` generated by the relative discriminant of `B / A`:

`(relDiscr A B).map (algebraMap A Aₘ) = relDiscr Aₘ Bₘ`.

This reduces questions about the relative discriminant at a prime `p` of `A` to the semilocal
extension obtained by inverting `p.primeCompl`; for that choice of `M` the canonical pair is
`Localization.AtPrime p` and `Localization (Algebra.algebraMapSubmonoid B p.primeCompl)`, whose
instances are provided by `Mathlib.RingTheory.DedekindDomain.Instances`.

The result is the composite of two localization statements: the different ideal commutes with
localization (`EpsilonEridani.map_differentIdeal_eq_differentIdeal`), and so does the relative ideal
norm (Mathlib's `Ideal.spanIntNorm_localization`).

## Main results

* `EpsilonEridani.relDiscr_localization`: the relative discriminant commutes with localization.

## References

* J. Neukirch, *Algebraic Number Theory*, Chapter III, §2.
-/

public section

open scoped nonZeroDivisors

namespace EpsilonEridani

attribute [local instance] FractionRing.liftAlgebra

variable {A B : Type*} [CommRing A] [IsDedekindDomain A] [CommRing B] [IsDedekindDomain B]
  [Algebra A B] [Module.Finite A B] [Module.IsTorsionFree A B]

variable (M : Submonoid A) (Aₘ Bₘ : Type*) [CommRing Aₘ] [CommRing Bₘ]
  [Algebra A Aₘ] [Algebra B Bₘ] [Algebra Aₘ Bₘ] [Algebra A Bₘ]
  [IsScalarTower A Aₘ Bₘ] [IsScalarTower A B Bₘ]
  [IsLocalization M Aₘ] [IsLocalization (Algebra.algebraMapSubmonoid B M) Bₘ]
  [IsDedekindDomain Aₘ] [IsDedekindDomain Bₘ] [Module.Finite Aₘ Bₘ]
  [Module.IsTorsionFree Aₘ Bₘ]

include M in
/-- **The relative discriminant commutes with localization.** If `Aₘ` is the localization of `A`
at `M` and `Bₘ` is the localization of `B` at the image of `M`, then the ideal of `Aₘ` generated
by `relDiscr A B` is `relDiscr Aₘ Bₘ`.

For a prime `p` of `A`, taking `M = p.primeCompl` with `Aₘ = Localization.AtPrime p` and
`Bₘ = Localization (Algebra.algebraMapSubmonoid B p.primeCompl)` gives the relative
discriminant of the semilocalization of `B / A` at `p`. -/
theorem relDiscr_localization [Algebra.IsSeparable (FractionRing A) (FractionRing B)] :
    (relDiscr A B).map (algebraMap A Aₘ) = relDiscr Aₘ Bₘ := by
  have hM : M ≤ A⁰ := fun m hm ↦ mem_nonZeroDivisors_iff_ne_zero.mpr fun hm0 ↦
    (IsLocalization.map_units Aₘ ⟨m, hm⟩).ne_zero (by simp [hm0])
  have hMB : Algebra.algebraMapSubmonoid B M ≤ B⁰ :=
    algebraMapSubmonoid_le_nonZeroDivisors_of_faithfulSMul B hM
  -- Realise `FractionRing A ⊆ FractionRing B` as the common fraction-field extension of `B / A`
  -- and of `Bₘ / Aₘ`, with every scalar tower the different-ideal localization theorem needs.
  have : IsLocalization (Algebra.algebraMapSubmonoid B A⁰) (FractionRing B) :=
    IsIntegralClosure.isLocalization _ (FractionRing A) _ _
  have : FiniteDimensional (FractionRing A) (FractionRing B) := .of_isLocalization A B A⁰
  let f : Aₘ →+* FractionRing A := IsLocalization.map _ (T := A⁰) (RingHom.id A) hM
  let g : Bₘ →+* FractionRing B := IsLocalization.map _ (T := B⁰) (RingHom.id B) hMB
  algebraize [f, g, (algebraMap (FractionRing A) (FractionRing B)).comp f]
  have : IsScalarTower A Aₘ (FractionRing A) :=
    .of_algebraMap_eq' (IsLocalization.map_comp hM).symm
  have : IsScalarTower B Bₘ (FractionRing B) :=
    .of_algebraMap_eq' (IsLocalization.map_comp hMB).symm
  have : IsScalarTower A Aₘ (FractionRing B) := .of_algebraMap_eq fun x ↦ by
    rw [IsScalarTower.algebraMap_apply A (FractionRing A) (FractionRing B),
      IsScalarTower.algebraMap_apply A Aₘ (FractionRing A),
      ← IsScalarTower.algebraMap_apply Aₘ (FractionRing A) (FractionRing B)]
  have : IsScalarTower A Bₘ (FractionRing B) := .of_algebraMap_eq fun x ↦ by
    rw [IsScalarTower.algebraMap_apply A B Bₘ, ← IsScalarTower.algebraMap_apply B Bₘ,
      ← IsScalarTower.algebraMap_apply]
  have : IsScalarTower Aₘ Bₘ (FractionRing B) := by
    refine .of_algebraMap_eq' (IsLocalization.ringHom_ext M (RingHom.ext fun x ↦ ?_))
    simp only [RingHom.comp_apply]
    rw [← IsScalarTower.algebraMap_apply A Aₘ, ← IsScalarTower.algebraMap_apply A Aₘ Bₘ,
      ← IsScalarTower.algebraMap_apply A Bₘ]
  have : IsFractionRing Aₘ (FractionRing A) :=
    IsFractionRing.isFractionRing_of_isDomain_of_isLocalization M Aₘ _
  have : IsFractionRing Bₘ (FractionRing B) :=
    IsFractionRing.isFractionRing_of_isDomain_of_isLocalization
      (Algebra.algebraMapSubmonoid B M) Bₘ _
  -- Localize the relative norm, then the different ideal.
  rw [relDiscr_def, relDiscr_def, ← Ideal.spanNorm_eq, ← Ideal.spanNorm_eq,
    ← Ideal.spanIntNorm_localization A _ M hM Bₘ,
    map_differentIdeal_eq_differentIdeal (M := M) (R := A) (Rₘ := Aₘ) (S := B) (Sₘ := Bₘ)
      (K := FractionRing A) (L := FractionRing B)]

end EpsilonEridani

end
