/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.Geometry.Convex.Cone.Face.Generation
public import EpsilonEridani.Geometry.Toric.Algebraic.DualSemigroup.Basic
public import EpsilonEridani.Geometry.Toric.Algebraic.Regular
public import Mathlib.Geometry.Convex.Cone.Simplicial

/-!
# Toric cones are generated by their primitive rays

A salient finitely generated cone is the join of its rays. For a toric cone in an integral lattice
each ray is spanned by its primitive generator, so the cone is the cone hull of its finitely many
primitive ray generators. This is the description of a toric cone that the later constructions
consume: an integral character is nonnegative on the cone exactly when it is nonnegative on each
primitive ray generator, and the primitive ray generators of a regular cone are part of an
integral basis, hence linearly independent, so a regular cone is simplicial.

## Main declarations

* `EpsilonEridani.Toric.ToricRay.iSup_toPointedCone`: a salient finitely generated cone is the join of
  its rays.
* `EpsilonEridani.Toric.IsToricCone.hull_primitiveGenerator`: a toric cone is the cone hull of its
  primitive ray generators.
* `EpsilonEridani.Toric.mem_dualSemigroup_iff_primitiveGenerator`: an integral character lies in the dual
  semigroup of a toric cone exactly when it is nonnegative on every primitive ray generator.
* `EpsilonEridani.Toric.mem_dualSemigroup_iff_of_isPrimitiveGenerator`: the same criterion for any
  chosen primitive generator of each ray.
* `EpsilonEridani.Toric.IsRegularCone.linearIndependent_primitiveGenerator`: the images of the primitive
  ray generators of a regular cone are linearly independent.
* `EpsilonEridani.Toric.IsRegularCone.isSimplicial`: a regular cone is simplicial.

## References

* W. Fulton, *Introduction to Toric Varieties*, §1.2.
* D. Cox, J. Little and H. Schenck, *Toric Varieties*, §1.2, Lemma 1.2.15 and Definition 1.2.16.
-/

public section

namespace EpsilonEridani.Toric

variable {N V : Type*} [AddCommGroup N] [AddCommGroup V] [Module ℝ V]
  {i : N →+ V} {σ : PointedCone ℝ V}

/-- A salient finitely generated pointed cone is the join of its rays. -/
theorem ToricRay.iSup_toPointedCone (hσ : σ.FG) (hsal : (σ : ConvexCone ℝ V).Salient) :
    ⨆ ρ : ToricRay σ, ρ.toPointedCone = σ := by
  refine le_antisymm (iSup_le fun ρ ↦ ρ.1.isFaceOf.le) ?_
  obtain ⟨s, hs, hface⟩ := PointedCone.FG.exists_finset_hull_eq_isFaceOf hσ hsal
  refine hs.ge.trans (Submodule.span_le.2 fun v hv ↦ ?_)
  obtain ⟨hv0, hvσ⟩ := hface v hv
  let ρ : ToricRay σ :=
    ⟨⟨ℝ ∙₊ v, hs ▸ hvσ⟩, PointedCone.finrank_span_coe_hull_singleton hv0⟩
  exact SetLike.mem_coe.2
    (le_iSup (fun ρ : ToricRay σ ↦ ρ.toPointedCone) ρ (PointedCone.subset_hull rfl))

/-- A toric cone in an integral lattice is the cone hull of its primitive ray generators. -/
theorem IsToricCone.hull_primitiveGenerator (hi : IsIntegralLattice i) (hσ : IsToricCone i σ) :
    PointedCone.hull ℝ (i '' Set.range (primitiveGenerator hi hσ)) = σ := by
  refine le_antisymm (Submodule.span_le.2 ?_) ?_
  · rintro _ ⟨_, ⟨ρ, rfl⟩, rfl⟩
    exact ρ.1.isFaceOf.le (primitiveGenerator_mem hi hσ ρ)
  · refine (ToricRay.iSup_toPointedCone hσ.fg hσ.salient).ge.trans (iSup_le fun ρ ↦ ?_)
    rw [ρ.eq_hull_singleton (hσ.salient.anti ρ.1.isFaceOf.le) (primitiveGenerator_mem hi hσ ρ)
      (by simpa using hi.injective.ne (primitiveGenerator_ne_zero hi hσ ρ))]
    exact Submodule.span_mono (Set.singleton_subset_iff.2 ⟨_, ⟨ρ, rfl⟩, rfl⟩)

/-- An integral character lies in the dual semigroup of a toric cone exactly when it is
nonnegative on every primitive ray generator. -/
theorem mem_dualSemigroup_iff_primitiveGenerator (hi : IsIntegralLattice i)
    (hσ : IsToricCone i σ) (m : N →+ ℤ) :
    m ∈ dualSemigroup hi σ ↔ ∀ ρ : ToricRay σ, 0 ≤ m (primitiveGenerator hi hσ ρ) := by
  have h := mem_dualSemigroup_hull_image hi (Set.range (primitiveGenerator hi hσ)) m
  rwa [hσ.hull_primitiveGenerator hi, Set.forall_mem_range] at h

/-- An integral character lies in the dual semigroup of a toric cone exactly when it is
nonnegative on a chosen primitive generator of each ray. -/
theorem mem_dualSemigroup_iff_of_isPrimitiveGenerator (hi : IsIntegralLattice i)
    (hσ : IsToricCone i σ) {v : ToricRay σ → N} (hv : ∀ ρ, IsPrimitiveGenerator i ρ (v ρ))
    (m : N →+ ℤ) : m ∈ dualSemigroup hi σ ↔ ∀ ρ : ToricRay σ, 0 ≤ m (v ρ) := by
  simp only [mem_dualSemigroup_iff_primitiveGenerator hi hσ, ← (hv _).eq_primitiveGenerator hi hσ]

/-- The images of the primitive ray generators of a regular cone are linearly independent over
the reals: they are part of an integral basis of the lattice, whose image is a real basis of the
ambient space. -/
theorem IsRegularCone.linearIndependent_primitiveGenerator (hi : IsIntegralLattice i)
    (hσ : IsRegularCone i σ) :
    LinearIndependent ℝ fun ρ : ToricRay σ ↦ i (primitiveGenerator hi hσ.toIsToricCone ρ) := by
  obtain ⟨n, b, r, hb⟩ := hσ.exists_basis
  -- The images of the integral basis vectors form a real basis of `V`.
  have heq : (fun ρ : ToricRay σ ↦ i (primitiveGenerator hi hσ.toIsToricCone ρ)) =
      hi.isBaseChange.basis b ∘ r := by
    refine funext fun ρ ↦ ?_
    rw [Function.comp_apply, hi.isBaseChange.basis_apply b (r ρ),
      ((hb.isPrimitiveGenerator_apply ρ).eq_primitiveGenerator hi hσ.toIsToricCone)]
    rfl
  rw [heq]
  exact (hi.isBaseChange.basis b).linearIndependent.comp r r.injective

/-- A regular cone is simplicial: it is the cone hull of its primitive ray generators, which are
part of an integral basis and hence linearly independent over the reals. -/
theorem IsRegularCone.isSimplicial (hi : IsIntegralLattice i) (hσ : IsRegularCone i σ) :
    σ.IsSimplicial := by
  have hli := hσ.linearIndependent_primitiveGenerator hi
  have := ToricRay.finite_of_fg hσ.fg
  refine ⟨_, (Set.finite_range _).image i, ?_, hσ.toIsToricCone.hull_primitiveGenerator hi⟩
  rw [← Set.range_comp]
  exact (linearIndepOn_id_range_iff hli.injective).2 hli

end EpsilonEridani.Toric
