/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.GroupTheory.Presentation.GroupPresentation

/-!
# A transcribed presentation of the Mathieu group `M₂₃`

This file carries the `M₂₃` row of the sporadic presentation data required by milestone S1 of
`EpsilonEridaniRoadmap/CFSGStatement/README.md`. It records the ATLAS version 3 presentation `M23G1-P1` of
the Mathieu group `M₂₃` on its standard generators `a` and `b` as a `EpsilonEridani.GroupPresentation`,
together with the source, the generator convention, transcription notes, and the expected counts.

Writing `s₁ = ab`, `s₂ = ab²` and `s₋₁ = ab⁻¹` for the three syllables that occur, the nine
transcribed relators are

```text
a², b⁴, s₁²³, s₂⁶, [a,b]⁶, (s₁s₋₁s₂)⁴,
s₁³ s₋₁ s₂ (s₁s₋₁)² s₁³ s₋₁³,
(s₁s₂s₂)⁶,
(s₁s₂)³ (s₂s₋₁)² s₁ s₂ s₁ s₋₁ s₂.
```

The eighth of these, `(abab²ab²)⁶`, is annotated "Is redundant, but very useful." in the source, and
the source's header records the two resulting counts as "NoRels: 8 [or 9]" with lengths 190 and 238.
Unlike the redundant words of the neighbouring ATLAS files — `M24G1-P1`, transcribed in
`EpsilonEridani.GroupTheory.SpecificGroups.CFSG.Sporadic.Mathieu.TwentyFour`, comments its redundant word
out of the Magma `Group<x, y | ...>` constructor — this word stands inside the relator list as
written, so it is transcribed and the recorded relator count is nine. The source's demonstration of
correctness covers the list both with and without it.

The source's commutator convention is `[r,s] = r⁻¹s⁻¹rs`, opposite to Mathlib's
`commutatorElement`, so the commutator is stored as `Relator.comm (.inv r) (.inv s)` as
`EpsilonEridani.Relator` prescribes. The proved `EpsilonEridani.Relator.toWord_toFreeGroup` is the audit boundary
between these expressions and the signed words that `PresentedGroup` consumes.

The source is a presentation rather than a semi-presentation — the ATLAS lists a separate
semi-presentation for `M₂₃`, which is not what is transcribed here — and it comes with a
demonstration of correctness: the relations force the presented group to be perfect and hence
generated by conjugates of `a`, a coset enumeration returns the index `3795` of a subgroup that
visibly centralizes `a`, which is the index of the involution centralizer `2⁴:L₃(2)` in `M₂₃`, and
`M₂₃` has trivial Schur multiplier. GAP 4.15.1 independently checks the transcription in both
directions. The nine words compiled by `Relator.toWord` from the expressions below vanish on five
independent standard generating pairs of the natural 23-point representation of `M₂₃`, so the
presented group surjects onto `M₂₃`; and enumerating the compiled relators over the cyclic subgroup
generated by the image of `ab` returns the index `443520`, which with `s₁²³` bounding that subgroup
by `23` pins the order of the presented group at `10200960 = |M₂₃|`. Both computations are
provenance for the transcription, not Lean theorems: this file asserts no order, finiteness,
simplicity, or identification result. The cross-check against the `M23` of the
[FiniteSimpleGroups](https://github.com/KitaKen1/finite-simple-groups-lean) development, which
`EpsilonEridaniRoadmap/CFSGStatement/README.md` asks for on the names that development covers, is still
recorded below.

## Independent source-to-Lean read-through

An independent read-through used the bytes of the ATLAS Magma source `M23G1-P1.M` whose SHA-256
digest is `3a4a7b8b116ac25b147b94ce0a6c6a73a730420e9865792d60587bd99cdc0e32`. Its constructor
`G<x,y>` fixes the generator order, and the later assignments `a := x; b := y` confirm that the
source's `x,y` are the presentation generators called `a,b` here.

Reading the constructor from top to bottom gives the five short relators

```text
x², y⁴, (xy)²³, (xy²)⁶, [x,y]⁶,
```

followed by these four words:

```text
(xy xy⁻¹ xy²)⁴,
(xy)³ xy⁻¹ xy² (xy xy⁻¹)² (xy)³ (xy⁻¹)³,
(xy xy² xy²)⁶,
(xy xy²)³ (xy² xy⁻¹)² xy xy² xy xy⁻¹ xy².
```

They agree in exponent, inverse placement, and source order with the nine entries of
`m23Presentation_transcribed`, after substituting `s₁ = ab`, `s₂ = ab²`, and `s₋₁ = ab⁻¹` and
using the source convention `[x,y] = x⁻¹y⁻¹xy`. The source places the eighth word inside the
constructor and labels it redundant but useful; it therefore belongs in this row. Its header's
`8 [or 9]` relators and lengths `190 [or 238]` are exactly the results of deleting or retaining
that 48-letter entry in `m23Presentation_map_length_relators`. This checks every source relator and
the only optional-word boundary independently of the original transcription and closes this row's
S1 source-to-Lean read-through.

## Independent comparison with `FiniteSimpleGroups`

The comparison used `finite-simple-groups-lean` at commit
`7f09e33a9ceef6b59ce03e34cd4f0558c763e325`, whose `m23a`, `m23b`, and `m23c` generate a
subgroup of `Equiv.Perm (Fin 23)` with proved order `10200960` and proved simplicity. A
deterministic search inside that subgroup found the following ATLAS standard pair, in the pinned
development's zero-based point numbering:

```text
a = (0 5)(2 7)(3 20)(6 14)(8 9)(11 17)(16 19)(18 21)
b = (0 15 6 7)(1 21 14 3)(4 12 5 11)(9 13 18 22)(10 20)(17 19).
```

Direct permutation calculation gives orders `2`, `4`, and `23` for `a`, `b`, and `ab`, and order
`8` for the standard-pair word `abababab²abab²ab²`. All nine compiled relators in this module
evaluate to the identity. Schreier--Sims calculation then verifies that `a` and `b` belong to the
subgroup generated by `m23a`, `m23b`, and `m23c`, while each of those three named generators
belongs to `⟨a,b⟩`; equivalently, `⟨a,b⟩` has the same order `10200960` and is that subgroup.

The check used Python 3.14.6 and SymPy 1.14.0. Concatenating the forward image tables for `a` and
then `b`, with each image stored as one byte, has SHA-256
`1ee47ccfd4fa651541d3b0826fc4ef407705bd727921e885c0f4ae9bd442f8e4`. This is the independent
comparison artifact required by S1; no external code or permutation data is imported into Tau Ceti.

The row is a sealed definition, so it publishes an equation for each of its fields: the transcribed
relator expressions with their generator indices written out, and the provenance a manifest row
exists to record. Together with `EpsilonEridani.GroupPresentation.relators_def` and
`EpsilonEridani.GroupPresentation.mem_relatorSet_iff` the first of those determines the compiled words and
the relations defining the presented group, so a consumer reasons about the row without unfolding
it.

Four decidable checks accompany those equations. The relator lengths and two aggregate totals record
the compiled data one word at a time and in aggregate, and cyclic reducedness makes the letter
counts comparable with the source's published lengths. The nine-word total is `238` and deleting the
useful redundant eighth relator leaves `190`, exactly the two figures in the source header for the
two versions of the presentation.

## Main definitions and results

* `EpsilonEridani.Sporadic.m23Presentation`: the ATLAS finite presentation of `M₂₃`.
* `EpsilonEridani.Sporadic.m23Presentation_transcribed` and the equations for the remaining fields: the
  characterization of the sealed row.
* `EpsilonEridani.Sporadic.m23Presentation_map_length_relators`,
  `EpsilonEridani.Sporadic.m23Presentation_totalLength`,
  `EpsilonEridani.Sporadic.m23Presentation_sum_map_length_eraseIdx_relators` and
  `EpsilonEridani.Sporadic.m23Presentation_relatorsCyclicallyReduced`: the four checks on the compiled
  words. The two totals are the figures on the source's header line `Length: 190 [or 238].`,
  whose bracketed alternative is the presence of the redundant eighth relator.

## References

* R. A. Wilson, R. A. Parker, J. N. Bray et al., *ATLAS of Finite Group Representations*,
  version 3, presentation `M23G1-P1`,
  <https://brauer.maths.qmul.ac.uk/Atlas/v3/pres/M23G1-P1>, with the relator list and the
  demonstration of correctness in the Magma source file
  <https://brauer.maths.qmul.ac.uk/Atlas/spor/M23/mag/M23G1-P1.M>.
* KitaKen1, *FiniteSimpleGroups*, `M23` construction at commit
  `7f09e33a9ceef6b59ce03e34cd4f0558c763e325`,
  <https://github.com/KitaKen1/finite-simple-groups-lean>.
-/

public section

namespace EpsilonEridani.Sporadic

private abbrev a : Relator (Fin 2) := .gen 0

private abbrev b : Relator (Fin 2) := .gen 1

@[inherit_doc Relator.mul]
local infixl:70 " ⬝ " => Relator.mul

/-- The source's commutator `[r, s] = r⁻¹ s⁻¹ r s`, which is `⁅r⁻¹, s⁻¹⁆` in Mathlib's
convention. -/
private abbrev sourceComm (r s : Relator (Fin 2)) : Relator (Fin 2) := .comm (.inv r) (.inv s)

/-- The syllable `a * b`. -/
private abbrev ab1 : Relator (Fin 2) := a ⬝ b

/-- The syllable `a * b ^ 2`. -/
private abbrev ab2 : Relator (Fin 2) := a ⬝ .pow b 2

/-- The syllable `a * b⁻¹`. -/
private abbrev abNeg1 : Relator (Fin 2) := a ⬝ .inv b

/-- The ATLAS version 3 finite presentation `M23G1-P1` of the Mathieu group `M₂₃` on its standard
generators `a` and `b`.

The ATLAS lists this as a full presentation of the abstract group, separately from the
semi-presentation used to recognize standard generators inside a group already constructed. No
structural property of the presented group is asserted here: this definition records only the
cited generators and relations. -/
def m23Presentation : GroupPresentation where
  generatorNames := ["a", "b"]
  source := "R. A. Wilson, R. A. Parker, J. N. Bray et al., ATLAS of Finite Group \
    Representations, version 3"
  sourceLocator := "M23G1-P1, https://brauer.maths.qmul.ac.uk/Atlas/v3/pres/M23G1-P1, with the \
    relator list and the demonstration of correctness in the Magma source file \
    https://brauer.maths.qmul.ac.uk/Atlas/spor/M23/mag/M23G1-P1.M"
  generatorConvention := "The ATLAS standard generators a and b of M23, that is, a of order 2 and \
    b of order 4 with ab of order 23 and abababab^2abab^2ab^2 of order 8, in that order, so index \
    0 is a and index 1 is b. Products are read left to right, negative exponents denote inverses, \
    and [r,s] denotes r^-1 s^-1 r s."
  transcriptionNotes := "The nine words of the source's Magma relator list are stored as nine \
    relators equal to the identity. The eighth, (ab*ab^2*ab^2)^6, carries the source's annotation \
    'Is redundant, but very useful.' but stands inside the relator list as written rather than \
    being commented out of it, so it is transcribed; the source's header records the two counts as \
    'NoRels: 8 [or 9]', of total length 190 and 238, and demonstrates correctness for the list \
    both with and without that word. GAP 4.15.1 checks that the nine compiled words vanish on five \
    independent standard generating pairs of the natural 23-point representation of M23, and that \
    enumerating the compiled relators over the cyclic subgroup generated by the image of ab \
    returns the index 443520, hence the order 23 * 443520 = 10200960 of M23."
  expectedGeneratorCount := 2
  expectedRelatorCount := 9
  transcribed :=
    [ .pow a 2,
      .pow b 4,
      .pow ab1 23,
      .pow ab2 6,
      .pow (sourceComm a b) 6,
      .pow (ab1 ⬝ abNeg1 ⬝ ab2) 4,
      .pow ab1 3 ⬝ abNeg1 ⬝ ab2 ⬝ .pow (ab1 ⬝ abNeg1) 2 ⬝ .pow ab1 3 ⬝ .pow abNeg1 3,
      .pow (ab1 ⬝ ab2 ⬝ ab2) 6,
      .pow (ab1 ⬝ ab2) 3 ⬝ .pow (ab2 ⬝ abNeg1) 2 ⬝ ab1 ⬝ ab2 ⬝ ab1 ⬝ abNeg1 ⬝ ab2 ]

/-- The generator names recorded for `M₂₃`. The row's body is sealed, so this is what lets a
consumer see that it is a two-generator presentation. -/
@[simp]
theorem m23Presentation_generatorNames : m23Presentation.generatorNames = ["a", "b"] := by
  simp [m23Presentation]

/-- The source recorded for `M₂₃`. The row's body is sealed, so this equation publishes the
citation itself, rather than only the row's name, to a downstream audit. -/
@[simp]
theorem m23Presentation_source :
    m23Presentation.source = "R. A. Wilson, R. A. Parker, J. N. Bray et al., ATLAS of Finite Group \
      Representations, version 3" := by
  simp [m23Presentation]

/-- The locator recorded for `M₂₃`, pointing at the presentation and its demonstration of
correctness inside the source. -/
@[simp]
theorem m23Presentation_sourceLocator :
    m23Presentation.sourceLocator = "M23G1-P1, \
      https://brauer.maths.qmul.ac.uk/Atlas/v3/pres/M23G1-P1, with the relator list and the \
      demonstration of correctness in the Magma source file \
      https://brauer.maths.qmul.ac.uk/Atlas/spor/M23/mag/M23G1-P1.M" := by
  simp [m23Presentation]

/-- The generator convention recorded for `M₂₃`, fixing which generator each relator index names
and which commutator convention the source uses. -/
@[simp]
theorem m23Presentation_generatorConvention :
    m23Presentation.generatorConvention = "The ATLAS standard generators a and b of M23, that is, \
      a of order 2 and b of order 4 with ab of order 23 and abababab^2abab^2ab^2 of order 8, in \
      that order, so index 0 is a and index 1 is b. Products are read left to right, negative \
      exponents denote inverses, and [r,s] denotes r^-1 s^-1 r s." := by
  simp [m23Presentation]

/-- The transcription notes recorded for `M₂₃`, including the source's two counts according to
whether the useful redundant relator is retained. -/
@[simp]
theorem m23Presentation_transcriptionNotes :
    m23Presentation.transcriptionNotes = "The nine words of the source's Magma relator list are \
      stored as nine relators equal to the identity. The eighth, (ab*ab^2*ab^2)^6, carries the \
      source's annotation 'Is redundant, but very useful.' but stands inside the relator list as \
      written rather than being commented out of it, so it is transcribed; the source's header \
      records the two counts as 'NoRels: 8 [or 9]', of total length 190 and 238, and demonstrates \
      correctness for the list both with and without that word. GAP 4.15.1 checks that the nine \
      compiled words vanish on five independent standard generating pairs of the natural 23-point \
      representation of M23, and that enumerating the compiled relators over the cyclic subgroup \
      generated by the image of ab returns the index 443520, hence the order 23 * 443520 = \
      10200960 of M23." := by
  simp [m23Presentation]

/-- The generator count `M₂₃`'s source states. With
`EpsilonEridani.Sporadic.m23Presentation_generatorNames` this makes
`EpsilonEridani.Sporadic.m23Presentation_matchesMetadata` an equation between two visible numbers. -/
@[simp]
theorem m23Presentation_expectedGeneratorCount : m23Presentation.expectedGeneratorCount = 2 := by
  simp [m23Presentation]

/-- The relator count of the transcribed nine-word version of the `M₂₃` presentation. -/
@[simp]
theorem m23Presentation_expectedRelatorCount : m23Presentation.expectedRelatorCount = 9 := by
  simp [m23Presentation]

/-- The relator expressions transcribed for `M₂₃`, with their generator indices written out and
the private syllable abbreviations expanded.

The row's body is sealed, so this equation characterizes it: with
`EpsilonEridani.GroupPresentation.relators_def` it determines the compiled words, and with
`EpsilonEridani.GroupPresentation.mem_relatorSet_iff` it determines the relations defining
`EpsilonEridani.GroupPresentation.Group`. Index `0` is `a` and index `1` is `b`, with bounds supplied by
`EpsilonEridani.Sporadic.m23Presentation_generatorNames`. -/
@[simp]
theorem m23Presentation_transcribed :
    m23Presentation.transcribed =
      [ -- a²
        .pow (.gen ⟨0, by simp⟩) 2,
        -- b⁴
        .pow (.gen ⟨1, by simp⟩) 4,
        -- (ab)²³
        .pow (.gen ⟨0, by simp⟩ ⬝ .gen ⟨1, by simp⟩) 23,
        -- (ab²)⁶
        .pow (.gen ⟨0, by simp⟩ ⬝ .pow (.gen ⟨1, by simp⟩) 2) 6,
        -- [a,b]⁶, in the source's commutator convention
        .pow (.comm (.inv (.gen ⟨0, by simp⟩)) (.inv (.gen ⟨1, by simp⟩))) 6,
        -- (ab ab⁻¹ ab²)⁴
        .pow ((.gen ⟨0, by simp⟩ ⬝ .gen ⟨1, by simp⟩) ⬝
          (.gen ⟨0, by simp⟩ ⬝ .inv (.gen ⟨1, by simp⟩)) ⬝
          (.gen ⟨0, by simp⟩ ⬝ .pow (.gen ⟨1, by simp⟩) 2)) 4,
        -- (ab)³ ab⁻¹ ab² (ab ab⁻¹)² (ab)³ (ab⁻¹)³
        .pow (.gen ⟨0, by simp⟩ ⬝ .gen ⟨1, by simp⟩) 3 ⬝
          (.gen ⟨0, by simp⟩ ⬝ .inv (.gen ⟨1, by simp⟩)) ⬝
          (.gen ⟨0, by simp⟩ ⬝ .pow (.gen ⟨1, by simp⟩) 2) ⬝
          .pow ((.gen ⟨0, by simp⟩ ⬝ .gen ⟨1, by simp⟩) ⬝
            (.gen ⟨0, by simp⟩ ⬝ .inv (.gen ⟨1, by simp⟩))) 2 ⬝
          .pow (.gen ⟨0, by simp⟩ ⬝ .gen ⟨1, by simp⟩) 3 ⬝
          .pow (.gen ⟨0, by simp⟩ ⬝ .inv (.gen ⟨1, by simp⟩)) 3,
        -- (ab ab² ab²)⁶, the useful redundant relator
        .pow ((.gen ⟨0, by simp⟩ ⬝ .gen ⟨1, by simp⟩) ⬝
          (.gen ⟨0, by simp⟩ ⬝ .pow (.gen ⟨1, by simp⟩) 2) ⬝
          (.gen ⟨0, by simp⟩ ⬝ .pow (.gen ⟨1, by simp⟩) 2)) 6,
        -- (ab ab²)³ (ab² ab⁻¹)² ab ab² ab ab⁻¹ ab²
        .pow ((.gen ⟨0, by simp⟩ ⬝ .gen ⟨1, by simp⟩) ⬝
          (.gen ⟨0, by simp⟩ ⬝ .pow (.gen ⟨1, by simp⟩) 2)) 3 ⬝
          .pow ((.gen ⟨0, by simp⟩ ⬝ .pow (.gen ⟨1, by simp⟩) 2) ⬝
            (.gen ⟨0, by simp⟩ ⬝ .inv (.gen ⟨1, by simp⟩))) 2 ⬝
          (.gen ⟨0, by simp⟩ ⬝ .gen ⟨1, by simp⟩) ⬝
          (.gen ⟨0, by simp⟩ ⬝ .pow (.gen ⟨1, by simp⟩) 2) ⬝
          (.gen ⟨0, by simp⟩ ⬝ .gen ⟨1, by simp⟩) ⬝
          (.gen ⟨0, by simp⟩ ⬝ .inv (.gen ⟨1, by simp⟩)) ⬝
          (.gen ⟨0, by simp⟩ ⬝ .pow (.gen ⟨1, by simp⟩) 2) ] := by
  simp [m23Presentation]

/-- The generator and relator counts recorded for `M₂₃` agree with the transcribed data. -/
theorem m23Presentation_matchesMetadata : m23Presentation.matchesMetadata := by
  decide

/-- The lengths of the nine compiled relator words for `M₂₃`, in the order of the Magma source.
Reading the counts one word at a time makes any transcription discrepancy local. -/
theorem m23Presentation_map_length_relators :
    m23Presentation.relators.map List.length = [2, 4, 46, 18, 24, 28, 31, 48, 37] := by
  simp [GroupPresentation.relators_def, m23Presentation]

/-- The compiled relator words for `M₂₃` have the total length `238` published for the nine-word
version of the presentation. -/
theorem m23Presentation_totalLength : m23Presentation.totalLength = 238 := by
  rw [GroupPresentation.totalLength_def, m23Presentation_map_length_relators]
  decide

/-- Deleting the redundant eighth relator `(ab·ab²·ab²)⁶` leaves `190` signed letters, which is
the length the source records for its eight-relator form.

With `EpsilonEridani.Sporadic.m23Presentation_totalLength` this checks the transcription against both of
the figures on the source's header lines `Length: 190 [or 238].` and `NoRels: 8 [or 9].`, whose
bracketed alternatives are exactly the presence of this relator. -/
theorem m23Presentation_sum_map_length_eraseIdx_relators :
    ((m23Presentation.relators.eraseIdx 7).map List.length).sum = 190 := by
  rw [← List.eraseIdx_map, m23Presentation_map_length_relators]
  decide

/-- Every compiled relator word for `M₂₃` is cyclically reduced. This is what makes
`EpsilonEridani.Sporadic.m23Presentation_totalLength` and
`EpsilonEridani.Sporadic.m23Presentation_sum_map_length_eraseIdx_relators` comparable with the source's
published lengths, which are measured after free and cyclic reduction of each relator. -/
theorem m23Presentation_relatorsCyclicallyReduced :
    m23Presentation.relatorsCyclicallyReduced := by
  simp only [GroupPresentation.relatorsCyclicallyReduced_iff, GroupPresentation.relators_def,
    m23Presentation, List.map_cons, List.map_nil, Relator.toWord_mul, Relator.toWord_pow,
    Relator.toWord_inv, Relator.toWord_comm, Relator.toWord_gen]
  decide

end EpsilonEridani.Sporadic
