/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Topology.Compactness.Compact
public import EpsilonEridani.GroupTheory.Gaschutz
public import EpsilonEridani.Topology.Algebra.Group.Profinite.Rank

/-!
# Gaschütz's lifting lemma for profinite groups

Let `f : G →* H` be a continuous surjection from a profinite group onto a Hausdorff group, and
let `G` be topologically generated by an `ι`-tuple, with `ι` finite. Then every `ι`-tuple that
topologically generates `H` lifts along `f` to an `ι`-tuple that topologically generates `G`
(`EpsilonEridani.exists_comp_eq_and_topologicalClosure_closure_range_eq_top`). In terms of the generator
rank: a generating `n`-tuple of `H` lifts to a generating `n`-tuple of `G` as soon as
`topologicalGeneratorRankNat G ≤ n`, which is
`exists_comp_eq_and_topologicalClosure_closure_range_eq_top_of_topologicalGeneratorRankNat_le`.
This is the mechanism behind minimal presentations: when `G` and a quotient of it have the same
generator rank `n`, a minimal generating `n`-tuple of the quotient pulls back to a minimal
generating `n`-tuple of `G`.

The proof reduces to Gaschütz's lemma for finite groups
(`MonoidHom.exists_comp_eq_and_closure_range_eq_top_of_surjective`) by compactness. For each open
normal subgroup `U ≤ G`, the tuples of `G` lifting the given tuple whose image generates `G ⧸ U`
form a closed subset of `ι → G`; it is nonempty by the finite lemma applied to
`G ⧸ U ↠ H ⧸ U.map f`, which is a surjection of finite groups because `f` is an open map. These
sets are directed downwards, so they have a common point, which is the required lift.

## Main results

* `EpsilonEridani.exists_comp_eq_and_topologicalClosure_closure_range_eq_top`: **Gaschütz's lifting
  lemma** for profinite groups.
* `exists_comp_eq_and_topologicalClosure_closure_range_eq_top_of_topologicalGeneratorRankNat_le`:
  the generator-rank form, for `Fin n`-tuples with `n` at least the generator rank of `G`.

## References

* L. Ribes and P. Zalesskii, *Profinite Groups*, Proposition 2.5.4.
-/

public section

namespace EpsilonEridani

variable {G : Type*} [Group G] [TopologicalSpace G] [IsTopologicalGroup G] [CompactSpace G]
  [TotallyDisconnectedSpace G] {H : Type*} [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
  [T2Space H] {ι : Type*} [Finite ι]

/-- **Gaschütz's lifting lemma for profinite groups.** Along a continuous surjection `f : G →* H`
from a profinite group onto a Hausdorff group, an `ι`-tuple that topologically generates `H` lifts
to an `ι`-tuple that topologically generates `G`, provided `G` is topologically generated by some
`ι`-tuple, with `ι` finite. -/
theorem exists_comp_eq_and_topologicalClosure_closure_range_eq_top {f : G →* H}
    (hf : Continuous f) (hsurj : Function.Surjective f) {g : ι → G}
    (hg : (Subgroup.closure (Set.range g)).topologicalClosure = ⊤) {h : ι → H}
    (hh : (Subgroup.closure (Set.range h)).topologicalClosure = ⊤) :
    ∃ g' : ι → G, f ∘ g' = h ∧ (Subgroup.closure (Set.range g')).topologicalClosure = ⊤ := by
  classical
  have hneIdx : Nonempty (OpenNormalSubgroup G) := ⟨openNormalSubgroupTop G⟩
  -- A continuous surjection of compact Hausdorff groups is an open map, so the image of an open
  -- normal subgroup `U ≤ G` is an open normal subgroup of `H`.
  have hopen : IsOpenMap f :=
    (MonoidHom.isOpenQuotientMap_of_isQuotientMap
      (hf.isClosedMap.isQuotientMap hf hsurj)).isOpenMap
  have hnormal : ∀ U : OpenNormalSubgroup G, (U.toSubgroup.map f).Normal := fun U ↦
    U.isNormal'.map f hsurj
  -- The tuples lifting `h` whose image generates `G ⧸ U`.
  set C : OpenNormalSubgroup G → Set (ι → G) := fun U ↦
    {x | Subgroup.closure (Set.range (⇑(QuotientGroup.mk' U.toSubgroup) ∘ x)) = ⊤} ∩
      ⋂ i, {x | f (x i) = h i} with hC
  have hmono : ∀ {U W : OpenNormalSubgroup G}, U ≤ W → C U ⊆ C W := by
    intro U W hUW x hx
    rw [hC, Set.mem_inter_iff] at hx ⊢
    refine ⟨?_, hx.2⟩
    have hmap : (Subgroup.closure (Set.range (⇑(QuotientGroup.mk' U.toSubgroup) ∘ x))).map
        (QuotientGroup.mapOfLE hUW) = ⊤ := by
      rw [hx.1]
      exact Subgroup.map_top_of_surjective _ (QuotientGroup.mapOfLE_surjective hUW)
    rw [MonoidHom.map_closure, ← Set.range_comp] at hmap
    simpa only [Set.mem_ofPred_eq, Function.comp_def, QuotientGroup.mk'_apply,
      QuotientGroup.mapOfLE_mk] using hmap
  have hdir : Directed (· ⊇ ·) C := fun U W ↦
    ⟨U ⊓ W, hmono inf_le_left, hmono inf_le_right⟩
  have hclosed : ∀ U : OpenNormalSubgroup G, IsClosed (C U) := by
    intro U
    have hcont : Continuous fun x : ι → G ↦ ⇑(QuotientGroup.mk' U.toSubgroup) ∘ x :=
      continuous_pi fun i ↦
        (QuotientGroup.continuous_mk (N := U.toSubgroup)).comp (continuous_apply i)
    exact ((isClosed_discrete
      {y : ι → G ⧸ U.toSubgroup | Subgroup.closure (Set.range y) = ⊤}).preimage hcont).inter
      (isClosed_iInter fun i ↦ isClosed_eq (hf.comp (continuous_apply i)) continuous_const)
  have hne : ∀ U : OpenNormalSubgroup G, (C U).Nonempty := by
    intro U
    -- Gaschütz's lemma for the finite quotient `G ⧸ U ↠ H ⧸ U.map f`.
    let φ : G ⧸ U.toSubgroup →* H ⧸ U.toSubgroup.map f :=
      QuotientGroup.map _ _ f (Subgroup.le_comap_map _ _)
    have hφ : Function.Surjective φ :=
      QuotientGroup.map_surjective_of_surjective _ _ f (QuotientGroup.mk_surjective.comp hsurj) _
    have hgU : Subgroup.closure (Set.range (⇑(QuotientGroup.mk' U.toSubgroup) ∘ g)) = ⊤ := by
      have := topologicalClosure_closure_eq_top_iff.mp hg U
      rwa [← Set.range_comp] at this
    have hhU :
        Subgroup.closure (Set.range (⇑(QuotientGroup.mk' (U.toSubgroup.map f)) ∘ h)) = ⊤ := by
      -- `H ⧸ U.map f` is discrete because `U.map f` is open, so the dense subgroup generated by
      -- the image of `h` is everything.
      have : DiscreteTopology (H ⧸ U.toSubgroup.map f) := QuotientGroup.discreteTopology (by
        rw [Subgroup.coe_map]
        exact hopen _ U.isOpen')
      have hdense := topologicalClosure_closure_image_eq_top hh
        (QuotientGroup.continuous_mk (N := U.toSubgroup.map f))
        (QuotientGroup.mk'_surjective _).denseRange
      rw [← Set.range_comp] at hdense
      have hle := (Subgroup.closure
        (Set.range (⇑(QuotientGroup.mk' (U.toSubgroup.map f)) ∘ h))).topologicalClosure_minimal
        le_rfl (isClosed_discrete _)
      rw [hdense] at hle
      exact top_le_iff.mp hle
    obtain ⟨y, hy, hygen⟩ := φ.exists_comp_eq_and_closure_range_eq_top_of_surjective hφ hgU hhU
    -- Lift `y` to `G` and correct each coordinate by an element of `U` so that it maps to `h`.
    choose x₀ hx₀ using fun i ↦ QuotientGroup.mk'_surjective U.toSubgroup (y i)
    have hmem : ∀ i, (f (x₀ i))⁻¹ * h i ∈ U.toSubgroup.map f := fun i ↦ by
      have hyi := congr_fun hy i
      rw [Function.comp_apply, Function.comp_apply, ← hx₀ i, QuotientGroup.mk'_apply,
        QuotientGroup.mk'_apply, QuotientGroup.map_mk] at hyi
      exact QuotientGroup.eq.mp hyi
    choose u hu hfu using fun i ↦ Subgroup.mem_map.mp (hmem i)
    refine ⟨fun i ↦ x₀ i * u i, ?_, Set.mem_iInter.mpr fun i ↦ ?_⟩
    · rw [Set.mem_ofPred_eq]
      have hcomp : (⇑(QuotientGroup.mk' U.toSubgroup) ∘ fun i ↦ x₀ i * u i) = y :=
        funext fun i ↦ by
          rw [Function.comp_apply, QuotientGroup.mk'_apply, QuotientGroup.mk_mul_of_mem _ (hu i),
            ← hx₀ i, QuotientGroup.mk'_apply]
      rw [hcomp]
      exact hygen
    · rw [Set.mem_ofPred_eq, map_mul, hfu i, mul_inv_cancel_left]
  obtain ⟨x, hx⟩ := IsCompact.nonempty_iInter_of_directed_nonempty_isCompact_isClosed C hdir hne
    (fun U ↦ (hclosed U).isCompact) hclosed
  have hxU : ∀ U : OpenNormalSubgroup G, x ∈ C U := Set.mem_iInter.mp hx
  refine ⟨x, funext fun i ↦ Set.mem_iInter.mp (hxU (openNormalSubgroupTop G)).2 i,
    topologicalClosure_closure_eq_top_iff.mpr fun U ↦ ?_⟩
  have hgen := (hxU U).1
  rwa [Set.mem_ofPred_eq, Set.range_comp] at hgen

/-- **Gaschütz's lifting lemma, generator-rank form.** Along a continuous surjection `f : G →* H`
from a topologically finitely generated profinite group onto a Hausdorff group, a topologically
generating `n`-tuple of `H` lifts to a topologically generating `n`-tuple of `G` whenever `n` is at
least the topological generator rank of `G`. -/
theorem exists_comp_eq_and_topologicalClosure_closure_range_eq_top_of_topologicalGeneratorRankNat_le
    (hG : IsTopologicallyFinitelyGenerated G) {n : ℕ} (hn : topologicalGeneratorRankNat G hG ≤ n)
    {f : G →* H} (hf : Continuous f) (hsurj : Function.Surjective f) {h : Fin n → H}
    (hh : (Subgroup.closure (Set.range h)).topologicalClosure = ⊤) :
    ∃ g' : Fin n → G, f ∘ g' = h ∧ (Subgroup.closure (Set.range g')).topologicalClosure = ⊤ := by
  obtain ⟨s, hcard, hgen⟩ := exists_finset_card_eq_topologicalGeneratorRankNat hG
  obtain ⟨g, hg⟩ := exists_topologicalClosure_closure_range_eq_top_of_rank_le (n := n) fun U ↦
    (rank_quotient_le_card_of_topologicalClosure_closure_eq_top hgen U).trans (hcard ▸ hn)
  exact exists_comp_eq_and_topologicalClosure_closure_range_eq_top hf hsurj hg hh

end EpsilonEridani
