/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Subsystem
public import EpsilonEridani.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Triangular
public import EpsilonEridani.LinearAlgebra.Matrix.GeneralLinearGroup.UpperUnitriangular.Nilpotent
-- The coordinate comparison between `kostantRootSubgroupParam` and its basis matrix is used only
-- in the containment proof, so it is not re-exported.
import EpsilonEridani.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Elementary.Coordinate

/-!
# Upper-unitriangular positive Kostant subsystem groups

Let a Kostant form act on an integral lattice with a finite ordered weight basis. Suppose that a
set `S` of distinguished root vectors acts by positive weight shifts: whenever a positive divided
power carries the weight at basis index `s` to the weight at `r`, one has `r < s`. The individual
root-subgroup matrices are then upper unitriangular by
`EpsilonEridani.UniversalEnvelopingAlgebra.isUpperUnitriangular_kostantRootSubgroupMatrix`.

This file passes from those individual root subgroups to the subgroup they generate. In basis
coordinates the whole subsystem group lies in the upper-unitriangular group, giving a faithful
homomorphism into that group. In particular the subsystem group is nilpotent, with no separate
root-string or commutator hypotheses. The basis is indexed by an arbitrary finite linearly
ordered type, which specializes to the `Fin n` carrier of the represented `GLₙ` scheme
downstream.

For a Chevalley system and `S` the positive roots, this is the group-level bridge from the positive
root-subgroup maps to the unipotent radical candidate in the Borel datum of the pinned
Chevalley--Demazure group scheme.

## Main declarations

* `EpsilonEridani.UniversalEnvelopingAlgebra.map_kostantSubsystemSubgroup_le_upperUnitriangular`: in
  ordered weight-basis coordinates, the subsystem group is upper unitriangular.
* `EpsilonEridani.UniversalEnvelopingAlgebra.kostantSubsystemUpperUnitriangular`: the resulting faithful
  homomorphism into the upper-unitriangular group.
* `EpsilonEridani.UniversalEnvelopingAlgebra.isNilpotent_kostantSubsystemSubgroup_of_isPositive`: a
  subsystem generated by positive weight shifts is nilpotent.

## References

* J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*, §§21, 26--27.
* R. W. Carter, *Simple Groups of Lie Type*, §§4.4 and 8.2.

This advances the pinning target of Layer 9 of `EpsilonEridaniRoadmap/ReductiveGroups/README.md`. Its
positive-root subgroup is consumed by milestone L0 of `EpsilonEridaniRoadmap/CFSGStatement/README.md` in
the construction of the Borel and ambient pinned group underlying
`EpsilonEridani.ValidLieTypeIndex.AmbientGroup`.
-/

public section

open CategoryTheory TensorProduct

namespace EpsilonEridani.UniversalEnvelopingAlgebra

universe u v w x

variable {L : Type u} [LieRing L] [LieAlgebra ℚ L]
variable {ι : Type w} {κ : Type*}
variable {V : Type x} [AddCommGroup V] [Module ℚ V]

variable (e : ι → L) (h : κ → L)
variable (ρ : _root_.UniversalEnvelopingAlgebra ℚ L →ₐ[ℚ] Module.End ℚ V)
variable (M : AddSubgroup V)
variable (hM : ∀ u ∈ kostantForm e h, ∀ v ∈ M, ρ u v ∈ M)
variable (hnil : ∀ i, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i))))
variable {η : Type*} [Fintype η] [LinearOrder η]
variable (b : Module.Basis η ℤ M) (wt : η → κ → ℤ)
variable (α : ι → κ → ℤ) (S : Set ι)

-- Match tensor products to the `ℤ`-algebra instance stored by `CommAlgCat` objects.
attribute [local instance high] Algebra.toModule

section

variable (hwt : ∀ x, IsCartanWeightVector h ρ (wt x) ((b x : M) : V))
variable (hα : ∀ i ∈ S, ∀ j, ⁅h j, e i⁆ = (α i j : ℚ) • e i)
variable (hpos : ∀ i ∈ S, ∀ {r s : η} {m : ℕ},
  0 < m → wt r = wt s + m • α i → r < s)

include wt α hwt hα hpos

/-- **A subsystem generated by positive weight shifts is upper unitriangular in ordered
weight-basis coordinates.**

The conclusion concerns the entire subgroup generated by the selected root subgroups, not only
its generators. Closure is supplied by the upper-unitriangular subgroup itself. -/
theorem map_kostantSubsystemSubgroup_le_upperUnitriangular (A : Type v) [CommRing A] :
    (kostantSubsystemSubgroup e h ρ M hM hnil S (CommAlgCat.of ℤ A)).map
        (Units.map (LinearMap.toMatrixAlgEquiv (b.baseChange A)).toMulEquiv) ≤
      upperUnitriangularGroup η A := by
  refine Subgroup.map_le_iff_le_comap.mpr ?_
  refine (kostantSubsystemSubgroup_le_iff e h ρ M hM hnil).mpr fun i hiS t ↦ ?_
  apply Subgroup.mem_comap.mpr
  have hle := range_kostantRootSubgroupMatrix_le_upperUnitriangular
    e h ρ M hM b wt i (hnil i) (A := A) hwt (hα i hiS) (hpos i hiS)
  rw [basisMatrix_kostantRootSubgroupParam]
  exact hle ⟨_, rfl⟩

/-- The faithful homomorphism from a positive Kostant subsystem group to the upper-unitriangular
group, obtained by writing its action in the ordered weight basis. -/
noncomputable def kostantSubsystemUpperUnitriangular (A : Type v) [CommRing A] :
    kostantSubsystemSubgroup e h ρ M hM hnil S (CommAlgCat.of ℤ A) →*
      upperUnitriangularGroup η A :=
  (((Units.map (LinearMap.toMatrixAlgEquiv (b.baseChange A)).toMulEquiv).comp
      (kostantSubsystemSubgroup e h ρ M hM hnil S (CommAlgCat.of ℤ A)).subtype).codRestrict
    (upperUnitriangularGroup η A) fun g ↦
      map_kostantSubsystemSubgroup_le_upperUnitriangular
        e h ρ M hM hnil b wt α S hwt hα hpos A ⟨g, g.2, rfl⟩)

/-- Forgetting the upper-unitriangular codomain recovers the matrix of the subsystem element in
the ordered weight basis. -/
@[simp]
theorem coe_kostantSubsystemUpperUnitriangular (A : Type v) [CommRing A]
    (g : kostantSubsystemSubgroup e h ρ M hM hnil S (CommAlgCat.of ℤ A)) :
    (kostantSubsystemUpperUnitriangular
        e h ρ M hM hnil b wt α S hwt hα hpos A g :
      Matrix.GeneralLinearGroup η A) =
      Units.map (LinearMap.toMatrixAlgEquiv (b.baseChange A)).toMulEquiv
        (g : LinearMap.GeneralLinearGroup A (A ⊗[ℤ] M)) := by
  rw [kostantSubsystemUpperUnitriangular]
  simp only [MonoidHom.codRestrict_apply, MonoidHom.comp_apply, Subgroup.subtype_apply]

/-- The upper-unitriangular representation of a positive Kostant subsystem group is injective. -/
theorem kostantSubsystemUpperUnitriangular_injective (A : Type v) [CommRing A] :
    Function.Injective
      (kostantSubsystemUpperUnitriangular
        e h ρ M hM hnil b wt α S hwt hα hpos A) := by
  intro g₁ g₂ heq
  apply Subtype.ext
  exact Units.map_injective (LinearMap.toMatrixAlgEquiv (b.baseChange A)).injective
    (congrArg Subtype.val heq)

omit [Fintype η] in
/-- **A Kostant subsystem generated by positive weight shifts is nilpotent.** It embeds faithfully
in the nilpotent upper-unitriangular group in ordered weight-basis coordinates. -/
theorem isNilpotent_kostantSubsystemSubgroup_of_isPositive [Finite η]
    (A : Type v) [CommRing A] :
    Group.IsNilpotent
      (kostantSubsystemSubgroup e h ρ M hM hnil S (CommAlgCat.of ℤ A)) := by
  have : Fintype η := Fintype.ofFinite η
  let f := kostantSubsystemUpperUnitriangular
    e h ρ M hM hnil b wt α S hwt hα hpos A
  let hRange : Group.IsNilpotent f.range := Subgroup.isNilpotent f.range
  exact @Group.nilpotent_of_mulEquiv f.range _ _ _ hRange
    (MonoidHom.ofInjective
      (kostantSubsystemUpperUnitriangular_injective
        e h ρ M hM hnil b wt α S hwt hα hpos A)).symm

end

end EpsilonEridani.UniversalEnvelopingAlgebra
