/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Claude
-/
module

public import Mathlib.GroupTheory.Nilpotent
public import EpsilonEridani.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Commutator.Basic
public import EpsilonEridani.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Elementary.Basic
public import EpsilonEridani.GroupTheory.Commutator

/-!
# Subgroups generated by a set of Kostant root subgroups

Let `U_ℤ = kostantForm e h` act on a rational representation `V` preserving an additive subgroup
`M ≤ V`, with every distinguished root vector `eᵢ` acting nilpotently. For a set `S` of indices,

```text
U_S(A) = ⟨xᵢ(t) : i ∈ S, t ∈ A⟩ ≤ Aut_A(A ⊗[ℤ] M)
```

is the subgroup generated by the corresponding Kostant root subgroups. Taking `S` to be all
indices recovers the elementary group of
`EpsilonEridani.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Elementary.Basic`. In the simply-laced
case, taking `S` to be the positive roots gives the positive-root subgroup, the class-two model of
the group that a pinning of a Chevalley--Demazure group scheme will exhibit as the unipotent
radical of a Borel subgroup; that identification is not made here.

The Chevalley commutator relations make `U_S` behave like the subgroup attached to a closed set of
roots. Two statements are proved. First, `U_S` is normalized by `U_T` whenever the bracket of a
root vector indexed in `T` with one indexed in `S` stays in `S`; this is
`IsChevalleyStableUnder`, which packages the class-two Chevalley hypothesis of
`EpsilonEridani.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Commutator.Basic` over a pair of index
sets. Second, if the indices of `S` carry a bounded height that every nonzero bracket strictly
raises, and each bracket root is central for both inputs, then `U_S(A)` is nilpotent: the
subgroups attached to the level sets `{i ∈ S | n ≤ ht i}` form a descending central series that
reaches the trivial subgroup.

The generic group-theoretic hypotheses of `kostantSubsystemSubgroup_le_normalizer` and
`commutator_kostantSubsystemSubgroup_le` are stated on the root-subgroup generators rather than
on Lie brackets, so that a longer commutator relation — a root string of length greater than one,
as occurs outside the simply-laced types — can be fed in the same way once available.

## Main declarations

* `EpsilonEridani.UniversalEnvelopingAlgebra.kostantSubsystemSubgroup`: the subgroup `U_S(A)` generated by
  the Kostant root subgroups indexed by `S`.
* `EpsilonEridani.UniversalEnvelopingAlgebra.IsChevalleyStableUnder`: the class-two Chevalley closure
  condition on a pair of index sets.
* `EpsilonEridani.UniversalEnvelopingAlgebra.kostantSubsystemSubgroup_le_normalizer_of_isChevalleyStable`:
  `U_T(A)` normalizes `U_S(A)` when `S` is stable under `T`.
* `EpsilonEridani.UniversalEnvelopingAlgebra.isNilpotent_kostantSubsystemSubgroup`: `U_S(A)` is nilpotent
  under a class-two, height-raising bracket hypothesis with the height bounded on `S`.

## References

* R. W. Carter, *Simple Groups of Lie Type*, §§5.2--5.3.
* J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*, §§26--27.
* J. C. Jantzen, *Representations of Algebraic Groups*, II.1.
-/

public section

open CategoryTheory TensorProduct WithConv
open scoped commutatorElement

namespace EpsilonEridani.UniversalEnvelopingAlgebra

universe u v w

variable {L : Type u} [LieRing L] [LieAlgebra ℚ L]
variable {ι : Type*} {κ : Type*}
variable {V : Type v} [AddCommGroup V] [Module ℚ V]

variable (e : ι → L) (h : κ → L)
variable (ρ : _root_.UniversalEnvelopingAlgebra ℚ L →ₐ[ℚ] Module.End ℚ V)
variable (M : AddSubgroup V)
variable (hM : ∀ u ∈ kostantForm e h, ∀ v ∈ M, ρ u v ∈ M)

-- Match tensor products to the `ℤ`-algebra instance stored by `CommAlgCat` objects.
attribute [local instance high] Algebra.toModule

section Relations

variable {i j k : ι}
variable (hi : IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i))))
variable (hj : IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e j))))
variable (hk : IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e k))))

/-- Root subgroups attached to commuting root vectors commute, with the parameter read in the
value ring. -/
theorem commute_kostantRootSubgroupParam (hij : ⁅e i, e j⁆ = 0) (A : CommAlgCat.{w} ℤ)
    (t u : Multiplicative A) :
    Commute (kostantRootSubgroupParam e h ρ M hM i hi A t)
      (kostantRootSubgroupParam e h ρ M hM j hj A u) := by
  rw [kostantRootSubgroupParam_apply, kostantRootSubgroupParam_apply]
  exact commute_kostantRootSubgroupPoints e h ρ M hM hij hi hj _ _

/-- **The Chevalley commutator relation with the parameter in the value ring.** If
`⁅eᵢ, eⱼ⁆ = c • eₖ` with `eₖ` central for both, then `xᵢ(t) xⱼ(u) xᵢ(t)⁻¹ = xⱼ(u) xₖ(c t u)`. -/
theorem kostantRootSubgroupParam_conj_of_lie_eq {c : ℤ} (hij : ⁅e i, e j⁆ = c • e k)
    (hik : ⁅e i, e k⁆ = 0) (hjk : ⁅e j, e k⁆ = 0) (A : CommAlgCat.{w} ℤ)
    (t u : Multiplicative A) :
    kostantRootSubgroupParam e h ρ M hM i hi A t *
        kostantRootSubgroupParam e h ρ M hM j hj A u *
        (kostantRootSubgroupParam e h ρ M hM i hi A t)⁻¹ =
      kostantRootSubgroupParam e h ρ M hM j hj A u *
        kostantRootSubgroupParam e h ρ M hM k hk A
          (Multiplicative.ofAdd
            ((c : A) * (Multiplicative.toAdd t * Multiplicative.toAdd u))) := by
  rw [kostantRootSubgroupParam_apply, kostantRootSubgroupParam_apply,
    kostantRootSubgroupParam_apply,
    kostantRootSubgroupPoints_conj_of_lie_eq' e h ρ M hM hij hik hjk hi hj hk]
  simp

/-- **The Chevalley commutator relation in element-commutator form, with the parameter in the
value ring**: `⁅xᵢ(t), xⱼ(u)⁆ = xₖ(c t u)`. -/
theorem commutatorElement_kostantRootSubgroupParam_of_lie_eq {c : ℤ}
    (hij : ⁅e i, e j⁆ = c • e k) (hik : ⁅e i, e k⁆ = 0) (hjk : ⁅e j, e k⁆ = 0)
    (A : CommAlgCat.{w} ℤ) (t u : Multiplicative A) :
    ⁅kostantRootSubgroupParam e h ρ M hM i hi A t,
        kostantRootSubgroupParam e h ρ M hM j hj A u⁆ =
      kostantRootSubgroupParam e h ρ M hM k hk A
        (Multiplicative.ofAdd
          ((c : A) * (Multiplicative.toAdd t * Multiplicative.toAdd u))) := by
  rw [kostantRootSubgroupParam_apply, kostantRootSubgroupParam_apply,
    kostantRootSubgroupParam_apply,
    commutatorElement_kostantRootSubgroupPoints_of_lie_eq' e h ρ M hM hij hik hjk hi hj hk]
  simp

end Relations

variable (hnil : ∀ i, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i))))

/-- The subgroup of `Aut_A(A ⊗[ℤ] M)` generated by the Kostant root subgroups indexed by a set `S`
of root indices. -/
noncomputable def kostantSubsystemSubgroup (S : Set ι) (A : CommAlgCat.{w} ℤ) :
    Subgroup (LinearMap.GeneralLinearGroup A (A ⊗[ℤ] M)) :=
  Subgroup.closure
    {g | ∃ i ∈ S, ∃ t, kostantRootSubgroupParam e h ρ M hM i (hnil i) A t = g}

-- The public `rfl` lemma below cannot unfold `kostantSubsystemSubgroup` itself: the module system
-- only lets an exported theorem unfold exposed definitions. This private theorem does the
-- unfolding, matching `kostantElementarySubgroup_eq_closure_def`.
private theorem kostantSubsystemSubgroup_eq_closure_def (S : Set ι) (A : CommAlgCat.{w} ℤ) :
    kostantSubsystemSubgroup e h ρ M hM hnil S A =
      Subgroup.closure
        {g | ∃ i ∈ S, ∃ t, kostantRootSubgroupParam e h ρ M hM i (hnil i) A t = g} :=
  rfl

/-- The subgroup attached to `S` is generated by the root-subgroup elements indexed by `S`. -/
theorem kostantSubsystemSubgroup_eq_closure (S : Set ι) (A : CommAlgCat.{w} ℤ) :
    kostantSubsystemSubgroup e h ρ M hM hnil S A =
      Subgroup.closure
        {g | ∃ i ∈ S, ∃ t, kostantRootSubgroupParam e h ρ M hM i (hnil i) A t = g} :=
  kostantSubsystemSubgroup_eq_closure_def e h ρ M hM hnil S A

/-- **Elimination principle.** A subgroup contains `U_S(A)` exactly when it contains every
root-subgroup element indexed by `S`. -/
theorem kostantSubsystemSubgroup_le_iff {S : Set ι} {A : CommAlgCat.{w} ℤ}
    {P : Subgroup (LinearMap.GeneralLinearGroup A (A ⊗[ℤ] M))} :
    kostantSubsystemSubgroup e h ρ M hM hnil S A ≤ P ↔
      ∀ i ∈ S, ∀ t : Multiplicative A,
        kostantRootSubgroupParam e h ρ M hM i (hnil i) A t ∈ P := by
  rw [kostantSubsystemSubgroup_eq_closure, Subgroup.closure_le]
  refine ⟨fun hle i hiS t => hle ⟨i, hiS, t, rfl⟩, ?_⟩
  rintro hgen - ⟨i, hiS, t, rfl⟩
  exact hgen i hiS t

/-- A root-subgroup element with index in `S` lies in the subgroup attached to `S`. -/
theorem kostantRootSubgroupParam_mem_kostantSubsystemSubgroup {S : Set ι} {i : ι} (hiS : i ∈ S)
    (A : CommAlgCat.{w} ℤ) (t : Multiplicative A) :
    kostantRootSubgroupParam e h ρ M hM i (hnil i) A t ∈
      kostantSubsystemSubgroup e h ρ M hM hnil S A :=
  Subgroup.subset_closure ⟨i, hiS, t, rfl⟩

/-- The subgroup attached to a set of indices grows with the set. -/
@[gcongr]
theorem kostantSubsystemSubgroup_mono {S T : Set ι} (hST : S ⊆ T) (A : CommAlgCat.{w} ℤ) :
    kostantSubsystemSubgroup e h ρ M hM hnil S A ≤
      kostantSubsystemSubgroup e h ρ M hM hnil T A :=
  (kostantSubsystemSubgroup_le_iff e h ρ M hM hnil).2 fun _ hiS t =>
    kostantRootSubgroupParam_mem_kostantSubsystemSubgroup e h ρ M hM hnil (hST hiS) A t

/-- The empty index set generates the trivial subgroup. -/
@[simp] theorem kostantSubsystemSubgroup_empty (A : CommAlgCat.{w} ℤ) :
    kostantSubsystemSubgroup e h ρ M hM hnil ∅ A = ⊥ := by
  rw [kostantSubsystemSubgroup_eq_closure, ← Subgroup.closure_empty]
  congr 1
  ext g
  simp

/-- All indices generate the elementary group. -/
@[simp] theorem kostantSubsystemSubgroup_univ (A : CommAlgCat.{w} ℤ) :
    kostantSubsystemSubgroup e h ρ M hM hnil Set.univ A =
      kostantElementarySubgroup e h ρ M hM hnil A := by
  rw [kostantSubsystemSubgroup_eq_closure, kostantElementarySubgroup_eq_closure]
  congr 1
  ext g
  simp [eq_comm]

/-- Every subsystem subgroup sits inside the elementary group. -/
theorem kostantSubsystemSubgroup_le_kostantElementarySubgroup (S : Set ι)
    (A : CommAlgCat.{w} ℤ) :
    kostantSubsystemSubgroup e h ρ M hM hnil S A ≤ kostantElementarySubgroup e h ρ M hM hnil A :=
  kostantSubsystemSubgroup_univ e h ρ M hM hnil A ▸
    kostantSubsystemSubgroup_mono e h ρ M hM hnil (Set.subset_univ S) A

/-- Scalar extension along a morphism of value rings carries a subsystem subgroup into the
subsystem subgroup attached to the same index set. -/
theorem map_kostantSubsystemSubgroup_le (S : Set ι) {A B : CommAlgCat.{w} ℤ} (φ : A ⟶ B) :
    (kostantSubsystemSubgroup e h ρ M hM hnil S A).map
        (GeneralLinear.mapScalarExtensionAutomorphisms (V := M) φ).hom ≤
      kostantSubsystemSubgroup e h ρ M hM hnil S B := by
  rw [kostantSubsystemSubgroup_eq_closure, MonoidHom.map_closure, Subgroup.closure_le]
  rintro - ⟨-, ⟨i, hiS, t, rfl⟩, rfl⟩
  exact (mapScalarExtensionAutomorphisms_kostantRootSubgroupParam e h ρ M hM i (hnil i) φ t) ▸
    kostantRootSubgroupParam_mem_kostantSubsystemSubgroup e h ρ M hM hnil hiS B _

section Normalizer

variable {S T R : Set ι} {A : CommAlgCat.{w} ℤ}

/-- **Generators normalize.** `U_T(A)` normalizes `U_S(A)` as soon as every root-subgroup element
indexed in `T` conjugates every root-subgroup element indexed in `S` back into `U_S(A)`.

The hypothesis is only needed for one of the two conjugations because the generating set is closed
under inverses: `xᵢ(t)⁻¹ = xᵢ(t⁻¹)`. -/
theorem kostantSubsystemSubgroup_le_normalizer
    (hconj : ∀ i ∈ T, ∀ j ∈ S, ∀ t u : Multiplicative A,
      kostantRootSubgroupParam e h ρ M hM i (hnil i) A t *
          kostantRootSubgroupParam e h ρ M hM j (hnil j) A u *
          (kostantRootSubgroupParam e h ρ M hM i (hnil i) A t)⁻¹ ∈
        kostantSubsystemSubgroup e h ρ M hM hnil S A) :
    kostantSubsystemSubgroup e h ρ M hM hnil T A ≤
      Subgroup.normalizer (kostantSubsystemSubgroup e h ρ M hM hnil S A : Set _) := by
  refine EpsilonEridani.closure_le_normalizer_closure ?_ ?_
  · rintro - ⟨i, hiT, t, rfl⟩ - ⟨j, hjS, u, rfl⟩
    exact hconj i hiT j hjS t u
  · rintro - ⟨i, hiT, t, rfl⟩ - ⟨j, hjS, u, rfl⟩
    have := hconj i hiT j hjS t⁻¹ u
    rwa [map_inv, inv_inv] at this

/-- **Generators bound a commutator subgroup.** If a subsystem subgroup is normalized by two
others, then it contains their commutator as soon as it contains the commutators of the
root-subgroup generators. -/
theorem commutator_kostantSubsystemSubgroup_le
    (hS : kostantSubsystemSubgroup e h ρ M hM hnil S A ≤
      Subgroup.normalizer (kostantSubsystemSubgroup e h ρ M hM hnil R A : Set _))
    (hT : kostantSubsystemSubgroup e h ρ M hM hnil T A ≤
      Subgroup.normalizer (kostantSubsystemSubgroup e h ρ M hM hnil R A : Set _))
    (hcomm : ∀ i ∈ S, ∀ j ∈ T, ∀ t u : Multiplicative A,
      ⁅kostantRootSubgroupParam e h ρ M hM i (hnil i) A t,
          kostantRootSubgroupParam e h ρ M hM j (hnil j) A u⁆ ∈
        kostantSubsystemSubgroup e h ρ M hM hnil R A) :
    ⁅kostantSubsystemSubgroup e h ρ M hM hnil S A,
        kostantSubsystemSubgroup e h ρ M hM hnil T A⁆ ≤
      kostantSubsystemSubgroup e h ρ M hM hnil R A := by
  refine EpsilonEridani.commutator_closure_closure_le hS hT ?_
  rintro - ⟨i, hiS, t, rfl⟩ - ⟨j, hjT, u, rfl⟩
  exact hcomm i hiS j hjT t u

end Normalizer

/-- The index set `S` is **Chevalley stable** under the index set `T` when, for every `i ∈ T` and
`j ∈ S`, the root vectors `eᵢ` and `eⱼ` either commute or have bracket an integer multiple of a
third root vector `eₖ` with `k ∈ S`, central for both.

This is the class-two case of the Chevalley commutator formula: `α + β` is a root while neither
`2α + β` nor `α + 2β` is. In a simply-laced root system every pair of non-proportional roots falls
under one of the two alternatives, so a set of roots closed under addition is stable under any set
of roots that maps it into itself. -/
def IsChevalleyStableUnder (e : ι → L) (S T : Set ι) : Prop :=
  ∀ i ∈ T, ∀ j ∈ S, ⁅e i, e j⁆ = 0 ∨
    ∃ k ∈ S, ∃ c : ℤ, ⁅e i, e j⁆ = c • e k ∧ ⁅e i, e k⁆ = 0 ∧ ⁅e j, e k⁆ = 0

/-- A Chevalley-stable index set has its subsystem subgroup normalized by the larger one. -/
theorem kostantSubsystemSubgroup_le_normalizer_of_isChevalleyStable {S T : Set ι}
    (hstable : IsChevalleyStableUnder e S T) (A : CommAlgCat.{w} ℤ) :
    kostantSubsystemSubgroup e h ρ M hM hnil T A ≤
      Subgroup.normalizer (kostantSubsystemSubgroup e h ρ M hM hnil S A : Set _) := by
  refine kostantSubsystemSubgroup_le_normalizer e h ρ M hM hnil fun i hiT j hjS t u => ?_
  rcases hstable i hiT j hjS with hij | ⟨k, hkS, c, hij, hik, hjk⟩
  · rw [(commute_kostantRootSubgroupParam e h ρ M hM (hnil i) (hnil j) hij A t u).eq,
      mul_inv_cancel_right]
    exact kostantRootSubgroupParam_mem_kostantSubsystemSubgroup e h ρ M hM hnil hjS A u
  · rw [kostantRootSubgroupParam_conj_of_lie_eq e h ρ M hM (hnil i) (hnil j) (hnil k)
      hij hik hjk A t u]
    exact mul_mem
      (kostantRootSubgroupParam_mem_kostantSubsystemSubgroup e h ρ M hM hnil hjS A u)
      (kostantRootSubgroupParam_mem_kostantSubsystemSubgroup e h ρ M hM hnil hkS A _)

/-- A Chevalley-stable index set contained in `T` is normal in the subsystem subgroup of `T`. -/
theorem kostantSubsystemSubgroup_normal_subgroupOf {S T : Set ι} (hST : S ⊆ T)
    (hstable : IsChevalleyStableUnder e S T) (A : CommAlgCat.{w} ℤ) :
    ((kostantSubsystemSubgroup e h ρ M hM hnil S A).subgroupOf
      (kostantSubsystemSubgroup e h ρ M hM hnil T A)).Normal :=
  (Subgroup.normal_subgroupOf_iff_le_normalizer
      (kostantSubsystemSubgroup_mono e h ρ M hM hnil hST A)).2
    (kostantSubsystemSubgroup_le_normalizer_of_isChevalleyStable e h ρ M hM hnil hstable A)

section Nilpotent

variable {S : Set ι} {ht : ι → ℕ} {n : ℕ}

/-- The set of indices of `S` of height at least `n`. -/
private def heightLevel (S : Set ι) (ht : ι → ℕ) (n : ℕ) : Set ι := {i ∈ S | n ≤ ht i}

/-- Membership in a height level set. -/
private theorem mem_heightLevel {i : ι} :
    i ∈ heightLevel S ht n ↔ i ∈ S ∧ n ≤ ht i := Iff.rfl

/-- **The unipotent group of a class-two graded closed set of roots is nilpotent.** Suppose every
index of `S` has height at most `N`, and that whenever two root vectors indexed in `S` fail to
commute their bracket is an integer multiple of a third root vector, indexed in `S`, of strictly
larger height and central for both. Then `U_S(A)` is nilpotent over every value ring.

The height hypothesis is only stated for the first of the two indices; the second one comes for
free by reading it at the swapped pair, whose bracket is the negative.

For a simply-laced Chevalley system and `S` the positive roots this is the class-two model of the
positive-root subgroup, with `ht` the height of a root and `N` the height of the highest root. The
identification of that subgroup with the unipotent radical of a Borel subgroup needs a pinning and
is not part of this statement; longer root strings in non-simply-laced systems are not covered. -/
theorem isNilpotent_kostantSubsystemSubgroup {N : ℕ} (hbdd : ∀ i ∈ S, ht i ≤ N)
    (hgrade : ∀ i ∈ S, ∀ j ∈ S, ⁅e i, e j⁆ = 0 ∨
      ∃ k ∈ S, ht i < ht k ∧ ∃ c : ℤ,
        ⁅e i, e j⁆ = c • e k ∧ ⁅e i, e k⁆ = 0 ∧ ⁅e j, e k⁆ = 0)
    (A : CommAlgCat.{w} ℤ) :
    Group.IsNilpotent (kostantSubsystemSubgroup e h ρ M hM hnil S A) := by
  -- Every level set is Chevalley stable under `S`, so its subgroup is normalized by `U_S`.
  -- Reading `hgrade` at the swapped pair keeps the bracket root above the height of `j`.
  have hstable : ∀ m, IsChevalleyStableUnder e (heightLevel S ht m) S := by
    intro m i hiS j hj
    obtain ⟨hjS, hjm⟩ := mem_heightLevel.1 hj
    rcases hgrade j hjS i hiS with hji | ⟨k, hkS, hkht, c, hji, hjk, hik⟩
    · exact Or.inl (by rw [← lie_skew, hji, neg_zero])
    · refine Or.inr ⟨k, mem_heightLevel.2 ⟨hkS, (hjm.trans_lt hkht).le⟩, -c, ?_, hik, hjk⟩
      rw [← lie_skew, hji, neg_smul]
  have hnorm : ∀ m, kostantSubsystemSubgroup e h ρ M hM hnil S A ≤
      Subgroup.normalizer
        (kostantSubsystemSubgroup e h ρ M hM hnil (heightLevel S ht m) A : Set _) := fun m =>
    kostantSubsystemSubgroup_le_normalizer_of_isChevalleyStable e h ρ M hM hnil (hstable m) A
  have hsub : ∀ m, heightLevel S ht m ⊆ S := fun _ _ hi => (mem_heightLevel.1 hi).1
  -- The level sets give a descending central series: brackets raise the height, so the commutator
  -- of level `m` with all of `S` lands in level `m + 1`.
  have hcomm : ∀ m, ⁅kostantSubsystemSubgroup e h ρ M hM hnil (heightLevel S ht m) A,
      kostantSubsystemSubgroup e h ρ M hM hnil S A⁆ ≤
      kostantSubsystemSubgroup e h ρ M hM hnil (heightLevel S ht (m + 1)) A := by
    intro m
    refine commutator_kostantSubsystemSubgroup_le e h ρ M hM hnil
      (le_trans (kostantSubsystemSubgroup_mono e h ρ M hM hnil (hsub m) A) (hnorm (m + 1)))
      (hnorm (m + 1)) fun i hi j hjS t u => ?_
    rcases hgrade i (mem_heightLevel.1 hi).1 j hjS with hij | ⟨k, hkS, hkht, c, hij, hik, hjk⟩
    · rw [(commute_kostantRootSubgroupParam e h ρ M hM (hnil i) (hnil j) hij A t u).commutator_eq]
      exact one_mem _
    · rw [commutatorElement_kostantRootSubgroupParam_of_lie_eq e h ρ M hM (hnil i) (hnil j)
        (hnil k) hij hik hjk A t u]
      exact kostantRootSubgroupParam_mem_kostantSubsystemSubgroup e h ρ M hM hnil
        (mem_heightLevel.2 ⟨hkS, lt_of_le_of_lt (mem_heightLevel.1 hi).2 hkht⟩) A _
  rw [Subgroup.nilpotent_iff_finite_descending_central_series]
  refine ⟨N + 1,
    fun m => (kostantSubsystemSubgroup e h ρ M hM hnil (heightLevel S ht m) A).subgroupOf
      (kostantSubsystemSubgroup e h ρ M hM hnil S A), ⟨?_, ?_⟩, ?_⟩
  · have hzero : heightLevel S ht 0 = S := by
      ext i
      simp [mem_heightLevel]
    dsimp only
    rw [hzero, Subgroup.subgroupOf_self]
  · intro x m hx g
    rw [Subgroup.mem_subgroupOf] at hx ⊢
    rw [commutatorElement_def]
    push_cast
    rw [← commutatorElement_def]
    exact Subgroup.commutator_le.1 (hcomm m) _ hx _ g.2
  · have htop : heightLevel S ht (N + 1) = ∅ := by
      ext i
      simp only [mem_heightLevel, Set.mem_empty_iff_false, iff_false, not_and, Nat.not_le]
      exact fun hiS => Nat.lt_succ_of_le (hbdd i hiS)
    dsimp only
    rw [htop, kostantSubsystemSubgroup_empty, Subgroup.bot_subgroupOf]

end Nilpotent

end EpsilonEridani.UniversalEnvelopingAlgebra
