/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.Algebra.Lie.UniversalEnveloping.Kostant.Basis
public import EpsilonEridani.Algebra.Lie.UniversalEnveloping.Kostant.Orbit
public import EpsilonEridani.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Torus.Basic
public import EpsilonEridani.Algebra.Lie.UniversalEnveloping.MatrixRepresentation
public import EpsilonEridani.LinearAlgebra.RootSystem.SimplyConnectedRootDatum.LieAlgebra.Basic

/-!
# A simple-generator Kostant form of the pinned split Lie algebra of a Dynkin type

`EpsilonEridani.DynkinType.lieAlgebra` is the split Lie algebra of a valid Dynkin type, realized by Geck's
construction as an explicit Lie subalgebra of `GeckIndex`-indexed rational matrices, with Chevalley
generators `EpsilonEridani.DynkinType.lieBasis` numbered by Bourbaki node. This file attaches the
simple-generator Kostant subring of its universal enveloping algebra to that pinned data, and
records the defining matrix representation through which the subring acts.

The form is generated by divided powers of the simple raising and lowering generators and by
binomial coefficients in the simple Cartan generators. Identifying it with the canonical
all-root Kostant `ℤ`-form is a separate theorem and is not claimed here.

Four things are needed before the divided powers of the Kostant form can be exponentiated into
root subgroups, and all four are supplied here.

*The form itself.* `EpsilonEridani.DynkinType.kostantForm` is
`LieAlgebra.Basis.kostantForm` applied to the pinned Lie algebra basis. Because the raising
and lowering generators already generate the whole Lie algebra,
`EpsilonEridani.DynkinType.span_kostantForm_eq_top` says the form spans `U(L)` over `ℚ` without further
hypotheses.

*A representation to act in.* Geck's Lie algebra consists of actual matrices, so its defining
action on `GeckIndex → ℚ` is available with no representation theory at all:
`EpsilonEridani.DynkinType.geckRepresentation` is the algebra map extending it, and it is faithful on the
Lie algebra by `EpsilonEridani.DynkinType.geckRepresentation_ι_injective`.

*Nilpotency and weights.* `EpsilonEridani.DynkinType.isNilpotent_geckRepresentation_rootGenerator` says
every numbered root generator acts nilpotently, which makes its divided-power exponential a finite
sum; and `EpsilonEridani.DynkinType.isCartanWeightVector_geckRepresentation_single` says each standard
coordinate vector is a joint eigenvector of the Cartan generators, with the *integer* eigenvalue
`EpsilonEridani.DynkinType.geckWeight`. In the Bourbaki numbering that weight is zero on the pinned base
support coordinates and is the Cartan pairing `⟨α_k, α_i^∨⟩` on the coordinate of the root `α_k`.

*A `ℤ`-module to act on.* `EpsilonEridani.DynkinType.geckOrbit` is the `ℤ`-span of the images of the
standard coordinate vectors under the whole Kostant form. It is stable under the form by
construction and spans the Geck module over `ℚ`, so it discharges the stability hypothesis that
every Kostant root-subgroup consumer has so far carried.

The orbit is in fact finitely generated over `ℤ`: it coincides with the coordinate lattice of
`EpsilonEridani/LinearAlgebra/RootSystem/SimplyConnectedRootDatum/GeckLattice/Basic.lean`, because that
lattice is preserved by the whole form, so it is a full lattice in the sense of Humphreys §27.
Nor is the pinned Lie
algebra asserted to be semisimple, which
`EpsilonEridani/LinearAlgebra/RootSystem/SimplyConnectedRootDatum/LieAlgebra/Basic.lean` already records as
not claimed. This file is the numbered input those later steps consume.

## Main definitions

* `EpsilonEridani.DynkinType.kostantForm`: the pinned simple-generator Kostant form.
* `EpsilonEridani.DynkinType.geckRepresentation`: the defining matrix representation of `U(L)`.
* `EpsilonEridani.DynkinType.geckWeight`: the integral weight of a Geck coordinate.
* `EpsilonEridani.DynkinType.rootGeneratorWeight`: the integral root of a numbered raising or lowering
  generator.
* `EpsilonEridani.DynkinType.geckOrbit`: the integral orbit of the standard coordinate vectors.

## Main results

* `EpsilonEridani.DynkinType.span_kostantForm_eq_top`: the Kostant form spans the enveloping algebra
  over `ℚ`.
* `EpsilonEridani.DynkinType.geckRepresentation_ι_injective`: the defining representation is faithful on
  the Lie algebra.
* `EpsilonEridani.DynkinType.isNilpotent_geckRepresentation_rootGenerator`: each numbered root generator
  acts nilpotently.
* `EpsilonEridani.DynkinType.isCartanWeightVector_geckRepresentation_single`: the standard coordinate
  vectors are Cartan weight vectors with integer weights.
* `EpsilonEridani.DynkinType.lie_lieBasis_h_rootGenerator`: the Cartan action on each numbered root
  generator is given by its integral root.
* `EpsilonEridani.DynkinType.rootGeneratorWeight_inl_eq_root_simpleIndex` and
  `EpsilonEridani.DynkinType.rootGeneratorWeight_inr_eq_neg_root_simpleIndex`: that integral root is the
  simple root of `EpsilonEridani.DynkinType.simplyConnectedRootDatum` with the same Bourbaki node number,
  respectively its negative.
* `EpsilonEridani.DynkinType.geckRepresentation_mem_geckOrbit` and
  `EpsilonEridani.DynkinType.span_geckOrbit_eq_top`: the integral orbit is stable under the Kostant form
  and spans the Geck module over `ℚ`.
* In `…/GeckLattice/Basic.lean`, `EpsilonEridani.DynkinType.geckOrbit_eq_geckCoordinateLattice` and
  `EpsilonEridani.DynkinType.instIsLatticeGeckOrbit`: the orbit equals the coordinate lattice and is a
  full, finitely generated lattice.

## References

* J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*, §26.
* M. Geck, *On the construction of semisimple Lie algebras and Chevalley groups*,
  Proc. Amer. Math. Soc. **145** (2017), 3233--3247.
* J. C. Jantzen, *Representations of Algebraic Groups*, II.1.

Layer 9 of `EpsilonEridaniRoadmap/ReductiveGroups/README.md` asks for the split reductive group scheme
over `ℤ` to be constructed "via a Chevalley basis and the Kostant `ℤ`-form of the enveloping
algebra". The concrete Geck matrix carrier is used here because its defining faithful
representation supplies the module on which the root subgroups will act. The separate
`EpsilonEridani.serreKostantForm` is the presentation-level simple-generator form used to study the
symmetries before passing to this concrete carrier. No comparison between those two forms is yet
proved; such a comparison is required before presentation-level results are transported here, and
the two forms are not intended to define independent group schemes. The consumer of the assembled
pinned construction is milestone L0 of `EpsilonEridaniRoadmap/CFSGStatement/README.md`.
-/

public section

namespace EpsilonEridani.DynkinType

open RootPairing.GeckConstruction Set

open scoped _root_.Matrix

noncomputable section

-- Matrices form a Lie ring through their commutator, which is how Geck's construction reads
-- them; the `SimplyConnectedRootDatum/LieAlgebra/Basic.lean` module activates the same instance
-- locally.
attribute [local instance 100] LieRing.ofAssociativeRing

attribute [local instance] EpsilonEridani.moduleNNRat

variable (t : DynkinType) (ht : t.Valid)

/-! ## The simple-generator Kostant form -/

/-- **The simple-generator Kostant form of the pinned split Lie algebra**: the subring of `U(L)`
generated by divided powers of the numbered simple raising and lowering generators and by binomial
coefficients of the numbered Cartan generators.

Identification with the canonical all-root Kostant `ℤ`-form is not asserted. -/
def kostantForm :
    Subring (_root_.UniversalEnvelopingAlgebra ℚ (t.lieAlgebra ht)) :=
  (t.lieBasis ht).kostantForm

/-- The pinned form is the basis Kostant form for the pinned Lie algebra basis. -/
theorem kostantForm_def : t.kostantForm ht = (t.lieBasis ht).kostantForm := (rfl)

/-- Every divided power of a numbered raising or lowering generator lies in the Kostant form. -/
theorem dividedPower_mem_kostantForm (i : Fin t.rank ⊕ Fin t.rank) (n : ℕ) :
    Associative.dividedPower n
        (_root_.UniversalEnvelopingAlgebra.ι ℚ ((t.lieBasis ht).rootGenerator i)) ∈
      t.kostantForm ht := by
  rw [kostantForm_def]
  exact (t.lieBasis ht).dividedPower_mem_kostantForm i n

/-- Every binomial coefficient of a numbered Cartan generator lies in the Kostant form. -/
theorem ringChoose_mem_kostantForm (i : Fin t.rank) (n : ℕ) :
    Ring.choose (_root_.UniversalEnvelopingAlgebra.ι ℚ ((t.lieBasis ht).h i)) n ∈
      t.kostantForm ht := by
  rw [kostantForm_def]
  exact (t.lieBasis ht).ringChoose_mem_kostantForm i n

/-- The universal property of the pinned simple-generator Kostant form. -/
@[simp]
theorem kostantForm_le_iff
    (T : Subring (_root_.UniversalEnvelopingAlgebra ℚ (t.lieAlgebra ht))) :
    t.kostantForm ht ≤ T ↔
      (∀ i n, Associative.dividedPower n
        (_root_.UniversalEnvelopingAlgebra.ι ℚ ((t.lieBasis ht).rootGenerator i)) ∈ T) ∧
      ∀ i n, Ring.choose (_root_.UniversalEnvelopingAlgebra.ι ℚ ((t.lieBasis ht).h i)) n ∈ T := by
  rw [kostantForm_def, LieAlgebra.Basis.kostantForm_le_iff]

/-- **The Kostant form spans the enveloping algebra.** Its `ℚ`-span is the whole universal
enveloping algebra of the pinned split Lie algebra.

This is the spanning half of the expected integral-form statement; freeness over `ℤ` and
comparison with the classical all-root form require additional results. -/
theorem span_kostantForm_eq_top :
    Submodule.span ℚ (t.kostantForm ht :
        Set (_root_.UniversalEnvelopingAlgebra ℚ (t.lieAlgebra ht))) = ⊤ :=
  (t.lieBasis ht).span_kostantForm_eq_top

/-! ## The roots of the numbered generators -/

/-- **The root of a numbered raising or lowering generator**, as an integral character of the
pinned Cartan generators: the corresponding Bourbaki Cartan-matrix row for a raising generator,
and its negative for a lowering generator. -/
def rootGeneratorWeight : Fin t.rank ⊕ Fin t.rank → Fin t.rank → ℤ :=
  (t.lieBasis ht).rootGeneratorWeight

@[simp] theorem rootGeneratorWeight_inl (i j : Fin t.rank) :
    t.rootGeneratorWeight ht (.inl i) j = t.cartanMatrix i j := by
  rw [rootGeneratorWeight, LieAlgebra.Basis.rootGeneratorWeight_inl, lieBasis_A_eq]

@[simp] theorem rootGeneratorWeight_inr (i j : Fin t.rank) :
    t.rootGeneratorWeight ht (.inr i) j = -t.cartanMatrix i j := by
  rw [rootGeneratorWeight, LieAlgebra.Basis.rootGeneratorWeight_inr, lieBasis_A_eq]

/-! The two identifications below read those Cartan-matrix rows as the simple roots of
`EpsilonEridani.DynkinType.simplyConnectedRootDatum`. They are deliberately not `simp` lemmas: both sides
are already `simp`-normal, since `rootGeneratorWeight_inl` and `root_simpleIndex` rewrite them to
the same row, and orienting the identification either way would undo one of them. -/

/-- **The root of the `i`-th numbered raising generator is the `i`-th pinned simple root.** The
integral character of the pinned Cartan generators through which they act on that generator is the
simple root of `t.simplyConnectedRootDatum ht` with the same Bourbaki node number. -/
theorem rootGeneratorWeight_inl_eq_root_simpleIndex (i : Fin t.rank) :
    t.rootGeneratorWeight ht (.inl i) =
      (t.simplyConnectedRootDatum ht).root (t.simpleIndex ht i) := by
  funext j
  rw [rootGeneratorWeight_inl, root_simpleIndex]

/-- **The root of the `i`-th numbered lowering generator is the negative of the `i`-th pinned
simple root.** -/
theorem rootGeneratorWeight_inr_eq_neg_root_simpleIndex (i : Fin t.rank) :
    t.rootGeneratorWeight ht (.inr i) =
      -(t.simplyConnectedRootDatum ht).root (t.simpleIndex ht i) := by
  funext j
  rw [rootGeneratorWeight_inr, Pi.neg_apply, root_simpleIndex]

/-- **The pinned Cartan generators act on a numbered root generator through its root.** -/
theorem lie_lieBasis_h_rootGenerator (i : Fin t.rank ⊕ Fin t.rank) (j : Fin t.rank) :
    ⁅(t.lieBasis ht).h j, (t.lieBasis ht).rootGenerator i⁆ =
      ((t.rootGeneratorWeight ht i j : ℤ) : ℚ) • (t.lieBasis ht).rootGenerator i := by
  rw [rootGeneratorWeight]
  exact (t.lieBasis ht).lie_h_rootGenerator i j

/-! ## The defining representation -/

/-- **The defining representation of the pinned split Lie algebra**, extended to its universal
enveloping algebra. Geck's Lie algebra is a Lie subalgebra of matrices, so the representation is
the matrix action on coordinate vectors; no existence theorem for a faithful representation is
invoked. -/
def geckRepresentation :
    _root_.UniversalEnvelopingAlgebra ℚ (t.lieAlgebra ht) →ₐ[ℚ]
      Module.End ℚ (t.GeckIndex ht → ℚ) :=
  (t.lieAlgebra ht).matrixRepresentation

/-- The Geck representation is the defining representation of its matrix Lie subalgebra. -/
theorem geckRepresentation_def :
    t.geckRepresentation ht = (t.lieAlgebra ht).matrixRepresentation := (rfl)

-- Neither this lemma nor its pointwise form below is a `simp` lemma: `simp` unfolds `ι` through
-- Mathlib's `UniversalEnvelopingAlgebra.ι_apply`, so a left-hand side mentioning `ι` is not in
-- simp-normal form.
/-- A Lie generator acts through its underlying matrix. -/
theorem geckRepresentation_ι (x : t.lieAlgebra ht) :
    t.geckRepresentation ht (_root_.UniversalEnvelopingAlgebra.ι ℚ x) =
      Matrix.toLinAlgEquiv' (x : Matrix (t.GeckIndex ht) (t.GeckIndex ht) ℚ) := by
  rw [geckRepresentation_def]
  exact LieSubalgebra.matrixRepresentation_ι (t.lieAlgebra ht) x

/-- The pointwise form of `EpsilonEridani.DynkinType.geckRepresentation_ι`: a Lie generator acts by
multiplying a coordinate vector by its underlying matrix. -/
theorem geckRepresentation_ι_apply (x : t.lieAlgebra ht) (v : t.GeckIndex ht → ℚ) :
    t.geckRepresentation ht (_root_.UniversalEnvelopingAlgebra.ι ℚ x) v =
      (x : Matrix (t.GeckIndex ht) (t.GeckIndex ht) ℚ) *ᵥ v := by
  rw [geckRepresentation_def]
  exact LieSubalgebra.matrixRepresentation_ι_apply (t.lieAlgebra ht) x v

/-- **The defining representation is faithful on the Lie algebra.** Distinct elements of the
pinned Lie algebra act
differently, so the Lie algebra embeds in the endomorphisms of the Geck module. -/
theorem geckRepresentation_ι_injective :
    Function.Injective fun x : t.lieAlgebra ht =>
      t.geckRepresentation ht (_root_.UniversalEnvelopingAlgebra.ι ℚ x) := by
  rw [geckRepresentation_def]
  exact LieSubalgebra.matrixRepresentation_ι_injective (t.lieAlgebra ht)

/-! ## Nilpotency of the numbered generators -/

/-- **Every numbered root generator acts nilpotently.** This is what makes the divided-power
exponential of a root vector a finite sum, hence an automorphism of any stable lattice over any
value ring. -/
theorem isNilpotent_geckRepresentation_rootGenerator (i : Fin t.rank ⊕ Fin t.rank) :
    IsNilpotent (t.geckRepresentation ht
      (_root_.UniversalEnvelopingAlgebra.ι ℚ ((t.lieBasis ht).rootGenerator i))) := by
  rw [geckRepresentation_def]
  apply LieSubalgebra.isNilpotent_matrixRepresentation_ι (t.lieAlgebra ht)
  cases i with
  | inl i => simpa only [LieAlgebra.Basis.rootGenerator_inl] using
      t.isNilpotent_coe_lieBasis_e ht i
  | inr i => simpa only [LieAlgebra.Basis.rootGenerator_inr] using
      t.isNilpotent_coe_lieBasis_f ht i

/-! ## The weights of the Geck module -/

/-- **The integral weight of a Geck coordinate**, in the Bourbaki numbering: zero on the
coordinates indexed by the pinned base support, and the Cartan pairing `⟨α_k, α_i^∨⟩` on the
coordinate indexed by the root `α_k`.

The matrix of each of Geck's Cartan generators is diagonal
(`RootPairing.GeckConstruction.h_eq_diagonal`) with these entries, so this is the weight function
of the standard coordinate vectors, and it takes values in `ℤ` rather than merely in `ℚ`. -/
def geckWeight : t.GeckIndex ht → Fin t.rank → ℤ :=
  Sum.elim 0 fun k i => (t.rationalRootSystem ht).pairingIn ℤ k (t.simpleSupportEquiv ht i)

@[simp] theorem geckWeight_inl (x : (t.rationalBase ht).support) (i : Fin t.rank) :
    t.geckWeight ht (Sum.inl x) i = 0 := (rfl)

@[simp] theorem geckWeight_inr (k : Fin t.numRoots) (i : Fin t.rank) :
    t.geckWeight ht (Sum.inr k) i =
      (t.rationalRootSystem ht).pairingIn ℤ k (t.simpleSupportEquiv ht i) := (rfl)

/-- **The standard coordinate vectors are joint eigenvectors of the Cartan generators**, with the
integer eigenvalues recorded by `EpsilonEridani.DynkinType.geckWeight`.

This is the pinned split torus in embryo: the diagonal action of the Cartan subalgebra on the
standard lattice of the Geck module is by integral characters, numbered by Bourbaki node. -/
theorem isCartanWeightVector_geckRepresentation_single (x : t.GeckIndex ht) :
    UniversalEnvelopingAlgebra.IsCartanWeightVector (t.lieBasis ht).h
      (t.geckRepresentation ht) (t.geckWeight ht x) (Pi.single x 1) := by
  classical
  rw [UniversalEnvelopingAlgebra.isCartanWeightVector_iff]
  intro i
  rw [geckRepresentation_ι_apply, coe_lieBasis_h, h_eq_diagonal,
    Matrix.diagonal_mulVec_single]
  cases x <;> simp [← Pi.single_smul']

/-! ## The integral orbit of the standard coordinates -/

/-- **The integral orbit of the standard coordinates of the Geck module**: the `ℤ`-span of the
images of the standard coordinate vectors under the simple-generator Kostant form.

Every downstream consumer of a Kostant root subgroup takes a `ℤ`-submodule preserved by the whole
integral form as a hypothesis. This one is preserved by construction, by
`EpsilonEridani.DynkinType.geckRepresentation_mem_geckOrbit`, and it is full by
`EpsilonEridani.DynkinType.span_geckOrbit_eq_top`. Its finite generation over `ℤ` is proved in
`EpsilonEridani/LinearAlgebra/RootSystem/SimplyConnectedRootDatum/GeckLattice/Basic.lean`,
where the orbit is identified with the coordinate lattice. -/
def geckOrbit : Submodule ℤ (t.GeckIndex ht → ℚ) :=
  UniversalEnvelopingAlgebra.orbitOfRep (t.kostantForm ht) (t.geckRepresentation ht)
    (range fun x => Pi.single x 1)

/-- The pinned integral orbit is the generic represented orbit of the standard coordinate
vectors. -/
theorem geckOrbit_def :
    t.geckOrbit ht = UniversalEnvelopingAlgebra.orbitOfRep (t.kostantForm ht)
      (t.geckRepresentation ht) (range fun x => Pi.single x 1) := (rfl)

/-- A Kostant-form translate of a standard coordinate vector lies in the integral orbit. -/
theorem geckRepresentation_single_mem_geckOrbit
    {u : _root_.UniversalEnvelopingAlgebra ℚ (t.lieAlgebra ht)} (hu : u ∈ t.kostantForm ht)
    (x : t.GeckIndex ht) :
    t.geckRepresentation ht u (Pi.single x 1) ∈ t.geckOrbit ht := by
  rw [geckOrbit_def]
  exact UniversalEnvelopingAlgebra.apply_mem_orbitOfRep _ _ _ hu (mem_range_self x)

/-- Every standard coordinate vector lies in the integral orbit, the identity of the enveloping
algebra being one of the elements the orbit is taken over. -/
theorem single_mem_geckOrbit (x : t.GeckIndex ht) :
    Pi.single x (1 : ℚ) ∈ t.geckOrbit ht := by
  rw [geckOrbit_def]
  exact UniversalEnvelopingAlgebra.subset_orbitOfRep _ _ _ (mem_range_self x)

/-- **The integral orbit is stable under the Kostant form.** This is the hypothesis a Kostant root
subgroup needs of the stable `ℤ`-submodule it acts on, and it holds here because the orbit is taken
over a subring: acting again multiplies inside the form. -/
theorem geckRepresentation_mem_geckOrbit
    {u : _root_.UniversalEnvelopingAlgebra ℚ (t.lieAlgebra ht)} (hu : u ∈ t.kostantForm ht)
    {v : t.GeckIndex ht → ℚ} (hv : v ∈ t.geckOrbit ht) :
    t.geckRepresentation ht u v ∈ t.geckOrbit ht := by
  rw [geckOrbit_def] at hv ⊢
  exact UniversalEnvelopingAlgebra.apply_mem_orbitOfRep_of_mem _ _ _ hu hv

/-- The elimination principle for the pinned integral orbit. -/
theorem geckOrbit_le_iff (N : Submodule ℤ (t.GeckIndex ht → ℚ)) :
    t.geckOrbit ht ≤ N ↔
      ∀ u ∈ t.kostantForm ht, ∀ x,
        t.geckRepresentation ht u (Pi.single x 1) ∈ N := by
  rw [geckOrbit_def, UniversalEnvelopingAlgebra.orbitOfRep_le_iff]
  constructor
  · intro h u hu x
    exact h u hu (Pi.single x 1) (mem_range_self x)
  · rintro h u hu - ⟨x, rfl⟩
    exact h u hu x

/-- **The integral orbit is full.** It spans the Geck module over `ℚ`, because it already contains
the standard coordinate vectors. -/
theorem span_geckOrbit_eq_top :
    Submodule.span ℚ (t.geckOrbit ht : Set (t.GeckIndex ht → ℚ)) = ⊤ := by
  classical
  rw [geckOrbit_def]
  apply UniversalEnvelopingAlgebra.span_orbitOfRep_eq_top
  have hrange : range (fun x : t.GeckIndex ht => Pi.single x (1 : ℚ)) =
      range (Pi.basisFun ℚ (t.GeckIndex ht)) :=
    congrArg Set.range
      (funext fun x => (Pi.basisFun_apply ℚ (t.GeckIndex ht) x).symm)
  rw [hrange, (Pi.basisFun ℚ (t.GeckIndex ht)).span_eq]

end

end EpsilonEridani.DynkinType
