/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

import Mathlib.LinearAlgebra.Matrix.NonsingularInverse
import EpsilonEridani.LinearAlgebra.IntegralLattice.RootLattice.TypeD.SimpleRoots
import EpsilonEridani.LinearAlgebra.Matrix.Cartan.Classical
public import EpsilonEridani.LinearAlgebra.RootSystem.SimplyConnectedRootDatum.Assembly

/-!
# When the pinned root lattice is the whole character lattice

The character lattice of `EpsilonEridani.DynkinType.simplyConnectedRootDatum` is the lattice of
fundamental weights: `EpsilonEridani.DynkinType.coroot_simpleIndex` makes the simple coroots the standard
basis vectors, so `EpsilonEridani.DynkinType.root_simpleIndex` writes each simple root as the
corresponding row of the Bourbaki-numbered Cartan matrix. The roots therefore span the character
lattice exactly when those rows do, which is exactly when the Cartan matrix is invertible over
`ℤ`. That criterion is `EpsilonEridani.DynkinType.span_range_root_eq_top_iff_isUnit_det`, and evaluating
it on the nine valid families gives
`EpsilonEridani.DynkinType.span_range_root_eq_top_iff`: the root lattice is the whole character lattice
precisely in types `E₈`, `F₄` and `G₂`.

The point of the criterion is which admissible lattice an explicit Chevalley--Demazure carrier has
to be built from. A carrier's split torus acts through the lattice generated by the weights of the
representation used to construct it, so a carrier whose weights generate only the root lattice is a
candidate for the adjoint form and not for the simply connected form. The classification below says
that this obstruction is present in six of the nine types, so that the `E₈`, `F₄` and `G₂`
constructions built from the root lattice do not generalize: the remaining types need an admissible
lattice in a representation whose weights generate a larger sublattice of the character lattice,
namely the standard module in types `A` and `C`, and a spin or minuscule module in types `B`, `D`,
`E₆` and `E₇`.

Nothing here is a group. The coroot side is unaffected: the coroots of the pinned datum span the
cocharacter lattice for every valid type, which is
`EpsilonEridani.DynkinType.span_coroot_simplyConnectedRootDatum` and is what makes the datum the simply
connected one.

## Main results

* `EpsilonEridani.DynkinType.span_range_root_eq_top_iff_isUnit_det`: the roots of the pinned datum span
  its character lattice if and only if its Cartan matrix has unit determinant.
* `EpsilonEridani.DynkinType.isUnit_det_cartanMatrix_iff`: the Cartan matrix of a valid Dynkin type has
  unit determinant precisely in types `E₈`, `F₄` and `G₂`.
* `EpsilonEridani.DynkinType.span_range_root_eq_top_iff`: the resulting classification of the types whose
  root lattice is the whole character lattice.

## References

* J. E. Humphreys, *Linear Algebraic Groups*, §27, for the role of the lattice generated by the
  weights of an admissible lattice in separating the isogeny forms.
* J. C. Jantzen, *Representations of Algebraic Groups*, II.1.
* N. Bourbaki, *Lie Groups and Lie Algebras, Chapters 4--6*, Plates I--IX, for the Cartan matrices
  and their determinants.

This decides which admissible lattices the Chevalley--Demazure construction of Layer 9 of
`EpsilonEridaniRoadmap/ReductiveGroups/README.md` may be built from, for its consumer, the pinned simply
connected ambient group of milestone L0 of `EpsilonEridaniRoadmap/CFSGStatement/README.md`.
-/

public section

namespace EpsilonEridani.DynkinType

open Set _root_.Submodule

/-- The simple roots of the pinned datum, read off the Bourbaki-numbered base, are exactly the rows
of its Cartan matrix. -/
private theorem image_support_simplyConnectedBase_eq_range_row (t : DynkinType) (ht : t.Valid) :
    (t.simplyConnectedRootDatum ht).root '' ↑(t.simplyConnectedBase ht).support =
      range t.cartanMatrix.row := by
  rw [Set.image_eq_range, ← (t.simpleSupportEquivSimplyConnectedBase ht).surjective.range_comp]
  simp [Function.comp_def, Matrix.row_def]

/-- **The roots of the pinned simply connected datum span its character lattice exactly when the
Cartan matrix is invertible over `ℤ`.** The simple roots are the rows of that matrix, and the base
generates every root over `ℤ`, so the root lattice is the row lattice. -/
theorem span_range_root_eq_top_iff_isUnit_det (t : DynkinType) (ht : t.Valid) :
    span ℤ (range (t.simplyConnectedRootDatum ht).root) = ⊤ ↔ IsUnit t.cartanMatrix.det := by
  rw [← (t.simplyConnectedBase ht).span_int_root_support,
    image_support_simplyConnectedBase_eq_range_row, ← _root_.range_vecMulLinear,
    LinearMap.range_eq_top, Matrix.coe_vecMulLinear, Matrix.vecMul_surjective_iff_isUnit,
    Matrix.isUnit_iff_isUnit_det]

/-- **The Cartan matrix of a valid Dynkin type is unimodular precisely in types `E₈`, `F₄` and
`G₂`.** The determinant of `A n` is `n + 1`, those of `B n` and `C n` are `2`, and those of
`D n`, `E₆` and `E₇` are `4`, `3` and `2`. -/
@[simp]
theorem isUnit_det_cartanMatrix_iff (t : DynkinType) (ht : t.Valid) :
    IsUnit t.cartanMatrix.det ↔ t = E8 ∨ t = F4 ∨ t = G2 := by
  cases t with
  | A n =>
    have hn : 1 ≤ n := valid_A.mp ht
    have hdet : (A n).cartanMatrix.det = (n : ℤ) + 1 := by
      rw [cartanMatrix_A]; exact CartanMatrix.A_det n
    exact iff_of_false (by rw [hdet, Int.isUnit_iff]; omega) (by simp)
  | B n =>
    have hn : 2 ≤ n := valid_B.mp ht
    have hdet : (B n).cartanMatrix.det = 2 := by
      rw [cartanMatrix_B]; exact CartanMatrix.B_det (by omega)
    exact iff_of_false (by rw [hdet, Int.isUnit_iff]; decide) (by simp)
  | C n =>
    have hn : 3 ≤ n := valid_C.mp ht
    have hdet : (C n).cartanMatrix.det = 2 := by
      rw [cartanMatrix_C]; exact CartanMatrix.C_det (by omega)
    exact iff_of_false (by rw [hdet, Int.isUnit_iff]; decide) (by simp)
  | D n =>
    have hn : 4 ≤ n := valid_D.mp ht
    have hdet : (D n).cartanMatrix.det = 4 := by
      rw [cartanMatrix_D]; exact CartanMatrix.D_det (by omega)
    exact iff_of_false (by rw [hdet, Int.isUnit_iff]; decide) (by simp)
  | E6 =>
    have hdet : E6.cartanMatrix.det = 3 := by rw [cartanMatrix_E6]; exact CartanMatrix.E₆_det
    exact iff_of_false (by rw [hdet, Int.isUnit_iff]; decide) (by simp)
  | E7 =>
    have hdet : E7.cartanMatrix.det = 2 := by rw [cartanMatrix_E7]; exact CartanMatrix.E₇_det
    exact iff_of_false (by rw [hdet, Int.isUnit_iff]; decide) (by simp)
  | E8 =>
    have hdet : E8.cartanMatrix.det = 1 := by rw [cartanMatrix_E8]; exact CartanMatrix.E₈_det
    rw [hdet]
    simp
  | F4 =>
    have hdet : F4.cartanMatrix.det = 1 := by rw [cartanMatrix_F4]; exact CartanMatrix.F₄_det
    rw [hdet]
    simp
  | G2 =>
    have hdet : G2.cartanMatrix.det = 1 := by
      rw [cartanMatrix_G2]
      exact (Matrix.det_transpose CartanMatrix.G₂).trans CartanMatrix.G₂_det
    rw [hdet]
    simp

/-- **The root lattice of the pinned simply connected datum is the whole character lattice
precisely in types `E₈`, `F₄` and `G₂`.** In the other six valid types the root lattice is a proper
sublattice, so a Chevalley--Demazure carrier built from an admissible lattice whose weights
generate only the root lattice is not the simply connected form there. -/
@[simp]
theorem span_range_root_eq_top_iff (t : DynkinType) (ht : t.Valid) :
    span ℤ (range (t.simplyConnectedRootDatum ht).root) = ⊤ ↔ t = E8 ∨ t = F4 ∨ t = G2 :=
  (span_range_root_eq_top_iff_isUnit_det t ht).trans (isUnit_det_cartanMatrix_iff t ht)

end EpsilonEridani.DynkinType
