"""Ensure the site's examples project builds the library at exactly the root's pins.

Run with: python3 scripts/test_web_pins.py

`web/examples` compiles the EpsilonEridani library, so it needs a Lean toolchain and a Mathlib, and the
only correct ones are the root project's. Nothing in Lake enforces that, and nothing outside
`pages.yml` builds that project, so when they part company the only symptom is the three-hourly
Pages job going red while every pull request stays green. That is not hypothetical: by September
2026 the examples project was two Lean releases and several hundred Mathlib commits behind, and
the site build broke on a deck-transformation `HSMul` instance -- a file that compiled perfectly
well at the root pins. The site had already served stale content for a day before anyone looked,
because a failing scheduled workflow is quiet.

Rather than commit copies of the pins and keep them in step, both are generated by
`scripts/sync_web_pins.py` from the root's and neither is committed; `.gitignore` covers them
and the Pages workflow writes them before building.

The toolchain is generated rather than inherited, which is worth stating because the opposite
looks right. elan resolves a toolchain from the nearest ancestor directory, so deleting
`web/examples/lean-toolchain` seems like it would make this project use the root's. The nearest
ancestor is `web/`, and `web/lean-toolchain` names the Verso site's Lean, which lags the
library's -- so deleting the file silently pins this project to the stale toolchain that broke
the site in the first place. `test_deleting_the_toolchain_would_inherit_the_wrong_one` holds
that trap open so nobody re-treads it.

That also keeps a Mathlib bump touching only the root pins. Committing the copies put two files
outside `EpsilonEridani/` into every bump, and the merge policy refuses to auto-merge a pull request
touching a lakefile or an unlisted path, so each bump would have stopped for a human.

These tests check the generator's output rather than any committed file, because after this
change there is no committed file left to check.
"""

import json
import pathlib
import subprocess
import sys
import unittest

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import sync_web_pins as sync  # noqa: E402

ROOT = sync.ROOT


def git(*args):
    return subprocess.run(["git", *args], cwd=ROOT, capture_output=True, text=True)


class WebPins(unittest.TestCase):
    def setUp(self):
        self.generated = {p["name"]: p for p in sync.derived_manifest()["packages"]}
        self.root = {p["name"]: p for p in sync.load(sync.ROOT_MANIFEST)["packages"]}
        self.web = {p["name"]: p for p in sync.load(sync.WEB_MANIFEST)["packages"]}

    def test_the_generator_writes_the_root_toolchain(self):
        # Mutates a wrong value in and checks the generator plans to correct it, rather than
        # asserting that the generator's output equals the generator's input, which an earlier
        # version of this test did and which passed happily on a drifted file.
        original = (sync.EXAMPLES_TOOLCHAIN.read_text()
                    if sync.EXAMPLES_TOOLCHAIN.exists() else None)
        try:
            sync.EXAMPLES_TOOLCHAIN.write_text("leanprover/lean4:v0.0.0-not-the-root\n")
            planned = dict(sync.planned_changes())
            self.assertIn(sync.EXAMPLES_TOOLCHAIN, planned,
                          "the generator left a toolchain that is not the root's in place")
            self.assertEqual(planned[sync.EXAMPLES_TOOLCHAIN], sync.ROOT_TOOLCHAIN.read_text(),
                             "web/examples must build with the root's Lean, not another one")
        finally:
            if original is None:
                sync.EXAMPLES_TOOLCHAIN.unlink(missing_ok=True)
            else:
                sync.EXAMPLES_TOOLCHAIN.write_text(original)

    def test_deleting_the_toolchain_would_inherit_the_wrong_one(self):
        # The trap this design exists to avoid. If web/ ever stops pinning a different Lean from
        # the root, generating the file becomes unnecessary and inheriting would be simpler --
        # but while these differ, an absent file resolves to Verso's Lean, not the library's.
        web_toolchain = ROOT / "web/lean-toolchain"
        self.assertTrue(web_toolchain.is_file(),
                        "web/lean-toolchain vanished; re-check whether elan would now inherit "
                        "the root toolchain, in which case generating one is redundant")
        self.assertNotEqual(
            web_toolchain.read_text().strip(), sync.ROOT_TOOLCHAIN.read_text().strip(),
            "web/ and the root now pin the same Lean. Inheriting would be safe again; if you "
            "make that change, delete the generated toolchain and this test together.")

    def test_the_toolchain_is_not_tracked(self):
        tracked = git("ls-files", "--error-unmatch", "web/examples/lean-toolchain")
        self.assertNotEqual(
            tracked.returncode, 0,
            "web/examples/lean-toolchain is tracked again; committing it puts a file outside "
            "EpsilonEridani/ into every Mathlib bump and stops the bump auto-merging.")
        ignored = git("check-ignore", "-q", "web/examples/lean-toolchain")
        self.assertEqual(ignored.returncode, 0,
                         "web/examples/lean-toolchain is not covered by .gitignore")

    def test_the_manifest_is_not_tracked(self):
        tracked = git("ls-files", "--error-unmatch", "web/examples/lake-manifest.json")
        self.assertNotEqual(
            tracked.returncode, 0,
            "web/examples/lake-manifest.json is tracked again. It is generated from the root "
            "pins; committing it puts a file outside EpsilonEridani/ into every Mathlib bump and stops "
            "the bump auto-merging.")

    def test_the_manifest_is_ignored(self):
        ignored = git("check-ignore", "-q", "web/examples/lake-manifest.json")
        self.assertEqual(ignored.returncode, 0,
                         "web/examples/lake-manifest.json is not covered by .gitignore")

    def test_every_shared_package_is_copied_from_the_root(self):
        # Copied, not re-resolved: that is what makes disagreement impossible rather than merely
        # unlikely. Compared field for field, so a differing inputRev or url is caught too.
        for name, entry in sorted(self.root.items()):
            with self.subTest(package=name):
                self.assertIn(name, self.generated,
                              f"the root pins {name} but the generated manifest omits it")
                self.assertEqual(
                    self.generated[name], entry,
                    f"the generated {name} entry differs from the root's; it must be copied "
                    "verbatim so the two projects cannot disagree about a revision")

    def test_it_adds_only_the_two_entries_the_root_lacks(self):
        extra = set(self.generated) - set(self.root)
        self.assertEqual(
            extra, {"EpsilonEridani", "subverso"},
            "the generated manifest introduces packages the root does not pin: "
            f"{sorted(extra - {'EpsilonEridani', 'subverso'})}. Anything beyond the root closure, the "
            "path requirement, and SubVerso is unpinned by the root and free to drift.")

    def test_subverso_matches_the_verso_site(self):
        self.assertEqual(
            self.generated["subverso"]["rev"], self.web["subverso"]["rev"],
            "the generated manifest and web/ resolve different SubVerso commits. SubVerso "
            "supports being built on a different Lean toolchain from the Verso that reads its "
            "output, but makes no promise across its own versions -- its data format is an "
            "implementation detail. The site would read snippets with a reader that did not "
            "write them.")

    def test_the_lakefile_still_builds_the_library(self):
        # The premise of everything above: if the examples project stopped compiling EpsilonEridani,
        # matching the root's pins would no longer be what makes the site build trustworthy.
        text = sync.EXAMPLES_LAKEFILE.read_text()
        self.assertRegex(
            text, r'require\s+«?EpsilonEridani»?\s+from\s+"\.\./\.\."',
            "web/examples/lakefile.lean no longer requires EpsilonEridani from '../..'; revisit the "
            "docstring above rather than deleting this test.")

    def test_the_lakefile_nominates_mathlib_the_way_the_root_does(self):
        # The generator copies the root's mathlib entry wholesale, inputRev included. That is
        # only honest while this lakefile asks for the same thing the root's asks for.
        self.assertEqual(sync.nominated(sync.MATHLIB_REQUIRE, "mathlib"), "master")

    def test_generating_twice_changes_nothing(self):
        first = sync.render(sync.derived_manifest())
        second = sync.render(sync.derived_manifest())
        self.assertEqual(first, second)


if __name__ == "__main__":
    unittest.main()
