/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.AlgebraicGeometry.WeilDivisor.Dedekind.ClassGroup
public import EpsilonEridani.FieldTheory.FunctionField.AffineModel.Prime
public import EpsilonEridani.FieldTheory.FunctionField.Divisor.ProductFormula

/-!
# The affine-model bridge at divisor level

An *affine model* of `F / k` is a Dedekind `k`-subalgebra `R` of `F` whose fraction field is `F`.
`EpsilonEridani/FieldTheory/FunctionField/AffineModel/Prime.lean` identifies the places of `F / k` finite
on `R` with the height one primes of `R`, place by place.  This file carries that dictionary up to
divisors and divisor classes.

Restricting a divisor of `F / k` to the finite chart — discarding the coefficients at the places
infinite on `R` — is a surjective homomorphism `Divisor k F →+ WeilDivisor (HeightOneSpectrum R)`
onto the divisor group of the model, and it carries `div z` to the divisor of the principal
fractional ideal generated by `z`.  It therefore descends to divisor classes, where Tau Ceti's
`classGroupAddEquiv` — the identification of the Weil divisor class group of a Dedekind domain
with Mathlib's `ClassGroup R`, built from `FractionalIdeal.count` — turns it into a surjection

`Cl(F) →+ Additive (ClassGroup R)`

whose kernel is exactly the subgroup generated by the classes of the places infinite on `R`.  That
is the exact sequence `⟨[P] : P ∤ R⟩ → Cl(F) → ClassGroup R → 0`: the ideal class group of an
affine model is the divisor class group of `F / k` with the classes of the places at infinity
killed.  The kernel is a *subgroup generated by* those classes rather than a free group on them,
because a function whose divisor is supported at infinity imposes a relation.

The specialization Mathlib's elliptic curves want closes the file: when the model has a single
place at infinity and that place is rational, the surjection restricts to an isomorphism
`Cl⁰(F) ≃+ ClassGroup R` from the degree-zero class group.

Restriction is split by pushforward along `EpsilonEridani.Place.ofPrime`, so the divisor group of the
model sits inside `Divisor k F` as the divisors supported on the finite chart; composing with Tau
Ceti's `fractionalIdealDivisorAddEquiv` turns divisors of the model into invertible fractional
ideals, so no fractional-ideal calculus is redeveloped here.

This is the affine-model bridge of Stichtenoth's Section I.4: the Dedekind factorization calculus
of the model computes divisors on its chart.

## Main definitions

* `EpsilonEridani.Divisor.restrict`: restriction of a divisor of `F / k` to the finite chart of a model.
* `EpsilonEridani.Divisor.classGroupHom`: the induced map from the divisor class group of `F / k` to the
  ideal class group of the model.
* `EpsilonEridani.Divisor.degreeZeroClassGroupEquiv`: the isomorphism `Cl⁰(F) ≃+ ClassGroup R` for a
  model whose only place at infinity is rational.

## Main results

* `EpsilonEridani.Divisor.restrict_principal`: restriction carries principal divisors to principal
  divisors.
* `EpsilonEridani.Divisor.classGroupHom_surjective`: the induced map on class groups is surjective.
* `EpsilonEridani.Divisor.ker_classGroupHom`: its kernel is generated by the classes of the places
  infinite on the model.
* `EpsilonEridani.Divisor.exists_degreeClass_mem_Ico_and_classGroupHom_eq`: every ideal class of the
  model is the image of a divisor class whose degree lies in `[0, deg P)`, for any place `P`
  infinite on the model.
* `EpsilonEridani.Divisor.classGroupHom_comp_subtype_surjective`: if some place infinite on the model is
  rational, then `Cl⁰(F)` already surjects onto the ideal class group of the model.

## References

* H. Stichtenoth, *Algebraic Function Fields and Codes*, 2nd ed., GTM 254, Springer, 2009,
  Sections I.4 and III.2.
-/

public section

open IsDedekindDomain

namespace EpsilonEridani

open AlgebraicGeometry AlgebraicGeometry.WeilDivisor

namespace Divisor

universe u v w

variable {k : Type u} {F : Type v} [Field k] [Field F] [Algebra k F]
  {R : Type w} [CommRing R] [IsDedekindDomain R] [Algebra k R] [Algebra R F]
  [IsScalarTower k R F] [IsFractionRing R F]

/-! ### Restriction to the finite chart -/

variable (R) in
/-- **Restriction of a divisor to the finite chart of an affine model** `R`: the coefficient at a
height one prime `𝔭` of `R` is the coefficient at the place of `𝔭`, and the coefficients at the
places infinite on `R` are discarded. -/
noncomputable def restrict : Divisor k F →+ WeilDivisor (HeightOneSpectrum R) :=
  WeilDivisor.pullback (Place.ofPrime_injective (R := R) k F)

@[simp]
theorem coeff_restrict (D : Divisor k F) (𝔭 : HeightOneSpectrum R) :
    (restrict R D).coeff 𝔭 = D.coeff (Place.ofPrime k F 𝔭) :=
  WeilDivisor.coeff_pullback _ D 𝔭

@[simp]
theorem restrict_pushforward (D : WeilDivisor (HeightOneSpectrum R)) :
    restrict R (WeilDivisor.pushforward (Place.ofPrime k F) D) = D :=
  WeilDivisor.pullback_pushforward _ D

theorem restrict_surjective : Function.Surjective (restrict (k := k) (F := F) R) :=
  fun D => ⟨WeilDivisor.pushforward (Place.ofPrime k F) D, restrict_pushforward D⟩

@[simp]
theorem restrict_ofPoint_ofPrime (𝔭 : HeightOneSpectrum R) :
    restrict R (WeilDivisor.ofPoint (Place.ofPrime k F 𝔭)) = WeilDivisor.ofPoint 𝔭 :=
  WeilDivisor.pullback_ofPoint _ 𝔭

/-- A place at which some element of the model has a pole contributes nothing to the finite
chart. -/
theorem restrict_ofPoint_of_exists_notMem_integers {P : Place k F}
    (hP : ∃ r : R, algebraMap R F r ∉ P.integers) :
    restrict R (WeilDivisor.ofPoint P) = 0 := by
  refine WeilDivisor.pullback_ofPoint_of_notMem_range _ ?_
  rw [← Set.mem_compl_iff, Place.compl_range_ofPrime k F R]
  exact hP

/-- **Restriction carries principal divisors to principal divisors.**  The order at the place of a
height one prime `𝔭` is the `𝔭`-adic order, because the place of `𝔭` has the `𝔭`-adic valuation
on the nose; so `div z` restricts to the divisor of the principal fractional ideal of `z`. -/
@[simp]
theorem restrict_principal (hF : IsFunctionField k F) (z : Fˣ) :
    restrict R (principal hF z) =
      (WeilDivisor.OrderSystem.ofDedekindDomain R F).principalDivisor (Additive.ofMul z) :=
  WeilDivisor.ext fun 𝔭 => by
    rw [coeff_restrict, coeff_principal, WeilDivisor.OrderSystem.coeff_principalDivisor,
      WeilDivisor.OrderSystem.ofDedekindDomain_ord, WeilDivisor.adicOrd_ofMul, Place.ord_def,
      Place.valuation_ofPrime]

/-- The order-system form of `EpsilonEridani.Divisor.restrict_principal`. -/
theorem restrict_principalDivisor (hF : IsFunctionField k F) (z : Additive Fˣ) :
    restrict R ((Place.orderSystem hF).principalDivisor z) =
      (WeilDivisor.OrderSystem.ofDedekindDomain R F).principalDivisor z := by
  rw [Divisor.principalDivisor_eq hF, restrict_principal, ofMul_toMul]

/-! ### The class group of the model as a quotient -/

variable (R) in
/-- **The ideal class group of an affine model, as a quotient of the divisor class group of
`F / k`**: the map induced by restriction to the finite chart, read through the identification
`EpsilonEridani.AlgebraicGeometry.WeilDivisor.classGroupAddEquiv` of the Weil divisor class group of a
Dedekind domain with Mathlib's `ClassGroup`. -/
noncomputable def classGroupHom (hF : IsFunctionField k F) :
    (Place.orderSystem hF).ClassGroup →+ Additive (ClassGroup R) :=
  WeilDivisor.OrderSystem.ClassGroup.lift _
    (((WeilDivisor.classGroupAddEquiv R F).toAddMonoidHom.comp
        (WeilDivisor.OrderSystem.ofDedekindDomain R F).divisorClass).comp
      (restrict (k := k) (F := F) R))
    fun z => by
      simp only [AddMonoidHom.coe_comp, Function.comp_apply, AddEquiv.coe_toAddMonoidHom]
      rw [restrict_principalDivisor hF,
        WeilDivisor.OrderSystem.divisorClass_principalDivisor, map_zero]

@[simp]
theorem classGroupHom_divisorClass (hF : IsFunctionField k F) (D : Divisor k F) :
    classGroupHom R hF ((Place.orderSystem hF).divisorClass D) =
      WeilDivisor.classGroupAddEquiv R F
        ((WeilDivisor.OrderSystem.ofDedekindDomain R F).divisorClass (restrict R D)) :=
  WeilDivisor.OrderSystem.ClassGroup.lift_divisorClass _ _ _ D

/-- The class of a place finite on the model goes to the ideal class of the corresponding height
one prime.  This is the non-vacuity of `EpsilonEridani.Divisor.classGroupHom`. -/
theorem classGroupHom_divisorClass_ofPoint_ofPrime (hF : IsFunctionField k F)
    (𝔭 : HeightOneSpectrum R) :
    classGroupHom R hF
        ((Place.orderSystem hF).divisorClass (WeilDivisor.ofPoint (Place.ofPrime k F 𝔭))) =
      Additive.ofMul 𝔭.classGroupMk := by
  rw [classGroupHom_divisorClass, restrict_ofPoint_ofPrime,
    WeilDivisor.classGroupAddEquiv_divisorClass_ofPoint]

/-- The class of a place infinite on the model dies in the ideal class group of the model. -/
theorem classGroupHom_divisorClass_ofPoint_of_exists_notMem_integers (hF : IsFunctionField k F)
    {P : Place k F} (hP : ∃ r : R, algebraMap R F r ∉ P.integers) :
    classGroupHom R hF ((Place.orderSystem hF).divisorClass (WeilDivisor.ofPoint P)) = 0 := by
  rw [classGroupHom_divisorClass, restrict_ofPoint_of_exists_notMem_integers hP, map_zero,
    map_zero]

/-- **Every ideal class of an affine model comes from a divisor class of `F / k`.** -/
theorem classGroupHom_surjective (hF : IsFunctionField k F) :
    Function.Surjective (classGroupHom R hF) := by
  intro x
  obtain ⟨D, hD⟩ := (WeilDivisor.OrderSystem.ofDedekindDomain R F).divisorClass_surjective
    ((WeilDivisor.classGroupAddEquiv R F).symm x)
  refine ⟨(Place.orderSystem hF).divisorClass (WeilDivisor.pushforward (Place.ofPrime k F) D), ?_⟩
  rw [classGroupHom_divisorClass, restrict_pushforward, hD, AddEquiv.apply_symm_apply]

/-- A divisor whose restriction to the finite chart vanishes is supported at the places infinite
on the model, hence is an integer combination of them. -/
private theorem mem_closure_of_restrict_eq_zero {D : Divisor k F} (hD : restrict R D = 0) :
    D ∈ AddSubgroup.closure
      (WeilDivisor.ofPoint '' {P : Place k F | ∃ r : R, algebraMap R F r ∉ P.integers}) := by
  rw [← Place.compl_range_ofPrime k F R]
  refine WeilDivisor.mem_closure_ofPoint_image_of_support_subset fun P hP hmem => ?_
  obtain ⟨𝔭, rfl⟩ := hmem
  exact (WeilDivisor.mem_support_iff.mp hP) (by rw [← coeff_restrict, hD, WeilDivisor.coeff_zero])

variable (R) in
/-- **The kernel of the class-group surjection is generated by the classes of the places infinite
on the model**: the sequence `⟨[P] : P ∤ R⟩ → Cl(F) → ClassGroup R → 0` is exact.  It is the
subgroup *generated by* those classes, not a free group on them: a function whose divisor is
supported at infinity imposes a relation. -/
theorem ker_classGroupHom (hF : IsFunctionField k F) :
    (classGroupHom R hF).ker =
      AddSubgroup.closure ((Place.orderSystem hF).divisorClass ''
        (WeilDivisor.ofPoint '' {P : Place k F | ∃ r : R, algebraMap R F r ∉ P.integers})) := by
  refine le_antisymm ?_ ?_
  · rintro c hc
    obtain ⟨D, rfl⟩ := (Place.orderSystem hF).divisorClass_surjective c
    rw [AddMonoidHom.mem_ker, classGroupHom_divisorClass,
      AddEquiv.map_eq_zero_iff, WeilDivisor.OrderSystem.divisorClass_eq_zero_iff] at hc
    obtain ⟨u, hu⟩ := (WeilDivisor.OrderSystem.ofDedekindDomain R F).mem_principalSubgroup.mp hc
    have hzero : restrict R (D - principal hF (Additive.toMul u)) = 0 := by
      rw [map_sub, restrict_principal, ofMul_toMul, hu, sub_self]
    rw [← AddMonoidHom.map_closure]
    refine ⟨D - principal hF (Additive.toMul u), mem_closure_of_restrict_eq_zero hzero, ?_⟩
    rw [map_sub, sub_eq_self, ← Divisor.principalDivisor_eq hF,
      WeilDivisor.OrderSystem.divisorClass_principalDivisor]
  · rw [AddSubgroup.closure_le]
    rintro c ⟨-, ⟨P, hP, rfl⟩, rfl⟩
    exact classGroupHom_divisorClass_ofPoint_of_exists_notMem_integers hF hP

variable (R) in
/-- **Every ideal class of an affine model comes from a divisor class of bounded degree.**  Fix a
place `P` infinite on `R`; its class dies in the ideal class group of the model, so a preimage of
an ideal class may be corrected by an integer multiple of `[P]` without changing its image, and
the multiple can be chosen to move its degree into `[0, deg P)`.

This is what makes the ideal class group of a model a quotient of finitely many degree classes:
over a finite constant field each of those degree classes is a coset of the finite group `Cl⁰(F)`.
-/
theorem exists_degreeClass_mem_Ico_and_classGroupHom_eq (hF : IsFunctionField k F)
    {P : Place k F} (hP : ∃ r : R, algebraMap R F r ∉ P.integers)
    (x : Additive (ClassGroup R)) :
    ∃ c, degreeClass hF c ∈ Set.Ico (0 : ℤ) (P.degree : ℤ) ∧ classGroupHom R hF c = x := by
  obtain ⟨c, hc⟩ := classGroupHom_surjective (R := R) hF x
  have hd : (0 : ℤ) < (P.degree : ℤ) := by
    exact_mod_cast P.one_le_degree_of_isFunctionField hF
  set c' := c - (degreeClass hF c / (P.degree : ℤ)) •
    (Place.orderSystem hF).divisorClass (WeilDivisor.ofPoint P) with hc'
  -- Correcting by a multiple of `[P]` replaces the degree by its remainder modulo `deg P`.
  have hmod : degreeClass hF c' = degreeClass hF c % (P.degree : ℤ) := by
    rw [hc', map_sub, map_zsmul, degreeClass_divisorClass, degree_ofPoint, smul_eq_mul]
    exact (eq_sub_of_add_eq (Int.emod_add_ediv_mul _ _)).symm
  refine ⟨c', ⟨?_, ?_⟩, ?_⟩
  · rw [hmod]
    exact Int.emod_nonneg _ hd.ne'
  · rw [hmod]
    exact Int.emod_lt_of_pos _ hd
  · rw [hc', map_sub, map_zsmul,
      classGroupHom_divisorClass_ofPoint_of_exists_notMem_integers hF hP, smul_zero, sub_zero, hc]

variable (R) in
/-- **With a rational place at infinity, every ideal class of the model comes from a degree-zero
divisor class**: the bounded-degree representative above then has degree in `[0, 1)`, hence degree
zero.  Uniqueness of the place at infinity is not needed. -/
theorem exists_degreeClass_eq_zero_and_classGroupHom_eq (hF : IsFunctionField k F)
    {P : Place k F} (hP : ∃ r : R, algebraMap R F r ∉ P.integers) (hdeg : P.degree = 1)
    (x : Additive (ClassGroup R)) :
    ∃ c, degreeClass hF c = 0 ∧ classGroupHom R hF c = x := by
  obtain ⟨c, hc, hcx⟩ := exists_degreeClass_mem_Ico_and_classGroupHom_eq R hF hP x
  rw [hdeg, Nat.cast_one] at hc
  exact ⟨c, by have := Set.mem_Ico.mp hc; omega, hcx⟩

variable (R) in
/-- **With a rational place at infinity, the ideal class group of the model is a quotient of
`Cl⁰(F)`.**  Uniqueness of the place at infinity is not needed; with it, the map is also injective
and `EpsilonEridani.Divisor.degreeZeroClassGroupEquiv` upgrades it to an isomorphism. -/
theorem classGroupHom_comp_subtype_surjective (hF : IsFunctionField k F) {P : Place k F}
    (hP : ∃ r : R, algebraMap R F r ∉ P.integers) (hdeg : P.degree = 1) :
    Function.Surjective ((classGroupHom R hF).comp (degreeClass hF).ker.subtype) := fun x ↦ by
  obtain ⟨c, hc, hcx⟩ := exists_degreeClass_eq_zero_and_classGroupHom_eq R hF hP hdeg x
  exact ⟨⟨c, AddMonoidHom.mem_ker.mpr hc⟩, by simpa using hcx⟩

/-! ### A model with a single rational place at infinity -/

section UniqueInfinitePlace

variable (R) (hF : IsFunctionField k F) {P : Place k F}
  (hP : {Q : Place k F | ∃ r : R, algebraMap R F r ∉ Q.integers} = {P})

include hF hP

/-- With a single place at infinity, the kernel of the class-group surjection is the group of
integer multiples of the class of that place. -/
theorem ker_classGroupHom_of_eq_singleton :
    (classGroupHom R hF).ker =
      AddSubgroup.closure {(Place.orderSystem hF).divisorClass (WeilDivisor.ofPoint P)} := by
  rw [ker_classGroupHom R hF, hP]
  rw [Set.image_singleton, Set.image_singleton]

/-- The class of the single place at infinity dies in the ideal class group of the model. -/
theorem classGroupHom_divisorClass_ofPoint_of_eq_singleton :
    classGroupHom R hF ((Place.orderSystem hF).divisorClass (WeilDivisor.ofPoint P)) = 0 :=
  classGroupHom_divisorClass_ofPoint_of_exists_notMem_integers hF
    (show P ∈ {Q : Place k F | ∃ r : R, algebraMap R F r ∉ Q.integers} by
      rw [hP]; exact Set.mem_singleton P)

variable (hdeg : P.degree = 1)

include hdeg

/-- With a single **rational** place at infinity, the class-group map is injective on degree-zero
classes: such a class in the kernel is an integer multiple of the class of the place at infinity,
and its degree reads off that integer. -/
theorem eq_zero_of_classGroupHom_eq_zero_of_degreeClass_eq_zero
    {c : (Place.orderSystem hF).ClassGroup} (hc : degreeClass hF c = 0)
    (h : classGroupHom R hF c = 0) : c = 0 := by
  obtain ⟨n, hn⟩ := AddSubgroup.mem_closure_singleton.mp
    (by rw [← ker_classGroupHom_of_eq_singleton R hF hP]; exact h)
  rw [← hn, map_zsmul, degreeClass_divisorClass, degree_ofPoint, hdeg, Nat.cast_one,
    smul_eq_mul, mul_one] at hc
  rw [← hn, hc, zero_zsmul]

/-- **The degree-zero class group of `F / k` is the ideal class group of a model whose only place
at infinity is rational** — the form Mathlib's elliptic curves need, `Cl⁰(F) ≅ ClassGroup R`. -/
noncomputable def degreeZeroClassGroupEquiv :
    (degreeClass hF).ker ≃+ Additive (ClassGroup R) :=
  AddEquiv.ofBijective ((classGroupHom R hF).comp (degreeClass hF).ker.subtype)
    ⟨by
        rw [injective_iff_map_eq_zero]
        rintro ⟨c, hc⟩ h
        exact Subtype.ext (eq_zero_of_classGroupHom_eq_zero_of_degreeClass_eq_zero R hF hP hdeg
          (AddMonoidHom.mem_ker.mp hc) (by simpa using h)),
      classGroupHom_comp_subtype_surjective R hF ((Set.ext_iff.mp hP P).mpr rfl) hdeg⟩

@[simp]
theorem degreeZeroClassGroupEquiv_apply (c : (degreeClass hF).ker) :
    degreeZeroClassGroupEquiv R hF hP hdeg c = classGroupHom R hF c := (rfl)

end UniqueInfinitePlace

end Divisor

end EpsilonEridani
