/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.Algebra.Subalgebra.Lattice
public import Mathlib.LinearAlgebra.Span.Defs
public import EpsilonEridani.Algebra.Coalgebra.Comodule.MatrixCoefficient.Basic

/-!
# Subobjects generated by matrix coefficients

This file packages the linear span and algebra generated by the matrix coefficients of a
right comodule, together with their basic functoriality under comodule morphisms. These are
bookkeeping objects for the faithful-representation criterion in the reductive-groups roadmap.
For a finite projective comodule over a commutative Hopf algebra, the closed-immersion criterion
uses the original coefficients together with their antipode images, equivalently the coefficients
of the comodule together with its dual; see
`EpsilonEridani.Algebra.Coalgebra.Comodule.MatrixCoefficient.Dual`.

## Main definitions

* `EpsilonEridani.Comodule.matrixCoefficientSet`: the set of all matrix coefficients of a comodule.
* `EpsilonEridani.Comodule.matrixCoefficientSubmodule`: the `R`-submodule spanned by those
  coefficients.
* `EpsilonEridani.Comodule.range_matrixCoefficientTensor`: the matrix-coefficient submodule is the
  range of the tensor-linearized matrix-coefficient map.
* `EpsilonEridani.Comodule.matrixCoefficientSubalgebra`: the `R`-subalgebra generated by those
  coefficients when the coalgebra is also an `R`-algebra.
* `EpsilonEridani.Comodule.matrixCoefficientSet_subset_of_surjective`: a surjective comodule
  morphism makes target coefficients source coefficients.
* `EpsilonEridani.Comodule.matrixCoefficientSubmodule_eq_of_inverse_hom` and
  `EpsilonEridani.Comodule.matrixCoefficientSubalgebra_eq_of_inverse_hom`: coefficient objects are
  invariant under inverse comodule morphisms.

## References

This is standard coalgebra/comodule terminology; see Sweedler, *Hopf Algebras*, Chapter 2.
It supplies a prerequisite for `ReductiveGroups/README.md` in EpsilonEridaniRoadmap, Layer 1,
"Faithfulness done right". The necessary antipode closure of the original coefficients is
developed in `EpsilonEridani.Algebra.Coalgebra.Comodule.MatrixCoefficient.Dual`.
-/

public section

open scoped TensorProduct

namespace EpsilonEridani

namespace Comodule

universe u v w x

variable {R : Type u} {C : Type v} {M : Type w} {N : Type x}

section Submodule

variable [CommSemiring R]
variable [AddCommMonoid C] [Module R C] [Coalgebra R C]
variable [AddCommMonoid M] [Module R M] [Comodule R C M]

/-- The set of all matrix coefficients of a right comodule. -/
@[expose] def matrixCoefficientSet : Set C :=
  Set.range (Function.uncurry (matrixCoefficient (R := R) (C := C) (M := M)))

/-- The matrix coefficient set is the range of the uncurried matrix coefficient map. -/
theorem matrixCoefficientSet_def :
    matrixCoefficientSet (R := R) (C := C) (M := M) =
      Set.range (Function.uncurry (matrixCoefficient (R := R) (C := C) (M := M))) :=
  rfl

/-- A matrix coefficient belongs to the set of all matrix coefficients. -/
@[simp]
theorem matrixCoefficient_mem_set (φ : M →ₗ[R] R) (m : M) :
    matrixCoefficient (R := R) (C := C) φ m ∈
      matrixCoefficientSet (R := R) (C := C) (M := M) :=
  ⟨(φ, m), rfl⟩

/-- Membership in the set of matrix coefficients is the existence of a functional and a
vector giving the element. -/
theorem mem_matrixCoefficientSet_iff (c : C) :
    c ∈ matrixCoefficientSet (R := R) (C := C) (M := M) ↔
      ∃ (φ : M →ₗ[R] R) (m : M), matrixCoefficient (R := R) (C := C) φ m = c := by
  constructor
  · rintro ⟨⟨φ, m⟩, rfl⟩
    exact ⟨φ, m, rfl⟩
  · rintro ⟨φ, m, rfl⟩
    exact matrixCoefficient_mem_set (R := R) (C := C) φ m

/-- The `R`-submodule spanned by all matrix coefficients of a right comodule. -/
@[expose] def matrixCoefficientSubmodule : Submodule R C :=
  Submodule.span R (matrixCoefficientSet (R := R) (C := C) (M := M))

/-- The matrix coefficient submodule is the span of the matrix coefficient set. -/
theorem matrixCoefficientSubmodule_def :
    matrixCoefficientSubmodule (R := R) (C := C) (M := M) =
      Submodule.span R (matrixCoefficientSet (R := R) (C := C) (M := M)) :=
  rfl

/-- A matrix coefficient belongs to the submodule spanned by all matrix coefficients. -/
@[simp]
theorem matrixCoefficient_mem_submodule (φ : M →ₗ[R] R) (m : M) :
    matrixCoefficient (R := R) (C := C) φ m ∈
      matrixCoefficientSubmodule (R := R) (C := C) (M := M) :=
  Submodule.subset_span (matrixCoefficient_mem_set (R := R) (C := C) φ m)

/-- The coefficient submodule is the smallest submodule containing all matrix coefficients. -/
theorem matrixCoefficientSubmodule_le {P : Submodule R C}
    (hP : ∀ (φ : M →ₗ[R] R) (m : M), matrixCoefficient (R := R) (C := C) φ m ∈ P) :
    matrixCoefficientSubmodule (R := R) (C := C) (M := M) ≤ P := by
  rw [matrixCoefficientSubmodule, Submodule.span_le]
  intro c hc
  rcases (mem_matrixCoefficientSet_iff (R := R) (C := C) (M := M) c).mp hc with ⟨φ, m, rfl⟩
  exact hP φ m

/-- The coefficient submodule is contained in a submodule iff that submodule contains each
matrix coefficient. -/
theorem matrixCoefficientSubmodule_le_iff {P : Submodule R C} :
    matrixCoefficientSubmodule (R := R) (C := C) (M := M) ≤ P ↔
      ∀ (φ : M →ₗ[R] R) (m : M), matrixCoefficient (R := R) (C := C) φ m ∈ P :=
  ⟨fun hP φ m => hP (matrixCoefficient_mem_submodule (R := R) (C := C) φ m),
    matrixCoefficientSubmodule_le (R := R) (C := C) (M := M)⟩

/-- The range of the tensor-linearized matrix-coefficient map is exactly the submodule
spanned by all matrix coefficients. -/
theorem range_matrixCoefficientTensor :
    LinearMap.range
        (matrixCoefficientTensor (R := R) (C := C) (M := M)) =
      matrixCoefficientSubmodule (R := R) (C := C) (M := M) := by
  rw [LinearMap.range_eq_map, ← TensorProduct.span_tmul_eq_top, Submodule.map_span,
    matrixCoefficientSubmodule, matrixCoefficientSet]
  congr 1
  ext c
  simp

end Submodule

section SubmoduleFunctorial

variable [CommSemiring R]
variable [AddCommMonoid C] [Module R C] [Coalgebra R C]
variable [AddCommMonoid M] [Module R M] [Comodule R C M]
variable [AddCommMonoid N] [Module R N] [Comodule R C N]

/-- The matrix coefficient of the image of a vector under a comodule morphism is a matrix
coefficient of the source comodule. -/
theorem matrixCoefficient_mem_set_of_map (f : Hom R C M N) (φ : N →ₗ[R] R) (m : M) :
    matrixCoefficient (R := R) (C := C) φ (f m) ∈
      matrixCoefficientSet (R := R) (C := C) (M := M) := by
  rw [matrixCoefficient_map]
  exact matrixCoefficient_mem_set (R := R) (C := C) (φ.comp f.toLinearMap) m

/-- If `f : M → N` is a surjective comodule morphism, every matrix coefficient of `N` is a
matrix coefficient of `M`. -/
theorem matrixCoefficientSet_subset_of_surjective (f : Hom R C M N) (hf : Function.Surjective f) :
    matrixCoefficientSet (R := R) (C := C) (M := N) ⊆
      matrixCoefficientSet (R := R) (C := C) (M := M) := by
  intro c hc
  rcases (mem_matrixCoefficientSet_iff (R := R) (C := C) (M := N) c).mp hc with
    ⟨φ, n, rfl⟩
  rcases hf n with ⟨m, rfl⟩
  exact matrixCoefficient_mem_set_of_map (R := R) (C := C) f φ m

/-- A surjective comodule morphism makes the coefficient submodule of the target contained in
the coefficient submodule of the source. -/
theorem matrixCoefficientSubmodule_le_of_surjective (f : Hom R C M N) (hf : Function.Surjective f) :
    matrixCoefficientSubmodule (R := R) (C := C) (M := N) ≤
      matrixCoefficientSubmodule (R := R) (C := C) (M := M) := by
  rw [matrixCoefficientSubmodule, Submodule.span_le]
  intro c hc
  exact Submodule.subset_span (matrixCoefficientSet_subset_of_surjective (R := R) (C := C) f hf hc)

/-- Inverse comodule morphisms identify the coefficient sets. -/
theorem matrixCoefficientSet_eq_of_inverse_hom (f : Hom R C M N) (g : Hom R C N M)
    (hfg : ∀ n, f (g n) = n) (hgf : ∀ m, g (f m) = m) :
    matrixCoefficientSet (R := R) (C := C) (M := M) =
      matrixCoefficientSet (R := R) (C := C) (M := N) := by
  apply Set.Subset.antisymm
  · exact matrixCoefficientSet_subset_of_surjective (R := R) (C := C) g
      (fun m => ⟨f m, hgf m⟩)
  · exact matrixCoefficientSet_subset_of_surjective (R := R) (C := C) f
      (fun n => ⟨g n, hfg n⟩)

/-- Inverse comodule morphisms identify the coefficient submodules. -/
theorem matrixCoefficientSubmodule_eq_of_inverse_hom (f : Hom R C M N) (g : Hom R C N M)
    (hfg : ∀ n, f (g n) = n) (hgf : ∀ m, g (f m) = m) :
    matrixCoefficientSubmodule (R := R) (C := C) (M := M) =
      matrixCoefficientSubmodule (R := R) (C := C) (M := N) := by
  rw [matrixCoefficientSubmodule, matrixCoefficientSubmodule,
    matrixCoefficientSet_eq_of_inverse_hom f g hfg hgf]

end SubmoduleFunctorial

section Algebra

variable [CommSemiring R]
variable [Semiring C] [Algebra R C]
variable [Coalgebra R C]
variable [AddCommMonoid M] [Module R M] [Comodule R C M]

/-- The `R`-subalgebra generated by all matrix coefficients of a right comodule.

For a finite projective comodule over a commutative Hopf algebra, a closed-immersion criterion
uses this subalgebra together with its antipode image, equivalently the coefficient subalgebra
of the product with the dual comodule. -/
@[expose] def matrixCoefficientSubalgebra : Subalgebra R C :=
  Algebra.adjoin R (matrixCoefficientSet (R := R) (C := C) (M := M))

/-- The matrix coefficient subalgebra is the algebra generated by the matrix coefficient set. -/
theorem matrixCoefficientSubalgebra_def :
    matrixCoefficientSubalgebra (R := R) (C := C) (M := M) =
      Algebra.adjoin R (matrixCoefficientSet (R := R) (C := C) (M := M)) :=
  rfl

/-- A matrix coefficient belongs to the algebra generated by all matrix coefficients. -/
@[simp]
theorem matrixCoefficient_mem_subalgebra (φ : M →ₗ[R] R) (m : M) :
    matrixCoefficient (R := R) (C := C) φ m ∈
      matrixCoefficientSubalgebra (R := R) (C := C) (M := M) :=
  Algebra.subset_adjoin (matrixCoefficient_mem_set (R := R) (C := C) φ m)

/-- The coefficient algebra is the smallest subalgebra containing all matrix coefficients. -/
theorem matrixCoefficientSubalgebra_le {S : Subalgebra R C}
    (hS : ∀ (φ : M →ₗ[R] R) (m : M), matrixCoefficient (R := R) (C := C) φ m ∈ S) :
    matrixCoefficientSubalgebra (R := R) (C := C) (M := M) ≤ S := by
  rw [matrixCoefficientSubalgebra, Algebra.adjoin_le_iff]
  intro c hc
  rcases (mem_matrixCoefficientSet_iff (R := R) (C := C) (M := M) c).mp hc with ⟨φ, m, rfl⟩
  exact hS φ m

/-- The coefficient algebra is contained in a subalgebra iff that subalgebra contains each
matrix coefficient. -/
theorem matrixCoefficientSubalgebra_le_iff {S : Subalgebra R C} :
    matrixCoefficientSubalgebra (R := R) (C := C) (M := M) ≤ S ↔
      ∀ (φ : M →ₗ[R] R) (m : M), matrixCoefficient (R := R) (C := C) φ m ∈ S :=
  ⟨fun hS φ m => hS (matrixCoefficient_mem_subalgebra (R := R) (C := C) φ m),
    matrixCoefficientSubalgebra_le (R := R) (C := C) (M := M)⟩

/-- If the matrix coefficients linearly span the coalgebra, then they generate the ambient
algebra. -/
theorem matrixCoefficientSubalgebra_eq_top_of_submodule_eq_top
    (h : matrixCoefficientSubmodule (R := R) (C := C) (M := M) = ⊤) :
    matrixCoefficientSubalgebra (R := R) (C := C) (M := M) = ⊤ := by
  rw [matrixCoefficientSubalgebra, ← Algebra.toSubmodule_eq_top]
  exact top_le_iff.mp <| by
    rw [← h, matrixCoefficientSubmodule]
    exact Algebra.span_le_adjoin R (matrixCoefficientSet (R := R) (C := C) (M := M))

end Algebra

section AlgebraFunctorial

variable [CommSemiring R]
variable [Semiring C] [Algebra R C] [Coalgebra R C]
variable [AddCommMonoid M] [Module R M] [Comodule R C M]
variable [AddCommMonoid N] [Module R N] [Comodule R C N]

/-- A surjective comodule morphism makes the coefficient algebra of the target contained in
the coefficient algebra of the source. -/
theorem matrixCoefficientSubalgebra_le_of_surjective (f : Hom R C M N)
    (hf : Function.Surjective f) :
    matrixCoefficientSubalgebra (R := R) (C := C) (M := N) ≤
      matrixCoefficientSubalgebra (R := R) (C := C) (M := M) := by
  rw [matrixCoefficientSubalgebra, Algebra.adjoin_le_iff]
  intro c hc
  exact Algebra.subset_adjoin (matrixCoefficientSet_subset_of_surjective (R := R) (C := C) f hf hc)

/-- Inverse comodule morphisms identify the coefficient algebras. -/
theorem matrixCoefficientSubalgebra_eq_of_inverse_hom (f : Hom R C M N) (g : Hom R C N M)
    (hfg : ∀ n, f (g n) = n) (hgf : ∀ m, g (f m) = m) :
    matrixCoefficientSubalgebra (R := R) (C := C) (M := M) =
      matrixCoefficientSubalgebra (R := R) (C := C) (M := N) := by
  rw [matrixCoefficientSubalgebra, matrixCoefficientSubalgebra,
    matrixCoefficientSet_eq_of_inverse_hom f g hfg hgf]

end AlgebraFunctorial

end Comodule

end EpsilonEridani
