import Lake
open Lake DSL

-- This project exists to type-check the theorems the site showcases against the real library,
-- and to extract highlighted snippets for Verso. It therefore compiles the EpsilonEridani library
-- itself, which forces an invariant: it must build with EXACTLY the Lean and the Mathlib the
-- library is written for.
--
-- Neither is pinned here, and neither is committed. `lean-toolchain` and `lake-manifest.json`
-- are both generated by `scripts/sync_web_pins.py` from the root's, and both are `.gitignore`d.
-- The Pages workflow generates them before building; run that script once before building here
-- by hand, or Lake will not find a manifest at all.
--
-- The toolchain is WRITTEN rather than inherited, which is not the obvious choice. elan does
-- resolve a toolchain from the nearest ancestor directory, so deleting this file looks like it
-- would make the project pick up the root's. The nearest ancestor is `web/`, whose
-- `lean-toolchain` names the Verso site's Lean -- currently v4.32.0, against the library's
-- v4.34.0-rc2. Deleting the file therefore pins this project to exactly the stale toolchain that
-- broke the site, silently and with no file to notice. Measured, not assumed.
--
-- The pins used to be committed copies kept in step by the daily bump. That worked, but it put
-- two files outside `EpsilonEridani/` into every bump, and the merge policy refuses to auto-merge a
-- pull request touching a lakefile or an unlisted path, so each bump would have stopped for a
-- human. Deriving them instead keeps a bump touching only the root pins.
--
-- Why this matters at all: when these come apart, this project compiles the root library against
-- a Mathlib and a Lean that library was never written for, and the build fails on whatever file
-- happens to use something newer -- with the root project's own CI perfectly green, because
-- nothing outside pages.yml builds this project. That is exactly what happened in September
-- 2026. Conversely, once they agree, "this project builds the library" is the same question as
-- "the root project builds the library", which is a required check on every pull request.

-- Nominated as `master`, exactly as the root `lakefile.toml` does; the generated manifest
-- carries the reproducible commit, copied from the root manifest.
require mathlib from git
  "https://github.com/leanprover-community/mathlib4" @ "master"

-- Must resolve to the same commit as the Verso site, which is where the generator reads it from.
-- SubVerso deliberately supports being built on a different Lean toolchain from the Verso that
-- reads its output -- that is why this project can sit on the root toolchain while `web/` stays
-- on Verso's. What it does not promise is compatibility between its own VERSIONS: its data
-- format is an implementation detail, so both sides must be the same commit.
require subverso from git
  "https://github.com/leanprover/subverso" @ "verso-v4.32.0"

-- The real Tau Ceti library, from the repository root, so the showcased theorems are
-- type-checked against exactly the library that proves them.
require «EpsilonEridani» from "../.."

package «examples» where

@[default_target]
lean_lib «Examples» where
