/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.GroupTheory.Subgroup.Centralizer

/-!
# Normality tested on generators

Two criteria for a subgroup to be normal, each read off from a generating set.

A subgroup is normal as soon as its normalizer is everything, and the normalizer contains both the
subgroup itself and anything centralising it. So a subgroup `C` that is centralised elementwise by
a subgroup `P` with `C ⊔ P = ⊤` is normal. Mathlib has each ingredient
(`Subgroup.normalizer_eq_top_iff`, `Subgroup.le_normalizer`,
`Subgroup.centralizer_le_normalizer`) but not this combination.

The subgroup generated by a set that is stable under conjugation is normal: every element of the
group normalizes the subgroup as soon as it conjugates the generators into it
(`Subgroup.le_normalizer_closure_iff`).

## Main results

* `EpsilonEridani.normal_of_commute_of_sup_eq_top`: a subgroup centralised elementwise by a subgroup that
  joins with it to the whole group is normal.
* `Subgroup.closure_normal_of_forall_conj_mem`: the subgroup generated by a conjugation-stable set
  is normal.
-/

public section

namespace EpsilonEridani

open Subgroup

variable {G : Type*} [Group G]

/-- A subgroup centralised elementwise by a subgroup that joins with it to the whole group is
normal.

The commutation hypothesis is elementwise rather than `P ≤ centralizer C` because that is the form
a direct-product decomposition supplies; `C ⊔ P = ⊤` is weaker than `C` and `P` being complements,
which is what such a decomposition actually gives. -/
theorem normal_of_commute_of_sup_eq_top {C P : Subgroup G}
    (hcomm : ∀ c ∈ C, ∀ x ∈ P, Commute c x) (hsup : C ⊔ P = ⊤) : C.Normal := by
  -- `C` is normalised by itself and centralised by `P`, and the two generate `G`.
  rw [← normalizer_eq_top_iff, eq_top_iff, ← hsup]
  exact sup_le le_normalizer fun x hx =>
    centralizer_le_normalizer _ (mem_centralizer_iff.mpr fun c hc => hcomm c hc x hx)

/-- The subgroup generated by a set that is stable under conjugation is normal. -/
theorem _root_.Subgroup.closure_normal_of_forall_conj_mem {S : Set G}
    (h : ∀ g : G, ∀ s ∈ S, g * s * g⁻¹ ∈ S) : (closure S).Normal :=
  normalizer_eq_top_iff.mp <| top_le_iff.mp <|
    le_normalizer_closure_iff.mpr fun g _ s hs ↦ subset_closure (h g s hs)

end EpsilonEridani
