/-
Copyright (c) 2024 Chris Birkbeck. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Birkbeck
-/
module

public import Mathlib.LinearAlgebra.Matrix.SpecialLinearGroup
public import Mathlib.Algebra.Group.Commutator
public import EpsilonEridani.LinearAlgebra.Matrix.SpecialLinearGroup.Diagonal.Basic

/-!
# Special linear groups generated by transvections

Every element of `SL_n(ℤ)` is a product of elementary transvection matrices
`I + c·e_{ij}`.  The proof is the Euclidean algorithm on the first column: transvection
row operations shrink the column to a single unit entry, two or three further transvections
move that unit to the `(0, 0)` corner as `+1`, row operations clear the first row, and the
lower-right block is handled by induction on the dimension.

Mathlib's `Mathlib.LinearAlgebra.Transvection.Generation` proves the Dieudonné generation
theorem over division rings; `ℤ` is not covered there, and the argument here is the
integer-specific one.  Transvections are carried as `Matrix.TransvectionStruct` data, the
vocabulary of Mathlib's transvection theory; all of the Euclidean machinery is private.

Over a field, Mathlib's diagonal--transvection induction and the arbitrary-index form of its
`diag2_decompose` factorization give the parallel generation theorem.

The file also records the type-A relations for bare `Matrix.transvection` matrices and their
determinant-one counterparts over an arbitrary commutative ring.

## Main results

* `Matrix.SpecialLinearGroup.exists_list_transvec_prod`: every `σ ∈ SL_n(ℤ)` is the
  product of a list of transvections.
* `Matrix.SpecialLinearGroup.closure_range_toSpecialLinearGroup_eq_top`: `SL_n(ℤ)` is
  generated by its transvections.
* `Matrix.SpecialLinearGroup.closure_range_toSpecialLinearGroup_eq_top_of_field`: over a field,
  `SL_n` is generated by its transvections.
* `Matrix.SpecialLinearGroup.transvectionHom`, `transvection_injective`, and
  `map_transvection`: the one-parameter subgroup over a commutative ring, its injectivity, and
  its naturality under ring homomorphisms.
* `EpsilonEridani.commute_transvection` and `EpsilonEridani.transvection_mul_transvection_eq_mul_mul`: the
  type-A relations for bare transvection matrices.
* `Matrix.SpecialLinearGroup.commute_transvection` and
  `Matrix.SpecialLinearGroup.commutatorElement_transvection`: the type-A commutator relations for
  determinant-one transvections.

Ported from the AINTLIB `LeanModularForms` project
([`LeanModularForms/HeckeRIngs/GLn/SLnTransvection.lean`](https://github.com/CBirkbeck/AINTLIB),
Chris Birkbeck), toward the multiplicativity theory of the `GL_n` Hecke ring.
-/

public section

namespace Matrix.SpecialLinearGroup

open Matrix (TransvectionStruct)

private lemma transvection_mul_entry {m : ℕ} (i j : Fin m) (hij : i ≠ j) (c : ℤ)
    (σ : SpecialLinearGroup (Fin m) ℤ) (a b : Fin m) :
    (transvection hij c * σ).1 a b =
    if a = i then σ.1 i b + c * σ.1 j b else σ.1 a b := by
  -- definitional: the matrix underlying the `SL` transvection is `Matrix.transvection`
  have hval : (transvection hij c * σ).1 = _root_.Matrix.transvection i j c * σ.1 := rfl
  rw [hval]
  split_ifs with hai
  · subst hai; rw [_root_.Matrix.transvection_mul_apply_same]
  · rw [_root_.Matrix.transvection_mul_apply_of_ne (ha := hai)]

private lemma transvection_mul_right_entry {m : ℕ} (i j : Fin m) (hij : i ≠ j)
    (c : ℤ) (σ : SpecialLinearGroup (Fin m) ℤ) (a b : Fin m) :
    (σ * transvection hij c).1 a b =
    if b = j then σ.1 a j + c * σ.1 a i else σ.1 a b := by
  -- definitional: the matrix underlying the `SL` transvection is `Matrix.transvection`
  have hval : (σ * transvection hij c).1 = σ.1 * _root_.Matrix.transvection i j c := rfl
  rw [hval]
  split_ifs with hbj
  · subst hbj; rw [_root_.Matrix.mul_transvection_apply_same]
  · rw [_root_.Matrix.mul_transvection_apply_of_ne (hb := hbj)]

private lemma toSpecialLinearGroup_inv {m : ℕ} (t : TransvectionStruct (Fin m) ℤ) :
    t.toSpecialLinearGroup⁻¹ = t.inv.toSpecialLinearGroup :=
  inv_eq_of_mul_eq_one_left (Subtype.ext (by
    simpa using TransvectionStruct.inv_mul t))

/-- Inverting the product of a list of transvections gives the product of the reversed list
of inverse transvections. -/
private lemma prod_map_inv {m : ℕ} (T : List (TransvectionStruct (Fin m) ℤ)) :
    ((T.map TransvectionStruct.toSpecialLinearGroup).prod)⁻¹ =
    (((T.map TransvectionStruct.inv).reverse).map
      TransvectionStruct.toSpecialLinearGroup).prod := by
  rw [List.prod_inv_reverse, List.map_reverse, List.map_map, List.map_map]
  exact congrArg List.prod (congrArg List.reverse
    (List.map_congr_left fun t _ ↦ toSpecialLinearGroup_inv t))

/-- The sum of the absolute values of the entries in the first column. -/
private def col0Sum {m : ℕ} (σ : SpecialLinearGroup (Fin (m + 1)) ℤ) : ℕ :=
  ∑ i : Fin (m + 1), (σ.1 i 0).natAbs

private lemma col0_ne_zero {m : ℕ} (σ : SpecialLinearGroup (Fin (m + 1)) ℤ) :
    ∃ i, σ.1 i 0 ≠ 0 := by
  by_contra! h
  exact absurd (Matrix.det_eq_zero_of_column_eq_zero 0 (fun i ↦ h i)) (by rw [σ.2]; norm_num)

/-- The number of nonzero entries in the first column. -/
private def nzCount {m : ℕ} (σ : SpecialLinearGroup (Fin (m + 1)) ℤ) : ℕ :=
  (Finset.univ.filter fun i : Fin (m + 1) ↦ σ.1 i 0 ≠ 0).card

private lemma exists_two_nz {m : ℕ} (σ : SpecialLinearGroup (Fin (m + 1)) ℤ)
    (h : 2 ≤ nzCount σ) :
    ∃ (i j : Fin (m + 1)), i ≠ j ∧ σ.1 i 0 ≠ 0 ∧ σ.1 j 0 ≠ 0 := by
  simp only [nzCount] at h
  have h1 : 1 < (Finset.univ.filter fun i : Fin (m + 1) ↦ σ.1 i 0 ≠ 0).card := by omega
  obtain ⟨i, hi, j, hj, hij⟩ := Finset.one_lt_card.mp h1
  simp only [Finset.mem_filter, Finset.mem_univ, true_and] at hi hj
  exact ⟨i, j, hij, hi, hj⟩

private lemma col0_euclidean_step_aux {m : ℕ} (σ : SpecialLinearGroup (Fin (m + 1)) ℤ)
    (i j : Fin (m + 1)) (hij : i ≠ j) (hj : σ.1 j 0 ≠ 0)
    (hle : (σ.1 j 0).natAbs ≤ (σ.1 i 0).natAbs) :
    col0Sum (transvection hij (-(σ.1 i 0 / σ.1 j 0)) * σ) < col0Sum σ := by
  set q := σ.1 i 0 / σ.1 j 0
  have h_new : (transvection hij (-q) * σ).1 i 0 = σ.1 i 0 % σ.1 j 0 := by
    rw [transvection_mul_entry]; simp only [ite_true]
    linarith [(Int.mul_ediv_add_emod (σ.1 i 0) (σ.1 j 0)).symm]
  have h_oth : ∀ a, a ≠ i → (transvection hij (-q) * σ).1 a 0 = σ.1 a 0 :=
    fun a ha ↦ by rw [transvection_mul_entry]; simp [ha]
  have h_rem : (σ.1 i 0 % σ.1 j 0).natAbs < (σ.1 j 0).natAbs := by
    have h1 := Int.emod_nonneg (σ.1 i 0) hj
    have h2 : σ.1 i 0 % σ.1 j 0 < |σ.1 j 0| := by
      rw [← Int.emod_abs]; exact Int.emod_lt_of_pos _ (abs_pos.mpr hj)
    simpa only [Int.natAbs_abs] using Int.natAbs_lt_natAbs_of_nonneg_of_lt h1 h2
  simp only [col0Sum]
  rw [← Finset.add_sum_erase _ _ (Finset.mem_univ i),
      ← Finset.add_sum_erase _ _ (Finset.mem_univ i)]
  have h_rest : ∑ k ∈ Finset.univ.erase i,
      ((transvection hij (-q) * σ).1 k 0).natAbs =
      ∑ k ∈ Finset.univ.erase i, (σ.1 k 0).natAbs :=
    Finset.sum_congr rfl fun k hk ↦ by rw [h_oth k (Finset.mem_erase.mp hk).1]
  rw [h_rest, h_new]; linarith [Nat.lt_of_lt_of_le h_rem hle]

private lemma col0_euclidean_step {m : ℕ} (σ : SpecialLinearGroup (Fin (m + 1)) ℤ)
    (h : 2 ≤ nzCount σ) :
    ∃ t : TransvectionStruct (Fin (m + 1)) ℤ,
      col0Sum (t.toSpecialLinearGroup * σ) < col0Sum σ := by
  obtain ⟨i₀, j₀, hij₀, hi₀, hj₀⟩ := exists_two_nz σ h
  by_cases hge : (σ.1 j₀ 0).natAbs ≤ (σ.1 i₀ 0).natAbs
  · exact ⟨⟨i₀, j₀, hij₀, -(σ.1 i₀ 0 / σ.1 j₀ 0)⟩, by
      rw [TransvectionStruct.toSpecialLinearGroup_mk]
      exact col0_euclidean_step_aux σ i₀ j₀ hij₀ hj₀ hge⟩
  · push Not at hge
    exact ⟨⟨j₀, i₀, hij₀.symm, -(σ.1 j₀ 0 / σ.1 i₀ 0)⟩, by
      rw [TransvectionStruct.toSpecialLinearGroup_mk]
      exact col0_euclidean_step_aux σ j₀ i₀ hij₀.symm hi₀ hge.le⟩

private lemma col0_reduce {m : ℕ} (σ : SpecialLinearGroup (Fin (m + 1)) ℤ) :
    ∃ T : List (TransvectionStruct (Fin (m + 1)) ℤ),
      nzCount ((T.map TransvectionStruct.toSpecialLinearGroup).prod * σ) ≤ 1 := by
  suffices key : ∀ (k : ℕ) (τ : SpecialLinearGroup (Fin (m + 1)) ℤ),
      col0Sum τ ≤ k → ∃ T : List (TransvectionStruct (Fin (m + 1)) ℤ),
        nzCount ((T.map TransvectionStruct.toSpecialLinearGroup).prod * τ) ≤ 1 from
    key (col0Sum σ) σ le_rfl
  intro k
  induction k using Nat.strongRecOn with
  | _ k ihk =>
  intro τ hk
  by_cases hn : nzCount τ ≤ 1
  · exact ⟨[], by simpa using hn⟩
  · push Not at hn
    obtain ⟨t, hlt⟩ := col0_euclidean_step τ hn
    have hlt' : col0Sum (t.toSpecialLinearGroup * τ) < k := Nat.lt_of_lt_of_le hlt hk
    obtain ⟨T, hT⟩ := ihk (col0Sum (t.toSpecialLinearGroup * τ)) hlt' _ le_rfl
    exact ⟨T ++ [t], by
      rw [List.map_append, List.prod_append]
      simpa [mul_assoc] using hT⟩

/-- The equivalence `Fin m ⊕ Unit ≃ Fin (m + 1)` sending `inl i` to `i.succ` and `inr` to
`0`, along which transvection data extends to the larger index type. -/
private def finSuccSum (m : ℕ) : Fin m ⊕ Unit ≃ Fin (m + 1) :=
  ((finSuccEquiv m).trans (Equiv.optionEquivSumPUnit (Fin m))).symm

private lemma finSuccSum_inl {m : ℕ} (i : Fin m) : finSuccSum m (Sum.inl i) = i.succ := by
  simp [finSuccSum]

/-- Transvection data extended from `Fin m` to `Fin (m + 1)`, acting on the successor
indices: Mathlib's `sumInl` into `Fin m ⊕ Unit`, reindexed along `finSuccSum`. -/
private def blockLiftT {m : ℕ} (t : TransvectionStruct (Fin m) ℤ) :
    TransvectionStruct (Fin (m + 1)) ℤ :=
  (t.sumInl (p := Unit)).reindexEquiv (finSuccSum m)

private lemma succ_ne_succ {m : ℕ} {i j : Fin m} (hij : i ≠ j) : i.succ ≠ j.succ :=
  fun h ↦ hij (Fin.succ_injective m h)

/-- The special-linear image of the lifted transvection data is the transvection at the
successor indices. -/
private lemma blockLiftT_toSpecialLinearGroup {m : ℕ} (t : TransvectionStruct (Fin m) ℤ) :
    (blockLiftT t).toSpecialLinearGroup = transvection (succ_ne_succ t.hij) t.c := by
  apply Subtype.ext
  obtain ⟨i, j, hij, c⟩ := t
  -- definitional: both values are `Matrix.transvection` at the images of `i` and `j`
  change _root_.Matrix.transvection (finSuccSum m (Sum.inl i)) (finSuccSum m (Sum.inl j)) c =
    _root_.Matrix.transvection i.succ j.succ c
  rw [finSuccSum_inl, finSuccSum_inl]

/-- A transvection on `Fin m` lifted to the successor indices of `Fin (m + 1)`. -/
private def blockLift {m : ℕ} (i j : Fin m) (hij : i ≠ j) (c : ℤ) :
    SpecialLinearGroup (Fin (m + 1)) ℤ :=
  transvection (succ_ne_succ hij) c

private lemma blockLift_entry {m : ℕ} (i j : Fin m) (hij : i ≠ j) (c : ℤ)
    (τ : SpecialLinearGroup (Fin (m + 1)) ℤ) (a b : Fin (m + 1)) :
    (blockLift i j hij c * τ).1 a b =
    if a = i.succ then τ.1 i.succ b + c * τ.1 j.succ b else τ.1 a b := by
  unfold blockLift; exact transvection_mul_entry i.succ j.succ _ c τ a b

private lemma blockLift_row0 {m : ℕ} (i j : Fin m) (hij : i ≠ j) (c : ℤ)
    (τ : SpecialLinearGroup (Fin (m + 1)) ℤ) (b : Fin (m + 1)) :
    (blockLift i j hij c * τ).1 0 b = τ.1 0 b := by
  rw [blockLift_entry]; split_ifs with h
  · exact absurd h.symm (Fin.succ_ne_zero i)
  · rfl

private lemma blockLift_col0 {m : ℕ} (i j : Fin m) (hij : i ≠ j) (c : ℤ)
    (τ : SpecialLinearGroup (Fin (m + 1)) ℤ)
    (hcol : ∀ k : Fin (m + 1), k ≠ 0 → τ.1 k 0 = 0) (a : Fin (m + 1)) :
    (blockLift i j hij c * τ).1 a 0 = τ.1 a 0 := by
  rw [blockLift_entry]; split_ifs with ha
  · subst ha; rw [hcol j.succ (Fin.succ_ne_zero j), mul_zero, add_zero]
  · rfl

private lemma det_lowerRight {m : ℕ} (τ : SpecialLinearGroup (Fin (m + 1)) ℤ)
    (h00 : τ.1 0 0 = 1) (h0j : ∀ j : Fin (m + 1), j ≠ 0 → τ.1 0 j = 0) :
    (Matrix.of fun (i : Fin m) (j : Fin m) ↦ τ.1 i.succ j.succ).det = 1 := by
  -- definitional: the `Matrix.of` matrix is the submatrix along `Fin.succ`
  change (τ.1.submatrix Fin.succ Fin.succ).det = 1
  have hdet : τ.1.det = 1 := τ.2
  rw [Matrix.det_succ_row_zero, Finset.sum_eq_single (0 : Fin (m + 1))
    (fun j _ hj ↦ by simp [h0j j hj])
    (fun h ↦ absurd (Finset.mem_univ _) h)] at hdet
  simpa [Fin.succAbove_zero, h00] using hdet

/-- The lower-right special-linear block after the first row and column have been cleared. -/
private def extractBlock {m : ℕ} (τ : SpecialLinearGroup (Fin (m + 1)) ℤ)
    (h00 : τ.1 0 0 = 1) (h0j : ∀ j : Fin (m + 1), j ≠ 0 → τ.1 0 j = 0)
    (_hi0 : ∀ i : Fin (m + 1), i ≠ 0 → τ.1 i 0 = 0) :
    SpecialLinearGroup (Fin m) ℤ :=
  ⟨Matrix.of fun i j ↦ τ.1 i.succ j.succ, det_lowerRight τ h00 h0j⟩

private lemma extractBlock_blockLift {m : ℕ} (i j : Fin m) (hij : i ≠ j) (c : ℤ)
    (τ : SpecialLinearGroup (Fin (m + 1)) ℤ)
    (h00 : τ.1 0 0 = 1) (h0j : ∀ j, j ≠ 0 → τ.1 0 j = 0)
    (hi0 : ∀ i, i ≠ 0 → τ.1 i 0 = 0) :
    extractBlock (blockLift i j hij c * τ)
      (by rw [blockLift_row0]; exact h00)
      (by intro k hk; rw [blockLift_row0]; exact h0j k hk)
      (by intro k hk; rw [blockLift_col0 _ _ _ _ _ hi0]; exact hi0 k hk) =
    transvection hij c * extractBlock τ h00 h0j hi0 := by
  have : NeZero m := ⟨by rintro rfl; exact i.elim0⟩
  apply Subtype.ext; ext a b
  -- definitional: both sides are entries of the `Fin.succ` submatrix
  change (blockLift i j hij c * τ).1 a.succ b.succ =
    (transvection hij c * extractBlock τ h00 h0j hi0).1 a b
  rw [blockLift_entry i j hij c τ a.succ b.succ,
      transvection_mul_entry i j hij c (extractBlock τ h00 h0j hi0) a b]
  simp only [Fin.succ_inj, extractBlock, Matrix.of_apply]

/-- The sum of the absolute values of the off-diagonal entries in the first row. -/
private def row0Sum {m : ℕ} (σ : SpecialLinearGroup (Fin (m + 1)) ℤ) : ℕ :=
  ∑ j : Fin (m + 1), if (j : ℕ) = 0 then 0 else (σ.1 0 j).natAbs

private lemma row0Sum_eq_zero_imp_cleared {m : ℕ} (σ : SpecialLinearGroup (Fin (m + 1)) ℤ)
    (hzero : row0Sum σ = 0) (j : Fin (m + 1)) (hj : j ≠ 0) : σ.1 0 j = 0 := by
  have h_le : (if (j : ℕ) = 0 then 0 else (σ.1 0 j).natAbs) ≤ row0Sum σ :=
    Finset.single_le_sum
      (f := fun (j : Fin (m + 1)) ↦ if (j : ℕ) = 0 then 0 else (σ.1 0 j).natAbs)
      (fun _ _ ↦ Nat.zero_le _) (Finset.mem_univ j)
  simp only [hzero, Fin.val_eq_zero_iff.not.mpr hj, ↓reduceIte] at h_le
  exact Int.natAbs_eq_zero.mp (Nat.eq_zero_of_le_zero h_le)

private lemma row0_clear_step {m : ℕ} (σ : SpecialLinearGroup (Fin (m + 1)) ℤ)
    (hσ00 : σ.1 0 0 = 1) (hσi0 : ∀ i, i ≠ 0 → σ.1 i 0 = 0) (hzero : row0Sum σ ≠ 0) :
    ∃ t : TransvectionStruct (Fin (m + 1)) ℤ,
      (σ * t.toSpecialLinearGroup).1 0 0 = 1 ∧
      (∀ i, i ≠ 0 → (σ * t.toSpecialLinearGroup).1 i 0 = 0) ∧
      row0Sum (σ * t.toSpecialLinearGroup) < row0Sum σ := by
  have ⟨j₀, hj₀_nz⟩ : ∃ j : Fin (m + 1),
      (if (j : ℕ) = 0 then 0 else (σ.1 0 j).natAbs) ≠ 0 := by
    by_contra h; push Not at h
    exact hzero (Finset.sum_eq_zero (fun j _ ↦ h j))
  have hj₀ : j₀ ≠ 0 := fun h ↦ by subst h; simp at hj₀_nz
  have hj₀_val : (j₀ : ℕ) ≠ 0 := Fin.val_eq_zero_iff.not.mpr hj₀
  refine ⟨⟨(0 : Fin (m + 1)), j₀, hj₀.symm, -σ.1 0 j₀⟩, ?_⟩
  rw [TransvectionStruct.toSpecialLinearGroup_mk]
  set E := transvection hj₀.symm (-σ.1 0 j₀) with hE_def
  refine ⟨?_, ?_, ?_⟩
  · rw [hE_def, transvection_mul_right_entry]; simp [hj₀.symm, hσ00]
  · intro i hi; rw [hE_def, transvection_mul_right_entry]; simp [hj₀.symm, hσi0 i hi]
  · have hclear : (σ * E).1 0 j₀ = 0 := by
      rw [hE_def, transvection_mul_right_entry]; simp [hσ00]
    have hother : ∀ k, k ≠ j₀ → (σ * E).1 0 k = σ.1 0 k := fun k hk ↦ by
      rw [hE_def, transvection_mul_right_entry]; simp [hk]
    simp only [row0Sum]
    rw [← Finset.add_sum_erase _ _ (Finset.mem_univ j₀),
        ← Finset.add_sum_erase _ _ (Finset.mem_univ j₀)]
    have h_rest : ∑ k ∈ Finset.univ.erase j₀,
        (if (k : ℕ) = 0 then 0 else ((σ * E).1 0 k).natAbs) =
        ∑ k ∈ Finset.univ.erase j₀, (if (k : ℕ) = 0 then 0 else (σ.1 0 k).natAbs) :=
      Finset.sum_congr rfl fun k hk ↦ by
        by_cases h0 : (k : ℕ) = 0 <;> simp [h0, hother k (Finset.mem_erase.mp hk).1]
    rw [h_rest, hclear]
    simp only [Int.natAbs_zero, hj₀_val, ↓reduceIte, zero_add] at hj₀_nz ⊢
    omega

private lemma row0_clear {m : ℕ} (τ : SpecialLinearGroup (Fin (m + 1)) ℤ)
    (h00 : τ.1 0 0 = 1) (hi0 : ∀ i : Fin (m + 1), i ≠ 0 → τ.1 i 0 = 0) :
    ∃ T : List (TransvectionStruct (Fin (m + 1)) ℤ),
      (τ * (T.map TransvectionStruct.toSpecialLinearGroup).prod).1 0 0 = 1 ∧
      (∀ j : Fin (m + 1), j ≠ 0 →
        (τ * (T.map TransvectionStruct.toSpecialLinearGroup).prod).1 0 j = 0) ∧
      (∀ i : Fin (m + 1), i ≠ 0 →
        (τ * (T.map TransvectionStruct.toSpecialLinearGroup).prod).1 i 0 = 0) := by
  suffices key : ∀ (k : ℕ) (σ : SpecialLinearGroup (Fin (m + 1)) ℤ),
      σ.1 0 0 = 1 → (∀ i, i ≠ 0 → σ.1 i 0 = 0) → row0Sum σ ≤ k →
      ∃ T : List (TransvectionStruct (Fin (m + 1)) ℤ),
        (σ * (T.map TransvectionStruct.toSpecialLinearGroup).prod).1 0 0 = 1 ∧
        (∀ j, j ≠ 0 →
          (σ * (T.map TransvectionStruct.toSpecialLinearGroup).prod).1 0 j = 0) ∧
        (∀ i, i ≠ 0 →
          (σ * (T.map TransvectionStruct.toSpecialLinearGroup).prod).1 i 0 = 0) from
    key (row0Sum τ) τ h00 hi0 le_rfl
  intro k; induction k using Nat.strongRecOn with
  | _ k ihk =>
  intro σ hσ00 hσi0 hk
  by_cases hzero : row0Sum σ = 0
  · exact ⟨[], by simp [hσ00],
      fun j hj ↦ by simpa using row0Sum_eq_zero_imp_cleared σ hzero j hj,
      fun i hi ↦ by simp [hσi0 i hi]⟩
  · obtain ⟨t, hσ'00, hσ'i0, hlt⟩ := row0_clear_step σ hσ00 hσi0 hzero
    obtain ⟨T', hT'_00, hT'_0j, hT'_i0⟩ :=
      ihk (row0Sum (σ * t.toSpecialLinearGroup)) (by omega)
        (σ * t.toSpecialLinearGroup) hσ'00 hσ'i0 le_rfl
    refine ⟨t :: T', ?_, ?_, ?_⟩
    · simpa only [List.map_cons, List.prod_cons, ← mul_assoc] using hT'_00
    · intro j hj
      simpa only [List.map_cons, List.prod_cons, ← mul_assoc] using hT'_0j j hj
    · intro i hi
      simpa only [List.map_cons, List.prod_cons, ← mul_assoc] using hT'_i0 i hi

private lemma nzCount_le_one_unique_nonzero {m : ℕ}
    (τ : SpecialLinearGroup (Fin (m + 1)) ℤ)
    (i₀ : Fin (m + 1)) (hi₀ : τ.1 i₀ 0 ≠ 0) (h_nz : nzCount τ ≤ 1) :
    ∀ k, k ≠ i₀ → τ.1 k 0 = 0 := by
  intro k hk; by_contra hne
  have h2 : 2 ≤ nzCount τ := calc
    2 = ({i₀, k} : Finset _).card := (Finset.card_pair hk.symm).symm
    _ ≤ nzCount τ := Finset.card_le_card fun x hx ↦ by
      simp only [Finset.mem_insert, Finset.mem_singleton] at hx
      simp only [Finset.mem_filter, Finset.mem_univ, true_and]
      exact hx.elim (· ▸ hi₀) (· ▸ hne)
  omega

private lemma sole_nonzero_col0_is_unit {m : ℕ} (τ : SpecialLinearGroup (Fin (m + 1)) ℤ)
    (i₀ : Fin (m + 1)) (h_others : ∀ k, k ≠ i₀ → τ.1 k 0 = 0) :
    τ.1 i₀ 0 = 1 ∨ τ.1 i₀ 0 = -1 := by
  set M := τ.1
  have hdet : M.det = 1 := τ.2
  rw [← Int.isUnit_iff]; apply isUnit_of_dvd_one; rw [← hdet, Matrix.det_apply]
  apply Finset.dvd_sum; intro σ _
  -- definitional: the summand of `det_apply` is the signed product over the permutation
  change M i₀ 0 ∣ (↑(Equiv.Perm.sign σ) : ℤ) * ∏ i, M (σ i) i
  rw [Fin.prod_univ_succ]
  by_cases hσ : σ 0 = i₀
  · rw [hσ, ← mul_assoc]; exact dvd_mul_of_dvd_left (dvd_mul_left _ _) _
  · rw [h_others (σ 0) hσ, zero_mul, mul_zero]; exact dvd_zero _

private lemma block_form_transvec_lift {m : ℕ} (M : SpecialLinearGroup (Fin (m + 1)) ℤ)
    (H00 : M.1 0 0 = 1) (H0j : ∀ j, j ≠ 0 → M.1 0 j = 0)
    (Hi0 : ∀ i, i ≠ 0 → M.1 i 0 = 0)
    (T : List (TransvectionStruct (Fin m) ℤ))
    (hT_eq : extractBlock M H00 H0j Hi0 =
      (T.map TransvectionStruct.toSpecialLinearGroup).prod) :
    ∃ T' : List (TransvectionStruct (Fin (m + 1)) ℤ),
      M = (T'.map TransvectionStruct.toSpecialLinearGroup).prod := by
  induction T generalizing M with
  | nil =>
    refine ⟨[], ?_⟩
    simp only [List.map_nil, List.prod_nil] at hT_eq ⊢
    apply Subtype.ext; ext a b
    simp only [Matrix.SpecialLinearGroup.coe_one, Matrix.one_apply]
    by_cases ha : a = 0
    · subst ha; by_cases hb : b = 0
      · subst hb; exact H00
      · rw [H0j b hb, ite_eq_right (Ne.symm hb)]
    · by_cases hb : b = 0
      · subst hb; rw [Hi0 a ha, ite_eq_right ha]
      · obtain ⟨a', rfl⟩ := Fin.exists_succ_eq.mpr ha
        obtain ⟨b', rfl⟩ := Fin.exists_succ_eq.mpr hb
        have h := congr_fun (congr_fun (congr_arg Subtype.val hT_eq) a') b'
        simp only [extractBlock, Matrix.of_apply, Matrix.SpecialLinearGroup.coe_one,
          Matrix.one_apply] at h
        simpa using h
  | cons t T' ihT =>
    obtain ⟨i, j, hij, c⟩ := t
    simp only [List.map_cons, List.prod_cons,
      TransvectionStruct.toSpecialLinearGroup_mk] at hT_eq
    have H00' : (blockLift i j hij (-c) * M).1 0 0 = 1 := by
      rw [blockLift_row0]; exact H00
    have H0j' : ∀ k, k ≠ 0 → (blockLift i j hij (-c) * M).1 0 k = 0 := by
      intro k hk; rw [blockLift_row0]; exact H0j k hk
    have Hi0' : ∀ k, k ≠ 0 → (blockLift i j hij (-c) * M).1 k 0 = 0 := by
      intro k hk; rw [blockLift_col0 _ _ _ _ _ Hi0]; exact Hi0 k hk
    have hext' : extractBlock (blockLift i j hij (-c) * M) H00' H0j' Hi0' =
        (T'.map TransvectionStruct.toSpecialLinearGroup).prod :=
      (extractBlock_blockLift i j hij (-c) M H00 H0j Hi0).trans
        (by rw [hT_eq, ← mul_assoc, ← transvection_add, neg_add_cancel,
          transvection_coeff_zero, one_mul])
    obtain ⟨T'', hT''_eq⟩ := ihT (blockLift i j hij (-c) * M) H00' H0j' Hi0' hext'
    refine ⟨blockLiftT ⟨i, j, hij, c⟩ :: T'', ?_⟩
    simp only [List.map_cons, List.prod_cons]
    rw [blockLiftT_toSpecialLinearGroup, ← hT''_eq, ← mul_assoc]
    unfold blockLift
    rw [← transvection_add, add_neg_cancel, transvection_coeff_zero, one_mul]

/-- Column-clearing for a `-1` pivot at the `(0,0)` position in dimension `≥ 2`:
three transvections turn the first column into the first standard basis vector. -/
private lemma column_pivot_of_neg_one_at_zero {m' : ℕ}
    (τ : SpecialLinearGroup (Fin (m' + 2)) ℤ) (h_neg1 : τ.1 0 0 = -1)
    (h_others : ∀ k, k ≠ 0 → τ.1 k 0 = 0) :
    ∃ T : List (TransvectionStruct (Fin (m' + 2)) ℤ),
      ((T.map TransvectionStruct.toSpecialLinearGroup).prod * τ).1 0 0 = 1 ∧
      (∀ i, i ≠ 0 →
        ((T.map TransvectionStruct.toSpecialLinearGroup).prod * τ).1 i 0 = 0) := by
  have h10 : (1 : Fin (m' + 2)) ≠ 0 := by simp
  have h01 : (0 : Fin (m' + 2)) ≠ 1 := h10.symm
  set σ₁ := transvection h10 1 * τ with hσ₁_def
  have hσ₁_00 : σ₁.1 0 0 = -1 := by
    rw [hσ₁_def, transvection_mul_entry]; simp [h01, h_neg1]
  have hσ₁_10 : σ₁.1 1 0 = -1 := by
    rw [hσ₁_def, transvection_mul_entry]; simp [h_neg1, h_others 1 h10]
  have hσ₁_i0 : ∀ i, i ≠ 0 → i ≠ 1 → σ₁.1 i 0 = 0 := fun i hi0 hi1 ↦ by
    rw [hσ₁_def, transvection_mul_entry]; simp [hi1, h_others i hi0]
  set σ₂ := transvection h01 (-2) * σ₁ with hσ₂_def
  have hσ₂_00 : σ₂.1 0 0 = 1 := by
    rw [hσ₂_def, transvection_mul_entry]; simp [hσ₁_00, hσ₁_10]
  have hσ₂_10 : σ₂.1 1 0 = -1 := by
    rw [hσ₂_def, transvection_mul_entry]; simp [h10, hσ₁_10]
  have hσ₂_i0 : ∀ i, i ≠ 0 → i ≠ 1 → σ₂.1 i 0 = 0 := fun i hi0 hi1 ↦ by
    rw [hσ₂_def, transvection_mul_entry]; simp [hi0, hσ₁_i0 i hi0 hi1]
  have hσ₃_00 : (transvection h10 1 * σ₂).1 0 0 = 1 := by
    rw [transvection_mul_entry]; simp [h01, hσ₂_00]
  have hσ₃_i0 : ∀ i, i ≠ 0 → (transvection h10 1 * σ₂).1 i 0 = 0 := fun i hi ↦ by
    rw [transvection_mul_entry]
    rcases eq_or_ne i 1 with rfl | hi1
    · simp [hσ₂_00, hσ₂_10]
    · simp [hi1, hσ₂_i0 i hi hi1]
  refine ⟨[⟨1, 0, h10, 1⟩, ⟨0, 1, h01, -2⟩, ⟨1, 0, h10, 1⟩], ?_, ?_⟩ <;>
    simp only [List.map_cons, List.map_nil, List.prod_cons, List.prod_nil, mul_one,
      TransvectionStruct.toSpecialLinearGroup_mk, mul_assoc, ← hσ₁_def, ← hσ₂_def]
  · exact hσ₃_00
  · exact fun i hi ↦ hσ₃_i0 i hi

/-- Column-clearing for a unit pivot `v ∈ {1, -1}` at an off-diagonal position `i₀ ≠ 0`:
two transvections turn the first column into the first standard basis vector. -/
private lemma column_pivot_of_unit_off_diagonal {m : ℕ}
    (τ : SpecialLinearGroup (Fin (m + 1)) ℤ) (i₀ : Fin (m + 1)) (hi₀_zero : i₀ ≠ 0)
    (h_others : ∀ k, k ≠ i₀ → τ.1 k 0 = 0) (h_unit : τ.1 i₀ 0 = 1 ∨ τ.1 i₀ 0 = -1) :
    ∃ T : List (TransvectionStruct (Fin (m + 1)) ℤ),
      ((T.map TransvectionStruct.toSpecialLinearGroup).prod * τ).1 0 0 = 1 ∧
      (∀ i, i ≠ 0 →
        ((T.map TransvectionStruct.toSpecialLinearGroup).prod * τ).1 i 0 = 0) := by
  have hi₀0 : (0 : Fin (m + 1)) ≠ i₀ := fun h ↦ hi₀_zero h.symm
  set v := τ.1 i₀ 0 with hv_def
  have hv2 : v * v = 1 := by rcases h_unit with h | h <;> simp [v, h]
  set σ₁ := transvection hi₀0 v * τ with hσ₁_def
  have hσ₁_00 : σ₁.1 0 0 = 1 := by
    rw [hσ₁_def, transvection_mul_entry]; simp [h_others 0 hi₀0, ← hv_def, hv2]
  have hσ₁_i₀0 : σ₁.1 i₀ 0 = v := by
    rw [hσ₁_def, transvection_mul_entry]; simp [hi₀_zero, ← hv_def]
  have hσ₁_other : ∀ k, k ≠ 0 → k ≠ i₀ → σ₁.1 k 0 = 0 := fun k hk0 hki₀ ↦ by
    rw [hσ₁_def, transvection_mul_entry]; simp [hk0, h_others k hki₀]
  have hσ₂_00 : (transvection hi₀_zero (-v) * σ₁).1 0 0 = 1 := by
    rw [transvection_mul_entry]; simp [hi₀0, hσ₁_00]
  have hσ₂_i0 : ∀ i, i ≠ 0 → (transvection hi₀_zero (-v) * σ₁).1 i 0 = 0 := fun i hi ↦ by
    rw [transvection_mul_entry]
    rcases eq_or_ne i i₀ with rfl | hne
    · simp [hσ₁_i₀0, hσ₁_00, add_neg_cancel]
    · simp [hne, hσ₁_other i hi hne]
  refine ⟨[⟨i₀, 0, hi₀_zero, -v⟩, ⟨0, i₀, hi₀0, v⟩], ?_, ?_⟩ <;>
    simp only [List.map_cons, List.map_nil, List.prod_cons, List.prod_nil, mul_one,
      TransvectionStruct.toSpecialLinearGroup_mk, mul_assoc, ← hσ₁_def]
  · exact hσ₂_00
  · exact fun i hi ↦ hσ₂_i0 i hi

private lemma to_block_form {m : ℕ} (τ : SpecialLinearGroup (Fin (m + 1)) ℤ)
    (i₀ : Fin (m + 1)) (hi₀ : τ.1 i₀ 0 ≠ 0) (h_others : ∀ k, k ≠ i₀ → τ.1 k 0 = 0)
    (h_unit : τ.1 i₀ 0 = 1 ∨ τ.1 i₀ 0 = -1) :
    ∃ T_left T_right : List (TransvectionStruct (Fin (m + 1)) ℤ),
      ((T_left.map TransvectionStruct.toSpecialLinearGroup).prod * τ *
        (T_right.map TransvectionStruct.toSpecialLinearGroup).prod).1 0 0 = 1 ∧
      (∀ j : Fin (m + 1), j ≠ 0 →
        ((T_left.map TransvectionStruct.toSpecialLinearGroup).prod * τ *
          (T_right.map TransvectionStruct.toSpecialLinearGroup).prod).1 0 j = 0) ∧
      (∀ i : Fin (m + 1), i ≠ 0 →
        ((T_left.map TransvectionStruct.toSpecialLinearGroup).prod * τ *
          (T_right.map TransvectionStruct.toSpecialLinearGroup).prod).1 i 0 = 0) := by
  suffices h_col : ∃ T₁ : List (TransvectionStruct (Fin (m + 1)) ℤ),
      ((T₁.map TransvectionStruct.toSpecialLinearGroup).prod * τ).1 0 0 = 1 ∧
      (∀ i, i ≠ 0 →
        ((T₁.map TransvectionStruct.toSpecialLinearGroup).prod * τ).1 i 0 = 0) by
    obtain ⟨T₁, h₁_00, h₁_i0⟩ := h_col
    obtain ⟨T₂, h₂_00, h₂_0j, h₂_i0⟩ :=
      row0_clear ((T₁.map TransvectionStruct.toSpecialLinearGroup).prod * τ) h₁_00 h₁_i0
    exact ⟨T₁, T₂, h₂_00, h₂_0j, h₂_i0⟩
  by_cases hi₀_zero : i₀ = 0
  · subst hi₀_zero
    rcases h_unit with h1 | h_neg1
    · exact ⟨[], by simp [h1], fun i hi ↦ by simpa using h_others i hi⟩
    rcases m with _ | m'
    · -- in dimension one the determinant is the unique entry, `-1`, contradicting `det = 1`
      have hdet_neg : τ.1.det = -1 := by simp [Matrix.det_unique, h_neg1]
      exact absurd hdet_neg (by rw [τ.2]; norm_num)
    · exact column_pivot_of_neg_one_at_zero τ h_neg1 h_others
  · exact column_pivot_of_unit_off_diagonal τ i₀ hi₀_zero h_others h_unit

private lemma exists_list_transvec_prod_fin (m : ℕ) (σ : SpecialLinearGroup (Fin m) ℤ) :
    ∃ T : List (TransvectionStruct (Fin m) ℤ),
      σ = (T.map TransvectionStruct.toSpecialLinearGroup).prod := by
  induction m with
  | zero =>
    refine ⟨[], ?_⟩
    apply Subtype.ext; ext i; exact i.elim0
  | succ m ih =>
    obtain ⟨T_col, h_nz⟩ := col0_reduce σ
    set τ := (T_col.map TransvectionStruct.toSpecialLinearGroup).prod * σ with hτ_def
    have hσ_eq : σ = ((T_col.map TransvectionStruct.toSpecialLinearGroup).prod)⁻¹ * τ := by
      simp [hτ_def]
    obtain ⟨i₀, hi₀⟩ := col0_ne_zero τ
    have h_others := nzCount_le_one_unique_nonzero τ i₀ hi₀ h_nz
    have h_unit := sole_nonzero_col0_is_unit τ i₀ h_others
    obtain ⟨T_left, T_right, h00, h0j, hhi0⟩ := to_block_form τ i₀ hi₀ h_others h_unit
    obtain ⟨T_B, hT_B_eq⟩ := ih (extractBlock _ h00 h0j hhi0)
    obtain ⟨T_block, hT_block_eq⟩ := block_form_transvec_lift _ h00 h0j hhi0 T_B hT_B_eq
    refine ⟨(T_col.map TransvectionStruct.inv).reverse ++
      ((T_left.map TransvectionStruct.inv).reverse ++ (T_block ++
        (T_right.map TransvectionStruct.inv).reverse)), ?_⟩
    rw [List.map_append, List.prod_append, List.map_append, List.prod_append,
      List.map_append, List.prod_append, ← prod_map_inv, ← prod_map_inv, ← prod_map_inv,
      ← hT_block_eq, hσ_eq]
    group

variable {ι : Type*} [Fintype ι] [DecidableEq ι]

private lemma coe_list_prod {κ : Type*} [Fintype κ] [DecidableEq κ]
    (T : List (TransvectionStruct κ ℤ)) :
    ((T.map TransvectionStruct.toSpecialLinearGroup).prod : Matrix κ κ ℤ) =
    (T.map TransvectionStruct.toMatrix).prod := by
  induction T with
  | nil => simp
  | cons t T ih => simp [ih]

/-- Every element of `SL_n(ℤ)` is a product of elementary transvections. -/
theorem exists_list_transvec_prod (σ : SpecialLinearGroup ι ℤ) :
    ∃ T : List (TransvectionStruct ι ℤ),
      σ = (T.map TransvectionStruct.toSpecialLinearGroup).prod := by
  set e := Fintype.equivFin ι
  set σ' : SpecialLinearGroup (Fin (Fintype.card ι)) ℤ :=
    ⟨σ.1.submatrix e.symm e.symm, by rw [Matrix.det_submatrix_equiv_self]; exact σ.2⟩
    with hσ'_def
  obtain ⟨T', hT'⟩ := exists_list_transvec_prod_fin (Fintype.card ι) σ'
  refine ⟨T'.map (TransvectionStruct.reindexEquiv e.symm), Subtype.ext ?_⟩
  have hprod : (T'.map TransvectionStruct.toMatrix).prod = σ'.1 := by
    rw [← coe_list_prod, ← hT']
  calc (σ : Matrix ι ι ℤ)
      = (Matrix.reindexAlgEquiv ℤ ℤ e.symm) σ'.1 := by
        simp [hσ'_def, Matrix.submatrix_submatrix]
    _ = ((T'.map (TransvectionStruct.toMatrix ∘ TransvectionStruct.reindexEquiv e.symm))).prod
        := by rw [TransvectionStruct.toMatrix_reindexEquiv_prod, hprod]
    _ = (((T'.map (TransvectionStruct.reindexEquiv e.symm)).map
          TransvectionStruct.toSpecialLinearGroup).prod : Matrix ι ι ℤ) := by
        rw [coe_list_prod, List.map_map]

/-- `SL_n(ℤ)` is generated by its transvections. -/
theorem closure_range_toSpecialLinearGroup_eq_top :
    Subgroup.closure (Set.range (TransvectionStruct.toSpecialLinearGroup :
      TransvectionStruct ι ℤ → SpecialLinearGroup ι ℤ)) = ⊤ := by
  rw [eq_top_iff]
  intro σ _
  obtain ⟨T, rfl⟩ := exists_list_transvec_prod σ
  exact list_prod_mem fun E hE ↦ by
    obtain ⟨t, -, rfl⟩ := List.mem_map.mp hE
    exact Subgroup.subset_closure (Set.mem_range_self t)

/-- Over a field, the special linear group is generated by its elementary transvections. -/
theorem closure_range_toSpecialLinearGroup_eq_top_of_field {K : Type*} [Field K] :
    Subgroup.closure (Set.range (TransvectionStruct.toSpecialLinearGroup :
      TransvectionStruct ι K → SpecialLinearGroup ι K)) = ⊤ := by
  rw [eq_top_iff]
  intro g _
  let H := Subgroup.closure (Set.range (TransvectionStruct.toSpecialLinearGroup :
    TransvectionStruct ι K → SpecialLinearGroup ι K))
  have htransvection {i j : ι} (hij : i ≠ j) (c : K) : transvection hij c ∈ H := by
    rw [← TransvectionStruct.toSpecialLinearGroup_mk]
    exact Subgroup.subset_closure
      (Set.mem_range_self (⟨i, j, hij, c⟩ : TransvectionStruct ι K))
  by_cases hι : Nontrivial ι
  · let _ := hι
    apply diagonal_transvection_induction' (fun x => x ∈ H) g
    · intro i j hij c hc
      rw [diag2n_decompose hij c hc]
      refine H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem ?_ ?_) ?_) ?_) ?_) ?_
      all_goals apply htransvection
    · exact fun _ _ hij c => htransvection hij c
    · exact fun _ _ => H.mul_mem
  · let _ : Subsingleton ι := not_nontrivial_iff_subsingleton.mp hι
    simpa only [Subsingleton.elim g 1] using H.one_mem

end Matrix.SpecialLinearGroup

namespace EpsilonEridani

universe u v

variable {n : Type*} [DecidableEq n] [Fintype n]
variable {A : Type u} [CommRing A] {i j : n}

/-- The transvections at a fixed pair of distinct indices form a one-parameter subgroup of
`Matrix.SpecialLinearGroup n A`, isomorphic to the additive group of `A`. -/
def _root_.Matrix.SpecialLinearGroup.transvectionHom (hij : i ≠ j) :
    Multiplicative A →* Matrix.SpecialLinearGroup n A where
  toFun c := Matrix.SpecialLinearGroup.transvection hij (Multiplicative.toAdd c)
  map_one' := Matrix.SpecialLinearGroup.transvection_coeff_zero hij
  map_mul' c d := Matrix.SpecialLinearGroup.transvection_add hij
    (Multiplicative.toAdd c) (Multiplicative.toAdd d)

/-- The value of the determinant-one root subgroup homomorphism is the transvection of the
parameter. -/
@[simp]
theorem _root_.Matrix.SpecialLinearGroup.transvectionHom_apply (hij : i ≠ j)
    (c : Multiplicative A) :
    Matrix.SpecialLinearGroup.transvectionHom hij c =
      Matrix.SpecialLinearGroup.transvection hij (Multiplicative.toAdd c) := by
  unfold Matrix.SpecialLinearGroup.transvectionHom
  rfl

/-- Distinct parameters give distinct determinant-one transvections. -/
theorem _root_.Matrix.SpecialLinearGroup.transvection_injective (hij : i ≠ j) :
    Function.Injective
      (Matrix.SpecialLinearGroup.transvection hij : A → Matrix.SpecialLinearGroup n A) :=
    fun c d h => by
  have h' := congrArg (fun s : Matrix.SpecialLinearGroup n A => (s : Matrix n n A) i j) h
  simpa [Matrix.SpecialLinearGroup.transvection_coe, Matrix.one_apply,
    Matrix.single_apply, hij] using h'

variable {B : Type v} [CommRing B]

/-- A determinant-one transvection is natural in the base ring: applying a ring homomorphism
entrywise to `Matrix.SpecialLinearGroup.transvection hij c` gives
`Matrix.SpecialLinearGroup.transvection hij (f c)`. -/
@[simp]
theorem _root_.Matrix.SpecialLinearGroup.map_transvection (f : A →+* B)
    (hij : i ≠ j) (c : A) :
    Matrix.SpecialLinearGroup.map f (Matrix.SpecialLinearGroup.transvection hij c) =
      Matrix.SpecialLinearGroup.transvection hij (f c) := by
  ext a b
  simp [Matrix.SpecialLinearGroup.map_apply_coe, RingHom.mapMatrix_apply, Matrix.map_apply,
    Matrix.SpecialLinearGroup.transvection_coe, Matrix.one_apply, Matrix.single_apply,
    apply_ite f]

end EpsilonEridani

namespace EpsilonEridani

open Matrix

universe w

variable {n : Type*} [Fintype n] [DecidableEq n]
variable {A : Type w} [CommRing A] {i j k l : n}

/-! ## The commutator relations between transvections -/

/-- Two matrices of the form `Matrix.transvection` commute when the corresponding matrix-unit
products vanish in both orders. When both index pairs are distinct, these are root-subgroup
elements and the sum of the two roots `εᵢ - εⱼ` and `εₖ - εₗ` is not a root. -/
theorem commute_transvection (hjk : j ≠ k) (hli : l ≠ i) (c d : A) :
    Commute (transvection i j c) (transvection k l d) := by
  simp only [Commute, SemiconjBy, transvection, Matrix.add_mul, Matrix.mul_add, Matrix.one_mul,
    Matrix.mul_one, single_mul_single_of_ne _ _ _ _ hjk, single_mul_single_of_ne _ _ _ _ hli]
  abel

/-- A product identity for two chaining matrices of the form `Matrix.transvection`: reversing
their order produces the extra factor at `(i, l)`. When `j ≠ l` as well, all three index pairs
are distinct and this is the type `A` Chevalley commutator relation before it is written as a
commutator. -/
theorem transvection_mul_transvection_eq_mul_mul (hij : i ≠ j) (hil : i ≠ l) (c d : A) :
    transvection i j c * transvection j l d =
      transvection j l d * transvection i j c * transvection i l (c * d) := by
  have hli : l ≠ i := hil.symm
  have hji : j ≠ i := hij.symm
  simp only [transvection, Matrix.add_mul, Matrix.mul_add, Matrix.one_mul, Matrix.mul_one,
    single_mul_single_same, single_mul_single_of_ne _ _ _ _ hli,
    single_mul_single_of_ne _ _ _ _ hji, Matrix.zero_mul]
  abel

end EpsilonEridani

namespace Matrix.SpecialLinearGroup

open scoped commutatorElement

universe w

variable {n : Type*} [Fintype n] [DecidableEq n]
variable {A : Type w} [CommRing A] {i j k l : n}

/-- Two determinant-one transvections at index pairs that do not chain commute in `SL n A`. -/
theorem commute_transvection (hij : i ≠ j) (hkl : k ≠ l) (hjk : j ≠ k) (hli : l ≠ i)
    (c d : A) : Commute (transvection hij c) (transvection hkl d) := by
  exact (commute_iff_eq _ _).mpr (Subtype.ext (by
    simpa only [SpecialLinearGroup.coe_mul, SpecialLinearGroup.transvection_coe,
      Matrix.transvection] using
      (EpsilonEridani.commute_transvection hjk hli c d).eq))

/-- A product identity for two chaining determinant-one transvections: reversing their order
produces the extra transvection at `(i, l)`. -/
theorem transvection_mul_transvection_eq_mul_mul
    (hij : i ≠ j) (hjl : j ≠ l) (hil : i ≠ l) (c d : A) :
    transvection hij c * transvection hjl d =
      transvection hjl d * transvection hij c * transvection hil (c * d) := by
  apply Subtype.ext
  simpa only [SpecialLinearGroup.coe_mul, SpecialLinearGroup.transvection_coe,
    Matrix.transvection] using
    EpsilonEridani.transvection_mul_transvection_eq_mul_mul hij hil c d

/-- **The Chevalley commutator relation of type `A` in `SL n A`.** The commutator of the
determinant-one transvections `xᵢⱼ(c)` and `xⱼₗ(d)`, for distinct `i`, `j` and `l`, is
`xᵢₗ(cd)`. -/
theorem commutatorElement_transvection
    (hij : i ≠ j) (hjl : j ≠ l) (hil : i ≠ l) (c d : A) :
    ⁅transvection hij c, transvection hjl d⁆ = transvection hil (c * d) := by
  have hxz : Commute (transvection hij c) (transvection hil (c * d)) :=
    commute_transvection hij hil hij.symm hil.symm c (c * d)
  have hyz : Commute (transvection hjl d) (transvection hil (c * d)) :=
    commute_transvection hjl hil hil.symm hjl.symm d (c * d)
  rw [commutatorElement_def, transvection_mul_transvection_eq_mul_mul hij hjl hil,
    mul_assoc (transvection hjl d) (transvection hij c),
    hxz.eq, ← mul_assoc, mul_inv_cancel_right, hyz.eq, mul_inv_cancel_right]

end Matrix.SpecialLinearGroup
