/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.RingTheory.DedekindDomain.Ideal.Lemmas
public import Mathlib.RingTheory.Ideal.MonicSpan

/-!
# The height one spectrum of a polynomial ring over a field

A polynomial ring `k[X]` over a field is a principal ideal domain, so each of its height-one
primes is generated by a single polynomial; normalizing that generator to be monic pins it down
uniquely: every height-one prime of `k[X]` has a unique monic irreducible generator. This is what
attaches a monic irreducible polynomial to each finite place of the rational function field
(Stichtenoth, *Algebraic Function Fields and Codes*, 2nd ed., Proposition 1.2.1(a)).

## Main definitions

* `IsDedekindDomain.HeightOneSpectrum.ofIrreducible`: the height-one prime generated by an
  irreducible polynomial.
* `IsDedekindDomain.HeightOneSpectrum.monicIrreducibleEquiv`: the resulting bijection between the
  monic irreducible polynomials and the height-one primes of `k[X]`.

## Main results

* `IsDedekindDomain.HeightOneSpectrum.existsUnique_monic_irreducible_span`: a height-one prime of
  `k[X]` is generated by a unique monic irreducible polynomial;
  `IsDedekindDomain.HeightOneSpectrum.exists_monic_irreducible_eq_ofIrreducible` says the same in
  the vocabulary of `IsDedekindDomain.HeightOneSpectrum.ofIrreducible`.

## References

* `Mathlib/RingTheory/Ideal/MonicSpan.lean` by Nailin Guan, whose
  `Polynomial.exists_monic_span` supplies the monic generator used here.
-/

public section

open Polynomial

namespace IsDedekindDomain.HeightOneSpectrum

variable {k : Type*} [Field k]

/-- **Each height-one prime of `k[X]` is generated by a unique monic irreducible polynomial.** -/
theorem existsUnique_monic_irreducible_span (p : HeightOneSpectrum k[X]) :
    ∃! q : k[X], q.Monic ∧ Irreducible q ∧ p.asIdeal = Ideal.span {q} := by
  obtain ⟨q, hqm, hspan⟩ := Polynomial.exists_monic_span p.asIdeal p.ne_bot
  have hirr : Irreducible q :=
    ((Ideal.span_singleton_prime hqm.ne_zero).mp (hspan ▸ p.isPrime)).irreducible
  refine ⟨q, ⟨hqm, hirr, hspan⟩, ?_⟩
  rintro r ⟨hrm, -, hrs⟩
  exact eq_of_monic_of_associated hrm hqm
    (Ideal.span_singleton_eq_span_singleton.mp (hrs.symm.trans hspan))

/-- The height-one prime of `k[X]` generated by an irreducible polynomial. This generalizes
Mathlib's `Polynomial.idealX`, the prime generated by `X`. -/
noncomputable def ofIrreducible {q : k[X]} (hq : Irreducible q) :
    HeightOneSpectrum k[X] :=
  HeightOneSpectrum.ofPrime (Ideal.prime_of_isPrime
    (by rw [ne_eq, Ideal.span_singleton_eq_bot]; exact hq.ne_zero)
    ((Ideal.span_singleton_prime hq.ne_zero).mpr hq.prime))

@[simp]
theorem ofIrreducible_asIdeal {q : k[X]} (hq : Irreducible q) :
    (ofIrreducible hq).asIdeal = Ideal.span {q} :=
  HeightOneSpectrum.ofPrime_asIdeal _

/-- **Every height-one prime of `k[X]` is the prime of a monic irreducible polynomial**: this is
`IsDedekindDomain.HeightOneSpectrum.existsUnique_monic_irreducible_span` read through
`IsDedekindDomain.HeightOneSpectrum.ofIrreducible`. -/
theorem exists_monic_irreducible_eq_ofIrreducible (p : HeightOneSpectrum k[X]) :
    ∃ (q : k[X]) (hq : Irreducible q), q.Monic ∧ p = ofIrreducible hq := by
  obtain ⟨q, ⟨hqm, hqi, hspan⟩, -⟩ := p.existsUnique_monic_irreducible_span
  exact ⟨q, hqi, hqm, HeightOneSpectrum.ext (hspan.trans (ofIrreducible_asIdeal hqi).symm)⟩

/-- **The height-one primes of `k[X]` are the monic irreducible polynomials**: the prime generated
by a monic irreducible polynomial determines it, by
`IsDedekindDomain.HeightOneSpectrum.existsUnique_monic_irreducible_span`. -/
noncomputable def monicIrreducibleEquiv :
    {q : k[X] // q.Monic ∧ Irreducible q} ≃ HeightOneSpectrum k[X] :=
  Equiv.ofBijective (fun q => ofIrreducible q.2.2)
    ⟨fun q r h => Subtype.ext (eq_of_monic_of_associated q.2.1 r.2.1
        (Ideal.span_singleton_eq_span_singleton.mp (by
          have h' := congrArg HeightOneSpectrum.asIdeal h
          rwa [ofIrreducible_asIdeal, ofIrreducible_asIdeal] at h'))),
      fun p => by
        obtain ⟨q, hqi, hqm, rfl⟩ := p.exists_monic_irreducible_eq_ofIrreducible
        exact ⟨⟨q, hqm, hqi⟩, rfl⟩⟩

@[simp]
theorem monicIrreducibleEquiv_apply (q : {q : k[X] // q.Monic ∧ Irreducible q}) :
    monicIrreducibleEquiv q = ofIrreducible q.2.2 :=
  (rfl)

@[simp]
theorem span_monicIrreducibleEquiv_symm (p : HeightOneSpectrum k[X]) :
    Ideal.span {((monicIrreducibleEquiv.symm p : {q : k[X] // q.Monic ∧ Irreducible q}) : k[X])} =
      p.asIdeal := by
  rw [← ofIrreducible_asIdeal (monicIrreducibleEquiv.symm p).2.2, ← monicIrreducibleEquiv_apply,
    Equiv.apply_symm_apply]

end IsDedekindDomain.HeightOneSpectrum

end
