/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Geometry.Convex.Cone.Face.Basic
public import Mathlib.Algebra.Order.Archimedean.Basic
public import Mathlib.RingTheory.Finiteness.Defs
import EpsilonEridani.Geometry.Convex.Cone.Face.Finite

/-!
# Faces cut out by nonnegative linear functionals

A linear functional `φ` that is nonnegative on a pointed cone `C` cuts out the face
`C ⊓ ker φ` of `C`. This file records that fact and the finiteness property that makes such faces
useful for localization: if `C` is finitely generated, then any functional `ψ` that is nonnegative
on the face `C ⊓ ker φ` becomes nonnegative on all of `C` after adding a sufficiently large
multiple of `φ`. Conversely, a face `F` of the cone hull of a set `s` is cut out by any
functional that is nonnegative on `s` and vanishes at exactly the members of `s` lying in `F`.

The second statement is what identifies the dual of the face with the dual of `C` enlarged by
`-φ`. In toric geometry it shows that the semigroup of characters of the face `σ ∩ m^⊥` is
obtained from that of `σ` by adjoining `-m`, so the affine chart of the face is the localization of
the chart of `σ` away from the monomial of `m`. Finite generation cannot be dropped: the cone in
`ℝ²` generated by all vectors `(1, t)` with `t ≥ 0` meets the kernel of `φ (x, y) = x` only in
`0`, so `ψ (x, y) = -y` is nonnegative on that face, yet `ψ + n • φ` is negative at `(1, n + 1)`.

## Main declarations

* `PointedCone.isFaceOf_inf_ker`: a functional nonnegative on `C` cuts out a face of `C`.
* `PointedCone.inf_ker_add`: the face cut out by a sum of nonnegative functionals is the
  intersection of the faces they cut out.
* `PointedCone.inf_ker_eq_of_eq_hull`: a functional nonnegative on a generating set and vanishing
  at exactly the generators in a face `F` cuts out `F`.
* `PointedCone.FG.exists_nonneg_add_nsmul`: on a finitely generated cone, a functional
  nonnegative on the face cut out by `φ` becomes nonnegative after adding a multiple of `φ`.

## References

* W. Fulton, *Introduction to Toric Varieties*, §§1.2–1.3.
* D. Cox, J. Little and H. Schenck, *Toric Varieties*, §1.2 and §1.3.
-/

public section

namespace PointedCone

section

variable {R M : Type*} [AddCommMonoid M]

/-- If two linear functionals `φ` and `ψ` are nonnegative on a pointed cone `C`, the face cut out
by `φ + ψ` is the intersection of the faces cut out by `φ` and by `ψ`. -/
theorem inf_ker_add [Semiring R] [PartialOrder R] [IsOrderedRing R] [Module R M]
    {C : PointedCone R M} {φ ψ : Module.Dual R M} (hφ : ∀ x ∈ C, 0 ≤ φ x)
    (hψ : ∀ x ∈ C, 0 ≤ ψ x) :
    C ⊓ PointedCone.ofSubmodule (LinearMap.ker (φ + ψ)) =
      (C ⊓ PointedCone.ofSubmodule (LinearMap.ker φ)) ⊓
        (C ⊓ PointedCone.ofSubmodule (LinearMap.ker ψ)) := by
  ext x
  simp only [Submodule.mem_inf, PointedCone.mem_ofSubmodule_iff, LinearMap.mem_ker,
    LinearMap.add_apply]
  refine ⟨fun ⟨hx, h⟩ ↦ ?_, fun ⟨⟨hx, h₁⟩, _, h₂⟩ ↦ ⟨hx, by rw [h₁, h₂, add_zero]⟩⟩
  obtain ⟨h₁, h₂⟩ := (add_eq_zero_iff_of_nonneg (hφ x hx) (hψ x hx)).1 h
  exact ⟨⟨hx, h₁⟩, hx, h₂⟩

end

section

variable {R M : Type*} [AddCommGroup M]

/-- A linear functional that is nonnegative on a pointed cone cuts out a face of the cone. -/
theorem isFaceOf_inf_ker [Semiring R] [PartialOrder R] [IsOrderedRing R] [NoZeroDivisors R]
    [Module R M] {C : PointedCone R M} {φ : Module.Dual R M} (hφ : ∀ x ∈ C, 0 ≤ φ x) :
    (C ⊓ PointedCone.ofSubmodule (LinearMap.ker φ)).IsFaceOf C := by
  refine ⟨inf_le_left, fun {x y a} hx hy ha hxy ↦ ⟨hx, ?_⟩⟩
  have hker : φ (a • x + y) = 0 := hxy.2
  rw [map_add, map_smul, smul_eq_mul] at hker
  have hax : a * φ x = 0 :=
    (add_eq_zero_iff_of_nonneg (mul_nonneg ha.le (hφ x hx)) (hφ y hy)).1 hker |>.1
  exact (mul_eq_zero.1 hax).resolve_left ha.ne'

/-- Let `F` be a face of the cone hull `C` of a set `s`. A linear functional that is nonnegative on
`s` and vanishes at exactly those members of `s` which lie in `F` cuts out `F` from `C`. -/
theorem inf_ker_eq_of_eq_hull [Semiring R] [PartialOrder R] [IsOrderedRing R] [NoZeroDivisors R]
    [Module R M] {C F : PointedCone R M} {s : Set M} (hC : C = PointedCone.hull R s)
    (hF : F.IsFaceOf C) {φ : Module.Dual R M} (hφ : ∀ x ∈ s, 0 ≤ φ x)
    (hφF : ∀ x ∈ s, φ x = 0 ↔ x ∈ F) :
    C ⊓ PointedCone.ofSubmodule (LinearMap.ker φ) = F := by
  have hφC : ∀ x ∈ C, 0 ≤ φ x := by
    subst hC
    intro x hx
    induction hx using Submodule.span_induction with
    | mem x hx => exact hφ x hx
    | zero => simp
    | add x y _ _ hx hy => rw [map_add]; exact add_nonneg hx hy
    | smul c x _ hx => rw [← Nonneg.coe_smul, map_smul, smul_eq_mul]; exact mul_nonneg c.2 hx
  -- Both cones are faces of `C`, so each is generated by the members of `s` it contains.
  refine le_antisymm ((Face.eq_hull_inter_of_eq_hull ⟨_, isFaceOf_inf_ker hφC⟩ s hC).le.trans
    (Submodule.span_le.2 fun x hx ↦ (hφF x hx.1).1 hx.2.2)) ?_
  exact (Face.eq_hull_inter_of_eq_hull ⟨F, hF⟩ s hC).le.trans <| Submodule.span_le.2 fun x hx ↦
    ⟨hC ▸ PointedCone.subset_hull hx.1, (hφF x hx.1).2 hx.2⟩

end

section

variable {R M : Type*} [AddCommMonoid M]

/-- On a finitely generated pointed cone `C`, let `φ` be nonnegative on `C` and let `ψ` be
nonnegative on the face `C ⊓ ker φ`. Then `ψ + n • φ` is nonnegative on `C` for some natural
number `n`. -/
theorem FG.exists_nonneg_add_nsmul [Ring R] [PartialOrder R] [IsOrderedRing R] [Archimedean R]
    [Module R M] {C : PointedCone R M} (hC : C.FG) {φ ψ : Module.Dual R M}
    (hφ : ∀ x ∈ C, 0 ≤ φ x) (hψ : ∀ x ∈ C, φ x = 0 → 0 ≤ ψ x) :
    ∃ n : ℕ, ∀ x ∈ C, 0 ≤ ψ x + n • φ x := by
  obtain ⟨s, rfl⟩ := hC
  -- Each generator needs its own multiple of `φ`; the largest of them works for all of `C`.
  have hgen : ∀ v ∈ s, ∃ n : ℕ, 0 ≤ ψ v + n • φ v := by
    intro v hv
    have hvC : v ∈ PointedCone.hull R (s : Set M) := PointedCone.subset_hull hv
    rcases (hφ v hvC).eq_or_lt with h | h
    · exact ⟨0, by simpa using hψ v hvC h.symm⟩
    · obtain ⟨n, hn⟩ := Archimedean.arch (-ψ v) h
      exact ⟨n, by rwa [neg_le_iff_add_nonneg, add_comm] at hn⟩
  choose! n hn using hgen
  refine ⟨s.sup n, fun x hx ↦ ?_⟩
  induction hx using Submodule.span_induction with
  | mem v hv =>
    have hle : n v • φ v ≤ s.sup n • φ v :=
      nsmul_le_nsmul_left (hφ v (Submodule.subset_span hv)) (Finset.le_sup hv)
    exact (hn v hv).trans (add_le_add_right hle _)
  | zero => simp
  | add x y _ _ hx hy =>
    rw [map_add, map_add, smul_add, add_add_add_comm]
    exact add_nonneg hx hy
  | smul c x _ hx =>
    rw [← Nonneg.coe_smul]
    calc
      0 ≤ (c : R) * (ψ x + s.sup n • φ x) := mul_nonneg c.2 hx
      _ = ψ ((c : R) • x) + s.sup n • φ ((c : R) • x) := by
        simp only [map_smul, smul_eq_mul, ← mul_smul_comm, mul_add]

end

end PointedCone
