/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.LinearAlgebra.Finsupp.LinearCombination
public import EpsilonEridani.Geometry.Convex.Cone.Face.Finite

/-!
# The face lattice of a simplicial cone

A simplicial cone is the cone hull of a linearly independent family `v : ι → M`. Because the
coefficients of a conical combination of a linearly independent family are unique, the faces of
such a cone are exactly the subcones spanned by subfamilies: the face lattice of
`PointedCone.hull R (Set.range v)` is the powerset of `ι`.

Both halves of the correspondence use the description of the cone hull of a subfamily as the set
of conical combinations supported on that subfamily. That a face is spanned by the generators it
contains holds for any generating set, and the family-indexed form
`PointedCone.Face.eq_hull_image` is a reindexing of
`PointedCone.Face.eq_hull_inter_of_eq_hull`. The converse, that every subfamily spans a face, is
where linear independence enters: if `a • x + y` has no `v j` component for `j` outside a subset
`A`, then neither does `x`, because the two nonnegative contributions to the `j`-th coefficient
cannot cancel.

Linear independence cannot be dropped. The cone in `ℝ²` spanned by `(1, 0)`, `(1, 1)` and
`(0, 1)` has four faces, not the eight cones spanned by subsets of that family, since the ray
through `(1, 1)` is not a face; and the cone spanned by `(1, 0)` and `(-1, 0)` is a line whose
only face is itself.

## Main declarations

* `PointedCone.mem_hull_image_iff_linearCombination`: membership in the cone hull of a subfamily
  is the existence of a nonnegative coefficient family supported on that subfamily. This is the
  cone analogue of `Finsupp.mem_span_image_iff_linearCombination`.
* `PointedCone.isFaceOf_hull_image`: a subfamily of a linearly independent family spans a face of
  the cone it generates.
* `PointedCone.apply_mem_hull_image_iff`: a member of a linearly independent family lies in the
  cone spanned by a subfamily exactly when it belongs to that subfamily.
* `PointedCone.Face.eq_hull_image`: a face of a cone generated by a family is spanned by the
  members of that family which it contains.
* `PointedCone.faceOrderIsoSet`: the face lattice of a simplicial cone is the lattice of subsets
  of its generating family.

## References

* D. Cox, J. Little and H. Schenck, *Toric Varieties*, §1.2.
* W. Fulton, *Introduction to Toric Varieties*, §1.2.
-/

public section

namespace PointedCone

variable {R M ι : Type*} [Semiring R] [PartialOrder R] [IsOrderedRing R]
  {v : ι → M} {A : Set ι} {x : M}

section AddCommMonoid

variable [AddCommMonoid M] [Module R M]

/-- An element of the cone hull of a subfamily `v '' A` is exactly a conical combination of the
family `v` whose coefficients are supported on `A`. This is the conical analogue of
`Finsupp.mem_span_image_iff_linearCombination`, with nonnegative coefficients. -/
theorem mem_hull_image_iff_linearCombination :
    x ∈ hull R (v '' A) ↔
      ∃ c ∈ Finsupp.supported R R A, (∀ j, 0 ≤ c j) ∧ Finsupp.linearCombination R v c = x := by
  constructor
  · intro hx
    -- The nonnegative scalars are a semiring, so the span description applies verbatim to them.
    obtain ⟨c, hcA, rfl⟩ := (Finsupp.mem_span_image_iff_linearCombination _).1 hx
    refine ⟨c.mapRange Subtype.val rfl, ?_, fun j ↦ (c j).2, ?_⟩
    · exact (Finsupp.mem_supported _ _).2 <| (Finset.coe_subset.2 Finsupp.support_mapRange).trans
        ((Finsupp.mem_supported _ _).1 hcA)
    · rw [Finsupp.linearCombination_apply, Finsupp.linearCombination_apply,
        Finsupp.sum_mapRange_index (by simp)]
      exact Finsupp.sum_congr fun j _ ↦ Nonneg.coe_smul _ _
  · rintro ⟨c, hcA, hc0, rfl⟩
    rw [Finsupp.mem_supported] at hcA
    rw [Finsupp.linearCombination_apply, Finsupp.sum]
    refine Submodule.sum_mem _ fun j hj ↦ smul_mem _ (hc0 j) ?_
    exact subset_hull ⟨j, hcA hj, rfl⟩

/-- A member of a linearly independent family lies in the cone spanned by a subfamily exactly
when it is one of the vectors of that subfamily. -/
theorem apply_mem_hull_image_iff [Nontrivial R] (hv : LinearIndependent R v) {j : ι} :
    v j ∈ hull R (v '' A) ↔ j ∈ A := by
  refine ⟨fun h ↦ ?_, fun h ↦ subset_hull ⟨j, h, rfl⟩⟩
  obtain ⟨c, hcA, -, hc⟩ := mem_hull_image_iff_linearCombination.1 h
  have hcj : c = Finsupp.single j 1 :=
    hv.finsuppLinearCombination_injective (by simp [hc])
  rw [Finsupp.mem_supported, hcj] at hcA
  exact hcA (by simp)

end AddCommMonoid

section AddCommGroup

variable [AddCommGroup M] [Module R M] {C : PointedCone R M}

/-- A subfamily of a linearly independent family spans a face of the cone generated by the whole
family: the coefficients of a conical combination are unique, and a positive combination cannot
cancel the coefficients outside the subfamily. -/
theorem isFaceOf_hull_image [NoZeroDivisors R] (hv : LinearIndependent R v)
    (hC : C = hull R (Set.range v)) (A : Set ι) : (hull R (v '' A)).IsFaceOf C := by
  subst hC
  refine ⟨Submodule.span_mono (Set.image_subset_range v A), ?_⟩
  intro x y a hx hy ha hxy
  rw [← Set.image_univ] at hx hy
  obtain ⟨c, -, hc0, rfl⟩ := mem_hull_image_iff_linearCombination.1 hx
  obtain ⟨d, -, hd0, rfl⟩ := mem_hull_image_iff_linearCombination.1 hy
  obtain ⟨e, heA, -, he⟩ := mem_hull_image_iff_linearCombination.1 hxy
  rw [Finsupp.mem_supported] at heA
  have hcd : a • c + d = e :=
    hv.finsuppLinearCombination_injective (by rw [map_add, map_smul, he])
  refine mem_hull_image_iff_linearCombination.2
    ⟨c, (Finsupp.mem_supported R c).2 fun j hj ↦ ?_, hc0, rfl⟩
  by_contra hjA
  -- Outside `A` the `j`-th coefficient of `a • x + y` vanishes, and both summands are nonnegative.
  have hej : e j = 0 := by
    by_contra hne
    exact hjA (heA (Finsupp.mem_support_iff.2 hne))
  have hsum : a * c j + d j = 0 := by
    simpa [hej] using congrArg (fun f : ι →₀ R ↦ f j) hcd
  have hac : a * c j = 0 :=
    ((add_eq_zero_iff_of_nonneg (mul_nonneg ha.le (hc0 j)) (hd0 j)).1 hsum).1
  exact (Finsupp.mem_support_iff.1 hj) ((mul_eq_zero.1 hac).resolve_left ha.ne')

/-- A face of a cone generated by a family `v` is the cone spanned by the members of `v` that it
contains. -/
theorem Face.eq_hull_image (F : C.Face) (hC : C = hull R (Set.range v)) :
    F.toPointedCone = hull R (v '' {j | v j ∈ F}) := by
  rw [F.eq_hull_inter_of_eq_hull (Set.range v) hC]
  refine congrArg (hull R) (Set.ext fun y ↦ ⟨?_, ?_⟩)
  · rintro ⟨⟨j, rfl⟩, hy⟩
    exact ⟨j, hy, rfl⟩
  · rintro ⟨j, hj, rfl⟩
    exact ⟨⟨j, rfl⟩, hj⟩

/-- The face lattice of the cone hull of a linearly independent family `v : ι → M` is the lattice
of subsets of `ι`: a face is recorded by the set of indices whose vectors it contains, and a set
of indices spans the corresponding face. -/
def faceOrderIsoSet [Nontrivial R] [NoZeroDivisors R] (hv : LinearIndependent R v)
    (hC : C = hull R (Set.range v)) : C.Face ≃o Set ι where
  toFun F := {j | v j ∈ F}
  invFun A := ⟨hull R (v '' A), isFaceOf_hull_image hv hC A⟩
  left_inv F := by
    refine SetLike.coe_injective ?_
    exact congrArg (fun P : PointedCone R M ↦ (P : Set M)) (F.eq_hull_image hC).symm
  right_inv _ := Set.ext fun _ ↦ apply_mem_hull_image_iff hv
  map_rel_iff' {F₁ F₂} := by
    refine ⟨fun h ↦ ?_, fun h _ hj ↦ h hj⟩
    rw [← Face.toPointedCone_le_toPointedCone, F₁.eq_hull_image hC, F₂.eq_hull_image hC]
    exact Submodule.span_mono (Set.image_mono h)

@[simp]
theorem faceOrderIsoSet_apply [Nontrivial R] [NoZeroDivisors R] (hv : LinearIndependent R v)
    (hC : C = hull R (Set.range v)) (F : C.Face) :
    faceOrderIsoSet hv hC F = {j | v j ∈ F} := (rfl)

@[simp]
theorem faceOrderIsoSet_symm_apply_toPointedCone [Nontrivial R] [NoZeroDivisors R]
    (hv : LinearIndependent R v) (hC : C = hull R (Set.range v)) (A : Set ι) :
    ((faceOrderIsoSet hv hC).symm A).toPointedCone = hull R (v '' A) := (rfl)

end AddCommGroup

end PointedCone
