/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Codex
-/
module

public import EpsilonEridani.Algebra.AlgebraicGroup.HopfIdeal.Normal.CommonKernel
public import EpsilonEridani.Algebra.AlgebraicGroup.HopfIdeal.Points.CommonKernel
public import EpsilonEridani.Algebra.AlgebraicGroup.HopfIdeal.Points.Order

/-!
# Points of a normal closed subgroup generated by morphisms

This file gives the point-level consequences of the normal common-kernel construction. The
quotient cuts out a normal subgroup over every commutative value algebra, and the abstract
normal subgroup generated by the defining point images lies in it. No equality of point sets is
asserted.

## Main declarations

* `EpsilonEridani.CommHopfAlgCat.normalCommonKernelPoints_normal`: normality on algebra-valued points.
* `EpsilonEridani.CommHopfAlgCat.mapPoints_normalCommonKernel_mem_quotientPointsSubgroup`: every point
  in one of the defining families belongs to the normal common-kernel quotient points.
* `EpsilonEridani.CommHopfAlgCat.normalClosure_iUnion_range_mapPoints_le_normalCommonKernelPoints`: the
  abstract normal subgroup generated by the defining point images lies in the normal quotient
  points.
-/

public section

open WithConv

namespace EpsilonEridani.CommHopfAlgCat

universe u v w x

variable {R : Type u} [CommRing R]
variable {H : _root_.CommHopfAlgCat.{v} R}
variable {ι : Type w} {K : ι → _root_.CommHopfAlgCat.{v} R}

/-- The normal common-kernel quotient cuts out a normal subgroup of the ambient point group over
every commutative value algebra. -/
instance normalCommonKernelPoints_normal (f : ∀ i, H ⟶ K i) (A : CommAlgCat.{x} R) :
    (quotientPointsSubgroup H (normalCommonKernelHopfIdeal f) A).Normal :=
  quotientPointsSubgroup_normal H (normalCommonKernelHopfIdeal f)
    (isNormal_normalCommonKernelHopfIdeal f) A

/-- Every point obtained from one of the defining morphisms belongs to the normal closed subgroup
generated by the family. -/
theorem mapPoints_normalCommonKernel_mem_quotientPointsSubgroup
    (f : ∀ i, H ⟶ K i) (i : ι) (A : CommAlgCat.{x} R)
    (p : HopfAlgebra.points (R := R) (H := K i) A) :
    toConv (p.ofConv.comp ((f i).hom : H →ₐ[R] K i)) ∈
      quotientPointsSubgroup H (normalCommonKernelHopfIdeal f) A :=
  mem_quotientPointsSubgroup_of_le H
    (normalCommonKernelHopfIdeal_le_commonKernelHopfIdeal f) A
    (mapPoints_commonKernel_mem_quotientPointsSubgroup f i A p)

/-- The abstract normal subgroup generated by all point images lies in their normal generated
closed subgroup. No equality of point sets is asserted. -/
theorem normalClosure_iUnion_range_mapPoints_le_normalCommonKernelPoints
    (f : ∀ i, H ⟶ K i) (A : CommAlgCat.{x} R) :
    Subgroup.normalClosure (⋃ i, Set.range (fun p : HopfAlgebra.points (R := R) (H := K i) A ↦
      toConv (p.ofConv.comp ((f i).hom : H →ₐ[R] K i)))) ≤
      quotientPointsSubgroup H (normalCommonKernelHopfIdeal f) A :=
  Subgroup.normalClosure_le_normal <| Subgroup.subset_closure.trans <|
    (closure_iUnion_range_mapPoints_le_commonKernelPoints f A).trans <|
      quotientPointsSubgroup_le_of_le H
        (normalCommonKernelHopfIdeal_le_commonKernelHopfIdeal f) A

end EpsilonEridani.CommHopfAlgCat
