/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Data.ZMod.Basic
public import Mathlib.RingTheory.Ideal.Quotient.Defs
public import EpsilonEridani.LinearAlgebra.QuadraticForm.RegularFormClass.Discriminant
public import EpsilonEridani.LinearAlgebra.QuadraticForm.RegularFormClass.Semiring
public import EpsilonEridani.LinearAlgebra.QuadraticForm.Witt.Decomposition
public import EpsilonEridani.RingTheory.GrothendieckRing

/-!
# The Witt-Grothendieck ring and the Witt ring of a field

Over a field in which `2` is invertible the isometry classes of regular finite-dimensional
quadratic forms form a commutative semiring under orthogonal sum and tensor product, and Witt
cancellation makes that semiring additively cancellative. Its Grothendieck ring is the
**Witt-Grothendieck ring** `GW(K)`, and the **Witt ring** `W(K)` is the quotient of `GW(K)` by the
ideal generated by the class of the hyperbolic plane.

The ideal is easy to describe because the hyperbolic plane absorbs tensor products: `q ⊗ ℍ` is
`dim q` copies of `ℍ` for every regular `q`, so the ideal it generates is exactly the cyclic
subgroup `ℤ · [ℍ]`. Consequently two forms have the same Witt class exactly when they differ by
hyperbolic planes, which by the uniqueness half of Witt decomposition happens exactly when their
anisotropic parts are isometric. Each Witt class therefore has a canonical representative, the
anisotropic part, unique up to isometry. Under this identification the ring operations take the
anisotropic part after the usual operations on forms.

Scaling by `-1` supplies additive inverses modulo hyperbolic planes — `q ⊥ (-q)` is `dim q`
copies of `ℍ` — so every element of `W(K)` is the Witt class of an honest form even though `GW(K)`
also contains formal differences.

## Main definitions

* `EpsilonEridani.WittGrothendieckRing`: the Witt-Grothendieck ring `GW(K)`.
* `EpsilonEridani.toWittGrothendieck`: the class of a regular form in `GW(K)`.
* `EpsilonEridani.WittGrothendieckRing.rank`: the rank of a virtual form, as a map to `ℤ`.
* `EpsilonEridani.hyperbolicIdeal`: the ideal of `GW(K)` generated by the hyperbolic plane.
* `EpsilonEridani.WittRing`: the Witt ring `W(K)`.
* `EpsilonEridani.wittClass`: the Witt class of a regular form.
* `EpsilonEridani.WittRing.dimMod2`: the dimension map `W(K) → ZMod 2`.

## Main results

* `EpsilonEridani.RegularFormClass.mul_hyperbolicClass`: `q ⊗ ℍ` is `dim q` copies of `ℍ`.
* `EpsilonEridani.mem_hyperbolicIdeal_iff`: the hyperbolic ideal is the cyclic subgroup on `[ℍ]`.
* `EpsilonEridani.wittClass_eq_iff_anisotropicPart_eq`: two forms have the same Witt class exactly when
  their anisotropic parts agree.
* `EpsilonEridani.wittClass_surjective`: every element of the Witt ring is the class of a form.

## References

* T. Y. Lam, *Introduction to Quadratic Forms over Fields* (2005), Chapter II, §1.
-/

public section

open QuadraticMap QuadraticForm

namespace EpsilonEridani

universe u

variable {K : Type u} [Field K] [Invertible (2 : K)]

/-! ### Multiples of the hyperbolic class -/

/-- Scaling a hyperbolic plane by a unit gives a hyperbolic plane: `⟨a⟩ ⊗ ℍ ≅ ⟨a, -a⟩ ≅ ℍ`. -/
theorem RegularFormClass.mk_rankOne_mul_hyperbolicClass (a : Kˣ) :
    Quotient.mk (regularFormSetoid K) ⟨1, fun _ => a⟩ * hyperbolicClass K = hyperbolicClass K := by
  refine RegularFormClass.eq_hyperbolicClass_of_rank_eq_two_of_discr_eq_neg_one ?_ ?_
  · simp
  · rw [RegularFormClass.discr_mk_rankOne_mul, rank_hyperbolicClass,
      RegularFormClass.discr_hyperbolicClass,
      ZModModule.char_nsmul_eq_zero 2 (squareClass a : SquareClassGroup K)]
    abel

/-- **The hyperbolic plane absorbs tensor products**: `q ⊗ ℍ` is `dim q` copies of `ℍ`. This is
what makes the ideal generated by the hyperbolic plane a cyclic subgroup. -/
theorem RegularFormClass.mul_hyperbolicClass (x : RegularFormClass K) :
    x * hyperbolicClass K = RegularFormClass.rank x • hyperbolicClass K := by
  induction x using RegularFormClass.induction_on_rankOne with
  | zero => simp
  | add_rankOne y a ih =>
    rw [add_mul, ih, RegularFormClass.mk_rankOne_mul_hyperbolicClass,
      RegularFormClass.rank_add, RegularFormClass.rank_mk, add_nsmul, one_nsmul]

/-- Adding a rank-one class to its scaling by `-1` produces a hyperbolic plane:
`⟨a, -a⟩ ≅ ℍ`. -/
theorem RegularFormClass.mk_rankOne_add_neg_one_mul (a : Kˣ) :
    Quotient.mk (regularFormSetoid K) ⟨1, fun _ => a⟩ +
        Quotient.mk (regularFormSetoid K) ⟨1, fun _ => (-1 : Kˣ)⟩ *
          Quotient.mk (regularFormSetoid K) ⟨1, fun _ => a⟩ = hyperbolicClass K := by
  refine RegularFormClass.eq_hyperbolicClass_of_rank_eq_two_of_discr_eq_neg_one ?_ ?_
  · simp
  · rw [RegularFormClass.discr_add, RegularFormClass.discr_mk_rankOne_mul]
    simp only [RegularFormClass.discr_mk, RegularFormClass.rank_mk, Fin.prod_univ_one, one_nsmul]
    rw [← add_assoc, add_comm (squareClass a) (squareClass (-1 : Kˣ)), add_assoc, ← two_nsmul,
      ZModModule.char_nsmul_eq_zero 2 (squareClass a : SquareClassGroup K)]
    abel

/-- **Scaling by `-1` inverts a form modulo hyperbolic planes**: `q ⊥ (-q)` is `dim q` copies of
`ℍ`. This is what makes the Witt class of every form invertible in `W(K)` without leaving the
image of the forms. -/
theorem RegularFormClass.add_neg_one_mul (x : RegularFormClass K) :
    x + Quotient.mk (regularFormSetoid K) ⟨1, fun _ => (-1 : Kˣ)⟩ * x =
      RegularFormClass.rank x • hyperbolicClass K := by
  induction x using RegularFormClass.induction_on_rankOne with
  | zero => simp
  | add_rankOne y a ih =>
    rw [mul_add, RegularFormClass.rank_add, RegularFormClass.rank_mk, add_nsmul, one_nsmul, ← ih,
      ← RegularFormClass.mk_rankOne_add_neg_one_mul a]
    abel

/-! ### The Witt-Grothendieck ring -/

/-- **The Witt-Grothendieck ring** `GW(K)`: the Grothendieck ring of the semiring of isometry
classes of regular quadratic forms, with orthogonal sum for addition and tensor product for
multiplication. -/
def WittGrothendieckRing (K : Type u) [Field K] : Type u :=
  Algebra.GrothendieckAddGroup (RegularFormClass K)

/-- The ring structure on the Witt-Grothendieck ring induced by orthogonal sum and tensor
product. -/
noncomputable instance : CommRing (WittGrothendieckRing K) :=
  inferInstanceAs (CommRing (Algebra.GrothendieckAddGroup (RegularFormClass K)))

attribute [irreducible] WittGrothendieckRing

unseal WittGrothendieckRing in
/-- The canonical ring equivalence from the Witt-Grothendieck ring to the additive Grothendieck
group equipped with its induced multiplication. -/
noncomputable def WittGrothendieckRing.equivGrothendieck :
    WittGrothendieckRing K ≃+* Algebra.GrothendieckAddGroup (RegularFormClass K) :=
  RingEquiv.refl _

/-- The class of an isometry class of regular forms in the Witt-Grothendieck ring. -/
noncomputable def toWittGrothendieck : RegularFormClass K →+* WittGrothendieckRing K :=
  (WittGrothendieckRing.equivGrothendieck (K := K)).symm.toRingHom.comp
    Algebra.GrothendieckAddGroup.ofRingHom

/-- Witt cancellation makes the map into the Witt-Grothendieck ring injective: no information
about a regular form is lost by passing to its virtual class. -/
theorem toWittGrothendieck_injective :
    Function.Injective (toWittGrothendieck (K := K)) := by
  intro x y h
  apply Algebra.GrothendieckAddGroup.of_injective
  have := congrArg (WittGrothendieckRing.equivGrothendieck (K := K)) h
  simpa only [toWittGrothendieck, RingHom.comp_apply, RingEquiv.toRingHom_eq_coe,
    RingEquiv.coe_toRingHom, RingEquiv.apply_symm_apply,
    Algebra.GrothendieckAddGroup.ofRingHom_apply] using this

/-- The Witt–Grothendieck class map agrees with the canonical map into the underlying additive
Grothendieck group. -/
theorem toWittGrothendieck_apply (x : RegularFormClass K) :
    WittGrothendieckRing.equivGrothendieck (toWittGrothendieck x) =
      Algebra.GrothendieckAddGroup.of x := by
  rw [toWittGrothendieck, RingHom.comp_apply, RingEquiv.toRingHom_eq_coe,
    RingEquiv.coe_toRingHom, RingEquiv.apply_symm_apply]
  exact Algebra.GrothendieckAddGroup.ofRingHom_apply x

/-- Every element of the Witt-Grothendieck ring is a formal difference of two isometry
classes. -/
theorem exists_eq_sub_toWittGrothendieck (z : WittGrothendieckRing K) :
    ∃ x y : RegularFormClass K, z = toWittGrothendieck x - toWittGrothendieck y := by
  obtain ⟨x, y, hxy⟩ := Algebra.GrothendieckAddGroup.exists_eq_sub_of
    (WittGrothendieckRing.equivGrothendieck z)
  refine ⟨x, y, WittGrothendieckRing.equivGrothendieck.injective ?_⟩
  rw [map_sub, toWittGrothendieck_apply, toWittGrothendieck_apply, hxy]

/-- The rank of a virtual form, as a ring homomorphism to `ℤ`. On the class of an honest form it
is the dimension of the underlying space. -/
noncomputable def WittGrothendieckRing.rank : WittGrothendieckRing K →+* ℤ :=
  (Algebra.GrothendieckAddGroup.liftRingHom
    ((Nat.castRingHom ℤ).comp RegularFormClass.rankHom)).comp
      (WittGrothendieckRing.equivGrothendieck (K := K)).toRingHom

/-- The rank map sends the Grothendieck class of a form to its dimension. -/
@[simp]
theorem WittGrothendieckRing.rank_toWittGrothendieck (x : RegularFormClass K) :
    WittGrothendieckRing.rank (toWittGrothendieck x) = (RegularFormClass.rank x : ℤ) := by
  rw [WittGrothendieckRing.rank, RingHom.comp_apply, RingEquiv.toRingHom_eq_coe,
    RingEquiv.coe_toRingHom, toWittGrothendieck_apply,
    Algebra.GrothendieckAddGroup.liftRingHom_apply_of, RingHom.comp_apply,
    RegularFormClass.rankHom_apply, Nat.coe_castRingHom]

/-! ### The hyperbolic ideal -/

/-- The ideal of the Witt-Grothendieck ring generated by the class of the hyperbolic plane. -/
noncomputable def hyperbolicIdeal (K : Type u) [Field K] [Invertible (2 : K)] :
    Ideal (WittGrothendieckRing K) :=
  Ideal.span {toWittGrothendieck (hyperbolicClass K)}

/-- **The hyperbolic ideal is the cyclic subgroup generated by the hyperbolic plane.** An ideal
generated by a single element consists of its multiples, and multiplying `[ℍ]` by the class of a
form only produces integer multiples of `[ℍ]`, by
`EpsilonEridani.RegularFormClass.mul_hyperbolicClass`. -/
theorem mem_hyperbolicIdeal_iff {z : WittGrothendieckRing K} :
    z ∈ hyperbolicIdeal K ↔ ∃ m : ℤ, z = m • toWittGrothendieck (hyperbolicClass K) := by
  rw [hyperbolicIdeal, Ideal.mem_span_singleton']
  refine ⟨?_, ?_⟩
  · rintro ⟨y, rfl⟩
    obtain ⟨a, b, rfl⟩ := exists_eq_sub_toWittGrothendieck y
    refine ⟨(RegularFormClass.rank a : ℤ) - (RegularFormClass.rank b : ℤ), ?_⟩
    rw [sub_mul, ← map_mul, ← map_mul, RegularFormClass.mul_hyperbolicClass,
      RegularFormClass.mul_hyperbolicClass, map_nsmul, map_nsmul, sub_smul, natCast_zsmul,
      natCast_zsmul]
  · rintro ⟨m, rfl⟩
    exact ⟨(m : WittGrothendieckRing K), by rw [zsmul_eq_mul]⟩

/-! ### The Witt ring -/

/-- **The Witt ring** `W(K)`: the Witt-Grothendieck ring modulo the ideal generated by the
hyperbolic plane. -/
def WittRing (K : Type u) [Field K] [Invertible (2 : K)] : Type u :=
  WittGrothendieckRing K ⧸ hyperbolicIdeal K

/-- The quotient ring structure on the Witt ring. -/
noncomputable instance : CommRing (WittRing K) :=
  inferInstanceAs (CommRing (WittGrothendieckRing K ⧸ hyperbolicIdeal K))

attribute [irreducible] WittRing

unseal WittRing in
/-- The canonical ring equivalence from the Witt ring to the quotient by the hyperbolic ideal. -/
noncomputable def WittRing.equivQuotient :
    WittRing K ≃+* WittGrothendieckRing K ⧸ hyperbolicIdeal K :=
  RingEquiv.refl _

/-- The canonical quotient homomorphism from the Witt-Grothendieck ring to the Witt ring. -/
noncomputable def WittRing.mk : WittGrothendieckRing K →+* WittRing K :=
  (WittRing.equivQuotient (K := K)).symm.toRingHom.comp
    (Ideal.Quotient.mk (hyperbolicIdeal K))

/-- Under the quotient equivalence, `WittRing.mk` is the ordinary ideal-quotient map. -/
@[simp]
theorem WittRing.equivQuotient_mk (x : WittGrothendieckRing K) :
    WittRing.equivQuotient (WittRing.mk x) = Ideal.Quotient.mk (hyperbolicIdeal K) x := by
  rw [WittRing.mk, RingHom.comp_apply, RingEquiv.toRingHom_eq_coe, RingEquiv.coe_toRingHom,
    RingEquiv.apply_symm_apply]

/-- Two virtual forms have the same image in the Witt ring exactly when their difference belongs
to the hyperbolic ideal. -/
theorem WittRing.mk_eq_mk {x y : WittGrothendieckRing K} :
    WittRing.mk x = WittRing.mk y ↔ x - y ∈ hyperbolicIdeal K := by
  rw [← (WittRing.equivQuotient (K := K)).injective.eq_iff, WittRing.equivQuotient_mk,
    WittRing.equivQuotient_mk, Ideal.Quotient.eq]

/-- A virtual form maps to zero in the Witt ring exactly when it belongs to the hyperbolic
ideal. -/
theorem WittRing.mk_eq_zero_iff_mem {x : WittGrothendieckRing K} :
    WittRing.mk x = 0 ↔ x ∈ hyperbolicIdeal K := by
  rw [← map_zero (WittRing.mk (K := K)), WittRing.mk_eq_mk]
  simp only [sub_zero]

/-- The kernel of the canonical map to the Witt ring is the hyperbolic ideal. -/
theorem WittRing.ker_mk : RingHom.ker (WittRing.mk (K := K)) = hyperbolicIdeal K := by
  ext x
  rw [RingHom.mem_ker, WittRing.mk_eq_zero_iff_mem]

/-- The canonical map from the Witt-Grothendieck ring onto the Witt ring is surjective. -/
theorem WittRing.mk_surjective : Function.Surjective (WittRing.mk (K := K)) := by
  intro z
  obtain ⟨x, hx⟩ := Ideal.Quotient.mk_surjective (WittRing.equivQuotient z)
  refine ⟨x, WittRing.equivQuotient.injective ?_⟩
  rw [WittRing.equivQuotient_mk, hx]

/-- A ring homomorphism from the Witt-Grothendieck ring that kills the hyperbolic ideal factors
through the Witt ring. -/
noncomputable def WittRing.lift {R : Type*} [Semiring R] (f : WittGrothendieckRing K →+* R)
    (h : hyperbolicIdeal K ≤ RingHom.ker f) : WittRing K →+* R :=
  (Ideal.Quotient.lift _ f fun _ hx => RingHom.mem_ker.mp (h hx)).comp
    (WittRing.equivQuotient (K := K)).toRingHom

/-- The factorization through the Witt ring agrees with the original map after the canonical
quotient map. -/
theorem WittRing.lift_comp_mk {R : Type*} [Semiring R]
    (f : WittGrothendieckRing K →+* R) (h : hyperbolicIdeal K ≤ RingHom.ker f) :
    (WittRing.lift f h).comp WittRing.mk = f := by
  ext x
  rw [RingHom.comp_apply, WittRing.lift, RingHom.comp_apply, RingEquiv.toRingHom_eq_coe,
    RingEquiv.coe_toRingHom, WittRing.equivQuotient_mk, Ideal.Quotient.lift_mk]

/-- The Witt class of an isometry class of regular quadratic forms. -/
noncomputable def wittClass : RegularFormClass K →+* WittRing K :=
  WittRing.mk.comp toWittGrothendieck

/-- The Witt class map is the composite of the Grothendieck map and the quotient map. -/
theorem wittClass_apply (x : RegularFormClass K) :
    wittClass x = WittRing.mk (toWittGrothendieck x) := by
  rw [wittClass, RingHom.comp_apply]

/-- The hyperbolic plane has trivial Witt class. -/
@[simp]
theorem wittClass_hyperbolicClass : wittClass (hyperbolicClass K) = 0 :=
  WittRing.mk_eq_zero_iff_mem.mpr (Ideal.subset_span rfl)

-- Not `@[simp]`: `RegularFormClass K` is a semiring, so `nsmul_eq_mul` rewrites the left-hand
-- side to `wittClass (↑m * hyperbolicClass K + x)` and the tag fails `simpNF`.
/-- Adding hyperbolic planes does not change the Witt class. -/
theorem wittClass_nsmul_hyperbolicClass_add (m : ℕ) (x : RegularFormClass K) :
    wittClass (m • hyperbolicClass K + x) = wittClass x := by
  rw [map_add, map_nsmul, wittClass_hyperbolicClass, smul_zero, zero_add]

/-- **Two forms have the same Witt class exactly when they differ by hyperbolic planes.** -/
theorem wittClass_eq_iff_exists_nsmul {x y : RegularFormClass K} :
    wittClass x = wittClass y ↔
      ∃ m n : ℕ, m • hyperbolicClass K + x = n • hyperbolicClass K + y := by
  refine ⟨fun h => ?_, ?_⟩
  · rw [wittClass_apply, wittClass_apply, WittRing.mk_eq_mk,
      mem_hyperbolicIdeal_iff] at h
    obtain ⟨m, hm⟩ := h
    rcases le_or_gt 0 m with hpos | hneg
    · lift m to ℕ using hpos with k
      refine ⟨0, k, ?_⟩
      rw [zero_nsmul, zero_add]
      refine toWittGrothendieck_injective ?_
      rw [map_add, map_nsmul, ← natCast_zsmul, ← hm]
      abel
    · refine ⟨(-m).toNat, 0, ?_⟩
      rw [zero_nsmul, zero_add]
      refine toWittGrothendieck_injective ?_
      rw [map_add, map_nsmul, ← natCast_zsmul,
        Int.toNat_of_nonneg (by omega : (0 : ℤ) ≤ -m), neg_smul, ← hm]
      abel
  · rintro ⟨m, n, h⟩
    rw [← wittClass_nsmul_hyperbolicClass_add m x, h, wittClass_nsmul_hyperbolicClass_add]

/-- **The anisotropic part is the canonical representative of a Witt class**: two regular forms
have the same Witt class exactly when their anisotropic parts are isometric. -/
@[simp]
theorem wittClass_eq_iff_anisotropicPart_eq {x y : RegularFormClass K} :
    wittClass x = wittClass y ↔
      RegularFormClass.anisotropicPart x = RegularFormClass.anisotropicPart y := by
  rw [wittClass_eq_iff_exists_nsmul]
  refine ⟨?_, fun h => ⟨RegularFormClass.wittIndex y, RegularFormClass.wittIndex x, ?_⟩⟩
  · rintro ⟨m, n, h⟩
    rw [← RegularFormClass.anisotropicPart_nsmul_hyperbolicClass_add m x, h,
      RegularFormClass.anisotropicPart_nsmul_hyperbolicClass_add]
  · conv_lhs => rw [RegularFormClass.wittDecomposition x]
    conv_rhs => rw [RegularFormClass.wittDecomposition y]
    rw [← add_assoc, ← add_assoc, ← add_nsmul, ← add_nsmul, Nat.add_comm, h]

/-- A form and its anisotropic part have the same Witt class. -/
@[simp]
theorem wittClass_anisotropicPart (x : RegularFormClass K) :
    wittClass (RegularFormClass.anisotropicPart x) = wittClass x :=
  wittClass_eq_iff_anisotropicPart_eq.mpr
    (RegularFormClass.anisotropicPart_eq_self (RegularFormClass.anisotropic_anisotropicPart x))

/-- **Anisotropic forms are separated by their Witt classes**: this is Witt's theorem that the
anisotropic part is a complete invariant. -/
theorem eq_of_anisotropic_of_anisotropic_of_wittClass_eq {x y : RegularFormClass K}
    (hx : RegularFormClass.Anisotropic x) (hy : RegularFormClass.Anisotropic y)
    (h : wittClass x = wittClass y) : x = y := by
  rw [← RegularFormClass.anisotropicPart_eq_self hx, ← RegularFormClass.anisotropicPart_eq_self hy]
  exact wittClass_eq_iff_anisotropicPart_eq.mp h

/-- A form has trivial Witt class exactly when it is a sum of hyperbolic planes. -/
@[simp]
theorem wittClass_eq_zero_iff {x : RegularFormClass K} :
    wittClass x = 0 ↔ RegularFormClass.anisotropicPart x = 0 := by
  rw [← map_zero (wittClass (K := K)), wittClass_eq_iff_anisotropicPart_eq,
    RegularFormClass.anisotropicPart_eq_self RegularFormClass.anisotropic_zero]

/-- **Every element of the Witt ring is the Witt class of a form.** The inverse of the class of
`q` is the class of `-q`, by `EpsilonEridani.RegularFormClass.add_neg_one_mul`. -/
theorem wittClass_surjective : Function.Surjective (wittClass (K := K)) := by
  intro z
  obtain ⟨w, rfl⟩ := WittRing.mk_surjective z
  obtain ⟨x, y, hxy⟩ := exists_eq_sub_toWittGrothendieck w
  refine ⟨x + Quotient.mk (regularFormSetoid K) ⟨1, fun _ => (-1 : Kˣ)⟩ * y, ?_⟩
  have hy : wittClass (Quotient.mk (regularFormSetoid K) ⟨1, fun _ => (-1 : Kˣ)⟩ * y) =
      -wittClass y := by
    rw [eq_neg_iff_add_eq_zero, add_comm, ← map_add, RegularFormClass.add_neg_one_mul, map_nsmul,
      wittClass_hyperbolicClass, smul_zero]
  rw [map_add, hy, wittClass_apply, wittClass_apply, ← sub_eq_add_neg, ← map_sub, ← hxy]

/-! ### The dimension map -/

/-- **The dimension map** `W(K) → ZMod 2`: the rank of a form modulo two, which is well defined
on Witt classes because a hyperbolic plane has rank two. -/
noncomputable def WittRing.dimMod2 : WittRing K →+* ZMod 2 :=
  WittRing.lift ((Int.castRingHom (ZMod 2)).comp WittGrothendieckRing.rank) <| by
      intro z hz
      rw [RingHom.mem_ker]
      obtain ⟨m, rfl⟩ := mem_hyperbolicIdeal_iff.mp hz
      rw [RingHom.comp_apply, map_zsmul, WittGrothendieckRing.rank_toWittGrothendieck,
        rank_hyperbolicClass, map_zsmul, eq_intCast]
      rw [zsmul_eq_mul, ← Int.cast_mul, ZMod.intCast_zmod_eq_zero_iff_dvd]
      exact ⟨m, by ring⟩

/-- The mod-two dimension of the Witt class of a form is its rank modulo two. -/
@[simp]
theorem WittRing.dimMod2_wittClass (x : RegularFormClass K) :
    WittRing.dimMod2 (wittClass x) = (RegularFormClass.rank x : ZMod 2) := by
  rw [WittRing.dimMod2, wittClass_apply, ← RingHom.comp_apply,
    WittRing.lift_comp_mk, RingHom.comp_apply,
    WittGrothendieckRing.rank_toWittGrothendieck, eq_intCast, Int.cast_natCast]

end EpsilonEridani
