/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.MonoidAlgebra.Lift
public import Mathlib.Algebra.MonoidAlgebra.MapDomain
public import Mathlib.RingTheory.Ideal.Maps

/-!
# Exactness for monoid algebras

The coefficient-sum augmentation ideal of a monoid algebra is generated by the basis
differences `single k 1 - 1`. More generally, a homomorphism from a group to a monoid induces a
monoid-algebra map whose kernel is generated by the corresponding differences for elements in the
kernel of the homomorphism.

These descriptions give the ideal-theoretic exactness of monoid algebras associated to an exact
pair of monoid homomorphisms whose middle object is a group. They provide the algebraic input for
transporting exact character sequences contravariantly to coordinate rings of diagonalizable
groups.

## Main declarations

* `EpsilonEridani.MonoidAlgebra.augmentation`: the coefficient-sum augmentation.
* `EpsilonEridani.MonoidAlgebra.ker_augmentation_eq_span`: its kernel is generated by basis
  differences.
* `EpsilonEridani.MonoidAlgebra.ker_mapDomainRingHom_eq_span`: the analogous kernel description for a
  homomorphism out of a group.
* `EpsilonEridani.MonoidAlgebra.map_ker_augmentation_eq_ker_mapDomainRingHom`: the resulting exactness
  statement for ideals.

## References

Milne, *Algebraic Groups*, Theorem 12.9(b), gives the corresponding augmentation and quotient
description for group algebras of finitely generated commutative groups over a field. The proofs
here use finite support directly and apply to arbitrary coefficient rings and the indicated
possibly noncommutative monoids.
-/

public section

namespace EpsilonEridani

universe u v w x

namespace MonoidAlgebra

variable (R : Type u) [Ring R]

/-- The coefficient-sum augmentation of a monoid algebra. It sends every standard basis element
to `1` and acts identically on coefficients. -/
noncomputable def augmentation (K : Type v) [Monoid K] : _root_.MonoidAlgebra R K →+* R :=
  _root_.MonoidAlgebra.liftNCRingHom (.id R) 1 fun _ _ ↦ Commute.one_right _

/-- The coefficient-sum augmentation sends a singleton to its coefficient. -/
@[simp]
theorem augmentation_single {K : Type v} [Monoid K] (k : K) (r : R) :
    augmentation R K (_root_.MonoidAlgebra.single k r) = r := by
  simp [augmentation]

/-- The coefficient-sum augmentation is natural with respect to homomorphisms of monoids. -/
@[simp]
theorem augmentation_comp_mapDomainRingHom {M : Type v} {N : Type w} [Monoid M] [Monoid N]
    (f : M →* N) :
    (augmentation R N).comp (_root_.MonoidAlgebra.mapDomainRingHom R f) = augmentation R M := by
  apply _root_.MonoidAlgebra.ringHom_ext <;> intro <;> simp

private theorem mapDomain_basisDifference {M : Type v} {N : Type w} [Monoid M] [Monoid N]
    (f : M →* N) (m : M) :
    (_root_.MonoidAlgebra.mapDomainRingHom R f)
        (_root_.MonoidAlgebra.single m (1 : R) - 1) =
      _root_.MonoidAlgebra.single (f m) (1 : R) - 1 := by
  calc
    _root_.MonoidAlgebra.mapDomain f
        (_root_.MonoidAlgebra.single m (1 : R) - 1) =
        _root_.MonoidAlgebra.mapDomain f
            (_root_.MonoidAlgebra.single m (1 : R)) -
          _root_.MonoidAlgebra.mapDomain f 1 :=
      (_root_.MonoidAlgebra.mapDomainRingHom R f).map_sub _ _
    _ = _root_.MonoidAlgebra.single (f m) (1 : R) - 1 := by simp

/-- The kernel of the coefficient-sum augmentation is generated by the differences between
standard basis elements and the unit basis element. -/
theorem ker_augmentation_eq_span (K : Type v) [Monoid K] :
    RingHom.ker (augmentation R K) =
      Ideal.span (Set.range fun k : K ↦
        _root_.MonoidAlgebra.single k (1 : R) - 1) := by
  apply le_antisymm
  · intro x hx
    have hdiff :
        x - _root_.MonoidAlgebra.single 1 (augmentation R K x) ∈
          Ideal.span (Set.range fun k : K ↦
            _root_.MonoidAlgebra.single k (1 : R) - 1) := by
      clear hx
      induction x using _root_.MonoidAlgebra.induction_linear with
      | zero => simp
      | add x y hx hy =>
          simpa only [map_add, _root_.MonoidAlgebra.single_add, add_sub_add_comm] using
            Ideal.add_mem _ hx hy
      | single k r =>
          have hgen : _root_.MonoidAlgebra.single k (1 : R) - 1 ∈
              Ideal.span (Set.range fun k : K ↦
                _root_.MonoidAlgebra.single k (1 : R) - 1) :=
            Ideal.subset_span ⟨k, rfl⟩
          have hmul := Ideal.mul_mem_left _ (_root_.MonoidAlgebra.single 1 r) hgen
          simpa only [augmentation_single, mul_sub, _root_.MonoidAlgebra.single_mul_single,
            one_mul, mul_one, _root_.MonoidAlgebra.one_def] using hmul
    simpa [RingHom.mem_ker.mp hx] using hdiff
  · rw [Ideal.span_le]
    rintro _ ⟨k, rfl⟩
    apply RingHom.mem_ker.mpr
    simp

/-- If `q : G → H` is a surjective homomorphism from a group to a monoid, the kernel of the
induced monoid-algebra map is generated by the basis differences indexed by `ker q`. -/
private theorem ker_mapDomainRingHom_eq_span_of_surjective
    {G : Type v} {H : Type w} [Group G] [Monoid H]
    (q : G →* H) (hq : Function.Surjective q) :
    RingHom.ker (_root_.MonoidAlgebra.mapDomainRingHom R q) =
      Ideal.span (Set.range fun k : q.ker ↦
        _root_.MonoidAlgebra.single (k : G) (1 : R) - 1) := by
  apply le_antisymm
  · intro x hx
    let s : H → G := Function.surjInv hq
    have hs : Function.RightInverse s q := Function.rightInverse_surjInv hq
    have hdiff :
        x - _root_.MonoidAlgebra.mapDomain s (_root_.MonoidAlgebra.mapDomain q x) ∈
          Ideal.span (Set.range fun k : q.ker ↦
            _root_.MonoidAlgebra.single (k : G) (1 : R) - 1) := by
      clear hx
      induction x using _root_.MonoidAlgebra.induction_linear with
      | zero => simp
      | add x y hx hy =>
          simpa only [_root_.MonoidAlgebra.mapDomain_add, add_sub_add_comm] using
            Ideal.add_mem _ hx hy
      | single g r =>
          let k : q.ker := ⟨(s (q g))⁻¹ * g, by
            rw [MonoidHom.mem_ker]
            calc
              q ((s (q g))⁻¹ * g) = q ((s (q g))⁻¹) * q g := map_mul q _ _
              _ = q ((s (q g))⁻¹) * q (s (q g)) :=
                congrArg (q ((s (q g))⁻¹) * ·) (hs (q g)).symm
              _ = q ((s (q g))⁻¹ * s (q g)) := (map_mul q _ _).symm
              _ = 1 := by simp⟩
          have hgen : _root_.MonoidAlgebra.single (k : G) (1 : R) - 1 ∈
              Ideal.span (Set.range fun k : q.ker ↦
                _root_.MonoidAlgebra.single (k : G) (1 : R) - 1) :=
            Ideal.subset_span ⟨k, rfl⟩
          have hmul := Ideal.mul_mem_left _ (_root_.MonoidAlgebra.single (s (q g)) r) hgen
          simpa only [_root_.MonoidAlgebra.mapDomain_single, mul_sub,
            _root_.MonoidAlgebra.single_mul_single, mul_one, one_mul,
            _root_.MonoidAlgebra.one_def, k, mul_inv_cancel_left] using hmul
    have hx' : _root_.MonoidAlgebra.mapDomain q x = 0 := RingHom.mem_ker.mp hx
    simpa [hx'] using hdiff
  · rw [Ideal.span_le]
    rintro _ ⟨k, rfl⟩
    apply RingHom.mem_ker.mpr
    rw [mapDomain_basisDifference R q, MonoidHom.mem_ker.mp k.property,
      ← _root_.MonoidAlgebra.one_def, sub_self]

/-- If `q : G → H` is a homomorphism from a group to a monoid, the kernel of the induced
monoid-algebra map is generated by the basis differences indexed by `ker q`. -/
theorem ker_mapDomainRingHom_eq_span {G : Type v} {H : Type w} [Group G] [Monoid H]
    (q : G →* H) :
    RingHom.ker (_root_.MonoidAlgebra.mapDomainRingHom R q) =
      Ideal.span (Set.range fun k : q.ker ↦
        _root_.MonoidAlgebra.single (k : G) (1 : R) - 1) := by
  let q' := q.mrangeRestrict
  let i : MonoidHom.mrange q →* H := (MonoidHom.mrange q).subtype
  have hker : q'.ker = q.ker := by
    apply Subgroup.toSubmonoid_injective
    exact MonoidHom.mrangeRestrict_mker q
  calc
    RingHom.ker (_root_.MonoidAlgebra.mapDomainRingHom R q) =
        RingHom.ker ((_root_.MonoidAlgebra.mapDomainRingHom R i).comp
          (_root_.MonoidAlgebra.mapDomainRingHom R q')) := by
      rw [← _root_.MonoidAlgebra.mapDomainRingHom_comp]
      congr 2
    _ = RingHom.ker (_root_.MonoidAlgebra.mapDomainRingHom R q') :=
      RingHom.ker_comp_of_injective _
        (_root_.MonoidAlgebra.mapDomain_injective Subtype.val_injective)
    _ = Ideal.span (Set.range fun k : q.ker ↦
        _root_.MonoidAlgebra.single (k : G) (1 : R) - 1) := by
      have h := ker_mapDomainRingHom_eq_span_of_surjective R q'
        q.mrangeRestrict_surjective
      rw [hker] at h
      exact h

/-- An exact pair of monoid homomorphisms whose middle object is a group induces an exact ideal
sequence on monoid algebras: the extension of the first augmentation ideal is the kernel of the
second induced map. -/
theorem map_ker_augmentation_eq_ker_mapDomainRingHom {L : Type v} {G : Type w}
    {H : Type x} [Monoid L] [Group G] [Monoid H] (p : L →* G) (q : G →* H)
    (hexact : MonoidHom.mrange p = MonoidHom.mker q) :
    Ideal.map (_root_.MonoidAlgebra.mapDomainRingHom R p)
        (RingHom.ker (augmentation R L)) =
      RingHom.ker (_root_.MonoidAlgebra.mapDomainRingHom R q) := by
  rw [ker_augmentation_eq_span, Ideal.map_span, ker_mapDomainRingHom_eq_span R q]
  congr 1
  ext z
  constructor
  · rintro ⟨_, ⟨l, rfl⟩, rfl⟩
    have hl : p l ∈ q.ker := by
      apply MonoidHom.mem_ker.mpr
      have : p l ∈ MonoidHom.mker q := by
        rw [← hexact]
        exact MonoidHom.mem_mrange.mpr ⟨l, rfl⟩
      exact MonoidHom.mem_mker.mp this
    refine ⟨⟨p l, hl⟩, ?_⟩
    symm
    exact mapDomain_basisDifference R p l
  · rintro ⟨k, rfl⟩
    have hk : (k : G) ∈ MonoidHom.mrange p := by
      rw [hexact]
      exact MonoidHom.mem_mker.mpr (MonoidHom.mem_ker.mp k.property)
    obtain ⟨l, hl⟩ := MonoidHom.mem_mrange.mp hk
    refine ⟨_root_.MonoidAlgebra.single l (1 : R) - 1, ⟨l, rfl⟩, ?_⟩
    rw [mapDomain_basisDifference R p, hl]

end MonoidAlgebra

end EpsilonEridani
