/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.RepresentationTheory.Symmetric.Specht.Ideal.Idempotent

/-!
# The Specht ideals of the one-row and the one-column shape

The two extreme shapes of a partition of `n` are the single row `(n)` and the single column
`(1ⁿ)`, and their Specht modules are the two representations of `Sₙ` that are visible without any
representation theory: the trivial one and the sign one.  This file proves that for the left-ideal
presentation `ℚ[Sₙ] c_t` of the Specht module.  Both are lines, so both are irreducible, but that
is a special case of `EpsilonEridani.YoungTableau.isIrreducible_spechtIdealRep` in
`EpsilonEridani.RepresentationTheory.Symmetric.Specht.Ideal.Irreducible`, which holds for every shape, and
is not restated here.

The shape hypotheses are stated on the row and column groups rather than on the diagram, because
that is the form the symmetrizer identities consume: `rowSubgroup t = ⊤` says that all the labels
share a row, and `colSubgroup t = ⊤` says that all of them share a column.  Each is supplied by a
diagram-level criterion, `YoungTableau.rowSubgroup_eq_top_iff` and
`YoungTableau.colSubgroup_eq_top_iff` in
`EpsilonEridani.RepresentationTheory.Symmetric.RowColumnSubgroup`, which say that the two hypotheses hold
exactly for the shapes intended: a diagram has at most one row exactly when its zeroth column has
length at most one, and dually.  The two hypotheses are compatible rather than exclusive -- the
empty diagram satisfies both, and there `Sₙ` is trivial and so are the sign and the trivial
representation.

The two eigenvector identities `YoungTableau.single_mul_youngSymmetrizer_of_rowSubgroup_eq_top`
and `..._of_colSubgroup_eq_top` are in
`EpsilonEridani.RepresentationTheory.Symmetric.Symmetrizer`: for a shape with at most one row the column
antisymmetrizer is `1`, so `c_t` is the sum of the whole group and every group element fixes it;
for a shape with at most one column the row symmetrizer is `1`, so `c_t` is the signed sum of the
whole group and every group element scales it by its sign.  What is left for this file is that
either way `c_t` spans a `ℚ`-line inside `ℚ[Sₙ]`, which is therefore the whole left ideal it
generates, and that the action on that line is the character in question.

Only the ideal presentation `ℚ[Sₙ] c_t` of the Specht module is available here, so that is what
these results are about; the identification of `S^λ` with the span of the polytabloids inside the
Young permutation module is a separate milestone and is not used or claimed.  The corresponding
statements one level down, that the permutation module `M^{(n)}` is the trivial representation and
`M^{(1ⁿ)}` the regular one, are in
`EpsilonEridani.RepresentationTheory.Symmetric.PermutationModule.Extremes`.

## Main results

* `YoungTableau.spechtIdealRep_ρ_eq_trivial`: the one-row Specht ideal is the trivial
  representation.
* `YoungTableau.spechtIdealRep_ρ_apply_of_colSubgroup_eq_top`: the one-column Specht ideal is the
  sign representation.
* `YoungTableau.finrank_spechtIdeal_of_rowSubgroup_eq_top` and
  `YoungTableau.finrank_spechtIdeal_of_colSubgroup_eq_top`: both are lines.
* `YoungTableau.youngSymmetrizer_sq_of_rowSubgroup_eq_top` and
  `YoungTableau.youngSymmetrizer_sq_of_colSubgroup_eq_top`: because both are lines, the scalar in
  the essential idempotence of `c_t` is the full `n!`.

## References

* [W. Fulton, *Young Tableaux*][fulton1997], Section 7.2.
* [Schur--Weyl roadmap](https://github.com/EpsilonEridaniProject/EpsilonEridaniRoadmap/blob/main/EpsilonEridaniRoadmap/RepresentationTheory/SchurWeyl/README.md),
  Layer 4, "the named small irreducibles".
-/

public section

namespace EpsilonEridani

namespace YoungTableau

variable {μ : YoungDiagram}

/-! ### The left ideal generated by an eigenvector of the group -/

variable {χ : Equiv.Perm (Fin μ.card) → ℚ}

/-- If every group element multiplies the Young symmetrizer by a scalar, then the left ideal it
generates is already the `ℚ`-line through it: the whole group algebra acts through the scalars. -/
private theorem restrictScalars_spechtIdeal_eq_span (t : YoungTableau μ)
    (h : ∀ g, MonoidAlgebra.single g (1 : ℚ) * youngSymmetrizer t = χ g • youngSymmetrizer t) :
    (spechtIdeal t).restrictScalars ℚ = ℚ ∙ youngSymmetrizer t := by
  refine le_antisymm (fun x hx => ?_) ?_
  · rw [Submodule.restrictScalars_mem] at hx
    obtain ⟨a, rfl⟩ := (mem_spechtIdeal_iff t x).mp hx
    clear hx
    induction a using MonoidAlgebra.induction_linear with
    | zero => rw [zero_mul]; exact Submodule.zero_mem _
    | add p q hp hq => rw [add_mul]; exact Submodule.add_mem _ hp hq
    | single g r =>
      have hr : MonoidAlgebra.single g r = r • MonoidAlgebra.single g (1 : ℚ) := by
        rw [MonoidAlgebra.smul_single', mul_one]
      rw [hr, smul_mul_assoc, h g, smul_smul]
      exact Submodule.smul_mem _ _ (Submodule.mem_span_singleton_self _)
  · rw [Submodule.span_le, Set.singleton_subset_iff]
    exact youngSymmetrizer_mem_spechtIdeal t

/-- A Young symmetrizer scaled by the group generates a one-dimensional left ideal. -/
private theorem finrank_spechtIdeal_eq_one (t : YoungTableau μ)
    (h : ∀ g, MonoidAlgebra.single g (1 : ℚ) * youngSymmetrizer t = χ g • youngSymmetrizer t) :
    Module.finrank ℚ (spechtIdeal t) = 1 := by
  have hline : Module.finrank ℚ ((spechtIdeal t).restrictScalars ℚ) = 1 := by
    rw [restrictScalars_spechtIdeal_eq_span t h]
    exact finrank_span_singleton (youngSymmetrizer_ne_zero t)
  rwa [LinearEquiv.finrank_eq
    (LinearEquiv.restrictScalars ℚ (Submodule.restrictScalarsEquiv ℚ _ _ (spechtIdeal t)))] at hline

/-- A Young symmetrizer scaled by the group spans its left ideal, so the group acts on that ideal
through the same scalars. -/
private theorem spechtIdealRep_ρ_apply (t : YoungTableau μ)
    (h : ∀ g, MonoidAlgebra.single g (1 : ℚ) * youngSymmetrizer t = χ g • youngSymmetrizer t)
    (g : Equiv.Perm (Fin μ.card)) (x : spechtIdeal t) :
    (spechtIdealRep t).ρ g x = χ g • x := by
  have hx : (x : MonoidAlgebra ℚ (Equiv.Perm (Fin μ.card))) ∈ ℚ ∙ youngSymmetrizer t := by
    rw [← restrictScalars_spechtIdeal_eq_span t h, Submodule.restrictScalars_mem]
    exact x.2
  obtain ⟨c, hc⟩ := Submodule.mem_span_singleton.mp hx
  refine Subtype.ext ?_
  calc ((spechtIdealRep t).ρ g x : MonoidAlgebra ℚ (Equiv.Perm (Fin μ.card)))
      = MonoidAlgebra.single g (1 : ℚ) * (c • youngSymmetrizer t) := by
        rw [spechtIdealRep_ρ_apply_coe, hc]
    _ = c • (χ g • youngSymmetrizer t) := by rw [mul_smul_comm, h g]
    _ = χ g • (c • youngSymmetrizer t) := smul_comm c (χ g) _
    _ = ((χ g • x : spechtIdeal t) : MonoidAlgebra ℚ (Equiv.Perm (Fin μ.card))) := by
        rw [hc, Submodule.coe_smul_of_tower]

/-! ### The one-row shape gives the trivial representation -/

/-- The Specht ideal of a shape with at most one row is a line. -/
theorem finrank_spechtIdeal_of_rowSubgroup_eq_top (t : YoungTableau μ)
    (h : rowSubgroup t = ⊤) : Module.finrank ℚ (spechtIdeal t) = 1 :=
  finrank_spechtIdeal_eq_one (χ := fun _ => 1) t fun g => by
    rw [one_smul]
    exact single_mul_youngSymmetrizer_of_rowSubgroup_eq_top t h g

/-- The symmetric group fixes the Specht ideal of a shape with at most one row pointwise. -/
theorem spechtIdealRep_ρ_apply_of_rowSubgroup_eq_top (t : YoungTableau μ)
    (h : rowSubgroup t = ⊤) (g : Equiv.Perm (Fin μ.card)) (x : spechtIdeal t) :
    (spechtIdealRep t).ρ g x = x := by
  refine (spechtIdealRep_ρ_apply (χ := fun _ => 1) t (fun g => ?_) g x).trans (one_smul ℚ x)
  rw [one_smul]
  exact single_mul_youngSymmetrizer_of_rowSubgroup_eq_top t h g

/-- **`S^{(n)}` is the trivial representation**: on a shape with at most one row the Specht ideal
`ℚ[Sₙ] c_t` carries the trivial action of `Sₙ`.  Together with
`YoungTableau.finrank_spechtIdeal_of_rowSubgroup_eq_top` this identifies it as the one-dimensional
trivial representation. -/
theorem spechtIdealRep_ρ_eq_trivial (t : YoungTableau μ) (h : rowSubgroup t = ⊤) :
    (spechtIdealRep t).ρ =
      Representation.trivial ℚ (Equiv.Perm (Fin μ.card)) (spechtIdeal t) := by
  refine DFunLike.ext _ _ fun g => LinearMap.ext fun x => ?_
  rw [spechtIdealRep_ρ_apply_of_rowSubgroup_eq_top t h, Representation.trivial_apply]

/-! ### The one-column shape gives the sign representation -/

/-- The Specht ideal of a shape with at most one column is a line. -/
theorem finrank_spechtIdeal_of_colSubgroup_eq_top (t : YoungTableau μ)
    (h : colSubgroup t = ⊤) : Module.finrank ℚ (spechtIdeal t) = 1 :=
  finrank_spechtIdeal_eq_one (χ := fun g => ((Equiv.Perm.sign g : ℤ) : ℚ)) t
    (single_mul_youngSymmetrizer_of_colSubgroup_eq_top t h)

/-- **`S^{(1ⁿ)}` is the sign representation**: on a shape with at most one column the symmetric
group acts on the Specht ideal `ℚ[Sₙ] c_t` through the sign character.  Together with
`YoungTableau.finrank_spechtIdeal_of_colSubgroup_eq_top` this identifies it as the
one-dimensional sign representation. -/
theorem spechtIdealRep_ρ_apply_of_colSubgroup_eq_top (t : YoungTableau μ)
    (h : colSubgroup t = ⊤) (g : Equiv.Perm (Fin μ.card)) (x : spechtIdeal t) :
    (spechtIdealRep t).ρ g x = ((Equiv.Perm.sign g : ℤ) : ℚ) • x :=
  spechtIdealRep_ρ_apply (χ := fun g => ((Equiv.Perm.sign g : ℤ) : ℚ)) t
    (single_mul_youngSymmetrizer_of_colSubgroup_eq_top t h) g x

/-! ### The essential idempotence on the extreme shapes

On both extreme shapes the left ideal is a line, so the scalar in
`EpsilonEridani.YoungTableau.youngSymmetrizer_sq` is the full `n!`. These are the two cases in which it
can be read off directly, and they check the normalisation. -/

/-- On a shape with at most one row the square of the Young symmetrizer is `n!` times itself. -/
theorem youngSymmetrizer_sq_of_rowSubgroup_eq_top (t : YoungTableau μ)
    (h : rowSubgroup t = ⊤) :
    youngSymmetrizer t * youngSymmetrizer t = (μ.card.factorial : ℚ) • youngSymmetrizer t := by
  rw [youngSymmetrizer_sq t, finrank_spechtIdeal_of_rowSubgroup_eq_top t h,
    Nat.cast_one, div_one]

/-- On a shape with at most one column the square of the Young symmetrizer is `n!` times
itself. -/
theorem youngSymmetrizer_sq_of_colSubgroup_eq_top (t : YoungTableau μ)
    (h : colSubgroup t = ⊤) :
    youngSymmetrizer t * youngSymmetrizer t = (μ.card.factorial : ℚ) • youngSymmetrizer t := by
  rw [youngSymmetrizer_sq t, finrank_spechtIdeal_of_colSubgroup_eq_top t h,
    Nat.cast_one, div_one]

end YoungTableau

end EpsilonEridani
