/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.Algebra.MonoidAlgebra.Trace
public import EpsilonEridani.LinearAlgebra.Trace.Idempotent
public import EpsilonEridani.RepresentationTheory.Symmetric.Factorization
public import EpsilonEridani.RepresentationTheory.Symmetric.Specht.Ideal.Basic

/-!
# Essential idempotence of the Young symmetrizer

The Young symmetrizer `c_t` of a tableau `t` of shape `μ` satisfies `c_t * c_t = κ • c_t` for some
rational `κ`; that much is the sandwich lemma
`EpsilonEridani.YoungTableau.exists_eq_smul_youngSymmetrizer_sq`, which leaves `κ` unidentified. This
file identifies it:
```
c_t * c_t = (n! / dim ℚ[Sₙ] c_t) • c_t.
```

The proof is the classical trace computation. Right multiplication by `c_t` is a `ℚ`-linear
endomorphism `φ` of `ℚ[Sₙ]` whose range is exactly the left ideal `ℚ[Sₙ] c_t`, and the identity
`c_t * c_t = κ • c_t` says `φ * φ = κ • φ`. Such a `φ` is a scaled projection onto its range, so
its trace is `κ · dim (ℚ[Sₙ] c_t)` (`EpsilonEridani.LinearMap.trace_eq_mul_finrank_range`). On the other
hand the matrix of `φ` in the basis of permutations has every diagonal entry equal to the
coefficient of `c_t` at the identity, which is `1`, so the trace is `n!`
(`EpsilonEridani.MonoidAlgebra.trace_mulRight`). Comparing gives `κ · dim = n!`, and the dimension is
positive.

The roadmap states the scalar as `n! / f^μ` with `f^μ` the number of standard Young tableaux of
shape `μ`. The two readings agree once the standard basis theorem identifies `dim S^μ = f^μ`; that
identification needs the straightening algorithm and is not proved here, so the dimension of the
ideal is what appears below. Nothing in this file assumes the comparison of `ℚ[Sₙ] c_t` with the
polytabloid presentation of `S^μ`.

The two extreme shapes are the cases in which the dimension, and hence the scalar, can be read off
directly; those evaluations live with the rest of the extreme-shape theory, in
`EpsilonEridani.RepresentationTheory.Symmetric.Specht.Ideal.Extremes`, which is downstream of this file.

## Main statements

* `EpsilonEridani.YoungTableau.range_mulRight_youngSymmetrizer`: right multiplication by `c_t` has the
  left ideal `ℚ[Sₙ] c_t` as its range.
* `EpsilonEridani.YoungTableau.finrank_spechtIdeal_smul_youngSymmetrizer_sq`: the division-free
  form `dim • (c_t * c_t) = n! • c_t`.
* `EpsilonEridani.YoungTableau.youngSymmetrizer_sq`: **essential idempotence**,
  `c_t * c_t = (n! / dim) • c_t`.
* `EpsilonEridani.YoungTableau.isIdempotentElem_smul_youngSymmetrizer`: the normalisation
  `(dim / n!) • c_t` is idempotent.

## Implementation notes

None of the identities below is a `simp` lemma. Their right-hand sides carry a dimension that no
other lemma consumes, and rewriting `c_t * c_t` into a scaled `c_t` replaces a product that later
`simp` sets do reduce (through `EpsilonEridani.YoungTableau.mul_youngSymmetrizer_left` and its
companions) by an opaque scalar.

## References

* W. Fulton and J. Harris, *Representation Theory: A First Course* (1991), Lemma 4.26.
* [Schur--Weyl roadmap](https://github.com/EpsilonEridaniProject/EpsilonEridaniRoadmap/blob/main/EpsilonEridaniRoadmap/RepresentationTheory/SchurWeyl/README.md),
  Layer 2, the “idempotent theory” item `c_t * c_t = (n! / f^λ) • c_t`.
-/

public section

namespace EpsilonEridani

namespace YoungTableau

variable {μ : YoungDiagram}

open Module

/-- **The left ideal generated by `c_t` is the range of right multiplication by `c_t`.** This is
the `ℚ`-linear description of `ℚ[Sₙ] c_t` that the trace computation needs. -/
theorem range_mulRight_youngSymmetrizer (t : YoungTableau μ) :
    LinearMap.range (LinearMap.mulRight ℚ (youngSymmetrizer t)) =
      (spechtIdeal t).restrictScalars ℚ := by
  ext x
  simp only [LinearMap.mem_range, LinearMap.mulRight_apply, Submodule.restrictScalars_mem,
    mem_spechtIdeal_iff]

/-- Right multiplication by `c_t` has the same square-to-scalar behaviour as `c_t` itself. -/
private theorem mulRight_youngSymmetrizer_sq (t : YoungTableau μ) {κ : ℚ}
    (hκ : youngSymmetrizer t * youngSymmetrizer t = κ • youngSymmetrizer t) :
    LinearMap.mulRight ℚ (youngSymmetrizer t) * LinearMap.mulRight ℚ (youngSymmetrizer t) =
      κ • LinearMap.mulRight ℚ (youngSymmetrizer t) := by
  rw [Module.End.mul_eq_comp, ← LinearMap.mulRight_mul, hκ]
  exact LinearMap.ext fun y => mul_smul_comm _ _ _

/-- The trace of right multiplication by `c_t` on `ℚ[Sₙ]` is `n!`: every diagonal entry of its
matrix in the basis of permutations is the coefficient of `c_t` at the identity, which is `1`. -/
theorem trace_mulRight_youngSymmetrizer (t : YoungTableau μ) :
    LinearMap.trace ℚ (MonoidAlgebra ℚ (Equiv.Perm (Fin μ.card)))
        (LinearMap.mulRight ℚ (youngSymmetrizer t)) = (μ.card.factorial : ℚ) := by
  rw [MonoidAlgebra.trace_mulRight, youngSymmetrizer_coeff_one, mul_one,
    Nat.card_eq_fintype_card, Fintype.card_perm, Fintype.card_fin]

/-- **The essential idempotence of the Young symmetrizer, division-free.** The dimension of the
left ideal `ℚ[Sₙ] c_t` times the square of `c_t` is `n!` times `c_t`. -/
theorem finrank_spechtIdeal_smul_youngSymmetrizer_sq (t : YoungTableau μ) :
    (finrank ℚ (spechtIdeal t) : ℚ) • (youngSymmetrizer t * youngSymmetrizer t) =
      (μ.card.factorial : ℚ) • youngSymmetrizer t := by
  obtain ⟨κ, hκ⟩ := exists_eq_smul_youngSymmetrizer_sq t
  have hdim : κ * (finrank ℚ (spechtIdeal t) : ℚ) = (μ.card.factorial : ℚ) := by
    -- Reading the left ideal as a `ℚ`-submodule does not change its dimension: the two are the
    -- same `ℚ`-module, `Submodule.restrictScalarsEquiv` being the identity map.
    have hres : finrank ℚ ((spechtIdeal t).restrictScalars ℚ) = finrank ℚ (spechtIdeal t) :=
      ((Submodule.restrictScalarsEquiv ℚ _ _ (spechtIdeal t)).restrictScalars ℚ).finrank_eq
    rw [← trace_mulRight_youngSymmetrizer t,
      LinearMap.trace_eq_mul_finrank_range (mulRight_youngSymmetrizer_sq t hκ),
      range_mulRight_youngSymmetrizer, hres]
  rw [hκ, smul_smul, ← hdim, mul_comm]

/-- **Essential idempotence of the Young symmetrizer.** The square of `c_t` is `c_t` scaled by
`n!` over the dimension of the left ideal `ℚ[Sₙ] c_t`.

The roadmap writes the scalar as `n! / f^μ`, with `f^μ` the number of standard Young tableaux of
shape `μ`; the two agree once the standard basis theorem gives `dim S^μ = f^μ`, which is not
available yet. -/
theorem youngSymmetrizer_sq (t : YoungTableau μ) :
    youngSymmetrizer t * youngSymmetrizer t =
      ((μ.card.factorial : ℚ) / (finrank ℚ (spechtIdeal t) : ℚ)) • youngSymmetrizer t := by
  have hpos : (0 : ℚ) < (finrank ℚ (spechtIdeal t) : ℚ) := by
    exact_mod_cast finrank_spechtIdeal_pos t
  calc youngSymmetrizer t * youngSymmetrizer t
      = ((finrank ℚ (spechtIdeal t) : ℚ))⁻¹ • ((finrank ℚ (spechtIdeal t) : ℚ) •
          (youngSymmetrizer t * youngSymmetrizer t)) := by
        rw [smul_smul, inv_mul_cancel₀ hpos.ne', one_smul]
    _ = ((finrank ℚ (spechtIdeal t) : ℚ))⁻¹ • ((μ.card.factorial : ℚ) • youngSymmetrizer t) := by
        rw [finrank_spechtIdeal_smul_youngSymmetrizer_sq t]
    _ = ((μ.card.factorial : ℚ) / (finrank ℚ (spechtIdeal t) : ℚ)) • youngSymmetrizer t := by
        rw [smul_smul, div_eq_inv_mul]

/-- The square of a Young symmetrizer is nonzero: the scalar `n! / dim` is positive and `c_t`
itself is nonzero. -/
theorem youngSymmetrizer_sq_ne_zero (t : YoungTableau μ) :
    youngSymmetrizer t * youngSymmetrizer t ≠ 0 := by
  have hpos : (0 : ℚ) < (finrank ℚ (spechtIdeal t) : ℚ) := by
    exact_mod_cast finrank_spechtIdeal_pos t
  rw [youngSymmetrizer_sq t, smul_ne_zero_iff]
  refine ⟨?_, youngSymmetrizer_ne_zero t⟩
  exact div_ne_zero (Nat.cast_ne_zero.mpr μ.card.factorial_ne_zero) hpos.ne'

/-- **The normalised Young symmetrizer is idempotent.** Scaling `c_t` by `dim / n!` turns the
essential idempotence into genuine idempotence, so `ℚ[Sₙ] c_t` is generated by an idempotent. -/
theorem isIdempotentElem_smul_youngSymmetrizer (t : YoungTableau μ) :
    IsIdempotentElem
      (((finrank ℚ (spechtIdeal t) : ℚ) / (μ.card.factorial : ℚ)) • youngSymmetrizer t) := by
  have hfac : ((μ.card.factorial : ℚ)) ≠ 0 := Nat.cast_ne_zero.mpr μ.card.factorial_ne_zero
  have hpos : (0 : ℚ) < (finrank ℚ (spechtIdeal t) : ℚ) := by
    exact_mod_cast finrank_spechtIdeal_pos t
  have key : (((finrank ℚ (spechtIdeal t) : ℚ) / (μ.card.factorial : ℚ)) • youngSymmetrizer t) *
      (((finrank ℚ (spechtIdeal t) : ℚ) / (μ.card.factorial : ℚ)) • youngSymmetrizer t) =
      ((finrank ℚ (spechtIdeal t) : ℚ) / (μ.card.factorial : ℚ)) • youngSymmetrizer t := by
    rw [smul_mul_assoc, mul_smul_comm, youngSymmetrizer_sq t, smul_smul, smul_smul]
    congr 1
    field_simp
  exact key

end YoungTableau

end EpsilonEridani
