/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.Algebra.Subalgebra.Lattice
public import Mathlib.Algebra.Algebra.Tower

/-!
# Generators survive a change of base ring in an algebra tower

If a set generates `A` as an `F`-algebra, then in any `K` receiving `A` and a second `F`-algebra
`R` compatibly, the images of those generators generate the whole image of `A`, now over the new
base `R`. This is the step that turns an algebra-finite model of `A` over `F` into an
algebra-finite model of its image over `R`.

## Main results

* `Set.algebraMap_mem_adjoin_image`: the image in `K` of any element of `A` lies in the
  `R`-subalgebra generated by the images of an `F`-algebra generating set of `A`.
-/

public section

namespace Set

variable {F R A K : Type*} [CommSemiring F] [CommSemiring R] [CommSemiring A] [Semiring K]
  [Algebra F R] [Algebra F A] [Algebra F K] [Algebra R K] [Algebra A K]
  [IsScalarTower F R K] [IsScalarTower F A K]

/-- The image of any element of `A` lies in the `R`-subalgebra generated by the images of a
generating set of `A` over `F`: generators go to generators, and the two routes from `F` into `K`
agree, so the adjoin-induction closes. -/
theorem algebraMap_mem_adjoin_image (s : Set A) (hs : Algebra.adjoin F s = ⊤) (x : A) :
    algebraMap A K x ∈ Algebra.adjoin R (algebraMap A K '' s) := by
  let B := Algebra.adjoin R (algebraMap A K '' s)
  have hx : x ∈ Algebra.adjoin F s := by simp [hs]
  induction hx using Algebra.adjoin_induction with
  | mem x hx => exact Algebra.subset_adjoin (Set.mem_image_of_mem _ hx)
  | algebraMap x =>
      -- both routes from `F` to `K` factor through the towers, so the two maps agree
      rw [← IsScalarTower.algebraMap_apply F A K, IsScalarTower.algebraMap_apply F R K]
      exact B.algebraMap_mem (algebraMap F R x)
  | add x y _ _ hx hy => simpa only [map_add] using B.add_mem hx hy
  | mul x y _ _ hx hy => simpa only [map_mul] using B.mul_mem hx hy

end Set
