/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

import EpsilonEridani.Algebra.Polynomial.SpecificDegree

public import EpsilonEridani.FieldTheory.GaloisGroups.Resolvent.Label
public import EpsilonEridani.FieldTheory.GaloisGroups.Resolvent.Quartic.Discriminant
public import EpsilonEridani.GroupTheory.Perm.TransitiveGroupLabel.Classification

/-!
# The Galois group of a quartic

An irreducible separable quartic has transitive Galois image in `Equiv.Perm (Fin 4)`, so it
carries exactly one of the five labels `4T1`, …, `4T5`, the cyclic, Klein four, dihedral,
alternating and symmetric groups. Away from characteristic `2` two tests read that label off the
coefficients of `f`.

* The discriminant. The Galois image consists of even permutations exactly when `f.discr` is a
  square, which happens for `4T2` and `4T4` only.
* The resolvent cubic, the specialization at `f` of the `D₄`-specification `EpsilonEridani.quarticD4Spec`
  of the invariant `x₀x₂ + x₁x₃`. Its roots in the base field detect confinement of the Galois
  image to a conjugate of the dihedral group of `4T3`, which happens for `4T1`, `4T2` and `4T3`
  only. No separation hypothesis is needed: a quartic and its resolvent cubic have the same
  discriminant, so the resolvent of a separable quartic is separable.

Together the two tests decide between `4T5`, `4T4` and `4T2` and isolate the pair `{4T1, 4T3}`,
which they do not separate: the cyclic and the dihedral group both have odd parity and both lie
in a dihedral group of order eight. Separating them takes a further datum, namely whether `f`
stays irreducible over the quadratic extension generated by a square root of the discriminant.

The resolvent cubic is monic of degree three (`EpsilonEridani.natDegree_quarticD4Spec_specialize`), so
Mathlib's `Polynomial.irreducible_iff_roots_eq_zero_of_degree_le_three` identifies having no root
in the base field with irreducibility there. The first two rows below use that classical
irreducible-resolvent formulation directly.

## Main results

* `EpsilonEridani.existsUnique_hasGaloisLabel_four`: an irreducible separable quartic carries exactly
  one label.
* `EpsilonEridani.HasGaloisLabel.isSquare_discr_iff_four` and
  `EpsilonEridani.HasGaloisLabel.exists_isRoot_specialize_quarticD4Spec_iff`: the discriminant test and
  the resolvent test, as conditions on the label.
* `EpsilonEridani.hasGaloisLabel_four_four_iff`, `EpsilonEridani.hasGaloisLabel_four_three_iff`,
  `EpsilonEridani.hasGaloisLabel_four_one_iff`, `EpsilonEridani.hasGaloisLabel_four_zero_or_two_iff`: **the
  quartic decision table**, one theorem for each of its four rows.
* `EpsilonEridani.hasGaloisLabel_four_one_iff_splits_resolvent`: the row for `4T2` with the resolvent
  cubic asked to split completely, and
  `EpsilonEridani.hasGaloisLabel_four_zero_or_two_iff_existsUnique_isRoot_resolvent`: the row for
  `{4T1, 4T3}` with the resolvent cubic asked to have exactly one root. Both drop the
  discriminant condition, which the resolvent condition already implies.

## References

* K. Conrad, *Galois groups of cubics and quartics (not in characteristic 2)*, §3.
* [H. Cohen, *A Course in Computational Algebraic Number Theory*][cohen1993], §6.3.
-/

public section

open Polynomial Equiv Equiv.Perm

namespace EpsilonEridani

variable {F : Type*} [Field F] {f : F[X]}

/-- A polynomial carries at most one label in degree four. -/
theorem HasGaloisLabel.eq_of_four {j k : TransitiveGroupIndex 4} (hj : HasGaloisLabel f j)
    (hk : HasGaloisLabel f k) : j = k :=
  hj.eq_of (fun h h' => h.eq_of_four h') hk

/-- **An irreducible separable quartic carries exactly one label**, one of `4T1`, …, `4T5`. -/
theorem existsUnique_hasGaloisLabel_four (hsep : f.Separable) (hirr : Irreducible f)
    (hdeg : f.natDegree = 4) : ∃! j : TransitiveGroupIndex 4, HasGaloisLabel f j :=
  existsUnique_hasGaloisLabel hsep hirr hdeg (fun G _ => exists_transitiveGroupLabel_four G)
    fun h h' => h.eq_of_four h'

variable {j : TransitiveGroupIndex 4}

/-- **The resolvent cubic reads three of the five quartic labels.** The resolvent cubic of a monic
quartic with a label has a root in the base field exactly when that label is `4T1`, `4T2` or
`4T3`, the labels whose reference subgroup lies in a conjugate of the dihedral group of `4T3`.

The resolvent cubic of a separable quartic is separable, by
`EpsilonEridani.separable_quarticD4Spec_specialize_iff`, so no separation hypothesis appears. -/
theorem HasGaloisLabel.exists_isRoot_specialize_quarticD4Spec_iff (h : HasGaloisLabel f j)
    (hf : f.Monic) :
    (∃ a : F, (quarticD4Spec.specialize F f).IsRoot a) ↔ (j : ℕ) ≤ 2 := by
  rw [h.exists_isRoot_specialize_iff hf quarticD4Spec
      ((separable_quarticD4Spec_specialize_iff hf h.natDegree_eq).2 h.separable),
    quarticD4Spec_H, exists_le_map_conj_referenceSubgroup_four_two_iff]

/-- **The discriminant reads the parity of a quartic label.** Away from characteristic `2`, the
discriminant of a monic quartic with a label is a square exactly when that label is `4T2` or
`4T4`. -/
theorem HasGaloisLabel.isSquare_discr_iff_four (h : HasGaloisLabel f j) (hf : f.Monic)
    (hchar : ringChar F ≠ 2) : IsSquare f.discr ↔ (j : ℕ) = 1 ∨ (j : ℕ) = 3 :=
  (h.isSquare_discr_iff hf hchar).trans (referenceSubgroup_four_le_alternatingGroup_iff j)

variable (hchar : ringChar F ≠ 2) (hf : f.Monic)
include hchar hf

/-- **A quartic with non-square discriminant and irreducible resolvent cubic has label `4T5`.**
Away from characteristic `2`, a monic polynomial has label `4T5`, that is Galois group the full
symmetric group on its four roots, exactly when it is an irreducible quartic whose discriminant is
not a square and whose resolvent cubic is irreducible over the base field. -/
theorem hasGaloisLabel_four_four_iff :
    HasGaloisLabel f (⟨4, by simp⟩ : TransitiveGroupIndex 4) ↔
      Irreducible f ∧ f.natDegree = 4 ∧ ¬ IsSquare f.discr ∧
        Irreducible (quarticD4Spec.specialize F f) := by
  have hresdeg := natDegree_quarticD4Spec_specialize f
  have hres0 : quarticD4Spec.specialize F f ≠ 0 := fun h0 => by simp [h0] at hresdeg
  rw [Polynomial.irreducible_iff_roots_eq_zero_of_degree_le_three
      (p := quarticD4Spec.specialize F f) (by omega) (by omega),
    Multiset.eq_zero_iff_forall_notMem]
  simp only [Polynomial.mem_roots hres0, ← not_exists]
  refine ⟨fun h => ⟨h.irreducible, h.natDegree_eq, fun hsq => ?_, fun hr => ?_⟩, ?_⟩
  · simpa using (h.isSquare_discr_iff_four hf hchar).1 hsq
  · simpa using (h.exists_isRoot_specialize_quarticD4Spec_iff hf).1 hr
  · rintro ⟨hirr, hdeg, hsq, hroot⟩
    -- A non-square discriminant is nonzero, so `f` is separable and carries a label.
    have hsep : f.Separable := hf.discr_ne_zero_iff.1 fun h0 => hsq ⟨0, by simp [h0]⟩
    obtain ⟨k, hk, -⟩ := existsUnique_hasGaloisLabel_four hsep hirr hdeg
    have hpar := hk.isSquare_discr_iff_four hf hchar
    have hrt := hk.exists_isRoot_specialize_quarticD4Spec_iff hf
    have hne : ¬ ((k : ℕ) = 1 ∨ (k : ℕ) = 3) := fun hk1 => hsq (hpar.2 hk1)
    have hgt : ¬ ((k : ℕ) ≤ 2) := fun hk2 => hroot (hrt.2 hk2)
    have hlt : (k : ℕ) < 5 := by simpa using k.isLt
    have hk4val : (k : ℕ) = 4 := by omega
    have hk4 : k = ⟨4, by simp⟩ := by
      exact Fin.ext hk4val
    subst k
    exact hk

/-- **A quartic with square discriminant and irreducible resolvent cubic has label `4T4`.**
Away from characteristic `2`, a monic polynomial has label `4T4`, that is Galois group the
alternating group on its four roots, exactly when it is an irreducible quartic whose
discriminant is a square and whose resolvent cubic is irreducible over the base field. -/
theorem hasGaloisLabel_four_three_iff :
    HasGaloisLabel f (⟨3, by simp⟩ : TransitiveGroupIndex 4) ↔
      Irreducible f ∧ f.natDegree = 4 ∧ IsSquare f.discr ∧
        Irreducible (quarticD4Spec.specialize F f) := by
  have hresdeg := natDegree_quarticD4Spec_specialize f
  have hres0 : quarticD4Spec.specialize F f ≠ 0 := fun h0 => by simp [h0] at hresdeg
  rw [Polynomial.irreducible_iff_roots_eq_zero_of_degree_le_three
      (p := quarticD4Spec.specialize F f) (by omega) (by omega),
    Multiset.eq_zero_iff_forall_notMem]
  simp only [Polynomial.mem_roots hres0, ← not_exists]
  refine ⟨fun h => ⟨h.irreducible, h.natDegree_eq,
    (h.isSquare_discr_iff_four hf hchar).2 (by simp), fun hr => ?_⟩, ?_⟩
  · simpa using (h.exists_isRoot_specialize_quarticD4Spec_iff hf).1 hr
  · rintro ⟨hirr, hdeg, hsq, hroot⟩
    have hsep := Polynomial.separable_of_irreducible_of_natDegree_eq_four hchar hirr hdeg
    obtain ⟨k, hk, -⟩ := existsUnique_hasGaloisLabel_four hsep hirr hdeg
    have hpar := (hk.isSquare_discr_iff_four hf hchar).1 hsq
    have hgt : ¬ ((k : ℕ) ≤ 2) :=
      fun hk2 => hroot ((hk.exists_isRoot_specialize_quarticD4Spec_iff hf).2 hk2)
    have hk3val : (k : ℕ) = 3 := by omega
    have hk3 : k = ⟨3, by simp⟩ := by
      exact Fin.ext hk3val
    subst k
    exact hk

/-- **A quartic with square discriminant whose resolvent cubic has a root has label `4T2`.**
Away from characteristic `2`, a monic polynomial has label `4T2`, that is Galois group the Klein
four-group acting regularly on its four roots, exactly when it is an irreducible quartic
whose discriminant is a square and whose resolvent cubic has a root in the base field. -/
theorem hasGaloisLabel_four_one_iff :
    HasGaloisLabel f (⟨1, by simp⟩ : TransitiveGroupIndex 4) ↔
      Irreducible f ∧ f.natDegree = 4 ∧ IsSquare f.discr ∧
        ∃ a : F, (quarticD4Spec.specialize F f).IsRoot a := by
  refine ⟨fun h => ⟨h.irreducible, h.natDegree_eq,
    (h.isSquare_discr_iff_four hf hchar).2 (by simp),
    (h.exists_isRoot_specialize_quarticD4Spec_iff hf).2 (by simp)⟩, ?_⟩
  rintro ⟨hirr, hdeg, hsq, hroot⟩
  have hsep := Polynomial.separable_of_irreducible_of_natDegree_eq_four hchar hirr hdeg
  obtain ⟨k, hk, -⟩ := existsUnique_hasGaloisLabel_four hsep hirr hdeg
  have hpar := (hk.isSquare_discr_iff_four hf hchar).1 hsq
  have hrt := (hk.exists_isRoot_specialize_quarticD4Spec_iff hf).1 hroot
  have hk1val : (k : ℕ) = 1 := by omega
  have hk1 : k = ⟨1, by simp⟩ := by
    exact Fin.ext hk1val
  subst k
  exact hk

/-- **A quartic with non-square discriminant whose resolvent cubic has a root has label `4T1` or
`4T3`.** Away from characteristic `2`, a monic polynomial has label `4T1` or `4T3`, that is Galois
group cyclic of order four or dihedral of order eight, exactly when it is an irreducible quartic
whose discriminant is not a square and whose resolvent cubic has a root in the base field.

The discriminant and the resolvent cubic do not separate the two labels: both reference subgroups
contain odd permutations and both lie in a dihedral group of order eight, so the two tests take
the same values on them. -/
theorem hasGaloisLabel_four_zero_or_two_iff :
    (HasGaloisLabel f (⟨0, by simp⟩ : TransitiveGroupIndex 4) ∨
        HasGaloisLabel f (⟨2, by simp⟩ : TransitiveGroupIndex 4)) ↔
      Irreducible f ∧ f.natDegree = 4 ∧ ¬ IsSquare f.discr ∧
        ∃ a : F, (quarticD4Spec.specialize F f).IsRoot a := by
  constructor
  · rintro (h | h) <;>
      exact ⟨h.irreducible, h.natDegree_eq,
        fun hsq => by simpa using (h.isSquare_discr_iff_four hf hchar).1 hsq,
        (h.exists_isRoot_specialize_quarticD4Spec_iff hf).2 (by simp)⟩
  · rintro ⟨hirr, hdeg, hsq, hroot⟩
    -- A non-square discriminant is nonzero, so `f` is separable and carries a label.
    have hsep : f.Separable := hf.discr_ne_zero_iff.1 fun h0 => hsq ⟨0, by simp [h0]⟩
    obtain ⟨k, hk, -⟩ := existsUnique_hasGaloisLabel_four hsep hirr hdeg
    have hne : ¬ ((k : ℕ) = 1 ∨ (k : ℕ) = 3) :=
      fun hk1 => hsq ((hk.isSquare_discr_iff_four hf hchar).2 hk1)
    have hrt := (hk.exists_isRoot_specialize_quarticD4Spec_iff hf).1 hroot
    have hk02 : (k : ℕ) = 0 ∨ (k : ℕ) = 2 := by omega
    rcases hk02 with hk0 | hk2
    · obtain rfl : k = ⟨0, by simp⟩ := Fin.ext hk0
      exact Or.inl hk
    · obtain rfl : k = ⟨2, by simp⟩ := Fin.ext hk2
      exact Or.inr hk

/-- **The split-resolvent row for `4T2`.** Away from characteristic `2`, a monic polynomial
has label `4T2` exactly when it is an irreducible quartic whose resolvent cubic splits completely
over the base field. The square-discriminant condition follows from splitting. -/
theorem hasGaloisLabel_four_one_iff_splits_resolvent :
    HasGaloisLabel f (⟨1, by simp⟩ : TransitiveGroupIndex 4) ↔
      Irreducible f ∧ f.natDegree = 4 ∧ (quarticD4Spec.specialize F f).Splits := by
  constructor
  · intro h
    obtain ⟨hirr, hdeg, hsq, a, ha⟩ := (hasGaloisLabel_four_one_iff hchar hf).1 h
    refine ⟨hirr, hdeg, ?_⟩
    apply (splits_iff_isSquare_discr_of_natDegree_eq_three_of_isRoot
      (natDegree_quarticD4Spec_specialize f) hchar ha).2
    rwa [← discr_quarticD4Spec_specialize hf hdeg]
  · rintro ⟨hirr, hdeg, hsplit⟩
    have hresdeg := natDegree_quarticD4Spec_specialize f
    obtain ⟨a, ha⟩ := hsplit.exists_eval_eq_zero
      (degree_ne_of_natDegree_ne (by rw [hresdeg]; norm_num))
    have hressq :=
      (splits_iff_isSquare_discr_of_natDegree_eq_three_of_isRoot hresdeg hchar ha).1 hsplit
    have hsq : IsSquare f.discr := by
      rw [discr_quarticD4Spec_specialize hf hdeg]
      exact hressq
    apply (hasGaloisLabel_four_one_iff hchar hf).2
    exact ⟨hirr, hdeg, hsq, a, ha⟩

/-- **The unique-root row for `4T1` or `4T3`.** Away from characteristic `2`, a monic
polynomial has label `4T1` or `4T3` exactly when it is an irreducible quartic whose resolvent
cubic has exactly one root in the base field. The non-square-discriminant condition follows from
the uniqueness of the root. -/
theorem hasGaloisLabel_four_zero_or_two_iff_existsUnique_isRoot_resolvent :
    (HasGaloisLabel f (⟨0, by simp⟩ : TransitiveGroupIndex 4) ∨
        HasGaloisLabel f (⟨2, by simp⟩ : TransitiveGroupIndex 4)) ↔
      Irreducible f ∧ f.natDegree = 4 ∧
        ∃! a : F, (quarticD4Spec.specialize F f).IsRoot a := by
  constructor
  · intro h
    obtain ⟨hirr, hdeg, hsq, a, ha⟩ := (hasGaloisLabel_four_zero_or_two_iff hchar hf).1 h
    refine ⟨hirr, hdeg, a, ha, ?_⟩
    intro x hx
    by_contra hxa
    have hresdeg := natDegree_quarticD4Spec_specialize f
    have hsplit := Splits.of_natDegree_eq_three_of_isRoot_of_isRoot_of_ne hresdeg ha hx hxa
    apply hsq
    rw [discr_quarticD4Spec_specialize hf hdeg]
    exact (splits_iff_isSquare_discr_of_natDegree_eq_three_of_isRoot
      hresdeg hchar ha).1 hsplit
  · rintro ⟨hirr, hdeg, a, ha, huniq⟩
    have hsep := Polynomial.separable_of_irreducible_of_natDegree_eq_four hchar hirr hdeg
    have hressep := (separable_quarticD4Spec_specialize_iff hf hdeg).2 hsep
    have hresdeg := natDegree_quarticD4Spec_specialize f
    have hsq : ¬ IsSquare f.discr := by
      intro hsq
      have hressq : IsSquare (quarticD4Spec.specialize F f).discr := by
        rwa [← discr_quarticD4Spec_specialize hf hdeg]
      have hsplit :=
        (splits_iff_isSquare_discr_of_natDegree_eq_three_of_isRoot hresdeg hchar ha).2 hressq
      obtain ⟨x, hx, hxa⟩ := hsplit.exists_isRoot_ne hressep (by omega) a
      exact hxa (huniq x hx)
    apply (hasGaloisLabel_four_zero_or_two_iff hchar hf).2
    exact ⟨hirr, hdeg, hsq, a, ha⟩

end EpsilonEridani
