/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.FieldTheory.GaloisGroups.Resolvent.Spec

import Mathlib.GroupTheory.Perm.ClosureSwap
import EpsilonEridani.GroupTheory.Perm.FiberSubgroup

/-!
# The pair-sum resolvent of a quintic

The linear invariant `x₀ + x₁` of five formal roots is fixed exactly by the permutations
that preserve the pair `{0, 1}`. Its stabilizer is the intransitive subgroup
`S_{{0,1}} × S_{{2,3,4}}`, generated by the three adjacent transpositions `(0 1)`, `(2 3)` and
`(3 4)`. The orbit consists of the ten sums `xᵢ + xⱼ` indexed by unordered pairs of distinct
indices, so the associated resolvent has degree ten.

This is the basic linear-resolvent example: specializing the universal specification at a monic
quintic of degree five produces the polynomial whose roots are the pairwise sums of the roots,
whenever those roots are enumerated in a splitting extension.

## Main definitions

* `EpsilonEridani.quinticPairSumStabilizer`: the subgroup preserving `{0, 1}`.
* `EpsilonEridani.quinticPairSumInvariant`: the invariant `x₀ + x₁`.
* `EpsilonEridani.quinticPairSumSpec`: its resolvent specification.

## Main results

* `EpsilonEridani.quinticPairSumStabilizer_eq_closure`: the stabilizer is generated by `(0 1)`,
  `(2 3)` and `(3 4)`.
* `EpsilonEridani.rename_quinticPairSumInvariant_eq_self_iff`: the exact stabilizer theorem.
* `EpsilonEridani.card_renameOrbit_quinticPairSumInvariant`: the symbolic orbit has ten elements.
* `EpsilonEridani.natDegree_specialize_quinticPairSumSpec`: every specialization has degree ten.

## References

* H. Cohen, *A Course in Computational Algebraic Number Theory*, §6.3.
-/

public section

open Equiv Equiv.Perm Polynomial

namespace EpsilonEridani

open MvPolynomial (renameOrbit)

/-- The intransitive subgroup of `S₅` preserving the pair `{0, 1}` setwise. -/
def quinticPairSumStabilizer : Subgroup (Perm (Fin 5)) :=
  fiberSubgroup fun i : Fin 5 => decide (i < 2)

/-- Membership in the pair-sum stabilizer means preserving the pair `{0, 1}`. -/
theorem mem_quinticPairSumStabilizer_iff (σ : Perm (Fin 5)) :
    σ ∈ quinticPairSumStabilizer ↔
      (σ 0 = 0 ∧ σ 1 = 1) ∨ (σ 0 = 1 ∧ σ 1 = 0) := by
  rw [quinticPairSumStabilizer, mem_fiberSubgroup]
  constructor
  · intro h
    have h0 : σ 0 < 2 := (decide_eq_decide.mp (h 0)).mpr (by decide)
    have h1 : σ 1 < 2 := (decide_eq_decide.mp (h 1)).mpr (by decide)
    have hne : σ 0 ≠ σ 1 := fun h01 => zero_ne_one (σ.injective h01)
    have h0' : σ 0 = 0 ∨ σ 0 = 1 := by omega
    have h1' : σ 1 = 0 ∨ σ 1 = 1 := by omega
    grind
  · rintro (⟨h0, h1⟩ | ⟨h0, h1⟩) i <;> apply Bool.decide_congr
    · have hσlt : σ i < 2 ↔ σ i = 0 ∨ σ i = 1 := by omega
      have hilt : i < 2 ↔ i = 0 ∨ i = 1 := by omega
      rw [hσlt, hilt]
      constructor
      · rintro (hσi | hσi)
        · exact Or.inl (σ.injective (hσi.trans h0.symm))
        · exact Or.inr (σ.injective (hσi.trans h1.symm))
      · rintro (rfl | rfl) <;> simp_all
    · have hσlt : σ i < 2 ↔ σ i = 0 ∨ σ i = 1 := by omega
      have hilt : i < 2 ↔ i = 0 ∨ i = 1 := by omega
      rw [hσlt, hilt]
      constructor
      · rintro (hσi | hσi)
        · exact Or.inr (σ.injective (hσi.trans h1.symm))
        · exact Or.inl (σ.injective (hσi.trans h0.symm))
      · rintro (rfl | rfl) <;> simp_all

/-- Two indices on the same side of the partition `{0, 1} ⊎ {2, 3, 4}` can be exchanged by
the three transpositions used to generate the pair-sum stabilizer. -/
private theorem swap_mem_quinticPairSumGenerators {x y : Fin 5}
    (hxy : decide (x < 2) = decide (y < 2)) :
    swap x y ∈ Subgroup.closure {swap (0 : Fin 5) 1, swap 2 3, swap 3 4} := by
  have h01 : swap (0 : Fin 5) 1 ∈
      Subgroup.closure {swap (0 : Fin 5) 1, swap 2 3, swap 3 4} :=
    Subgroup.subset_closure (by simp)
  have h23 : swap (2 : Fin 5) 3 ∈
      Subgroup.closure {swap (0 : Fin 5) 1, swap 2 3, swap 3 4} :=
    Subgroup.subset_closure (by simp)
  have h34 : swap (3 : Fin 5) 4 ∈
      Subgroup.closure {swap (0 : Fin 5) 1, swap 2 3, swap 3 4} :=
    Subgroup.subset_closure (by simp)
  have h24 : swap (2 : Fin 5) 4 ∈
      Subgroup.closure {swap (0 : Fin 5) 1, swap 2 3, swap 3 4} :=
    SubmonoidClass.swap_mem_trans _ h23 h34
  by_cases hx : x < 2
  · have hy : y < 2 := (decide_eq_decide.mp hxy).mp hx
    rcases (by omega : x = 0 ∨ x = 1) with rfl | rfl <;>
      rcases (by omega : y = 0 ∨ y = 1) with rfl | rfl
    all_goals try simp only [swap_self]
    all_goals first
      | exact Subgroup.one_mem _
      | exact h01
      | simpa only [swap_comm] using h01
  · have hxle : 2 ≤ x := by omega
    have hy : ¬ y < 2 := fun hy => hx ((decide_eq_decide.mp hxy).mpr hy)
    have hy : 2 ≤ y := by omega
    rcases (by omega : x = 2 ∨ x = 3 ∨ x = 4) with rfl | rfl | rfl <;>
      rcases (by omega : y = 2 ∨ y = 3 ∨ y = 4) with rfl | rfl | rfl
    all_goals try simp only [swap_self]
    all_goals first
      | exact Subgroup.one_mem _
      | exact h23
      | exact h24
      | exact h34
      | simpa only [swap_comm] using h23
      | simpa only [swap_comm] using h24
      | simpa only [swap_comm] using h34

/-- The pair stabilizer is generated by the transpositions `(0 1)`, `(2 3)` and `(3 4)`. -/
theorem quinticPairSumStabilizer_eq_closure :
    quinticPairSumStabilizer =
      Subgroup.closure {swap (0 : Fin 5) 1, swap 2 3, swap 3 4} := by
  let S : Set (Perm (Fin 5)) := {swap (0 : Fin 5) 1, swap 2 3, swap 3 4}
  have hS : ∀ σ ∈ S, σ.IsSwap := by
    rintro σ (rfl | rfl | rfl) <;> exact ⟨_, _, by decide, rfl⟩
  apply le_antisymm
  -- A fiber-preserving permutation moves every index within the orbit generated by the three
  -- swaps, so Mathlib's transposition-generation criterion puts it in their closure.
  · intro σ hσ
    rw [mem_closure_isSwap hS]
    refine ⟨Set.toFinite _, fun i => ?_⟩
    rw [← (swap_mem_closure_isSwap hS)]
    have hσ' : σ ∈ fiberSubgroup (fun i : Fin 5 => decide (i < 2)) := by
      simpa [quinticPairSumStabilizer] using hσ
    simpa [S] using swap_mem_quinticPairSumGenerators (mem_fiberSubgroup.mp hσ' i)
  -- Each listed generator exchanges two indices in the same fiber.
  · rw [Subgroup.closure_le]
    rintro σ (rfl | rfl | rfl)
    · exact swap_mem_fiberSubgroup (by decide)
    · exact swap_mem_fiberSubgroup (by decide)
    · exact swap_mem_fiberSubgroup (by decide)

/-- The linear invariant `x₀ + x₁` of five formal roots. -/
noncomputable def quinticPairSumInvariant : MvPolynomial (Fin 5) ℤ :=
  MvPolynomial.X 0 + MvPolynomial.X 1

/-- The defining formula of the quintic pair-sum invariant. -/
theorem quinticPairSumInvariant_def :
    quinticPairSumInvariant = MvPolynomial.X 0 + MvPolynomial.X 1 :=
  (rfl)

/-- Renaming the variables of the pair-sum invariant along `σ`. -/
theorem rename_quinticPairSumInvariant (σ : Perm (Fin 5)) :
    MvPolynomial.rename (⇑σ) quinticPairSumInvariant =
      MvPolynomial.X (σ 0) + MvPolynomial.X (σ 1) := by
  simp [quinticPairSumInvariant]

/-- If a permutation does not preserve `{0, 1}`, evaluation at `(1, 2, 4, 8, 16)` distinguishes
the renamed pair-sum invariant from the original one. -/
private theorem pair_or_value_ne (σ : Perm (Fin 5)) :
    ((σ 0 = 0 ∧ σ 1 = 1) ∨ (σ 0 = 1 ∧ σ 1 = 0)) ∨
      (![1, 2, 4, 8, 16] (σ 0) + ![1, 2, 4, 8, 16] (σ 1) : ℤ) ≠ 3 := by
  generalize h0 : σ 0 = a
  generalize h1 : σ 1 = b
  fin_cases a <;> fin_cases b <;> simp_all

/-- **The exact stabilizer.** A permutation fixes `x₀ + x₁` if and only if it preserves
the pair `{0, 1}`. -/
theorem rename_quinticPairSumInvariant_eq_self_iff (σ : Perm (Fin 5)) :
    MvPolynomial.rename (⇑σ) quinticPairSumInvariant = quinticPairSumInvariant ↔
      σ ∈ quinticPairSumStabilizer := by
  rw [mem_quinticPairSumStabilizer_iff]
  constructor
  · intro h
    have horient := (pair_or_value_ne σ).resolve_right fun hne => hne (by
      have := congrArg (MvPolynomial.eval ![1, 2, 4, 8, 16]) h
      simpa [rename_quinticPairSumInvariant, quinticPairSumInvariant] using this)
    exact horient
  · intro h
    rcases h with ⟨h0, h1⟩ | ⟨h0, h1⟩ <;>
      simp [quinticPairSumInvariant, h0, h1, add_comm]

/-- **The quintic pair-sum resolvent specification**: the invariant `x₀ + x₁`, whose
stabilizer is the intransitive subgroup preserving `{0, 1}`. -/
noncomputable def quinticPairSumSpec : ResolventSpec 5 :=
  ResolventSpec.mk' quinticPairSumStabilizer quinticPairSumInvariant
    rename_quinticPairSumInvariant_eq_self_iff

@[simp]
theorem quinticPairSumSpec_H : quinticPairSumSpec.H = quinticPairSumStabilizer :=
  ResolventSpec.mk'_H _ _ _

@[simp]
theorem quinticPairSumSpec_Φ : quinticPairSumSpec.Φ = quinticPairSumInvariant :=
  ResolventSpec.mk'_Φ _ _ _

attribute [local instance] Fintype.ofFinite in
/-- The pair-sum stabilizer has order twelve: independently permuting the pair and its
three-element complement gives `2! · 3! = 12` elements. -/
@[simp]
theorem card_quinticPairSumStabilizer : Fintype.card quinticPairSumStabilizer = 12 := by
  unfold quinticPairSumStabilizer
  have htwo : Fintype.card {i : Fin 5 // i < 2} = 2 := by decide
  have hthree : Fintype.card {i : Fin 5 // 2 ≤ i} = 3 := by decide
  rw [Fintype.card_congr
    (fiberSubgroupMulEquivPiPerm (fun i : Fin 5 => decide (i < 2))).toEquiv]
  norm_num [Fintype.card_pi, Fintype.card_perm, Nat.factorial, htwo, hthree]

/-- The pair-sum stabilizer has index ten in `S₅`, one coset for each unordered pair. -/
@[simp]
theorem index_quinticPairSumStabilizer : quinticPairSumStabilizer.index = 10 := by
  have h := quinticPairSumStabilizer.index_mul_card
  have hcard : Nat.card quinticPairSumStabilizer = 12 := by
    rw [@Nat.card_eq_fintype_card _ (Fintype.ofFinite _), card_quinticPairSumStabilizer]
  rw [hcard, Nat.card_eq_fintype_card, Fintype.card_perm] at h
  norm_num [Nat.factorial] at h
  omega

/-- **The orbit of `x₀ + x₁` has ten elements**, indexed by the unordered pairs of five
indices. -/
theorem card_renameOrbit_quinticPairSumInvariant :
    (renameOrbit quinticPairSumInvariant).card = 10 := by
  rw [← quinticPairSumSpec_Φ, ResolventSpec.card_renameOrbit, quinticPairSumSpec_H,
    index_quinticPairSumStabilizer]

/-- Every specialization of the quintic pair-sum specification has degree ten. -/
theorem natDegree_specialize_quinticPairSumSpec (R : Type*) [CommRing R] [Nontrivial R]
    (f : R[X]) : (quinticPairSumSpec.specialize R f).natDegree = 10 := by
  rw [ResolventSpec.natDegree_specialize, quinticPairSumSpec_H,
    index_quinticPairSumStabilizer]

end EpsilonEridani
