/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.Algebra.Lie.G2.ShortRoot.CrossProduct.Basic
public import EpsilonEridani.LinearAlgebra.Basis.DiagonalTorus.Basic

/-!
# Invariance of the G2 tensors under the root elements and torus

The four numbered simple root elements of the seven-dimensional representation preserve its
cross product and its invariant dual form, over every commutative ring. The weight torus preserves
the same tensors. These are the generator equations needed to place the group generated by the
root subgroups and torus inside the tensor stabilizers. In characteristic three, those stabilizer
conditions are the hypotheses of `Matrix.g2SpecialIsogeny_mul`.

The short-root elements include their integral divided-square terms; no division by two or
characteristic restriction is needed. All parameters are arbitrary ring elements, so the equations
also apply to the universal root parameter over a polynomial ring.

The coordinates and conventions are those of `EpsilonEridani.G2ShortRoot.crossOperator` and
`EpsilonEridani.G2ShortRoot.invariantDualForm`. See R. W. Carter, *Simple Groups of Lie Type*, §§12.3,
13.4, and S. Garibaldi and R. M. Guralnick, *Simple groups stabilizing polynomials*, §6.
-/

public section

open Matrix

namespace EpsilonEridani.G2ShortRoot

variable {R : Type*} [CommRing R]

-- Equate the four nonconstant coefficients of cross-product preservation for 1 + tA + t²B.
private theorem preservesG2Cross_quadratic (A B : Matrix (Fin 7) (Fin 7) R)
    (h : ∀ k : Fin 7,
      let C := (crossOperator k).map (Int.cast : ℤ → R)
      let U := ∑ a, A a k • (crossOperator a).map (Int.cast : ℤ → R)
      let V := ∑ a, B a k • (crossOperator a).map (Int.cast : ℤ → R)
      A * C = C * A + U ∧ B * C = C * B + U * A + V ∧
        U * B + V * A = 0 ∧ V * B = 0) (t : R) :
    PreservesG2Cross (1 + t • A + t ^ 2 • B) := by
  rw [preservesG2Cross_def]
  intro k
  obtain ⟨h₁, h₂, h₃, h₄⟩ := h k
  have hs : (∑ a, (1 + t • A + t ^ 2 • B) a k •
      (crossOperator a).map (Int.cast : ℤ → R)) =
      (crossOperator k).map (Int.cast : ℤ → R) +
        t • (∑ a, A a k • (crossOperator a).map (Int.cast : ℤ → R)) +
        t ^ 2 • (∑ a, B a k • (crossOperator a).map (Int.cast : ℤ → R)) := by
    simp [Matrix.add_apply, Matrix.smul_apply, add_smul, mul_smul,
      Finset.sum_add_distrib, Finset.smul_sum, Matrix.one_apply]
  rw [hs]
  simp only [add_mul, mul_add, one_mul, mul_one, Matrix.smul_mul, Matrix.mul_smul,
    smul_smul]
  linear_combination (norm := module) t • h₁ + t ^ 2 • h₂ - t ^ 3 • h₃ - t ^ 4 • h₄

private theorem root_cross_coefficients (i : Fin 4) :
    let A : Matrix (Fin 7) (Fin 7) ℤ :=
      ![raisingMatrix 0, raisingMatrix 1, loweringMatrix 0, loweringMatrix 1] i
    let B : Matrix (Fin 7) (Fin 7) ℤ :=
      ![Matrix.single 2 4 1, 0, Matrix.single 4 2 1, 0] i
    ∀ k : Fin 7,
      let C := (crossOperator k).map (Int.cast : ℤ → ℤ)
      let U := ∑ a, A a k • (crossOperator a).map (Int.cast : ℤ → ℤ)
      let V := ∑ a, B a k • (crossOperator a).map (Int.cast : ℤ → ℤ)
      A * C = C * A + U ∧ B * C = C * B + U * A + V ∧
        U * B + V * A = 0 ∧ V * B = 0 := by
  revert i
  rw [crossOperator_def]
  decide +kernel

private theorem preservesG2Cross_root (i : Fin 4) (t : R) :
    PreservesG2Cross
      (1 + t • (![raisingMatrix 0, raisingMatrix 1, loweringMatrix 0, loweringMatrix 1] i).map
        (Int.cast : ℤ → R) +
        t ^ 2 • (![Matrix.single 2 4 1, 0, Matrix.single 4 2 1, 0] i).map (Int.cast : ℤ → R)) := by
  apply preservesG2Cross_quadratic
  intro k
  obtain ⟨h₁, h₂, h₃, h₄⟩ := root_cross_coefficients i k
  simp only [← Matrix.ext_iff, Matrix.mul_apply, Matrix.sum_apply, Matrix.add_apply,
    Matrix.smul_apply, Matrix.map_apply, Matrix.zero_apply, smul_eq_mul, Int.cast_id]
    at h₁ h₂ h₃ h₄
  refine ⟨?_, ?_, ?_, ?_⟩
  all_goals
    ext a b
  · simpa [Matrix.mul_apply, Matrix.sum_apply, Int.cast_sum] using
      congrArg (Int.castRingHom R) (h₁ a b)
  · simpa [Matrix.mul_apply, Matrix.sum_apply, Int.cast_sum] using
      congrArg (Int.castRingHom R) (h₂ a b)
  · simpa [Matrix.mul_apply, Matrix.sum_apply, Int.cast_sum] using
      congrArg (Int.castRingHom R) (h₃ a b)
  · simpa [Matrix.mul_apply, Matrix.sum_apply, Int.cast_sum] using
      congrArg (Int.castRingHom R) (h₄ a b)

/-- The positive short simple root elements preserve the cross product. -/
@[simp↓]
theorem preservesG2Cross_one_add_smul_raisingMatrix_zero_add_sq_smul_single (t : R) :
    PreservesG2Cross
      (1 + t • (raisingMatrix 0).map (Int.cast : ℤ → R) + t ^ 2 • Matrix.single 2 4 1) := by
  have hs : (Matrix.single (2 : Fin 7) (4 : Fin 7) (1 : ℤ)).map (Int.cast : ℤ → R) =
      Matrix.single 2 4 1 := by
    exact (Matrix.map_single 2 4 1 (Int.castRingHom R)).trans (by simp)
  simpa [hs] using preservesG2Cross_root 0 t

/-- The positive long simple root elements preserve the cross product. -/
@[simp]
theorem preservesG2Cross_one_add_smul_raisingMatrix_one (t : R) :
    PreservesG2Cross (1 + t • (raisingMatrix 1).map (Int.cast : ℤ → R)) := by
  simpa using preservesG2Cross_root 1 t

/-- The negative short simple root elements preserve the cross product. -/
@[simp↓]
theorem preservesG2Cross_one_add_smul_loweringMatrix_zero_add_sq_smul_single (t : R) :
    PreservesG2Cross
      (1 + t • (loweringMatrix 0).map (Int.cast : ℤ → R) + t ^ 2 • Matrix.single 4 2 1) := by
  have hs : (Matrix.single (4 : Fin 7) (2 : Fin 7) (1 : ℤ)).map (Int.cast : ℤ → R) =
      Matrix.single 4 2 1 := by
    exact (Matrix.map_single 4 2 1 (Int.castRingHom R)).trans (by simp)
  simpa [hs] using preservesG2Cross_root 2 t

/-- The negative long simple root elements preserve the cross product. -/
@[simp]
theorem preservesG2Cross_one_add_smul_loweringMatrix_one (t : R) :
    PreservesG2Cross (1 + t • (loweringMatrix 1).map (Int.cast : ℤ → R)) := by
  simpa using preservesG2Cross_root 3 t

/-- The positive short simple root elements fix the invariant dual form by congruence. -/
@[simp↓]
theorem one_add_smul_raisingMatrix_zero_add_sq_smul_single_mul_invariantDualForm_mul_transpose
    (t : R) :
    let g := 1 + t • (raisingMatrix 0).map (Int.cast : ℤ → R) + t ^ 2 • Matrix.single 2 4 1
    g * invariantDualForm.map (Int.cast : ℤ → R) * gᵀ =
      invariantDualForm.map (Int.cast : ℤ → R) := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [Matrix.mul_apply, Fin.sum_univ_seven, invariantDualForm_def] <;> ring

/-- The positive long simple root elements fix the invariant dual form by congruence. -/
@[simp↓]
theorem one_add_smul_raisingMatrix_one_mul_invariantDualForm_mul_transpose (t : R) :
    let g := 1 + t • (raisingMatrix 1).map (Int.cast : ℤ → R)
    g * invariantDualForm.map (Int.cast : ℤ → R) * gᵀ =
      invariantDualForm.map (Int.cast : ℤ → R) := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [Matrix.mul_apply, Fin.sum_univ_seven, invariantDualForm_def] <;> ring

/-- The negative short simple root elements fix the invariant dual form by congruence. -/
@[simp↓]
theorem one_add_smul_loweringMatrix_zero_add_sq_smul_single_mul_invariantDualForm_mul_transpose
    (t : R) :
    let g := 1 + t • (loweringMatrix 0).map (Int.cast : ℤ → R) + t ^ 2 • Matrix.single 4 2 1
    g * invariantDualForm.map (Int.cast : ℤ → R) * gᵀ =
      invariantDualForm.map (Int.cast : ℤ → R) := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [Matrix.mul_apply, Fin.sum_univ_seven, invariantDualForm_def] <;> ring

/-- The negative long simple root elements fix the invariant dual form by congruence. -/
@[simp↓]
theorem one_add_smul_loweringMatrix_one_mul_invariantDualForm_mul_transpose (t : R) :
    let g := 1 + t • (loweringMatrix 1).map (Int.cast : ℤ → R)
    g * invariantDualForm.map (Int.cast : ℤ → R) * gᵀ =
      invariantDualForm.map (Int.cast : ℤ → R) := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [Matrix.mul_apply, Fin.sum_univ_seven, invariantDualForm_def] <;> ring

/-- The weight torus preserves the cross product. -/
@[simp]
theorem preservesG2Cross_diagonal_torusCharacter (s : Fin 2 → Rˣ) :
    PreservesG2Cross (Matrix.diagonal fun a => (torusCharacter s (weight a) : R)) := by
  rw [preservesG2Cross_def]
  intro k
  have hs : (∑ a, (Matrix.diagonal fun a => (torusCharacter s (weight a) : R)) a k •
      (crossOperator a).map (Int.cast : ℤ → R)) =
      (torusCharacter s (weight k) : R) • (crossOperator k).map (Int.cast : ℤ → R) := by
    simp [Matrix.diagonal_apply]
  rw [hs]
  ext i j
  simp only [Matrix.diagonal_mul, Matrix.mul_diagonal, Matrix.smul_apply, Matrix.map_apply,
    smul_eq_mul]
  by_cases h : crossOperator k i j = 0
  · simp [h]
  · rw [weight_eq_add_of_crossOperator_ne_zero k i j h, torusCharacter_add, Units.val_mul]
    ring

/-- The weight torus fixes the invariant dual form by congruence. -/
@[simp↓]
theorem diagonal_torusCharacter_mul_invariantDualForm_mul_transpose (s : Fin 2 → Rˣ) :
    let g := Matrix.diagonal fun a => (torusCharacter s (weight a) : R)
    g * invariantDualForm.map (Int.cast : ℤ → R) * gᵀ =
      invariantDualForm.map (Int.cast : ℤ → R) := by
  dsimp only
  rw [Matrix.diagonal_transpose]
  ext i j
  simp only [Matrix.mul_diagonal, Matrix.diagonal_mul, Matrix.map_apply]
  by_cases h : invariantDualForm i j = 0
  · simp [h]
  · have hs : (torusCharacter s (weight i) : R) * (torusCharacter s (weight j) : R) = 1 := by
      rw [← Units.val_mul, ← torusCharacter_add,
        weight_add_eq_zero_of_invariantDualForm_ne_zero i j h, torusCharacter_zero, Units.val_one]
    linear_combination (invariantDualForm i j : R) * hs

end EpsilonEridani.G2ShortRoot
