/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.GroupTheory.SpecificGroups.CFSG.Frobenius
public import EpsilonEridani.LinearAlgebra.RootSystem.SimplyConnectedRootDatum.GeckLattice.Frobenius
public import EpsilonEridani.LinearAlgebra.RootSystem.SimplyConnectedRootDatum.GeckLattice.RootDatum

/-!
# The Geck carrier of a Lie-type index

Every valid Lie-type index names a valid Dynkin type through `EpsilonEridani.ValidLieTypeIndex.dynkinType`
and `dynkinType_valid`, and the root-systems roadmap attaches to such a type the pinned Geck group
scheme `EpsilonEridani.DynkinType.geckGroupScheme`: an explicit closed subgroup scheme of `GLₙ` over `ℤ`
generated by the divided-power exponential root subgroups of the Bourbaki-numbered Chevalley
generators together with its weight torus. This file evaluates that carrier at the data an index
records, giving every valid index a concrete matrix group over the algebraic closure of its prime
field, numbered root subgroups, and a `q`-power Frobenius endomorphism.

Nothing in the construction depends on which diagram the index names, so the whole API is stated
for `EpsilonEridani.ValidLieTypeIndex`, exactly as `EpsilonEridani.ValidLieTypeIndex.frobeniusEquiv` is: the
field-level and carrier-level maps are the same recipe on every branch, and the branches differ
only in which endomorphism of this group is later taken as the Steinberg map.

The names all carry the `geck` prefix because this carrier is not the uniform ambient group.
Geck's module is the adjoint module, so the characters occurring in it generate the root lattice
and not, in general, the whole character lattice of the pinned torus. This file does not identify
the carrier with the pinned simply connected Chevalley--Demazure group scheme of
`EpsilonEridani.DynkinType.simplyConnectedRootDatum`. The uniform
`EpsilonEridani.ValidLieTypeIndex.AmbientGroup` and `EpsilonEridani.ValidLieTypeIndex.simpleRootSubgroup` are
assembled by cases in `EpsilonEridani.GroupTheory.SpecificGroups.CFSG.Assembly.AmbientGroup`; this carrier
serves only the `E₈`, `F₄` and `G₂` branches through `EpsilonEridani.UnimodularExceptionalIndex`. No
declaration below asserts that this carrier is reductive, that its root datum is the simply
connected one, that its weight torus is maximal, or that its point group is finite.

## Main definitions

* `EpsilonEridani.ValidLieTypeIndex.geckPoints` and `EpsilonEridani.ValidLieTypeIndex.GeckGroup`: the points of
  the Geck carrier of the underlying Dynkin type over the algebraic closure of the prime field, as
  a subgroup of `GLₙ` and as a type.
* `EpsilonEridani.ValidLieTypeIndex.geckRootSubgroup`: its Bourbaki-numbered root subgroups.
* `EpsilonEridani.ValidLieTypeIndex.geckWeightTorus`: the split weight torus of the same carrier, of rank
  the rank of the index.
* `EpsilonEridani.ValidLieTypeIndex.geckFrobenius`: its `q`-power Frobenius, for `q` the field order
  recorded by the index.

## Main results

* `EpsilonEridani.ValidLieTypeIndex.geckWeightTorus_conj_geckRootSubgroup_root_simpleIndex` and its
  negative-root counterpart: conjugation by a weight-torus point rescales the parameter of the
  numbered root subgroup at node `i` by the simple root `α_i` of the root datum
  `EpsilonEridani.DynkinType.simplyConnectedRootDatum` of the Dynkin type the index names, in the same
  Bourbaki numbering.
* `EpsilonEridani.ValidLieTypeIndex.coe_geckFrobenius_apply`: the Frobenius raises every matrix entry to
  the `q`-th power.
* `EpsilonEridani.ValidLieTypeIndex.geckFrobenius_geckRootSubgroup` and
  `EpsilonEridani.ValidLieTypeIndex.geckFrobenius_geckWeightTorus`: it raises the parameter of every
  numbered root subgroup, and every coordinate of a weight-torus point, to the `q`-th power.
* `EpsilonEridani.ValidLieTypeIndex.mem_fixedSubgroup_geckFrobenius_iff`: its fixed points are the points
  whose matrix entries lie in the field of definition `𝔽_q` of
  `EpsilonEridani.ValidLieTypeIndex.fixedField`.
* `EpsilonEridani.ValidLieTypeIndex.geckWeightTorus_mem_fixedSubgroup_geckFrobenius`: among those points
  are the weight-torus points all of whose coordinates lie in `𝔽_q`.

* `EpsilonEridani.ValidLieTypeIndex.geckPrimeFrobenius`, with
  `EpsilonEridani.ValidLieTypeIndex.geckPrimeFrobenius_geckRootSubgroup`,
  `EpsilonEridani.ValidLieTypeIndex.geckPrimeFrobenius_geckWeightTorus` and
  `EpsilonEridani.ValidLieTypeIndex.geckFrobenius_eq_geckPrimeFrobenius_pow`: the prime-field Frobenius of
  the Geck point group, its action on the numbered root subgroups and on the weight torus, and the
  `q`-power Frobenius as its `e`-th power.
## References

* M. Geck, *On the construction of semisimple Lie algebras and Chevalley groups*,
  Proc. Amer. Math. Soc. **145** (2017), 3233--3247, for the matrix realization that
  `EpsilonEridani.LinearAlgebra.RootSystem.SimplyConnectedRootDatum.GeckLattice` supplies.
* R. W. Carter, *Simple Groups of Lie Type*, §4.4, for the pinned root-subgroup conventions and the
  entrywise action of the Frobenius.

## Roadmap

Milestone L0 of `EpsilonEridaniRoadmap/CFSGStatement/README.md` asks for the points of the pinned simply
connected Chevalley--Demazure group scheme, and milestone L1 for the equation
`Frob_q (x_α(t)) = x_α(t ^ q)` on it. This file closes neither: it supplies the explicit data in
the shape those milestones need it, on a carrier whose identification with the L0 one is owed by
Layer 9 of `EpsilonEridaniRoadmap/ReductiveGroups/README.md`. The lattice condition that identification
requires, namely that the Geck weights span the whole character lattice, holds only on the `E₈`,
`F₄` and `G₂` diagrams and is recorded in
`EpsilonEridani/GroupTheory/SpecificGroups/CFSG/Unimodular.lean`.
-/

public section

namespace EpsilonEridani

namespace ValidLieTypeIndex

noncomputable section

variable (d : ValidLieTypeIndex)

/-! ## The Geck point group and its root subgroups -/

/-- **The points of the Geck carrier of a valid Lie-type index**, taken over the algebraic closure
of its prime field: a subgroup of `GLₙ`, generally infinite, carrying the Bourbaki-numbered root
subgroups and weight torus that carrier comes with.

No finiteness, reductivity or maximality statement is attached to it, and it is *not* claimed to be
the pinned simply connected Chevalley--Demazure group of
`EpsilonEridani.DynkinType.simplyConnectedRootDatum` that milestone L0 of
`EpsilonEridaniRoadmap/CFSGStatement/README.md` asks for: identifying the two is Layer 9 work of
`EpsilonEridaniRoadmap/ReductiveGroups/README.md`, and this file neither performs nor assumes it. -/
abbrev geckPoints :
    Subgroup (Matrix.GeneralLinearGroup
      (Fin (d.dynkinType.geckDim d.dynkinType_valid)) d.Closure) :=
  d.dynkinType.geckPoints d.dynkinType_valid d.Closure

/-- The Geck point group as a type, with the group structure it inherits as a subgroup of
`GLₙ` over the algebraic closure. It is named for the carrier it is built from rather than as an
ambient group, since the identification with the L0 carrier is not available. -/
abbrev GeckGroup : Type := ↥d.geckPoints

/-- **The numbered root subgroups of the Geck point group.** The left summand indexes the raising
generators and the right summand the lowering generators of the pinned Bourbaki numbering, so
`geckRootSubgroup d (.inl i)` is the simple root subgroup `x_{α_i}`. -/
def geckRootSubgroup (i : Fin d.dynkinType.rank ⊕ Fin d.dynkinType.rank) :
    Multiplicative d.Closure →* GeckGroup d :=
  d.dynkinType.geckRootSubgroupPoints d.dynkinType_valid i d.Closure

/-- The general linear matrix underlying a root-subgroup point is the represented Geck
root-subgroup matrix of the same parameter. -/
@[simp]
theorem coe_geckRootSubgroup (i : Fin d.dynkinType.rank ⊕ Fin d.dynkinType.rank)
    (u : Multiplicative d.Closure) :
    (d.geckRootSubgroup i u : Matrix.GeneralLinearGroup
        (Fin (d.dynkinType.geckDim d.dynkinType_valid)) d.Closure) =
      d.dynkinType.geckRootSubgroupMatrix d.dynkinType_valid i
        ((AdditiveGroup.gaPointsMulEquiv (R := ℤ) (A := d.Closure)).symm u) :=
  d.dynkinType.coe_geckRootSubgroupPoints d.dynkinType_valid i d.Closure u

/-! ## The pinned weight torus -/

/-- **The split weight torus of the Geck point group of a valid Lie-type index**, of rank the rank
of the index: the diagonal points through which the Geck coordinate weights act. Together with
`EpsilonEridani.ValidLieTypeIndex.geckRootSubgroup` it is the pinned data of the carrier that the
conjugation equations below are stated against.

As for the point group itself, no maximality statement is attached to it, and it is not claimed to
be the split maximal torus of a pinned simply connected Chevalley--Demazure group. -/
def geckWeightTorus : (Fin d.rank → d.Closureˣ) →* GeckGroup d :=
  d.dynkinType.geckWeightTorusPoints d.dynkinType_valid d.Closure

/-- The weight torus of an index is the represented weight torus of the pinned Geck carrier of the
Dynkin type it names, over the algebraic closure of the prime field of the index. -/
theorem geckWeightTorus_def : d.geckWeightTorus =
    d.dynkinType.geckWeightTorusPoints d.dynkinType_valid d.Closure := by
  rw [geckWeightTorus]

/-- The general linear matrix underlying a weight-torus point is the diagonal matrix of the Geck
weight characters at that point. -/
@[simp]
theorem coe_geckWeightTorus (s : Fin d.rank → d.Closureˣ) :
    (d.geckWeightTorus s : Matrix.GeneralLinearGroup
        (Fin (d.dynkinType.geckDim d.dynkinType_valid)) d.Closure) =
      d.dynkinType.geckTorusMatrix d.dynkinType_valid s := by
  rw [geckWeightTorus_def]
  exact d.dynkinType.coe_geckWeightTorusPoints d.dynkinType_valid d.Closure s

/-- **The pinning equation of the Geck carrier of an index, at a named simple root.** Conjugating
the numbered raising subgroup at Bourbaki node `i` by a weight-torus point `s` rescales its
parameter by `α_i(s)`, where `α_i` is the simple root of the pinned simply connected root datum of
the Dynkin type the index names, at the same node.

The character is read in that root datum rather than as a row of the Cartan matrix: the datum is
the one attached to `EpsilonEridani.ValidLieTypeIndex.dynkinType`, so it carries the Bourbaki node
numbering that numbers the root subgroups here, and node `i` on either side is the same node. -/
@[simp]
theorem geckWeightTorus_conj_geckRootSubgroup_root_simpleIndex (i : Fin d.rank)
    (s : Fin d.rank → d.Closureˣ) (u : Multiplicative d.Closure) :
    d.geckWeightTorus s * d.geckRootSubgroup (.inl i) u * (d.geckWeightTorus s)⁻¹ =
      d.geckRootSubgroup (.inl i)
        (Multiplicative.ofAdd
          ((torusCharacter s
              ((d.dynkinType.simplyConnectedRootDatum d.dynkinType_valid).root
                (d.dynkinType.simpleIndex d.dynkinType_valid i)) : d.Closure) *
            Multiplicative.toAdd u)) := by
  rw [geckWeightTorus_def]
  exact d.dynkinType.geckWeightTorusPoints_conj_geckRootSubgroupPoints_root_simpleIndex
    d.dynkinType_valid i d.Closure s u

/-- **The pinning equation of the Geck carrier of an index, at the negative of a named simple
root.** -/
@[simp]
theorem geckWeightTorus_conj_geckRootSubgroup_neg_root_simpleIndex (i : Fin d.rank)
    (s : Fin d.rank → d.Closureˣ) (u : Multiplicative d.Closure) :
    d.geckWeightTorus s * d.geckRootSubgroup (.inr i) u * (d.geckWeightTorus s)⁻¹ =
      d.geckRootSubgroup (.inr i)
        (Multiplicative.ofAdd
          ((torusCharacter s
              (-(d.dynkinType.simplyConnectedRootDatum d.dynkinType_valid).root
                (d.dynkinType.simpleIndex d.dynkinType_valid i)) : d.Closure) *
            Multiplicative.toAdd u)) := by
  rw [geckWeightTorus_def]
  exact d.dynkinType.geckWeightTorusPoints_conj_geckRootSubgroupPoints_neg_root_simpleIndex
    d.dynkinType_valid i d.Closure s u

/-! ## The Frobenius endomorphism -/

/-- **The `q`-power Frobenius endomorphism of the Geck point group**, for `q` the field order
recorded by the index. It is the carrier-level companion of the field-level
`EpsilonEridani.ValidLieTypeIndex.frobeniusEquiv`, and like it is defined on every branch: the untwisted
branches take it as their Steinberg map, the graph-twisted branches compose it with a diagram
automorphism, and the Suzuki--Ree and Tits branches take an odd power of a half-Frobenius whose
square it is. -/
def geckFrobenius : GeckGroup d →* GeckGroup d :=
  d.dynkinType.geckFrobenius d.dynkinType_valid d.characteristic d.fieldExponent d.Closure

/-- The Frobenius is that of the pinned Geck carrier at the exponent recorded by the index. This is
its unfolding lemma; the definition itself stays sealed. -/
theorem geckFrobenius_def : d.geckFrobenius =
    d.dynkinType.geckFrobenius d.dynkinType_valid d.characteristic d.fieldExponent d.Closure := by
  rw [geckFrobenius]

/-- The Frobenius acts on the Geck point group by raising every matrix entry to the `q`-th
power. -/
@[simp]
theorem coe_geckFrobenius_apply (g : GeckGroup d)
    (r c : Fin (d.dynkinType.geckDim d.dynkinType_valid)) :
    ((d.geckFrobenius g : Matrix.GeneralLinearGroup
          (Fin (d.dynkinType.geckDim d.dynkinType_valid)) d.Closure) :
        Matrix _ _ d.Closure) r c =
      ((g : Matrix.GeneralLinearGroup
          (Fin (d.dynkinType.geckDim d.dynkinType_valid)) d.Closure) :
        Matrix _ _ d.Closure) r c ^ d.fieldOrder := by
  rw [d.fieldOrder_eq_characteristic_pow]
  exact d.dynkinType.coe_geckFrobenius_apply d.dynkinType_valid _ _ _ g r c

/-- **The Frobenius raises the parameter of every numbered root subgroup to the `q`-th power.** On
a simple root subgroup this is the equation `Frob_q (x_α(t)) = x_α(t ^ q)` that milestone L1 asks
of the untwisted families, proved here on the Geck carrier. -/
@[simp]
theorem geckFrobenius_geckRootSubgroup (i : Fin d.dynkinType.rank ⊕ Fin d.dynkinType.rank)
    (u : Multiplicative d.Closure) :
    d.geckFrobenius (d.geckRootSubgroup i u) =
      d.geckRootSubgroup i (Multiplicative.ofAdd (Multiplicative.toAdd u ^ d.fieldOrder)) := by
  rw [d.fieldOrder_eq_characteristic_pow]
  exact d.dynkinType.geckFrobenius_geckRootSubgroupPoints d.dynkinType_valid
    d.characteristic d.fieldExponent d.Closure i u

/-- **The prime-field Frobenius endomorphism of the Geck point group**, the `p`-power map for `p`
the defining characteristic. The `q`-power Frobenius `EpsilonEridani.ValidLieTypeIndex.geckFrobenius` is
its `e`-th power, for `e` the field exponent the index records, by
`geckFrobenius_eq_geckPrimeFrobenius_pow`, so the two agree on an index of prime field
order. -/
def geckPrimeFrobenius : GeckGroup d →* GeckGroup d :=
  d.dynkinType.geckFrobenius d.dynkinType_valid d.characteristic 1 d.Closure

/-- The prime-field Frobenius is that of the pinned Geck carrier at exponent one. This is its
unfolding lemma; the definition itself stays sealed. -/
theorem geckPrimeFrobenius_def : d.geckPrimeFrobenius =
    d.dynkinType.geckFrobenius d.dynkinType_valid d.characteristic 1 d.Closure := by
  rw [geckPrimeFrobenius]

/-- The prime-field Frobenius acts on the Geck point group by raising every matrix entry to the
`p`-th power, for `p` the defining characteristic. -/
@[simp]
theorem coe_geckPrimeFrobenius_apply (g : GeckGroup d)
    (r c : Fin (d.dynkinType.geckDim d.dynkinType_valid)) :
    ((d.geckPrimeFrobenius g : Matrix.GeneralLinearGroup
          (Fin (d.dynkinType.geckDim d.dynkinType_valid)) d.Closure) :
        Matrix _ _ d.Closure) r c =
      ((g : Matrix.GeneralLinearGroup
          (Fin (d.dynkinType.geckDim d.dynkinType_valid)) d.Closure) :
        Matrix _ _ d.Closure) r c ^ d.characteristic := by
  rw [geckPrimeFrobenius_def]
  simpa only [pow_one] using d.dynkinType.coe_geckFrobenius_apply d.dynkinType_valid
    d.characteristic 1 d.Closure g r c

/-- **The prime-field Frobenius raises the parameter of every numbered root subgroup to the `p`-th
power.** On a simple root subgroup this reads `Frob_p (x_α(t)) = x_α(t ^ p)`. -/
@[simp]
theorem geckPrimeFrobenius_geckRootSubgroup
    (i : Fin d.dynkinType.rank ⊕ Fin d.dynkinType.rank) (u : Multiplicative d.Closure) :
    d.geckPrimeFrobenius (d.geckRootSubgroup i u) =
      d.geckRootSubgroup i (Multiplicative.ofAdd (Multiplicative.toAdd u ^ d.characteristic)) := by
  have h := d.dynkinType.geckFrobenius_geckRootSubgroupPoints d.dynkinType_valid
    d.characteristic 1 d.Closure i u
  rw [pow_one] at h
  exact h

-- The `show` reads the prime-field Frobenius in the endomorphism monoid of the Geck point group,
-- there being no power operation on `MonoidHom` itself; this is the form
-- `EpsilonEridani.DynkinType.geckFrobenius_pow` states the carrier's iteration law in.
/-- **The `q`-power Frobenius is the `e`-th power of the prime-field Frobenius**, for `e` the field
exponent the index records. -/
theorem geckFrobenius_eq_geckPrimeFrobenius_pow :
    d.geckFrobenius = (show Monoid.End _ from d.geckPrimeFrobenius) ^ d.fieldExponent := by
  rw [geckFrobenius_def, geckPrimeFrobenius_def, DynkinType.geckFrobenius_pow, Nat.one_mul]

/-- **The prime-field Frobenius raises every coordinate of a weight-torus point to the `p`-th
power.** -/
@[simp]
theorem geckPrimeFrobenius_geckWeightTorus (s : Fin d.rank → d.Closureˣ) :
    d.geckPrimeFrobenius (d.geckWeightTorus s) = d.geckWeightTorus (s ^ d.characteristic) := by
  rw [geckPrimeFrobenius_def, geckWeightTorus_def]
  exact (d.dynkinType.geckFrobenius_geckWeightTorusPoints d.dynkinType_valid d.characteristic 1
    d.Closure s).trans (by rw [pow_one])

/-- **The Frobenius raises every coordinate of a weight-torus point to the `q`-th power.** -/
@[simp]
theorem geckFrobenius_geckWeightTorus (s : Fin d.rank → d.Closureˣ) :
    d.geckFrobenius (d.geckWeightTorus s) = d.geckWeightTorus (s ^ d.fieldOrder) := by
  rw [d.fieldOrder_eq_characteristic_pow, geckFrobenius_def, geckWeightTorus_def]
  exact d.dynkinType.geckFrobenius_geckWeightTorusPoints d.dynkinType_valid
    d.characteristic d.fieldExponent d.Closure s

/-- **A weight-torus point whose coordinates lie in the field of definition is fixed by the
Frobenius.** Writing `𝔽_q` for `EpsilonEridani.ValidLieTypeIndex.fixedField`, these are the weight-torus
points with coordinates in `𝔽_q`; that they exhaust the weight-torus points of the Frobenius-fixed
group, or that they form a maximal torus of it, is not claimed. -/
theorem geckWeightTorus_mem_fixedSubgroup_geckFrobenius (s : Fin d.rank → d.Closureˣ)
    (hs : ∀ k, (s k : d.Closure) ∈ d.fixedField) :
    d.geckWeightTorus s ∈ fixedSubgroup d.geckFrobenius := by
  rw [mem_fixedSubgroup, geckFrobenius_geckWeightTorus]
  refine congrArg _ (funext fun k => Units.ext ?_)
  rw [Pi.pow_apply, Units.val_pow_eq_pow_val]
  exact (d.mem_fixedField).1 (hs k)

/-- **A point of the Geck point group is fixed by the Frobenius exactly when all of its matrix
entries lie in the field of definition.** Writing `𝔽_q` for `EpsilonEridani.ValidLieTypeIndex.fixedField`,
the copy of the field of `q` elements inside the algebraic closure, the Frobenius-fixed group is
therefore the group of points of the Geck carrier whose entries lie in `𝔽_q`.

This is deliberately not a `simp` lemma: `EpsilonEridani.fixedSubgroup` is `MonoidHom.eqLocus` against the
identity, so `simp` rewrites its left-hand side to `d.geckFrobenius g = g` through the Mathlib
`simp` lemma `MonoidHom.mem_eqLocus`, and the `simpNF` linter rejects the annotation. -/
theorem mem_fixedSubgroup_geckFrobenius_iff (g : GeckGroup d) :
    g ∈ fixedSubgroup d.geckFrobenius ↔
      ∀ r c, ((g : Matrix.GeneralLinearGroup
          (Fin (d.dynkinType.geckDim d.dynkinType_valid)) d.Closure) :
        Matrix (Fin (d.dynkinType.geckDim d.dynkinType_valid))
          (Fin (d.dynkinType.geckDim d.dynkinType_valid)) d.Closure) r c ∈
        d.fixedField := by
  rw [mem_fixedSubgroup, geckFrobenius_def,
    d.dynkinType.geckFrobenius_eq_self_iff d.dynkinType_valid _ _ _ g]
  simp only [mem_frobeniusFixedSubring, ValidLieTypeIndex.mem_fixedField,
    d.fieldOrder_eq_characteristic_pow]

end

end ValidLieTypeIndex

end EpsilonEridani
