/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.CategoryTheory.Sites.CoversTop.Basic

/-!
# Common refinements of covering families

This file provides the cover-theoretic common refinement construction used by local
trivializations. It reuses Mathlib's `GrothendieckTopology.intersection_covering` theorem; no
formalization is vendored.
-/

public section

open CategoryTheory

universe u v

namespace CategoryTheory.GrothendieckTopology.CoversTop

variable {C : Type u} [Category.{v} C]

/-- A common refinement of two covering families.

Each object in the refined family admits arrows to one member of each original family. -/
structure CommonRefinement (J : GrothendieckTopology C) {I₁ I₂ : Type*}
    (X₁ : I₁ → C) (X₂ : I₂ → C) where
  /-- The indexing type of the common refinement. -/
  I : Type u
  /-- The objects in the common refinement. -/
  X : I → C
  /-- The member of the first covering family above each refined object. -/
  leftIndex : I → I₁
  /-- The arrow from each refined object to its member of the first covering family. -/
  left : ∀ i, X i ⟶ X₁ (leftIndex i)
  /-- The member of the second covering family above each refined object. -/
  rightIndex : I → I₂
  /-- The arrow from each refined object to its member of the second covering family. -/
  right : ∀ i, X i ⟶ X₂ (rightIndex i)
  /-- The refined family covers the top. -/
  coversTop : J.CoversTop X

/-- Construct a common refinement of two covering families.

The refined family is indexed by the objects admitting arrows to a member of each original
family. Its covering property follows by applying `intersection_covering` to the two original
sieves and then enlarging that intersection to the sieve generated by the refined family. -/
noncomputable def commonRefinement {I₁ I₂ : Type*} {X₁ : I₁ → C} {X₂ : I₂ → C}
    {J : GrothendieckTopology C} (h₁ : J.CoversTop X₁) (h₂ : J.CoversTop X₂) :
    CommonRefinement J X₁ X₂ := by
  let I := {W : C // (∃ i, Nonempty (W ⟶ X₁ i)) ∧ (∃ j, Nonempty (W ⟶ X₂ j))}
  let leftIndex : I → I₁ := fun w => w.2.1.choose
  let left : ∀ w : I, w.1 ⟶ X₁ (leftIndex w) :=
    fun w => w.2.1.choose_spec.some
  let rightIndex : I → I₂ := fun w => w.2.2.choose
  let right : ∀ w : I, w.1 ⟶ X₂ (rightIndex w) :=
    fun w => w.2.2.choose_spec.some
  exact
    { I := I
      X := Subtype.val
      leftIndex := leftIndex
      left := left
      rightIndex := rightIndex
      right := right
      coversTop := by
        intro A
        refine J.superset_covering ?_ (J.intersection_covering (h₁ A) (h₂ A))
        rintro Z f ⟨⟨i, ⟨a⟩⟩, ⟨j, ⟨b⟩⟩⟩
        exact ⟨⟨Z, ⟨⟨i, ⟨a⟩⟩, ⟨j, ⟨b⟩⟩⟩⟩, ⟨𝟙 Z⟩⟩ }

end CategoryTheory.GrothendieckTopology.CoversTop
