/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.Algebra.AlgebraicGroup.AdditiveGroup.CoordinateBaseChange
public import EpsilonEridani.Algebra.AlgebraicGroup.GeneralLinear.Coordinate.BaseChange
public import EpsilonEridani.Algebra.AlgebraicGroup.HopfIdeal.BaseChange
public import EpsilonEridani.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.Generated.Basic

/-!
# Base change of the group scheme generated by Kostant root subgroups

The Chevalley carrier `G` generated by the represented Kostant root subgroups is a closed subgroup
scheme of `GLₙ` over `ℤ`, presented as the quotient of the general-linear coordinate Hopf algebra
by the Hopf ideal `J` common to the kernels of all root-subgroup coordinate maps. This file
transports that presentation along `ℤ → A` for an arbitrary commutative ring `A`.

The base change `G_A` is cut out inside the base change of the ambient general-linear coordinate
algebra by the base-changed Hopf ideal `J_A`, and the base change of each root subgroup still
factors through it, with the same factorization the construction over `ℤ` provides. That is the
compatibility of the root-subgroup coordinate maps with base change: their factorizations do not
have to be rechosen over `A`.

Generation, on the other hand, only transports in one direction: the carrier generated over `A` by
the base-changed root subgroups is a closed subgroup scheme of `G_A`
(`kostantGeneratedBaseChangeIdeal_le_commonKernelHopfIdeal`), and equality is not claimed, since a
Hopf ideal of `A ⊗[ℤ] O(GLₙ)` killed by every base-changed root-subgroup map need not descend.

The second half of the file removes the tensor factor from the ambient group. Transporting the
presentation along `A ⊗[ℤ] O(GLₙ) ≅ O(GLₙ over A)` exhibits `G_A` as a closed subgroup scheme of
`GLₙ` over `A` itself, cut out by the Hopf ideal
`kostantGeneratedGeneralLinearBaseChangeIdeal`, and each
base-changed root subgroup becomes a morphism `𝔾ₐ → G_A` of group schemes over `A` after the same
identification is made on the additive coordinate algebra. This is the form a consumer working in
a fixed characteristic asks for: it base-changes the Chevalley carrier to `𝔽_p` or to an algebraic
closure and wants a subgroup scheme of the general linear group over that field, not of a scalar
extension of the general linear group over `ℤ`.

## Main declarations

* `EpsilonEridani.UniversalEnvelopingAlgebra.kostantGeneratedBaseChangeIdeal`: the base change `J_A` of
  the defining Hopf ideal.
* `EpsilonEridani.UniversalEnvelopingAlgebra.kostantGeneratedBaseChangeIso`: the base change of the
  carrier is the quotient by `J_A`.
* `EpsilonEridani.UniversalEnvelopingAlgebra.kostantRootSubgroupBaseChangeGeneratedCoordinateMap`: the
  base-changed root subgroup, factored through the base-changed carrier.
* `mkQuotient_comp_kostantRootSubgroupBaseChangeGeneratedCoordinateMap`: the factorization
  recovers the base change of the root-subgroup coordinate map.
* `EpsilonEridani.UniversalEnvelopingAlgebra.kostantGeneratedBaseChangeIdeal_le_commonKernelHopfIdeal`:
  the carrier generated over `A` lies inside the base-changed carrier.
* `EpsilonEridani.UniversalEnvelopingAlgebra.kostantGeneratedGeneralLinearBaseChangeIdeal`: the Hopf ideal
  of the general-linear coordinate algebra *over `A`* which presents the base-changed carrier.
* `EpsilonEridani.UniversalEnvelopingAlgebra.kostantGeneratedGeneralLinearBaseChangeIso`: that
  presentation is the base change of the carrier over `ℤ`.
* `EpsilonEridani.UniversalEnvelopingAlgebra.kostantRootSubgroupGeneralLinearBaseChangeCoordinateMap`: the
  base-changed root subgroup over `A`.
* `kostantGeneratedGeneralLinearBaseChangeIdeal_le_commonKernelHopfIdeal`: over `A` too, the
  carrier generated by the root subgroups lies inside the base-changed carrier.

## References

This advances the Layer 9 milestone "base change along `ℤ → k` for any commutative ring `k`, and
the compatibility of the pinning with it" of `EpsilonEridaniRoadmap/ReductiveGroups/README.md`, which
milestone L0 of the CFSGStatement roadmap consumes when it base-changes a pinned
Chevalley--Demazure group to a prime field and its algebraic closure. See R. W. Carter, *Simple
Groups of Lie Type*, §4.4, and B. Conrad, *Reductive Group Schemes*, §1.
-/

public section

open CategoryTheory

namespace EpsilonEridani.UniversalEnvelopingAlgebra

universe u w

-- Match tensor products to the `ℤ`-algebra structure used by scalar extension.
attribute [local instance high] Algebra.toModule

variable {L : Type u} [LieRing L] [LieAlgebra ℚ L]
variable {I : Type w} {κ : Type*}
variable {V : Type} [AddCommGroup V] [Module ℚ V]

variable (e : I → L) (h : κ → L)
variable (ρ : _root_.UniversalEnvelopingAlgebra ℚ L →ₐ[ℚ] Module.End ℚ V)
variable (M : AddSubgroup V)
variable (hM : ∀ u ∈ kostantForm e h, ∀ m ∈ M, ρ u m ∈ M)
variable (hnil : ∀ i, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i))))
variable {n : ℕ} (b : Module.Basis (Fin n) ℤ M)
variable (A : Type*) [CommRing A]

/-- The base change along `ℤ → A` of the Hopf ideal defining the Chevalley carrier generated by
the represented Kostant root subgroups. -/
noncomputable def kostantGeneratedBaseChangeIdeal :
    HopfIdeal A
      (CommHopfAlgCat.baseChange (K := A) (GeneralLinear.coordinateHopfAlgebra ℤ n)) :=
  CommHopfAlgCat.baseChangeHopfIdeal (kostantGeneratedDefiningIdeal e h ρ M hM hnil b)

/-- The specialized base-changed defining ideal is the generic base change of the ideal defining
the Chevalley carrier over `ℤ`. -/
@[simp]
theorem kostantGeneratedBaseChangeIdeal_def :
    kostantGeneratedBaseChangeIdeal e h ρ M hM hnil b A =
      CommHopfAlgCat.baseChangeHopfIdeal
        (kostantGeneratedDefiningIdeal e h ρ M hM hnil b) := by
  unfold kostantGeneratedBaseChangeIdeal
  rfl

/-- The base change of the Chevalley carrier is the quotient of the base-changed general-linear
coordinate algebra by the base-changed defining ideal: base change of the group scheme and of its
presentation as a closed subgroup scheme agree. -/
noncomputable def kostantGeneratedBaseChangeIso :
    CommHopfAlgCat.quotient
        (CommHopfAlgCat.baseChange (K := A) (GeneralLinear.coordinateHopfAlgebra ℤ n))
        (kostantGeneratedBaseChangeIdeal e h ρ M hM hnil b A) ≅
      CommHopfAlgCat.baseChange (K := A)
        (CommHopfAlgCat.quotient (GeneralLinear.coordinateHopfAlgebra ℤ n)
          (kostantGeneratedDefiningIdeal e h ρ M hM hnil b)) :=
  CommHopfAlgCat.quotientBaseChangeIso (kostantGeneratedDefiningIdeal e h ρ M hM hnil b)

/-- The specialized identification of the base-changed carrier is compatible with the quotient
morphism presenting the carrier over `ℤ`. -/
@[simp]
theorem mkQuotient_comp_kostantGeneratedBaseChangeIso_hom :
    CommHopfAlgCat.mkQuotient
          (CommHopfAlgCat.baseChange (K := A) (GeneralLinear.coordinateHopfAlgebra ℤ n))
          (kostantGeneratedBaseChangeIdeal e h ρ M hM hnil b A) ≫
        (kostantGeneratedBaseChangeIso e h ρ M hM hnil b A).hom =
      CommHopfAlgCat.baseChangeMap
        (CommHopfAlgCat.mkQuotient (GeneralLinear.coordinateHopfAlgebra ℤ n)
          (kostantGeneratedDefiningIdeal e h ρ M hM hnil b)) := by
  unfold kostantGeneratedBaseChangeIdeal kostantGeneratedBaseChangeIso
  exact CommHopfAlgCat.mkQuotient_comp_quotientBaseChangeIso_hom (K := A)
    (kostantGeneratedDefiningIdeal e h ρ M hM hnil b)

/-- The `i`th base-changed root-subgroup coordinate map, factored through the base change of the
Chevalley carrier: the base change of the factorization over `ℤ`, read through the presentation of
the base change. -/
noncomputable def kostantRootSubgroupBaseChangeGeneratedCoordinateMap (i : I) :
    CommHopfAlgCat.quotient
        (CommHopfAlgCat.baseChange (K := A) (GeneralLinear.coordinateHopfAlgebra ℤ n))
        (kostantGeneratedBaseChangeIdeal e h ρ M hM hnil b A) ⟶
      CommHopfAlgCat.baseChange (K := A) (AdditiveGroup.coordinateHopfAlgebra ℤ) :=
  (kostantGeneratedBaseChangeIso e h ρ M hM hnil b A).hom ≫
    CommHopfAlgCat.baseChangeMap
      (kostantRootSubgroupGeneratedCoordinateMap e h ρ M hM hnil b i)

/-- Quotienting by the base-changed defining ideal and then applying the base-changed factored
root subgroup recovers the base change of the `i`th root-subgroup coordinate map. This is the
compatibility of the root-subgroup data with base change. -/
@[simp]
theorem mkQuotient_comp_kostantRootSubgroupBaseChangeGeneratedCoordinateMap (i : I) :
    CommHopfAlgCat.mkQuotient
          (CommHopfAlgCat.baseChange (K := A) (GeneralLinear.coordinateHopfAlgebra ℤ n))
          (kostantGeneratedBaseChangeIdeal e h ρ M hM hnil b A) ≫
        kostantRootSubgroupBaseChangeGeneratedCoordinateMap e h ρ M hM hnil b A i =
      CommHopfAlgCat.baseChangeMap
        (kostantRootSubgroupCoordinateMap e h ρ M hM i (hnil i) b) := by
  rw [kostantRootSubgroupBaseChangeGeneratedCoordinateMap, ← Category.assoc,
    mkQuotient_comp_kostantGeneratedBaseChangeIso_hom,
    ← (CommHopfAlgCat.baseChangeFunctor (K := A)).map_comp,
    mkQuotient_comp_kostantRootSubgroupGeneratedCoordinateMap]

/-- Every base-changed root-subgroup coordinate map kills the base-changed defining ideal, so the
base-changed root subgroups all land in the base change of the Chevalley carrier. -/
theorem kostantGeneratedBaseChangeIdeal_toIdeal_le_ker (i : I) :
    (kostantGeneratedBaseChangeIdeal e h ρ M hM hnil b A).toIdeal ≤
      RingHom.ker
        (CommHopfAlgCat.baseChangeMap (K := A)
            (kostantRootSubgroupCoordinateMap e h ρ M hM i
              (hnil i) b)).hom.toAlgHom.toRingHom := by
  unfold kostantGeneratedBaseChangeIdeal
  rw [kostantGeneratedDefiningIdeal_def]
  exact (HopfIdeal.toIdeal_le_toIdeal.mpr
      (CommHopfAlgCat.baseChangeHopfIdeal_commonKernelHopfIdeal_le
        (K := A) fun i ↦ kostantRootSubgroupCoordinateMap e h ρ M hM i (hnil i) b)).trans
    (CommHopfAlgCat.commonKernelHopfIdeal_toIdeal_le_ker _ i)

/-- The Chevalley carrier generated over `A` by the base-changed root subgroups is a closed
subgroup scheme of the base change of the carrier generated over `ℤ`.

The reverse containment is not claimed: it asks a Hopf ideal of `A ⊗[ℤ] O(GLₙ)` killed by every
base-changed root-subgroup coordinate map to descend to `ℤ`. -/
theorem kostantGeneratedBaseChangeIdeal_le_commonKernelHopfIdeal :
    kostantGeneratedBaseChangeIdeal e h ρ M hM hnil b A ≤
      CommHopfAlgCat.commonKernelHopfIdeal fun i ↦
        CommHopfAlgCat.baseChangeMap (K := A)
          (kostantRootSubgroupCoordinateMap e h ρ M hM i (hnil i) b) := by
  unfold kostantGeneratedBaseChangeIdeal
  rw [kostantGeneratedDefiningIdeal_def]
  exact CommHopfAlgCat.baseChangeHopfIdeal_commonKernelHopfIdeal_le _

/-! ## The presentation inside the general linear group over the new base

Base change of the ambient general linear group is `GLₙ` over the new base, so the presentation
above can be read there. The identification used is
`EpsilonEridani.GeneralLinear.coordinateHopfAlgebraBaseChangeIso` on the ambient group and
`EpsilonEridani.AdditiveGroup.coordinateHopfAlgebraBaseChangeIso` on the parameter group. -/

/-- The Hopf ideal of the general-linear coordinate algebra over `A` which presents the base
change of the Chevalley carrier: the inverse image of the base-changed defining ideal under the
identification of `O(GLₙ)` over `A` with `A ⊗[ℤ] O(GLₙ)`. -/
noncomputable def kostantGeneratedGeneralLinearBaseChangeIdeal :
    HopfIdeal A (GeneralLinear.coordinateHopfAlgebra A n) :=
  (kostantGeneratedBaseChangeIdeal e h ρ M hM hnil b A).comapOfSurjective
    (GeneralLinear.coordinateHopfAlgebraBaseChangeIso ℤ A n).symm.hom.hom
    (ConcreteCategory.bijective_of_isIso
      (GeneralLinear.coordinateHopfAlgebraBaseChangeIso ℤ A n).symm.hom).2

/-- Membership in the general-linear defining ideal over `A` is membership of the transported
element in the base-changed defining ideal. -/
@[simp]
theorem mem_kostantGeneratedGeneralLinearBaseChangeIdeal_iff
    {x : GeneralLinear.coordinateHopfAlgebra A n} :
    x ∈ kostantGeneratedGeneralLinearBaseChangeIdeal e h ρ M hM hnil b A ↔
      (GeneralLinear.coordinateHopfAlgebraBaseChangeIso ℤ A n).inv.hom x ∈
        kostantGeneratedBaseChangeIdeal e h ρ M hM hnil b A :=
  HopfIdeal.mem_comapOfSurjective

/-- The transported pure tensor of every scalar and defining equation over `ℤ` belongs to the
general-linear base-change ideal over `A`. -/
theorem map_tmul_mem_kostantGeneratedGeneralLinearBaseChangeIdeal_of_mem (s : A)
    {y : GeneralLinear.coordinateHopfAlgebra ℤ n}
    (hy : y ∈ kostantGeneratedDefiningIdeal e h ρ M hM hnil b) :
    (GeneralLinear.coordinateHopfAlgebraBaseChangeIso ℤ A n).hom.hom (s ⊗ₜ[ℤ] y) ∈
      kostantGeneratedGeneralLinearBaseChangeIdeal e h ρ M hM hnil b A := by
  rw [mem_kostantGeneratedGeneralLinearBaseChangeIdeal_iff,
    CommHopfAlgCat.inv_hom_apply, kostantGeneratedBaseChangeIdeal_def]
  exact CommHopfAlgCat.tmul_mem_baseChangeHopfIdeal s hy

/-- The Chevalley carrier cut out inside `GLₙ` over `A` is the same closed subgroup scheme as the
one cut out inside the base change of `GLₙ` over `ℤ`. -/
private noncomputable def kostantGeneratedGeneralLinearBaseChangePresentationIso :
    CommHopfAlgCat.quotient (GeneralLinear.coordinateHopfAlgebra A n)
        (kostantGeneratedGeneralLinearBaseChangeIdeal e h ρ M hM hnil b A) ≅
      CommHopfAlgCat.quotient
        (CommHopfAlgCat.baseChange (K := A) (GeneralLinear.coordinateHopfAlgebra ℤ n))
        (kostantGeneratedBaseChangeIdeal e h ρ M hM hnil b A) :=
  CommHopfAlgCat.quotientIsoOfIso
    (GeneralLinear.coordinateHopfAlgebraBaseChangeIso ℤ A n).symm
    (kostantGeneratedBaseChangeIdeal e h ρ M hM hnil b A)

/-- Quotienting by the general-linear defining ideal over `A` and then transporting is the same as
transporting first and then quotienting by the base-changed defining ideal. -/
@[simp]
private theorem mkQuotient_comp_kostantGeneratedGeneralLinearBaseChangePresentationIso_hom :
    CommHopfAlgCat.mkQuotient (GeneralLinear.coordinateHopfAlgebra A n)
          (kostantGeneratedGeneralLinearBaseChangeIdeal e h ρ M hM hnil b A) ≫
        (kostantGeneratedGeneralLinearBaseChangePresentationIso e h ρ M hM hnil b A).hom =
      (GeneralLinear.coordinateHopfAlgebraBaseChangeIso ℤ A n).inv ≫
        CommHopfAlgCat.mkQuotient
          (CommHopfAlgCat.baseChange (K := A) (GeneralLinear.coordinateHopfAlgebra ℤ n))
          (kostantGeneratedBaseChangeIdeal e h ρ M hM hnil b A) :=
  CommHopfAlgCat.mkQuotient_comp_quotientIsoOfIso_hom
    (GeneralLinear.coordinateHopfAlgebraBaseChangeIso ℤ A n).symm
    (kostantGeneratedBaseChangeIdeal e h ρ M hM hnil b A)

/-- The Chevalley carrier presented inside `GLₙ` over `A` is the base change of the Chevalley
carrier over `ℤ`. -/
noncomputable def kostantGeneratedGeneralLinearBaseChangeIso :
    CommHopfAlgCat.quotient (GeneralLinear.coordinateHopfAlgebra A n)
        (kostantGeneratedGeneralLinearBaseChangeIdeal e h ρ M hM hnil b A) ≅
      CommHopfAlgCat.baseChange (K := A)
        (CommHopfAlgCat.quotient (GeneralLinear.coordinateHopfAlgebra ℤ n)
          (kostantGeneratedDefiningIdeal e h ρ M hM hnil b)) :=
  kostantGeneratedGeneralLinearBaseChangePresentationIso e h ρ M hM hnil b A ≪≫
    kostantGeneratedBaseChangeIso e h ρ M hM hnil b A

/-- The identification of the carrier presented over `A` with the base change of the carrier over
`ℤ` is compatible with the two quotient morphisms. -/
@[simp]
theorem mkQuotient_comp_kostantGeneratedGeneralLinearBaseChangeIso_hom :
    CommHopfAlgCat.mkQuotient (GeneralLinear.coordinateHopfAlgebra A n)
          (kostantGeneratedGeneralLinearBaseChangeIdeal e h ρ M hM hnil b A) ≫
        (kostantGeneratedGeneralLinearBaseChangeIso e h ρ M hM hnil b A).hom =
      (GeneralLinear.coordinateHopfAlgebraBaseChangeIso ℤ A n).inv ≫
        CommHopfAlgCat.baseChangeMap
          (CommHopfAlgCat.mkQuotient (GeneralLinear.coordinateHopfAlgebra ℤ n)
            (kostantGeneratedDefiningIdeal e h ρ M hM hnil b)) := by
  rw [kostantGeneratedGeneralLinearBaseChangeIso, Iso.trans_hom, ← Category.assoc,
    mkQuotient_comp_kostantGeneratedGeneralLinearBaseChangePresentationIso_hom, Category.assoc,
    mkQuotient_comp_kostantGeneratedBaseChangeIso_hom]

/-- The `i`th base-changed root subgroup, read as a morphism of coordinate Hopf algebras over `A`:
a morphism `𝔾ₐ → GLₙ` of group schemes over `A`. -/
noncomputable def kostantRootSubgroupGeneralLinearBaseChangeCoordinateMap
    (e : I → L) (h : κ → L)
    (ρ : _root_.UniversalEnvelopingAlgebra ℚ L →ₐ[ℚ] Module.End ℚ V)
    (M : AddSubgroup V)
    (hM : ∀ u ∈ kostantForm e h, ∀ m ∈ M, ρ u m ∈ M)
    (i : I) (hnil : IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i))))
    {n : ℕ} (b : Module.Basis (Fin n) ℤ M) (A : Type*) [CommRing A] :
    GeneralLinear.coordinateHopfAlgebra A n ⟶ AdditiveGroup.coordinateHopfAlgebra A :=
  (GeneralLinear.coordinateHopfAlgebraBaseChangeIso ℤ A n).inv ≫
    CommHopfAlgCat.baseChangeMap
      (kostantRootSubgroupCoordinateMap e h ρ M hM i hnil b) ≫
    (AdditiveGroup.coordinateHopfAlgebraBaseChangeIso ℤ A).hom

/-- The `i`th base-changed root subgroup over `A`, factored through the Chevalley carrier
presented inside `GLₙ` over `A`. -/
noncomputable def kostantRootSubgroupGeneralLinearBaseChangeGeneratedCoordinateMap (i : I) :
    CommHopfAlgCat.quotient (GeneralLinear.coordinateHopfAlgebra A n)
        (kostantGeneratedGeneralLinearBaseChangeIdeal e h ρ M hM hnil b A) ⟶
      AdditiveGroup.coordinateHopfAlgebra A :=
  (kostantGeneratedGeneralLinearBaseChangePresentationIso e h ρ M hM hnil b A).hom ≫
    kostantRootSubgroupBaseChangeGeneratedCoordinateMap e h ρ M hM hnil b A i ≫
    (AdditiveGroup.coordinateHopfAlgebraBaseChangeIso ℤ A).hom

/-- Quotienting by the general-linear defining ideal over `A` and then applying the factored root
subgroup recovers the base-changed root subgroup itself. This is the compatibility of the
root-subgroup data with base change, stated over `A` throughout. -/
@[simp]
theorem mkQuotient_comp_kostantRootSubgroupGeneralLinearBaseChangeGeneratedCoordinateMap (i : I) :
    CommHopfAlgCat.mkQuotient (GeneralLinear.coordinateHopfAlgebra A n)
          (kostantGeneratedGeneralLinearBaseChangeIdeal e h ρ M hM hnil b A) ≫
        kostantRootSubgroupGeneralLinearBaseChangeGeneratedCoordinateMap
          e h ρ M hM hnil b A i =
      kostantRootSubgroupGeneralLinearBaseChangeCoordinateMap e h ρ M hM i (hnil i) b A := by
  rw [kostantRootSubgroupGeneralLinearBaseChangeGeneratedCoordinateMap, ← Category.assoc,
    mkQuotient_comp_kostantGeneratedGeneralLinearBaseChangePresentationIso_hom, Category.assoc,
    ← Category.assoc (CommHopfAlgCat.mkQuotient _ _),
    mkQuotient_comp_kostantRootSubgroupBaseChangeGeneratedCoordinateMap,
    kostantRootSubgroupGeneralLinearBaseChangeCoordinateMap]

/-- Every root subgroup over `A` kills the general-linear defining ideal over `A`, so all of them
land in the Chevalley carrier presented there. -/
theorem kostantGeneratedGeneralLinearBaseChangeIdeal_toIdeal_le_ker (i : I) :
    (kostantGeneratedGeneralLinearBaseChangeIdeal e h ρ M hM hnil b A).toIdeal ≤
      RingHom.ker
        (kostantRootSubgroupGeneralLinearBaseChangeCoordinateMap
          e h ρ M hM i (hnil i) b A).hom.toAlgHom.toRingHom := by
  intro x hx
  have hbase := kostantGeneratedBaseChangeIdeal_toIdeal_le_ker e h ρ M hM hnil b A i
    (HopfIdeal.mem_toIdeal.mpr
      ((mem_kostantGeneratedGeneralLinearBaseChangeIdeal_iff
        e h ρ M hM hnil b A).mp hx))
  rw [RingHom.mem_ker] at hbase ⊢
  rw [kostantRootSubgroupGeneralLinearBaseChangeCoordinateMap]
  have hbase' :
      (CommHopfAlgCat.baseChangeMap
          (kostantRootSubgroupCoordinateMap e h ρ M hM i (hnil i) b)).hom
          ((GeneralLinear.coordinateHopfAlgebraBaseChangeIso ℤ A n).inv x) = 0 := by
    simpa only [BialgHom.coe_toAlgHom, AlgHom.toRingHom_eq_coe, RingHom.coe_coe] using hbase
  simp only [CommHopfAlgCat.hom_comp, BialgHom.coe_toAlgHom,
    AlgHom.toRingHom_eq_coe, RingHom.coe_coe, BialgHom.comp_apply]
  rw [hbase', map_zero]

/-- The Chevalley carrier generated over `A` by the root subgroups over `A` is a closed subgroup
scheme of the base change of the carrier over `ℤ`, now inside `GLₙ` over `A`.

As over the base-changed ambient group, the reverse containment is not claimed. -/
theorem kostantGeneratedGeneralLinearBaseChangeIdeal_le_commonKernelHopfIdeal :
    kostantGeneratedGeneralLinearBaseChangeIdeal e h ρ M hM hnil b A ≤
      CommHopfAlgCat.commonKernelHopfIdeal
        (fun i ↦ kostantRootSubgroupGeneralLinearBaseChangeCoordinateMap
          e h ρ M hM i (hnil i) b A) :=
  (CommHopfAlgCat.le_commonKernelHopfIdeal_iff _ _).mpr
    (kostantGeneratedGeneralLinearBaseChangeIdeal_toIdeal_le_ker e h ρ M hM hnil b A)

end EpsilonEridani.UniversalEnvelopingAlgebra
