/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.Algebra.AlgebraicGroup.HopfIdeal.Equalizer
public import EpsilonEridani.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.Generated.Basic
import EpsilonEridani.AlgebraicGeometry.AffineGroupScheme.HopfSpec

/-!
# Homomorphisms out of the generated Chevalley carrier are determined by the root subgroups

The closed subgroup scheme of `GLₙ` generated by the represented Kostant root subgroups is, by
construction, the smallest one through which every `xᵢ : 𝔾ₐ ⟶ GLₙ` factors. This file records
what that minimality buys: a homomorphism out of the generated group scheme is *determined* by its
restrictions to the root subgroups.

The argument is the scheme-theoretic replacement for "a group is generated by a family of
subgroups, so a homomorphism is determined on generators". Two homomorphisms agreeing on every
root subgroup have an equalizer, which is a closed subgroup scheme containing all of them;
minimality forces it to be everything. In coordinate terms the equalizer Hopf ideal is squeezed
below the defining ideal, so it vanishes.

This supplies the generated-carrier universal property needed by Layer 9's explicit
Chevalley--Demazure construction: the theorems below quantify over the *whole* family
`e : I → L` of represented root subgroups used to define the carrier. They do not establish the
separate isomorphism theorem for pinned groups, whose uniqueness statement only assumes agreement
on the simple root subgroups.

## Main declarations

* `EpsilonEridani.UniversalEnvelopingAlgebra.kostantGeneratedCoordinate_hom_ext`: two coordinate
  morphisms into the generated Chevalley carrier agreeing on every root subgroup are equal.
* `EpsilonEridani.UniversalEnvelopingAlgebra.kostantGeneratedGroupScheme_hom_ext`: the same statement for
  morphisms of affine group schemes out of the generated group scheme.

## References

The determination of a homomorphism by a generating family of root subgroups is standard in the
Chevalley--Demazure construction; see J. E. Humphreys, *Linear Algebraic Groups*, §27, and
R. W. Carter, *Simple Groups of Lie Type*, §12.2. It advances the explicit
"Chevalley--Demazure construction" and "Root subgroup maps" targets in Layer 9 of
`EpsilonEridaniRoadmap/ReductiveGroups/README.md`.
-/

public section

open AlgebraicGeometry CategoryTheory

namespace EpsilonEridani.UniversalEnvelopingAlgebra

universe u w

-- Match tensor products to the `ℤ`-algebra structure used by scalar extension.
attribute [local instance high] Algebra.toModule

variable {L : Type u} [LieRing L] [LieAlgebra ℚ L]
variable {I : Type w} {κ : Type*}
variable {V : Type} [AddCommGroup V] [Module ℚ V]

variable (e : I → L) (h : κ → L)
variable (ρ : _root_.UniversalEnvelopingAlgebra ℚ L →ₐ[ℚ] Module.End ℚ V)
variable (M : AddSubgroup V)
variable (hM : ∀ u ∈ kostantForm e h, ∀ m ∈ M, ρ u m ∈ M)
variable (hnil : ∀ i, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i))))
variable {n : ℕ} (b : Module.Basis (Fin n) ℤ M)

/-- **Coordinate rigidity.** Two morphisms of commutative Hopf algebras into the coordinate algebra
of the generated Chevalley carrier that agree after composing with every root-subgroup coordinate
map are equal.

Contravariantly: a homomorphism of affine group schemes out of the group scheme generated by the
Kostant root subgroups is determined by its restrictions to those root subgroups. -/
theorem kostantGeneratedCoordinate_hom_ext {Y : _root_.CommHopfAlgCat.{0} ℤ}
    (u v : Y ⟶ CommHopfAlgCat.quotient (GeneralLinear.coordinateHopfAlgebra ℤ n)
      (kostantGeneratedDefiningIdeal e h ρ M hM hnil b))
    (huv : ∀ i, u ≫ kostantRootSubgroupGeneratedCoordinateMap e h ρ M hM hnil b i =
      v ≫ kostantRootSubgroupGeneratedCoordinateMap e h ρ M hM hnil b i) :
    u = v :=
  CommHopfAlgCat.hom_ext_of_le_iff_forall_toIdeal_le_ker
    (le_kostantGeneratedDefiningIdeal_iff e h ρ M hM hnil b)
    (mkQuotient_comp_kostantRootSubgroupGeneratedCoordinateMap e h ρ M hM hnil b) u v huv

/-- **Rigidity of the generated Chevalley carrier.** Two homomorphisms of affine group schemes out
of the group scheme generated by the represented Kostant root subgroups are equal as soon as they
agree after composing with every root subgroup `xᵢ : 𝔾ₐ ⟶ G`.

In particular, there is at most one endomorphism of the carrier realizing a prescribed action on
the whole generating family. -/
theorem kostantGeneratedGroupScheme_hom_ext {Y : _root_.CommHopfAlgCat.{0} ℤ}
    (φ ψ : kostantGeneratedGroupScheme e h ρ M hM hnil b ⟶
      (hopfSpec (CommRingCat.of ℤ)).obj (Opposite.op Y))
    (hφψ : ∀ i, kostantRootSubgroupToGenerated e h ρ M hM hnil b i ≫ φ =
      kostantRootSubgroupToGenerated e h ρ M hM hnil b i ≫ ψ) :
    φ = ψ := by
  refine CommHopfAlgCat.hom_ext_of_preimage_unop_eq φ ψ
    (kostantGeneratedCoordinate_hom_ext e h ρ M hM hnil b _ _ fun i => ?_)
  refine CommHopfAlgCat.preimage_unop_comp_eq_of_hopfSpec_map_comp_eq _ φ ψ ?_
  have hi := hφψ i
  rw [kostantRootSubgroupToGenerated_def, Category.assoc, Category.assoc] at hi
  exact (cancel_epi (eqToHom (AdditiveGroup.groupScheme_def ℤ))).1 hi

end EpsilonEridani.UniversalEnvelopingAlgebra
