/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.Group.Hom.Basic
public import Mathlib.Tactic.Group

/-!
# Building a homomorphism from a ternary relation

Mathlib builds a `MonoidHom` out of a bare map from the two-variable identities
`f (x * y) = f x * f y` (`MonoidHom.mk'`) and `f (x * y⁻¹) = f x * (f y)⁻¹`
(`MonoidHom.ofMapMulInv`). Some maps are not naturally presented that way: they are defined by a
*symmetric ternary* condition, and what one can prove about them directly is that they send triples
with product `1` to triples with product `1`. The motivating example is the descent map on an
elliptic curve, whose defining property is that the classes of three collinear points multiply to
`1` — collinearity being symmetric in the three points, whereas the group law is not.

## Main results

* `MonoidHom.ofMapMulMulEqOne`: a map of groups with `f 1 = 1` that sends triples with product `1`
  to triples with product `1` is a homomorphism, and `MonoidHom.coe_ofMapMulMulEqOne` says it is
  the original map. The additive versions are generated by `to_additive`.

## Provenance

Adapted, with the author's proof, from Michael Stoll's `EllipticCurves` project
(`github.com/MichaelStollBayreuth/EllipticCurves`, Apache-2.0, pinned by
`EpsilonEridaniRoadmap/EllipticCurves/README.md` at `66889eada51a`), `EllipticCurves/Mathlib/Basic.lean`.
-/

public section

variable {G H : Type*} [Group G] [Group H]

/-- A map `f` between groups with `f 1 = 1` that sends triples with product `1` to triples
with product `1` is a homomorphism. Useful when a map is naturally defined via a symmetric
ternary relation, like collinearity on a cubic curve. -/
@[to_additive /-- A map `f` between additive groups with `f 0 = 0` that sends triples with
sum `0` to triples with sum `0` is a homomorphism. Useful when a map is naturally defined via
a symmetric ternary relation, like collinearity on a cubic curve. -/]
def MonoidHom.ofMapMulMulEqOne {f : G → H} (hf₁ : f 1 = 1)
    (hf : ∀ a b c, a * b * c = 1 → f a * f b * f c = 1) :
    G →* H :=
  .ofMapMulInv f fun x y ↦ by
    have (x : G) : f x⁻¹ = (f x)⁻¹ := by
      rw [← mul_eq_one_iff_eq_inv', ← mul_one (_ * _)]
      nth_rewrite 1 [← hf₁]
      exact hf _ _ _ <| by group
    rw [eq_mul_inv_iff_mul_eq, eq_comm, ← inv_mul_eq_one, ← mul_assoc, ← this]
    exact hf _ _ _ <| by group

/-- The homomorphism built by `MonoidHom.ofMapMulMulEqOne` has the original map as its
underlying function. -/
@[to_additive (attr := simp) /-- The homomorphism built by the additive constructor has the
original map as its underlying function. -/]
lemma MonoidHom.coe_ofMapMulMulEqOne {f : G → H} (hf₁ : f 1 = 1)
    (hf : ∀ a b c, a * b * c = 1 → f a * f b * f c = 1) :
    ⇑(ofMapMulMulEqOne hf₁ hf) = f :=
  (rfl)

end
