/-
Copyright (c) 2026 Chris Birkbeck. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Birkbeck, Claude
-/
module

public import EpsilonEridani.GroupTheory.Index.Basic
public import EpsilonEridani.NumberTheory.HeckeRing.GL2.Delta0
public import Mathlib.NumberTheory.ModularForms.CongruenceSubgroups

-- the Γ₀ unit-entry lemma and `withCenter_le_Gamma0`, both only inside proofs
import EpsilonEridani.NumberTheory.ModularForms.CongruenceSubgroups.Basic

/-!
# The Hecke triple of `Γ₀(N)`

The image of `Γ₀(N)` in `GL₂(ℚ)` forms a Hecke triple with the submonoid `Δ₀(N)`. This is the
setting of Shimura §3.3: the Hecke ring `R(Γ₀(N), Δ₀(N))` whose operators act on
`M_k(Γ₀(N))`.

`Δ₀(N)` is shared with the Hecke triple of `Γ₁(N)` and lives in
`EpsilonEridani.NumberTheory.HeckeRing.GL2.Delta0`; nothing about it refers to either group. What is
specific here is which group sits inside it: an element of `Γ₀(N)` has `ad ≡ 1` modulo `N`,
since `c ≡ 0` and the determinant is one, so its upper-left entry is a unit — which is exactly
the condition `Δ₀(N)` imposes, and the reason it was defined with a *unit* upper-left entry
rather than `a ≡ 1`.

`Γ₁(N) ≤ Γ₀(N)`, so `R(Γ₀(N), Δ₀(N))` is the smaller of the two rings. Shimura's Theorem 3.35
is a separate statement again: a surjection onto `R(Γ₀(N), Δ₀(N))` from the **level-one** ring
`R(SL₂(ℤ), Δ)` — not from the `Γ₁(N)` ring — with kernel generated by `T(p, p)` for `p ∣ N`.
It is not formalised here.

The Γ₀ pair corresponds to the AINTLIB
[`LeanModularForms`](https://github.com/CBirkbeck/AINTLIB) file
`LeanModularForms/HeckeRIngs/GLn/CongruenceHecke/Foundation.lean` (Chris Birkbeck), whose
`Delta0_submonoid` and `Gamma0_pair` open that file.

## Main definitions

* `HeckeRing.GL2.Gamma0Image`: the image of `Γ₀(N)` in `GL₂(ℚ)`.

## Main results

* `HeckeRing.GL2.Gamma0Image_le_Delta0`: `Γ₀(N) ≤ Δ₀(N)`.
* `HeckeRing.GL2.map_withCenter_le_Delta0`: and `H·{±I} ≤ Δ₀(N)` for any `H ≤ Γ₀(N)`, the
  centre being absorbed.
* `HeckeRing.GL2.Delta0_le_commensurator_Gamma0Image`: `Δ₀(N)` lies in the commensurator of
  `Γ₀(N)`.
* `HeckeRing.GL2.out_mem_glpos_of_delta0`: the chosen representative of a double coset of
  `Δ₀(N)` has positive determinant, for *any* pair of flanking subgroups — the positivity
  hypothesis every level's Hecke operators carry.
* the `IsHeckeTriple (Delta0 N) ((Gamma0 N).map (mapGL ℚ)) ((Gamma0 N).map (mapGL ℚ))`
  instance, stated in the unfolded spelling that the modular-form side uses.

## References

* [G. Shimura, *Introduction to the arithmetic theory of automorphic functions*][shimura1971],
  §3.3.
-/

public section

open Matrix Matrix.SpecialLinearGroup CongruenceSubgroup Subgroup
  Subgroup.Commensurable HeckeRing.GLn

open scoped Pointwise MatrixGroups

namespace HeckeRing.GL2

variable (N : ℕ)

/-- The image of `Γ₀(N)` in `GL₂(ℚ)`. -/
noncomputable def Gamma0Image : Subgroup (GL (Fin 2) ℚ) :=
  (Gamma0 N).map (mapGL ℚ)

/-- Membership in the image of `Γ₀(N)`, by an integral witness. -/
@[simp] lemma mem_Gamma0Image_iff {g : GL (Fin 2) ℚ} :
    g ∈ Gamma0Image N ↔ ∃ σ ∈ Gamma0 N, mapGL ℚ σ = g := by
  rw [Gamma0Image, Subgroup.mem_map]

/-- `Gamma0Image N` unfolded. Stated here, in the file where the definition lives, because
downstream modules cannot see through the `def`: without this lemma a containment proved for
`Gamma0Image N` cannot be reused where `(Gamma0 N).map (mapGL ℚ)` is expected. -/
lemma Gamma0Image_def : Gamma0Image N = (Gamma0 N).map (mapGL ℚ) := by
  rw [Gamma0Image]

/-- `Γ₀(N) ≤ Δ₀(N)`: an element of `Γ₀(N)` has `ad ≡ 1` modulo `N`, since `c ≡ 0` and the
determinant is one, so its upper-left entry is a unit — which is exactly what `Δ₀(N)` asks.
This containment is also what puts the diamond operators into the Hecke ring of `Γ₁(N)`. -/
lemma Gamma0Image_le_Delta0 : (Gamma0Image N).toSubmonoid ≤ Delta0 N := by
  intro g hg
  obtain ⟨σ, hσ, rfl⟩ := (mem_Gamma0Image_iff N).mp hg
  refine (mem_Delta0_iff N).mpr ⟨(σ : Matrix (Fin 2) (Fin 2) ℤ), ?_, ?_, ?_,
    isUnit_intCast_apply_zero_zero_of_mem_Gamma0 hσ⟩
  · simp [mapGL_coe_matrix, algebraMap_int_eq]
  · rw [mapGL_coe_matrix, (SpecialLinearGroup.map (algebraMap ℤ ℚ) σ).prop]
    exact one_pos
  · exact mem_Gamma0_iff_dvd.mp hσ

/-- `Γ₀(N)` lands in `Δ₀(N)`: its elements are integral of determinant one, with lower-left
entry divisible by `N` and upper-left entry a unit because `ad ≡ 1`. -/
lemma mapGL_mem_Delta0 (γ : Gamma0 N) :
    (mapGL ℚ (γ : SL(2, ℤ)) : GL (Fin 2) ℚ) ∈ Delta0 N :=
  Gamma0Image_le_Delta0 N ((mem_Gamma0Image_iff N).mpr ⟨(γ : SL(2, ℤ)), γ.2, rfl⟩)

/-- **`H·{±I} ≤ Δ₀(N)`** for any `H ≤ Γ₀(N)`, transported to the images in `GL₂(ℚ)`. Adjoining
the centre costs nothing on the `Δ₀(N)` side, because `Γ₀(N)` already contains `-I` and so
absorbs the central factor; `withCenter_le_Gamma0` is that step. This is what puts the enlarged
group `Γ₁(N)·{±I}` — the one the Petersson layer sums over — into the same Hecke triple. -/
lemma map_withCenter_le_Delta0 {H : Subgroup SL(2, ℤ)} (hH : H ≤ Gamma0 N) :
    ((H.withCenter).map (mapGL ℚ)).toSubmonoid ≤ Delta0 N :=
  fun _ hg ↦ Gamma0Image_le_Delta0 N ((mem_Gamma0Image_iff N).mpr
    (Subgroup.mem_map.mp (Subgroup.map_mono (withCenter_le_Gamma0 hH) hg)))

/-- The chosen representative of a double coset of `Δ₀(N)` has positive determinant, whatever the
two flanking subgroups: `Δ₀(N)` consists of integral matrices of positive determinant. This is the
positivity hypothesis the Hecke operators on modular forms of level `N` carry, discharged once for
this semigroup.

Nothing here mentions `Γ₀(N)`: the lemma is about `Δ₀(N)` and is generic in both flanks. It sits
in this file because this is the earliest point where `Δ₀(N)` and the double-coset API are both in
scope, so every level — `Γ₀(N)`, `Γ₁(N)`, and any other flank — reaches it without importing a
sibling level's file. It is stated above the `[NeZero N]` variable deliberately: the proof never
needs `N` to be nonzero. -/
lemma out_mem_glpos_of_delta0 {Γ₁ Γ₂ : Subgroup (GL (Fin 2) ℚ)}
    (D : HeckeCoset (Delta0 N) Γ₁ Γ₂) :
    (D.out : GL (Fin 2) ℚ) ∈ Matrix.GLPos (Fin 2) ℚ :=
  posDetInt_le_glpos 2 (Delta0_le_posDetInt N D.out.2)

variable [NeZero N]

/-- `Δ₀(N)` lies in the commensurator of `Γ₀(N)`, the right-hand half of its Hecke triple. -/
lemma Delta0_le_commensurator_Gamma0Image :
    Delta0 N ≤ (commensurator (Gamma0Image N)).toSubmonoid :=
  Delta0_le_commensurator_map N (Gamma0 N)

/-- **The Hecke triple of `Γ₀(N)`**: `Γ₀(N) ≤ Δ₀(N) ≤ commensurator(Γ₀(N))` inside `GL₂(ℚ)` —
the setting of Shimura §3.3, in which the Hecke ring `R(Γ₀(N), Δ₀(N))` is formed.

Stated on the unfolded `(Gamma0 N).map (mapGL ℚ)`, matching the `Γ₁(N)` instance: the
modular-form side writes the level as `(Gamma0 N).map (mapGL ℝ)`, and its rational companion
arrives in the same shape, which is the form instance search looks for. -/
-- The two hypotheses are stated for `Gamma0Image N`, which is by definition
-- `(Gamma0 N).map (mapGL ℚ)`, so unfolding that definition is what connects them to the
-- target above.
instance : IsHeckeTriple (Delta0 N) ((Gamma0 N).map (mapGL ℚ)) ((Gamma0 N).map (mapGL ℚ)) :=
  IsHeckeTriple.of_diagonal (Gamma0Image_le_Delta0 N) (Delta0_le_commensurator_Gamma0Image N)

end HeckeRing.GL2
