/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Borel
public import EpsilonEridani.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.PositiveSubsystem
public import EpsilonEridani.LinearAlgebra.RootSystem.SimplyConnectedRootDatum.GeckLattice.GroupScheme
import EpsilonEridani.Algebra.Lie.UniversalEnveloping.Kostant.Weight.Order
import EpsilonEridani.LinearAlgebra.RootSystem.SimplyConnectedRootDatum.WeightDegree

/-!
# Borel-type point subgroups of the pinned Geck carrier

`EpsilonEridani.DynkinType.geckGroupScheme` is the explicit Chevalley carrier of a valid Dynkin type: the
closed subgroup scheme of `GLₙ` generated by the divided-power exponential root subgroups of the
Bourbaki-numbered Chevalley generators together with the weight torus of Geck's coordinate lattice.
A pinning of it is the quadruple `(G, T, B, {X_α})`. The numbered root subgroups of the carrier are
already available as closed subgroup schemes; the weight torus is available as a morphism of group
schemes into the carrier, which is a closed immersion under the exact hypothesis that the Geck
weights span the character lattice, known so far for `E₈`, `F₄` and `G₂`. The remaining member `B`
is not constructed here, and building a Borel subgroup scheme of the carrier, compatible with the
torus and the root subgroups, remains open. This file works one step below, on points alone: over
every value ring `A` it takes the abstract subgroup

```text
U(A) ⬝ T(A)
```

generated by the Geck weight torus and by the *raising* numbered root subgroups, and proves the two
group-theoretic properties expected of a Borel-type pair, namely that its positive part `U(A)` is
nilpotent and that the whole subgroup is solvable. The letter `U` is only a label: no unipotence of
any kind is defined or proved below.

The ambient group these subgroups live in is the one the Kostant root subgroups are built in:
`Aut_A(A ⊗ L)`, the general linear group of `A ⊗ L` for `L` the Geck coordinate lattice
`EpsilonEridani.DynkinType.geckCoordinateLattice`, inside which the carrier is cut out. They are therefore
*not* typed as subgroups of the carrier's point group `EpsilonEridani.DynkinType.geckPoints`; what places
them there, after the transport along the Geck coordinate basis that turns an automorphism into a
matrix, is `EpsilonEridani.DynkinType.map_geckTorusPositiveSubgroup_le_geckPoints` and its positive-part
companion. Together with the scalar-extension inclusions
`EpsilonEridani.DynkinType.map_geckSubsystemSubgroup_le` and
`EpsilonEridani.DynkinType.map_geckTorusPositiveSubgroup_le`, these say that the subgroups below form a
family of subgroups of the points of the carrier that grows along maps of value rings, which is the
data a Borel subgroup scheme would have to refine.

## Why the height ordering

The general Kostant apparatus offers two routes to nilpotence of a subsystem group. One grades the
selected indices and asks that a nonzero bracket of two selected root vectors be an integer
multiple of a third *selected* one, of strictly larger height; that is
`EpsilonEridani.UniversalEnvelopingAlgebra.isNilpotent_kostantSubsystemSubgroup`, and it does not apply
here. The Geck carrier carries one raising and one lowering root subgroup per Bourbaki *node*, and
no others, so a nonzero bracket of two distinct simple raising generators — the case of two
adjacent nodes — is a root vector for a non-simple root, which is not among the numbered generators
at all.

The route that does apply is triangularity:
`EpsilonEridani.UniversalEnvelopingAlgebra.isNilpotent_kostantSubsystemSubgroup_of_isPositive` asks only
that the weight basis be ordered so that adding a positive multiple of the root of a selected
generator moves strictly towards the beginning of the basis. Such an ordering is built once and for
all by `EpsilonEridani.UniversalEnvelopingAlgebra.orderedWeightBasis`, which reindexes a finite weight
basis by decreasing value of a degree functional; all this file has to supply is the functional and
the proof that it is positive on the root of each raising generator.

That functional is `EpsilonEridani.DynkinType.weightDegree`, the simple-root height read off the rational
root system `EpsilonEridani.DynkinType.rationalRootSystem`, where the roots span the weight space; the
integral character lattice of the pinned datum is in general strictly larger than its root lattice,
so there is no integral coordinate sum to use instead. Its positivity on a raising generator is
just the value one on each pinned simple root, and nothing here needs to know which Geck coordinates
carry which weight.

The results are therefore stated for an arbitrary set of raising generators, since that is the
generality the argument has: every subset of the raising nodes gives an abstract nilpotent
subgroup, together with a solvable Borel-type subgroup containing it, and the whole positive system
is the case of all of them.

## What is and is not claimed

Everything below is a statement about abstract subgroups of the individual groups `Aut_A(A ⊗ L)`,
one value ring `A` at a time. Nothing here builds a subgroup scheme: what is proved of the
dependence on `A` is the inclusion of the image under scalar extension, not an equality, and no
representability or closedness in the carrier is proved, so none of these subgroups is shown to be
the Borel member of a pinning; they are only its candidate on points. Nor is it asserted that they
are *maximal* among solvable subgroups of the carrier's points, that `U(A)` consists of unipotent
elements or is the unipotent radical, or that the Geck weight torus is a maximal torus; those are
geometric statements about the group scheme and remain Layer 9 work, as does the construction of
full-weight admissible lattices outside the three unimodular exceptional types. No finiteness or
simplicity of any group appears.

## Main definitions

* `EpsilonEridani.DynkinType.geckSubsystemSubgroup`: the subgroup of `Aut_A(A ⊗ L)` generated by a chosen
  set of numbered root subgroups.
* `EpsilonEridani.DynkinType.geckPositiveSubgroup`: the subgroup of `Aut_A(A ⊗ L)` generated by the
  numbered raising root subgroups.
* `EpsilonEridani.DynkinType.geckTorusPositiveSubgroup`: the subgroup of `Aut_A(A ⊗ L)` generated by that
  group together with the Geck weight torus.

## Main results

* `EpsilonEridani.DynkinType.isNilpotent_geckSubsystemSubgroup_of_subset_range_inl` and
  `EpsilonEridani.DynkinType.isNilpotent_geckPositiveSubgroup`: a group generated by raising root
  subgroups is nilpotent.
* `EpsilonEridani.DynkinType.isSolvable_geckTorusSubsystemSubgroup_of_subset_range_inl` and
  `EpsilonEridani.DynkinType.isSolvable_geckTorusPositiveSubgroup`: the corresponding Borel-type group is
  solvable.
* `EpsilonEridani.DynkinType.geckSubsystemSubgroup_le_geckTorusSubsystemSubgroup` and
  `EpsilonEridani.DynkinType.geckPositiveSubgroup_le_geckTorusPositiveSubgroup`: the root-subgroup part
  lies inside the corresponding Borel-type group.
* `EpsilonEridani.DynkinType.geckSubsystemSubgroup_normal_subgroupOf_geckTorusSubsystemSubgroup` and
  `EpsilonEridani.DynkinType.geckPositiveSubgroup_normal_subgroupOf_geckTorusPositiveSubgroup`: it is
  normal there.
* `EpsilonEridani.DynkinType.map_geckPositiveSubgroup_le_geckPoints` and
  `EpsilonEridani.DynkinType.map_geckTorusPositiveSubgroup_le_geckPoints`: written in the Geck coordinate
  basis, both groups lie in the points of the carrier.
* `EpsilonEridani.DynkinType.map_geckSubsystemSubgroup_le` and
  `EpsilonEridani.DynkinType.map_geckTorusPositiveSubgroup_le`: scalar extension along a morphism of value
  rings carries each of them into its counterpart over the target.

The characterizations `EpsilonEridani.DynkinType.geckSubsystemSubgroup_eq_closure`,
`EpsilonEridani.DynkinType.geckSubsystemSubgroup_le_iff`,
`EpsilonEridani.DynkinType.geckTorusPositiveSubgroup_eq_sup` and the membership and monotonicity lemmas
beside them are how these subgroups are meant to be used, without unfolding them to the generic
Kostant construction.

## References

* M. Geck, *On the construction of semisimple Lie algebras and Chevalley groups*,
  Proc. Amer. Math. Soc. **145** (2017), 3233--3247.
* R. W. Carter, *Simple Groups of Lie Type*, §§4.4, 7.1 and 8.2.
* J. E. Humphreys, *Linear Algebraic Groups*, §§26--28.
* J. C. Jantzen, *Representations of Algebraic Groups*, II.1.

This is a step towards the "Pinnings" target of Layer 9 of
`EpsilonEridaniRoadmap/ReductiveGroups/README.md`, whose consumer is the pinned ambient group
`EpsilonEridani.ValidLieTypeIndex.AmbientGroup` of milestone L0 of
`EpsilonEridaniRoadmap/CFSGStatement/README.md`; the Borel subgroup scheme that target asks for is still
to be built.
-/

public section

open CategoryTheory TensorProduct EpsilonEridani.UniversalEnvelopingAlgebra

namespace EpsilonEridani.DynkinType

universe v

noncomputable section

-- Match tensor products to the `ℤ`-algebra instance stored by `CommAlgCat` objects.
attribute [local instance high] Algebra.toModule

variable (t : DynkinType) (ht : t.Valid)

/-! ## The height ordering of the Geck coordinates -/

/-- **A raising generator has positive weight height.** This is the only input the generic ordered
weight basis `EpsilonEridani.UniversalEnvelopingAlgebra.orderedWeightBasis` needs in order to place the
raising Geck root subgroups in triangular position. -/
private theorem weightDegree_rootGeneratorWeight_pos {i : Fin t.rank ⊕ Fin t.rank}
    (hi : i ∈ Set.range (Sum.inl : Fin t.rank → Fin t.rank ⊕ Fin t.rank)) :
    0 < t.weightDegree ht (t.rootGeneratorWeight ht i) := by
  obtain ⟨j, rfl⟩ := hi
  have hrow : t.rootGeneratorWeight ht (.inl j) = fun k => t.cartanMatrix j k := by
    funext k
    rw [rootGeneratorWeight_inl]
  rw [hrow, weightDegree_cartanMatrix_row]
  norm_num

/-! ## The positive part and the Borel-type subgroup on points -/

/-- The subgroup of `Aut_A(A ⊗ L)`, the general linear group of the base-changed Geck coordinate
lattice, generated by a chosen set of numbered root subgroups. It is the root-subgroup half of
`EpsilonEridani.DynkinType.geckTorusSubsystemSubgroup`, which
`EpsilonEridani.DynkinType.map_geckTorusSubsystemSubgroup_le_geckPoints` places inside the points of the
carrier. -/
abbrev geckSubsystemSubgroup (S : Set (Fin t.rank ⊕ Fin t.rank)) (A : CommAlgCat.{v} ℤ) :
    Subgroup (LinearMap.GeneralLinearGroup A
      (A ⊗[ℤ] (t.geckCoordinateLattice ht).toAddSubgroup)) :=
  kostantSubsystemSubgroup
    (t.lieBasis ht).rootGenerator (t.lieBasis ht).h (t.geckRepresentation ht)
    (t.geckCoordinateLattice ht).toAddSubgroup
    (t.geckRepresentation_kostantForm_mem_geckCoordinateLattice ht)
    (t.isNilpotent_geckRepresentation_rootGenerator ht) S A

/-- **The positive part of the pinned Geck carrier on points**: the subgroup of `Aut_A(A ⊗ L)`
generated by the numbered raising root subgroups. -/
abbrev geckPositiveSubgroup (A : CommAlgCat.{v} ℤ) :
    Subgroup (LinearMap.GeneralLinearGroup A
      (A ⊗[ℤ] (t.geckCoordinateLattice ht).toAddSubgroup)) :=
  t.geckSubsystemSubgroup ht (Set.range Sum.inl) A

/-- **The Borel-type subgroup of the pinned Geck carrier on points**: the subgroup of
`Aut_A(A ⊗ L)` generated by the Geck weight torus together with the numbered raising root
subgroups.

It is a subgroup of that group for one value ring `A` at a time, the candidate on points for the
Borel member of a pinning; it is not built as a subgroup scheme here, and neither maximality among
solvable subgroups nor closedness in the carrier is asserted. Its containment in the points of the
carrier is `EpsilonEridani.DynkinType.map_geckTorusPositiveSubgroup_le_geckPoints`, and what holds of its
dependence on `A` is the inclusion `EpsilonEridani.DynkinType.map_geckTorusPositiveSubgroup_le`. -/
abbrev geckTorusPositiveSubgroup (A : CommAlgCat.{v} ℤ) :
    Subgroup (LinearMap.GeneralLinearGroup A
      (A ⊗[ℤ] (t.geckCoordinateLattice ht).toAddSubgroup)) :=
  t.geckTorusSubsystemSubgroup ht (Set.range Sum.inl) A

/-! ## The interface of these subgroups -/

/-- A group generated by a chosen set of numbered root subgroups is generated, as a subgroup of
`Aut_A(A ⊗ L)`, by the elements of those root subgroups. -/
theorem geckSubsystemSubgroup_eq_closure (S : Set (Fin t.rank ⊕ Fin t.rank))
    (A : CommAlgCat.{v} ℤ) :
    t.geckSubsystemSubgroup ht S A =
      Subgroup.closure {g | ∃ i ∈ S, ∃ u, t.geckRootSubgroupParam ht i A u = g} :=
  kostantSubsystemSubgroup_eq_closure _ _ _ _ _ _ S A

/-- **Elimination principle.** A subgroup of `Aut_A(A ⊗ L)` contains the group generated by a
chosen set of numbered root subgroups exactly when it contains every element of those root
subgroups. -/
theorem geckSubsystemSubgroup_le_iff {S : Set (Fin t.rank ⊕ Fin t.rank)} {A : CommAlgCat.{v} ℤ}
    {P : Subgroup (LinearMap.GeneralLinearGroup A
      (A ⊗[ℤ] (t.geckCoordinateLattice ht).toAddSubgroup))} :
    t.geckSubsystemSubgroup ht S A ≤ P ↔
      ∀ i ∈ S, ∀ u : Multiplicative A, t.geckRootSubgroupParam ht i A u ∈ P :=
  kostantSubsystemSubgroup_le_iff _ _ _ _ _ _

/-- An element of a numbered root subgroup indexed in `S` lies in the group `S` generates. -/
theorem geckRootSubgroupParam_mem_geckSubsystemSubgroup {S : Set (Fin t.rank ⊕ Fin t.rank)}
    {i : Fin t.rank ⊕ Fin t.rank} (hiS : i ∈ S) (A : CommAlgCat.{v} ℤ) (u : Multiplicative A) :
    t.geckRootSubgroupParam ht i A u ∈ t.geckSubsystemSubgroup ht S A :=
  kostantRootSubgroupParam_mem_kostantSubsystemSubgroup _ _ _ _ _ _ hiS A u

/-- An element of a numbered raising root subgroup lies in the positive part. -/
theorem geckRootSubgroupParam_inl_mem_geckPositiveSubgroup (i : Fin t.rank)
    (A : CommAlgCat.{v} ℤ) (u : Multiplicative A) :
    t.geckRootSubgroupParam ht (Sum.inl i) A u ∈ t.geckPositiveSubgroup ht A :=
  t.geckRootSubgroupParam_mem_geckSubsystemSubgroup ht (S := Set.range Sum.inl)
    (Set.mem_range_self i) A u

/-- The group generated by a set of numbered root subgroups grows with the set. -/
theorem geckSubsystemSubgroup_mono {S T : Set (Fin t.rank ⊕ Fin t.rank)} (hST : S ⊆ T)
    (A : CommAlgCat.{v} ℤ) :
    t.geckSubsystemSubgroup ht S A ≤ t.geckSubsystemSubgroup ht T A :=
  kostantSubsystemSubgroup_mono _ _ _ _ _ _ hST A

/-- **Change of value ring for the root-subgroup part.** Scalar extension along a morphism of
value rings carries the group generated by a set of numbered root subgroups into the group the
same set generates over the target. This is an inclusion, not an equality: over the target the
same root subgroups have more parameters available. -/
theorem map_geckSubsystemSubgroup_le (S : Set (Fin t.rank ⊕ Fin t.rank))
    {A B : CommAlgCat.{v} ℤ} (φ : A ⟶ B) :
    (t.geckSubsystemSubgroup ht S A).map
        (GeneralLinear.mapScalarExtensionAutomorphisms
          (V := (t.geckCoordinateLattice ht).toAddSubgroup) φ).hom ≤
      t.geckSubsystemSubgroup ht S B :=
  map_kostantSubsystemSubgroup_le _ _ _ _ _ _ S φ

/-- The Borel-type subgroup on points is the join of the positive part and the Geck weight
torus. -/
theorem geckTorusPositiveSubgroup_eq_sup (A : CommAlgCat.{v} ℤ) :
    t.geckTorusPositiveSubgroup ht A =
      t.geckPositiveSubgroup ht A ⊔ (t.geckTorusPoints ht A).range :=
  kostantTorusSubsystemSubgroup_eq_sup _ _ _ _ _ _ _ _ _ A

/-- Every point of the Geck weight torus lies in the Borel-type subgroup. -/
theorem geckTorusPoints_mem_geckTorusPositiveSubgroup (A : CommAlgCat.{v} ℤ)
    (s : Fin t.rank → Aˣ) :
    t.geckTorusPoints ht A s ∈ t.geckTorusPositiveSubgroup ht A :=
  kostantTorusPoints_mem_kostantTorusSubsystemSubgroup _ _ _ _ _ _ _ _ _ A s

/-- **Change of value ring for the Borel-type subgroup.** Scalar extension along a morphism of
value rings carries the Borel-type subgroup into the Borel-type subgroup over the target. Like
`EpsilonEridani.DynkinType.map_geckSubsystemSubgroup_le` this is an inclusion, not an equality, so it
does not by itself make the family of these subgroups a subgroup scheme. -/
theorem map_geckTorusPositiveSubgroup_le {A B : CommAlgCat.{v} ℤ} (φ : A ⟶ B) :
    (t.geckTorusPositiveSubgroup ht A).map
        (GeneralLinear.mapScalarExtensionAutomorphisms
          (V := (t.geckCoordinateLattice ht).toAddSubgroup) φ).hom ≤
      t.geckTorusPositiveSubgroup ht B :=
  map_kostantTorusSubsystemSubgroup_le _ _ _ _ _ _ _ _ _ φ

/-! ## Nilpotence and solvability -/

/-- **A group generated by raising Geck root subgroups is nilpotent**, over every value ring. -/
theorem isNilpotent_geckSubsystemSubgroup_of_subset_range_inl
    {S : Set (Fin t.rank ⊕ Fin t.rank)} (hS : S ⊆ Set.range Sum.inl) (A : Type v) [CommRing A] :
    Group.IsNilpotent (t.geckSubsystemSubgroup ht S (CommAlgCat.of ℤ A)) :=
  isNilpotent_kostantSubsystemSubgroup_of_isPositive
    (t.lieBasis ht).rootGenerator (t.lieBasis ht).h (t.geckRepresentation ht)
    (t.geckCoordinateLattice ht).toAddSubgroup
    (t.geckRepresentation_kostantForm_mem_geckCoordinateLattice ht)
    (t.isNilpotent_geckRepresentation_rootGenerator ht)
    (orderedWeightBasis (t.weightDegree ht) (t.geckWeightFin ht) (t.geckCoordinateBasisFin ht))
    (orderedWeight (t.weightDegree ht) (t.geckWeightFin ht)) (t.rootGeneratorWeight ht) S
    (isCartanWeightVector_coe_orderedWeightBasis (t.lieBasis ht).h (t.geckRepresentation ht)
      (t.geckCoordinateLattice ht).toAddSubgroup (t.geckCoordinateBasisFin ht)
      (t.geckWeightFin ht) (t.weightDegree ht)
      (t.isCartanWeightVector_geckCoordinateBasisFin ht))
    (fun i _ j => t.lie_lieBasis_h_rootGenerator ht i j)
    (fun _ hiS {_ _ _} hm heq => orderedWeight_lt_of_eq_add_nsmul _ _
      (t.weightDegree_rootGeneratorWeight_pos ht (hS hiS)) hm heq) A

/-- **The subgroup generated by all the numbered raising Geck root subgroups is nilpotent**, over
every value ring. -/
theorem isNilpotent_geckPositiveSubgroup (A : Type v) [CommRing A] :
    Group.IsNilpotent (t.geckPositiveSubgroup ht (CommAlgCat.of ℤ A)) :=
  t.isNilpotent_geckSubsystemSubgroup_of_subset_range_inl ht subset_rfl A

/-- **A group generated by the Geck weight torus and raising root subgroups is solvable**, over
every value ring. -/
theorem isSolvable_geckTorusSubsystemSubgroup_of_subset_range_inl
    {S : Set (Fin t.rank ⊕ Fin t.rank)} (hS : S ⊆ Set.range Sum.inl) (A : Type v) [CommRing A] :
    Group.IsSolvable (t.geckTorusSubsystemSubgroup ht S (CommAlgCat.of ℤ A)) :=
  isSolvable_kostantTorusSubsystemSubgroup_of_isSolvable
    (t.lieBasis ht).rootGenerator (t.lieBasis ht).h (t.geckRepresentation ht)
    (t.geckCoordinateLattice ht).toAddSubgroup
    (t.geckRepresentation_kostantForm_mem_geckCoordinateLattice ht)
    (t.isNilpotent_geckRepresentation_rootGenerator ht)
    (t.geckCoordinateBasisFin ht) (t.geckWeightFin ht)
    (t.isCartanWeightVector_geckCoordinateBasisFin ht) (t.rootGeneratorWeight ht)
    (fun i _ j => t.lie_lieBasis_h_rootGenerator ht i j) (CommAlgCat.of ℤ A)
    (IsNilpotent.to_isSolvable
      (h := t.isNilpotent_geckSubsystemSubgroup_of_subset_range_inl ht hS A))

/-- **The Borel-type subgroup of the pinned Geck carrier on points is solvable.** -/
theorem isSolvable_geckTorusPositiveSubgroup (A : Type v) [CommRing A] :
    Group.IsSolvable (t.geckTorusPositiveSubgroup ht (CommAlgCat.of ℤ A)) :=
  t.isSolvable_geckTorusSubsystemSubgroup_of_subset_range_inl ht subset_rfl A

/-- A group generated by a chosen set of numbered root subgroups lies inside the group that set
generates together with the Geck weight torus. -/
theorem geckSubsystemSubgroup_le_geckTorusSubsystemSubgroup (S : Set (Fin t.rank ⊕ Fin t.rank))
    (A : CommAlgCat.{v} ℤ) :
    t.geckSubsystemSubgroup ht S A ≤ t.geckTorusSubsystemSubgroup ht S A :=
  kostantSubsystemSubgroup_le_kostantTorusSubsystemSubgroup
    (t.lieBasis ht).rootGenerator (t.lieBasis ht).h (t.geckRepresentation ht)
    (t.geckCoordinateLattice ht).toAddSubgroup
    (t.geckRepresentation_kostantForm_mem_geckCoordinateLattice ht)
    (t.isNilpotent_geckRepresentation_rootGenerator ht)
    (t.geckCoordinateBasisFin ht) (t.geckWeightFin ht) S A

/-- A group generated by a chosen set of numbered root subgroups is normal in the group that set
generates together with the Geck weight torus. -/
theorem geckSubsystemSubgroup_normal_subgroupOf_geckTorusSubsystemSubgroup
    (S : Set (Fin t.rank ⊕ Fin t.rank)) (A : CommAlgCat.{v} ℤ) :
    ((t.geckSubsystemSubgroup ht S A).subgroupOf (t.geckTorusSubsystemSubgroup ht S A)).Normal :=
  kostantSubsystemSubgroup_normal_subgroupOf_kostantTorusSubsystemSubgroup
    (t.lieBasis ht).rootGenerator (t.lieBasis ht).h (t.geckRepresentation ht)
    (t.geckCoordinateLattice ht).toAddSubgroup
    (t.geckRepresentation_kostantForm_mem_geckCoordinateLattice ht)
    (t.isNilpotent_geckRepresentation_rootGenerator ht)
    (t.geckCoordinateBasisFin ht) (t.geckWeightFin ht)
    (t.isCartanWeightVector_geckCoordinateBasisFin ht) (t.rootGeneratorWeight ht)
    S (fun i _ j => t.lie_lieBasis_h_rootGenerator ht i j) A

/-- The positive part lies inside the Borel-type subgroup. -/
theorem geckPositiveSubgroup_le_geckTorusPositiveSubgroup (A : CommAlgCat.{v} ℤ) :
    t.geckPositiveSubgroup ht A ≤ t.geckTorusPositiveSubgroup ht A :=
  t.geckSubsystemSubgroup_le_geckTorusSubsystemSubgroup ht (Set.range Sum.inl) A

/-- **The positive part is normal in the Borel-type subgroup.** -/
theorem geckPositiveSubgroup_normal_subgroupOf_geckTorusPositiveSubgroup (A : CommAlgCat.{v} ℤ) :
    ((t.geckPositiveSubgroup ht A).subgroupOf (t.geckTorusPositiveSubgroup ht A)).Normal :=
  t.geckSubsystemSubgroup_normal_subgroupOf_geckTorusSubsystemSubgroup ht (Set.range Sum.inl) A

/-! ## Inside the points of the carrier -/

/-- **The Borel-type subgroup lies in the points of the carrier.** Written in the Geck coordinate
basis, the subgroup generated by the weight torus and the numbered raising root subgroups is
contained in the `A`-valued points of the Geck carrier, so the solvable group of
`EpsilonEridani.DynkinType.isSolvable_geckTorusPositiveSubgroup` is a solvable subgroup of
`EpsilonEridani.DynkinType.geckPoints A`. -/
theorem map_geckTorusPositiveSubgroup_le_geckPoints (A : Type v) [CommRing A] :
    (t.geckTorusPositiveSubgroup ht (CommAlgCat.of ℤ A)).map
        (Units.map (LinearMap.toMatrixAlgEquiv
          ((t.geckCoordinateBasisFin ht).baseChange A)).toMulEquiv) ≤
      t.geckPoints ht A :=
  t.map_geckTorusSubsystemSubgroup_le_geckPoints ht (Set.range Sum.inl) A

/-- **The positive part lies in the points of the carrier**, so the nilpotent group of
`EpsilonEridani.DynkinType.isNilpotent_geckPositiveSubgroup` is a nilpotent subgroup of
`EpsilonEridani.DynkinType.geckPoints A`. -/
theorem map_geckPositiveSubgroup_le_geckPoints (A : Type v) [CommRing A] :
    (t.geckPositiveSubgroup ht (CommAlgCat.of ℤ A)).map
        (Units.map (LinearMap.toMatrixAlgEquiv
          ((t.geckCoordinateBasisFin ht).baseChange A)).toMulEquiv) ≤
      t.geckPoints ht A :=
  (Subgroup.map_mono
      (t.geckPositiveSubgroup_le_geckTorusPositiveSubgroup ht (CommAlgCat.of ℤ A))).trans
    (t.map_geckTorusPositiveSubgroup_le_geckPoints ht A)

end

end EpsilonEridani.DynkinType
