/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.LinearAlgebra.RootSystem.SimplyConnectedRootDatum.GeckLattice.Weyl.Basic
import EpsilonEridani.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Torus.Coroot

/-!
# Root generation of the Geck weight torus

The Geck carrier of a valid Dynkin type is built from its numbered positive and negative root
subgroups and its split weight torus. The represented generators form `sl₂` triples, and the root
of the `i`-th raising generator is the `i`-th row of the Bourbaki Cartan matrix. So the generic
coroot-generation theorem puts the entire weight torus in the subgroup generated by the root
subgroups, over every commutative ring, as soon as every row of the Cartan matrix is a primitive
integer vector: some integer combination of its entries is `1`.

That hypothesis is checked here for the three types whose Geck carrier is full-weight, `E₈`, `F₄`
and `G₂`. Every row of the `E₈` and `F₄` Cartan matrices contains an entry `-1`, at a neighbouring
node of the diagram. The long row `(-3, 2)` of `G₂` has no such entry, but its Bézout coefficients
`(-1, -1)` still give `1`.

This is a statement about the generated subgroups in the defining representation. Identifying
that subgroup with all points of the Geck toral-closure scheme is a separate comparison.

## Main results

* `EpsilonEridani.DynkinType.range_geckTorusPoints_le_geckElementarySubgroup`: when every Cartan row is
  primitive, the Geck weight torus is contained in the elementary subgroup.
* `EpsilonEridani.DynkinType.geckTorusSubsystemSubgroup_univ_eq_geckElementarySubgroup`: under the same
  hypothesis, adjoining the torus to all numbered root subgroups adds no elements.
* `EpsilonEridani.DynkinType.range_geckTorusPoints_le_geckElementarySubgroup_E8`,
  `range_geckTorusPoints_le_geckElementarySubgroup_F4` and
  `range_geckTorusPoints_le_geckElementarySubgroup_G2`, with the corresponding
  `geckTorusSubsystemSubgroup_univ_eq_geckElementarySubgroup_E8`, `_F4` and `_G2`: the three
  full-weight Geck carriers.

## References

* R. Steinberg, *Lectures on Chevalley Groups*, §3.
* N. Bourbaki, *Lie Groups and Lie Algebras, Chapters 4--6*, Plates VII, VIII and IX, for the
  Cartan matrices.
* `EpsilonEridani.Algebra.Lie.E7.Minuscule.Generation`, an earlier formal coroot-generation application.
-/

public section

open scoped Matrix TensorProduct

universe v

namespace EpsilonEridani.DynkinType

open EpsilonEridani.UniversalEnvelopingAlgebra

attribute [local instance 100] LieRing.ofAssociativeRing
attribute [local instance high] Algebra.toModule

/-! ## Types whose Cartan rows are primitive -/

section General

variable (t : DynkinType) (ht : t.Valid)

/-- **The Geck weight torus lies in the elementary subgroup** when every row of the Cartan matrix
is primitive. Over every commutative ring, the torus is then contained in the subgroup generated
by the numbered positive and negative simple-root subgroups. -/
theorem range_geckTorusPoints_le_geckElementarySubgroup
    (hrow : ∀ i, ∃ c : Fin t.rank → ℤ, ∑ j, t.cartanMatrix i j * c j = 1)
    (A : CommAlgCat.{v} ℤ) :
    (t.geckTorusPoints ht A).range ≤ t.geckElementarySubgroup ht A := by
  choose m hm using hrow
  rw [← kostantTorusSubgroup_eq_range
    (t.geckCoordinateLattice ht).toAddSubgroup
    (t.geckCoordinateBasisFin ht) (t.geckWeightFin ht) A]
  exact kostantTorusSubgroup_le_kostantElementarySubgroup
    (t.lieBasis ht).rootGenerator (t.lieBasis ht).h
    (t.geckRepresentation ht) (t.geckCoordinateLattice ht).toAddSubgroup
    (t.geckRepresentation_kostantForm_mem_geckCoordinateLattice ht)
    (t.isNilpotent_geckRepresentation_rootGenerator ht)
    (t.geckCoordinateBasisFin ht) (t.geckWeightFin ht)
    (t.isCartanWeightVector_geckCoordinateBasisFin ht)
    (t.rootGeneratorWeight ht) (t.lie_lieBasis_h_rootGenerator ht)
    Sum.inl Sum.inr (t.isSl2Triple_geckRepresentation ht)
    (fun i => by funext j; simp) m
    (fun i => by simpa only [rootGeneratorWeight_inl] using hm i) A

/-- **Adjoining the Geck weight torus to every numbered simple-root subgroup adds nothing** when
every row of the Cartan matrix is primitive, over every commutative ring. -/
theorem geckTorusSubsystemSubgroup_univ_eq_geckElementarySubgroup
    (hrow : ∀ i, ∃ c : Fin t.rank → ℤ, ∑ j, t.cartanMatrix i j * c j = 1)
    (A : CommAlgCat.{v} ℤ) :
    t.geckTorusSubsystemSubgroup ht Set.univ A = t.geckElementarySubgroup ht A := by
  rw [geckTorusSubsystemSubgroup, kostantTorusSubsystemSubgroup_univ, sup_eq_left]
  exact t.range_geckTorusPoints_le_geckElementarySubgroup ht hrow A

end General

/-! ## The full-weight types -/

/-- Every row of the `E₈` Cartan matrix is primitive: node `i` has a neighbour, listed here, at
which its Cartan entry is `-1`. -/
private theorem exists_sum_cartanMatrix_mul_eq_one_E8 (i : Fin E8.rank) :
    ∃ c : Fin E8.rank → ℤ, ∑ j, E8.cartanMatrix i j * c j = 1 :=
  ⟨fun j : Fin 8 => if j = ![2, 3, 0, 1, 3, 4, 5, 6] i then -1 else 0, by
    rw [cartanMatrix_E8]
    fin_cases i <;> decide⟩

/-- Every row of the `F₄` Cartan matrix is primitive: node `i` has a neighbour, listed here, at
which its Cartan entry is `-1`. -/
private theorem exists_sum_cartanMatrix_mul_eq_one_F4 (i : Fin F4.rank) :
    ∃ c : Fin F4.rank → ℤ, ∑ j, F4.cartanMatrix i j * c j = 1 :=
  ⟨fun j : Fin 4 => if j = ![1, 0, 1, 2] i then -1 else 0, by
    rw [cartanMatrix_F4]
    fin_cases i <;> decide⟩

/-- Every row of the `G₂` Cartan matrix is primitive. The short row `(2, -1)` has the entry `-1`,
and the long row `(-3, 2)` has the Bézout coefficients `(-1, -1)`. -/
private theorem exists_sum_cartanMatrix_mul_eq_one_G2 (i : Fin G2.rank) :
    ∃ c : Fin G2.rank → ℤ, ∑ j, G2.cartanMatrix i j * c j = 1 :=
  ⟨fun j => if i.val = 0 then if j.val = 1 then -1 else 0 else -1, by
    rw [cartanMatrix_G2]
    fin_cases i <;> decide⟩

/-- Over every commutative ring, the type-`E₈` Geck weight torus is contained in the elementary
subgroup generated by the sixteen numbered positive and negative simple-root subgroups. -/
theorem range_geckTorusPoints_le_geckElementarySubgroup_E8 (A : CommAlgCat.{v} ℤ) :
    (E8.geckTorusPoints valid_E8 A).range ≤ E8.geckElementarySubgroup valid_E8 A :=
  E8.range_geckTorusPoints_le_geckElementarySubgroup valid_E8
    exists_sum_cartanMatrix_mul_eq_one_E8 A

/-- Adding the type-`E₈` Geck weight torus to every numbered simple-root subgroup does not
enlarge the elementary subgroup over any commutative ring. -/
@[simp]
theorem geckTorusSubsystemSubgroup_univ_eq_geckElementarySubgroup_E8 (A : CommAlgCat.{v} ℤ) :
    E8.geckTorusSubsystemSubgroup valid_E8 Set.univ A = E8.geckElementarySubgroup valid_E8 A :=
  E8.geckTorusSubsystemSubgroup_univ_eq_geckElementarySubgroup valid_E8
    exists_sum_cartanMatrix_mul_eq_one_E8 A

/-- Over every commutative ring, the type-`F₄` Geck weight torus is contained in the elementary
subgroup generated by the eight numbered positive and negative simple-root subgroups. -/
theorem range_geckTorusPoints_le_geckElementarySubgroup_F4 (A : CommAlgCat.{v} ℤ) :
    (F4.geckTorusPoints valid_F4 A).range ≤ F4.geckElementarySubgroup valid_F4 A :=
  F4.range_geckTorusPoints_le_geckElementarySubgroup valid_F4
    exists_sum_cartanMatrix_mul_eq_one_F4 A

/-- Adding the type-`F₄` Geck weight torus to every numbered simple-root subgroup does not
enlarge the elementary subgroup over any commutative ring. -/
@[simp]
theorem geckTorusSubsystemSubgroup_univ_eq_geckElementarySubgroup_F4 (A : CommAlgCat.{v} ℤ) :
    F4.geckTorusSubsystemSubgroup valid_F4 Set.univ A = F4.geckElementarySubgroup valid_F4 A :=
  F4.geckTorusSubsystemSubgroup_univ_eq_geckElementarySubgroup valid_F4
    exists_sum_cartanMatrix_mul_eq_one_F4 A

/-- Over every commutative ring, the type-`G₂` Geck weight torus is contained in the elementary
subgroup generated by the four numbered positive and negative simple-root subgroups. -/
theorem range_geckTorusPoints_le_geckElementarySubgroup_G2 (A : CommAlgCat.{v} ℤ) :
    (G2.geckTorusPoints valid_G2 A).range ≤ G2.geckElementarySubgroup valid_G2 A :=
  G2.range_geckTorusPoints_le_geckElementarySubgroup valid_G2
    exists_sum_cartanMatrix_mul_eq_one_G2 A

/-- Adding the type-`G₂` Geck weight torus to every numbered simple-root subgroup does not
enlarge the elementary subgroup over any commutative ring. -/
@[simp]
theorem geckTorusSubsystemSubgroup_univ_eq_geckElementarySubgroup_G2 (A : CommAlgCat.{v} ℤ) :
    G2.geckTorusSubsystemSubgroup valid_G2 Set.univ A = G2.geckElementarySubgroup valid_G2 A :=
  G2.geckTorusSubsystemSubgroup_univ_eq_geckElementarySubgroup valid_G2
    exists_sum_cartanMatrix_mul_eq_one_G2 A

end EpsilonEridani.DynkinType
