/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import EpsilonEridani.Analysis.Calculus.Morse.Index
public import EpsilonEridani.Analysis.Calculus.Morse.Linearization
public import EpsilonEridani.Analysis.InnerProductSpace.Spectrum
-- Private: used only to turn the finite-dimensional algebraic splitting into a continuous
-- projection; the public API exposes the resulting continuous linear map.
import Mathlib.Analysis.Normed.Module.Complemented
import Mathlib.Topology.Algebra.Module.ContinuousLinearMap.Idempotent

/-!
# Spectral splitting at a Morse critical point

At a nondegenerate critical point on a finite-dimensional real Hilbert space, the Hessian is an
invertible self-adjoint operator. Its positive and negative spectral subspaces therefore give a
direct-sum decomposition of the tangent space. For the negative-gradient vector field, the
positive Hessian subspace is the stable linear subspace and the negative Hessian subspace is the
unstable linear subspace.

This file constructs those two subspaces, shows that both are invariant under the
negative-gradient linearization, and identifies the dimension of the unstable subspace with the
Morse index; the stable dimension and the Morse index therefore add up to the dimension of the
ambient space.

These are the linear data used by the local stable- and unstable-manifold theorems. No local
invariant manifold is asserted here: those theorems additionally have to control the nonlinear
remainder of the negative-gradient field, supplied by
`EpsilonEridani.IsNondegenerateCriticalPoint.neg_gradient_sub_linearization_isLittleO`.

## Main declarations

* `ContDiffAt.stableLinearSubspace`: the positive spectral subspace of the Hessian.
* `ContDiffAt.unstableLinearSubspace`: the negative spectral subspace of the Hessian.
* `ContDiffAt.map_neg_hessianOperator_stableLinearSubspace_le` and
  `ContDiffAt.map_neg_hessianOperator_unstableLinearSubspace_le`: both subspaces are invariant
  under the negative-gradient linearization `-hessianOperator f x`.
* `ContDiffAt.isCompl_unstableLinearSubspace_stableLinearSubspace`: when the Hessian is injective
  these subspaces are complementary, so the tangent space is their direct sum.
* `ContDiffAt.finrank_unstableLinearSubspace`: the unstable dimension is the Morse index.
* `ContDiffAt.finrank_stableLinearSubspace_add_morseIndex`: the stable dimension plus the Morse
  index is the ambient dimension.
* `EpsilonEridani.IsNondegenerateCriticalPoint.isCompl_unstableLinearSubspace_stableLinearSubspace` and
  `EpsilonEridani.IsNondegenerateCriticalPoint.finrank_stableLinearSubspace_add_morseIndex`: the same two
  results stated for a nondegenerate critical point, which supplies the Hessian injectivity.
* `ContDiffAt.stableProjection`: when the Hessian is injective, the continuous projection onto
  the stable linear subspace along the unstable linear subspace.
* `ContDiffAt.unstableProjection`: the complementary projection onto the unstable linear
  subspace along the stable linear subspace.
* `EpsilonEridani.IsNondegenerateCriticalPoint.stableProjection` and
  `EpsilonEridani.IsNondegenerateCriticalPoint.unstableProjection`: the same two projections specialized
  to a nondegenerate critical point, which supplies Hessian injectivity.

## References

* M. Audin and M. Damian, *Morse Theory and Floer Homology*, Springer Universitext, 2014,
  Chapter 2.
* J. Milnor, *Morse Theory*, Princeton University Press, 1963, §2.
-/

public section

open InnerProductSpace Set

noncomputable section

namespace ContDiffAt

open EpsilonEridani

variable {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [FiniteDimensional ℝ E]
  {f : E → ℝ} {x : E}

/-- The stable linear subspace of the negative-gradient field at a `C²` point: the span of the
Hessian eigenvectors with positive eigenvalues. The linear flow generated by
`-hessianOperator f x` contracts these directions. -/
noncomputable def stableLinearSubspace (hf : ContDiffAt ℝ 2 f x) : Submodule ℝ E :=
  hf.isSelfAdjoint_hessianOperator.isSymmetric.positiveSpectralSubspace rfl

/-- The unstable linear subspace of the negative-gradient field at a `C²` point: the span of the
Hessian eigenvectors with negative eigenvalues. The linear flow generated by
`-hessianOperator f x` expands these directions in forward time. -/
noncomputable def unstableLinearSubspace (hf : ContDiffAt ℝ 2 f x) : Submodule ℝ E :=
  hf.isSelfAdjoint_hessianOperator.isSymmetric.negativeSpectralSubspace rfl

/-- A vector is stable exactly when its Hessian eigenbasis representation is supported on the
positive eigenvalues. -/
@[simp]
theorem mem_stableLinearSubspace_iff (hf : ContDiffAt ℝ 2 f x) {v : E} :
    v ∈ hf.stableLinearSubspace ↔
      ∀ i ∈ ((hf.isSelfAdjoint_hessianOperator.isSymmetric.eigenvectorBasis
        rfl).toBasis.repr v).support,
        0 < hf.isSelfAdjoint_hessianOperator.isSymmetric.eigenvalues rfl i := by
  rw [stableLinearSubspace,
    LinearMap.IsSymmetric.mem_positiveSpectralSubspace_iff]

/-- A vector is unstable exactly when its Hessian eigenbasis representation is supported on the
negative eigenvalues. -/
@[simp]
theorem mem_unstableLinearSubspace_iff (hf : ContDiffAt ℝ 2 f x) {v : E} :
    v ∈ hf.unstableLinearSubspace ↔
      ∀ i ∈ ((hf.isSelfAdjoint_hessianOperator.isSymmetric.eigenvectorBasis
        rfl).toBasis.repr v).support,
        hf.isSelfAdjoint_hessianOperator.isSymmetric.eigenvalues rfl i < 0 := by
  rw [unstableLinearSubspace,
    LinearMap.IsSymmetric.mem_negativeSpectralSubspace_iff]

/-- The Hessian preserves the stable linear subspace. -/
theorem map_hessianOperator_stableLinearSubspace_le (hf : ContDiffAt ℝ 2 f x) :
    Submodule.map (hessianOperator f x).toLinearMap hf.stableLinearSubspace ≤
      hf.stableLinearSubspace := by
  rw [stableLinearSubspace]
  exact hf.isSelfAdjoint_hessianOperator.isSymmetric.map_positiveSpectralSubspace_le rfl

/-- The Hessian preserves the unstable linear subspace. -/
theorem map_hessianOperator_unstableLinearSubspace_le (hf : ContDiffAt ℝ 2 f x) :
    Submodule.map (hessianOperator f x).toLinearMap hf.unstableLinearSubspace ≤
      hf.unstableLinearSubspace := by
  rw [unstableLinearSubspace]
  exact hf.isSelfAdjoint_hessianOperator.isSymmetric.map_negativeSpectralSubspace_le rfl

/-- The negative-gradient linearization preserves the stable linear subspace. It is
`-hessianOperator f x`, the derivative of `-∇ f` at `x` by
`ContDiffAt.hasFDerivAt_neg_gradient`. -/
theorem map_neg_hessianOperator_stableLinearSubspace_le (hf : ContDiffAt ℝ 2 f x) :
    Submodule.map (-hessianOperator f x).toLinearMap hf.stableLinearSubspace ≤
      hf.stableLinearSubspace := by
  rw [ContinuousLinearMap.toLinearMap_neg, Submodule.map_neg]
  exact hf.map_hessianOperator_stableLinearSubspace_le

/-- The negative-gradient linearization preserves the unstable linear subspace. It is
`-hessianOperator f x`, the derivative of `-∇ f` at `x` by
`ContDiffAt.hasFDerivAt_neg_gradient`. -/
theorem map_neg_hessianOperator_unstableLinearSubspace_le (hf : ContDiffAt ℝ 2 f x) :
    Submodule.map (-hessianOperator f x).toLinearMap hf.unstableLinearSubspace ≤
      hf.unstableLinearSubspace := by
  rw [ContinuousLinearMap.toLinearMap_neg, Submodule.map_neg]
  exact hf.map_hessianOperator_unstableLinearSubspace_le

/-- The stable and unstable linear subspaces at a `C²` point are disjoint. This does not require
nondegeneracy: the zero eigenspace belongs to neither subspace. -/
theorem disjoint_unstableLinearSubspace_stableLinearSubspace (hf : ContDiffAt ℝ 2 f x) :
    Disjoint hf.unstableLinearSubspace hf.stableLinearSubspace := by
  rw [unstableLinearSubspace, stableLinearSubspace]
  exact hf.isSelfAdjoint_hessianOperator.isSymmetric
    |>.disjoint_negativeSpectralSubspace_positiveSpectralSubspace rfl

/-- In the Hessian eigenbasis, the number of negative eigenvalues, counted with multiplicity, is
the Morse index. -/
theorem morseIndex_eq_ncard_hessianOperator_eigenvalues_neg (hf : ContDiffAt ℝ 2 f x) :
    morseIndex f x =
      {i | hf.isSelfAdjoint_hessianOperator.isSymmetric.eigenvalues rfl i < 0}.ncard := by
  let hT := hf.isSelfAdjoint_hessianOperator.isSymmetric
  let b := hT.eigenvectorBasis rfl
  have horth : (QuadraticMap.associated (hessianQuadraticForm f x)).IsOrthoᵢ b := by
    rw [LinearMap.isOrthoᵢ_def]
    intro i j hij
    rw [associated_hessianQuadraticForm hf, ContinuousLinearMap.toBilinForm_apply,
      ← inner_hessianOperator_left]
    have heigen : hessianOperator f x (b i) =
        (hT.eigenvalues rfl i : ℝ) • b i := by
      exact hT.apply_eigenvectorBasis rfl i
    rw [heigen, real_inner_smul_left, orthonormal_iff_ite.mp b.orthonormal i j]
    simp [hij]
  have hequiv : QuadraticMap.Equivalent (hessianQuadraticForm f x)
      (QuadraticMap.weightedSumSquares ℝ fun i ↦ hessianQuadraticForm f x (b i)) :=
    ⟨QuadraticForm.isometryEquivWeightedSumSquares (hessianQuadraticForm f x) b.toBasis horth⟩
  have hweights : (fun i ↦ hessianQuadraticForm f x (b i)) = hT.eigenvalues rfl := by
    funext i
    rw [hessianQuadraticForm_apply, ← inner_hessianOperator_left]
    have heigen : hessianOperator f x (b i) =
        (hT.eigenvalues rfl i : ℝ) • b i := by
      exact hT.apply_eigenvectorBasis rfl i
    rw [heigen, real_inner_smul_left, orthonormal_iff_ite.mp b.orthonormal i i]
    simp
  rw [hweights] at hequiv
  rw [morseIndex_def]
  simpa only [hT] using
    QuadraticForm.sigNeg_of_equiv_weightedSumSquares hequiv

/-- The dimension of the unstable linear subspace at a `C²` point is its Morse index. -/
@[simp]
theorem finrank_unstableLinearSubspace (hf : ContDiffAt ℝ 2 f x) :
    Module.finrank ℝ hf.unstableLinearSubspace = morseIndex f x := by
  rw [unstableLinearSubspace,
    hf.isSelfAdjoint_hessianOperator.isSymmetric.finrank_negativeSpectralSubspace,
    hf.morseIndex_eq_ncard_hessianOperator_eigenvalues_neg]

/-- When the Hessian is injective, the unstable and stable linear subspaces are complementary,
so the tangent space is their direct sum. Injectivity excludes the zero eigenspace; at a
nondegenerate critical point it comes from
`EpsilonEridani.IsNondegenerateCriticalPoint.isInvertible_hessianOperator`. -/
theorem isCompl_unstableLinearSubspace_stableLinearSubspace (hf : ContDiffAt ℝ 2 f x)
    (hker : LinearMap.ker (hessianOperator f x).toLinearMap = ⊥) :
    IsCompl hf.unstableLinearSubspace hf.stableLinearSubspace := by
  rw [unstableLinearSubspace, stableLinearSubspace]
  exact hf.isSelfAdjoint_hessianOperator.isSymmetric
    |>.isCompl_negativeSpectralSubspace_positiveSpectralSubspace_of_ker_eq_bot rfl hker

/-- When the Hessian is injective, the dimension of the stable linear subspace plus the Morse
index is the dimension of the ambient tangent space. -/
theorem finrank_stableLinearSubspace_add_morseIndex (hf : ContDiffAt ℝ 2 f x)
    (hker : LinearMap.ker (hessianOperator f x).toLinearMap = ⊥) :
    Module.finrank ℝ hf.stableLinearSubspace + morseIndex f x = Module.finrank ℝ E := by
  rw [← hf.finrank_unstableLinearSubspace, add_comm]
  exact Submodule.finrank_add_eq_of_isCompl (hf.isCompl_unstableLinearSubspace_stableLinearSubspace
    hker)

/-- When the Hessian is injective, the continuous projection onto the stable linear subspace
along the unstable linear subspace. -/
noncomputable def stableProjection (hf : ContDiffAt ℝ 2 f x)
    (hker : LinearMap.ker (hessianOperator f x).toLinearMap = ⊥) : E →L[ℝ] E :=
  hf.stableLinearSubspace.projectionL hf.unstableLinearSubspace
    (Submodule.IsCompl.isTopCompl_of_isClosed
      (hf.isCompl_unstableLinearSubspace_stableLinearSubspace hker).symm
      hf.stableLinearSubspace.closed_of_finiteDimensional
      hf.unstableLinearSubspace.closed_of_finiteDimensional)

/-- The range of the stable projection is the stable linear subspace. -/
@[simp]
theorem range_stableProjection (hf : ContDiffAt ℝ 2 f x)
    (hker : LinearMap.ker (hessianOperator f x).toLinearMap = ⊥) :
    (hf.stableProjection hker).range = hf.stableLinearSubspace := by
  rw [stableProjection, Submodule.range_projectionL]

/-- The kernel of the stable projection is the unstable linear subspace. -/
@[simp]
theorem ker_stableProjection (hf : ContDiffAt ℝ 2 f x)
    (hker : LinearMap.ker (hessianOperator f x).toLinearMap = ⊥) :
    (hf.stableProjection hker).ker = hf.unstableLinearSubspace := by
  rw [stableProjection, Submodule.ker_projectionL]

/-- The stable projection is idempotent. -/
theorem isIdempotentElem_stableProjection (hf : ContDiffAt ℝ 2 f x)
    (hker : LinearMap.ker (hessianOperator f x).toLinearMap = ⊥) :
    IsIdempotentElem (hf.stableProjection hker) := by
  rw [stableProjection]
  exact Submodule.isIdempotentElem_projectionL _

/-- A vector is killed by the stable projection exactly when it is unstable. -/
@[simp]
theorem stableProjection_apply_eq_zero_iff (hf : ContDiffAt ℝ 2 f x)
    (hker : LinearMap.ker (hessianOperator f x).toLinearMap = ⊥) {v : E} :
    hf.stableProjection hker v = 0 ↔ v ∈ hf.unstableLinearSubspace := by
  rw [stableProjection, Submodule.projectionL_apply_eq_zero_iff]

/-- A vector is fixed by the stable projection exactly when it is stable. -/
@[simp]
theorem stableProjection_apply_eq_self_iff (hf : ContDiffAt ℝ 2 f x)
    (hker : LinearMap.ker (hessianOperator f x).toLinearMap = ⊥) {v : E} :
    hf.stableProjection hker v = v ↔ v ∈ hf.stableLinearSubspace := by
  rw [stableProjection, Submodule.projectionL_eq_self_iff]

/-- The stable projection takes every vector into the stable linear subspace. -/
theorem stableProjection_apply_mem (hf : ContDiffAt ℝ 2 f x)
    (hker : LinearMap.ker (hessianOperator f x).toLinearMap = ⊥) (v : E) :
    hf.stableProjection hker v ∈ hf.stableLinearSubspace := by
  rw [stableProjection]
  exact Submodule.projectionL_apply_mem _ _

/-- The negative Hessian operator commutes with the projection onto its stable linear subspace. -/
theorem commute_neg_hessianOperator_stableProjection (hf : ContDiffAt ℝ 2 f x)
    (hker : LinearMap.ker (hessianOperator f x).toLinearMap = ⊥) :
    Commute (-hessianOperator f x) (hf.stableProjection hker) := by
  apply Commute.symm
  rw [ContinuousLinearMap.IsIdempotentElem.commute_iff
    (hf.isIdempotentElem_stableProjection hker), hf.range_stableProjection hker,
    hf.ker_stableProjection hker]
  constructor
  · intro v hv
    exact hf.map_neg_hessianOperator_stableLinearSubspace_le ⟨v, hv, rfl⟩
  · intro v hv
    exact hf.map_neg_hessianOperator_unstableLinearSubspace_le ⟨v, hv, rfl⟩

/-- When the Hessian is injective, the continuous projection onto the unstable linear subspace
along the stable linear subspace: the projection complementary to `ContDiffAt.stableProjection`. -/
noncomputable def unstableProjection (hf : ContDiffAt ℝ 2 f x)
    (hker : LinearMap.ker (hessianOperator f x).toLinearMap = ⊥) : E →L[ℝ] E :=
  ContinuousLinearMap.id ℝ E - hf.stableProjection hker

/-- The unstable projection is the identity minus the stable projection. -/
theorem unstableProjection_def (hf : ContDiffAt ℝ 2 f x)
    (hker : LinearMap.ker (hessianOperator f x).toLinearMap = ⊥) :
    hf.unstableProjection hker = ContinuousLinearMap.id ℝ E - hf.stableProjection hker := by
  rw [unstableProjection]

/-- The unstable projection subtracts the stable component. -/
theorem unstableProjection_apply (hf : ContDiffAt ℝ 2 f x)
    (hker : LinearMap.ker (hessianOperator f x).toLinearMap = ⊥) (v : E) :
    hf.unstableProjection hker v = v - hf.stableProjection hker v := by
  simp [unstableProjection]

/-- The unstable projection is idempotent. -/
theorem isIdempotentElem_unstableProjection (hf : ContDiffAt ℝ 2 f x)
    (hker : LinearMap.ker (hessianOperator f x).toLinearMap = ⊥) :
    IsIdempotentElem (hf.unstableProjection hker) := by
  rw [unstableProjection]
  exact (hf.isIdempotentElem_stableProjection hker).one_sub

/-- The range of the unstable projection is the unstable linear subspace. -/
@[simp]
theorem range_unstableProjection (hf : ContDiffAt ℝ 2 f x)
    (hker : LinearMap.ker (hessianOperator f x).toLinearMap = ⊥) :
    (hf.unstableProjection hker).range = hf.unstableLinearSubspace := by
  rw [← hf.ker_stableProjection hker]
  have hP : IsIdempotentElem (hf.stableProjection hker).toLinearMap :=
    congrArg ContinuousLinearMap.toLinearMap (hf.isIdempotentElem_stableProjection hker).eq
  -- The complementary-range lemma is stated for linear maps, so expose the underlying maps.
  change LinearMap.range (LinearMap.id - (hf.stableProjection hker).toLinearMap) =
    LinearMap.ker (hf.stableProjection hker).toLinearMap
  exact (LinearMap.IsIdempotentElem.ker_eq_range_one_sub hP).symm

/-- The kernel of the unstable projection is the stable linear subspace. -/
@[simp]
theorem ker_unstableProjection (hf : ContDiffAt ℝ 2 f x)
    (hker : LinearMap.ker (hessianOperator f x).toLinearMap = ⊥) :
    (hf.unstableProjection hker).ker = hf.stableLinearSubspace := by
  rw [← hf.range_stableProjection hker]
  have hP : IsIdempotentElem (hf.stableProjection hker).toLinearMap :=
    congrArg ContinuousLinearMap.toLinearMap (hf.isIdempotentElem_stableProjection hker).eq
  -- The complementary-kernel lemma is stated for linear maps, so expose the underlying maps.
  change LinearMap.ker (LinearMap.id - (hf.stableProjection hker).toLinearMap) =
    LinearMap.range (hf.stableProjection hker).toLinearMap
  exact (LinearMap.IsIdempotentElem.range_eq_ker_one_sub hP).symm

/-- A vector is killed by the unstable projection exactly when it is stable. -/
@[simp]
theorem unstableProjection_apply_eq_zero_iff (hf : ContDiffAt ℝ 2 f x)
    (hker : LinearMap.ker (hessianOperator f x).toLinearMap = ⊥) {v : E} :
    hf.unstableProjection hker v = 0 ↔ v ∈ hf.stableLinearSubspace := by
  rw [← hf.ker_unstableProjection hker]
  exact (LinearMap.mem_ker (f := (hf.unstableProjection hker).toLinearMap)).symm

/-- A vector is fixed by the unstable projection exactly when it is unstable. -/
@[simp]
theorem unstableProjection_apply_eq_self_iff (hf : ContDiffAt ℝ 2 f x)
    (hker : LinearMap.ker (hessianOperator f x).toLinearMap = ⊥) {v : E} :
    hf.unstableProjection hker v = v ↔ v ∈ hf.unstableLinearSubspace := by
  rw [← hf.range_unstableProjection hker]
  exact (LinearMap.IsIdempotentElem.mem_range_iff
    (congrArg ContinuousLinearMap.toLinearMap
      (hf.isIdempotentElem_unstableProjection hker).eq)).symm

/-- The unstable projection takes every vector into the unstable linear subspace. -/
theorem unstableProjection_apply_mem (hf : ContDiffAt ℝ 2 f x)
    (hker : LinearMap.ker (hessianOperator f x).toLinearMap = ⊥) (v : E) :
    hf.unstableProjection hker v ∈ hf.unstableLinearSubspace := by
  rw [← hf.range_unstableProjection hker]
  exact LinearMap.mem_range_self _ v

/-- The negative Hessian operator commutes with the projection onto its unstable linear
subspace. -/
theorem commute_neg_hessianOperator_unstableProjection (hf : ContDiffAt ℝ 2 f x)
    (hker : LinearMap.ker (hessianOperator f x).toLinearMap = ⊥) :
    Commute (-hessianOperator f x) (hf.unstableProjection hker) := by
  rw [unstableProjection]
  exact (Commute.one_right _).sub_right (hf.commute_neg_hessianOperator_stableProjection hker)

end ContDiffAt

namespace EpsilonEridani

variable {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [FiniteDimensional ℝ E]
  {f : E → ℝ} {x : E}

/-- At a nondegenerate critical point the unstable and stable linear subspaces are complementary,
so the tangent space is their direct sum. -/
theorem IsNondegenerateCriticalPoint.isCompl_unstableLinearSubspace_stableLinearSubspace
    (h : IsNondegenerateCriticalPoint f x) :
    IsCompl h.contDiffAt.unstableLinearSubspace h.contDiffAt.stableLinearSubspace :=
  h.contDiffAt.isCompl_unstableLinearSubspace_stableLinearSubspace
    (LinearMap.ker_eq_bot.2 h.isInvertible_hessianOperator.injective)

/-- At a nondegenerate critical point the dimension of the stable linear subspace plus the Morse
index is the dimension of the ambient tangent space. -/
theorem IsNondegenerateCriticalPoint.finrank_stableLinearSubspace_add_morseIndex
    (h : IsNondegenerateCriticalPoint f x) :
    Module.finrank ℝ h.contDiffAt.stableLinearSubspace + morseIndex f x = Module.finrank ℝ E :=
  h.contDiffAt.finrank_stableLinearSubspace_add_morseIndex
    (LinearMap.ker_eq_bot.2 h.isInvertible_hessianOperator.injective)

namespace IsNondegenerateCriticalPoint

/-- The continuous projection onto the stable linear subspace at a nondegenerate critical
point, along the unstable linear subspace. -/
noncomputable def stableProjection (h : IsNondegenerateCriticalPoint f x) : E →L[ℝ] E :=
  h.contDiffAt.stableProjection
    (LinearMap.ker_eq_bot.2 h.isInvertible_hessianOperator.injective)

/-- The continuous projection onto the unstable linear subspace at a nondegenerate critical
point, complementary to `stableProjection`. -/
noncomputable def unstableProjection (h : IsNondegenerateCriticalPoint f x) : E →L[ℝ] E :=
  ContinuousLinearMap.id ℝ E - h.stableProjection

/-- The unstable projection is the complementary projection to the stable projection. -/
theorem unstableProjection_def (h : IsNondegenerateCriticalPoint f x) :
    h.unstableProjection = ContinuousLinearMap.id ℝ E - h.stableProjection := by
  rw [unstableProjection]

/-- The unstable projection is the identity minus the stable projection. -/
theorem unstableProjection_apply (h : IsNondegenerateCriticalPoint f x) (v : E) :
    h.unstableProjection v = v - h.stableProjection v := by
  simp [unstableProjection]

/-- The stable projection at a nondegenerate critical point is the general stable projection
formed using the Hessian injectivity supplied by nondegeneracy. -/
theorem stableProjection_eq_contDiffAt (h : IsNondegenerateCriticalPoint f x) :
    h.stableProjection = h.contDiffAt.stableProjection
      (LinearMap.ker_eq_bot.2 h.isInvertible_hessianOperator.injective) := by
  rw [stableProjection]

/-- The unstable projection at a nondegenerate critical point is the general unstable projection
formed using the Hessian injectivity supplied by nondegeneracy. -/
theorem unstableProjection_eq_contDiffAt (h : IsNondegenerateCriticalPoint f x) :
    h.unstableProjection = h.contDiffAt.unstableProjection
      (LinearMap.ker_eq_bot.2 h.isInvertible_hessianOperator.injective) := by
  rw [unstableProjection, ContDiffAt.unstableProjection, stableProjection]

/-- The range of the stable projection at a nondegenerate critical point is the stable linear
subspace. -/
@[simp]
theorem range_stableProjection (h : IsNondegenerateCriticalPoint f x) :
    h.stableProjection.range = h.contDiffAt.stableLinearSubspace := by
  simpa only [stableProjection] using h.contDiffAt.range_stableProjection
    (LinearMap.ker_eq_bot.2 h.isInvertible_hessianOperator.injective)

/-- The kernel of the stable projection at a nondegenerate critical point is the unstable linear
subspace. -/
@[simp]
theorem ker_stableProjection (h : IsNondegenerateCriticalPoint f x) :
    h.stableProjection.ker = h.contDiffAt.unstableLinearSubspace := by
  simpa only [stableProjection] using h.contDiffAt.ker_stableProjection
    (LinearMap.ker_eq_bot.2 h.isInvertible_hessianOperator.injective)

/-- The stable projection at a nondegenerate critical point is idempotent. -/
theorem isIdempotentElem_stableProjection (h : IsNondegenerateCriticalPoint f x) :
    IsIdempotentElem h.stableProjection := by
  simpa only [stableProjection] using h.contDiffAt.isIdempotentElem_stableProjection
    (LinearMap.ker_eq_bot.2 h.isInvertible_hessianOperator.injective)

/-- The range of the unstable projection is the unstable linear subspace. -/
@[simp]
theorem range_unstableProjection (h : IsNondegenerateCriticalPoint f x) :
    h.unstableProjection.range = h.contDiffAt.unstableLinearSubspace := by
  rw [h.unstableProjection_eq_contDiffAt, ContDiffAt.range_unstableProjection]

/-- The kernel of the unstable projection is the stable linear subspace. -/
@[simp]
theorem ker_unstableProjection (h : IsNondegenerateCriticalPoint f x) :
    h.unstableProjection.ker = h.contDiffAt.stableLinearSubspace := by
  rw [h.unstableProjection_eq_contDiffAt, ContDiffAt.ker_unstableProjection]

/-- The unstable projection is idempotent. -/
theorem isIdempotentElem_unstableProjection (h : IsNondegenerateCriticalPoint f x) :
    IsIdempotentElem h.unstableProjection := by
  rw [h.unstableProjection_eq_contDiffAt]
  exact h.contDiffAt.isIdempotentElem_unstableProjection _

/-- A vector is killed by the stable projection at a nondegenerate critical point exactly when it
is unstable. -/
@[simp]
theorem stableProjection_apply_eq_zero_iff (h : IsNondegenerateCriticalPoint f x) {v : E} :
    h.stableProjection v = 0 ↔ v ∈ h.contDiffAt.unstableLinearSubspace := by
  simpa only [stableProjection] using h.contDiffAt.stableProjection_apply_eq_zero_iff
    (LinearMap.ker_eq_bot.2 h.isInvertible_hessianOperator.injective) (v := v)

/-- A vector is fixed by the stable projection at a nondegenerate critical point exactly when it
is stable. -/
@[simp]
theorem stableProjection_apply_eq_self_iff (h : IsNondegenerateCriticalPoint f x) {v : E} :
    h.stableProjection v = v ↔ v ∈ h.contDiffAt.stableLinearSubspace := by
  simpa only [stableProjection] using h.contDiffAt.stableProjection_apply_eq_self_iff
    (LinearMap.ker_eq_bot.2 h.isInvertible_hessianOperator.injective) (v := v)

/-- A vector is killed by the unstable projection exactly when it is stable. -/
@[simp]
theorem unstableProjection_apply_eq_zero_iff (h : IsNondegenerateCriticalPoint f x) {v : E} :
    h.unstableProjection v = 0 ↔ v ∈ h.contDiffAt.stableLinearSubspace := by
  rw [h.unstableProjection_eq_contDiffAt, ContDiffAt.unstableProjection_apply_eq_zero_iff]

/-- A vector is fixed by the unstable projection exactly when it is unstable. -/
@[simp]
theorem unstableProjection_apply_eq_self_iff (h : IsNondegenerateCriticalPoint f x) {v : E} :
    h.unstableProjection v = v ↔ v ∈ h.contDiffAt.unstableLinearSubspace := by
  rw [h.unstableProjection_eq_contDiffAt, ContDiffAt.unstableProjection_apply_eq_self_iff]

/-- The unstable projection takes every vector into the unstable linear subspace. -/
theorem unstableProjection_apply_mem (h : IsNondegenerateCriticalPoint f x) (v : E) :
    h.unstableProjection v ∈ h.contDiffAt.unstableLinearSubspace := by
  rw [h.unstableProjection_eq_contDiffAt]
  exact h.contDiffAt.unstableProjection_apply_mem _ v

/-- The stable projection at a nondegenerate critical point takes every vector into the stable
linear subspace. -/
theorem stableProjection_apply_mem (h : IsNondegenerateCriticalPoint f x) (v : E) :
    h.stableProjection v ∈ h.contDiffAt.stableLinearSubspace := by
  simpa only [stableProjection] using h.contDiffAt.stableProjection_apply_mem
    (LinearMap.ker_eq_bot.2 h.isInvertible_hessianOperator.injective) v

/-- The negative Hessian operator commutes with the stable projection at a nondegenerate critical
point. -/
theorem commute_neg_hessianOperator_stableProjection (h : IsNondegenerateCriticalPoint f x) :
    Commute (-hessianOperator f x) h.stableProjection := by
  simpa only [stableProjection] using h.contDiffAt.commute_neg_hessianOperator_stableProjection
    (LinearMap.ker_eq_bot.2 h.isInvertible_hessianOperator.injective)

/-- The negative Hessian operator commutes with the unstable projection at a nondegenerate
critical point. -/
theorem commute_neg_hessianOperator_unstableProjection (h : IsNondegenerateCriticalPoint f x) :
    Commute (-hessianOperator f x) h.unstableProjection := by
  rw [h.unstableProjection_eq_contDiffAt]
  exact h.contDiffAt.commute_neg_hessianOperator_unstableProjection _

end IsNondegenerateCriticalPoint

end EpsilonEridani

end
