/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.Lie.Semisimple.Basic

/-!
# Modules over a Lie subalgebra which is the whole algebra

A Lie subalgebra `L₁` of `L` acts on every `L`-module by restriction along the inclusion. When
`L₁ = ⊤` that restriction loses nothing, because every element of `L` is the underlying element of
one of `L₁`: the two actions have the same invariant subspaces, hence the same irreducibility, and
a map intertwining the one intertwines the other.

Mathlib has `LieSubalgebra.topEquiv`, the equivalence `(⊤ : LieSubalgebra R L) ≃ₗ⁅R⁆ L` of Lie
algebras. That equivalence does not by itself move module-level statements, because a module over
`L₁` is not the transport of a module over `L` along it but the same module with a restricted
action; the three declarations below say what that restriction does to submodules, to
irreducibility, and to equivalences.

The intended use is a Lie algebra presented as generated by a distinguished family, where a
hypothesis is naturally stated over the subalgebra that family generates and the conclusion is
wanted over the whole algebra. `EpsilonEridani/Algebra/Lie/Sl2/WeightString.lean` classifies modules
irreducible over the subalgebra generated by an `sl₂` triple, and
`EpsilonEridani/Algebra/Lie/Sl2/Classification.lean` converts that into a statement about
`LieAlgebra.SpecialLinear.sl (Fin 2) K`-modules, the standard triple generating all of
`sl (Fin 2) K`.

## Main definitions

* `EpsilonEridani.lieSubmoduleOfEqTop`: a submodule for a Lie subalgebra which is everything, read as a
  submodule for the whole Lie algebra.
* `EpsilonEridani.lieModuleEquivOfEqTop`: an equivalence of modules over a Lie subalgebra which is
  everything, read as an equivalence of modules over the whole Lie algebra.

## Main results

* `EpsilonEridani.isIrreducible_of_eq_top`: a module irreducible over a Lie algebra is irreducible over
  any Lie subalgebra which is the whole algebra.

## Implementation notes

Neither definition is exposed: each is a repackaging that changes no data, and the equations
`EpsilonEridani.lieSubmoduleOfEqTop_toSubmodule` and `EpsilonEridani.lieModuleEquivOfEqTop_apply` recording that
are the whole elimination API, so nothing downstream needs to unfold further. Those two equations
are proved by the parenthesised `(rfl)`, which elaborates against the definitions themselves; a
bare `rfl` in an exported theorem would demand that they be `@[expose]`d.
-/

public section

namespace EpsilonEridani

variable {R L : Type*} [CommRing R] [LieRing L] [LieAlgebra R L]
variable {M : Type*} [AddCommGroup M] [Module R M] [LieRingModule L M]
variable {N : Type*} [AddCommGroup N] [Module R N] [LieRingModule L N]
variable {L₁ : LieSubalgebra R L}

/-- A submodule for a Lie subalgebra which is the whole Lie algebra, read as a submodule for the
whole Lie algebra: an element of `L` acts as the element of `L₁` it underlies. -/
def lieSubmoduleOfEqTop (hL₁ : L₁ = ⊤) (P : LieSubmodule R L₁ M) : LieSubmodule R L M where
  __ := P.toSubmodule
  lie_mem {x _} hm := P.lie_mem (x := ⟨x, hL₁ ▸ LieSubalgebra.mem_top x⟩) hm

@[simp]
theorem lieSubmoduleOfEqTop_toSubmodule (hL₁ : L₁ = ⊤) (P : LieSubmodule R L₁ M) :
    (lieSubmoduleOfEqTop hL₁ P).toSubmodule = P.toSubmodule :=
  (rfl)

/-- **Irreducibility descends to a Lie subalgebra which is everything.** The submodules for the two
actions are the same, so the lattice of submodules is simple for the one exactly when it is for the
other; only the direction needed in practice is recorded. -/
theorem isIrreducible_of_eq_top (hL₁ : L₁ = ⊤)
    [LieModule.IsIrreducible R L M] : LieModule.IsIrreducible R L₁ M := by
  have : Nontrivial M := LieModule.nontrivial_of_isIrreducible R L M
  refine LieModule.IsIrreducible.mk fun P hP => ?_
  refine (LieSubmodule.toSubmodule_eq_top P).1 ?_
  rcases IsSimpleOrder.eq_bot_or_eq_top (lieSubmoduleOfEqTop hL₁ P) with hbot | htop
  · exact absurd ((LieSubmodule.toSubmodule_eq_bot P).1 (congrArg LieSubmodule.toSubmodule hbot)) hP
  · exact congrArg LieSubmodule.toSubmodule htop

/-- **An equivalence over a Lie subalgebra which is everything is an equivalence over the whole
algebra.** A linear equivalence intertwining the action of every element of `L₁` intertwines the
action of every element of `L`, each of which underlies one of `L₁`. -/
def lieModuleEquivOfEqTop (hL₁ : L₁ = ⊤) (φ : M ≃ₗ⁅R,L₁⁆ N) : M ≃ₗ⁅R,L⁆ N :=
  { (φ : M ≃ₗ[R] N) with
    map_lie' := by
      intro x m
      -- The `map_lie'` goal is phrased with the anonymous constructor's `toFun`, which is `φ` only
      -- after the bundled `LinearEquiv` of the `with`-clause is unfolded.
      change φ ⁅x, m⁆ = ⁅x, φ m⁆
      simpa using φ.map_lie ⟨x, hL₁ ▸ LieSubalgebra.mem_top x⟩ m }

@[simp]
theorem lieModuleEquivOfEqTop_apply (hL₁ : L₁ = ⊤) (φ : M ≃ₗ⁅R,L₁⁆ N) (m : M) :
    lieModuleEquivOfEqTop hL₁ φ m = φ m :=
  (rfl)

end EpsilonEridani
