/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.MeasureTheory.MeasurableSpace.CountablyGenerated
public import EpsilonEridani.Order.Partition.Finpartition
import Mathlib.MeasureTheory.MeasurableSpace.Constructions

/-!
# Measurable finite partitions

This file records elementary ways to construct measurable finite partitions and shows that
measurability passes from a finer finite partition to a coarser one. It also makes the canonical
map from a point to its finite-partition index measurable and packages the canonical finite
partitions of a countably generated measurable space as `Finpartition`s.
-/

public section

open Set

namespace Finpartition

variable {Ω : Type*} [MeasurableSpace Ω]

/-- The map sending a point to its part in a measurable finite partition is measurable, for any
measurable space structure on the finite type of parts — in particular for the discrete one.
Countability of the parts is what makes an arbitrary structure on them admissible: measurability of
the fibres already forces measurability of every preimage. -/
theorem measurable_indexedPartition_index (P : Finpartition (Set.univ : Set Ω))
    [MeasurableSpace P.parts] (hP : ∀ p ∈ P.parts, MeasurableSet p) :
    Measurable P.indexedPartition.index := by
  refine measurable_to_countable' fun p => ?_
  have hpreimage : P.indexedPartition.index ⁻¹' {p} = (p : Set Ω) := by
    ext x
    exact P.indexedPartition.mem_iff_index_eq.symm
  rw [hpreimage]
  exact hP p p.property

omit [MeasurableSpace Ω] in
/-- The σ-algebra generated by the parts of a finite partition is the pullback of the discrete
σ-algebra along the map sending a point to its part. -/
theorem comap_indexedPartition_index_top (P : Finpartition (Set.univ : Set Ω)) :
    MeasurableSpace.comap P.indexedPartition.index ⊤ =
      MeasurableSpace.generateFrom (P.parts : Set (Set Ω)) := by
  apply le_antisymm
  · let m : MeasurableSpace Ω := MeasurableSpace.generateFrom (P.parts : Set (Set Ω))
    let _ : MeasurableSpace P.parts := ⊤
    have hmeas : @Measurable Ω P.parts m (inferInstance) P.indexedPartition.index := by
      refine measurable_to_countable' fun p => ?_
      have hpreimage : P.indexedPartition.index ⁻¹' {p} = (p : Set Ω) := by
        ext x
        exact P.indexedPartition.mem_iff_index_eq.symm
      rw [hpreimage]
      exact MeasurableSpace.measurableSet_generateFrom p.property
    exact hmeas.comap_le
  · refine MeasurableSpace.generateFrom_le fun p hp => ?_
    refine ⟨{⟨p, hp⟩}, MeasurableSpace.measurableSet_top, ?_⟩
    ext x
    simpa only [Set.mem_preimage, Set.mem_singleton_iff] using
      (P.indexedPartition.mem_iff_index_eq (x := x) (i := ⟨p, hp⟩)).symm

/-- The canonical finite partition at level `n` of a countably generated measurable space.

Its nonempty parts are Mathlib's `MeasurableSpace.countablePartition Ω n`; the empty member of
that set-valued partition is discarded, as required by `Finpartition`. -/
noncomputable def countablePartition (Ω : Type*) [MeasurableSpace Ω]
    [MeasurableSpace.CountablyGenerated Ω]
    (n : ℕ) : Finpartition (Set.univ : Set Ω) :=
  (Finpartition.ofPairwiseDisjoint
    (MeasurableSpace.finite_countablePartition Ω n).toFinset (by
      intro s hs t ht hst
      exact MeasurableSpace.disjoint_countablePartition
        ((MeasurableSpace.finite_countablePartition Ω n).mem_toFinset.mp hs)
        ((MeasurableSpace.finite_countablePartition Ω n).mem_toFinset.mp ht) hst)).copy (by
          rw [Finset.sup_id_set_eq_sUnion,
            MeasurableSpace.finite_countablePartition Ω n |>.coe_toFinset,
            MeasurableSpace.sUnion_countablePartition])

/-- The parts of the canonical `Finpartition` are the nonempty members of Mathlib's canonical
finite set-valued partition. -/
@[simp]
theorem parts_countablePartition (Ω : Type*) [MeasurableSpace Ω]
    [MeasurableSpace.CountablyGenerated Ω]
    (n : ℕ) :
    (countablePartition Ω n).parts =
      (MeasurableSpace.finite_countablePartition Ω n).toFinset.erase ∅ := by
  rfl

/-- The canonical finite partitions become finer as the level increases. -/
theorem countablePartition_antitone (Ω : Type*) [MeasurableSpace Ω]
    [MeasurableSpace.CountablyGenerated Ω] : Antitone (countablePartition Ω) := by
  apply antitone_nat_of_succ_le
  intro n s hs
  rw [parts_countablePartition, Finset.mem_erase] at hs
  have hs' : s ∈ MeasurableSpace.countablePartition Ω (n + 1) :=
    (MeasurableSpace.finite_countablePartition Ω (n + 1)).mem_toFinset.mp hs.2
  rw [MeasurableSpace.countablePartition, memPartition_succ] at hs'
  obtain ⟨u, hu, rfl | rfl⟩ := hs'
  · refine ⟨u, ?_, Set.inter_subset_left⟩
    rw [parts_countablePartition, Finset.mem_erase]
    exact ⟨fun h => hs.1 (by simp [h]),
      (MeasurableSpace.finite_countablePartition Ω n).mem_toFinset.mpr hu⟩
  · refine ⟨u, ?_, Set.sdiff_subset⟩
    rw [parts_countablePartition, Finset.mem_erase]
    exact ⟨fun h => hs.1 (by simp [h]),
      (MeasurableSpace.finite_countablePartition Ω n).mem_toFinset.mpr hu⟩

/-- Every part of the canonical finite partition of a countably generated measurable space is
measurable. -/
theorem measurableSet_of_mem_countablePartition (Ω : Type*) [MeasurableSpace Ω]
    [MeasurableSpace.CountablyGenerated Ω] (n : ℕ) {s : Set Ω}
    (hs : s ∈ (countablePartition Ω n).parts) :
    MeasurableSet s := by
  rw [parts_countablePartition, Finset.mem_erase] at hs
  exact MeasurableSpace.measurableSet_countablePartition n
    ((MeasurableSpace.finite_countablePartition Ω n).mem_toFinset.mp hs.2)

/-- The index map of the canonical finite partition generates Mathlib's canonical finite
σ-algebra at the same level. -/
theorem comap_countablePartition_index_top (Ω : Type*) [MeasurableSpace Ω]
    [MeasurableSpace.CountablyGenerated Ω] (n : ℕ) :
    MeasurableSpace.comap (countablePartition Ω n).indexedPartition.index ⊤ =
      MeasurableSpace.generateFrom (MeasurableSpace.countablePartition Ω n) := by
  rw [comap_indexedPartition_index_top, parts_countablePartition]
  apply le_antisymm
  · refine MeasurableSpace.generateFrom_le fun s hs => ?_
    exact MeasurableSpace.measurableSet_generateFrom
      ((MeasurableSpace.finite_countablePartition Ω n).mem_toFinset.mp
        (Finset.mem_erase.mp hs).2)
  · refine MeasurableSpace.generateFrom_le fun s hs => ?_
    by_cases hsempty : s = ∅
    · subst s
      exact @MeasurableSet.empty Ω
        (MeasurableSpace.generateFrom
          ((MeasurableSpace.finite_countablePartition Ω n).toFinset.erase ∅))
    · exact MeasurableSpace.measurableSet_generateFrom
        (Finset.mem_erase.mpr ⟨hsempty,
          (MeasurableSpace.finite_countablePartition Ω n).mem_toFinset.mpr hs⟩)

/-- Every part of a bipartition along a measurable set is measurable. -/
theorem measurableSet_of_mem_bipartition {s p : Set Ω} (hs : MeasurableSet s)
    (hp : p ∈ (bipartition s).parts) : MeasurableSet p := by
  rw [parts_bipartition, Finset.mem_erase, Finset.mem_insert, Finset.mem_singleton] at hp
  rcases hp.2 with rfl | rfl
  · exact hs
  · exact hs.compl

/-- The common refinement of two measurable finite partitions is measurable. -/
theorem measurableSet_of_mem_inf {u : Set Ω} {P Q : Finpartition u}
    (hP : ∀ p ∈ P.parts, MeasurableSet p) (hQ : ∀ q ∈ Q.parts, MeasurableSet q)
    {r : Set Ω} (hr : r ∈ (P ⊓ Q).parts) : MeasurableSet r := by
  rw [Finpartition.parts_inf, Finset.mem_erase, Finset.mem_image] at hr
  obtain ⟨_, pq, hpq, rfl⟩ := hr
  rw [Finset.mem_product] at hpq
  exact (hP pq.1 hpq.1).inter (hQ pq.2 hpq.2)

/-- A part of a finite partition is measurable when it is a union of parts of a measurable
refinement. -/
theorem measurableSet_of_mem_of_le {u : Set Ω} {P Q : Finpartition u}
    (hQ : ∀ q ∈ Q.parts, MeasurableSet q) (href : Q ≤ P) {p : Set Ω} (hp : p ∈ P.parts) :
    MeasurableSet p := by
  classical
  let parts := Q.parts.filter fun q => q ⊆ p
  have hp_eq : p = ⋃₀ (parts : Set (Set Ω)) := by
    ext x
    constructor
    · intro hx
      have hx_parts : x ∈ ⋃₀ (Q.parts : Set (Set Ω)) := by
        rw [← Finset.sup_id_set_eq_sUnion, Q.sup_parts]
        exact P.le hp hx
      obtain ⟨q, hq, hxq⟩ := Set.mem_sUnion.1 hx_parts
      obtain ⟨p', hp', hqp'⟩ := href hq
      have hp'p : p' = p := P.disjoint.elim hp' hp <|
        Set.not_disjoint_iff.2 ⟨x, hqp' hxq, hx⟩
      exact Set.mem_sUnion.2 ⟨q, Finset.mem_filter.2 ⟨hq, hp'p ▸ hqp'⟩, hxq⟩
    · intro hx
      obtain ⟨q, hq, hxq⟩ := Set.mem_sUnion.1 hx
      exact (Finset.mem_filter.1 hq).2 hxq
  rw [hp_eq]
  exact parts.finite_toSet.measurableSet_sUnion fun q hq =>
    hQ q (Finset.mem_filter.1 hq).1

end Finpartition
