/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.GroupTheory.FreeGroup.Basic
public import EpsilonEridani.Topology.Algebra.Group.Profinite.Completion

/-!
# The free profinite group on a type

The **free profinite group** on a type `X` is the profinite completion of the discrete free
group on `X`. This file constructs it together with the data that pins it down: the canonical
map `freeProfiniteGroup.of` from `X`, the universal property that a map from `X` to a profinite
group extends uniquely to a continuous homomorphism, and the resulting functoriality in `X`.

The universal property is stated for an unbundled profinite target, so that it applies without
first packaging the target as an object of `ProfiniteGrp`; the target must nevertheless live in
the same universe as `X`, because the completion of a group in `Type u` is again in `Type u`.
Uniqueness is separated into `freeProfiniteGroup.hom_ext`, whose target need only be a Hausdorff
topological space carrying a group structure, with no `IsTopologicalGroup` instance required:
two continuous homomorphisms that agree on the generators agree on the dense subgroup the
generators generate.

## Main definitions

* `freeProfiniteGroup X`: the free profinite group on `X`, as an object of `ProfiniteGrp`.
* `freeProfiniteGroup.of`: the canonical map from `X` to the free profinite group.
* `freeProfiniteGroup.fromFreeGroup`: the canonical homomorphism from the discrete free group.
* `freeProfiniteGroup.lift`: the continuous homomorphism extending a map on generators.
* `freeProfiniteGroup.map`: the continuous homomorphism induced by a map of generating types.

## Main results

* `freeProfiniteGroup.dense_closure_range_of`: the generators generate topologically.
* `freeProfiniteGroup.hom_ext`: continuous homomorphisms agreeing on the generators are equal.
* `freeProfiniteGroup.existsUnique_lift`: the universal property.
* `freeProfiniteGroup.map_surjective`: a surjection of generating types induces a surjection.
* `freeProfiniteGroup.existsUnique_continuousMulEquiv`: the free profinite group is unique up to
  a unique topological isomorphism matching the generators.

## References

* L. Ribes and P. Zalesskii, *Profinite Groups*, Chapter 3.
-/

public section

namespace EpsilonEridani

open CategoryTheory

universe u v

/-- The **free profinite group** on a type `X`: the profinite completion of the discrete free
group on `X`. What pins this construction down is its universal property,
`freeProfiniteGroup.existsUnique_lift`. -/
noncomputable abbrev freeProfiniteGroup (X : Type u) : ProfiniteGrp.{u} :=
  ProfiniteGrp.ProfiniteCompletion.completion (GrpCat.of (FreeGroup X))

namespace freeProfiniteGroup

variable {X Y Z : Type u}

/-- The canonical homomorphism from the discrete free group on `X` to the free profinite group
on `X`. It is Mathlib's unit `ProfiniteGrp.ProfiniteCompletion.eta` at `FreeGroup X`, read as a
plain monoid homomorphism rather than as a morphism of `GrpCat`. -/
noncomputable def fromFreeGroup (X : Type u) : FreeGroup X →* freeProfiniteGroup X :=
  (ProfiniteGrp.ProfiniteCompletion.eta (GrpCat.of (FreeGroup X))).hom

/-- The canonical map from the generating type into the free profinite group. -/
noncomputable def of (x : X) : freeProfiniteGroup X :=
  fromFreeGroup X (FreeGroup.of x)

/-- `fromFreeGroup` carries the free-group generator at `x` to the generator `of x`. -/
@[simp]
theorem fromFreeGroup_of (x : X) : fromFreeGroup X (FreeGroup.of x) = of x :=
  (rfl)

/-- The underlying function of `fromFreeGroup` is the unit map into the profinite completion. -/
theorem coe_fromFreeGroup (X : Type u) :
    ⇑(fromFreeGroup X) = ProfiniteGrp.ProfiniteCompletion.etaFn (GrpCat.of (FreeGroup X)) :=
  (rfl)

/-- The image of the discrete free group is the subgroup generated by the generators. -/
theorem range_fromFreeGroup (X : Type u) :
    (fromFreeGroup X).range = Subgroup.closure (Set.range (of : X → freeProfiniteGroup X)) := by
  conv_lhs => rw [← FreeGroup.lift.apply_symm_apply (fromFreeGroup X)]
  exact FreeGroup.range_lift_eq_closure

/-- The generators generate the free profinite group topologically. -/
theorem dense_closure_range_of (X : Type u) :
    Dense ((Subgroup.closure (Set.range (of : X → freeProfiniteGroup X)) :
      Subgroup (freeProfiniteGroup X)) : Set (freeProfiniteGroup X)) := by
  rw [← range_fromFreeGroup, MonoidHom.coe_range, coe_fromFreeGroup]
  exact ProfiniteGrp.ProfiniteCompletion.denseRange (G := GrpCat.of (FreeGroup X))

section HomExt

variable {Q : Type v} [Group Q] [TopologicalSpace Q] [T2Space Q]

/-- Two continuous homomorphisms out of the free profinite group that agree on the generators
are equal. The target need only be a Hausdorff topological space carrying a group structure; no
`IsTopologicalGroup Q` instance is required. -/
@[ext]
theorem hom_ext {φ ψ : freeProfiniteGroup X →ₜ* Q} (h : ∀ x : X, φ (of x) = ψ (of x)) :
    φ = ψ := by
  refine ProfiniteCompletion.continuousMonoidHom_ext (FreeGroup X) fun w => ?_
  have hcomp : φ.toMonoidHom.comp (fromFreeGroup X) = ψ.toMonoidHom.comp (fromFreeGroup X) :=
    FreeGroup.ext_hom _ _ (by simpa using h)
  simpa [coe_fromFreeGroup] using DFunLike.congr_fun hcomp w

end HomExt

section Lift

variable {P : Type u} [Group P] [TopologicalSpace P] [IsTopologicalGroup P] [CompactSpace P]
  [TotallyDisconnectedSpace P]

/-- The continuous homomorphism to a profinite group `P` extending a map `X → P` on the
generators. -/
noncomputable def lift (f : X → P) : freeProfiniteGroup X →ₜ* P :=
  (ProfiniteCompletion.continuousMonoidHomEquiv (FreeGroup X) P).symm (FreeGroup.lift f)

/-- The lift of `f` agrees with `f` on each canonical generator. -/
@[simp]
theorem lift_of (f : X → P) (x : X) : lift f (of x) = f x := by
  rw [← fromFreeGroup_of, lift, coe_fromFreeGroup,
    ProfiniteCompletion.continuousMonoidHomEquiv_symm_apply_etaFn, FreeGroup.lift_apply_of]

/-- A continuous homomorphism restricting to `f` on the generators is the lift of `f`. -/
theorem lift_unique (f : X → P) (φ : freeProfiniteGroup X →ₜ* P)
    (hφ : ∀ x : X, φ (of x) = f x) : φ = lift f :=
  hom_ext fun x => by rw [hφ, lift_of]

/-- **The universal property of the free profinite group.** A map from `X` to a profinite group
extends uniquely to a continuous homomorphism from `freeProfiniteGroup X`. -/
theorem existsUnique_lift (f : X → P) :
    ∃! φ : freeProfiniteGroup X →ₜ* P, ∀ x : X, φ (of x) = f x :=
  ⟨lift f, lift_of f, fun φ hφ => lift_unique f φ hφ⟩

/-- The lift is natural in the target. -/
@[simp]
theorem comp_lift {Q : Type u} [Group Q] [TopologicalSpace Q] [IsTopologicalGroup Q]
    [CompactSpace Q] [TotallyDisconnectedSpace Q] (g : P →ₜ* Q) (f : X → P) :
    g.comp (lift f) = lift (⇑g ∘ f) :=
  hom_ext fun x => by simp

/-- A map whose range generates the target topologically lifts to a surjection. -/
theorem lift_surjective {f : X → P}
    (hf : Dense ((Subgroup.closure (Set.range f) : Subgroup P) : Set P)) :
    Function.Surjective (lift f) := by
  have hle : Subgroup.closure (Set.range f) ≤ (lift f).toMonoidHom.range :=
    Subgroup.closure_le _ |>.2 (by rintro _ ⟨x, rfl⟩; exact ⟨of x, lift_of f x⟩)
  have hdense : Dense (Set.range (lift f)) := hf.mono hle
  rw [← Set.range_eq_univ, ← (map_continuous (lift f)).isClosedMap.isClosed_range.closure_eq,
    hdense.closure_eq]

end Lift

section Map

/-- The continuous homomorphism induced by a map of generating types. -/
noncomputable def map (u : X → Y) : freeProfiniteGroup X →ₜ* freeProfiniteGroup Y :=
  lift (of ∘ u)

/-- `map u` carries the generator at `x` to the generator at `u x`. -/
@[simp]
theorem map_of (u : X → Y) (x : X) : map u (of x) = of (u x) :=
  lift_of _ x

/-- `map` sends the identity to the identity. -/
@[simp]
theorem map_id : map (id : X → X) = ContinuousMonoidHom.id (freeProfiniteGroup X) :=
  hom_ext fun x => by simp

/-- `map` is functorial in the generating type. -/
@[simp]
theorem map_comp (u : X → Y) (v : Y → Z) : map (v ∘ u) = (map v).comp (map u) :=
  (hom_ext fun x => by simp).symm

/-- A surjection of generating types induces a surjection of free profinite groups. -/
theorem map_surjective {u : X → Y} (hu : Function.Surjective u) :
    Function.Surjective (map u) := by
  refine lift_surjective ?_
  rw [hu.range_comp (of : Y → freeProfiniteGroup Y)]
  exact dense_closure_range_of Y

end Map

/-- The free profinite group on an empty type is trivial. -/
instance [IsEmpty X] : Subsingleton (freeProfiniteGroup X) :=
  (ProfiniteCompletion.etaFn_bijective_of_finite (G := FreeGroup X)).2.subsingleton

section Uniqueness

variable {G : Type u} [Group G] [TopologicalSpace G] [IsTopologicalGroup G] [CompactSpace G]
  [TotallyDisconnectedSpace G]

/-- **The free profinite group is unique up to a unique isomorphism.** A profinite group `G`
with a map `ι : X → G` through which every map from `X` to a profinite group factors uniquely
is topologically isomorphic to `freeProfiniteGroup X` by a unique isomorphism matching the two
families of generators. -/
theorem existsUnique_continuousMulEquiv (ι : X → G)
    (h : ∀ (P : Type u) [Group P] [TopologicalSpace P] [IsTopologicalGroup P] [CompactSpace P]
      [TotallyDisconnectedSpace P] (f : X → P), ∃! φ : G →ₜ* P, ∀ x : X, φ (ι x) = f x) :
    ∃! e : freeProfiniteGroup X ≃ₜ* G, ∀ x : X, e (of x) = ι x := by
  obtain ⟨ψ, hψ, -⟩ := h (freeProfiniteGroup X) of
  have hleft : ψ.comp (lift ι) = ContinuousMonoidHom.id (freeProfiniteGroup X) :=
    hom_ext fun x => by simp [hψ x]
  have hright : (lift ι).comp ψ = ContinuousMonoidHom.id G :=
    (h G ι).unique (fun x => by simp [hψ x]) (fun _ => rfl)
  refine ⟨{ toFun := lift ι, invFun := ψ
            left_inv := fun a => congrArg (fun φ : freeProfiniteGroup X →ₜ* _ => φ a) hleft
            right_inv := fun g => congrArg (fun φ : G →ₜ* G => φ g) hright
            map_mul' := map_mul (lift ι)
            continuous_toFun := map_continuous (lift ι)
            continuous_invFun := map_continuous ψ }, lift_of ι, fun e he => ?_⟩
  have hcoe : (e : freeProfiniteGroup X →ₜ* G) = lift ι := hom_ext fun x => by simp [he x]
  exact ContinuousMulEquiv.ext fun a => congrArg (fun φ : freeProfiniteGroup X →ₜ* G => φ a) hcoe

end Uniqueness

end freeProfiniteGroup

end EpsilonEridani
