/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.LinearAlgebra.FreeModule.PID
public import EpsilonEridani.Algebra.Lie.Weights.Chevalley.System
public import EpsilonEridani.Algebra.Lie.Weights.Root.CorootSpan

/-!
# The integral root--coroot lattice

Let `L` be a finite-dimensional Lie algebra with nondegenerate Killing form, let `H` be a
splitting Cartan subalgebra, and let `x` be a normalized system of root vectors. The integral
root--coroot span from `EpsilonEridani.Algebra.Lie.Weights.Root.CorootSpan` is generated by the vectors
`x α` and the coroots `α∨`.

This file proves the module-theoretic properties that make that span a lattice. Its generating set
is finite, hence the span is finite over `ℤ`; as a submodule of a vector space over a
characteristic-zero field, it is torsion-free and therefore free. It is also full: its scalar span
over the ground field is all of `L`. Fullness follows because the root vectors span `L` together
with `H`, while the coroots span `H`.

For a Chevalley system, the integral structure-constant theorem canonically makes this lattice a
Lie subalgebra. `IsChevalleySystem.chevalleyLieLattice` packages that specialization, so downstream
Kostant constructions do not have to pass the integral-coefficient theorem as a separate argument.
It is a finite free full `ℤ`-form of the characteristic-zero Lie algebra.

These are the lattice properties required by the Chevalley-basis input to the explicit
Chevalley--Demazure construction in Layer 9 of the `ReductiveGroups` roadmap. That construction is
consumed by milestone L0 of the `CFSGStatement` roadmap.

## Main declarations

* `EpsilonEridani.finite_rootCorootGenerators`: the root--coroot generating set is finite.
* `EpsilonEridani.IsSl2System.span_rootCorootSpan_eq_top`: the integral span is full over the ground
  field.
* `EpsilonEridani.IsChevalleySystem.chevalleyLieLattice`: the canonical integral Lie lattice attached to
  a Chevalley system.
* `EpsilonEridani.IsChevalleySystem.span_chevalleyLieLattice_eq_top`: the Chevalley Lie lattice is full.

## References

* J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*, GTM 9, §25.2.
* R. W. Carter, *Simple Groups of Lie Type*, §4.1.
-/

public section

namespace EpsilonEridani

open LieAlgebra LieAlgebra.IsKilling LieModule

universe u v

variable {K : Type u} {L : Type v} [Field K] [CharZero K] [LieRing L] [LieAlgebra K L]
  [LieAlgebra.IsKilling K L] [FiniteDimensional K L]
  {H : LieSubalgebra K L} [H.IsCartanSubalgebra] [LieModule.IsTriangularizable K H L]

omit [CharZero K] [LieModule.IsTriangularizable K H L] in
/-- The root vectors and coroots form a finite set. -/
theorem finite_rootCorootGenerators (x : Weight K H L → L) :
    (rootCorootGenerators x).Finite := by
  apply ((Set.finite_range x).union
    (Set.finite_range fun α : Weight K H L => (coroot α : L))).subset
  intro y hy
  rw [mem_rootCorootGenerators_iff] at hy
  rcases hy with ⟨α, hα⟩ | ⟨α, hα⟩
  · exact Or.inl ⟨α, hα⟩
  · exact Or.inr ⟨α, hα⟩

omit [CharZero K] [LieModule.IsTriangularizable K H L] in
/-- The root--coroot span is the `ℤ`-span of its named generating set. -/
theorem rootCorootSpan_eq_span_generators (x : Weight K H L → L) :
    rootCorootSpan x = Submodule.span ℤ (rootCorootGenerators x) := by
  apply le_antisymm
  · rw [rootCorootSpan_le_iff]
    constructor
    · exact fun α => Submodule.subset_span
        (mem_rootCorootGenerators_iff.2 (Or.inl ⟨α, rfl⟩))
    · exact fun α => Submodule.subset_span
        (mem_rootCorootGenerators_iff.2 (Or.inr ⟨α, rfl⟩))
  · rw [Submodule.span_le]
    intro y hy
    rw [mem_rootCorootGenerators_iff] at hy
    rcases hy with ⟨α, rfl⟩ | ⟨α, rfl⟩
    · exact rootVector_mem_rootCorootSpan x α
    · exact coroot_mem_rootCorootSpan x α

/-- The integral root--coroot span is finitely generated as a `ℤ`-module. -/
noncomputable instance instModuleFiniteRootCorootSpan (x : Weight K H L → L) :
    Module.Finite ℤ (rootCorootSpan x) := by
  rw [rootCorootSpan_eq_span_generators]
  exact Module.Finite.span_of_finite ℤ (finite_rootCorootGenerators x)

namespace IsSl2System

variable {x : Weight K H L → L} (hx : IsSl2System x)

include hx

/-- The scalar span of the integral root--coroot span is the whole Lie algebra. -/
theorem span_rootCorootSpan_eq_top :
    Submodule.span K (rootCorootSpan x : Set L) = ⊤ := by
  rw [rootCorootSpan_eq_span_generators, Submodule.span_span_of_tower ℤ K]
  apply top_unique
  rw [← hx.span_range_sup_toSubmodule_eq_top]
  apply sup_le
  · rw [Submodule.span_le]
    rintro _ ⟨α, rfl⟩
    exact Submodule.subset_span
      (mem_rootCorootGenerators_iff.2 (Or.inl ⟨α, rfl⟩))
  · intro h hh
    have hspan :
        (⟨h, hh⟩ : H) ∈ Submodule.span K (Set.range (rootSystem H).coroot) := by
      rw [RootPairing.IsRootSystem.span_coroot_eq_top]
      trivial
    have hcoe : ∀ y : H, y ∈ Submodule.span K (Set.range (rootSystem H).coroot) →
        (y : L) ∈ Submodule.span K (rootCorootGenerators x) := by
      intro y hy
      induction hy using Submodule.span_induction with
      | mem y hy =>
          obtain ⟨α, rfl⟩ := hy
          rw [rootSystem_coroot_apply]
          exact Submodule.subset_span
            (mem_rootCorootGenerators_iff.2 (Or.inr ⟨α.1, rfl⟩))
      | zero => exact Submodule.zero_mem _
      | add y z _ _ hy hz =>
          -- The induction runs in the Cartan subtype; the target is its image in `L`.
          change (y : L) + (z : L) ∈ _
          exact Submodule.add_mem _ hy hz
      | smul c y _ hy =>
          -- The induction runs in the Cartan subtype; the target is its image in `L`.
          change c • (y : L) ∈ _
          exact Submodule.smul_mem _ c hy
    exact hcoe ⟨h, hh⟩ hspan

/-- Every integral root--coroot Lie subalgebra has full scalar span. The integral-coefficient
hypothesis affects its Lie bracket structure, not its underlying lattice. -/
theorem span_rootCorootLieSubalgebra_eq_top
    (hIntegral : ∀ (α β γ : Weight K H L), α.IsNonZero → β.IsNonZero → γ.IsNonZero →
      (γ : H → K) = (α : H → K) + (β : H → K) →
        ∃ z : ℤ, ⁅x α, x β⁆ = (z : K) • x γ) :
    Submodule.span K (hx.rootCorootLieSubalgebra hIntegral : Set L) = ⊤ := by
  have hset : (hx.rootCorootLieSubalgebra hIntegral : Set L) =
      (rootCorootSpan x : Set L) := by
    ext y
    exact hx.mem_rootCorootLieSubalgebra_iff hIntegral
  rw [hset]
  exact hx.span_rootCorootSpan_eq_top

end IsSl2System

/-- The finite root--coroot span is a free `ℤ`-module. -/
noncomputable instance instModuleFreeRootCorootSpan (x : Weight K H L → L) :
    Module.Free ℤ (rootCorootSpan x) := by
  let _ : IsAddTorsionFree L := by
    constructor
    intro n hn a b hab
    apply smul_right_injective L (Nat.cast_ne_zero.mpr hn : (n : K) ≠ 0)
    simpa only [Nat.cast_smul_eq_nsmul] using hab
  exact Module.free_of_finite_type_torsion_free'

namespace IsChevalleySystem

variable {ω : L ≃ₗ⁅K⁆ L} {x : Weight K H L → L} (hx : IsChevalleySystem ω x)

include hx

/-- The integral root--coroot Lie lattice canonically attached to a Chevalley system. -/
noncomputable def chevalleyLieLattice : LieSubalgebra ℤ L :=
  hx.toIsSl2System.rootCorootLieSubalgebra fun α β γ _ _ hγ hαβ =>
    hx.exists_int_lie_eq_smul α β γ hγ hαβ

/-- The underlying integer submodule of the Chevalley Lie lattice is the root--coroot span. -/
@[simp]
theorem chevalleyLieLattice_toSubmodule :
    hx.chevalleyLieLattice.toSubmodule = rootCorootSpan x :=
  hx.toIsSl2System.rootCorootLieSubalgebra_toSubmodule _

/-- Membership in the Chevalley Lie lattice is membership in the root--coroot span. -/
@[simp]
theorem mem_chevalleyLieLattice_iff {y : L} :
    y ∈ hx.chevalleyLieLattice ↔ y ∈ rootCorootSpan x :=
  hx.toIsSl2System.mem_rootCorootLieSubalgebra_iff _

/-- The Chevalley Lie lattice is the least integral Lie subalgebra containing all root vectors and
coroots. -/
@[simp]
theorem chevalleyLieLattice_le_iff {M : LieSubalgebra ℤ L} :
    hx.chevalleyLieLattice ≤ M ↔
      (∀ α, x α ∈ M) ∧ ∀ α,
        (IsKilling.coroot (K := K) (L := L) (H := H) α : L) ∈ M :=
  hx.toIsSl2System.rootCorootLieSubalgebra_le_iff _

-- These generator membership facts are intentionally not simp lemmas: their left-hand sides
-- already simplify through `mem_chevalleyLieLattice_iff`, so `simpNF` rejects the attributes.
/-- Every root vector belongs to the Chevalley Lie lattice. -/
theorem rootVector_mem_chevalleyLieLattice (α : Weight K H L) :
    x α ∈ hx.chevalleyLieLattice :=
  hx.mem_chevalleyLieLattice_iff.2 (rootVector_mem_rootCorootSpan x α)

/-- Every coroot belongs to the Chevalley Lie lattice. -/
theorem coroot_mem_chevalleyLieLattice (α : Weight K H L) :
    (coroot α : L) ∈ hx.chevalleyLieLattice :=
  hx.mem_chevalleyLieLattice_iff.2 (coroot_mem_rootCorootSpan x α)

/-- A Chevalley Lie lattice is finitely generated as a `ℤ`-module. -/
noncomputable instance instModuleFiniteChevalleyLieLattice :
    Module.Finite ℤ hx.chevalleyLieLattice := by
  let e : rootCorootSpan x ≃ₗ[ℤ] hx.chevalleyLieLattice.toSubmodule :=
    LinearEquiv.ofEq _ _ hx.chevalleyLieLattice_toSubmodule.symm
  exact Module.Finite.equiv e

/-- The scalar span of a Chevalley Lie lattice is the whole Lie algebra. -/
theorem span_chevalleyLieLattice_eq_top :
    Submodule.span K (hx.chevalleyLieLattice : Set L) = ⊤ :=
  hx.toIsSl2System.span_rootCorootLieSubalgebra_eq_top _

/-- A Chevalley Lie lattice is a finite free `ℤ`-module. -/
noncomputable instance instModuleFreeChevalleyLieLattice :
    Module.Free ℤ hx.chevalleyLieLattice := by
  let e : rootCorootSpan x ≃ₗ[ℤ] hx.chevalleyLieLattice.toSubmodule :=
    LinearEquiv.ofEq _ _ hx.chevalleyLieLattice_toSubmodule.symm
  exact Module.Free.of_equiv e

end IsChevalleySystem

end EpsilonEridani
